import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {setup,terminal,upload,workspace,edit,doc,copy,preview,binary} from '../portable/helpers.mjs';
import {importRaster} from '../raster/helpers.mjs';
import {emptyComposition,emptyElement,linkField,serialize,detach} from '../../dist/local/src/composition/core.js';
import {canonical} from '../../dist/local/src/protocol/json.js';
const state=async(f,id='document_1')=>(await f.read('/api/v1/documents/'+id+'/image')).json;
async function ref(f,bytes,mediaType='application/json'){const stage=await upload(f,Buffer.from(bytes),'text','application/octet-stream'),a=(await workspace(f,{type:'FinalizeStaging',stagingId:stage.stagingId,expectedSha256:stage.sha256})).event.payload.asset;return {...a.blob,mediaType};}
async function commit(f,c,bindings={},id='document_1',type='CommitCompositionVersion',draft=null){const value=await ref(f,canonical(c));return edit(f,{type,composition:{id:c.id,value,bindings},draft},id);}
const view=async(f,id='document_1')=>(await f.read('/api/v1/documents/'+id+'/composition?revision='+(await doc(f,id)).revision)).json;
test('semantic history is independent; raw, projection and exact bytes survive two copies and undo',async t=>{
 const f=await setup(t);await terminal(f,f.command({},{width:3,height:2}));const original=Buffer.from('{"unknown":true,"unknown":false}\n'),raw=await ref(f,original,'application/octet-stream');let c=emptyComposition(3,2,randomUUID());const a=emptyElement('text',randomUUID()),b=emptyElement('obj',randomUUID());a.text.value='Café\n東京';c.scene='Scene';c.elements=[a,b];c.raw=[raw];await commit(f,c);
 let d=await doc(f);assert.deepEqual(d.orderedLayerIds,[]);assert.equal(d.compositionVersion,c.id);assert.deepEqual((await state(f)).layers,[]);
 c=structuredClone(c);c.id=randomUUID();c.elements.reverse();await commit(f,c,{},'document_1','ReorderSemanticElement');const reordered=await doc(f);await edit(f,{type:'Undo',historyHead:reordered.historyHead});assert.equal((await view(f)).composition.elements[0].id,a.id);await edit(f,{type:'Redo',historyNode:reordered.historyHead});
 c.id=randomUUID();const p=serialize(c,[],{}),prompt=await ref(f,p.prompt,'text/plain');c.review={serializer:'caption-json-1',sourceId:c.id,frame:c.frame,request:c.request,dependencies:p.dependencies,boxes:p.boxes,prompt};await commit(f,c,{},'document_1','ApprovePromptProjection');
 let id='document_1';for(let i=0;i<2;i++){const archive=await copy(f,id),r=(await preview(f,archive.bytes)).review;assert.equal(r.editable,true,JSON.stringify(r));assert.equal(r.formatVersion,7);await workspace(f,{type:'ImportBundle',reviewId:r.reviewId,reviewHash:r.reviewHash});id=r.documentId;const v=await view(f,id);assert.deepEqual(v.composition,c);const bytes=await binary(f,'/api/v1/documents/'+id+'/composition?revision='+(await doc(f,id)).revision+'&raw=0&download=1');assert.deepEqual(bytes.bytes,original);assert.equal((await state(f,id)).layers.length,0);}
});
test('binding source authority, stale review, deletion, detach and remapped copy closure',async t=>{
 const f=await setup(t);await terminal(f,f.command({},{width:3,height:2}));const {asset}=await importRaster(f,'hidden-alpha.png');await edit(f,{type:'ImportAsset',assetId:asset.id,layerId:'picture',name:'Native',draft:null});await edit(f,{type:'SetLayerAppearance',layerId:'picture',layerVersion:'1',description:'Explicit appearance',draft:null});
 let v=await view(f),c=emptyComposition(3,2,randomUUID()),e=emptyElement('obj',randomUUID());e.desc=linkField('appearance-description',v.layers[0]);e.bounds=linkField('frame-bounds',v.layers[0]);c.elements=[e];await commit(f,c,{picture:'picture'});const before=await state(f);await edit(f,{type:'DuplicateLayer',layerId:'picture',layerVersion:'2',newLayerId:'other',name:'Copy',draft:null});assert.equal((await view(f)).composition.elements.length,1);assert.deepEqual((await view(f)).bindings,{picture:'picture'});
 await edit(f,{type:'ApplyTransform',layerId:'picture',layerVersion:'2',transform:[1,0,0,1,1,0],draft:null});v=await view(f);assert.throws(()=>serialize(v.composition,v.layers,v.bindings),/STALE_LINK/);
 const forged=structuredClone(c);forged.id=randomUUID();forged.elements[0].desc.lastReviewedLayerVersion='3';forged.elements[0].desc.lastReviewedValue='Invented';const value=await ref(f,canonical(forged)),rejected=await terminal(f,f.command({expectedDocumentRevision:(await doc(f)).revision,body:{type:'CommitCompositionVersion',composition:{id:forged.id,value,bindings:{picture:'picture'}},draft:null}}));assert.equal(rejected.json.receipt.status,'rejected');
 const bundle=await copy(f),r=(await preview(f,bundle.bytes)).review;assert.equal(r.editable,true,JSON.stringify(r));await workspace(f,{type:'ImportBundle',reviewId:r.reviewId,reviewHash:r.reviewHash});const imported=await view(f,r.documentId);assert.notEqual(imported.bindings.picture,'picture');assert(imported.layers.some(l=>l.id===imported.bindings.picture));
 await edit(f,{type:'DeleteLayer',layerId:'picture',layerVersion:'3',draft:null});v=await view(f);assert.throws(()=>serialize(v.composition,v.layers,v.bindings),/MISSING_LINK/);c=structuredClone(v.composition);c.id=randomUUID();c.elements[0].desc=detach(c.elements[0].desc);c.elements[0].bounds=detach(c.elements[0].bounds);await commit(f,c,{},'document_1','DetachSemanticBinding');assert.equal((await view(f)).composition.elements[0].desc.value,'Explicit appearance');assert.equal(before.layers[0].layerToDocument[4],0);
});
test('unapplied invalid draft and original raw closure retain exact graph bytes and nested binding maps',async t=>{
 const f=await setup(t);await terminal(f,f.command({},{width:3,height:2}));const {asset}=await importRaster(f,'hidden-alpha.png');await edit(f,{type:'ImportAsset',assetId:asset.id,layerId:'source',name:'Native',draft:null});const v=await view(f),c=emptyComposition(3,2,randomUUID()),e=emptyElement('obj','unfinished');e.desc=linkField('appearance-description',v.layers[0]);c.elements=[e];const raw=await ref(f,Buffer.from([0xff,0,10]),'application/octet-stream');c.raw=[raw];const graphBytes=canonical({composition:c,bindings:{source:'source'},numbers:{width:'not a number'},selected:e.id}),graph=await ref(f,graphBytes),envelope={schemaVersion:1,kind:'composition-draft-1',graph,raw:[raw],bindings:{source:'source'}},stage=await upload(f,Buffer.from(canonical(envelope)),'caption','text/plain'),caption=(await workspace(f,{type:'FinalizeStaging',stagingId:stage.stagingId,expectedSha256:stage.sha256})).event.payload.asset;
 const d=await doc(f),saved=await f.post('/api/v1/ui/semantic',{protocolVersion:1,requestId:randomUUID(),sessionId:'semantic',expectedUISeq:'0',body:{type:'SaveDraft',draft:{id:'unfinished-draft',generation:'1',kind:'composition',documentId:d.id,targetLayerId:null,expectedDocumentRevision:d.revision,assetId:caption.id,composing:false}}});assert.equal(saved.json.status,'accepted',saved.text);
 let id=d.id;for(let i=0;i<2;i++){const b=await copy(f,id),r=(await preview(f,b.bytes)).review;assert.equal(r.editable,true,JSON.stringify(r));await workspace(f,{type:'ImportBundle',reviewId:r.reviewId,reviewHash:r.reviewHash});id=r.documentId;const ui=(await f.read('/api/v1/ui/'+r.uiSessionIds[0])).json,draft=ui.drafts[0];assert.notEqual(draft.compositionBindings.source,'source');const data=(await f.read('/api/v1/ui/'+r.uiSessionIds[0]+'/composition?draftId='+draft.id+'&generation='+draft.generation)).json;assert.equal(canonical(data.graph),graphBytes);assert.equal(data.graph.numbers.width,'not a number');}
});

test('opaque original beyond the inspection bound streams completely with bounded pages and no execution',async t=>{
 const f=await setup(t);await terminal(f,f.command({},{width:1,height:1}));const rawBytes=Buffer.alloc(17*1024*1024,65);rawBytes[32767]=0xff;rawBytes[rawBytes.length-1]=0;const raw=await ref(f,rawBytes,'application/octet-stream'),c=emptyComposition(1,1,randomUUID());c.raw=[raw];await commit(f,c);const path='/api/v1/documents/document_1/composition?revision='+(await doc(f)).revision+'&raw=0';const page=await binary(f,path+'&offset=32768');assert.equal(page.bytes.length,32768);assert.deepEqual(page.bytes,rawBytes.subarray(32768,65536));assert.deepEqual((await binary(f,path+'&download=1')).bytes,rawBytes);const bundle=await copy(f),r=(await preview(f,bundle.bytes)).review;assert.equal(r.editable,true);await workspace(f,{type:'ImportBundle',reviewId:r.reviewId,reviewHash:r.reviewHash});assert.deepEqual((await binary(f,'/api/v1/documents/'+r.documentId+'/composition?revision='+(await doc(f,r.documentId)).revision+'&raw=0&download=1')).bytes,rawBytes);t.diagnostic(JSON.stringify({raw,parsed:false,pageBytes:page.bytes.length,retainedBeyondInspectionBound:true}));
});

test('semantic versions cannot be recycled through undo or copies; specialized commands cannot edit unrelated fields',async t=>{
 const f=await setup(t);await terminal(f,f.command({},{width:3,height:2}));const {asset}=await importRaster(f,'hidden-alpha.png');await edit(f,{type:'ImportAsset',assetId:asset.id,layerId:'source',name:'Native',draft:null});let c=emptyComposition(3,2,randomUUID());c.elements=[emptyElement('obj','semantic')];await commit(f,c);const first=c.id;
 const reject=async(next,type='CommitCompositionVersion',bindings={},documentId='document_1')=>{const value=await ref(f,canonical(next)),r=await terminal(f,f.command({documentId,expectedDocumentRevision:(await doc(f,documentId)).revision,body:{type,composition:{id:next.id,value,bindings},draft:null}}));assert.equal(r.json.receipt.status,'rejected',JSON.stringify(r.json));};
 c=structuredClone(c);c.id=randomUUID();c.elements[0].desc=linkField('appearance-description',(await view(f)).layers[0]);await commit(f,c,{source:'source'},'document_1','SetSemanticBinding');
 const wrong=structuredClone(c);wrong.id=randomUUID();wrong.elements[0].desc={mode:'literal',value:'Invented detach'};await reject(wrong,'DetachSemanticBinding');
 const unrelated=structuredClone(c);unrelated.id=randomUUID();unrelated.scene='Unrelated edit';unrelated.elements[0].desc=detach(unrelated.elements[0].desc);await reject(unrelated,'DetachSemanticBinding');
 const detached=structuredClone(c);detached.id=randomUUID();detached.elements[0].desc=detach(detached.elements[0].desc);await commit(f,detached,{},'document_1','DetachSemanticBinding');
 const reused=structuredClone(detached);reused.id=first;await reject(reused);const d=await doc(f);await edit(f,{type:'Undo',historyHead:d.historyHead});await reject(detached);
 const bundle=await copy(f),r=(await preview(f,bundle.bytes)).review;assert.equal(r.editable,true);await workspace(f,{type:'ImportBundle',reviewId:r.reviewId,reviewHash:r.reviewHash});await reject(reused,'CommitCompositionVersion',{},r.documentId);
 const add=structuredClone((await view(f)).composition);add.id=randomUUID();add.elements[0].desc={mode:'literal',value:'Unrelated change'};add.elements.push(emptyElement('obj','new'));await reject(add,'AddSemanticElement');
});
