import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {closeSync,constants,fstatSync,fsyncSync,lstatSync,mkdirSync,openSync,readSync,readdirSync,writeSync} from 'node:fs';
import {dirname,join,resolve} from 'node:path';

export const MAX_JSON_BYTES=8*1048576,MAX_FILE_BYTES=2**31,MAX_CAPSULE_BYTES=8*2**30,MAX_FILES=8192;
export const hash=bytes=>'sha256:'+createHash('sha256').update(bytes).digest('hex');
export function digest(value){assert.equal(typeof value,'string');assert.match(value,/^sha256:[a-f0-9]{64}$/);return value;}
export function relativePath(value){assert.equal(typeof value,'string');assert(value.length>0&&value.length<=1024);assert.match(value,/^[A-Za-z0-9_.-]+(?:\/[A-Za-z0-9_.-]+)*$/);assert(value.split('/').every(part=>part!=='.'&&part!=='..'));return value;}
export function inside(directory,path){relativePath(path);const base=resolve(directory),target=join(base,path);assert(target.startsWith(base+'/'));return target;}
const same=(a,b)=>a.dev===b.dev&&a.ino===b.ino&&a.mode===b.mode&&a.nlink===b.nlink&&a.size===b.size&&a.mtimeNs===b.mtimeNs&&a.ctimeNs===b.ctimeNs;
export function checkParents(path){for(let at=dirname(resolve(path));;at=dirname(at)){const s=lstatSync(at);assert(s.isDirectory()&&!s.isSymbolicLink(),'Capsule parent must be a real directory');if(dirname(at)===at)break;}}
function openHeld(path,maximum){checkParents(path);const before=lstatSync(path,{bigint:true});assert(before.isFile()&&!before.isSymbolicLink()&&before.nlink===1n,'Capsule requires singly linked regular files');assert(before.size>=0n&&before.size<=BigInt(maximum),'Capsule file exceeds its bound');const fd=openSync(path,constants.O_RDONLY|constants.O_NOFOLLOW);try{assert(same(before,fstatSync(fd,{bigint:true})),'Capsule file changed before open');return {fd,before};}catch(error){closeSync(fd);throw error;}}
export function identity(path,maximum=MAX_FILE_BYTES){const {fd,before}=openHeld(path,maximum),buffer=Buffer.alloc(65536),h=createHash('sha256');let bytes=0;try{for(;;){const n=readSync(fd,buffer,0,buffer.length,bytes);if(!n)break;bytes+=n;assert(bytes<=maximum);h.update(buffer.subarray(0,n));}assert.equal(BigInt(bytes),before.size);assert(same(before,fstatSync(fd,{bigint:true}))&&same(before,lstatSync(path,{bigint:true})),'Capsule file changed during read');return {bytes,hash:'sha256:'+h.digest('hex')};}finally{closeSync(fd);}}
export function readJSON(path){const {fd,before}=openHeld(path,MAX_JSON_BYTES);try{const bytes=Buffer.alloc(Number(before.size));let at=0;while(at<bytes.length){const n=readSync(fd,bytes,at,bytes.length-at,at);assert(n>0,'Capsule JSON shortened');at+=n;}assert(same(before,fstatSync(fd,{bigint:true}))&&same(before,lstatSync(path,{bigint:true})),'Capsule JSON changed during read');return {value:JSON.parse(bytes.toString('utf8')),bytes,hash:hash(bytes)};}finally{closeSync(fd);}}
export function copyHeld(source,destination,expected){assert(Number.isSafeInteger(expected.bytes)&&expected.bytes>=0&&expected.bytes<=MAX_FILE_BYTES);digest(expected.hash);const {fd,before}=openHeld(source,expected.bytes),buffer=Buffer.alloc(65536),h=createHash('sha256');let output,bytes=0;try{assert.equal(before.size,BigInt(expected.bytes));mkdirSync(dirname(destination),{recursive:true,mode:0o700});checkParents(destination);output=openSync(destination,constants.O_WRONLY|constants.O_CREAT|constants.O_EXCL|constants.O_NOFOLLOW,0o600);for(;;){const n=readSync(fd,buffer,0,buffer.length,bytes);if(!n)break;bytes+=n;assert(bytes<=expected.bytes);h.update(buffer.subarray(0,n));for(let at=0;at<n;){const count=writeSync(output,buffer,at,n-at);assert(count>0);at+=count;}}assert.equal(bytes,expected.bytes);assert.equal('sha256:'+h.digest('hex'),expected.hash,'Captured bytes differ from the reviewed identity');assert(same(before,fstatSync(fd,{bigint:true}))&&same(before,lstatSync(source,{bigint:true})),'Source changed during capture');fsyncSync(output);}finally{if(output!==undefined)closeSync(output);closeSync(fd);}assert.deepEqual(identity(destination),{bytes:expected.bytes,hash:expected.hash},'Captured destination changed');}
export function writeJSON(path,value){const bytes=Buffer.from(JSON.stringify(value,null,2)+'\n');assert(bytes.length<=MAX_JSON_BYTES);mkdirSync(dirname(path),{recursive:true,mode:0o700});checkParents(path);const fd=openSync(path,constants.O_WRONLY|constants.O_CREAT|constants.O_EXCL|constants.O_NOFOLLOW,0o600);try{let at=0;while(at<bytes.length){const n=writeSync(fd,bytes,at,bytes.length-at);assert(n>0);at+=n;}fsyncSync(fd);}finally{closeSync(fd);}return {bytes:bytes.length,hash:hash(bytes)};}
export function listFiles(directory){const result=[];function walk(path,prefix){const s=lstatSync(path);assert(s.isDirectory()&&!s.isSymbolicLink(),'Capsule directory must not be a link');for(const name of readdirSync(path).sort()){relativePath(name);const next=join(path,name),relative=prefix+name,entry=lstatSync(next);if(entry.isDirectory())walk(next,relative+'/');else{assert(entry.isFile()&&!entry.isSymbolicLink()&&entry.nlink===1,'Nonregular capsule entry');result.push(relative);assert(result.length<=MAX_FILES);}}}walk(resolve(directory),'');return result;}
