import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {verifyLinuxCodecsSeal} from '../linux-codecs/verify.mjs';
const root=resolve(import.meta.dirname,'../../..');
const hash=value=>'sha256:'+createHash('sha256').update(value).digest('hex');
export function linuxColorIdentitySource(identity){return '// Generated by tooling/raster/linux-color/build.mjs. Do not edit.\nexport const LINUX_COLOR_'+identity.arch.toUpperCase()+' = '+JSON.stringify(identity,null,2)+' as const;\n';}
export function verifyLinuxColorSeal({arch=process.arch,installed=process.platform==='linux'&&process.arch===arch}={}){
  assert(['arm64','x64'].includes(arch));
  const directory=join(root,'vendor/raster/linux-color/1.0.0',`linux-${arch}`);
  const raw=readFileSync(join(directory,'manifest.json')),manifest=JSON.parse(raw),identity=JSON.parse(readFileSync(join(directory,'identity.json')));
  assert.equal(identity.platform,'linux');assert.equal(identity.arch,arch);assert.equal(identity.abiVersion,1);assert.equal(identity.manifestHash,hash(raw));
  for(const item of [...manifest.producerInputs,...manifest.sourceInputs]){const bytes=readFileSync(join(root,item.path));assert.equal(bytes.length,item.bytes,item.path);assert.equal(hash(bytes),item.hash,item.path);}
  assert.equal(identity.producerHash,hash(JSON.stringify(manifest.producerInputs)));
  const bytes=readFileSync(join(root,identity.path));assert.equal(bytes.length,identity.bytes);assert.equal(hash(bytes),identity.hash);
  assert.deepEqual(manifest.artifact,{path:'libideogram-linux-color.so.1',bytes:identity.bytes,hash:identity.hash});
  const codec=JSON.parse(readFileSync(join(root,`tooling/raster/linux-codecs/1.0.0/linux-${arch}/codecs.json`)));
  assert.equal(identity.codecIdentity,hash(JSON.stringify(codec)));assert.equal(manifest.codecIdentity,identity.codecIdentity);
  assert.equal(readFileSync(join(root,`server/raster/linux-color-${arch}-identity.ts`),'utf8'),linuxColorIdentitySource(identity));
  const codecSeal=verifyLinuxCodecsSeal({arch,installed});assert.equal(codecSeal.codecIdentity,identity.codecIdentity);
  return {status:'passed',arch,identity,installed};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){const args=process.argv.slice(2);assert(args.length===0||args.length===2&&args[0]==='--arch');console.log(JSON.stringify(verifyLinuxColorSeal(args.length?{arch:args[1]}:{})));}
