// Actual RequestEditing and RequestNavigationMemory; a controlled child seam
// independently refuses prospective index admission. Run only after assembly.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {allocationsURL as allocationURL,promptMemoryURL as promptURL,compositionObservationsURL} from '../owned-preview-module.mjs';
import {resolve,posix} from 'node:path';
import {pathToFileURL} from 'node:url';
import {transformWithOxc} from 'vite';
const roots=[...new Set([process.env.REQUEST_PROMPT_ROOT,process.env.IE_DRAFT_METADATA_SOURCE_ROOT,process.env.CLIENT_CONTROL_ROOT,process.env.CANDIDATE_COMPARISON_ROOT,process.env.UI_MODEL_ROOT,'.'].filter(Boolean))],data=code=>'data:text/javascript;base64,'+Buffer.from(code).toString('base64');
async function sourceText(path){for(const root of roots){try{return await readFile(resolve(root,path),'utf8');}catch(error){if(error.code!=='ENOENT')throw error;}}throw Error('Missing candidate controller source: '+path);}
async function source(path,imports={}){const original=await sourceText(path);let code=(await transformWithOxc(original,path)).code;for(const [name,url]of Object.entries(imports))code=code.replaceAll(JSON.stringify(name),JSON.stringify(url)).replaceAll("'"+name+"'",JSON.stringify(url));return data(code+'\n//# sourceURL=ideogram-candidate-controller/'+path+'?sha256='+createHash('sha256').update(original).digest('hex')+'\n');}
const modelURL=await source('src/observability/model-memory.ts',{'./allocations.js':allocationURL,'./prompt-memory.js':promptURL});
// Real draft registration and persistence share the controller's exact ledger.
// State dependencies are source-loaded recursively; public protocol validators
// use the coordinated build, as the other controller dependencies do.
const stateURLs=new Map([['src/observability/allocations.ts',Promise.resolve(allocationURL)],['src/observability/prompt-memory.ts',Promise.resolve(promptURL)],['src/observability/model-memory.ts',Promise.resolve(modelURL)]]);
function stateModule(path){
 if(stateURLs.has(path))return stateURLs.get(path);
 if(!path.startsWith('src/state/')&&!path.startsWith('src/observability/')&&!['src/protocol/json.ts','src/protocol/sha256.ts'].includes(path))return Promise.resolve(pathToFileURL(resolve('dist/local',path.replace(/\.ts$/,'.js'))).href);
 const pending=(async()=>{
  let code=(await transformWithOxc(await sourceText(path),path)).code;
  const specifiers=[...new Set([...code.matchAll(/(?:\bfrom\s*|\bimport\s*)(["'])([^"']+)\1/g)].map(match=>match[2]))];
  for(const specifier of specifiers){if(!specifier.startsWith('.'))throw Error('Unsupported draft fixture dependency: '+specifier+' in '+path);const dependency=posix.normalize(posix.join(posix.dirname(path),specifier)).replace(/\.js$/,'.ts'),url=await stateModule(dependency);code=code.replaceAll(JSON.stringify(specifier),JSON.stringify(url)).replaceAll("'"+specifier+"'",JSON.stringify(url));}
  return data(code);
 })();stateURLs.set(path,pending);return pending;
}
const persistenceURL=await stateModule('src/state/draft-persistence.ts');
const compositionViewURL=await source('src/composition/view.ts');
const compositionURL=await source('src/composition/core.ts'),compositionMemoryURL=await source('src/composition/memory.ts',{'./view.js':compositionViewURL,'./core.js':compositionURL,'../observability/allocations.js':allocationURL,'../observability/prompt-memory.js':promptURL,'../observability/composition-observations.js':compositionObservationsURL});
const entryURL=await source('src/ui/request-entry-memory.ts',{'../observability/model-memory.js':modelURL,'../observability/prompt-memory.js':promptURL});
const promptInputURL=await source('src/ui/request-prompt-memory.ts',{'../observability/prompt-memory.js':promptURL,'../observability/allocations.js':allocationURL});
const ownerURL=await source('src/ui/model-owner.ts',{'../observability/model-memory.js':modelURL,'../observability/prompt-memory.js':promptURL});
const navigationURL=await source('src/ui/request-navigation-memory.ts',{'../observability/model-memory.js':modelURL,'./model-owner.js':ownerURL});
const lit=data('export const nothing=null;export const noChange=Symbol.for("lit-noChange");export const html=(strings,...values)=>({strings,values});');
const children=data(`export class AdapterLibraryEditing{dispose(){}render(){return null;}async eligibility(){return {adapters:new Map()};}}export class RequestEdits{constructor(host,editor,hooks){this.hooks=hooks;this.index=[];this.refuse=false;}dispose(){}async sync(){}renderSourceMask(){return null;}renderCandidate(){return null;}renderCandidateNavigator(){return null;}prepareCandidates(rows){if(this.refuse)throw Error('FIXTURE_CHILD_ADMISSION_REFUSAL');const next=Array.from(rows);return {commit:()=>{this.index=next;},release(){}};}retainCandidates(rows){this.prepareCandidates(rows).commit();}}export class V45EditInputsEditing{constructor(host,editor,hooks){this.hooks=hooks;}dispose(){}render(){return null;}}export class TextTreatmentEditing{dispose(){}async drain(){}intent(){return undefined;}render(){return null;}}export class ReturnedDescriptionEditing{async releaseDocument(){}render(){return null;}}export const renderV45EditSettings=()=>null,renderV45EditReview=()=>null;`);
const display=data('export const displayImage=value=>value;export function revokeDisplayPreviewURL(){}export function displayPreviewInfo(){return null;}export async function readDisplaySource(){throw Error("unused display read");}export const withDisplaySource=readDisplaySource;export async function createDisplayPreviewURL(){throw Error("unused display preview");}export async function validateDisplayImage(){throw Error("unused display validation");}');
const v45=data('export const renderV45Generation=()=>null,renderV45GenerationReview=()=>null,renderV45UnavailableResultMetadata=()=>null,renderRequestEstimate=()=>null;');
const compiled=name=>pathToFileURL(resolve('dist/local/src/'+name+'.js')).href;
const compositionTextURL=await source('src/ui/request-composition-text.ts',{'lit':lit,'../composition/text-export.js':compiled('composition/text-export'),'../protocol/json.js':compiled('protocol/json'),'../observability/model-memory.js':modelURL,'../observability/prompt-memory.js':promptURL});
const keyboardScopeURL=await source('src/ui/keyboard-scope.ts');
const controllerURL=await source('src/ui/request.ts',{'../observability/composition-observations.js':compositionObservationsURL,'lit':lit,'lit/directives/repeat.js':data('export const repeat=(items,key,render)=>Array.from(items,render);'),'./adapters.js':await source('src/ui/adapters.ts'),'./display-image.js':display,'../observability/display-preview.js':display,'../observability/prompt-memory.js':promptURL,'../observability/model-memory.js':modelURL,'./request-entry-memory.js':entryURL,'./request-prompt-memory.js':promptInputURL,'./request-navigation-memory.js':navigationURL,'./request-composition-text.js':compositionTextURL,'./keyboard-scope.js':keyboardScopeURL,'./adapter-library.js':children,'./request-edits.js':children,'./request-v45-edit.js':children,'./request-v45.js':v45,'./text-treatment.js':children,'./returned-description.js':children,'../protocol/asset-projection.js':compiled('protocol/asset-projection'),'../composition/core.js':compositionURL,'../composition/memory.js':compositionMemoryURL,'../protocol/json.js':compiled('protocol/json'),'../request/core.js':compiled('request/core'),'../request/family.js':compiled('request/family')});
const {navigationHistory}=await import(navigationURL);
const {RequestEditing}=await import(controllerURL),{allocationLedger,ALLOCATION_LIMITS}=await import(allocationURL),{readOwnedJSON,modelPayloadBytes}=await import(modelURL),{DraftPersistence}=await import(persistenceURL),{PromptReaderCleanupError}=await import(promptURL),{ownRequestEntry}=await import(entryURL),{newDraft,hash}=await import(compiled('request/core')),{newV45EditDraft}=await import(compiled('request/family')),{emptyComposition,serialize}=await import(compositionURL);
const flush=async()=>{for(let n=0;n<100;n++)await Promise.resolve();},turn=()=>new Promise(resolve=>setTimeout(resolve,5));
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const ref=text=>({hash:hash(text),byteLength:String(new TextEncoder().encode(text).byteLength),mediaType:'text/plain'});
const response=value=>{const text=JSON.stringify(value);return new Response(text,{headers:{'content-length':String(new TextEncoder().encode(text).byteLength)}});};
const event=(id,value='')=>{const currentTarget={id,value,isConnected:true};return {currentTarget,composedPath:()=>[currentTarget],defaultPrevented:false,preventDefault(){this.defaultPrevented=true;}};};
function field(template,id){if(!template||typeof template!=='object')return null;if(template.strings){const at=template.strings.findIndex(s=>s.includes('id="'+id+'"'));if(at>=0){const end=template.strings.findIndex((s,i)=>i>at&&s.includes('</en-'));return template.values.slice(at,end<0?undefined:end).find(value=>typeof value==='function');}}for(const value of Array.isArray(template)?template:template.values??[]){const found=field(value,id);if(found)return found;}return null;}
function fixture(){let uiPins=0,instance,route=async()=>{throw Error('Unexpected transport');},rendered;const owners=[],saved=[],reads=[];const editor={sessionId:'session',view:{ready:true,document:{id:'old',revision:'1',width:512,height:512},image:{layers:[]},selected:[]},session:{identity:()=> 'client',transport(path,init){reads.push(path);return path.endsWith('/request-reviews')?Promise.resolve(response({items:[]})):route(path,init);}},ui:{drafts:[]},pinUI(){uiPins++;let held=true;return ()=>{assert(held,'UI checkpoint pin released twice');held=false;uiPins--;};},async json(){return {items:[]};},ownedJSON(path,owner,init,owns,maxBytes,kind){return readOwnedJSON(this.session.transport.bind(this.session),path,{owner,init,owns,maxBytes,kind});},changeDraft(id,kind,text,targetLayerId,composing,expectedDocumentRevision){this.draftOwner.change({id,kind,text,targetLayerId,composing,expectedDocumentRevision,documentId:this.view.document.id});saved.push({id,text});},async flushDrafts(){for(const draft of this.draftOwner.drafts.values())draft.savedGeneration=draft.generation;}};
 const owner=()=>{const value=new DraftPersistence('session',editor.session.transport.bind(editor.session),()=> 'csrf');value.checkpoint={drafts:[],uiSeq:'1'};owners.push(value);return value;};editor.draftOwner=owner();
 editor.registerDraft=(id,documentId)=>{if(!editor.draftOwner||editor.view.document?.id!==documentId)throw Error('DRAFT_OWNER_CHANGED');return editor.draftOwner.registerDraft(id,documentId);};
 const host={requestUpdate(){this.updateComplete=Promise.resolve().then(()=>{rendered=instance.render();});},updateComplete:Promise.resolve(),querySelector(){return null;}};instance=new RequestEditing(host,editor);
 return {instance,editor,host,saved,reads,owner,route(value){route=value;},template:()=>rendered,async initial(){await instance.sync();await flush();},async close(){await instance.dispose();for(const value of owners)await value.dispose();await flush();assert.equal(uiPins,0,'Every checkpoint restoration pin released');}};
}
const result=(cursor,next=null)=>({protocolVersion:1,jobId:'job',documentId:'old',items:[{id:'candidate-'+(cursor||'first'),version:'1',jobId:'job',attemptId:'attempt',documentId:'old',outputIndex:cursor?32:0,safety:'safe',state:'prepared',preparedAssetId:'asset',hidden:false}],requestedCount:64,actualCount:64,observation:{phase:'completed'},inert:false,nextCursor:next});
async function pages(){const f=fixture();await f.initial();f.instance.queue={session:{id:'spend',version:'1',cap:null},counts:{reserved:0,dispatched:1,remaining:null,active:1},jobs:[{id:'job',documentId:'old',version:'1',local:'ready-to-dispatch',disposition:'eligible',review:{endpoint:'ideogram/v4',request:{kind:'generate',settings:{count:64}}},attempts:[{id:'attempt',state:'acknowledged',count:'dispatched',estimate:{rate:0.015,unit:'megapixel',count:64,source:'fixture',unknown:[]}}]}],nextCursor:null};f.route(async path=>{const cursor=new URL(path,'http://127.0.0.1').searchParams.get('after');return response(result(cursor,cursor?null:'second'));});return f;}
test('actual polling refresh keeps the current retained candidate cursor and exact backstack',async()=>{
 const f=await pages();try{await f.instance.inspectCandidates('job','attempt');await f.instance.navigateCandidatePage('job','attempt','next');assert.deepEqual(f.instance.navigation.candidatePage('attempt'),{cursor:'second',back:['']});await f.instance.inspectCandidates('job','attempt');assert.match(f.reads.at(-1),/&after=second$/);assert.equal(f.instance.candidateViews.get('attempt').items[0].id,'candidate-second');await f.instance.navigateCandidatePage('job','attempt','previous');assert.deepEqual(f.instance.navigation.candidatePage('attempt'),{cursor:'',back:[]});assert.equal(f.instance.candidateViews.get('attempt').items[0].id,'candidate-first');}finally{await f.close();}
});
test('prospective child admission failure preserves parent page, cursor, version and old child index',async()=>{
 const f=await pages();try{await f.instance.inspectCandidates('job','attempt');const prior=f.instance.candidateViews.get('attempt'),version=f.instance.candidateVersions.get('attempt'),index=f.instance.requestEdits.index,bytes=f.instance.navigation.lifecycle.candidateBytes;f.instance.requestEdits.refuse=true;await assert.rejects(f.instance.navigateCandidatePage('job','attempt','next'),/FIXTURE_CHILD_ADMISSION_REFUSAL/);assert.equal(f.instance.candidateViews.get('attempt'),prior);assert.equal(f.instance.candidateVersions.get('attempt'),version);assert.equal(f.instance.requestEdits.index,index);assert.equal(f.instance.navigation.lifecycle.candidateBytes,bytes);assert.deepEqual(f.instance.navigation.candidatePage('attempt'),{cursor:'',back:[]});}finally{f.instance.requestEdits.refuse=false;await f.close();}
});
test('late older page read cannot publish over an explicit later page action',async()=>{
 const f=await pages(),old=deferred();try{await f.instance.inspectCandidates('job','attempt');let first=true;f.route(async path=>{const cursor=new URL(path,'http://127.0.0.1').searchParams.get('after');if(!cursor&&first){first=false;return old.promise;}return response(result(cursor));});const pending=f.instance.inspectCandidates('job','attempt');void pending.catch(()=>{});await flush();await f.instance.navigateCandidatePage('job','attempt','next');old.resolve(response(result('')));await assert.rejects(pending,error=>error instanceof DOMException&&error.name==='AbortError');assert.equal(f.instance.candidateViews.get('attempt').items[0].id,'candidate-second');assert.deepEqual(f.instance.navigation.candidatePage('attempt'),{cursor:'second',back:['']});assert.equal(f.instance.navigation.lifecycle.candidateReads,0);}finally{old.resolve(response(result('')));await f.close();}
});
test('cross-attempt response identity cannot replace the current retained page',async()=>{
 const f=await pages();try{await f.instance.inspectCandidates('job','attempt');const prior=f.instance.candidateViews.get('attempt');f.route(async()=>{const value=result('second');value.items[0].attemptId='other-attempt';return response(value);});await assert.rejects(f.instance.navigateCandidatePage('job','attempt','next'),/identity changed/);assert.equal(f.instance.candidateViews.get('attempt'),prior);assert.deepEqual(f.instance.navigation.candidatePage('attempt'),{cursor:'',back:[]});}finally{await f.close();}
});
test('First resets both cursor and exact backstack, leaving retained candidate records untouched',async()=>{
 const f=await pages();try{await f.instance.inspectCandidates('job','attempt');await f.instance.navigateCandidatePage('job','attempt','next');const oldPage=f.instance.candidateViews.get('attempt'),snapshot=structuredClone(oldPage);await f.instance.navigateCandidatePage('job','attempt','first');assert.deepEqual(f.instance.navigation.candidatePage('attempt'),{cursor:'',back:[]});assert.deepEqual(oldPage,snapshot);}finally{await f.close();}
});
test('synchronous initial render failure closes its exact pending page generation',async()=>{const f=await pages(),update=f.host.requestUpdate;try{f.host.requestUpdate=()=>{throw Error('render unavailable');};await assert.rejects(f.instance.inspectCandidates('job','attempt'),/render unavailable/);assert.equal(f.instance.navigation.lifecycle.candidateReads,0);assert.equal(f.instance.navigation.candidatePending('attempt'),false);}finally{f.host.requestUpdate=update;await f.close();}});
test('failed child cleanup still clears and drains independent parent navigation owners',async()=>{const f=await pages();try{await f.instance.inspectCandidates('job','attempt');f.instance.requestEdits.refuse=true;await assert.rejects(f.instance.releaseNavigation(),/REQUEST_NAVIGATION_RELEASE_INCOMPLETE/);assert.equal(f.instance.candidateViews.size,0);assert.equal(f.instance.navigation.lifecycle.candidatePages,0);assert.equal(f.instance.navigation.lifecycle.candidates.models,0);}finally{f.instance.requestEdits.refuse=false;await f.close();}});
