// Actual RequestEdits, model owners and ControlAdapter. The display transport is
// unused here; the sibling browser fixture covers actual bounded SVG consumers.
import test from 'node:test';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {readFile} from 'node:fs/promises';import {transformWithOxc} from 'vite';
import {modelMemoryURL,uiModelOwnerURL,allocationsURL,promptMemoryURL,uiModule} from './module.mjs';
const root=process.env.CANDIDATE_COMPARISON_ROOT??'.',data=code=>'data:text/javascript;base64,'+Buffer.from(code).toString('base64');
const lit=data('export const nothing=null;export const html=(strings,...values)=>({strings,values});export const svg=html;');
async function module(path,imports){let code=(await transformWithOxc(await readFile(path,'utf8'),path)).code;code=code.replace(/import\s+["']\.\/(?:request-edits|candidate-comparison)\.css["'];?/g,'');for(const [name,url]of Object.entries(imports))code=code.replaceAll(JSON.stringify(name),JSON.stringify(url)).replaceAll("'"+name+"'",JSON.stringify(url));return data(code);}
const display=data('export const displayImage=value=>value;export const createDisplayPreviewURL=()=>{throw Error("Unexpected display read");};export const readDisplaySource=createDisplayPreviewURL,withDisplaySource=createDisplayPreviewURL;export const displayPreviewInfo=()=>null;export const validateDisplayImage=()=>{};export const revokeDisplayPreviewURL=()=>{};export async function retryDisplayPreviewCleanup(){}');
const common={'lit':lit,'../observability/model-memory.js':modelMemoryURL,'./adapters.js':await uiModule('src/ui/adapters.ts'),'./display-image.js':display,'../observability/display-preview.js':display};
const viewport=await uiModule(root+'/src/ui/comparison-viewport.ts'),view=await uiModule(root+'/src/ui/comparison-view.ts',{...common,'./comparison-viewport.js':viewport});
const comparison=await module(root+'/src/ui/candidate-comparison.ts',{...common,'./comparison-viewport.js':viewport,'./comparison-view.js':view});
const selection=await uiModule(root+'/src/ui/candidate-selection.ts',{'../observability/model-memory.js':modelMemoryURL});
const models=await uiModule('src/ui/request-edit-models.ts',{'../observability/model-memory.js':modelMemoryURL,'../observability/prompt-memory.js':promptMemoryURL,'./model-owner.js':uiModelOwnerURL});
const mask=await uiModule('src/ui/request-mask-memory.ts',{'../observability/allocations.js':allocationsURL});
const treatment=await module(root+'/src/ui/candidate-text-treatment.ts',{...common,'../observability/prompt-memory.js':promptMemoryURL,...Object.fromEntries(['protocol/json','protocol/sha256','request/text-treatment'].map(name=>['../'+name+'.js',pathToFileURL(resolve('dist/local/src/'+name+'.js')).href]))});
const {RequestEdits}=await import(await module(root+'/src/ui/request-edits.ts',{...common,'./candidate-text-treatment.js':treatment,'./candidate-comparison.js':comparison,'./candidate-selection.js':selection,'./request-mask-memory.js':mask,'./request-edit-models.js':models,...Object.fromEntries(['protocol/json','protocol/asset-projection','request/core','request/raster-plan','raster/mask','raster/mapping'].map(name=>['../'+name+'.js',pathToFileURL(resolve('dist/local/src/'+name+'.js')).href]))}));
const {allocationLedger}=await import(allocationsURL),turn=()=>new Promise(resolve=>setTimeout(resolve,5));
const candidate=(id,index,extra={})=>({id,version:'1',jobId:'job',attemptId:'attempt',documentId:'doc',outputIndex:index,hidden:false,safety:'safe',state:'prepared',preparedAssetId:'asset-'+id,...extra});
function buttons(template){const values=[],flat=value=>{if(value==null)return '';if(Array.isArray(value))return value.map(flat).join('');if(value.strings)return value.strings.reduce((out,part,i)=>out+part+(i<value.values.length?flat(value.values[i]):''),'');return '__v'+(values.push(value)-1)+'__';},markup=flat(template);return [...markup.matchAll(/<en-button\b([^>]*)>([\s\S]*?)<\/en-button>/g)].map(([,attributes,name])=>({name,click:values[Number(/@click=__v(\d+)__/.exec(attributes)?.[1])],disabled:values[Number(/\?disabled=__v(\d+)__/.exec(attributes)?.[1])]}));}
const event=()=>{const currentTarget={isConnected:true};return {currentTarget,composedPath:()=>[currentTarget],defaultPrevented:false,timeStamp:1};};
function fixture(){const errors=[],host={updateComplete:Promise.resolve(true),requestUpdate(){}},editor={view:{ready:true,document:{id:'doc',revision:'1',width:512,height:512},image:{layers:[]},selected:[]},sessionId:'session',session:{identity:()=> 'client'},draftOwner:{},beginFeedback(){},pinViewModels(){return ()=>{};}},hooks={draft:()=>undefined,entryKey:()=>undefined,hold:()=>()=>{},owns:()=>()=>true,changed(){},mutate(){throw Error('Unexpected draft edit');},error:error=>errors.push(error)},controller=new RequestEdits(host,editor,hooks);return {controller,errors,render:rows=>buttons(controller.renderCandidateNavigator('attempt',rows,false))};}
test('actual Previous/Next buttons change the single selected inspector while readiness refresh preserves it',async()=>{const f=fixture(),rows=[candidate('one',0),candidate('two',1)];try{f.controller.retainCandidates(rows);assert.equal(f.controller.isCandidateSelected('one'),true);assert.equal(f.controller.renderCandidate(rows[1],false),null);let next=f.render(rows).find(button=>button.name==='Next candidate');assert.equal(next.disabled,false);next.click(event());await turn();assert.equal(f.controller.isCandidateSelected('two'),true);assert.equal(f.controller.renderCandidate(rows[0],false),null);f.controller.retainCandidates([candidate('zero',-1),...rows]);assert.equal(f.controller.isCandidateSelected('two'),true);const prior=f.render(rows).find(button=>button.name==='Previous candidate');prior.click(event());await turn();assert.equal(f.controller.isCandidateSelected('one'),true);assert.deepEqual(f.errors,[]);}finally{await f.controller.dispose();}});
test('a stale navigation callback cannot replace a changed page and withheld outputs have no inspector',async()=>{const f=fixture(),rows=[candidate('one',0),candidate('two',1)];try{f.controller.retainCandidates(rows);const stale=f.render(rows).find(button=>button.name==='Next candidate');const replacement=[candidate('safe',2),candidate('withheld',3,{state:'withheld',safety:'unknown'})];f.controller.retainCandidates(replacement);stale.click(event());await turn();assert.equal(f.controller.isCandidateSelected('safe'),true);assert.equal(f.controller.isCandidateSelected('withheld'),false);assert.equal(f.controller.renderCandidate(replacement[1],false),null);assert.deepEqual(f.errors,[]);}finally{await f.controller.dispose();}});
test('selection retires the old inspection branch and selected version change invalidates prior action authority',async()=>{const f=fixture(),rows=[candidate('one',0),candidate('two',1)],released=[];try{f.controller.retainCandidates(rows);const actual=f.controller.releaseCandidate.bind(f.controller);f.controller.releaseCandidate=id=>{released.push(id);return actual(id);};const owns=f.controller.own();f.render(rows).find(button=>button.name==='Next candidate').click(event());await turn();assert.deepEqual(released,['one']);assert.equal(owns(),false);const selectedOwns=f.controller.own();f.controller.retainCandidates([rows[0],{...rows[1],version:'2'}]);assert.equal(selectedOwns(),false);assert.equal(f.controller.isCandidateSelected('two'),true);}finally{await f.controller.dispose();}});
test('dispose releases all selection/index owners after actual controller use',async()=>{const before=allocationLedger.snapshot().cpuBytes,f=fixture();f.controller.retainCandidates([candidate('one',0),candidate('two',1)]);f.render([candidate('one',0),candidate('two',1)]).find(button=>button.name==='Next candidate').click(event());await turn();await f.controller.dispose();assert.equal(allocationLedger.snapshot().cpuBytes,before);});
