// Actual logical ledger and draft owners; source-only authored, not executed.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {transformWithOxc} from 'vite';
import {allocationsURL,promptMemoryURL} from '../owned-preview-module.mjs';
const root=process.env.IE_DRAFT_METADATA_SOURCE_ROOT??'.',resultsRoot=process.env.CLIENT_CONTROL_ROOT??'.';
const data=code=>'data:text/javascript;base64,'+Buffer.from(code).toString('base64');
async function source(path,imports={}){let code=(await transformWithOxc(await readFile(path,'utf8'),path)).code;for(const [name,url]of Object.entries(imports))code=code.replaceAll(JSON.stringify(name),JSON.stringify(url)).replaceAll("'"+name+"'",JSON.stringify(url));return data(code);}
const models=await source('src/observability/model-memory.ts',{'./allocations.js':allocationsURL,'./prompt-memory.js':promptMemoryURL}),control=await source('src/state/control-memory.ts',{'../observability/allocations.js':allocationsURL}),json=await source('src/protocol/json.ts'),sha=await source('src/protocol/sha256.ts');
const imports={'../observability/allocations.js':allocationsURL,'../observability/prompt-memory.js':promptMemoryURL,'../observability/model-memory.js':models,'./control-memory.js':control};
const values=await source(root+'/src/state/draft-values.ts',imports),results=await source(resultsRoot+'/src/state/command-results.ts',{...imports,'../protocol/json.js':json,'../protocol/sha256.js':sha,'../protocol/validate.js':pathToFileURL(resolve('dist/local/src/protocol/validate.js')).href});
const persistence=await source(root+'/src/state/draft-persistence.ts',{...imports,'./draft-values.js':values,'./command-results.js':results});
const {DraftValues,DraftRegistrations,DRAFT_METADATA_LIMITS}=await import(values),{DraftPersistence}=await import(persistence),{allocationLedger,ALLOCATION_LIMITS}=await import(allocationsURL);
const totals=()=>{const s=allocationLedger.snapshot();return {cpu:s.cpuBytes,prompt:s.promptBytes,handles:s.handles,records:s.activeRecords};},deferred=()=>{let resolve;const promise=new Promise(done=>resolve=done);return {promise,resolve};},flush=async()=>{for(let n=0;n<40;n++)await Promise.resolve();};
const row=(overrides={})=>({id:'draft',kind:'prompt',documentId:'document',targetLayerId:null,expectedDocumentRevision:'1',composing:false,text:'complete text',generation:'1',savedGeneration:null,pending:false,error:null,...overrides});
const response=value=>{const text=JSON.stringify(value);return new Response(text,{headers:{'content-type':'application/json','content-length':String(Buffer.byteLength(text))}});};
const checkpoint=()=>({sessionId:'session',uiSeq:'1',preferences:{documentId:'document'},drafts:[],reconciledLayerIds:[]});
function fixture(){const registrations=new DraftRegistrations(),drafts=new DraftValues(registrations);return {registrations,drafts,async dispose(){drafts.clear();registrations.dispose();await registrations.drain();}};}
function fullCPU(){return allocationLedger.reserve({owner:'draft-test-pressure',kind:'control',cpuBytes:ALLOCATION_LIMITS.cpuBytes-ALLOCATION_LIMITS.textPartitionBytes-allocationLedger.snapshot().cpuBytes});}

test('registration refuses prospectively with no identity publication under pressure',async()=>{const before=totals(),f=fixture(),pressure=fullCPU();try{assert.throws(()=>f.registrations.register('draft','document'),/ALLOCATION_BUDGET/);assert.deepEqual(f.registrations.inspect(),{identities:0,editableBorrowers:0,refused:0});}finally{pressure.release();await f.dispose();}assert.deepEqual(totals(),before);});
test('same-ID registrations release exactly once and canceled blank identities do not accumulate',async()=>{const before=totals(),f=fixture();try{for(let n=0;n<80;n++){const a=f.registrations.register('draft','document'),b=f.registrations.register('draft','document');try{assert.equal(f.registrations.inspect().identities,1);assert.equal(f.registrations.inspect().editableBorrowers,2);a();a();assert.equal(f.registrations.inspect().editableBorrowers,1);}finally{a();b();b();}assert.equal(f.registrations.inspect().identities,0);}}finally{await f.dispose();}assert.deepEqual(totals(),before);});
test('first-input refusal uses existing capacity and releasing its editable owner cannot erase Close evidence',async()=>{const before=totals(),owner=new DraftPersistence('session',async()=>{throw Error('unexpected');},()=>''),release=owner.registerDraft('draft','document');let pressure;try{pressure=fullCPU();owner.refuseChange('draft','document');release();assert.equal(owner.drafts.size,0);assert.equal(owner.hasRefusedChanges,true);assert.throws(()=>owner.assertDocumentSaved('document'),/workspace is full/);pressure.release();pressure=undefined;owner.change(row());assert.equal(owner.hasRefusedChanges,false);assert.equal(owner.drafts.get('draft').text,'complete text');}finally{pressure?.release();release();await owner.dispose();}assert.deepEqual(totals(),before);});
test('unregistered refusal never invents an unbounded pending identity',async()=>{const before=totals(),f=fixture();try{assert.throws(()=>f.registrations.refuse('unregistered','document'),/DRAFT_UNREGISTERED/);assert.equal(f.registrations.inspect().identities,0);}finally{await f.dispose();}assert.deepEqual(totals(),before);});
test('64 live identities bound admission and exact release restores capacity',async()=>{const before=totals(),f=fixture(),releases=[];try{for(let n=0;n<DRAFT_METADATA_LIMITS.ids;n++)releases.push(f.registrations.register('draft_'+n,'document'));assert.throws(()=>f.registrations.register('overflow','document'),/DRAFT_ID_LIMIT/);releases.shift()();const next=f.registrations.register('recovered','document');releases.push(next);assert.equal(f.registrations.inspect().identities,64);}finally{for(const release of releases)release();await f.dispose();}assert.deepEqual(totals(),before);});
test('metadata replacement is preadmitted and preserves complete prior text and bindings on refusal',async()=>{const before=totals(),f=fixture(),binding={asset:'original'};let pressure;try{f.drafts.set('draft',row({maskBindings:binding}));binding.asset='changed';const old=f.drafts.get('draft');assert.equal(old.maskBindings.asset,'original');pressure=fullCPU();assert.throws(()=>f.drafts.set('draft',row({text:'new',maskBindings:{asset:'replacement'}})),/ALLOCATION_BUDGET/);assert.equal(f.drafts.get('draft'),old);assert.equal(old.text,'complete text');assert.throws(()=>{old.maskBindings.asset='mutated';},TypeError);}finally{pressure?.release();await f.dispose();}assert.deepEqual(totals(),before);});
test('status cleanup consumes bounded preadmitted slots even when the ledger is full',async()=>{const before=totals(),f=fixture();let pressure;try{f.drafts.set('draft',row());const current=f.drafts.get('draft');pressure=fullCPU();current.pending=true;current.error='Save unavailable';current.savedGeneration='1';current.pending=false;assert.equal(current.error,'Save unavailable');const held=totals();current.error='x'.repeat(4097);assert.match(current.error,/unsupported diagnostic/);assert.deepEqual(totals(),held);assert.throws(()=>{current.generation='9'.repeat(129);},/DRAFT_SEQUENCE_LIMIT/);assert.equal(current.generation,'1');}finally{pressure?.release();await f.dispose();}assert.deepEqual(totals(),before);});
test('full-row save borrow owns old metadata and exact text after replacement until final unpin',async()=>{const before=totals(),f=fixture();let borrowed,unpin;try{f.drafts.set('draft',row({maskBindings:{asset:'old'}}));borrowed=f.drafts.borrow('draft');unpin=borrowed.pin();f.drafts.set('draft',row({text:'new',generation:'2'}));f.drafts.clear();assert.equal(borrowed.value.maskBindings.asset,'old');assert.equal(borrowed.value.text,'complete text');borrowed.release();assert(totals().cpu>before.cpu);unpin();assert.equal(f.drafts.inspect().retainedRows,0);}finally{unpin?.();borrowed?.release();await f.dispose();}assert.deepEqual(totals(),before);});
test('text-only borrow keeps the shared backing while metadata retires normally',async()=>{const before=totals(),f=fixture();let borrowed;try{f.drafts.set('draft',row());borrowed=f.drafts.borrowText('draft');f.drafts.clear();assert.equal(f.drafts.inspect().retainedRows,0);assert.equal(allocationLedger.snapshot().promptBytes-before.prompt,row().text.length*2);borrowed.release();}finally{borrowed?.release();await f.dispose();}assert.deepEqual(totals(),before);});
test('invalidate preflights every generation and never publishes a partial batch',async()=>{const before=totals(),f=fixture();try{f.drafts.set('draft',row());f.drafts.set('last',row({id:'last',generation:'9'.repeat(128)}));assert.throws(()=>f.drafts.invalidate(),/DRAFT_SEQUENCE_LIMIT/);assert.equal(f.drafts.get('draft').generation,'1');assert.equal(f.drafts.get('last').generation,'9'.repeat(128));}finally{await f.dispose();}assert.deepEqual(totals(),before);});
test('owned save keeps original metadata through late preparation and disposal drain',async()=>{const before=totals(),gate=deferred(),owner=new DraftPersistence('session',async()=>{throw Error('stale save must not post');},()=>''),input=row();let done=false,pending;try{owner.checkpoint=checkpoint();owner.change(input);pending=owner.ownedSave('draft',async text=>{assert.equal(text,input.text);await gate.promise;return 'caption';});await flush();owner.change({...input,text:'replacement',targetLayerId:'new_target'});const drain=owner.dispose().then(()=>{done=true;});await flush();assert.equal(done,false);assert(owner.metadataOwnership.retainedRows>0);gate.resolve();assert.equal(await pending,undefined);await drain;}finally{gate.resolve();await pending?.catch(()=>{});await owner.dispose();}assert.deepEqual(totals(),before);});
test('owner disposal waits for actual editable callback lifetime rather than refunding its registration early',async()=>{const before=totals(),owner=new DraftPersistence('session',async()=>response(checkpoint()),()=>''),release=owner.registerDraft('blank','document');let done=false;try{const drain=owner.dispose().then(()=>{done=true;});await flush();assert.equal(done,false);assert(totals().cpu>before.cpu);release();await drain;assert.equal(done,true);}finally{release();await owner.dispose();}assert.deepEqual(totals(),before);});

for(const boundary of ['checkpoint','row','generation','asset'])test('saved text finishing after changed '+boundary+' authority cannot publish its stale draft',async()=>{
 const before=totals(),gate=deferred(),owner=new DraftPersistence('session',async()=>{throw Error('unexpected');},()=>''),saved={...row(),assetId:'original_asset',status:'saved-unapplied'};delete saved.text;delete saved.savedGeneration;delete saved.pending;delete saved.error;let loading;try{owner.checkpoint={...checkpoint(),drafts:[saved]};loading=owner.restoreDraft('draft',async assetId=>{assert.equal(assetId,'original_asset');return gate.promise;});await flush();if(boundary==='checkpoint')owner.checkpoint={...checkpoint(),uiSeq:'2',drafts:[{...saved,assetId:'new_asset',generation:'2'}]};else if(boundary==='row')owner.checkpoint.drafts[0]={...saved};else if(boundary==='generation')owner.checkpoint.drafts[0].generation='2';else owner.checkpoint.drafts[0].assetId='new_asset';gate.resolve('old complete text');await loading;assert.equal(owner.drafts.size,0);}finally{gate.resolve('old complete text');await loading?.catch(()=>{});await owner.dispose();}assert.deepEqual(totals(),before);
});
test('a registered change can mark generation-work admission refusal without needing a new editable lease',async()=>{const before=totals(),owner=new DraftPersistence('session',async()=>{throw Error('unexpected');},()=>''),release=owner.registerDraft('draft','document');let pressure;try{owner.change(row());const prior=owner.drafts.get('draft');pressure=fullCPU();assert.throws(()=>owner.change(row({text:'new complete input'})),/ALLOCATION_BUDGET/);assert.equal(owner.drafts.get('draft'),prior);assert.equal(owner.hasRefusedChanges,true);assert.throws(()=>owner.assertDocumentSaved('document'),/workspace is full/);pressure.release();pressure=undefined;owner.change(row({text:'new complete input'}));assert.equal(owner.hasRefusedChanges,false);}finally{pressure?.release();release();await owner.dispose();}assert.deepEqual(totals(),before);});
