import type {CandidatePlacementReview} from './history.js';
import {blob,id,seq,keys,requireValue as ok,imageVersion} from './validate.js';
import {historyBody} from './history-validation.js';
import {extent} from '../raster/core.js';
import {canonical} from './json.js';
import {validateRequestRasterPlan,requireOutputMapping} from '../request/raster-plan.js';
import {validateRequestSourceCapture} from './request-edits.js';
import {validateRequestTextTreatmentEnvelope,validateTextTreatmentAdoptionChoice} from '../request/text-treatment.js';
import {ENCODED_COMPOSITION_BYTES,validateEncodedCompositionInputs,validateEncodedAdoptionInputs} from './encoded-rebuild.js';
const same=(a:unknown,b:unknown)=>canonical(a)===canonical(b);
const digest=(v:unknown)=>typeof v==='string'&&/^sha256:[a-f0-9]{64}$/.test(v);
/** Stored review metadata has no preparation or filesystem authority of its own. */
export function candidatePlacementReview(v:any):asserts v is CandidatePlacementReview{
 keys(v,['protocolVersion','kind','reviewId','reviewHash','targetClientId','expiresAt','documentId','documentRevision','source','placement','inputs','preparation','width','height',...(Object.hasOwn(v,'lettering')?['lettering']:[]),...(Object.hasOwn(v,'encodedComposition')?['encodedComposition']:[]),...(Object.hasOwn(v,'encodedCompositionRef')?['encodedCompositionRef']:[])]);
 ok(v.protocolVersion===1&&v.kind==='candidate-placement-review-1'&&id(v.reviewId)&&digest(v.reviewHash)&&id(v.targetClientId)&&typeof v.expiresAt==='string'&&Number.isFinite(Date.parse(v.expiresAt))&&id(v.documentId)&&seq(v.documentRevision)&&['deferred','prepared-reuse'].includes(v.preparation));extent(v.width,v.height);imageVersion(v.source);keys(v.placement,['candidateId','mode','placement','newDocumentId','actualOutput','newLayerId','name',...(Object.hasOwn(v.placement,'replacement')?['replacement']:[]),...(Object.hasOwn(v.placement,'textTreatment')?['textTreatment']:[])]);historyBody({type:'ReviewCandidatePlacement',...v.placement});
 const i=v.inputs;keys(i,['kind','mode','identity','plan','sourceCapture','outputMapping','coverage',...(Object.hasOwn(i,'encodedRebuild')?['encodedRebuild']:[])]);ok(i.kind==='candidate-adoption-inputs-1'&&i.mode===v.placement.mode);
 const a=i.identity;keys(a,['candidateId','candidateVersion','documentId','jobId','attemptId','requestId','outputIdentity','preparedAssetId','preparedAssetVersion','preparedAssetHash','requestHash','jobVersion','writerEpoch']);for(const field of ['candidateId','documentId','jobId','attemptId','requestId','preparedAssetId'])ok(id(a[field]));for(const field of ['candidateVersion','preparedAssetVersion','jobVersion','writerEpoch'])ok(seq(a[field]));for(const field of ['outputIdentity','preparedAssetHash','requestHash'])ok(digest(a[field]));ok(a.candidateId===v.placement.candidateId&&a.documentId===v.documentId);
 if(i.plan!==null)validateRequestRasterPlan(i.plan);if(i.sourceCapture!==null)validateRequestSourceCapture(i.sourceCapture);if(i.outputMapping!==null){ok(i.plan!==null);requireOutputMapping(i.plan,i.outputMapping,i.outputMapping.actualOutput.width,i.outputMapping.actualOutput.height);}
 if(i.mode==='safe-region')ok(i.plan!==null&&i.sourceCapture!==null&&i.coverage!==null&&i.plan.document.width===v.width&&i.plan.document.height===v.height);else ok(i.outputMapping===null&&i.coverage===null);
 if(i.encodedRebuild!==undefined){validateEncodedAdoptionInputs(i.encodedRebuild);ok(i.mode==='safe-region'&&i.plan!==null);const e=i.encodedRebuild;ok(e.candidate.assetId===a.preparedAssetId&&e.candidate.assetVersion===a.preparedAssetVersion&&e.candidate.assetHash===a.preparedAssetHash&&same(e.source.info.pixels,i.plan.sourcePixels)&&same(e.mask.authored.pixels,i.plan.authoredMask)&&same(e.mask.effective.pixels,i.plan.effectiveMask)&&same(e.mask.approved.pixels,i.outputMapping?.effectiveMask??i.plan.effectiveMask)&&e.source.info.width===i.plan.document.width&&e.source.info.height===i.plan.document.height);}
 if(i.coverage!==null){keys(i.coverage,['originalEffectivePixels','effectivePixels','lostPixels']);for(const field of Object.keys(i.coverage))ok(Number.isSafeInteger(i.coverage[field])&&i.coverage[field]>=0&&i.coverage[field]<=25000000);}
 if(v.lettering!==undefined){const l=v.lettering;keys(l,['kind','plan','choice','intent','intentHash','manifest','grid','candidateAloneAssetId','nativeOffAssetId','nativeOnAssetId']);ok(l.kind==='candidate-lettering-comparison-1'&&v.placement.textTreatment!==undefined&&i.outputMapping===null);validateRequestTextTreatmentEnvelope(l.plan);validateTextTreatmentAdoptionChoice(l.choice);ok(same(l.plan,v.placement.textTreatment.plan)&&same(l.choice,v.placement.textTreatment.choice));blob(l.intent);blob(l.manifest);ok(l.intent.mediaType==='application/json'&&BigInt(l.intent.byteLength)>0n&&BigInt(l.intent.byteLength)<=524288n&&l.manifest.mediaType==='application/json'&&BigInt(l.manifest.byteLength)>0n&&BigInt(l.manifest.byteLength)<=65536n&&l.intentHash===l.intent.hash);keys(l.grid,['width','height']);ok(l.grid.width===v.width&&l.grid.height===v.height);for(const field of ['candidateAloneAssetId','nativeOffAssetId','nativeOnAssetId'])ok(id(l[field]));ok(new Set([l.candidateAloneAssetId,l.nativeOffAssetId,l.nativeOnAssetId]).size===3);}
 else ok(v.placement.textTreatment===undefined);
 if(v.encodedCompositionRef!==undefined){ok(v.encodedComposition===undefined&&i.encodedRebuild!==undefined);blob(v.encodedCompositionRef);ok(v.encodedCompositionRef.mediaType==='application/json'&&BigInt(v.encodedCompositionRef.byteLength)>0n&&BigInt(v.encodedCompositionRef.byteLength)<=BigInt(ENCODED_COMPOSITION_BYTES));}
 if(v.encodedComposition!==undefined){ok(i.encodedRebuild!==undefined);validateEncodedCompositionInputs(v.encodedComposition);ok(v.encodedComposition.candidateAssetId===a.preparedAssetId&&v.encodedComposition.width===v.width&&v.encodedComposition.height===v.height);}
 if(v.lettering&&i.encodedRebuild)ok(v.encodedComposition!==undefined||v.encodedCompositionRef!==undefined);
}
