import assert from 'node:assert/strict';import {readFile,writeFile,unlink} from 'node:fs/promises';import {createHash,randomUUID} from 'node:crypto';import {resolve,join} from 'node:path';import {setup,pair,call,mutationHeaders,cookieFrom,readHeaders} from '../source/tests/protocol/helpers.mjs';import {operate,original,envelope,terminal,eventFor,binary} from '../source/tests/raster/helpers.mjs';
const root=resolve(import.meta.dirname,'..'),after=[],ctx={after:fn=>after.push(fn)},facts={};let now=Date.now();const f=await setup(ctx,{now:()=>now});const hash=b=>'sha256:'+createHash('sha256').update(b).digest('hex');
async function stage(){const bytes=await readFile(join(root,'source/tests/raster/fixtures/white.png')),s={protocolVersion:1,stagingId:randomUUID(),purpose:'image',expectedBytes:String(bytes.length),sha256:hash(bytes),mediaType:'image/png'};assert.equal((await f.post('/api/v1/assets/staging',s)).status,201);assert.equal((await call(f.server.origin,'/api/v1/assets/staging/'+s.stagingId,{method:'PUT',raw:bytes,headers:{...mutationHeaders(f.server,f.paired),'Content-Type':'application/octet-stream','Upload-Offset':'0'}})).status,200);return s;}
try{const input=await original(f,'hidden-alpha.png'),preview=(await operate(f,{type:'PrepareRaster',assetId:input.id})).event.payload.asset,r=(await operate(f,{type:'ReviewRaster',assetId:preview.id})).event,review=(await f.read('/api/v1/assets/raster-reviews/'+r.payload.reviewId)).json;
const foreign=await pair(f.server);assert.equal((await call(f.server.origin,'/api/v1/assets/raster-reviews/'+review.reviewId,{headers:readHeaders(cookieFrom(foreign))})).status,403);now+=1700000;assert.equal((await f.read('/api/v1/session')).status,200);now+=100001;assert.equal((await f.read('/api/v1/assets/raster-reviews/'+review.reviewId)).status,410);const expired=await terminal(f,envelope(f,{type:'ApproveRaster',assetId:preview.id,reviewId:review.reviewId,reviewHash:review.reviewHash}));assert.equal(expired.json.receipt.status,'rejected');facts.expiry={read:410,receipt:expired.json.receipt};
const pairs=[];for(let n=0;n<12;n++){const s=await stage(),c=envelope(f,{type:'PrepareRaster',assetId:input.id}),other={...c,command:{...c.command,body:{type:'FinalizeStaging',stagingId:s.stagingId,expectedSha256:s.sha256}}},responses=await Promise.all([f.post('/api/v1/commands',n%2?other:c),f.post('/api/v1/commands',n%2?c:other)]);assert.equal(responses.filter(r=>r.status===409&&r.json.error.code==='COMMAND_ID_REUSE').length,1);const win=responses[0].status===409?(n%2?c:other):(n%2?other:c),done=await terminal(f,win);assert.equal(done.json.receipt.status,'accepted');assert.deepEqual((await f.post('/api/v1/commands',win)).json.receipt,done.json.receipt);const changed={...win,command:{...win.command,sessionId:'changed'}};assert.equal((await f.post('/api/v1/commands',changed)).status,409);pairs.push({statuses:responses.map(r=>r.status),winner:win.command.body.type,commandId:c.command.commandId});}facts.assetRasterRaces=pairs;
const rr=(await operate(f,{type:'ReviewRaster',assetId:preview.id})).event,rv=(await f.read('/api/v1/assets/raster-reviews/'+rr.payload.reviewId)).json,p=join(f.root,'objects','sha256',preview.raster.pixels.hash.slice(7,9),preview.raster.pixels.hash.slice(7));await unlink(p);const corruptApproval=await terminal(f,envelope(f,{type:'ApproveRaster',assetId:preview.id,reviewId:rv.reviewId,reviewHash:rv.reviewHash}));facts.missingPixelsApproval=corruptApproval.json;if(corruptApproval.json.receipt.status==='accepted'){const a=(await eventFor(f,corruptApproval.json.receipt)).payload.asset;facts.newAsset=a;facts.manifestRead=(await f.read('/api/v1/assets/'+a.id+'/raster')).status;const ec=envelope(f,{type:'ExportRaster',assetId:a.id});facts.exportInitial=(await f.post('/api/v1/commands',ec)).json;await new Promise(r=>setTimeout(r,100));facts.exportState=(await f.read('/api/v1/commands/'+ec.command.commandId)).json;}
await writeFile(join(root,'safety-results-v2.json'),JSON.stringify(facts,null,2));console.log(JSON.stringify({expiry:'PASS',races:pairs.length,missingPixelsApproval:facts.missingPixelsApproval}));}
catch(e){await writeFile(join(root,'safety-partial-v2.json'),JSON.stringify({facts,error:e.stack},null,2));throw e;}finally{for(const fn of after.reverse())await fn();}
