import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { inflateSync } from 'node:zlib';
import { brushCorpus, crc32, deterministicChunks, fileIdentity, portableFixtureFailure, rasterRow, setupFixture, textFrames, validateObserved, verifyFixtureManifest, FIXTURE_VERSION, workloadDefinition, writeExactSizePNG, writeRasterPNG } from '../../tooling/qualification/campaigns/fixtures.mjs';

test('portable preparation reports the actual abort code and message when missing inputs are empty',()=>{
  const built={status:'fail',missing:[],error:{code:'ABORT_ERR',message:'Synthetic export was cancelled'}};
  assert.equal(portableFixtureFailure(built).message,'Portable fixture incomplete: {"code":"ABORT_ERR","message":"Synthetic export was cancelled"}');
  assert.deepEqual(built,{status:'fail',missing:[],error:{code:'ABORT_ERR',message:'Synthetic export was cancelled'}});
});
test('portable preparation retains nonempty missing-input diagnostics ahead of a generic error',()=>{
  const built={status:'inconclusive',missing:['Synthetic seed requires a font','Synthetic seed requires an adapter'],error:{code:'FIXTURE_REQUIRED',message:'Incomplete seed'}};
  assert.equal(portableFixtureFailure(built).message,'Portable fixture incomplete: ["Synthetic seed requires a font","Synthetic seed requires an adapter"]');
});
test('portable preparation reports errors without missing inputs and falls back to status when no error exists',()=>{
  assert.equal(portableFixtureFailure({status:'fail',error:{code:'EIO',message:'Synthetic write failed'}}).message,'Portable fixture incomplete: {"code":"EIO","message":"Synthetic write failed"}');
  for(const built of [{status:'inconclusive',missing:[]},{status:'inconclusive',missing:[],error:null},{status:'inconclusive'}])assert.equal(portableFixtureFailure(built).message,'Portable fixture incomplete: "inconclusive"');
});

test('workload dimensions and histories cannot silently shrink',()=>{
  const n=workloadDefinition('W1'),s=workloadDefinition('W2');assert.deepEqual([n.width,n.height,n.layers,n.visibleLayers,n.events,n.snapshotTail,n.queued],[2048,2048,20,5,10000,500,100]);assert.deepEqual([s.width,s.height,s.layers,s.visibleLayers,s.events,s.snapshotTail,s.candidates],[5000,5000,100,10,100000,500,4]);assert.equal(workloadDefinition('WC',{closureBytes:'4294967296'}).assets,10000);assert.throws(()=>workloadDefinition('WC',{closureBytes:100}));assert.throws(()=>workloadDefinition('scaled-W1'));
});
test('native UTF8 corpus is exact, bounded, multilingual and has long lines',()=>{
  for(const name of ['WXn','WXs']){const d=workloadDefinition(name),frames=textFrames(d);assert.equal(frames.length,d.textLayers);assert.equal(frames.reduce((n,f)=>n+Buffer.byteLength(f.text),0),d.textBytes);assert(frames.every(f=>f.byteLength<=d.frameTextLimit&&f.logicalLines<=d.logicalLines));const all=frames.map(f=>f.text).join('');for(const fragment of ['Cafe\u0301','العَرَبِيَّة','देवनागरी','中文','✈','unbrokenunbroken'])assert(all.includes(fragment));}
});
test('100 actual 120-sample stroke specimens retain independent gestures and 60Hz timing',()=>{const rows=brushCorpus();assert.equal(rows.length,100);assert.equal(new Set(rows.map(x=>x.id)).size,100);assert(rows.every(x=>x.brushDiameter===64&&x.samples.length===120&&x.samples[119].timeMs===119*1000/60));assert.notDeepEqual(rows[0].samples,rows[1].samples);assert(rows.every(row=>row.samples[119].x===row.samples[118].x&&row.samples[119].y===row.samples[118].y));});
test('streamed binary fixtures contain deterministic real bytes independent of chunk size',()=>{const a=Buffer.concat([...deterministicChunks(1031,{seed:'a',chunkBytes:100})]),b=Buffer.concat([...deterministicChunks(1031,{seed:'a',chunkBytes:31})]);assert.equal(a.length,1031);assert.deepEqual(a,b);assert.notDeepEqual(a,Buffer.concat([...deterministicChunks(1031,{seed:'b'})]));assert.throws(()=>[...deterministicChunks(100,{chunkBytes:0})]);});
test('streamed PNG has genuine full-grid pixels and valid chunk CRCs',async t=>{const root=await mkdtemp(join(tmpdir(),'campaign-png-'));t.after(()=>rm(root,{recursive:true,force:true}));const path=join(root,'pixels.png'),identity=await writeRasterPNG(path,{width:11,height:7,index:2,alpha:true}),bytes=await readFile(path);assert.equal(identity.byteLength,String(bytes.length));assert.deepEqual(bytes.subarray(0,8),Buffer.from([137,80,78,71,13,10,26,10]));let offset=8;const chunks=[];while(offset<bytes.length){const length=bytes.readUInt32BE(offset),type=bytes.toString('ascii',offset+4,offset+8),payload=bytes.subarray(offset+8,offset+8+length);assert.equal(bytes.readUInt32BE(offset+8+length),crc32(bytes.subarray(offset+4,offset+8+length)));if(type==='IDAT')chunks.push(payload);offset+=length+12;}assert.deepEqual(inflateSync(Buffer.concat(chunks)),Buffer.concat(Array.from({length:7},(_,y)=>rasterRow(11,y,2,{alpha:true}))));await assert.rejects(writeRasterPNG(path,{width:11,height:7}),{code:'EEXIST'});});
test('manifest observed-count checks refuse metadata-only or incomplete claims',()=>{const d=workloadDefinition('W1'),facts={productionValidated:true,activeRequests:1,width:2048,height:2048,layers:20,imageLayers:20,textLayers:0,visibleLayers:5,events:10000,snapshotTail:500,queued:100,candidates:1};assert.doesNotThrow(()=>validateObserved(d,facts));assert.throws(()=>validateObserved(d,{...facts,events:100}),/events/);assert.throws(()=>validateObserved(d,{...facts,productionValidated:false}),/real product/);assert.throws(()=>validateObserved('WC4G',{productionValidated:true,events:100000,assets:10000,closureBytes:4294967296,captionVersions:4096,closureVerified:true,features:{}}),/real referenced/);});
test('heavy fixture preparation is opt-in and never runs merely by importing helpers',async()=>{await assert.rejects(setupFixture({workload:'W2',output:'/tmp/unused'}),/allowHeavy/);});
test('file identities change with actual retained bytes',async t=>{const root=await mkdtemp(join(tmpdir(),'campaign-seal-'));t.after(()=>rm(root,{recursive:true,force:true}));const p=join(root,'input');await writeFile(p,'before');const first=await fileIdentity(p);await writeFile(p,'after');assert.notEqual((await fileIdentity(p)).sha256,first.sha256);});

test('outer fixture seal is required and detects rewritten metadata before product claims are read',async t=>{const root=await mkdtemp(join(tmpdir(),'campaign-manifest-'));t.after(()=>rm(root,{recursive:true,force:true}));const path=join(root,'fixture.json'),manifest={kind:'sealed-performance-fixture',version:FIXTURE_VERSION,workload:'W0',outcome:'prepared',observed:{productionValidated:true,width:2048,height:2048,activeRequests:0,layers:0,imageLayers:0,textLayers:0,visibleLayers:0,events:0,snapshotTail:0,queued:0,candidates:0},corpus:{files:[]}},bytes=Buffer.from(JSON.stringify(manifest)),seal={path,sha256:'sha256:'+createHash('sha256').update(bytes).digest('hex')};await writeFile(path,bytes);await assert.rejects(verifyFixtureManifest(path),/separately retained/);assert.equal((await verifyFixtureManifest(path,{seal})).workload,'W0');await writeFile(path,JSON.stringify({...manifest,outcome:'incomplete'}));await assert.rejects(verifyFixtureManifest(path,{seal}),/changed after preparation/);});

test('exact transport PNG retains complete pixels and real target bytes',async t=>{const root=await mkdtemp(join(tmpdir(),'campaign-exact-png-'));t.after(()=>rm(root,{recursive:true,force:true}));const source=join(root,'source.png'),path=join(root,'exact.png');await writeRasterPNG(source,{width:11,height:7,index:3});const sealed=await writeExactSizePNG(path,source,4096);assert.equal(sealed.byteLength,'4096');const b=await readFile(path),parts=[];for(let offset=8;offset<b.length;){const n=b.readUInt32BE(offset),type=b.toString('ascii',offset+4,offset+8);assert.equal(b.readUInt32BE(offset+8+n),crc32(b.subarray(offset+4,offset+8+n)));if(type==='IDAT')parts.push(b.subarray(offset+8,offset+8+n));offset+=12+n;}assert.deepEqual(inflateSync(Buffer.concat(parts)),Buffer.concat(Array.from({length:7},(_,y)=>rasterRow(11,y,3))));});
