import {html,nothing} from 'lit';
import type {LitElement} from 'lit';
import type {EditorClient} from '../state/editor-client.js';
import {canonical} from '../protocol/json.js';
import {SHA256} from '../protocol/sha256.js';
import {validateTextTreatmentPlan,validateRequestTextTreatmentEnvelope,assertTextTreatmentEnvelope,type TextTreatmentPlan,type RequestTextTreatmentEnvelope,type TreatmentAdoptionChoice} from '../request/text-treatment.js';
import {createOwnedModel,modelPayloadBytes,reserveModelBytes,type OwnedModel,type ModelPayload} from '../observability/model-memory.js';
import {PromptReaderCleanupError} from '../observability/prompt-memory.js';
import {ControlAdapter} from './adapters.js';

type Page={bytes:string;byteLength:string;offset:string;nextOffset:string|null};
export type CandidateTreatmentInput={candidateId:string;candidateVersion:string;jobId:string;attemptId:string;safety:'safe'|'unknown'|'withheld';envelope:RequestTextTreatmentEnvelope};
export type CandidateTreatmentPlacement={newLayerId:string;placement:'current-document'|'new-document';mode:'safe-region'|'full-candidate';preservation:TreatmentAdoptionChoice['preservation']};
export type CandidateTreatmentAdjunct={kind:'candidate-text-treatment-1';plan:RequestTextTreatmentEnvelope;choice:TreatmentAdoptionChoice};
export type CandidateTreatmentHooks={owns:()=>()=>boolean;invalidatePlacement:(candidateId:string)=>void;error:(error:unknown)=>void};
const ID=/^[A-Za-z0-9_-]{1,128}$/,MAX_PLAN=524288,MAX_PAGE=65536;
const stopped=()=>new DOMException('Candidate text treatment changed.','AbortError');
const fresh=(current:()=>boolean,signal:AbortSignal)=>{if(signal.aborted||!current())throw stopped();};

/** One explicit metadata read, at most seventeen sequential <=32 KiB pages.
 * Never reads candidate pixels, generated text, or provider URLs. */
export async function loadCandidateTextTreatment(editor:EditorClient,input:CandidateTreatmentInput,current:()=>boolean,signal:AbortSignal):Promise<OwnedModel<TextTreatmentPlan>>{
 validateRequestTextTreatmentEnvelope(input.envelope);if(!ID.test(input.jobId)||!ID.test(input.attemptId)||input.safety!=='safe')throw Error('Text treatment metadata requires an admitted candidate.');
 const total=Number(input.envelope.plan.byteLength);if(!Number.isSafeInteger(total)||total<1||total>MAX_PLAN)throw Error('Text treatment plan exceeds the metadata limit.');fresh(current,signal);
 const workspace=reserveModelBytes('candidate-text-plan-workspace',total*24+MAX_PAGE*4,4,'prompt');
 try{const bytes=new Uint8Array(total);let offset=0,pages=0;
  while(offset<total){if(++pages>17)throw Error('Text treatment page count exceeds the bound.');fresh(current,signal);
   const path='/api/v1/jobs/'+encodeURIComponent(input.jobId)+'/candidates?attempt='+encodeURIComponent(input.attemptId)+'&prompt=text-treatment&offset='+offset;
   const page=await editor.ownedJSON<Page>(path,'candidate-text-plan-page',{signal},current,MAX_PAGE,'prompt');
   try{fresh(current,signal);const p=page.value;if(!p||p.byteLength!==String(total)||p.offset!==String(offset)||typeof p.bytes!=='string'||p.bytes.length>43692||p.bytes.length%4||!/^[A-Za-z0-9+/]*={0,2}$/.test(p.bytes))throw Error('Text treatment metadata page identity is invalid.');
    const decoded=atob(p.bytes);if(decoded.length<1||decoded.length>32768||decoded.length>total-offset)throw Error('Text treatment metadata page length is invalid.');
    for(let i=0;i<decoded.length;i++)bytes[offset+i]=decoded.charCodeAt(i);offset+=decoded.length;
    if(p.nextOffset!==(offset===total?null:String(offset)))throw Error('Text treatment metadata page order changed.');
   }finally{page.release();}
  }
  if(new SHA256().update(bytes).digest()!==input.envelope.plan.hash)throw Error('Text treatment plan bytes changed.');fresh(current,signal);
  const text=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(bytes),owned=createOwnedModel<TextTreatmentPlan>('candidate-text-plan',text.length*4+8,()=>JSON.parse(text) as TextTreatmentPlan,'prompt');
  try{validateTextTreatmentPlan(owned.value);assertTextTreatmentEnvelope(input.envelope,owned.value);fresh(current,signal);return owned;}catch(error){owned.release();throw error;}
 }finally{workspace.release();}
}

type CopyFields={newLayerId:string;values:[string,string,string,string,string,string]};
/** One visible candidate. This helper supplies review choices only; the caller
 * must show actual native-off/on comparisons before accepting either placement path. */
export class CandidateTextTreatmentEditing{
 private adapter=new ControlAdapter();private disposed=false;private epoch=0;private busy=false;private scheduled=false;private task:Promise<void>|null=null;private abort:AbortController|null=null;
 private binding:OwnedModel<CandidateTreatmentInput>|null=null;private bindingKey='';private plan:OwnedModel<TextTreatmentPlan>|null=null;private planCurrent:(()=>boolean)|null=null;private form:ModelPayload|null=null;
 private action:TreatmentAdoptionChoice['action']|''='';private hides=new Set<string>();private copies=new Map<string,CopyFields>();private duplicate=false;private approved=false;private revision=0;private prepared:OwnedModel<CandidateTreatmentAdjunct>|null=null;private preparedKey='';
 private retired=new Set<Promise<void>>();private cleanup=new Set<PromptReaderCleanupError>();private failures=new Set<unknown>();
 constructor(private host:LitElement,private editor:EditorClient,private hooks:CandidateTreatmentHooks){}
 private changed(){this.host.requestUpdate();}
 private remember(error:unknown){if(error instanceof PromptReaderCleanupError)this.cleanup.add(error);else if(error instanceof AggregateError)for(const cause of error.errors)this.remember(cause);}
 private retire(value:{release:()=>void}|null){if(!value)return;const task=Promise.resolve().then(()=>this.host.updateComplete).then(()=>value.release()).finally(()=>this.retired.delete(task));this.retired.add(task);void task.catch(error=>{this.failures.add(error);this.hooks.error(error);});}
 private clear(){this.epoch++;this.abort?.abort();this.adapter.invalidate();this.retire(this.plan);this.plan=null;this.planCurrent=null;this.retire(this.binding);this.binding=null;this.bindingKey='';this.retire(this.prepared);this.prepared=null;this.preparedKey='';this.retire(this.form);this.form=null;this.action='';this.hides.clear();this.copies.clear();this.duplicate=this.approved=false;this.changed();}
 dispose(){this.disposed=true;this.clear();}
 async drain(){if(this.task)await Promise.allSettled([this.task]);while(this.retired.size)await Promise.allSettled([...this.retired]);const errors:unknown[]=[...this.failures];for(const error of this.cleanup)try{await error.retry();this.cleanup.delete(error);}catch(failure){errors.push(failure);}if(errors.length)throw new AggregateError(errors,'CANDIDATE_TEXT_TREATMENT_RELEASE_INCOMPLETE');}
 private current(){const owns=this.hooks.owns(),epoch=this.epoch,binding=this.binding,session=this.editor.session,identity=session.identity(),owner=this.editor.draftOwner,documentId=this.editor.view.document?.id,revision=this.editor.view.document?.revision;return ()=>!this.disposed&&epoch===this.epoch&&binding===this.binding&&owns()&&session===this.editor.session&&identity===session.identity()&&owner===this.editor.draftOwner&&documentId===this.editor.view.document?.id&&revision===this.editor.view.document?.revision;}
 private hold(){const releases=[this.binding?.pin(),this.plan?.pin(),this.form?.pin()].filter((value):value is ()=>void=>!!value);return ()=>{for(const release of releases)release();};}
 private run(event:Event,work:(current:()=>boolean,signal:AbortSignal)=>Promise<void>|void){if(this.busy||this.scheduled||this.disposed||!this.binding)return;const current=this.current(),release=this.hold();this.scheduled=true;let started=false,freed=false;const free=()=>{if(!freed){freed=true;release();}};this.adapter.action(event,()=>{started=true;this.scheduled=false;if(!current()){free();return;}const abort=new AbortController();this.abort=abort;this.busy=true;this.changed();const task=Promise.resolve().then(()=>work(()=>!abort.signal.aborted&&current(),abort.signal)).catch(error=>{this.remember(error);if(current()&&!(error instanceof DOMException&&error.name==='AbortError'))this.hooks.error(error);}).finally(()=>{free();if(this.task===task){this.task=null;this.busy=false;this.abort=null;this.changed();}});this.task=task;});setTimeout(()=>{if(!started){this.scheduled=false;free();}},0);}
 private async load(current:()=>boolean,signal:AbortSignal){const binding=this.binding!.value,owned=await loadCandidateTextTreatment(this.editor,binding,current,signal);if(!current()){owned.release();throw stopped();}this.retire(this.plan);this.plan=owned;const owner=this.current();this.planCurrent=()=>owner()&&owned.value.inventory.documentId===this.editor.view.document?.id;this.invalidate();}
 private invalidate(){this.approved=false;this.revision++;this.retire(this.prepared);this.prepared=null;this.preparedKey='';if(this.binding)this.hooks.invalidatePlacement(this.binding.value.candidateId);this.changed();}
 private change(event:Event,read:()=>string|boolean,apply:(value:string|boolean)=>void){if(!this.binding||this.busy)return;const current=this.current(),release=this.hold();this.adapter.settled(event,read,value=>{if(!current())return;try{apply(value);this.invalidate();}catch(error){this.hooks.error(error);}});queueMicrotask(release);}
 private visibleNative(id:string){const plan=this.plan?.value,original=plan?.inventory.layers.find(row=>row.id===id),current=this.editor.view.image?.layers.find(row=>row.id===id);if(!original||original.kind!=='text'||!current||current.kind!=='text'||current.version!==original.version||!current.visible||current.locked)throw Error('The native text layer changed, is hidden, or is locked. Review the current document again.');return current;}
 private retainedNative(id:string){const row=this.plan?.value.inventory.layers.find(layer=>layer.id===id);if(!row||row.kind!=='text')throw Error('The retained native version is unavailable.');if(!row.visible||row.locked)throw Error('The retained native version was hidden or locked in this request.');return row;}
 private copy(id:string,checked:boolean){if(!checked){this.copies.delete(id);return;}if(this.copies.size>=99)throw Error('A new document supports at most 99 copied native layers beside the candidate.');const original=this.retainedNative(id),live=this.editor.view.image?.layers.find(layer=>layer.id===id),v=live?.kind==='text'&&live.version===original.version?live.layerToDocument:[1,0,0,1,0,0];if(!Array.isArray(v)||v.length!==6||!v.every(Number.isFinite))throw Error('The native transform is unavailable.');this.copies.set(id,{newLayerId:crypto.randomUUID(),values:v.map(String) as CopyFields['values']});}
 private transform(event:Event,id:string,copy:CopyFields,index:number){const control=event.currentTarget as unknown as {value:string};this.change(event,()=>control.value,value=>{if(this.copies.get(id)!==copy)throw stopped();if(typeof value!=='string'||value.length>64)throw Error('Transform value exceeds its bound.');copy.values[index]=value;});}
 private validateSelections(){const plan=this.plan?.value;if(!plan||!this.planCurrent?.())throw Error('Load current text-treatment provenance first.');if(!this.action)throw Error('Choose the lettering treatment explicitly.');
  if(this.action!=='new-document'&&plan.inventory.documentRevision!==this.editor.view.document?.revision)throw Error('The request document changed. Review a new-document placement using the retained request versions.');
  if(this.action==='keep-native-overlay'&&(plan.choice.kind!=='native-overlay'||plan.choice.placement!=='current-document'))throw Error('This request did not review native overlay preservation.');
  if(this.action==='hide-native-originals'&&!this.hides.size)throw Error('Select the native originals to hide explicitly.');
  if(this.action==='keep-both'&&!this.duplicate)throw Error('Acknowledge duplicate lettering before keeping both.');
  for(const id of this.action==='hide-native-originals'?this.hides:[]){this.visibleNative(id);if(!plan.allowedHideNativeIds.includes(id))throw Error('This native layer was not approved for hiding in the request.');}
  for(const [id,copy]of this.action==='new-document'?this.copies:[]){this.retainedNative(id);if(plan.choice.kind==='native-overlay'&&!plan.retainedNativeIds.includes(id))throw Error('This native layer was not reviewed for copying.');const v=copy.values.map(Number);if(copy.values.some(x=>!x.trim()||x.length>64)||!v.every(Number.isFinite)||v[0]*v[3]-v[1]*v[2]===0)throw Error('Each copied native layer needs an explicit finite, invertible transform.');}
 }
 /** Borrowed through next selection/owner change; caller must admit serialization.
  * The exact generated layer ID is supplied by the same placement review command. */
 selection(candidateId:string,placement:CandidateTreatmentPlacement):CandidateTreatmentAdjunct|undefined{
  if(!this.binding||this.binding.value.candidateId!==candidateId)return undefined;this.validateSelections();if(!this.approved)throw Error('Confirm the lettering choices before preparing placement.');if(!ID.test(placement.newLayerId)||this.editor.view.image?.layers.some(row=>row.id===placement.newLayerId)||[...this.copies.values()].some(row=>row.newLayerId===placement.newLayerId))throw Error('Candidate layer identity must be fresh and distinct from every native copy.');
  if((this.action==='new-document')!==(placement.placement==='new-document'))throw Error('Choose the matching current-document or new-document placement.');
  if(placement.mode==='full-candidate'&&placement.preservation!=='none'||placement.placement==='new-document'&&placement.preservation!=='none')throw Error('This placement cannot claim source-exterior preservation.');
  if(this.action==='keep-native-overlay'&&placement.preservation!=='single-original-contribution')throw Error('Keeping this native overlay in the current document requires the exact reviewed background contribution.');
  const key=canonical({candidateId,placement,revision:this.revision});if(this.prepared&&this.prepared.value.choice.newLayerId===placement.newLayerId&&this.preparedKey===key)return this.prepared.value;
  const plan=this.plan!.value,choice:TreatmentAdoptionChoice={kind:'text-treatment-adoption-choice-1',action:this.action as TreatmentAdoptionChoice['action'],approvalId:crypto.randomUUID(),duplicationAcknowledgement:this.action==='keep-both'?crypto.randomUUID():null,newLayerId:placement.newLayerId,hideNativeIds:this.action==='hide-native-originals'?plan.inventory.layers.filter(row=>this.hides.has(row.id)).map(row=>row.id):[],nativeCopies:this.action==='new-document'?plan.inventory.layers.filter(row=>this.copies.has(row.id)).map(row=>{const copy=this.copies.get(row.id)!;return {sourceLayerId:row.id,newLayerId:copy.newLayerId,transform:copy.values.map(Number) as [number,number,number,number,number,number]};}):[],preservation:placement.preservation};
  const value:CandidateTreatmentAdjunct={kind:'candidate-text-treatment-1',plan:this.binding.value.envelope,choice},owned=createOwnedModel('candidate-text-adjunct',modelPayloadBytes(value),()=>structuredClone(value),'prompt');this.retire(this.prepared);this.prepared=owned;this.preparedKey=key;return owned.value;
 }
 private check(id:string,label:string,checked:boolean,disabled:boolean,apply:(value:boolean)=>void){return html`<en-checkbox id=${id} .checked=${checked} ?disabled=${disabled||this.busy} @en-change=${(event:Event)=>{const control=event.currentTarget as unknown as {checked:boolean};this.change(event,()=>control.checked,value=>apply(value===true));}}>${label}</en-checkbox>`;}
 render(input:CandidateTreatmentInput|null){if(this.disposed)return nothing;if(!input){if(this.binding)this.clear();return nothing;}let key:string;try{if(Object.keys(input).sort().join(',')!=='attemptId,candidateId,candidateVersion,envelope,jobId,safety')throw Error('Candidate binding has unknown fields.');validateRequestTextTreatmentEnvelope(input.envelope);if(!['safe','unknown','withheld'].includes(input.safety)||![input.candidateId,input.jobId,input.attemptId].every(id=>ID.test(id))||input.candidateVersion.length>128||!/^(0|[1-9][0-9]*)$/.test(input.candidateVersion))throw Error('Candidate identity is invalid.');key=canonical(input);if(key.length>4096)throw Error('Candidate text-treatment binding exceeds its bound.');if(input.safety!=='safe'){if(this.binding)this.clear();return html`<p>Text-treatment comparison is withheld with this candidate.</p>`;}if(key!==this.bindingKey){if(this.retired.size>=8)throw Error('Candidate treatment rendering is still pending.');const binding=createOwnedModel('candidate-text-binding',modelPayloadBytes(input),()=>structuredClone(input),'prompt');let form:ModelPayload;try{form=reserveModelBytes('candidate-text-controls',262144,12,'prompt');}catch(error){binding.release();throw error;}this.clear();this.binding=binding;this.bindingKey=key;this.form=form;}}catch(error){this.hooks.error(error);return nothing;}
  const plan=this.plan?.value,current=!!this.planCurrent?.(),sameRevision=plan?.inventory.documentRevision===this.editor.view.document?.revision,id=input.candidateId;return html`<section id=${'candidate-text-treatment-'+id} aria-label="Check lettering and duplicates" aria-busy=${String(this.busy)}><h4>Check lettering and duplicates</h4><p>Generated lettering and spelling are not guaranteed. Native overlays, generated pixels and semantic text have separate provenance.</p><en-button id=${'candidate-text-load-'+id} ?disabled=${this.busy} @click=${(event:Event)=>this.run(event,(owns,signal)=>this.load(owns,signal))}>Inspect exact text-treatment provenance</en-button>
   ${plan?html`<p>Request plan ${plan.fingerprint}. Native pixels included: ${plan.rasterIncludedNativeIds.join(', ')||'none'}; excluded: ${plan.rasterExcludedNativeIds.join(', ')||'none'}. Semantic text included: ${plan.includedSemanticIds.join(', ')||'none'}; excluded: ${plan.excludedSemanticIds.join(', ')||'none'}.</p>${!current?html`<en-alert announcement="none">The candidate or document changed. Reload its retained provenance and review the placement again.</en-alert>`:!sameRevision?html`<en-alert announcement="none">The request document changed. Only a fresh new-document placement can use these retained request versions; the original document stays unchanged.</en-alert>`:nothing}<en-select id=${'candidate-text-action-'+id} label="Lettering adoption choice" .value=${this.action} ?disabled=${this.busy||!current} @en-change=${(event:Event)=>{const control=event.currentTarget as unknown as {value:string};this.change(event,()=>control.value,value=>{if(!['keep-native-overlay','hide-native-originals','keep-both','new-document'].includes(String(value)))throw Error('Choose a lettering treatment.');this.action=value as TreatmentAdoptionChoice['action'];});}}><en-select-option value="">Choose explicitly</en-select-option><en-select-option value="keep-native-overlay" ?disabled=${!sameRevision}>Keep native overlay on the reviewed background</en-select-option><en-select-option value="hide-native-originals" ?disabled=${!sameRevision}>Use baked candidate and hide selected native originals</en-select-option><en-select-option value="keep-both" ?disabled=${!sameRevision}>Keep both knowingly</en-select-option><en-select-option value="new-document">New document with explicit native copies</en-select-option></en-select>
   ${this.action==='keep-both'?this.check('candidate-text-duplicate-'+id,'I reviewed the lettering and knowingly retain both generated and editable text.',this.duplicate,!current,value=>this.duplicate=value):nothing}
   ${plan.inventory.layers.filter(row=>row.kind==='text').map(row=>{const live=this.editor.view.image?.layers.find(layer=>layer.id===row.id),eligible=!!live&&live.version===row.version&&live.visible&&!live.locked,copy=this.copies.get(row.id);return html`<div><p>Native ${row.id} · retained version ${row.version} · ${eligible?'current visible unlocked layer':'stale, hidden, locked or missing'}.</p>${this.action==='hide-native-originals'?this.check('candidate-text-hide-'+row.id,'Hide native original '+row.id,this.hides.has(row.id),!current||!eligible||!plan.allowedHideNativeIds.includes(row.id),value=>{if(value){this.visibleNative(row.id);this.hides.add(row.id);}else this.hides.delete(row.id);}):nothing}${this.action==='new-document'?html`${this.check('candidate-text-copy-'+row.id,'Copy editable native layer '+row.id+' into the new document',!!copy,!current||!row.visible||row.locked||plan.choice.kind==='native-overlay'&&!plan.retainedNativeIds.includes(row.id),value=>this.copy(row.id,value))}${copy?html`<p>Copying retained request version ${row.version}, including its exact native text and font resources. Fresh copied layer ID ${copy.newLayerId}. Review the explicit document transform [a, b, c, d, e, f]; when the original version is no longer current, it starts at identity [1, 0, 0, 1, 0, 0]:</p>${copy.values.map((value,index)=>html`<en-number-field id=${'candidate-text-transform-'+row.id+'-'+index} label=${'Native '+row.id+' transform '+['a','b','c','d','e','f'][index]} .value=${value} ?disabled=${this.busy||!current} @en-input=${(event:Event)=>this.transform(event,row.id,copy,index)} @en-change=${(event:Event)=>this.transform(event,row.id,copy,index)}></en-number-field>`)}`:nothing}`:nothing}</div>`;})}
   <en-button id=${'candidate-text-confirm-'+id} ?disabled=${this.busy||!current||!this.action} @click=${(event:Event)=>this.run(event,()=>{this.validateSelections();this.approved=true;this.changed();})}>Use these lettering choices in the placement preview</en-button><p role="status">${this.approved?'Lettering choices confirmed. Review the actual placement or its lettering comparisons before adopting.':'No lettering adoption choices are confirmed.'}</p><p>Review a full prepared placement, or inspect the retained candidate and native-off/on lettering comparisons before accepting deferred preparation. These comparisons use actual retained rasters; no text pixels are manufactured or erased.</p>`:nothing}</section>`;
 }
}
