import {html,nothing,noChange} from 'lit';
import {labels as v4OperationLabels} from '../request/core.js';
import type {LitElement} from 'lit';
import {parseColor,exportSRGB} from '@en-reve/elements/color-picker.js';
import {chooseDestination,writeDestination} from '../state/destination.js';
import type {EditorClient} from '../state/editor-client.js';
import type {Document,BlobRef} from '../protocol/store.js';
import type {CompositionCommand} from '../protocol/history.js';
import {canonical} from '../protocol/json.js';
import {browserPhases} from '../observability/browser.js';
import {compositionObservations} from '../observability/composition-observations.js';
import {ControlAdapter} from './adapters.js';
import {CompositionLifetime,type CompositionOwner} from './composition-lifetime.js';
import {CompositionError,emptyComposition,emptyElement,emptyStyle,validateComposition,bindingIds,bindingValue,fieldStatus,linkField,detach,fromCaption,projectBounds,inverseAffine} from '../composition/core.js';
import type {Composition,LayerValue,Element as SemanticElement,Binding,Geometry,Issue,ParseResult} from '../composition/core.js';
import {bytes} from '../composition/core.js';
import {jsonPayloadUnits,reservePromptPayload,PromptReaderCleanupError} from '../observability/prompt-memory.js';
import {CompositionPayload,CompositionReadCleanupError,compositionAllowance,compositionPayloadBytes,cloneCompositionValue,createCompositionValue,compositionRenderAllowance,reserveCompositionRead,readCompositionJSON,parseCompositionValue,encodeCompositionText,serializeCompositionValue,projectCompositionValue,readCompositionBlob,readCompositionBytes} from '../composition/memory.js';
import type {OwnedCompositionValue} from '../composition/memory.js';

type Field=HTMLElement&{value:string};
type View={composition:Composition|null;bindings:Record<string,string>;layers:LayerValue[];revision:string};
type DocumentBase=Pick<Document,'id'|'revision'|'width'|'height'>;
type SyncOwner={connection:EditorClient['session'];identity:string|null;owner:EditorClient['draftOwner'];session:string;document:string;revision:string;documentEpoch:number;fieldEpoch:number;recovery:number};
export class CompositionEditing {
 private payloads=new Map<string,CompositionOwner>();private lifetime?:CompositionLifetime;private renderDepth=0;private focusPending?:Promise<void>;private queuedActions=new Map<ReturnType<typeof setTimeout>,()=>void>();private reads=new Set<AbortController>();private pending=new Set<Promise<unknown>>();private pinWaiters=new Set<Promise<void>>();private cleanupFailures=new Set<PromptReaderCleanupError>();private releasePending:Promise<void>|undefined;
 private get owners(){return this.lifetime??=new CompositionLifetime(bytes=>compositionAllowance('composition-owner-metadata',bytes),async request=>{if(request)this.host.requestUpdate();await this.host.updateComplete;});}
 private adopt<T>(slot:string,next:OwnedCompositionValue<T>,registration?:()=>void){
  let owned:CompositionOwner;try{this.owners.ensure(slot.startsWith('render-')?1:7);if(slot==='draft'&&!registration){if(!this.base)throw Error('COMPOSITION_DRAFT_OWNER');registration=this.editor.registerDraft(this.draftId,this.base.id);}owned=this.owners.own(next.owner,registration,!slot.startsWith('render-'));}catch(error){next.owner.release();registration?.();throw error;}
  const old=this.payloads.get(slot);this.payloads.set(slot,owned);old?.release(!this.renderDepth);return next.value;
 }
 private releasePayload(slot:string){this.payloads.get(slot)?.release(!this.renderDepth);this.payloads.delete(slot);}
 private pinPayloads(){const release=this.owners.action();let done!:()=>void;const waiting=new Promise<void>(resolve=>done=resolve);this.pinWaiters.add(waiting);let live=true;return ()=>{if(!live)return;live=false;release();this.pinWaiters.delete(waiting);done();};}
 private watch<T>(work:()=>Promise<T>){const task=work();this.pending.add(task);void task.then(()=>{this.pending.delete(task);},error=>{this.pending.delete(task);if(error instanceof PromptReaderCleanupError)this.cleanupFailures.add(error);});return task;}
 private async drain(){while(this.pending.size||this.pinWaiters.size)await Promise.allSettled([...this.pending,...this.pinWaiters]);const errors:unknown[]=[];try{await this.lifetime?.close();this.lifetime=undefined;}catch(error){errors.push(error);}for(const error of this.cleanupFailures)try{await error.retry();this.cleanupFailures.delete(error);}catch(failure){errors.push(failure);}if(errors.length)throw new AggregateError(errors,'COMPOSITION_RELEASE_INCOMPLETE');}
 private copyBase(document:DocumentBase,revision=document.revision){
  // Four keys (21 UTF-16 units), two strings and two numbers. No image or
  // ordered-layer graph is captured by the synchronous factory or its result.
  const id=document.id,width=document.width,height=document.height;
  return createCompositionValue<DocumentBase>('composition-document-base',58+2*(id.length+revision.length),()=>({id,revision,width,height}));
 }
 private captureBase(){const document=this.editor.view.document;return document?this.copyBase(document):undefined;}
 private draftPayload(){return {composition:this.c,bindings:this.bindings,numbers:this.numbers,rawText:this.convertText,color:this.color,selected:this.selected};}
 private admitMutation(extra=4096){this.owners.ensure(7);const size=compositionPayloadBytes(this.draftPayload())+extra;this.adopt('draft',{value:undefined,owner:compositionAllowance('composition-draft',size)});}
 private async readJSON<T>(path:string,owns:()=>boolean,view:'accepted'|'draft'){
  const lease=reserveCompositionRead(),abort=new AbortController();this.reads.add(abort);let handed=false;
  try{const response=await this.editor.session.transport(path,{signal:abort.signal});handed=true;return await readCompositionJSON<T>(response,owns,abort.signal,view,lease);}finally{if(!handed)lease.release();this.reads.delete(abort);}
 }
 private async readBytes(path:string,limit:number,owns:()=>boolean){
  const lease=reservePromptPayload('composition-raw-read-operation',0),abort=new AbortController();this.reads.add(abort);let handed=false;
  try{const response=await this.editor.session.transport(path,{signal:abort.signal});handed=true;const value=await readCompositionBytes(response,limit,owns,abort.signal,lease);if(!response.ok){value.owner.release();throw Error('Original source unavailable.');}return value;}finally{if(!handed)lease.release();this.reads.delete(abort);}
 }
 private disposed=false;private reviewIntent=0;private fieldEpoch=0;private ownsModel=()=>false;private settlements=new Set<Promise<void>>();private currentView='plain';guides=true;
 get view(){return this.currentView;}
 set view(value:string){if(value!==this.currentView){this.reviewIntent++;this.currentView=value;}}
 cancelReview(){this.reviewIntent++;}
 get operation(){return this.c?.request.operation;}
 private c:Composition|null=null;private accepted:Composition|null=null;private layers:LayerValue[]=[];private bindings:Record<string,string>={};
 private selected='';private layerChoice='';private key='';private base:DocumentBase|null=null;private dirty=false;private draftId:string=crypto.randomUUID();private generation=0;private loading='';private loadingOwner:unknown;private loadingRead=0;private composing=false;
 private syncFailure:SyncOwner|null=null;private loadingSync:SyncOwner|null=null;private syncRecovery=0;
 private restoreRetry:{scope:SyncOwner;model:WeakRef<Composition>;generation:number}|null=null;
 private adapter=new ControlAdapter();private issueValue:Issue[]=[];
 private get issues(){return this.issueValue;}
 private set issues(value:Issue[]){if(!value.length){this.issueValue=[];this.releasePayload('issues');}else this.issueValue=this.adopt('issues',cloneCompositionValue(value));}
 private readonly refusalIssue:Issue[]=[{path:'$',code:'CAPACITY',message:'The edit remains in its control. Free local capacity and retry before closing.'}];
 private issuesRefused(){this.releasePayload('issues');this.issueValue=this.refusalIssue;this.host.requestUpdate();}
 // Ordinary model admission leaves six slots for a three-pane render and
 // its previous scopes. Rendering can then retire saturated old generations.
 private render<T>(slot:string,build:()=>T){this.renderDepth++;try{if(!this.disposed&&!this.releasePending){this.owners.ensure();let names=0;for(const layer of this.editor.view.image?.layers??[])names+=layer.name.length*2;const size=compositionPayloadBytes({...this.draftPayload(),layers:this.layers,issues:this.issues,rawText:this.rawText,convertText:this.convertText,exact:this.exact,conversion:this.conversion,message:this.message})*4+names*8+65536;this.adopt('render-'+slot,{value:null,owner:compositionRenderAllowance(size)});}return build();}finally{this.renderDepth--;}}
 private messageValue='';private get message(){return this.messageValue;}private set message(value:string){this.releasePayload('message');this.messageValue=value;}private exact='';private projection=false;private committing=false;
 private numbers:Record<string,string>={};private color='#336699';private paletteTarget='element';private conversionValue:{hex:string;clipped:boolean;alpha:number}|null=null;private get conversion(){return this.conversionValue;}private set conversion(value:{hex:string;clipped:boolean;alpha:number}|null){if(value===null)this.releasePayload('conversion');this.conversionValue=value;}
 private rawRead=0;private rawInspected='';private rawText='';private rawResult:ParseResult|null=null;private rawIndex=0;private rawOffset=0;private convertOpen=false;private convertText='';private convertResult:ParseResult|null=null;private sourceRaw:BlobRef|null=null;private refusedControl:Field|null=null;
 private fieldValue(id:string,value:string){return this.refusedControl?.id===id?noChange:value;}
 constructor(private host:LitElement,private editor:EditorClient,private inspect:()=>void,private draw:()=>void,private dialogs:()=>Promise<void>,private revealNative:(id:string)=>void){this.owners.ensure(0);}
 releaseDocument(){if(this.releasePending)return this.releasePending;for(const abort of this.reads)abort.abort();for(const [timer,release]of this.queuedActions){clearTimeout(timer);release();}this.queuedActions.clear();for(const owner of this.payloads.values())owner.release();this.payloads.clear();this.fieldEpoch++;this.syncFailure=null;this.restoreRetry=null;this.loadingSync=null;this.rawRead++;this.loadingRead++;this.reviewIntent++;this.drag?.release();this.drag=null;this.generation++;this.adapter.invalidate();this.loading='';this.loadingOwner=undefined;this.c=null;this.accepted=null;this.layers=[];this.bindings={};this.base=null;this.key='';this.ownsModel=()=>false;this.modeAdmission=null;this.modeIntent=null;this.modeReady=()=>false;this.selected='';this.layerChoice='';this.dirty=false;this.composing=false;this.issues=[];this.message='';this.exact='';this.numbers={};this.conversion=null;this.rawInspected='';this.rawText='';this.rawResult=null;this.convertOpen=false;this.convertText='';this.convertResult=null;this.sourceRaw=null;this.refusedControl=null;this.host.requestUpdate();this.releasePending=this.drain().finally(()=>{this.releasePending=undefined;});return this.releasePending;}
 get lifecycle(){return {models:(this.c?1:0)+(this.accepted?1:0),rawCharacters:this.rawText.length+this.convertText.length+this.exact.length,pendingSettlements:this.settlements.size,pendingOperations:this.pending.size,pendingPins:this.pinWaiters.size,cleanupFailures:this.cleanupFailures.size,owners:this.lifetime?.state.owners??0,retiredOwners:this.lifetime?.state.retired??0,queuedActions:this.queuedActions.size};}
 dispose(){this.disposed=true;return this.releaseDocument();}
 operationChanged(operation:string){if(!v4OperationLabels.includes(operation))return;if(this.c&&this.c.request.operation!==operation){this.admitMutation(operation.length*2+4096);this.c.request.operation=operation;this.c.request.rewriteAcknowledged=false;this.touch();}}
 linked(layer:string){return this.c?.elements.filter(e=>[e.desc,e.text,e.bounds].some(b=>b?.mode==='layer'&&this.bindings[b.layerId]===layer))??[];}
 reveal(layer:string){const links=this.linked(layer),at=links.findIndex(e=>e.id===this.selected);if(links.length){this.selected=links[(at+1)%links.length].id;this.view='composition';this.inspect();this.touch(false);}}
 private changed(){this.host.requestUpdate();this.draw();}
 private focusAfter(work:()=>void|Promise<void>){if(this.focusPending||this.disposed||this.releasePending)return;let release:()=>void;try{release=this.pinPayloads();}catch{return;}const pending=this.host.updateComplete.then(async()=>{if(!this.disposed&&!this.releasePending)await work();}).catch(()=>{}).finally(()=>{if(this.focusPending===pending)this.focusPending=undefined;release();});this.focusPending=pending;}
 private error(e:unknown){if(this.disposed||this.releasePending)return;try{this.issues=e instanceof CompositionError?e.issues:[{path:'$',code:'ACTION',message:e instanceof Error?e.message:String(e)}];compositionObservations.value('issues',this.issues,'ui-issues');}catch{this.issuesRefused();}this.changed();this.focusAfter(()=>this.host.querySelector<HTMLElement>('#composition-errors')?.focus());}
 private action(work:()=>void|Promise<void>){const owns=this.fieldOwner();return (event:Event)=>this.button(event,work,owns);}
 private button(e:Event,work:()=>void|Promise<void>,owns=this.fieldOwner()){if(this.disposed||this.releasePending||this.refusedControl||!owns()){e.preventDefault();return;}const host=e.currentTarget as Node;let release:()=>void;try{release=this.pinPayloads();}catch(error){e.preventDefault();this.error(error);return;}let live=true;const done=()=>{if(live){live=false;release();}};const timer=setTimeout(()=>{this.queuedActions.delete(timer);if(!live)return;if(e.defaultPrevented||!host?.isConnected||!owns()){done();return;}this.cancelReview();void this.watch(async()=>{try{if(this.c)this.admitMutation();await work();}catch(error){if(error instanceof PromptReaderCleanupError)this.cleanupFailures.add(error);this.error(error);}finally{done();}});},0);this.queuedActions.set(timer,done);}
 private compositionState(active:boolean){if(this.disposed)return;this.cancelReview();this.composing=active;this.save();this.changed();}
 private fieldOwner(){const epoch=this.fieldEpoch,c=this.c,documentId=this.editor.view.document?.id,session=this.editor.sessionId,owner=this.editor.draftOwner,modelOwner=this.ownsModel;return ()=>!this.disposed&&this.fieldEpoch===epoch&&this.c===c&&this.editor.view.document?.id===documentId&&this.editor.sessionId===session&&this.editor.draftOwner===owner&&(!c||modelOwner());}
 // Disposal is permanent; even callbacks obtained from a later render cannot
 // admit a new payload or invoke a control mutation on this controller.
 private refuseControl(target:Field){if(this.c&&this.base){this.editor.draftOwner?.refuseChange(this.draftId,this.base.id);if(target?.id&&typeof target.value==='string')this.refusedControl=target;}}
 private settleControl<T>(e:Event,read:()=>T,accept:(v:T)=>void,owns=this.fieldOwner()){if(this.disposed||this.releasePending||!owns()){e.preventDefault();return;}const target=e.currentTarget as Field;if(this.refusedControl&&this.refusedControl!==target){e.preventDefault();return;}let release:()=>void;try{release=this.pinPayloads();}catch(error){e.preventDefault();this.refuseControl(target);this.error(error);return;}this.adapter.settled(e,read,value=>{if(this.disposed||!owns()){e.preventDefault();return;}try{accept(value);if(this.refusedControl===target){this.save();this.refusedControl=null;}}catch(error){this.refuseControl(target);this.error(error);}});queueMicrotask(release);}
 private settled<T>(e:Event,read:()=>T,accept:(v:T)=>void){const owns=this.fieldOwner();if(!owns())return;let done!:()=>void;const pending=new Promise<void>(resolve=>done=resolve);this.settlements.add(pending);this.settleControl(e,read,v=>{if(owns())accept(v);});queueMicrotask(()=>{this.settlements.delete(pending);done();});}
 // Keep weak proposal tokens through release so queued stale proposals can
 // still veto and reconcile their public host after adapter invalidation.
 private modeIntent:{value:string;owns:()=>boolean;pending:boolean}|null=null;private modeReady=()=>false;private modeProposals=new WeakMap<Field,Event>();
 private saveMode(){const intent=this.modeIntent;if(intent?.pending&&intent.owns()&&this.ownsModel()&&this.modeReady()){this.save();intent.pending=false;}}
 private modeAdmission:{epoch:number;connection:EditorClient['session'];identity:string|null;documentId:string;sessionId:string;owner:EditorClient['draftOwner']}|null=null;
 private modeSelection(){
  const epoch=this.fieldEpoch,documentId=this.editor.view.document?.id,session=this.editor.sessionId,owner=this.editor.draftOwner,connection=this.editor.session,identity=connection.identity();
  const startup=!this.modeAdmission&&!this.c&&!this.base&&!documentId&&!this.editor.view.ready&&(identity!==null||!owner&&session==='editor_null');let firstIdentity=identity,firstOwner=owner,firstDocument=documentId;
  const owns=()=>{
   if(this.disposed||this.fieldEpoch!==epoch||this.editor.session!==connection)return false;
   const currentIdentity=connection.identity();if(startup&&firstIdentity===null)firstIdentity=currentIdentity;if(currentIdentity!==firstIdentity)return false;
   if(!startup)return this.editor.view.document?.id===documentId&&this.editor.sessionId===session&&this.editor.draftOwner===owner;
   const admission=this.modeAdmission;
   if(admission)return firstIdentity!==null&&admission.epoch===epoch&&admission.connection===connection&&admission.identity===firstIdentity&&(!firstOwner||firstOwner===admission.owner)&&(!firstDocument||firstDocument===admission.documentId)&&this.editor.draftOwner===admission.owner&&this.editor.sessionId===admission.sessionId&&this.editor.view.document?.id===admission.documentId;
   if(this.c||this.base||firstIdentity===null&&(this.editor.draftOwner!==undefined||this.editor.view.document!==null))return false;
   firstOwner??=this.editor.draftOwner;firstDocument??=this.editor.view.document?.id;
   return this.editor.draftOwner===firstOwner&&this.editor.view.document?.id===firstDocument&&(this.editor.sessionId===session||!owner&&session==='editor_null'&&firstIdentity!==null&&this.editor.sessionId==='editor_'+firstIdentity||!!firstOwner&&this.editor.sessionId===firstOwner.sessionId);
  };
  return (ev:Event)=>{
   const h=ev.currentTarget as Field;if(!h||ev.composedPath()[0]!==h)return;
   const refuse=()=>{ev.preventDefault();this.adapter.write(h,'value',this.view);};
   if(!owns()||!['plain','composition'].includes(h.value)){refuse();return;}
   this.modeProposals.set(h,ev);let done!:()=>void;const pending=new Promise<void>(resolve=>done=resolve);this.settlements.add(pending);
   this.settleControl(ev,()=>h.value,v=>{if(!owns()||!['plain','composition'].includes(v)){refuse();return;}this.modeIntent={value:v,owns,pending:true};this.view=v;this.saveMode();this.changed();},owns);
   queueMicrotask(()=>{if(this.modeProposals.get(h)===ev&&!owns())refuse();this.settlements.delete(pending);done();});
  };
 }
 private value(e:Event,set:(v:string)=>void){const h=e.currentTarget as Field;this.settled(e,()=>h.value,v=>{this.admitMutation(v.length*4+4096);set(v);this.touch();});}
 private input(e:Event,set:(v:string)=>void){const h=e.currentTarget as Field,d=(e as CustomEvent).detail;this.settled(e,()=>h.value,v=>{this.composing=!!d?.isComposing;this.admitMutation(v.length*4+4096);set(v);this.touch();});}
 private issueTarget(i:Issue){if(this.numbers[i.path]!==undefined)return i.path;const m=/^elements\.([^.]+)\.(desc|text|bounds)$/.exec(i.path);if(m)return 'semantic-issue-'+m[1]+'-'+m[2];if(i.path==='frame')return this.c?.frame.width===null?'request-dimensions':'request-width';if(i.path==='request')return 'composition-expansion';if(i.path==='background')return 'composition-background';if(i.path==='style')return 'composition-style';if(i.path==='raw'||i.path==='ref')return 'composition-raw';return 'composition-scene';}
 private errorNavigation(ev:Event){if(ev.defaultPrevented)return;let target=(ev as CustomEvent).detail?.data?.target;if(typeof target!=='string'||target.length>256)return;ev.preventDefault();const e=this.c?.elements.find(e=>target.includes(e.id));if(e){this.selected=e.id;const b=e.bounds?.mode==='literal'?e.bounds.value:null;target=target.endsWith('-desc')?'semantic-desc':target.endsWith('-text')?'semantic-text':target.endsWith('-bounds')?b&&b.rect[2]<=0?'semantic-'+e.id+'-Width':b&&b.rect[3]<=0?'semantic-'+e.id+'-Height':'semantic-bounds-policy':target;this.inspect();}this.changed();const active=document.activeElement;this.focusAfter(async()=>{const field=this.host.querySelector<HTMLElement>('#'+CSS.escape(target)),item=field?.closest('en-accordion-item'),group=item?.closest('en-accordion');if(item&&group){group.value=[item.getAttribute('value')!];await group.updateComplete;await item.updateComplete;}if(!this.disposed&&!this.releasePending&&document.activeElement===active)field?.focus();});}
 private text(id:string,label:string,value:string,set:(v:string)=>void,readOnly=false){const owns=this.fieldOwner();return html`<en-textarea id=${id} label=${label} .value=${this.fieldValue(id,value)} .rows=${2} ?readOnly=${readOnly} @en-input=${(e:Event)=>{if(!readOnly&&owns())this.input(e,set);}}></en-textarea>`;}
 private number(id:string,label:string,initial:number,set:(v:number)=>void){const owns=this.fieldOwner();return html`<en-number-field id=${id} label=${label} .value=${this.fieldValue(id,this.numbers[id]??String(initial))} @en-input=${(e:Event)=>{if(owns())this.input(e,v=>{this.numbers[id]=v;if(v.trim()&&Number.isFinite(Number(v)))set(Number(v));});}}></en-number-field>`;}
 private choice(label:string,value:string,options:[string,string][],set:(v:string)=>void,id=''){id||='composition-choice-'+label.replace(/[^A-Za-z0-9]+/g,'-').toLowerCase();const owns=this.fieldOwner();return html`<en-select id=${id} label=${label} .value=${this.fieldValue(id,value)} @en-change=${(e:Event)=>{if(owns())this.value(e,set);}}>${options.map(([v,l])=>html`<en-select-option value=${v}>${l}</en-select-option>`)}</en-select>`;}
 private touch(domain=true){if(!this.c||!this.base)return;if(domain){if(!this.dirty||this.c.review)this.c.id=crypto.randomUUID();this.c.review=null;this.dirty=true;this.exact='';this.projection=false;this.message='Unapplied Composition draft.';}this.generation++;this.issues=[];this.save();this.changed();}
 private save(){if(!this.c||!this.base)return;const value={composition:this.c,bindings:this.bindings,selected:this.selected,numbers:this.numbers,color:this.color,view:this.view,guides:this.guides,rawText:this.convertText,rawIndex:this.rawIndex,rawOffset:this.rawOffset},lease=reservePromptPayload('composition-draft-serialize',jsonPayloadUnits(value)*2);try{this.editor.changeDraft(this.draftId,'composition',JSON.stringify(value),null,this.composing,this.base.revision);}finally{lease.release();}}
 private moveGuides=false;private drag:{id:number;start:readonly[number,number];point:readonly[number,number];element:SemanticElement;geometry:Geometry;generation:number;revision:string;release:()=>void}|null=null;
 get dragging(){return this.drag!==null;}
 cancelDrag(){this.drag?.release();this.drag=null;this.draw();}
 pointerDown(ev:PointerEvent,p:readonly[number,number]){const e=this.selectedElement();if(this.disposed||this.releasePending||this.refusedControl||!this.moveGuides||this.view!=='composition'||!this.guides||ev.button!==0||ev.defaultPrevented||!e||e.bounds?.mode!=='literal')return false;this.admitMutation();const release=this.pinPayloads();try{this.drag?.release();this.drag={id:ev.pointerId,start:p,point:p,element:e,geometry:structuredClone(e.bounds.value),generation:this.generation,revision:this.editor.view.document!.revision,release};(ev.target as HTMLElement).setPointerCapture(ev.pointerId);return true;}catch(error){this.drag=null;release();throw error;}}
 pointerMove(ev:PointerEvent,p:readonly[number,number]){if(!this.drag||ev.pointerId!==this.drag.id)return false;if(!ev.defaultPrevented)this.drag.point=p;this.draw();return true;}
 private translated(g:Geometry,x:number,y:number){const next=structuredClone(g),m=inverseAffine(g.transform);next.rect[0]+=m[0]*x+m[2]*y;next.rect[1]+=m[1]*x+m[3]*y;return next;}
 pointerUp(ev:PointerEvent,p:readonly[number,number]){const g=this.drag;if(!g||g.id!==ev.pointerId)return false;this.drag=null;let live=true;const done=()=>{if(live){live=false;g.release();}};const timer=setTimeout(()=>{this.queuedActions.delete(timer);try{if(!live||this.disposed||this.releasePending||ev.defaultPrevented||g.generation!==this.generation||g.revision!==this.editor.view.document?.revision||g.element!==this.selectedElement()){this.draw();return;}this.admitMutation();g.element.bounds={mode:'literal',value:this.translated(g.geometry,p[0]-g.start[0],p[1]-g.start[1])};for(const k of Object.keys(this.numbers))if(k.startsWith('semantic-'+g.element.id+'-'))delete this.numbers[k];this.touch();}catch(error){this.error(error);}finally{done();}},0);this.queuedActions.set(timer,done);return true;}
 private boxKey(ev:KeyboardEvent){if(this.disposed||this.releasePending||this.refusedControl||ev.defaultPrevented||ev.isComposing||ev.metaKey||ev.ctrlKey||ev.altKey||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(ev.key))return;const e=this.selectedElement();if(e?.bounds?.mode!=='literal')return;ev.preventDefault();try{this.admitMutation();const n=ev.shiftKey?10:1;e.bounds.value=this.translated(e.bounds.value,ev.key==='ArrowLeft'?-n:ev.key==='ArrowRight'?n:0,ev.key==='ArrowUp'?-n:ev.key==='ArrowDown'?n:0);for(const k of Object.keys(this.numbers))if(k.startsWith('semantic-'+e.id+'-'))delete this.numbers[k];this.touch();}catch(error){this.error(error);}}
 private selectedElement(){return this.c?.elements.find(e=>e.id===this.selected);}
 // These spans end at local function return; neither DOM update nor presented
 // pixels are implied. The serializer includes its own bounds projections.
 private phaseContext(){return {documentId:this.base?.id,revision:this.base?.revision,correlationId:this.c?.id??this.draftId};}
 private parseLocal(raw:Uint8Array,slot='raw-result',source?:BlobRef){
  const span=browserPhases.recorder.start('composition.parse',{...this.phaseContext(),bytes:raw.byteLength});
  try{const result=this.adopt(slot,parseCompositionValue(raw,source));span.end(result.state==='supported'?'ok':'rejected',{count:result.value?.compositional_deconstruction.elements.length??0});return result;}catch(error){span.end('error');throw error;}
 }
 private serializeLocal(c:Composition){
  const span=browserPhases.recorder.start('composition.serialize',{...this.phaseContext(),correlationId:c.id,count:c.elements.length});
  try{const result=serializeCompositionValue(c,this.layers,this.bindings);span.end('incomplete',{boundary:'observed'});return result;}catch(error){span.end(error instanceof CompositionError?'rejected':'error');throw error;}
 }
 private projectLocal(...args:Parameters<typeof projectBounds>){
  const span=browserPhases.recorder.start('composition.project',{...this.phaseContext(),count:1});
  try{const result=this.adopt(this.renderDepth?'render-box-projection':'box-projection',projectCompositionValue(...args));span.end('ok');return result;}catch(error){span.end(error instanceof CompositionError?'rejected':'error');throw error;}
 }
 private sameSyncDocument(a:SyncOwner,b:SyncOwner){return a.connection===b.connection&&a.identity===b.identity&&a.owner===b.owner&&a.session===b.session&&a.document===b.document&&a.fieldEpoch===b.fieldEpoch;}
 private sameSyncOwner(a:SyncOwner|null,b:SyncOwner){return !!a&&this.sameSyncDocument(a,b)&&a.revision===b.revision&&a.documentEpoch===b.documentEpoch&&a.recovery===b.recovery;}
 private syncCurrent(scope:SyncOwner){return !this.disposed&&!this.releasePending&&this.editor.view.ready&&this.fieldEpoch===scope.fieldEpoch&&this.syncRecovery===scope.recovery&&this.editor.session===scope.connection&&scope.connection.identity()===scope.identity&&this.editor.draftOwner===scope.owner&&this.editor.sessionId===scope.session&&this.editor.documentEpoch===scope.documentEpoch&&this.editor.view.document?.id===scope.document&&this.editor.view.document.revision===scope.revision;}
 sync(){
  if(this.disposed||this.releasePending)return Promise.resolve();
  // Recovery has its own retry boundary. Status, focus and layout publications
  // must not turn a refused read into a render-driven request loop.
  if(!this.editor.view.ready){this.syncFailure=null;this.syncRecovery++;return Promise.resolve();}
  const document=this.editor.view.document;if(!document){this.syncFailure=null;return Promise.resolve();}
  const scope:SyncOwner={connection:this.editor.session,identity:this.editor.session.identity(),owner:this.editor.draftOwner,session:this.editor.sessionId,document:document.id,revision:document.revision,documentEpoch:this.editor.documentEpoch,fieldEpoch:this.fieldEpoch,recovery:this.syncRecovery};
  if(this.sameSyncOwner(this.syncFailure,scope))return Promise.resolve();
  this.syncFailure=null;
  return this.watch(async()=>{try{await this.syncOwned(scope);}catch(error){if(this.loadingSync===scope&&this.syncCurrent(scope))this.syncFailure=scope;throw error;}});
 }
 private async syncOwned(scope:SyncOwner){
  if(!this.syncCurrent(scope)||this.refusedControl)return;
  const retry=this.restoreRetry,restoreAgain=!!retry&&this.sameSyncDocument(retry.scope,scope)&&retry.model.deref()===this.c&&retry.generation===this.generation&&!this.dirty;
  if(retry&&!restoreAgain)this.restoreRetry=null;
  const session=scope.session,owner=scope.owner,key=session+':'+scope.document+':'+scope.revision;
  if(this.key===key&&this.ownsModel()&&!restoreAgain||this.loading===key&&this.loadingOwner===owner&&this.sameSyncOwner(this.loadingSync,scope))return;
  this.loading=key;this.loadingOwner=owner;this.loadingSync=scope;const read=++this.loadingRead,generation=this.generation,epoch=this.fieldEpoch,owns=()=>this.loadingRead===read&&this.loading===key&&this.syncCurrent(scope);
  let snapshot:OwnedCompositionValue<DocumentBase>|undefined,releaseUI=()=>{};
  try{snapshot=this.captureBase();if(!snapshot)return;const d=snapshot.value,documentId=d.id;
   if(!this.c&&!this.base&&!this.modeAdmission)this.modeAdmission={epoch:this.fieldEpoch,connection:this.editor.session,identity:this.editor.session.identity(),documentId:d.id,sessionId:this.editor.sessionId,owner:this.editor.draftOwner};
  const pins:(()=>void)[]=[];let incoming:OwnedCompositionValue<View>|undefined,draft:OwnedCompositionValue<Composition>|undefined,nextBase:OwnedCompositionValue<DocumentBase>|undefined,registration:(()=>void)|undefined;try{incoming=await this.readJSON<View>('/api/v1/documents/'+d.id+'/composition?revision='+d.revision,owns,'accepted');const value=incoming.value;if(!owns()||this.refusedControl)return;while(this.settlements.size){await Promise.all(this.settlements);if(!owns()||this.refusedControl)return;}if(!owns()||this.refusedControl)return;
   const restoringOwner=!this.ownsModel()||restoreAgain,replace=restoringOwner||!this.dirty&&!this.committing;
   let prepared:{bindings:Record<string,string>;draftId:string;numbers:Record<string,string>;selected:string}|undefined;
   if(replace){
    // Admission can refuse after the response has arrived. Keep the old model,
    // owner predicate and retry key intact until every successor copy is ready.
    draft=value.composition?cloneCompositionValue(value.composition):createCompositionValue('composition-empty-model',4096,()=>emptyComposition(d.width,d.height,crypto.randomUUID()));
    const selected=draft.value.elements.some(e=>e.id===this.selected)?this.selected:'';
    draft.owner.resize(compositionPayloadBytes({composition:draft.value,bindings:value.bindings,numbers:{},rawText:'',color:this.color,selected})+4096);
    nextBase=this.copyBase(d);prepared={bindings:{...value.bindings},draftId:crypto.randomUUID(),numbers:{},selected};this.owners.ensure(9);registration=this.editor.registerDraft(prepared.draftId,d.id);
   }
   pins.push(incoming.owner.pin());this.adopt('view',incoming);incoming=undefined;this.layers=value.layers;this.releasePayload('layers');this.accepted=value.composition;this.releasePayload('accepted');this.key=key;
   if(prepared){this.drag?.release();this.drag=null;this.modeReady=()=>false;this.rawRead++;this.rawText='';this.rawResult=null;this.rawInspected='';this.rawIndex=0;this.rawOffset=0;this.convertOpen=false;this.sourceRaw=null;this.convertText='';this.dirty=false;this.c=this.adopt('draft',draft!,registration);registration=undefined;draft=undefined;this.bindings=prepared.bindings;this.base=this.adopt('base',nextBase!);nextBase=undefined;this.draftId=prepared.draftId;this.numbers=prepared.numbers;this.selected=prepared.selected;this.ownsModel=()=>this.fieldEpoch===epoch&&this.editor.sessionId===session&&this.editor.draftOwner===owner&&this.editor.view.document?.id===documentId;this.exact='';this.projection=false;
    releaseUI=this.editor.pinUI();const saved=this.editor.ui?.drafts.find(x=>x.kind==='composition'&&x.documentId===d.id&&x.status==='saved-unapplied');
    if(restoringOwner&&saved){this.restoreRetry={scope,model:new WeakRef(this.c!),generation:this.generation};const restoredOwned=await this.readJSON<any>('/api/v1/ui/'+this.editor.sessionId+'/composition?draftId='+saved.id+'&generation='+saved.generation,owns,'draft');let transferred=false;try{const restored=restoredOwned.value;if(!owns()||this.refusedControl)return;while(this.settlements.size){await Promise.all(this.settlements);if(!owns()||this.refusedControl)return;}if(!owns()||this.refusedControl)return;if(generation!==this.generation){this.modeReady=this.ownsModel;this.saveMode();return;}const graph=restored.graph;this.owners.ensure(8);const registration=this.editor.registerDraft(saved.id,d.id);let restoredBase:OwnedCompositionValue<DocumentBase>;try{restoredBase=this.copyBase(d,saved.expectedDocumentRevision);}catch(error){registration();throw error;}this.adopt('draft',restoredOwned,registration);transferred=true;this.c=graph.composition;this.bindings=restored.bindings;this.selected=graph.selected??'';this.numbers=graph.numbers??{};this.color=graph.color??this.color;this.view=this.modeIntent?.owns()?this.modeIntent.value:graph.view??'composition';this.guides=graph.guides!==false;this.convertText=graph.rawText??'';this.rawIndex=graph.rawIndex??0;this.rawOffset=graph.rawOffset??0;this.base=this.adopt('base',restoredBase);this.draftId=saved.id;this.dirty=true;this.message='Recovered Composition draft. Review the current document before Apply.';}finally{if(!transferred)restoredOwned.owner.release();}}
    if(owns())this.restoreRetry=null;
    this.modeReady=this.ownsModel;this.saveMode();this.changed();
    if(this.c?.raw.length){this.rawIndex=Math.min(this.rawIndex,this.c.raw.length-1);await this.rawPage(0);}
   }
   if(owns()){this.syncFailure=null;this.changed();}
  }catch(e){if(owns()||e instanceof PromptReaderCleanupError||e instanceof CompositionReadCleanupError)throw e;}finally{registration?.();nextBase?.owner.release();draft?.owner.release();incoming?.owner.release();for(const unpin of pins)unpin();}
  }catch(error){if(this.loadingSync===scope&&this.syncCurrent(scope))this.syncFailure=scope;throw error;}finally{try{releaseUI();}finally{try{snapshot?.owner.release();}finally{if(this.loadingRead===read)this.loading='';}}}
 }
 private validate(){if(!this.c||!this.base)throw Error('Open a document first.');if(this.composing)throw Error('Finish text composition before Apply.');for(const [path,v]of Object.entries(this.numbers))if(!v.trim()||!Number.isFinite(Number(v)))throw new CompositionError([{path,code:'NUMBER_REQUIRED',message:'Enter a finite number. Your draft is retained.'}]);const scratch=reservePromptPayload('composition-validate-scratch',jsonPayloadUnits(this.c)*8);try{validateComposition(this.c);}finally{scratch.release();}if(this.c.frame.documentWidth!==this.base.width||this.c.frame.documentHeight!==this.base.height)throw new CompositionError([{path:'frame',code:'FRAME_CHANGED',message:'Review the changed document frame explicitly before projection.'}]);if(this.editor.view.document?.id!==this.base.id||this.editor.view.document.revision!==this.base.revision)throw Error('The document changed. Review the current document before Apply.');}
 private current(){return this.watch(()=>this.currentOwned());}
 private async currentOwned(){
  const snapshot=this.captureBase();if(!snapshot)throw Error('Open a document.');const d=snapshot.value;
  try{
  const intent=++this.reviewIntent,c=this.c,generation=this.generation,draftId=this.draftId,owner=this.editor.draftOwner,session=this.editor.sessionId;
  const owns=()=>intent===this.reviewIntent&&this.c===c&&this.generation===generation&&this.draftId===draftId&&this.editor.draftOwner===owner&&this.editor.sessionId===session&&this.editor.view.document?.id===d.id&&this.editor.view.document.revision===d.revision;
  const unpin=this.pinPayloads();let next:OwnedCompositionValue<View>|undefined,nextBase:OwnedCompositionValue<DocumentBase>|undefined;try{next=await this.readJSON<View>('/api/v1/documents/'+d.id+'/composition?revision='+d.revision,owns,'accepted');const v=next.value;if(!owns())return;if(v.revision!==d.revision)throw Error('Document changed during review.');
   this.owners.ensure(8);nextBase=this.copyBase(d);this.adopt('layers',next);next=undefined;this.layers=v.layers;this.base=this.adopt('base',nextBase);nextBase=undefined;if(c){c.frame.documentWidth=d.width;c.frame.documentHeight=d.height;c.frame.revision=crypto.randomUUID();}this.touch();this.message='Current document reviewed. Each stale field still needs explicit relink or detach.';
  }catch(e){if(owns()||e instanceof PromptReaderCleanupError||e instanceof CompositionReadCleanupError)throw e;}finally{nextBase?.owner.release();next?.owner.release();unpin();}
  }finally{snapshot.owner.release();}
 }

 private async flushOwnDraft(){for(let i=0;i<3;i++){await this.editor.flushDrafts();const saved=this.editor.draftOwner?.drafts.get(this.draftId);if(saved&&saved.savedGeneration===saved.generation)return saved;}throw Error('Draft still changing. Wait for local save before continuing.');}
 private commit(type:CompositionCommand='CommitCompositionVersion'){return this.watch(()=>this.commitOwned(type));}
 private async commitOwned(type:CompositionCommand='CommitCompositionVersion'){
  this.validate();const c=this.c!,base=this.base!,g=this.generation,unpin=this.pinPayloads();let staged:Awaited<ReturnType<EditorClient['ownedStageTextBlob']>>|undefined;this.committing=true;
  try{this.save();await this.flushOwnDraft();if(g!==this.generation||this.c!==c)throw Error('Composition changed while saving. Apply the current draft.');const saved=this.editor.draftOwner?.drafts.get(this.draftId);if(!saved||saved.savedGeneration!==saved.generation)throw Error('Wait for the draft to save, then Apply.');const serialization=reservePromptPayload('composition-commit-copy',jsonPayloadUnits(c)*18);try{staged=await this.editor.ownedStageTextBlob(new Blob([canonical(c)]),'application/json','text',()=>g===this.generation&&this.c===c);}finally{serialization.release();}if(g!==this.generation||this.editor.view.document?.revision!==base.revision)throw Error('Composition or document changed. The saved draft is retained.');await this.editor.withCommandEvents({type,composition:{id:c.id,value:staged.value,bindings:this.bindings},draft:{sessionId:this.editor.sessionId,draftId:this.draftId,generation:saved.generation}},()=>undefined,base);
   if(g===this.generation){
    let accepted:OwnedCompositionValue<Composition>|undefined=cloneCompositionValue(c),nextBase:OwnedCompositionValue<DocumentBase>|undefined;
    try{nextBase=this.captureBase();if(!nextBase)throw Error('The document changed. The saved draft is retained.');const draftId=crypto.randomUUID();this.owners.ensure(9);const registration=this.editor.registerDraft(draftId,nextBase.value.id);let draft:CompositionPayload;try{draft=compositionAllowance('composition-draft',compositionPayloadBytes(this.draftPayload())+4096);}catch(error){registration();throw error;}this.adopt('draft',{value:c,owner:draft},registration);
     this.accepted=this.adopt('accepted',accepted);accepted=undefined;this.base=this.adopt('base',nextBase);nextBase=undefined;this.dirty=false;this.draftId=draftId;this.message=type==='ApprovePromptProjection'?'Local request draft reviewed and saved. No provider request was made.':'Composition applied and saved locally.';
    }finally{accepted?.owner.release();nextBase?.owner.release();}
   }
  }finally{staged?.release();unpin();this.committing=false;this.changed();}
 }
 private preview(){this.validate();const result=this.adopt('projection',this.serializeLocal(this.c!));this.exact=result.prompt;this.projection=true;this.messageValue=this.adopt('message',createCompositionValue('composition-message',512,()=>`Local draft: ${bytes(result.prompt)} UTF-8 bytes; ${result.wirePromptBytes} escaped prompt bytes. Bounding boxes are soft guidance.`));this.changed();}
 private approve(){return this.watch(()=>this.approveOwned());}
 private async approveOwned(){this.validate();if(!this.projection)throw Error('Preview the current request draft first.');const c=this.c!,g=this.generation,owned=this.serializeLocal(c),result=owned.value,unpin=this.pinPayloads();let blob:ReturnType<typeof reservePromptPayload>|undefined,prompt:Awaited<ReturnType<EditorClient['ownedStageTextBlob']>>|undefined;try{blob=reservePromptPayload('composition-prompt-blob',bytes(result.prompt));prompt=await this.editor.ownedStageTextBlob(new Blob([result.prompt]),'text/plain','text',()=>g===this.generation&&this.c===c);if(g!==this.generation||this.c!==c)throw Error('Projection changed during preparation.');this.admitMutation(compositionPayloadBytes(result)+compositionPayloadBytes(c.frame)+compositionPayloadBytes(c.request)+compositionPayloadBytes(prompt.value)+4096);c.id=crypto.randomUUID();c.review=structuredClone({serializer:'caption-json-1' as const,sourceId:c.id,frame:c.frame,request:c.request,dependencies:result.dependencies,boxes:result.boxes,prompt:prompt.value});this.dirty=true;await this.commit('ApprovePromptProjection');}finally{prompt?.release();blob?.release();owned.owner.release();unpin();}}
 private add(type:SemanticElement['type']){if(!this.c)return;if(this.c.elements.length>=256)throw Error('At most 256 semantic elements can be retained in one Composition.');this.admitMutation(4096);const e=emptyElement(type,crypto.randomUUID());this.c.elements.push(e);this.selected=e.id;this.inspect();this.touch();}
 private remove(){const c=this.c!,i=c.elements.findIndex(e=>e.id===this.selected);c.elements.splice(i,1);this.selected=c.elements[Math.min(i,c.elements.length-1)]?.id??'';this.touch();this.focusAfter(()=>this.host.querySelector<HTMLElement>(this.selected?'#semantic-tree':'#add-semantic-object')?.focus());}
 private move(delta:number){const es=this.c!.elements,i=es.findIndex(e=>e.id===this.selected),j=i+delta;if(j<0||j>=es.length)return;[es[i],es[j]]=[es[j],es[i]];this.touch();}
 private pruneBindings(){if(this.c){const ids=bindingIds(this.c);this.bindings=Object.fromEntries(ids.map(id=>[id,this.bindings[id]??id]));}}
 private bind(field:'desc'|'text'|'bounds'){const e=this.selectedElement(),l=this.layers.find(l=>l.id===this.layerChoice);if(!e||!l)throw Error('Choose a native layer, then explicitly link the field.');this.admitMutation(compositionPayloadBytes(l)+4096);const b=linkField<any>(field==='text'?'text-content':field==='desc'?'appearance-description':'frame-bounds',l);(e as any)[field]=b;this.bindings[l.id]=l.id;this.pruneBindings();this.touch();}
 private binding(field:'desc'|'text'|'bounds',label:string){const e=this.selectedElement()!,b=e[field],status=b?fieldStatus(b,this.layers,this.bindings):'omitted';return html`<en-card><h3>${label}</h3><en-badge>${status}</en-badge>${b?.mode==='layer'?html`<p>Layer ${this.editor.view.image?.layers.find(l=>l.id===this.bindings[b.layerId])?.name??this.bindings[b.layerId]} · last reviewed version ${b.lastReviewedLayerVersion}</p><en-button variant="secondary" @click=${this.action(()=>{this.admitMutation(compositionPayloadBytes(b)+4096);(e as any)[field]=detach(b as Binding<any>);this.pruneBindings();this.touch();})}>Detach ${label} as last reviewed literal</en-button><en-button variant="secondary" @click=${this.action(()=>{this.revealNative(this.bindings[b.layerId]);})}>Reveal linked layer</en-button>`:nothing}<en-button variant="secondary" @click=${this.action(()=>this.bind(field))}>Link ${label}</en-button></en-card>`;}
 private retainTyped(){return this.watch(()=>this.retainTypedOwned());}
 private async retainTypedOwned(){const value=this.convertText,lease=reservePromptPayload('composition-raw-blob',bytes(value));try{await this.retain(new Blob([value]));}finally{lease.release();}}
 private retain(file:Blob){return this.watch(()=>this.retainOwned(file));}
 private async retainOwned(file:Blob){
  if(!this.c)throw Error('Open a document.');if(this.c.raw.length>=256)throw Error('At most 256 originals can be retained in one Composition.');
  const c=this.c,g=this.generation,unpin=this.pinPayloads();let staged:Awaited<ReturnType<EditorClient['ownedStageTextBlob']>>|undefined;
  try{staged=await this.editor.ownedStageTextBlob(file,'application/octet-stream','text',()=>g===this.generation&&c===this.c);const ref=staged.value;if(g!==this.generation||c!==this.c)throw Error('The draft changed. Original staged bytes remain retained.');
   const page=await readCompositionBlob(file,32768);try{if(g!==this.generation||c!==this.c)return;this.rawText=this.adopt('raw-page',createCompositionValue('composition-raw-page',page.value.byteLength*2,()=>new TextDecoder('utf-8',{ignoreBOM:true}).decode(page.value)));compositionObservations.page(ref,0,page.value.byteLength);}finally{page.owner.release();}
   const raw=await readCompositionBlob(file,262145);try{if(g!==this.generation||c!==this.c)return;this.rawResult=this.parseLocal(raw.value,'raw-result',ref);}finally{raw.owner.release();}
   this.admitMutation(compositionPayloadBytes(ref)+4096);const retained=structuredClone(ref);c.raw.push(retained);this.sourceRaw=retained;this.rawIndex=c.raw.length-1;this.rawOffset=0;this.rawInspected=ref.hash;this.touch();await this.flushOwnDraft();if(g+1!==this.generation||c!==this.c)return;this.message='Original bytes retained separately. Inspection grants no authoring authority.';this.changed();
  }finally{staged?.release();unpin();}
 }
 private rawPath(){const local=this.editor.draftOwner?.drafts.get(this.draftId),saved=local?.savedGeneration?{id:this.draftId,generation:local.savedGeneration}:this.editor.ui?.drafts.find(d=>d.id===this.draftId);return saved?'/api/v1/ui/'+this.editor.sessionId+'/composition?draftId='+saved.id+'&generation='+saved.generation:'/api/v1/documents/'+this.base!.id+'/composition?revision='+this.editor.view.document!.revision;}
 private async downloadRaw(){const ref=this.c?.raw[this.rawIndex];if(!ref)throw Error('Retain raw bytes first.');const chosen=chooseDestination('caption-original.bin');const status=await writeDestination({path:this.rawPath()+'&raw='+this.rawIndex+'&download=1',name:'caption-original.bin',hash:ref.hash,bytes:ref.byteLength},this.editor.session.transport,chosen);this.message=status==='confirmed'?'Original bytes saved to the chosen destination.':'Original-byte download started; destination remains unconfirmed.';this.changed();}
 private rawPage(delta:number){return this.watch(()=>this.rawPageOwned(delta));}
 private async rawPageOwned(delta:number){
  const owner=this.fieldOwner();if(!owner()||!this.c?.raw.length)return;this.rawOffset=Math.max(0,this.rawOffset+delta*32768);const source=this.c.raw[this.rawIndex];if(this.rawOffset>=Number(source.byteLength))this.rawOffset=Math.max(0,Math.floor((Number(source.byteLength)-1)/32768)*32768);
  const token=++this.rawRead,path=this.rawPath(),index=this.rawIndex,offset=this.rawOffset,inspect=this.rawInspected!==source.hash,owns=()=>owner()&&token===this.rawRead&&this.c?.raw[index]?.hash===source.hash&&this.rawIndex===index&&this.rawOffset===offset;this.rawText='';this.releasePayload('raw-page');if(inspect){this.rawResult=null;this.releasePayload('raw-result');}
  const unpin=this.pinPayloads();let page:OwnedCompositionValue<Uint8Array>|undefined;
  try{page=await this.readBytes(path+'&raw='+index+'&offset='+offset,32768,owns);if(!owns())return;let result=this.rawResult;
   if(inspect){if(BigInt(source.byteLength)>262144n){result=this.adopt('raw-result',createCompositionValue<ParseResult>('composition-parse-model',4096,()=>({state:'over-limit',issues:[{path:'$',code:'BYTE_LIMIT',message:'Raw retained. Parsing is limited to 256 KiB.'}]})));compositionObservations.parsed(0,result,source);}else{const raw=await this.readBytes(path+'&raw='+index+'&download=1',262144,owns);try{if(!owns())return;result=this.parseLocal(raw.value,'raw-result',source);}finally{raw.owner.release();}}}
   if(!owns())return;const bytes=page.value;this.rawText=this.adopt('raw-page',createCompositionValue('composition-raw-page',bytes.byteLength*2,()=>new TextDecoder('utf-8',{ignoreBOM:true}).decode(bytes)));compositionObservations.page(source,offset,bytes.byteLength);this.rawResult=result;this.rawInspected=source.hash;this.changed();
  }catch(e){if(owns()||e instanceof PromptReaderCleanupError||e instanceof CompositionReadCleanupError)throw e;}finally{page?.owner.release();unpin();}
 }
 private parseText(value:string){const raw=encodeCompositionText(value);try{return this.parseLocal(raw.value,'convert-result');}finally{raw.owner.release();}}
 private async convert(){
  const epoch=this.fieldEpoch,generation=this.generation;await this.dialogs();if(epoch!==this.fieldEpoch||generation!==this.generation||this.releasePending)return;return this.watch(()=>this.convertOwned());
 }
 private async convertOwned(){
  const owns=this.fieldOwner(),source=this.c?.raw[this.rawIndex]??null,index=this.rawIndex,path=source?this.rawPath():'';if(!source)throw Error('Retain original raw input first.');const unpin=this.pinPayloads();try{
  if(!owns())return;this.sourceRaw=source;this.convertOpen=true;this.convertText='';this.releasePayload('convert-text');
  if(BigInt(source.byteLength)<=262144n){const raw=await this.readBytes(path+'&raw='+index+'&download=1',262144,owns);try{if(!owns()||this.sourceRaw!==source)return;try{this.convertText=this.adopt('convert-text',createCompositionValue('composition-convert-text',raw.value.byteLength*2,()=>new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(raw.value)));}catch(error){if(!(error instanceof TypeError))throw error;this.message='Invalid UTF-8 original retained. Author a separate valid conversion copy.';}}finally{raw.owner.release();}}
  if(!owns()||this.sourceRaw!==source)return;this.convertResult=this.parseText(this.convertText);this.changed();}finally{unpin();}
 }
 private convertCopy(){return this.watch(()=>this.convertCopyOwned());}
 private async convertCopyOwned(){
  if(!this.c||!this.sourceRaw||!this.convertResult?.value)throw Error('Correct the conversion copy and review its field errors first.');const current=this.c,caption=this.convertResult.value;
  const owned=createCompositionValue('composition-converted-model',compositionPayloadBytes(current)+compositionPayloadBytes(caption)*2+262144,()=>{const next=fromCaption(caption,current.frame,crypto.randomUUID(),()=>crypto.randomUUID());next.raw=[...current.raw];next.request=structuredClone(current.request);return next;});
  const next=this.adopt('draft',owned);this.c=next;this.bindings={};this.selected=next.elements[0]?.id??'';this.convertOpen=false;this.admitMutation(this.convertText.length*2+4096);this.touch();await this.commit();this.inspect();
 }
 private palette(){const owns=this.fieldOwner(),c=this.c!,e=this.selectedElement(),style=this.paletteTarget==='style',palette=style?c.style?.palette:e?.palette;const assign=(p:string[]|null)=>{if(style){if(!c.style)throw Error('Enable Style first.');c.style.palette=p;}else{if(!e)throw Error('Select a semantic element.');e.palette=p;}this.touch();};return html`<en-accordion><en-accordion-item value="palette"><span slot="heading">Caption palette</span>${this.choice('Palette scope',this.paletteTarget,[['element','Selected element'],['style','Overall style']],v=>{this.paletteTarget=v;})}<en-color-field id="composition-color-chooser" label="sRGB color chooser" .value=${this.fieldValue('composition-color-chooser',/^#[0-9A-Fa-f]{6}$/.test(this.color)?this.color:'#336699')} @en-change=${(ev:Event)=>{if(owns())this.value(ev,v=>{this.color=v;this.conversion=null;});else ev.preventDefault();}}></en-color-field><en-text-field id="composition-color-draft" label="Color draft including alpha or Display P3" .value=${this.fieldValue('composition-color-draft',this.color)} @en-input=${(ev:Event)=>{if(owns())this.input(ev,v=>{this.color=v;this.conversion=null;});else ev.preventDefault();}}></en-text-field><en-button variant="secondary" @click=${this.action(()=>{const scratch=compositionAllowance('composition-color-scratch',65536+this.color.length*16);try{const p=parseColor(this.color);if(!p)throw Error('Choose a supported color.');const result=exportSRGB(p),hex='#'+result.color.channels.map(x=>Math.round(x*255).toString(16).padStart(2,'0')).join('').toUpperCase();this.conversion=this.adopt('conversion',cloneCompositionValue({hex,clipped:result.clipped,alpha:p.alpha}));this.changed();}finally{scratch.release();}})}>Preview opaque sRGB color</en-button>${this.conversion?html`<en-alert>Use ${this.conversion.hex}; alpha ${this.conversion.alpha} becomes 1. ${this.conversion.clipped?'Out-of-gamut channels are clipped.':'No gamut clipping.'} Original color draft is retained.</en-alert><en-button @click=${this.action(()=>{if((palette?.length??0)>=(style?16:5))throw Error('Palette limit reached.');assign([...(palette??[]),this.conversion!.hex]);this.conversion=null;})}>Apply color to palette</en-button>`:nothing}${(palette??[]).map((p,i)=>html`<en-stack direction="horizontal" wrap><en-badge>${p}</en-badge><en-button variant="ghost" @click=${this.action(()=>assign(palette!.filter((_,j)=>j!==i)))}>Remove color ${i+1}</en-button><en-button variant="ghost" ?disabled=${i===0} @click=${this.action(()=>{const a=[...palette!];[a[i-1],a[i]]=[a[i],a[i-1]];assign(a);})}>Move color ${i+1} earlier</en-button></en-stack>`)}<en-button variant="ghost" @click=${this.action(()=>assign(palette===null?[]:null))}>${palette===null?'Enable empty palette':'Omit palette'}</en-button></en-accordion-item></en-accordion>`;}
 request(){return this.render('request',()=>this.requestOwned());}
 private requestOwned(){const c=this.c,owns=this.fieldOwner();return html`<en-segmented-control id="composition-mode" label="Prompt source" .value=${this.fieldValue('composition-mode',this.view)} .items=${[{value:'plain',label:'Plain prompt'},{value:'composition',label:'Composition'}]} @en-change=${this.modeSelection()}></en-segmented-control><section class="composition-editor" @compositionstart=${()=>{if(owns())this.compositionState(true);}} @compositionend=${()=>{if(owns())this.compositionState(false);}} ?hidden=${this.view!=='composition'}><h2>Composition</h2>${!c?html`<p>Open a document to author Composition.</p>`:html`
 <en-badge>${this.c?.review?(this.c.frame.documentWidth!==this.base?.width||this.c.frame.documentHeight!==this.base?.height||this.c.elements.some(e=>[e.desc,e.text,e.bounds].some(b=>b?.mode==='layer'&&fieldStatus(b,this.layers,this.bindings)!=='reviewed'))?'Local projection needs review':'Local projection reviewed'):'Local projection not approved'}</en-badge><en-alert announcement="none">Semantic elements are independent of Layers. Selection never creates a link.</en-alert>
 ${this.text('composition-scene','Scene',c.scene,v=>c.scene=v)}
 ${this.choice('Style',c.style?.kind??'none',[['none','No style'],['photo','Photography'],['art','Art']],v=>{this.admitMutation(compositionPayloadBytes(c.style)+compositionPayloadBytes(c.inactiveStyle)+4096);if(c.style)c.inactiveStyle=structuredClone(c.style);c.style=v==='none'?null:{...structuredClone(c.inactiveStyle),kind:v as 'photo'|'art'};},'composition-style')}
 <div ?hidden=${!c.style}>${c.style?html`${this.text('composition-aesthetics','Aesthetics',c.style.aesthetics,v=>c.style!.aesthetics=v)}${this.text('composition-lighting','Lighting',c.style.lighting,v=>c.style!.lighting=v)}${this.text('composition-medium','Medium',c.style.medium,v=>c.style!.medium=v)}${c.style.kind==='photo'?this.text('composition-photo','Photography description',c.style.photo,v=>c.style!.photo=v):this.text('composition-art','Art style',c.style.artStyle,v=>c.style!.artStyle=v)}`:nothing}</div>
 ${this.text('composition-background','Background',c.background,v=>c.background=v)}
 <h3>Local request draft</h3><p>Operation: ${c.request.operation}. Authored content is retained below; nothing has been submitted and no returned or expanded prompt exists.</p>${this.choice('Prompt expansion',c.request.expansion,[['None','None — recommended'],['Medium','Medium'],['Large','Large']],v=>{c.request.expansion=v as Composition['request']['expansion'];c.request.rewriteAcknowledged=false;},'composition-expansion')}${c.request.expansion!=='None'?html`<en-alert>Provider expansion may rewrite structure or placement. Large is unavailable for Fast and Instant.</en-alert><en-switch label="Acknowledge possible expansion rewrite" .checked=${c.request.rewriteAcknowledged} @en-change=${(ev:Event)=>{if(!owns()){ev.preventDefault();return;}const h=ev.currentTarget as HTMLElement&{checked:boolean};this.settleControl(ev,()=>h.checked,v=>{c.request.rewriteAcknowledged=v;this.touch();});}}></en-switch>`:html`<p>None requests preservation of caption structure. Forwarding and model fidelity remain unverified.</p>`}
 <h3>Semantic elements</h3><en-tree id="semantic-tree" label="Composition elements" .items=${c.elements.map((e,i)=>({key:e.id,label:`${i+1}. ${e.type==='text'?'Text':'Object'} · ${bindingValue(e.desc).slice(0,60)||'Untitled'}${e.excluded?' · excluded':''}`}))} .selectedKeys=${this.selected?[this.selected]:[]} @en-change=${(ev:Event)=>{if(!owns()){ev.preventDefault();return;}const host=ev.currentTarget as HTMLElement&{selectedKeys:string[]};this.settleControl(ev,()=>host.selectedKeys[0]??'',v=>{this.selected=v;this.inspect();this.touch(false);});}}></en-tree>
 <en-stack direction="horizontal" wrap><en-button id="add-semantic-object" @click=${this.action(()=>this.add('obj'))}>Add object</en-button><en-button @click=${this.action(()=>this.add('text'))}>Add semantic text</en-button></en-stack><p>${c.elements.length}/256 semantic elements; ${this.editor.view.image?.layers.length??0} native layers.</p>
 <en-accordion><en-accordion-item value="frame"><span slot="heading">Request frame and guides</span>${this.choice('Request dimensions',c.frame.width===null?'auto':'explicit',[['explicit','Explicit size'],['auto','Unresolved auto']],v=>{c.frame.width=v==='auto'?null:this.base!.width;c.frame.height=v==='auto'?null:this.base!.height;c.frame.revision=crypto.randomUUID();},'request-dimensions')}${c.frame.width!==null?html`<div class="composition-numbers">${this.number('request-width','Request width',c.frame.width,v=>{c.frame.width=v;c.frame.revision=crypto.randomUUID();})}${this.number('request-height','Request height',c.frame.height!,v=>{c.frame.height=v;c.frame.revision=crypto.randomUUID();})}</div>`:nothing}<p>Document → request affine map: crop, padding and scale in physical x-right/y-down axes.</p><div class="composition-numbers">${['a','b','c','d','x','y'].map((k,i)=>this.number('request-'+k,'Request '+k.toUpperCase(),c.frame.documentToRequest[i],v=>{c.frame.documentToRequest=c.frame.documentToRequest.map((n,j)=>j===i?v:n) as unknown as typeof c.frame.documentToRequest;c.frame.revision=crypto.randomUUID();}))}</div><en-switch label="Composition guides" .checked=${this.guides} @en-change=${(ev:Event)=>{if(!owns()){ev.preventDefault();return;}const h=ev.currentTarget as HTMLElement&{checked:boolean};this.settleControl(ev,()=>h.checked,v=>{this.guides=v;this.touch(false);});}}></en-switch></en-accordion-item></en-accordion>
 <en-validation-summary id="composition-errors" heading="Composition needs attention" .items=${this.issues.map(i=>({target:this.issueTarget(i),message:i.code+': '+i.message}))} @en-action=${(e:Event)=>{if(owns())this.errorNavigation(e);else e.preventDefault();}}></en-validation-summary>
 <en-alert announcement="polite">${this.message|| (this.dirty?'Unapplied Composition draft.':'Accepted Composition; local request preview only.')}</en-alert>
 <en-stack direction="horizontal" wrap><en-button id="apply-composition" ?disabled=${this.composing||this.committing} @click=${this.action(()=>this.commit())}>Apply Composition</en-button><en-button variant="secondary" @click=${this.action(()=>this.current())}>Review current document</en-button><en-button variant="secondary" @click=${this.action(()=>this.preview())}>Preview request draft</en-button></en-stack>
 ${this.exact?html`<en-textarea label="Exact local prompt string" .value=${this.exact} .readOnly=${true} .rows=${6}></en-textarea><en-alert announcement="none">Expansion None is recommended for Composition. Forwarding, layout and lettering fidelity are unverified. Provider transport is unavailable.</en-alert><en-button ?disabled=${!this.projection||this.composing} @click=${this.action(()=>this.approve())}>Approve local request draft</en-button>`:nothing}
 <en-accordion><en-accordion-item value="raw"><span slot="heading">Raw caption inspection and Convert copy</span><en-file-upload label="Import raw caption bytes" @en-change=${(ev:Event)=>{if(!owns()){ev.preventDefault();return;}const h=ev.currentTarget as HTMLElement&{files:File[]};this.settleControl(ev,()=>h.files[0],f=>{if(f)void this.retain(f).catch(x=>this.error(x));});}}></en-file-upload>${this.text('composition-raw','Raw caption to retain',this.convertText,v=>this.convertText=v)}<en-button variant="secondary" @click=${this.action(()=>this.retainTyped())}>Retain and inspect raw</en-button>${c.raw.length?html`<en-select id="composition-raw-source" label="Retained raw source" .value=${this.fieldValue('composition-raw-source',String(this.rawIndex))} @en-change=${(ev:Event)=>{if(!owns()){ev.preventDefault();return;}const h=ev.currentTarget as Field;if(owns())this.settled(ev,()=>h.value,v=>{this.rawIndex=Number(v);this.rawOffset=0;this.touch(false);void this.rawPage(0).catch(e=>this.error(e));});}}>${c.raw.map((r,i)=>html`<en-select-option value=${String(i)}>Original ${i+1}: ${r.byteLength} bytes · ${r.hash.slice(0,22)}</en-select-option>`)}</en-select>`:nothing}<en-textarea label="Immutable raw byte page" .value=${this.rawText} .readOnly=${true} .rows=${5}></en-textarea><p>32 KiB byte pages; decoding is for display only. Original bytes remain separate. ${c.raw[this.rawIndex]?.byteLength??0} bytes retained.</p><en-stack direction="horizontal" wrap><en-button variant="secondary" @click=${this.action(()=>this.downloadRaw())}>Export exact original bytes</en-button><en-button variant="ghost" @click=${this.action(()=>this.rawPage(-1))}>Previous raw page</en-button><en-button variant="ghost" @click=${this.action(()=>this.rawPage(1))}>Next raw page</en-button></en-stack>${this.rawResult?html`<en-badge>${this.rawResult.state}</en-badge><en-validation-summary heading="Raw inspection" .items=${this.rawResult.issues.map(i=>({target:'composition-raw',message:i.path+' · '+i.code}))}></en-validation-summary>`:nothing}<en-button variant="secondary" @click=${this.action(()=>this.convert())}>Convert copy…</en-button></en-accordion-item></en-accordion>`}</section>`;}
 inspector(){return this.render('inspector',()=>this.inspectorOwned());}
 private inspectorOwned(){const owns=this.fieldOwner(),e=this.selectedElement();if(!e)return html`<h2>Semantic element inspector</h2><p>Select a Composition element. This does not select a native layer.</p>`;const b=e.bounds?bindingValue(e.bounds):null;return html`<section id="semantic-inspector" tabindex="-1" class="composition-editor" @compositionstart=${()=>{if(owns())this.compositionState(true);}} @compositionend=${()=>{if(owns())this.compositionState(false);}}><h2>Semantic ${e.type==='text'?'text':'object'} inspector</h2>${this.choice('Element type',e.type,[['obj','Object'],['text','Text']],v=>{e.type=v as 'obj'|'text';})}<p>Object versions omit literal text; the inactive text draft remains retained.</p>${this.text('semantic-desc','Appearance description',bindingValue(e.desc),v=>{e.desc={mode:'literal',value:v};},e.desc.mode==='layer')}${e.type==='text'?this.text('semantic-text','Literal lettering',bindingValue(e.text),v=>{e.text={mode:'literal',value:v};},e.text.mode==='layer'):nothing}
 ${this.choice('Native layer for explicit links',this.layerChoice,[['','Choose a layer'],...this.layers.map(l=>[l.id,(this.editor.view.image?.layers.find(x=>x.id===l.id)?.name??l.id)+' · '+l.kind] as [string,string])],v=>this.layerChoice=v)}${this.binding('desc','appearance')}${e.type==='text'?this.binding('text','content'):nothing}${this.binding('bounds','bounds')}
 ${b?html`<div class="composition-numbers">${['X','Y','Width','Height'].map((k,i)=>e.bounds!.mode==='literal'?this.number('semantic-'+e.id+'-'+k,k+' in document pixels',b.rect[i],v=>b.rect[i]=v):html`<p>${k}: ${b.rect[i]}</p>`)}</div>`:html`<en-button variant="secondary" @click=${this.action(()=>{e.bounds={mode:'literal',value:{rect:[0,0,100,100],transform:[1,0,0,1,0,0]}};this.touch();})}>Add literal bounds</en-button>`}
 ${this.choice('Bounds review',e.boundsPolicy,[['inside','Require inside request frame'],['clip','Explicitly clip to request frame'],['omit','Explicitly omit bbox']],v=>e.boundsPolicy=v as SemanticElement['boundsPolicy'],'semantic-bounds-policy')}<p>Full-precision geometry stays unchanged. Projection maps all four corners, encloses rotation/shear and rounds row-first edges.</p>${b?html`<en-alert announcement="none">${(()=>{try{const p=this.projectLocal(b,this.c!.frame,e.boundsPolicy);return p?`[y0,x0,y1,x1] ${JSON.stringify(p.quantized)}; before rounding ${JSON.stringify(p.normalized)}. ${p.approximation?'Rotated/sheared axis-aligned approximation.':''} ${p.policy==='clip'?'Clipping explicitly selected.':''}`:'Bounds deliberately omitted.';}catch(x){return x instanceof Error?x.message:String(x);}})()}</en-alert>`:nothing}
 ${e.bounds?.mode==='literal'?html`<en-switch label="Move selected semantic bounds on canvas" .checked=${this.moveGuides} @en-change=${(ev:Event)=>{if(!owns()){ev.preventDefault();return;}const h=ev.currentTarget as HTMLElement&{checked:boolean};this.settleControl(ev,()=>h.checked,v=>{this.moveGuides=v;this.changed();});}}></en-switch><en-button variant="secondary" @keydown=${(ev:KeyboardEvent)=>{if(owns())this.boxKey(ev);else ev.preventDefault();}}>Adjust semantic bounds with arrow keys</en-button><p>Arrow keys move one document pixel; Shift moves ten. Drag and numeric changes remain a draft until Apply Composition.</p>`:nothing}${this.palette()}<en-switch label="Exclude element from request" .checked=${e.excluded} @en-change=${(ev:Event)=>{if(!owns()){ev.preventDefault();return;}const h=ev.currentTarget as HTMLElement&{checked:boolean};this.settleControl(ev,()=>h.checked,v=>{e.excluded=v;this.touch();});}}></en-switch><en-stack direction="horizontal" wrap><en-button variant="secondary" @click=${this.action(()=>this.move(-1))}>Move element earlier</en-button><en-button variant="secondary" @click=${this.action(()=>this.move(1))}>Move element later</en-button><en-button variant="secondary" @click=${this.action(()=>{if(this.c!.elements.length>=256)throw Error('At most 256 semantic elements can be retained in one Composition.');this.admitMutation(compositionPayloadBytes(e)+4096);const copy=structuredClone(e);copy.id=crypto.randomUUID();this.c!.elements.push(copy);this.selected=copy.id;this.touch();})}>Duplicate semantic element</en-button><en-button variant="ghost" @click=${this.action(()=>this.remove())}>Delete semantic element</en-button></en-stack></section>`;}
 dialog(){return this.render('dialog',()=>this.dialogOwned());}
 private dialogOwned(){const owns=this.fieldOwner();return html`<en-dialog label="Review Convert copy" .open=${this.convertOpen} @en-change=${(ev:Event)=>{if(!owns()){ev.preventDefault();return;}const h=ev.currentTarget as HTMLElement&{open:boolean};this.settleControl(ev,()=>h.open,v=>{this.cancelReview();this.convertOpen=v;this.changed();});}}><en-alert announcement="none">The original ${this.sourceRaw?.byteLength??0} bytes stay immutable. Edit this new copy explicitly; only the displayed supported fields will become a new Composition version, replacing the current semantic list.</en-alert><en-textarea label="Original raw page" .value=${this.rawText} .readOnly=${true}></en-textarea><en-textarea id="conversion-copy" label="Conversion copy" .value=${this.fieldValue('conversion-copy',this.convertText)} @en-input=${(e:Event)=>{if(!owns()){e.preventDefault();return;}const h=e.currentTarget as Field;this.settleControl(e,()=>h.value,v=>{this.admitMutation(v.length*2+4096);this.convertText=v;this.convertResult=this.parseText(v);this.changed();});}}></en-textarea><en-validation-summary heading="Conversion errors" .items=${this.convertResult?.issues.map(i=>({target:'conversion-copy',message:i.path+' · '+i.code}))??[]}></en-validation-summary><en-button ?disabled=${this.convertResult?.state!=='supported'} @click=${this.action(()=>this.convertCopy())}>Apply reviewed Convert copy</en-button><en-button variant="secondary" @click=${this.action(()=>{this.convertOpen=false;this.changed();})}>Cancel conversion</en-button></en-dialog>`;}
 overlay(ctx:CanvasRenderingContext2D){if(!this.guides||!this.c||this.view!=='composition')return;ctx.save();ctx.strokeStyle='#d08aff';ctx.fillStyle='#d08aff';ctx.lineWidth=1;ctx.setLineDash([5,4]);if(this.c.frame.width!==null){ctx.save();ctx.transform(...inverseAffine(this.c.frame.documentToRequest));ctx.strokeRect(0,0,this.c.frame.width,this.c.frame.height!);ctx.fillText('Request frame',4,14);ctx.restore();}for(const [i,e]of this.c.elements.entries()){if(!e.bounds||e.excluded)continue;const g=this.drag?.element===e?this.translated(this.drag.geometry,this.drag.point[0]-this.drag.start[0],this.drag.point[1]-this.drag.start[1]):bindingValue(e.bounds),[x,y,w,h]=g.rect;ctx.save();ctx.transform(...g.transform);ctx.strokeRect(x,y,w,h);ctx.fillText(`Composition ${i+1}: ${e.type}`,x,y-4);ctx.restore();}ctx.restore();}
}
