import {html,nothing} from 'lit';
import type {LitElement} from 'lit';
import {parseColor,exportSRGB} from '@en-reve/elements/color-picker.js';
import {chooseDestination,writeDestination} from '../state/destination.js';
import type {EditorClient} from '../state/editor-client.js';
import type {Document,BlobRef} from '../protocol/store.js';
import type {CompositionCommand} from '../protocol/history.js';
import {canonical} from '../protocol/json.js';
import {ControlAdapter} from './adapters.js';
import {CompositionError,emptyComposition,emptyElement,emptyStyle,validateComposition,bindingIds,bindingValue,fieldStatus,linkField,detach,parseCaption,fromCaption,serialize,projectBounds,inverseAffine} from '../composition/core.js';
import type {Composition,LayerValue,Element as SemanticElement,Binding,Geometry,Issue,ParseResult} from '../composition/core.js';

type Field=HTMLElement&{value:string};
type View={composition:Composition|null;bindings:Record<string,string>;layers:LayerValue[];revision:string};
export class CompositionEditing {
 private reviewIntent=0;private currentView='plain';guides=true;
 get view(){return this.currentView;}
 set view(value:string){if(value!==this.currentView){this.reviewIntent++;this.currentView=value;}}
 cancelReview(){this.reviewIntent++;}
 get operation(){return this.c?.request.operation;}
 private c:Composition|null=null;private accepted:Composition|null=null;private layers:LayerValue[]=[];private bindings:Record<string,string>={};
 private selected='';private layerChoice='';private key='';private base:Document|null=null;private dirty=false;private draftId:string=crypto.randomUUID();private generation=0;private loading='';private composing=false;
 private adapter=new ControlAdapter();private issues:Issue[]=[];private message='';private exact='';private projection=false;private committing=false;
 private numbers:Record<string,string>={};private color='#336699';private paletteTarget='element';private conversion:{hex:string;clipped:boolean;alpha:number}|null=null;
 private rawRead=0;private rawInspected='';private rawText='';private rawResult:ParseResult|null=null;private rawIndex=0;private rawOffset=0;private convertOpen=false;private convertText='';private convertResult:ParseResult|null=null;private sourceRaw:BlobRef|null=null;
 constructor(private host:LitElement,private editor:EditorClient,private inspect:()=>void,private draw:()=>void,private dialogs:()=>Promise<void>,private revealNative:(id:string)=>void){}
 dispose(){this.rawRead++;this.drag=null;this.generation++;this.adapter.invalidate();this.loading='';}
 operationChanged(operation:string){if(this.c&&this.c.request.operation!==operation){this.c.request.operation=operation;this.c.request.rewriteAcknowledged=false;this.touch();}}
 linked(layer:string){return this.c?.elements.filter(e=>[e.desc,e.text,e.bounds].some(b=>b?.mode==='layer'&&this.bindings[b.layerId]===layer))??[];}
 reveal(layer:string){const links=this.linked(layer),at=links.findIndex(e=>e.id===this.selected);if(links.length){this.selected=links[(at+1)%links.length].id;this.view='composition';this.inspect();this.touch(false);}}
 private changed(){this.host.requestUpdate();this.draw();}
 private error(e:unknown){this.issues=e instanceof CompositionError?e.issues:[{path:'$',code:'ACTION',message:e instanceof Error?e.message:String(e)}];this.changed();void this.host.updateComplete.then(()=>this.host.querySelector<HTMLElement>('#composition-errors')?.focus());}
 private button(e:Event,work:()=>void|Promise<void>){this.adapter.action(e,()=>{this.cancelReview();void Promise.resolve().then(work).catch(x=>this.error(x));});}
 private compositionState(active:boolean){this.cancelReview();this.composing=active;this.save();this.changed();}
 private value(e:Event,set:(v:string)=>void){const h=e.currentTarget as Field;this.adapter.settled(e,()=>h.value,v=>{set(v);this.touch();});}
 private input(e:Event,set:(v:string)=>void){const h=e.currentTarget as Field,d=(e as CustomEvent).detail;this.adapter.settled(e,()=>h.value,v=>{this.composing=!!d?.isComposing;set(v);this.touch();});}
 private issueTarget(i:Issue){if(this.numbers[i.path]!==undefined)return i.path;const m=/^elements\.([^.]+)\.(desc|text|bounds)$/.exec(i.path);if(m)return 'semantic-issue-'+m[1]+'-'+m[2];if(i.path==='frame')return this.c?.frame.width===null?'request-dimensions':'request-width';if(i.path==='request')return 'composition-expansion';if(i.path==='background')return 'composition-background';if(i.path==='style')return 'composition-style';if(i.path==='raw'||i.path==='ref')return 'composition-raw';return 'composition-scene';}
 private errorNavigation(ev:Event){if(ev.defaultPrevented)return;let target=(ev as CustomEvent).detail?.data?.target;if(!target)return;ev.preventDefault();const e=this.c?.elements.find(e=>target.includes(e.id));if(e){this.selected=e.id;const b=e.bounds?.mode==='literal'?e.bounds.value:null;target=target.endsWith('-desc')?'semantic-desc':target.endsWith('-text')?'semantic-text':target.endsWith('-bounds')?b&&b.rect[2]<=0?'semantic-'+e.id+'-Width':b&&b.rect[3]<=0?'semantic-'+e.id+'-Height':'semantic-bounds-policy':target;this.inspect();}this.changed();const active=document.activeElement;void this.host.updateComplete.then(async()=>{const field=this.host.querySelector<HTMLElement>('#'+CSS.escape(target)),item=field?.closest('en-accordion-item'),group=item?.closest('en-accordion');if(item&&group){group.value=[item.getAttribute('value')!];await group.updateComplete;await item.updateComplete;}if(document.activeElement===active)field?.focus();});}
 private text(id:string,label:string,value:string,set:(v:string)=>void,readOnly=false){return html`<en-textarea id=${id} label=${label} .value=${value} .rows=${2} ?readOnly=${readOnly} @en-input=${(e:Event)=>{if(!readOnly)this.input(e,set);}}></en-textarea>`;}
 private number(id:string,label:string,initial:number,set:(v:number)=>void){return html`<en-number-field id=${id} label=${label} .value=${this.numbers[id]??String(initial)} @en-input=${(e:Event)=>this.input(e,v=>{this.numbers[id]=v;if(v.trim()&&Number.isFinite(Number(v)))set(Number(v));})}></en-number-field>`;}
 private choice(label:string,value:string,options:[string,string][],set:(v:string)=>void,id=''){return html`<en-select id=${id} label=${label} .value=${value} @en-change=${(e:Event)=>this.value(e,set)}>${options.map(([v,l])=>html`<en-select-option value=${v}>${l}</en-select-option>`)}</en-select>`;}
 private touch(domain=true){if(!this.c||!this.base)return;if(domain){if(!this.dirty||this.c.review)this.c.id=crypto.randomUUID();this.c.review=null;this.dirty=true;this.exact='';this.projection=false;this.message='Unapplied Composition draft.';}this.generation++;this.issues=[];this.save();this.changed();}
 private save(){if(!this.c||!this.base)return;this.editor.changeDraft(this.draftId,'composition',JSON.stringify({composition:this.c,bindings:this.bindings,selected:this.selected,numbers:this.numbers,color:this.color,view:this.view,guides:this.guides,rawText:this.convertText,rawIndex:this.rawIndex,rawOffset:this.rawOffset}),null,this.composing,this.base.revision);}
 private moveGuides=false;private drag:{id:number;start:readonly[number,number];point:readonly[number,number];element:SemanticElement;geometry:Geometry;generation:number;revision:string}|null=null;
 get dragging(){return this.drag!==null;}
 cancelDrag(){this.drag=null;this.draw();}
 pointerDown(ev:PointerEvent,p:readonly[number,number]){const e=this.selectedElement();if(!this.moveGuides||this.view!=='composition'||!this.guides||ev.button!==0||ev.defaultPrevented||!e||e.bounds?.mode!=='literal')return false;this.drag={id:ev.pointerId,start:p,point:p,element:e,geometry:structuredClone(e.bounds.value),generation:this.generation,revision:this.editor.view.document!.revision};(ev.target as HTMLElement).setPointerCapture(ev.pointerId);return true;}
 pointerMove(ev:PointerEvent,p:readonly[number,number]){if(!this.drag||ev.pointerId!==this.drag.id)return false;if(!ev.defaultPrevented)this.drag.point=p;this.draw();return true;}
 private translated(g:Geometry,x:number,y:number){const next=structuredClone(g),m=inverseAffine(g.transform);next.rect[0]+=m[0]*x+m[2]*y;next.rect[1]+=m[1]*x+m[3]*y;return next;}
 pointerUp(ev:PointerEvent,p:readonly[number,number]){const g=this.drag;if(!g||g.id!==ev.pointerId)return false;this.drag=null;setTimeout(()=>{if(ev.defaultPrevented||g.generation!==this.generation||g.revision!==this.editor.view.document?.revision||g.element!==this.selectedElement()){this.draw();return;}g.element.bounds={mode:'literal',value:this.translated(g.geometry,p[0]-g.start[0],p[1]-g.start[1])};for(const k of Object.keys(this.numbers))if(k.startsWith('semantic-'+g.element.id+'-'))delete this.numbers[k];this.touch();},0);return true;}
 private boxKey(ev:KeyboardEvent){if(ev.defaultPrevented||ev.isComposing||ev.metaKey||ev.ctrlKey||ev.altKey||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(ev.key))return;const e=this.selectedElement();if(e?.bounds?.mode!=='literal')return;ev.preventDefault();const n=ev.shiftKey?10:1;e.bounds.value=this.translated(e.bounds.value,ev.key==='ArrowLeft'?-n:ev.key==='ArrowRight'?n:0,ev.key==='ArrowUp'?-n:ev.key==='ArrowDown'?n:0);for(const k of Object.keys(this.numbers))if(k.startsWith('semantic-'+e.id+'-'))delete this.numbers[k];this.touch();}
 private selectedElement(){return this.c?.elements.find(e=>e.id===this.selected);}
 async sync(){
  const d=this.editor.view.document;if(!this.editor.view.ready||!d)return;const key=this.editor.sessionId+':'+d.id+':'+d.revision;if(this.key===key||this.loading===key)return;this.loading=key;const generation=this.generation;
  try{const value=await this.editor.json<View>('/api/v1/documents/'+d.id+'/composition?revision='+d.revision);if(this.loading!==key||this.editor.view.document?.id!==d.id||this.editor.view.document.revision!==d.revision)return;
   const changedDocument=this.base?.id!==d.id;this.layers=value.layers;this.accepted=value.composition;this.key=key;
   if(changedDocument||!this.dirty&&!this.committing){this.rawRead++;this.rawText='';this.rawResult=null;this.rawInspected='';this.rawIndex=0;this.rawOffset=0;this.convertOpen=false;this.sourceRaw=null;this.convertText='';this.dirty=false;this.c=structuredClone(value.composition??emptyComposition(d.width,d.height,crypto.randomUUID()));this.bindings={...value.bindings};this.base={...d};this.draftId=crypto.randomUUID();this.numbers={};this.selected=this.c.elements.some(e=>e.id===this.selected)?this.selected:'';this.exact='';this.projection=false;
    const saved=this.editor.ui?.drafts.find(x=>x.kind==='composition'&&x.documentId===d.id&&x.status==='saved-unapplied');
    if(changedDocument&&saved){const restored=await this.editor.json<any>('/api/v1/ui/'+this.editor.sessionId+'/composition?draftId='+saved.id+'&generation='+saved.generation);if(this.loading!==key||generation!==this.generation)return;const graph=restored.graph;this.c=graph.composition;this.bindings=restored.bindings;this.selected=graph.selected??'';this.numbers=graph.numbers??{};this.color=graph.color??this.color;this.view=graph.view??'composition';this.guides=graph.guides!==false;this.convertText=graph.rawText??'';this.rawIndex=graph.rawIndex??0;this.rawOffset=graph.rawOffset??0;this.base={...d,revision:saved.expectedDocumentRevision};this.draftId=saved.id;this.dirty=true;this.message='Recovered Composition draft. Review the current document before Apply.';}
    if(this.c?.raw.length){this.rawIndex=Math.min(this.rawIndex,this.c.raw.length-1);await this.rawPage(0);}
   }
   this.changed();
  }finally{if(this.loading===key)this.loading='';}
 }
 private validate(){if(!this.c||!this.base)throw Error('Open a document first.');if(this.composing)throw Error('Finish text composition before Apply.');for(const [path,v]of Object.entries(this.numbers))if(!v.trim()||!Number.isFinite(Number(v)))throw new CompositionError([{path,code:'NUMBER_REQUIRED',message:'Enter a finite number. Your draft is retained.'}]);validateComposition(this.c);if(this.c.frame.documentWidth!==this.base.width||this.c.frame.documentHeight!==this.base.height)throw new CompositionError([{path:'frame',code:'FRAME_CHANGED',message:'Review the changed document frame explicitly before projection.'}]);if(this.editor.view.document?.id!==this.base.id||this.editor.view.document.revision!==this.base.revision)throw Error('The document changed. Review the current document before Apply.');}
 private async current(){
  const d=this.editor.view.document;if(!d)throw Error('Open a document.');
  const intent=++this.reviewIntent,c=this.c,generation=this.generation,draftId=this.draftId,owner=this.editor.draftOwner,session=this.editor.sessionId;
  const owns=()=>intent===this.reviewIntent&&this.c===c&&this.generation===generation&&this.draftId===draftId&&this.editor.draftOwner===owner&&this.editor.sessionId===session&&this.editor.view.document?.id===d.id&&this.editor.view.document.revision===d.revision;
  try{const v=await this.editor.json<View>('/api/v1/documents/'+d.id+'/composition?revision='+d.revision);if(!owns())return;if(v.revision!==d.revision)throw Error('Document changed during review.');
   this.layers=v.layers;this.base={...d};if(c){c.frame.documentWidth=d.width;c.frame.documentHeight=d.height;c.frame.revision=crypto.randomUUID();}this.touch();this.message='Current document reviewed. Each stale field still needs explicit relink or detach.';
  }catch(e){if(owns())throw e;}
 }

 private async flushOwnDraft(){for(let i=0;i<3;i++){await this.editor.flushDrafts();const saved=this.editor.draftOwner?.drafts.get(this.draftId);if(saved&&saved.savedGeneration===saved.generation)return saved;}throw Error('Draft still changing. Wait for local save before continuing.');}
 private async commit(type:CompositionCommand='CommitCompositionVersion'){
  this.validate();const c=this.c!,base=this.base!,g=this.generation;this.committing=true;
  try{this.save();await this.flushOwnDraft();if(g!==this.generation||this.c!==c)throw Error('Composition changed while saving. Apply the current draft.');const saved=this.editor.draftOwner?.drafts.get(this.draftId);if(!saved||saved.savedGeneration!==saved.generation)throw Error('Wait for the draft to save, then Apply.');const ref=await this.editor.stageTextBlob(new Blob([canonical(c)]),'application/json');if(g!==this.generation||this.editor.view.document?.revision!==base.revision)throw Error('Composition or document changed. The saved draft is retained.');await this.editor.command({type,composition:{id:c.id,value:ref,bindings:this.bindings},draft:{sessionId:this.editor.sessionId,draftId:this.draftId,generation:saved.generation}},base);
   if(g===this.generation){this.dirty=false;this.accepted=structuredClone(c);this.base={...this.editor.view.document!};this.draftId=crypto.randomUUID();this.message=type==='ApprovePromptProjection'?'Local request draft reviewed and saved. No provider request was made.':'Composition applied and saved locally.';}
  }finally{this.committing=false;this.changed();}
 }
 private preview(){this.validate();const result=serialize(this.c!,this.layers,this.bindings);this.exact=result.prompt;this.projection=true;this.message=`Local draft: ${new TextEncoder().encode(result.prompt).length} UTF-8 bytes; ${result.wirePromptBytes} escaped prompt bytes. Bounding boxes are soft guidance.`;this.changed();}
 private async approve(){this.validate();if(!this.projection)throw Error('Preview the current request draft first.');const c=this.c!,g=this.generation,result=serialize(c,this.layers,this.bindings),prompt=await this.editor.stageTextBlob(new Blob([result.prompt]),'text/plain');if(g!==this.generation)throw Error('Projection changed during preparation.');c.id=crypto.randomUUID();c.review={serializer:'caption-json-1',sourceId:c.id,frame:structuredClone(c.frame),request:structuredClone(c.request),dependencies:result.dependencies,boxes:result.boxes,prompt};this.dirty=true;await this.commit('ApprovePromptProjection');}
 private add(type:SemanticElement['type']){if(!this.c)return;if(this.c.elements.length>=256)throw Error('At most 256 semantic elements can be retained in one Composition.');const e=emptyElement(type,crypto.randomUUID());this.c.elements.push(e);this.selected=e.id;this.inspect();this.touch();}
 private remove(){const c=this.c!,i=c.elements.findIndex(e=>e.id===this.selected);c.elements.splice(i,1);this.selected=c.elements[Math.min(i,c.elements.length-1)]?.id??'';this.touch();void this.host.updateComplete.then(()=>this.host.querySelector<HTMLElement>(this.selected?'#semantic-tree':'#add-semantic-object')?.focus());}
 private move(delta:number){const es=this.c!.elements,i=es.findIndex(e=>e.id===this.selected),j=i+delta;if(j<0||j>=es.length)return;[es[i],es[j]]=[es[j],es[i]];this.touch();}
 private pruneBindings(){if(this.c){const ids=bindingIds(this.c);this.bindings=Object.fromEntries(ids.map(id=>[id,this.bindings[id]??id]));}}
 private bind(field:'desc'|'text'|'bounds'){const e=this.selectedElement(),l=this.layers.find(l=>l.id===this.layerChoice);if(!e||!l)throw Error('Choose a native layer, then explicitly link the field.');const b=linkField<any>(field==='text'?'text-content':field==='desc'?'appearance-description':'frame-bounds',l);(e as any)[field]=b;this.bindings[l.id]=l.id;this.pruneBindings();this.touch();}
 private binding(field:'desc'|'text'|'bounds',label:string){const e=this.selectedElement()!,b=e[field],status=b?fieldStatus(b,this.layers,this.bindings):'omitted';return html`<en-card><h3>${label}</h3><en-badge>${status}</en-badge>${b?.mode==='layer'?html`<p>Layer ${this.editor.view.image?.layers.find(l=>l.id===this.bindings[b.layerId])?.name??this.bindings[b.layerId]} · last reviewed version ${b.lastReviewedLayerVersion}</p><en-button variant="secondary" @click=${(ev:Event)=>this.button(ev,()=>{(e as any)[field]=detach(b as Binding<any>);this.pruneBindings();this.touch();})}>Detach ${label} as last reviewed literal</en-button><en-button variant="secondary" @click=${(ev:Event)=>this.button(ev,()=>{this.revealNative(this.bindings[b.layerId]);})}>Reveal linked layer</en-button>`:nothing}<en-button variant="secondary" @click=${(ev:Event)=>this.button(ev,()=>this.bind(field))}>Link ${label}</en-button></en-card>`;}
 private async retain(file:Blob){if(!this.c)throw Error('Open a document.');if(this.c.raw.length>=256)throw Error('At most 256 originals can be retained in one Composition.');const c=this.c,g=this.generation,ref=await this.editor.stageTextBlob(file,'application/octet-stream');if(g!==this.generation||c!==this.c)throw Error('The draft changed. Original staged bytes remain retained.');c.raw.push(ref);this.sourceRaw=ref;this.rawIndex=c.raw.length-1;this.rawOffset=0;this.rawText=new TextDecoder('utf-8',{ignoreBOM:true}).decode(await file.slice(0,32768).arrayBuffer());this.rawResult=parseCaption(new Uint8Array(await file.slice(0,262145).arrayBuffer()));this.rawInspected=ref.hash;this.touch();await this.flushOwnDraft();this.message='Original bytes retained separately. Inspection grants no authoring authority.';this.changed();}
 private rawPath(){const local=this.editor.draftOwner?.drafts.get(this.draftId),saved=local?.savedGeneration?{id:this.draftId,generation:local.savedGeneration}:this.editor.ui?.drafts.find(d=>d.id===this.draftId);return saved?'/api/v1/ui/'+this.editor.sessionId+'/composition?draftId='+saved.id+'&generation='+saved.generation:'/api/v1/documents/'+this.base!.id+'/composition?revision='+this.editor.view.document!.revision;}
 private async downloadRaw(){const ref=this.c?.raw[this.rawIndex];if(!ref)throw Error('Retain raw bytes first.');const chosen=chooseDestination('caption-original.bin');const status=await writeDestination({path:this.rawPath()+'&raw='+this.rawIndex+'&download=1',name:'caption-original.bin',hash:ref.hash,bytes:ref.byteLength},this.editor.session.transport,chosen);this.message=status==='confirmed'?'Original bytes saved to the chosen destination.':'Original-byte download started; destination remains unconfirmed.';this.changed();}
 private async rawPage(delta:number){
  if(!this.c?.raw.length)return;this.rawOffset=Math.max(0,this.rawOffset+delta*32768);const source=this.c.raw[this.rawIndex];if(this.rawOffset>=Number(source.byteLength))this.rawOffset=Math.max(0,Math.floor((Number(source.byteLength)-1)/32768)*32768);
  const token=++this.rawRead,path=this.rawPath(),index=this.rawIndex,offset=this.rawOffset,inspect=this.rawInspected!==source.hash;this.rawText='';if(inspect)this.rawResult=null;
  const response=await this.editor.session.transport(path+'&raw='+index+'&offset='+offset);if(!response.ok)throw Error('Raw bytes unavailable at this saved version.');const page=await response.arrayBuffer();let result=this.rawResult;
  if(inspect){if(BigInt(source.byteLength)>262144n)result={state:'over-limit',issues:[{path:'$',code:'BYTE_LIMIT',message:'Raw retained. Parsing is limited to 256 KiB.'}]};else{const full=await this.editor.session.transport(path+'&raw='+index+'&download=1');if(!full.ok)throw Error('Original source unavailable.');result=parseCaption(new Uint8Array(await full.arrayBuffer()));}}
  if(token!==this.rawRead||this.c?.raw[index]?.hash!==source.hash||this.rawIndex!==index||this.rawOffset!==offset)return;this.rawText=new TextDecoder('utf-8',{ignoreBOM:true}).decode(page);this.rawResult=result;this.rawInspected=source.hash;this.changed();
 }
 private async convert(){this.sourceRaw=this.c?.raw[this.rawIndex]??null;if(!this.sourceRaw)throw Error('Retain original raw input first.');await this.dialogs();this.convertOpen=true;this.convertText='';if(BigInt(this.sourceRaw.byteLength)<=262144n){const response=await this.editor.session.transport(this.rawPath()+'&raw='+this.rawIndex+'&download=1');if(!response.ok)throw Error('Original source unavailable.');try{this.convertText=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(await response.arrayBuffer());}catch{this.message='Invalid UTF-8 original retained. Author a separate valid conversion copy.';}}this.convertResult=parseCaption(new TextEncoder().encode(this.convertText));this.changed();}
 private async convertCopy(){if(!this.c||!this.sourceRaw||!this.convertResult?.value)throw Error('Correct the conversion copy and review its field errors first.');const next=fromCaption(this.convertResult.value,this.c.frame,crypto.randomUUID(),()=>crypto.randomUUID());next.raw=[...this.c.raw];next.request=structuredClone(this.c.request);this.c=next;this.bindings={};this.selected=next.elements[0]?.id??'';this.convertOpen=false;this.touch();await this.commit();this.inspect();}
 private palette(){const c=this.c!,e=this.selectedElement(),style=this.paletteTarget==='style',palette=style?c.style?.palette:e?.palette;const assign=(p:string[]|null)=>{if(style){if(!c.style)throw Error('Enable Style first.');c.style.palette=p;}else{if(!e)throw Error('Select a semantic element.');e.palette=p;}this.touch();};return html`<en-accordion><en-accordion-item value="palette"><span slot="heading">Caption palette</span>${this.choice('Palette scope',this.paletteTarget,[['element','Selected element'],['style','Overall style']],v=>{this.paletteTarget=v;})}<en-color-field label="sRGB color chooser" .value=${/^#[0-9A-Fa-f]{6}$/.test(this.color)?this.color:'#336699'} @en-change=${(ev:Event)=>this.value(ev,v=>{this.color=v;this.conversion=null;})}></en-color-field><en-text-field label="Color draft including alpha or Display P3" .value=${this.color} @en-input=${(ev:Event)=>this.input(ev,v=>{this.color=v;this.conversion=null;})}></en-text-field><en-button variant="secondary" @click=${(ev:Event)=>this.button(ev,()=>{const p=parseColor(this.color);if(!p)throw Error('Choose a supported color.');const result=exportSRGB(p),hex='#'+result.color.channels.map(x=>Math.round(x*255).toString(16).padStart(2,'0')).join('').toUpperCase();this.conversion={hex,clipped:result.clipped,alpha:p.alpha};this.changed();})}>Preview opaque sRGB color</en-button>${this.conversion?html`<en-alert>Use ${this.conversion.hex}; alpha ${this.conversion.alpha} becomes 1. ${this.conversion.clipped?'Out-of-gamut channels are clipped.':'No gamut clipping.'} Original color draft is retained.</en-alert><en-button @click=${(ev:Event)=>this.button(ev,()=>{if((palette?.length??0)>=(style?16:5))throw Error('Palette limit reached.');assign([...(palette??[]),this.conversion!.hex]);this.conversion=null;})}>Apply color to palette</en-button>`:nothing}${(palette??[]).map((p,i)=>html`<en-stack direction="horizontal" wrap><en-badge>${p}</en-badge><en-button variant="ghost" @click=${(ev:Event)=>this.button(ev,()=>assign(palette!.filter((_,j)=>j!==i)))}>Remove color ${i+1}</en-button><en-button variant="ghost" ?disabled=${i===0} @click=${(ev:Event)=>this.button(ev,()=>{const a=[...palette!];[a[i-1],a[i]]=[a[i],a[i-1]];assign(a);})}>Move color ${i+1} earlier</en-button></en-stack>`)}<en-button variant="ghost" @click=${(ev:Event)=>this.button(ev,()=>assign(palette===null?[]:null))}>${palette===null?'Enable empty palette':'Omit palette'}</en-button></en-accordion-item></en-accordion>`;}
 request(){const c=this.c;return html`<en-segmented-control label="Prompt source" .value=${this.view} .items=${[{value:'plain',label:'Plain prompt'},{value:'composition',label:'Composition'}]} @en-change=${(ev:Event)=>{const h=ev.currentTarget as Field;this.adapter.settled(ev,()=>h.value,v=>{this.view=v;this.touch(false);});}}></en-segmented-control><section class="composition-editor" @compositionstart=${()=>this.compositionState(true)} @compositionend=${()=>this.compositionState(false)} ?hidden=${this.view!=='composition'}><h2>Composition</h2>${!c?html`<p>Open a document to author Composition.</p>`:html`
 <en-badge>${this.c?.review?(this.c.frame.documentWidth!==this.base?.width||this.c.frame.documentHeight!==this.base?.height||this.c.elements.some(e=>[e.desc,e.text,e.bounds].some(b=>b?.mode==='layer'&&fieldStatus(b,this.layers,this.bindings)!=='reviewed'))?'Local projection needs review':'Local projection reviewed'):'Local projection not approved'}</en-badge><en-alert announcement="none">Semantic elements are independent of Layers. Selection never creates a link.</en-alert>
 ${this.text('composition-scene','Scene',c.scene,v=>c.scene=v)}
 ${this.choice('Style',c.style?.kind??'none',[['none','No style'],['photo','Photography'],['art','Art']],v=>{if(c.style)c.inactiveStyle=structuredClone(c.style);c.style=v==='none'?null:{...structuredClone(c.inactiveStyle),kind:v as 'photo'|'art'};},'composition-style')}
 <div ?hidden=${!c.style}>${c.style?html`${this.text('composition-aesthetics','Aesthetics',c.style.aesthetics,v=>c.style!.aesthetics=v)}${this.text('composition-lighting','Lighting',c.style.lighting,v=>c.style!.lighting=v)}${this.text('composition-medium','Medium',c.style.medium,v=>c.style!.medium=v)}${c.style.kind==='photo'?this.text('composition-photo','Photography description',c.style.photo,v=>c.style!.photo=v):this.text('composition-art','Art style',c.style.artStyle,v=>c.style!.artStyle=v)}`:nothing}</div>
 ${this.text('composition-background','Background',c.background,v=>c.background=v)}
 <h3>Local request draft</h3><p>Operation: ${c.request.operation}. Authored content is retained below; nothing has been submitted and no returned or expanded prompt exists.</p>${this.choice('Prompt expansion',c.request.expansion,[['None','None — recommended'],['Medium','Medium'],['Large','Large']],v=>{c.request.expansion=v as Composition['request']['expansion'];c.request.rewriteAcknowledged=false;},'composition-expansion')}${c.request.expansion!=='None'?html`<en-alert>Provider expansion may rewrite structure or placement. Large is unavailable for Fast and Instant.</en-alert><en-switch label="Acknowledge possible expansion rewrite" .checked=${c.request.rewriteAcknowledged} @en-change=${(ev:Event)=>{const h=ev.currentTarget as HTMLElement&{checked:boolean};this.adapter.settled(ev,()=>h.checked,v=>{c.request.rewriteAcknowledged=v;this.touch();});}}></en-switch>`:html`<p>None requests preservation of caption structure. Forwarding and model fidelity remain unverified.</p>`}
 <h3>Semantic elements</h3><en-tree id="semantic-tree" label="Composition elements" .items=${c.elements.map((e,i)=>({key:e.id,label:`${i+1}. ${e.type==='text'?'Text':'Object'} · ${bindingValue(e.desc).slice(0,60)||'Untitled'}${e.excluded?' · excluded':''}`}))} .selectedKeys=${this.selected?[this.selected]:[]} @en-change=${(ev:Event)=>{const host=ev.currentTarget as HTMLElement&{selectedKeys:string[]};this.adapter.settled(ev,()=>host.selectedKeys[0]??'',v=>{this.selected=v;this.inspect();this.touch(false);});}}></en-tree>
 <en-stack direction="horizontal" wrap><en-button id="add-semantic-object" @click=${(e:Event)=>this.button(e,()=>this.add('obj'))}>Add object</en-button><en-button @click=${(e:Event)=>this.button(e,()=>this.add('text'))}>Add semantic text</en-button></en-stack><p>${c.elements.length}/256 semantic elements; ${this.editor.view.image?.layers.length??0} native layers.</p>
 <en-accordion><en-accordion-item value="frame"><span slot="heading">Request frame and guides</span>${this.choice('Request dimensions',c.frame.width===null?'auto':'explicit',[['explicit','Explicit size'],['auto','Unresolved auto']],v=>{c.frame.width=v==='auto'?null:this.base!.width;c.frame.height=v==='auto'?null:this.base!.height;c.frame.revision=crypto.randomUUID();},'request-dimensions')}${c.frame.width!==null?html`<div class="composition-numbers">${this.number('request-width','Request width',c.frame.width,v=>{c.frame.width=v;c.frame.revision=crypto.randomUUID();})}${this.number('request-height','Request height',c.frame.height!,v=>{c.frame.height=v;c.frame.revision=crypto.randomUUID();})}</div>`:nothing}<p>Document → request affine map: crop, padding and scale in physical x-right/y-down axes.</p><div class="composition-numbers">${['a','b','c','d','x','y'].map((k,i)=>this.number('request-'+k,'Request '+k.toUpperCase(),c.frame.documentToRequest[i],v=>{c.frame.documentToRequest=c.frame.documentToRequest.map((n,j)=>j===i?v:n) as unknown as typeof c.frame.documentToRequest;c.frame.revision=crypto.randomUUID();}))}</div><en-switch label="Composition guides" .checked=${this.guides} @en-change=${(ev:Event)=>{const h=ev.currentTarget as HTMLElement&{checked:boolean};this.adapter.settled(ev,()=>h.checked,v=>{this.guides=v;this.touch(false);});}}></en-switch></en-accordion-item></en-accordion>
 <en-validation-summary id="composition-errors" heading="Composition needs attention" .items=${this.issues.map(i=>({target:this.issueTarget(i),message:i.code+': '+i.message}))} @en-action=${(e:Event)=>this.errorNavigation(e)}></en-validation-summary>
 <en-alert announcement="polite">${this.message|| (this.dirty?'Unapplied Composition draft.':'Accepted Composition; local request preview only.')}</en-alert>
 <en-stack direction="horizontal" wrap><en-button id="apply-composition" ?disabled=${this.composing||this.committing} @click=${(e:Event)=>this.button(e,()=>this.commit())}>Apply Composition</en-button><en-button variant="secondary" @click=${(e:Event)=>this.button(e,()=>this.current())}>Review current document</en-button><en-button variant="secondary" @click=${(e:Event)=>this.button(e,()=>this.preview())}>Preview request draft</en-button></en-stack>
 ${this.exact?html`<en-textarea label="Exact local prompt string" .value=${this.exact} .readOnly=${true} .rows=${6}></en-textarea><en-alert announcement="none">Expansion None is recommended for Composition. Forwarding, layout and lettering fidelity are unverified. Provider transport is unavailable.</en-alert><en-button ?disabled=${!this.projection||this.composing} @click=${(e:Event)=>this.button(e,()=>this.approve())}>Approve local request draft</en-button>`:nothing}
 <en-accordion><en-accordion-item value="raw"><span slot="heading">Raw caption inspection and Convert copy</span><en-file-upload label="Import raw caption bytes" @en-change=${(ev:Event)=>{const h=ev.currentTarget as HTMLElement&{files:File[]};this.adapter.settled(ev,()=>h.files[0],f=>{if(f)void this.retain(f).catch(x=>this.error(x));});}}></en-file-upload>${this.text('composition-raw','Raw caption to retain',this.convertText,v=>this.convertText=v)}<en-button variant="secondary" @click=${(ev:Event)=>this.button(ev,()=>this.retain(new Blob([this.convertText])))}>Retain and inspect raw</en-button>${c.raw.length?html`<en-select label="Retained raw source" .value=${String(this.rawIndex)} @en-change=${(ev:Event)=>{const h=ev.currentTarget as Field;this.adapter.settled(ev,()=>h.value,v=>{this.rawIndex=Number(v);this.rawOffset=0;this.touch(false);void this.rawPage(0).catch(e=>this.error(e));});}}>${c.raw.map((r,i)=>html`<en-select-option value=${String(i)}>Original ${i+1}: ${r.byteLength} bytes · ${r.hash.slice(0,22)}</en-select-option>`)}</en-select>`:nothing}<en-textarea label="Immutable raw byte page" .value=${this.rawText} .readOnly=${true} .rows=${5}></en-textarea><p>32 KiB byte pages; decoding is for display only. Original bytes remain separate. ${c.raw[this.rawIndex]?.byteLength??0} bytes retained.</p><en-stack direction="horizontal" wrap><en-button variant="secondary" @click=${(e:Event)=>this.button(e,()=>this.downloadRaw())}>Export exact original bytes</en-button><en-button variant="ghost" @click=${(e:Event)=>this.button(e,()=>this.rawPage(-1))}>Previous raw page</en-button><en-button variant="ghost" @click=${(e:Event)=>this.button(e,()=>this.rawPage(1))}>Next raw page</en-button></en-stack>${this.rawResult?html`<en-badge>${this.rawResult.state}</en-badge><en-validation-summary heading="Raw inspection" .items=${this.rawResult.issues.map(i=>({target:'composition-raw',message:i.path+' · '+i.code}))}></en-validation-summary>`:nothing}<en-button variant="secondary" @click=${(ev:Event)=>this.button(ev,()=>this.convert())}>Convert copy…</en-button></en-accordion-item></en-accordion>`}</section>`;}
 inspector(){const e=this.selectedElement();if(!e)return html`<h2>Semantic element inspector</h2><p>Select a Composition element. This does not select a native layer.</p>`;const b=e.bounds?bindingValue(e.bounds):null;return html`<section id="semantic-inspector" tabindex="-1" class="composition-editor" @compositionstart=${()=>this.compositionState(true)} @compositionend=${()=>this.compositionState(false)}><h2>Semantic ${e.type==='text'?'text':'object'} inspector</h2>${this.choice('Element type',e.type,[['obj','Object'],['text','Text']],v=>{e.type=v as 'obj'|'text';})}<p>Object versions omit literal text; the inactive text draft remains retained.</p>${this.text('semantic-desc','Appearance description',bindingValue(e.desc),v=>{e.desc={mode:'literal',value:v};},e.desc.mode==='layer')}${e.type==='text'?this.text('semantic-text','Literal lettering',bindingValue(e.text),v=>{e.text={mode:'literal',value:v};},e.text.mode==='layer'):nothing}
 ${this.choice('Native layer for explicit links',this.layerChoice,[['','Choose a layer'],...this.layers.map(l=>[l.id,(this.editor.view.image?.layers.find(x=>x.id===l.id)?.name??l.id)+' · '+l.kind] as [string,string])],v=>this.layerChoice=v)}${this.binding('desc','appearance')}${e.type==='text'?this.binding('text','content'):nothing}${this.binding('bounds','bounds')}
 ${b?html`<div class="composition-numbers">${['X','Y','Width','Height'].map((k,i)=>e.bounds!.mode==='literal'?this.number('semantic-'+e.id+'-'+k,k+' in document pixels',b.rect[i],v=>b.rect[i]=v):html`<p>${k}: ${b.rect[i]}</p>`)}</div>`:html`<en-button variant="secondary" @click=${(ev:Event)=>this.button(ev,()=>{e.bounds={mode:'literal',value:{rect:[0,0,100,100],transform:[1,0,0,1,0,0]}};this.touch();})}>Add literal bounds</en-button>`}
 ${this.choice('Bounds review',e.boundsPolicy,[['inside','Require inside request frame'],['clip','Explicitly clip to request frame'],['omit','Explicitly omit bbox']],v=>e.boundsPolicy=v as SemanticElement['boundsPolicy'],'semantic-bounds-policy')}<p>Full-precision geometry stays unchanged. Projection maps all four corners, encloses rotation/shear and rounds row-first edges.</p>${b?html`<en-alert announcement="none">${(()=>{try{const p=projectBounds(b,this.c!.frame,e.boundsPolicy);return p?`[y0,x0,y1,x1] ${JSON.stringify(p.quantized)}; before rounding ${JSON.stringify(p.normalized)}. ${p.approximation?'Rotated/sheared axis-aligned approximation.':''} ${p.policy==='clip'?'Clipping explicitly selected.':''}`:'Bounds deliberately omitted.';}catch(x){return x instanceof Error?x.message:String(x);}})()}</en-alert>`:nothing}
 ${e.bounds?.mode==='literal'?html`<en-switch label="Move selected semantic bounds on canvas" .checked=${this.moveGuides} @en-change=${(ev:Event)=>{const h=ev.currentTarget as HTMLElement&{checked:boolean};this.adapter.settled(ev,()=>h.checked,v=>{this.moveGuides=v;this.changed();});}}></en-switch><en-button variant="secondary" @keydown=${(ev:KeyboardEvent)=>this.boxKey(ev)}>Adjust semantic bounds with arrow keys</en-button><p>Arrow keys move one document pixel; Shift moves ten. Drag and numeric changes remain a draft until Apply Composition.</p>`:nothing}${this.palette()}<en-switch label="Exclude element from request" .checked=${e.excluded} @en-change=${(ev:Event)=>{const h=ev.currentTarget as HTMLElement&{checked:boolean};this.adapter.settled(ev,()=>h.checked,v=>{e.excluded=v;this.touch();});}}></en-switch><en-stack direction="horizontal" wrap><en-button variant="secondary" @click=${(ev:Event)=>this.button(ev,()=>this.move(-1))}>Move element earlier</en-button><en-button variant="secondary" @click=${(ev:Event)=>this.button(ev,()=>this.move(1))}>Move element later</en-button><en-button variant="secondary" @click=${(ev:Event)=>this.button(ev,()=>{if(this.c!.elements.length>=256)throw Error('At most 256 semantic elements can be retained in one Composition.');const copy=structuredClone(e);copy.id=crypto.randomUUID();this.c!.elements.push(copy);this.selected=copy.id;this.touch();})}>Duplicate semantic element</en-button><en-button variant="ghost" @click=${(ev:Event)=>this.button(ev,()=>this.remove())}>Delete semantic element</en-button></en-stack></section>`;}
 dialog(){return html`<en-dialog label="Review Convert copy" .open=${this.convertOpen} @en-change=${(ev:Event)=>{const h=ev.currentTarget as HTMLElement&{open:boolean};this.adapter.settled(ev,()=>h.open,v=>{this.cancelReview();this.convertOpen=v;this.changed();});}}><en-alert announcement="none">The original ${this.sourceRaw?.byteLength??0} bytes stay immutable. Edit this new copy explicitly; only the displayed supported fields will become a new Composition version, replacing the current semantic list.</en-alert><en-textarea label="Original raw page" .value=${this.rawText} .readOnly=${true}></en-textarea><en-textarea id="conversion-copy" label="Conversion copy" .value=${this.convertText} @en-input=${(e:Event)=>{const h=e.currentTarget as Field;this.adapter.settled(e,()=>h.value,v=>{this.convertText=v;this.convertResult=parseCaption(new TextEncoder().encode(v));this.changed();});}}></en-textarea><en-validation-summary heading="Conversion errors" .items=${this.convertResult?.issues.map(i=>({target:'conversion-copy',message:i.path+' · '+i.code}))??[]}></en-validation-summary><en-button ?disabled=${this.convertResult?.state!=='supported'} @click=${(e:Event)=>this.button(e,()=>this.convertCopy())}>Apply reviewed Convert copy</en-button><en-button variant="secondary" @click=${(e:Event)=>this.button(e,()=>{this.convertOpen=false;this.changed();})}>Cancel conversion</en-button></en-dialog>`;}
 overlay(ctx:CanvasRenderingContext2D){if(!this.guides||!this.c||this.view!=='composition')return;ctx.save();ctx.strokeStyle='#d08aff';ctx.fillStyle='#d08aff';ctx.lineWidth=1;ctx.setLineDash([5,4]);if(this.c.frame.width!==null){ctx.save();ctx.transform(...inverseAffine(this.c.frame.documentToRequest));ctx.strokeRect(0,0,this.c.frame.width,this.c.frame.height!);ctx.fillText('Request frame',4,14);ctx.restore();}for(const [i,e]of this.c.elements.entries()){if(!e.bounds||e.excluded)continue;const g=this.drag?.element===e?this.translated(this.drag.geometry,this.drag.point[0]-this.drag.start[0],this.drag.point[1]-this.drag.start[1]):bindingValue(e.bounds),[x,y,w,h]=g.rect;ctx.save();ctx.transform(...g.transform);ctx.strokeRect(x,y,w,h);ctx.fillText(`Composition ${i+1}: ${e.type}`,x,y-4);ctx.restore();}ctx.restore();}
}
