import {html,nothing} from 'lit';import type {LitElement} from 'lit';
import type {EditorClient} from '../state/editor-client.js';
import {ControlAdapter} from './adapters.js';
import {operations,labels,presets,newDraft,hash,captureMaskFrame,maskAlignment,resolve,resolveInactive,ignored,RequestError,routes} from '../request/core.js';
import type {Draft,Fields,Operation,Issue} from '../request/core.js';
import type {RequestReview} from '../request/review.js';
import type {Asset} from '../protocol/assets.js';
import type {Composition,LayerValue} from '../composition/core.js';
import {serialize} from '../composition/core.js';
import {canonical} from '../protocol/json.js';
type Entry={draft:Draft;text:string;id:string;revision:string;generation:number};
const promptRef=(text:string)=>({hash:hash(text),byteLength:String(new TextEncoder().encode(text).length),mediaType:'text/plain'});
export class RequestEditing{
 private adapter=new ControlAdapter();private entries=new Map<string,Entry>();private mode:Draft['prompt']['mode']='plain';private op:Operation='generate';private owner:unknown;private documentId='';private epoch=0;private loaded=false;private loading=false;private composing=false;private intent=0;
 private historical:{review:Pick<RequestReview,'id'|'token'|'endpoint'|'documentId'>;accepted:boolean}[]=[];private review:RequestReview|null=null;private accepted=false;private message='';private issues:Issue[]=[];private busy=false;private previewKey='';private previewURL='';private adapterVersion='';private adapterHash='';private adapterScale='1';
 constructor(private host:LitElement,private editor:EditorClient){}
 dispose(){if(this.previewURL)URL.revokeObjectURL(this.previewURL);this.previewURL='';this.previewKey='';this.epoch++;this.intent++;this.adapter.invalidate();}
 private changed(){this.host.requestUpdate();}
 private key(op=this.op,mode=this.mode){return op+':'+mode;}
 private entry(){return this.entries.get(this.key());}
 private owns(generationFence=true){const epoch=this.epoch,owner=this.editor.draftOwner,session=this.editor.session,identity=session.identity(),sessionId=this.editor.sessionId,doc=this.editor.view.document?.id,entry=this.entry(),generation=entry?.generation;return ()=>session===this.editor.session&&identity===session.identity()&&sessionId===this.editor.sessionId&&epoch===this.epoch&&owner===this.editor.draftOwner&&doc===this.editor.view.document?.id&&entry===this.entry()&&(!generationFence||generation===entry?.generation);}
 get operation(){return labels[operations.indexOf(this.op)];}
 operationChoice(changed:(value:string)=>void){const owns=this.owns(false);return (event:Event)=>{if(!owns())return;const host=event.currentTarget as HTMLElement&{value:string};this.adapter.settled(event,()=>host.value,value=>{if(!owns())return;this.operationChanged(value);changed(value);});};}
 operationChanged(label:string){const op=operations[labels.indexOf(label)];if(!op||op===this.op)return;const old=this.entry();this.op=op;this.busy=false;this.intent++;this.review=null;this.accepted=false;if(!this.entries.has(this.key())&&old){const next=structuredClone(old);next.id=crypto.randomUUID();next.draft.operation=op;next.generation=0;this.entries.set(this.key(),next);this.save();}this.issues=[];this.changed();}
 private modeChanged(mode:Draft['prompt']['mode']){if(mode===this.mode)return;const old=this.entry()!;this.mode=mode;if(!this.entries.has(this.key())){const next=structuredClone(old);next.id=crypto.randomUUID();next.generation=0;next.draft.prompt={mode,text:promptRef(next.text),projection:null,composition:null};this.entries.set(this.key(),next);}this.touch();}
 async sync(){const doc=this.editor.view.document,owner=this.editor.draftOwner;if(!doc||!owner||!this.editor.view.ready)return;
  if(this.owner===owner&&this.documentId===doc.id&&(this.loaded||this.loading)){if(this.loaded)void this.preview();return;}
  this.epoch++;this.intent++;this.adapter.invalidate();const epoch=this.epoch;this.owner=owner;this.documentId=doc.id;this.loading=true;this.loaded=false;this.composing=false;this.busy=false;this.entries.clear();this.review=null;this.accepted=false;
  const session=this.editor.session,identity=session.identity(),sessionId=this.editor.sessionId;const owns=()=>session===this.editor.session&&identity===session.identity()&&sessionId===this.editor.sessionId&&epoch===this.epoch&&owner===this.editor.draftOwner&&doc.id===this.editor.view.document?.id;
  try{for(const saved of this.editor.ui?.drafts??[]){if(saved.kind!=='request'||saved.documentId!==doc.id)continue;
    const path='/api/v1/ui/'+this.editor.sessionId+'/request?draftId='+saved.id+'&generation='+saved.generation;
    const value=await this.editor.json<{value:Draft}>(path),r=await this.editor.session.transport(path+'&content=1');if(!r.ok)throw Error('Saved request prompt unavailable.');const text=await r.text();if(!owns())return;
    this.entries.set(this.key(value.value.operation,value.value.prompt.mode),{draft:value.value,text,id:saved.id,revision:saved.expectedDocumentRevision,generation:0});
   }
   if(!owns())return;
   for(const saved of this.editor.ui?.drafts??[]){if(saved.kind!=='prompt'||saved.documentId!==doc.id)continue;const raw=await this.editor.draftText(saved.id);if(!owns())return;let text=raw,operation:Operation='generate';try{const v=JSON.parse(raw);if(v.schema==='editor-prompt-1'&&typeof v.text==='string'&&labels.includes(v.operation)){text=v.text;operation=operations[labels.indexOf(v.operation)];}}catch{}if(!this.entries.has(this.key(operation,'plain'))){const draft=newDraft(promptRef(text));draft.operation=operation;this.entries.set(this.key(operation,'plain'),{draft,text,id:crypto.randomUUID(),revision:doc.revision,generation:0});}}
   if(!this.entries.has(this.key())){const draft=newDraft(promptRef(''));draft.prompt.mode=this.mode;this.entries.set(this.key(),{draft,text:'',id:crypto.randomUUID(),revision:doc.revision,generation:0});}
   const history=await this.editor.json<{items:{review:Pick<RequestReview,'id'|'token'|'endpoint'|'documentId'>;accepted:boolean}[]}>('/api/v1/ui/'+this.editor.sessionId+'/request-reviews');if(!owns())return;this.historical=history.items.filter(x=>x.review.documentId===doc.id);
   const e=this.entry()!;e.draft.operation=this.op;this.loaded=true;this.message=this.entries.size>1||e.text?'Recovered saved request drafts. Prepare a fresh review before acceptance.':'Request drafts autosave locally. Review acceptance makes no provider call.';this.changed();
  }catch(e){if(owns())throw e;}finally{if(owns())this.loading=false;}
 }
 private save(){const e=this.entry();if(!e||!this.loaded)return;e.draft.prompt.text=promptRef(e.text);this.editor.changeDraft(e.id,'request',JSON.stringify({draft:e.draft,text:e.text}),null,this.composing,e.revision);}
 private touch(){const e=this.entry();if(!e)return;e.generation++;this.intent++;this.review=null;this.accepted=false;this.busy=false;this.issues=[];this.save();this.changed();}
 private field(event:Event,set:(value:string)=>void,restore?:string){const host=event.currentTarget as HTMLElement&{value:string},owns=this.owns(false);this.adapter.settled(event,()=>host.value,v=>{if(!owns())return;try{set(v);this.touch();}catch(e){if(restore!==undefined)this.adapter.write(host,'value',restore);this.error(e);}});}
 private action(event:Event,work:()=>void|Promise<void>){const owns=this.owns();this.adapter.action(event,()=>{if(!owns())return;void Promise.resolve().then(work).catch(e=>{if(owns())this.error(e);});});}
 private error(error:unknown){this.issues=error instanceof RequestError?error.issues:[{field:'review',code:'REVIEW',message:error instanceof Error?error.message:String(error)}];this.busy=false;this.changed();void this.host.updateComplete.then(()=>this.host.querySelector<HTMLElement>('#request-errors')?.focus());}
 private choice(label:string,value:string,items:string[],set:(v:string)=>void){const owns=this.owns(false),id=({'Expansion':'expansion','Rendering speed':'speed','Acceleration':'acceleration','Output format':'format','Request size':'size'} as Record<string,string>)[label]??'prompt-mode';return html`<en-select id=${'request-'+id} label=${label} .value=${value} @en-change=${(e:Event)=>owns()&&this.field(e,set,value)}>${items.map(v=>html`<en-select-option value=${v}>${v}</en-select-option>`)}</en-select>`;}
 private numeric(field:keyof Fields,label:string){const e=this.entry()!,owns=this.owns(false);return html`<en-number-field id=${'request-'+field} label=${label} .value=${e.draft.fields[field]} @en-input=${(ev:Event)=>owns()&&this.field(ev,v=>e.draft.fields[field]=v)}></en-number-field>`;}
 private async preview(){const source=this.entry()?.draft.source,key=source?this.epoch+':'+source.blob.hash:'';if(key===this.previewKey)return;this.previewKey=key;if(this.previewURL)URL.revokeObjectURL(this.previewURL);this.previewURL='';this.changed();if(!source)return;const owner=this.editor.draftOwner,session=this.editor.session,identity=session.identity(),owns=()=>key===this.previewKey&&owner===this.editor.draftOwner&&session===this.editor.session&&identity===session.identity();try{const r=await session.transport('/api/v1/assets/'+source.assetId+'/content');if(!r.ok)throw Error('Source preview is unavailable.');const blob=await r.blob(),bitmap=await createImageBitmap(blob);bitmap.close();if(!owns())return;this.previewURL=URL.createObjectURL(blob);this.changed();}catch(e){if(owns())this.error(e);}}
 private async source(assetId:string,scope:'asset'|'visible-document'){
  const owns=this.owns(),e=this.entry()!,doc=this.editor.view.document!;if(!assetId)throw Error('Choose a retained raster asset first.');const a=(await this.editor.json<{projection:{value:Asset}}>('/api/v1/assets/'+assetId)).projection.value;
  if(!owns())return;if(!a?.raster||a.qualification!=='canonical-raster'||a.raster.role==='mask')throw Error('Use an approved image asset as the source.');
  e.draft.source={assetId:a.id,version:a.version,blob:a.blob,pixels:a.raster.pixels,width:a.raster.width,height:a.raster.height,scope,documentRevision:doc.revision};e.draft.conversion=null;this.touch();this.message='Source snapshot attached. Reattach its mask before confirming alignment.';
 }
 private async mask(){const owns=this.owns(),e=this.entry()!,document=this.editor.view.document!,layer=this.editor.view.image?.layers.find(l=>l.id===this.editor.view.selected[0]);if(!e.draft.source||!layer?.mask)throw Error('Attach a source and select a layer with a saved local mask.');if(layer.mask.inverted||!['document-r16-v1','retained-r16-v1'].includes(layer.mask.mapping))throw Error('Use a non-inverted retained local mask; mapping changes need a separate mask review.');
  const a=(await this.editor.json<{projection:{value:Asset}}>('/api/v1/assets/'+layer.mask.assetId)).projection.value;if(!owns())return;if(!a?.raster||a.raster.role!=='mask')throw Error('The selected mask is unavailable.');
  // Coverage is read from the writer's retained manifest through the explicit asset read.
  const manifest=await this.editor.json<{plan:{statistics:{effectivePixels:number}}}>('/api/v1/assets/'+a.id+'/raster');const info={empty:manifest.plan.statistics.effectivePixels===0,full:manifest.plan.statistics.effectivePixels===a.raster.width*a.raster.height};if(!owns())return;
  e.draft.mask={assetId:a.id,version:a.version,blob:a.blob,pixels:a.raster.pixels,width:a.raster.width,height:a.raster.height,sourceHash:e.draft.source.pixels.hash,polarity:'white-edit',fullAcknowledged:false,empty:info.empty,full:info.full,plan:a.raster.manifest,frame:captureMaskFrame(document,layer)};this.touch();this.message='Mask frame attached to the '+e.draft.source.scope+' source. Confirm its alignment.';
 }
 private confirmAlignment(){const d=this.entry()!.draft;if(!d.source||!d.mask)throw Error('Attach the source and mask first.');const frame=d.mask.frame,document=this.editor.view.document!,layer=this.editor.view.image?.layers.find(l=>l.id===frame?.layer.id);if(!frame||!layer||canonical({...frame,alignment:null})!==canonical(captureMaskFrame(document,layer)))throw new RequestError([{field:'mask',code:'MASK_FRAME_CHANGED',message:'Document or layer geometry changed. Reattach the mask before confirming alignment.'}]);const alignment=maskAlignment(d.source,d.mask);d.mask.frame!.alignment=alignment;this.touch();this.message='Source and mask alignment confirmed without changing pixels.';}
 private async composition(){const owns=this.owns(),doc=this.editor.view.document!;const view=await this.editor.json<{composition:Composition|null;bindings:Record<string,string>;layers:LayerValue[]}>('/api/v1/documents/'+doc.id+'/composition?revision='+doc.revision);if(!owns())return;const c=view.composition,ref=this.editor.view.image?.composition;if(!c?.review||!ref)throw Error('Apply Composition and approve its local request projection first.');const projected=serialize(c,view.layers,view.bindings);if(hash(projected.prompt)!==c.review.prompt.hash)throw Error('Composition projection bytes changed.');this.modeChanged('composition');const e=this.entry()!;e.text=projected.prompt;e.draft.prompt={mode:'composition',text:c.review.prompt,projection:structuredClone(c.review),composition:structuredClone(ref)};e.draft.fields.expansion=c.request.expansion;e.draft.rewriteAcknowledged=c.request.rewriteAcknowledged;this.touch();}
 private async prepare(){const e=this.entry()!,owns=this.owns();if(this.composing)throw Error('Finish composing text before review.');this.busy=true;this.review=null;this.accepted=false;this.changed();e.draft.prompt.text=promptRef(e.text);resolve(e.draft,e.text);this.save();const gen=e.generation,intent=++this.intent;await this.editor.flushDrafts();if(!owns()||gen!==e.generation||intent!==this.intent)return;
  let saved=this.editor.draftOwner?.drafts.get(e.id);if(saved&&saved.savedGeneration!==saved.generation&&!saved.error){await this.editor.flushDrafts();if(!owns()||gen!==e.generation||intent!==this.intent)return;saved=this.editor.draftOwner?.drafts.get(e.id);}if(!saved||saved.savedGeneration!==saved.generation)throw Error('The current request draft has not been saved.');
  const receipt=await this.editor.requestReview({type:'PrepareRequestReview',draftId:e.id,generation:saved.generation});if(!owns()||gen!==e.generation||intent!==this.intent)return;
  this.review=receipt.review??null;if(!this.review)throw Error('Request review is unavailable.');this.busy=false;this.message='Exact request frozen for review. Acceptance saves this candidate locally; dispatch is unavailable.';this.changed();await this.host.updateComplete;this.host.querySelector<HTMLElement>('#request-review')?.focus();
 }
 private async accept(){const review=this.review,owns=this.owns(),intent=this.intent;if(!review)throw Error('Prepare a review first.');this.busy=true;this.changed();const receipt=await this.editor.requestReview({type:'AcceptRequestReview',reviewId:review.id,token:review.token});if(!owns()||intent!==this.intent)return;this.accepted=receipt.acceptedReview===review.id;this.busy=false;this.message='Request review accepted locally. No job was queued and no provider call was made.';this.changed();}
 render(){const e=this.entry();if(!e||!this.loaded)return html`<en-alert>Open a document and wait for saved request drafts to load.</en-alert>`;const owns=this.owns(false),action=(event:Event,work:()=>void|Promise<void>)=>{if(owns())this.action(event,work);},field=(event:Event,set:(value:string)=>void)=>{if(owns())this.field(event,set);};const d=e.draft,f=d.fields,r=this.review,previewURL=d.source&&this.previewKey===this.epoch+':'+d.source.blob.hash?this.previewURL:'';const inactive=(k:keyof Draft['inactive'])=>html`<en-button variant="secondary" @click=${(ev:Event)=>action(ev,()=>{resolveInactive(d,k);this.touch();})}>Keep ${k} inactive in this draft</en-button>${ignored(d,k)?html`<p role="status">${k} is confirmed inactive for this operation.</p>`:nothing}`;
  return html`<section aria-label="Typed request draft" class="typed-request" @compositionstart=${()=>{if(owns()){this.composing=true;this.touch();}}} @compositionend=${()=>{if(owns()){this.composing=false;this.touch();}}}>
   <en-alert>${this.message}</en-alert>${this.historical.length?html`<en-accordion-item label="Retained request reviews"><p>Historical records are read-only. Reopen does not queue work or renew approval.</p>${this.historical.map(x=>html`<p>${x.accepted?'Accepted locally':'Prepared'} · ${x.review.endpoint} · ${x.review.token}</p>`)}</en-accordion-item>`:nothing}
   ${this.choice('Request prompt type',d.prompt.mode,['plain','raw','composition'],v=>{if(v==='composition')throw Error('Use the explicit approved Composition action.');this.modeChanged(v as 'plain'|'raw');})}
   <en-textarea id="prompt" label="Prompt" .rows=${5} .value=${e.text} ?readOnly=${d.prompt.mode==='composition'} @en-input=${(ev:Event)=>field(ev,v=>{e.text=v;})} @focusout=${()=>{if(owns())void this.editor.flushDrafts().catch(e=>this.error(e));}}></en-textarea>
   <en-button @click=${(ev:Event)=>action(ev,()=>this.composition())}>Use approved Composition prompt</en-button>
   ${this.choice('Expansion',f.expansion,['None','Medium','Large'],v=>f.expansion=v)}
   <en-button variant="secondary" @click=${(ev:Event)=>action(ev,()=>{d.guidanceAcknowledged=true;d.rewriteAcknowledged=true;this.touch();})}>Acknowledge prompt guidance and possible rewriting</en-button>
   <p>None follows model guidance for structured captions; exact forwarding is unqualified. Expansion may rewrite text and placement. Raw text is retained exactly and is not validated Composition.</p>
   ${this.choice('Rendering speed',f.speed,['TURBO','BALANCED','QUALITY'],v=>f.speed=v)}${d.operation==='instant'?inactive('speed'):nothing}
   ${this.choice('Acceleration',f.acceleration,['none','low','regular','high'],v=>f.acceleration=v)}${['instant','fast'].includes(d.operation)?inactive('acceleration'):nothing}
   ${this.numeric('count','Output count')}<en-text-field id="request-seed" label="Exact seed (empty means Random)" .value=${f.seed} @en-input=${(ev:Event)=>field(ev,v=>f.seed=v)}></en-text-field>
   ${this.choice('Output format',f.format,['png','jpeg'],v=>f.format=v)}<p>JPEG cannot preserve alpha. PNG preserves returned alpha when present; it does not request transparent generation.</p>${this.choice('Request size',f.size,['custom',...presets,'auto'],v=>f.size=v)}
   ${f.size==='custom'?html`${this.numeric('width','Output width')}${this.numeric('height','Output height')}`:nothing}
   <p>Generation metadata: 512–3840, or 512–2048 for Fast/Instant; multiples of 16. Preset and auto dimensions remain unqualified. No automatic rounding.</p>
   ${this.numeric('strength','Transformation strength')}${!d.operation.startsWith('transform')&&!d.operation.startsWith('inpaint')&&f.strength?inactive('strength'):nothing}
   <en-button @click=${(ev:Event)=>action(ev,()=>{f.strength=d.operation.startsWith('inpaint')?'1':'0.8';this.touch();})}>Use operation strength default</en-button>
   <h2>Explicit inputs</h2><p>Selecting a layer never attaches it automatically.</p>
   <en-button id="request-visible-source" @click=${(ev:Event)=>action(ev,()=>this.source(this.editor.view.document?.image?.compositeAssetId??'','visible-document'))}>Attach visible document snapshot</en-button>
   <en-button id="request-source" @click=${(ev:Event)=>action(ev,()=>this.source(this.editor.view.image?.layers.find(l=>l.id===this.editor.view.selected[0])?.assetId??'','asset'))}>Attach selected image asset</en-button>
   ${d.source?html`<p>Source ${d.source.assetId} · version ${d.source.version} · ${d.source.width} × ${d.source.height} · ${d.source.scope}</p>${inactive('source')}`:nothing}
   <en-button id="request-mask" @click=${(ev:Event)=>action(ev,()=>this.mask())}>Attach selected layer edit mask</en-button>
   ${d.mask?html`<p>Mask ${d.mask.assetId} · white edits, black keeps · ${d.mask.empty?'empty':d.mask.full?'entire source':'partial coverage'}</p>${inactive('mask')}<en-card><p>Mask frame: ${d.mask.frame?'document '+d.mask.frame.document.width+' × '+d.mask.frame.document.height+', layer '+d.mask.frame.layer.id+' version '+d.mask.frame.layer.version:'unresolved legacy draft; reattach the mask'}. Source scope: ${d.source?.scope??'unattached'}. Equal dimensions alone do not prove alignment.</p><p>Only an identical pixel grid can be confirmed here. For a document mask on a moved image, explicitly attach the visible document snapshot, then reattach the mask. Original image bytes and mask pixels stay unchanged.</p><en-button id="request-mask-alignment" @click=${(ev:Event)=>action(ev,()=>this.confirmAlignment())}>Confirm source and mask alignment</en-button></en-card><en-button @click=${(ev:Event)=>action(ev,()=>{d.mask!.fullAcknowledged=true;this.touch();})}>Confirm entire source can change</en-button>`:nothing}
   <en-accordion-item id="request-adapters" tabindex="-1" label="Adapter version drafts"><p>Local adapter eligibility is unavailable until the adapter library is implemented. Unknown versions remain blocked.</p><en-text-field label="Adapter version" .value=${this.adapterVersion} @en-input=${(ev:Event)=>field(ev,v=>this.adapterVersion=v)}></en-text-field><en-text-field label="Adapter SHA-256" .value=${this.adapterHash} @en-input=${(ev:Event)=>field(ev,v=>this.adapterHash=v)}></en-text-field><en-number-field label="Adapter scale" .value=${this.adapterScale} @en-input=${(ev:Event)=>field(ev,v=>this.adapterScale=v)}></en-number-field><en-button @click=${(ev:Event)=>action(ev,()=>{if(!/^[A-Za-z0-9_-]{1,128}$/.test(this.adapterVersion)||!/^sha256:[a-f0-9]{64}$/.test(this.adapterHash))throw Error('Enter a version identity and sha256 digest.');d.adapters.push({version:this.adapterVersion,hash:this.adapterHash,scale:this.adapterScale});this.touch();})}>Add explicit adapter version</en-button>${d.adapters.map((a,i)=>html`<p>${i+1}. ${a.version} · scale ${a.scale}</p>`)}${d.adapters.length?inactive('adapters'):nothing}</en-accordion-item>
   ${d.source&&f.size==='custom'?html`<en-card>${previewURL?html`<svg class="request-resize-preview" role="img" aria-label="Preview of the request source with the proposed stretch mapping" viewBox=${'0 0 '+Math.max(1,Number(f.width)||1)+' '+Math.max(1,Number(f.height)||1)}><image href=${previewURL} width=${Math.max(1,Number(f.width)||1)} height=${Math.max(1,Number(f.height)||1)} preserveAspectRatio="none"></image></svg>`:html`<p>Loading source preview before resize confirmation.</p>`}<p>Request resize: ${d.source.width} × ${d.source.height} → ${f.width} × ${f.height}. Stretch mapping changes the request aspect ratio when ratios differ; original pixels remain retained.</p><en-button ?disabled=${!previewURL} @click=${(ev:Event)=>action(ev,()=>{d.conversion={from:{width:d.source!.width,height:d.source!.height},to:{width:Number(f.width),height:Number(f.height)},mapping:'stretch',approved:true};this.touch();this.message='Request resize mapping confirmed.';})}>Confirm this request resize mapping</en-button></en-card>`:nothing}
   <en-button id="request-document" @click=${(ev:Event)=>action(ev,()=>{e.revision=this.editor.view.document!.revision;this.touch();this.message='Request document revision confirmed.';})}>Review current request document</en-button>
   ${this.issues.length?html`<en-validation-summary id="request-errors" tabindex="-1" heading="Request needs attention" .items=${this.issues.map(i=>({target:'request-'+i.field,message:i.code+': '+i.message}))} @en-action=${(ev:Event)=>{ev.preventDefault();const target=(ev as CustomEvent).detail?.data?.target;this.host.querySelector<HTMLElement>('#'+CSS.escape(target==='request-prompt'?'prompt':target??'request-width'))?.focus();}}></en-validation-summary>`:nothing}
   <en-button id="prepare-request" ?disabled=${this.busy||this.composing||!this.editor.view.ready} @click=${(ev:Event)=>action(ev,()=>this.prepare())}>Review exact request</en-button>
   ${r?html`<en-card id="request-review" tabindex="-1"><h2>Immutable request review</h2><p>${r.endpoint} · ${r.request.kind}</p><p>Safety checker enabled. Asynchronous delivery policy (sync_mode false).</p><p>Prompt ${r.prompt.hash} · ${r.prompt.byteLength} bytes</p><p>Destination: retained candidates. Native text remains editable. Privacy: minimum-retention policy is required, provider behavior is unqualified; production support stays denied.</p><p>Published ${r.estimate.source}: USD ${r.estimate.rate} per ${r.estimate.unit}, count ${r.estimate.count}. Total and actual spend are unknown; billing-area rounding, expansion and batch/cancel fees remain unresolved.</p><en-accordion-item label="Exact request provenance"><pre>${JSON.stringify(r,null,2)}</pre><en-textarea label="Frozen prompt" .value=${e.text} readOnly .rows=${4}></en-textarea></en-accordion-item><en-button id="accept-request" ?disabled=${this.busy||this.accepted} @click=${(ev:Event)=>action(ev,()=>this.accept())}>Accept this exact review locally</en-button><en-button variant="secondary" @click=${(ev:Event)=>action(ev,()=>{this.review=null;this.intent++;this.changed();void this.host.updateComplete.then(()=>this.host.querySelector<HTMLElement>('#prepare-request')?.focus());})}>Close request review</en-button></en-card>`:nothing}
  </section>`;
 }
}
