import {html,nothing} from 'lit';
import type {LitElement} from 'lit';
import type {EditorClient} from '../state/editor-client.js';
import type {Asset} from '../protocol/assets.js';
import {hash} from '../request/core.js';
import type {Source,Seed} from '../request/core.js';
import type {V45EditDraft,V45PreparedInputs,V45EditRequest} from '../request/family.js';
import {preparedInputsShape} from '../request/v45-family-edit.js';
import {V45_EDIT_PRESETS,V45_EDIT_PRESET_DIMENSIONS} from '../request/v45-edit.js';
import {v45EditInputsPlan} from '../protocol/v45-inputs.js';
import {canonical} from '../protocol/json.js';
import {ControlAdapter} from './adapters.js';
import {UIModelOwner} from './model-owner.js';
import {createOwnedModel,modelPayloadBytes,type OwnedModel} from '../observability/model-memory.js';
import {v45InputCalculation,v45InputBytes,ownV45Input,formatV45Input,joinV45Input,ownV45Fingerprint,type V45InputFingerprint} from './request-v45-memory.js';

type OriginalInputs=Pick<V45EditDraft,'operation'|'source'|'mask'|'references'>;
type Scope='single-layer'|'selected-layers'|'visible-document';
export type V45EditHooks={draft:()=>V45EditDraft|undefined;owns:()=>()=>boolean;changed:()=>void;hold:(expected:V45EditDraft)=>()=>void;mutate:(expected:V45EditDraft,growth:unknown,change:(next:V45EditDraft)=>void)=>V45EditDraft;error:(error:unknown)=>void;invalidateMapping:()=>void};
const originals=(d:OriginalInputs)=>({source:d.source,mask:d.mask,references:d.references});
const fingerprintValue=(draft:V45EditDraft)=>({operation:draft.operation,...originals(draft)});
const ownFingerprint=(draft:V45EditDraft)=>ownV45Fingerprint(fingerprintValue(draft),canonical,hash);
const dimensions=(r:{width:number;height:number})=>r.width+' × '+r.height;
const seedLabel=(seed:Seed)=>seed.kind==='integer'?seed.decimal:'Random';

/** Decode the public preparation result without substituting transport rasters
 * for the retained original capture, reference order, or R16 authoring mask. */
export function v45PreparedInputsFromAsset(draft:OriginalInputs,asset:Asset,manifest:unknown):V45PreparedInputs{return v45InputCalculation({draft,asset,manifest},()=>decodePreparedInputs(draft,asset,manifest));}
function decodePreparedInputs(draft:OriginalInputs,asset:Asset,manifest:unknown):V45PreparedInputs{
 if(draft.operation==='transform-v45'&&draft.mask!==null)throw Error('Remove the retained mask explicitly before preparing an unmasked edit.');
 const raster=asset.raster,root=manifest as import('../protocol/raster.js').RasterManifest,plan=root?.plan;
 v45EditInputsPlan(plan);
 if(asset.qualification!=='canonical-raster'||asset.availability!=='available'||asset.safety!=='safe'||!raster||raster.role!=='composite'||canonical(plan.original)!==canonical({source:draft.source,mask:draft.operation==='inpaint-v45'?draft.mask:null})||canonical(plan.references.map(r=>r.original))!==canonical(draft.references))throw Error('Prepared inputs do not match the exact original source, mask and ordered references.');
 const encoded=canonical(root);if(encoded.length>65536||hash(encoded)!==raster.manifest.hash||String(new TextEncoder().encode(encoded).byteLength)!==raster.manifest.byteLength)throw Error('Prepared raster manifest identity changed.');
 if(root.width!==raster.width||root.height!==raster.height||root.pipeline!==raster.pipeline||root.schemaVersion!==raster.schemaVersion||canonical(root.pixels)!==canonical(raster.pixels))throw Error('Prepared raster manifest does not match the registered source asset.');
 if(plan.assetBindings.source!==draft.source?.assetId||plan.assetBindings.mask!==(draft.operation==='inpaint-v45'?draft.mask?.assetId??null:null)||canonical(plan.assetBindings.references)!==canonical(draft.references.map(r=>r.assetId)))throw Error('Prepared input bindings changed.');
 if(canonical(plan.requestPlan)!==canonical(draft.operation==='inpaint-v45'?draft.mask?.requestPlan??null:null))throw Error('Prepared mask mapping changed.');
 const value:V45PreparedInputs={assetId:asset.id,version:asset.version,manifest:raster.manifest,source:{blob:asset.blob,pixels:raster.pixels,manifest:raster.manifest,pixelIdentity:raster.pixelIdentity,width:raster.width,height:raster.height},mask:plan.mask,references:plan.references.map(r=>r.input)};
 preparedInputsShape(value);
 if(draft.operation==='transform-v45'&&(value.mask!==null||value.source.width!==draft.source?.width||value.source.height!==draft.source?.height||value.source.pixels.hash!==draft.source?.pixels.hash)||draft.operation==='inpaint-v45'&&(!value.mask||value.mask.sourcePixels.hash!==value.source.pixels.hash||value.mask.width!==value.source.width||value.mask.height!==value.source.height||value.mask.editPixels<=0||value.mask.keepPixels<=0)||value.references.some((ref,i)=>ref.width!==draft.references[i].width||ref.height!==draft.references[i].height||ref.pixels.hash!==draft.references[i].pixels.hash))throw Error('Prepared raster descriptors do not match the reviewed grids and coverage.');
 if(draft.operation==='inpaint-v45'){const p=draft.mask?.requestPlan,grid=p?.kind==='request-raster-plan-2'?p.requestGrid:p?.expectedOutput;if(!p||!grid||grid.width!==value.source.width||grid.height!==value.source.height||p.expectedOutput.width!==grid.width||p.expectedOutput.height!==grid.height)throw Error('Prepared masked source does not match its approved transport grid.');}
 return value;
}

type InputView={draft:V45EditDraft;guard:V45InputFingerprint;key:string;formatted:string|null;prepared:V45PreparedInputs|null};
type PendingInput={draft:V45EditDraft;key:string;value:V45PreparedInputs;formatted:string;owns:()=>boolean;fingerprint:OwnedModel<V45InputFingerprint>;format:OwnedModel<string>};
export class V45EditInputsEditing{
 private adapter=new ControlAdapter();private epoch=0;private busy=false;private pendingDispatch:object|null=null;private pending:PendingInput|null=null;private view:InputView|null=null;private models:UIModelOwner;private draftTokens=new WeakMap<V45EditDraft,number>();private nextDraftToken=0;private blocked=false;private releasePending:Promise<void>|undefined;
 constructor(private host:LitElement,private editor:EditorClient,private hooks:V45EditHooks){this.models=new UIModelOwner(host,editor,'request-v45-inputs','prompt');}
 get lifecycle(){return {...this.models.lifecycle,blocked:this.blocked,pendingDispatch:this.pendingDispatch!==null};}
 dispose(){if(this.releasePending)return this.releasePending;this.blocked=true;this.epoch++;this.busy=false;this.pendingDispatch=null;this.pending=null;this.view=null;this.adapter.invalidate();const work=this.models.release().then(()=>{this.blocked=false;},error=>{throw error;}).finally(()=>{this.releasePending=undefined;});this.releasePending=work;void work.catch(()=>{});return work;}
 private clearPending(){this.pending=null;this.models.clear('pending');}
 private changed(){this.host.requestUpdate();}
 private viewFor(draft:V45EditDraft){if(this.blocked||this.models.releasing)throw new DOMException('Prepared inputs are releasing.','AbortError');if(this.view?.draft===draft&&this.view.prepared===draft.preparedInputs&&this.view.guard.matches(fingerprintValue(draft)))return this.view;if(this.models.lifecycle.pending>=64)throw Error('Prepared input rendering is still pending.');
  const release=this.hooks.hold(draft);let key:OwnedModel<V45InputFingerprint>|undefined,format:OwnedModel<string>|undefined,owned:OwnedModel<InputView>|undefined;
  try{key=ownFingerprint(draft);if(draft.preparedInputs)format=formatV45Input(draft.preparedInputs);const view={draft,guard:key.value,key:key.value.key,formatted:format?.value??null,prepared:draft.preparedInputs};owned=joinV45Input(view,[key,...(format?[format]:[])],release);this.models.replace('view',owned);this.view=view;return view;}catch(error){if(owned)owned.release();else{key?.release();format?.release();release();}throw error;}
 }
 private draftToken(draft:V45EditDraft){let token=this.draftTokens.get(draft);if(token===undefined){token=++this.nextDraftToken;this.draftTokens.set(draft,token);}return token;}
 private owner(draft:V45EditDraft){const token=this.draftToken(draft),guard=this.viewFor(draft).guard,owns=this.hooks.owns(),epoch=this.epoch,documentId=this.editor.view.document?.id,revision=this.editor.view.document?.revision,session=this.editor.session,identity=session.identity(),owner=this.editor.draftOwner;return ()=>{const current=this.hooks.draft();return !!current&&!this.blocked&&epoch===this.epoch&&owns()&&this.draftTokens.get(current)===token&&guard.matches(fingerprintValue(current))&&this.editor.draftOwner===owner&&this.editor.session===session&&session.identity()===identity&&this.editor.view.document?.id===documentId&&this.editor.view.document?.revision===revision;};}
 private mutate(draft:V45EditDraft,growth:unknown,change:(next:V45EditDraft)=>void){const next=this.hooks.mutate(draft,growth,candidate=>{change(candidate);candidate.preparedInputs=null;});this.clearPending();this.changed();return next;}
 private action(event:Event,work:(draft:V45EditDraft,owns:()=>boolean)=>Promise<void>|void){if(this.blocked||this.pendingDispatch||this.busy)return;const draft=this.hooks.draft();if(!draft)return;let entryRelease:(()=>void)|undefined,modelRelease:(()=>void)|undefined;
  try{this.viewFor(draft);entryRelease=this.hooks.hold(draft);modelRelease=this.models.hold();}catch(error){entryRelease?.();modelRelease?.();this.hooks.error(error);return;}
  const owns=this.owner(draft),dispatch={};this.pendingDispatch=dispatch;let started=false,released=false;const release=()=>{if(released)return;released=true;entryRelease!();modelRelease!();};
  try{this.adapter.action(event,()=>{started=true;if(this.pendingDispatch!==dispatch||!owns()||this.busy){if(this.pendingDispatch===dispatch)this.pendingDispatch=null;release();return;}this.pendingDispatch=null;const epoch=this.epoch;let task:Promise<void>;
   try{task=this.models.run(async()=>{if(!owns())return;this.busy=true;this.changed();await work(draft,owns);});}catch(error){release();if(owns())this.hooks.error(error);return;}
   void task.catch(error=>{if(owns())this.hooks.error(error);}).finally(()=>{release();if(this.epoch===epoch){this.busy=false;this.changed();}}).catch(()=>{});
  });}catch(error){this.pendingDispatch=null;release();throw error;}setTimeout(()=>{if(!started){if(this.pendingDispatch===dispatch)this.pendingDispatch=null;release();}},0);
 }
 private captureReference(draft:V45EditDraft,scope:Scope,owns:()=>boolean){return this.models.run(async()=>{if(this.blocked||!owns())return;const entryRelease=this.hooks.hold(draft);let releaseDocument:(()=>void)|undefined,selection:ReturnType<UIModelOwner['temporary']>|undefined;
  try{const limit=draft.operation==='inpaint-v45'?3:4;if(draft.references.length>=limit)throw Error('This operation supports at most '+limit+' ordered references.');const document=this.editor.view.document!;releaseDocument=this.editor.pinViewModels(document);selection=this.models.temporary(modelPayloadBytes(this.editor.view.selected)+256);const layerIds=scope==='visible-document'?[]:scope==='single-layer'?this.editor.view.selected.slice(0,1):[...this.editor.view.selected];if(scope!=='visible-document'&&!layerIds.length)throw Error('Select reference layers before capturing.');
   await this.editor.withCommandEvents({type:'PrepareRequestSource',scope,layerIds},events=>{if(!owns())return;const event=events.find(e=>e.type==='AssetRegistered');if(event?.type!=='AssetRegistered')throw Error('Reference capture is unavailable.');const a=event.payload.asset,r=a.raster;if(a.qualification!=='canonical-raster'||!r||r.role==='mask')throw Error('Reference capture must retain a canonical rendered image.');
    const reference=ownV45Input<Source>({assetId:a.id,version:a.version,blob:a.blob,pixels:r.pixels,width:r.width,height:r.height,scope,documentRevision:document.revision,capture:r.manifest});try{this.mutate(draft,reference.value,next=>{next.references.push(structuredClone(reference.value));});}finally{reference.release();}
   },document);
  }finally{selection?.release();releaseDocument?.();entryRelease();}
 });}
 private move(draft:V45EditDraft,index:number,delta:number){const target=index+delta;if(index<0||index>=draft.references.length||target<0||target>=draft.references.length)return;this.mutate(draft,null,next=>{[next.references[index],next.references[target]]=[next.references[target],next.references[index]];});}
 private prepare(draft:V45EditDraft,owns:()=>boolean){return this.models.run(async()=>{if(this.blocked||!owns())return;const releaseEntry=this.hooks.hold(draft);try{
  if(draft.operation==='transform-v45'&&draft.mask!==null)throw Error('Remove the retained mask explicitly before preparing an unmasked edit.');if(!draft.source?.capture)throw Error('Capture the original rendered source first.');if(draft.operation==='inpaint-v45'&&!draft.mask?.requestPlan)throw Error('Approve the independent request mask and transport mapping first.');
  const asset=await this.editor.withCommandEvents({type:'PrepareV45EditInputs',...originals(draft),source:draft.source},events=>{if(!owns())return;const event=events.find(e=>e.type==='AssetRegistered');if(event?.type!=='AssetRegistered')throw Error('Prepared edit input asset is unavailable.');return ownV45Input(event.payload.asset);},null);if(!asset)return;
  try{const manifest=await this.models.read<unknown>('/api/v1/assets/'+asset.value.id+'/raster',owns,65536);try{if(!owns())return;
   let descriptor:OwnedModel<V45PreparedInputs>|undefined,key:OwnedModel<V45InputFingerprint>|undefined,format:OwnedModel<string>|undefined,joined:OwnedModel<PendingInput>|undefined,hold:(()=>void)|undefined,installed=false;
   try{const allowance=v45InputBytes({asset:asset.value,manifest:manifest.value})*2+4096;descriptor=createOwnedModel('request-v45-prepared',allowance,()=>{const value=v45PreparedInputsFromAsset(draft,asset.value,manifest.value);v45InputBytes(value);return structuredClone(value);},'prompt');key=ownFingerprint(draft);format=formatV45Input(descriptor.value);hold=this.hooks.hold(draft);const pending={draft,key:key.value.key,value:descriptor.value,formatted:format.value,owns,fingerprint:key,format};joined=joinV45Input(pending,[descriptor,key,format],hold);this.models.replace('pending',joined);this.pending=pending;installed=true;this.changed();}catch(error){if(installed)throw error;if(joined)joined.release();else{descriptor?.release();key?.release();format?.release();hold?.();}throw error;}
  }finally{manifest.release();}}finally{asset.release();}
 }finally{releaseEntry();}});}
 private confirm(draft:V45EditDraft){const p=this.pending;if(!p||p.draft!==draft||!p.owns())throw Error('Input preparation changed. Prepare the current inputs again.');const releaseKey=p.fingerprint.pin(),releaseFormat=p.format.pin();let transferred=false;
  try{const next=this.hooks.mutate(draft,p.value,value=>{value.preparedInputs=structuredClone(p.value);});const releaseEntry=this.hooks.hold(next),view={draft:next,guard:p.fingerprint.value,key:p.key,formatted:p.formatted,prepared:next.preparedInputs};const owned=joinV45Input(view,[joinV45Input(p.fingerprint.value,[],releaseKey),joinV45Input(p.format.value,[],releaseFormat)],releaseEntry);try{this.models.replace('view',owned);}catch(error){owned.release();throw error;}this.view=view;transferred=true;this.clearPending();this.changed();}finally{if(!transferred){releaseKey();releaseFormat();}}
 }
 render(){const draft=this.hooks.draft();if(this.blocked||this.models.releasing)return nothing;if(!draft){this.clearPending();this.view=null;this.models.clear('view');return nothing;}let view:InputView;try{view=this.viewFor(draft);}catch{return html`<en-alert>Prepared input review is unavailable until its local memory allowance can be admitted.</en-alert>`;}if(this.pending&&(!this.pending.owns()||this.pending.draft!==draft))this.clearPending();
  const limit=draft.operation==='inpaint-v45'?3:4,pending=this.pending,value=pending?.value??draft.preparedInputs,owns=this.owner(draft),act=(event:Event,work:(d:V45EditDraft,current:()=>boolean)=>void|Promise<void>)=>{if(owns())this.action(event,work);};
  return html`<section id="request-v45-inputs" aria-label="Ideogram v4.5 original and prepared inputs" aria-busy=${String(this.busy)}><h3>Ordered reference captures</h3><p>References are attached only by these explicit capture actions. Order and repeated references are preserved. ${draft.references.length} of ${limit} attached.</p><en-toolbar label="Capture reference" keyboard-navigation="tab">${(['single-layer','selected-layers','visible-document'] as const).map((scope,index)=>html`<en-button id=${'request-v45-reference-'+scope} ?disabled=${this.busy||draft.references.length>=limit} @click=${(event:Event)=>act(event,(d,current)=>this.captureReference(d,scope,current))}>${['Capture selected layer as reference','Capture selected layers as reference','Capture visible document as reference'][index]}</en-button>`)}</en-toolbar>
  <ol>${draft.references.map((ref,index)=>html`<li><p>Reference ${index+1}: ${ref.scope} · ${dimensions(ref)} · captured revision ${ref.documentRevision}. Asset ${ref.assetId}; version ${ref.version}; pixels ${ref.pixels.hash}.</p><en-button id=${'request-v45-reference-up-'+index} ?disabled=${this.busy||index===0} @click=${(event:Event)=>act(event,d=>this.move(d,index,-1))}>Move reference ${index+1} earlier</en-button><en-button id=${'request-v45-reference-down-'+index} ?disabled=${this.busy||index===draft.references.length-1} @click=${(event:Event)=>act(event,d=>this.move(d,index,1))}>Move reference ${index+1} later</en-button><en-button id=${'request-v45-reference-remove-'+index} ?disabled=${this.busy} @click=${(event:Event)=>act(event,d=>{this.mutate(d,null,next=>{next.references.splice(index,1);});})}>Remove reference ${index+1}</en-button></li>`)}</ol>
  <h3>Prepare provider inputs locally</h3><p>Original source: ${draft.source?dimensions(draft.source):'not captured'}. ${draft.operation==='inpaint-v45'?'Original R16 authoring coverage stays white-edit. Preparation maps that coverage conservatively and produces a separate opaque black-edit PNG: black edits, white keeps. Empty or all-edit transport masks are refused.':'The original full source grid is retained for regular unmasked editing.'} No upload or provider call occurs here.</p>
  ${draft.operation==='transform-v45'&&draft.mask?html`<en-alert announcement="none">This saved unmasked draft contains a mask. It remains retained until explicitly removed.</en-alert><en-button id="request-v45-remove-unexpected-mask" ?disabled=${this.busy} @click=${(event:Event)=>act(event,d=>{this.mutate(d,null,next=>{next.mask=null;});})}>Remove saved mask from this unmasked draft</en-button>`:nothing}
  <en-button id="request-v45-prepare-inputs" ?disabled=${this.busy||!draft.source||draft.operation==='inpaint-v45'&&!draft.mask?.requestPlan} @click=${(event:Event)=>act(event,(d,current)=>this.prepare(d,current))}>Prepare source, mask and ordered references</en-button>
  ${value?html`<en-card id="request-v45-input-review" tabindex="-1"><h4>${pending?'Review prepared input descriptors':'Confirmed prepared input descriptors'}</h4><p>Original ${draft.source?dimensions(draft.source):'unavailable'}; prepared source ${dimensions(value.source)}. Provider output size setting: ${draft.fields.size}. Actual returned geometry is unavailable until separately permitted output bytes are measured.</p>${value.mask?html`<p>Separate black-edit transport mask: ${dimensions(value.mask)}; ${value.mask.editPixels} black edit pixels and ${value.mask.keepPixels} white keep pixels. It is bound to source pixels ${value.mask.sourcePixels.hash}. The original R16 mask and source are retained separately.</p>`:nothing}<p>${value.references.length} prepared references in the explicit order above. Input preparation is not production eligibility.</p><pre aria-label="Exact prepared input descriptors">${pending?.formatted??view.formatted}</pre>${pending?html`<en-button id="request-v45-confirm-inputs" ?disabled=${this.busy} @click=${(event:Event)=>act(event,d=>this.confirm(d))}>Confirm these exact prepared inputs</en-button>`:nothing}</en-card>`:nothing}
  <en-alert announcement="none">Provider uploads and dispatch remain blocked. Output safety is unknown and results remain withheld from ordinary display, adoption and export.</en-alert></section>`;
 }
}

export function renderV45EditSettings(draft:V45EditDraft,options:{disabled:boolean;error?:(field:string)=>string;change:(event:Event,patch:(value:string)=>Partial<V45EditDraft['fields']>,mapping:boolean)=>void}){
 const fields=draft.fields,masked=draft.operation==='inpaint-v45',change=(key:keyof typeof fields,mapping=false)=>(event:Event)=>{if(!options.disabled)options.change(event,value=>({[key]:value}),mapping);};
 const number=(key:'width'|'height',label:string)=>html`<en-number-field id=${'request-'+key} label=${label} .value=${fields[key]} .error=${options.error?.(key)??''} ?disabled=${options.disabled} @en-input=${change(key,masked)} @en-change=${change(key,masked)}></en-number-field>`;
 return html`<section id="request-v45-edit-settings" aria-label="Ideogram v4.5 edit settings"><p>Ideogram v4.5 edit · ${masked?'masked high':'unmasked regular'} precision · medium quality. Other precision and quality combinations are not qualified.</p><en-select id="request-precision" label="Edit precision" .value=${fields.precision} ?disabled=${options.disabled} @en-change=${change('precision')}>${fields.precision!==(masked?'high':'regular')?html`<en-select-option value=${fields.precision}>Unsupported saved precision: ${fields.precision}</en-select-option>`:nothing}<en-select-option value=${masked?'high':'regular'}>${masked?'High (masked)':'Regular (unmasked)'}</en-select-option></en-select><en-select id="request-quality" label="Quality" .value=${fields.quality} ?disabled=${options.disabled} @en-change=${change('quality')}>${fields.quality!=='medium'?html`<en-select-option value=${fields.quality}>Unsupported saved quality: ${fields.quality}</en-select-option>`:nothing}<en-select-option value="medium">Medium</en-select-option></en-select>
 <en-number-field id="request-count" label="Output count (1–4)" .value=${fields.count} .error=${options.error?.('count')??''} ?disabled=${options.disabled} @en-input=${change('count')} @en-change=${change('count')}></en-number-field><en-text-field id="request-seed" label="Exact seed (empty means Random)" .value=${fields.seed} .error=${options.error?.('seed')??''} ?disabled=${options.disabled} @en-input=${change('seed')}></en-text-field>
 <en-select id="request-size" label=${masked?'Provider output size (Auto required)':'Requested output size'} .value=${fields.size} .error=${options.error?.('size')??''} ?disabled=${options.disabled} @en-change=${change('size')}>${masked&&fields.size!=='auto'?html`<en-select-option value=${fields.size}>Unsupported saved size: ${fields.size}</en-select-option>`:nothing}<en-select-option value="auto">Auto</en-select-option>${!masked?html`${V45_EDIT_PRESETS.map(size=>html`<en-select-option value=${size}>${size} · ${dimensions({width:V45_EDIT_PRESET_DIMENSIONS[size][0],height:V45_EDIT_PRESET_DIMENSIONS[size][1]})}</en-select-option>`)}<en-select-option value="custom">Custom</en-select-option>`:nothing}</en-select>
 ${masked?html`<h4>Prepared transport grid</h4><p>These explicit dimensions control source and mask preparation, independently of the provider Auto setting. Crop, padding and coverage require a fresh mapping preview after changes.</p>${number('width','Prepared transport width')}${number('height','Prepared transport height')}`:fields.size==='custom'?html`${number('width','Requested output width')}${number('height','Requested output height')}<p>Each dimension must be at least 256 and a multiple of 32; area at most 4,194,304 pixels and aspect at most 6:1. Values are not rounded.</p>`:nothing}
 <p>Output format is provider-controlled. Requested dimensions do not establish actual returned geometry. Safety admission and production upload eligibility remain blocked.</p></section>`;
}

export function renderV45EditReview(request:V45EditRequest){return html`<section id="request-v45-edit-review-contract" aria-label="Ideogram v4.5 edit request contract"><p>${request.kind==='inpaint-v45'?'High masked':'Regular unmasked'} precision, medium quality; ${request.settings.count} output(s); exact seed ${seedLabel(request.settings.seed)}.</p><p>Original captured source ${dimensions(request.source)}; prepared source ${dimensions(request.preparedInputs.source)}; requested output ${dimensions(request.modelRequest.requested)}. Actual returned dimensions are unavailable.</p><p>${request.references.length} references in explicit order.${request.preparedInputs.mask?' Provider transport is black-edit; original white-edit R16 coverage remains retained.':''} Format is provider-controlled; no returned prompt or timing evidence is invented.</p><p>Safety is unknown; display, adoption, export and production dispatch remain blocked.</p></section>`;}
