import {html,svg,nothing} from 'lit';
import type {LitElement} from 'lit';
import type {EditorClient} from '../state/editor-client.js';
import type {Asset} from '../protocol/assets.js';
import type {Source} from '../request/core.js';
import {hash} from '../request/core.js';
import {canonical} from '../protocol/json.js';
import {validateRequestSourceCapture,type RequestSourceCapture} from '../protocol/request-edits.js';
import type {TextTreatmentChoice,TextTreatmentReviewIntent} from '../request/text-treatment.js';
import {createOwnedModel,modelPayloadBytes,reserveModelBytes,type OwnedModel,type ModelPayload} from '../observability/model-memory.js';
import {PromptReaderCleanupError} from '../observability/prompt-memory.js';
import {createDisplayPreviewURL,withDisplaySource,revokeDisplayPreviewURL,validateDisplayImage} from '../observability/display-preview.js';
import {displayImage} from './display-image.js';
import {ControlAdapter} from './adapters.js';

export type TextTreatmentDraft={operation:string;prompt:{mode:'plain'|'raw'|'composition'};source?:Source|null;mask?:unknown};
export type TextTreatmentSemantics={key:string;items:readonly {id:string;label:string}[];approvedExcludedIds:readonly string[]|null};
export type TextTreatmentHooks={
 draft:()=>TextTreatmentDraft|undefined;entryKey:()=>string|undefined;hold:(expected:TextTreatmentDraft)=>()=>void;owns:()=>()=>boolean;
 /** Synchronously borrowed, complete semantic TEXT inventory. Labels are display-only. */
 semantic:()=>TextTreatmentSemantics;
 /** Must prospectively admit the successor, clear mask and preparedInputs, invalidate its request review and return the exact new draft. */
 attachAlternateSource:(expected:TextTreatmentDraft,source:Source|null)=>TextTreatmentDraft;
 openComposition:()=>void;error:(error:unknown)=>void;
};
type NativeRow={id:string;version:string;name:string;visible:boolean;locked:boolean};
type Context={document:{id:string;revision:string;width:number;height:number;image:unknown};entryKey:string;operation:string;mode:TextTreatmentDraft['prompt']['mode'];beforeSource:Source|null;native:NativeRow[];visibleIds:string[];semantic:{key:string;items:{id:string;label:string}[];approvedExcludedIds:string[]|null}};
type Picture={source:Source;url:string;loaded:boolean};
type Review={context:OwnedModel<Context>;captures:OwnedModel<Source>[];draft:TextTreatmentDraft;current:()=>boolean;releaseEntry:()=>void;releaseForm:()=>void;choice:TextTreatmentChoice;baseline:Source|null;afterSource:Source|null;beforeIds:string[];afterIds:string[];pictures:{baseline:Picture|null;before:Picture|null;after:Picture|null};approved:OwnedModel<TextTreatmentReviewIntent>|null};
type Retirement={cleanups:(()=>void)[];pending:Promise<void>|null;failed:boolean};
const MAX_MODEL=512*1024,MAX_FORM=512*1024,ID=/^[A-Za-z0-9_-]{1,128}$/;
const generate=(operation:string)=>['generate','fast','instant','generate-adapters','generate-v45'].includes(operation);
const same=(a:unknown,b:unknown)=>canonical(a)===canonical(b);
const stale=()=>new DOMException('Text treatment review changed. Review the current request again.','AbortError');

/** Metadata selection only. Pixels are captured separately by a public command. */
export function textTreatmentUISelection(beforeIds:readonly string[],visibleIds:readonly string[],retainedIds:readonly string[],kind:TextTreatmentChoice['kind']){
 if(beforeIds.length>100||visibleIds.length>100||retainedIds.length>100||[...beforeIds,...visibleIds,...retainedIds].some(id=>!ID.test(id))||new Set(beforeIds).size!==beforeIds.length||new Set(visibleIds).size!==visibleIds.length||new Set(retainedIds).size!==retainedIds.length)throw Error('Text treatment layer inventory is invalid.');
 if(beforeIds.some(id=>!visibleIds.includes(id)))throw Error('The previous source contains a hidden or unavailable layer. Capture it again explicitly.');
 return beforeIds.filter(id=>kind!=='native-overlay'||!retainedIds.includes(id));
}

/** A separate adjunct; no legacy draft, provider payload or composition is rewritten. */
export class TextTreatmentEditing{
 private adapter=new ControlAdapter();private disposed=false;private epoch=0;private busy=false;private scheduled=false;private task:Promise<void>|null=null;private actions=new Set<Promise<void>>();private abort:AbortController|null=null;
 private cleanup=new Set<PromptReaderCleanupError>();private retired=new Set<Retirement>();private form:ModelPayload|null=null;private review:Review|null=null;private rendered:OwnedModel<Context>|null=null;private uiOwner:unknown;private uiSession:unknown;private uiDocument='';private uiEntry='';
 private kind:TextTreatmentChoice['kind']|''='';private retained=new Set<string>();private hide=new Set<string>();private excluded=new Set<string>();private placement:'current-document'|'new-document'='new-document';private duplicate=false;
 private mode:'before'|'after'|'reveal'='before';private reveal='50';private percentage=50;private message='Choose how native text and semantic text enter this request.';
 constructor(private host:LitElement,private editor:EditorClient,private hooks:TextTreatmentHooks){}
 private changed(){this.host.requestUpdate();}
 private admit(){if(this.retired.size>=8)throw Error('Text treatment rendering is still pending.');this.form??=reserveModelBytes('text-treatment-controls',MAX_FORM,16,'prompt');}
 private remember(error:unknown){if(error instanceof PromptReaderCleanupError)this.cleanup.add(error);else if(error instanceof AggregateError)for(const cause of error.errors)this.remember(cause);}
 /** Eight retiring publications plus the live review/context/form and one active preparation permit bounded teardown without new admission. */
 private renderComplete(refresh=false){return Promise.resolve().then(()=>{if(refresh)this.changed();return this.host.updateComplete;});}
 private runRetirement(record:Retirement,committed:Promise<unknown>){
  if(record.pending)return record.pending;
  const task=committed.then(()=>{const failed:(()=>void)[]=[],errors:unknown[]=[];for(const cleanup of record.cleanups)try{cleanup();}catch(error){failed.push(cleanup);errors.push(error);}record.cleanups=failed;if(errors.length)throw new AggregateError(errors,'Text treatment retirement cleanup failed.');this.retired.delete(record);}).catch(error=>{record.failed=true;try{this.hooks.error(error);}catch{/* Reporting cannot discard the retained cleanup owner. */}}).finally(()=>{record.pending=null;});
  record.pending=task;return task;
 }
 private retireCleanups(cleanups:(()=>void)[],committed:Promise<unknown>=this.renderComplete()){const record:Retirement={cleanups,pending:null,failed:false};this.retired.add(record);this.runRetirement(record,committed);return record;}
 private retire(review:Review,committed=this.renderComplete()){
  const {context,captures,approved,releaseEntry,releaseForm}=review;
  this.retireCleanups([()=>context.release(),...captures.map(owner=>()=>owner.release()),...(approved?[()=>approved.release()]:[]),releaseEntry,releaseForm,...Object.values(review.pictures).flatMap(picture=>{if(!picture)return [];const url=picture.url;return [()=>revokeDisplayPreviewURL(url)];})],committed);
 }
 private clearReview(){const old=this.review;this.review=null;if(old)this.retire(old,this.renderComplete(true));}
 private reset(){this.epoch++;this.abort?.abort();this.clearReview();this.message='Text treatment changed. Prepare and confirm the current source and text selection.';this.changed();}
 private retireModel(model:OwnedModel<Context>,committed=this.renderComplete()){this.retireCleanups([()=>model.release()],committed);}
 private syncOwner(){if(this.disposed)return;const owner=this.editor.draftOwner,session=this.editor.session,document=this.editor.view.document?.id??'',entry=this.hooks.entryKey()??'';if(owner===this.uiOwner&&session===this.uiSession&&document===this.uiDocument&&entry===this.uiEntry)return;this.releaseState();this.uiOwner=owner;this.uiSession=session;this.uiDocument=document;this.uiEntry=entry;}
 dispose(){this.disposed=true;this.releaseState();}
 private releaseState(){
  this.epoch++;this.abort?.abort();this.adapter.invalidate();this.scheduled=false;
  const review=this.review,rendered=this.rendered,form=this.form;this.review=null;this.rendered=null;this.form=null;
  this.kind='';this.retained.clear();this.hide.clear();this.excluded.clear();this.duplicate=false;this.placement='new-document';this.mode='before';this.reveal='50';this.percentage=50;this.uiOwner=undefined;this.uiSession=undefined;this.uiDocument=this.uiEntry='';
  // Register every detached owner before the deferred requestUpdate can throw.
  if(review||rendered||form){const committed=this.renderComplete(true);if(review)this.retire(review,committed);if(rendered)this.retireModel(rendered,committed);if(form)this.retireCleanups([()=>form.release()],committed);}
 }
 async drain(){
  while(this.actions.size)await Promise.allSettled([...this.actions]);
  if(this.task)await Promise.allSettled([this.task]);
  while([...this.retired].some(record=>record.pending))await Promise.allSettled([...this.retired].flatMap(record=>record.pending?[record.pending]:[]));
  // A previous rejection is not a commit. Retry the retained actual owners only
  // after requesting and observing a fresh host render; a failed retry stays owned.
  if(this.retired.size){const committed=this.renderComplete(true);await Promise.allSettled([...this.retired].map(record=>this.runRetirement(record,committed)));}
  while([...this.retired].some(record=>record.pending))await Promise.allSettled([...this.retired].flatMap(record=>record.pending?[record.pending]:[]));
  const errors:unknown[]=[...this.retired].map(record=>Error(record.failed?'Text treatment render or cleanup failed.':'Text treatment retirement is incomplete.'));for(const error of this.cleanup)try{await error.retry();this.cleanup.delete(error);}catch(failure){errors.push(failure);}if(errors.length)throw new AggregateError(errors,'TEXT_TREATMENT_RELEASE_INCOMPLETE');
 }
 private current(draft:TextTreatmentDraft){const owns=this.hooks.owns(),epoch=this.epoch,entry=this.hooks.entryKey(),document=this.editor.view.document,session=this.editor.session,identity=session.identity(),sessionId=this.editor.sessionId,owner=this.editor.draftOwner;const id=document?.id,revision=document?.revision,semanticKey=this.hooks.semantic().key;return ()=>epoch===this.epoch&&owns()&&draft===this.hooks.draft()&&entry===this.hooks.entryKey()&&session===this.editor.session&&identity===session.identity()&&sessionId===this.editor.sessionId&&owner===this.editor.draftOwner&&id===this.editor.view.document?.id&&revision===this.editor.view.document?.revision&&semanticKey===this.hooks.semantic().key;}
 private context(draft:TextTreatmentDraft){
  const document=this.editor.view.document,image=this.editor.view.image,semantic=this.hooks.semantic(),entryKey=this.hooks.entryKey();
  if(!document||!image||!entryKey||!document.image)throw Error('Open a document before reviewing text treatment.');
  if(image.layers.length>100||semantic.items.length>256||semantic.items.some(row=>!ID.test(row.id)||typeof row.label!=='string'||row.label.length>160)||new Set(semantic.items.map(row=>row.id)).size!==semantic.items.length||semantic.key.length>256)throw Error('Text treatment inventory exceeds its supported bound.');
  if(semantic.approvedExcludedIds&&(semantic.approvedExcludedIds.length>256||new Set(semantic.approvedExcludedIds).size!==semantic.approvedExcludedIds.length||semantic.approvedExcludedIds.some(id=>!semantic.items.some(row=>row.id===id))))throw Error('Approved semantic exclusions are unavailable.');
  return createOwnedModel<Context>('text-treatment-context',MAX_MODEL,()=>({document:{id:document.id,revision:document.revision,width:document.width,height:document.height,image:structuredClone(document.image)},entryKey,operation:draft.operation,mode:draft.prompt.mode,beforeSource:generate(draft.operation)?null:structuredClone(draft.source??null),native:image.layers.filter(layer=>layer.kind==='text').map(layer=>({id:layer.id,version:layer.version,name:layer.name.slice(0,160),visible:layer.visible,locked:layer.locked})),visibleIds:image.layers.filter(layer=>layer.visible).map(layer=>layer.id),semantic:{key:semantic.key,items:semantic.items.map(row=>({...row})),approvedExcludedIds:semantic.approvedExcludedIds?[...semantic.approvedExcludedIds]:null}}),'prompt');
 }
 private choice(context:Context):TextTreatmentChoice{
  if(!this.kind)throw Error('Choose a text treatment explicitly.');
  if(context.mode==='composition'&&context.operation.endsWith('-v45'))throw Error('Composition projection is unavailable for Ideogram v4.5. Choose an explicit supported prompt mode.');
  const excludedSemanticIds=context.semantic.items.filter(row=>this.excluded.has(row.id)).map(row=>row.id);
  if(context.mode==='composition'){if(context.semantic.approvedExcludedIds===null||!same(excludedSemanticIds,context.semantic.approvedExcludedIds))throw Error('Review semantic exclusions in the Composition editor. This control does not change the approved projection.');}
  else if(excludedSemanticIds.length!==context.semantic.items.length)throw Error('Explicitly exclude every semantic text element from this plain or raw request. Metadata exclusion does not remove rasterized text.');
  const common={excludedSemanticIds,approvalId:crypto.randomUUID()},eligible=context.native.filter(row=>row.visible&&!row.locked);
  if(this.kind==='native-overlay'){const retainedNativeIds=context.native.filter(row=>this.retained.has(row.id)).map(row=>row.id);if(!retainedNativeIds.length||retainedNativeIds.some(id=>!eligible.some(row=>row.id===id)))throw Error('Select at least one visible, unlocked native text layer to keep editable.');return {...common,kind:'native-overlay',retainedNativeIds,placement:this.placement};}
  if(this.kind==='baked-lettering'){if(!this.duplicate)throw Error('Acknowledge that AI lettering may duplicate existing editable text and is not guaranteed.');const allowedHideNativeIds=context.native.filter(row=>this.hide.has(row.id)).map(row=>row.id);if(allowedHideNativeIds.some(id=>!eligible.some(row=>row.id===id)))throw Error('Hidden or locked text cannot be approved for hiding.');return {...common,kind:'baked-lettering',allowedHideNativeIds,duplicationAcknowledgement:crypto.randomUUID()};}
  return {...common,kind:'no-native-text'};
 }
 private action(event:Event,work:(draft:TextTreatmentDraft,current:()=>boolean,signal:AbortSignal)=>Promise<void>|void){
  this.syncOwner();if(this.disposed||this.scheduled||this.busy)return;if(this.actions.size>=8){this.hooks.error(Error('Text treatment actions are still pending.'));return;}const draft=this.hooks.draft();if(!draft)return;let release:()=>void;try{this.admit();const unpin=this.form!.pin();try{const entry=this.hooks.hold(draft);release=()=>{try{entry();}finally{unpin();}};}catch(error){unpin();throw error;}}catch(error){this.hooks.error(error);return;}const current=this.current(draft);this.scheduled=true;let finish!:()=>void;const completion=new Promise<void>(resolve=>finish=resolve);this.actions.add(completion);let started=false,freed=false;const free=()=>{if(!freed){freed=true;try{release();}finally{this.actions.delete(completion);finish();}}};
  this.adapter.action(event,()=>{started=true;this.scheduled=false;if(!current()){free();return;}const abort=new AbortController();this.abort=abort;this.busy=true;const task=Promise.resolve().then(()=>{this.changed();return work(draft,()=>!abort.signal.aborted&&current(),abort.signal);}).catch(error=>{this.remember(error);if(current()&&!(error instanceof DOMException&&error.name==='AbortError'))this.hooks.error(error);}).finally(()=>{free();if(this.task===task){this.task=null;this.abort=null;this.busy=false;this.changed();}});this.task=task;void task.catch(error=>{this.remember(error);try{this.hooks.error(error);}catch{/* The task remains observed after its pins are released. */}});});setTimeout(()=>{if(!started){this.scheduled=false;free();}},0);
 }
 private capture(scope:RequestSourceCapture['scope'],layerIds:string[],context:Context,current:()=>boolean):Promise<OwnedModel<Source>>{
  return this.editor.withCommandEvents({type:'PrepareRequestSource',scope,layerIds},events=>{if(!current())throw stale();const event=events.find(row=>row.type==='AssetRegistered');if(event?.type!=='AssetRegistered')throw Error('Text treatment source capture is unavailable.');const asset=event.payload.asset as Asset,raster=asset.raster;
   if(asset.qualification!=='canonical-raster'||asset.availability!=='available'||asset.safety!=='safe'||!raster||raster.role!=='composite'||raster.width!==context.document.width||raster.height!==context.document.height)throw Error('The capture must be an available canonical document raster.');
   return createOwnedModel<Source>('text-treatment-capture',modelPayloadBytes({assetId:asset.id,version:asset.version,blob:asset.blob,pixels:raster.pixels,width:raster.width,height:raster.height,scope,documentRevision:context.document.revision,capture:raster.manifest}),()=>structuredClone({assetId:asset.id,version:asset.version,blob:asset.blob,pixels:raster.pixels,width:raster.width,height:raster.height,scope,documentRevision:context.document.revision,capture:raster.manifest}),'prompt');
  },context.document);
 }

 private async captureIds(source:Source,context:Context,current:()=>boolean,signal:AbortSignal){
  if(!source.capture||source.documentRevision!==context.document.revision)throw Error('Capture the request source at the current document revision before reviewing text treatment.');
  const owned=await this.editor.ownedJSON<{width:number;height:number;pixels:unknown;plan:{kind:string;capture:RequestSourceCapture}}>('/api/v1/assets/'+encodeURIComponent(source.assetId)+'/raster','text-treatment-source-manifest',{signal},current,65536,'prompt');
  try{if(!current())throw stale();const root=owned.value,capture=root.plan?.capture;validateRequestSourceCapture(capture);const workspace=reserveModelBytes('text-treatment-manifest-identity',524288,1,'prompt');try{const wire=canonical(root);if(hash(wire)!==source.capture.hash||String(new TextEncoder().encode(wire).byteLength)!==source.capture.byteLength)throw Error('Source capture manifest identity changed.');}finally{workspace.release();}
   if(root.plan.kind!=='request-source-capture-v1'||capture.documentId!==context.document.id||capture.documentRevision!==context.document.revision||!same(capture.image,context.document.image)||capture.scope!==source.scope||!same(root.pixels,source.pixels)||root.width!==source.width||root.height!==source.height||source.width!==context.document.width||source.height!==context.document.height)throw Error('The source capture no longer matches this document and request.');
   return [...capture.layerIds];
  }finally{owned.release();}
 }
 private async picture(source:Source,current:()=>boolean,signal:AbortSignal):Promise<Picture>{const transport=this.editor.session.transport.bind(this.editor.session),url=await withDisplaySource(transport,source.assetId,{owner:'text-treatment-display-source',signal,owns:current},descriptor=>createDisplayPreviewURL(transport,descriptor,{owner:'text-treatment-preview',edge:1024,signal,owns:current}));if(!current()){revokeDisplayPreviewURL(url);throw stale();}return {source,url,loaded:false};}
 private async prepare(draft:TextTreatmentDraft,current:()=>boolean,signal:AbortSignal){
  const context=this.context(draft),pictures:Review['pictures']={baseline:null,before:null,after:null},captures:OwnedModel<Source>[]=[];let installed=false,preparationFailed=false,releaseEntry:(()=>void)|undefined,releaseForm:(()=>void)|undefined;
  try{const c=context.value,choice=this.choice(c);if(!generate(c.operation)&&!c.beforeSource)throw Error('Capture a request source before reviewing this edit.');
   const beforeIds=c.beforeSource?await this.captureIds(c.beforeSource,c,current,signal):[],selected=choice.kind==='native-overlay'?choice.retainedNativeIds:[],afterIds=textTreatmentUISelection(beforeIds,c.visibleIds,selected,choice.kind);
   if(choice.kind==='no-native-text'&&c.native.some(row=>afterIds.includes(row.id)))throw Error('The source contains native text. Choose keep editable or AI lettering explicitly.');
   if(!generate(c.operation)&&afterIds.length===0)throw Error('Removing these native layers leaves no request source. Choose Generate explicitly or capture another source; the operation will not switch automatically.');
   if(choice.kind==='native-overlay'&&choice.placement==='current-document'&&!c.operation.startsWith('inpaint'))throw Error('Keeping editable overlays in the current document requires a mask-backed inpaint request. Choose a new document for generation or unmasked editing.');const changed=!same(beforeIds,afterIds);if(draft.mask&&changed)throw Error('Detach the current request mask explicitly before preparing a different text source. Recreate and approve the mask afterward.');if(choice.kind==='native-overlay'&&choice.placement==='current-document'&&(afterIds.length!==1||(!changed&&c.beforeSource?.scope!=='single-layer')||c.native.some(row=>row.id===afterIds[0])))throw Error('Keeping editable overlays with this source requires an explicit new-document placement.');
   const baselineOwner=c.visibleIds.length?await this.capture('visible-document',[],c,current):null;if(baselineOwner)captures.push(baselineOwner);const baseline=baselineOwner?.value??null;if(baseline){const ids=await this.captureIds(baseline,c,current,signal);if(!same(ids,c.visibleIds))throw Error('The visible baseline changed.');}
   const afterOwner=changed?await this.capture(afterIds.length===1?'single-layer':'selected-layers',afterIds,c,current):null;if(afterOwner)captures.push(afterOwner);const afterSource=afterOwner?.value??c.beforeSource;
   if(afterSource&&changed&&!same(await this.captureIds(afterSource,c,current,signal),afterIds))throw Error('The alternate capture does not contain the reviewed layer subset.');
   if(baseline)pictures.baseline=await this.picture(baseline,current,signal);if(c.beforeSource)pictures.before=await this.picture(c.beforeSource,current,signal);if(afterSource)pictures.after=await this.picture(afterSource,current,signal);
   if(!current())throw stale();this.admit();releaseEntry=this.hooks.hold(draft);releaseForm=this.form!.pin();const review:Review={context,captures,draft,current:this.current(draft),releaseEntry,releaseForm,choice,baseline,afterSource,beforeIds,afterIds,pictures,approved:null};this.clearReview();this.review=review;installed=true;this.message='Review the native and semantic selections and source previews, then confirm this exact treatment.';this.changed();
  }catch(error){preparationFailed=true;throw error;}finally{if(!installed){
   // No Lit publication occurred. Attempt cleanup immediately, keeping only
   // failed callbacks for drain; a cleanup failure must not erase the prepare error.
   const retired=this.retireCleanups([()=>context.release(),...captures.map(owner=>()=>owner.release()),...(releaseEntry?[releaseEntry]:[]),...(releaseForm?[releaseForm]:[]),...Object.values(pictures).flatMap(picture=>{if(!picture)return [];const url=picture.url;return [()=>revokeDisplayPreviewURL(url)];})],Promise.resolve());
   await retired.pending;if(this.retired.has(retired)&&!preparationFailed)throw Error('Unpublished text treatment cleanup failed.');
  }}
 }
 private confirm(draft:TextTreatmentDraft){const review=this.review;if(!review||review.draft!==draft||!review.current())throw stale();if(Object.values(review.pictures).some(picture=>picture&&!picture.loaded))throw Error('Wait for every retained source preview to load before confirming.');
  const value={kind:'text-treatment-review-intent-1',choice:review.choice,baseline:review.baseline,beforeSource:review.context.value.beforeSource} satisfies TextTreatmentReviewIntent,approved=createOwnedModel('text-treatment-intent',modelPayloadBytes(value),()=>structuredClone(value),'prompt');let installed=false;
  try{if(!same(review.afterSource,review.context.value.beforeSource)){const next=this.hooks.attachAlternateSource(draft,review.afterSource);const release=this.hooks.hold(next);review.releaseEntry();review.releaseEntry=release;review.draft=next;review.current=this.current(next);}review.approved?.release();review.approved=approved;installed=true;this.message='Text treatment confirmed for the current request. The server will verify its complete native and semantic lineage during request review.';this.changed();}finally{if(!installed)approved.release();}
 }
 /** Borrowed until the next change/dispose; caller must hold its request Entry and own command serialization. */
 intent():TextTreatmentReviewIntent|undefined{if(this.review?.approved&&this.review.current())return this.review.approved.value;return undefined;}
 private update(event:Event,read:()=>string|boolean,change:(value:string|boolean)=>void){const draft=this.hooks.draft();if(!draft)return;let release:()=>void;try{release=this.hooks.hold(draft);}catch(error){this.hooks.error(error);return;}const current=this.current(draft);this.adapter.settled(event,read,value=>{if(!current()||this.busy)return;try{this.admit();change(value);this.reset();}catch(error){this.hooks.error(error);}});queueMicrotask(release);}

 private check(id:string,label:string,checked:boolean,disabled:boolean,change:(value:boolean)=>void){return html`<en-checkbox id=${id} .checked=${checked} ?disabled=${disabled||this.busy} @en-change=${(event:Event)=>{const control=event.currentTarget as unknown as {checked:boolean};this.update(event,()=>control.checked,value=>change(value===true));}}>${label}</en-checkbox>`;}
 private toggle(set:Set<string>,id:string,value:boolean){if(!ID.test(id)||set.size>=256&&!set.has(id))throw Error('Text selection exceeds its bound.');if(value)set.add(id);else set.delete(id);}
 private loaded(picture:Picture,event:Event){if(!Object.values(this.review?.pictures??{}).includes(picture))return;try{validateDisplayImage(event.currentTarget as HTMLImageElement,picture.url);picture.loaded=true;this.changed();}catch(error){this.hooks.error(error);}}
 private figure(picture:Picture|null,label:string){return picture?html`<figure><figcaption>${label}: ${picture.source.width} × ${picture.source.height} original pixels.</figcaption><img src=${displayImage(picture.url)} alt=${label} @load=${(event:Event)=>this.loaded(picture,event)}></figure>`:html`<p>${label}: no raster source.</p>`;}
 private comparison(review:Review){const a=review.pictures.before,b=review.pictures.after;if(!a||!b)return html`${this.figure(a,'Previous request source')}${this.figure(b,'Reviewed request source')}`;const width=a.source.width,height=a.source.height;if(width!==b.source.width||height!==b.source.height)return html`${this.figure(a,'Previous source')}${this.figure(b,'Reviewed source')}`;
  const split=width*this.percentage/100,clip='text-treatment-reveal-'+review.choice.approvalId;return html`<section aria-label="Native lettering source comparison"><p>Previous request source (A) and reviewed request source (B), same document coordinates. Display previews may be scaled; retained pixels are unchanged.</p><en-select id="text-treatment-comparison-mode" label="Text source comparison" .value=${this.mode} @en-change=${(event:Event)=>{const control=event.currentTarget as unknown as {value:string};this.adapter.settled(event,()=>control.value,value=>{if(review===this.review&&review.current()&&['before','after','reveal'].includes(value)){this.mode=value as typeof this.mode;this.changed();}});}}><en-select-option value="before">A: Previous source</en-select-option><en-select-option value="after">B: Reviewed source</en-select-option><en-select-option value="reveal">Reveal B over A</en-select-option></en-select><en-number-field id="text-treatment-reveal" label="Reviewed source reveal percentage" min="0" max="100" .value=${this.reveal} @en-input=${(event:Event)=>{const control=event.currentTarget as unknown as {value:string};this.adapter.settled(event,()=>control.value,value=>{const n=Number(value);if(review!==this.review||!review.current())return;if(!value.trim()||value.length>8||!Number.isFinite(n)||n<0||n>100){this.adapter.write(control as unknown as HTMLElement&{value:string},'value',this.reveal);this.hooks.error(Error('Enter a reveal percentage from 0 to 100.'));return;}this.reveal=value;this.percentage=n;this.mode='reveal';this.changed();});}}></en-number-field><svg viewBox=${`0 0 ${width} ${height}`} width=${width} height=${height} role="img" aria-label="Previous and reviewed native lettering source at the same origin and scale"><defs><clipPath id=${clip} clipPathUnits="userSpaceOnUse"><rect x="0" y="0" width=${split} height=${height}></rect></clipPath></defs>${this.mode!=='after'?svg`<image href=${displayImage(a.url)} x="0" y="0" width=${width} height=${height}></image>`:nothing}${this.mode!=='before'?svg`<image href=${displayImage(b.url)} x="0" y="0" width=${width} height=${height} clip-path=${this.mode==='reveal'?`url(#${clip})`:nothing}></image>`:nothing}</svg><details><summary>Load and inspect both individual source previews</summary>${this.figure(a,'Previous request source')}${this.figure(b,'Reviewed request source')}</details></section>`;
 }
 render(){if(this.disposed)return nothing;this.syncOwner();const draft=this.hooks.draft();if(!draft)return nothing;if(this.review&&!this.review.current())this.clearReview();let context:OwnedModel<Context>;try{this.admit();context=this.context(draft);}catch(error){return html`<en-alert role="status">${error instanceof Error?error.message:'Text treatment is unavailable.'}</en-alert>`;}const previous=this.rendered;this.rendered=context;if(previous)this.retireModel(previous);const c=context.value,review=this.review;const result=html`<section id="request-text-treatment" aria-label="Native and semantic text treatment" aria-busy=${String(this.busy)}><h3>Text treatment</h3><p>Native text pixels and semantic text descriptions are separate inputs. Excluding semantic metadata does not erase lettering already in the source image. No OCR or generation is performed by these controls.</p><en-select id="text-treatment-kind" label="Text treatment" .value=${this.kind} ?disabled=${this.busy} @en-change=${(event:Event)=>{const control=event.currentTarget as unknown as {value:string};this.update(event,()=>control.value,value=>{if(!['native-overlay','baked-lettering','no-native-text'].includes(String(value)))throw Error('Choose a supported text treatment.');this.kind=value as TextTreatmentChoice['kind'];});}}><en-select-option value="">Choose explicitly</en-select-option><en-select-option value="native-overlay">Keep selected native text editable</en-select-option><en-select-option value="baked-lettering">Ask AI for lettering</en-select-option><en-select-option value="no-native-text">No native text in the request source</en-select-option></en-select>
   <h4>Native text layers</h4>${c.native.length?html`<ul>${c.native.map(row=>html`<li>${row.name||row.id} · version ${row.version} · ${row.visible?'visible':'hidden'}${row.locked?' · locked':''}${this.kind==='native-overlay'?this.check('text-treatment-retain-'+row.id,'Keep '+(row.name||row.id)+' editable',this.retained.has(row.id),!row.visible||row.locked,value=>this.toggle(this.retained,row.id,value)):this.kind==='baked-lettering'?this.check('text-treatment-hide-'+row.id,'Allow a later adoption review to hide '+(row.name||row.id),this.hide.has(row.id),!row.visible||row.locked,value=>this.toggle(this.hide,row.id,value)):nothing}</li>`)}</ul>`:html`<p>No native text layers in this document.</p>`}
   ${this.kind==='native-overlay'?html`<en-select id="text-treatment-placement" label="Editable overlay placement" .value=${this.placement} ?disabled=${this.busy} @en-change=${(event:Event)=>{const control=event.currentTarget as unknown as {value:string};this.update(event,()=>control.value,value=>{if(value!=='new-document'&&value!=='current-document')throw Error('Choose an explicit placement.');this.placement=value;});}}><en-select-option value="new-document">New document with retained editable overlays</en-select-option><en-select-option value="current-document" ?disabled=${!c.operation.startsWith('inpaint')}>Current document, exact single background contribution</en-select-option></en-select><p>Generation, unmasked editing and multiple background contributions require a new document for retained editable overlays. The writer will recheck layer order, transforms, masks and locks before adoption.</p>`:nothing}
   ${this.kind==='baked-lettering'?this.check('text-treatment-duplication','AI may duplicate existing native text; generated lettering and spelling are not guaranteed. Hiding originals requires a separate adoption review.',this.duplicate,false,value=>this.duplicate=value):nothing}
   <h4>Semantic text descriptions</h4><p>${c.mode==='composition'?'Only the approved Composition projection can include semantic text. Match its explicit exclusions here.':'Plain and raw prompts do not use structured semantic text. Explicitly exclude each existing semantic text element here; the opaque prompt may still describe lettering.'}</p>${c.semantic.items.length?html`<ul>${c.semantic.items.map(row=>html`<li>${this.check('text-treatment-semantic-'+row.id,'Exclude semantic text '+(row.label||row.id),this.excluded.has(row.id),false,value=>this.toggle(this.excluded,row.id,value))}${c.mode==='composition'?html`<span> Approved projection: ${c.semantic.approvedExcludedIds?.includes(row.id)?'excluded':'included'}.</span>`:nothing}</li>`)}</ul>`:html`<p>No app semantic text elements.</p>`}<en-button id="text-treatment-open-composition" ?disabled=${this.busy||c.operation.endsWith('-v45')} @click=${(event:Event)=>this.action(event,()=>this.hooks.openComposition())}>Review semantic exclusions in Composition</en-button>${c.operation.endsWith('-v45')?html`<p>Composition and returned structured descriptions are unavailable for Ideogram v4.5.</p>`:nothing}
   ${draft.mask?html`<en-alert announcement="none">The current mask can be reviewed again with an unchanged source. Changing the source subset requires explicit mask detachment, then recreation and approval for the new source.</en-alert>`:nothing}<en-button id="text-treatment-prepare" ?disabled=${this.busy||!this.kind} @click=${(event:Event)=>this.action(event,(current,owns,signal)=>this.prepare(current,owns,signal))}>Capture baseline and prepare text source review</en-button>
   ${review?html`<en-card id="text-treatment-review" tabindex="-1"><h4>${review.approved?'Confirmed text treatment':'Review text inputs'}</h4><p>Raster layer IDs before: ${review.beforeIds.join(', ')||'none'}.</p><p>Raster layer IDs after: ${review.afterIds.join(', ')||'none'}.</p><p>Native pixels excluded from the request: ${review.beforeIds.filter(id=>!review.afterIds.includes(id)).join(', ')||'none'}.</p><p>Semantic text included: ${review.context.value.semantic.items.filter(row=>!review.choice.excludedSemanticIds.includes(row.id)).map(row=>row.id).join(', ')||'none'}. Excluded: ${review.choice.excludedSemanticIds.join(', ')||'none'}.</p>${this.figure(review.pictures.baseline,'Visible document baseline for native contribution inventory')}${this.comparison(review)}<en-button id="text-treatment-confirm" ?disabled=${this.busy||Object.values(review.pictures).some(picture=>picture&&!picture.loaded)} @click=${(event:Event)=>this.action(event,current=>this.confirm(current))}>Confirm exact native and semantic text treatment</en-button></en-card>`:nothing}<p role="status" aria-live="polite">${this.message}</p></section>`;
  // The rendered summary stays owned while its Lit callbacks remain live.
  return result;
 }
}
