// Test-only corpus builder. Production accepts archives only through staged,
// authenticated bytes and has no generic entity setter.
import {writeFile,readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
import {ZipIndex,spool,writeZip,crc32} from '../../dist/local/server/portable/zip.js';
import {canonical} from '../../dist/local/server/storage/canonical.js';
export const hash=b=>createHash('sha256').update(b).digest('hex');
export const encoded=v=>Buffer.from(canonical(v));
export async function unpack(root,bytes){const file=join(root,randomUUID()+'.zip');await writeFile(file,bytes,{mode:0o600});const db=spool(join(root,randomUUID()+'.sqlite')),z=new ZipIndex(file,db),entries=new Map();try{await z.headers(()=>{});await z.hashes(()=>{});for(const row of db.prepare('SELECT name FROM zip_entries').iterate()){const parts=[];for await(const b of z.chunks(z.entry(row.name),()=>{}))parts.push(b);entries.set(row.name,Buffer.concat(parts));}}finally{z.close();db.close();}return entries;}
export function records(entries,kind='records'){const m=JSON.parse(entries.get('manifest.json'));const s=m.segments.find(s=>s.kind===kind);return {path:s.path,values:entries.get(s.path).toString().trimEnd().split('\n').map(JSON.parse)};}
export function putRecords(entries,path,values){entries.set(path,Buffer.from(values.map(canonical).join('\n')+'\n'));}
export function addObject(entries,bytes,mediaType='application/json'){const {path,values}=records(entries),sha=hash(bytes),ref={hash:'sha256:'+sha,byteLength:String(bytes.length),mediaType};if(!entries.has('objects/'+sha)){entries.set('objects/'+sha,bytes);values.push({schemaVersion:1,kind:'object',sha256:sha,bytes:ref.byteLength,mediaType,path:'objects/'+sha});putRecords(entries,path,values);}return ref;}
export function addEntity(entries,kind,id,value){const payloadRef=addObject(entries,encoded(value)),r={schemaVersion:1,kind:'entity',entityType:kind,logicalId:id,payloadVersion:1,payloadRef,dependencies:[]},{path,values}=records(entries);values.push(r);putRecords(entries,path,values);return r;}
export function changeEntity(entries,kind,change){const {values}=records(entries),r=values.find(r=>r.kind==='entity'&&r.entityType===kind),old=hash(encoded(r));const value=JSON.parse(entries.get('objects/'+r.payloadRef.hash.slice(7)));change(value);const ref=addObject(entries,encoded(value)),fresh=records(entries);fresh.values.find(x=>x.kind==='entity'&&x.entityType===kind).payloadRef=ref;putRecords(entries,fresh.path,fresh.values);const m=JSON.parse(entries.get('manifest.json'));for(const root of m.rootRefs)if(root.recordHash==='sha256:'+old)root.recordHash='sha256:'+hash(encoded(fresh.values.find(x=>x.kind==='entity'&&x.entityType===kind)));entries.set('manifest.json',encoded(m));return value;}
export async function pack(root,entries,fix=true){if(fix){const m=JSON.parse(entries.get('manifest.json'));for(const s of m.segments){const bytes=entries.get(s.path);if(bytes){s.bytes=String(bytes.length);s.sha256=hash(bytes);s.recordCount=String(bytes.toString().split('\n').length-1);}}entries.set('manifest.json',encoded(m));}const path=join(root,randomUUID()+'.zip'),db=spool(join(root,randomUUID()+'.sqlite'));try{await writeZip(path,db,(async function*(){for(const [name,b]of entries)yield {name,bytes:BigInt(b.length),sha256:hash(b),crc:(crc32(b)^0xffffffff)>>>0,chunks:async function*(){for(let at=0;at<b.length;at+=1048576)yield b.subarray(at,at+1048576);}};})(),()=>{});}finally{db.close();}return readFile(path);}
