import test from 'node:test';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {join,resolve} from 'node:path';
import {chromium} from 'playwright';
import {rootFor} from '../store/helpers.mjs';
import {setup,copy,preview,workspace,terminal,edit,doc} from './helpers.mjs';
import {importRaster} from '../raster/helpers.mjs';
import {startLocalServer} from '../../dist/local/server/http.js';
let output,browser;test.before(async t=>{output=await rootFor(t);execFileSync(process.execPath,['node_modules/vite/bin/vite.js','build','--config','tests/recovery/vite.config.ts'],{env:{...process.env,IE_RECOVERY_OUTPUT:output}});browser=await chromium.launch({headless:true});});test.after(async()=>browser?.close());
async function fixture(t,checkpoints=1){const f=await setup(t);await terminal(f,f.command({}, {width:3,height:2}));const {asset}=await importRaster(f,'hidden-alpha.png');await edit(f,{type:'ImportAsset',assetId:asset.id,layerId:'picture',name:'Recovered image',draft:null});for(let i=0;i<checkpoints;i++)await edit(f,{type:'SaveCheckpoint',name:'Retained checkpoint '+i+' '+(checkpoints>1?'full bounded namespace '.repeat(120):'')});const saved=await copy(f),p=await preview(f,saved.bytes),accepted=await workspace(f,{type:'ImportBundle',reviewId:p.review.reviewId,reviewHash:p.review.reviewHash}),document=await doc(f,p.review.documentId),history=(await f.read('/api/v1/documents/'+document.id+'/history')).json.items;
 let cps=[],after='';do{const q=(await f.read('/api/v1/documents/'+document.id+'/checkpoints'+(after?'?after='+after:''))).json;cps.push(...q.items);after=q.next??'';}while(after);
 const ids=(await f.read('/api/v1/bundle-reviews/'+p.review.reviewId+'/mapping?kind=asset')).json.items.map(x=>x.localId),assets=[];for(const id of ids){const r=(await f.read('/api/v1/assets/'+id)).json;assets.push(r.projection?.value??r.asset??r);}
 return {f,p,accepted,expected:{document,history,checkpoints:cps,assets}};}
async function pageFor(t,f){await f.server.close();const server=await startLocalServer({root:f.root,staticDirectory:join(output,'browser-app')});t.after(()=>server.close());const context=await browser.newContext(),page=await context.newPage();t.after(()=>context.close());const external=[];await context.route('**/*',route=>{if(new URL(route.request().url()).origin!==server.origin){external.push(route.request().url());return route.abort();}return route.continue();});await page.goto(server.issuePairingURL());await page.waitForFunction(()=>window.harness);return {page,server,external};}
const refetch=route=>route.fetch({headers:{...route.request().headers(),Origin:new URL(route.request().url()).origin,'Sec-Fetch-Site':'same-origin'}});
const recover=page=>page.evaluate(async()=>{try{return {cursor:await window.harness.client.recover()};}catch(e){return {error:String(e)};}});
const published=page=>page.evaluate(()=>window.harness.cache.published());
async function assertRows(page,expected){const observed=await page.evaluate(async e=>{const c=window.harness.cache;return {document:await c.read('document',e.document.id),assets:await Promise.all(e.assets.map(x=>c.read('asset',x.id))),history:await Promise.all(e.history.map(x=>c.read('history',x.id))),checkpoints:await Promise.all(e.checkpoints.map(x=>c.read('checkpoint',x.id))) };},expected);assert.deepEqual(observed,expected);return observed;}
test('Chromium restart recovery hydrates a multi-chunk imported namespace before the cursor and survives missing or corrupt pages',async t=>{
 const {f,accepted,expected}=await fixture(t,70),{page,external}=await pageFor(t,f);console.error('browser fixture ready',accepted.receipt.toSeq);await page.evaluate(async()=>{const c=window.harness.cache,old=await c.published();await c.put('prior','document','sentinel',{intact:true});await c.publish({generation:'prior',cursor:'0',epoch:null},old);});const before=await published(page);console.error('browser prior cursor',before);
 for(const fault of ['missing-descriptor','wrong-context','missing-content','truncated-content']){
  let namespaceURL='',injected=false;await page.route('**/api/v1/namespace-events/**',async route=>{if(fault==='missing-descriptor'){injected=true;return route.abort();}const r=await refetch(route),value=await r.json();console.error('namespace descriptor',r.status(),value.content?.blob??value);if(r.status()!==200)return route.fulfill({response:r});namespaceURL=new URL(value.content.url,f.server.origin).pathname;if(fault==='wrong-context'){injected=true;value.recovery.writerEpoch=String(BigInt(value.recovery.writerEpoch)+1n);}await route.fulfill({response:r,json:value});});
  await page.route('**/api/v1/protocol-content/**',async route=>{if(new URL(route.request().url()).pathname===namespaceURL){if(fault==='missing-content'){injected=true;return route.abort();}if(fault==='truncated-content'){injected=true;const r=await refetch(route),b=await r.body();return route.fulfill({response:r,body:b.subarray(0,b.length-1)});}}return route.continue();});
  const failed=await recover(page);console.error('hydration fault',fault,failed);assert(failed.error,fault);assert(injected,'Requested browser fault was actually exercised: '+fault);assert.deepEqual(await published(page),before);assert.deepEqual(await page.evaluate(()=>window.harness.cache.read('document','sentinel')),{intact:true});assert.equal(await page.evaluate(id=>window.harness.cache.read('document',id),expected.document.id),undefined);await page.unroute('**/api/v1/namespace-events/**');await page.unroute('**/api/v1/protocol-content/**');
 }
 let release,entered;const hit=new Promise(r=>entered=r),gate=new Promise(r=>release=r);await page.route('**/api/v1/namespace-events/**',async route=>{entered();await gate;await route.continue();});const pending=recover(page);await Promise.race([hit,pending.then(result=>{throw Error('Recovery ended before hydration barrier '+JSON.stringify(result));})]);assert.deepEqual(await published(page),before);release();const result=await pending;assert.equal(result.cursor,accepted.receipt.toSeq);await page.unroute('**/api/v1/namespace-events/**');await assertRows(page,expected);assert.equal((await recover(page)).cursor,result.cursor);await assertRows(page,expected);assert.deepEqual(external,[]);t.diagnostic(JSON.stringify({finding:'I-PF02',browser:browser.version(),cursor:result.cursor,assets:expected.assets.length,history:expected.history.length,checkpoints:expected.checkpoints.length,failedHydrationRetainsPrior:true,externalRequests:external,qualification:false}));
});
test('Chromium SSE import uses its pinned context, publishes complete rows once and ignores duplicate delivery',async t=>{const {f,accepted,expected}=await fixture(t),{page,external}=await pageFor(t,f);await page.evaluate(()=>window.harness.seedFirst());
 await page.evaluate(()=>{window.abort=new AbortController();window.running=window.harness.client.consumeStream(window.abort.signal).catch(e=>{window.streamFailure=String(e);return String(e);});});let applied;for(let i=0;i<1000;i++){applied=await published(page);if(applied.cursor===accepted.receipt.toSeq)break;const error=await page.evaluate(()=>window.streamFailure);assert.equal(error,undefined,error);await new Promise(r=>setTimeout(r,5));}assert.equal(applied.cursor,accepted.receipt.toSeq);console.error('SSE reached',await page.evaluate(async()=>({published:await window.harness.cache.published(),failure:window.streamFailure})));await assertRows(page,expected);await page.evaluate(async()=>{window.abort.abort();await window.running;});
 const reference=await page.evaluate(async after=>(await (await window.harness.transport('/api/v1/events?after='+after)).json()).batches[0],String(BigInt(accepted.receipt.fromSeq)-1n));const before=await published(page),frame='id: '+accepted.receipt.toSeq+'\ndata: '+JSON.stringify({protocolVersion:1,kind:'transaction-ref',reference})+'\n\n';await page.route('**/api/v1/events/stream?**',route=>route.fulfill({status:200,contentType:'text/event-stream',body:frame+frame}));await page.evaluate(()=>window.harness.client.consumeStream());assert.deepEqual(await published(page),before);await assertRows(page,expected);assert.deepEqual(external,[]);});
test('Chromium snapshot plus tail includes all imported domain projections after server restart',async t=>{const {f,expected}=await fixture(t);let current=await doc(f);for(let i=0;i<255;i++){const r=await terminal(f,f.command({expectedDocumentRevision:current.revision,body:{type:'SaveCheckpoint',name:'After import '+i}}));assert.equal(r.json.receipt.status,'accepted');current={...current,revision:r.json.receipt.documentRevision};}const {page,external}=await pageFor(t,f),paths=[];page.on('request',r=>paths.push(r.url()));assert((await recover(page)).cursor);await assertRows(page,expected);assert(paths.some(p=>p.includes('/snapshots/')),'must exercise snapshot recovery');assert.deepEqual(external,[]);t.diagnostic(JSON.stringify({finding:'I-PF02',browser:browser.version(),snapshotRecovery:true,namespaceRowsAgree:true,externalRequests:external,qualification:false}));});
