import {installSchema18Packet} from '../recovery/schema18-packet.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {join} from 'node:path';
import {readFile} from 'node:fs/promises';
import {priorWriter,reopen} from './prior-writer.mjs';
import {setup,copy,preview,workspace,terminal,doc,digest} from './helpers.mjs';
import {cookieFrom} from '../session/helpers.mjs';
import {encode} from '../store/helpers.mjs';
import {openWriter} from '../../dist/local/server/storage/writer.js';
import {unpack,pack,encoded,records} from './archive-fixture.mjs';
let old;test.before(async t=>old=await priorWriter(t));
const pause=()=>new Promise(r=>setTimeout(r,5));
const snapshot=root=>{const db=new DatabaseSync(join(root,'metadata.sqlite'),{readOnly:true});try{return Object.fromEntries(['commands','events_v2','roots','objects','portable_namespaces','portable_rows','portable_maps','portable_preparations','portable_pins'].map(table=>[table,db.prepare('SELECT * FROM '+table+' ORDER BY 1,2').all()]));}finally{db.close();}};
async function seed(t,mutation){const f=await old.setup(t);await old.terminal(f,f.command({}, {width:3,height:2}));const {asset}=await old.importRaster(f,'hidden-alpha.png');const imported=await old.edit(f,{type:'ImportAsset',assetId:asset.id,layerId:'picture',name:'Prior writer',draft:null});let saved=await old.copy(f),bytes=saved.bytes;
 if(mutation){const entries=await old.archive.unpack(f.root,bytes),e=old.archive.records(entries,'events');e.values=e.values.filter(x=>x.event.workspaceSeq!==imported.receipt.fromSeq);old.archive.putRecords(entries,e.path,e.values);bytes=await old.archive.pack(f.root,entries);}
 return {f,saved,bytes,imported};}
for(const kind of ['proven','truncated','foreign'])test('actual d4 accepted format1 namespace new copy is '+kind+' without rewriting original history',async t=>{
 const s=await seed(t,kind==='truncated'),f=kind==='foreign'?await old.setup(t):s.f,p=await old.preview(f,s.bytes);assert.equal(p.review.editable,true);await old.workspace(f,{type:'ImportBundle',reviewId:p.review.reviewId,reviewHash:p.review.reviewHash});const before=await old.doc(f,p.review.documentId),kept=snapshot(f.root),cookie=cookieFrom(f.paired);await f.server.close();const g=await reopen(t,f.root,cookie,{legacyMigration:true});assert.deepEqual(await doc(g,p.review.documentId),before);
 if(kind==='proven'){const saved=await copy(g,p.review.documentId),entries=await unpack(g.root,saved.bytes),tx=records(entries).values.filter(x=>x.kind==='transaction'&&x.sourceArchive===digest(s.bytes));assert(tx.some(x=>x.receipt.transactionId===s.imported.receipt.transactionId));const fresh=await old.setup(t);await fresh.server.close();const h=await reopen(t,fresh.root,undefined,{legacyMigration:true}),review=await preview(h,saved.bytes);assert.equal(review.review.editable,true);await workspace(h,{type:'ImportBundle',reviewId:review.review.reviewId,reviewHash:review.review.reviewHash});}
 else{const c=g.command({documentId:p.review.documentId,expectedDocumentRevision:before.revision,body:{type:'SaveCopy'}});let result=await g.post('/api/v1/commands',c);for(let i=0;i<1000;i++){const inventory=(await g.read('/api/v1/bundles/recovery')).json;result=await g.read('/api/v1/commands/'+c.command.commandId);if(result.status===200||inventory.items.some(x=>x.commandId===c.command.commandId&&x.reason)){if(kind==='foreign'){const item=inventory.items.find(x=>x.commandId===c.command.commandId);assert.equal(item.reason,'TRANSACTION_EVIDENCE_UNAVAILABLE');assert.match(item.recovery,/original-archive-retained/);}break;}await pause();}if(kind==='truncated')assert.equal(result.json.receipt?.status,'rejected',result.text);else assert.equal(result.status,202);}
 const after=snapshot(f.root);for(const table of ['commands','events_v2','roots','objects','portable_namespaces','portable_rows','portable_maps'])for(const row of kept[table])assert(after[table].some(x=>JSON.stringify(x)===JSON.stringify(row)),table);assert.deepEqual(await doc(g,p.review.documentId),before);const original=join(f.root,'objects','sha256',digest(s.bytes).slice(7,9),digest(s.bytes).slice(7));assert.deepEqual(await readFile(original),s.bytes);
 t.diagnostic(JSON.stringify({finding:'I-PF01',priorExecutable:'d4ed761',legacy:kind,originalArchive:digest(s.bytes),acceptedNamespace:p.review.namespaceId,originalTransaction:s.imported.receipt,preservedOriginal:true}));
});
for(const proven of [true,false])test('actual d4 pending frozen capture '+(proven?'upgrades from immutable receipts':'retains exact pending identity when evidence is unavailable'),async t=>{
 const s=await seed(t,false);let f=s.f,documentId='document_1';if(!proven){const foreign=await old.setup(t),p=await old.preview(foreign,s.bytes);await old.workspace(foreign,{type:'ImportBundle',reviewId:p.review.reviewId,reviewHash:p.review.reviewHash});f=foreign;documentId=p.review.documentId;}
 const d=await old.doc(f,documentId),c=f.command({documentId,expectedDocumentRevision:d.revision,body:{type:'SaveCopy'}}),auth={clientId:f.paired.json.clientId,sessionHash:'b'.repeat(64),now:Date.now(),expires:Date.now()+1800000};await f.server.close();const prior=await old.childFor(t,f.root,{phase:'portable-preparation-after-commit'});const sent=prior.call('portableCommand',encode(c),auth).catch(()=>{});await prior.wait('barrier');const before=snapshot(f.root),pending=before.portable_preparations.find(x=>x.id===c.command.commandId);assert(pending);assert.equal(JSON.parse(pending.frozen).captureVersion,undefined);const capture=join(f.root,'portable',pending.operation_id,'capture.sqlite'),captureBytes=await readFile(capture);await prior.kill();await sent;
 await installSchema18Packet(f.root); const w=await openWriter({root:f.root});t.after(()=>w.close());let state,inventory;for(let i=0;i<1000;i++){state=await w.commandState(c.command.commandId);inventory=await w.portableInventory('',auth);if(state.record||inventory.items.some(x=>x.commandId===c.command.commandId&&x.reason))break;await pause();}
 if(proven){assert.equal(state.record?.receipt.status,'accepted',JSON.stringify(state));assert.deepEqual(state.record.command,c.command);assert.equal(state.record.hash,pending.hash);assert.deepEqual(await w.portableCommand(encode(c),auth),state.record.receipt);}
 else{assert.equal(state.record,null);assert.equal(inventory.items.find(x=>x.commandId===c.command.commandId).reason,'TRANSACTION_EVIDENCE_UNAVAILABLE');const retained=snapshot(f.root).portable_preparations.find(x=>x.id===c.command.commandId);for(const key of ['id','hash','original','canonical','operation_id','frozen','confirmed_at'])assert.equal(retained[key],pending[key],key);assert.deepEqual(snapshot(f.root).portable_pins,before.portable_pins);}
 assert.deepEqual(await readFile(capture),captureBytes);assert.equal(digest(captureBytes),JSON.parse(pending.frozen).captureHash);t.diagnostic(JSON.stringify({finding:'I-PF01',proven,originalCommand:c.command.commandId,operation:pending.operation_id,frozen:pending.frozen,receipt:state.record?.receipt??null,captureUnchanged:true}));
});

// This exercises the actual historical decoder's required-version boundary.
// The real comparison graph and conditional PF13 producer are covered by the
// registered native-deferred-adoption writer fixture, without shared outputs.
test('actual prior reader preserves a portable13 capsule for inspection and refuses editable import',async t=>{
 const current=await setup(t);await terminal(current,current.command({}, {width:1,height:1}));const ordinary=await copy(current),entries=await unpack(current.root,ordinary.bytes),manifest=JSON.parse(entries.get('manifest.json'));
 assert.equal(manifest.formatVersion,7);entries.set('manifest.json',encoded({...manifest,formatVersion:13,documentSchema:13}));const bytes=await pack(current.root,entries),supported=await preview(current,bytes);assert.equal(supported.review.editable,true);assert.equal(supported.review.formatVersion,13);
 const legacy=await old.setup(t),inspection=await old.preview(legacy,bytes),review=inspection.review;assert.equal(review.formatVersion,13);assert.equal(review.documentSchema,13);assert.equal(review.editable,false);assert.equal(review.reason,'UNSUPPORTED_FORMAT_VERSION');
 const attempted=await old.terminal(legacy,legacy.command({documentId:null,expectedDocumentRevision:null,body:{type:'ImportBundle',reviewId:review.reviewId,reviewHash:review.reviewHash}}));assert.equal(attempted.json.receipt.status,'rejected');assert.equal((await legacy.read('/api/v1/documents/'+review.documentId)).status,404);
 const db=new DatabaseSync(join(legacy.root,'metadata.sqlite'),{readOnly:true});let filename;try{assert.equal(db.prepare('SELECT count(*) n FROM portable_namespaces').get().n,0);filename=db.prepare('SELECT filename FROM staged_assets WHERE id=?').get(inspection.stage.stagingId).filename;}finally{db.close();}
 assert.deepEqual(await readFile(join(legacy.root,'uploads',filename)),bytes);assert.deepEqual(JSON.parse((await unpack(current.root,ordinary.bytes)).get('manifest.json')),manifest);
});
