import test from 'node:test';
import assert from 'node:assert/strict';
import {setup,doc,edit,workspace,copy,preview,terminal,binary} from './helpers.mjs';
import {importRaster} from '../raster/helpers.mjs';
import sharp from 'sharp';

test('empty document real HTTP copy, review, fresh namespace import and exact retry',async t=>{
 const f=await setup(t);assert.equal((await terminal(f,f.command({}, {width:3,height:2}))).json.receipt.status,'accepted');const original=await doc(f);const saved=await copy(f);const inspected=await preview(f,saved.bytes);assert.equal(inspected.review.editable,true,JSON.stringify(inspected.review));const imported=await workspace(f,{type:'ImportBundle',reviewId:inspected.review.reviewId,reviewHash:inspected.review.reviewHash});const d=await doc(f,inspected.review.documentId);assert.notEqual(d.id,original.id);assert.equal(d.width,3);assert.equal(d.height,2);assert.notEqual(d.historyHead,original.historyHead);assert.deepEqual((await terminal(f,imported.command)).json.receipt,imported.receipt);assert.deepEqual(await doc(f),original);const recopy=await copy(f,d.id);assert.ok(recopy.bytes.length>0);
});
test('image retained pixels and old branch reopen in fresh namespace',async t=>{
 const f=await setup(t);await terminal(f,f.command({}, {width:3,height:2}));const {asset}=await importRaster(f,'hidden-alpha.png');const first=await edit(f,{type:'ImportAsset',assetId:asset.id,layerId:'picture',name:'Original',draft:null});const second=await edit(f,{type:'SetLayerProperties',layerId:'picture',layerVersion:'1',properties:{visible:false},draft:null});await edit(f,{type:'Undo',historyHead:second.document.historyHead});await edit(f,{type:'SaveCheckpoint',name:'Retained original'});const saved=await copy(f),p=await preview(f,saved.bytes);assert.equal(p.review.editable,true,JSON.stringify(p.review));await workspace(f,{type:'ImportBundle',reviewId:p.review.reviewId,reviewHash:p.review.reviewHash});const d=await doc(f,p.review.documentId);const out=await binary(f,'/api/v1/assets/'+d.image.compositeAssetId+'/content');assert.equal(out.status,200);assert.deepEqual(await sharp(out.bytes).ensureAlpha().raw().toBuffer(),Buffer.from([17,99,231,0,255,0,0,128,0,255,0,255,0,0,255,64,255,255,255,255,0,0,0,255]));const history=(await f.read('/api/v1/documents/'+d.id+'/history')).json.items;const hidden=history.find(n=>n.operation==='SetLayerProperties');assert(hidden);await edit(f,{type:'Redo',historyNode:hidden.id},d.id);const h=await doc(f,d.id);assert.deepEqual(await sharp((await binary(f,'/api/v1/assets/'+h.image.compositeAssetId+'/content')).bytes).ensureAlpha().raw().toBuffer(),Buffer.alloc(24));
});
