import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {join} from 'node:path';
import {setup,copy,preview,workspace,terminal,edit,doc,upload,binary} from './helpers.mjs';
import {importRaster} from '../raster/helpers.mjs';
import {cookieFrom} from '../session/helpers.mjs';
import {reopen} from './prior-writer.mjs';
import {unpack} from './archive-fixture.mjs';
const persist=async(f,sessionId,body)=>{const ui=(await f.read('/api/v1/ui/'+sessionId)).json,r=await f.post('/api/v1/ui/'+sessionId,{protocolVersion:1,requestId:randomUUID(),sessionId,expectedUISeq:ui.uiSeq,body});assert.equal(r.json.status,'accepted',r.text);return r.json;};
async function fixture(t){const f=await setup(t);await terminal(f,f.command({}, {width:3,height:2}));await terminal(f,f.command({documentId:'other_document'},{width:1,height:1}));const {asset}=await importRaster(f,'hidden-alpha.png');await edit(f,{type:'ImportAsset',assetId:asset.id,layerId:'picture',name:'Original',draft:null});const text=Buffer.from('Applied restored draft — exact 🦋'),s=await upload(f,text,'caption','text/plain'),caption=(await workspace(f,{type:'FinalizeStaging',stagingId:s.stagingId,expectedSha256:s.sha256})).event.payload.asset;await persist(f,'editor',{type:'SaveDraft',draft:{id:'rename',generation:'1',kind:'inspector',documentId:'document_1',targetLayerId:'picture',expectedDocumentRevision:'2',assetId:caption.id,composing:false}});const secret=Buffer.from('UNRELATED private draft must stay local'),p=await upload(f,secret,'caption','text/plain'),privateCaption=(await workspace(f,{type:'FinalizeStaging',stagingId:p.stagingId,expectedSha256:p.sha256})).event.payload.asset;await persist(f,'other_editor',{type:'SaveDraft',draft:{id:'rename',generation:'1',kind:'prompt',documentId:'other_document',targetLayerId:null,expectedDocumentRevision:'1',assetId:privateCaption.id,composing:false}});const saved=await copy(f),review=await preview(f,saved.bytes);assert.equal(saved.bytes.includes(secret),false);return {f,text,caption,secret,saved,review};}
const roots=(root,owner)=>{const db=new DatabaseSync(join(root,'metadata.sqlite'),{readOnly:true});try{return db.prepare('SELECT * FROM roots WHERE owner=? ORDER BY hash').all(owner);}finally{db.close();}};
for(const restart of [false,true])test('restored draft apply clear recopy retains exact history ownership '+(restart?'across restart':'and dedup'),async t=>{
 const x=await fixture(t),{review}=x;let f=x.f;const imported=await workspace(f,{type:'ImportBundle',reviewId:review.review.reviewId,reviewHash:review.review.reviewHash});assert.deepEqual((await terminal(f,imported.command)).json.receipt,imported.receipt);const uiId=review.review.uiSessionIds[0],ui=(await f.read('/api/v1/ui/'+uiId)).json,d=ui.drafts[0],owner='ui:'+f.paired.json.clientId+':'+uiId+':'+d.id+':'+d.generation;assert.deepEqual(roots(f.root,owner).map(x=>x.hash),[x.caption.blob.hash]);
 if(restart){const cookie=cookieFrom(f.paired);await f.server.close();f=await reopen(t,f.root,cookie);assert.deepEqual((await terminal(f,imported.command)).json.receipt,imported.receipt);assert.deepEqual((await f.read('/api/v1/ui/'+uiId)).json,ui);}
 const applied=await edit(f,{type:'SetLayerProperties',layerId:d.targetLayerId,layerVersion:'1',properties:{name:x.text.toString()},draft:{sessionId:uiId,draftId:d.id,generation:d.generation}},review.review.documentId);await persist(f,uiId,{type:'ClearDraft',draftId:d.id,generation:d.generation});assert.deepEqual((await terminal(f,applied.command)).json.receipt,applied.receipt);const saved=await copy(f,review.review.documentId),entries=await unpack(f.root,saved.bytes);assert.deepEqual(entries.get('objects/'+x.caption.blob.hash.slice(7)),x.text);assert.equal(saved.bytes.includes(x.secret),false);assert.equal(roots(f.root,owner).length,1);
 const fresh=await setup(t),p=await preview(fresh,saved.bytes);assert.equal(p.review.editable,true);await workspace(fresh,{type:'ImportBundle',reviewId:p.review.reviewId,reviewHash:p.review.reviewHash});assert.deepEqual((await binary(fresh,'/api/v1/assets/'+(await doc(fresh,p.review.documentId)).image.compositeAssetId+'/content')).bytes,(await binary(f,'/api/v1/assets/'+applied.document.image.compositeAssetId+'/content')).bytes);assert.equal((await doc(f)).revision,'2');assert.equal((await doc(f,'other_document')).revision,'1');t.diagnostic(JSON.stringify({finding:'I-PF03',restart,owner,blob:x.caption.blob,importReceipt:imported.receipt,applyReceipt:applied.receipt,recopy:saved.bundle.blob,reopened:p.review.documentId,unrelatedExcluded:true}));
});
for(const phase of ['current','accepted-history'])test('required '+phase+' mapped draft ownership still fails explicitly when missing',async t=>{const x=await fixture(t),{f,review}=x;await workspace(f,{type:'ImportBundle',reviewId:review.review.reviewId,reviewHash:review.review.reviewHash});const uiId=review.review.uiSessionIds[0],d=(await f.read('/api/v1/ui/'+uiId)).json.drafts[0],owner='ui:'+f.paired.json.clientId+':'+uiId+':'+d.id+':'+d.generation;if(phase==='accepted-history'){await edit(f,{type:'SetLayerProperties',layerId:d.targetLayerId,layerVersion:'1',properties:{name:x.text.toString()},draft:{sessionId:uiId,draftId:d.id,generation:d.generation}},review.review.documentId);await persist(f,uiId,{type:'ClearDraft',draftId:d.id,generation:d.generation});}const original=roots(f.root,owner),before=await doc(f,review.review.documentId),db=new DatabaseSync(join(f.root,'metadata.sqlite'));db.prepare('DELETE FROM roots WHERE owner=?').run(owner);db.close();const response=await f.post('/api/v1/commands',f.command({documentId:before.id,expectedDocumentRevision:before.revision,body:{type:'SaveCopy'}}));assert.equal(response.status,503,response.text);assert.equal(response.json.error.code,'RECOVERY_UNAVAILABLE');assert.match(response.text,/required-(current|history)-draft-ownership-unavailable/);assert.deepEqual(await doc(f,before.id),before);const restore=new DatabaseSync(join(f.root,'metadata.sqlite'));for(const r of original)restore.prepare('INSERT INTO roots VALUES (?,?,?)').run(r.owner,r.hash,r.media_type);restore.close();await copy(f,before.id);});
test('failed atomic import leaves no mapped draft owner or partial namespace and retains original roots',async t=>{const {f,review,caption}=await fixture(t),db=new DatabaseSync(join(f.root,'metadata.sqlite'));const before=db.prepare('SELECT * FROM roots ORDER BY owner,hash').all();db.exec("CREATE TRIGGER fail_imported_draft_owner BEFORE INSERT ON roots WHEN NEW.owner LIKE 'ui:%:p_%' BEGIN SELECT RAISE(ABORT,'injected imported owner failure'); END;");db.close();const c=f.command({documentId:null,expectedDocumentRevision:null,body:{type:'ImportBundle',reviewId:review.review.reviewId,reviewHash:review.review.reviewHash}}),r=await terminal(f,c);assert.equal(r.json.receipt.status,'rejected');const after=new DatabaseSync(join(f.root,'metadata.sqlite'));assert.equal(after.prepare('SELECT count(*) n FROM portable_namespaces').get().n,0);assert.equal(after.prepare('SELECT count(*) n FROM portable_rows').get().n,0);assert.equal(after.prepare("SELECT count(*) n FROM ui_checkpoints WHERE session_id LIKE 'p_%'").get().n,0);assert.equal(after.prepare("SELECT count(*) n FROM roots WHERE owner LIKE 'ui:%:p_%'").get().n,0);for(const row of before)assert(after.prepare('SELECT 1 FROM roots WHERE owner=? AND hash=?').get(row.owner,row.hash));after.exec('DROP TRIGGER fail_imported_draft_owner');after.close();const fresh=await preview(f,(await copy(f)).bytes);await workspace(f,{type:'ImportBundle',reviewId:fresh.review.reviewId,reviewHash:fresh.review.reviewHash});});
