import test from 'node:test';
import assert from 'node:assert/strict';
import sharp from 'sharp';
import {setup,copy,preview,workspace,terminal,edit,doc,binary,upload} from './helpers.mjs';
import {importRaster} from '../raster/helpers.mjs';
import {child} from './process-helpers.mjs';
import {cookieFrom} from '../session/helpers.mjs';
import {command} from '../store/helpers.mjs';
import {EMPTY_EXPECTED_VERSIONS} from '../../dist/local/src/protocol/store.js';
import {unpack,records} from './archive-fixture.mjs';
const original=Buffer.from([17,99,231,0,255,0,0,128,0,255,0,255,0,0,255,64,255,255,255,255,0,0,0,255]);
const movedPixels=Buffer.from([0,0,0,0,17,99,231,0,255,0,0,128,0,0,0,0,0,0,255,64,255,255,255,255]);
const pixels=async(f,id)=>sharp((await binary(f,'/api/v1/assets/'+id+'/content')).bytes).ensureAlpha().raw().toBuffer();
test('copy retains mask, deleted layer, inactive branches, checkpoint, export and exact source events; reopen restarts and navigates all',async t=>{
 const f=await setup(t);await terminal(f,f.command({}, {width:3,height:2}));const {asset,input}=await importRaster(f,'hidden-alpha.png');const imported=await edit(f,{type:'ImportAsset',assetId:asset.id,layerId:'picture',name:'Original',draft:null});
 const maskBytes=await sharp({create:{width:3,height:2,channels:4,background:{r:0,g:0,b:0,alpha:1}}}).png().toBuffer(),stage=await upload(f,maskBytes,'image','image/png'),maskInput=(await workspace(f,{type:'FinalizeStaging',stagingId:stage.stagingId,expectedSha256:stage.sha256})).event.payload.asset,maskPreview=(await workspace(f,{type:'PrepareRaster',assetId:maskInput.id})).event.payload.asset,maskReview=(await workspace(f,{type:'ReviewRaster',assetId:maskPreview.id})).event.payload,mask=(await workspace(f,{type:'ApproveRaster',assetId:maskPreview.id,...maskReview})).event.payload.asset;
 const masked=await edit(f,{type:'SetLayerProperties',layerId:'picture',layerVersion:'1',properties:{mask:{assetId:mask.id,mapping:'document-luminance-alpha-v1',inverted:false}},draft:null});assert.deepEqual(await pixels(f,masked.document.image.compositeAssetId),Buffer.alloc(24));await edit(f,{type:'SaveCheckpoint',name:'Masked branch'});await edit(f,{type:'Undo',historyHead:masked.document.historyHead});const moved=await edit(f,{type:'ApplyTransform',layerId:'picture',layerVersion:'1',transform:[1,0,0,1,1,0],draft:null});assert.notEqual(moved.document.branchId,masked.document.branchId);assert.deepEqual(await pixels(f,moved.document.image.compositeAssetId),movedPixels);const exported=await edit(f,{type:'ExportDocument',historyHead:moved.document.historyHead});const exportedAsset=exported.event.payload.asset;await edit(f,{type:'DeleteLayer',layerId:'picture',layerVersion:'2',draft:null});
 const before=await doc(f),saved=await copy(f),entries=await unpack(f.root,saved.bytes),all=records(entries).values,assets=all.filter(x=>x.kind==='entity'&&x.entityType==='asset').map(x=>JSON.parse(entries.get('objects/'+x.payloadRef.hash.slice(7)))),ids=new Set(assets.map(x=>x.id));for(const required of [asset,input,mask,maskInput,exportedAsset])assert(ids.has(required.id),required.id);const sourceEvents=records(entries,'events').values.map(x=>x.event),byCommand=new Map(sourceEvents.map(x=>[x.commandId,x]));for(const x of [imported,masked,moved,exported]){const receipt=x.receipt,batch=(await f.read('/api/v1/events?after='+String(BigInt(receipt.fromSeq)-1n))).json.batches[0];const archived=sourceEvents.filter(e=>e.transactionId===receipt.transactionId);assert.deepEqual(archived,batch.events);assert.equal(archived[0].workspaceSeq,receipt.fromSeq);assert.equal(archived.at(-1).workspaceSeq,receipt.toSeq);}
 const p=await preview(f,saved.bytes);await workspace(f,{type:'ImportBundle',reviewId:p.review.reviewId,reviewHash:p.review.reviewHash});const local=await doc(f,p.review.documentId);assert.equal(local.image.semanticDigest,before.image.semanticDigest);const mapping=(await f.read('/api/v1/bundle-reviews/'+p.review.reviewId+'/mapping?kind=history')).json.items,mapped=id=>mapping.find(x=>x.sourceId===id).localId;const cookie=cookieFrom(f.paired);await f.server.close();const g=await child(t,f.root);await g.pair(cookie);g.command=(patch,body)=>command(EMPTY_EXPECTED_VERSIONS,{clientId:g.paired.json.clientId,...patch},body);const history=(await g.read('/api/v1/documents/'+local.id+'/history')).json.items;assert.equal(history.length,5);const branch=id=>history.find(x=>x.id===mapped(id)).branchId;
 const restored=await edit(g,{type:'SwitchBranch',branchId:branch(moved.document.historyHead),historyNode:mapped(moved.document.historyHead)},local.id);assert.deepEqual(await pixels(g,restored.document.image.compositeAssetId),movedPixels);const png=await edit(g,{type:'ExportDocument',historyHead:restored.document.historyHead},local.id);assert.deepEqual(await pixels(g,png.event.payload.asset.id),movedPixels);const maskState=await edit(g,{type:'SwitchBranch',branchId:branch(masked.document.historyHead),historyNode:mapped(masked.document.historyHead)},local.id);assert.deepEqual(await pixels(g,maskState.document.image.compositeAssetId),Buffer.alloc(24));const undone=await edit(g,{type:'Undo',historyHead:maskState.document.historyHead},local.id);assert.deepEqual(await pixels(g,undone.document.image.compositeAssetId),original);const redone=await edit(g,{type:'Redo',historyNode:mapped(masked.document.historyHead)},local.id);assert.deepEqual(await pixels(g,redone.document.image.compositeAssetId),Buffer.alloc(24));await g.effects();assert.deepEqual(await doc(g),before);
 t.diagnostic(JSON.stringify({retainedHistoryNodes:history.length,retainedAssetIds:assets.length,sourceEventCount:sourceEvents.length,literalPixelOracles:true,sourceTransactionsPreserved:true,namespaceFresh:true,providerEffects:0}));
});
