import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {join} from 'node:path';
import {readFile} from 'node:fs/promises';
import {setup,copy,preview,workspace,terminal,upload} from './helpers.mjs';
import {unpack,pack,addObject,addEntity,encoded,hash} from './archive-fixture.mjs';
import {child} from './process-helpers.mjs';
import {cookieFrom} from '../session/helpers.mjs';
import {command} from '../store/helpers.mjs';
import {EMPTY_EXPECTED_VERSIONS} from '../../dist/local/src/protocol/store.js';
const policy={profileId:'privacy_verified',profileVersion:1,evidenceDigest:'sha256:'+'c'.repeat(64),requestedStoreIO:'0',requestedAccess:'most-private-compatible',appliedLifecycleSeconds:null,appliedACL:'private',enforcement:'unknown',fallbackAcknowledgementId:null};
const transport=Buffer.from('backend transport FAL_KEY=PRIVATE_SECRET_SENTINEL cookie=SECRET_COOKIE https://provider.invalid/download?signature=SIGNED_TRANSPORT_SENTINEL');
async function fixture(t,promptBytes=Buffer.from('exact authored prompt https://user.invalid/?signature=literal')){const f=await setup(t);await terminal(f,f.command({}, {width:1,height:1}));const saved=await copy(f),entries=await unpack(f.root,saved.bytes),prompt=addObject(entries,promptBytes,'text/plain'),privacyPolicyRef=addObject(entries,encoded(policy)),safeTimingsRef=addObject(entries,encoded({processingMs:12.125,totalMs:14}));
 const image=await readFile(new URL('../raster/fixtures/hidden-alpha.png',import.meta.url)),imageRef=addObject(entries,image,'image/png');addEntity(entries,'asset','provider_result',{id:'provider_result',version:'1',purpose:'image',blob:imageRef,dependencies:[],safety:'unknown',availability:'available',qualification:'pending-decoder',measuredMediaType:'image/png'});
 const provider={class:'portable-provider',attemptId:'past_attempt',endpoint:'fal/ideogram-v3',requestId:'past_request',status:'completed',assetHashes:[imageRef.hash],requestedPromptRef:prompt,submittedPromptRef:prompt,returnedPromptRef:prompt,seedText:'18446744073709551615',safeTimingsRef,privacyPolicyRef,derivation:{profile:'TP-1',sourceBodyHash:'sha256:'+hash(transport),complete:true}};return {f,entries,prompt,provider};}
test('inert provider provenance retains oversized exact prompts and result bytes across import, copy and restart with zero effects',async t=>{
 const unit=Buffer.from('exact 🦋 שלום \\u0041\nhttps://authored.invalid/?token=user-text\n'),promptBytes=Buffer.concat(Array.from({length:Math.ceil((17*1048576)/unit.length)},()=>unit)),{f,entries,prompt,provider}=await fixture(t,promptBytes);addEntity(entries,'portable-provider',provider.attemptId,provider);const archive=await pack(f.root,entries);assert.equal(archive.includes(transport),false);await f.server.close();
 const process=await child(t,f.root);await process.pair(cookieFrom(f.paired));process.command=(patch,body)=>command(EMPTY_EXPECTED_VERSIONS,{clientId:process.paired.json.clientId,...patch},body);const p=await preview(process,archive);assert.equal(p.review.editable,true);await workspace(process,{type:'ImportBundle',reviewId:p.review.reviewId,reviewHash:p.review.reviewHash});await process.effects();const copied=await copy(process,p.review.documentId);assert(copied.bytes.includes(promptBytes));assert.equal(copied.bytes.includes(transport),false);const unpacked=await unpack(f.root,copied.bytes);assert.deepEqual(unpacked.get('objects/'+prompt.hash.slice(7)),promptBytes);assert.deepEqual(unpacked.get('objects/'+provider.assetHashes[0].slice(7)),entries.get('objects/'+provider.assetHashes[0].slice(7)));await process.effects();const cookie=cookieFrom(process.paired);await process.kill();const restart=await child(t,f.root);await restart.pair(cookie);assert.equal((await restart.read('/api/v1/documents/'+p.review.documentId)).status,200);await restart.effects();t.diagnostic(JSON.stringify({promptBytes:promptBytes.length,exactUTF8:true,bodyHashTraversed:false,providerEffects:0,qualification:false}));
});
for(const fault of ['headers','transportURL','backendClass','bodyReachability','invalidUTF8','incomplete','timings-array'])test('portable provider '+fault+' cannot become an editable namespace',async t=>{
 const x=await fixture(t),{f,entries,provider}=x;if(fault==='headers')provider.headers={Authorization:'SECRET'};if(fault==='transportURL')provider.endpoint='https://provider.invalid/image?token=secret';if(fault==='backendClass')provider.class='backend-transport';if(fault==='bodyReachability')addObject(entries,transport);if(fault==='invalidUTF8')provider.returnedPromptRef=addObject(entries,Buffer.from([0xff,0xfe,0x80]),'text/plain');if(fault==='incomplete')provider.derivation.complete=false;if(fault==='timings-array')provider.safeTimingsRef=addObject(entries,encoded([]));
 addEntity(entries,'portable-provider',provider.attemptId,provider);const s=await upload(f,await pack(f.root,entries)),c=f.command({documentId:null,expectedDocumentRevision:null,body:{type:'PreviewBundleImport',stagingId:s.stagingId,expectedSha256:s.sha256}});assert.equal((await terminal(f,c)).json.receipt.status,'rejected');const db=new DatabaseSync(join(f.root,'metadata.sqlite'),{readOnly:true});assert.equal(db.prepare('SELECT count(*) n FROM portable_namespaces').get().n,0);db.close();
});
test('known transport-contaminated prompt hash is inspection-only without altering the exact staged original',async t=>{
 const {f,entries,prompt,provider}=await fixture(t,Buffer.from('KNOWN_SIGNED_TRANSPORT_SENTINEL'));addEntity(entries,'portable-provider',provider.attemptId,provider);const db=new DatabaseSync(join(f.root,'metadata.sqlite'));db.prepare('INSERT INTO portable_quarantined_hashes VALUES (?,?)').run(prompt.hash,'known-transport-sentinel');db.close();const archive=await pack(f.root,entries),p=await preview(f,archive);assert.equal(p.review.editable,false);assert.equal(p.review.reason,'TRANSPORT_PROVENANCE_QUARANTINED');const read=new DatabaseSync(join(f.root,'metadata.sqlite'),{readOnly:true}),name=read.prepare('SELECT filename FROM staged_assets WHERE id=?').get(p.stage.stagingId).filename;read.close();assert.deepEqual(await readFile(join(f.root,'uploads',name)),archive);
});

test('provider artifact-hash metadata has no invented 200-item format cap',async t=>{
 const {f,entries,provider}=await fixture(t);provider.assetHashes=Array(201).fill(provider.assetHashes[0]);addEntity(entries,'portable-provider',provider.attemptId,provider);const p=await preview(f,await pack(f.root,entries));assert.equal(p.review.editable,true);
});
