import test from 'node:test';
import assert from 'node:assert/strict';
import sharp from 'sharp';
import {setup,doc,edit,workspace,copy,preview,terminal,binary,upload} from './helpers.mjs';
import {startLocalServer} from '../../dist/local/server/http.js';
import {call,cookieFrom,readHeaders,mutationHeaders} from '../protocol/helpers.mjs';
import {importRaster} from '../raster/helpers.mjs';
import {randomUUID} from 'node:crypto';

async function reopen(t,f){const cookie=cookieFrom(f.paired);await f.server.close();const server=await startLocalServer({root:f.root});t.after(()=>server.close());const paired=await call(server.origin,'/api/v1/session/bootstrap',{method:'POST',headers:{Origin:server.origin,Cookie:cookie},body:{protocolVersion:1,pairingToken:new URL(server.issuePairingURL()).hash.slice(9)}});assert.equal(paired.status,200);return {root:f.root,server,paired,read:path=>call(server.origin,path,{headers:readHeaders(cookieFrom(paired))}),post:(path,body)=>call(server.origin,path,{method:'POST',body,headers:mutationHeaders(server,paired)}),command:(patch,body)=>f.command({...patch,clientId:paired.json.clientId},body)};}
async function persist(f,body){const before=(await f.read('/api/v1/ui/editor')).json;const r=await f.post('/api/v1/ui/editor',{protocolVersion:1,requestId:randomUUID(),sessionId:'editor',expectedUISeq:before.uiSeq,body});assert.equal(r.json.status,'accepted',r.text);}
test('pinned concurrent history and UI, draft isolation, exact reopen/export and original-command retry',async t=>{
 const f=await setup(t);await terminal(f,f.command({}, {width:3,height:2}));await terminal(f,f.command({documentId:'private_document'}, {width:1,height:1}));const {asset}=await importRaster(f,'hidden-alpha.png');const imported=await edit(f,{type:'ImportAsset',assetId:asset.id,layerId:'picture',name:'Original',draft:null});
 const text=Buffer.from('Draft 🦋 שלום 100% exact\nhttps://authored.example/?signature=literal'),s=await upload(f,text,'caption','text/plain'),a=(await workspace(f,{type:'FinalizeStaging',stagingId:s.stagingId,expectedSha256:s.sha256})).event.payload.asset;
 await persist(f,{type:'SaveDraft',draft:{id:'prompt',generation:'1',kind:'prompt',documentId:'document_1',targetLayerId:null,expectedDocumentRevision:'2',assetId:a.id,composing:true}});
 const secret=Buffer.from('UNRELATED_PRIVATE_DRAFT_SENTINEL'),p=await upload(f,secret,'caption','text/plain'),b=(await workspace(f,{type:'FinalizeStaging',stagingId:p.stagingId,expectedSha256:p.sha256})).event.payload.asset;
 await persist(f,{type:'SaveDraft',draft:{id:'private',generation:'1',kind:'prompt',documentId:'private_document',targetLayerId:null,expectedDocumentRevision:'1',assetId:b.id,composing:false}});
 const c=f.command({expectedDocumentRevision:'2',body:{type:'SaveCopy'}});const admission=await f.post('/api/v1/commands',c);assert.equal(admission.status,202);
 const changed=await edit(f,{type:'SetLayerProperties',layerId:'picture',layerVersion:'1',properties:{visible:false},draft:null});const saved=await terminal(f,c);assert.equal(saved.json.receipt.status,'accepted');const e=(await f.read('/api/v1/events?after='+String(BigInt(saved.json.receipt.fromSeq)-1n))).json.batches[0].events[0];const bytes=(await binary(f,'/api/v1/bundles/'+e.payload.bundle.bundleId+'/content')).bytes;assert.equal(bytes.includes(secret),false);assert.equal(bytes.includes(Buffer.from('private_document')),false);assert.equal(bytes.includes(text),true);
 const status=(await f.read('/api/v1/documents/document_1/save-status?sessionId=editor')).json;assert.equal(status.bundleOutdated,true);assert.equal(status.destinationStatus,'unconfirmed');
 const inspected=await preview(f,bytes),accepted=await workspace(f,{type:'ImportBundle',reviewId:inspected.review.reviewId,reviewHash:inspected.review.reviewHash});const restored=await doc(f,inspected.review.documentId);assert.equal(restored.revision,'2');const pixels=await sharp((await binary(f,'/api/v1/assets/'+restored.image.compositeAssetId+'/content')).bytes).ensureAlpha().raw().toBuffer();assert.deepEqual(pixels,Buffer.from([17,99,231,0,255,0,0,128,0,255,0,255,0,0,255,64,255,255,255,255,0,0,0,255]));
 const ui=(await f.read('/api/v1/ui/'+inspected.review.uiSessionIds[0])).json;assert.equal(ui.drafts.length,1);assert.equal(ui.drafts[0].composing,true);assert.equal(ui.drafts[0].documentId,restored.id);assert.notEqual(ui.drafts[0].assetId,a.id);assert.deepEqual((await binary(f,'/api/v1/assets/'+ui.drafts[0].assetId+'/content')).bytes,text);
 const g=await reopen(t,f);assert.deepEqual(await doc(g,restored.id),restored);assert.deepEqual((await terminal(g,accepted.command)).json.receipt,accepted.receipt);assert.deepEqual((await terminal(g,c)).json.receipt,saved.json.receipt);assert.deepEqual(await doc(g),changed.document);
 const exported=await edit(g,{type:'ExportDocument',historyHead:restored.historyHead},restored.id);const exportedAsset=exported.event.payload.asset;assert.deepEqual(await sharp((await binary(g,'/api/v1/assets/'+exportedAsset.id+'/content')).bytes).ensureAlpha().raw().toBuffer(),pixels);
 const copiedAgain=await copy(g,restored.id);const p2=await preview(g,copiedAgain.bytes);assert.equal(p2.review.editable,true);await workspace(g,{type:'ImportBundle',reviewId:p2.review.reviewId,reviewHash:p2.review.reviewHash});assert.notEqual(p2.review.documentId,restored.id);
});
test('review authority, namespace collision, source integrity and ranges are checked at public boundary',async t=>{
 const f=await setup(t);await terminal(f,f.command({}, {width:1,height:1}));const saved=await copy(f),p=await preview(f,saved.bytes);const path='/api/v1/bundles/'+saved.bundle.bundleId+'/content';
 const part=await binary(f,path,{Range:'bytes=7-19'});assert.equal(part.status,206);assert.deepEqual(part.bytes,saved.bytes.subarray(7,20));assert.match(part.headers['content-security-policy'],/sandbox/);assert.equal(part.headers['content-type'],'application/x-ideogram-project');assert.equal((await binary(f,path,{Range:'bytes=0-1,3-4'})).status,416);assert.deepEqual((await binary(f,path,{Range:'bytes=1-3','If-Range':'"wrong"'})).bytes,saved.bytes);
 const first=await workspace(f,{type:'ImportBundle',reviewId:p.review.reviewId,reviewHash:p.review.reviewHash});const second=f.command({documentId:null,expectedDocumentRevision:null,body:{type:'ImportBundle',reviewId:p.review.reviewId,reviewHash:p.review.reviewHash}});assert.equal((await terminal(f,second)).json.receipt.status,'rejected');assert.deepEqual((await terminal(f,first.command)).json.receipt,first.receipt);
 const p2=await preview(f,saved.bytes);f.paired=await f.post('/api/v1/session/renew',{protocolVersion:1});assert.equal((await f.read('/api/v1/bundle-reviews/'+p2.review.reviewId)).status,410);const stale=f.command({documentId:null,expectedDocumentRevision:null,body:{type:'ImportBundle',reviewId:p2.review.reviewId,reviewHash:p2.review.reviewHash}});assert.equal((await f.post('/api/v1/commands',stale)).status,410);
});
