import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {join,resolve} from 'node:path';
import {fork} from 'node:child_process';
import {once} from 'node:events';
import {readFile,writeFile,readdir,cp} from 'node:fs/promises';
import {priorWriter,priorCommit} from './prior-writer.mjs';
import {openWriter} from '../../dist/local/server/storage/writer.js';
import {rootFor,childFor,encode} from '../store/helpers.mjs';
import {digest} from './helpers.mjs';
let old;test.before(async t=>old=await priorWriter(t));
const inspect=root=>{const db=new DatabaseSync(join(root,'metadata.sqlite'),{readOnly:true});try{return {version:db.prepare('PRAGMA user_version').get().user_version,tables:Object.fromEntries(db.prepare("SELECT name FROM sqlite_schema WHERE type='table' ORDER BY name").all().map(x=>[x.name,db.prepare('SELECT * FROM '+x.name+' ORDER BY 1,2').all()]))};}finally{db.close();}};
const same=(after,before)=>{for(const [table,rows]of Object.entries(before.tables))assert.deepEqual(table==='schema_migrations'?after.tables[table].filter(x=>x.version<=7):after.tables[table],rows,table);};
const release=gate=>{Atomics.store(new Int32Array(gate),0,1);Atomics.notify(new Int32Array(gate),0);};
async function seed(t){const f=await old.setup(t);await old.terminal(f,f.command({}, {width:1,height:1}));const saved=await old.copy(f),p=await old.preview(f,saved.bytes);await old.workspace(f,{type:'ImportBundle',reviewId:p.review.reviewId,reviewHash:p.review.reviewHash});await f.server.close();const c=f.command({documentId:'document_1',expectedDocumentRevision:'1',body:{type:'SaveCopy'}}),a={clientId:f.paired.json.clientId,sessionHash:'b'.repeat(64),now:Date.now(),expires:Date.now()+1800000},prior=await old.childFor(t,f.root,{phase:'portable-preparation-after-commit'}),sent=prior.call('portableCommand',encode(c),a).catch(()=>{});await prior.wait('barrier');await prior.kill();await sent;return {f,c,a};}
async function files(root){const result={};async function visit(path){for(const file of await readdir(join(root,path),{withFileTypes:true})){const next=join(path,file.name);if(file.isDirectory())await visit(next);else result[next]=digest(await readFile(join(root,next)));}}for(const path of ['objects','staging','uploads','portable'])await visit(path);return result;}
async function preserved(root,before){for(const [path,hash]of Object.entries(before))assert.equal(digest(await readFile(join(root,path))),hash,path);}
test('schema8 fences the actual d4 writer and verifies schema7 rollback including pending portable captures',async t=>{
 const {f,c}=await seed(t),before=inspect(f.root),bytes=await files(f.root),gate=new SharedArrayBuffer(4);assert.equal(before.version,7);let hit;const barrier=new Promise(r=>hit=r),opening=openWriter({root:f.root},{phase:'portable-transaction-schema-after-activation',gate,onBarrier:hit});await barrier;let migration;
 try{const after=inspect(f.root);assert.equal(after.version,8);same(after,before);migration=JSON.parse(after.tables.schema_migrations.find(x=>x.version===8).receipt);assert.equal(migration.capability,'portable-copy-v2-transaction-bounds');assert.equal(migration.rollback.compatibleExecutable,priorCommit);const manifest=JSON.parse(await readFile(join(f.root,migration.manifestFile)));assert.equal(manifest.storageVersion,7);assert.deepEqual(manifest.retainedDirectories,['objects','staging','uploads','portable']);assert.equal(manifest.backupHash,digest(await readFile(join(f.root,migration.backup))));const saved=new DatabaseSync(join(f.root,migration.backup),{readOnly:true});try{assert.equal(saved.prepare('PRAGMA integrity_check').get().integrity_check,'ok');for(const [table,rows]of Object.entries(before.tables))assert.deepEqual(saved.prepare('SELECT * FROM '+table+' ORDER BY 1,2').all(),rows,table);}finally{saved.close();}await preserved(f.root,bytes);
 }finally{release(gate);}const w=await opening;await w.close();const refusal=inspect(f.root);await assert.rejects(old.openWriter({root:f.root}),{code:'UNSUPPORTED_STORAGE'});assert.deepEqual(inspect(f.root),refusal);await preserved(f.root,bytes);
 const rollback=await rootFor(t);for(const name of ['objects','staging','uploads','portable'])await cp(join(f.root,name),join(rollback,name),{recursive:true});await writeFile(join(rollback,'metadata.sqlite'),await readFile(join(f.root,migration.backup)),{mode:0o600});assert.deepEqual(inspect(rollback),before);await preserved(rollback,bytes);const prior=await old.openWriter({root:rollback});t.after(()=>prior.close());let state;for(let i=0;i<1000;i++){state=await prior.commandState(c.command.commandId);if(state.record)break;await new Promise(r=>setTimeout(r,5));}assert.equal(state.record?.receipt.status,'accepted');assert.equal(state.record.hash,before.tables.portable_preparations[0].hash);assert.deepEqual(state.record.command,c.command);t.diagnostic(JSON.stringify({migration,priorRefusal:'UNSUPPORTED_STORAGE',rollbackCommand:state.record.command.commandId,rollbackReceipt:state.record.receipt,allOriginalTablesAndFilesPreserved:true}));
});
test('schema8 capacity refusal leaves schema7 and exact pending requests intact',async t=>{const {f}=await seed(t),before=inspect(f.root),bytes=await files(f.root);await assert.rejects(openWriter({root:f.root,quotaBytes:'1'}),{code:'CAPACITY'});assert.deepEqual(inspect(f.root),before);await preserved(f.root,bytes);const w=await openWriter({root:f.root});await w.close();assert.equal(inspect(f.root).version,8);});
for(const target of ['backup-written','database','manifest'])test('schema8 activation refuses changed '+target+' without altering source',async t=>{const {f}=await seed(t),before=inspect(f.root),bytes=await files(f.root),gate=new SharedArrayBuffer(4);let hit;const barrier=new Promise(r=>hit=r),opening=openWriter({root:f.root},{phase:target==='backup-written'?'portable-transaction-schema-backup-written':'portable-transaction-schema-before-activation',gate,onBarrier:hit}),rejected=assert.rejects(opening,{code:'CORRUPT_STORE'});await barrier;const name=(await readdir(f.root)).find(x=>target==='manifest'?/^schema7-backup-.*\.manifest\.json$/.test(x):/^schema7-backup-.*\.sqlite$/.test(x));if(target==='manifest')await writeFile(join(f.root,name),'{}');else{const db=new DatabaseSync(join(f.root,name));db.prepare("UPDATE meta SET value='999' WHERE key='writerEpoch'").run();db.close();}release(gate);await rejected;assert.deepEqual(inspect(f.root),before);await preserved(f.root,bytes);const corrupt=digest(await readFile(join(f.root,name))),w=await openWriter({root:f.root});await w.close();assert.equal(digest(await readFile(join(f.root,name))),corrupt);});
for(const phase of ['before-backup','backup-written','backup-verified','before-activation','after-activation'])test('schema8 SIGKILL '+phase+' retains pending identity and original portable files',async t=>{const {f}=await seed(t),before=inspect(f.root),bytes=await files(f.root),child=await killAt(t,f.root,'portable-transaction-schema-'+phase);const after=inspect(f.root);assert.equal(after.version,phase==='after-activation'?8:7);same(after,before);await preserved(f.root,bytes);const w=await openWriter({root:f.root});await w.close();assert.equal(inspect(f.root).version,8);await preserved(f.root,bytes);});

async function killAt(t,root,phase){const dir=await rootFor(t),file=join(dir,'kill.mjs');await writeFile(file,`import{openWriter}from ${JSON.stringify(new URL('../../dist/local/server/storage/writer.js',import.meta.url).href)};await openWriter({root:process.argv[2]},{phase:process.argv[3],gate:new SharedArrayBuffer(4),onBarrier:phase=>process.send({phase})});`);const child=fork(file,[root,phase],{execArgv:['--import',resolve('tests/session/no-egress.mjs')],stdio:['ignore','ignore','pipe','ipc']}),ended=once(child,'exit');let errors='';child.stderr.on('data',b=>errors+=b);t.after(async()=>{if(child.exitCode===null&&child.signalCode===null){child.kill('SIGKILL');await ended;}});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('schema8 barrier timeout '+errors)),15000);child.once('message',m=>{clearTimeout(timer);assert.equal(m.phase,phase);resolve();});child.once('exit',()=>{clearTimeout(timer);reject(Error('schema8 early exit '+errors));});});child.kill('SIGKILL');await ended;}
