import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,readdirSync,existsSync} from 'node:fs';
import {resolve,relative,dirname} from 'node:path';
import {createHash} from 'node:crypto';
const repo=process.cwd();
const {syntaxInventory}=await import(repo+'/tests/editor/completion/host-final-issuers.mjs');
const sha=b=>createHash('sha256').update(b).digest('hex');
const all=dir=>readdirSync(dir,{withFileTypes:true}).flatMap(d=>d.isDirectory()?all(dir+'/'+d.name):[dir+'/'+d.name]);
const assets=all('dist/app'),sources=all('src').filter(p=>/\.(ts|json)$/.test(p));
const entries=['tests/editor/composition.spec.ts','tests/editor/composition.config.ts','tests/editor/composition-save.spec.ts','tests/editor/composition-save.config.ts','tests/editor/integration.spec.ts','tests/editor/integration-reads.spec.ts','tests/editor/integration-fixture.ts','tests/editor/integration.config.ts','tests/editor/integration-regression.config.ts','tests/editor/process-completion-fixture.mjs'];
const reached=new Set();function follow(path){if(reached.has(path))return;assert(existsSync(path),'Test import closure '+path);reached.add(path);if(!/\.(ts|mjs|js)$/.test(path))return;const syntax=syntaxInventory(path,readFileSync(path,'utf8'));for(const edge of syntax.edges){if(!edge.value.startsWith('.'))continue;let dest=relative('.',resolve(dirname(path),edge.value));if(dest.startsWith('dist/local/'))continue;if(!existsSync(dest)&&dest.endsWith('.js'))dest=dest.slice(0,-3)+'.ts';if(existsSync(dest))follow(dest);else assert(false,'Closed test module '+dest);}}
for(const path of entries)follow(path);
const files=[...new Set([...assets,...sources,...reached,'package-lock.json','node_modules/rolldown/package.json','node_modules/@en-reve/elements/package.json','node_modules/@en-reve/primitives/package.json','node_modules/lit/package.json','node_modules/playwright/package.json'])].sort();
const pins=files.map(path=>{const b=readFileSync(path);let role=path.startsWith('tests/')?'injection':path.includes('worker-')?'worker':path.includes('editor-panels-')?'dynamic':path.includes('icon-')?'vendor':path.startsWith('dist/')?'emitted':'source';return {path,bytes:b.length,sha256:sha(b),role};});
const modules=pins.filter(p=>/\.(js|mjs|ts)$/.test(p.path)).map(p=>({path:p.path,syntax:syntaxInventory(p.path,readFileSync(p.path,'utf8'))}));
const direct=modules.filter(m=>m.path.startsWith('dist/app/')).flatMap(m=>m.syntax.calls.filter(c=>['fetch','XMLHttpRequest'].includes(c.callee)).map(c=>({path:m.path,...c})));
assert.equal(direct.filter(c=>c.callee==='fetch').length,8);assert.equal(direct.filter(c=>c.callee==='XMLHttpRequest').length,3);
for(const m of modules){if(m.path==='tests/editor/completion/host-final-issuers.mjs')assert.deepEqual(m.syntax.keepalive.map(k=>k.expression),['keepalive'],'Node-only syntax inventory shorthand');else assert.equal(m.syntax.keepalive.length,0,'No undeclared explicit keepalive option '+m.path);}
const worker=modules.find(m=>m.path.includes('worker-'));const workerFallbacks=worker.syntax.calls.filter(c=>c.callee==='fetch'&&c.at<85000||['t.send','r.send'].includes(c.callee)).map(c=>({path:worker.path,at:c.at,source:c.source,method:'GET',body:null,keepalive:false,scope:'CanvasKit generic loader remains emitted and may execute on fallback; fetch credentials same-origin; XHR send(null); not globally unreachable'}));assert.equal(workerFallbacks.length,5);
const documentEdges=[...readFileSync('dist/app/index.html','utf8').matchAll(/(?:src|href)="([^"]+)"/g)].map(m=>m[1]).filter(Boolean);const cssEdges=[...readFileSync('dist/app/assets/index-CKeqbJD0.css','utf8').matchAll(/url\(([^)]+)\)/g)].map(m=>m[1]);for(const edge of [...documentEdges,...cssEdges])assert(pins.some(p=>p.path==='dist/app'+edge),'Closed HTML/CSS asset '+edge);
const manifest={nodeOnlyMetadataAssets:modules.find(m=>m.path==='tests/editor/completion/host-final-issuers.mjs').syntax.assets,computedAssetPrefixes:[{path:'tests/editor/original-font-reader.ts',prefix:'/assets/',source:'sealedBrowserFonts exact profile hash and unique emitted font basename'}],documentEdges,cssEdges,kind:'PINNED-APPLICATION-ISSUERS-280',pins,modules,assetFiles:readdirSync('dist/app/assets').sort(),directBrowserNetworking:direct,
 browserBodyIssuers:[
 {kind:'session-json',source:'src/state/session-client.ts:request',emitted:'shell-CJmMbJF4.js:443946',methods:['GET','POST'],body:'JSON.stringify(body) only for protocol session/bootstrap/renew/revoke; private request closure',keepalive:false,telemetryCharge:false,options:'same-origin/no-store/error; original abort/timeout signal'},
 {kind:'application-transport',source:'src/state/session-client.ts:transport; all src/state/editor-client.ts json/post/command/staging and src/state/draft-persistence.ts callers pinned',emitted:'shell-CJmMbJF4.js:445897',methods:['GET','HEAD','POST','PUT'],body:'Original commands, UI checkpoints/drafts, native admission, staging setup and binary staging PUT. All caller init objects pinned; no keepalive option or Request input.',keepalive:false,telemetryCharge:false,options:'spread original init then headers/same-origin/no-store/error; no added signal'},
 {kind:'recovery-release',source:'src/state/recovery-client.ts:recover finally/default transport and supplied session transport',emitted:'shell-CJmMbJF4.js:452551',methods:['GET','POST'],body:'POST literal protocolVersion JSON for recovery release; ordinary GET stream/content/revalidation retain own init',keepalive:false,telemetryCharge:false,options:'Default transport spread init then same-origin and X-App-Client; stream signal is not propagated to other calls'},
 {kind:'private-native-beacon',source:'tests/editor/completion/host-final-page.mjs:genuineIntegrationHostFinal',methods:['POST'],body:'Complete privately registered UTF-8 native snapshot metadata, <=32768 bytes before original native sendBeacon',keepalive:true,telemetryCharge:true,maximum:32768,options:'Original native same-origin sendBeacon, single invocation, no reissue'}],
 workerFallbacks,
 bodylessIssuers:[{source:'index-BfDsElky.js:865',scope:'Vite modulepreload polyfill',options:'GET/no body/default keepalive false; credentials derived only from fixed link crossOrigin, integrity/referrer fields'}, {source:'preload-helper-BZ1Pz5am.js + HTML/CSS/static and dynamic edges',scope:'Pinned modulepreload/style/worker/font/image imports and links',options:'Browser asset GETs; no form/body method override in selected workflow'}, {source:'src/text/contracts.ts readSealedAsset emitted shell:71928 worker:86077',scope:'WASM/font read',options:'GET/no body/same-origin/redirect:error/original signal'}, {source:'src/text/engine.ts createTextEngine',scope:'Pinned same-origin WASM bytes/hash/compile and explicit instantiateWasm callback',options:'Generic CanvasKit fallbacks are retained in worker inventory, all bodyless; no universal reachability claim'}],
 injectionMap:[{source:'tests/editor/original-font-reader.ts',effect:'GET font observer forwards every original nativeFetch this/args unchanged; no new request/body/keepalive'}, {source:'tests/editor/original-recovery-reader.ts',effect:'GET reader/IDB observation forwards nativeFetch this/args unchanged; no new request/body/keepalive'}, {source:'tests/editor/completion/completion-observer.mjs',effect:'Original Worker constructor/messages/terminate forwarding only; no added worker messages or payload reads'}, {source:'tests/editor/completion/host-final-page.mjs',effect:'One declared metadata beacon; genuine handler+journal consistency; receiver has no native operation'}, {source:'tests/editor/integration-fixture.ts + owned-opfs.ts + error-monitor.ts',effect:'SaveFilePicker disabled; CSP/DOM metadata callbacks; owned bodyless storage probe documents; no additional bodyful issuer'}, {source:'tests/editor/integration.spec.ts + integration-reads.spec.ts',effect:'Pinned public UI/file operations and held original routes; continue preserves original arguments; no network option substitution'}],
 closure:{html:'dist/app/index.html',css:'dist/app/assets/index-CKeqbJD0.css',vendor:'en-reve/Lit materialized in pinned shell/icon/panels bundles; package-lock and installed package identities retained',worker:'Explicit Worker URL asset is an entry even though its IIFE has no ES module imports; WASM/font literal asset edges are separately closed',server:'Ordinary server source/compiled inputs separate; Node body reader only on exact private POST; ordinary requests passed unchanged'},unknownIssuers:[],limits:['Source-derived pinned map plus exact call/import inventory; no browser/CSP/host capability proof','Actual telemetry charges and future reservation headroom must be recorded by the parent-owned runtime ledger; no saved267 byte transfer','Unknown changed source/issuer or incomplete closure refuses readiness']};
const one=predicate=>{const rows=direct.filter(predicate);assert.equal(rows.length,1);return rows[0];},at=row=>row.path+':'+row.at;
const session=one(x=>x.source.includes('AbortSignal.timeout(1e4)')),transport=one(x=>x.source.includes('...n,headers:r,credentials:')),recovery=one(x=>x.source.includes('X-App-Client')),preload=one(x=>x.path.includes('/index-')),sealed=direct.filter(x=>x.source==='fetch(e,{credentials:`same-origin`,redirect:`error`,signal:n})');assert.equal(sealed.length,2);
for(const [kind,row]of [['session-json',session],['application-transport',transport],['recovery-release',recovery]])manifest.browserBodyIssuers.find(x=>x.kind===kind).emitted=at(row);
manifest.bodylessIssuers[0].source=at(preload);manifest.bodylessIssuers[2].source='src/text/contracts.ts readSealedAsset; '+sealed.map(at).join('; ');
manifest.injectionMap.push({source:'tests/editor/composition.spec.ts',effect:'Existing public trusted mode actions and read-only public mode diagnostics; no added fetch/body/keepalive'});
writeFileSync('tests/editor/completion/host-final-issuers.json' ,JSON.stringify(manifest,null,2));console.log(JSON.stringify({pins:pins.length,modules:modules.length,directBrowserNetworking:direct,workerFallbacks,issuerManifestBytes:readFileSync('tests/editor/completion/host-final-issuers.json').length}));
