import test from 'node:test';
import {rootFor} from '../store/helpers.mjs';
import {cookieFrom} from '../session/helpers.mjs';
import {binary} from '../raster/helpers.mjs';
import {unpack,pack,records,putRecords} from '../portable/archive-fixture.mjs';
import {priorWriter} from './prior-writer.mjs';
import {createHash} from 'node:crypto';
const hash=x=>'sha256:'+createHash('sha256').update(x).digest('hex');
const identify=v=>{const {id,...body}=v;return {...body,id:hash(canonical(body))};};
import {isolated} from './helpers.mjs';
import assert from 'node:assert/strict';
import {readFile,writeFile,unlink,mkdir,cp} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {chromium,webkit,firefox} from '@playwright/test';
import {setup,terminal,workspace,edit,doc,upload,copy,preview} from '../portable/helpers.mjs';
import {openWriter} from '../../dist/local/server/storage/writer.js';
import {canonical} from '../../dist/local/server/storage/canonical.js';
const profile=JSON.parse(await readFile('src/text/profile.json'));
const file=(root,ref)=>join(root,'objects','sha256',ref.hash.slice(7,9),ref.hash.slice(7));
for(const engine of (process.env.TEXT_STATE_ENGINES??'chromium').split(','))test('native '+engine+' durable text/history/copy/restart exact identities',async t=>{
 const f=await isolated(t);await terminal(f,f.command({}, {width:120,height:70}));
 const stage=async(bytes,media='application/octet-stream',purpose='text')=>{const s=await upload(f,bytes,purpose,purpose==='caption'?'text/plain':'application/octet-stream');const result=await workspace(f,{type:'FinalizeStaging',stagingId:s.stagingId,expectedSha256:s.sha256});return {...result.event.payload.asset.blob,mediaType:media};};
 const fonts=[];
 for(const font of profile.fonts.filter(x=>['NotoSans','NotoSansCJKsc'].includes(x.id))){const source=await stage(await readFile('vendor/text/'+font.file),'application/octet-stream','font'),license=await stage(await readFile('vendor/text/'+font.licenseFile),'text/plain','caption');const r=await edit(f,{type:'ImportFont',source,license,origin:'bundled',embeddingReviewed:true});fonts.push(r.event.payload.asset.font);}
 const browser=await ({chromium,webkit,firefox}[engine]).launch();t.after(()=>browser.close());const context=await browser.newContext(),page=await context.newPage();let workers=0,closed=0;const errors=[],closedSignals=[];page.on('worker',w=>{workers++;closedSignals.push(new Promise(resolve=>w.once('close',()=>{closed++;resolve();})));});page.on('pageerror',e=>errors.push(e.message));
 await page.exposeFunction('stage',async(base64,media)=>stage(Buffer.from(base64,'base64'),media));
 await page.exposeFunction('admit',async id=>{const r=await f.post('/api/v1/text-admission/'+id,{protocolVersion:1});assert.equal(r.status,200,r.text);});
 await page.exposeFunction('protocolRead',async path=>{const r=await f.read(path);return {status:r.status,text:r.text,headers:r.headers};});
 await page.goto(f.server.origin);await page.waitForFunction(()=>!!window.DurableTextPreparation);
 await page.evaluate(()=>{window.preparation=new window.DurableTextPreparation({admit:id=>window.admit(id),releaseAdmission:async()=>{},stage:async(blob,media)=>{if(window.holdStage)await new Promise(resolve=>window.releaseStage=resolve);const bytes=new Uint8Array(await blob.arrayBuffer());let binary='';for(let at=0;at<bytes.length;at+=32768)binary+=String.fromCharCode(...bytes.subarray(at,at+32768));return window.stage(btoa(binary),media);}});});
 let generation=0,uiSeq='0';const draftId='text_draft';
 async function candidate(text,layerVersion='0',type='CreateTextLayer',selected=fonts){
  const d=await doc(f);generation++;
  const textUtf8=await stage(Buffer.from(text),'text/plain','caption');const style={primaryFont:selected[0].bytes.hash,explicitFallbacks:selected.slice(1).map(f=>f.bytes.hash),sizePx:32,lineHeightMultiplier:1.2,fill:[40,90,190,255],align:'start',direction:'auto'};const draftBytes=Buffer.from(canonical({schemaVersion:1,kind:'text-draft-1',textUtf8,style,frame:{width:120,height:70},fonts:selected}));
  const textAssetStage=await upload(f,draftBytes,'caption','text/plain'),a=await workspace(f,{type:'FinalizeStaging',stagingId:textAssetStage.stagingId,expectedSha256:textAssetStage.sha256});
  const ui=await f.post('/api/v1/ui/session_1',{protocolVersion:1,requestId:randomUUID(),sessionId:'session_1',expectedUISeq:uiSeq,body:{type:'SaveDraft',draft:{id:draftId,generation:String(generation),kind:'text',documentId:d.id,targetLayerId:type==='CreateTextLayer'?null:'native_text',expectedDocumentRevision:d.revision,assetId:a.event.payload.asset.id,composing:false}}});assert.equal(ui.json.status,'accepted',ui.text);uiSeq=ui.json.uiSeq;
  const result=await page.evaluate(async({text,revision,layerVersion,generation,fonts,fontNames})=>{const request=await window.textFixture.request(text,fontNames,{token:{documentId:'document_1',documentRevision:revision,layerId:'native_text',layerVersion,sessionId:'session_1',generation},frame:{width:120,height:70}});return window.preparation.prepare(request,fonts);},{text,revision:d.revision,layerVersion,generation,fonts:selected,fontNames:selected.map(f=>profile.fonts.find(p=>'sha256:'+p.sha256===f.bytes.hash).id)});
  const savedCandidate=JSON.parse(await readFile(file(f.root,result.candidate)));await writeFile('evidence/p1c2-text-state/layout-'+savedCandidate.source.render.layout.hash.slice(7)+'.json',await readFile(file(f.root,savedCandidate.source.render.layout)));
  const body={type,layerId:'native_text',...(type==='CreateTextLayer'?{name:'Native text'}:{layerVersion,reviewedDependencyHash:result.dependencyHash}),candidate:result.candidate,draft:{sessionId:'session_1',draftId,generation:String(generation)},admissionId:result.admissionId};return {d,body,result};
 }
 async function apply(c){const command=f.command({expectedDocumentRevision:c.d.revision,body:c.body});const result=await terminal(f,command);if(result.json.receipt.status!=='accepted'){const detail=await readFile(file(f.root,result.json.receipt.details)).catch(()=>Buffer.from('missing detail'));assert.fail(result.text+' '+detail);}
  uiSeq=(await f.read('/api/v1/ui/session_1')).json.uiSeq;return {command,receipt:result.json.receipt,document:await doc(f)};}
 const first=await apply(await candidate('Café\n東京'));const state=(await f.read('/api/v1/documents/document_1/image')).json;assert.equal(state.layers[0].kind,'text');const originalSource=JSON.parse(await readFile(file(f.root,state.layers[0].source)));assert.equal(Buffer.from(await readFile(file(f.root,originalSource.text.textUtf8))).toString(),'Café\n東京');
 assert.equal((await terminal(f,first.command)).json.receipt.toSeq,first.receipt.toSeq);

 async function reject(c,reason){const before=await doc(f),r=await terminal(f,f.command({expectedDocumentRevision:c.d.revision,body:c.body}));assert.equal(r.json.receipt.status,'rejected',r.text);assert.equal(r.json.rejectionDetails.value.issues[0].code,reason,r.text);assert.deepEqual(await doc(f),before);return r;}
 const stale=await candidate('stale','1','CommitTextEdit');stale.body.draft.generation='1';await reject(stale,'DRAFT_GENERATION_CHANGED');
 const glyph=await candidate('bad glyph','1','CommitTextEdit'),g=JSON.parse(await readFile(file(f.root,glyph.result.candidate))),layout=JSON.parse(await readFile(file(f.root,g.source.render.layout)));layout.paragraphs[0].runs[0].glyphs[0]=0;g.source.render.layout=await stage(Buffer.from(canonical(layout)),'application/json');g.source.render=identify(g.source.render);glyph.body.candidate=await stage(Buffer.from(canonical(g)),'application/json');await reject(glyph,'TEXT_LAYOUT_INVALID');
 const future=await candidate('profile','1','CommitTextEdit'),v=JSON.parse(await readFile(file(f.root,future.result.candidate)));v.source.render.rendererProfile.id='sha256:'+'a'.repeat(64);v.source.render=identify(v.source.render);future.body.candidate=await stage(Buffer.from(canonical(v)),'application/json');await reject(future,'TEXT_PROFILE_UNSUPPORTED');
 await reject(await candidate('東京','1','CommitTextEdit',[...fonts].reverse()),'REVIEWED_FONT_REPLACEMENT_REQUIRED');
 const replaced=await apply(await candidate('東京','1','ReplaceTextFont',[...fonts].reverse()));const replacement=(await f.read('/api/v1/documents/document_1/image')).json;assert.notEqual(replacement.layers[0].source.hash,state.layers[0].source.hash);await edit(f,{type:'Undo',historyHead:replaced.document.historyHead});assert.deepEqual((await doc(f)).image,first.document.image);
 const empty=await apply(await candidate('','1','CommitTextEdit'));const emptyState=(await f.read('/api/v1/documents/document_1/image')).json;assert.equal(emptyState.layers.length,1);
 const emptySource=JSON.parse(await readFile(file(f.root,emptyState.layers[0].source)));assert.equal(Number(emptySource.text.textUtf8.byteLength),0);assert((await readFile(file(f.root,emptySource.render.pixels))).every(x=>x===0));
 const undone=(await edit(f,{type:'Undo',historyHead:empty.document.historyHead})).document;assert.deepEqual(undone.image,first.document.image);
 await edit(f,{type:'SetLayerProperties',layerId:'native_text',layerVersion:'1',properties:{visible:false},draft:null});const branched=await doc(f);assert.notEqual(branched.branchId,empty.document.branchId);
 await edit(f,{type:'SaveCheckpoint',name:'Hidden text'});
 const derivativeSource=JSON.parse(await readFile(file(f.root,state.layers[0].source)));await edit(f,{type:'RasterizeTextDerivative',layerId:'native_text',layerVersion:'2',newLayerId:'derived_image',name:'Raster derivative',hideOriginal:false,reviewedRender:derivativeSource.render.id,draft:null});



 const beforeCancel=await doc(f);await page.evaluate(async fonts=>{const request=await window.textFixture.request('cancel',['NotoSans','NotoSansCJKsc']);window.holdStage=true;window.cancelled=window.preparation.prepare(request,fonts).then(()=>({accepted:true}),e=>({error:e.message}));return true;},fonts);await page.waitForFunction(()=>!!window.releaseStage);const held=await page.evaluate(()=>window.textMemory.snapshot);await page.evaluate(()=>{window.preparation.cancel();window.holdStage=false;window.releaseStage();});const cancelled=await page.evaluate(()=>window.cancelled);assert.equal(cancelled.error,'TEXT_STALE');const dropped=await page.evaluate(()=>window.textMemory.snapshot);assert(dropped.textBytes<held.textBytes);assert.deepEqual(await doc(f),beforeCancel);
 const pending=await candidate('uncommitted','2','CommitTextEdit');await page.evaluate(()=>{window.preparation.dispose();window.textFixture.renderer.dispose();});await Promise.race([Promise.all(closedSignals),new Promise((_,reject)=>{const timer=setTimeout(()=>reject(Error('Actual worker close was not observed')),10000);timer.unref();})]);await context.close();assert.equal(closed,workers);assert.deepEqual(errors,[]);assert.equal((await f.post('/api/v1/text-admission/'+pending.body.admissionId+'/release',{protocolVersion:1})).status,200);
 const copied=await copy(f);const reviewed=await preview(f,copied.bytes);assert.equal(reviewed.review.editable,true,canonical(reviewed.review));assert.equal(reviewed.review.formatVersion,3);
 const futureArchive=await unpack(f.root,copied.bytes),futureEvents=records(futureArchive,'events');futureEvents.values.find(r=>r.event?.payload?.asset?.font).event.payload.asset.font.schemaVersion=999;putRecords(futureArchive,futureEvents.path,futureEvents.values);const futureReview=await preview(f,await pack(f.root,futureArchive));assert.equal(futureReview.review.editable,false);assert.equal(futureReview.review.reason,'UNSUPPORTED_FONT_VERSION');
 const imported=await workspace(f,{type:'ImportBundle',reviewId:reviewed.review.reviewId,reviewHash:reviewed.review.reviewHash});const newId=imported.event.payload.document.id;const importedState=(await f.read('/api/v1/documents/'+newId+'/image')).json;assert.equal(importedState.layers[0].kind,'text');assert.equal(importedState.layers[0].source.hash,state.layers[0].source.hash);await copy(f,newId);const inventory=new Set();let after='';do{const page=(await f.read('/api/v1/documents/'+newId+'/closure?after='+encodeURIComponent(after))).json;page.items.forEach(r=>inventory.add(r.hash));after=page.next;}while(after);for(const ref of [state.layers[0].source,originalSource.text.textUtf8,originalSource.render.layout,originalSource.render.pixels,...originalSource.text.fonts.flatMap(f=>[f.bytes,f.licenseRecord])])assert(inventory.has(ref.hash),'import inventory '+ref.hash);
 const recoveryContext=await browser.newContext(),recoveryPage=await recoveryContext.newPage();await recoveryPage.exposeFunction('protocolRead',async path=>{const r=await f.read(path);return {status:r.status,text:r.text,headers:r.headers};});await recoveryPage.goto(f.server.origin);await recoveryPage.waitForFunction(()=>!!window.RecoveryConsumer);const recovered=await recoveryPage.evaluate(async id=>{const cache=await window.RecoveryCache.open('durable-text-recovery');try{const client=new window.RecoveryConsumer(cache,async path=>{const r=await window.protocolRead(path);return new Response(r.text,{status:r.status,headers:r.headers});});await client.recover();return await cache.read('document',id);}finally{cache.close();}},newId);assert.equal(recovered.id,newId);assert.deepEqual(recovered.image,(await doc(f,newId)).image);await recoveryContext.close();
 // Exact old appearance is usable with a historical font absent; complete copy refuses.
 const missing=originalSource.text.fonts[0].bytes,saved=await readFile(file(f.root,missing));await unlink(file(f.root,missing));
 const badCommand=f.command({expectedDocumentRevision:(await doc(f)).revision,body:{type:'SaveCopy'}});const badCopy=await terminal(f,badCommand);assert.equal(badCopy.json.receipt.status,'rejected',badCopy.text);
 await writeFile(file(f.root,missing),saved,{mode:0o600});await copy(f);
 const cookie=cookieFrom(f.paired);await f.server.close();
 // Prior executable reads PF3 as read-only without pretending to understand text.
 if(engine==='chromium'){const old=await priorWriter(t),prior=await old.setup(t);const reviewedOld=await old.preview(prior,copied.bytes);assert.equal(reviewedOld.review.editable,false);assert.equal(reviewedOld.review.reason,'UNSUPPORTED_FORMAT_VERSION');await prior.server.close();}
 const expected=await readFile(file(f.root,originalSource.render.pixels));await unlink(file(f.root,missing));
 const restart=await isolated(t,{root:f.root,cookie});const restored=(await restart.read('/api/v1/documents/document_1/image')).json;assert.equal(restored.layers.filter(l=>l.kind==='text').length,1);assert.equal(restored.layers[0].source.hash,state.layers[0].source.hash);assert.deepEqual(await readFile(file(f.root,originalSource.render.pixels)),expected);
 const live=await doc(restart),exported=await edit(restart,{type:'ExportDocument',historyHead:live.historyHead});assert.equal(exported.document.revision,live.revision);const refusal=await terminal(restart,restart.command({expectedDocumentRevision:live.revision,body:{type:'SaveCopy'}}));assert.equal(refusal.json.receipt.status,'rejected');await restart.server.close();await writeFile(file(f.root,missing),saved,{mode:0o600});
 if(engine==='chromium')for(const phase of ['history-before-commit','history-after-commit']){
  const root=await rootFor(t);await cp(f.root,root,{recursive:true});const crash=await isolated(t,{root,cookie:cookieFrom(restart.paired),phase});assert.equal((await crash.post('/api/v1/text-admission/'+pending.body.admissionId,{protocolVersion:1})).status,200);const command=crash.command({expectedDocumentRevision:pending.d.revision,body:pending.body});const sent=crash.post('/api/v1/commands',command).catch(()=>null);await crash.wait('barrier');await crash.kill();await sent;
  const db=new DatabaseSync(join(root,'metadata.sqlite'),{readOnly:true});const events=db.prepare('SELECT * FROM events_v2 WHERE command_id=?').all(command.command.commandId),record=db.prepare('SELECT * FROM commands WHERE id=?').get(command.command.commandId),preparation=db.prepare('SELECT * FROM history_preparations WHERE id=?').get(command.command.commandId);assert.equal(events.length,phase==='history-after-commit'?2:0);if(events.length)assert.deepEqual(events.map(e=>JSON.parse(e.json).type).sort(),['AssetRegistered','ImageEdited']);const draftCheckpoint=JSON.parse(db.prepare('SELECT json FROM ui_checkpoints WHERE client_id=? AND session_id=?').get(command.command.clientId,'session_1').json);assert.equal(draftCheckpoint.drafts.find(d=>d.id==='text_draft').status,phase==='history-after-commit'?'applied':'saved-unapplied');assert.equal((record??preparation).original,JSON.stringify(command));db.close();
  const resumed=await isolated(t,{root,cookie:cookieFrom(crash.paired)});const result=await terminal(resumed,command);assert.equal(result.json.receipt.status,phase==='history-after-commit'?'accepted':'rejected');const current=await doc(resumed);assert.equal(current.revision,phase==='history-after-commit'?String(BigInt(pending.d.revision)+1n):pending.d.revision);assert.deepEqual((await terminal(resumed,command)).json,result.json);if(phase==='history-after-commit'){await edit(resumed,{type:'Undo',historyHead:current.historyHead});assert.deepEqual((await resumed.read('/api/v1/documents/document_1/image')).json,restored);}await resumed.server.close();
 }

 t.diagnostic(canonical({engine,profile:profile.id,first:first.receipt,empty:empty.receipt,source:state.layers[0].source,workers,closed,copyHash:copied.bundle.blob.hash}));
});
