import '@en-reve/tokens/default.css';
import './style.css';
import {html,render} from 'lit';
import {createElementScope} from '@en-reve/elements/element-scope.js';
import {buttonDefinition} from '@en-reve/elements/definitions/button.js';
import {EMPTY_EXPECTED_VERSIONS} from '../../../src/protocol/store.js';
import {RecoveryCache} from '../../../src/state/recovery-cache.js';
import {RecoveryConsumer} from '../../../src/state/recovery-client.js';
const w=window as any,token=w.__IE_PAIRING__;delete w.__IE_PAIRING__;
const response=await fetch('/api/v1/session/bootstrap',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({protocolVersion:1,pairingToken:token})});if(!response.ok)throw Error('Pairing failed');const session=await response.json();
const transport=(path:string,init?:RequestInit)=>fetch(path,{...init,headers:{'X-App-Client':'LP-1',...init?.headers}});
const cache=await RecoveryCache.open('raster-review-consumer');const recovery=new RecoveryConsumer(cache,transport,()=>session.csrfToken);
const status=document.querySelector('#state')!,image=document.querySelector<HTMLImageElement>('#preview')!,facts=document.querySelector('#facts')!;
const scope=createElementScope({document,registry:'auto'});scope.register([buttonDefinition]);const host=scope.createElement('div');document.querySelector('#review')!.append(host);
let current:any=null,url:string|null=null;
async function send(body:unknown){const command={schemaVersion:1,commandId:crypto.randomUUID(),clientId:session.clientId,sessionId:'isolated-consumer',correlationId:crypto.randomUUID(),causationId:null,transactionId:crypto.randomUUID(),documentId:null,expectedDocumentRevision:null,expectedEntityVersions:EMPTY_EXPECTED_VERSIONS,issuedAt:new Date().toISOString(),body};
 let r=await transport('/api/v1/commands',{method:'POST',headers:{'Content-Type':'application/json','X-App-CSRF':session.csrfToken},body:JSON.stringify({protocolVersion:1,command})}),value=await r.json();
 for(let n=0;value.kind==='pending'&&n<1000;n++){await new Promise(resolve=>setTimeout(resolve,10));r=await transport(value.receiptUrl);value=await r.json();}
 if(value.receipt?.status!=='accepted')throw Error(JSON.stringify(value));await recovery.recover();const page=await(await transport('/api/v1/events?after='+String(BigInt(value.receipt.fromSeq)-1n))).json();return page.batches[0].events[0];}
async function approve(){const selected=current;if(!selected)return;status.textContent='Approving retained pixels';const event=await send({type:'ApproveRaster',assetId:selected.asset.id,reviewId:selected.review.reviewId,reviewHash:selected.review.reviewHash});if(current!==selected)return;w.harness.approved=event.payload.asset;status.textContent='Canonical raster approved';render(html`<p>The accepted raster shares the exact preview pixel identity.</p>`,host,{creationScope:scope.creationScope});}
function draw(){render(html`<en-button @click=${(event:Event)=>queueMicrotask(()=>{if(!event.defaultPrevented)void approve();})}>Approve converted raster</en-button>`,host,{creationScope:scope.creationScope});}
w.harness={session,transport,cache,recovery,send,approved:null,async upload(bytes:number[],mediaType:string){const data=new Uint8Array(bytes),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',data)),b=>b.toString(16).padStart(2,'0')).join(''),id=crypto.randomUUID();let r=await transport('/api/v1/assets/staging',{method:'POST',headers:{'Content-Type':'application/json','X-App-CSRF':session.csrfToken},body:JSON.stringify({protocolVersion:1,stagingId:id,purpose:'image',expectedBytes:String(data.length),sha256:'sha256:'+hash,mediaType})});if(!r.ok)throw Error(await r.text());r=await transport('/api/v1/assets/staging/'+id,{method:'PUT',headers:{'Content-Type':'application/octet-stream','X-App-CSRF':session.csrfToken,'Upload-Offset':'0'},body:data});if(!r.ok)throw Error(await r.text());return(await send({type:'FinalizeStaging',stagingId:id,expectedSha256:'sha256:'+hash})).payload.asset;},async review(assetId:string){const event=await send({type:'PrepareRaster',assetId}),asset=event.payload.asset,reviewed=await send({type:'ReviewRaster',assetId:asset.id}),review=await(await transport('/api/v1/assets/raster-reviews/'+reviewed.payload.reviewId)).json();const response=await transport('/api/v1/assets/'+asset.id+'/content');if(!response.ok)throw Error('Preview unavailable');const blob=await response.blob();if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(blob);image.src=url;await image.decode();current={asset,review};facts.textContent=`${asset.raster.width} × ${asset.raster.height} pixels · ${review.conversion.profile} to sRGB · alpha retained · no resize`;status.textContent='Conversion ready for review';draw();return current;}};
status.textContent='Raster consumer ready';
