import {browserPhasesURL as browser} from '../owned-preview-module.mjs';
import {allocationsURL,displayPreviewURL,displaySchedulerURL} from '../display-module.mjs';
import {modelMemoryURL,exportMemoryURL} from './memory-module.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {transformWithOxc} from 'vite';
import sharp from 'sharp';

// Load the production controller and ControlAdapter. The Lit stand-in only
// retains template values so these tests can call the real rendered handlers.
const data=code=>'data:text/javascript;base64,'+Buffer.from(code).toString('base64');
const exportRoot=process.env.IE_EXPORT_SOURCE_ROOT??process.env.IE_DISPLAY_SOURCE_ROOT,sourceRoot=exportRoot?exportRoot.replace(/\/$/,'')+'/':'';
const lit=data('export const nothing=null;export function html(strings,...values){return {strings,values};}');
// The DOM-owning AsyncDirective has its own lifecycle suite. This template
// stand-in preserves only the URL value used by the actual export controller.
const displayImage=data('export const displayImage=value=>value;');
const adapter=data((await transformWithOxc(await readFile('src/ui/adapters.ts','utf8'),'adapters.ts')).code);
const options=data((await transformWithOxc(await readFile('src/state/export-options.ts','utf8'),'export-options.ts')).code);
const sha256=data((await transformWithOxc(await readFile('src/protocol/sha256.ts','utf8'),'sha256.ts')).code);
let code=(await transformWithOxc(await readFile(sourceRoot+'src/ui/export.ts','utf8'),'export.ts')).code;
for(const [name,url]of Object.entries({'../observability/model-memory.js':modelMemoryURL,'./export-memory.js':exportMemoryURL,'./display-image.js':displayImage,'../observability/display-preview.js':displayPreviewURL,'../observability/allocations.js':allocationsURL,'lit':lit,'./adapters.js':adapter,'../state/export-options.js':options,'../protocol/sha256.js':sha256,'../observability/browser.js':browser}))code=code.replaceAll(JSON.stringify(name),JSON.stringify(url)).replaceAll("'"+name+"'",JSON.stringify(url));
const {ExportControls}=await import(data(code));
const {displayPreviewInfo,displayPreviewOwnership,cancelDisplayPreviewReads,waitForDisplayPreviewReads}=await import(displayPreviewURL),{waitForDisplayReads,displayReadOwnership}=await import(displaySchedulerURL),{allocationLedger,ALLOCATION_LIMITS}=await import(allocationsURL),{EXPORT_MEMORY_LIMITS}=await import(exportMemoryURL),{modelPayloadBytes,createOwnedModel}=await import(modelMemoryURL);
// Persistent instrumentation is admitted once; every component owner must return to this exact baseline.
const diagnosticBaseline=allocationLedger.snapshot();
const owned=new Map(),liveBitmaps=new Set(),fixtureGates=new Set(),decodeCalls=[];
const savedBitmap=Object.getOwnPropertyDescriptor(globalThis,'createImageBitmap');
// Node has no native ImageBitmap. This browser-boundary double exposes the
// dimensions/close contract after the real helper validates the PNG. Fixture
// renditions are generated by decoding actual encoded exports below; this
// double is not native-browser decoder or pixel qualification.
async function decodeBitmap(blob){
 const bytes=Buffer.from(await blob.arrayBuffer()),width=bytes.readUInt32BE(16),height=bytes.readUInt32BE(20);
 const record={bytes,mediaType:blob.type,width,height,closes:0},bitmap={width,height,close(){record.closes++;liveBitmaps.delete(bitmap);}};
 decodeCalls.push(record);liveBitmaps.add(bitmap);return bitmap;
}
Object.defineProperty(globalThis,'createImageBitmap',{configurable:true,writable:true,value:decodeBitmap});
test.afterEach(async()=>{
 globalThis.createImageBitmap=decodeBitmap;
 try{for(const release of fixtureGates)release();fixtureGates.clear();for(const [controller,restore]of owned){restore();await controller.releaseAndWait();}owned.clear();cancelDisplayPreviewReads();await waitForDisplayPreviewReads();await waitForDisplayReads();assert.equal(liveBitmaps.size,0);assert.equal(allocationLedger.snapshot().activeRecords,diagnosticBaseline.activeRecords);assert.deepEqual(displayPreviewOwnership(),{activeReads:0,previewURLs:0,imageConsumers:0,failedNativeOwners:0,cleanupFailures:0});}
 finally{decodeCalls.length=0;}
});
test.after(()=>{if(savedBitmap)Object.defineProperty(globalThis,'createImageBitmap',savedBitmap);else delete globalThis.createImageBitmap;});
const flush=async()=>{for(let i=0;i<16;i++)await Promise.resolve();};
const settle=async()=>{await new Promise(resolve=>setTimeout(resolve,5));await flush();};
function deferred(){let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};}
function find(template,part){
 if(!template||typeof template!=='object')return;
 if(template.strings){const i=template.strings.findIndex(s=>s.includes(part));if(i>=0)return {strings:template.strings.slice(i),values:template.values.slice(i)};}
 for(const value of Array.isArray(template)?template:template.values??[]){const found=find(value,part);if(found)return found;}
}
function text(template){
 if(template===null||template===undefined||typeof template==='function')return '';
 if(Array.isArray(template))return template.map(text).join('');
 if(template.strings)return template.strings.map((s,i)=>s+text(template.values[i])).join('');
 return String(template);
}
function event(value){const host={isConnected:true,...(value===undefined?{}:{value})};return {currentTarget:host,composedPath:()=>[host],defaultPrevented:false};}
function handler(template,id,attribute){
 const found=find(template,'id="'+id+'"');assert(found,'Rendered #'+id);
 const index=found.strings.findIndex(string=>string.includes(attribute+'='));assert(index>=0,'Rendered '+attribute+' on #'+id);
 assert.equal(typeof found.values[index],'function');return found.values[index];
}
function attribute(template,id,name){
 const found=find(template,'id="'+id+'"');assert(found,'Rendered #'+id);
 const index=found.strings.findIndex(string=>string.includes(name+'='));assert(index>=0,'Rendered '+name+' on #'+id);return found.values[index];
}
const hash=bytes=>'sha256:'+createHash('sha256').update(bytes).digest('hex');
function originalPixels(width,height){const bytes=Buffer.alloc(width*height*4);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const at=(y*width+x)*4;bytes[at]=(x*47+y*13)%256;bytes[at+1]=(x*11+y*71)%256;bytes[at+2]=(x*29+y*19)%256;bytes[at+3]=255;}return bytes;}
async function artifact(format,width,height,quality=90){
 const pixels=originalPixels(width,height),source=sharp(pixels,{raw:{width,height,channels:4}});
 const encoded=await(format==='jpeg'?source.jpeg({quality,chromaSubsampling:'4:4:4'}):source.png({compressionLevel:9})).toBuffer(),scale=Math.min(1,1024/Math.max(width,height)),previewWidth=Math.ceil(width*scale),previewHeight=Math.ceil(height*scale);
 // Decode the retained encoded bytes before generating the response: JPEG's
 // lossy encoded appearance, rather than its pre-encoder pixels, is the basis.
 // This controlled response fixture does not qualify the server's CP1 resize.
 const rendition=await sharp(encoded).resize(previewWidth,previewHeight,{kernel:'nearest'}).ensureAlpha().png({compressionLevel:6}).toBuffer();
 return {encoded,rendition,previewWidth,previewHeight,pixelIdentity:hash(pixels)};
}
const original=await artifact('png',8,6),encoded=original.encoded,imageHash=hash(encoded);
function fixture(){
 const responseOwners=[];const ownResponse=(value,kind)=>{const payload=createOwnedModel('export-test-response',modelPayloadBytes(value),()=>structuredClone(value)),record={kind,released:false,value:payload.value};responseOwners.push(record);return {value:payload.value,pin:()=>payload.pin(),release(){assert.equal(record.released,false,'Exact response released once');record.released=true;payload.release();}};};
 let instance,rendered,identity='client',bytes=original;const prepared=[],confirmed=[],reads=[],commands=[],cancellations=[];
 const document={id:'document',revision:'4',historyHead:'history-4',width:8,height:6,name:'Frozen document'},prior={path:'/prior/content',name:'previous.png',status:'ready'};
 const asset={id:'encoded-asset',availability:'available',safety:'safe',blob:{hash:imageHash,byteLength:String(encoded.byteLength),mediaType:'image/png'},raster:{role:'export',width:8,height:6,pixelIdentity:original.pixelIdentity}};
 const response=()=>new Response(bytes.rendition,{headers:{etag:'"'+hash(bytes.rendition)+'"','content-length':String(bytes.rendition.byteLength),'content-type':'image/png','x-display-profile':'cp1-display-v1','x-display-source':asset.blob.hash,'x-display-basis':'encoded','x-display-width':String(bytes.previewWidth),'x-display-height':String(bytes.previewHeight),'x-display-source-width':String(asset.raster.width),'x-display-source-height':String(asset.raster.height),'x-display-lod':'0'}});
 const editor={async ownedPrepareExport(...args){return ownResponse(await this.prepareExport(...args),'asset');},async ownedCancelExport(...args){return ownResponse(await this.cancelExport(...args),'cancel');},view:{ready:true,busy:false,document,image:{layers:[{id:'visible-layer',visible:true},{id:'hidden-layer',visible:false}]},selected:['visible-layer'],download:prior},documentEpoch:1,sessionId:'session',session:{identity:()=>identity,async transport(path,init){reads.push({path,init});return response();}},draftOwner:{drafts:new Map()},async prepareExport(options,document,onJournaled){prepared.push({options:structuredClone(options),document:structuredClone(document)});onJournaled?.('export-command-'+prepared.length);return asset;},async cancelExport(commandId,owner){cancellations.push({commandId,owner});return {protocolVersion:1,commandId,status:'canceled',receipt:{status:'rejected',code:'INVALID_INPUT'}};},confirmExport(asset,document){confirmed.push({asset,document});this.view.download={asset,document};},async command(...args){commands.push(args);throw Error('Unexpected command from export controls');}};
 const host={requestUpdate(){this.updateComplete=Promise.resolve().then(()=>rendered=instance.render());},updateComplete:Promise.resolve()};
 instance=new ExportControls(host,editor);const cancelExport=editor.cancelExport;owned.set(instance,()=>{editor.cancelExport=cancelExport;});
 const callback=(id,type='@click')=>handler(rendered,id,type);
 return {responseOwners,instance,host,editor,document,asset,prior,prepared,confirmed,reads,commands,cancellations,response,identity(value){identity=value;},template:()=>rendered,text:()=>text(rendered),callback,
  encoded:()=>bytes.encoded,rendition:()=>bytes.rendition,
  async setArtifact(format,width,height,quality=90){bytes=await artifact(format,width,height,quality);Object.assign(asset.blob,{hash:hash(bytes.encoded),byteLength:String(bytes.encoded.length),mediaType:format==='jpeg'?'image/jpeg':'image/png'});Object.assign(asset.raster,{width,height,pixelIdentity:bytes.pixelIdentity});},
  async initial(){instance.begin();await flush();},
  async change(id,value){callback('export-'+id,'@en-change')(event(value));await flush();},
  async prepare(){callback('prepare-export')(event());await settle();},
  load(overrides={}){const url=attribute(rendered,'export-preview','src'),info=displayPreviewInfo(url);assert(info,'The production display helper owns the loaded URL');callback('export-preview','@load')({currentTarget:{src:url,naturalWidth:info.width,naturalHeight:info.height,isConnected:true,...overrides}});},
  async ready(){
   await this.prepare();
   // Blob streaming may finish on a later event-loop turn. Observe the actual
   // rendered result rather than assuming a fixed sleep completes preparation.
   const deadline=performance.now()+2000;
   while(!find(rendered,'id="export-review"')&&!find(rendered,'role="alert"')&&performance.now()<deadline)await new Promise(resolve=>setImmediate(resolve));
   assert(find(rendered,'id="export-review"'),'Encoded preview: '+text(rendered));this.load();await flush();
  },
  composition(){const section=find(rendered,'class="export-controls"');return ['@compositionstart','@compositionend'].map(name=>section.values[section.strings.findIndex(string=>string.includes(name+'='))]);}
 };
}
function replaceOwner(f,boundary){
 if(boundary==='document')f.editor.view.document={...f.document,id:'replacement-document'};
 if(boundary==='document epoch')f.editor.documentEpoch++;
 if(boundary==='session')f.editor.sessionId='replacement-session';
 if(boundary==='identity')f.identity('replacement-client');
 if(boundary==='connection')f.editor.session={...f.editor.session};
 if(boundary==='draft owner')f.editor.draftOwner={drafts:new Map()};
 if(boundary==='disposal')f.instance.dispose();
 if(boundary==='readiness')f.editor.view.ready=false;
 if(boundary==='composition')f.composition()[0]();
}

test('opening, changing settings and preparing do not replace a prior download or mutate the document',async()=>{
 const f=fixture(),before=structuredClone(f.document);await f.initial();assert.deepEqual(f.prepared,[]);assert.deepEqual(f.commands,[]);
 await f.ready();assert.equal(f.editor.view.download,f.prior);assert.deepEqual(f.document,before);assert.deepEqual(f.commands,[]);assert.deepEqual(f.confirmed,[]);
 assert.deepEqual(f.prepared,[{document:before,options:{scope:{kind:'visible-document'},format:'png',resize:null,matte:null,quality:null}}]);
 assert.equal(f.reads.length,1);assert.equal(f.reads[0].path,'/api/v1/assets/encoded-asset/display?identity='+encodeURIComponent(f.asset.blob.hash)+'&basis=encoded&edge=1024');assert(f.reads[0].init.signal instanceof AbortSignal);assert(!f.reads.some(read=>read.path.endsWith('/content')));
});
test('confirmed export exposes the exact reviewed asset and frozen revision once without encoding again',async()=>{
 const f=fixture();await f.initial();await f.ready();const callback=f.callback('confirm-export');callback(event());callback(event());await settle();callback(event());await settle();
 assert.equal(f.confirmed.length,1);assert.deepEqual(f.confirmed[0],{asset:f.asset,document:f.document});assert.equal(f.prepared.length,1);assert.equal(f.reads.length,1);assert.deepEqual(f.commands,[]);
 assert.match(f.text(),/download request alone does not confirm a destination write/);
});
test('confirmation is refused before the exact encoded image has decoded',async()=>{
 const f=fixture();await f.initial();await f.prepare();assert.equal(attribute(f.template(),'confirm-export','?disabled'),true);f.callback('confirm-export')(event());await settle();assert.deepEqual(f.confirmed,[]);
 f.load();await flush();assert.equal(attribute(f.template(),'confirm-export','?disabled'),false);f.callback('confirm-export')(event());await settle();assert.equal(f.confirmed.length,1);
});
for(const [name,change]of [['wrong URL',{src:'blob:another-preview'}],['wrong width',{naturalWidth:9}],['wrong height',{naturalHeight:7}],['failed decode',{naturalWidth:0,naturalHeight:0}]])test('confirmation is refused after '+name,async()=>{
 const f=fixture();await f.initial();await f.prepare();f.load(change);await flush();f.callback('confirm-export')(event());await settle();assert.deepEqual(f.confirmed,[]);assert.equal(attribute(f.template(),'confirm-export','?disabled'),true);
});
test('a decode error revokes a previously loaded preview approval',async()=>{
 const f=fixture();await f.initial();await f.ready();f.callback('export-preview','@error')();await flush();f.callback('confirm-export')(event());await settle();assert.deepEqual(f.confirmed,[]);assert.match(f.text(),/could not be displayed/);
});
for(const action of ['prepare','confirm'])for(const boundary of ['document','document epoch','session','identity','connection','draft owner','disposal','readiness','composition'])for(const scheduled of [false,true])test(`${action} refuses ${boundary} ${scheduled?'after scheduling':'before invocation'}`,async()=>{
 const f=fixture();await f.initial();if(action==='confirm')await f.ready();const callback=f.callback(action+'-export'),e=event(),count=f.prepared.length;
 if(scheduled)callback(e);replaceOwner(f,boundary);if(!scheduled)callback(e);await settle();assert.equal(f.prepared.length,count);assert.deepEqual(f.confirmed,[]);assert.deepEqual(f.commands,[]);
});
for(const action of ['prepare','confirm'])for(const boundary of ['late native veto','detached host'])test(`${action} respects ${boundary}`,async()=>{
 const f=fixture();await f.initial();if(action==='confirm')await f.ready();const count=f.prepared.length,e=event();f.callback(action+'-export')(e);if(boundary==='late native veto')e.defaultPrevented=true;else e.currentTarget.isConnected=false;
 await settle();assert.equal(f.prepared.length,count);assert.deepEqual(f.confirmed,[]);
});
test('busy editor state vetoes a retained preparation or confirmation callback',async()=>{
 for(const action of ['prepare','confirm']){const f=fixture();await f.initial();if(action==='confirm')await f.ready();const count=f.prepared.length;f.editor.view.busy=true;f.callback(action+'-export')(event());await settle();assert.equal(f.prepared.length,count);assert.deepEqual(f.confirmed,[]);}
});
test('settings changed after preparation revoke the preview and its retained confirmation callback',async()=>{
 const f=fixture();await f.initial();await f.ready();const confirm=f.callback('confirm-export');await f.change('format','jpeg');confirm(event());await settle();assert.deepEqual(f.confirmed,[]);assert(!find(f.template(),'id="export-review"'));assert.equal(f.editor.view.download,f.prior);
});
for(const boundary of ['late native veto','detached host','document'])test('a form edit respects '+boundary,async()=>{
 const f=fixture();await f.initial();await f.ready();const e=event('jpeg');f.callback('export-format','@en-change')(e);if(boundary==='late native veto')e.defaultPrevented=true;else if(boundary==='detached host')e.currentTarget.isConnected=false;else replaceOwner(f,boundary);await flush();assert.equal(attribute(f.template(),'export-format','.value'),'png');assert.deepEqual(f.confirmed,[]);
});
test('changing only the current revision preserves the frozen preview and makes its revision visible',async()=>{
 const f=fixture();await f.initial();await f.ready();f.editor.view.document={...f.document,revision:'5',historyHead:'history-5'};f.instance.sync();f.host.requestUpdate();await flush();assert.match(f.text(),/still contains revision 4/);
 f.callback('confirm-export')(event());await settle();assert.equal(f.confirmed.length,1);assert.equal(f.confirmed[0].document.revision,'4');assert.equal(f.confirmed[0].document.historyHead,'history-4');assert.equal(f.prepared.length,1);
});
test('prepared metadata does not alias later mutations of the returned asset or source document',async()=>{
 const f=fixture();await f.initial();await f.ready();const expected={asset:structuredClone(f.asset),document:structuredClone(f.document)};f.asset.id='replacement-asset';f.asset.blob.hash='replacement-hash';f.document.name='Renamed later';f.document.historyHead='replacement-head';f.callback('confirm-export')(event());await settle();assert.deepEqual(f.confirmed,[expected]);
});
test('JPEG, resize and selected scope are frozen into one explicit preparation',async()=>{
 const f=fixture();await f.initial();await f.change('scope','selected-layers');f.editor.view.selected=['hidden-layer','visible-layer'];const hidden=event();hidden.currentTarget.checked=true;f.callback('export-include-hidden','@en-change')(hidden);await flush();
 await f.change('format','jpeg');await f.change('matte','#12aBcD');await f.change('quality','0.73');await f.change('dimensions','resize');await f.change('width','4');await f.change('height','3');await f.setArtifact('jpeg',4,3,73);await f.ready();
 assert.deepEqual(f.prepared[0].options,{scope:{kind:'selected-layers',layerIds:['hidden-layer','visible-layer'],includeHidden:true},format:'jpeg',resize:{width:4,height:3},matte:'#12ABCD',quality:0.73});assert.match(f.text(),/actual encoded export/);assert.match(f.text(),/Revision 4 · 4 × 3 · JPEG · [0-9]+ bytes/);assert.match(f.text(),/Opaque matte #12ABCD; quality 0.73/);
 f.editor.view.selected=['visible-layer'];f.callback('confirm-export')(event());await settle();assert.equal(f.confirmed.length,1);assert.equal(f.prepared.length,1);
});
for(const format of ['png','jpeg'])test('a bounded PNG rendition confirms the retained full-size '+format+' artifact',async()=>{
 const f=fixture();Object.assign(f.document,{width:2048,height:1024});await f.setArtifact(format,2048,1024);const originalAsset=structuredClone(f.asset),originalBytes=Buffer.from(f.encoded());await f.initial();if(format==='jpeg')await f.change('format','jpeg');await f.ready();
 const url=attribute(f.template(),'export-preview','src'),info=displayPreviewInfo(url),decoded=decodeCalls.at(-1);
 assert.deepEqual({width:info.width,height:info.height,sourceWidth:info.sourceWidth,sourceHeight:info.sourceHeight,basis:info.basis,source:info.source,mediaType:info.mediaType},{width:1024,height:512,sourceWidth:2048,sourceHeight:1024,basis:'encoded',source:originalAsset.blob.hash,mediaType:'image/png'});
 assert.equal(info.hash,hash(f.rendition()));assert.notEqual(info.hash,originalAsset.blob.hash);assert.equal(info.byteLength,String(f.rendition().byteLength));assert.equal(originalAsset.blob.byteLength,String(originalBytes.byteLength));assert.equal(decoded.mediaType,'image/png');assert.deepEqual([decoded.width,decoded.height,decoded.closes],[1024,512,1]);assert.deepEqual(decoded.bytes,f.rendition());
 assert.match(f.text(),/2048 × 1024/);assert.match(f.text(),/Scaled preview 1024 × 512/);assert.match(f.text(),new RegExp(originalAsset.blob.byteLength+' bytes'));assert.match(f.text(),/export retains its original dimensions and encoded bytes/);
 // Full artifact dimensions are deliberately incorrect for this <img> load.
 f.load({naturalWidth:2048,naturalHeight:1024});await flush();f.callback('confirm-export')(event());await settle();assert.deepEqual(f.confirmed,[]);assert.equal(attribute(f.template(),'confirm-export','?disabled'),true);
 f.load();await flush();f.callback('confirm-export')(event());await settle();assert.deepEqual(f.confirmed,[{asset:originalAsset,document:f.document}]);assert.equal(f.confirmed[0].asset.blob.hash,hash(originalBytes));assert.equal(f.confirmed[0].asset.blob.mediaType,format==='jpeg'?'image/jpeg':'image/png');assert.deepEqual(f.encoded(),originalBytes);assert.equal(f.prepared.length,1);assert.equal(f.reads.length,1);assert(!f.reads.some(read=>read.path.includes('/content')));assert.deepEqual(f.commands,[]);
});
test('JPEG rendition fixture represents its lossy encoded appearance and uses the encoded hash as source authority',async()=>{
 const f=fixture();await f.setArtifact('jpeg',8,6);await f.initial();await f.change('format','jpeg');const decodedOriginal=await sharp(f.encoded()).ensureAlpha().raw().toBuffer(),decodedRendition=await sharp(f.rendition()).ensureAlpha().raw().toBuffer();assert.notDeepEqual(decodedOriginal,originalPixels(8,6));assert.deepEqual(decodedRendition,decodedOriginal);
 await f.ready();const request=new URL(f.reads[0].path,'http://127.0.0.1'),info=displayPreviewInfo(attribute(f.template(),'export-preview','src'));assert.equal(request.searchParams.get('basis'),'encoded');assert.equal(request.searchParams.get('identity'),hash(f.encoded()));assert.notEqual(request.searchParams.get('identity'),f.asset.raster.pixelIdentity);assert.equal(info.source,hash(f.encoded()));assert.equal(info.hash,hash(f.rendition()));
});
test('a native bitmap with dimensions different from the rendition cannot publish a review',async()=>{
 const f=fixture();await f.initial();globalThis.createImageBitmap=async blob=>{const bitmap=await decodeBitmap(blob);bitmap.width++;return bitmap;};await f.prepare();const deadline=performance.now()+2000;while(!find(f.template(),'role="alert"')&&performance.now()<deadline)await new Promise(resolve=>setImmediate(resolve));assert(!find(f.template(),'id="export-review"'));assert.match(f.text(),/DISPLAY_DECODE_DIMENSIONS/);assert.equal(decodeCalls.length,1);assert.equal(decodeCalls[0].closes,1);assert.equal(displayPreviewOwnership().previewURLs,0);assert.deepEqual(f.confirmed,[]);assert.equal(f.editor.view.download,f.prior);
});
for(const [name,apply]of [
 ['empty selection',async f=>{await f.change('scope','selected-layers');f.editor.view.selected=[];}],
 ['only hidden selected layers without acknowledgment',async f=>{await f.change('scope','selected-layers');f.editor.view.selected=['hidden-layer'];}],
 ['unknown selected layer',async f=>{await f.change('scope','selected-layers');f.editor.view.selected=['unknown'];}],
 ['invalid matte',async f=>{await f.change('format','jpeg');await f.change('matte','#FFFFFF00');}],
 ['invalid quality',async f=>{await f.change('format','jpeg');await f.change('quality','0');}],
 ['oversized dimensions',async f=>{await f.change('dimensions','resize');await f.change('width','8193');}],
 ['fractional dimensions',async f=>{await f.change('dimensions','resize');await f.change('height','2.5');}],
])test('invalid '+name+' cannot prepare bytes or replace the previous download',async()=>{
 const f=fixture();await f.initial();await apply(f);await f.prepare();assert.deepEqual(f.prepared,[]);assert.deepEqual(f.reads,[]);assert.deepEqual(f.confirmed,[]);assert.equal(f.editor.view.download,f.prior);assert(find(f.template(),'role="alert"'));
});
async function pendingAt(f,stage){
 const pending=deferred();let complete,decoderEntered=false;
 if(stage==='preparation'){
  const prepare=f.editor.prepareExport;f.editor.prepareExport=async(...args)=>{await prepare(...args);return pending.promise;};complete=()=>pending.resolve(f.asset);
 }else if(stage==='authenticated read'){
  const transport=f.editor.session.transport;f.editor.session.transport=async(...args)=>{await transport(...args);return pending.promise;};complete=()=>pending.resolve(f.response());
 }else if(stage==='rendition body'){
  const transport=f.editor.session.transport;let canceled=false;
  const stream=new ReadableStream({async pull(controller){await pending.promise;if(!canceled){controller.enqueue(f.rendition());controller.close();}},async cancel(){canceled=true;await pending.promise;}});
  f.editor.session.transport=async(...args)=>{const response=await transport(...args);return new Response(stream,{headers:response.headers});};complete=()=>pending.resolve();
 }else{
  assert.equal(stage,'bitmap decode');
  // Pause only the browser decoder boundary, after real rendition descriptor,
  // SHA and PNG validation. Every late bitmap still must be closed by helper.
  globalThis.createImageBitmap=async blob=>{globalThis.createImageBitmap=decodeBitmap;const bitmap=await decodeBitmap(blob);decoderEntered=true;await pending.promise;return bitmap;};
  complete=()=>{globalThis.createImageBitmap=decodeBitmap;pending.resolve();};
 }
 const release=()=>{fixtureGates.delete(release);complete();};fixtureGates.add(release);await f.prepare();
 if(stage==='bitmap decode'){const deadline=performance.now()+2000;while(!decoderEntered&&!find(f.template(),'role="alert"')&&performance.now()<deadline)await new Promise(resolve=>setImmediate(resolve));assert(decoderEntered,'Native bitmap decoder was not reached: '+f.text());}
 return release;
}
for(const stage of ['preparation','authenticated read','rendition body','bitmap decode'])test('canceling during '+stage+' preserves the previous download and suppresses late completion',async()=>{
 const f=fixture();await f.initial();const complete=await pendingAt(f,stage);assert.equal(f.instance.inspect().preparing,true);const signal=f.reads.at(-1)?.init.signal;
 f.callback('cancel-export-preparation')(event());await settle();if(signal)assert.equal(signal.aborted,true);complete();await settle();assert.deepEqual(f.confirmed,[]);assert.equal(f.editor.view.download,f.prior);assert(!find(f.template(),'id="export-review"'));assert.deepEqual(f.instance.inspect(),{previewURLs:0,activeReads:0,retainedDocument:false,preparing:false,pendingPreparations:0,pendingCancellations:0,cleanupFailures:0});
});
for(const stage of ['preparation','authenticated read','rendition body','bitmap decode'])for(const boundary of ['document','document epoch','session','identity','connection','draft owner','readiness','disposal','composition'])test('pending '+stage+' cannot publish across '+boundary,async()=>{
 const f=fixture();await f.initial();const complete=await pendingAt(f,stage);replaceOwner(f,boundary);f.instance.sync();complete();await settle();assert.deepEqual(f.confirmed,[]);assert.equal(f.editor.view.download,f.prior);assert(!find(f.template(),'id="export-review"'));assert.equal(f.instance.inspect().previewURLs,0);assert.equal(f.instance.inspect().preparing,false);
});
test('a revision-only update during encoding still reviews the captured old document',async()=>{
 const f=fixture();await f.initial();const complete=await pendingAt(f,'preparation');f.editor.view.document={...f.document,revision:'5',width:40,height:30,historyHead:'history-5'};f.instance.sync();complete();await settle();f.load();await flush();assert.match(f.text(),/still contains revision 4/);f.callback('confirm-export')(event());await settle();assert.equal(f.confirmed[0].document.width,8);assert.equal(f.confirmed[0].document.height,6);assert.equal(f.confirmed[0].document.historyHead,'history-4');
});
test('old preparation cannot replace a new preview after cancel and retry',async()=>{
 const f=fixture();await f.initial();const prepare=f.editor.prepareExport,complete=await pendingAt(f,'preparation');f.instance.cancel();await settle();f.editor.prepareExport=prepare;await f.ready();const url=attribute(f.template(),'export-preview','src');complete();await settle();assert.equal(attribute(f.template(),'export-preview','src'),url);assert.equal(f.prepared.length,2);f.callback('confirm-export')(event());await settle();assert.equal(f.confirmed.length,1);
});
test('a retained cancel callback from an earlier preparation cannot cancel its replacement',async()=>{
 const f=fixture();await f.initial();const prepare=f.editor.prepareExport,first=await pendingAt(f,'preparation'),oldCancel=f.callback('cancel-export-preparation');f.instance.cancel();await settle();f.editor.prepareExport=prepare;const second=await pendingAt(f,'preparation');oldCancel(event());await settle();assert.equal(f.instance.inspect().preparing,true);second();await settle();assert(find(f.template(),'id="export-review"'));first();await settle();assert(find(f.template(),'id="export-review"'));assert.deepEqual(f.confirmed,[]);
});
for(const boundary of ['late native veto','detached host'])test('cancel respects '+boundary,async()=>{
 const f=fixture();await f.initial();const complete=await pendingAt(f,'preparation'),e=event();f.callback('cancel-export-preparation')(e);if(boundary==='late native veto')e.defaultPrevented=true;else e.currentTarget.isConnected=false;await settle();assert.equal(f.instance.inspect().preparing,true);complete();await settle();assert(find(f.template(),'id="export-review"'));
});
test('old preparation cannot return after leaving and reopening the same document',async()=>{
 const f=fixture();await f.initial();const prepare=f.editor.prepareExport,complete=await pendingAt(f,'preparation');f.editor.view.document={...f.document,id:'other'};f.instance.sync();f.editor.view.document=f.document;f.instance.begin();await flush();f.editor.prepareExport=prepare;await f.ready();const url=attribute(f.template(),'export-preview','src');complete();await settle();assert.equal(attribute(f.template(),'export-preview','src'),url);f.callback('confirm-export')(event());await settle();assert.equal(f.confirmed.length,1);
});
test('canceled and released previews cannot be confirmed through retained callbacks',async()=>{
 for(const release of ['cancel','releaseDocument','dispose']){const f=fixture();await f.initial();await f.ready();const confirm=f.callback('confirm-export'),load=f.callback('export-preview','@load');f.instance[release]();load({currentTarget:{src:'old',naturalWidth:8,naturalHeight:6}});confirm(event());await settle();assert.deepEqual(f.confirmed,[]);assert.equal(f.editor.view.download,f.prior);assert.equal(f.instance.inspect().previewURLs,0);}
});
for(const [name,change]of [
 ['asset media type',f=>{f.asset.blob.mediaType='image/jpeg';}],
 ['asset dimensions',f=>{f.asset.raster.width=9;}],
 ['asset role',f=>{f.asset.raster.role='source';}],
 ['asset safety',f=>{f.asset.safety='quarantined';}],
 ['asset availability',f=>{f.asset.availability='missing';}],
 ['HTTP status',f=>{f.editor.session.transport=async()=>new Response('missing',{status:404});}],
 ['ETag',f=>{f.editor.session.transport=async()=>{const response=f.response();response.headers.set('etag','"wrong"');return response;};}],
 ['content length',f=>{f.editor.session.transport=async()=>{const response=f.response();response.headers.set('content-length','1');return response;};}],
 ['content type',f=>{f.editor.session.transport=async()=>{const response=f.response();response.headers.set('content-type','text/plain');return response;};}],
 ['truncated body',f=>{f.editor.session.transport=async()=>new Response(f.rendition().subarray(1),{headers:f.response().headers});}],
 ['content digest',f=>{f.editor.session.transport=async()=>new Response(Buffer.alloc(f.rendition().length,0),{headers:f.response().headers});}],
 ...Object.entries({'x-display-profile':'untrusted-profile','x-display-source':'sha256:'+'f'.repeat(64),'x-display-basis':'pixels','x-display-width':'7','x-display-height':'5','x-display-source-width':'9','x-display-source-height':'7','x-display-lod':'1'}).map(([header,value])=>[header,f=>{f.editor.session.transport=async()=>{const response=f.response();response.headers.set(header,value);return response;};}]),
 ['PNG signature',f=>{f.editor.session.transport=async()=>{const bytes=Buffer.from(f.rendition());bytes[0]=0;const headers=f.response().headers;headers.set('etag','"'+hash(bytes)+'"');return new Response(bytes,{headers});};}],
 ['PNG dimensions',f=>{f.editor.session.transport=async()=>{const bytes=Buffer.from(f.rendition());bytes.writeUInt32BE(9,16);const headers=f.response().headers;headers.set('etag','"'+hash(bytes)+'"');return new Response(bytes,{headers});};}],
])test('untrusted preview '+name+' cannot become confirmable',async()=>{
 const f=fixture();await f.initial();change(f);await f.prepare();assert(!find(f.template(),'id="export-review"'));assert.deepEqual(f.confirmed,[]);assert.equal(f.editor.view.download,f.prior);assert(find(f.template(),'role="alert"'));assert.equal(f.instance.inspect().preparing,false);assert.equal(decodeCalls.length,0,'Untrusted descriptors/bytes must be rejected before the decoder');
});
test('a failed preparation is visible, retains the old download and does not retry automatically',async()=>{
 const f=fixture();await f.initial();let calls=0;f.editor.prepareExport=async()=>{calls++;throw Error('Local export encoder failed');};await f.prepare();await settle();assert.equal(calls,1);assert.match(f.text(),/Local export encoder failed/);assert.equal(f.editor.view.download,f.prior);assert(!find(f.template(),'id="export-review"'));
});
test('an old failed preparation cannot overwrite a newer owner preview',async()=>{
 const f=fixture();await f.initial();const prepare=f.editor.prepareExport,pending=deferred();f.editor.prepareExport=()=>pending.promise;await f.prepare();replaceOwner(f,'draft owner');f.instance.sync();f.instance.begin();await flush();f.editor.prepareExport=prepare;await f.ready();const url=attribute(f.template(),'export-preview','src');pending.reject(Error('Old export failed'));await settle();assert.equal(attribute(f.template(),'export-preview','src'),url);assert(!f.text().includes('Old export failed'));
});
test('composition ending before action settlement cannot resurrect the discarded preview',async()=>{
 const f=fixture();await f.initial();await f.ready();f.callback('confirm-export')(event());const [start,end]=f.composition();start();end();await settle();assert.deepEqual(f.confirmed,[]);assert(!find(f.template(),'id="export-review"'));await f.ready();f.callback('confirm-export')(event());await settle();assert.equal(f.confirmed.length,1);
});
test('canceling a subsequent export does not discard an already confirmed download',async()=>{
 const f=fixture();await f.initial();await f.ready();f.callback('confirm-export')(event());await settle();const download=f.editor.view.download;f.instance.begin();await flush();await f.ready();f.instance.cancel();await flush();assert.equal(f.editor.view.download,download);assert.equal(f.confirmed.length,1);
});
test('canceling an encoder remains pending until the worker drain receipt is confirmed',async()=>{
 const f=fixture(),reply=deferred();await f.initial();const complete=await pendingAt(f,'preparation'),cancel=f.editor.cancelExport;f.editor.cancelExport=async(...args)=>{await cancel(...args);return reply.promise;};
 f.callback('cancel-export-preparation')(event());await settle();assert.equal(f.cancellations.length,1);assert.equal(f.cancellations[0].commandId,'export-command-1');assert.equal(f.cancellations[0].owner.session,f.editor.session);assert.equal(f.cancellations[0].owner.identity,'client');assert.equal(f.instance.inspect().preparing,true);assert.match(f.text(),/Cancellation requested/);assert(!f.text().includes('Export canceled.'));
 assert.equal(attribute(f.template(),'prepare-export','?disabled'),true);f.callback('prepare-export')(event());f.callback('cancel-export-preparation')(event());await settle();assert.equal(f.prepared.length,1);assert.equal(f.cancellations.length,1);
 reply.resolve({protocolVersion:1,commandId:'export-command-1',status:'canceled',receipt:{status:'rejected',code:'INVALID_INPUT'}});await settle();assert.equal(f.instance.inspect().pendingPreparations,1);assert.equal(f.instance.inspect().pendingCancellations,0);assert.equal(f.instance.inspect().retainedDocument,true);assert.match(f.text(),/local worker has stopped/);assert.equal(f.editor.view.download,f.prior);complete();await settle();assert.equal(f.instance.inspect().preparing,false);assert(!find(f.template(),'id="export-review"'));assert.deepEqual(f.confirmed,[]);
});
test('cancel requested before journaling waits for the original command identity',async()=>{
 const f=fixture(),pending=deferred(),reply=deferred();let journaled;await f.initial();f.editor.prepareExport=async(options,document,onJournaled)=>{f.prepared.push({options,document});journaled=onJournaled;return pending.promise;};const cancel=f.editor.cancelExport;f.editor.cancelExport=async(...args)=>{await cancel(...args);return reply.promise;};await f.prepare();f.instance.cancel();await settle();assert.deepEqual(f.cancellations,[]);assert.equal(f.instance.inspect().preparing,true);assert.match(f.text(),/Cancellation requested/);
 journaled('original-journaled-command');await settle();assert.deepEqual(f.cancellations.map(item=>item.commandId),['original-journaled-command']);reply.resolve({protocolVersion:1,commandId:'original-journaled-command',status:'canceled',receipt:{status:'rejected',code:'INVALID_INPUT'}});await settle();pending.reject(Error('INVALID_INPUT EXPORT_CANCELED'));await settle();assert.match(f.text(),/local worker has stopped/);assert.equal(f.instance.inspect().preparing,false);assert.equal(f.editor.view.download,f.prior);
});
test('a completed receipt during cancellation reports preserved bytes without publishing a download',async()=>{
 const f=fixture();await f.initial();const complete=await pendingAt(f,'preparation'),cancel=f.editor.cancelExport;f.editor.cancelExport=async(...args)=>{await cancel(...args);return {protocolVersion:1,commandId:args[0],status:'completed',receipt:{status:'accepted'}};};f.instance.cancel();await settle();assert.match(f.text(),/Export finished before cancellation/);assert.match(f.text(),/exact encoded bytes remain saved locally/);assert.equal(f.editor.view.download,f.prior);assert.equal(f.instance.inspect().pendingPreparations,1);complete();await settle();assert.equal(f.instance.inspect().preparing,false);assert(!find(f.template(),'id="export-review"'));assert.deepEqual(f.confirmed,[]);
});
test('a rejected original receipt during cancellation does not claim encoded bytes exist',async()=>{
 const f=fixture();await f.initial();const complete=await pendingAt(f,'preparation'),cancel=f.editor.cancelExport;f.editor.cancelExport=async(...args)=>{await cancel(...args);return {protocolVersion:1,commandId:args[0],status:'completed',receipt:{status:'rejected',code:'STORAGE_FULL'}};};f.instance.cancel();await settle();assert.match(f.text(),/original export failed/);assert.match(f.text(),/STORAGE_FULL/);assert(!f.text().includes('exact encoded bytes remain'));assert.equal(f.editor.view.download,f.prior);assert.equal(f.instance.inspect().pendingPreparations,1);complete();await settle();assert.equal(f.instance.inspect().preparing,false);assert(!find(f.template(),'id="export-review"'));
});
test('an uncertain cancellation requires explicit same-command retry and blocks new preparation',async()=>{
 const f=fixture();await f.initial();const complete=await pendingAt(f,'preparation'),cancel=f.editor.cancelExport;f.editor.cancelExport=async(...args)=>{await cancel(...args);throw Error('Local response lost');};f.instance.cancel();await settle();assert.match(f.text(),/Cancellation is unconfirmed/);assert.match(f.text(),/original export may still complete/);assert.equal(f.instance.inspect().preparing,true);assert.equal(f.cancellations.length,1);await settle();assert.equal(f.cancellations.length,1);assert.equal(attribute(f.template(),'cancel-export-preparation','?disabled'),false);
 f.callback('prepare-export')(event());await settle();assert.equal(f.prepared.length,1);f.editor.cancelExport=cancel;f.callback('cancel-export-preparation')(event());await settle();assert.deepEqual(f.cancellations.map(item=>item.commandId),['export-command-1','export-command-1']);assert.match(f.text(),/local worker has stopped/);complete();await settle();assert.equal(f.editor.view.download,f.prior);
});
test('original delivery rejection after an uncertain cancel does not automatically resend cancellation',async()=>{
 const f=fixture(),pending=deferred();await f.initial();const prepare=f.editor.prepareExport,cancel=f.editor.cancelExport;f.editor.prepareExport=async(...args)=>{await prepare(...args);return pending.promise;};f.editor.cancelExport=async(...args)=>{await cancel(...args);throw Error('Cancellation response lost');};await f.prepare();f.instance.cancel();await settle();pending.reject(Error('Original delivery response lost'));await settle();assert.equal(f.cancellations.length,1);assert.match(f.text(),/Cancellation is unconfirmed/);assert.equal(f.instance.inspect().preparing,true);
});
test('an accepted export arriving during uncertain cancellation resolves to retained bytes',async()=>{
 const f=fixture();await f.initial();const complete=await pendingAt(f,'preparation'),cancel=f.editor.cancelExport;f.editor.cancelExport=async(...args)=>{await cancel(...args);throw Error('Cancellation response lost');};f.instance.cancel();await settle();assert.match(f.text(),/Cancellation is unconfirmed/);complete();await settle();assert.match(f.text(),/Export finished before cancellation/);assert.equal(f.instance.inspect().preparing,false);assert(!find(f.template(),'id="export-review"'));assert.equal(f.editor.view.download,f.prior);assert.equal(f.cancellations.length,1);
});
for(const boundary of ['document','connection','identity','draft owner','disposal'])test('owner release at '+boundary+' does not wait for cancellation or transfer its authority',async()=>{
 const f=fixture(),reply=deferred();await f.initial();const complete=await pendingAt(f,'preparation'),session=f.editor.session,cancel=f.editor.cancelExport;f.editor.cancelExport=async(...args)=>{await cancel(...args);return reply.promise;};replaceOwner(f,boundary);f.instance.sync();await settle();assert.equal(f.instance.inspect().pendingPreparations,1);assert.equal(f.instance.inspect().pendingCancellations,1);assert.equal(f.instance.inspect().retainedDocument,true);assert.equal(f.instance.inspect().previewURLs,0);assert.equal(f.cancellations.length,1);assert.equal(f.cancellations[0].owner.session,session);assert.equal(f.cancellations[0].owner.identity,'client');
 f.editor.view.ready=true;if(boundary!=='disposal'){f.instance.begin();await flush();}const before=f.text();reply.resolve({protocolVersion:1,commandId:'export-command-1',status:'canceled',receipt:{status:'rejected',code:'INVALID_INPUT'}});await settle();assert.equal(f.text(),before);complete();await settle();assert.equal(f.text(),before);assert.equal(f.editor.view.download,f.prior);
});
test('owner release before journaling still requests cancellation with the captured authority',async()=>{
 const f=fixture(),pending=deferred();let journaled;await f.initial();f.editor.prepareExport=async(options,document,onJournaled)=>{journaled=onJournaled;return pending.promise;};await f.prepare();const session=f.editor.session;f.instance.releaseDocument();await flush();assert.equal(f.instance.inspect().pendingPreparations,1);journaled('late-journaled-command');await settle();assert.equal(f.cancellations.length,1);assert.equal(f.cancellations[0].owner.session,session);assert.equal(f.cancellations[0].owner.identity,'client');pending.reject(Error('EXPORT_CANCELED'));await settle();assert.equal(f.instance.inspect().preparing,false);assert.equal(f.editor.view.download,f.prior);
});
test('closing an encoded preview does not send a redundant backend cancellation request',async()=>{
 for(const stage of ['authenticated read','rendition body','bitmap decode']){const f=fixture();await f.initial();const complete=await pendingAt(f,stage);f.instance.cancel();await settle();assert.deepEqual(f.cancellations,[]);assert.match(f.text(),/Encoding already completed/);complete();await settle();assert.equal(f.editor.view.download,f.prior);assert(!find(f.template(),'id="export-review"'));}
});
for(const first of ['preparation','cancellation'])test('awaited release waits for both closures when '+first+' settles first',async()=>{
 const f=fixture(),reply=deferred();await f.initial();const complete=await pendingAt(f,'preparation'),cancel=f.editor.cancelExport;f.editor.cancelExport=async(...args)=>{await cancel(...args);return reply.promise;};let settled=false;const release=f.instance.releaseAndWait().then(()=>{settled=true;});await settle();
 assert.equal(f.instance.inspect().previewURLs,0);assert.equal(f.instance.inspect().pendingPreparations,1);assert.equal(f.instance.inspect().pendingCancellations,1);assert.equal(f.instance.inspect().retainedDocument,true);assert.equal(settled,false);
 if(first==='preparation')complete();else reply.resolve({protocolVersion:1,commandId:'export-command-1',status:'canceled',receipt:{status:'rejected',code:'INVALID_INPUT'}});await settle();assert.equal(settled,false);
 assert.equal(f.instance.inspect().pendingPreparations,first==='preparation'?0:1);assert.equal(f.instance.inspect().pendingCancellations,first==='cancellation'?0:1);
 if(first==='preparation')reply.resolve({protocolVersion:1,commandId:'export-command-1',status:'completed',receipt:{status:'accepted'}});else complete();await release;
 assert.equal(settled,true);assert.deepEqual(f.instance.inspect(),{previewURLs:0,activeReads:0,retainedDocument:false,preparing:false,pendingPreparations:0,pendingCancellations:0,cleanupFailures:0});assert.equal(f.editor.view.download,f.prior);
});
test('awaited release tracks preparation before the journal callback exists',async()=>{
 const f=fixture(),pending=deferred();let journaled;await f.initial();f.editor.prepareExport=async(options,document,callback)=>{journaled=callback;return pending.promise;};await f.prepare();let released=false;const release=f.instance.releaseAndWait().then(()=>{released=true;});await settle();assert.equal(released,false);assert.equal(f.instance.inspect().pendingPreparations,1);assert.equal(f.instance.inspect().pendingCancellations,1);assert.deepEqual(f.cancellations,[]);
 journaled('journal-after-close');await settle();assert.equal(released,false);assert.equal(f.instance.inspect().pendingCancellations,0);assert.equal(f.instance.inspect().pendingPreparations,1);pending.reject(Error('INVALID_INPUT EXPORT_CANCELED'));await release;assert.equal(released,true);assert.equal(f.instance.inspect().retainedDocument,false);
});
test('a failed journal write settles release without inventing a server cancellation',async()=>{
 const f=fixture(),pending=deferred();await f.initial();f.editor.prepareExport=()=>pending.promise;await f.prepare();const release=f.instance.releaseAndWait();pending.reject(Error('Browser journal unavailable'));await release;assert.deepEqual(f.cancellations,[]);assert.equal(f.instance.inspect().pendingPreparations,0);assert.equal(f.instance.inspect().cleanupFailures,0);
});
test('uncertain cancellation rejects close while retaining the pending original closure',async()=>{
 const f=fixture();await f.initial();const complete=await pendingAt(f,'preparation'),cancel=f.editor.cancelExport;f.editor.cancelExport=async(...args)=>{await cancel(...args);throw Error('Cancellation response lost');};await assert.rejects(f.instance.releaseAndWait(),/EXPORT_RELEASE_UNCONFIRMED.*Cancellation response lost/);assert.equal(f.instance.inspect().pendingPreparations,1);assert.equal(f.instance.inspect().retainedDocument,true);assert.equal(f.instance.inspect().cleanupFailures,1);
 complete();await settle();assert.equal(f.instance.inspect().pendingPreparations,0);assert.equal(f.instance.inspect().cleanupFailures,0);await f.instance.releaseAndWait();assert.equal(f.editor.view.download,f.prior);assert.deepEqual(f.confirmed,[]);
});
test('session loss fails release and preserves a minimal same-command cleanup failure until explicit retry',async()=>{
 const f=fixture(),pending=deferred(),reply=deferred();await f.initial();const prepare=f.editor.prepareExport,cancel=f.editor.cancelExport;f.editor.prepareExport=async(...args)=>{await prepare(...args);return pending.promise;};f.editor.cancelExport=async(...args)=>{await cancel(...args);return reply.promise;};await f.prepare();const rejected=assert.rejects(f.instance.releaseAndWait(),/EXPORT_RELEASE_UNCONFIRMED.*OWNER_CHANGED/);await settle();f.identity('replacement-client');f.instance.sync();await rejected;assert.equal(f.instance.inspect().pendingPreparations,1);assert.equal(f.instance.inspect().pendingCancellations,1);assert.equal(f.instance.inspect().cleanupFailures,1);
 reply.reject(Error('EXPORT_CANCELLATION_OWNER_CHANGED'));pending.reject(Error('Original session ended'));await settle();assert.equal(f.instance.inspect().retainedDocument,false);assert.equal(f.instance.inspect().pendingPreparations,0);assert.equal(f.instance.inspect().pendingCancellations,0);assert.equal(f.instance.inspect().cleanupFailures,1);
 f.identity('client');f.editor.cancelExport=cancel;await f.instance.releaseAndWait();assert.deepEqual(f.cancellations.map(row=>row.commandId),['export-command-1','export-command-1']);assert.equal(f.instance.inspect().cleanupFailures,0);assert.equal(f.editor.view.download,f.prior);
});
test('a late committed export after session loss clears settled cleanup without exposing a download in the new owner',async()=>{
 const f=fixture(),reply=deferred();await f.initial();const complete=await pendingAt(f,'preparation'),cancel=f.editor.cancelExport;f.editor.cancelExport=async(...args)=>{await cancel(...args);return reply.promise;};const rejected=assert.rejects(f.instance.releaseAndWait(),/EXPORT_RELEASE_UNCONFIRMED.*OWNER_CHANGED/);await settle();f.identity('replacement-client');f.instance.sync();await rejected;reply.reject(Error('EXPORT_CANCELLATION_OWNER_CHANGED'));await settle();complete();await settle();assert.equal(f.instance.inspect().pendingPreparations,0);assert.equal(f.instance.inspect().cleanupFailures,0);assert.equal(f.editor.view.download,f.prior);assert.deepEqual(f.confirmed,[]);
});
test('dispose starts handled cleanup while preserving unsettled counts',async()=>{
 const f=fixture();await f.initial();const complete=await pendingAt(f,'preparation'),cancel=f.editor.cancelExport;f.editor.cancelExport=async(...args)=>{await cancel(...args);throw Error('Writer disconnected');};f.instance.dispose();await settle();assert.equal(f.instance.inspect().pendingPreparations,1);assert.equal(f.instance.inspect().cleanupFailures,1);assert.equal(f.instance.inspect().retainedDocument,true);complete();await settle();assert.equal(f.instance.inspect().pendingPreparations,0);assert.equal(f.instance.inspect().cleanupFailures,0);
});
test('a bounded release timeout reports incomplete cleanup rather than zero retained work',async()=>{
 const f=fixture();await f.initial();const complete=await pendingAt(f,'preparation');await assert.rejects(f.instance.releaseAndWait(20),/EXPORT_RELEASE_UNCONFIRMED.*not settled/);assert.equal(f.instance.inspect().pendingPreparations,1);assert.equal(f.instance.inspect().retainedDocument,true);assert.equal(f.instance.inspect().cleanupFailures,1);complete();await settle();assert.equal(f.instance.inspect().pendingPreparations,0);assert.equal(f.instance.inspect().cleanupFailures,0);await f.instance.releaseAndWait();
});
test('awaited release works inside the editor busy guard without another UI action',async()=>{
 const f=fixture();await f.initial();const complete=await pendingAt(f,'preparation');f.editor.view.busy=true;const release=f.instance.releaseAndWait();await settle();assert.equal(f.cancellations.length,1);complete();await release;assert.equal(f.instance.inspect().pendingPreparations,0);assert.equal(f.instance.inspect().pendingCancellations,0);assert.equal(f.editor.view.download,f.prior);
});
test('awaited release of an encoded preview frees the URL without a cancel command',async()=>{
 const f=fixture();await f.initial();await f.ready();await f.instance.releaseAndWait();assert.equal(f.instance.inspect().previewURLs,0);assert.equal(f.instance.inspect().retainedDocument,false);assert.deepEqual(f.cancellations,[]);assert.equal(f.editor.view.download,f.prior);
});
test('awaited release still counts an aborted preview read until its original closure settles',async()=>{
 const f=fixture();await f.initial();const complete=await pendingAt(f,'rendition body');let released=false;const release=f.instance.releaseAndWait().then(()=>{released=true;});await settle();assert.equal(released,false);assert.equal(f.instance.inspect().activeReads,0);assert.equal(f.instance.inspect().pendingPreparations,1);assert.equal(f.instance.inspect().retainedDocument,true);assert.deepEqual(f.cancellations,[]);complete();await release;assert.equal(f.instance.inspect().pendingPreparations,0);assert.equal(f.instance.inspect().retainedDocument,false);
});
test('awaited release keeps decoder ownership until a late bitmap is closed',async()=>{
 const f=fixture();await f.initial();const complete=await pendingAt(f,'bitmap decode'),decoded=decodeCalls.at(-1);let released=false;const release=f.instance.releaseAndWait().then(()=>{released=true;});await settle();
 assert.equal(released,false);assert.equal(f.instance.inspect().pendingPreparations,1);assert.equal(f.instance.inspect().retainedDocument,true);assert.equal(displayPreviewOwnership().activeReads,1);assert.equal(displayPreviewOwnership().previewURLs,0);assert.equal(displayReadOwnership().active,1);assert.ok(allocationLedger.snapshot().byKind.bitmap.cpuBytes>0);assert.equal(decoded.closes,0);assert.equal(liveBitmaps.size,1);assert.deepEqual(f.cancellations,[]);
 complete();await release;await waitForDisplayPreviewReads();await waitForDisplayReads();assert.equal(released,true);assert.equal(decoded.closes,1);assert.equal(liveBitmaps.size,0);assert.equal(f.instance.inspect().retainedDocument,false);assert.equal(displayPreviewOwnership().activeReads,0);assert.equal(displayReadOwnership().active,0);assert.equal(allocationLedger.snapshot().activeRecords,diagnosticBaseline.activeRecords);assert(!find(f.template(),'id="export-review"'));assert.deepEqual(f.confirmed,[]);assert.equal(f.editor.view.download,f.prior);
});

// Logical application payload ownership. These tests do not claim native heap,
// ImageBitmap/browser RSS, DOM, or physical Blob-residency qualification.
function fillCPU(leave=0){
 const used=allocationLedger.snapshot().cpuBytes;
 return allocationLedger.reserve({owner:'export-fixture-pressure',kind:'control',cpuBytes:ALLOCATION_LIMITS.cpuBytes-ALLOCATION_LIMITS.textPartitionBytes-used-leave});
}
const emptyExportMemory={models:0,records:{operation:0,owner:0,action:0},retired:0,pending:0,failed:0,callbacks:0,timers:0};
test('refused document admission does not clone or replace the prior complete review',async()=>{
 const f=fixture();await f.initial();await f.ready();const expected={asset:structuredClone(f.asset),document:structuredClone(f.document)},url=attribute(f.template(),'export-preview','src');f.document.name='N'.repeat(8192);
 const nativeClone=globalThis.structuredClone;let clones=0;globalThis.structuredClone=(value,...args)=>{if(value===f.document)clones++;return nativeClone(value,...args);};const pressure=fillCPU(512+16384+1);
 try{await f.prepare();assert.equal(clones,0);assert.equal(f.prepared.length,1);assert.match(f.text(),/ALLOCATION_BUDGET/);assert.equal(attribute(f.template(),'export-preview','src'),url);assert.equal(attribute(f.template(),'confirm-export','?disabled'),false);assert.deepEqual(f.cancellations,[]);}
 finally{pressure.release();globalThis.structuredClone=nativeClone;}
 f.callback('confirm-export')(event());await settle();assert.deepEqual(f.confirmed,[expected]);
});
for(const reason of ['field limit','shared budget'])test('form replacement refused by '+reason+' preserves the exact prior field and preview',async()=>{
 const f=fixture();await f.initial();await f.change('format','jpeg');await f.setArtifact('jpeg',8,6);await f.ready();const url=attribute(f.template(),'export-preview','src'),next=reason==='field limit'?'X'.repeat(EXPORT_MEMORY_LIMITS.formBytes):'#000000',e=event(next),pressure=reason==='shared budget'?fillCPU(512):null;
 try{f.callback('export-matte','@en-change')(e);await flush();assert.equal(e.currentTarget.value,'#FFFFFF');assert.equal(attribute(f.template(),'export-matte','.value'),'#FFFFFF');assert.equal(attribute(f.template(),'export-preview','src'),url);assert.equal(attribute(f.template(),'confirm-export','?disabled'),false);assert.match(f.text(),reason==='field limit'?/EXPORT_MODEL_LIMIT/:/ALLOCATION_BUDGET/);assert.equal(f.prepared.length,1);assert.deepEqual(f.cancellations,[]);}
 finally{pressure?.release();}
 f.callback('confirm-export')(event());await settle();assert.equal(f.confirmed.length,1);assert.equal(f.confirmed[0].asset.blob.mediaType,'image/jpeg');
});
test('asset admission after durable encoding preserves the prior reviewed artifact without canceling accepted work',async()=>{
 const f=fixture();await f.initial();await f.ready();const expected={asset:structuredClone(f.asset),document:structuredClone(f.document)},url=attribute(f.template(),'export-preview','src'),prepare=f.editor.ownedPrepareExport;let pressure;
 f.editor.ownedPrepareExport=async(...args)=>{const response=await prepare.apply(f.editor,args);pressure=fillCPU(16384);return response;};
 try{await f.prepare();assert.equal(f.prepared.length,2);assert.equal(f.reads.length,1);assert.match(f.text(),/ALLOCATION_BUDGET/);assert.equal(attribute(f.template(),'export-preview','src'),url);assert.equal(attribute(f.template(),'confirm-export','?disabled'),false);assert.deepEqual(f.cancellations,[]);}
 finally{pressure?.release();}
 f.callback('confirm-export')(event());await settle();assert.deepEqual(f.confirmed,[expected]);
});
test('a replacement remains separate until its bounded encoded preview is ready',async()=>{
 const f=fixture();await f.initial();await f.ready();const url=attribute(f.template(),'export-preview','src'),complete=await pendingAt(f,'preparation');
 assert.equal(attribute(f.template(),'export-preview','src'),url);assert.equal(attribute(f.template(),'confirm-export','?disabled'),true);assert.equal(f.instance.inspectMemory().models,6);complete();const deadline=performance.now()+2000;while(f.instance.inspect().pendingPreparations&&performance.now()<deadline)await new Promise(resolve=>setImmediate(resolve));await flush();
 assert.notEqual(attribute(f.template(),'export-preview','src'),url);assert.equal(f.instance.inspectMemory().models,4);assert.equal(f.instance.inspectMemory().records.operation,0);assert.equal(f.instance.inspectMemory().records.owner,2);assert.deepEqual(f.confirmed,[]);
});
test('owned snapshots remain booked after release until preparation and cancellation actually settle',async()=>{
 const f=fixture(),reply=deferred();await f.initial();const complete=await pendingAt(f,'preparation'),cancel=f.editor.cancelExport;f.editor.cancelExport=async(...args)=>{await cancel(...args);return reply.promise;};
 const finish=()=>reply.resolve({protocolVersion:1,status:'canceled',receipt:{status:'rejected',code:'INVALID_INPUT'}});fixtureGates.add(finish);
 let settled=false;const release=f.instance.releaseAndWait().then(()=>{settled=true;});await settle();assert.equal(settled,false);assert.equal(f.instance.inspectMemory().models,2);assert.equal(f.instance.inspectMemory().records.operation,1);assert.equal(f.instance.inspectMemory().records.action,1);assert.ok(allocationLedger.snapshot().byKind.control.cpuBytes-diagnosticBaseline.byKind.control.cpuBytes>=16384+512);
 finish();fixtureGates.delete(finish);await settle();assert.equal(settled,false);assert.equal(f.instance.inspectMemory().models,2);complete();await release;assert.deepEqual(f.instance.inspectMemory(),emptyExportMemory);assert.equal(allocationLedger.snapshot().activeRecords,diagnosticBaseline.activeRecords);
});
test('the operation cap retains prior work and refuses another preparation before calling the writer',async()=>{
 const f=fixture(),pending=deferred();await f.initial();await f.ready();const url=attribute(f.template(),'export-preview','src'),prepare=f.editor.prepareExport;f.editor.prepareExport=async(...args)=>{await prepare(...args);return pending.promise;};const finish=()=>pending.resolve(f.asset);fixtureGates.add(finish);
 for(let index=0;index<EXPORT_MEMORY_LIMITS.operations;index++){await f.prepare();f.instance.cancel();await settle();}
 assert.equal(f.prepared.length,1+EXPORT_MEMORY_LIMITS.operations);assert.equal(f.instance.inspectMemory().records.operation,EXPORT_MEMORY_LIMITS.operations);assert.equal(f.instance.inspect().pendingPreparations,EXPORT_MEMORY_LIMITS.operations);
 await f.prepare();assert.equal(f.prepared.length,1+EXPORT_MEMORY_LIMITS.operations);assert.match(f.text(),/EXPORT_OPERATION_CAPACITY/);assert.equal(attribute(f.template(),'export-preview','src'),url);assert.equal(f.cancellations.length,EXPORT_MEMORY_LIMITS.operations);
 finish();fixtureGates.delete(finish);await f.instance.releaseAndWait();assert.deepEqual(f.instance.inspectMemory(),emptyExportMemory);assert.equal(f.editor.view.download,f.prior);
});
test('uncertain settled cancellations keep bounded exact-command ownership until explicit successful drain',async()=>{
 const f=fixture(),pending=deferred();await f.initial();const prepare=f.editor.prepareExport,cancel=f.editor.cancelExport;f.editor.prepareExport=async(...args)=>{await prepare(...args);return pending.promise;};f.editor.cancelExport=async(...args)=>{await cancel(...args);throw Error('Receipt delivery uncertain');};await f.prepare();f.instance.cancel();await settle();pending.reject(Error('Original delivery lost'));await settle();
 assert.equal(f.instance.inspect().cleanupFailures,1);assert.equal(f.instance.inspectMemory().models,1);assert.equal(f.instance.inspectMemory().records.operation,1);assert.equal(f.instance.inspectMemory().records.action,0);assert.deepEqual(f.cancellations.map(row=>row.commandId),['export-command-1']);await assert.rejects(f.instance.releaseAndWait(),/EXPORT_RELEASE_UNCONFIRMED/);assert.equal(f.instance.inspectMemory().records.operation,1);
 f.editor.cancelExport=cancel;await f.instance.releaseAndWait();assert.deepEqual(f.cancellations.map(row=>row.commandId),['export-command-1','export-command-1','export-command-1']);assert.deepEqual(f.instance.inspectMemory(),emptyExportMemory);
});
test('queued action ownership is capped and disposal drains vetoed native tasks without starting work',async()=>{
 const f=fixture();await f.initial();const prepare=f.callback('prepare-export');for(let index=0;index<=EXPORT_MEMORY_LIMITS.actions;index++){const e=event();e.defaultPrevented=true;prepare(e);}
 assert.equal(f.instance.inspectMemory().records.action,EXPORT_MEMORY_LIMITS.actions);assert.equal(f.instance.inspectMemory().timers,EXPORT_MEMORY_LIMITS.actions);await flush();assert.match(f.text(),/EXPORT_ACTION_CAPACITY/);await f.instance.releaseAndWait();await settle();assert.deepEqual(f.instance.inspectMemory(),emptyExportMemory);assert.deepEqual(f.prepared,[]);assert.deepEqual(f.commands,[]);
});
test('retained old form, composition, load and confirmation callbacks cannot keep a released payload live',async()=>{
 const f=fixture();await f.initial();await f.ready();const old={field:f.callback('export-format','@en-change'),load:f.callback('export-preview','@load'),error:f.callback('export-preview','@error'),confirm:f.callback('confirm-export'),composition:f.composition()};
 await f.instance.releaseAndWait();assert.deepEqual(f.instance.inspectMemory(),emptyExportMemory);assert.equal(allocationLedger.snapshot().activeRecords,diagnosticBaseline.activeRecords);await f.initial();await f.ready();const url=attribute(f.template(),'export-preview','src');old.field(event('jpeg'));old.composition[0]();old.composition[1]();old.load({currentTarget:{src:url,naturalWidth:8,naturalHeight:6}});old.error();old.confirm(event());await settle();
 assert.equal(attribute(f.template(),'export-format','.value'),'png');assert.equal(attribute(f.template(),'export-preview','src'),url);assert.equal(attribute(f.template(),'confirm-export','?disabled'),false);assert.deepEqual(f.confirmed,[]);f.callback('confirm-export')(event());await settle();assert.equal(f.confirmed.length,1);
});
test('a form callback retained from a prior generation cannot alter the current review',async()=>{
 const f=fixture();await f.initial();const old=f.callback('export-format','@en-change');await f.ready();old(event('jpeg'));await settle();assert.equal(attribute(f.template(),'export-format','.value'),'png');assert(find(f.template(),'id="export-review"'));assert.equal(f.instance.inspectMemory().models,4);assert.deepEqual(f.confirmed,[]);
});
test('a failed destination-record admission leaves export confirmation retryable',async()=>{
 const f=fixture();await f.initial();await f.ready();const confirm=f.editor.confirmExport;f.editor.confirmExport=()=>{throw Error('DOWNLOAD_MEMORY_BUDGET');};f.callback('confirm-export')(event());await settle();assert.match(f.text(),/DOWNLOAD_MEMORY_BUDGET/);assert.equal(attribute(f.template(),'confirm-export','?disabled'),false);assert.deepEqual(f.confirmed,[]);f.editor.confirmExport=confirm;f.callback('confirm-export')(event());await settle();assert.equal(f.confirmed.length,1);assert.equal(f.prepared.length,1);
});
test('UI retirement timeout retains owned snapshots until the actual later template commit',async()=>{
 const f=fixture(),commit=deferred();await f.initial();await f.ready();const requestUpdate=f.host.requestUpdate;f.host.requestUpdate=function(){this.updateComplete=commit.promise.then(()=>{requestUpdate.call(this);return this.updateComplete;});};
 try{await assert.rejects(f.instance.releaseAndWait(20),/EXPORT_RELEASE_UNCONFIRMED.*UI release has not settled/);assert.equal(f.instance.inspectMemory().models,4);assert.equal(f.instance.inspectMemory().retired,5);assert.ok(f.instance.inspectMemory().pending>0);assert.ok(allocationLedger.snapshot().byKind.control.cpuBytes-diagnosticBaseline.byKind.control.cpuBytes>0);assert.equal(f.instance.inspect().previewURLs,0);}
 finally{f.host.requestUpdate=requestUpdate;commit.resolve();await f.instance.releaseAndWait();}
 assert.deepEqual(f.instance.inspectMemory(),emptyExportMemory);assert(!find(f.template(),'id="export-review"'));assert.equal(allocationLedger.snapshot().activeRecords,diagnosticBaseline.activeRecords);
});
test('a blocked begin admission retains the current complete settings and reviewed file',async()=>{
 const f=fixture();await f.initial();await f.ready();const url=attribute(f.template(),'export-preview','src'),pressure=fillCPU();
 try{f.instance.begin();await flush();assert.match(f.text(),/ALLOCATION_BUDGET/);assert.equal(attribute(f.template(),'export-preview','src'),url);assert.equal(attribute(f.template(),'export-format','.value'),'png');assert.equal(attribute(f.template(),'confirm-export','?disabled'),false);assert.deepEqual(f.cancellations,[]);}
 finally{pressure.release();}f.callback('confirm-export')(event());await settle();assert.equal(f.confirmed.length,1);
});
test('option normalization is not entered when its scratch cannot be admitted',async()=>{
 const f=fixture();await f.initial();await f.ready();const url=attribute(f.template(),'export-preview','src'),nativeSet=globalThis.Set;let normalized=0;globalThis.Set=class extends nativeSet{constructor(value){if(value===f.editor.view.selected)normalized++;super(value);}};
 const pressure=fillCPU(512+16384+modelPayloadBytes(f.document)+8191);
 try{await f.prepare();assert.equal(normalized,0);assert.equal(f.prepared.length,1);assert.match(f.text(),/ALLOCATION_BUDGET/);assert.equal(attribute(f.template(),'export-preview','src'),url);assert.deepEqual(f.cancellations,[]);}
 finally{pressure.release();globalThis.Set=nativeSet;}
 f.callback('confirm-export')(event());await settle();assert.equal(f.confirmed.length,1);
});
test('reopening export during an old drain cannot report the new review released',async()=>{
 const f=fixture();await f.initial();const prepare=f.editor.prepareExport,complete=await pendingAt(f,'preparation'),release=assert.rejects(f.instance.releaseAndWait(),/EXPORT_RELEASE_SUPERSEDED/);f.instance.begin();await flush();await release;
 assert.equal(attribute(f.template(),'export-format','.value'),'png');assert.ok(f.instance.inspectMemory().models>0);f.editor.prepareExport=prepare;await f.ready();const url=attribute(f.template(),'export-preview','src');complete();await settle();assert.equal(attribute(f.template(),'export-preview','src'),url);f.callback('confirm-export')(event());await settle();assert.equal(f.confirmed.length,1);
});
for(const [label,code,expected]of [['oversized string','X'.repeat(EXPORT_MEMORY_LIMITS.errorUnits+1),/oversized diagnostic/],['non-string',{untrusted:'receipt code'},/EXPORT_UNAVAILABLE/]])test('a cancellation receipt with '+label+' code cannot bypass bounded diagnostics',async()=>{
 const f=fixture();await f.initial();const complete=await pendingAt(f,'preparation');f.editor.cancelExport=async()=>({status:'completed',receipt:{status:'rejected',code}});f.instance.cancel();await settle();assert.match(f.text(),expected);assert.match(f.text(),/original export failed/);assert(!f.text().includes('X'.repeat(EXPORT_MEMORY_LIMITS.errorUnits)));assert(!f.text().includes('[object Object]'));complete();await f.instance.releaseAndWait();assert.deepEqual(f.instance.inspectMemory(),emptyExportMemory);
});
for(const boundary of ['document','identity','draft owner'])test('an image error cannot change a stale owner before sync after '+boundary,async()=>{
 const f=fixture();await f.initial();await f.ready();const imageError=f.callback('export-preview','@error');replaceOwner(f,boundary);imageError();await flush();assert(!f.text().includes('Encoded export could not be displayed.'));assert.deepEqual(f.confirmed,[]);f.instance.sync();await f.instance.releaseAndWait();assert.deepEqual(f.instance.inspectMemory(),emptyExportMemory);
});

for(const phase of ['ready','stale','invalid','clone-refused'])test('owned export response releases once after '+phase+' result handoff',async()=>{
 const f=fixture();await f.initial();let pressure;try{
  if(phase==='invalid')f.asset.raster.role='canonical';
  if(phase==='clone-refused'){const original=f.editor.ownedPrepareExport;f.editor.ownedPrepareExport=async(...args)=>{const result=await original.apply(f.editor,args);pressure=fillCPU(16384);return result;};}
  if(phase==='stale'){const complete=await pendingAt(f,'preparation');replaceOwner(f,'document');f.instance.sync();complete();await settle();}else await f.prepare();
  await settle();const result=f.responseOwners.find(value=>value.kind==='asset');assert(result);assert.equal(result.released,true);assert.equal(f.responseOwners.filter(value=>value.kind==='asset').length,1);
  if(phase==='ready'){const deadline=performance.now()+2000;while(!find(f.template(),'id="export-review"')&&!find(f.template(),'role="alert"')&&performance.now()<deadline)await new Promise(resolve=>setImmediate(resolve));assert(find(f.template(),'id="export-review"'));const original=structuredClone(result.value);result.value.id='changed after response release';result.value.blob.hash='changed';f.load();await flush();f.callback('confirm-export')(event());await settle();assert.equal(f.confirmed[0].asset.id,original.id);assert.equal(f.confirmed[0].asset.blob.hash,original.blob.hash);}else assert(!find(f.template(),'id="export-review"'));
 }finally{pressure?.release();}
});
test('owned cancellation response releases after updating only bounded export status',async()=>{const f=fixture();await f.initial();const complete=await pendingAt(f,'preparation');f.instance.cancel();await settle();const response=f.responseOwners.find(value=>value.kind==='cancel');assert(response);assert.equal(response.released,true);assert.match(f.text(),/Export canceled/);complete();await settle();assert(f.responseOwners.every(value=>value.released));});
