import test from 'node:test';import assert from 'node:assert/strict';import {fixture,prepare,enqueue,auth,envelope,encode} from '../queue/helpers.mjs';import {childFor} from '../store/helpers.mjs';
const send=(w,b)=>w.queueCommand(encode(envelope(b)),auth());
async function plan(w){await send(w,{type:'PreviewDocumentDeletion',documentId:'document_1',expectedRevision:'1'});const p=(await w.deletionView('document_1',auth())).plan;return {type:'DeleteDocument',documentId:p.documentId,planId:p.id,planHash:p.planHash,expectedRevision:p.documentRevision,rootGeneration:p.rootGeneration,acknowledgeRunningAndUncertain:false};}
for(const [phase,deleted] of [['deletion-before-commit',false],['asset-after-commit',true]])test('process death at '+phase+' keeps deletion atomic and replay has zero effects',async t=>{const f=await fixture(t);await enqueue(f.writer,(await prepare(f.writer)).body);await f.close();const child=await childFor(t,f.root,{phase});let b;if(phase==='asset-after-commit'){
 // Preview must be created before installing the generic accepted-command barrier.
 await child.kill();const w=await f.reopen();b=await plan(w);await f.close();
 }const active=phase==='asset-after-commit'?await childFor(t,f.root,{phase}):child;
 const api={queueCommand:(...p)=>active.call('queueCommand',...p),deletionView:(...p)=>active.call('deletionView',...p)};
 if(!b)b=await plan(api);const c=envelope(b),pending=active.call('queueCommand',encode(c),auth()).catch(e=>e);await active.wait('barrier');await active.assertNoEffects();await active.kill();await pending;const w=await f.reopen();assert.equal((await w.document('document_1'))===null,deleted);assert.equal(!!await w.lookup(c.command.commandId),deleted);
});
for(const phase of ['deletion-quarantine-committed','deletion-unlink-intent-committed','deletion-after-unlink'])test('process death at '+phase+' preserves restart-safe GC and actual reclaimed accounting',async t=>{const f=await fixture(t);await enqueue(f.writer,(await prepare(f.writer)).body);await send(f.writer,await plan(f.writer));await f.close();const child=await childFor(t,f.root,{phase}),c=envelope({type:'CollectDocumentGarbage',documentId:'document_1'}),pending=child.call('queueCommand',encode(c),auth()).catch(e=>e);await child.wait('barrier');await child.assertNoEffects();await child.kill();await pending;const w=await f.reopen();assert.equal(await w.document('document_1'),null);assert.equal((await w.queueCommand(encode(c),auth())).status,'accepted');const r=(await w.deletionView('document_1',auth())).receipt;assert.equal(r.status,'cleanup-complete');assert(BigInt(r.actualFreedBytes)>0n);});
