// Test-only controlled loopback transport. No production entry imports this module.
import {createServer} from 'node:http';import {once} from 'node:events';import {readFileSync,writeFileSync,existsSync} from 'node:fs';import {join} from 'node:path';import assert from 'node:assert/strict';import sharp from 'sharp';
import {emulator,fixtureProfile} from '../provider/emulator.mjs';import {QueueDispatcher} from '../../dist/local/server/provider/dispatcher.js';import {ResultObserver} from '../../dist/local/server/provider/observer.js';
export async function setup(store){
 const path=join(store.root,'e4-fixture.json'),gatePath=join(store.root,'e4-gate.json'),prior=existsSync(path)?JSON.parse(readFileSync(path,'utf8')):{effects:[],requests:[],milestones:[]},effects=prior.effects,requests=new Map(prior.requests),errors=[],milestones=prior.milestones;let origin='',closing=false,pending;
 const gate=()=>existsSync(gatePath)?JSON.parse(readFileSync(gatePath,'utf8')):{status:'IN_PROGRESS',image:false,uncertain:false};
 const write=extra=>writeFileSync(path,JSON.stringify({effects,requests:[...requests],milestones,errors,port:new URL(origin).port,...extra},null,2),{mode:0o600});
 const png=await sharp({create:{width:512,height:512,channels:4,background:'#2468ac'}}).png().toBuffer();
 const server=createServer(async(req,res)=>{try{const body=Buffer.concat(await Array.fromAsync(req));effects.push({at:Date.now(),method:req.method,path:req.url,bytes:body.length});res.setHeader('Content-Type','application/json');
  if(req.method==='POST'){const id='e4_'+(requests.size+1),value=JSON.parse(body);requests.set(id,{value,endpoint:req.url});write({closed:false});if(gate().uncertain){req.socket.destroy();return;}await new Promise(r=>setTimeout(r,850));const base=origin+req.url+'/requests/'+id;res.end(JSON.stringify({request_id:id,status_url:base+'/status',response_url:base,cancel_url:base+'/cancel'}));}
  else if(req.url.endsWith('/cancel')){res.statusCode=202;res.end('{}');}
  else if(req.url.startsWith('/image/')){const deadline=Date.now()+15000;while(!gate().image&&!closing&&!res.destroyed&&Date.now()<deadline)await new Promise(r=>setTimeout(r,25));if(!gate().image&&!res.destroyed)throw Error('Image gate deadline');if(!res.destroyed){res.setHeader('Content-Type','image/png');res.end(png);}}
  else{const id=/\/requests\/([^/?]+)/.exec(req.url)?.[1],request=requests.get(id);assert(request);if(req.url.endsWith('/status')){const status=gate().status;if(status==='COMPLETED')milestones.push({phase:'availability',requestId:id,at:Date.now(),clock:'writer-wall-ms'});res.end(JSON.stringify({request_id:id,status}));}else res.end(JSON.stringify({images:[{url:origin+'/image/'+id,width:512,height:512}],prompt:request.value.prompt,seed:7,timings:{inference:0.2},has_nsfw_concepts:[false]}));}write({closed:false});
 }catch(error){errors.push({message:error.message,stack:error.stack});res.statusCode=500;res.end('{}');write({closed:false});}});
 server.listen(prior.port?Number(prior.port):0,'127.0.0.1');await once(server,'listening');origin='http://127.0.0.1:'+server.address().port;
 const endpoints=['ideogram/v4','ideogram/v4/fast','ideogram/v4/instant'],profiles=endpoints.map((endpoint,i)=>fixtureProfile({id:'e4-profile-'+i,endpoint})),provider=emulator({queueOrigin:origin,mediaOrigin:origin,profiles});
 const routes=endpoints.map((endpoint,i)=>{const dispatcher=new QueueDispatcher(store.queue,provider,{queueOrigin:origin,profileId:profiles[i].id}),queue=new Proxy(store.queue,{get(target,key){const value=target[key];if(['controlWork','recoveryWork'].includes(key))return ()=>value.call(target).filter(w=>target.recovery(w.jobId,w.attemptId).endpoint===endpoint);return typeof value==='function'?value.bind(target):value;}}),candidates=new Proxy(store.candidates,{get(target,key){if(key==='queue')return queue;const value=target[key];if(key==='due')return now=>value.call(target,now).filter(f=>store.queue.recovery(f.jobId,f.attemptId).endpoint===endpoint);if(key==='retries')return ()=>value.call(target).filter(f=>store.queue.recovery(f.jobId,f.attemptId).endpoint===endpoint);return typeof value==='function'?value.bind(target):value;}});return {endpoint,dispatcher,observer:new ResultObserver(candidates,provider,dispatcher,profiles[i].id)};});
 let last='';const record=()=>{const jobs=store.queue.view().jobs,state=JSON.stringify(jobs.map(j=>({id:j.id,version:j.version,attempts:j.attempts})));if(state!==last){last=state;milestones.push({at:Date.now(),jobs:JSON.parse(state),journal:store.db.prepare('SELECT json FROM queue_journal ORDER BY seq DESC LIMIT 1').get()?.json});}write({closed:false});};
 const authority=(phase,value)=>{milestones.push({phase,clock:'writer-wall-ms',at:Date.now(),monotonic:performance.now(),...value});write({closed:false});};
 const dispatch=store.queue.dispatch.bind(store.queue);store.queue.dispatch=(...args)=>{const result=dispatch(...args);if(result){const job=store.queue.view().jobs.find(j=>j.id===result.jobId),command=store.db.prepare("SELECT command_id,json FROM events_v2 WHERE json_extract(json,'$.type')='JobQueued' AND json_extract(json,'$.payload.id')=?").get(job.id);authority('P1',{job,commandId:command.command_id,event:JSON.parse(command.json)});}return result;};
 const command=store.queue.command.bind(store.queue);store.queue.command=async(bytes,...args)=>{const result=await command(bytes,...args),c=JSON.parse(Buffer.from(bytes)).command;if(c.body.type==='CancelJob'&&result.status==='accepted')authority('P2',{commandId:c.commandId,receipt:result,job:store.queue.view().jobs.find(j=>j.id===c.body.jobId)});return result;};
 const resultTransaction=store.queue.resultTransaction.bind(store.queue),seen=new Set();store.queue.resultTransaction=(f,work)=>{const result=resultTransaction(f,work);let view;try{view=store.candidates.view(f.jobId,f.attemptId);}catch{return result;}if(view.observation?.phase==='completed'&&!seen.has('P3:'+f.attemptId)){seen.add('P3:'+f.attemptId);authority('P3',{jobId:f.jobId,attemptId:f.attemptId,view});}for(const c of view.items)if(c.state==='prepared'&&!seen.has('P4:'+c.id)){seen.add('P4:'+c.id);authority('P4',{jobId:f.jobId,attemptId:f.attemptId,candidate:c,asset:store.assets.asset(c.preparedAssetId)});}return result;};
 const timer=setInterval(()=>{if(closing||pending)return;pending=(async()=>{for(const route of routes){for(const job of store.queue.view().jobs)if(job.review.endpoint===route.endpoint&&job.attempts.at(-1).state==='not-started'){try{await route.dispatcher.submit(job.id);}catch(error){const a=store.queue.view().jobs.find(j=>j.id===job.id).attempts.at(-1);if(!gate().uncertain||a.state!=='submission-uncertain')throw error;}}await route.observer.tick();}record();})().catch(error=>{errors.push({message:error.message,stack:error.stack});closing=true;clearInterval(timer);write({closed:false});}).finally(()=>pending=undefined);},100);
 write({closed:false});return async()=>{closing=true;clearInterval(timer);for(const route of routes)route.observer.close();await pending;await new Promise(r=>server.close(r));const rasterRead=store.rasters.readDiagnostics();try{const resources={objects:store.objects.reservationInventory(),raster:rasterRead.value,text:{reservedCPU:store.texts.reservedCPU,externalBytes:store.texts.externalBytes()}};write({closed:true,resources});assert.deepEqual(errors,[]);assert.deepEqual(resources.objects,{reservedBytes:'0',activeTransfers:0});assert.equal(resources.raster.activeWorkers,0);assert.equal(resources.raster.reservedCPU,0);}finally{rasterRead.release();}};
}
