import {test as base,expect,type Page} from '@playwright/test';import {mkdtemp,realpath,readFile,mkdir,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {serverProcess} from './e4-process.js';import {ownedOPFS} from '../editor/owned-opfs.js';import {recordDOMErrors} from '../editor/error-monitor.js';import {runs,step,throwFailures,type RunState} from '../editor/harness-lifecycle.js';import {finish} from './lifecycle.js';import {publicReadRequest} from '../request/persistence-witness.js';
const receipt=process.env.EDITOR_RECEIPT??'artifacts/p25-browser';
const test=base.extend({context:async({playwright,browserName,contextOptions,viewport},use,info)=>{const profile=browserName==='webkit'?await mkdtemp(join(await realpath(tmpdir()),'p25-webkit-')):undefined,browser=profile?undefined:await playwright[browserName].launch(),context=profile?await playwright.webkit.launchPersistentContext(profile,{...contextOptions,viewport}):await browser!.newContext({...contextOptions,viewport});await Promise.all(context.pages().map(p=>p.close()));try{await use(context);}finally{await finish(context,browser,profile,receipt,info);}}});
const click=(page:Page,name:string)=>page.getByRole('button',{name,exact:true}).click();
async function number(page:Page,name:string,value:string){const f=page.getByRole('spinbutton',{name,exact:true});await f.fill(value);await f.press('Tab');}
test('E4 and DR-1 preserve known and uncertain attempts, late candidates and durable deletion',async({page,context,browserName})=>{
 const guard=await ownedOPFS(context,'p25-e4'),errors=await recordDOMErrors(context),csp:any[]=[],external:any[]=[],consoleErrors:any[]=[],commands:any[]=[],deliveries:any[]=[],states:any[]=[],restarts:any[]=[],paints:any[]=[],publications:any[]=[],network:any[]=[],consoleDiagnostics:any[]=[],runtime:any={},dir=await mkdtemp(join(await realpath(tmpdir()),'p25-e4-')),root=join(dir,'private'),origins=new Set<string>();let server:any,closed:any,trace:any;
 const state:RunState={failures:[],roots:[dir],writerClosed:false,contextClosed:false,browserClosed:false,retention:[],receipt,prefix:'e4-'};runs.set(context,state);
 state.observe=()=>({errors,csp,external,consoleErrors,consoleDiagnostics,network,commands,deliveries,states,restarts,paints,publications,runtime,closed,process:server?.lifecycle,requestLifecycle:guard.requests,cleanup:guard.ledger,limits:'Six distinct semantic states and four delivery identities only. Raw renderer events are uncorrelated diagnostics only: no status-paint association, renderer paint timing, presented/display timing, R04 pass or formal H4/I6H samples are claimed.'});
 state.finalCheck=async()=>{guard.verify();expect(errors).toEqual([]);expect(csp).toEqual([]);expect(external).toEqual([]);expect(consoleErrors).toEqual([]);expect(closed?.closed).toBe(true);expect(closed?.errors).toEqual([]);expect(closed?.resources.objects).toEqual({reservedBytes:'0',activeTransfers:0});expect(closed?.resources.raster.activeWorkers).toBe(0);};
 await context.exposeBinding('e4CSP',(_s,v)=>csp.push(v));await context.addInitScript(()=>addEventListener('securitypolicyviolation',e=>(window as any).e4CSP({directive:e.effectiveDirective,blocked:e.blockedURI})));
 await context.addInitScript(()=>{const original=window.fetch.bind(window);(window as any).__p25OriginalFetch=original;(window as any).__p25Deliveries=[];window.fetch=async(...args)=>{const response=await original(...args);if(response.url.includes('/api/v1/queue')||response.url.includes('/candidates?')||response.url.includes('/api/v1/commands')){const json=response.json.bind(response);response.json=async()=>{const value=await json();(window as any).__p25Deliveries.push({clock:'browser-wall-ms',at:Date.now(),monotonic:performance.now(),path:new URL(response.url).pathname,value});return value;};}return response;};});
 const safeURL=(raw:string)=>{try{const u=new URL(raw);return u.origin+u.pathname;}catch{return '';}};
 const requestIds=new WeakMap<object,number>();let requestSequence=0;const requestId=(r:object)=>{let id=requestIds.get(r);if(!id){id=++requestSequence;requestIds.set(r,id);}return id;};
 page.on('request',r=>network.push({event:'request',at:Date.now(),id:requestId(r),method:r.method(),url:safeURL(r.url()),resourceType:r.resourceType()}));
 page.on('response',r=>network.push({event:'response',at:Date.now(),id:requestId(r.request()),status:r.status(),url:safeURL(r.url()),resourceType:r.request().resourceType()}));
 page.on('requestfailed',r=>network.push({event:'failed',at:Date.now(),id:requestId(r),url:safeURL(r.url()),resourceType:r.resourceType(),error:r.failure()?.errorText??null}));
 page.on('console',m=>{const location=m.location();consoleDiagnostics.push({at:Date.now(),type:m.type(),text:m.text(),location:{...location,url:safeURL(location.url)}});if(m.type()==='error')consoleErrors.push(m.text());});page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/api/v1/commands'))commands.push({at:Date.now(),...JSON.parse(r.postData()!).command});});page.on('response',r=>{if(r.url().includes('/api/v1/queue')||r.url().includes('/candidates?'))void r.json().then(value=>deliveries.push({at:Date.now(),path:new URL(r.url()).pathname,value})).catch(()=>{});});
 await context.route('**/*',async route=>{const r=route.request(),u=new URL(r.url());if(['http:','https:'].includes(u.protocol)&&!origins.has(u.origin)){external.push(u.origin);await route.abort();return;}if(r.method()==='POST'&&u.pathname==='/api/v1/commands'&&['QueueInference','CancelJob'].includes(JSON.parse(r.postData()!).command.body.type))await new Promise(r=>setTimeout(r,200));await route.continue();});
 async function read(path:string){return page.evaluate(async s=>{const r=await ((window as any).__p25OriginalFetch??fetch)(s.path,s.init);if(!r.ok)throw Error('Public read '+r.status);return r.json();},publicReadRequest(path));}
 async function gate(value:unknown){await writeFile(join(root,'e4-gate.json'),JSON.stringify(value),{mode:0o600});}
 async function boot(){server=await serverProcess(root);origins.add(server.origin);await guard.admit(page,server.origin);await page.goto(await server.pair());await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();}
 async function restart(job:any){const before=await server.effects();deliveries.push(...(await page.evaluate(()=>(window as any).__p25Deliveries)).map((d:any)=>({...d,application:true})));await page.goto('about:blank');await server.kill();restarts.push({before,lifecycle:server.lifecycle});await boot();const reopened=await read('/api/v1/queue'),same=reopened.jobs.find((j:any)=>j.id===job.id);expect(same.attempts.map((a:any)=>a.id)).toEqual(job.attempts.map((a:any)=>a.id));expect((await server.effects()).effects).toEqual(before.effects);await click(page,'Open');await page.getByRole('button',{name:new RegExp('^Restore '+job.review.draft.sessionId+' · document '+job.documentId+' · sequence ')}).click();await expect(page.getByRole('dialog',{name:'Open document',exact:true})).toBeHidden();await expect(page.getByRole('textbox',{name:'Prompt',exact:true})).toHaveValue(job.review.endpoint.endsWith('/fast')?'Fast uncertain Café 東京':'Known late Café 東京');await click(page,'Refresh durable queue');return same;}
 async function milestone(name:string,text:string,publication:string|null,job:any=null){await expect(page.getByText(text,{exact:false}).first()).toBeVisible();const mark=await page.evaluate(name=>{performance.mark('p25.'+name);return {at:Date.now(),monotonic:performance.now()};},name);const q=await read('/api/v1/queue');states.push({name,...mark,text,publication,jobId:job?.id??q.jobs.at(-1)?.id,attemptId:job?.attempts[0]?.id??q.jobs.at(-1)?.attempts[0]?.id,queue:q,commandId:commands.at(-1)?.commandId,body:await page.locator('body').innerText()});}
 async function create(prompt:string){await click(page,'New');await number(page,'Width (px)','512');await number(page,'Height (px)','512');await click(page,'Create');await expect(page.getByRole('dialog',{name:'New document',exact:true})).toBeHidden();await number(page,'Output width','512');await number(page,'Output height','512');await page.getByRole('textbox',{name:'Prompt',exact:true}).fill(prompt);}
 async function review(){await click(page,'Review exact request');await expect(page.locator('#request-review')).toBeFocused();await click(page,'Accept this exact review locally');await expect(page.locator('#enqueue-request')).toBeEnabled();}
 try{
  await mkdir(receipt,{recursive:true});await boot();Object.assign(runtime,{version:context.browser()?.version()??null,userAgent:await page.evaluate(()=>navigator.userAgent),pin:JSON.parse(await readFile('node_modules/playwright-core/browsers.json','utf8')).browsers.find((b:any)=>b.name===browserName)});
  if(browserName==='chromium'){trace=await context.newCDPSession(page);trace.on('Tracing.dataCollected',({value}:any)=>{for(const e of value)if(e.name==='Paint'||e.name.startsWith('p25.'))paints.push({name:e.name,ts:e.ts,dur:e.dur,pid:e.pid,tid:e.tid});});await trace.send('Tracing.start',{categories:'devtools.timeline,blink.user_timing',transferMode:'ReportEvents'});}
  await create('Known late Café 東京');await review();const pending=click(page,'Enqueue accepted request');await milestone('F1','Saving request…',null);await pending;let known:any;await expect.poll(async()=>{known=(await read('/api/v1/queue')).jobs[0];return known?.attempts[0].state;}).toBe('dispatching');await milestone('F2','dispatching','P1',known);states[0].jobId=known.id;states[0].attemptId=known.attempts[0].id;states[0].identityLinkedAfterReceipt=true;await expect.poll(async()=>((await read('/api/v1/queue')).jobs[0]).attempts[0].state).toBe('acknowledged');
  known=await restart(known);await expect(page.locator('#durable-queue')).toContainText('Recovery is paused after restart');await click(page,'Check existing request '+known.attempts[0].id);await expect(page.locator('#durable-queue')).not.toContainText('Recovery is paused after restart');await expect(page.locator('#durable-queue')).toHaveAttribute('aria-busy','false');await expect(page.getByRole('button',{name:'Request cancellation '+known.attempts[0].id,exact:true})).toBeEnabled();
  const cancelling=click(page,'Request cancellation '+known.attempts[0].id);await milestone('F3','Saving cancellation request…',null,known);await cancelling;await milestone('F4','Cancellation requested; work may still finish.','P2',known);expect(commands.filter(c=>c.body.type==='CancelJob')).toHaveLength(1);await expect.poll(async()=>((await read('/api/v1/queue')).jobs.find((j:any)=>j.id===known.id)).attempts[0].cancel).toBe('acknowledged');
  await gate({status:'COMPLETED',image:false,uncertain:false});await milestone('F5','Late result available; retrieving and verifying owned image bytes.','P3',known);await gate({status:'COMPLETED',image:true,uncertain:false});await milestone('F6','Output 1: prepared','P4',known);
  const prompt=page.getByRole('textbox',{name:'Prompt',exact:true});await prompt.focus();await expect(prompt).toBeFocused();expect((await read('/api/v1/documents/'+known.documentId)).projection.value.revision).toBe('1');await click(page,'Undo pending request');await expect(page.locator('#durable-queue')).toContainText('suppressed-by-undo');await click(page,'Redo pending request without resubmitting');await expect(page.locator('#durable-queue')).toContainText('set-aside');expect((await server.effects()).effects.filter((e:any)=>e.method==='POST')).toHaveLength(1);
  await click(page,'Review document deletion');const deletion=page.getByRole('region',{name:'Document deletion',exact:true});await expect(deletion).toContainText('Normal Undo cannot restore it');await expect(deletion.getByRole('button',{name:'Save a complete copy first',exact:true})).toBeVisible();const confirm=deletion.getByRole('button',{name:'Confirm permanent document deletion',exact:true});await confirm.evaluate(el=>el.addEventListener('click',e=>e.preventDefault(),{once:true}));await confirm.click();expect(commands.filter(c=>c.body.type==='DeleteDocument')).toHaveLength(0);await confirm.focus();await confirm.press('Enter');await expect(deletion).toContainText('Document deleted; cleanup pending');await click(page,'Check and reclaim eligible bytes');await expect(deletion).toContainText('Actual freed local backend bytes:');expect((await read('/api/v1/deletions')).items.some((r:any)=>r.documentId===known.documentId)).toBe(true);
  await gate({status:'IN_PROGRESS',image:false,uncertain:true});await create('Fast uncertain Café 東京');await page.getByRole('combobox',{name:'Operation',exact:true}).selectOption('Generate with Fast');await click(page,'Keep acceleration inactive in this draft');await review();await click(page,'Enqueue accepted request');let uncertain:any;await expect.poll(async()=>{uncertain=(await read('/api/v1/queue')).jobs.find((j:any)=>j.review.endpoint==='ideogram/v4/fast');return uncertain?.attempts[0].state;}).toBe('submission-uncertain');uncertain=await restart(uncertain);await expect(page.locator('#durable-queue')).toContainText('submission-uncertain');await click(page,'Check existing request '+uncertain.attempts[0].id);await expect(page.locator('#durable-queue')).toContainText('No validated acknowledgement found');expect((await server.effects()).effects.filter((e:any)=>e.method==='POST')).toHaveLength(2);expect((await read('/api/v1/queue')).jobs.find((j:any)=>j.id===uncertain.id).attempts).toHaveLength(1);
  await click(page,'Review document deletion');await expect(deletion).toContainText('may still run or be charged');await click(page,'Acknowledge running work and delete document');await expect(deletion).toContainText('A remote slot remains held');await click(page,'Check and reclaim eligible bytes');await expect(deletion).toContainText('Document cleanup complete.');await expect(deletion).toHaveAttribute('aria-busy','false');await expect(deletion.getByRole('button',{name:'Review possible overlap for deleted request',exact:true})).toBeEnabled();await click(page,'Review possible overlap for deleted request');await expect(deletion).toContainText('does not cancel, refund or erase it');await expect(deletion.locator('en-alert[role="status"]')).toHaveText('Review the overlap and charge risk below. No hold has been released.');await expect(deletion).toHaveAttribute('aria-busy','false');await click(page,'Acknowledge overlap and release deleted request hold');await expect(deletion).toContainText('No local slot remains held');
  deliveries.push(...(await page.evaluate(()=>(window as any).__p25Deliveries)).map((d:any)=>({...d,application:true})));await page.reload();await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await click(page,'Review pending document cleanup');await click(page,'Inspect cleanup for '+uncertain.documentId);await expect(deletion).toContainText('Actual freed local backend bytes');await expect(deletion.locator('en-alert[role="status"]')).toHaveText('Receipt inspected: document cleanup is complete. Remote work and charges remain unconfirmed.');await expect(deletion).toHaveAttribute('aria-busy','false');expect((await read('/api/v1/deletions')).items).toHaveLength(2);const effects=await server.effects();expect(effects.errors).toEqual([]);expect(effects.effects.filter((e:any)=>e.method==='POST').map((e:any)=>e.path)).toEqual(['/ideogram/v4','/ideogram/v4/fast']);expect(effects.effects.filter((e:any)=>e.path.endsWith('/cancel'))).toHaveLength(1);
  deliveries.push(...(await page.evaluate(()=>(window as any).__p25Deliveries)).map((d:any)=>({...d,application:true})));const authority=(await server.effects()).milestones;const browserDeliveries=deliveries.filter(d=>d.application===true);for(const phase of ['P1','P2','P3','P4']){const a=authority.find((a:any)=>a.phase===phase&&(a.job?.id??a.jobId)===known.id);expect(a,'Committed authority '+phase).toBeTruthy();const d=browserDeliveries.find(d=>d.at>=a.at&&(phase==='P1'?d.value.jobs?.some((j:any)=>j.id===known.id&&j.version===a.job.version):phase==='P2'?d.value.receipt?.commandId===a.commandId&&d.value.receipt?.toSeq===a.receipt.toSeq:d.value.jobId===known.id&&d.value.items!==undefined&&(phase==='P3'?d.value.observation?.digest===a.view.observation.digest&&!d.value.items.some((c:any)=>c.state==='prepared'):d.value.items.some((c:any)=>c.id===a.candidate.id&&c.version===a.candidate.version&&c.preparedAssetId===a.candidate.preparedAssetId))));expect(d,'Actual application delivery '+phase).toBeTruthy();expect(d.at-a.at,'Observed '+phase+' publication allowance').toBeLessThanOrEqual(250);publications.push({phase,authority:a,delivery:d,intervalMs:d.at-a.at,clockUncertainty:'Same-host wall clocks, 1 ms resolution; software observation after commit, not hardware presentation'});}const available=authority.find((a:any)=>a.phase==='availability'),retrieval=effects.effects.find((e:any)=>e.path.startsWith('/image/'));expect(available).toBeTruthy();expect(retrieval).toBeTruthy();expect(retrieval.at-available.at).toBeGreaterThanOrEqual(0);expect(retrieval.at-available.at).toBeLessThanOrEqual(3000);runtime.retrievalStart={availabilityAt:available.at,startAt:retrieval.at,intervalMs:retrieval.at-available.at};runtime.semanticTraceUnionMs=states.at(-1).at-states[0].at;expect(publications[0].authority.commandId).toBe(states[0].commandId);expect(states.find(s=>s.name==='F3').at,'F3 precedes cancellation acknowledgement').toBeLessThan(publications.find(p=>p.phase==='P2').authority.at);expect(states.map(s=>s.name)).toEqual(['F1','F2','F3','F4','F5','F6']);expect(states.filter(s=>s.publication).map(s=>s.publication)).toEqual(['P1','P2','P3','P4']);expect(new Set(states.map(s=>s.jobId))).toEqual(new Set([known.id]));expect(new Set(states.map(s=>s.attemptId))).toEqual(new Set([known.attempts[0].id]));
  await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await page.setViewportSize({width:320,height:900});await deletion.scrollIntoViewIfNeeded();const geometry=await deletion.evaluate(el=>({width:el.getBoundingClientRect().width,scroll:el.scrollWidth}));expect(geometry.scroll).toBeLessThanOrEqual(geometry.width+1);await deletion.getByRole('button',{name:'Review pending document cleanup',exact:true}).focus();await expect(deletion.getByRole('button',{name:'Review pending document cleanup',exact:true})).toBeFocused();if(browserName!=='webkit')await page.screenshot({path:join(receipt,'deletion-narrow.png'),caret:'initial'});
 }catch(error){state.failures.push({phase:'body',error});}finally{
  if(trace)await step(state,'renderer-trace-close',async()=>{const done=new Promise<void>(r=>trace.once('Tracing.tracingComplete',()=>r()));await trace.send('Tracing.end');await done;});
  if(!state.failures.length)await step(state,'logical-cleanup',async()=>{for(const p of context.pages())await p.goto('about:blank');await guard.cleanup();guard.verify();});
  if(server)state.writerClosed=await step(state,'writer-close',()=>server.close());if(state.writerClosed)await step(state,'native-close-receipt',async()=>{closed=JSON.parse(await readFile(join(root,'e4-fixture.json'),'utf8'));expect(closed.closed).toBe(true);expect(closed.errors).toEqual([]);});throwFailures(state.failures);
 }
});
