import {test as base,expect,type Page} from '@playwright/test';import {mkdtemp,realpath,readFile,mkdir,writeFile,rename,cp} from 'node:fs/promises';import {randomUUID} from 'node:crypto';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {serverProcess} from './e4-process.js';import {ownedOPFS} from '../editor/owned-opfs.js';import {recordDOMErrors} from '../editor/error-monitor.js';import {runs,type RunState} from '../editor/harness-lifecycle.js';import {registerFinish,assertFinished} from './lifecycle.js';import {publicReadRequest} from '../request/persistence-witness.js';
// @ts-ignore Bounded independent cleanup checks.
import {boundedStep} from './bounded-step.mjs';
// @ts-ignore Public lifecycle ownership is covered by focused runner controls.
import {acquireBrowserContext} from './browser-lifetime.mjs';
// @ts-ignore Synthetic controls exercise this exact fixture owner.
import {FixtureOwner,ownedFixture} from './fixture-owner.mjs';
// @ts-ignore The bounded fixture observes original consumer reads and parse returns.
import {installE4DeliveryObserver} from './e4-delivery-observer.mjs';
import {installE4TransactionTiming} from './e4-transaction-timing.mjs';
const owners=new WeakMap<object,any>();
const receipt=process.env.EDITOR_RECEIPT??'artifacts/p25-browser';
const test=base.extend({context:[async({playwright,browserName,contextOptions,viewport},use,info)=>{
 const state:RunState={failures:[],roots:[],writerClosed:false,contextClosed:false,browserClosed:false,retention:[],receipt,prefix:'e4-'};
 const owner=new FixtureOwner(state);let profile:string|undefined;
 registerFinish(owner,receipt,info);
 await ownedFixture(owner,async()=>{
  if(browserName==='webkit'){profile=await owner.acquire('profile',async()=>mkdtemp(join(await realpath(tmpdir()),'p25-webkit-')));state.roots.push(profile!);await acquireBrowserContext(owner,playwright.webkit,profile,{...contextOptions,viewport});}
  else{await acquireBrowserContext(owner,playwright[browserName],undefined,{...contextOptions,viewport});}
  const context=owner.resources.context;owners.set(context,owner);runs.set(context,state);
  await owner.active(()=>Promise.all(context.pages().map((p:Page)=>p.close())));
 },()=>use(owner.resources.context));assertFinished(owner);
}, {scope:'test',timeout:140000}]});
test('E4 and DR-1 preserve known and uncertain attempts, late candidates and durable deletion',async({page,context,browserName})=>{
 const owner=owners.get(context),state:RunState=owner.state;let guard:any,errors:any[]=[],dir:string|undefined,root:string|undefined,server:any,closed:any,trace:any;
 const csp:any[]=[],external:any[]=[],consoleErrors:any[]=[],commands:any[]=[],deliveries:any[]=[],deliveryErrors:any[]=[],states:any[]=[],restarts:any[]=[],paints:any[]=[],publications:any[]=[],network:any[]=[],consoleDiagnostics:any[]=[],runtime:any={},transactionTimings:any[]=[],transactionTimingErrors:string[]=[],origins=new Set<string>(),cleanupEvents:any[]=[];
 const click=(page:Page,name:string)=>{const pending=owner.active(()=>page.getByRole('button',{name,exact:true}).click());void pending.catch(()=>{});return pending;};
 async function number(page:Page,name:string,value:string){const f=page.getByRole('spinbutton',{name,exact:true});await owner.active(()=>f.fill(value));await owner.active(()=>f.press('Tab'));}
 state.observe=()=>({transactionTimings,transactionTimingErrors,cleanupEvents,errors,csp,external,consoleErrors,consoleDiagnostics,network,commands,deliveries,deliveryErrors,states,restarts,paints,publications,runtime,closed,process:server?.lifecycle,requestLifecycle:guard?.requests??null,cleanup:guard?.ledger??null,ownerEvents:owner.events,deliveryObservation:{kind:'bounded-original-consumer-parse-return',scope:'Unique completed original reader text matched to actual parser return, or original native response.json completion; not UI model adoption or paint.'},limits:'Six distinct semantic states and four delivery identities only. Raw renderer events are uncorrelated diagnostics only: no status-paint association, renderer paint timing, presented/display timing, R04 pass or formal H4/I6H samples are claimed.'});
 state.finalCheck=async()=>{const checks:[string,()=>void][]=[['native-verify',()=>{if(!guard)throw Error('Native guard unavailable');guard.verify();}],['DOM-errors',()=>expect(errors).toEqual([])],['CSP',()=>expect(csp).toEqual([])],['external-requests',()=>expect(external).toEqual([])],['console-errors',()=>expect(consoleErrors).toEqual([])],['application-delivery-observer',()=>expect(deliveryErrors).toEqual([])],['transaction-timing-diagnostic',()=>{expect(transactionTimingErrors).toEqual([]);for(const snapshot of transactionTimings){expect(snapshot.errors).toEqual([]);expect(snapshot.dropped).toBe(0);expect(snapshot.phases.errors).toEqual([]);}}],['writer-closed-receipt',()=>expect(closed?.closed).toBe(true)],['writer-errors',()=>expect(closed?.errors).toEqual([])],['object-resources',()=>expect(closed?.resources.objects).toEqual({reservedBytes:'0',activeTransfers:0})],['raster-resources',()=>expect(closed?.resources.raster.activeWorkers).toBe(0)]];for(const [name,check] of checks)await boundedStep(state,name,1000,check);};

 async function collectDeliveries(scope:(work:()=>Promise<any>)=>Promise<any>=(work)=>owner.active(work)){const observed=await scope(()=>page.evaluate(()=>{const rows=(window as any).__p25Deliveries,errors=(window as any).__p25DeliveryErrors;if(!Array.isArray(rows)||!Array.isArray(errors))return {rows:[],errors:['E4_DELIVERY_OBSERVER_MISSING'],transactionTiming:undefined};const result={rows:rows.slice(),errors:errors.slice(),transactionTiming:(window as any).__p25TransactionTiming?.snapshot()};rows.length=0;errors.length=0;return result;}));deliveries.push(...observed.rows.map((delivery:any)=>({...delivery,application:true})));deliveryErrors.push(...observed.errors);if(transactionTimings.length>=8){if(transactionTimingErrors.length<8)transactionTimingErrors.push('E4_TRANSACTION_TIMING_SNAPSHOTS');}else if(!observed.transactionTiming){if(transactionTimingErrors.length<8)transactionTimingErrors.push('E4_TRANSACTION_TIMING_MISSING');}else transactionTimings.push(observed.transactionTiming);}

 owner.provide('raw-failure-retention',20000,()=>true,async(scope:any)=>{await scope(()=>mkdir(receipt,{recursive:true}));await scope(()=>writeFile(join(receipt,'e4-before-cleanup.json'),JSON.stringify({...state.observe?.() as object,failures:state.failures.map(f=>({phase:f.phase,error:String(f.error)}))},null,2)));if(state.failures.length&&root){await scope(()=>cp(root!,join(receipt,'failed-private-before-cleanup'),{recursive:true,errorOnExist:true,force:false}));cleanupEvents.push({event:'failed-private-copied',at:Date.now(),limit:'Live asynchronous copy; no atomic snapshot or consistency proof'});}});
 owner.provide('renderer-trace-close',5000,()=>browserName!=='chromium'||Boolean(trace),async(scope:any)=>{if(!trace)return;const done=new Promise<void>(r=>trace.once('Tracing.tracingComplete',()=>r()));await scope(()=>trace.send('Tracing.end'));await scope(()=>done);});
 owner.provide('logical-cleanup',30000,()=>Boolean(guard),async(scope:any)=>{if(!page.isClosed()&&new URL(page.url()).protocol!=='about:')await collectDeliveries(scope);for(const p of context.pages())await scope(()=>p.goto('about:blank'));await scope(()=>guard.cleanup());});
 owner.provide('writer-close',15000,()=>Boolean(owner.resources.server),async(scope:any)=>{server=owner.resources.server;await scope(()=>server.close());state.writerClosed=true;});
 owner.provide('writer-expiry-termination',1000,()=>true,()=>{server=owner.resources.server;if(server&&!state.writerClosed&&!server.lifecycle.exit){cleanupEvents.push({event:'owned-writer-termination',pid:server.pid,at:Date.now()});process.kill(server.pid,'SIGKILL');}const child=owner.resources.child;if(!state.writerClosed&&child&&child.exitCode===null&&child.signalCode===null){cleanupEvents.push({event:'owned-startup-child-termination',pid:child.pid,at:Date.now()});child.kill('SIGKILL');}});
 owner.provide('native-close-receipt',1000,()=>Boolean(root),async(scope:any)=>{closed=JSON.parse(await scope(()=>readFile(join(root!,'e4-fixture.json'),'utf8')));});

 owner.bodyPhase='body-setup';
 await owner.body(async()=>{
 guard=await owner.active(async()=>(ownedOPFS(context,'p25-e4')));errors=await owner.active(async()=>(recordDOMErrors(context)));dir=await owner.active(async()=>(owner.acquire('privateDir',async()=>mkdtemp(join(await owner.active(async()=>(realpath(tmpdir()))),'p25-e4-')))));state.roots.push(dir!);root=join(dir!,'private');

 await owner.active(async()=>(context.exposeBinding('e4CSP',(_s,v)=>csp.push(v))));await owner.active(async()=>(context.addInitScript(()=>addEventListener('securitypolicyviolation',e=>(window as any).e4CSP({directive:e.effectiveDirective,blocked:e.blockedURI})))));
 await owner.active(async()=>(context.addInitScript(installE4DeliveryObserver)));
 await owner.active(()=>context.addInitScript(installE4TransactionTiming));
 const safeURL=(raw:string)=>{try{const u=new URL(raw);return u.origin+u.pathname;}catch{return '';}};
 const requestIds=new WeakMap<object,number>();let requestSequence=0;const requestId=(r:object)=>{let id=requestIds.get(r);if(!id){id=++requestSequence;requestIds.set(r,id);}return id;};
 page.on('request',r=>network.push({event:'request',at:Date.now(),id:requestId(r),method:r.method(),url:safeURL(r.url()),resourceType:r.resourceType()}));
 page.on('response',r=>network.push({event:'response',at:Date.now(),id:requestId(r.request()),status:r.status(),url:safeURL(r.url()),resourceType:r.request().resourceType()}));
 page.on('requestfailed',r=>network.push({event:'failed',at:Date.now(),id:requestId(r),url:safeURL(r.url()),resourceType:r.resourceType(),error:r.failure()?.errorText??null}));
 page.on('console',m=>{const location=m.location();consoleDiagnostics.push({at:Date.now(),type:m.type(),text:m.text(),location:{...location,url:safeURL(location.url)}});if(m.type()==='error')consoleErrors.push(m.text());});page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/api/v1/commands'))commands.push({at:Date.now(),...JSON.parse(r.postData()!).command});});page.on('response',r=>{if(r.url().includes('/api/v1/queue')||r.url().includes('/candidates?'))void r.json().then(value=>deliveries.push({at:Date.now(),path:new URL(r.url()).pathname,value})).catch(()=>{});});
 await owner.active(async()=>(context.route('**/*',async route=>{try{const r=route.request(),u=new URL(r.url());if(['http:','https:'].includes(u.protocol)&&!origins.has(u.origin)){external.push(u.origin);await owner.active(async()=>(route.abort()));return;}if(r.method()==='POST'&&u.pathname==='/api/v1/commands'&&['QueueInference','CancelJob'].includes(JSON.parse(r.postData()!).command.body.type))await owner.active(async()=>(new Promise(r=>setTimeout(r,200))));await owner.active(async()=>(route.continue()));}catch(error){if(!owner.stopped)throw error;cleanupEvents.push({event:'expired-route-aborted',at:Date.now()});await route.abort().catch(()=>{});}})));
 async function read(path:string){return page.evaluate(async s=>{const r=await ((window as any).__p25OriginalFetch??fetch)(s.path,s.init);if(!r.ok)throw Error('Public read '+r.status);return r.json();},publicReadRequest(path));}
 async function gate(value:unknown){await owner.active(async()=>{
  const path=join(root!,'e4-gate.json'),temporary=join(root!,'.e4-gate-'+randomUUID()+'.tmp');
  await writeFile(temporary,JSON.stringify(value),{mode:0o600,flag:'wx'});
  await rename(temporary,path);
 });}
 async function boot(){owner.assertActive();owner.resources.server=undefined;server=await owner.active(async()=>(owner.acquire('server',()=>serverProcess(root!,child=>{owner.resources.child=child;}))));origins.add(server.origin);await owner.active(async()=>(guard.admit(page,server.origin)));await owner.active(async()=>(page.goto(await owner.active(async()=>(server.pair())))));await owner.active(async()=>(expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible()));}
 async function restart(job:any){const before=await owner.active(async()=>(server.effects()));await collectDeliveries();await owner.active(async()=>(page.goto('about:blank')));await owner.active(async()=>(server.kill()));restarts.push({before,lifecycle:server.lifecycle});await owner.active(async()=>(boot()));const reopened=await owner.active(async()=>(read('/api/v1/queue'))),same=reopened.jobs.find((j:any)=>j.id===job.id);expect(same.attempts.map((a:any)=>a.id)).toEqual(job.attempts.map((a:any)=>a.id));expect((await owner.active(async()=>(server.effects()))).effects).toEqual(before.effects);await owner.active(async()=>(click(page,'Open')));await owner.active(async()=>(page.getByRole('button',{name:new RegExp('^Restore '+job.review.draft.sessionId+' · document '+job.documentId+' · sequence ')}).click()));await owner.active(async()=>(expect(page.getByRole('dialog',{name:'Open document',exact:true})).toBeHidden()));await owner.active(async()=>(expect(page.getByRole('textbox',{name:'Prompt',exact:true})).toHaveValue(job.review.endpoint.endsWith('/fast')?'Fast uncertain Café 東京':'Known late Café 東京')));await owner.active(async()=>(click(page,'Refresh durable queue')));return same;}
 async function milestone(name:string,text:string,publication:string|null,job:any=null){await owner.active(async()=>(expect(page.getByText(text,{exact:false}).first()).toBeVisible()));const mark=await owner.active(async()=>(page.evaluate(name=>{performance.mark('p25.'+name);return {at:Date.now(),monotonic:performance.now()};},name)));const q=await owner.active(async()=>(read('/api/v1/queue')));states.push({name,...mark,text,publication,jobId:job?.id??q.jobs.at(-1)?.id,attemptId:job?.attempts[0]?.id??q.jobs.at(-1)?.attempts[0]?.id,queue:q,commandId:commands.at(-1)?.commandId,body:await owner.active(async()=>(page.locator('body').innerText()))});}
 async function create(prompt:string){await owner.active(async()=>(click(page,'New')));await owner.active(async()=>(number(page,'Width (px)','512')));await owner.active(async()=>(number(page,'Height (px)','512')));await owner.active(async()=>(click(page,'Create')));await owner.active(async()=>(expect(page.getByRole('dialog',{name:'New document',exact:true})).toBeHidden()));await owner.active(async()=>(number(page,'Output width','512')));await owner.active(async()=>(number(page,'Output height','512')));await owner.active(async()=>(page.getByRole('textbox',{name:'Prompt',exact:true}).fill(prompt)));}
 async function review(){await owner.active(async()=>(click(page,'Review exact request')));await owner.active(async()=>(expect(page.locator('#request-review')).toBeFocused()));await owner.active(async()=>(click(page,'Accept this exact review locally')));await owner.active(async()=>(expect(page.locator('#enqueue-request')).toBeEnabled()));}

  owner.bodyPhase='body';
  await owner.active(async()=>(mkdir(receipt,{recursive:true})));await owner.active(async()=>(boot()));Object.assign(runtime,{version:context.browser()?.version()??null,userAgent:await owner.active(async()=>(page.evaluate(()=>navigator.userAgent))),pin:JSON.parse(await owner.active(async()=>(readFile('node_modules/playwright-core/browsers.json','utf8')))).browsers.find((b:any)=>b.name===browserName)});
  if(browserName==='chromium'){trace=await owner.active(async()=>(context.newCDPSession(page)));trace.on('Tracing.dataCollected',({value}:any)=>{for(const e of value)if(e.name==='Paint'||e.name.startsWith('p25.'))paints.push({name:e.name,ts:e.ts,dur:e.dur,pid:e.pid,tid:e.tid});});await owner.active(async()=>(trace.send('Tracing.start',{categories:'devtools.timeline,blink.user_timing',transferMode:'ReportEvents'})));}
  await owner.active(async()=>(create('Known late Café 東京')));await owner.active(async()=>(review()));const pending=click(page,'Enqueue accepted request');await owner.active(async()=>(milestone('F1','Saving request…',null)));await owner.active(async()=>(pending));let known:any;await owner.active(async()=>(expect.poll(async()=>{known=(await owner.active(async()=>(read('/api/v1/queue')))).jobs[0];return known?.attempts[0].state;}).toBe('dispatching')));await owner.active(async()=>(milestone('F2','dispatching','P1',known)));states[0].jobId=known.id;states[0].attemptId=known.attempts[0].id;states[0].identityLinkedAfterReceipt=true;await owner.active(async()=>(expect.poll(async()=>((await owner.active(async()=>(read('/api/v1/queue')))).jobs[0]).attempts[0].state).toBe('acknowledged')));
  known=await owner.active(async()=>(restart(known)));await owner.active(async()=>(expect(page.locator('#durable-queue')).toContainText('Recovery is paused after restart')));await owner.active(async()=>(click(page,'Check existing request '+known.attempts[0].id)));await owner.active(async()=>(expect(page.locator('#durable-queue')).not.toContainText('Recovery is paused after restart')));await owner.active(async()=>(expect(page.locator('#durable-queue')).toHaveAttribute('aria-busy','false')));await owner.active(async()=>(expect(page.getByRole('button',{name:'Request cancellation '+known.attempts[0].id,exact:true})).toBeEnabled()));
  const cancelling=click(page,'Request cancellation '+known.attempts[0].id);await owner.active(async()=>(milestone('F3','Saving cancellation request…',null,known)));await owner.active(async()=>(cancelling));await owner.active(async()=>(milestone('F4','Cancellation requested; work may still finish.','P2',known)));expect(commands.filter(c=>c.body.type==='CancelJob')).toHaveLength(1);await owner.active(async()=>(expect.poll(async()=>((await owner.active(async()=>(read('/api/v1/queue')))).jobs.find((j:any)=>j.id===known.id)).attempts[0].cancel).toBe('acknowledged')));
  await owner.active(async()=>(gate({status:'COMPLETED',image:false,uncertain:false})));await owner.active(async()=>(milestone('F5','Late result available; retrieving and verifying owned image bytes.','P3',known)));await owner.active(async()=>(gate({status:'COMPLETED',image:true,uncertain:false})));await owner.active(async()=>(milestone('F6','Output 1: prepared','P4',known)));
  const prompt=page.getByRole('textbox',{name:'Prompt',exact:true});await owner.active(async()=>(prompt.focus()));await owner.active(async()=>(expect(prompt).toBeFocused()));expect((await owner.active(async()=>(read('/api/v1/documents/'+known.documentId)))).projection.value.revision).toBe('1');await owner.active(async()=>(click(page,'Undo pending request')));await owner.active(async()=>(expect(page.locator('#durable-queue')).toContainText('suppressed-by-undo')));await owner.active(async()=>(click(page,'Redo pending request without resubmitting')));await owner.active(async()=>(expect(page.locator('#durable-queue')).toContainText('set-aside')));expect((await owner.active(async()=>(server.effects()))).effects.filter((e:any)=>e.method==='POST')).toHaveLength(1);
  await owner.active(async()=>(click(page,'Review document deletion')));const deletion=page.getByRole('region',{name:'Document deletion',exact:true});await owner.active(async()=>(expect(deletion).toContainText('Normal Undo cannot restore it')));await owner.active(async()=>(expect(deletion.getByRole('button',{name:'Save a complete copy first',exact:true})).toBeVisible()));const confirm=deletion.getByRole('button',{name:'Confirm permanent document deletion',exact:true});await owner.active(async()=>(confirm.evaluate(el=>el.addEventListener('click',e=>e.preventDefault(),{once:true}))));await owner.active(async()=>(confirm.click()));expect(commands.filter(c=>c.body.type==='DeleteDocument')).toHaveLength(0);await owner.active(async()=>(confirm.focus()));await owner.active(async()=>(confirm.press('Enter')));await owner.active(async()=>(expect(deletion).toContainText('Document deleted; cleanup pending')));await owner.active(async()=>(click(page,'Check and reclaim eligible bytes')));await owner.active(async()=>(expect(deletion).toContainText('Actual freed local backend bytes:')));expect((await owner.active(async()=>(read('/api/v1/deletions')))).items.some((r:any)=>r.documentId===known.documentId)).toBe(true);
  await owner.active(async()=>(gate({status:'IN_PROGRESS',image:false,uncertain:true})));await owner.active(async()=>(create('Fast uncertain Café 東京')));await owner.active(async()=>(page.getByRole('combobox',{name:'Operation',exact:true}).selectOption('Generate with Fast')));await owner.active(async()=>(click(page,'Keep acceleration inactive in this draft')));await owner.active(async()=>(expect(page.getByText('acceleration is confirmed inactive for this operation.',{exact:true})).toBeVisible()));await owner.active(async()=>(review()));await owner.active(async()=>(click(page,'Enqueue accepted request')));let uncertain:any;await owner.active(async()=>(expect.poll(async()=>{uncertain=(await owner.active(async()=>(read('/api/v1/queue')))).jobs.find((j:any)=>j.review.endpoint==='ideogram/v4/fast');return uncertain?.attempts[0].state;}).toBe('submission-uncertain')));uncertain=await owner.active(async()=>(restart(uncertain)));await owner.active(async()=>(expect(page.locator('#durable-queue')).toContainText('submission-uncertain')));await owner.active(async()=>(click(page,'Check existing request '+uncertain.attempts[0].id)));await owner.active(async()=>(expect(page.locator('#durable-queue')).toContainText('No validated acknowledgement found')));expect((await owner.active(async()=>(server.effects()))).effects.filter((e:any)=>e.method==='POST')).toHaveLength(2);expect((await owner.active(async()=>(read('/api/v1/queue')))).jobs.find((j:any)=>j.id===uncertain.id).attempts).toHaveLength(1);
  await owner.active(async()=>(click(page,'Review document deletion')));await owner.active(async()=>(expect(deletion).toContainText('may still run or be charged')));await owner.active(async()=>(click(page,'Acknowledge running work and delete document')));await owner.active(async()=>(expect(deletion).toContainText('A remote slot remains held')));await owner.active(async()=>(click(page,'Check and reclaim eligible bytes')));await owner.active(async()=>(expect(deletion).toContainText('Document cleanup complete.')));await owner.active(async()=>(expect(deletion).toHaveAttribute('aria-busy','false')));await owner.active(async()=>(expect(deletion.getByRole('button',{name:'Review possible overlap for deleted request',exact:true})).toBeEnabled()));await owner.active(async()=>(click(page,'Review possible overlap for deleted request')));await owner.active(async()=>(expect(deletion).toContainText('does not cancel, refund or erase it')));await owner.active(async()=>(expect(deletion.locator('en-alert[role="status"]')).toHaveText('Review the overlap and charge risk below. No hold has been released.')));await owner.active(async()=>(expect(deletion).toHaveAttribute('aria-busy','false')));await owner.active(async()=>(click(page,'Acknowledge overlap and release deleted request hold')));await owner.active(async()=>(expect(deletion).toContainText('No local slot remains held')));
  await collectDeliveries();await owner.active(async()=>(page.reload()));await owner.active(async()=>(expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible()));await owner.active(async()=>(click(page,'Review pending document cleanup')));await owner.active(async()=>(click(page,'Inspect cleanup for '+uncertain.documentId)));await owner.active(async()=>(expect(deletion).toContainText('Actual freed local backend bytes')));await owner.active(async()=>(expect(deletion.locator('en-alert[role="status"]')).toHaveText('Receipt inspected: document cleanup is complete. Remote work and charges remain unconfirmed.')));await owner.active(async()=>(expect(deletion).toHaveAttribute('aria-busy','false')));expect((await owner.active(async()=>(read('/api/v1/deletions')))).items).toHaveLength(2);const effects=await owner.active(async()=>(server.effects()));expect(effects.errors).toEqual([]);expect(effects.effects.filter((e:any)=>e.method==='POST').map((e:any)=>e.path)).toEqual(['/ideogram/v4','/ideogram/v4/fast']);expect(effects.effects.filter((e:any)=>e.path.endsWith('/cancel'))).toHaveLength(1);
  await collectDeliveries();const authority=(await owner.active(async()=>(server.effects()))).milestones;const browserDeliveries=deliveries.filter(d=>d.application===true);for(const phase of ['P1','P2','P3','P4']){const a=authority.find((a:any)=>a.phase===phase&&(a.job?.id??a.jobId)===known.id);expect(a,'Committed authority '+phase).toBeTruthy();const d=browserDeliveries.find(d=>d.at>=a.at&&(phase==='P1'?d.value.jobs?.some((j:any)=>j.id===known.id&&j.version===a.job.version):phase==='P2'?d.value.receipt?.commandId===a.commandId&&d.value.receipt?.toSeq===a.receipt.toSeq:d.value.jobId===known.id&&d.value.items!==undefined&&(phase==='P3'?d.value.observation?.digest===a.view.observation.digest&&!d.value.items.some((c:any)=>c.state==='prepared'):d.value.items.some((c:any)=>c.id===a.candidate.id&&c.version===a.candidate.version&&c.preparedAssetId===a.candidate.preparedAssetId))));expect(d,'Actual application delivery '+phase).toBeTruthy();expect(d.at-a.at,'Observed '+phase+' publication allowance').toBeLessThanOrEqual(250);publications.push({phase,authority:a,delivery:d,intervalMs:d.at-a.at,clockUncertainty:'Same-host wall clocks, 1 ms resolution; software observation after commit, not hardware presentation'});}const available=authority.find((a:any)=>a.phase==='availability'),retrieval=effects.effects.find((e:any)=>e.path.startsWith('/image/'));expect(available).toBeTruthy();expect(retrieval).toBeTruthy();expect(retrieval.at-available.at).toBeGreaterThanOrEqual(0);expect(retrieval.at-available.at).toBeLessThanOrEqual(3000);runtime.retrievalStart={availabilityAt:available.at,startAt:retrieval.at,intervalMs:retrieval.at-available.at};runtime.semanticTraceUnionMs=states.at(-1).at-states[0].at;expect(publications[0].authority.commandId).toBe(states[0].commandId);expect(states.find(s=>s.name==='F3').at,'F3 precedes cancellation acknowledgement').toBeLessThan(publications.find(p=>p.phase==='P2').authority.at);expect(states.map(s=>s.name)).toEqual(['F1','F2','F3','F4','F5','F6']);expect(states.filter(s=>s.publication).map(s=>s.publication)).toEqual(['P1','P2','P3','P4']);expect(new Set(states.map(s=>s.jobId))).toEqual(new Set([known.id]));expect(new Set(states.map(s=>s.attemptId))).toEqual(new Set([known.attempts[0].id]));
  await owner.active(async()=>(page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'})));await owner.active(async()=>(page.setViewportSize({width:320,height:900})));await owner.active(async()=>(deletion.scrollIntoViewIfNeeded()));const geometry=await owner.active(async()=>(deletion.evaluate(el=>({width:el.getBoundingClientRect().width,scroll:el.scrollWidth}))));expect(geometry.scroll).toBeLessThanOrEqual(geometry.width+1);await owner.active(async()=>(deletion.getByRole('button',{name:'Review pending document cleanup',exact:true}).focus()));await owner.active(async()=>(expect(deletion.getByRole('button',{name:'Review pending document cleanup',exact:true})).toBeFocused()));if(browserName!=='webkit')await owner.active(async()=>(page.screenshot({path:join(receipt,'deletion-narrow.png'),caret:'initial'})));

 });
});
