// The fixture owns this object before any fallible acquisition. Only teardown
// runs cleanup; a runner timeout stops continuations, not the underlying Promise.
export class FixtureOwner {
 constructor(state){this.state=state;this.resources={};this.stopped=false;this.steps=[];this.events=[];this.teardownBudgetMs=130000;this.pending=new Set();this.done=undefined;}
 assertActive(){if(this.stopped)throw Error('FUNCTIONAL_WORK_EXPIRED');}
 async active(work){this.assertActive();const token={};this.pending.add(token);try{const value=await work();this.assertActive();return value;}finally{this.pending.delete(token);}}
 async acquire(name,work){return this.active(async()=>{const value=await work();this.resources[name]=value;this.events.push({event:'acquired',name,at:Date.now(),afterStop:this.stopped});return value;});}
 add(phase,ms,available,work,order=0){if(this.stopped)throw Error('Cannot add teardown after stop');this.steps.push({phase,ms,available,work,order});}
 provide(phase,ms,available,work){const previous=this.steps.findIndex(step=>step.phase===phase);if(previous<0)throw Error('Unknown teardown phase: '+phase);if(this.stopped)throw Error('Cannot provide teardown after stop');this.steps[previous]={phase,ms,available,work,order:0};}
 async body(work){this.events.push({event:'body-start',at:Date.now()});try{return await work();}catch(error){this.state.failures.push({phase:this.stopped?'late-body':(this.bodyPhase??'body'),error});throw error;}finally{this.events.push({event:'body-settled',at:Date.now(),afterStop:this.stopped});}}
 stop(){if(!this.stopped){this.stopped=true;this.events.push({event:'functional-stop',at:Date.now(),pending:this.pending.size});}}
 teardown(){if(this.done)return this.done;this.stop();this.done=this.finish();return this.done;}
 async finish(){const deadline=performance.now()+this.teardownBudgetMs;for(const step of this.steps.sort((a,b)=>a.order-b.order)){const row={phase:step.phase,start:Date.now(),limitMs:step.ms};(this.state.timingCleanup??=[]).push(row);if(!step.available()){row.unavailable=true;row.end=Date.now();this.state.failures.push({phase:step.phase,error:Error('Required teardown resource unavailable')});continue;}const remaining=deadline-performance.now();if(remaining<=0&&step.phase!=='final-receipt'){row.expiredBeforeStart=true;row.end=Date.now();this.state.failures.push({phase:step.phase,error:Error('Teardown budget exhausted before phase')});continue;}const limit=Math.min(step.ms,step.phase==='final-receipt'?1000:remaining);let timer,live=true;const scope=async work=>{if(!live)throw Error('CLEANUP_PHASE_EXPIRED');const value=await work();if(!live)throw Error('CLEANUP_PHASE_EXPIRED');return value;};try{await Promise.race([Promise.resolve().then(()=>step.work(scope)),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error(step.phase+' deadline')),limit);})]);row.passed=true;}catch(error){row.error=String(error);this.state.failures.push({phase:step.phase,error});}finally{live=false;clearTimeout(timer);row.end=Date.now();}}this.events.push({event:'teardown-settled',at:Date.now(),pending:this.pending.size});}
}
export async function ownedFixture(owner,setup,use){let setupComplete=false;try{await setup();setupComplete=true;await use();}catch(error){if(!setupComplete)owner.state.failures.push({phase:'fixture-setup',error});throw error;}finally{await owner.teardown();}}
