import test from 'node:test';import assert from 'node:assert/strict';import {FixtureOwner,ownedFixture} from './fixture-owner.mjs';
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
function fixture(){const state={failures:[]},owner=new FixtureOwner(state),events=[];owner.add('native',100,()=>!!owner.resources.guard,async()=>events.push('native'));owner.add('context',100,()=>!!owner.resources.context,async()=>{events.push('context');await owner.resources.context.close();});owner.add('browser',100,()=>!!owner.resources.browser,async()=>{events.push('browser');await owner.resources.browser.close();});return {state,owner,events};}
const resource=()=>({closed:0,async close(){this.closed++;}});
for(const failed of ['context','initial-page','guard'])test('actual fixture owner retains acquired resources on '+failed+' setup failure',async()=>{const f=fixture(),browser=resource(),context=resource();let body=false;await assert.rejects(ownedFixture(f.owner,async()=>{await f.owner.acquire('browser',async()=>browser);if(failed==='context')throw Error(failed);await f.owner.acquire('context',async()=>context);if(failed==='initial-page')await f.owner.active(async()=>{throw Error(failed);});await f.owner.active(async()=>{throw Error('guard');});},async()=>{body=true;}));assert.equal(body,false);assert.equal(browser.closed,1);assert.equal(context.closed,failed==='context'?0:1);assert.equal(f.state.failures.filter(x=>x.phase==='fixture-setup').length,1);assert.equal(f.state.timingCleanup.find(x=>x.phase==='native').unavailable,true);assert.equal(f.state.timingCleanup.find(x=>x.phase==='native').passed,undefined);await f.owner.teardown();assert.equal(browser.closed,1);});
test('runner timeout hands off to fixture owner and late body resolution cannot resume functional actions',async()=>{const f=fixture(),held=deferred(),entered=deferred(),browser=resource(),context=resource();let functional=0,body;await assert.rejects(ownedFixture(f.owner,async()=>{await f.owner.acquire('browser',async()=>browser);await f.owner.acquire('context',async()=>context);},async()=>{body=f.owner.body(async()=>{entered.resolve();await f.owner.active(()=>held.promise);await f.owner.active(async()=>functional++);});await entered.promise;await Promise.race([body,new Promise((_,reject)=>setTimeout(()=>reject(Error('runner body budget')),5))]);}),/runner body budget/);assert.equal(browser.closed,1);assert.equal(context.closed,1);assert.equal(f.owner.pending.size,1);const again=f.owner.teardown();assert.equal(again,f.owner.teardown());held.resolve();await assert.rejects(body,/WORK_EXPIRED/);await again;assert.equal(functional,0);assert.equal(f.state.failures.at(-1).phase,'late-body');assert.equal(f.events.filter(x=>x==='browser').length,1);});
test('late assertion failure is retained separately after runner timeout',async()=>{const f=fixture(),held=deferred();let body;await assert.rejects(ownedFixture(f.owner,async()=>{await f.owner.acquire('browser',async()=>resource());},async()=>{body=f.owner.body(async()=>{await f.owner.active(()=>held.promise);});await Promise.race([body,new Promise((_,reject)=>setTimeout(()=>reject(Error('runner timeout')),5))]);}));held.reject(Error('late original assertion'));await assert.rejects(body,/late original assertion/);assert.equal(f.state.failures.at(-1).phase,'late-body');assert.match(String(f.state.failures.at(-1).error),/late original assertion/);});
test('cleanup rejection and expiry preserve later closure without resuming expired phase',async()=>{const f=fixture(),held=deferred();let resumed=0;f.owner.steps=[];f.owner.add('native',5,()=>true,async scope=>{await scope(()=>held.promise);resumed++;});f.owner.add('writer',100,()=>true,async()=>{throw Error('writer close rejected');});f.owner.add('browser',100,()=>true,async()=>{f.events.push('browser');});await ownedFixture(f.owner,async()=>{},async()=>{});assert.deepEqual(f.state.failures.map(x=>x.phase),['native','writer']);assert.deepEqual(f.events,['browser']);held.resolve();await new Promise(r=>setTimeout(r,0));assert.equal(resumed,0);await f.owner.teardown();assert.deepEqual(f.events,['browser']);});
test('global teardown budget labels unstarted phase and still retains final receipt',async()=>{const f=fixture(),held=deferred();f.owner.steps=[];f.owner.teardownBudgetMs=0;f.owner.add('native',100,()=>true,()=>held.promise);f.owner.add('archive',100,()=>true,async()=>{throw Error('must not run');});let receipt=false;f.owner.add('final-receipt',1000,()=>true,async()=>{receipt=true;});await ownedFixture(f.owner,async()=>{},async()=>{});assert.equal(receipt,true);assert.equal(f.state.timingCleanup.find(x=>x.phase==='archive').expiredBeforeStart,true);held.resolve();});

test('predeclared unavailable phases remain explicit until body provides owned handles',async()=>{const state={failures:[]},owner=new FixtureOwner(state);owner.add('native',100,()=>false,()=>assert.fail('unavailable work'));owner.add('writer',100,()=>false,()=>assert.fail('unavailable work'));let calls=0;owner.provide('writer',100,()=>true,async()=>calls++);owner.bodyPhase='body-setup';await assert.rejects(owner.body(async()=>{throw Error('guard initialization');}));await owner.teardown();assert.equal(calls,1);assert.equal(state.failures[0].phase,'body-setup');assert.equal(state.timingCleanup.find(x=>x.phase==='native').unavailable,true);assert.equal(state.timingCleanup.find(x=>x.phase==='writer').passed,true);});
