import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {once} from 'node:events';import {join} from 'node:path';
import {fixture,prepare,enqueue,auth,encode,envelope} from '../queue/helpers.mjs';import {StoreDatabase} from '../../dist/local/server/storage/database.js';import {acquireRoot} from '../../dist/local/server/storage/ownership.js';import {QueueDispatcher} from '../../dist/local/server/provider/dispatcher.js';import {ResultObserver} from '../../dist/local/server/provider/observer.js';import {emulator,fixtureProfile} from '../provider/emulator.mjs';import sharp from 'sharp';
async function setup(t,withSource=false){const clean=[],f=await fixture({name:t.name,after:f=>clean.push(f)});const q=await enqueue(f.writer,(withSource?await sourceReview(f.writer):await prepare(f.writer)).body);await f.close();const owner=await acquireRoot(f.root),db=new StoreDatabase(f.root,()=>{}),effects=[],controls={status:'IN_PROGRESS',hold:null,uploadHold:null,statusHold:null,resultHold:null,cancelHold:null,outputs:1},png=await sharp({create:{width:512,height:512,channels:4,background:'#2468ac'}}).png().toBuffer();let origin='';const server=createServer(async(req,res)=>{const body=Buffer.concat(await Array.fromAsync(req));effects.push({method:req.method,path:req.url,bytes:body.length});res.setHeader('Content-Type','application/json');if(req.url==='/upload'){if(controls.uploadHold)await controls.uploadHold;res.end(JSON.stringify({url:origin+'/uploaded-source'}));}else if(req.url.endsWith('/cancel')){if(controls.cancelHold)await controls.cancelHold;res.statusCode=202;res.end('{}');}else if(req.method==='POST'){const base=origin+'/ideogram/v4/requests/known';res.end(JSON.stringify({request_id:'known',status_url:base+'/status',response_url:base,cancel_url:base+'/cancel'}));}else if(req.url.endsWith('/status')){if(controls.statusHold)await controls.statusHold;res.end(JSON.stringify({request_id:'known',status:controls.status}));}else if(req.url==='/image'){if(controls.hold)await controls.hold;res.setHeader('Content-Type','image/png');res.end(png);}else{if(controls.resultHold)await controls.resultHold;res.end(JSON.stringify({images:Array.from({length:controls.outputs},()=>({url:origin+'/image',width:512,height:512})),prompt:'Late exact Café 東京',seed:4,timings:{},has_nsfw_concepts:Array.from({length:controls.outputs},()=>false)}));}});server.listen(0,'127.0.0.1');await once(server,'listening');origin='http://127.0.0.1:'+server.address().port;const provider=emulator({queueOrigin:origin,mediaOrigin:origin,uploadOrigin:origin,profiles:[fixtureProfile({endpoint:q.job.review.endpoint})]}),dispatcher=new QueueDispatcher(db.queue,provider,{queueOrigin:origin,mediaOrigin:origin,uploadURL:origin+'/upload',profileId:'local-fixture-v1'}),observer=new ResultObserver(db.candidates,provider,dispatcher,'local-fixture-v1');t.after(async()=>{observer.close();await db.candidates.close();await db.queue.close();await db.portables.close();await db.histories.close();await db.rasters.close();await db.assets.close();await db.recovery.settle();db.close();owner.close();await new Promise(r=>server.close(r));for(const c of clean)await c();});return {db,dispatcher,observer,effects,q,controls,provider,origin};}
const send=(db,body)=>db.queue.command(encode(envelope(body)),auth());
async function sourceReview(writer){
 const {readFile}=await import('node:fs/promises'),{randomUUID,createHash}=await import('node:crypto');
 const bytes=await readFile('tests/raster/fixtures/hidden-alpha.png'),sha256='sha256:'+createHash('sha256').update(bytes).digest('hex'),stagingId=randomUUID(),a=auth();
 await writer.assetCreate({protocolVersion:1,stagingId,purpose:'image',expectedBytes:String(bytes.length),sha256,mediaType:'image/png'},a);const token=await writer.assetBeginChunk(stagingId,'0',bytes.length,a);await writer.assetChunk(token,bytes,a);
 async function finish(body,method){const c=envelope(body);await writer[method](encode(c),a);let r;for(let n=0;n<1000;n++){r=await writer.lookup(c.command.commandId);if(r)break;await new Promise(resolve=>setTimeout(resolve,5));}assert.equal(r?.receipt.status,'accepted',JSON.stringify(r));return (await writer.events(String(BigInt(r.receipt.fromSeq)-1n))).events.find(e=>e.commandId===c.command.commandId).payload;}
 const original=(await finish({type:'FinalizeStaging',stagingId,expectedSha256:sha256},'assetCommand')).asset,preview=(await finish({type:'PrepareRaster',assetId:original.id},'rasterCommand')).asset,reviewId=(await finish({type:'ReviewRaster',assetId:preview.id},'rasterCommand')).reviewId,review=await writer.rasterReview(reviewId,a),asset=(await finish({type:'ApproveRaster',assetId:preview.id,reviewId,reviewHash:review.reviewHash},'rasterCommand')).asset;
 return prepare(writer,d=>{d.operation='transform';d.source={assetId:asset.id,version:asset.version,blob:asset.blob,pixels:asset.raster.pixels,width:3,height:2,scope:'asset',documentRevision:'1'};d.fields.width='6';d.fields.height='4';d.fields.strength='0.8';d.conversion={from:{width:3,height:2},to:{width:6,height:4},mapping:'stretch',approved:true};});
}
for(const type of ['CancelJob','UndoPendingJob','DeleteDocument'])test(type+' during held source upload finishes locally without inference dispatch',async t=>{
 const x=await setup(t,true);assert.equal(x.q.job.stagePlan.length,1);let release;x.controls.uploadHold=new Promise(r=>release=r);const running=x.dispatcher.submit(x.q.job.id);void running.catch(()=>{});
 try{for(let n=0;!x.effects.some(e=>e.path==='/upload')&&n<200;n++)await new Promise(r=>setTimeout(r,10));assert(x.effects.some(e=>e.path==='/upload'));const j=x.db.queue.view().jobs[0];assert.equal(j.attempts[0].count,'reserved');
  if(type==='DeleteDocument')await remove(x.db);else assert.equal((await send(x.db,{type,jobId:j.id,attemptId:j.attempts[0].id,expectedVersion:j.version})).status,'accepted');release();assert.equal(await running,null);
  const after=x.db.queue.view().jobs[0];assert.equal(after.attempts[0].state,'locally-cancelled');assert.equal(after.attempts[0].count,'released');assert.equal(after.attempts[0].hold,false);assert.deepEqual(x.effects.map(e=>[e.method,e.path]),[['POST','/upload']]);assert.equal(x.db.objects.reservationInventory().activeTransfers,0);
 }finally{release();await running;}
});
for(const type of ['CancelJob','UndoPendingJob'])test(type+' during held batch media preserves all outputs and an explicit same-output retry without new inference',async t=>{
 const x=await setup(t);await x.dispatcher.submit(x.q.job.id);let release;x.controls.hold=new Promise(r=>release=r);x.controls.status='COMPLETED';x.controls.outputs=2;const running=x.observer.tick();void running.catch(()=>{});
 try{for(let n=0;!x.effects.some(e=>e.path==='/image')&&n<200;n++)await new Promise(r=>setTimeout(r,10));assert(x.effects.some(e=>e.path==='/image'));const j=x.db.queue.view().jobs[0],before=x.db.candidates.view(j.id).items[0];assert.equal(before.state,'received');
  const stale=await send(x.db,{type,jobId:j.id,attemptId:j.attempts[0].id,expectedVersion:'0'});assert.equal(stale.status,'rejected');assert.equal(stale.code,'STALE_REVISION');const accepted=await send(x.db,{type,jobId:j.id,attemptId:j.attempts[0].id,expectedVersion:j.version});assert.equal(accepted.status,'accepted');release();await running;
  const failed=x.db.candidates.view(j.id).items[0];assert.equal(failed.id,before.id);assert.equal(failed.state,'transfer-failed');assert.equal(x.db.objects.reservationInventory().activeTransfers,0);assert.equal(x.effects.filter(e=>e.path==='/image').length,2);assert.equal(x.db.candidates.view(j.id).items[1].state,'prepared');
  const retry=await send(x.db,{type:'RetryCandidateImport',candidateId:failed.id,expectedVersion:failed.version});assert.equal(retry.status,'accepted');await x.observer.tick(Date.now()+9000);
  const after=x.db.candidates.view(j.id).items[0];assert.equal(after.id,before.id);assert.equal(after.state,'prepared');assert.equal(x.db.document('document_1').revision,'1');assert.equal(x.db.queue.view().jobs[0].disposition,type==='CancelJob'?'cancel-requested':'suppressed-by-undo');assert.equal(x.effects.filter(e=>e.method==='POST').length,1);assert.equal(x.effects.filter(e=>e.path==='/image').length,3);assert.equal(x.db.candidates.view(j.id).items.length,2);
 }finally{release();await running;}
});
async function remove(db,ack=true){await send(db,{type:'PreviewDocumentDeletion',documentId:'document_1',expectedRevision:'1'});const p=db.deletions.view('document_1',auth()).plan;const receipt=await send(db,{type:'DeleteDocument',documentId:p.documentId,planId:p.id,planHash:p.planHash,rootGeneration:p.rootGeneration,expectedRevision:p.documentRevision,acknowledgeRunningAndUncertain:ack});assert.equal(receipt.status,'accepted',JSON.stringify(receipt));}
for(const type of ['UndoPendingJob','DeleteDocument'])test(type+' during cancel acknowledgement retains control evidence without duplicate effects',async t=>{
 const x=await setup(t);await x.dispatcher.submit(x.q.job.id);let j=x.db.queue.view().jobs[0];assert.equal((await send(x.db,{type:'CancelJob',jobId:j.id,attemptId:j.attempts[0].id,expectedVersion:j.version})).status,'accepted');let release;x.controls.cancelHold=new Promise(r=>release=r);const running=x.observer.tick();void running.catch(()=>{});
 try{for(let n=0;!x.effects.some(e=>e.path.endsWith('/cancel'))&&n<200;n++)await new Promise(r=>setTimeout(r,10));assert(x.effects.some(e=>e.path.endsWith('/cancel')));j=x.db.queue.view().jobs[0];if(type==='DeleteDocument')await remove(x.db);else assert.equal((await send(x.db,{type,jobId:j.id,attemptId:j.attempts[0].id,expectedVersion:j.version})).status,'accepted');release();await running;await x.observer.tick(Date.now()+3000);assert.equal(x.effects.filter(e=>e.path.endsWith('/cancel')).length,1);assert.equal(x.effects.filter(e=>e.method==='POST').length,1);const after=x.db.queue.view().jobs[0];assert.equal(after.disposition,type==='DeleteDocument'?'deleted':'suppressed-by-undo');if(type==='DeleteDocument'){assert.equal(after.attempts[0].recoveryRequired,true);assert.equal(x.db.document('document_1'),null);}else assert.equal(after.attempts[0].cancel,'acknowledged');assert.equal(x.db.objects.reservationInventory().activeTransfers,0);
 }finally{release();await running;}
});
test('repeated explicit detached recovery during held status retains one identity and releases only a confirmed terminal hold',async t=>{
 const x=await setup(t);await x.dispatcher.submit(x.q.job.id);await remove(x.db);let j=x.db.queue.view().jobs[0];assert.equal((await send(x.db,{type:'RecoverJob',jobId:j.id,attemptId:j.attempts[0].id,expectedVersion:j.version})).status,'accepted');x.controls.status='COMPLETED';let release;x.controls.statusHold=new Promise(r=>release=r);const running=x.observer.tick();void running.catch(()=>{});
 try{for(let n=0;!x.effects.some(e=>e.path.endsWith('/status'))&&n<200;n++)await new Promise(r=>setTimeout(r,10));assert(x.effects.some(e=>e.path.endsWith('/status')));j=x.db.queue.view().jobs[0];assert.equal(j.attempts[0].hold,true);assert.equal((await send(x.db,{type:'RecoverJob',jobId:j.id,attemptId:j.attempts[0].id,expectedVersion:j.version})).status,'accepted');release();await running;const after=x.db.queue.view().jobs[0];assert.equal(after.attempts.length,1);assert.equal(after.attempts[0].hold,false);assert.equal(after.attempts[0].terminal,'completed');assert.equal(x.effects.filter(e=>e.path==='/image').length,0);assert.equal(x.effects.filter(e=>e.method==='POST').length,1);
 }finally{release();await running;}
});
for(const hold of ['statusHold','resultHold'])for(const type of ['CancelJob','DeleteDocument'])test(type+' during '+hold+' preserves identity and respects deletion before media retrieval',async t=>{
 const x=await setup(t);await x.dispatcher.submit(x.q.job.id);x.controls.status='COMPLETED';let release;x.controls[hold]=new Promise(r=>release=r);const running=x.observer.tick();void running.catch(()=>{});
 try{const observed=()=>x.effects.some(e=>e.method==='GET'&&(hold==='statusHold'?e.path.endsWith('/status'):e.path==='/ideogram/v4/requests/known'));for(let n=0;!observed()&&n<200;n++)await new Promise(r=>setTimeout(r,10));assert(observed());const j=x.db.queue.view().jobs[0];
  if(type==='DeleteDocument')await remove(x.db);else assert.equal((await send(x.db,{type,jobId:j.id,attemptId:j.attempts[0].id,expectedVersion:j.version})).status,'accepted');release();await running;
  assert.equal(x.db.queue.view().jobs[0].attempts.length,1);assert.equal(x.effects.filter(e=>e.method==='POST').length,1);assert.equal(x.db.objects.reservationInventory().activeTransfers,0);
  if(type==='DeleteDocument'){assert.equal(x.db.document('document_1'),null);assert.equal(x.effects.filter(e=>e.path==='/image').length,0);assert.equal(x.db.db.prepare('SELECT count(*) n FROM candidates').get().n,0);}else{assert.equal(x.db.candidates.view(j.id).items[0].state,'prepared');assert.equal(x.db.document('document_1').revision,'1');assert.equal(x.db.queue.view().jobs[0].disposition,'cancel-requested');}
 }finally{release();await running;}
});
test('202 cancellation is not stopped; late completion retains one candidate and no adoption',async t=>{const x=await setup(t);await x.dispatcher.submit(x.q.job.id);let j=x.db.queue.view().jobs[0];await send(x.db,{type:'CancelJob',jobId:j.id,attemptId:j.attempts[0].id,expectedVersion:j.version});await x.observer.tick();j=x.db.queue.view().jobs[0];assert.equal(j.attempts[0].cancel,'acknowledged');assert.equal(j.attempts[0].hold,true);x.controls.status='COMPLETED';await x.observer.tick(Date.now()+3000);const v=x.db.candidates.view(j.id);assert.equal(v.items.length,1);assert.equal(v.items[0].state,'prepared');assert.equal(x.db.document('document_1').revision,'1');assert.equal(x.db.queue.view().jobs[0].disposition,'cancel-requested');await x.observer.tick(Date.now()+9000);assert.equal(x.effects.filter(e=>e.method==='POST').length,1);assert.equal(x.effects.filter(e=>e.path.endsWith('/cancel')).length,1);});
test('confirmed cancellation followed by contradictory completion quarantines rather than flipping terminal success',async t=>{const x=await setup(t);await x.dispatcher.submit(x.q.job.id);x.controls.status='CANCELLED';await x.observer.tick();const j=x.db.queue.view().jobs[0];assert.equal(j.attempts[0].cancel,'confirmed');assert.equal(j.attempts[0].hold,false);x.controls.status='COMPLETED';const f=x.db.queue.resultFence(j.id,j.attempts[0].id),r=await x.dispatcher.readKnown(j.id,f.attemptId,'status');x.db.candidates.observe(f,r.evidence,Date.now());assert.equal(x.db.candidates.view(j.id).observation.phase,'quarantined');assert.equal(x.db.queue.view().jobs[0].attempts[0].terminal,'cancelled');});
test('delete known work prevents result fetch and publication but permits explicitly initiated status reconciliation',async t=>{const x=await setup(t);await x.dispatcher.submit(x.q.job.id);await remove(x.db);const before=x.effects.length;await x.observer.tick();assert.equal(x.effects.length,before);let j=x.db.queue.view().jobs[0];assert.throws(()=>x.db.queue.resultFence(j.id,j.attempts[0].id),e=>e.code==='STALE_EPOCH');await send(x.db,{type:'RecoverJob',jobId:j.id,attemptId:j.attempts[0].id,expectedVersion:j.version});x.controls.status='COMPLETED';await x.observer.tick();assert.equal(x.effects.length,before+1);assert(x.effects.at(-1).path.endsWith('/status'));assert.equal(x.db.queue.view().counts.active,0);assert.equal(x.db.document('document_1'),null);assert.throws(()=>x.db.candidates.view(j.id),e=>e.code==='NOT_FOUND');});
test('active IO lease delays reclamation and a concurrent registered pin rescues quarantined bytes',async t=>{const x=await setup(t);const lease='retained-reader';x.db.objects.acquire(lease);await remove(x.db,false);await send(x.db,{type:'CollectDocumentGarbage',documentId:'document_1'});assert.equal(x.db.deletions.receipt('document_1').actualFreedBytes,'0');const row=x.db.db.prepare("SELECT * FROM deletion_objects WHERE state='quarantined' AND hash NOT IN (SELECT hash FROM roots) LIMIT 1").get();assert(row);const ref={hash:row.hash,byteLength:row.byte_length,mediaType:row.media_type};x.db.db.exec('BEGIN IMMEDIATE');x.db.register('external-pin:rescue',ref);x.db.db.exec('COMMIT');x.db.objects.release(lease);await send(x.db,{type:'CollectDocumentGarbage',documentId:'document_1'});x.db.objects.verify(ref);assert.equal(x.db.db.prepare('SELECT state FROM deletion_objects WHERE hash=?').get(ref.hash).state,'rescued');assert(BigInt(x.db.deletions.receipt('document_1').actualFreedBytes)>0n);});

test('explicit uncertain recovery validates retained acknowledgement without sending another submission',async t=>{const x=await setup(t),j=x.db.queue.view().jobs[0],a=j.attempts[0],policy=x.provider.policy({attemptId:a.id,identity:{endpoint:j.review.endpoint},profileId:'local-fixture-v1'}).applied;x.db.queue.reserve(j.id);const d=x.db.queue.dispatch(j.id,a.id,{},policy),base=x.origin+'/ideogram/v4/requests/known',sink=x.db.queue.sink(a.id,'response',policy);sink.append(Buffer.from(JSON.stringify({request_id:'known',status_url:base+'/status',response_url:base,cancel_url:base+'/cancel'})));sink.finish(true);x.db.queue.outcome(j.id,a.id,d.epoch,{kind:'uncertain',reason:'Acknowledgement commit interrupted'});let now=x.db.queue.view().jobs[0];await send(x.db,{type:'RecoverJob',jobId:now.id,attemptId:a.id,expectedVersion:now.version});x.dispatcher.recoverRetained(now.id,a.id);now=x.db.queue.view().jobs[0];assert.equal(now.attempts[0].requestId,'known');assert.equal(now.attempts.length,1);assert.equal(now.attempts[0].hold,true);assert.deepEqual(x.effects,[]);});
test('conflicting retained acknowledgements never select a provider identity or release the hold',async t=>{const x=await setup(t),j=x.db.queue.view().jobs[0],a=j.attempts[0],policy=x.provider.policy({attemptId:a.id,identity:{endpoint:j.review.endpoint},profileId:'local-fixture-v1'}).applied;x.db.queue.reserve(j.id);const d=x.db.queue.dispatch(j.id,a.id,{},policy);for(const id of ['one','two']){const base=x.origin+'/ideogram/v4/requests/'+id,sink=x.db.queue.sink(a.id,'response',policy);sink.append(Buffer.from(JSON.stringify({request_id:id,status_url:base+'/status',response_url:base,cancel_url:base+'/cancel'})));sink.finish(true);}x.db.queue.outcome(j.id,a.id,d.epoch,{kind:'uncertain',reason:'Commit interrupted'});let now=x.db.queue.view().jobs[0];await send(x.db,{type:'RecoverJob',jobId:now.id,attemptId:a.id,expectedVersion:now.version});x.dispatcher.recoverRetained(now.id,a.id);now=x.db.queue.view().jobs[0];assert.equal(now.attempts[0].requestId,null);assert.equal(now.attempts[0].hold,true);assert.match(now.attempts[0].controlWarning,/Conflicting/);assert.deepEqual(x.effects,[]);});
test('deletion aborts an active media transfer before publication and cleans document-only transport bytes',async t=>{const x=await setup(t);await x.dispatcher.submit(x.q.job.id);let release;x.controls.hold=new Promise(r=>release=r);x.controls.status='COMPLETED';const running=x.observer.tick();void running.catch(()=>{});try{for(let n=0;!x.effects.some(e=>e.path==='/image')&&n<200;n++)await new Promise(r=>setTimeout(r,10));assert(x.effects.some(e=>e.path==='/image'));await remove(x.db);await running;assert.equal(x.db.document('document_1'),null);assert.equal(x.db.objects.reservationInventory().activeTransfers,0);await send(x.db,{type:'CollectDocumentGarbage',documentId:'document_1'});assert(BigInt(x.db.deletions.receipt('document_1').actualFreedBytes)>0n);assert.equal(x.db.db.prepare('SELECT count(*) n FROM candidates').get().n,0);assert.equal(x.db.db.prepare("SELECT count(*) n FROM deletion_files WHERE state!='freed'").get().n,0);}finally{release();await running;}});

test('whole deletion reclaims completed document-only raster work and protected response copies',async t=>{const x=await setup(t);await x.dispatcher.submit(x.q.job.id);x.controls.status='COMPLETED';await x.observer.tick();const v=x.db.candidates.view(x.q.job.id);assert.equal(v.items[0].state,'prepared');const work=x.db.db.prepare('SELECT path FROM deletion_work WHERE document_id=?').all('document_1');assert(work.length>0);await remove(x.db,false);await send(x.db,{type:'CollectDocumentGarbage',documentId:'document_1'});const {access}=await import('node:fs/promises');for(const row of work)await assert.rejects(access(row.path));const files=x.db.db.prepare('SELECT * FROM deletion_files').all();assert(files.length>0);assert(files.every(f=>f.state==='freed'));assert.equal(x.db.db.prepare("SELECT count(*) n FROM roots WHERE owner LIKE 'candidate:%' OR owner LIKE 'candidate-prepared:%' OR owner LIKE 'candidate-provenance:%'").get().n,0);assert.equal(x.db.deletions.receipt('document_1').status,'cleanup-complete');});
test('matching original recovery restores missing bytes without replacing candidate or repeating inference',async t=>{const x=await setup(t);await x.dispatcher.submit(x.q.job.id);x.controls.status='COMPLETED';await x.observer.tick();const v=x.db.candidates.view(x.q.job.id),c=v.items[0],original=x.db.assets.asset(c.encodedAssetId),{readFile,unlink}=await import('node:fs/promises'),{randomUUID}=await import('node:crypto'),bytes=await readFile(x.db.objects.path(original.blob)),before=x.effects.length;await unlink(x.db.objects.path(original.blob));assert.throws(()=>x.db.objects.verify(original.blob));const bad=await send(x.db,{type:'RecoverCandidateOriginal',candidateId:c.id,expectedVersion:c.version,assetId:x.q.job.review.draftAsset});assert.equal(bad.status,'rejected');const stagingId=randomUUID(),a=auth();x.db.assets.create({protocolVersion:1,stagingId,purpose:'image',expectedBytes:String(bytes.length),sha256:original.blob.hash,mediaType:original.blob.mediaType},a);const token=x.db.assets.beginChunk(stagingId,'0',bytes.length,a);x.db.assets.chunk(token,bytes,a);const command=envelope({type:'FinalizeStaging',stagingId,expectedSha256:original.blob.hash});x.db.assets.command(encode(command),a);let record;for(let n=0;n<200;n++){record=x.db.lookup(command.command.commandId);if(record)break;await new Promise(r=>setTimeout(r,10));}assert.equal(record?.receipt.status,'accepted');const event=x.db.events(String(BigInt(record.receipt.fromSeq)-1n),100).events.find(e=>e.commandId===command.command.commandId&&e.type==='AssetRegistered');const repaired=await send(x.db,{type:'RecoverCandidateOriginal',candidateId:c.id,expectedVersion:c.version,assetId:event.payload.asset.id});assert.equal(repaired.status,'accepted',JSON.stringify(repaired));await x.observer.tick(Date.now()+9000);x.db.objects.verify(original.blob);const after=x.db.candidates.view(x.q.job.id).items[0];assert.equal(after.id,c.id);assert.equal(after.encodedAssetId,c.encodedAssetId);assert.equal(after.state,'prepared');assert.equal(x.effects.length,before);assert.equal(x.effects.filter(e=>e.method==='POST').length,1);});
