import {fork} from 'node:child_process';import {once} from 'node:events';
import test from 'node:test';import assert from 'node:assert/strict';import {readFile,unlink,access} from 'node:fs/promises';import {join} from 'node:path';
import {reviewFixture,send,remove} from './review-fixture.mjs';import {childFor} from '../store/helpers.mjs';import {auth,encode,envelope} from '../queue/helpers.mjs';
async function shared(t){const x=await reviewFixture(t,{two:true});for(const q of [x.q,x.q2]){await x.dispatcher.submit(q.job.id);await x.observer.tick();}const a=x.db.candidates.view(x.q.job.id).items[0],b=x.db.candidates.view(x.q2.job.id).items[0];assert.equal(a.state,'prepared');assert.equal(b.state,'prepared');const ref=x.db.assets.asset(a.encodedAssetId).blob;assert.equal(x.db.assets.asset(b.encodedAssetId).blob.hash,ref.hash);assert.equal(x.db.db.prepare('SELECT count(*) n FROM deletion_backup_pins WHERE hash=?').get(ref.hash).n,0);return {x,ref};}
const collect=(x,id)=>send(x.db,{type:'CollectDocumentGarbage',documentId:id});
for(const first of ['document_1','document_2'])for(const crash of [false,true])test('F2 shared hash '+first+' first, restart after first collection and '+(crash?'second intent':'second collection'),async t=>{
 const {x,ref}=await shared(t),second=first==='document_1'?'document_2':'document_1';await remove(x.db,'document_1');await remove(x.db,'document_2');const rows=x.db.db.prepare('SELECT * FROM deletion_objects').all(),unique=new Map(rows.map(r=>[r.hash,BigInt(r.byte_length)]));const freedHashes=new Set();for(const [hash]of unique)if(!x.db.db.prepare('SELECT 1 FROM roots WHERE hash=?').get(hash)&&!x.db.db.prepare('SELECT 1 FROM deletion_backup_pins WHERE hash=?').get(hash))freedHashes.add(hash);
 assert.equal((await collect(x,first)).status,'accepted');await assert.rejects(access(x.db.objects.path(ref)));await x.reopen();
 if(crash){await x.close();const child=await childFor(t,x.f.root,{phase:'deletion-quarantine-committed'}),c=envelope({type:'CollectDocumentGarbage',documentId:second}),pending=child.call('queueCommand',encode(c),auth()).catch(e=>e);await child.wait('barrier');await child.assertNoEffects();await child.kill();await pending;await x.reopen();}
 assert.equal((await collect(x,second)).status,'accepted');await x.reopen();for(const id of [first,second])assert.equal(x.db.deletions.receipt(id).status,'cleanup-complete');
 const actual=[first,second].reduce((s,id)=>s+BigInt(x.db.deletions.receipt(id).actualFreedBytes),0n),fileBytes=x.db.db.prepare("SELECT bytes FROM deletion_files WHERE state='freed'").all().reduce((s,r)=>s+BigInt(r.bytes),0n);assert.equal(actual,fileBytes+[...freedHashes].reduce((s,h)=>s+unique.get(h),0n));
 const before=actual;await collect(x,second);assert.equal([first,second].reduce((s,id)=>s+BigInt(x.db.deletions.receipt(id).actualFreedBytes),0n),before);assert.equal(x.effects.filter(e=>e.method==='POST').length,2);
});
test('F2 a live second owner retains actual shared bytes',async t=>{const {x,ref}=await shared(t);await remove(x.db);await collect(x,'document_1');assert.deepEqual(await readFile(x.db.objects.path(ref)),x.png);await x.reopen();x.db.objects.verify(ref);assert(x.db.document('document_2'));assert(BigInt(x.db.deletions.receipt('document_1').retainedBytes)>=BigInt(ref.byteLength));});
test('F2 unexplained missing object before unlink intent remains an explicit failure',async t=>{const {x,ref}=await shared(t);await remove(x.db);await remove(x.db,'document_2');await unlink(x.db.objects.path(ref));await assert.rejects(collect(x,'document_1'),e=>e.code==='MISSING_OBJECT');assert.notEqual(x.db.deletions.receipt('document_1').status,'cleanup-complete');});
for(const phase of ['deletion-unlink-intent-committed','deletion-after-unlink'])test('F2 shared in-flight intent survives process death at '+phase,async t=>{
 const {x,ref}=await shared(t);await remove(x.db);await remove(x.db,'document_2');await x.close();
 const child=fork(new URL('./review-gc-child.mjs',import.meta.url),[x.f.root,ref.hash,phase],{execArgv:['--import',new URL('../store/no-network.mjs',import.meta.url).pathname],stdio:['ignore','pipe','pipe','ipc']});let stderr='';child.stderr.on('data',b=>stderr+=b);const ended=once(child,'exit');
 t.after(async()=>{if(child.exitCode===null&&child.signalCode===null){child.kill('SIGKILL');await ended;}});
 const next=()=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Targeted GC barrier timeout: '+stderr)),10000);child.once('message',m=>{clearTimeout(timer);resolve(m);});});
 assert.equal((await next()).type,'ready');const barrier=next();child.send('collect');const reached=await barrier;assert.equal(reached.type,'barrier',JSON.stringify(reached));assert.equal(reached.hash,ref.hash);assert.equal(reached.present,phase==='deletion-unlink-intent-committed');assert(Object.values(reached.effects).every(n=>n===0));t.diagnostic(JSON.stringify(reached));child.kill('SIGKILL');await ended;await x.reopen();
 for(const id of ['document_1','document_2'])assert.equal((await collect(x,id)).status,'accepted');await assert.rejects(access(x.db.objects.path(ref)));assert.equal(x.db.db.prepare("SELECT count(*) n FROM deletion_objects WHERE hash=? AND state='freed'").get(ref.hash).n,1);await x.reopen();
});
