import test from 'node:test';import assert from 'node:assert/strict';
import {reviewFixture,send,remove} from './review-fixture.mjs';
const effects=rows=>({submit:rows.filter(x=>x.method==='POST'&&x.path!=='/upload').length,upload:rows.filter(x=>x.path==='/upload').length,poll:rows.filter(x=>x.path.endsWith('/status')).length,cancel:rows.filter(x=>x.path.endsWith('/cancel')).length,fetch:rows.filter(x=>x.method==='GET'&&!x.path.endsWith('/status')&&!x.path.endsWith('/cancel')).length});
test('F1 persisted unconsumed retrieval retry remains paused until explicit recovery',async t=>{
 const x=await reviewFixture(t);await x.dispatcher.submit(x.q.job.id);x.controls.mediaStatus=503;await x.observer.tick();let c=x.db.candidates.view(x.q.job.id).items[0];assert.equal(c.state,'transfer-failed');
 assert.equal((await send(x.db,{type:'RetryCandidateImport',candidateId:c.id,expectedVersion:c.version})).status,'accepted');assert.equal(x.db.candidates.retries().length,1);await x.reopen();x.controls.mediaStatus=200;const start=x.effects.length;
 await x.observer.tick(Date.now()+10000);assert.deepEqual(effects(x.effects.slice(start)),{submit:0,upload:0,poll:0,cancel:0,fetch:0});assert.equal(x.db.candidates.retries().length,1);
 let j=x.db.queue.view().jobs[0];assert.equal(j.attempts[0].recoveryRequired,true);assert.equal((await send(x.db,{type:'RecoverJob',jobId:j.id,attemptId:j.attempts[0].id,expectedVersion:j.version})).status,'accepted');await x.observer.tick(Date.now()+20000);
 assert.deepEqual(effects(x.effects.slice(start)),{submit:0,upload:0,poll:0,cancel:0,fetch:1});assert.equal(x.effects.at(-1).path,'/image');const after=x.db.candidates.view(j.id).items[0];assert.equal(after.id,c.id);assert.equal(after.attemptId,c.attemptId);assert.equal(after.state,'prepared');assert.equal(x.db.candidates.retries().length,0);assert.equal(x.db.queue.view().jobs[0].attempts.length,1);
});
for(const status of ['COMPLETED','FAILED','CANCELLED'])for(const kind of ['503','incomplete','wrong-id','200'])test('F3 detached '+status+' '+kind+' respects successful same-request terminal evidence',async t=>{
 const x=await reviewFixture(t);await x.dispatcher.submit(x.q.job.id);await remove(x.db);const j=x.db.queue.view().jobs[0];assert.equal((await send(x.db,{type:'RecoverJob',jobId:j.id,attemptId:j.attempts[0].id,expectedVersion:j.version})).status,'accepted');Object.assign(x.controls,{status,statusCode:kind==='503'?503:200,incomplete:kind==='incomplete',requestId:kind==='wrong-id'?'other':'known'});const before=x.effects.length;await x.observer.tick();
 const view=x.db.queue.view(),a=view.jobs[0].attempts[0];assert.equal(a.hold,kind!=='200');assert.equal(a.state==='provider-terminal',kind==='200');assert.equal(a.terminal??null,kind==='200'?status.toLowerCase():null);assert.equal(view.counts.dispatched,1);assert.equal(a.count,'dispatched');assert.equal(x.db.document('document_1'),null);assert.deepEqual(effects(x.effects.slice(before)),{submit:0,upload:0,poll:1,cancel:0,fetch:0});if(kind!=='200')assert.match(a.controlWarning,/unconfirmed|could not be confirmed/i);
});
test('F3 unsuccessful later check preserves an already confirmed terminal without claiming a held slot',async t=>{
 const x=await reviewFixture(t);await x.dispatcher.submit(x.q.job.id);await remove(x.db);async function recover(){const j=x.db.queue.view().jobs[0];assert.equal((await send(x.db,{type:'RecoverJob',jobId:j.id,attemptId:j.attempts[0].id,expectedVersion:j.version})).status,'accepted');await x.observer.tick();}
 await recover();x.controls.statusCode=503;await recover();const a=x.db.queue.view().jobs[0].attempts[0];assert.equal(a.hold,false);assert.equal(a.terminal,'completed');assert.match(a.controlWarning,/could not be confirmed/);assert.doesNotMatch(a.controlWarning,/hold remains/);assert.equal(x.db.queue.view().counts.dispatched,1);
});
