import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {join} from 'node:path';import {readFile,access} from 'node:fs/promises';
import {fixture,prepare,enqueue,auth,envelope,encode,command,EMPTY_EXPECTED_VERSIONS} from '../queue/helpers.mjs';
import {resolvePrivacy} from '../../dist/local/server/provider/policy.js';import {fixtureProfile} from '../provider/emulator.mjs';
const policy=resolvePrivacy(fixtureProfile(),'ideogram/v4','fixture').applied;
const send=(w,body)=>w.queueCommand(encode(envelope(body)),auth());
const current=async w=>(await w.queueView()).jobs[0];
async function pending(f,ack=false){let {job}=await enqueue(f.writer,(await prepare(f.writer)).body);const r=await f.writer.queueReserve(job.id),d=await f.writer.queueDispatch(job.id,r.attempt.id,{},policy);if(ack)await f.writer.queueOutcome(job.id,r.attempt.id,d.epoch,{kind:'ack',requestId:'known',urls:{status:'http://127.0.0.1:1/status',result:'http://127.0.0.1:1/result',cancel:'http://127.0.0.1:1/cancel'},responseRecord:'fixture'});return current(f.writer);}
async function preview(w,id='document_1'){const receipt=await send(w,{type:'PreviewDocumentDeletion',documentId:id,expectedRevision:await w.documentRevision(id)});assert.equal(receipt.status,'accepted',JSON.stringify(receipt));return (await w.deletionView(id,auth())).plan;}
function deletion(plan,ack=false){return {type:'DeleteDocument',documentId:plan.documentId,planId:plan.id,planHash:plan.planHash,rootGeneration:plan.rootGeneration,expectedRevision:plan.documentRevision,acknowledgeRunningAndUncertain:ack};}
function sql(root,query){const db=new DatabaseSync(join(root,'metadata.sqlite'),{readOnly:true});try{return db.prepare(query).all();}finally{db.close();}}
test('cancel safe reservation and redo preserve no-submit state and release only unspent count',async t=>{const f=await fixture(t),q=await enqueue(f.writer,(await prepare(f.writer)).body);await f.writer.queueReserve(q.job.id);let j=await current(f.writer);assert.equal((await send(f.writer,{type:'UndoPendingJob',jobId:j.id,attemptId:j.attempts[0].id,expectedVersion:j.version})).status,'accepted');j=await current(f.writer);assert.equal(j.disposition,'suppressed-by-undo');assert.equal(j.attempts[0].state,'locally-cancelled');assert.equal((await send(f.writer,{type:'RedoPendingJob',jobId:j.id,attemptId:j.attempts[0].id,expectedVersion:j.version})).status,'accepted');assert.equal(await f.writer.queueReserve(j.id),null);assert.equal((await f.writer.queueView()).counts.active,0);await f.reopen();assert.equal((await current(f.writer)).attempts.length,1);});
test('reopen known job requires explicit same-identity recovery without a new attempt or released hold',async t=>{const f=await fixture(t);await pending(f,true);await f.reopen();let j=await current(f.writer),a=j.attempts[0];assert.equal(a.recoveryRequired,true);assert.equal(a.requestId,'known');assert.equal(a.hold,true);assert.equal((await send(f.writer,{type:'RecoverJob',jobId:j.id,attemptId:a.id,expectedVersion:j.version})).status,'accepted');j=await current(f.writer);assert.equal(j.attempts.length,1);assert.equal(j.attempts[0].recoveryRequired,false);assert.equal(j.attempts[0].count,'dispatched');});
test('uncertain recovery never creates an identifier or releases its original reservation',async t=>{const f=await fixture(t);await pending(f);await f.reopen();let j=await current(f.writer),a=j.attempts[0];assert.equal(a.state,'submission-uncertain');await send(f.writer,{type:'RecoverJob',jobId:j.id,attemptId:a.id,expectedVersion:j.version});j=await current(f.writer);assert.equal(j.attempts[0].requestId,null);assert.equal(j.attempts[0].hold,true);assert.equal(j.attempts.length,1);assert.match(j.attempts[0].controlWarning,/No durable provider identifier/);});
test('cancel intent keeps the dispatched count and hold; duplicate command returns the same receipt',async t=>{const f=await fixture(t),j=await pending(f,true),a=j.attempts[0],c=envelope({type:'CancelJob',jobId:j.id,attemptId:a.id,expectedVersion:j.version});const receipt=await f.writer.queueCommand(encode(c),auth());assert.equal(receipt.status,'accepted');assert.deepEqual(await f.writer.queueCommand(encode(c),auth()),receipt);const next=await current(f.writer);assert.equal(next.attempts[0].cancel,'requested');assert.equal(next.attempts[0].hold,true);assert.equal(next.attempts[0].count,'dispatched');assert.equal((await send(f.writer,{...c.command.body})).code,'STALE_REVISION');});
test('deletion preview is durable and a changed document invalidates confirmation',async t=>{const f=await fixture(t),p=await preview(f.writer);assert.equal(p.histories,1);await f.writer.submit(encode(command(EMPTY_EXPECTED_VERSIONS,{expectedDocumentRevision:'1',body:{type:'SaveCheckpoint',name:'keep'}})),f.writer.epoch);const r=await send(f.writer,deletion(p));assert.equal(r.status,'rejected');assert.equal(r.code,'STALE_REVISION');assert(await f.writer.document('document_1'));});
test('changed roots invalidate confirmation even when document revision is unchanged',async t=>{const f=await fixture(t),p=await preview(f.writer);await prepare(f.writer);assert.equal((await send(f.writer,deletion(p))).code,'STALE_REVISION');assert(await f.writer.document('document_1'));});
test('deletion atomically cancels unstarted work and duplicate receipt cannot resurrect a namespace',async t=>{const f=await fixture(t);const q=await enqueue(f.writer,(await prepare(f.writer)).body),p=await preview(f.writer),c=envelope(deletion(p));const r=await f.writer.queueCommand(encode(c),auth());assert.equal(r.status,'accepted',JSON.stringify(r));assert.deepEqual(await f.writer.queueCommand(encode(c),auth()),r);assert.equal(await f.writer.document('document_1'),null);assert.equal(await f.writer.queueReserve(q.job.id),null);assert.equal((await current(f.writer)).attempts[0].state,'locally-cancelled');await f.reopen();assert.equal(await f.writer.document('document_1'),null);assert.equal((await current(f.writer)).disposition,'deleted');const newDoc=await f.writer.submit(encode(command(EMPTY_EXPECTED_VERSIONS,{})),f.writer.epoch);assert.equal(newDoc.status,'rejected');assert.equal((await f.writer.deletionView('document_1',auth())).receipt.actualFreedBytes,'0');});
test('deletion needs running acknowledgement and preserves conservative uncertainty and charge holds',async t=>{const f=await fixture(t);await pending(f);await f.reopen();let j=await current(f.writer),p=await preview(f.writer);assert.equal(p.unresolvedAttempts.length,1);assert.equal((await send(f.writer,deletion(p))).status,'rejected');p=await preview(f.writer);assert.equal((await send(f.writer,deletion(p,true))).status,'accepted');j=await current(f.writer);assert.equal(j.attempts[0].hold,true);assert.equal(j.attempts[0].state,'submission-uncertain');assert.equal((await send(f.writer,{type:'OverrideUncertainHold',jobId:j.id,attemptId:j.attempts[0].id,expectedVersion:j.version,acknowledgeOverlapAndChargeRisk:true})).status,'accepted');assert.equal((await f.writer.queueView()).counts.dispatched,1);});
test('reclamation reports only actual unlink bytes and retained independent roots survive reopen',async t=>{const f=await fixture(t);await enqueue(f.writer,(await prepare(f.writer)).body);const p=await preview(f.writer);assert(BigInt(p.exclusiveBytes)>0n);assert.equal((await send(f.writer,deletion(p))).status,'accepted');const before=(await f.writer.deletionView('document_1',auth())).receipt;assert.equal(before.actualFreedBytes,'0');const r=await send(f.writer,{type:'CollectDocumentGarbage',documentId:'document_1'});assert.equal(r.status,'accepted');const receipt=(await f.writer.deletionView('document_1',auth())).receipt;assert.equal(receipt.status,'cleanup-complete');assert(BigInt(receipt.actualFreedBytes)>0n);for(const row of sql(f.root,"SELECT * FROM deletion_objects WHERE state='freed'"))await assert.rejects(access(join(f.root,'objects/sha256',row.hash.slice(7,9),row.hash.slice(7))));await f.reopen();assert.equal(await f.writer.document('document_1'),null);assert.equal((await f.writer.deletionView('document_1',auth())).receipt.actualFreedBytes,receipt.actualFreedBytes);assert.equal((await send(f.writer,{type:'CollectDocumentGarbage',documentId:'document_1'})).status,'accepted');assert.equal((await f.writer.deletionView('document_1',auth())).receipt.actualFreedBytes,receipt.actualFreedBytes);});
