import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {nothing} from 'lit';
import {uiModule,modelMemoryURL,uiModelOwnerURL,allocationsURL,readOwnedJSON} from '../ui-model-module.mjs';
import {allocationDeltaSnapshot} from '../owned-preview-module.mjs';

const storageURL=await uiModule('src/protocol/storage.ts'),repairURL=await uiModule('src/protocol/storage-repair.ts'),adapterURL=await uiModule('src/ui/adapters.ts');
const flowURL=await uiModule('src/ui/storage-library.ts',{'lit':import.meta.resolve('lit'),'./adapters.js':adapterURL,'./model-owner.js':uiModelOwnerURL,'../protocol/storage.js':storageURL,'../protocol/storage-repair.js':repairURL});
const {StorageLibrary}=await import(flowURL),{STORAGE_CATEGORIES}=await import(storageURL),{cloneOwnedModel}=await import(modelMemoryURL),{allocationLedger}=await import(allocationsURL);
const digest=value=>'sha256:'+createHash('sha256').update(value).digest('hex');
const content=new Uint8Array([1,2,3,4]),ref={hash:digest(content),byteLength:'4',mediaType:'application/octet-stream'};
const asset={id:'asset_one',version:'7',purpose:'image',qualification:'canonical-raster',recordedAvailability:'available',availability:'missing',availabilityScope:'primary-object-only',blob:ref,knownBytes:'4'};
const observation={protocolVersion:1,epoch:'1',highWater:'2'};
function summary(){return {...observation,categories:STORAGE_CATEGORIES.map(id=>({id,label:id==='all'?'All registered assets':id,assetCount:['all','originals'].includes(id)?1:0,objectCount:['all','originals'].includes(id)?1:0,knownBytes:['all','originals'].includes(id)?'4':'0',complete:id!=='history',unknownCount:id==='history'?null:0,assetRows:!['datasets','history','staging','previews'].includes(id)})),registeredObjects:{count:1,knownBytes:'4',complete:false},filesystem:{availableBytes:'1000',totalBytes:'2000'},appPhysicalBytes:null,accounting:'logical-content-bytes; categories may overlap',previewCache:{entries:3,knownBytes:'12',pinnedEntries:1,activeBuilds:1,clearableEntries:2,clearableBytes:'8',scope:'registered-display-derivatives'}};}
function assetPage(patch={}){return {...observation,highWater:'3',category:'originals',items:[asset],nextCursor:'assets_next',complete:false,...patch};}
function dependencies(patch={}){return {...observation,highWater:'4',asset,items:[{kind:'object',id:ref.hash,label:'Original bytes',relation:'expected-object',ref,availability:'missing'},{kind:'root',id:'document:doc',label:'Current document',relation:'asset-reference'}],nextCursor:'dependencies_next',complete:false,...patch};}
function review(){return {protocolVersion:1,reviewId:'repair_one',reviewHash:'sha256:'+'b'.repeat(64),assetId:asset.id,assetVersion:asset.version,ref,condition:'missing',targetIdentity:'sha256:'+'a'.repeat(64),owner:'asset:asset_one',staging:{purpose:'text',mediaType:'application/octet-stream'},expiresAt:new Date(Date.now()+600000).toISOString()};}
function stage(patch={}){return {protocolVersion:1,stagingId:'stage_one',purpose:'text',expectedBytes:'4',sha256:ref.hash,mediaType:'application/octet-stream',ownerClientId:'client',version:'12',committedOffset:'4',state:'complete',...patch};}
const cleared=()=>({...observation,highWater:'5',scope:'registered-unpinned-display-derivatives',outcome:'partial',removedEntries:1,freedLogicalBytes:'4',pinnedEntries:1,activeBuilds:1,retainedEntries:2,examinedEntries:3,unexaminedEntries:0,failures:[{key:'c'.repeat(64),reason:'identity'}],untrackedScope:'retained-not-enumerated'});
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});void promise.catch(()=>{});return {promise,resolve,reject};};
const turn=()=>new Promise(resolve=>setTimeout(resolve,0));
async function until(predicate){const end=performance.now()+3000;while(!predicate()){assert.ok(performance.now()<end,'Expected owned controller state');await new Promise(setImmediate);}}
function rendered(flow){
 const slots=[];
 const flatten=value=>value===nothing||value===null||value===undefined?'':Array.isArray(value)?value.map(flatten).join(''):value?.strings?value.strings.reduce((text,part,index)=>text+part+(index<value.values.length?flatten(value.values[index]):''),''):'__slot'+(slots.push(value)-1)+'__';
 const markup=flatten(flow.render()),resolve=text=>text.replace(/__slot(\d+)__/g,(_,index)=>String(slots[Number(index)]));
 const controls=[...markup.matchAll(/<(en-button|en-file-upload)\b([^>]*)>([\s\S]*?)<\/\1>/g)].map(([,tag,attributes,label])=>{
  const disabled=/\?disabled=__slot(\d+)__/.exec(attributes),click=/@click=__slot(\d+)__/.exec(attributes),change=/@en-change=__slot(\d+)__/.exec(attributes),labelAttribute=/\blabel="([^"]+)"/.exec(attributes);
  return {tag,name:tag==='en-button'?resolve(label).trim():labelAttribute?.[1],disabled:disabled?Boolean(slots[Number(disabled[1])]):false,click:click?slots[Number(click[1])]:undefined,change:change?slots[Number(change[1])]:undefined};
 });return {controls,text:resolve(markup.replace(/<[^>]+>/g,'')),markup};
}
function fixture(){
 const baseline=allocationDeltaSnapshot(allocationLedger),calls=[],uploads=[],commands=[],gates=[],failures=[];let identity='client',routeOverride,uploadOverride,chooser,commit=Promise.resolve(true);
 const gate=()=>{const value=deferred();gates.push(value);return value;};
 const state={summary:summary(),assets:assetPage(),dependencies:dependencies(),review:review(),stage:stage(),cache:cleared()};
 const host={requestUpdate(){},querySelector(selector){return selector==='[data-storage-repair-file]'?chooser:null;},get updateComplete(){return commit;}};
 const editor={session:{identity:()=>identity},sessionId:'session',documentEpoch:1,view:{ready:true,busy:false,document:null},fail(error){failures.push(error);},
  ownedJSON(path,owner,init,owns,maxBytes,kind){return readOwnedJSON(async()=>{
   calls.push({path,method:init?.method??'GET',body:init?.body,signal:init?.signal});
   const custom=await routeOverride?.(path,init);if(custom instanceof Response)return custom;if(custom!==undefined)return response(custom);
   if(path==='/api/v1/storage')return response(state.summary);
   if(path.startsWith('/api/v1/storage/assets?'))return response(state.assets);
   if(path.includes('/dependencies'))return response(state.dependencies);
   if(path.includes('/relink/'))return response(state.review);
   if(path.startsWith('/api/v1/assets/staging/'))return response(state.stage);
   if(path==='/api/v1/storage/preview-cache/clear')return response(state.cache);
   if(path==='/api/v1/storage/assets/asset_one/relink'&&init?.method==='POST')return response({protocolVersion:1,operationId:JSON.parse(init.body).operationId,status:'restored',assetId:asset.id,assetVersion:asset.version,ref,previousCondition:state.review.condition});
   throw Error('Unexpected transport path '+path);
  },path,{owner,init,owns,maxBytes,kind});},
  async ownedUpload(file,purpose,mediaType,existing,current,signal){uploads.push({file,purpose,mediaType,existing,current,signal});await uploadOverride?.(uploads.at(-1));const value={protocolVersion:1,stagingId:'stage_one',purpose,expectedBytes:String(file.size),sha256:digest(new Uint8Array(await file.arrayBuffer())),mediaType};return cloneOwnedModel('storage-fixture-upload',value);},
  async withCommandEvents(...args){commands.push(args);throw Error('Storage must not dispatch an editor command');}
 };
 const callbacks=[],flow=new StorageLibrary(host,editor,{onRestoreCopy(){callbacks.push({kind:'restore',lifecycle:flow.lifecycle});},onImport(){callbacks.push({kind:'import',lifecycle:flow.lifecycle});}});
 const event=(extra={})=>{const target={isConnected:true,...extra};return {currentTarget:target,composedPath:()=>[target],defaultPrevented:false};};
 const fileEvent=files=>{chooser??={isConnected:true,files:[]};chooser.files=files;return {currentTarget:chooser,composedPath:()=>[chooser],defaultPrevented:false};};
 const control=name=>{const value=rendered(flow).controls.find(value=>value.name===name);assert.ok(value,'Rendered control '+name);return value;};
 const click=(name,ev=event())=>{const value=control(name);assert.equal(value.disabled,false,'Action enabled: '+name);value.click(ev);return ev;};
 const idle=async()=>{await turn();await until(()=>!flow.busy&&flow.lifecycle.pending===0&&flow.lifecycle.reads===0);};
 const select=async(file)=>{const value=control('Exact repair file');assert.equal(value.disabled,false);value.change(fileEvent([file]));await Promise.resolve();};
 const inspect=async()=>{await flow.open();click('Inspect originals');await idle();click('Inspect dependencies for asset_one');await idle();};
 const prepare=async()=>{await inspect();click('Review exact repair '+ref.hash);await idle();};
 const close=async()=>{for(const g of gates)g.resolve();commit=Promise.resolve(true);await flow.dispose();await turn();assert.equal(baseline().activeRecords,0);assert.equal(baseline().cpuBytes,0);assert.equal(baseline().handles,0);};
 return {flow,editor,state,calls,uploads,commands,callbacks,failures,gate,event,fileEvent,control,click,idle,select,inspect,prepare,close,baseline,setIdentity(value){identity=value;},route(value){routeOverride=value;},upload(value){uploadOverride=value;},commit(value){commit=value;}};
}
function response(value){const bytes=new TextEncoder().encode(JSON.stringify(value));return new Response(bytes,{headers:{'Content-Type':'application/json','Content-Length':String(bytes.length)}});}
const exactFile=()=>new File([content],'exact.bin',{type:'application/octet-stream'});

test('storage opens while its shell operation is busy, without requiring a document; counts remain explicit',async()=>{
 const f=fixture();try{f.editor.view.busy=true;await f.flow.open();assert.equal(f.calls.length,1);assert.equal(f.flow.summary.categories.length,10);assert.equal(f.flow.summary.categories[0].id,'all');assert.equal(f.control('Inspect All registered assets').disabled,false);const view=rendered(f.flow);assert.match(view.text,/Categories can overlap/);assert.match(view.text,/Physical app disk usage is not measured/);assert.match(view.text,/unknown count unavailable/);assert.match(view.text,/No asset rows; category accounting only/);assert.match(view.text,/cannot replace an existing corrupt object/);assert.match(view.text,/IDEOGRAM_PROVIDER_MODE=disabled npm start -- --root \/absolute\/path\/to\/new-private-root/);assert.match(view.text,/does not repair the previous document/);assert.match(view.markup,/class="storage-library-table" tabindex="0" role="region" aria-label="Known content by category"/);assert.equal(f.control('Clear unpinned previews').disabled,true);assert.equal(f.control('Refresh storage').disabled,false);assert.equal(f.baseline().activeRecords>0,true);}finally{await f.close();}
});
test('open paints pending feedback before the actual summary response arrives',async()=>{
 const f=fixture(),gate=f.gate();f.route(async path=>{if(path==='/api/v1/storage')await gate.promise;});try{const opened=f.flow.open();assert.match(rendered(f.flow).text,/Reading local storage inventory/);assert.equal(f.flow.busy,true);await until(()=>f.calls.length===1);gate.resolve();await opened;assert.equal(f.flow.summary.epoch,'1');}finally{await f.close();}
});
test('asset and dependency pages permit independent high-water observations and retain one bounded page',async()=>{
 const f=fixture();try{await f.inspect();assert.equal(f.flow.assets.highWater,'3');assert.equal(f.flow.dependencies.highWater,'4');assert.match(rendered(f.flow).text,/Shared dependency roots/);f.state.dependencies=dependencies({items:[{kind:'root',id:'history:one',label:'Retained history',relation:'content-root'}],nextCursor:null,complete:true});f.click('Next dependency page');await f.idle();assert.equal(f.flow.dependencies.items.length,1);assert.equal(f.flow.dependencies.items[0].id,'history:one');assert.equal(f.calls.at(-1).path,'/api/v1/storage/assets/asset_one/dependencies?cursor=dependencies_next');f.state.assets=assetPage({items:[],nextCursor:null,complete:true});f.click('Next asset page');await f.idle();assert.equal(f.flow.assets.items.length,0);assert.equal(f.flow.dependencies,null);assert.equal(f.calls.at(-1).path,'/api/v1/storage/assets?category=originals&cursor=assets_next');}finally{await f.close();}
});
test('malformed response, root drift and unstable cursor each preserve the last admitted page',async()=>{
 const f=fixture();try{await f.inspect();const prior=f.flow.assets;for(const invalid of [assetPage({unexpected:true}),assetPage({epoch:'2'}),assetPage({highWater:'99'})]){f.state.assets=invalid;f.click('Next asset page');await f.idle();assert.equal(f.flow.assets,prior);assert.ok(f.flow.error);assert.equal(f.flow.dependencies.asset.id,asset.id);}}finally{await f.close();}
});
test('wrong immutable dependency asset never replaces the current inspection',async()=>{
 const f=fixture();try{await f.inspect();const prior=f.flow.dependencies;f.state.dependencies=dependencies({asset:{...asset,version:'8'}});f.click('First dependency page');await f.idle();assert.equal(f.flow.dependencies,prior);assert.match(f.flow.error,/identity/);}finally{await f.close();}
});
test('retained old handlers and later veto cannot send a cache mutation',async()=>{
 const f=fixture();try{await f.flow.open();const old=f.control('Clear unpinned previews').click;f.click('Refresh storage');await f.idle();old(f.event());await f.idle();assert.equal(f.calls.filter(call=>call.method==='POST').length,0);const veto=f.click('Clear unpinned previews');veto.defaultPrevented=true;await f.idle();assert.equal(f.calls.filter(call=>call.method==='POST').length,0);assert.equal(f.flow.cacheResult,null);}finally{await f.close();}
});
test('cache clearing posts only the exact registered-unpinned scope and displays partial retained failures',async()=>{
 const f=fixture();try{await f.flow.open();f.click('Clear unpinned previews');await f.idle();const posts=f.calls.filter(call=>call.method==='POST');assert.equal(posts.length,1);assert.equal(posts[0].path,'/api/v1/storage/preview-cache/clear');assert.deepEqual(JSON.parse(posts[0].body),{protocolVersion:1,scope:'registered-unpinned-display-derivatives'});assert.equal(f.flow.cacheResult.outcome,'partial');assert.match(rendered(f.flow).text,/removed 1 entries/);assert.match(rendered(f.flow).text,/Untracked files were retained and not enumerated/);assert.match(rendered(f.flow).text,/identity/);assert.deepEqual(f.commands,[]);assert.deepEqual(f.uploads,[]);assert.equal(f.calls.at(-1).path,'/api/v1/storage');}finally{await f.close();}
});
test('a failed refresh after cache clearing retains its actual result and never repeats the mutation',async()=>{
 const f=fixture();try{await f.flow.open();f.route(path=>{if(path==='/api/v1/storage'&&f.calls.some(call=>call.method==='POST'))throw Error('INVENTORY_BUSY');});f.click('Clear unpinned previews');await f.idle();assert.equal(f.flow.cacheResult.removedEntries,1);assert.equal(f.flow.error,'INVENTORY_BUSY');assert.equal(f.calls.filter(call=>call.method==='POST').length,1);assert.equal(f.control('Refresh storage').disabled,false);}finally{await f.close();}
});
test('principal change while an inventory response is pending blocks publication and releases it',async()=>{
 const f=fixture(),gate=f.gate();f.route(async path=>{if(path==='/api/v1/storage')await gate.promise;});try{const work=f.flow.open();await until(()=>f.calls.length===1);f.setIdentity('other');gate.resolve();await work;assert.equal(f.flow.summary,null);rendered(f.flow);await f.flow.releaseDocument();assert.equal(f.baseline().activeRecords,0);}finally{await f.close();}
});
test('Close aborts and waits for actual response cancellation, then drains every read/model owner',async()=>{
 const f=fixture(),cancel=f.gate();let cancellationStarted=false;f.route(path=>path==='/api/v1/storage'?new Response(new ReadableStream({pull(){},cancel(){cancellationStarted=true;return cancel.promise;}}),{headers:{'Content-Length':'5'}}):undefined);
 try{const work=f.flow.open();await until(()=>f.flow.lifecycle.reads===1&&f.calls.length===1);let released=false;const drain=f.flow.releaseDocument().then(()=>{released=true;});await until(()=>cancellationStarted);assert.equal(released,false);assert.equal(f.baseline().activeRecords>0,true);cancel.resolve();await Promise.all([work,drain]);assert.equal(f.flow.summary,null);assert.deepEqual(f.flow.lifecycle,{models:0,reads:0,pending:0,cleanupFailures:0});}finally{await f.close();}
});
test('Close retains rendered summary ownership until the real render retirement commits',async()=>{
 const f=fixture(),commit=f.gate();try{await f.flow.open();f.commit(commit.promise);let done=false;const drain=f.flow.releaseDocument().then(()=>{done=true;});await Promise.resolve();await Promise.resolve();assert.equal(done,false);assert.equal(f.baseline().activeRecords>0,true);commit.resolve(true);await drain;assert.equal(f.baseline().activeRecords,0);}finally{await f.close();}
});
test('repair review validates exact immutable target; refused review grants no upload or repair',async()=>{
 const f=fixture();try{await f.inspect();f.state.review={...review(),assetVersion:'8'};f.click('Review exact repair '+ref.hash);await f.idle();assert.equal(f.flow.review,null);assert.match(f.flow.error,/changed/);f.route(path=>{if(path.includes('/relink/'))throw Error('REPAIR_REVIEW_UNAVAILABLE');});f.click('Review exact repair '+ref.hash);await f.idle();assert.equal(f.flow.review,null);assert.equal(f.flow.error,'REPAIR_REVIEW_UNAVAILABLE');assert.deepEqual(f.uploads,[]);assert.equal(f.calls.filter(call=>call.method==='POST').length,0);assert.deepEqual(f.commands,[]);}finally{await f.close();}
});
test('a mismatching selected length retains the target and refuses upload; ordinary import remains explicit',async()=>{
 const f=fixture();try{await f.prepare();const exact=f.flow.review;await f.select(new File([new Uint8Array([1])],'wrong.bin'));assert.equal(f.flow.review,exact);assert.match(f.flow.error,/different length/);assert.equal(f.control('Relink exact file').disabled,true);assert.deepEqual(f.uploads,[]);assert.deepEqual(f.commands,[]);assert.equal(f.control('Import as a new asset').disabled,false);}finally{await f.close();}
});
test('same-length wrong hash cannot submit repair or replace the existing asset identity',async()=>{
 const f=fixture();try{await f.prepare();const expected=f.flow.review;await f.select(new File([new Uint8Array([4,3,2,1])],'wrong.bin'));f.click('Relink exact file');await f.idle();assert.equal(f.uploads.length,1);assert.equal(f.commands.length,0);assert.equal(f.flow.review,expected);assert.equal(f.flow.dependencies.asset.version,'7');assert.match(f.flow.error,/different hash/);assert.equal(f.calls.some(call=>call.path.startsWith('/api/v1/assets/staging/')),false);}finally{await f.close();}
});
test('exact repair posts the completed staging version and verifies matching physical result before refresh',async()=>{
 const f=fixture();try{await f.prepare();await f.select(exactFile());const accepted=f.flow.review;f.click('Relink exact file');await f.idle();assert.equal(f.flow.error,'');assert.equal(f.uploads.length,1);assert.equal(f.uploads[0].purpose,'text');assert.equal(f.uploads[0].mediaType,'application/octet-stream');assert.equal(f.uploads[0].existing,undefined);const posts=f.calls.filter(call=>call.method==='POST');assert.equal(posts.length,1);assert.equal(posts[0].path,'/api/v1/storage/assets/asset_one/relink');const posted=JSON.parse(posts[0].body);assert.match(posted.operationId,/^[a-f0-9-]{36}$/);assert.deepEqual(posted,{protocolVersion:1,operationId:posted.operationId,reviewId:accepted.reviewId,reviewHash:accepted.reviewHash,stagingId:'stage_one',expectedStagingVersion:'12'});assert.deepEqual(f.commands,[]);assert.equal(f.calls.some(call=>call.path==='/api/v1/assets/staging/stage_one'),true);assert.equal(f.calls.at(-1).path,'/api/v1/storage');assert.equal(f.flow.review,null);assert.equal(f.flow.file,null);assert.equal(f.flow.prepared,null);assert.equal(f.flow.repairResult.status,'restored');assert.match(f.flow.message,/identity, version and history are unchanged/);const text=rendered(f.flow).text;assert.match(text,/storage inventory refreshes after repair/);assert.match(text,/current canvas is not reloaded automatically/);assert.match(text,/Close Library, choose Close document, then Open the retained document/);assert.match(text,/Repairing one reference does not verify the other dependencies/);assert.match(text,/prepare a fresh native text preview/);}finally{await f.close();}
});
for(const patch of [{ownerClientId:'other'},{version:'NaN'},{version:12},{committedOffset:'3'},{state:'receiving'},{sha256:'sha256:'+'0'.repeat(64)}])test('changed staged '+Object.keys(patch)[0]+'='+JSON.stringify(Object.values(patch)[0])+' refuses repair before POST',async()=>{
 const f=fixture();try{await f.prepare();await f.select(exactFile());f.state.stage=stage(patch);f.click('Relink exact file');await f.idle();assert.equal(f.calls.filter(call=>call.method==='POST').length,0);assert.equal(f.commands.length,0);assert.match(f.flow.error,/staged file changed/);assert.ok(f.flow.review);}finally{await f.close();}
});
for(const patch of [{operationId:'other_operation'},{assetVersion:'8'},{previousCondition:'corrupt'},{ref:{...ref,hash:'sha256:'+'0'.repeat(64)}}])test('wrong physical result '+Object.keys(patch)[0]+' cannot claim success or discard retry identity',async()=>{
 const f=fixture();try{await f.prepare();await f.select(exactFile());const expected=f.flow.review;f.route((path,init)=>init?.method==='POST'?{protocolVersion:1,operationId:JSON.parse(init.body).operationId,status:'restored',assetId:asset.id,assetVersion:asset.version,ref,previousCondition:'missing',...patch}:undefined);f.click('Relink exact file');await f.idle();assert.equal(f.flow.review,expected);assert.ok(f.flow.error);assert.equal(f.flow.repairResult,null);assert.ok(f.flow.prepared);assert.equal(f.calls.at(-1).path,'/api/v1/storage/assets/asset_one/relink');assert.deepEqual(f.commands,[]);}finally{await f.close();}
});
test('manual retry after a lost repair response preserves nonce and exact stage without a second upload',async()=>{
 const f=fixture();try{await f.prepare();await f.select(exactFile());let attempts=0;f.route((path,init)=>{if(init?.method!=='POST')return;if(++attempts===1)throw Error('REPAIR_RESPONSE_LOST');return {protocolVersion:1,operationId:JSON.parse(init.body).operationId,status:'already-available',assetId:asset.id,assetVersion:asset.version,ref,previousCondition:'available'};});f.click('Relink exact file');await f.idle();const retained=f.flow.prepared;assert.ok(retained);assert.equal(f.flow.error,'REPAIR_RESPONSE_LOST');assert.equal(f.flow.repairResult,null);assert.equal(attempts,1);assert.match(rendered(f.flow).text,/same physical repair request/);f.click('Relink exact file');await f.idle();const posts=f.calls.filter(call=>call.method==='POST');assert.equal(posts.length,2);assert.equal(posts[0].body,posts[1].body);assert.equal(f.uploads.length,1);assert.equal(f.calls.filter(call=>call.path==='/api/v1/assets/staging/stage_one').length,1);assert.equal(f.flow.repairResult.status,'already-available');assert.equal(f.flow.prepared,null);assert.deepEqual(f.commands,[]);}finally{await f.close();}
});
test('existing present-unverified and wrong-length objects can be reviewed for exact corrupt repair',async()=>{
 for(const availability of ['present-unverified','unavailable']){const f=fixture();try{f.state.dependencies=dependencies({items:[{kind:'object',id:ref.hash,label:'Expected bytes',relation:'expected-object',ref,availability}]});f.state.review={...review(),condition:'corrupt'};await f.prepare();assert.equal(f.flow.review.condition,'corrupt');assert.match(rendered(f.flow).text,/Exact file repair: corrupt/);await f.select(exactFile());f.click('Relink exact file');await f.idle();assert.equal(f.flow.repairResult.previousCondition,'corrupt');assert.equal(f.flow.repairResult.status,'restored');assert.deepEqual(f.commands,[]);}finally{await f.close();}}
});
test('a verified available review reports Already available and exposes no repair upload or POST',async()=>{
 const f=fixture();try{f.state.review={...review(),condition:'available'};await f.prepare();assert.equal(f.flow.review.condition,'available');assert.match(rendered(f.flow).text,/Already available/);assert.equal(rendered(f.flow).controls.some(control=>control.name==='Exact repair file'||control.name==='Relink exact file'),false);assert.deepEqual(f.uploads,[]);assert.equal(f.calls.filter(call=>call.method==='POST').length,0);}finally{await f.close();}
});
test('owner change or a competing mutation during upload fences repair and retains no late result',async()=>{
 for(const mutate of [f=>{f.editor.documentEpoch++;},f=>{f.editor.view.busy=true;}]){const f=fixture(),gate=f.gate();try{await f.prepare();await f.select(exactFile());f.upload(()=>gate.promise);f.click('Relink exact file');await until(()=>f.uploads.length===1);mutate(f);gate.resolve();await f.idle();assert.equal(f.commands.length,0);assert.equal(f.calls.some(call=>call.path.startsWith('/api/v1/assets/staging/')),false);}finally{await f.close();}}
});
test('Close signals the upload boundary and waits for its returned real model to retire',async()=>{
 const f=fixture(),gate=f.gate();try{await f.prepare();await f.select(exactFile());f.upload(()=>gate.promise);f.click('Relink exact file');await until(()=>f.uploads.length===1);let done=false;const drain=f.flow.releaseDocument().then(()=>{done=true;});assert.equal(f.uploads[0].signal.aborted,true);await Promise.resolve();assert.equal(done,false);gate.resolve();await drain;assert.equal(f.commands.length,0);assert.equal(f.baseline().activeRecords,0);}finally{await f.close();}
});
test('restore and new-import handoffs wait for render drain outside tracked operations',async()=>{
 for(const [label,kind]of [['Restore copy as a new project','restore'],['Import as a new asset','import']]){const f=fixture(),commit=f.gate();try{await f.flow.open();f.commit(commit.promise);f.click(label);await until(()=>f.flow.handoff!==null);assert.equal(f.callbacks.length,0);commit.resolve(true);await until(()=>f.callbacks.length===1);assert.equal(f.callbacks[0].kind,kind);assert.deepEqual(f.callbacks[0].lifecycle,{models:0,reads:0,pending:0,cleanupFailures:0});assert.equal(f.calls.filter(call=>call.method==='POST').length,0);assert.deepEqual(f.commands,[]);}finally{await f.close();}}
});
test('late-vetoed or owner-changed recovery handoff never opens another workflow',async()=>{
 const f=fixture(),commit=f.gate();try{await f.flow.open();const veto=f.click('Restore copy as a new project');veto.defaultPrevented=true;await f.idle();assert.deepEqual(f.callbacks,[]);f.commit(commit.promise);f.click('Restore copy as a new project');await until(()=>f.flow.handoff!==null);f.setIdentity('other');commit.resolve(true);await until(()=>f.flow.handoff===null);assert.deepEqual(f.callbacks,[]);}finally{await f.close();}
});

test('late file proposals and vetoed file changes cannot replace the explicitly selected repair bytes',async()=>{
 const f=fixture();try{await f.prepare();const control=f.control('Exact repair file'),selected=exactFile();await f.select(selected);const stale=f.fileEvent([new File([content],'late.bin')]);control.change(stale);await Promise.resolve();assert.equal(f.flow.file,selected);assert.equal(stale.currentTarget.files[0],selected);const obsoleteFile=new File([content],'obsolete.bin'),obsolete=f.event({files:[obsoleteFile]});control.change(obsolete);await Promise.resolve();assert.equal(obsolete.currentTarget.files[0],obsoleteFile);assert.equal(f.flow.file,selected);const current=f.control('Exact repair file'),veto=f.fileEvent([new File([content],'veto.bin')]);current.change(veto);veto.defaultPrevented=true;await Promise.resolve();assert.equal(f.flow.file,selected);assert.equal(f.flow.prepared,null);assert.deepEqual(f.uploads,[]);}finally{await f.close();}
});
test('lost repair response preserves result ownership and Close aborts a pending physical POST without claiming success',async()=>{
 const f=fixture(),gate=f.gate();let posted;try{await f.prepare();await f.select(exactFile());f.route(async(path,init)=>{if(init?.method==='POST'){posted=init;await gate.promise;return {protocolVersion:1,operationId:JSON.parse(init.body).operationId,status:'restored',assetId:asset.id,assetVersion:asset.version,ref,previousCondition:'missing'};}});f.click('Relink exact file');await until(()=>!!posted);let done=false;const drain=f.flow.releaseDocument().then(()=>{done=true;});assert.equal(posted.signal.aborted,true);await Promise.resolve();assert.equal(done,false);gate.resolve();await drain;assert.equal(f.flow.repairResult,null);assert.equal(f.flow.review,null);assert.equal(f.baseline().activeRecords,0);assert.deepEqual(f.commands,[]);}finally{await f.close();}
});

test('Refresh after a released view binds a new owner so principal changes retire its retained metadata',async()=>{
 const f=fixture();try{await f.flow.open();await f.flow.releaseDocument();assert.equal(f.flow.owner,null);f.click('Refresh storage');await f.idle();assert.ok(f.flow.summary);assert.ok(f.flow.owner);assert.equal(f.baseline().activeRecords>0,true);f.setIdentity('other');rendered(f.flow);await f.flow.models.release();assert.equal(f.flow.summary,null);assert.equal(f.flow.owner,null);assert.equal(f.baseline().activeRecords,0);}finally{await f.close();}
});

test('All registered assets exposes font and metadata references; exact font restoration requires the server review and no editor command',async()=>{
 const f=fixture(),font={...asset,id:'font_one',purpose:'font',qualification:'font'},metadata={...asset,id:'metadata_one',purpose:'text',qualification:'opaque-text'};try{f.state.assets=assetPage({category:'all',items:[font,metadata],nextCursor:null,complete:true});f.state.dependencies=dependencies({asset:font});f.state.review={...review(),assetId:font.id,condition:'corrupt'};await f.flow.open();f.click('Inspect All registered assets');await f.idle();assert.equal(f.calls.at(-1).path,'/api/v1/storage/assets?category=all');assert.equal(f.control('Inspect dependencies for metadata_one').disabled,false);f.click('Inspect dependencies for font_one');await f.idle();const captured=f.flow.dependencies.asset;f.route(path=>{if(path.includes('/relink/'))throw Error('FONT_PROFILE_UNSUPPORTED');});f.click('Review exact repair '+ref.hash);await f.idle();assert.equal(f.flow.review,null);assert.equal(f.flow.error,'FONT_PROFILE_UNSUPPORTED');assert.deepEqual(f.uploads,[]);assert.equal(f.calls.filter(call=>call.method==='POST').length,0);f.route(undefined);f.click('Review exact repair '+ref.hash);await f.idle();assert.equal(f.flow.review.assetId,font.id);await f.select(exactFile());f.route((path,init)=>path==='/api/v1/storage/assets/font_one/relink'&&init?.method==='POST'?{protocolVersion:1,operationId:JSON.parse(init.body).operationId,status:'restored',assetId:font.id,assetVersion:font.version,ref,previousCondition:'corrupt'}:undefined);f.click('Relink exact file');await f.idle();assert.equal(f.flow.repairResult.assetId,font.id);assert.equal(f.flow.repairResult.assetVersion,font.version);assert.equal(f.flow.repairResult.status,'restored');assert.deepEqual(captured,font);assert.deepEqual(f.commands,[]);assert.match(rendered(f.flow).text,/adds no font trust/);assert.equal(f.calls.filter(call=>call.method==='POST').length,1);}finally{await f.close();}
});
