import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,writeFileSync,mkdirSync,mkdtempSync,chmodSync,unlinkSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {busyStateObserver} from './busy-state.mjs';
import {emptyNative} from './empty-native.mjs';
import {canonical,hashBytes} from '../../../dist/local/server/storage/canonical.js';
const saved=JSON.parse(readFileSync(new URL('./busy-state312.json',import.meta.url))),base=resolve(process.env.EDITOR_RECEIPT,'busy-state-fixtures');mkdirSync(base,{recursive:true});
function fixture(image=false,named=false){
 const root=mkdtempSync(join(base,'case-'));chmodSync(root,0o700);const db=new DatabaseSync(join(root,'metadata.sqlite'));db.exec('CREATE TABLE documents(id TEXT,json TEXT); CREATE TABLE commands(id TEXT,original TEXT,receipt TEXT)');
 const document=structuredClone(saved.document),created=structuredClone(saved.created),held=structuredClone(saved.held);let active=true;const request={method:()=> 'POST',url:()=>saved.origin+'/api/v1/commands',postData:()=>JSON.stringify({protocolVersion:1,command:held})};
 if(named){created.body={type:'CreateDocument',name:'Busy witness',width:document.width,height:document.height,background:{kind:'transparent'}};document.metadata={schemaVersion:1,name:created.body.name,creationBackground:created.body.background};}
 const update=()=>{db.exec('DELETE FROM documents');db.prepare('INSERT INTO documents VALUES (?,?)').run(document.id,canonical(document));};
 const put=(state)=>{const text=canonical(state),ref={hash:hashBytes(text),byteLength:String(Buffer.byteLength(text)),mediaType:'application/json'},dir=join(root,'objects','sha256',ref.hash.slice(7,9));mkdirSync(dir,{recursive:true,mode:0o700});for(const p of [join(root,'objects'),join(root,'objects','sha256'),dir])chmodSync(p,0o700);const path=join(dir,ref.hash.slice(7));writeFileSync(path,text,{mode:0o600});document.image={state:ref,semanticDigest:hashBytes(canonical({...state,layers:state.layers.map(({version,...l})=>l)})),compositeAssetId:null};document.redo=null;document.orderedLayerIds=state.layers.map(l=>l.id);return path;};
 if(image)put({schemaVersion:1,width:360,height:200,layers:[]});update();db.prepare('INSERT INTO commands VALUES (?,?,?)').run(created.commandId,JSON.stringify({protocolVersion:1,command:created}),JSON.stringify(saved.receipt));
 return {root,db,document,created,held,request,update,put,stop:()=>active=false,observe:()=>busyStateObserver({root,origin:saved.origin,request,created,held:()=>active}),close:()=>db.close()};
}
function assertPair(before,after,command){
 const origin=saved.origin,url=origin+'/api/v1/commands',q={id:1,url,method:'POST',originalRequestObject:true,frameExposure:{ownerPage:true,ownerContext:true},redirectedFrom:null,redirectedTo:null};
 const x={page:{origin},requests:[q],responses:[{requestId:1,url,originalRequestObject:true,originalPairConfirmed:true,fromServiceWorker:false}],terminals:[{requestId:1,url,originalRequestObject:true}],server:[],network:[]},e={epoch:'epoch',mode:'EMPTY-NATIVE',fixture:'busy-actions',operations:[],proofs:[],workers:{rows:[]},nativeClosed:{rows:[]},discovery:[]};
 const routes=[{epoch:'epoch',requestId:1,originalRouteRequest:true,command,hold:1,release:2,continueStarted:3,continueFulfilled:4,publicBefore:{previewDisabled:true,applyDisabled:true,cancelDisabled:false,text:'Keep this draft during checkpoint',acceptedNative:before},publicAfter:{editorHidden:true,stillHeld:true,acceptedNative:after,commands:[]}}];
 return emptyNative(x,e,routes);
}
for(const image of [false,true])test('actual read-only DB/object observer accepts '+(image?'validated referenced image':'retained312 valid blank shape'),()=>{const f=fixture(image);try{const observe=f.observe(),before=observe(),after=observe();assert.deepEqual(before.document,f.document);assert.deepEqual(before.image,{schemaVersion:1,width:360,height:200,layers:[]});assert.equal(assertPair(before,after,f.held).qualified,false);}finally{f.close();}});
test('actual image observer refuses BOM with otherwise valid object and semantic identities',()=>{const f=fixture(true);try{const state={schemaVersion:1,width:360,height:200,layers:[]},bytes=Buffer.from('\ufeff'+canonical(state)),ref=f.document.image.state;ref.hash=hashBytes(bytes);ref.byteLength=String(bytes.length);const dir=join(f.root,'objects','sha256',ref.hash.slice(7,9));mkdirSync(dir,{recursive:true,mode:0o700});writeFileSync(join(dir,ref.hash.slice(7)),bytes,{mode:0o600});f.update();assert.equal(ref.hash,hashBytes(bytes));assert.equal(ref.byteLength,String(bytes.length));assert.equal(f.document.image.semanticDigest,hashBytes(canonical(state)));assert.throws(()=>f.observe()());}finally{f.close();}});
for(const [name,change]of Object.entries({missing:f=>f.db.exec('DELETE FROM documents'),duplicate:f=>f.db.prepare('INSERT INTO documents VALUES (?,?)').run(f.document.id,canonical(f.document)),wrongId:f=>{f.document.id='foreign';f.update();},wrongRevision:f=>{f.document.revision='7';f.update();},malformed:f=>f.db.exec("UPDATE documents SET json='{}'"),rowIdentity:f=>f.db.exec("UPDATE documents SET id='foreign'"),createdIdentity:f=>f.created.documentId='foreign',heldIdentity:f=>f.held.documentId='foreign',heldRevision:f=>f.held.expectedDocumentRevision='9',heldKind:f=>f.held.body.type='Undo',released:f=>f.stop(),missingCreation:f=>f.db.exec('DELETE FROM commands'),duplicateCreation:f=>f.db.exec('INSERT INTO commands SELECT * FROM commands'),badCreation:f=>f.db.exec("UPDATE commands SET receipt='{}'"),wrongSize:f=>{f.document.width++;f.update();},nullImage:f=>{f.document.image=null;f.update();}}))test('actual busy observer refuses '+name,()=>{const f=fixture();try{change(f);assert.throws(()=>f.observe()());}finally{f.close();}});
for(const [name,change]of Object.entries({missing:f=>unlinkSync(f.objectPath),corrupt:f=>writeFileSync(f.objectPath,'corrupt'),wrongHash:f=>{f.document.image.state.hash='sha256:'+'0'.repeat(64);f.update();},wrongLength:f=>{f.document.image.state.byteLength='1';f.update();},malformedReference:f=>{f.document.image.state={};f.update();},wrongSemantic:f=>{f.document.image.semanticDigest='sha256:'+'0'.repeat(64);f.update();},invalidState:f=>{f.put({schemaVersion:1,width:360,height:200,layers:'bad'});f.update();},mismatchedSize:f=>{f.put({schemaVersion:1,width:359,height:200,layers:[]});f.update();},noncanonical:f=>{const text=JSON.stringify({schemaVersion:1,width:360,height:200,layers:[]},null,2);const ref=f.document.image.state;ref.hash=hashBytes(text);ref.byteLength=String(Buffer.byteLength(text));const dir=join(f.root,'objects','sha256',ref.hash.slice(7,9));mkdirSync(dir,{mode:0o700});writeFileSync(join(dir,ref.hash.slice(7)),text,{mode:0o600});f.update();}}))test('actual image reference refuses '+name,()=>{const f=fixture(true);try{const ref=f.document.image.state;f.objectPath=join(f.root,'objects','sha256',ref.hash.slice(7,9),ref.hash.slice(7));if(name==='invalidState'){f.put({schemaVersion:99,width:360,height:200,layers:[]});f.update();}else change(f);assert.throws(()=>f.observe()());}finally{f.close();}});
for(const [name,change]of Object.entries({revision:f=>f.document.revision='2',history:f=>f.document.historyHead='different-history',checkpoint:f=>f.document.checkpoint='different-checkpoint',branch:f=>f.document.branchId='different-branch',dimensions:f=>f.document.height=201,image:f=>f.put({schemaVersion:1,width:360,height:200,layers:[]}),layers:f=>f.put({schemaVersion:1,width:360,height:200,layers:[{id:'layer',version:'1',kind:'image',name:'Changed',assetId:'asset',layerToDocument:[1,0,0,1,0,0],opacity:1,visible:true,locked:false,blend:'normal',mask:null}]})}))test('full EMPTY-NATIVE witness refuses changed '+name,()=>{const f=fixture();try{const observe=f.observe(),before=observe();change(f);f.update();assert.throws(()=>assertPair(before,observe(),f.held));}finally{f.close();}});

for(const image of [false,true])test('named transparent UI creation preserves exact metadata '+(image?'with referenced empty image':'without an image field'),()=>{const f=fixture(image,true);try{const observe=f.observe(),before=observe();assert.deepEqual(before.creation.command.body,f.created.body);assert.deepEqual(before.document.metadata,{schemaVersion:1,name:'Busy witness',creationBackground:{kind:'transparent'}});assert.deepEqual(before,observe());}finally{f.close();}});
for(const [name,change]of Object.entries({name:f=>f.document.metadata.name='Different name',background:f=>f.document.metadata.creationBackground={kind:'solid',color:[255,255,255,255],layerId:'other'},color:f=>f.document.color='DisplayP3',depth:f=>f.document.depth=16}))test('named creation witness refuses changed '+name,()=>{const f=fixture(true,true);try{change(f);f.update();assert.throws(()=>f.observe()());}finally{f.close();}});
