import assert from 'node:assert/strict';
import {isDeepStrictEqual} from 'node:util';
import {EXPECTED,POLICY,ApplicationCollector,auditTraffic,headers,serverHeaders,assertNoWorkerCommands} from './app-buffer-core.mjs';
const same=(a,b)=>isDeepStrictEqual(headers(a),headers(b));
const one=(a,label)=>{assert.equal(a.length,1,label);return a[0];};
const subset=(a,b)=>{for(const [k,v]of Object.entries(headers(a)))assert.equal(headers(b)[k],v,'Server/optional header contradiction '+k);};
export function perfectMatching(edges,n){
  assert.equal(edges.length,n,'All originals/candidates represented');assert(n>0);const matches=Array(n).fill(-1);
  for(const row of edges){assert.equal(new Set(row).size,row.length,'Duplicate compatibility edge');for(const j of row)assert(Number.isInteger(j)&&j>=0&&j<n,'Candidate outside closed group');}
  function place(i,seen){for(const j of edges[i]){assert(Number.isInteger(j)&&j>=0&&j<n);if(seen.has(j))continue;seen.add(j);if(matches[j]===-1||place(matches[j],seen)){matches[j]=i;return true;}}return false;}
  for(let i=0;i<n;i++)assert(place(i,new Set()),'No exhaustive admissible bijection');return matches;
}
export function closedWasmGroup(x,{negative=false}={}) {
  const {page,requests,responses,terminals,network,server}=x;assertNoWorkerCommands(x.commands);assert.equal(x.epoch,x.currentEpoch);assert(x.epoch);assert(x.closedBeforeNavigation);assert(x.collector.installed&&!x.collector.disabled);assert.deepEqual(x.collector.owner,page);
  assert.equal(x.recorder.installed,true);assert.deepEqual(x.recorder.failures,[]);assert.equal(x.recorder.servers,1);assert.equal(x.recorder.pid,x.serverOwner.pid);assert.equal(x.serverOwner.origin,page.origin);assert(server.every(r=>r.pid===x.serverOwner.pid));
  const accounting=auditTraffic(x),url=page.origin+EXPECTED.wasmPath,originals=requests.filter(q=>q.url===url);assert(originals.length>0);assert.equal(new Set(originals.map(q=>q.id)).size,originals.length);
  const pairs=originals.map(q=>{const p=one(responses.filter(p=>p.requestId===q.id),'Original response'),t=one(terminals.filter(t=>t.requestId===q.id),'Original terminal');assert.equal(q.method,'GET');assert.equal(q.resourceType,'fetch');assert.equal(p.status,200);assert.equal(p.actualHeaders['content-type'],'application/wasm');assert.equal(p.actualHeaders['content-length'],String(EXPECTED.wasmBytes));assert.equal(p.actualHeaders['cache-control'],'no-store');assert.equal(p.actualHeaders['referrer-policy'],'no-referrer');assert.equal(headers(q.actualHeaders).referer,undefined);
    if(!negative)assert(t.kind==='finished'||t.kind==='failed'&&t.failure?.errorText==='net::ERR_ABORTED','Only declared Chromium transport status');return {q,p,t};});
  const sr=server.filter(e=>e.kind==='request'&&new URL(e.url,page.origin).href===url);assert.equal(sr.length,pairs.length);
  for(const r of sr){assert(r.requestObject&&r.responseObject&&r.responseRequestSame);assert.equal(r.serverId,1);assert(Array.isArray(r.rawHeaders)&&r.rawHeaders.length%2===0);const raw={};for(let i=0;i<r.rawHeaders.length;i+=2){const k=r.rawHeaders[i].toLowerCase();assert(!(k in raw),'Duplicate original raw header');raw[k]=r.rawHeaders[i+1];}assert(same(raw,r.headers));
    const candidates=pairs.filter(v=>same(v.q.actualHeaders,r.headers));assert(candidates.length);const finishes=server.filter(e=>e.id===r.id&&e.kind==='response'),closes=server.filter(e=>e.id===r.id&&e.kind==='response-close');assert(finishes.length<=1&&closes.length<=1);if(!negative){assert.equal(finishes.length,1);assert.equal(closes.length,1);}for(const e of [...finishes,...closes]){assert(e.originalObjects);assert.equal(e.status,200);if(!negative)assert(e.writableFinished);for(const c of candidates)subset(serverHeaders(e.headers),c.p.actualHeaders);}
    assert(server.some(e=>e.id===r.id&&e.kind==='header-return'&&e.name==='writeHead'&&e.sameResponseObject&&e.headersSent&&e.status===200));assert(!server.some(e=>e.id===r.id&&e.kind==='header-throw'));}
  for(const v of pairs)assert(!requests.some(q=>q.url!==url&&same(q.actualHeaders,v.q.actualHeaders)&&responses.some(p=>p.requestId===q.id&&p.status===v.p.status&&same(p.actualHeaders,v.p.actualHeaders))),'Outside same-fingerprint competitor');
  const candidates=[];
  for(const id of new Set(network.map(e=>e.params.requestId).filter(Boolean))){const rows=network.filter(e=>e.params.requestId===id),re=rows.filter(e=>e.name==='Network.requestWillBeSentExtraInfo'),pe=rows.filter(e=>e.name==='Network.responseReceivedExtraInfo'),starts=rows.filter(e=>e.name==='Network.requestWillBeSent'),regular=rows.filter(e=>e.name==='Network.responseReceived');
    const knownURLs=[...starts.map(e=>e.params.request.url),...regular.map(e=>e.params.response.url)];assert(!knownURLs.length||new Set(knownURLs).size===1,'Contradictory request URL');if(knownURLs.length&&knownURLs[0]!==url)continue;
    const possible=knownURLs.includes(url)||re.some(e=>pairs.some(v=>same(e.params.headers,v.q.actualHeaders)))&&(!pe.length||pe.some(e=>pairs.some(v=>e.params.statusCode===v.p.status&&same(e.params.headers,v.p.actualHeaders))));if(!possible)continue;
    const a=one(re,'Mandatory same-ID request ExtraInfo'),b=one(pe,'Mandatory same-ID response ExtraInfo');assert.equal(starts.length<=1,true);assert.equal(regular.length<=1,true);assert(!rows.some(e=>e.name==='Network.requestServedFromCache'));
    const compatible=pairs.map((v,i)=>same(a.params.headers,v.q.actualHeaders)&&b.params.statusCode===v.p.status&&same(b.params.headers,v.p.actualHeaders)?i:-1).filter(i=>i>=0);assert(compatible.length,'Contradictory candidate');
    const terminal=rows.filter(e=>['Network.loadingFinished','Network.loadingFailed'].includes(e.name));assert(terminal.length<=1);for(const i of compatible){const v=pairs[i];for(const e of starts){assert.equal(e.params.request.method,'GET');assert.equal(e.params.redirectResponse,undefined);subset(e.params.request.headers??{},v.q.actualHeaders);}for(const e of regular){assert.equal(e.params.response.status,200);subset(e.params.response.headers,v.p.actualHeaders);for(const k of ['fromDiskCache','fromServiceWorker','fromPrefetchCache'])assert(e.params.response[k]!==true);}for(const e of terminal){assert.equal(v.t.kind,e.name==='Network.loadingFinished'?'finished':'failed');if(e.name==='Network.loadingFailed')assert.equal(e.params.errorText,v.t.failure?.errorText);}}
    candidates.push({requestId:id,compatibleOriginals:compatible,rows});
  }
  assert.equal(new Set(candidates.map(c=>c.requestId)).size,candidates.length);assert.equal(candidates.length,pairs.length,'All candidate bodies belong to the exhaustive bijection');const edges=pairs.map((_,i)=>candidates.flatMap((c,j)=>c.compatibleOriginals.includes(i)?[j]:[]));perfectMatching(edges,pairs.length);
  assert(pairs.length*EXPECTED.wasmBytes<=POLICY.maxTotalBufferSize,'Group exceeds declared collector bound');
  return {passed:true,epoch:x.epoch,owningPage:page,originals:pairs,candidates,edges,accounting,association:'universal closed group; no particular ambiguous assignment claimed'};
}
export class CompletionCollector extends ApplicationCollector {
  constructor(options){super(options);this.saveBody=options.saveBody??(()=>{});}
  async retrieveGroup(group){assert(group.passed);assert.deepEqual(group.owningPage,this.row.owner);assert.equal(this.row.group,undefined,'Closed group assessed once');this.row.group={epoch:group.epoch,requestIds:group.candidates.map(c=>c.requestId),captures:[]};let total=0;
    const errors=[];
    for(const c of group.candidates){
      const per=new ApplicationCollector({send:this.send,owner:this.row.owner,verify:this.verify,expected:this.expected,now:this.now,sleep:this.sleep});per.row.installed=this.row.installed;per.row.attempted=true;
      const record={requestId:c.requestId,collector:per.row};this.row.group.captures.push(record);
      try{const capture=await per.retrieve({passed:true,requestId:c.requestId,terminal:group.originals[c.compatibleOriginals[0]].t,owningPage:group.owningPage});record.proof=capture.proof;if(capture.bytes){total+=capture.bytes.length;this.saveBody(c.requestId,capture.bytes);}assert(total<=POLICY.maxTotalBufferSize);assert.equal(capture.proof.matchesCompleteSealedWASM,true,'Every possible candidate must contain the complete sealed WASM');}
      catch(error){record.error=String(error);errors.push(error);}
    }
    if(errors.length)throw new AggregateError(errors,'Closed-group capture failed; every candidate attempt retained');
    return this.row.group;
  }
}
export function assessCohort(x,native,{negative=false}={}){
  const url=x.page.origin+EXPECTED.workerPath,workers=x.workerRows,created=x.discovery.filter(e=>e.name==='Target.targetCreated'&&e.params.targetInfo.type==='worker');assert(workers.length>0);assert.equal(created.length,workers.length);assert.equal(native.length,workers.length);assert.equal(new Set(native.map(n=>n.actionId)).size,native.length);assert.equal(new Set(created.map(e=>e.params.targetInfo.targetId)).size,created.length);
  const scripts=x.requests.filter(q=>q.url===url);assert.equal(scripts.length,workers.length);assert(workers.every(w=>w.url===url&&w.originalObject&&w.closed&&w.closeSameObject));const edges=[];
  for(const entry of created){const id=entry.params.targetInfo.targetId;const infos=x.discovery.filter(e=>e.params.targetInfo?.targetId===id).map(e=>e.params.targetInfo);assert(infos.some(t=>t.url===url));for(const t of infos){assert.equal(t.type,'worker');assert.equal(t.parentId,x.page.targetId);assert.equal(t.parentFrameId,x.page.frameId);assert.equal(t.browserContextId,x.page.contextId);if(t.url)assert.equal(t.url,url);}one(x.discovery.filter(e=>e.name==='Target.targetDestroyed'&&e.params.targetId===id),'Genuine original target destruction');
    const rows=x.network.filter(e=>e.params.requestId===id),a=one(rows.filter(e=>e.name==='Network.requestWillBeSentExtraInfo'),'Original script request'),b=one(rows.filter(e=>e.name==='Network.responseReceivedExtraInfo'),'Original script response');const compatible=[];
    scripts.forEach((q,i)=>{const p=one(x.responses.filter(p=>p.requestId===q.id),'Script original Response'),t=one(x.terminals.filter(t=>t.requestId===q.id),'Script original terminal');assert.equal(q.method,'GET');assert.equal(q.resourceType,'script');assert.equal(t.kind,'finished');assert.equal(p.actualHeaders['content-length'],String(EXPECTED.workerBytes));assert(/javascript/.test(p.actualHeaders['content-type']));assert.equal(headers(q.actualHeaders)['sec-fetch-dest'],'worker');if(same(a.params.headers,q.actualHeaders)&&b.params.statusCode===200&&same(b.params.headers,p.actualHeaders))compatible.push(i);});edges.push(compatible);
  }perfectMatching(edges,workers.length);assert(native.every(n=>negative?n.negativePassed&&!n.qualified:n.qualified),'Every possible native association must meet its declared fresh operation outcome');return {passed:true,workers:workers.length,actionIds:native.map(n=>n.actionId),association:'All possible native associations independently successful; no timestamp join'};
}
export function groupSignature(g){return {epoch:g.epoch,owner:g.owningPage,originals:g.originals.map(v=>({id:v.q.id,url:v.q.url,requestHeaders:headers(v.q.actualHeaders),responseHeaders:headers(v.p.actualHeaders),terminal:v.t})).sort((a,b)=>a.id-b.id),candidates:g.candidates.map(c=>({id:c.requestId,originalIds:c.compatibleOriginals.map(i=>g.originals[i].q.id).sort((a,b)=>a-b)})).sort((a,b)=>a.id.localeCompare(b.id))};}
export function qualifyCompletion({initial,final,captures,native,cohort,cleanup}){assert.deepEqual(groupSignature(final),groupSignature(initial),'Late contradiction invalidates provisional group');assert.equal(captures.epoch,initial.epoch);assert.deepEqual(captures.requestIds,initial.candidates.map(c=>c.requestId));assert.equal(captures.captures.length,initial.candidates.length);assert(captures.captures.every((c,i)=>c.requestId===captures.requestIds[i]&&c.proof?.matchesCompleteSealedWASM&&c.proof.bytes===EXPECTED.wasmBytes&&c.proof.sha256===EXPECTED.wasmSHA256));assert(native.length>0&&native.every(n=>n.qualified&&n.observedEOF===false));assert(cohort?.passed&&cohort.workers===native.length);assert.deepEqual(cohort.actionIds,native.map(n=>n.actionId));assert.equal(cleanup,true);return {qualified:true,transport:initial.originals.map(v=>v.t),browserBytes:captures.captures.map(c=>({requestId:c.requestId,...c.proof})),native,cohort,cleanup,label:'Transport status retained; application consumption established by the source contract',observedEOF:false};}
