import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
export function savedState(root,draftId){const db=new DatabaseSync(join(root,'metadata.sqlite'),{readOnly:true});try{const table=n=>db.prepare('SELECT json FROM '+n).all().map(r=>JSON.parse(String(r.json)));const documents=table('documents'),history=table('history'),uis=table('ui_checkpoints');const matches=uis.flatMap(ui=>ui.drafts.filter(d=>d.id===draftId).map(draft=>({ui,draft})));const read=ref=>{const b=readFileSync(join(root,'objects','sha256',ref.hash.slice(7,9),ref.hash.slice(7)));assert.equal(String(b.length),ref.byteLength);assert.equal('sha256:'+createHash('sha256').update(b).digest('hex'),ref.hash);return b;};let savedText=null;if(matches.length===1){const a=table('assets').find(a=>a.id===matches[0].draft.assetId);if(a){const value=JSON.parse(read(a.blob));savedText=read(value.textUtf8).toString('utf8');}}const doc=documents.length===1?documents[0]:undefined;const ref=doc?.image?.state;const image=ref?readFileSync(join(root,'objects','sha256',ref.hash.slice(7,9),ref.hash.slice(7))):null;return {savedText,accepted:{documents,history,imageSHA256:image?createHash('sha256').update(image).digest('hex'):null},draft:matches.length===1?matches[0]:null,document:doc};}finally{db.close();}}
export async function completionPublic({page,result,expect,beforePreview,mode,server,root,observerKey,until,requests,responses}){
  const actions=result.publicActions=[];const act=async(name,fn)=>{const row={name,started:new Date().toISOString()};actions.push(row);try{const v=await fn();row.state='fulfilled';return v;}catch(e){row.state='rejected';row.error=String(e);throw e;}finally{row.ended=new Date().toISOString();}};
  const click=name=>act(name,()=>page.getByRole('button',{name,exact:true}).click());await click('New');for(const [name,value]of [['Width (px)','360'],['Height (px)','200']])await act(name,async()=>{const f=page.getByRole('spinbutton',{name,exact:true});await f.fill(value);await f.press('Tab');await expect(f).toHaveValue(value);});await click('Create');await click('Text');
  const input=page.locator('#native-text-content'),region=page.locator('#native-text-editor');await expect(input).toHaveCount(1);await expect(region).toBeVisible({timeout:22000});await expect(input).toBeVisible();await expect(input).toBeEditable();const node=await input.elementHandle();assert(node);
  const observe=()=>node.evaluate(el=>{const r=el.closest('#native-text-editor');return {sameTextarea:el===document.querySelector('#native-text-content'),connected:el.isConnected,editable:!el.disabled&&!el.readOnly,draftId:r?.getAttribute('data-session'),revision:r?.getAttribute('data-revision'),value:el.value,ready:r?.textContent?.includes('Text preview ready. Accepted appearance is unchanged.')??false};});
  try{await act('Original exact font',()=>node.fill('Original exact font'));const before=await observe();assert(before.sameTextarea&&before.connected&&before.editable&&before.draftId&&!before.ready);
    await expect.poll(()=>{const s=savedState(root,before.draftId);return !!s.draft&&s.draft.draft.status==='saved-unapplied'&&s.draft.draft.documentId===s.document?.id&&s.savedText==='Original exact font';},{timeout:15000}).toBe(true);
    const saved=savedState(root,before.draftId);const action={id:randomUUID(),kind:'Preview',text:'Original exact font',draftId:before.draftId,revision:before.revision,documentId:saved.document.id,documentRevision:saved.document.revision,sessionId:saved.draft.ui.sessionId,generation:Number(saved.draft.draft.generation),beforeReady:false};result.action=action;result.acceptedBefore=saved.accepted;
    await beforePreview();await page.evaluate(({key,action})=>globalThis[key].begin(action),{key:observerKey,action});await click('Preview text');
    if(mode==='valid'){await expect(region.getByText('Text preview ready. Accepted appearance is unchanged.',{exact:true})).toBeVisible({timeout:22000});result.publicPreviewReady={at:new Date().toISOString(),previewCalls:1,applyCalls:0};}
    else if(mode==='cancelled'){
      await expect(region.getByText('Preparing text layout…',{exact:true})).toBeVisible();await expect.poll(async()=>{const fs=await server.fault();return fs.length===1&&fs[0].written===16384&&!fs[0].released&&fs[0].withheldBytes>0;},{timeout:10000}).toBe(true);
      await until('Original held WASM response',()=>requests.filter(q=>q.url.endsWith(result.application.wasmPath)).length===1&&responses.some(p=>p.url.endsWith(result.application.wasmPath)));
      const obs=await page.evaluate(key=>globalThis[key].snapshot(),observerKey);assert.equal(obs.rows.filter(r=>r.kind==='created').length,1);assert(!obs.rows.some(r=>r.kind==='terminate'||r.kind==='post'||r.kind==='message'&&r.ok));const held=(await server.fault())[0];result.hold={activeAtInput:true,releasedBeforeTermination:false,cleanupBeforeTermination:false,originalRequests:1,originalResponse:true,bytesWritten:held.written,expectedBytes:held.expectedBytes,preparing:true,server:held};
      await page.evaluate(key=>globalThis[key].mark('partial-held',{}),observerKey);await expect(input).toBeEditable();await act('Trusted native input invalidation',()=>node.fill('Changed while preparation is pending'));await expect(region.getByText(/^TEXT_CANCELLED/)).toBeVisible({timeout:10000});
      const stopped=await page.evaluate(key=>globalThis[key].snapshot(),observerKey);assert.equal(stopped.rows.filter(r=>r.kind==='terminate-return').length,1);assert(!stopped.rows.some(r=>r.kind==='message'&&r.ok===true));assert.equal((await server.fault())[0].released,false);await page.evaluate(key=>globalThis[key].mark('cancelled-public',{}),observerKey);
      await expect.poll(()=>savedState(root,action.draftId).savedText,{timeout:15000}).toBe('Changed while preparation is pending');assert(Number(savedState(root,action.draftId).draft.draft.generation)>action.generation);
    }else await expect(region.getByText(/^TEXT_ENGINE_LOAD/)).toBeVisible({timeout:22000});
    const after=await observe(),savedAfter=savedState(root,action.draftId);result.publicAfter={...after,documentId:savedAfter.document.id,sessionId:savedAfter.draft.ui.sessionId,generation:Number(savedAfter.draft.draft.generation),cleanupStarted:false,error:mode==='valid'?null:mode==='cancelled'?'TEXT_CANCELLED':'TEXT_ENGINE_LOAD'};result.savedTextAfter=savedAfter.savedText;result.acceptedAfter=savedAfter.accepted;assert.deepEqual(result.acceptedAfter,result.acceptedBefore);assert.equal(after.draftId,action.draftId);await page.evaluate(key=>globalThis[key].end({}),observerKey);result.observation=await page.evaluate(key=>globalThis[key].snapshot(),observerKey);
  }finally{await node.dispose();}
}
