import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {DatabaseSync} from 'node:sqlite';
import {bundledFontIntent,selectNativeFont,adoptNativeInput,nativeDescriptor,nativeOpeningDescriptor,awaitNativeOpening,cancelAndReopenNativeFont,readDraftOccurrences} from './font-state.mjs';
import {monitorHarness} from './monitor-harness.mjs';
const clone=structuredClone,style={primaryFont:'old',explicitFallbacks:[],fontSize:20,color:[0,0,0,1]},source={style,frame:{width:360,height:100}};
function fixture(){
 const intent={...bundledFontIntent('NotoSansArabic',source,'مرحبا'),owner:{draftId:'draft',documentId:'doc',documentRevision:'2',sessionId:'session'}};
 const view={visible:true,regionHidden:false,sameTextarea:true,connected:true,editable:true,draftId:'draft',revision:'2',value:intent.text,ready:false};
 const saved={savedText:intent.text,savedGraph:clone(intent.graph),document:{id:'doc',revision:'2'},draft:{ui:{sessionId:'session'},draft:{id:'draft',documentId:'doc',expectedDocumentRevision:'2',generation:'2',status:'saved-unapplied'}},accepted:{document:'unchanged'}};
 return {intent,view,saved};
}
function assertions({tick=()=>{},visible=()=>{},enabled=()=>{},count=()=>{},hidden=()=>{},contains=()=>{}}={}){
 const calls=[];const expect=locator=>({async toBeVisible(){calls.push(['visible',locator]);await visible(locator);},async toContainText(text){calls.push(['contains',locator,text]);await contains(locator,text);},async toBeHidden(){calls.push(['hidden',locator]);await hidden(locator);},async toBeEnabled(){calls.push(['enabled',locator]);await enabled(locator);},async toHaveCount(n){calls.push(['count',locator,n]);await count(locator,n);}});
 expect.poll=(fn,options)=>({async toBe(value){calls.push(['poll',options]);for(let i=0;i<4;i++){await tick(i);if(await fn()===value)return;}throw Error('Original expectation deadline');}});return {expect,calls};
}
for(const [name,mutate]of Object.entries({font:x=>x.fonts[0].id='old',fontBytes:x=>x.fonts[0].bytes.hash='old',order:x=>x.fonts.reverse().push(clone(x.fonts[0])),primary:x=>x.style.primaryFont='old',fallback:x=>x.style.explicitFallbacks=['old'],style:x=>x.style.fontSize++,frame:x=>x.frame.width++,textBlob:x=>x.textUtf8.hash='old',extra:x=>x.unrequested=true}))test('full intended saved graph refuses '+name,async()=>{const f=fixture();mutate(f.saved.savedGraph);await assert.rejects(adoptNativeInput({...f,observe:async()=>clone(f.view),read:()=>clone(f.saved),expect:assertions().expect}),/deadline/);});
for(const faultRead of [1,2])for(const [name,mutate]of Object.entries({document:x=>x.document.id='foreign',revision:x=>x.document.revision='4',session:x=>x.draft.ui.sessionId='foreign',draft:x=>x.draft.draft.id='foreign',draftDocument:x=>x.draft.draft.documentId='foreign',draftRevision:x=>x.draft.draft.expectedDocumentRevision='8'}))test('capture permanently refuses foreign '+name+' at read '+faultRead,async()=>{const f=fixture();let reads=0;const read=()=>{const s=clone(f.saved);if(++reads===faultRead)mutate(s);return s;};await assert.rejects(adoptNativeInput({...f,observe:async()=>clone(f.view),read,expect:assertions().expect}),/owner|identity|revision/i);});
for(const [name,mutate]of Object.entries({replacement:x=>x.sameTextarea=false,disconnect:x=>x.connected=false,disabled:x=>x.editable=false,draft:x=>x.draftId='foreign',text:x=>x.value='changed',action:x=>x.ready=true}))test('refreshed public descriptor refuses '+name,async()=>{const f=fixture();let observations=0;await assert.rejects(adoptNativeInput({...f,observe:async()=>{const v=clone(f.view);if(++observations===2)mutate(v);return v;},read:()=>clone(f.saved),expect:assertions().expect}),/textarea|draft|text|operation/);});
test('completion before persistence waits for full graph then captures the fresh public revision',async()=>{const f=fixture();let persisted=false,observations=0;const a=assertions({tick:i=>{if(i===1){persisted=true;f.view.revision='3';}}});const read=()=>{const s=clone(f.saved);if(!persisted){s.savedGraph.fonts[0].bytes.hash='old';s.draft.draft.generation='1';}return s;};const result=await adoptNativeInput({...f,observe:async()=>{observations++;return clone(f.view);},read,expect:a.expect});assert.equal(observations,2);assert.equal(result.before.revision,'3');assert.equal(result.saved.draft.draft.generation,'2');assert.deepEqual(a.calls.filter(x=>x[0]==='poll'),[['poll',undefined]]);});
test('saved generation changing across fresh public observation is refused',async()=>{const f=fixture();let n=0;await assert.rejects(adoptNativeInput({...f,observe:async()=>clone(f.view),read:()=>{const s=clone(f.saved);if(++n===4)s.draft.draft.generation='3';return s;},expect:assertions().expect}),/unchanged across/);});
function publicDriver({failClick=false,deadline=false,fresh=false,reopened=false,foreignCommand=false,extraCommand=false}={}){
 const f=fixture(),events=[],commands=[];if(reopened){f.view.draftId='reopened';f.intent.owner.draftId='reopened';f.saved.draft.draft.id='reopened';}const current=clone(f.saved);if(fresh||reopened){f.saved.draft=null;f.saved.savedGraph=null;f.saved.savedText=null;}let done=false,resolveDone;const completion=new Promise(r=>resolveDone=r),node={evaluate:async fn=>{assert([nativeDescriptor,nativeOpeningDescriptor].includes(fn));return clone(f.view);},fill:async text=>{assert(done,'No edit while font action remains pending');events.push('fill');f.view.value=text;Object.assign(f.saved,current);},dispose:async()=>events.push('dispose')};
 const locator=name=>({name,evaluate:async fn=>node.evaluate(fn),elementHandle:async()=>node,getByText:pattern=>({name:'order',pattern})});
 const page={locator,getByText:(name,options)=>({name,options}),getByRole:(role,options)=>({role,...options,selectOption:async id=>events.push(['select',id]),click:async()=>{events.push('click');if(failClick)throw Error('Font action failed');const command={commandId:'import',clientId:'client',sessionId:'session',documentId:foreignCommand?'foreign':'doc',expectedDocumentRevision:'2',body:{type:'ImportFont',source:f.intent.graph.fonts[0].bytes,license:f.intent.graph.fonts[0].licenseRecord,origin:'bundled',embeddingReviewed:true}};commands.push(command);if(extraCommand)commands.push({...command,commandId:'duplicate'});}})};
 const a=assertions({visible:async l=>{events.push(['visible',l.name]);if(l.name.startsWith('Font substitution')){if(deadline)throw Error('Original expectation deadline');await completion;}else{assert(done);assert(l.pattern.test('Exact font order: NotoSansArabic. Retained appearance'));assert(!l.pattern.test('Exact font order: NotoSans → NotoSansArabic. Retained appearance'));}},enabled:async l=>{assert(done);assert.equal(l.name,'Preview text');events.push('enabled');}});
 return {f,events,a,page,commands,node,start:()=>selectNativeFont({page,expect:a.expect,read:()=>clone(f.saved),intent:f.intent,document:f.saved.document,acceptedText:f.view.value,commands:()=>commands}),complete:()=>{done=true;resolveDone();}};
}
test('actual selection driver awaits completion, exact order and enabled Preview before trusted text edit',async()=>{const d=publicDriver(),pending=d.start();for(let i=0;i<30;i++)await Promise.resolve();assert(d.events.includes('click'));assert(!d.events.includes('fill'));d.complete();const intent=await pending;assert.deepEqual(intent.owner,d.f.intent.owner);assert(d.events.indexOf('enabled')<d.events.indexOf('fill'));assert.equal(d.events.filter(x=>x==='click').length,1);assert.equal(d.events.at(-1),'dispose');});
for(const option of ['failClick','deadline'])test('actual selection driver preserves '+option+' and does not edit or retry',async()=>{const d=publicDriver({[option]:true});await assert.rejects(d.start(),/Font action failed|deadline/);assert(!d.events.includes('fill'));assert.equal(d.events.filter(x=>x==='click').length,1);assert.equal(d.events.at(-1),'dispose');});
test('actual monitor refreshes its action revision after saved polling',async()=>{const h=await monitorHarness();let reads=0;h.onReadState(()=>{if(++reads===2)h.ui.revision='8';});await h.preview();assert.equal(h.record().epochs[0].operations[0].action.revision,'8');});
test('unchanged positive native operation rejects post-capture revision mutation',async()=>{const h=await monitorHarness();await assert.rejects(h.monitor.operation('Preview',async()=>{await h.nativeSuccess();h.ui.revision='8';}),/8.*7|7.*8/s);assert.equal(h.record().epochs[0].operations[0].completed,undefined);});

for(const option of ['fresh','reopened'])test('actual driver and adoption accept '+option+' unsaved native draft without presave',async()=>{const d=publicDriver({[option]:true});assert.equal(d.f.saved.draft,null);d.complete();const intent=await d.start();const capture=await adoptNativeInput({intent,expect:d.a.expect,observe:async()=>clone(d.f.view),read:()=>clone(d.f.saved)});assert.equal(capture.owner.draftId,d.f.view.draftId);assert.equal(capture.owner.sessionId,'session');assert.equal(d.events.filter(x=>x==='fill').length,1);});
for(const option of ['foreignCommand','extraCommand'])test('fresh font command refuses '+option,async()=>{const d=publicDriver({[option]:true,fresh:true});d.complete();await assert.rejects(d.start(),/font action/i);assert(!d.events.includes('fill'));});

test('first post-action save may be pending without borrowing another draft',async()=>{const f=fixture();let persisted=false;const a=assertions({tick:i=>{if(i===1)persisted=true;}});const read=()=>persisted?clone(f.saved):{...clone(f.saved),draft:null,savedGraph:null,savedText:null};const result=await adoptNativeInput({...f,expect:a.expect,observe:async()=>clone(f.view),read});assert.equal(result.saved.draft.draft.id,'draft');});

function lifecycleDriver({cancelDeadline=false,clearDeadline=false,openDeadline=false,foreignClear=false,openFault,admissionFault}={}){
 const d=publicDriver(),previous=clone(d.f.intent),accepted=clone(d.f.saved.accepted),document=clone(d.f.saved.document),records=[];let phase='initial',cancelDone=false,cleared=false,openTicks=0,clearTicks=0,resolveCancel;const cancelled=new Promise(r=>resolveCancel=r);
 const getRole=d.page.getByRole;d.page.getByRole=(role,opts)=>{if(opts.name==='Cancel text edit')return {click:async()=>{assert.equal(phase,'initial');d.events.push('cancel');phase='cancel';}};if(opts.name==='Edit text')return {click:async()=>{assert(cancelDone&&cleared,'No premature Edit');assert.equal(phase,'cancel');d.events.push('edit');phase='opening';Object.assign(d.f.view,{visible:false,regionHidden:true,draftId:'',value:''});}};return getRole(role,opts);};
 const originalElement=d.page.locator;d.page.locator=name=>{const loc=originalElement(name);return {...loc,elementHandle:async()=>{d.events.push('handle');assert.equal(phase,'opening');const node=await loc.elementHandle();if(admissionFault)admissionFault(d.f.view);return node;}};};
 const a=assertions({contains:async(l,text)=>{assert.equal(l.name,'#native-text-editor');assert.equal(text,'Text draft cancelled. Accepted appearance is unchanged.');if(cancelDeadline)throw Error('Original expectation deadline');await cancelled;cancelDone=true;d.events.push('cancel-completed');},visible:async l=>{assert(!l.name.startsWith('Text draft cancelled'),'Cancelled message is in hidden section');await d.a.expect(l).toBeVisible();},hidden:async()=>{assert(cancelDone);d.events.push('hidden');},enabled:async l=>d.a.expect(l).toBeEnabled(),count:async(l,n)=>d.a.expect(l).toHaveCount(n),tick:async()=>{if(phase==='cancel'){clearTicks++;if(!clearDeadline&&clearTicks===2){cleared=true;d.f.saved.draft=null;}}else if(phase==='opening'){openTicks++;if(openTicks===2)d.f.view.regionHidden=false;if(!openDeadline&&openTicks===3){Object.assign(d.f.view,{visible:true,editable:true,regionHidden:false,draftId:'new-draft',revision:'3',value:'Original exact font'});if(openFault)openFault(d.f);} }} });
 return {...d,records,previous,finishCancel:()=>resolveCancel(),startLifecycle:()=>cancelAndReopenNativeFont({page:d.page,expect:a.expect,read:()=>clone(d.f.saved),occurrences:()=>cleared?[]:[{...clone(d.f.saved.draft),...foreignClear?{ui:{sessionId:'foreign'}}:{}}],intent:d.f.intent,previous,document,acceptedText:'Original exact font',commands:()=>d.commands,record:r=>records.push(r)}),phase:()=>phase,stats:()=>({clearTicks,openTicks}),bounds:()=>a.calls.filter(x=>x[0]==='poll')};
}
test('actual Cancel/open/font flow waits for cancellation and exact draft clear before one Edit and fresh admission',async()=>{const d=lifecycleDriver();d.complete();const pending=d.startLifecycle();for(let i=0;i<20;i++)await Promise.resolve();assert.deepEqual(d.events,['cancel']);d.finishCancel();const result=await pending;assert.equal(result.owner.draftId,'new-draft');assert.equal(result.owner.sessionId,'session');assert(d.events.indexOf('cancel-completed')<d.events.indexOf('edit'));assert(d.events.indexOf('hidden')<d.events.indexOf('edit'));assert.equal(d.events.filter(x=>x==='edit').length,1);assert.equal(d.events.filter(x=>x==='handle').length,1);assert.deepEqual(d.stats(),{clearTicks:2,openTicks:3});assert(d.bounds().every(x=>x[1]===undefined));const opens=d.records.filter(x=>x.phase==='opening-observation');assert.deepEqual(opens.map(x=>[x.descriptor.regionHidden,x.descriptor.draftId]),[[true,''],[false,''],[false,'new-draft']]);assert.equal(d.records.filter(x=>x.phase==='cancel-complete').length,1);});
for(const option of ['cancelDeadline','clearDeadline','openDeadline'])test('actual lifecycle preserves '+option+' without extra actions or widened bounds',async()=>{const d=lifecycleDriver({[option]:true});d.complete();d.finishCancel();await assert.rejects(d.startLifecycle(),/deadline/);assert.equal(d.events.filter(x=>x==='edit').length,option==='openDeadline'?1:0);assert(!d.events.includes('fill'));assert(!d.events.includes('handle'));assert(d.bounds().every(x=>x[1]===undefined));assert(d.records.some(x=>x.phase==='cancel-or-reopen-refused'));if(option==='openDeadline')assert(d.records.find(x=>x.phase==='opening-refused').descriptor);});
test('exact prior draft cannot clear under foreign session ownership',async()=>{const d=lifecycleDriver({foreignClear:true});d.complete();d.finishCancel();await assert.rejects(d.startLifecycle(),/owner|deadline/i);assert(!d.events.includes('edit'));});
for(const [name,openFault]of Object.entries({prior:f=>f.view.draftId='draft',foreignDocument:f=>f.saved.document.id='foreign',foreignSession:f=>{f.saved.draft={ui:{sessionId:'foreign'},draft:{id:'new-draft',documentId:'doc',expectedDocumentRevision:'2'}};},wrongAcceptedText:f=>f.view.value='Wrong accepted layer',disconnected:f=>f.view.connected=false,replaced:f=>f.view.sameTextarea=false}))test('actual reopened observation permanently refuses '+name,async()=>{const d=lifecycleDriver({openFault});d.complete();d.finishCancel();await assert.rejects(d.startLifecycle(),/draft|document|session|text|textarea/i);assert.equal(d.events.filter(x=>x==='edit').length,1);assert(!d.events.includes('fill'));assert(d.records.find(x=>x.phase==='opening-refused').descriptor);});
for(const [name,admissionFault]of Object.entries({draft:v=>v.draftId='changed',hidden:v=>v.visible=false,disconnected:v=>v.connected=false,replaced:v=>v.sameTextarea=false}))test('actual handle admission refuses '+name+' after readiness observation',async()=>{const d=lifecycleDriver({admissionFault});d.complete();d.finishCancel();await assert.rejects(d.startLifecycle(),/draft|textarea|Visible editor/);assert(!d.events.includes('fill'));assert(d.events.includes('dispose'));});

test('actual public opening descriptor preserves hidden, empty and visible native observations through serialization',()=>{const region={hidden:true,textContent:'',getAttribute:k=>k==='data-session'?'':'2'},el={isConnected:true,disabled:false,readOnly:false,value:'',closest:()=>region,getClientRects:()=>[]},sandbox={document:{querySelector:()=>el},getComputedStyle:()=>({visibility:'visible'}),el};const evaluate=()=>JSON.parse(JSON.stringify(vm.runInNewContext('('+nativeOpeningDescriptor.toString()+')(el)',sandbox)));assert.equal(evaluate().visible,false);assert.equal(evaluate().draftId,'');region.hidden=false;region.getAttribute=k=>k==='data-session'?'fresh':'3';el.getClientRects=()=>[{}];el.value='Original exact font';assert.deepEqual(evaluate(),{sameTextarea:true,connected:true,editable:true,draftId:'fresh',revision:'3',value:'Original exact font',ready:false,regionHidden:false,visible:true});el.disabled=true;assert.equal(evaluate().editable,false);el.isConnected=false;assert.equal(evaluate().connected,false);sandbox.document.querySelector=()=>({});assert.equal(evaluate().sameTextarea,false);});
test('actual saved draft occurrence read distinguishes exact absence from duplicate and foreign-session rows',()=>{const root=mkdtempSync(join(tmpdir(),'font-clear-')),db=new DatabaseSync(join(root,'metadata.sqlite'));try{db.exec('CREATE TABLE ui_checkpoints (json TEXT)');const row=(sessionId,ids)=>({sessionId,drafts:ids.map(id=>({id}))});db.prepare('INSERT INTO ui_checkpoints VALUES(?)').run(JSON.stringify(row('s',['prior','other'])));assert.equal(readDraftOccurrences(root,'prior').length,1);db.prepare('INSERT INTO ui_checkpoints VALUES(?)').run(JSON.stringify(row('foreign',['prior'])));assert.equal(readDraftOccurrences(root,'prior').length,2);assert.deepEqual(readDraftOccurrences(root,'prior').map(x=>x.ui.sessionId),['s','foreign']);assert.equal(readDraftOccurrences(root,'absent').length,0);}finally{db.close();rmSync(root,{recursive:true,force:true});}});

for(const [name,mutate]of Object.entries({draft:v=>v.draftId='foreign-after-admission',revision:v=>v.revision='999',text:v=>v.value='foreign text',ready:v=>v.ready=true}))test('actual selection handoff refuses '+name+' after opening admission before any font command',async()=>{const d=publicDriver();d.complete();const evaluate=d.node.evaluate;let openingReads=0;d.node.evaluate=async fn=>{if(fn===nativeOpeningDescriptor)openingReads++;if(fn===nativeDescriptor){assert.equal(openingReads,2);mutate(d.f.view);}return evaluate(fn);};await assert.rejects(d.start(),/Original public draft|Admitted public/);assert.equal(d.commands.length,0);assert(!d.events.some(x=>Array.isArray(x)&&x[0]==='select'));assert(!d.events.includes('click'));assert(!d.events.includes('fill'));assert.equal(d.events.at(-1),'dispose');});
