import {privateServerRows} from './header-fixtures.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {readFileSync} from 'node:fs';
import {hostFixture} from './host-final-fixtures.mjs';
import {assessHostFinal,hostBudget,departureState,validateHostPayload,HOST_MAX} from './host-final-core.mjs';
import {installPrivateDispatch} from './host-final-receiver.mjs';
import {auditHostIssuers,syntaxInventory,loadHostIssuers} from './host-final-issuers.mjs';
import {nativeOperation} from './operation.mjs';
import {monitorHarness} from './monitor-harness.mjs';
const clone=structuredClone;
function nativeFixture(){
 const h=hostFixture(),e=h.e,action={id:'action',kind:'Preview',text:'Current literal',draftId:'draft',documentId:'document',documentRevision:'2',sessionId:'ui-session',generation:3,revision:'7',beforeReady:false,workerURL:e.origin+'/worker.js'},token={documentId:'document',documentRevision:'2',sessionId:'ui-session',generation:3,layerId:'layer',layerVersion:'1'},rows=[];
 const push=(kind,value={})=>rows.push({kind,epoch:e.epoch,sequence:rows.length+1,actionId:action.id,...value});push('action-begin',{action});push('created',{workerId:1,url:action.workerURL,type:'module',name:'ideogram-text-1'});push('message',{workerId:1,workerAction:action.id,ready:true});push('post',{workerId:1,workerAction:action.id,token,text:action.text});push('post-return',{workerId:1});push('message',{workerId:1,workerAction:action.id,ok:true,token,rasterHash:'sha256:'+'a'.repeat(64),rgbaBytes:400,width:10,height:10});push('terminate',{workerId:1});push('terminate-return',{workerId:1});push('action-end');
 const op={action,observation:{epoch:e.epoch,rows,errors:[]},acceptedBefore:{document:{id:'document',revision:'2'}},acceptedAfter:{document:{id:'document',revision:'2'}},after:{sameTextarea:true,connected:true,editable:true,ready:true,value:action.text,draftId:'draft',revision:'7'}};op.proof=nativeOperation(op);e.operations=[op];e.proofs=[op.proof];e.nativeClosed=op.observation;return hostFixture(e);
}
for(const [name,create]of [['empty',hostFixture],['native',nativeFixture]]){
 test('actual host assessor accepts '+name+' while legacy final remains absent',()=>{const x=create(),r=assessHostFinal(x);assert(r.hostReceived);assert(!r.legacyCDPFinal&&!r.qualified&&!r.nativeQualified&&!r.consumerEOF);});
 const mutations={
  unarmed:x=>x.registration.armed=false,run:x=>x.registration.run='foreign',pid:x=>x.registration.pid++,instance:x=>x.registration.instance='foreign',nonce:x=>x.registration.nonce='foreign',path:x=>x.registration.path+='/foreign',origin:x=>x.registration.origin='http://127.0.0.1:1234',epoch:x=>x.registration.epoch='other',page:x=>x.registration.context.pageObjectId='other',frame:x=>x.registration.context.frameId='other',target:x=>x.registration.context.targetId='other',browserContext:x=>x.registration.context.browserContextId='other',generation:x=>x.registration.context.uniqueId='other',recycledContext:x=>x.contexts.push({...clone(x.contexts[0]),uniqueId:'recycled'}),foreignContext:x=>x.contexts[0].owner.contextId='foreign',missingContext:x=>x.contexts=[],missingBody:x=>x.body.end=false,partial:x=>x.body.complete=false,aborted:x=>x.body.aborted=true,bodyHash:x=>x.body.sha256='wrong',bodyLink:x=>x.body.registration='other',bodyInstance:x=>x.body.instance='other',bodyPID:x=>x.body.pid++,bodyRun:x=>x.body.run='other',bodyMethod:x=>x.body.method='PUT',chunk:x=>x.body.chunks[0].bytes++,drain:x=>x.body.responseWritableFinished=false,bodyError:x=>x.body.errors.push('late'),row:x=>x.boundaries.push({epoch:x.e.epoch,kind:'row',row:{kind:'native-input'}}),closedRows:x=>x.e.nativeClosed.rows.push({kind:'native-input'}),sticky:x=>x.e.failure='prior failure',source:x=>x.handlerSource='different',lateError:x=>x.registration.nativeClosed.errors.push('late'),wrongParent:x=>x.e.hostRegistration.context.uniqueId='other'
 };
 for(const [label,mutate]of Object.entries(mutations))test('actual '+name+' host-final refuses '+label,()=>{const x=create();mutate(x);assert.throws(()=>assessHostFinal(x));});
 for(const field of ['binding','beacon','serialization','finalObservation','errors','storageError','bindingError','observerError'])test('actual '+name+' host-final refuses post-serialization '+field,()=>{const x=create(),j=JSON.parse(x.journal);if(field==='errors')j.errors.push('late');else if(field==='binding')j.binding={returned:false,error:'late'};else if(field==='beacon')j.beacon.returned=false;else if(field==='serialization')j.serialization.bytes++;else if(field==='finalObservation')j.finalObservation.rows.push({kind:'native-input'});else j[field]='late';x.journal=JSON.stringify(j);assert.throws(()=>assessHostFinal(x));});
 test('actual '+name+' dual channels agree exactly and conflicts fail',()=>{const x=create(),c=x.registration.context;x.boundaries.push({...clone(x.body.payload),ownerPage:true,ownerFrame:true,executionContextId:c.id,executionContextUniqueId:c.uniqueId,frameId:c.frameId});assert(assessHostFinal(x).legacyCDPFinal);x.boundaries.at(-1).nonce='other';assert.throws(()=>assessHostFinal(x));});
}
for(const mutation of [x=>x.e.operations[0].action.generation++,x=>x.e.operations[0].acceptedAfter.document.revision='9',x=>x.e.operations[0].action.text='other',x=>x.e.operations[0].proof.rasterHash='other'])test('host metadata cannot override native operation/token/accepted-state proof',()=>{const x=nativeFixture();mutation(x);assert.throws(()=>assessHostFinal(x));});
const next=(r,n)=>({...clone(r),epoch:'epoch'+n,nonce:'nonce'+n,origin:'http://127.0.0.1:'+(34567+n),url:'http://127.0.0.1:'+(34567+n)+'/',pid:r.pid+n,path:'/__p1c6-completion/run/nonce'+n+'/final',receiver:'/__p1c6-completion/run/nonce'+n+'/receiver',context:{...r.context,epoch:'epoch'+n}});
test('actual workload budget carries charges through new server origins without refund',()=>{const r=hostFixture().registration,b=hostBudget({run:'run',fixture:'combined'});b.reserve(r);b.charge(r,{bodyValidated:true,bytes:12000});const n=next(r,1);assert.equal(b.reserve(n).priorCharged,12000);b.charge(n,{bodyValidated:true,bytes:13000});const last=next(r,2);assert.equal(b.reserve(last).priorCharged,25000);b.charge(last,{bodyValidated:true,bytes:10000});assert.equal(b.data.charged,35000);assert(b.assertComplete());});
for(const [name,work]of Object.entries({concurrent:b=>{const r=hostFixture().registration;b.reserve(r);b.reserve(next(r,1));b.reserve(next(r,2));},overflow:b=>{const r=hostFixture().registration;b.reserve(r);b.charge(r,{bodyValidated:true,bytes:HOST_MAX+1});},missingBody:b=>{const r=hostFixture().registration;b.reserve(r);b.charge(r,{bodyValidated:false,bytes:1});},duplicate:b=>{const r=hostFixture().registration;b.reserve(r);b.reserve(r);},chargeReplay:b=>{const r=hostFixture().registration;b.reserve(r);b.charge(r,{bodyValidated:true,bytes:1});b.charge(r,{bodyValidated:true,bytes:1});},retainedCharges:b=>{const r=hostFixture().registration;b.reserve(r);b.charge(r,{bodyValidated:true,bytes:HOST_MAX});b.reserve(next(r,1));b.charge(next(r,1),{bodyValidated:true,bytes:1});b.reserve(next(r,2));}}))test('actual budget refuses '+name+' permanently',()=>{const b=hostBudget({run:'run',fixture:'combined'});assert.throws(()=>work(b));assert.throws(()=>b.assertComplete());});
for(const action of ['kill','close','binding-remove','reset','qualification'])test('actual departure requires drained host body before '+action,()=>{const d=departureState();assert.throws(()=>d.require(action));d.begin('terminal');assert.throws(()=>d.require(action));d.drain({hostReceived:true,phase:'terminal'});d.require(action);d.fail('late');assert.throws(()=>d.require(action));});
test('cleanup-only departure cannot repair a normal result or be repeated',()=>{const d=departureState();d.begin('cleanup');d.drain({hostReceived:true,phase:'cleanup'});d.require('close');assert.throws(()=>d.require('qualification'));assert.throws(()=>d.begin('terminal'));});
for(const method of ['POST','PUT'])test('actual private dispatcher preserves ordinary '+method+' objects/body methods/return/throw',()=>{const request={url:'/api/v1/ordinary',method,on(){throw Error('Body listener forbidden');}},response={};let calls=0;const sentinel={},owner={},proto={emit(event,...args){calls++;assert.equal(this,owner);assert.equal(event,'request');assert.equal(args[0],request);assert.equal(args[1],response);if(calls===2)throw sentinel;return sentinel;}};const before=proto.emit,dispatch=installPrivateDispatch({prototype:proto,receiver:{handles:()=>false,handle(){throw Error('Private handler forbidden');}}});assert.equal(proto.emit.call(owner,'request',request,response),sentinel);assert.throws(()=>proto.emit.call(owner,'request',request,response),e=>e===sentinel);assert.equal(calls,2);dispatch.uninstall();assert.equal(proto.emit,before);});
for(const mutate of [h=>h.nativeInput(),h=>h.rootSession.emit('Target.targetCreated',{targetInfo:h.target('late')}),h=>h.originalRequest('/late')])test('actual changed monitor permanently refuses late application/native activity beside host final',async()=>{const h=await monitorHarness();await h.preview();await h.monitor.closeEpoch();await h.monitor.beforeNavigate();await h.pagehide();mutate(h);await h.monitor.detach();await assert.rejects(()=>h.monitor.finish(true));});
test('pinned issuer map validates actual emitted and injection sources',()=>{const m=loadHostIssuers();assert(auditHostIssuers(m).files>0);});
for(const kind of ['worker','dynamic','vendor','injection'])test('actual issuer audit refuses changed '+kind+' dependency',()=>{const m=loadHostIssuers(),f=m.pins.find(f=>f.role===kind);assert(f);assert.throws(()=>auditHostIssuers(m,{read:p=>p===f.path?Buffer.concat([readFileSync(p),Buffer.from('\nfetch("unknown",{keepalive:true,body:"x",method:"POST"})')]):readFileSync(p)}),/Issuer input/);});

const {partitionHostTraffic}=await import('./host-final-traffic.mjs');
const {privateHostReceiver}=await import('./host-final-receiver.mjs');
const {ownedHostIPC}=await import('./host-final-ipc.mjs');
function trafficFixture(){const f=hostFixture(),r=f.registration,b=f.body,d={...clone(b),id:1,kind:'receiver',path:r.receiver,method:'GET',responseStatus:200,inert:true};const host={run:r.run,origin:r.origin,pid:r.pid,instance:r.instance,errors:[],registrations:[r],bodies:[b],documents:[d]},server=[];for(const [i,receipt]of [b,d].entries())server.push(...privateServerRows(receipt,i+1));return {origin:r.origin,host,requests:[],responses:[],terminals:[],network:[],server};}
test('actual private traffic partition retains nonexposure without inventing browser requests',()=>{const x=trafficFixture(),p=partitionHostTraffic(x);assert.equal(p.private.records.length,2);assert(p.private.records.every(r=>!r.pwExposed&&!r.protocolExposed&&!r.qualified));assert.equal(p.requests.length,0);assert.equal(p.server.length,0);});
const trafficFaults={duplicateRegistration:x=>x.host.registrations.push(clone(x.host.registrations[0])),duplicateBody:x=>x.host.bodies.push(clone(x.host.bodies[0])),missingBody:x=>x.host.bodies=[],duplicateDoc:x=>x.host.documents.push(clone(x.host.documents[0])),missingDoc:x=>x.host.documents=[],foreignBody:x=>x.host.bodies[0].pid++,foreignServer:x=>x.server[0].pid++,header:x=>x.server[0].headers.origin='foreign',rawHeaders:x=>x.server[0].rawHeaders.push('Origin','foreign'),socket:x=>x.server[0].remotePort++,postMethod:x=>x.server[0].method='PUT',unlinkedPost:x=>x.server[0].url+='/other',duplicatePost:x=>x.server.push({...clone(x.server[0]),id:3}),swappedLinks:x=>{[x.server[0].url,x.server[5].url]=[x.server[5].url,x.server[0].url];},partialDrain:x=>x.server.find(r=>r.kind==='response').writableFinished=false,unknownBodyError:x=>x.host.errors.push('late'),conflictingProtocol:x=>x.network.push({name:'Network.requestWillBeSent',params:{requestId:'private',request:{url:x.origin+x.host.registrations[0].path,method:'GET'}}})};
for(const [name,mutate]of Object.entries(trafficFaults))test('actual private traffic refuses '+name,()=>{const x=trafficFixture();mutate(x);assert.throws(()=>partitionHostTraffic(x));});
test('actual partition leaves possible application/WASM records untouched',()=>{const x=trafficFixture();x.requests.push({id:99,url:x.origin+'/assets/engine.wasm',method:'POST'});x.server.push({id:99,kind:'request',url:'/assets/engine.wasm',method:'POST'});x.network.push({name:'Network.requestWillBeSent',params:{requestId:'wasm',request:{url:x.origin+'/assets/engine.wasm'}}});const y=partitionHostTraffic(x);assert.deepEqual(y.requests,x.requests);assert.deepEqual(y.network,x.network);assert.equal(y.server[0].id,99);});
function receiverFixture(){const x=hostFixture(),receiver=privateHostReceiver({run:x.registration.run,origin:x.registration.origin,pid:123,instance:'instance'}),r=receiver.allocate({epoch:x.e.epoch,context:x.registration.context,url:x.registration.url,namespace:'owned:'}),arm={phase:'terminal',nativeClosed:x.e.nativeClosed,inspection:{...x.registration.inspection,context:r.context},nativeMethod:x.registration.nativeMethod,budget:{priorCharged:0,priorReserved:0,maximum:32768,limit:65536}};return {receiver,r,arm};}
for(const [name,mutate]of Object.entries({phase:x=>x.arm.phase='unknown',epoch:x=>x.arm.nativeClosed.epoch='foreign',observer:x=>x.arm.nativeClosed.errors.push('late'),row:x=>x.arm.nativeClosed.rows.push({sequence:2,epoch:x.r.epoch}),source:x=>x.arm.inspection.source='other',inspection:x=>x.arm.inspection.errors.push('late'),context:x=>x.arm.inspection.context={...x.r.context,id:9},nativeMethod:x=>x.arm.nativeMethod.original=false,budget:x=>x.arm.budget.priorReserved=65536}))test('actual receiver arm refuses '+name,()=>{const x=receiverFixture();mutate(x);assert.throws(()=>x.receiver.arm(x.r.nonce,x.arm));});
test('actual receiver cannot drain an unarmed or incomplete registration',()=>{const x=receiverFixture();assert.throws(()=>x.receiver.assertDrained());x.receiver.arm(x.r.nonce,x.arm);assert.throws(()=>x.receiver.assertDrained());assert.throws(()=>x.receiver.arm(x.r.nonce,x.arm));});
for(const configure of [false,true])test('actual private IPC rejects premature normal close and keeps forced cleanup failure '+configure,async()=>{const messages=[],calls=[];const ipc=ownedHostIPC({server:{origin:'http://127.0.0.1:34567',close:async()=>calls.push('close')},instance:'instance',pid:123,send:m=>messages.push(m),uninstall:()=>calls.push('uninstall'),disconnect:()=>calls.push('disconnect')});if(configure)await ipc.message({type:'host',method:'configure',args:{origin:'http://127.0.0.1:34567',run:'run'},reply:'config'});await ipc.message({type:'completion-close'});assert.equal(messages.at(-1).type,'close-refused');assert.deepEqual(calls,[]);await ipc.message({type:'completion-close',cleanupOnly:true});assert.deepEqual(calls,['close','uninstall','disconnect']);assert(messages.at(-1).failure);assert(ipc.state.errors.length);});

test("syntax inventory survives exact JSON storage for nonliteral metadata",()=>{const x=syntaxInventory("metadata.mjs","const value = {keepalive};");assert.deepEqual(JSON.parse(JSON.stringify(x)),x);});

// Actual driver and page handler with explicit injected page/CDP/HTTP objects.
// isTrusted/native-method/body-object values below are fixtures, never live proof.
const {default:vm}=await import('node:vm');
const {integrationHostFinal}=await import('./host-final-monitor.mjs');
const {HOST_HANDLER_SOURCE}=await import('./host-final-page.mjs');
async function driverFixture(){
 const x=hostFixture(),e=x.e,origin=e.origin,listeners={},storage=new Map(),beacons=[],boundaries=[],calls=[],context={},frame={},page={},sink={contexts:x.contexts};let url=origin+'/',currentFrame=frame;const key='observer',hostKey=key+'Host';
 const realm=vm.createContext({TextEncoder,URL,location:{protocol:'http:',origin,href:url},sessionStorage:{setItem:(k,v)=>storage.set(k,v),getItem:k=>storage.get(k)??null,removeItem:k=>storage.delete(k)},addEventListener:(name,fn)=>listeners[name]=fn,recordBeacon:(path,body)=>{beacons.push({path,body});return true;}});
 vm.runInContext("function Navigator(){};const nativeBeacon=function(path,body){return recordBeacon(path,body)};Object.defineProperty(Navigator.prototype,'sendBeacon',{value:nativeBeacon});globalThis.navigator=new Navigator();const prior=Function.prototype.toString;Function.prototype.toString=function(){return this===nativeBeacon?'function sendBeacon() { [native code] }':Reflect.apply(prior,this,[])};globalThis.observer={snapshot:()=>({epoch:'epoch',rows:globalThis.nativeRows,errors:[]})};globalThis.nativeRows=[];",realm);
 realm[key+'Boundary']=payload=>{const p=JSON.parse(payload);boundaries.push({...p,ownerPage:true,ownerFrame:true,executionContextId:1,executionContextUniqueId:'default-context-1',frameId:'page'});};
 const evaluate=async(fn,arg)=>{realm.arg=structuredClone(arg);return structuredClone(await vm.runInContext('('+fn.toString()+')(arg)',realm));};
 Object.assign(context,{addInitScript:async(fn,arg)=>{await evaluate(fn,arg);listeners.pageshow({type:'pageshow',isTrusted:true,persisted:false});}});
 let receiver;
 const server={pid:123,instance:'instance',host:async(method,args={})=>{calls.push(method);if(method==='configure'){receiver=privateHostReceiver({run:args.run,origin,pid:123,instance:'instance'});return {run:args.run,origin,pid:123,instance:'instance'};}if(method==='allocate')return receiver.allocate(args);if(method==='arm')return receiver.arm(args.nonce,args.value);if(method==='drain'||method==='snapshot'){const r=receiver.data.registrations[0],p=JSON.parse(beacons[0].body),b=Buffer.from(beacons[0].body);r.receiptId=1;return {...clone(receiver.data),bodies:[{...clone(x.body),path:r.path,registration:r.nonce,run:r.run,bytes:b.length,sha256:shaBuffer(b),rawBase64:b.toString('base64'),chunks:[{sequence:1,bytes:b.length,sha256:shaBuffer(b),base64:b.toString('base64')}],payload:p}]};}throw Error(method);}};
 Object.assign(page,{context:()=>context,mainFrame:()=>currentFrame,isClosed:()=>false,url:()=>url,evaluate,goto:async next=>{listeners.pagehide({type:'pagehide',isTrusted:true,persisted:false,timeStamp:1});url=next;realm.location.href=next;}});
 Object.assign(e,{server,owner:{targetId:'page',contextId:'context',frameId:'page'},defaultContext:{id:1,uniqueId:'default-context-1'},closed:true,navigationSealed:true});
 const send=async(method)=>{calls.push(method);if(method==='Runtime.evaluate')return {result:{objectId:'window',className:'Window'}};if(method==='DOMDebugger.getEventListeners')return {listeners:[{type:'pagehide',once:true,handler:{objectId:'handler',description:'genuineIntegrationHostFinal'},scriptId:'script',lineNumber:1,columnNumber:1}]};if(method==='Runtime.callFunctionOn')return {result:{value:HOST_HANDLER_SOURCE}};if(method==='Runtime.releaseObjectGroup')return {};throw Error(method);};
 const driver=await integrationHostFinal({page,context,send,sink,boundaries,key,fixture:'combined'});await driver.activate(e);return {driver,e,page,context,realm,beacons,boundaries,calls,storage,changeFrame:()=>currentFrame={},changePageOwner:()=>page.context=()=>({})};
}
function shaBuffer(b){return createHash('sha256').update(b).digest('hex');}
const {createHash}=await import('node:crypto');
for(const legacy of ['present','absent'])test('actual host driver/page handler drains exact empty final with legacy '+legacy,async()=>{const f=await driverFixture();await f.driver.arm(f.e,'terminal');await f.driver.depart(f.e);if(legacy==='absent')f.boundaries.length=0;await f.driver.refresh(f.e);const r=f.driver.retained(f.e);assert(r.hostReceived&&!r.qualified);assert.equal(r.legacyCDPFinal,legacy==='present');assert.equal(f.beacons.length,1);assert.equal(f.storage.size,0);f.driver.requireDrained();});
for(const [name,mutate]of Object.entries({frame:f=>f.changeFrame(),pageOwner:f=>f.changePageOwner(),unclosed:f=>f.e.closed=false,unsealed:f=>f.e.navigationSealed=false,sticky:f=>f.e.failure='prior',snapshot:f=>f.realm.nativeRows.push({epoch:'epoch',sequence:1,kind:'late'})}))test('actual host driver refuses '+name+' before beacon',async()=>{const f=await driverFixture();mutate(f);await assert.rejects(()=>f.driver.arm(f.e,'terminal'));assert.equal(f.beacons.length,0);assert.throws(()=>f.driver.requireDrained());});
test('actual host page handler rejects changed native snapshot after arm',async()=>{const f=await driverFixture();await f.driver.arm(f.e,'terminal');f.realm.nativeRows.push({epoch:'epoch',sequence:1,kind:'late'});await assert.rejects(()=>f.driver.depart(f.e));assert.equal(f.beacons.length,0);assert.throws(()=>f.driver.requireDrained());});
test('actual host driver preserves cleanup-only qualification refusal',async()=>{const f=await driverFixture();await f.driver.arm(f.e,'cleanup');await f.driver.depart(f.e);await f.driver.refresh(f.e);f.driver.requireDrained();assert.throws(()=>f.driver.retained(f.e),/Cleanup cannot repair/);});
test('issuer audit refuses an emitted module omitted from its syntax closure',()=>{const m=loadHostIssuers(),i=m.modules.findIndex(module=>module.path.startsWith('dist/app/')&&module.path.endsWith('.js'));assert(i>=0);m.modules.splice(i,1);assert.throws(()=>auditHostIssuers(m),/Every pinned module is inventoried exactly once/);});
test('issuer audit refuses an emitted asset omitted from its byte pins',()=>{const m=loadHostIssuers(),i=m.pins.findIndex(pin=>pin.path==='dist/app/assets/'+m.assetFiles[0]);assert(i>=0);m.pins.splice(i,1);assert.throws(()=>auditHostIssuers(m),/Every emitted asset is pinned/);});
test('explicit issuer receipt never falls back to the checked-in default',()=>{assert.throws(()=>loadHostIssuers({env:{COMPLETION_ISSUER_MANIFEST:'relative.json'}}),/absolute/);assert.throws(()=>loadHostIssuers({env:{COMPLETION_ISSUER_MANIFEST:'/missing-explicit.json'},read:path=>{assert.equal(path,'/missing-explicit.json');throw Error('missing explicit receipt');}}),/missing explicit receipt/);});
