import {adoptNativeInput,readNativeState,nativeDescriptor} from './font-state.mjs';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {EXPECTED,POLICY,sha,PublicWorkerLedger,assertNoWorkerCommands,headers,auditTraffic} from './app-buffer-core.mjs';
import {CompletionCollector,closedWasmGroup,assessCohort,qualifyCompletion,groupSignature} from './completion-group.mjs';
import {installCompletionObserver} from './completion-observer.mjs';
import {savedState} from './completion-public.mjs';
import {nativeOperation,qualifiedWasmAbort} from './operation.mjs';
import {wireEpoch} from './wire.mjs';
import {nativeTargetsDisposed,validateNative} from './boundary.mjs';
import {pageReceiptSink} from './page-sink.mjs';
import {emptyNative} from './empty-native.mjs';
import {integrationHostFinal} from './host-final-monitor.mjs';
import {partitionHostTraffic} from './host-final-traffic.mjs';
import {validateRecorder,retainedRecorder} from './recorder-health.mjs';
import {auditHostIssuers} from './host-final-issuers.mjs';
import {networkForEpoch,assertProtocolOwnership} from './protocol-membership.mjs';
import {RESTORED_MODE,refuseRestoredNative,restoredNative,restoredOriginalChannels} from './restored-native.mjs';
import {restoredRoutes} from './restored-route.mjs';
import {accountFavicon,faviconSourceProof} from './ancillary-favicon.mjs';

const readJSON=p=>JSON.parse(readFileSync(p));
const once=(a,label)=>{assert.equal(a.length,1,label);return a[0];};
export async function completionMonitor({page,context,root,out,id,expect,storageProbePath,readState=readNativeState,fixture,hostFactory=integrationHostFinal,mode='NATIVE-COMPLETION'}){
 assert(mode==='NATIVE-COMPLETION'||mode==='EMPTY-NATIVE'&&fixture==='busy-actions'||mode===RESTORED_MODE&&fixture==='restored-reads','Explicit fixture-selected native mode');
 const issuerEvidence=auditHostIssuers(readJSON('tests/editor/completion/host-final-issuers.json'));
 const key='__integrationNativeCompletion',epochs=[],requests=[],responses=[],terminals=[],network=[],discovery=[],commands=[],errors=[],pending=[],objects=new Map(),pages=new Map(),boundaries=[],targetOwners=new Map();let current,sequence=0;
 const record={scope:'Pinned Chromium test fixture: raw transport plus browser bytes plus source-derived native consumption',epochs,requests,responses,terminals,network,discovery,commands,errors,boundaries,observedEOF:false};
 record.issuerEvidence=issuerEvidence;
 const save=()=>writeFileSync(join(out,'wasm-completion.json'),JSON.stringify(record,null,2));
 const fail=(e,error)=>{record.complete=false;const message=String(error);if(e)e.failure??=message;errors.push(message);};
 const binding=key+'Boundary',routes=[],restorationEvents=[];record.mode=mode;record.routes=routes;
 const restored=mode===RESTORED_MODE?restoredRoutes({current:()=>current,epochs:()=>epochs,page,context,id,objects,rows:routes,fail,order:()=>++sequence,events:restorationEvents}):null;
 if(restored)Object.assign(record,{restorationEvents,scope:'Restored-only negative native accounting; raw channels retained independently',nativeQualified:false,wasmQualified:false,byteQualified:false,transportQualified:false,qualified:false});
 const watch=p=>{const q=p.catch(e=>errors.push(String(e)));pending.push(q);};
 const flush=async()=>{let count;do{count=pending.length;await Promise.all(pending);}while(count!==pending.length);assert.deepEqual(errors,[]);};
 await context.addInitScript(installCompletionObserver,{key});
 let pageCDP,rootCDP,sink;try{
 pageCDP=await context.newCDPSession(page);rootCDP=await context.browser().newBrowserCDPSession();
 async function send(method,params={},session){assert(!session||session==='owned-page-CDPSession-1');const c={method,params,controllerSessionLabel:session??'owned-root-CDPSession-1',started:new Date().toISOString(),state:'pending'};commands.push(c);assertNoWorkerCommands([c]);try{const value=await (session?pageCDP:rootCDP).send(method,params);c.state='fulfilled';c.value=method==='Network.getResponseBody'?{base64Encoded:value.base64Encoded,encodedCharacters:value.body?.length}:value;return value;}catch(e){c.state='rejected';c.error=String(e);throw e;}finally{c.ended=new Date().toISOString();}}
 sink=pageReceiptSink({session:pageCDP,send,name:binding,receipts:boundaries,fail:error=>fail(null,error)});record.pageSink={contexts:sink.contexts,raw:sink.raw,errors:sink.errors};await sink.install();
 const hostFinal=await hostFactory({page,context,send,sink,boundaries,key,fixture});record.hostFinal=hostFinal.data;
 for(const name of ['Network.requestWillBeSent','Network.requestWillBeSentExtraInfo','Network.responseReceived','Network.responseReceivedExtraInfo','Network.dataReceived','Network.loadingFinished','Network.loadingFailed','Network.requestServedFromCache'])pageCDP.on(name,params=>network.push({sequence:++sequence,at:new Date().toISOString(),controllerSessionLabel:'owned-page-CDPSession-1',name,params}));
 for(const name of ['Target.targetCreated','Target.targetInfoChanged','Target.targetDestroyed'])rootCDP.on(name,params=>{const e={sequence:++sequence,at:new Date().toISOString(),name,params};discovery.push(e);const info=params.targetInfo,id=info?.targetId??params.targetId;if(restored&&info?.type==='worker')fail(current,'Restored mode forbids any worker target');
  if(name==='Target.targetCreated'){let owner=current;if(info.type==='worker'){const candidates=epochs.filter(v=>info.url&&new URL(info.url).origin===v.origin);if(candidates.length===1)owner=candidates[0];else if(info.url)fail(current,'Unowned native target URL');if(!owner||owner.navigationSealed)fail(owner,'Native target created outside active epoch');}if(targetOwners.has(id))fail(owner,'Recycled target ID');targetOwners.set(id,owner??null);}
  let owner=targetOwners.get(id);if(owner===undefined&&info?.type==='worker'){const matches=epochs.filter(v=>info.url&&new URL(info.url).origin===v.origin);if(matches.length===1)owner=matches[0];else fail(current,'Unowned late native target');}
  if(owner)owner.discovery.push(e);else if(owner===undefined)fail(current,'Target event without observed creation');});
 context.on('request',q=>{const row={id:id(q),url:q.url(),method:q.method(),resourceType:q.resourceType(),redirectedFrom:q.redirectedFrom()?.url()??null,redirectedTo:q.redirectedTo()?.url()??null,originalRequestObject:true,frameExposure:(()=>{try{const p=q.frame().page();if(!pages.has(p))pages.set(p,pages.size+1);return {ownerPage:p===page,ownerFrame:q.frame()===page.mainFrame(),ownerContext:p.context()===context,pageId:pages.get(p)};}catch(e){return {unavailable:String(e)};}})()};objects.set(row.id,q);requests.push(row);if(restored)try{restored.admit(q,row);}catch(error){fail(current,error);}watch(q.allHeaders().then(h=>row.actualHeaders=h));});
 context.on('response',p=>{const q=p.request(),row={requestId:id(q),url:p.url(),status:p.status(),fromServiceWorker:p.fromServiceWorker(),originalRequestObject:objects.get(id(q))===q};responses.push(row);watch(Promise.all([p.allHeaders(),q.response()]).then(([h,v])=>{row.actualHeaders=h;row.originalPairConfirmed=v===p;}));});
 for(const [event,kind]of [['requestfinished','finished'],['requestfailed','failed']])context.on(event,q=>terminals.push({requestId:id(q),url:q.url(),kind,originalRequestObject:objects.get(id(q))===q,...kind==='failed'?{failure:q.failure()}:{}}));
 page.on('worker',w=>{try{assert(!restored,'Restored mode forbids any Worker object');const matches=epochs.filter(e=>w.url()===e.origin+EXPECTED.workerPath);assert.equal(matches.length,1,'Original Worker has one epoch');const e=matches[0];e.workers.retain(w);assert(!e.navigationSealed,'Native worker after navigation seal');}catch(error){fail(current,error);}});
 await send('Network.enable',{},'owned-page-CDPSession-1');await send('Target.setDiscoverTargets',{discover:true});
 const binary=readFileSync('dist/app'+EXPECTED.wasmPath);assert.equal(binary.length,EXPECTED.wasmBytes);assert.equal(sha(binary),EXPECTED.wasmSHA256);
 async function identity(e){const target=(await send('Target.getTargetInfo',{},'owned-page-CDPSession-1')).targetInfo,tree=(await send('Page.getFrameTree',{},'owned-page-CDPSession-1')).frameTree;assert.equal(target.type,'page');assert(target.browserContextId);assert.equal(tree.frame.url,e.origin+'/');assert.equal(tree.childFrames,undefined);assert.equal(page.url(),e.origin+'/');if((mode==='NATIVE-COMPLETION'||mode===RESTORED_MODE)&&!e.ancillaryFrame)e.ancillaryFrame={id:tree.frame.id,loaderId:tree.frame.loaderId,url:tree.frame.url};return {kind:'page',sessionId:'owned-page-CDPSession-1',targetId:target.targetId,contextId:target.browserContextId,frameId:tree.frame.id,origin:e.origin,live:!page.isClosed()};}
 const ledger=e=>readFileSync(e.ledger,'utf8').split('\n').filter(Boolean).map(JSON.parse);
 const networkFor=e=>networkForEpoch(network,e);
 async function input(e,retained=false){await flush();for(const q of requests)q.redirectedTo=objects.get(q.id).redirectedTo()?.url()??null;const retainedServer=ledger(e),partition=partitionHostTraffic({origin:e.origin,host:e.hostSnapshot,requests,responses,terminals,network:networkFor(e),server:retainedServer});e.privateTraffic=partition.private;if(restored)e.originalChannelAccounting=restoredOriginalChannels({origin:e.origin,...partition},e);const server=partition.server,wire=wireEpoch({origin:e.origin,...partition,storageProbePath});e.localImages=wire.localImages;e.storageProbes=wire.storageProbes;const recorder=retained?retainedRecorder(e.server,retainedServer):validateRecorder(await e.server.recorder(),{pid:e.pid,instance:e.server.instance,rows:retainedServer});(e.recorderSamples??=[]).push({retained,at:new Date().toISOString(),sample:structuredClone(recorder)});
  let nativeServer=server,nativeNetwork=wire.network;
  if(mode==='NATIVE-COMPLETION'||mode===RESTORED_MODE){
   assert.deepEqual(faviconSourceProof(),e.ancillaryAdmission.source,'Ancillary source changed');
   if(!page.isClosed()&&page.url()===e.origin+'/')assert.equal(await page.locator('link[rel~=icon]').count(),0,'Ancillary public icon link');
   const ancillary=accountFavicon({page:e.owner,...partition,network:wire.network,recorder,epoch:e.epoch,currentEpoch:e.epoch},e.ancillaryAdmission,{previous:e.ancillary,cancellation:restored&&e.index===2?restored.ancillaryWindow(e):null});
   e.ancillary=ancillary.account;(e.ancillaryChecks??=[]).push({retained,at:new Date().toISOString()});nativeServer=ancillary.server;nativeNetwork=ancillary.network;
  }
  return {page:e.owner,requests:wire.requests,responses:wire.responses,terminals:wire.terminals,network:nativeNetwork,server:nativeServer,discovery:e.discovery,workerRows:e.workers.rows,application:EXPECTED,commands,collector:e.collector?{...e.collector.row,disabled:undefined}:undefined,recorder,serverOwner:{pid:e.pid,origin:e.origin},epoch:e.epoch,currentEpoch:e.epoch,closedBeforeNavigation:true};}
 async function snapshot(e){const observation=await page.evaluate(async k=>{await globalThis[k].boundaryFlush();return globalThis[k].snapshot();},key);if(restored)assert(observation.rows.every(r=>r.kind==='installed'&&r.workerId===undefined&&r.actionId===null),'Restored mode forbids native observer activity');validateNative(e,observation);return observation;}
 function retainedNative(e,requireHide=false){
  const own=boundaries.filter(b=>b.epoch===e.epoch);assert(own.every(b=>b.ownerPage&&b.ownerFrame&&b.origin===e.origin),'Exact main-page boundary owner');
  const rows=own.filter(b=>b.kind==='row').map(b=>b.row);const observation={epoch:e.epoch,rows,errors:[]};validateNative(e,observation);assert.deepEqual(rows,e.nativeClosed.rows,'Late native rows invalidate the closed epoch');
  const hides=own.filter(b=>b.kind==='pagehide');assert(hides.length<=1);if(requireHide)hostFinal.retained(e);for(const h of hides){validateNative(e,h.observation);assert.deepEqual(h.observation,e.nativeClosed);}
 }
 async function validateRetained(e,{native,retained=false,requireHide=false}={}){
  assert(!e.failure,'Permanent epoch failure');if(native){const next=await snapshot(e);if(e.nativeClosed)assert.deepEqual(next,e.nativeClosed,'Native evidence changed after provisional closure');else e.nativeClosed=structuredClone(next);}
  retainedNative(e,requireHide);const x=await input(e,retained);if(restored)refuseRestoredNative(e,x);assert.deepEqual(x.requests.map(q=>q.id),e.provisionalRequestIds,'New original request after provisional closure');assert(nativeTargetsDisposed({owner:e.owner,discovery:e.discovery,workers:e.workers.rows}),'Native disposal incomplete');
  if(e.initial){const group=closedWasmGroup(x),cohort=assessCohort(x,e.proofs);assert.deepEqual(groupSignature(group),groupSignature(e.initial));assert.deepEqual(cohort,e.cohort);e.final=group;e.finalCohort=cohort;}
  else {assert.equal(e.proofs.length,0);assert.equal(e.workers.rows.length,0);assert.equal(x.requests.filter(q=>[EXPECTED.workerPath,EXPECTED.wasmPath].includes(new URL(q.url).pathname)).length,0,'Empty epoch became native');if(restored)e.restoredNative=restoredNative(x,e,restored.assess(e,x));else if(mode==='EMPTY-NATIVE')e.emptyNative=emptyNative(x,e,routes);else auditTraffic(x);}
  if(e.navigationSealed){assert.deepEqual(x.requests.map(q=>q.id),e.sealedRequestIds,'New original request after navigation seal');const ids=[...new Set(x.network.map(n=>n.params.requestId))];assert(ids.every(id=>e.sealedNetworkIds.includes(id)),'New protocol request after navigation seal');}
  return x;
 }
 function storeRead(ref){const b=readFileSync(join(root,'objects','sha256',ref.hash.slice(7,9),ref.hash.slice(7)));assert.equal(String(b.length),ref.byteLength);assert.equal('sha256:'+sha(b),ref.hash);return b;}
 function applied(action,token,commandIdsBefore){const db=new DatabaseSync(join(root,'metadata.sqlite'),{readOnly:true});try{const rows=db.prepare('SELECT id,original,receipt FROM commands').all().filter(x=>!commandIdsBefore.has(x.id)).map(x=>({id:x.id,command:JSON.parse(String(x.original)).command,receipt:JSON.parse(String(x.receipt))}));const c=once(rows.filter(x=>['CreateTextLayer','CommitTextEdit','ReplaceTextFont'].includes(x.command.body.type)),'Own accepted native command');const candidate=JSON.parse(storeRead(c.command.body.candidate));const document=JSON.parse(String(db.prepare('SELECT json FROM documents WHERE id=?').get(action.documentId).json));const state=JSON.parse(storeRead(document.image.state));const layer=once(state.layers.filter(l=>l.id===token.layerId),'Own accepted native layer');const source=JSON.parse(storeRead(layer.source));const pixels=storeRead(source.render.pixels);return {candidate,command:c.command,acceptedAfter:{document,layer,source,text:storeRead(source.text.textUtf8).toString('utf8'),pixelSHA256:'sha256:'+sha(pixels),pixelBytes:pixels.length,commandSucceeded:c.receipt.status==='accepted',receipt:c.receipt,commandId:c.id}};}finally{db.close();}}
 return {
  begin(server,ledgerPath){assert(!current||current.closed);if(restored)assert(epochs.length<2,'Exactly two restored epochs');current={index:epochs.length+1,mode,fixture,origin:server.origin,pid:server.pid,ledger:ledgerPath,server,workers:new PublicWorkerLedger(),discovery:[],operations:[],proofs:[],closed:false};Object.defineProperty(current,'toJSON',{value(){const {server,collector,workers,...rest}=this;return {...rest,workers:workers.rows,collector:collector?.row,shutdownEvidence:{epoch:this.epoch,index:this.index,owner:this.owner,pid:server.pid,instance:server.instance,origin:server.origin,shutdown:server.shutdown??null,lifecycle:server.lifecycle??null}};}});epochs.push(current);if(restored)restored.begin(current);},
  async activate(){const e=current;assert(e);e.owner=await identity(e);e.epoch=(await page.evaluate(k=>globalThis[k].snapshot(),key)).epoch;e.defaultContext=sink.bind(e.owner,e.epoch);if(mode==='NATIVE-COMPLETION'||mode===RESTORED_MODE){
   assert.equal(await page.locator('link[rel~=icon]').count(),0,'Ancillary public icon link');
   e.ancillaryAdmission={origin:e.origin,epoch:e.epoch,owner:structuredClone(e.owner),frame:structuredClone(e.ancillaryFrame),defaultContext:structuredClone(e.defaultContext),serverOwner:{pid:e.pid,instance:e.server.instance,origin:e.origin},source:faviconSourceProof(),noPublicIconLink:true};
  }await hostFinal.activate(e);if(restored)restored.activate(e);if(!restored){e.collector=new CompletionCollector({send,owner:e.owner,verify:()=>identity(e),expected:binary,saveBody:(requestId,bytes)=>writeFileSync(join(out,'wasm-'+e.index+'-'+requestId.replace(/[^a-zA-Z0-9_-]/g,'_')+'.bin'),bytes,{flag:'wx'})});await e.collector.install();}assert.equal(e.workers.rows.length,0);},
  restoredRoute(pattern,path){assert(restored,'Explicit restored fixture only');return restored.register(pattern,path);},
  heldRoute(route){assert.equal(mode,'EMPTY-NATIVE');const q=route.request();assert.equal(objects.get(id(q)),q);const r={epoch:current.epoch,requestId:id(q),originalRouteRequest:route.request()===q,command:q.postDataJSON().command,hold:Date.now()};routes.push(r);return {publicBefore:value=>r.publicBefore=value,publicAfter:value=>r.publicAfter=value,release:()=>{assert(!r.release);r.release=Date.now();},async continue(){assert(r.release);r.continueStarted=Date.now();try{const value=await route.continue();r.continueFulfilled=Date.now();return value;}catch(error){r.error=String(error);throw error;}}};},
  async operation(kind,work,intent){if(restored){const error=Error('Restored mode forbids native operations');fail(current,error);throw error;}assert.equal(mode,'NATIVE-COMPLETION');const e=current;assert(e&&!e.closed&&e.collector.row.installed);const node=await page.locator('#native-text-content').elementHandle();assert(node);const observe=()=>node.evaluate(nativeDescriptor);
   await expect(page.getByText('Draft saved locally; not applied to the document',{exact:true}).first()).toBeVisible();await expect(page.getByText('Unsaved UI draft',{exact:true})).toHaveCount(0);
   const {before,saved}=await adoptNativeInput({expect,observe,read:id=>readState(root,id),intent}),action={id:randomUUID(),kind,text:before.value,draftId:before.draftId,revision:before.revision,documentId:saved.document.id,documentRevision:saved.document.revision,sessionId:saved.draft.ui.sessionId,generation:Number(saved.draft.draft.generation),beforeReady:before.ready,workerURL:e.origin+EXPECTED.workerPath};const db=new DatabaseSync(join(root,'metadata.sqlite'),{readOnly:true});let priorIds;try{priorIds=new Set(db.prepare('SELECT id FROM commands').all().map(x=>x.id));}finally{db.close();}
   const op={action,started:new Date().toISOString(),acceptedBefore:saved.accepted};e.operations.push(op);await page.evaluate(({key,action})=>globalThis[key].begin(action),{key,action});
   try{await work();if(kind==='Preview')await expect(page.getByText('Text preview ready. Accepted appearance is unchanged.',{exact:true})).toBeVisible();else await expect(page.locator('#native-text-editor')).toBeHidden();await page.evaluate(k=>globalThis[k].end({}),key);op.observation=await page.evaluate(k=>globalThis[k].snapshot(),key);op.after=kind==='Preview'?await observe():{hidden:true};const success=once(op.observation.rows.filter(r=>r.actionId===action.id&&r.kind==='message'&&r.ok),'Own success');if(kind==='Apply')Object.assign(op,applied(action,success.token,priorIds));else op.acceptedAfter=readState(root,action.draftId).accepted;op.priorPreview=[...e.proofs].reverse().find(p=>p.kind==='Preview'&&p.draftId===action.draftId);op.proof=nativeOperation(op);e.proofs.push(op.proof);op.completed=true;}catch(error){op.error=String(error);throw error;}finally{op.ended=new Date().toISOString();await node.dispose();save();}
  },
  async closeEpoch(){const e=current;if(!e)return;assert(!e.failure,'Permanent epoch failure');if(e.closed)return;assert(!e.closeAttempted,'Failed epoch closure is permanent');e.closeAttempted=true;
   try{await flush();e.nativeClosed=structuredClone(await snapshot(e));await expect.poll(()=>nativeTargetsDisposed({owner:e.owner,discovery:e.discovery,workers:e.workers.rows})).toBe(true);const x=await input(e);if(restored)refuseRestoredNative(e,x);e.provisionalRequestIds=x.requests.map(q=>q.id);
    if(x.requests.some(q=>q.url===e.origin+EXPECTED.wasmPath)){assert.notEqual(mode,'EMPTY-NATIVE','Busy mode cannot collect native bytes');e.initial=closedWasmGroup(x);e.cohort=assessCohort(x,e.proofs);e.captures=await e.collector.retrieveGroup(e.initial);}
    await validateRetained(e,{native:true});e.closedNetworkIds=[...new Set(x.network.map(n=>n.params.requestId))];e.closed=true;e.closedAt=new Date().toISOString();
   }catch(error){fail(e,error);throw error;}finally{try{await e.collector?.disable();}catch(error){fail(e,error);throw error;}finally{save();}}
  },
  async beforeNavigate(){const e=current;if(!e)return;try{assert(e.closed);const x=await validateRetained(e,{native:true});e.sealedRequestIds=x.requests.map(q=>q.id);e.sealedNetworkIds=[...new Set(x.network.map(n=>n.params.requestId))];e.navigationSealed=true;e.preNavigationAt=new Date().toISOString();}catch(error){fail(e,error);throw error;}finally{save();}},
  async depart(phase){const e=current;try{assert(e.closed&&e.navigationSealed);await hostFinal.arm(e,phase);await hostFinal.depart(e);await validateRetained(e,{requireHide:phase!=='cleanup'});}catch(error){fail(e,error);throw error;}finally{save();}},
  async beforeServerStop(){const e=current;try{await hostFinal.refresh(e);await validateRetained(e);}catch(error){fail(e,error);throw error;}finally{save();}},
  beforeStorageReset(){hostFinal.requireDrained();},
  privateEvent(event){return record.complete===true&&epochs.some(e=>e.privateTraffic?.requestIds.includes(event.requestId));},
  async finish(cleanup){try{assert.equal(cleanup,true,'Independent owned cleanup is required');assert.equal(record.detach?.passed,true);for(const e of epochs){assert(!e.failure,'Permanent epoch failure');assert(e.closed&&e.navigationSealed,'Epoch not sealed before navigation');if(restored)assert.equal(e.collector,undefined,'No collection in restored mode');else{assert.equal(e.collector.row.disabled,true,'Own collection disable required');assert.equal(e.collector.row.disableError,undefined);}await validateRetained(e,{retained:true,requireHide:true});if(e.initial)e.qualification=qualifyCompletion({initial:e.initial,final:e.final,captures:e.captures,native:e.proofs,cohort:e.finalCohort,cleanup});}
   if(restored)restored.finish();assert(boundaries.every(b=>epochs.filter(e=>e.epoch===b.epoch&&e.origin===b.origin).length===1),'No unowned native boundary');assertProtocolOwnership(network,epochs,networkFor);assert(requests.every(q=>epochs.some(e=>new URL(q.url).origin===e.origin)),'No unowned original request');assert.deepEqual(errors,[]);record.complete=true;
   }catch(error){fail(current,error);throw error;}finally{save();}},
  async detach(){const failed=[];for(const [name,fn]of [['final-host-receipts',()=>hostFinal.requireDrained()],['binding-remove',()=>{hostFinal.requireDrained();return sink.remove();}],['discovery-disable',()=>send('Target.setDiscoverTargets',{discover:false})],['page-detach',()=>pageCDP.detach()],['root-detach',()=>rootCDP.detach()]]){try{await fn();}catch(e){failed.push({name,error:String(e)});}}record.detach={passed:failed.length===0,failures:failed};save();assert.deepEqual(failed,[]);},
  qualifies(event){return mode==='NATIVE-COMPLETION'&&record.complete===true&&qualifiedWasmAbort(event,epochs);},
  save,
 };
 }catch(primary){const failures=[primary];for(const fn of [()=>sink?.remove(),()=>pageCDP?.detach(),()=>rootCDP?.detach()])try{await fn();}catch(error){failures.push(error);}throw new AggregateError(failures,'Completion observer setup and independent cleanup');}
}
