import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
import {recoveryReaderHarness} from './recovery-reader-harness.mjs';
import {originalRecoveryCompletion} from '../integration-network.mjs';
test('actual original reader seals SSE descriptor/body/publication after complete frame and later abort',async()=>{const h=await recoveryReaderHarness(),r=await h.scenario({streamAbort:true});assert.deepEqual(r.errors,[]);assert.equal(r.proofs.length,1);const p=r.proofs[0];assert.equal(p.validationKind,'sse-reference-publication');assert.equal(p.validated,true,p.validationError);const event={channel:'requestfailed',resourceType:'fetch',failure:{errorText:'net::ERR_ABORTED'},method:'GET',requestId:p.requestId,url:p.url,response:{requestId:p.requestId,url:p.url,method:'GET',status:200,contentType:'application/x-ndjson',contentLength:String(p.bytes),etag:'"sha256:'+p.sha256+'"'}};assert.equal(originalRecoveryCompletion(event,[p]),true);for(const mutate of [v=>v.descriptor.frameOrdinal=0,v=>v.publication.value.cursor='3',v=>v.eventWrites=[],v=>v.finalCheck.url=v.finalCheck.url.replace('after=2','after=3'),v=>v.descriptor.parserFailures=['lost'],v=>v.descriptor.requestOperation=999,v=>v.descriptor.offeredId='3']){const x=structuredClone(p);mutate(x);assert.equal(originalRecoveryCompletion(event,[x]),false);}});
for(const fault of ['corrupt','truncated'])test('actual original reader refuses '+fault+' content despite real descriptor and committed-looking records',async()=>{const h=await recoveryReaderHarness(),r=await h.scenario({bodyFault:fault});assert.equal(r.proofs.length,1);assert.equal(r.proofs[0].validated,false);});
test('actual original reader refuses duplicate descriptors rather than borrowing equal bytes',async()=>{const h=await recoveryReaderHarness(),r=await h.scenario({duplicateFrame:true});assert.equal(r.proofs[0].descriptorCandidates,2);assert.equal(r.proofs[0].validated,false);});
for(const [label,mutate]of Object.entries({
 'missing original EOF':es=>{es.splice(es.findIndex(e=>e.kind==='eof'&&e.operation===2),1);},'second content reader':es=>es.push({...es.find(e=>e.kind==='reader'&&e.operation===2),readerNumber:2}),'wrong session':es=>{for(const e of es.filter(e=>e.operation===2))e.owners=[{clientId:'client',sessionId:'other'}];},'lost publication':es=>es.splice(es.findIndex(e=>e.kind==='publication-writes'&&e.transaction===3),1),'other cache':es=>{for(const e of es.filter(e=>e.kind==='publication-writes'))e.db='ie-projection-other';},'aborted publication':es=>es.find(e=>e.kind==='publication-writes'&&e.transaction===3).kind='publication-aborted','later recovery':es=>es.push({...es.find(e=>e.kind==='start'),start:31,url:'http://127.0.0.1:34567/api/v1/events?after=0'}),'SSE observation overflow':(es,send)=>send({...es.find(e=>e.kind==='start'&&e.operation===1),kind:'observation-limit',count:67108865}),'wrong final owner':es=>{for(const e of es.filter(e=>e.operation===3))e.owners=[{clientId:'client',sessionId:'other'}];}
}))test('actual original reader cannot qualify '+label,async()=>{const h=await recoveryReaderHarness(),r=await h.scenario({mutate});assert(!r.proofs.some(p=>p.validated));});
test('actual browser observation preserves fetch/read/cancel arguments, original promises and values',async()=>{
 const h=await recoveryReaderHarness(),calls=[],events=[],fetchThis={},readThis={},cancelThis={},chunk={done:false,value:new Uint8Array([100,97,116,97,58,32])},readPromise=Promise.resolve(chunk),cancelPromise=Promise.resolve('cancelled');
 const reader={read:function(...args){calls.push(['read',this,args]);return readPromise;},cancel:function(...args){calls.push(['cancel',this,args]);return cancelPromise;}};
 const body={getReader:function(...args){calls.push(['getReader',this,args]);return reader;},tee(){throw Error('No tee');}};
 const response={body,status:200,url:'http://127.0.0.1:34567/api/v1/events/stream?after=0',redirected:false,headers:new Headers({'content-type':'text/event-stream'}),json:()=>Promise.resolve({}),clone(){throw Error('No clone');}},fetchPromise=Promise.resolve(response);
 class Store {put(){return {};}}const realm=vm.createContext({URL,Request,Headers,TextDecoder,TextEncoder,Uint8Array,Promise,crypto:webcrypto,structuredClone,performance,location:{protocol:'http:',origin:'http://127.0.0.1:34567',href:'http://127.0.0.1:34567/'},sessionStorage:{'ie-ui-session:client':'session',getItem(){return 'session';}},IDBObjectStore:Store,btoa:s=>Buffer.from(s,'binary').toString('base64')});realm.window=realm;realm.p1c6RecoveryRead=value=>{events.push(value);return Promise.resolve();};realm.fetch=function(...args){calls.push(['fetch',this,args]);return fetchPromise;};realm.arg=h.scripts[0].arg;vm.runInContext('('+h.scripts[0].fn.toString()+')(arg)',realm);
 const init={headers:{original:'unchanged'}},p=realm.fetch.call(fetchThis,response.url,init);assert.equal(p,fetchPromise);await p;const originalReader=body.getReader('original-reader-option');assert.equal(originalReader,reader);assert.equal(reader.read.call(readThis,'original-read-arg'),readPromise);assert.equal(await readPromise,chunk);await Promise.resolve();assert.equal(reader.cancel.call(cancelThis,'original-cancel-reason'),cancelPromise);await realm.__p1c6RecoveryObserver.flush();assert.equal(calls.length,4);assert.equal(calls[0][1],fetchThis);assert.equal(calls[0][2][1],init);assert.equal(calls[1][1],body);assert.deepEqual(calls[1][2],['original-reader-option']);assert.equal(calls[2][1],readThis);assert.deepEqual(calls[2][2],['original-read-arg']);assert.equal(calls[3][1],cancelThis);assert.deepEqual(calls[3][2],['original-cancel-reason']);assert(events.some(e=>e.kind==='chunk'));assert(!events.some(e=>['clone','tee'].includes(e.kind)));
});
