import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {pageReceiptSink} from './page-sink.mjs';
import {emptyNative} from './empty-native.mjs';
import {OriginalSSEFrames} from './sse-frames.mjs';
import {sseDescriptor,ssePublication,sseQualification} from './sse-publication.mjs';
import {recoveryFixture} from './recovery-fixture.mjs';
const clone=structuredClone,origin='http://127.0.0.1:34567';
async function sinkHarness(){const session=new EventEmitter(),receipts=[],errors=[],commands=[];const sink=pageReceiptSink({session,name:'receipt',receipts,fail:e=>errors.push(String(e)),send:async(method,params)=>commands.push({method,params})});await sink.install();const created=(id=1,uniqueId='u1',more={})=>session.emit('Runtime.executionContextCreated',{context:{id,uniqueId,origin,auxData:{isDefault:true,frameId:'frame'},...more}});created();sink.bind({origin,frameId:'frame'},'epoch');const emit=(value,id=1)=>session.emit('Runtime.bindingCalled',{name:'receipt',executionContextId:id,payload:JSON.stringify({origin,epoch:'epoch',deliverySequence:1,kind:'pagehide',observation:{epoch:'epoch',rows:[],errors:[]},...value})});return {sink,session,receipts,errors,commands,created,emit};}
test('actual page sink retains delayed old default-context receipt after destruction without current-epoch lookup',async()=>{const h=await sinkHarness();h.session.emit('Runtime.executionContextDestroyed',{executionContextId:1,executionContextUniqueId:'u1'});h.created(2,'u2');h.sink.bind({origin,frameId:'frame'},'next');h.emit({});assert(h.sink.final('epoch'));assert(!h.sink.final('next'));assert.equal(h.receipts[0].executionContextUniqueId,'u1');await h.sink.remove();assert.equal(h.errors.length,0);});
for(const [label,mutate]of Object.entries({
 'unknown context':h=>h.emit({},9),'wrong epoch':h=>h.emit({epoch:'next'}),'wrong origin':h=>h.emit({origin:'http://other'}),'lost row':h=>h.emit({deliverySequence:2}),'duplicate final':h=>{h.emit({});h.emit({deliverySequence:2});},'post-final activity':h=>{h.emit({});h.emit({deliverySequence:2,kind:'row',row:{}});},'recycled numeric context':h=>{h.session.emit('Runtime.executionContextDestroyed',{executionContextId:1});h.created(1,'u2');h.emit({});},'unbound foreign context':h=>{h.created(2,'u2',{auxData:{isDefault:false,frameId:'frame'}});h.emit({},2);},'wrong default frame':h=>{h.created(2,'u2',{auxData:{isDefault:true,frameId:'other'}});h.emit({},2);},'malformed payload':h=>h.session.emit('Runtime.bindingCalled',{name:'receipt',executionContextId:1,payload:'{'})
}))test('actual page sink permanently refuses '+label,async()=>{const h=await sinkHarness();mutate(h);assert(h.errors.length);assert.throws(()=>h.sink.final('epoch'));await assert.rejects(()=>h.sink.remove());});
test('navigation/context destruction is not a final receipt',async()=>{const h=await sinkHarness();h.session.emit('Runtime.executionContextsCleared',{});assert.equal(h.sink.final('epoch'),false);});

function emptyFixture(){const q={id:1,url:origin+'/api/v1/commands',method:'POST',originalRequestObject:true,frameExposure:{ownerPage:true,ownerContext:true},redirectedFrom:null,redirectedTo:null,actualHeaders:{provisional:'retained'}},p={requestId:1,url:q.url,status:204,originalRequestObject:true,originalPairConfirmed:true,fromServiceWorker:false,actualHeaders:{}},t={requestId:1,url:q.url,kind:'finished',originalRequestObject:true};return {x:{page:{origin},requests:[q],responses:[p],terminals:[t],server:[],network:[]},e:{mode:'EMPTY-NATIVE',fixture:'busy-actions',epoch:'epoch',operations:[],proofs:[],workers:{rows:[]},nativeClosed:{rows:[]},discovery:[]},routes:[{epoch:'epoch',requestId:1,originalRouteRequest:true,hold:1,release:2,continueStarted:3,continueFulfilled:4,command:{body:{type:'SaveCheckpoint'}},publicBefore:{previewDisabled:true,applyDisabled:true,cancelDisabled:false,text:'Keep this draft during checkpoint',acceptedNative:[]},publicAfter:{editorHidden:true,stillHeld:true,commands:[],acceptedNative:[]}}]};}
const assessEmpty=f=>emptyNative(f.x,f.e,f.routes);
test('busy-only result retains provisional headers but cannot confer any positive qualification',()=>{const p=assessEmpty(emptyFixture());for(const k of ['qualified','nativeQualified','byteQualified','wasmQualified'])assert.equal(p[k],false);assert.equal(p.kind,'EMPTY-NATIVE');});
for(const [label,mutate]of Object.entries({
 'unselected fixture':v=>v.e.fixture='combined','fallback mode':v=>v.e.mode='NATIVE-COMPLETION','worker':v=>v.e.workers.rows.push({}),'operation':v=>v.e.operations.push({}),'valid proof':v=>v.e.proofs.push({qualified:true}),'valid bytes':v=>v.e.captures={matchesCompleteSealedWASM:true},'native snapshot':v=>v.e.nativeClosed.rows.push({kind:'created',workerId:1}),'late target':v=>v.e.discovery.push({params:{targetInfo:{type:'worker'}}}),'native request':v=>v.x.requests[0].actualHeaders['sec-fetch-dest']='worker','native wire':v=>v.x.network.push({params:{response:{mimeType:'application/wasm'}}}),'borrowed response':v=>v.x.responses[0].originalPairConfirmed=false,'wrong page':v=>v.x.requests[0].frameExposure.ownerPage=false,'lost terminal':v=>v.x.terminals=[],'wrong terminal':v=>v.x.terminals[0].originalRequestObject=false,'missing hold':v=>delete v.routes[0].hold,'missing release':v=>delete v.routes[0].release,'early continuation':v=>v.routes[0].continueStarted=1,'failed continue':v=>v.routes[0].error='failed','different held Request':v=>v.routes[0].requestId=9,'different command':v=>v.routes[0].command.body.type='CommitTextEdit','disabled Cancel':v=>v.routes[0].publicBefore.cancelDisabled=true,'changed accepted state':v=>v.routes[0].publicAfter.acceptedNative=['changed'],'Cancel after release':v=>v.routes[0].publicAfter.stillHeld=false
}))test('actual EMPTY-NATIVE rejects '+label,()=>{const f=emptyFixture();mutate(f);assert.throws(()=>assessEmpty(f));});

const chunk=(b,at=10)=>({kind:'chunk',readerNumber:1,reads:1,count:b.length,at,frameId:1,document:'document',operation:1,start:1,url:origin+'/api/v1/events/stream?after=0',owners:[{clientId:'client',sessionId:'session'}]});
test('actual SSE parser frames an open stream, multiple frames and exact delivered byte ranges',()=>{const f=recoveryFixture(),s=new OriginalSSEFrames(),bytes=Buffer.concat([f.frame,f.frame]);s.push(chunk(bytes),bytes);assert.equal(s.frames.length,2);assert.deepEqual(s.failures,[]);assert.equal(s.frames[0].byteEnd,f.frame.length);assert.equal(s.frames[1].byteStart,f.frame.length);assert.equal(s.frames[1].byteEnd,bytes.length);assert.equal(s.ended,undefined);});
test('actual SSE parser preserves split UTF-8 and chunk boundaries',()=>{const bytes=Buffer.from('data: {"protocolVersion":1,"kind":"framing-only","label":"é🧭"}\n\n'),s=new OriginalSSEFrames();let count=0,reads=0;for(const byte of bytes){count++;reads++;s.push({...chunk(bytes),count,reads},Buffer.from([byte]));}assert.equal(s.frames[0].value.label,'é🧭');assert.equal(s.frames[0].byteEnd,bytes.length);assert.deepEqual(s.failures,[]);});
for(const [label,bytes]of [['malformed',Buffer.from('bad\n\n')],['overflow',Buffer.from('data: '+'x'.repeat(65665))],['invalid UTF8',Buffer.from([0xff,10,10])],['duplicate data',Buffer.from('data: {}\ndata: {}\n\n')]])test('actual SSE parser refuses '+label,()=>{const s=new OriginalSSEFrames();s.push(chunk(bytes),bytes);assert(s.failures.length);});
test('actual SSE parser cannot promote a partial frame or lost/repeated original read',()=>{for(const mode of ['partial','lost','repeated','other reader']){const f=recoveryFixture(),s=new OriginalSSEFrames(),b=f.frame.subarray(0,-1),e=chunk(b);if(mode==='lost')e.reads=2;if(mode==='other reader')e.readerNumber=2;s.push(e,b);if(mode==='repeated')s.push(e,b);s.finish({...e,reads:2});assert(s.failures.length);assert.equal(s.frames.length,0);}});

function publicationFixture(){const f=recoveryFixture(),s=new OriginalSSEFrames();s.push(chunk(f.frame),f.frame);const c={...s.frames[0],parserFailures:[],headers:{type:'text/event-stream'},status:200,responseURL:origin+'/api/v1/events/stream?after=0'},d={control:c,owner:f.reference,recovery:f.reference.recovery,content:f.reference.content};
 const proof={...c,readerCount:1,association:'unique-frame-time-window',responseStatus:200,redirectedFrom:null,browserResponseURL:c.url};const e={frameId:1,document:'document',start:15,end:20,owners:clone(c.owners)};
 const final={...e,owners:clone(e.owners),end:30,url:origin+'/api/v1/events?after=2&recoveryId=recovery_fixture',value:f.final,originalProof:{association:'unique-frame-time-window',responseStatus:200,redirectedFrom:null,readerCount:1}};
 const writes=f.values.map((v,i)=>({...e,kind:'publication-writes',db:'ie-projection-client',at:25+i,transaction:i+1,records:[{store:'rows',key:['generation','event',v.eventId],value:v.workspaceSeq},{store:'rows',key:['generation','document',f.doc.id],value:i?f.finalDocument:f.doc}]}));writes.push({...e,kind:'publication-writes',db:'ie-projection-client',at:40,transaction:3,records:[{store:'meta',key:'published',value:{generation:'generation',cursor:'2',epoch:'1'},at:39}]});
 return {e,d,values:f.values,controls:[final],committed:writes,aborted:[],events:[],cachePrefix:'ie-projection-',proof};}
test('actual SSE branch accepts exact toSeq publication beside later batches and later stream abort',()=>{const f=publicationFixture();Object.assign(f.proof,{earlyCancel:true,readError:true,protocolFailure:{errorText:'net::ERR_ABORTED'}});sseDescriptor(f.d,f.proof);const p=ssePublication(f);assert.equal(p.publication.value.cursor,'2');assert.equal(p.finalCheck.value.nextCursor,'3');assert.equal(p.eventWrites.length,2);});
test('actual SSE descriptor accepts the pinned server charset media type',()=>{const f=publicationFixture();f.proof.headers.type='text/event-stream; charset=utf-8';sseDescriptor(f.d,f.proof);f.proof.headers.type='application/json';assert.throws(()=>sseDescriptor(f.d,f.proof));});
for(const [label,mutate]of Object.entries({
 'wrong offered boundary':f=>f.d.control.offeredId='3','wrong reader':f=>f.proof.readerCount=2,'malformed frames':f=>f.d.control.parserFailures=['bad'],'wrong schema':f=>f.d.recovery.projectionSchema=0,'wrong content URL':f=>f.d.content.url+='x','wrong frame range':f=>f.d.control.byteEnd=999999,'missing original response':f=>f.proof.responseStatus=undefined,'cloned response':f=>f.proof.cloned=true
}))test('actual SSE descriptor refuses '+label,()=>{const f=publicationFixture();mutate(f);assert.throws(()=>sseDescriptor(f.d,f.proof));});
for(const [label,mutate]of Object.entries({
 'wrong client':f=>f.e.owners=[{clientId:'other',sessionId:'session'}],'wrong session':f=>f.e.owners[0].sessionId='other','wrong frame':f=>f.e.frameId=2,'wrong epoch':f=>f.e.document='next','no final':f=>f.controls=[],'wrong validation cursor':f=>f.controls[0].url=f.controls[0].url.replace('after=2','after=3'),'failed validation response':f=>f.controls[0].originalProof.responseStatus=503,'wrong validation context':f=>f.controls[0].value={...f.controls[0].value,recovery:{...f.controls[0].value.recovery,writerEpoch:'2'}},'revalidation clone':f=>f.controls[0].originalProof.cloned=true,'uncommitted generation':f=>f.committed.pop(),'later cursor':f=>f.committed[2].records[0].value.cursor='3','wrong publication epoch':f=>f.committed[2].records[0].value.epoch='2','wrong generation':f=>f.committed[2].records[0].value.generation='other','missing event marker':f=>f.committed[0].records.shift(),'wrong event transaction':f=>f.committed[0].transaction=undefined,'missing intermediate document':f=>f.committed[0].records.pop(),'wrong document transaction':f=>{f.committed[0].records.pop();},'conflicting publication':f=>f.committed.push({...clone(f.committed[2]),at:35}),'aborted generation':f=>f.aborted.push({...clone(f.committed[0]),kind:'publication-aborted'}),'later root recovery':f=>f.events.push({...f.e,kind:'start',start:21,url:origin+'/api/v1/events?after=0'}),'later SSE recovery':f=>f.events.push({...f.e,kind:'start',start:21,url:origin+'/api/v1/events/stream?after=0'}),'equal hash other recovery':f=>f.d.recovery={...f.d.recovery,recoveryId:'other'}
}))test('actual SSE publication refuses '+label,()=>{const f=publicationFixture();mutate(f);assert.throws(()=>ssePublication(f));});
test('SSE qualification cannot be claimed from a flag or an HTTP publication',()=>{assert.equal(sseQualification({validationKind:'sse-reference-publication',validated:true}),false);assert.equal(sseQualification({validationKind:'recovery-publication'}),false);});

test('SSE reference keeps an earlier frame publication before its own content request distinct',()=>{const f=publicationFixture(),prior=clone(f.committed[2]);prior.at=12;prior.records[0].value={generation:'previous',cursor:'0',epoch:'1'};f.committed.unshift(prior);assert.equal(ssePublication(f).publication.value.cursor,'2');prior.at=22;assert.throws(()=>ssePublication(f));});

test('immutable event writer epochs may precede the current recovery writer epoch',()=>{const f=publicationFixture();for(const v of f.values)v.writerEpoch='0';assert.equal(ssePublication(f).publication.value.epoch,'1');});

test('SSE imported events require corresponding committed namespace writes before their markers',()=>{const f=publicationFixture(),v=f.values[0];v.type='BundleImported';v.payload={namespaceId:'namespace',namespaceHash:'sha256:'+'a'.repeat(64),source:{hash:'sha256:'+'b'.repeat(64),byteLength:'4',mediaType:'application/x-ideogram-project'},document:v.payload.document};const ns={...clone(f.committed[0]),at:24,transaction:4,records:[{store:'rows',key:['generation','namespace','namespace'],value:{eventId:v.eventId,namespaceHash:v.payload.namespaceHash}}]};f.committed.unshift(ns);assert.equal(ssePublication(f).eventWrites.length,2);ns.records[0].value.namespaceHash='sha256:'+'c'.repeat(64);assert.throws(()=>ssePublication(f));ns.records[0].value.namespaceHash=v.payload.namespaceHash;ns.at=29;assert.throws(()=>ssePublication(f));});
