import assert from 'node:assert/strict';
import {RESTORED_MODE} from './restored-native.mjs';
const one=(xs,label)=>{assert.equal(xs.length,1,label);return xs[0];};
export function restoredRoutes({current,epochs,page,context,id,objects,rows,fail,order,events}){
 const registrations=[],windows=new Map(),admissions=new Map();let tick=0;const step=()=>++tick;
 const check=e=>{assert(e&&e.mode===RESTORED_MODE&&e.fixture==='restored-reads');assert(epochs().includes(e)&&e.index<=2&&!e.closed&&!e.navigationSealed,'Active original epoch');};
 const guarded=fn=>{try{return fn();}catch(error){fail(current(),error);throw error;}};
 const stamp=(kind,data)=>{const row=Object.freeze({sequence:order(),kind,...data});events.push(row);return row;};
 const windowFor=e=>{const w=windows.get(e);assert(w,'Original restoration window');assert.equal(current(),e,'Current captured restoration epoch');assert.equal(page.context(),w.context,'Original window context');assert.equal(page.mainFrame(),w.frame,'Original window frame');assert.equal(e.origin,w.origin);assert.equal(e.pid,w.pid);assert.equal(e.server,w.server);assert.equal(e.server.origin,w.origin,'Original window server origin');assert.equal(e.server.instance,w.instance);return w;};
 function begin(e){if(e.index!==2)return;check(e);assert(!windows.has(e));assert.equal(registrations.length,1,'Registration precedes restoration admission');const w={epoch:e,page,context,frame:page.mainFrame(),origin:e.origin,pid:e.pid,server:e.server,instance:e.server.instance,admitted:[],cut:null};windows.set(e,w);w.start=stamp('restoration-window-start',{epochIndex:e.index,origin:e.origin,pid:e.pid,instance:w.instance});}
 function activate(e){if(e.index!==2)return;const w=windowFor(e);assert(!w.owner&&e.owner&&e.epoch,'One original window activation');w.owner=Object.freeze({...e.owner});w.activeEpoch=e.epoch;}
 function admit(q,row){const e=current();if(e?.index!==2)return;const w=windowFor(e);assert.equal(objects.get(row.id),q);assert(!admissions.has(row.id),'Unique original admission');const receipt=stamp('restoration-request',{epochIndex:e.index,requestId:row.id,url:row.url,method:row.method,ownerPage:row.frameExposure.ownerPage,ownerFrame:row.frameExposure.ownerFrame,ownerContext:row.frameExposure.ownerContext,arrivalActivated:!!e.epoch});const a=Object.freeze({receipt,request:q,epoch:e});admissions.set(row.id,a);w.admitted.push(a);}
 function confirm(r){return guarded(()=>{const e=current();check(e);const w=windowFor(e);assert.equal(e.epoch,w.activeEpoch,'Original confirmed epoch');assert.deepEqual(e.owner,w.owner,'Original confirmed owner');assert(w.owner&&!w.cut,'Exactly one confirmed-restoration marker');assert(r.registered&&r.removed&&r.removalStarted&&!r.normalContractFailed&&!r.registrationError&&!r.removalError,'Successful original removal before confirmation');const h=one(r.holds,'One forwarded original before confirmation');assert(h.epoch===e&&h.continueFulfilled&&!h.error&&!h.normalContractFailed&&!h.workflowError,'Original forwarding before confirmation');const membership=Object.freeze(w.admitted.map(a=>a.receipt.requestId));w.cut=stamp('confirmed-restoration',{epochIndex:e.index,epoch:e.epoch,origin:e.origin,pid:e.pid,instance:w.instance,afterRemoval:r.removed,requestIds:membership});return w.cut;});}
 function membership(e,x,r,h){const w=windowFor(e);assert(w.cut,'Confirmed restoration boundary required');assert.equal(e.epoch,w.activeEpoch);assert.deepEqual(e.owner,w.owner);assert(events.includes(w.start)&&events.includes(w.cut),'Original immutable boundary receipts');assert(events.every((event,i)=>i===0||event.sequence>events[i-1].sequence),'Ordered original restoration receipts');assert(w.start.sequence<w.cut.sequence);assert.equal(w.cut.afterRemoval,r.removed);const before=w.admitted.filter(a=>a.receipt.sequence<w.cut.sequence);assert.deepEqual(before.map(a=>a.receipt.requestId),w.cut.requestIds,'Immutable original request membership');const matches=before.filter(a=>a.receipt.url===e.origin+r.path&&a.receipt.method==='GET');const admitted=one(matches,'One exact image read in confirmed restoration window');assert.equal(admitted.request,h.request,'Original held object in restoration window');assert.equal(admitted.epoch,e);for(const a of w.admitted){assert.equal(admissions.get(a.receipt.requestId),a);assert.equal(objects.get(a.receipt.requestId),a.request,'Original admitted object retained');assert(events.includes(a.receipt));assert(a.receipt.sequence>w.start.sequence);}
  const q=one(x.requests.filter(q=>q.id===admitted.receipt.requestId),'Original admitted Request row');assert.equal(q.url,admitted.receipt.url);assert.equal(q.method,admitted.receipt.method);return {q,window:{start:w.start,confirmed:w.cut,matchingRequestId:q.id,laterRequestIds:w.admitted.filter(a=>a.receipt.sequence>w.cut.sequence).map(a=>a.receipt.requestId),scope:'Observed original Request order; browser issuance timing unobserved'}};
 }

 function register(pattern,path){return guarded(()=>{
  const e=current();check(e);assert.equal(e.index,1);assert.equal(registrations.length,0);assert(/^\/api\/v1\/assets\/[^/]+\/content$/.test(path));assert.equal(pattern,'**'+path);assert(page.context()===context);const frame=page.mainFrame();
  const r={pattern,path,registeredEpochIndex:e.index,registrationStarted:step(),holds:[]};Object.defineProperties(r,{page:{value:page},context:{value:context},frame:{value:frame},epoch:{value:e}});registrations.push(r);
  return {confirmedRestoration:()=>confirm(r),registrationFailed:error=>{r.registrationError=String(error);fail(current(),error);},removalFailed:error=>{r.removalError=String(error);fail(current(),error);},cleanupRemoving:()=>{r.normalContractFailed=true;r.cleanupRemovalStarted=step();},cleanupRemoved:()=>{r.cleanupRemoved=step();},registered:()=>guarded(()=>{assert(!r.registered);r.registered=step();}),hold:route=>guarded(()=>{
   const own=current();check(own);assert(r.registered&&!r.registrationError&&!r.removalStarted);assert.equal(own.index,2);const q=route.request();assert.equal(objects.get(id(q)),q);assert.equal(q.frame(),frame);assert.equal(q.frame().page(),page);assert.equal(page.context(),context);assert.equal(q.method(),'GET');assert.equal(q.url(),own.origin+path);assert.equal(r.holds.length,0,'Exactly one original held image');
   const row={registration:0,epochIndex:own.index,origin:own.origin,pid:own.pid,instance:own.server.instance,requestId:id(q),url:q.url(),method:q.method(),arrivalActivated:!!own.epoch,arrivalEpoch:own.epoch??null,originalRouteRequest:true,originalPage:true,originalFrame:true,originalContext:true,hold:step()};Object.defineProperties(row,{epoch:{value:own},request:{value:q},server:{value:own.server}});rows.push(row);r.holds.push(row);
   const verify=()=>{assert.equal(current(),own,'Never rebind the held epoch');check(own);assert(own.epoch&&own.owner,'Original held epoch activated');assert.equal(own.origin,row.origin);assert.equal(own.pid,row.pid);assert.equal(own.server,row.server);assert.equal(own.server.instance,row.instance);if(row.arrivalActivated)assert.equal(own.epoch,row.arrivalEpoch);assert.equal(route.request(),q);assert.equal(q.frame(),frame);assert.equal(q.frame().page(),page);assert.equal(page.context(),context);};
   const originalContinue=route.continue;let forwarding;
   const forward=cleanup=>{
    if(forwarding)return forwarding;
    if(cleanup){row.normalContractFailed=true;row.cleanupContinueStarted=step();}
    else guarded(()=>{verify();assert(row.release&&!row.continueStarted);row.continueStarted=step();});
    try{const value=Reflect.apply(originalContinue,route,[]);forwarding=Promise.resolve(value).then(result=>{if(cleanup)row.cleanupContinueFulfilled=step();else guarded(()=>{verify();row.continueFulfilled=step();});return result;},error=>{row.error=String(error);fail(own,error);throw error;});}
    catch(error){row.error=String(error);fail(own,error);forwarding=Promise.reject(error);}
    return forwarding;
   };
   return {release:()=>guarded(()=>{verify();assert(!row.release);row.activatedEpoch=own.epoch;row.release=step();}),continue:async()=>forward(false),cleanupContinue(error){row.workflowError=String(error);return forward(!row.continueStarted);}};

  }),removing:()=>guarded(()=>{assert(r.registered&&!r.registrationError&&!r.removalStarted);assert.equal(r.holds.length,1);assert(r.holds.every(h=>h.continueFulfilled&&!h.error));r.removalStarted=step();}),removed:()=>guarded(()=>{assert(r.removalStarted&&!r.removed);r.removed=step();})};
 });}
 function assess(e,x){checkClosed(e);const rs=registrations.filter(r=>r.epoch===epochs()[0]);assert(rs.length<=1);const own=rows.filter(r=>r.epoch===e);assert.equal(own.length,e.index===1?0:1,'Zero held images first epoch; one second');if(e.index===1)return {epochIndex:1,held:0};
  const r=one(rs,'Original registration'),h=one(own,'Original held image');assert.equal(registrations.length,1);assert(r.registered&&r.removalStarted&&r.removed&&!r.normalContractFailed&&!r.registrationError&&!r.removalError);assert.equal(r.page,page);assert.equal(r.frame,page.mainFrame());assert.equal(r.context,context);assert.equal(h.activatedEpoch,e.epoch);assert.equal(h.origin,e.origin);assert.equal(h.pid,e.pid);assert.equal(h.instance,e.server.instance);assert.equal(h.server,e.server);assert(!h.normalContractFailed&&!h.workflowError&&!h.error&&h.release&&h.continueStarted&&h.continueFulfilled);assert(r.registrationStarted<r.registered&&r.registered<h.hold&&h.hold<h.release&&h.release<h.continueStarted&&h.continueStarted<h.continueFulfilled&&h.continueFulfilled<r.removalStarted&&r.removalStarted<r.removed);
  const {q,window}=membership(e,x,r,h);assert.equal(q.id,h.requestId);assert.equal(objects.get(q.id),h.request);assert.equal(q.method,'GET');const p=one(x.responses.filter(p=>p.requestId===q.id),'Held original Response'),t=one(x.terminals.filter(t=>t.requestId===q.id),'Held original terminal');assert(p.originalRequestObject&&p.originalPairConfirmed&&t.originalRequestObject);assert.equal(p.url,q.url);assert.equal(t.url,q.url);assert.equal(p.fromServiceWorker,false);return {epochIndex:2,held:1,requestId:q.id,window,registration:{pattern:r.pattern,path:r.path,registrationStarted:r.registrationStarted,registered:r.registered,removalStarted:r.removalStarted,removed:r.removed},forwarding:h,observedEOF:false};
 }
 function checkClosed(e){assert.equal(e.mode,RESTORED_MODE);assert.equal(e.fixture,'restored-reads');assert(epochs().includes(e)&&e.index>=1&&e.index<=2);}
 return {begin,activate,admit,register,assess,finish(){assert.equal(epochs().length,2);assert.equal(registrations.length,1);assert.equal(rows.length,1);assert.equal(rows[0].epoch,epochs()[1]);},registrations};
}
