// Generated by tooling/raster/bounded-webp/build.mjs --adopt; do not edit.
export const BOUNDED_WEBP = {
  "abiVersion": 1,
  "version": "1.6.0-ideogram.1",
  "platform": "darwin",
  "arch": "arm64",
  "path": "vendor/raster/bounded-webp/1.6.0-ideogram.1/darwin-arm64/libideogram-webp.1.dylib",
  "bytes": 249880,
  "hash": "sha256:4aa72a0fe8eb08d65a75cfbfca069bda5b796c3c44b8bf672f587ef8a079d5ff",
  "sourceHash": "sha256:e4ab7009bf0629fd11982d4c2aa83964cf244cffba7347ecd39019a9e38c4564",
  "manifestHash": "sha256:35313df37b2e04891212bf8c89de85068383372ce68830cfa9e4ff3a70628453",
  "producerHash": "sha256:35878592c0ada377c9ff6dbcb738aab52f2106fad798d9a49abe465d6b8b3424"
} as const;
