import test from 'node:test';import assert from 'node:assert/strict';import {writeFile,readFile} from 'node:fs/promises';import {DatabaseSync} from 'node:sqlite';import {join} from 'node:path';
import {setup,terminal,edit,copy,preview,workspace,upload,doc,binary} from './source/tests/portable/helpers.mjs';import {importRaster} from './source/tests/raster/helpers.mjs';import {unpack,pack,canonical,sha} from './reviewer-archive.mjs';
function records(e){const m=JSON.parse(e.get('manifest.json'));return {m,segments:m.segments.map(s=>({s,rows:e.get(s.path).toString().trimEnd().split('\n').map(JSON.parse)}))};}
function save(e,x){for(const {s,rows}of x.segments){const b=Buffer.from(rows.map(canonical).join('\n')+'\n');e.set(s.path,b);s.bytes=String(b.length);s.sha256=sha(b);s.recordCount=String(rows.length);}e.set('manifest.json',Buffer.from(canonical(x.m)));}
const cases=['prefix','tail','interior-checkpoint','missing-descriptor','extra-descriptor','bad-count','bad-first','bad-last','bad-hash','bad-receipt-command','bad-domain-revision','domain-revision-hidden-by-tail','duplicate-event-rehashed','split-command-rehashed','inconsistent-epoch-rehashed','unreferenced-scope','nested-conflicting-scope'];
test('reviewer format2 receipt framing, nested fresh-workspace roundtrip and hostile structural corpus',async t=>{
 const f=await setup(t);await terminal(f,f.command({}, {width:3,height:2}));const {asset}=await importRaster(f,'hidden-alpha.png'),native=await edit(f,{type:'ImportAsset',assetId:asset.id,layerId:'picture',name:'Original',draft:null}),checkpoint=await edit(f,{type:'SaveCheckpoint',name:'Retained'});const saved=await copy(f),baseline=await doc(f),base=unpack(saved.bytes),decoded=records(base),tx=decoded.segments.flatMap(x=>x.rows).find(r=>r.kind==='transaction'&&r.receipt.commandId===native.command.command.commandId),events=decoded.segments.flatMap(x=>x.rows).filter(r=>r.kind==='event'&&r.event.commandId===tx.receipt.commandId).map(x=>x.event);
 assert.equal(decoded.m.formatVersion,2);assert.deepEqual(tx.receipt,native.receipt);assert.equal(tx.eventsHash,'sha256:'+sha(Buffer.from(events.map(e=>canonical(e)+'\n').join(''))));assert.equal(tx.eventCount,'2');
 const healthy=await preview(f,pack(base));assert.equal(healthy.review.editable,true);await workspace(f,{type:'ImportBundle',reviewId:healthy.review.reviewId,reviewHash:healthy.review.reviewHash});const nested=await copy(f,healthy.review.documentId),fresh=await setup(t),np=await preview(fresh,nested.bytes);assert.equal(np.review.editable,true);await workspace(fresh,{type:'ImportBundle',reviewId:np.review.reviewId,reviewHash:np.review.reviewHash});assert.deepEqual((await binary(fresh,'/api/v1/assets/'+(await doc(fresh,np.review.documentId)).image.compositeAssetId+'/content')).bytes,(await binary(f,'/api/v1/assets/'+baseline.image.compositeAssetId+'/content')).bytes);assert(nested.bytes.includes(saved.bytes)||nested.bytes.includes(pack(base)));
 const result=[];
 for(const kind of cases){const e=unpack(kind==='nested-conflicting-scope'?nested.bytes:saved.bytes),x=records(e),r=x.segments.find(x=>x.s.kind==='records'),ev=x.segments.find(x=>x.s.kind==='events');let descriptor=r.rows.find(r=>r.kind==='transaction'&&(kind==='nested-conflicting-scope'?r.sourceArchive!==null:r.receipt.commandId===native.command.command.commandId));const selected=()=>ev.rows.filter(y=>y.event.transactionId===descriptor.receipt.transactionId),rehash=()=>descriptor.eventsHash='sha256:'+sha(Buffer.from(selected().map(y=>canonical(y.event)+'\n').join('')));
 if(kind==='prefix')ev.rows=ev.rows.filter(y=>y.event.workspaceSeq!==descriptor.receipt.fromSeq);
 if(kind==='tail')ev.rows=ev.rows.filter(y=>y.event.workspaceSeq!==descriptor.receipt.toSeq);
 if(kind==='interior-checkpoint')ev.rows=ev.rows.filter(y=>y.event.commandId!==checkpoint.command.command.commandId);
 if(kind==='missing-descriptor')r.rows=r.rows.filter(y=>y!==descriptor);
 if(kind==='extra-descriptor')r.rows.push(structuredClone(descriptor));
 if(kind==='bad-count')descriptor.eventCount='99';
 if(kind==='bad-first'){descriptor.receipt.fromSeq=String(BigInt(descriptor.receipt.fromSeq)-1n);descriptor.eventCount='3';}
 if(kind==='bad-last'){descriptor.receipt.toSeq=String(BigInt(descriptor.receipt.toSeq)+1n);descriptor.eventCount='3';}
 if(kind==='bad-hash')descriptor.eventsHash='sha256:'+'e'.repeat(64);
 if(kind==='bad-receipt-command')descriptor.receipt.commandId='not_the_event_command';
 if(kind==='bad-domain-revision')descriptor.receipt.documentRevision='999';
 if(kind==='domain-revision-hidden-by-tail'){const a=selected();[a[0].event.workspaceSeq,a[1].event.workspaceSeq]=[a[1].event.workspaceSeq,a[0].event.workspaceSeq];a[0].event.streamSeq=a[0].event.workspaceSeq;ev.rows.sort((a,b)=>BigInt(a.event.workspaceSeq)<BigInt(b.event.workspaceSeq)?-1:1);descriptor.receipt.documentRevision='999';rehash();}
 if(kind==='duplicate-event-rehashed'){selected()[1].event.eventId=selected()[0].event.eventId;rehash();}
 if(kind==='inconsistent-epoch-rehashed'){selected()[1].event.writerEpoch='999';rehash();}
 if(kind==='split-command-rehashed'){const a=selected(),second=structuredClone(descriptor);second.receipt.transactionId='reviewer_split';second.receipt.fromSeq=second.receipt.toSeq;second.eventCount='1';a[1].event.transactionId=second.receipt.transactionId;second.eventsHash='sha256:'+sha(Buffer.from(canonical(a[1].event)+'\n'));descriptor.receipt.toSeq=descriptor.receipt.fromSeq;descriptor.receipt.documentRevision=null;descriptor.eventCount='1';rehash();r.rows.push(second);}
 if(kind==='unreferenced-scope'){const extra=structuredClone(descriptor);extra.sourceArchive='sha256:'+'f'.repeat(64);r.rows.push(extra);}
 if(kind==='nested-conflicting-scope')descriptor.eventsHash='sha256:'+'e'.repeat(64);
 save(e,x);const b=pack(e),stage=await upload(f,b),c=f.command({documentId:null,expectedDocumentRevision:null,body:{type:'PreviewBundleImport',stagingId:stage.stagingId,expectedSha256:stage.sha256}}),res=await terminal(f,c);const db=new DatabaseSync(join(f.root,'metadata.sqlite'),{readOnly:true}),name=db.prepare('SELECT filename FROM staged_assets WHERE id=?').get(stage.stagingId).filename;db.close();assert.deepEqual(await readFile(join(f.root,'uploads',name)),b);assert.deepEqual(await doc(f),baseline);result.push({kind,status:res.json.receipt.status,receipt:res.json.receipt,sha256:sha(b),sourcePreserved:true});await writeFile(new URL('./format2-'+kind+'.zip',import.meta.url),b);await writeFile(new URL('./format2-oracle.json',import.meta.url),JSON.stringify({target:'5dab27df7555606d6ee09c21bad62015f0ed8d96',originalReceipt:native.receipt,descriptor:tx,framedBytes:events.map(e=>canonical(e)+'\n').join(''),healthyEditable:true,nestedFreshWorkspace:true,result},null,2));}
 assert(result.every(r=>r.status==='rejected'),JSON.stringify(result.filter(r=>r.status!=='rejected')));
});
