// Qualification-only official static Noto corpus. No runtime network fallback.
import { createHash } from 'node:crypto';
import { lstat, mkdir, readFile, realpath, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, join, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
const REPO=resolve(dirname(fileURLToPath(import.meta.url)),'../../..');
const MiB=1048576, VERSION='perf-noto-static-1';
const NOTO='ffebf8c1ee449e544955a7e813c54f9b73848eac',CJK='f8d157532fbfaeda587e826d4cd5b21a49186f7c';
const hash=b=>'sha256:'+createHash('sha256').update(b).digest('hex');
const emit=v=>JSON.stringify(v,null,2)+'\n';
export const FONT_SOURCES=Object.freeze(['NotoSans','NotoSansArabic','NotoSansDevanagari','NotoSansSymbols2','NotoSansBengali','NotoSansGujarati','NotoSansGurmukhi','NotoSansHebrew','NotoSansKannada','NotoSansKhmer','NotoSansMalayalam','NotoSansMyanmar','NotoSansOriya','NotoSansTamil','NotoSansTelugu'].map(id=>({id,file:id+'-Regular.ttf',url:`https://raw.githubusercontent.com/notofonts/noto-fonts/${NOTO}/hinted/ttf/${id}/${id}-Regular.ttf`,revision:NOTO,license:'Noto-OFL.txt'})).concat([{id:'NotoSansSC',file:'NotoSansSC-Regular.otf',url:`https://raw.githubusercontent.com/notofonts/noto-cjk/${CJK}/Sans/SubsetOTF/SC/NotoSansSC-Regular.otf`,revision:CJK,license:'Noto-CJK-OFL.txt'}]));
export const NORMAL_FACE_IDS=Object.freeze(['NotoSansArabic','NotoSansDevanagari','NotoSansSymbols2','NotoSansSC']);
export const LICENSE_SOURCES=Object.freeze([{id:'Noto-OFL.txt',url:`https://raw.githubusercontent.com/notofonts/noto-fonts/${NOTO}/LICENSE`,revision:NOTO},{id:'Noto-CJK-OFL.txt',url:`https://raw.githubusercontent.com/notofonts/noto-cjk/${CJK}/Sans/LICENSE`,revision:CJK}]);
export function inspectStaticFace(input) {
  const b=Buffer.from(input);if(b.length<12||!['00010000','4f54544f'].includes(b.subarray(0,4).toString('hex')))throw Error('Expected standalone static TTF/CFF1 OTF');
  const count=b.readUInt16BE(4);if(count<1||count>128||12+count*16>b.length)throw Error('Malformed sfnt tables');const tables=new Map();
  for(let i=0;i<count;i++){const at=12+i*16,tag=b.toString('ascii',at,at+4),offset=b.readUInt32BE(at+8),length=b.readUInt32BE(at+12);if(tables.has(tag)||offset+length>b.length)throw Error('Malformed sfnt table');tables.set(tag,{offset,length});}
  if(['fvar','gvar','COLR','CBDT','CBLC','sbix','SVG '].some(t=>tables.has(t)))throw Error('Variable/color/bitmap font unsupported for this corpus');
  const os=tables.get('OS/2');if(!os||os.length<64)throw Error('Missing OS/2 embedding/style fields');const p=os.offset,fsType=b.readUInt16BE(p+8),weight=b.readUInt16BE(p+4),width=b.readUInt16BE(p+6),selection=b.readUInt16BE(p+62);if(fsType!==0||weight!==400||width!==5||(selection&1))throw Error('Fixture font must permit embedding and be regular upright normal width');
  const names={};const name=tables.get('name');if(name&&name.length>=6){const n=b.readUInt16BE(name.offset+2),strings=name.offset+b.readUInt16BE(name.offset+4);for(let i=0;i<n;i++){const at=name.offset+6+i*12;if(at+12>name.offset+name.length)throw Error('Malformed font names');const platform=b.readUInt16BE(at),id=b.readUInt16BE(at+6),length=b.readUInt16BE(at+8),offset=strings+b.readUInt16BE(at+10);if(offset+length>name.offset+name.length)throw Error('Malformed font name');if(platform===3&&[0,1,2,5,6,13,14].includes(id)&&!names[id]){const copy=Buffer.from(b.subarray(offset,offset+length));copy.swap16();names[id]=copy.toString('utf16le');}}}
  if(!names[13]?.includes('Open Font License'))throw Error('Font lacks retained OFL name record');
  return {format:tables.has('CFF ')?'static-otf':'static-ttf',faceIndex:0,fsType,weight,width,italic:false,nameRecords:names};
}
export function glyphForCodePoint(input,codepoint) {
  const b=Buffer.from(input),count=b.readUInt16BE(4);let cmap;
  for(let i=0;i<count;i++){const at=12+i*16;if(b.toString('ascii',at,at+4)==='cmap')cmap=b.readUInt32BE(at+8);}if(cmap===undefined)return 0;
  const n=b.readUInt16BE(cmap+2),subtables=[];for(let i=0;i<n;i++){const at=cmap+4+i*8,platform=b.readUInt16BE(at),encoding=b.readUInt16BE(at+2),offset=cmap+b.readUInt32BE(at+4);if(platform===0||platform===3&&(encoding===1||encoding===10))subtables.push(offset);}
  for(const at of subtables.sort((a,c)=>b.readUInt16BE(c)-b.readUInt16BE(a))){const format=b.readUInt16BE(at);if(format===12){const groups=b.readUInt32BE(at+12);for(let i=0;i<groups;i++){const p=at+16+i*12,start=b.readUInt32BE(p),end=b.readUInt32BE(p+4);if(codepoint>=start&&codepoint<=end)return b.readUInt32BE(p+8)+codepoint-start;}}else if(format===4&&codepoint<=65535){const seg=b.readUInt16BE(at+6)/2,endAt=at+14,startAt=endAt+seg*2+2,deltaAt=startAt+seg*2,rangeAt=deltaAt+seg*2;for(let i=0;i<seg;i++){const end=b.readUInt16BE(endAt+i*2),start=b.readUInt16BE(startAt+i*2);if(codepoint<start||codepoint>end)continue;const delta=b.readInt16BE(deltaAt+i*2),range=b.readUInt16BE(rangeAt+i*2);if(range===0)return(codepoint+delta)&65535;const where=rangeAt+i*2+range+(codepoint-start)*2;if(where+2>b.length)return 0;const glyph=b.readUInt16BE(where);return glyph?(glyph+delta)&65535:0;}}}return 0;
}
export function checkCoverage(faces,text) {const missing=[];for(const point of new Set(Array.from(text,character=>character.codePointAt(0))))if(point!==10&&point!==13&&!faces.some(face=>glyphForCodePoint(face,point)!==0))missing.push('U+'+point.toString(16).toUpperCase());if(missing.length)throw Error('Exact qualification fonts lack glyphs: '+missing.join(', '));return {codepoints:new Set(Array.from(text)).size,missing:[]};}
async function boundedFetch(url,maximum,signal){const parsed=new URL(url);if(parsed.protocol!=='https:'||parsed.hostname!=='raw.githubusercontent.com'||!/(?:ffebf8c1ee449e544955a7e813c54f9b73848eac|f8d157532fbfaeda587e826d4cd5b21a49186f7c)/.test(parsed.pathname))throw Error('Unpinned font source');const response=await fetch(url,{redirect:'error',signal:signal?AbortSignal.any([signal,AbortSignal.timeout(60000)]):AbortSignal.timeout(60000)});if(!response.ok||!response.body)throw Error('Font source returned '+response.status);const chunks=[];let bytes=0;for await(const chunk of response.body){bytes+=chunk.length;if(bytes>maximum)throw Error('Font download exceeds explicit bound');chunks.push(chunk);}return Buffer.concat(chunks);}
export async function produceFontCorpus({output,allowNetwork=false,lockPath=join(REPO,'tooling/qualification/campaigns/fonts.lock.json'),signal}={}) {
  if(!allowNetwork)throw Error('Font acquisition requires explicit allowNetwork:true during fixture preparation');if(!isAbsolute(output)||!resolve(output).startsWith(join(REPO,'artifacts')+sep))throw Error('Use a new artifact directory');if(await realpath(dirname(resolve(output)))!==dirname(resolve(output)))throw Error('Font output parent must be canonical and nonsymlinked');output=resolve(output);await mkdir(output,{mode:0o700,recursive:false});
  let lock;try{lock=JSON.parse(await readFile(lockPath,'utf8'));}catch(error){if(error.code!=='ENOENT')throw error;}
  const manifest={kind:'qualification-font-corpus',version:VERSION,provenance:'Unmodified official Noto static font files and their complete OFL notices, acquired from exact upstream commits. Separate qualification inputs; shipped font distribution remains unchanged.',faces:[],licenses:[],normalFaceIds:NORMAL_FACE_IDS};
  for(const license of LICENSE_SOURCES){const bytes=await boundedFetch(license.url,65536,signal);if(!bytes.includes(Buffer.from('SIL OPEN FONT LICENSE Version 1.1')))throw Error('Unexpected license bytes');const record={...license,path:join(output,license.id),sha256:hash(bytes),byteLength:String(bytes.length)};if(lock&&lock.licenses.find(x=>x.id===license.id)?.sha256!==record.sha256)throw Error('License lock identity changed');await writeFile(record.path,bytes,{flag:'wx',mode:0o600});manifest.licenses.push(record);}
  for(const source of FONT_SOURCES){const bytes=await boundedFetch(source.url,16*MiB,signal),inspection=inspectStaticFace(bytes),license=manifest.licenses.find(l=>l.id===source.license),record={...source,path:join(output,source.file),sha256:hash(bytes),byteLength:String(bytes.length),...inspection,licenseId:'OFL-1.1',licensePath:license.path,licenseHash:license.sha256,embedding:'permitted',unmodified:true};if(lock&&lock.faces.find(x=>x.id===source.id)?.sha256!==record.sha256)throw Error('Font lock identity changed');await writeFile(record.path,bytes,{flag:'wx',mode:0o600});manifest.faces.push(record);}
  const manifestPath=join(output,'fonts.json');await writeFile(manifestPath,emit(manifest),{flag:'wx',mode:0o600});
  if(!lock)await writeFile(lockPath,emit({kind:'qualification-font-input-lock',version:VERSION,faces:manifest.faces.map(({id,url,revision,sha256,byteLength,licenseHash})=>({id,url,revision,sha256,byteLength,licenseHash})),licenses:manifest.licenses.map(({id,url,revision,sha256,byteLength})=>({id,url,revision,sha256,byteLength}))}),{flag:'wx',mode:0o600});
  await verifyFontCorpus(manifestPath,{workload:'WXs',lockPath});await verifyFontCorpus(manifestPath,{workload:'WXn',lockPath});return {manifestPath,...manifest};
}
export async function verifyFontCorpus(path,{workload,lockPath=join(REPO,'tooling/qualification/campaigns/fonts.lock.json')}={}) {
  if(typeof path!=='string'||!isAbsolute(path))throw Error('An exact sealed qualification font manifest is required');const file=await lstat(path);if(!file.isFile()||file.isSymbolicLink())throw Error('Unsafe font manifest');const manifestBytes=await readFile(path),manifest=JSON.parse(manifestBytes.toString('utf8')),after=await lstat(path);if(after.dev!==file.dev||after.ino!==file.ino||after.size!==file.size||after.mtimeMs!==file.mtimeMs||after.ctimeMs!==file.ctimeMs)throw Error('Font manifest changed while reading');if(manifest.kind!=='qualification-font-corpus'||manifest.version!==VERSION)throw Error('Unsupported font corpus');
  const lock=JSON.parse(await readFile(lockPath,'utf8')),want=workload==='WXn'?NORMAL_FACE_IDS:FONT_SOURCES.map(f=>f.id),faces=want.map(id=>manifest.faces.find(f=>f.id===id));if(faces.some(f=>!f)||new Set(faces.map(f=>f.sha256+':'+f.faceIndex)).size!==want.length)throw Error('Missing or duplicate exact font faces');let bytes=0;const loaded=[];
  for(const face of faces){const info=await lstat(face.path),resolved=await realpath(face.path);if(!info.isFile()||info.isSymbolicLink()||resolved!==face.path)throw Error('Unsafe font path');const contents=await readFile(face.path),expected=lock.faces.find(x=>x.id===face.id);if(!expected||hash(contents)!==expected.sha256||hash(contents)!==face.sha256||String(contents.length)!==expected.byteLength||face.faceIndex!==0)throw Error('Font bytes disagree with sealed identity');inspectStaticFace(contents);const license=await readFile(face.licensePath);if(hash(license)!==expected.licenseHash||face.licenseHash!==expected.licenseHash)throw Error('Font license identity changed');bytes+=contents.length;loaded.push(contents);}
  if(bytes>(workload==='WXn'?16:64)*MiB)throw Error('Exact font corpus exceeds workload bytes');
  checkCoverage(loaded,'Cafe\u0301 A\u0300 Latin العربية العَرَبِيَّة اتجاه देवनागरी हिन्दी 中文 日本語 ✈ ☀ ★ unbrokenx\n');
  return {manifestPath:path,manifestHash:hash(manifestBytes),faces,totalBytes:bytes,rendererManifestPath:join(REPO,'vendor/text/manifest.json'),rendererManifestHash:hash(await readFile(join(REPO,'vendor/text/manifest.json')))};
}
