import { readdir } from 'node:fs/promises';
import { isAbsolute, join } from 'node:path';
import { isDeepStrictEqual } from 'node:util';
import { fileIdentity, digest, readSealedJSON } from './common.mjs';
import { canonicalVitalsVersion, loadCanonicalVitalsLibrary } from './browser-canonical-vitals.mjs';

export const CAMPAIGN_TOOL_VERSIONS = Object.freeze({ typescript: '7.0.2', vite: '8.3.1', lit: '3.3.3', 'signal-polyfill': '0.2.2', 'signal-utils': '0.21.1', '@playwright/test': '1.63.0', 'playwright-core': '1.63.0', sharp: '0.35.4' });
export const CAMPAIGN_TOOL_NAMES = Object.freeze(Object.keys(CAMPAIGN_TOOL_VERSIONS));
// These file hashes were independently extracted from cached npm tarballs after
// checking the tarball SHA512 against the repository's official registry lock.
// They are verified artifact hashes, not publisher-published per-file hashes.
export const CAMPAIGN_BROWSER_MANIFEST = Object.freeze({
  comment: 'Do not edit this file, use utils/roll_browser.js',
  browsers: [
    { name: 'chromium', revision: '1243', installByDefault: true, browserVersion: '153.0.8010.12', title: 'Chrome for Testing' },
    { name: 'chromium-headless-shell', revision: '1243', installByDefault: true, browserVersion: '153.0.8010.12', title: 'Chrome Headless Shell' },
    { name: 'firefox', revision: '1543', installByDefault: true, browserVersion: '155.0', title: 'Firefox' },
    { name: 'webkit', revision: '2359', installByDefault: true, revisionOverrides: { mac14: '2251', 'mac14-arm64': '2251' }, browserVersion: '26.6', title: 'WebKit' },
    { name: 'ffmpeg', revision: '1011', installByDefault: true },
    { name: 'winldd', revision: '1007', installByDefault: false },
    { name: 'android', revision: '1001', installByDefault: false },
  ],
});
export const CAMPAIGN_BROWSER_MANIFEST_IDENTITY = Object.freeze({ path: 'node_modules/playwright-core/browsers.json', bytes: 1137, sha256: 'sha256:545d52f8382c391e605562c330e9c1c534a16045898203037a49bb8bd769a946' });
export const CAMPAIGN_VITALS_SOURCE = Object.freeze({ version: canonicalVitalsVersion, bytes: 8991, sha256: 'sha256:1e5e9b9af6b8d71cfef508e5a869c53b4cf2bbccad8c9b5ac664c34e93f6151a', integrity: 'sha512-oto5x6dLEgrRqfcWed+pZEUb2q6ikbFmqF54CRDhI/QGbn+qxC49b4C4OkbH+kb9C3a8shpFD3SgR9kRcs80ZQ==' });
const vitalOperations = new Set(['navigation.ready', 'interaction.brush', 'text.interaction']);
const hash = value => typeof value === 'string' && /^sha256:[a-f0-9]{64}$/.test(value);
const file = value => !!value && Number.isSafeInteger(value.bytes) && value.bytes > 0 && hash(value.sha256);

/** Both runtime and receipt verification derive requirements from the selected
 * immutable cells. C0/H0 may prepare an installation, so developer-only jobs
 * require the pinned Node identity without pretending dependencies exist. */
export function campaignToolRequirements(plan) {
  if (!Array.isArray(plan?.jobs) || !plan.jobs.length || plan.jobs.some(job => !Array.isArray(job?.cells) || !job.cells.length)) return null;
  const cells = plan.jobs.flatMap(job => job.cells);
  if (cells.some(cell => !cell || !['developer', 'browser', 'backend', 'adapters'].includes(cell.handler))) return null;
  const browsers = [...new Set(cells.filter(cell => cell.handler === 'browser').map(cell => cell.parameters?.browser ?? cell.browser ?? 'chromium'))];
  if (browsers.some(name => !['chromium', 'firefox', 'webkit'].includes(name))) return null;
  return { developerOnly: cells.every(cell => cell.handler === 'developer'), browsers, canonicalVitals: cells.some(cell => cell.handler === 'browser' && vitalOperations.has(cell.operation)) };
}

export function validToolIdentity(identity, plan) {
  const required = campaignToolRequirements(plan);
  if (!required || identity?.node?.version !== '26.10.0' || !file(identity.node.executable) || typeof identity.node.executable.path !== 'string' || !isAbsolute(identity.node.executable.path)) return false;
  if (required.developerOnly) return true;
  if (!file(identity.lock) || !Array.isArray(identity.tools) || identity.tools.length !== CAMPAIGN_TOOL_NAMES.length || !Array.isArray(identity.missing) || identity.missing.length) return false;
  const names = identity.tools.map(tool => tool?.name);
  if (new Set(names).size !== CAMPAIGN_TOOL_NAMES.length || CAMPAIGN_TOOL_NAMES.some(name => !names.includes(name))) return false;
  for (const tool of identity.tools) {
    if (tool.missing || tool.packageName !== tool.name || tool.matchesLock !== true || tool.version !== CAMPAIGN_TOOL_VERSIONS[tool.name] || tool.lockedVersion !== tool.version || !file(tool.package) || tool.package.path !== `node_modules/${tool.name}/package.json`) return false;
  }
  if (required.browsers.length) {
    const pins = identity.browserPins;
    if (!pins) return false;
    const { identity: manifestIdentity, ...manifest } = pins;
    if (!isDeepStrictEqual(manifestIdentity, CAMPAIGN_BROWSER_MANIFEST_IDENTITY) || !isDeepStrictEqual(manifest, CAMPAIGN_BROWSER_MANIFEST)) return false;
  }
  if (required.canonicalVitals) {
    const vitals = identity.canonicalVitals;
    if (!vitals || vitals.missing || vitals.name !== 'web-vitals' || vitals.version !== CAMPAIGN_VITALS_SOURCE.version || vitals.declaredVersion !== vitals.version || vitals.lockedVersion !== vitals.version || vitals.packageIntegrity !== CAMPAIGN_VITALS_SOURCE.integrity || vitals.sha256 !== CAMPAIGN_VITALS_SOURCE.sha256.slice(7) || vitals.bytes !== CAMPAIGN_VITALS_SOURCE.bytes || !file(vitals.package) || vitals.package.path !== 'node_modules/web-vitals/package.json' || !isDeepStrictEqual(vitals.bundle, { path: 'node_modules/web-vitals/dist/web-vitals.iife.js', bytes: CAMPAIGN_VITALS_SOURCE.bytes, sha256: CAMPAIGN_VITALS_SOURCE.sha256 })) return false;
  }
  return true;
}

/** Dist is an executable input independent of the source SHA. A current source
 * hash cannot certify a stale build, so retain both complete identities. */
export async function buildIdentity(repo) {
  const files = [], missing = [];
  async function walk(relative) {
    let entries;
    try { entries = await readdir(join(repo, relative), { withFileTypes: true }); }
    catch (error) { if (error.code === 'ENOENT') { missing.push(relative); return; } throw error; }
    for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
      const path = `${relative}/${entry.name}`;
      if (entry.isSymbolicLink()) throw Error('Executable build contains a symlink');
      if (entry.isDirectory()) await walk(path);
      else if (entry.isFile()) files.push({ path, ...await fileIdentity(join(repo, path)) });
    }
  }
  await walk('dist/local'); await walk('dist/app');
  return { digest: digest(files), files, missing };
}

export async function toolIdentity(repo) {
  const sealedLock = await readSealedJSON(join(repo, 'package-lock.json')), lock = sealedLock.value;
  const tools = [];
  for (const name of CAMPAIGN_TOOL_NAMES) {
    const relative = `node_modules/${name}/package.json`;
    try {
      const sealed = await readSealedJSON(join(repo, relative)), source = sealed.value;
      const expected = lock.packages?.[`node_modules/${name}`]?.version;
      tools.push({ name, packageName: source.name, version: source.version, lockedVersion: expected ?? null, matchesLock: expected === source.version, package: { path: relative, ...sealed.identity } });
    } catch (error) { tools.push({ name, missing: true, reason: error.code ?? 'unreadable' }); }
  }
  const node = { version: process.versions.node, executable: { path: process.execPath, ...await fileIdentity(process.execPath) } };
  let browserPins = null;
  try { const path = 'node_modules/playwright-core/browsers.json', sealed = await readSealedJSON(join(repo, path)); browserPins = { ...sealed.value, identity: { path, ...sealed.identity } }; } catch {}
  let canonicalVitals = null;
  try {
    const [{ library }, subject, pkg] = await Promise.all([loadCanonicalVitalsLibrary(repo), readSealedJSON(join(repo, 'package.json')), readSealedJSON(join(repo, 'node_modules/web-vitals/package.json'))]);
    canonicalVitals = { ...library, declaredVersion: subject.value.devDependencies?.['web-vitals'] ?? null, lockedVersion: lock.packages?.['node_modules/web-vitals']?.version ?? null,
      package: { path: 'node_modules/web-vitals/package.json', ...pkg.identity }, bundle: { path: 'node_modules/web-vitals/dist/web-vitals.iife.js', bytes: library.bytes, sha256: 'sha256:' + library.sha256 } };
  } catch (error) { canonicalVitals = { missing: true, reason: error.code ?? 'unreadable' }; }
  return { node, tools, browserPins, canonicalVitals, lock: sealedLock.identity, missing: tools.filter(tool => tool.missing || !tool.matchesLock || tool.packageName !== tool.name).map(tool => tool.name), browserExecutables: 'Each browser driver independently records actual executable version/hash; revision pins alone are not binary evidence.' };
}
