import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {join} from 'node:path';import {fixture,prepare,accept,enqueue,auth,envelope,encode,legacyAcknowledgement} from './helpers.mjs';import {childFor} from '../store/helpers.mjs';import {resolvePrivacy} from '../../dist/local/server/provider/policy.js';import {fixtureProfile} from '../provider/emulator.mjs';
const policy=resolvePrivacy(fixtureProfile(),'ideogram/v4','fixture').applied;
const remote=c=>({uiRead:(...p)=>c.call('uiRead',...p),uiPersist:(...p)=>c.call('uiPersist',...p)});
for(const [phase,accepted] of [['queue-accept-before-fact',false],['asset-after-commit',true]])test('killed acceptance at '+phase+' has an atomic receipt event job and outbox',async t=>{const f=await fixture(t);await prepare(f.writer);await f.close();const child=await childFor(t,f.root,{phase}),p=await accept(remote(child)),c=envelope(p.body),pending=child.call('queueCommand',encode(c),auth()).catch(e=>e);await child.wait('barrier');await child.kill();await pending;const w=await f.reopen(),record=await w.lookup(c.command.commandId),view=await w.queueView();assert.equal(!!record,accepted);assert.equal(view.jobs.length,accepted?1:0);const db=new DatabaseSync(join(f.root,'metadata.sqlite'),{readOnly:true});try{assert.equal(db.prepare('SELECT count(*) n FROM queue_outbox').get().n,accepted?1:0);assert.equal(db.prepare("SELECT count(*) n FROM events_v2 WHERE json_extract(json,'$.type')='JobQueued'").get().n,accepted?1:0);}finally{db.close();}if(accepted)assert.deepEqual(await w.queueCommand(encode(c),auth()),record.receipt);});
for(const [phase,uncertain] of [['queue-before-dispatch-fence',false],['queue-dispatch-before-commit',false],['queue-dispatch-after-commit',true]])test('killed dispatch at '+phase+' preserves conservative count and never retries',async t=>{const f=await fixture(t),p=await prepare(f.writer),q=await enqueue(f.writer,p.body);await f.close();const child=await childFor(t,f.root,{phase}),r=await child.call('queueReserve',q.job.id),pending=child.call('queueDispatch',q.job.id,r.attempt.id,{},policy).catch(e=>e);await child.wait('barrier');await child.assertNoEffects();await child.kill();await pending;const w=await f.reopen(),view=await w.queueView(),a=view.jobs[0].attempts[0];assert.equal(a.state,uncertain?'submission-uncertain':'not-started');assert.equal(a.count,uncertain?'dispatched':'reserved');assert.equal(view.counts.active,1);assert.equal(view.jobs[0].attempts.length,1);assert.equal(a.payloadHash!==null,uncertain);if(uncertain)assert.equal(await w.queueReserve(q.job.id),null);});
test('killed acknowledgment commit retains uncertainty and held charge count',async t=>{
 const f=await fixture(t),p=await prepare(f.writer),q=await enqueue(f.writer,p.body);await f.close();
 const child=await childFor(t,f.root,{phase:'queue-outcome-before-commit'}),r=await child.call('queueReserve',q.job.id),d=await child.call('queueDispatch',q.job.id,r.attempt.id,{},policy);
 const ack=legacyAcknowledgement(f.root,r.attempt.id,'request_1',{status:'http://127.0.0.1:1234/ideogram/v4/requests/request_1/status',result:'http://127.0.0.1:1234/ideogram/v4/requests/request_1',cancel:'http://127.0.0.1:1234/ideogram/v4/requests/request_1/cancel'},policy);
 const pending=child.call('queueOutcome',q.job.id,r.attempt.id,d.epoch,ack).catch(e=>e);await child.wait('barrier');await child.kill();await pending;
 const w=await f.reopen(),a=(await w.queueView()).jobs[0].attempts[0];assert.equal(a.state,'submission-uncertain');assert.equal(a.requestId,null);assert.equal(a.count,'dispatched');assert.equal(a.hold,true);
 const recovery=await w.queueRecovery(q.job.id,r.attempt.id);assert.equal(recovery.outbox.wireEvidence.submission,null);assert.equal(recovery.outbox.responseRecord,null);
});
