import {test as base,expect,type Page,type Request} from '@playwright/test';
import {mkdtemp,realpath,readFile,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {publicReadRequest} from '../request/persistence-witness.js';
// @ts-ignore Bounded original-consumer UI receipts; GET queue evidence is unchanged.
import {installE4DeliveryObserver,matchV45Deliveries} from '../recovery/e4-delivery-observer.mjs';
import {observeDisplayAborts,displayReadProofs,DISPLAY_OBSERVATION_LIMIT,DISPLAY_REQUEST_LIMIT} from '../editor/display-aborts.js';
// @ts-ignore Pure evidence classifier shared with the Node helper contract tests.
import {queueBodyObserverDisposition} from '../editor/composition-network.mjs';
import {serverProcess} from '../editor/process.js';import {ownedOPFS} from '../editor/owned-opfs.js';import {recordDOMErrors} from '../editor/error-monitor.js';import {runs,step,throwFailures,finishFixture,errorRecord,type RunState} from '../editor/harness-lifecycle.js';
// @ts-ignore The node fixture calls the real compiled sole writer; it does not submit network bytes.
import {openWriter} from '../../dist/local/server/storage/writer.js';
// @ts-ignore Test-owned policy is confined to durable no-network fixture transitions.
import {resolvePrivacy} from '../../dist/local/server/provider/policy.js';
// @ts-ignore Separate fixture entry point outside the production build.
import {fixtureProfile} from '../provider/emulator.mjs';
const receipt=process.env.EDITOR_RECEIPT??'artifacts/p23-browser';
const test=base.extend({context:async({playwright,browserName,contextOptions,viewport},use,testInfo)=>{const profile=browserName==='webkit'?await mkdtemp(join(await realpath(tmpdir()),'p23-webkit-')):undefined,browser=profile?undefined:await playwright[browserName].launch(),context=profile?await playwright.webkit.launchPersistentContext(profile,{...contextOptions,viewport}):await browser!.newContext({...contextOptions,viewport});await Promise.all(context.pages().map(p=>p.close()));try{await use(context);}finally{await finishFixture(context,browser,profile,receipt,'queue-',testInfo);}}});
const click=(page:Page,name:string)=>page.getByRole('button',{name,exact:true}).click();
async function number(page:Page,name:string,value:string){const f=page.getByRole('spinbutton',{name,exact:true});await f.fill(value);await f.press('Tab');}
test('public queue preserves exact review cap uncertainty and session history',async({page,context,browserName})=>{
 const guard=await ownedOPFS(context,'p23-public'),errors=await recordDOMErrors(context),csp:unknown[]=[],external:string[]=[],consoleErrors:string[]=[],commands:any[]=[],queueReads:any[]=[],fixtureTransitions:any[]=[],publicUI:any[]=[],restores:any[]=[],capEvents:any[]=[],runtime:any={},responseWork:Promise<void>[]=[];
 const dir=await mkdtemp(join(await realpath(tmpdir()),'p23-public-')),root=join(dir,'private');let server=await serverProcess(root),closed=false,fixtureWriterClosed=true;const origins=new Set([server.origin]);
 const state:RunState={failures:[],roots:[dir],writerClosed:false,contextClosed:false,browserClosed:false,retention:[],receipt,prefix:'queue-'};runs.set(context,state);
 const originalRequestIds=new WeakMap<Request,number>();let originalRequestSequence=0;const originalRequestId=(request:Request)=>{let id=originalRequestIds.get(request);if(id===undefined){id=++originalRequestSequence;originalRequestIds.set(request,id);}return id;};
 // Observe the original fetch signal and reader; never reconstruct a missing body.
 const originalReads=await observeDisplayAborts(context,originalRequestId);
 await page.addInitScript(installE4DeliveryObserver,{profile:'queue-ui' as const});
 const uiPosts:any[]=[],uiDeliveries:any[]=[],uiDeliveryErrors:unknown[]=[],uiDeliverySnapshots:any[]=[];let uiSealed=false;
 type ResponseEpoch={id:number;admitted:number;pending:number;completed:number;failed:number;outside:number;sealed:boolean;drained:boolean;drain?:Promise<void>};
 const responseEpochs:ResponseEpoch[]=[],responseFailures:{phase:string;error:unknown}[]=[],responseLimit=1024;let responseEpoch:ResponseEpoch,overflow=false,refusedResponses=0;
 type ResponseObservation={id:number;originalRequestId:number;epoch:number;method:string;origin:string;path:string;hasQuery:boolean;contentType:string|null;contentLength:string|null;startedAt:string;startedMs:number;headersMs:number|null;settledMs:number|null;status:number|null;stage:'response'|'json'|'retain'|'complete';body:'pending'|'complete'|'failed';failureIndex:number|null;errorName:string|null;terminal:'unknown'|'finished'|'failed';terminalMs:number|null;nativeFailure:string|null};
 const responseObservations:ResponseObservation[]=[],responseIdentity=new WeakMap<Request,ResponseObservation>();let metadataTruncated=0;
 const bounded=(value:string,limit:number)=>{if(value.length>limit)metadataTruncated++;return value.slice(0,limit);};
 function observeTerminal(request:Request,terminal:'finished'|'failed'){const row=responseIdentity.get(request);if(!row)return;row.terminal=terminal;row.terminalMs=performance.now();const failure=request.failure();row.nativeFailure=failure?bounded(failure.errorText,256):null;}
 const responseFinished=(request:Request)=>observeTerminal(request,'finished'),responseFailed=(request:Request)=>observeTerminal(request,'failed');
 const responseFailure=(error:unknown)=>responseFailures.push({phase:'response-observation',error});
 type ProofSnapshot={epoch:number;boundary:'body-drain'|'sealed';capturedAt:number;eventLimit:number;requestLimit:number;raw:ReturnType<typeof originalReads.observations>;proofs:ReturnType<typeof displayReadProofs>};
 const responseProofSnapshots:ProofSnapshot[]=[],responseDispositions=new Map<number,{snapshot:number;proof:unknown}>(),reportedResponseFailures=new Set<number>(),proofSnapshotLimit=16;
 function classifyResponseFailures(){const current=originalReads.observations();for(const [index,failure]of responseFailures.entries()){responseDispositions.delete(index);const row=responseObservations.find(r=>r.failureIndex===index);if(!row||overflow||metadataTruncated||!origins.has(row.origin))continue;for(let i=responseProofSnapshots.length-1;i>=0;i--){const snapshot=responseProofSnapshots[i];if(snapshot.epoch!==row.epoch)continue;const proof=queueBodyObserverDisposition(row,failure.error,row.origin,browserName,responseObservations,snapshot,current);if(proof){responseDispositions.set(index,{snapshot:i+1,proof});break;}}}}
 function throwResponseFailures(){classifyResponseFailures();const unresolved=responseFailures.filter((failure,index)=>{if(responseDispositions.has(index))return false;if(!reportedResponseFailures.has(index)){reportedResponseFailures.add(index);state.failures.push(failure);}return true;});throwFailures(unresolved);}
 async function captureResponseProof(boundary:'body-drain'|'sealed'){
  if(responseProofSnapshots.length>=proofSnapshotLimit)throw Error('QUEUE_ORIGINAL_PROOF_SNAPSHOT_LIMIT');
  let snapshot:ProofSnapshot|undefined;
  const sample=async()=>{
   for(const current of context.pages())await originalReads.flush(current);
   const capturedAt=performance.timeOrigin+performance.now(),raw=structuredClone(originalReads.observations()),proofs=displayReadProofs(raw.events,raw.requests,raw.errors);
   return snapshot={epoch:responseEpoch.id,boundary,capturedAt,eventLimit:DISPLAY_OBSERVATION_LIMIT,requestLimit:DISPLAY_REQUEST_LIMIT,raw,proofs};
  };
  try{
   if(browserName!=='chromium'||!responseFailures.some((_failure,index)=>!responseDispositions.has(index))){await sample();return;}
   await expect.poll(async()=>{
    const {raw,proofs}=await sample();
    if(raw.errors.length||raw.events.length>=DISPLAY_OBSERVATION_LIMIT||raw.requests.length>=DISPLAY_REQUEST_LIMIT)throw Error('QUEUE_ORIGINAL_PROOF_OBSERVATION_REFUSED');
    // A scheduled refresh can begin after body admission seals. Keep every raw
    // queue vertex and let its original read settle before freezing the proof.
    const queue=(row:{url:string;method:string})=>row.method==='GET'&&row.url===server.origin+'/api/v1/queue',key=(row:{frameId:number;document:string;operation:number})=>JSON.stringify([row.frameId,row.document,row.operation]);
    const requests=raw.requests.filter(queue),operations=new Set(raw.events.filter(queue).map(key)),resolved=proofs.filter(queue);
    return operations.size===requests.length&&resolved.length===requests.length&&new Set(requests.map(row=>row.requestId)).size===requests.length&&new Set(resolved.map(row=>row.requestId)).size===requests.length&&new Set(resolved.map(key)).size===operations.size&&resolved.every(row=>row.exactOccurrence===true&&operations.has(key(row))&&requests.some(request=>request.requestId===row.requestId));
   }).toBe(true);
  }finally{if(snapshot)responseProofSnapshots.push(snapshot);}
 }
 async function collectUIDeliveries(){
  const observed=await page.evaluate(()=>{const observer=(window as any).__p25DeliveryObserver,rows=(window as any).__p25Deliveries,errors=(window as any).__p25DeliveryErrors;if(!observer||!Array.isArray(rows)||!Array.isArray(errors))throw Error('QUEUE_UI_DELIVERY_OBSERVER_MISSING');return {rows:rows.splice(0),errors:errors.splice(0),snapshot:observer.snapshot()};});
  uiDeliveries.push(...observed.rows.map((row:any)=>({...row,epoch:responseEpoch.id})));uiDeliveryErrors.push(...observed.errors);expect(uiDeliveryErrors).toEqual([]);expect(observed.snapshot.disabled).toBe(false);expect(observed.snapshot.droppedErrors).toBe(0);
  return {joined:matchV45Deliveries(uiPosts,uiDeliveries),snapshot:observed.snapshot};
 }
 async function originalUIReceipt(post:any,response:any){
  let found:any;await expect.poll(async()=>{if(post.epoch!==responseEpoch.id||uiSealed)throw Error('QUEUE_UI_DELIVERY_EPOCH_CLOSED');const {joined}=await collectUIDeliveries();found=joined.find((entry:any)=>entry.post===post);return !!found;}).toBe(true);
  expect(found.delivery.status).toBe(response.status());expect(found.delivery.url).toBe(response.url());expect(found.delivery.origin).toBe(new URL(response.url()).origin);return found.delivery.value;
 }
 async function sealUIDeliveries(){
  if(uiSealed)return;
  await expect.poll(async()=>{const {joined,snapshot}=await collectUIDeliveries();return joined.length===uiPosts.length&&snapshot.pending===0;}).toBe(true);matchV45Deliveries(uiPosts,uiDeliveries,true);
  const snapshot=await page.evaluate(()=>{const observer=(window as any).__p25DeliveryObserver;if(observer.snapshot().pending||(window as any).__p25Deliveries.length||(window as any).__p25DeliveryErrors.length)throw Error('QUEUE_UI_DELIVERY_CHANGED_DURING_SEAL');observer.dispose();return observer.snapshot();});
  uiDeliverySnapshots.push({epoch:responseEpoch.id,...snapshot});for(const key of ['errors','droppedErrors','pending','ownedMethods','retainedBytes'])expect(snapshot[key]).toBe(0);expect(snapshot.disabled).toBe(false);uiSealed=true;
 }
 function openResponses(){uiSealed=false;if(responseEpoch&&!responseEpoch.drained)throw Error('QUEUE_OBSERVER_EPOCH_NOT_DRAINED');responseEpoch={id:responseEpochs.length+1,admitted:0,pending:0,completed:0,failed:0,outside:0,sealed:false,drained:false};responseEpochs.push(responseEpoch);}
 function observeResponse(request:Request){
  const method=request.method(),path=new URL(request.url()).pathname,ui=method==='POST'&&path.startsWith('/api/v1/ui/'),queue=method==='GET'&&request.url().includes('/api/v1/queue');if(!ui&&!queue)return;
  const epoch=responseEpoch;if(epoch.sealed){epoch.outside++;if(ui)responseFailure(Error('QUEUE_UI_POST_AFTER_SEAL'));return;}
  if(responseWork.length>=responseLimit){refusedResponses++;if(!overflow){overflow=true;responseFailure(Error('QUEUE_RESPONSE_OBSERVATION_LIMIT'));}return;}
  epoch.admitted++;epoch.pending++;
  const uiPost=ui?{epoch:epoch.id,path,request:JSON.parse(request.postData()!)}:undefined;if(uiPost)uiPosts.push(uiPost);
  const url=new URL(request.url()),row:ResponseObservation={id:responseObservations.length+1,originalRequestId:originalRequestId(request),epoch:epoch.id,method,origin:bounded(url.origin,256),path:bounded(path,1024),hasQuery:!!url.search,contentType:null,contentLength:null,startedAt:new Date().toISOString(),startedMs:performance.now(),headersMs:null,settledMs:null,status:null,stage:'response',body:'pending',failureIndex:null,errorName:null,terminal:'unknown',terminalMs:null,nativeFailure:null};responseObservations.push(row);responseIdentity.set(request,row);
  // Admit at request start: sealing still owns responses whose headers arrive later.
  const work=Promise.resolve().then(async()=>{const response=await request.response();if(!response)throw Error('QUEUE_OBSERVED_REQUEST_FAILED: '+method+' '+path);row.status=response.status();row.headersMs=performance.now();const headers=response.headers();row.contentType=headers['content-type']===undefined?null:bounded(headers['content-type'],128);row.contentLength=headers['content-length']===undefined?null:bounded(headers['content-length'],32);row.stage='json';const value=ui?await originalUIReceipt(uiPost,response):await response.json();row.stage='retain';if(ui)publicUI.push({request:uiPost!.request,result:value});else queueReads.push(value);row.body='complete';row.stage='complete';epoch.completed++;}).catch(error=>{row.body='failed';row.failureIndex=responseFailures.length;row.errorName=bounded(error instanceof Error?error.name:typeof error,64);epoch.failed++;responseFailure(error);}).finally(()=>{row.settledMs=performance.now();epoch.pending--;});responseWork.push(work);
 }
 async function flushResponses(){await Promise.all(responseWork);if(responseFailures.some((_failure,index)=>!responseDispositions.has(index)))await captureResponseProof('body-drain');throwResponseFailures();}
 function sealResponses(){const epoch=responseEpoch;epoch.sealed=true;return epoch.drain??=(async()=>{await expect.poll(()=>epoch.pending).toBe(0);await sealUIDeliveries();epoch.drained=true;await captureResponseProof('sealed');throwResponseFailures();})();}
 openResponses();
 state.observe=()=>({uiDeliveryObservation:{scope:'original-consumer-parse-return; not model adoption or paint',posts:uiPosts,deliveries:uiDeliveries,errors:uiDeliveryErrors,snapshots:uiDeliverySnapshots,sealed:uiSealed},originalReads:{proofs:originalReads(),...originalReads.observations()},responseObserver:{uiBodyEvidence:'original-consumer-parse-return',queueGETBodyEvidence:'unchanged native inspector body with exact original-reader disposition',limit:responseLimit,overflow,refused:refusedResponses,metadataTruncated,observations:responseObservations,failures:responseFailures.map((failure,index)=>({...failure,error:errorRecord(failure.error),disposition:responseDispositions.get(index)??null})),proofSnapshotLimit,proofSnapshots:responseProofSnapshots,epochs:responseEpochs.map(({drain,...epoch})=>epoch)},errors,csp,external,consoleErrors,commands,queueReads,fixtureTransitions,publicUI,restores,capEvents,runtime,requestLifecycle:guard.requests,cleanup:guard.ledger});
 // Keep native terminal evidence through context closure; body settlement is not native completion.
 state.finalCheck=async()=>{try{await step(state,'response-observer-final',async()=>{await expect.poll(()=>responseEpochs.reduce((sum,epoch)=>sum+epoch.pending,0)).toBe(0);expect(uiSealed).toBe(true);matchV45Deliveries(uiPosts,uiDeliveries,true);expect(uiDeliveryErrors).toEqual([]);throwResponseFailures();});guard.verify();expect(guard.ledger.filter(e=>e.phase==='refused')).toEqual([]);expect(errors).toEqual([]);expect(csp).toEqual([]);expect(external).toEqual([]);expect(consoleErrors).toEqual([]);expect(originalReads.observations().errors).toEqual([]);}finally{page.off('requestfinished',responseFinished);page.off('requestfailed',responseFailed);}};
 await context.exposeBinding('queueCapObservation',(_source,value)=>capEvents.push(value));await context.addInitScript(()=>{for(const type of ['en-input','en-change'])document.addEventListener(type,event=>{const host=event.composedPath()[0] as HTMLElement&{value:string};if(host?.id!=='request-cap')return;const record=()=>({type,detail:(event as CustomEvent).detail,value:host.value,defaultPrevented:event.defaultPrevented});void (window as any).queueCapObservation({phase:'dispatch',...record()});setTimeout(()=>void (window as any).queueCapObservation({phase:'settled',...record()}),0);},true);});
 await context.exposeBinding('queueCSP',(_source,value)=>csp.push(value));await context.addInitScript(()=>addEventListener('securitypolicyviolation',e=>(window as any).queueCSP({directive:e.effectiveDirective,blocked:e.blockedURI})));
 page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/api/v1/commands'))commands.push(JSON.parse(r.postData()!).command);});page.on('request',observeResponse);page.on('requestfinished',responseFinished);page.on('requestfailed',responseFailed);
 await context.route('**/*',route=>{const u=new URL(route.request().url());if(['http:','https:'].includes(u.protocol)&&!origins.has(u.origin)){external.push(u.origin);return route.abort();}return route.continue();});
 let original:{sessionId:string;documentId:string;draftId:string;generation:string;assetId:string;checkpoint:any;review:any}|undefined;
 async function publicRead(path:string,text=false){const spec=publicReadRequest(path);return page.evaluate(async({spec,text})=>{const r=await fetch(spec.path,spec.init);if(!r.ok)throw Error('Public read failed: '+r.status);return text?await r.text():await r.json();},{spec,text});}
 async function retainedOriginal(){await flushResponses();const queued=commands.filter(c=>c.body.type==='QueueInference');expect(queued).toHaveLength(2);expect(new Set(queued.map(c=>c.sessionId)).size).toBe(1);const jobs=queueReads.at(-1).jobs;expect(jobs).toHaveLength(2);const review=jobs[0].review;expect(jobs[1].review).toEqual(review);expect(review.draft.sessionId).toBe(queued[0].sessionId);const accepted=publicUI.filter(x=>x.result.requestId===queued[0].body.acceptanceId);expect(accepted).toHaveLength(1);expect(accepted[0].result.status).toBe('accepted');expect(accepted[0].result.acceptedReview).toBe(review.id);expect(accepted[0].result.review).toEqual(review);const checkpoint=await publicRead('/api/v1/ui/'+review.draft.sessionId);expect(checkpoint.uiSeq).toBe(accepted[0].result.uiSeq);expect(checkpoint.preferences.documentId).toBe(review.documentId);const drafts=checkpoint.drafts.filter((d:any)=>d.id===review.draft.draftId);expect(drafts).toHaveLength(1);expect(drafts[0]).toMatchObject({generation:review.draft.generation,documentId:review.documentId,expectedDocumentRevision:review.documentRevision,assetId:review.draftAsset,kind:'request',status:'saved-unapplied',composing:false});original={sessionId:review.draft.sessionId,documentId:review.documentId,draftId:review.draft.draftId,generation:review.draft.generation,assetId:review.draftAsset,checkpoint,review};await verifyRetained();}
 async function verifyRetained(){const o=original!;const checkpoint=await publicRead('/api/v1/ui/'+o.sessionId);expect(checkpoint).toEqual(o.checkpoint);const path='/api/v1/ui/'+o.sessionId+'/request?draftId='+o.draftId+'&generation='+o.generation,value=await publicRead(path),content=await publicRead(path+'&content=1',true);expect(content).toBe('Queue public Café 東京');expect(value.value.prompt.text).toEqual(o.review.prompt);return {checkpoint,value,content};}
 async function restart(transition:(writer:any)=>Promise<void>){expect(original).toBeDefined();await sealResponses();await page.goto('about:blank');await server.close();closed=true;const w=await openWriter({root});fixtureWriterClosed=false;try{await transition(w);}finally{await w.close();fixtureWriterClosed=true;}server=await serverProcess(root);closed=false;origins.add(server.origin);await guard.admit(page,server.origin);openResponses();await page.goto(await server.pair());await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();const o=original!,retained=await verifyRetained();await click(page,'Open');const choice=page.getByRole('button',{name:'Restore '+o.sessionId+' · document '+o.documentId+' · sequence '+o.checkpoint.uiSeq,exact:true});await expect(choice).toHaveCount(1);await choice.click();await expect(page.getByRole('dialog',{name:'Open document',exact:true})).toBeHidden();await expect(page.locator('footer')).toContainText('Restored UI checkpoint. Drafts remain unapplied.');await expect(page.getByRole('textbox',{name:'Prompt',exact:true})).toHaveValue('Queue public Café 東京');restores.push({origin:server.origin,sessionId:o.sessionId,documentId:o.documentId,draftId:o.draftId,generation:o.generation,retained,panelClosed:true,prompt:'Queue public Café 東京'});await click(page,'Refresh durable queue');}

 try{
  await mkdir(receipt,{recursive:true});await guard.admit(page,server.origin);await page.goto(await server.pair());Object.assign(runtime,{version:context.browser()?.version()??null,userAgent:await page.evaluate(()=>navigator.userAgent),pin:JSON.parse(await readFile('node_modules/playwright-core/browsers.json','utf8')).browsers.find((b:any)=>b.name===browserName)});await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await click(page,'New');await number(page,'Width (px)','1024');await number(page,'Height (px)','1024');await click(page,'Create');await expect(page.getByRole('dialog',{name:'New document',exact:true})).toBeHidden();
  const prompt=page.getByRole('textbox',{name:'Prompt',exact:true});await prompt.fill('Queue public Café 東京');await click(page,'Refresh durable queue');const panel=page.locator('#durable-queue');await expect(panel).toContainText('Request cap: Off');await number(page,'Paid-request cap','0');await click(page,'Set request cap');await expect(page.locator('#request-errors')).toContainText('positive whole');await expect(page.locator('#request-errors')).toBeFocused();await page.locator('#request-errors').getByRole('link').click();await expect(page.getByRole('spinbutton',{name:'Paid-request cap',exact:true})).toBeFocused();await number(page,'Paid-request cap','1');const capField=page.locator('#request-cap');await expect.poll(()=>capField.evaluate((el:any)=>el.value)).toBe('1');await expect.poll(()=>capEvents.some(e=>e.type==='en-change'&&e.phase==='settled'&&!e.defaultPrevented&&e.value==='1')).toBe(true);await click(page,'Set request cap');await expect(panel).toContainText('Request cap: 1');await capField.getByRole('button',{name:'Increase value',exact:true}).click();await expect.poll(()=>capField.evaluate((el:any)=>el.value)).toBe('2');await click(page,'Set request cap');await expect(panel).toContainText('Request cap: 2');await capField.getByRole('button',{name:'Decrease value',exact:true}).click();await expect.poll(()=>capField.evaluate((el:any)=>el.value)).toBe('1');await click(page,'Set request cap');await expect(panel).toContainText('Request cap: 1');expect(commands.filter(c=>c.body.type==='SetSpendGuard').map(c=>c.body.cap)).toEqual([1,2,1]);
  await click(page,'Review exact request');await expect(page.locator('#request-review')).toBeFocused();await click(page,'Accept this exact review locally');await expect(page.getByRole('button',{name:'Enqueue accepted request',exact:true})).toBeEnabled();expect(commands.filter(c=>c.body.type==='QueueInference')).toHaveLength(0);
  await page.locator('#enqueue-request').evaluate(el=>el.addEventListener('click',e=>e.preventDefault(),{once:true}));await click(page,'Enqueue accepted request');await click(page,'Refresh durable queue');await flushResponses();expect(commands.filter(c=>c.body.type==='QueueInference')).toHaveLength(0);
  const enqueue=page.getByRole('button',{name:'Enqueue accepted request',exact:true});await enqueue.focus();await enqueue.press('Enter');await expect(panel).toContainText('accepted-local-queue');await expect(enqueue).toBeEnabled();await enqueue.click();await expect.poll(()=>commands.filter(c=>c.body.type==='QueueInference').length).toBe(2);await expect.poll(()=>queueReads.at(-1)?.jobs.length).toBe(2);await flushResponses();
  await retainedOriginal();await restart(async w=>{const v=await w.queueView(),j=v.jobs[0],r=await w.queueReserve(j.id),d=await w.queueDispatch(j.id,r.attempt.id,{},resolvePrivacy(fixtureProfile(),'ideogram/v4',r.attempt.id).applied);fixtureTransitions.push({kind:'durable-fence-without-network-bytes',jobId:j.id,attemptId:r.attempt.id,payloadHash:d.payloadHash});});
  await expect(panel).toContainText('submission-uncertain');await expect(panel).toContainText('Total and actual spend are unknown.');await expect(panel).toContainText('Active holds 1 of one');const peer=await context.newPage();await peer.goto(server.origin);await expect(peer.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await click(peer,'Refresh durable queue');await expect(peer.locator('#durable-queue')).toContainText('Active holds 1 of one');await expect(peer.locator('#durable-queue')).toContainText('submission-uncertain');await peer.close();await click(page,'Review possible overlapping work');await expect(page.locator('#queue-risk')).toBeFocused();await expect(page.locator('#queue-risk')).toContainText('may still be running');await click(page,'Acknowledge risk and release this local hold');await expect(panel).toContainText('Active holds 0 of one');
  await restart(async w=>{const v=await w.queueView(),j=v.jobs.find((j:any)=>j.attempts[0].state==='not-started');expect(await w.queueReserve(j.id)).toBeNull();fixtureTransitions.push({kind:'cap-reservation-refused',jobId:j.id});});await expect(panel).toContainText('Paused at request cap');await expect(panel).toContainText('submission-uncertain');
  await click(page,'Review new work session');await expect(page.locator('#spend-review')).toBeFocused();await expect(page.locator('#spend-review')).toContainText('Old counts and uncertain charges remain');await click(page,'Acknowledge unresolved charges and start session');await expect(panel).toContainText('remaining 1');await expect(panel).toContainText('submission-uncertain');await expect(panel).not.toContainText('Paused at request cap');await click(page,'Disable request cap');await expect(panel).toContainText('Request cap: Off');
  await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await page.setViewportSize({width:320,height:900});await page.getByRole('link',{name:'Go to Request',exact:true}).press('Enter');const geometry=await panel.evaluate(el=>({width:el.getBoundingClientRect().width,scroll:el.scrollWidth}));expect(geometry.scroll).toBeLessThanOrEqual(geometry.width+1);await panel.getByRole('button',{name:'Refresh durable queue',exact:true}).focus();await expect(panel.getByRole('button',{name:'Refresh durable queue',exact:true})).toBeFocused();
  if(browserName!=='webkit')await page.screenshot({path:join(receipt,'queue-viewport.png'),caret:'initial'});expect(Object.values(await server.effects() as object).every(n=>n===0)).toBe(true);
 }catch(error){state.failures.push({phase:'body',error});}finally{
  await step(state,'response-observations',sealResponses);page.off('request',observeResponse);if(!state.failures.length)await step(state,'logical-cleanup',async()=>{for(const p of context.pages())await p.goto('about:blank');await guard.cleanup();guard.verify();});
  if(!closed)state.writerClosed=await step(state,'writer-close',()=>server.close());else state.writerClosed=fixtureWriterClosed;throwFailures(state.failures);
 }
});
