import {test as base,expect,type Page} from '@playwright/test';
import {mkdtemp,realpath,readFile,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {publicReadRequest} from '../request/persistence-witness.js';
import {serverProcess} from '../editor/process.js';import {ownedOPFS} from '../editor/owned-opfs.js';import {recordDOMErrors} from '../editor/error-monitor.js';import {runs,step,throwFailures,finishFixture,type RunState} from '../editor/harness-lifecycle.js';
// @ts-ignore The node fixture calls the real compiled sole writer; it does not submit network bytes.
import {openWriter} from '../../dist/local/server/storage/writer.js';
// @ts-ignore Test-owned policy is confined to durable no-network fixture transitions.
import {resolvePrivacy} from '../../dist/local/server/provider/policy.js';
// @ts-ignore Separate fixture entry point outside the production build.
import {fixtureProfile} from '../provider/emulator.mjs';
const receipt=process.env.EDITOR_RECEIPT??'artifacts/p23-browser';
const test=base.extend({context:async({playwright,browserName,contextOptions,viewport},use,testInfo)=>{const profile=browserName==='webkit'?await mkdtemp(join(await realpath(tmpdir()),'p23-webkit-')):undefined,browser=profile?undefined:await playwright[browserName].launch(),context=profile?await playwright.webkit.launchPersistentContext(profile,{...contextOptions,viewport}):await browser!.newContext({...contextOptions,viewport});await Promise.all(context.pages().map(p=>p.close()));try{await use(context);}finally{await finishFixture(context,browser,profile,receipt,'queue-',testInfo);}}});
const click=(page:Page,name:string)=>page.getByRole('button',{name,exact:true}).click();
async function number(page:Page,name:string,value:string){const f=page.getByRole('spinbutton',{name,exact:true});await f.fill(value);await f.press('Tab');}
test('public queue preserves exact review cap uncertainty and session history',async({page,context,browserName})=>{
 const guard=await ownedOPFS(context,'p23-public'),errors=await recordDOMErrors(context),csp:unknown[]=[],external:string[]=[],consoleErrors:string[]=[],commands:any[]=[],queueReads:any[]=[],fixtureTransitions:any[]=[],publicUI:any[]=[],restores:any[]=[],capEvents:any[]=[],runtime:any={},responseWork:Promise<void>[]=[];
 const dir=await mkdtemp(join(await realpath(tmpdir()),'p23-public-')),root=join(dir,'private');let server=await serverProcess(root),closed=false,fixtureWriterClosed=true;const origins=new Set([server.origin]);
 const state:RunState={failures:[],roots:[dir],writerClosed:false,contextClosed:false,browserClosed:false,retention:[],receipt,prefix:'queue-'};runs.set(context,state);
 state.observe=()=>({errors,csp,external,consoleErrors,commands,queueReads,fixtureTransitions,publicUI,restores,capEvents,runtime,requestLifecycle:guard.requests,cleanup:guard.ledger});
 state.finalCheck=async()=>{guard.verify();expect(guard.ledger.filter(e=>e.phase==='refused')).toEqual([]);expect(errors).toEqual([]);expect(csp).toEqual([]);expect(external).toEqual([]);expect(consoleErrors).toEqual([]);};
 await context.exposeBinding('queueCapObservation',(_source,value)=>capEvents.push(value));await context.addInitScript(()=>{for(const type of ['en-input','en-change'])document.addEventListener(type,event=>{const host=event.composedPath()[0] as HTMLElement&{value:string};if(host?.id!=='request-cap')return;const record=()=>({type,detail:(event as CustomEvent).detail,value:host.value,defaultPrevented:event.defaultPrevented});void (window as any).queueCapObservation({phase:'dispatch',...record()});setTimeout(()=>void (window as any).queueCapObservation({phase:'settled',...record()}),0);},true);});
 await context.exposeBinding('queueCSP',(_source,value)=>csp.push(value));await context.addInitScript(()=>addEventListener('securitypolicyviolation',e=>(window as any).queueCSP({directive:e.effectiveDirective,blocked:e.blockedURI})));
 page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/api/v1/commands'))commands.push(JSON.parse(r.postData()!).command);});page.on('response',r=>{if(r.request().method()==='POST'&&new URL(r.url()).pathname.startsWith('/api/v1/ui/'))responseWork.push(r.json().then(result=>{publicUI.push({request:JSON.parse(r.request().postData()!),result});}));if(r.request().method()==='GET'&&r.url().includes('/api/v1/queue'))responseWork.push(r.json().then(v=>{queueReads.push(v);}));});
 await context.route('**/*',route=>{const u=new URL(route.request().url());if(['http:','https:'].includes(u.protocol)&&!origins.has(u.origin)){external.push(u.origin);return route.abort();}return route.continue();});
 let original:{sessionId:string;documentId:string;draftId:string;generation:string;assetId:string;checkpoint:any;review:any}|undefined;
 async function publicRead(path:string,text=false){const spec=publicReadRequest(path);return page.evaluate(async({spec,text})=>{const r=await fetch(spec.path,spec.init);if(!r.ok)throw Error('Public read failed: '+r.status);return text?await r.text():await r.json();},{spec,text});}
 async function retainedOriginal(){await Promise.all(responseWork);const queued=commands.filter(c=>c.body.type==='QueueInference');expect(queued).toHaveLength(2);expect(new Set(queued.map(c=>c.sessionId)).size).toBe(1);const jobs=queueReads.at(-1).jobs;expect(jobs).toHaveLength(2);const review=jobs[0].review;expect(jobs[1].review).toEqual(review);expect(review.draft.sessionId).toBe(queued[0].sessionId);const accepted=publicUI.filter(x=>x.result.requestId===queued[0].body.acceptanceId);expect(accepted).toHaveLength(1);expect(accepted[0].result.status).toBe('accepted');expect(accepted[0].result.acceptedReview).toBe(review.id);expect(accepted[0].result.review).toEqual(review);const checkpoint=await publicRead('/api/v1/ui/'+review.draft.sessionId);expect(checkpoint.uiSeq).toBe(accepted[0].result.uiSeq);expect(checkpoint.preferences.documentId).toBe(review.documentId);const drafts=checkpoint.drafts.filter((d:any)=>d.id===review.draft.draftId);expect(drafts).toHaveLength(1);expect(drafts[0]).toMatchObject({generation:review.draft.generation,documentId:review.documentId,expectedDocumentRevision:review.documentRevision,assetId:review.draftAsset,kind:'request',status:'saved-unapplied',composing:false});original={sessionId:review.draft.sessionId,documentId:review.documentId,draftId:review.draft.draftId,generation:review.draft.generation,assetId:review.draftAsset,checkpoint,review};await verifyRetained();}
 async function verifyRetained(){const o=original!;const checkpoint=await publicRead('/api/v1/ui/'+o.sessionId);expect(checkpoint).toEqual(o.checkpoint);const path='/api/v1/ui/'+o.sessionId+'/request?draftId='+o.draftId+'&generation='+o.generation,value=await publicRead(path),content=await publicRead(path+'&content=1',true);expect(content).toBe('Queue public Café 東京');expect(value.value.prompt.text).toEqual(o.review.prompt);return {checkpoint,value,content};}
 async function restart(transition:(writer:any)=>Promise<void>){expect(original).toBeDefined();await page.goto('about:blank');await server.close();closed=true;const w=await openWriter({root});fixtureWriterClosed=false;try{await transition(w);}finally{await w.close();fixtureWriterClosed=true;}server=await serverProcess(root);closed=false;origins.add(server.origin);await guard.admit(page,server.origin);await page.goto(await server.pair());await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();const o=original!,retained=await verifyRetained();await click(page,'Open');const choice=page.getByRole('button',{name:'Restore '+o.sessionId+' · document '+o.documentId+' · sequence '+o.checkpoint.uiSeq,exact:true});await expect(choice).toHaveCount(1);await choice.click();await expect(page.getByRole('dialog',{name:'Open document',exact:true})).toBeHidden();await expect(page.locator('footer')).toContainText('Restored UI checkpoint. Drafts remain unapplied.');await expect(page.getByRole('textbox',{name:'Prompt',exact:true})).toHaveValue('Queue public Café 東京');restores.push({origin:server.origin,sessionId:o.sessionId,documentId:o.documentId,draftId:o.draftId,generation:o.generation,retained,panelClosed:true,prompt:'Queue public Café 東京'});await click(page,'Refresh durable queue');}

 try{
  await mkdir(receipt,{recursive:true});await guard.admit(page,server.origin);await page.goto(await server.pair());Object.assign(runtime,{version:context.browser()?.version()??null,userAgent:await page.evaluate(()=>navigator.userAgent),pin:JSON.parse(await readFile('node_modules/playwright-core/browsers.json','utf8')).browsers.find((b:any)=>b.name===browserName)});await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await click(page,'New');await number(page,'Width (px)','1024');await number(page,'Height (px)','1024');await click(page,'Create');await expect(page.getByRole('dialog',{name:'New document',exact:true})).toBeHidden();
  const prompt=page.getByRole('textbox',{name:'Prompt',exact:true});await prompt.fill('Queue public Café 東京');await click(page,'Refresh durable queue');const panel=page.locator('#durable-queue');await expect(panel).toContainText('Request cap: Off');await number(page,'Paid-request cap','0');await click(page,'Set request cap');await expect(page.locator('#request-errors')).toContainText('positive whole');await expect(page.locator('#request-errors')).toBeFocused();await page.locator('#request-errors').getByRole('link').click();await expect(page.getByRole('spinbutton',{name:'Paid-request cap',exact:true})).toBeFocused();await number(page,'Paid-request cap','1');const capField=page.locator('#request-cap');await expect.poll(()=>capField.evaluate((el:any)=>el.value)).toBe('1');await expect.poll(()=>capEvents.some(e=>e.type==='en-change'&&e.phase==='settled'&&!e.defaultPrevented&&e.value==='1')).toBe(true);await click(page,'Set request cap');await expect(panel).toContainText('Request cap: 1');await capField.getByRole('button',{name:'Increase value',exact:true}).click();await expect.poll(()=>capField.evaluate((el:any)=>el.value)).toBe('2');await click(page,'Set request cap');await expect(panel).toContainText('Request cap: 2');await capField.getByRole('button',{name:'Decrease value',exact:true}).click();await expect.poll(()=>capField.evaluate((el:any)=>el.value)).toBe('1');await click(page,'Set request cap');await expect(panel).toContainText('Request cap: 1');expect(commands.filter(c=>c.body.type==='SetSpendGuard').map(c=>c.body.cap)).toEqual([1,2,1]);
  await click(page,'Review exact request');await expect(page.locator('#request-review')).toBeFocused();await click(page,'Accept this exact review locally');await expect(page.getByRole('button',{name:'Enqueue accepted request',exact:true})).toBeEnabled();expect(commands.filter(c=>c.body.type==='QueueInference')).toHaveLength(0);
  await page.locator('#enqueue-request').evaluate(el=>el.addEventListener('click',e=>e.preventDefault(),{once:true}));await click(page,'Enqueue accepted request');await click(page,'Refresh durable queue');await Promise.all(responseWork);expect(commands.filter(c=>c.body.type==='QueueInference')).toHaveLength(0);
  const enqueue=page.getByRole('button',{name:'Enqueue accepted request',exact:true});await enqueue.focus();await enqueue.press('Enter');await expect(panel).toContainText('accepted-local-queue');await expect(enqueue).toBeEnabled();await enqueue.click();await expect.poll(()=>commands.filter(c=>c.body.type==='QueueInference').length).toBe(2);await expect.poll(async()=>{await Promise.all(responseWork);return queueReads.at(-1)?.jobs.length;}).toBe(2);
  await retainedOriginal();await restart(async w=>{const v=await w.queueView(),j=v.jobs[0],r=await w.queueReserve(j.id),d=await w.queueDispatch(j.id,r.attempt.id,{},resolvePrivacy(fixtureProfile(),'ideogram/v4',r.attempt.id).applied);fixtureTransitions.push({kind:'durable-fence-without-network-bytes',jobId:j.id,attemptId:r.attempt.id,payloadHash:d.payloadHash});});
  await expect(panel).toContainText('submission-uncertain');await expect(panel).toContainText('Total and actual spend are unknown.');await expect(panel).toContainText('Active holds 1 of one');const peer=await context.newPage();await peer.goto(server.origin);await expect(peer.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await click(peer,'Refresh durable queue');await expect(peer.locator('#durable-queue')).toContainText('Active holds 1 of one');await expect(peer.locator('#durable-queue')).toContainText('submission-uncertain');await peer.close();await click(page,'Review possible overlapping work');await expect(page.locator('#queue-risk')).toBeFocused();await expect(page.locator('#queue-risk')).toContainText('may still be running');await click(page,'Acknowledge risk and release this local hold');await expect(panel).toContainText('Active holds 0 of one');
  await restart(async w=>{const v=await w.queueView(),j=v.jobs.find((j:any)=>j.attempts[0].state==='not-started');expect(await w.queueReserve(j.id)).toBeNull();fixtureTransitions.push({kind:'cap-reservation-refused',jobId:j.id});});await expect(panel).toContainText('Paused at request cap');await expect(panel).toContainText('submission-uncertain');
  await click(page,'Review new work session');await expect(page.locator('#spend-review')).toBeFocused();await expect(page.locator('#spend-review')).toContainText('Old counts and uncertain charges remain');await click(page,'Acknowledge unresolved charges and start session');await expect(panel).toContainText('remaining 1');await expect(panel).toContainText('submission-uncertain');await expect(panel).not.toContainText('Paused at request cap');await click(page,'Disable request cap');await expect(panel).toContainText('Request cap: Off');
  await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await page.setViewportSize({width:320,height:900});await page.getByRole('link',{name:'Go to Request',exact:true}).press('Enter');const geometry=await panel.evaluate(el=>({width:el.getBoundingClientRect().width,scroll:el.scrollWidth}));expect(geometry.scroll).toBeLessThanOrEqual(geometry.width+1);await panel.getByRole('button',{name:'Refresh durable queue',exact:true}).focus();await expect(panel.getByRole('button',{name:'Refresh durable queue',exact:true})).toBeFocused();
  if(browserName!=='webkit')await page.screenshot({path:join(receipt,'queue-viewport.png'),caret:'initial'});expect(Object.values(await server.effects() as object).every(n=>n===0)).toBe(true);
 }catch(error){state.failures.push({phase:'body',error});}finally{
  await step(state,'response-observations',()=>Promise.all(responseWork));if(!state.failures.length)await step(state,'logical-cleanup',async()=>{for(const p of context.pages())await p.goto('about:blank');await guard.cleanup();guard.verify();});
  if(!closed)state.writerClosed=await step(state,'writer-close',()=>server.close());else state.writerClosed=fixtureWriterClosed;throwFailures(state.failures);
 }
});
