import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {fixture,prepare,enqueue,ui,auth,envelope,encode,command,EMPTY_EXPECTED_VERSIONS} from './helpers.mjs';

test('a changed document requires explicit replacement metadata refresh before a fresh review can be accepted and queued',async t=>{
 const f=await fixture(t),prepared=await prepare(f.writer),{job}=await enqueue(f.writer,prepared.body),frozen=structuredClone(job.review);
 const db=new DatabaseSync(join(f.root,'metadata.sqlite'),{readOnly:true});let authored;try{authored=JSON.parse(db.prepare('SELECT json FROM assets WHERE id=?').get(frozen.draftAsset).json).blob;}finally{db.close();}const path=join(f.root,'objects/sha256',authored.hash.slice(7,9),authored.hash.slice(7)),bytes=await readFile(path);
 assert.equal((await f.writer.submit(encode(command(EMPTY_EXPECTED_VERSIONS,{expectedDocumentRevision:frozen.documentRevision,body:{type:'SaveCheckpoint',name:'Document changed after the queued review'}})),f.writer.epoch)).status,'accepted');const revision=await f.writer.documentRevision(job.documentId);assert.notEqual(revision,frozen.documentRevision);
 const before=await f.writer.uiRead('request_session',auth()),request=envelope({type:'EditQueuedJob',jobId:job.id,expectedVersion:job.version,sessionId:before.sessionId,expectedUISeq:before.uiSeq,replacementDraftId:'replacement_after_document_change'});assert.equal((await f.writer.queueCommand(encode(request),auth())).status,'accepted');const state=await f.writer.uiRead(before.sessionId,auth()),replacement=state.drafts.find(draft=>draft.id==='replacement_after_document_change');assert(replacement);assert.equal(replacement.expectedDocumentRevision,frozen.documentRevision);assert.equal(replacement.assetId,frozen.draftAsset);assert.equal(replacement.generation,'1');assert.deepEqual(await readFile(path),bytes);
 const stale=await ui(f.writer,{type:'PrepareRequestReview',draftId:replacement.id,generation:'1'});assert.equal(stale.status,'rejected');assert.match(stale.reason,/STALE_REVISION/);const priorApproval=await ui(f.writer,{type:'AcceptRequestReview',reviewId:frozen.id,token:frozen.token});assert.equal(priorApproval.status,'rejected');assert.equal((await f.writer.queueCommand(encode(envelope(prepared.body)),auth())).status,'rejected');assert.equal((await f.writer.queueView()).totalJobs,1);
 // This is the explicit metadata save performed by Review current request
 // document. The authored request asset is retained exactly; it gains no approval.
 const saved=await ui(f.writer,{type:'SaveDraft',draft:{id:replacement.id,generation:'2',kind:'request',documentId:replacement.documentId,targetLayerId:null,expectedDocumentRevision:revision,assetId:replacement.assetId,composing:false}});assert.equal(saved.status,'accepted');const reviewed=await ui(f.writer,{type:'PrepareRequestReview',draftId:replacement.id,generation:'2'});assert.equal(reviewed.status,'accepted');assert.equal(reviewed.review.documentRevision,revision);assert.equal(reviewed.review.draft.draftId,replacement.id);assert.equal(reviewed.review.draft.generation,'2');assert.notEqual(reviewed.review.token,frozen.token);assert.deepEqual(reviewed.review.request,frozen.request);assert.deepEqual(reviewed.review.prompt,frozen.prompt);
 const acceptance=await ui(f.writer,{type:'AcceptRequestReview',reviewId:reviewed.review.id,token:reviewed.review.token});assert.equal(acceptance.status,'accepted');const next=await enqueue(f.writer,{type:'QueueInference',reviewId:reviewed.review.id,token:reviewed.review.token,acceptanceId:acceptance.requestId});assert.notEqual(next.job.id,job.id);assert.equal(next.job.attempts.length,1);assert.equal(next.job.attempts[0].state,'not-started');assert.equal(next.job.attempts[0].providerAuthorization,undefined);
 const final=await f.writer.queueView(),old=final.jobs.find(value=>value.id===job.id);assert.equal(final.totalJobs,2);assert.equal(old.local,'locally-cancelled');assert.deepEqual(old.review,frozen);assert.deepEqual(old.stagePlan,job.stagePlan);assert.deepEqual(await readFile(path),bytes);assert.deepEqual((await f.writer.uiRead(before.sessionId,auth())).drafts.find(draft=>draft.id===frozen.draft.draftId),before.drafts.find(draft=>draft.id===frozen.draft.draftId));
});
