import {captureMaskFrame,maskAlignment} from '../../dist/local/src/request/core.js';
import sharp from 'sharp';import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {join} from 'node:path';import {randomUUID,createHash} from 'node:crypto';import {fixture,prepare,enqueue,envelope,encode,auth} from './helpers.mjs';
async function finish(w,c,method){await w[method](encode(c),auth());let record;for(let i=0;i<1000&&!record;i++){record=await w.lookup(c.command.commandId);if(!record)await new Promise(r=>setTimeout(r,5));}assert.equal(record?.receipt.status,'accepted',JSON.stringify(record));return (await w.events(String(BigInt(record.receipt.fromSeq)-1n))).events.find(e=>e.commandId===c.command.commandId);}
for(const masked of [false,true])test('enqueue materializes approved resize with '+(masked?'aligned mask':'source')+' and retains original bytes',async t=>{const f=await fixture(t,{width:3,height:2}),w=f.writer;const bytes=await readFile('tests/raster/fixtures/hidden-alpha.png'),sha256='sha256:'+createHash('sha256').update(bytes).digest('hex'),stagingId=randomUUID();await w.assetCreate({protocolVersion:1,stagingId,purpose:'image',expectedBytes:String(bytes.length),sha256,mediaType:'image/png'},auth());const token=await w.assetBeginChunk(stagingId,'0',bytes.length,auth());await w.assetChunk(token,bytes,auth());const original=(await finish(w,envelope({type:'FinalizeStaging',stagingId,expectedSha256:sha256}),'assetCommand')).payload.asset,preview=(await finish(w,envelope({type:'PrepareRaster',assetId:original.id}),'rasterCommand')).payload.asset,reviewId=(await finish(w,envelope({type:'ReviewRaster',assetId:preview.id}),'rasterCommand')).payload.reviewId,review=await w.rasterReview(reviewId,auth()),asset=(await finish(w,envelope({type:'ApproveRaster',assetId:preview.id,reviewId,reviewHash:review.reviewHash}),'rasterCommand')).payload.asset;
 let mask=null;let document=await w.document('document_1');
 if(masked){
  await finish(w,{...envelope({type:'ImportAsset',assetId:asset.id,layerId:'source_layer',name:'Source',draft:null}),command:{...envelope({type:'ImportAsset',assetId:asset.id,layerId:'source_layer',name:'Source',draft:null}).command,documentId:'document_1',expectedDocumentRevision:'1'}},'historyCommand');
  const a=(await finish(w,envelope({type:'PrepareMask',plan:{width:3,height:2,feather:0,operations:[{kind:'shape',shape:{kind:'rectangle',x:1,y:0,width:1,height:2},mode:'replace'}]}}),'rasterCommand')).payload.asset;
  const c=envelope({type:'SetLayerProperties',layerId:'source_layer',layerVersion:'1',properties:{mask:{assetId:a.id,mapping:'document-r16-v1',inverted:false}},draft:null});c.command.documentId='document_1';c.command.expectedDocumentRevision='2';await finish(w,c,'historyCommand');
  document=await w.document('document_1');const layer=(await w.imageState('document_1')).layers[0];mask={assetId:a.id,version:a.version,blob:a.blob,pixels:a.raster.pixels,width:3,height:2,sourceHash:asset.raster.pixels.hash,polarity:'white-edit',empty:false,full:false,fullAcknowledged:false,plan:a.raster.manifest,frame:captureMaskFrame(document,layer)};
 }
 const p=await prepare(w,d=>{d.operation=masked?'inpaint':'transform';d.source={assetId:asset.id,version:asset.version,blob:asset.blob,pixels:asset.raster.pixels,width:3,height:2,scope:'asset',documentRevision:document.revision};if(mask){mask.frame.alignment=maskAlignment(d.source,mask);d.mask=mask;}d.fields.width='6';d.fields.height='4';d.fields.strength='0.8';d.conversion={from:{width:3,height:2},to:{width:6,height:4},mapping:'stretch',approved:true};});const q=await enqueue(w,p.body),stage=q.job.stagePlan[0];assert.equal(q.job.stagePlan.length,masked?2:1);assert.equal(stage.role,'source');if(masked){assert.equal(q.job.stagePlan[1].role,'mask');assert.deepEqual([q.job.stagePlan[1].width,q.job.stagePlan[1].height],[6,4]);assert.notEqual(q.job.stagePlan[1].transport.hash,mask.blob.hash);}assert.deepEqual(stage.original,asset.blob);assert.notEqual(stage.transport.hash,stage.original.hash);assert.deepEqual([stage.width,stage.height],[6,4]);const path=r=>join(f.root,'objects/sha256',r.hash.slice(7,9),r.hash.slice(7));assert.equal('sha256:'+createHash('sha256').update(await readFile(path(stage.transport))).digest('hex'),stage.transport.hash);assert.deepEqual(await readFile(path(original.blob)),bytes);const template=await readFile(path(q.job.review.template),'utf8');assert.equal(JSON.parse(template).image_url,'asset:'+asset.blob.hash);assert.deepEqual(q.job.review.conversion,p.review.conversion);if(masked){const data=await sharp(path(q.job.stagePlan[1].transport)).raw().toBuffer();const rows=[[0,48,143,143,48,0],[0,64,191,191,64,0],[0,64,191,191,64,0],[0,48,143,143,48,0]];assert.deepEqual([...data],rows.flatMap(row=>row.flatMap(v=>[v,v,v,255])));}});
