import {compileLegacy} from '../../tooling/qualification/legacy-compiler.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {mkdtemp,realpath,cp,readdir,mkdir,readFile,writeFile,rm,symlink,lstat,readlink}from'node:fs/promises';import {tmpdir}from'node:os';import{join,resolve}from'node:path';import{DatabaseSync}from'node:sqlite';import{createHash}from'node:crypto';import{openWriter}from'../../dist/local/server/storage/writer.js';
async function inventory(root){const rows=[];async function walk(dir,rel=''){for(const name of (await readdir(dir)).sort()){const p=join(dir,name),key=rel+name,st=await lstat(p);if(st.isSymbolicLink())rows.push({path:key,link:await readlink(p)});else if(st.isDirectory())await walk(p,key+'/');else rows.push({path:key,bytes:st.size,sha256:createHash('sha256').update(await readFile(p)).digest('hex')});}}await walk(root);return rows;}
const base='9764b03ae889ae2fe2cf5d38e9e8e66bd6cf2eb4';
test('actual accepted 9764 reader opens the verified schema14 rollback with pending job and prompt intact',async t=>{
 const dir=await mkdtemp(join(await realpath(tmpdir()),'p24-rollback-')),old=join(dir,'old'),root=join(dir,'private'),rollback=join(dir,'rollback');await mkdir(old);await mkdir(root,{mode:0o700});await mkdir(rollback,{mode:0o700});
 compileLegacy(old,base,['server','src','tests','tooling','tsconfig.server.json']);
 const run=(path,mode)=>JSON.parse(execFileSync(process.execPath,['--import',resolve('tests/provider/no-egress.mjs'),resolve('tests/candidates/prior-reader.mjs'),old,path,mode],{encoding:'utf8'}));const before=run(root,'create');const w=await openWriter({root});await w.close();const db=new DatabaseSync(join(root,'metadata.sqlite'),{readOnly:true}),receipt=JSON.parse(db.prepare('SELECT receipt FROM schema_migrations WHERE version=15').get().receipt);db.close();assert.equal(receipt.rollback.compatibleExecutable,base);assert.equal('sha256:'+createHash('sha256').update(await readFile(join(root,receipt.backup))).digest('hex'),receipt.backupHash);await cp(join(root,receipt.backup),join(rollback,'metadata.sqlite'));const manifest=JSON.parse(await readFile(join(root,receipt.manifestFile),'utf8'));for(const name of manifest.retainedDirectories)if((await readdir(root)).includes(name))await cp(join(root,name),join(rollback,name),{recursive:true});const after=run(rollback,'read');assert.deepEqual(after,before);const evidence=resolve(process.env.CANDIDATE_EVIDENCE??'artifacts/p24','rollback-'+Date.now());await mkdir(evidence,{recursive:true});const original=await inventory(dir);await cp(dir,join(evidence,'private'),{recursive:true,dereference:false});assert.deepEqual(await inventory(dir),original);assert.deepEqual(await inventory(join(evidence,'private')),original);await writeFile(join(evidence,'inventory.json'),JSON.stringify(original,null,2));await writeFile(join(evidence,'receipt.json'),JSON.stringify({base,receipt,before,after},null,2));t.diagnostic(JSON.stringify({base,backup:receipt.backupHash,pendingJobs:before.queue.jobs.length,evidence}));await rm(dir,{recursive:true});
});
