import test from 'node:test';
import assert from 'node:assert/strict';
import {initialized,pending} from './initialization-helpers.mjs';
import {fixture,prepare,enqueue,envelope,encode,auth} from '../queue/helpers.mjs';
import {StoreDatabase} from '../../dist/local/server/storage/database.js';
import {acquireRoot} from '../../dist/local/server/storage/ownership.js';
const options={timeout:20000};
async function owned(t,x){await x.close();const owner=await acquireRoot(x.f.root),db=new StoreDatabase(x.f.root,()=>{});x.closures.push(async()=>{await db.candidates.close();await db.queue.close();await db.portables.close();await db.histories.close();await db.rasters.close();await db.assets.close();await db.recovery.settle();db.close();owner.close();});return db;}
const counts=db=>({queue:db.db.prepare('SELECT count(*) n FROM queue_journal').get().n,candidates:db.db.prepare('SELECT count(*) n FROM candidate_journal').get().n,jobs:db.db.prepare('SELECT count(*) n FROM candidate_jobs').get().n,view:db.queue.view()});
async function change(db,job,type){const j=db.queue.view().jobs.find(j=>j.id===job),r=await db.queue.command(encode(envelope({type,jobId:j.id,attemptId:j.attempts.at(-1).id,expectedVersion:j.version,...(type==='OverrideUncertainHold'?{acknowledgeOverlapAndChargeRisk:true}:{acknowledgeDuplicateWorkAndChargeRisk:true})})),auth());assert.equal(r.status,'accepted');return db.queue.view().jobs.find(j=>j.id===job);}
test('acknowledged pending view is truthful before any writer restart',options,async t=>{const x=await initialized(t,{restart:false,recover:false}),before=await x.audit();pending(await x.read(x.path),await x.current());assert.deepEqual(await x.audit(),before);});
test('paused recovery stays paused after default and explicit candidate reads',options,async t=>{const x=await initialized(t,{recover:false}),j=await x.current(),before=await x.audit();assert.equal(j.attempts[0].recoveryRequired,true);pending(await x.read(x.path),j);pending(await x.read(x.path.split('?')[0]),j);assert.deepEqual(await x.audit(),before);});
test('one real observer step replaces pending view with its retained observation without new inference',options,async t=>{const x=await initialized(t),j=await x.current();pending(await x.read(x.path),j);const result=await x.step();assert.equal(result.steps,1);assert.equal(result.candidateJournal,1);assert.equal(result.candidateJobs,1);assert.equal(result.effects.filter(e=>e.method==='POST').length,1);assert.equal(result.effects.filter(e=>e.path.endsWith('/status')).length,1);const r=await x.read(x.path);assert.equal(r.status,200);assert.equal(r.json.observation.phase,'running');assert.equal(r.json.actualCount,null);assert.equal(r.json.jobId,j.id);assert.deepEqual(r.json.items,[]);assert.deepEqual(await x.audit(),result);});
test('unknown job and malformed cursor or attempt remain strict HTTP errors',options,async t=>{const x=await initialized(t),before=await x.audit();for(const [path,status] of [['/api/v1/jobs/unknown_job/candidates',404],[x.path+'&after=!',400],[x.path.split('?')[0]+'?attempt=!',400]])assert.equal((await x.read(path)).status,status,path);assert.deepEqual(await x.audit(),before);});
test('unknown and other-job attempts cannot borrow the live job pending projection',options,async t=>{const x=await initialized(t,{other:true}),before=await x.audit();for(const a of ['unknown_attempt',x.q2.job.attempts[0].id])assert.equal((await x.read(x.path.split('?')[0]+'?attempt='+a)).status,404);assert.deepEqual(await x.audit(),before);});
test('permanent deletion rejects a previously valid pending view through the admitted route',options,async t=>{const x=await initialized(t),j=await x.current();await x.command({type:'PreviewDocumentDeletion',documentId:j.documentId,expectedRevision:'1'});const p=(await x.read('/api/v1/documents/'+j.documentId+'/deletion')).json.plan;await x.command({type:'DeleteDocument',documentId:j.documentId,planId:p.id,planHash:p.planHash,rootGeneration:p.rootGeneration,expectedRevision:p.documentRevision,acknowledgeRunningAndUncertain:true});const before=await x.audit();assert.equal((await x.read(x.path)).status,404);assert.deepEqual(await x.audit(),before);});
test('retained tombstone rejects pending projection even when document row still exists',options,async t=>{const x=await initialized(t),db=await owned(t,x);assert(db.document('document_1'));db.db.prepare('INSERT INTO candidate_document_tombstones VALUES (?,?)').run('document_1','1');const before=counts(db);assert.throws(()=>db.candidates.view(x.q.job.id),e=>e.code==='NOT_FOUND');assert.deepEqual(counts(db),before);});
test('cancellation pending does not fabricate terminal observation or release its hold',options,async t=>{const x=await initialized(t),j=await x.current();await x.command({type:'CancelJob',jobId:j.id,attemptId:j.attempts[0].id,expectedVersion:j.version});const before=await x.audit();pending(await x.read(x.path),await x.current());assert.equal(before.queue.jobs[0].attempts[0].cancel,'requested');assert.equal(before.queue.jobs[0].attempts[0].hold,true);assert.deepEqual(await x.audit(),before);});
test('uncertain and new explicit attempt pending views preserve existing retained default selection',options,async t=>{const x=await initialized(t);await x.step();const db=await owned(t,x),job=db.queue.view().jobs[0],old=job.attempts[0].id;db.queue.outcome(job.id,old,db.epoch,{kind:'uncertain',reason:'controlled ambiguity'});const retained=db.candidates.view(job.id,old);await change(db,job.id,'OverrideUncertainHold');const next=await change(db,job.id,'RetryUncertainJob'),a=next.attempts.at(-1);assert.notEqual(a.id,old);const before=counts(db);assert.deepEqual(db.candidates.view(job.id),retained);assert.deepEqual(db.candidates.view(job.id,old),retained);pending({status:200,json:db.candidates.view(job.id,a.id)},next);assert.deepEqual(counts(db),before);});
test('never-dispatched and submission-uncertain attempts expose no invented observation or results',options,async t=>{const clean=[],f=await fixture({name:t.name,after:fn=>clean.push(fn)});t.after(async()=>{for(const fn of clean)await fn();});const p=await prepare(f.writer),q=await enqueue(f.writer,p.body);const v=await f.writer.candidateView(q.job.id);pending({status:200,json:v},q.job);assert.equal((await f.writer.queueView()).jobs[0].attempts[0].state,'not-started');const x=await initialized(t),db=await owned(t,x),j=db.queue.view().jobs[0];db.queue.outcome(j.id,j.attempts[0].id,db.epoch,{kind:'uncertain',reason:'controlled missing acknowledgement'});const before=counts(db);pending({status:200,json:db.candidates.view(j.id)},j);assert.equal(db.queue.view().jobs[0].attempts[0].hold,true);assert.deepEqual(counts(db),before);});
