// Test-only loopback policy and scheduler. No application entry point imports this module.
import {createServer} from 'node:http';import {once} from 'node:events';import {writeFileSync}from'node:fs';import{join}from'node:path';import assert from'node:assert/strict';import sharp from'sharp';
import{emulator,fixtureProfile,SENTINEL_KEY,SENTINEL_COOKIE}from'../provider/emulator.mjs';import{QueueDispatcher}from'../../dist/local/server/provider/dispatcher.js';import{ResultObserver}from'../../dist/local/server/provider/observer.js';
export async function setup(store){
 const effects=[],requests=new Map(),errors=[];let origin='',pending,closing=false;
 const png=await sharp({create:{width:512,height:512,channels:4,background:'#2468ac'}}).png().toBuffer();
 const write=extra=>writeFileSync(join(store.root,'candidate-fixture.json'),JSON.stringify({effects,errors,...extra},null,2),{mode:0o600});
 const server=createServer(async(req,res)=>{try{const parts=[];for await(const b of req)parts.push(b);const body=Buffer.concat(parts);effects.push({method:req.method,path:req.url,bytes:body.length});res.setHeader('Content-Type','application/json');res.setHeader('Set-Cookie',SENTINEL_COOKIE);if(req.method==='POST'){
  assert(['/ideogram/v4','/ideogram/v4/fast','/ideogram/v4/instant'].includes(req.url));const id='fixture_'+(requests.size+1),value=JSON.parse(body.toString());requests.set(id,{endpoint:req.url,value});const base=origin+req.url+'/requests/'+id;res.end(JSON.stringify({request_id:id,status_url:base+'/status',response_url:base,cancel_url:base+'/cancel'}));
 }else if(req.url.startsWith('/image/')){res.setHeader('Content-Type','image/png');res.end(png);}else{const id=/\/requests\/([^/?]+)/.exec(req.url)?.[1],r=requests.get(id);assert(r);if(req.url.endsWith('/status'))res.end(JSON.stringify({request_id:id,status:'COMPLETED'}));else res.end(JSON.stringify({images:[{url:origin+'/image/'+id+'?token=fixture-transfer-secret',content_type:'image/png',file_size:png.length,width:512,height:512}],prompt:r.value.prompt,seed:31,timings:{inference:0.4},has_nsfw_concepts:[false]}));}write({closed:false});}catch(e){errors.push(String(e));res.statusCode=500;res.end('{}');write({closed:false});}});
 server.listen(0,'127.0.0.1');await once(server,'listening');origin='http://127.0.0.1:'+server.address().port;
 const profiles=['ideogram/v4','ideogram/v4/fast','ideogram/v4/instant'].map(endpoint=>fixtureProfile({endpoint})),provider=emulator({queueOrigin:origin,mediaOrigin:origin,profiles}),dispatcher=new QueueDispatcher(store.queue,provider,{queueOrigin:origin,profileId:'local-fixture-v1'}),observer=new ResultObserver(store.candidates,provider,dispatcher,'local-fixture-v1',[SENTINEL_KEY,SENTINEL_COOKIE]);
 const timer=setInterval(()=>{if(closing||pending)return;pending=(async()=>{for(const job of store.queue.view().jobs)if(job.attempts.at(-1).state==='not-started')await dispatcher.submit(job.id);await observer.tick();})().catch(e=>{errors.push(String(e));closing=true;clearInterval(timer);write({closed:false});}).finally(()=>{pending=undefined;});},100);
 write({closed:false});
 return async()=>{closing=true;clearInterval(timer);observer.close();await pending;await new Promise((resolve,reject)=>server.close(e=>e?reject(e):resolve()));const resources={objects:store.objects.reservationInventory(),raster:store.rasters.diagnostics(),text:{reservedCPU:store.texts.reservedCPU,externalBytes:store.texts.externalBytes()}};write({closed:true,resources});assert.deepEqual(errors,[]);assert.equal(resources.objects.activeTransfers,0);assert.equal(resources.objects.reservedBytes,'0');assert.equal(resources.raster.activeWorkers,0);assert.equal(resources.raster.reservedCPU,0);};
}
