import{test as base,expect,type Page}from'@playwright/test';import{mkdtemp,realpath,readFile,mkdir}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';
import{serverProcess}from'./process.js';import{ownedOPFS}from'../editor/owned-opfs.js';import{recordDOMErrors}from'../editor/error-monitor.js';import{runs,step,throwFailures,finishFixture,type RunState}from'../editor/harness-lifecycle.js';import{publicReadRequest}from'../request/persistence-witness.js';
const receipt=process.env.EDITOR_RECEIPT??'artifacts/p24-browser';
const test=base.extend({context:async({playwright,browserName,contextOptions,viewport},use,info)=>{const profile=browserName==='webkit'?await mkdtemp(join(await realpath(tmpdir()),'p24-webkit-')):undefined,browser=profile?undefined:await playwright[browserName].launch(),context=profile?await playwright.webkit.launchPersistentContext(profile,{...contextOptions,viewport}):await browser!.newContext({...contextOptions,viewport});await Promise.all(context.pages().map(p=>p.close()));try{await use(context);}finally{await finishFixture(context,browser,profile,receipt,'candidates-',info);}}});
const click=(page:Page,name:string)=>page.getByRole('button',{name,exact:true}).click();
async function number(page:Page,name:string,value:string){const f=page.getByRole('spinbutton',{name,exact:true});await f.fill(value);await f.press('Tab');}
test('E2 Base and explicit Fast conflict resolution retain independent candidates',async({page,context,browserName})=>{
 const guard=await ownedOPFS(context,'p24-e2'),errors=await recordDOMErrors(context),csp:unknown[]=[],external:string[]=[],consoleErrors:string[]=[],commands:any[]=[],views:any[]=[],runtime:any={},dir=await mkdtemp(join(await realpath(tmpdir()),'p24-e2-')),root=join(dir,'private');let server:any,effects:any,closed:any;
 const state:RunState={failures:[],roots:[dir],writerClosed:false,contextClosed:false,browserClosed:false,retention:[],receipt,prefix:'candidates-'};runs.set(context,state);
 state.observe=()=>({errors,csp,external,consoleErrors,commands,views,runtime,effects,closed,process:server?.lifecycle,requestLifecycle:guard.requests,cleanup:guard.ledger});
 state.finalCheck=async()=>{guard.verify();expect(errors).toEqual([]);expect(csp).toEqual([]);expect(external).toEqual([]);expect(consoleErrors).toEqual([]);expect(closed?.closed).toBe(true);expect(closed?.resources.objects).toEqual({reservedBytes:'0',activeTransfers:0});expect(closed?.resources.raster.activeWorkers).toBe(0);};
 await context.exposeBinding('candidateCSP',(_source,value)=>csp.push(value));await context.addInitScript(()=>addEventListener('securitypolicyviolation',e=>(window as any).candidateCSP({directive:e.effectiveDirective,blocked:e.blockedURI})));
 page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/api/v1/commands'))commands.push(JSON.parse(r.postData()!).command);});
 async function read(path:string){return page.evaluate(async spec=>{const r=await fetch(spec.path,spec.init);if(!r.ok)throw Error('Public read '+r.status);return r.json();},publicReadRequest(path));}
 try{
  server=await serverProcess(root);await context.route('**/*',route=>{const u=new URL(route.request().url());if(['http:','https:'].includes(u.protocol)&&u.origin!==server.origin){external.push(u.origin);return route.abort();}return route.continue();});await mkdir(receipt,{recursive:true});await guard.admit(page,server.origin);await page.goto(await server.pair());Object.assign(runtime,{version:context.browser()?.version()??null,userAgent:await page.evaluate(()=>navigator.userAgent),pin:JSON.parse(await readFile('node_modules/playwright-core/browsers.json','utf8')).browsers.find((b:any)=>b.name===browserName)});
  await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await click(page,'New');await number(page,'Width (px)','512');await number(page,'Height (px)','512');await click(page,'Create');await expect(page.getByRole('dialog',{name:'New document',exact:true})).toBeHidden();await number(page,'Output width','512');await number(page,'Output height','512');
  const prompt=page.getByRole('textbox',{name:'Prompt',exact:true});
  for(const [index,operation,text]of [[0,'Generate image','Base Café\n東京 exact'],[1,'Generate with Fast','Fast Café\n東京 exact']] as const){
   if(index){await click(page,'Close request review');await page.getByRole('combobox',{name:'Operation',exact:true}).selectOption(operation);await prompt.fill(text);await click(page,'Review exact request');await expect(page.locator('#request-errors')).toContainText('acceleration');await expect(page.locator('#request-errors')).toBeFocused();await page.locator('#request-errors').getByRole('link').first().click();await expect(page.getByRole('combobox',{name:'Acceleration',exact:true})).toBeFocused();expect(commands.filter(c=>c.body.type==='QueueInference')).toHaveLength(1);await click(page,'Keep acceleration inactive in this draft');await expect(page.getByText('acceleration is confirmed inactive for this operation.',{exact:true})).toBeVisible();}else await prompt.fill(text);
   await click(page,'Review exact request');await expect(page.locator('#request-review')).toBeFocused();await click(page,'Accept this exact review locally');const enqueue=page.getByRole('button',{name:'Enqueue accepted request',exact:true});await expect(enqueue).toBeEnabled();await enqueue.focus();await enqueue.press('Enter');await expect.poll(()=>commands.filter(c=>c.body.type==='QueueInference').length).toBe(index+1);await prompt.focus();
   let job:any;await expect.poll(async()=>{const q=await read('/api/v1/queue');job=q.jobs.find((j:any)=>j.review.endpoint===(index?'ideogram/v4/fast':'ideogram/v4'));return job?.attempts[0]?.state;}).toBe('provider-terminal');let view:any;await expect.poll(async()=>{view=await read('/api/v1/jobs/'+job.id+'/candidates?attempt='+job.attempts[0].id);return view.items[0]?.state;}).toBe('prepared');views.push(view);await expect(prompt).toBeFocused();expect(view.items).toHaveLength(1);expect(view.provenance.requestedPrompt).toEqual(job.review.prompt);expect(view.items[0].hidden).toBe(false);expect((await read('/api/v1/documents/'+job.documentId)).projection.value.revision).toBe('1');
   await click(page,'Refresh durable queue');const jobCard=page.locator('#durable-queue > en-card').filter({hasText:'Job '+job.id+':'}),inspect=jobCard.getByRole('button',{name:'Inspect retained results',exact:true});await inspect.click();const card=jobCard.locator('.candidate-results');await expect(card).toContainText('Output 1: prepared');await card.getByRole('button',{name:'Inspect image 1',exact:true}).click();const image=card.getByRole('img',{name:'Scaled preview of retained output 1',exact:true});await expect(image).toBeVisible();await expect.poll(()=>image.evaluate((el:HTMLImageElement)=>[el.naturalWidth,el.naturalHeight])).toEqual([256,256]);await expect(card).toContainText('Scaled thumbnail · original 512 × 512.');await card.getByRole('button',{name:'Exact prompt provenance',exact:true}).click();await card.getByRole('button',{name:'Inspect exact returned prompt',exact:true}).click();await expect(card.getByRole('textbox',{name:'Exact prompt page',exact:true})).toHaveValue(text);
  }
  const first=page.locator('#durable-queue > en-card').filter({hasText:'Job '+views[0].jobId+':'}).locator('.candidate-results');await first.getByRole('button',{name:'Hide output 1',exact:true}).click();await expect(first).toContainText('Hidden');await expect(first).toContainText('no disk space is freed');
  await click(page,'Close request review');await page.getByRole('combobox',{name:'Operation',exact:true}).selectOption('Generate with Instant');await click(page,'Keep acceleration inactive in this draft');await click(page,'Keep speed inactive in this draft');await click(page,'Review exact request');await expect(page.locator('#request-review')).toContainText('ideogram/v4/instant');expect(commands.filter(c=>c.body.type==='QueueInference')).toHaveLength(2);
  await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await page.setViewportSize({width:320,height:900});const link=page.getByRole('link',{name:'Go to Request',exact:true});await link.focus();await link.press('Enter');const geometry=await page.locator('.typed-request').evaluate(el=>({width:el.getBoundingClientRect().width,scroll:el.scrollWidth}));expect(geometry.scroll).toBeLessThanOrEqual(geometry.width+1);await page.getByRole('button',{name:'Close request review',exact:true}).focus();await expect(page.getByRole('button',{name:'Close request review',exact:true})).toBeFocused();await page.locator('.candidate-image').scrollIntoViewIfNeeded();if(browserName!=='webkit')await page.screenshot({path:join(receipt,'candidates-viewport.png'),caret:'initial'});
  effects=await server.effects();expect(effects.errors).toEqual([]);expect(effects.effects.filter((e:any)=>e.method==='POST').map((e:any)=>e.path)).toEqual(['/ideogram/v4','/ideogram/v4/fast']);expect(effects.effects.filter((e:any)=>e.path.endsWith('/status'))).toHaveLength(2);expect(effects.effects.filter((e:any)=>e.path.startsWith('/image/'))).toHaveLength(2);expect(effects.effects.filter((e:any)=>e.path.endsWith('/cancel'))).toHaveLength(0);
 }catch(error){state.failures.push({phase:'body',error});}finally{
  if(!state.failures.length)await step(state,'logical-cleanup',async()=>{for(const p of context.pages())await p.goto('about:blank');await guard.cleanup();guard.verify();});
  if(server)state.writerClosed=await step(state,'writer-close',()=>server.close());if(state.writerClosed)await step(state,'native-close-receipt',async()=>{closed=JSON.parse(await readFile(join(root,'candidate-fixture.json'),'utf8'));expect(closed.closed).toBe(true);expect(closed.errors).toEqual([]);});throwFailures(state.failures);
 }
});
