import {test as base,expect,type Page} from '@playwright/test';
import {mkdtemp,realpath,mkdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {serverProcess} from './process.js';
import {ownedOPFS} from './owned-opfs.js';
import {recordDOMErrors} from './error-monitor.js';
const test=base.extend({context:async({playwright,browserName,contextOptions,viewport},use)=>{
 const profile=browserName==='webkit'?await mkdtemp(join(await realpath(tmpdir()),'ie-p1c3-webkit-')):undefined;
 const browser=profile?undefined:await playwright[browserName].launch();
 const context=profile?await playwright.webkit.launchPersistentContext(profile,{...contextOptions,viewport}):await browser!.newContext({...contextOptions,viewport});
 await Promise.all(context.pages().map(page=>page.close()));
 try{await use(context);}finally{await context.close();await browser?.close();if(profile)await rm(profile,{recursive:true,force:true});}
}});
const receipt=process.env.EDITOR_RECEIPT??'artifacts/p1c3/browser';
const click=(p:Page,name:string)=>p.getByRole('button',{name,exact:true}).click();
async function field(p:Page,name:string,value:string){const f=p.getByRole('spinbutton',{name,exact:true});await f.fill(value);await f.press('Tab');}
async function cancelMask(p:Page){await click(p,'Cancel mask draft');await expect(p.getByText(/draft operations\./)).toHaveCount(0);await expect(p.getByRole('button',{name:'Cancel mask draft',exact:true})).toBeDisabled();await expect(p.getByRole('button',{name:'Import PNG mask',exact:true})).toBeEnabled();}
async function importImage(p:Page){await p.locator('.canvas-empty en-file-upload input[type=file]').setInputFiles('tests/raster/fixtures/hidden-alpha.png');await click(p,'Apply reviewed result');await expect(p.getByText('ImportAsset accepted and saved locally.',{exact:true})).toBeVisible();await p.getByRole('treeitem').first().click();}
test('P1c3 selection, exact mask review, draft undo, attachment, sample, transforms and responsive En Reve controls',async({page,context,browserName},info)=>{
 const guard=await ownedOPFS(context,'p1c3-'+info.project.name),errors=await recordDOMErrors(context),consoleErrors:string[]=[],failedResponses:unknown[]=[],commands:string[]=[],plans:any[]=[];
 page.on('response',async r=>{if(r.status()>=400)failedResponses.push({url:r.url(),status:r.status(),body:await r.text().catch(()=>'<unavailable>')});});
  page.on('pageerror',e=>consoleErrors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});
 page.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname==='/api/v1/commands'){const body=JSON.parse(r.postData()!).command.body;commands.push(body.type);if(body.type==='PrepareMask')plans.push(body.plan);}});
 const dir=await mkdtemp(join(await realpath(tmpdir()),'ie-p1c3-')),server=await serverProcess(join(dir,'private'));
 await mkdir(receipt,{recursive:true});
 try{
  await guard.admit(page,server.origin);await page.goto(await server.pair());await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await importImage(page);
  await click(page,'Select');await field(page,'Selection X','1');await field(page,'Selection Y','0');await field(page,'Selection width','1');await field(page,'Selection height','2');
  const revision=await page.locator('.document-name').textContent();await click(page,'Apply selection');expect(await page.locator('.document-name').textContent()).toBe(revision);
  await click(page,'Use selection as mask');await field(page,'Feather radius (document px)','2');await click(page,'Preview mask');await expect(page.getByRole('button',{name:'Apply layer mask',exact:true})).toBeEnabled();
  await expect(page.getByText(/Hard support: 2 pixels. Effective support: 6 pixels/)).toBeVisible();
  await page.getByRole('radio',{name:'hard',exact:true}).focus();await page.keyboard.press('Space');await expect(page.getByAltText('hard mask view')).toBeVisible();await page.getByRole('radio',{name:'effective',exact:true}).focus();await page.keyboard.press('Space');await page.getByRole('radio',{name:'result',exact:true}).focus();await page.keyboard.press('Space');
  const before=commands.filter(c=>c==='SetLayerProperties').length;await click(page,'Apply layer mask');await expect(page.getByText('SetLayerProperties accepted and saved locally.',{exact:true})).toBeVisible();expect(commands.filter(c=>c==='SetLayerProperties').length).toBe(before+1);
  await click(page,'Sample');await field(page,'Sample X','1');await field(page,'Sample Y','0');await page.getByRole('button',{name:'Sample color',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByText(/sRGB RGBA \(255, 0, 0, 48\)/)).toBeVisible();await expect(page.locator('en-alert').filter({hasText:'sRGB RGBA (255, 0, 0, 48)'})).toHaveAttribute('announcement','polite');
  await click(page,'Undo');await expect(page.getByText('Undo accepted and saved locally.',{exact:true})).toBeVisible();
  await click(page,'Mask');await click(page,'Fill all');await click(page,'Clear mask');await click(page,'Undo mask stroke');await click(page,'Preview mask');await expect(page.getByText(/Hard support: 6 pixels/)).toBeVisible();await cancelMask(page);
  await click(page,'Select');await click(page,'100%');
  const selectionBox=(await page.locator('canvas').boundingBox())!,sx=selectionBox.x+selectionBox.width/2-1.5,sy=selectionBox.y+selectionBox.height/2-1;
  await page.mouse.move(sx+1,sy);await page.mouse.down();await page.mouse.move(sx+2,sy+2);await page.mouse.up();await click(page,'Use selection as mask');await click(page,'Preview mask');await expect(page.getByRole('button',{name:'Apply layer mask',exact:true})).toBeEnabled();
  const pointerPlan=plans.at(-2);for(const [label,key] of [['Selection X','x'],['Selection Y','y'],['Selection width','width'],['Selection height','height']])expect(Number(await page.getByRole('spinbutton',{name:label,exact:true}).inputValue())).toBe(pointerPlan.operations[0].shape[key]);await cancelMask(page);
  await click(page,'Apply selection');await click(page,'Use selection as mask');await click(page,'Preview mask');await expect(page.getByRole('button',{name:'Apply layer mask',exact:true})).toBeEnabled();expect(plans.at(-2).operations).toEqual(pointerPlan.operations);await cancelMask(page);
  await click(page,'Mask');await click(page,'Fill all');await expect(page.getByText(/1 draft operations/)).toBeVisible();await field(page,'Feather radius (document px)','65');await click(page,'Preview mask');await expect(page.getByText('Feather radius must be between 0 and 64 document pixels.',{exact:true}).first()).toBeVisible();await field(page,'Feather radius (document px)','2');const count=commands.filter(c=>c==='PrepareMask').length;
  await page.getByRole('button',{name:'Preview mask',exact:true}).evaluate(button=>(button.getRootNode() as ShadowRoot).host.addEventListener('click',e=>e.preventDefault(),{once:true}));await click(page,'Preview mask');await expect(page.getByRole('button',{name:'Preview mask',exact:true})).toBeEnabled();expect(commands.filter(c=>c==='PrepareMask').length).toBe(count);
  await field(page,'Brush diameter (document px)','1');const brushBox=(await page.locator('canvas').boundingBox())!,bx=brushBox.x+brushBox.width/2,by=brushBox.y+brushBox.height/2;
  await page.getByRole('radio',{name:'subtract',exact:true}).last().focus();await page.keyboard.press('Space');
  await page.mouse.move(bx,by);await page.mouse.down();await page.mouse.move(bx+1,by);await page.mouse.up();await expect(page.getByText(/2 draft operations/)).toBeVisible();await click(page,'Undo mask stroke');await expect(page.getByText(/1 draft operations/)).toBeVisible();
  await expect(page.getByText('Draft saved locally; not applied to the document',{exact:true}).first()).toBeVisible();await page.reload();await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await page.getByRole('treeitem').first().click();await click(page,'Mask');await expect(page.getByText(/1 draft operations/)).toBeVisible();
  const second=await context.newPage();await second.goto(server.origin);await expect(second.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await second.getByRole('treeitem').first().click();await field(second,'Opacity (0–1)','0.75');await click(second,'Apply properties');await expect(second.getByText('SetLayerProperties accepted and saved locally.',{exact:true})).toBeVisible();await expect(page.getByText('Stale mask draft',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Preview mask',exact:true})).toBeDisabled();await second.close();await cancelMask(page);
  await expect(page.getByRole('button',{name:'Import PNG mask',exact:true})).toBeEnabled();await page.locator('en-file-upload').filter({hasText:'Import PNG mask'}).locator('input[type=file]').setInputFiles('tests/raster/fixtures/hidden-alpha.png');await expect(page.getByRole('button',{name:'Review aligned mask',exact:true})).toBeVisible();const approvals=commands.filter(c=>c==='ApproveRaster').length;await field(page,'Imported mask X','0.5');await click(page,'Review aligned mask');await expect(page.getByText('Mask alignment must use whole document pixels at the imported native size.',{exact:true}).first()).toBeVisible();expect(commands.filter(c=>c==='ApproveRaster').length).toBe(approvals);await field(page,'Imported mask X','0');await click(page,'Review aligned mask');await expect(page.getByRole('button',{name:'Apply layer mask',exact:true})).toBeEnabled();await cancelMask(page);
  await click(page,'Lock layer');await expect(page.getByRole('button',{name:'Unlock layer',exact:true})).toBeVisible();await click(page,'Unlock layer');await expect(page.getByRole('button',{name:'Lock layer',exact:true})).toBeVisible();
  await click(page,'Move');await click(page,'100%');const canvas=page.locator('canvas'),box=(await canvas.boundingBox())!,cx=box.x+box.width/2,cy=box.y+box.height/2;
  const transformCount=commands.filter(c=>c==='ApplyTransform').length;await page.mouse.move(cx,cy);await page.mouse.down();await page.mouse.move(cx+10,cy+5);await page.mouse.up();await expect(page.getByText('ApplyTransform accepted and saved locally.',{exact:true})).toBeVisible();expect(commands.filter(c=>c==='ApplyTransform').length).toBe(transformCount+1);
  await page.mouse.move(cx,cy);await page.mouse.down();await page.mouse.move(cx+5,cy+5);await page.locator('#canvas').focus();await page.keyboard.press('Escape');await page.mouse.up();expect(commands.filter(c=>c==='ApplyTransform').length).toBe(transformCount+1);
  const colors:string[]=[];for(const appearance of ['light','dark']){await page.evaluate(v=>document.documentElement.setAttribute('data-en-appearance',v),appearance);colors.push(await page.locator('body').evaluate(el=>getComputedStyle(el).color));await page.getByRole('button',{name:'Sample color',exact:true}).focus();await expect(page.getByRole('button',{name:'Sample color',exact:true})).toBeFocused();}expect(colors[0]).not.toBe(colors[1]);
  await field(page,'Zoom percentage','200');await expect(page.getByRole('spinbutton',{name:'Zoom percentage',exact:true})).toHaveValue('200');await click(page,'100%');
  if(browserName!=='webkit')await page.screenshot({path:join(receipt,'authoring-desktop.png'),caret:'initial'});
  for(const width of [720,320]){await page.setViewportSize({width,height:950});for(const dir of ['ltr','rtl']){await page.evaluate(d=>document.documentElement.dir=d,dir);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await expect(page.getByRole('button',{name:'Preview mask',exact:true})).toBeVisible();}}
  if(browserName!=='webkit')await page.screenshot({path:join(receipt,'authoring-320.png'),caret:'initial'});
  await page.getByRole('button',{name:'Preview mask',exact:true}).scrollIntoViewIfNeeded();if(browserName!=='webkit')await page.screenshot({path:join(receipt,'mask-controls-320.png'),caret:'initial'});
  expect(errors).toEqual([]);expect(consoleErrors).toEqual([]);expect(Object.values(await server.effects()).every(v=>v===0)).toBe(true);
 }finally{try{await guard.cleanup();guard.verify();}finally{await writeFile(join(receipt,'ownership.json'),JSON.stringify(guard.ledger,null,2));await writeFile(join(receipt,'commands.json'),JSON.stringify(commands,null,2));await writeFile(join(receipt,'errors.json'),JSON.stringify({errors,consoleErrors,failedResponses},null,2));await server.close();}}
});
test('P1c3 inherited layer operations and reviewed geometry remain usable through public controls',async({page,context,browserName})=>{
 const guard=await ownedOPFS(context,'p1c3-inherited-'+browserName),errors=await recordDOMErrors(context),commands:any[]=[],ids=new Map<string,string>(),receipts=new Map<string,any>(),seen=new Map<string,number>();
 const dir=await mkdtemp(join(await realpath(tmpdir()),'ie-p1c3-inherited-')),server=await serverProcess(join(dir,'private'));
 page.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname==='/api/v1/commands'){const c=JSON.parse(r.postData()!).command;commands.push(c.body);ids.set(c.commandId,c.body.type);}});
 page.on('response',async r=>{if(new URL(r.url()).pathname.startsWith('/api/v1/commands')&&r.status()===200){const value=await r.json().catch(()=>null);if(value?.receipt)receipts.set(value.receipt.commandId,value.receipt);}});
 let observedRevision='';const accepted=async(type:string)=>{const count=()=>[...receipts].filter(([id,r])=>ids.get(id)===type&&r.status==='accepted').length;await expect.poll(count).toBeGreaterThan(seen.get(type)??0);seen.set(type,count());await expect(page.locator('.document-name')).not.toHaveText(observedRevision);observedRevision=(await page.locator('.document-name').textContent())!;await expect(page.getByRole('button',{name:'Undo',exact:true})).toBeEnabled();};
 try{
  await guard.admit(page,server.origin);await page.goto(await server.pair());await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await importImage(page);
  await page.getByRole('textbox',{name:'Layer name',exact:true}).fill('Renamed original');await field(page,'Opacity (0–1)','0.75');await click(page,'Apply properties');await accepted('SetLayerProperties');await expect(page.getByRole('treeitem')).toContainText('Renamed original');
  await click(page,'Duplicate');await accepted('DuplicateLayer');await expect(page.getByRole('treeitem')).toHaveCount(2);await page.getByRole('treeitem').first().click();await click(page,'Move down');await accepted('MoveLayers');await click(page,'Move up');await accepted('MoveLayers');
  const visible=page.getByRole('switch',{name:'Visible',exact:true});await visible.focus();await page.keyboard.press('Space');await click(page,'Apply properties');await accepted('SetLayerProperties');expect(commands.filter(c=>c.type==='SetLayerProperties').at(-1).properties.visible).toBe(false);
  await visible.focus();await page.keyboard.press('Space');await click(page,'Apply properties');await accepted('SetLayerProperties');
  const before=commands.filter(c=>c.type==='ApplyTransform').length;for(const [name,value] of [['X','1'],['Y','1'],['A','0.5'],['D','0.5']])await field(page,name,value);await click(page,'Apply transform');await accepted('ApplyTransform');expect(commands.filter(c=>c.type==='ApplyTransform').length).toBe(before+1);expect(commands.filter(c=>c.type==='ApplyTransform').at(-1).transform).toEqual([0.5,0,0,0.5,1,1]);
  await click(page,'Delete layer');await accepted('DeleteLayer');await expect(page.getByRole('treeitem')).toHaveCount(1);await click(page,'Undo');await accepted('Undo');await expect(page.getByRole('treeitem')).toHaveCount(2);await page.getByRole('treeitem').first().click();
  await click(page,'Resample image…');await field(page,'Intrinsic width (px)','6');await field(page,'Intrinsic height (px)','4');await click(page,'Prepare preview');await expect(page.getByRole('dialog',{name:'Review prepared image edit'})).toBeVisible();await click(page,'Apply reviewed result');await accepted('ResampleImage');
  await click(page,'Canvas bounds…');await page.getByRole('combobox',{name:'Bounds action',exact:true}).selectOption('resize');await field(page,'Width (px)','4');await field(page,'Height (px)','3');await click(page,'Apply bounds');await expect(page.locator('.document-name')).toContainText('4 × 3');
  await click(page,'Canvas bounds…');await page.getByRole('combobox',{name:'Bounds action',exact:true}).selectOption('crop');await field(page,'Width (px)','2');await field(page,'Height (px)','2');await click(page,'Apply bounds');await expect(page.locator('.document-name')).toContainText('2 × 2');
  await click(page,'Flatten copy…');await click(page,'Prepare preview');await expect(page.getByRole('dialog',{name:'Review prepared image edit'})).toBeVisible();const flattened=commands.filter(c=>c.type==='CreateFlattenedCopy').length;await click(page,'Apply reviewed result');await accepted('CreateFlattenedCopy');expect(commands.filter(c=>c.type==='CreateFlattenedCopy').length).toBe(flattened+1);await expect(page.getByRole('treeitem')).toHaveCount(3);
  const handle=page.getByRole('separator',{name:'Request panel width',exact:true});await handle.focus();const width=await page.locator('#left-divider').evaluate((h:any)=>h.value);await page.keyboard.press('ArrowRight');expect(await page.locator('#left-divider').evaluate((h:any)=>h.value)).toBeGreaterThan(width);
  const splitter=await page.locator('#left-divider').evaluate(h=>({track:getComputedStyle(h.parentElement!).gridTemplateColumns.split(' ')[1],margin:getComputedStyle(h).marginInlineStart,width:h.getBoundingClientRect().width,z:getComputedStyle(h).zIndex}));expect(splitter.track).toBe('1px');expect(parseFloat(splitter.margin)).toBe(-(splitter.width-1)/2);expect(splitter.z).toBe('1');
  expect(errors).toEqual([]);expect(Object.values(await server.effects()).every(v=>v===0)).toBe(true);
 }finally{try{await guard.cleanup();guard.verify();}finally{await mkdir(receipt,{recursive:true});await writeFile(join(receipt,'inherited-ownership.json'),JSON.stringify(guard.ledger,null,2));await writeFile(join(receipt,'inherited-commands.json'),JSON.stringify(commands,null,2));await writeFile(join(receipt,'inherited-receipts.json'),JSON.stringify([...receipts],null,2));await writeFile(join(receipt,'inherited-errors.json'),JSON.stringify(errors,null,2));await server.close();}}
});

test('P1c3 retained attached mask bounds and reviewed baseline Cancel/Apply',async({page,context,browserName},info)=>{
 const guard=await ownedOPFS(context,'p1c3-retained-'+info.project.name),errors=await recordDOMErrors(context),consoleErrors:string[]=[],bodies:any[]=[];
 page.on('pageerror',e=>consoleErrors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname==='/api/v1/commands')bodies.push(JSON.parse(r.postData()!).command.body);});
 const dir=await mkdtemp(join(await realpath(tmpdir()),'ie-p1c3-retained-')),server=await serverProcess(join(dir,'private'));await mkdir(receipt,{recursive:true});
 try{
  await guard.admit(page,server.origin);await page.goto(await server.pair());await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await importImage(page);
  await click(page,'Select');await field(page,'Selection X','1');await field(page,'Selection Y','0');await field(page,'Selection width','1');await field(page,'Selection height','2');await click(page,'Apply selection');await click(page,'Use selection as mask');await click(page,'Preview mask');await expect(page.getByRole('button',{name:'Apply layer mask',exact:true})).toBeEnabled();await click(page,'Apply layer mask');await expect(page.getByText('SetLayerProperties accepted and saved locally.',{exact:true})).toBeVisible();
  await click(page,'Canvas bounds…');await expect(page.getByText(/Original pixels and hard\/effective coverage stay intact/)).toBeVisible();await page.getByRole('combobox',{name:'Bounds action',exact:true}).selectOption('crop');await field(page,'Width (px)','2');await field(page,'Height (px)','2');await field(page,'X offset / crop origin (px)','1');const count=bodies.filter(b=>b.type==='CropDocument').length;await click(page,'Apply bounds');await expect(page.locator('.document-name')).toContainText('2 × 2');expect(bodies.filter(b=>b.type==='CropDocument').length).toBe(count+1);
  await click(page,'Sample');await field(page,'Sample X','0');await field(page,'Sample Y','0');await page.getByRole('button',{name:'Sample color',exact:true}).focus();await page.keyboard.press('Enter');const status=page.locator('en-alert').filter({hasText:'sRGB RGBA (255, 0, 0, 128)'});await expect(status).toBeVisible();await expect(status).toHaveAttribute('announcement','polite');
  await click(page,'Mask');await click(page,'Fill all');await expect(page.getByText(/This new draft starts from the retained mask/)).toBeVisible();const revision=await page.locator('.document-name').textContent();await click(page,'Preview mask');await expect(page.getByRole('button',{name:'Apply layer mask',exact:true})).toBeEnabled();expect(bodies.filter(b=>b.type==='PrepareMask').at(-1).plan.schemaVersion).toBe(2);await cancelMask(page);expect(await page.locator('.document-name').textContent()).toBe(revision);
  await click(page,'Fill all');await click(page,'Preview mask');await expect(page.getByRole('button',{name:'Apply layer mask',exact:true})).toBeEnabled();await click(page,'Apply layer mask');await expect(page.getByText('SetLayerProperties accepted and saved locally.',{exact:true})).toBeVisible();await click(page,'Undo');await expect(page.getByText('Undo accepted and saved locally.',{exact:true})).toBeVisible();
  await click(page,'Canvas bounds…');await field(page,'Width (px)','4');await field(page,'Height (px)','3');await field(page,'X offset / crop origin (px)','1');await field(page,'Y offset / crop origin (px)','1');await click(page,'Apply bounds');await expect(page.locator('.document-name')).toContainText('4 × 3');
  expect(consoleErrors).toEqual([]);expect(errors).toEqual([]);expect(Object.values(await server.effects()).every(n=>n===0)).toBe(true);
  await writeFile(join(receipt,'retained-bounds-'+browserName+'.json'),JSON.stringify({bodies,consoleErrors,errors},null,2));
 }finally{await guard.cleanup();guard.verify();await writeFile(join(receipt,'retained-ownership-'+browserName+'.json'),JSON.stringify(guard.ledger,null,2));await server.close();}
});
