// Source-only fixture authorship. This loads actual production methods and owners;
// transport/journal fixtures do not claim native IndexedDB clone measurement.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
import {transformWithOxc} from 'vite';
import {createValueModel} from '@en-reve/primitives/state/value.js';
import {allocationsURL as allocations} from '../owned-preview-module.mjs';
const root=process.env.CLIENT_CONTROL_ROOT??'.',stateRoot=process.env.STATE_CONTROL_ROOT??'.',ownerRoot=process.env.CLIENT_CONTROL_OWNER_ROOT??root,data=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
async function source(path,imports={}){let value=(await transformWithOxc(await readFile(path,'utf8'),path)).code;for(const [name,url]of Object.entries(imports))value=value.replaceAll(JSON.stringify(name),JSON.stringify(url)).replaceAll("'"+name+"'",JSON.stringify(url));return data(value);}
const prompt=await source('src/observability/prompt-memory.ts',{'./allocations.js':allocations}),memory=await source('src/observability/model-memory.ts',{'./allocations.js':allocations,'./prompt-memory.js':prompt}),control=await source('src/state/control-memory.ts',{'../observability/allocations.js':allocations}),json=await source('src/protocol/json.ts'),sha=await source('src/protocol/sha256.ts');
const commands=await source(ownerRoot+'/src/state/command-results.ts',{'../observability/allocations.js':allocations,'../observability/model-memory.js':memory,'../observability/prompt-memory.js':prompt,'./control-memory.js':control,'../protocol/json.js':json,'../protocol/sha256.js':sha,'../protocol/validate.js':pathToFileURL(resolve('dist/local/src/protocol/validate.js')).href});
const views=await source(ownerRoot+'/src/state/view-models.ts',{'../observability/allocations.js':allocations,'../observability/model-memory.js':memory,'../observability/prompt-memory.js':prompt,'./control-memory.js':control,'../protocol/json.js':json,'../protocol/sha256.js':sha});
const draftValues=await source(stateRoot+'/src/state/draft-values.ts',{'../observability/allocations.js':allocations,'../observability/model-memory.js':memory,'../observability/prompt-memory.js':prompt,'./control-memory.js':control});
const drafts=await source(stateRoot+'/src/state/draft-persistence.ts',{'../observability/allocations.js':allocations,'../observability/model-memory.js':memory,'../observability/prompt-memory.js':prompt,'./control-memory.js':control,'./command-results.js':commands,'./draft-values.js':draftValues});
const stripped=(await transformWithOxc(await readFile(root+'/src/state/editor-client.ts','utf8'),'editor-client.ts')).code.replace(/^import\s+[\s\S]*?\sfrom\s+["'][^"']+["'];?\n/gm,'');
const clientURL=data(`import {allocationLedger} from ${JSON.stringify(allocations)};import {readRetainedPrompt} from ${JSON.stringify(prompt)};import {readOwnedJSON,createOwnedModel,cloneOwnedModel,modelPayloadBytes,reserveModelBytes,ModelPayload} from ${JSON.stringify(memory)};import {reserveCommandWire,measureControl} from ${JSON.stringify(control)};import {ViewModelOwners,ViewModelReads,VIEW_MODEL_LIMITS,canonicalControlHash,ownDownload} from ${JSON.stringify(views)};import {CommandControlReads,COMMAND_RESULT_LIMITS} from ${JSON.stringify(commands)};const EMPTY_EXPECTED_VERSIONS={};const browserPhases={resetNavigation(){},recorder:{start(){return {end(){}};}},reset(){}};import {DraftPersistence} from ${JSON.stringify(drafts)};\n`+stripped);
const {EditorClient}=await import(clientURL),{allocationLedger}=await import(allocations),{createOwnedModel}=await import(memory),{ViewModelOwners,ViewModelReads}=await import(views),{CommandControlReads}=await import(commands),{DraftPersistence}=await import(drafts),{ControlAdmissionError}=await import(control);
const totals=()=>{const s=allocationLedger.snapshot();return {cpu:s.cpuBytes,handles:s.handles,records:s.activeRecords};},deferred=()=>{let resolve;const promise=new Promise(a=>resolve=a);return {promise,resolve};},flush=async()=>{for(let i=0;i<80;i++)await Promise.resolve();};
const response=value=>{const text=JSON.stringify(value);return new Response(text,{headers:{'content-length':String(Buffer.byteLength(text))}});};
function fixture(transport=async()=>{throw Error('unexpected transport');}){const client=Object.create(EditorClient.prototype);Object.assign(client,{state:createValueModel({documents:[],document:null,image:null,history:[],checkpoints:[],save:null,download:null,review:null,pending:[],uiChoices:[],stages:[],selected:[],uiPending:[],message:'',error:'',recovery:'',drafts:'',cursor:'0',historyNext:null,checkpointNext:null,uiNext:null,stageNext:null,pendingAfter:null,pendingDirection:'next',pendingPrevious:null,pendingNext:null,pendingCreate:false,ready:false,busy:false,undoAvailable:null}),viewModels:new ViewModelOwners(),viewReads:new ViewModelReads(),recoveryDrain:Promise.resolve(),importAdmissions:new Map(),exportAdmissions:new Map(),reviewAdmissions:new Map(),controlReads:new CommandControlReads(),session:{identity:()=> 'client',csrf:()=> 'csrf',transport},owner:'client',lifecycle:1,documentLifetime:1,pendingRead:0,retiredDraftOwners:new Set(),draftOwnerDrains:new Map()});client.mountViewMetadata();return client;}
async function close(client){client.patch({pending:[],uiChoices:[],stages:[],review:null});client.ui=undefined;await client.draftOwner?.dispose();await client.controlReads.release();client.viewModels.releaseControlView();}
const checkpoint=seq=>({sessionId:'session',uiSeq:seq,preferences:{documentId:'document',tool:'select',viewport:{x:0,y:0,zoom:1},panels:{left:280,right:320,active:'layers'},selectedLayerIds:[]},drafts:[{id:'draft',generation:seq,kind:'prompt',documentId:'document',targetLayerId:null,expectedDocumentRevision:'1',assetId:'caption-'+seq,composing:false,status:'saved-unapplied'}],reconciledLayerIds:[]});
function pendingJournal(count=40){
 const rows=new Map(),scans=[],gets=[],puts=[];
 for(let i=0;i<count;i++){const id=String(i).padStart(3,'0'),request={protocolVersion:1,command:{schemaVersion:1,commandId:id,clientId:'client',sessionId:'session',transactionId:'transaction-'+id,correlationId:'correlation-'+id,causationId:null,documentId:null,expectedDocumentRevision:null,expectedEntityVersions:{hash:'sha256:'+'0'.repeat(64),byteLength:'2',mediaType:'application/json'},issuedAt:'2026-10-01T00:00:00.000Z',body:{type:'SaveCheckpoint',name:'Saved '+id}}};rows.set('command:'+id,{request,wire:JSON.stringify(request,null,2)+'\n',label:'Saved '+id});const settled={...request,command:{...request.command,commandId:id+'-settled'}};rows.set('command:'+id+'-settled',{request:settled,wire:JSON.stringify(settled,null,2)+'\n',label:'Settled '+id,result:{kind:'receipt'}});}
 const journal={async scan(prefix,visit,{after=null,direction='next'}={}){const scan={after,direction,unresolved:0,keys:[]};scans.push(scan);const entries=[...rows].filter(([key])=>key.startsWith(prefix)&&(after===null||(direction==='prev'?key<after:key>after))).sort(([a],[b])=>a<b?-1:a>b?1:0);if(direction==='prev')entries.reverse();for(const [key,value]of entries){scan.keys.push(key);if(value.result?.kind!=='receipt')scan.unresolved++;if(visit(structuredClone(value),key)===false)break;}},async get(key){gets.push(key);return rows.has(key)?structuredClone(rows.get(key)):undefined;},async put(key,value){puts.push(key);rows.set(key,structuredClone(value));}};
 return {rows,scans,gets,puts,journal};
}
const pendingIDs=client=>client.view.pending.map(row=>row.request.command.commandId);
const pageState=client=>Object.fromEntries(['pendingAfter','pendingDirection','pendingPrevious','pendingNext','pendingCreate'].map(key=>[key,client.view[key]]));

test('scoped command snapshots before its deferred admission and drains the real callback owner',async()=>{const baseline=totals(),client=fixture(),gate=deferred();let called=false,bodySeen;client.ownedCommand=async body=>{bodySeen=body;return createOwnedModel('fixture-events',128,()=>[{type:'PortableCancelled',payload:{operationId:'one'}}]);};const body={type:'CancelPortable',operationId:'one'},task=client.withCommandEvents(body,async events=>{called=true;assert.equal(events[0].payload.operationId,'one');await gate.promise;return 'done';});void task.catch(()=>{});let drained=false;try{body.operationId='changed';await flush();assert.equal(bodySeen.operationId,'one');assert.equal(called,true);const drain=client.controlReads.release().then(()=>{drained=true;});await flush();assert.equal(drained,false);assert(totals().cpu>baseline.cpu);gate.resolve();assert.equal(await task,'done');await drain;}finally{gate.resolve();await task.catch(()=>{});await close(client);}assert.deepEqual(totals(),baseline);});
test('review replacement is prospectively admitted and real render pin retains the old root',async()=>{const baseline=totals(),client=fixture();let pin;try{client.patch({review:{kind:'edit',review:{reviewId:'first'}}});const first=client.view.review;pin=client.renderViewModels(first)[0].pin();client.patch({review:{kind:'edit',review:{reviewId:'second'}}});assert.equal(first.review.reviewId,'first');assert.equal(client.viewModels.ownership.retiredPinnedRoots,1);assert.throws(()=>client.patch({review:{kind:'edit',review:{payload:'x'.repeat(1024*1024)}}}),error=>error instanceof ControlAdmissionError&&error.reason==='size'&&error.limit===1024*1024);assert.equal(client.view.review.review.reviewId,'second');pin();assert.equal(client.viewModels.ownership.retiredPinnedRoots,0);}finally{pin?.();await close(client);}assert.deepEqual(totals(),baseline);});
test('inventory publishes both exact array and row identities and unchanged pages reuse roots',async()=>{const baseline=totals(),page={protocolVersion:1,kind:'ui-inventory',semantics:'current-at-page-read',writerEpoch:'1',next:null,items:[{sessionId:'session',documentId:null,uiSeq:'1'}]},client=fixture(async()=>response(page));let pin;try{await client.listUI();const first=client.view.uiChoices,render=client.renderViewModels(first,first[0]);assert.equal(render.length,1);pin=render[0].pin();await client.listUI();assert.equal(client.view.uiChoices,first);page.items[0].uiSeq='2';await client.listUI();assert.notEqual(client.view.uiChoices,first);assert.equal(first[0].uiSeq,'1');assert.equal(client.viewModels.ownership.retiredPinnedRoots,1);}finally{pin?.();await close(client);}assert.deepEqual(totals(),baseline);});
test('forty pending deliveries remain reachable in bounded keyset pages while old render pins retain exact rows',async()=>{
 const baseline=totals(),client=fixture(),f=pendingJournal(),saved=structuredClone([...f.rows]);client.journal=f.journal;let pin;
 try{await client.listPending();assert.deepEqual(pendingIDs(client),Array.from({length:32},(_,i)=>String(i).padStart(3,'0')));assert.deepEqual(pageState(client),{pendingAfter:null,pendingDirection:'next',pendingPrevious:null,pendingNext:'command:031',pendingCreate:false});
  const first=client.view.pending,roots=client.renderViewModels(first,first[0]);assert.equal(roots.length,1);pin=roots[0].pin();
  await client.listPending('next');assert.deepEqual(pendingIDs(client),Array.from({length:8},(_,i)=>String(i+32).padStart(3,'0')));assert.deepEqual(pageState(client),{pendingAfter:'command:031',pendingDirection:'next',pendingPrevious:'command:032',pendingNext:null,pendingCreate:false});assert.equal(first[0].request.command.commandId,'000');assert.equal(client.viewModels.ownership.retiredPinnedRoots,1);assert.equal(client.renderViewModels(first,first[0]).length,1);
  pin();pin=undefined;assert.equal(client.viewModels.ownership.retiredPinnedRoots,0);assert.throws(()=>client.renderViewModels(first),/UNOWNED/);
  await client.listPending('previous');assert.deepEqual(pendingIDs(client),Array.from({length:32},(_,i)=>String(i).padStart(3,'0')));assert.equal(client.view.pendingPrevious,null);assert.equal(client.view.pendingNext,'command:031');assert.equal(client.view.pending.length,32);
  await client.listPending('first');assert.equal(client.view.pendingAfter,null);assert.equal(client.view.pendingDirection,'next');assert.deepEqual([...f.rows],saved);assert.deepEqual(f.gets,[]);assert.deepEqual(f.puts,[]);
 }finally{pin?.();await close(client);}assert.deepEqual(totals(),baseline);
});
test('refresh of a fully resolved last page falls back to the first remaining page without changing original deliveries',async()=>{
 const baseline=totals(),client=fixture(),f=pendingJournal(),originals=[...f.rows].map(([key,value])=>[key,{request:structuredClone(value.request),wire:value.wire}]);client.journal=f.journal;
 try{await client.listPending();await client.listPending('next');assert.deepEqual(pendingIDs(client),Array.from({length:8},(_,i)=>String(i+32).padStart(3,'0')));
  for(let i=32;i<40;i++){const key='command:'+String(i).padStart(3,'0');f.rows.set(key,{...f.rows.get(key),result:{kind:'receipt'}});}
  await client.restorePending();assert.deepEqual(pendingIDs(client),Array.from({length:32},(_,i)=>String(i).padStart(3,'0')));assert.deepEqual(pageState(client),{pendingAfter:null,pendingDirection:'next',pendingPrevious:null,pendingNext:null,pendingCreate:false});assert.equal(f.rows.size,80);
  assert.deepEqual([...f.rows].map(([key,value])=>[key,{request:value.request,wire:value.wire}]),originals);assert.deepEqual(f.gets,[]);assert.deepEqual(f.puts,[]);
 }finally{await close(client);}assert.deepEqual(totals(),baseline);
});
for(const failure of ['scan','publication'])test('failed pending '+failure+' preserves the complete previous page and refunds candidate ownership',async()=>{
 const baseline=totals(),client=fixture(),f=pendingJournal();client.journal=f.journal;let state;
 try{await client.listPending();const prior=client.view.pending,cursors=pageState(client),held=totals(),saved=structuredClone([...f.rows]);
  if(failure==='scan')f.journal.scan=async(_prefix,visit)=>{visit(structuredClone(f.rows.get('command:032')),'command:032');throw Error('PENDING_SCAN_FAILED');};
  else{state=client.state;client.state={value:state.value,set(next){if(next.pending!==prior)throw Error('PENDING_PUBLICATION_FAILED');state.set(next);}};}
  await assert.rejects(client.listPending('next'),failure==='scan'?/PENDING_SCAN_FAILED/:/PENDING_PUBLICATION_FAILED/);assert.equal(client.view.pending,prior);assert.deepEqual(pageState(client),cursors);assert.deepEqual([...f.rows],saved);assert.deepEqual(totals(),held);const pin=client.renderViewModels(prior,prior[0])[0].pin();pin();
 }finally{if(state)client.state=state;await close(client);}assert.deepEqual(totals(),baseline);
});
test('a superseded pending scan cannot replace a newer complete page or its navigation cursors',async()=>{
 const baseline=totals(),client=fixture(),f=pendingJournal(),gate=deferred(),entered=deferred();client.journal=f.journal;let pending;
 try{await client.listPending();const scan=f.journal.scan;let hold=true;f.journal.scan=async(prefix,visit,options)=>{if(hold){hold=false;visit(structuredClone(f.rows.get('command:032')),'command:032');entered.resolve();await gate.promise;visit(structuredClone(f.rows.get('command:033')),'command:033');return;}return scan(prefix,visit,options);};
  pending=client.listPending('next');await entered.promise;await client.listPending('first');const current=client.view.pending,cursors=pageState(client);gate.resolve();await pending;assert.equal(client.view.pending,current);assert.deepEqual(pageState(client),cursors);assert.deepEqual(pendingIDs(client),Array.from({length:32},(_,i)=>String(i).padStart(3,'0')));assert.equal(f.rows.size,80);assert.deepEqual(f.puts,[]);assert.deepEqual(f.gets,[]);
 }finally{gate.resolve();await pending?.catch(()=>{});await close(client);}assert.deepEqual(totals(),baseline);
});
test('pending page refusal at eight active control reads preserves the prior page without admitting a journal scan',async()=>{
 const baseline=totals(),client=fixture(),f=pendingJournal(),gate=deferred(),readers=[];client.journal=f.journal;
 try{await client.listPending();const prior=client.view.pending,cursors=pageState(client),saved=structuredClone([...f.rows]),scans=f.scans.length;for(let i=0;i<8;i++)readers.push(client.controlReads.run(async()=>gate.promise));await flush();assert.equal(client.controlReads.ownership.controlReads,8);const held=totals();
  await assert.rejects(client.listPending('next'),/COMMAND_RESULT_READ_LIMIT/);assert.equal(client.view.pending,prior);assert.deepEqual(pageState(client),cursors);assert.deepEqual([...f.rows],saved);assert.equal(f.scans.length,scans);assert.deepEqual(totals(),held);assert.equal(client.controlReads.ownership.controlReads,8);
 }finally{gate.resolve();await Promise.allSettled(readers);await close(client);}assert.deepEqual(totals(),baseline);
});
test('retry of an off-page delivery submits its exact saved wire and keeps every journal record',async()=>{
 const baseline=totals(),f=pendingJournal(),id='039',key='command:'+id,saved=f.rows.get(key),requests=[];
 const client=fixture(async(path,init)=>{requests.push({path,method:init?.method??'GET',body:init?.body});return response(init?.method==='POST'?{protocolVersion:1,kind:'receipt',receipt:{commandId:id,status:'rejected',code:'INVALID_INPUT',currentRevision:null,details:{hash:'sha256:'+'0'.repeat(64),byteLength:'2',mediaType:'application/json'}}}:{protocolVersion:1,kind:'unknown',commandId:id});});client.journal=f.journal;
 try{await client.listPending();assert.equal(pendingIDs(client).includes(id),false);await assert.rejects(client.ownedRetry(id),/INVALID_INPUT/);assert.deepEqual(f.gets,[key]);assert.deepEqual(requests,[{path:'/api/v1/commands/'+id,method:'GET',body:undefined},{path:'/api/v1/commands',method:'POST',body:saved.wire}]);assert.notEqual(saved.wire,JSON.stringify(saved.request));assert.equal(f.rows.size,80);assert.equal(f.rows.get(key).wire,saved.wire);assert.deepEqual(f.rows.get(key).request,saved.request);assert.equal(f.rows.get(key).result.receipt.code,'INVALID_INPUT');assert.deepEqual(f.puts,[key]);assert(client.view.pending.length<=32);
 }finally{await close(client);}assert.deepEqual(totals(),baseline);
});
test('an unresolved creation outside the current page blocks duplicate creation until a fresh journal probe confirms its receipt',async()=>{
 const baseline=totals(),client=fixture(),f=pendingJournal(),key='command:039',delivery=f.rows.get(key),created=[],opened=[];delivery.request.command.body={type:'CreateDocument',name:'Original',width:32,height:32,background:{kind:'transparent'}};delivery.wire=JSON.stringify(delivery.request,null,2)+'\n';client.journal=f.journal;
 client.withCommandEvents=async(body,work,document,id)=>{created.push({body,document,id});return work([]);};client.open=async id=>{opened.push(id);};
 try{await client.listPending();assert.equal(client.view.pendingCreate,true);assert.equal(client.view.pending.some(row=>row.request.command.body.type==='CreateDocument'),false);await assert.rejects(client.create(64,48,{name:'Next'}),/creation receipt is unresolved/);assert.deepEqual(created,[]);assert.deepEqual(opened,[]);
  f.rows.set(key,{...delivery,result:{kind:'receipt'}});assert.equal(client.view.pendingCreate,true,'The published flag is intentionally stale until another page read');await client.create(64,48,{name:'Next'});assert.equal(created.length,1);assert.deepEqual(created[0].body,{type:'CreateDocument',name:'Next',width:64,height:48,background:{kind:'transparent'}});assert.equal(created[0].document,null);assert.deepEqual(opened,[created[0].id]);assert.equal(f.rows.get(key).wire,delivery.wire);assert.equal(f.rows.size,80);
 }finally{await close(client);}assert.deepEqual(totals(),baseline);
});
test('an owner change after the real creation probe settles cannot submit a new command',async()=>{
 const baseline=totals(),client=fixture(),f=pendingJournal(),gate=deferred(),entered=deferred(),created=[];client.journal=f.journal;const scan=f.journal.scan,probe=client.unresolvedCreation;
 f.journal.scan=async(...args)=>{entered.resolve();await gate.promise;return scan(...args);};client.unresolvedCreation=async function(){const found=await probe.call(this);assert.equal(found,false);this.lifecycle++;return found;};
 client.withCommandEvents=async()=>{created.push('submitted');};client.open=async()=>{created.push('opened');};const work=client.create(32,32);void work.catch(()=>{});
 try{await entered.promise;assert.deepEqual(created,[]);gate.resolve();await assert.rejects(work,/original command owner changed/i);assert.deepEqual(created,[]);assert.equal(f.rows.size,80);assert.deepEqual(f.puts,[]);assert.deepEqual(f.gets,[]);
 }finally{gate.resolve();await work.catch(()=>{});await close(client);}assert.deepEqual(totals(),baseline);
});
test('checkpoint replaced during actual draft body read cannot cache the old generation',async()=>{const baseline=totals(),gate=deferred();let started=false;const client=fixture(async()=>{started=true;await gate.promise;const body='original';return new Response(body,{headers:{'content-length':String(body.length)}});});client.draftOwner=new DraftPersistence('session',client.session.transport,client.session.csrf);client.draftOwner.checkpoint=checkpoint('1');client.ui=client.draftOwner.checkpoint;const task=client.ownedDraftText('draft');void task.catch(()=>{});try{await flush();assert.equal(started,true);client.draftOwner.checkpoint=checkpoint('2');client.ui=client.draftOwner.checkpoint;gate.resolve();await assert.rejects(task,/cancel|superseded|changed|stale/i);assert.equal(client.draftOwner.drafts.has('draft'),false);assert.equal(client.ui.uiSeq,'2');}finally{gate.resolve();const result=await task.catch(()=>undefined);result?.release();await close(client);}assert.deepEqual(totals(),baseline);});

for(const kind of ['command','retry'])test('dispose drains delayed original journal '+kind+' before closing it or allowing any submission',async()=>{
 const baseline=totals(),gate=deferred(),entered=deferred();let fetched=0,closed=0,recorded;
 const client=fixture(async()=>{fetched++;throw Error('must not submit');});client.restorePending=async()=>{};
 client.journal={async put(_key,value){recorded=value;entered.resolve();await gate.promise;},async get(){entered.resolve();await gate.promise;return {request:{command:{commandId:'original'}},wire:'{}',label:'original'};},close(){closed++;}};
 const task=kind==='command'?client.ownedCommand({type:'Checkpoint',name:'retained'},null):client.ownedRetry('original');void task.catch(()=>{});
 try{await entered.promise;assert.equal(client.controlReads.ownership.controlReads,1);client.dispose();await flush();assert.equal(closed,0,'The captured journal stays open while its admitted entry is pending');gate.resolve();await assert.rejects(task,/original command owner changed|cancel/i);await flush();assert.equal(fetched,0);assert.equal(closed,1);if(kind==='command')assert.equal(recorded.request.command.body.name,'retained');}
 finally{gate.resolve();const result=await task.catch(()=>undefined);result?.release();await close(client);await flush();}assert.deepEqual(totals(),baseline);
});
test('reconnect authority changes during journal admission cannot submit the old command under a replacement session',async()=>{
 const baseline=totals(),gate=deferred(),entered=deferred();let fetched=0,oldWrites=0,newWrites=0;
 const client=fixture(async()=>{fetched++;throw Error('unexpected');});client.restorePending=async()=>{};client.journal={async put(){oldWrites++;entered.resolve();await gate.promise;}};
 const task=client.ownedCommand({type:'Checkpoint',name:'original'},null);void task.catch(()=>{});
 try{await entered.promise;client.lifecycle++;client.session={...client.session,identity:()=> 'replacement'};client.owner='replacement';client.journal={async put(){newWrites++;}};const drain=client.controlReads.release();gate.resolve();await assert.rejects(task,/original command owner changed|cancel/i);await drain;assert.equal(oldWrites,1);assert.equal(newWrites,0);assert.equal(fetched,0);}
 finally{gate.resolve();const result=await task.catch(()=>undefined);result?.release();await close(client);}assert.deepEqual(totals(),baseline);
});
test('request review snapshots its body before a deferred flush and retains result ownership',async()=>{
 const baseline=totals(),gate=deferred(),client=fixture();let delivered;client.patch({ready:true});client.uiTail=Promise.resolve();client.flushDrafts=()=>gate.promise;
 client.draftOwner=new DraftPersistence('session',async()=>{throw Error('unexpected');},()=> 'csrf');client.draftOwner.checkpoint=checkpoint('1');client.ui=client.draftOwner.checkpoint;
 client.draftOwner.ownedDispatch=async value=>{delivered=structuredClone(value);return createOwnedModel('fixture-review-receipt',512,()=>({protocolVersion:1,requestId:value.requestId,status:'accepted',uiSeq:'2',reason:null}));};
 const input={type:'PrepareRequestReview',draftId:'draft',generation:'1'},task=client.ownedRequestReview(input);let result;void task.catch(()=>{});
 try{input.draftId='mutated';input.generation='9';await flush();assert.equal(delivered,undefined);gate.resolve();result=await task;assert.equal(delivered.body.draftId,'draft');assert.equal(delivered.body.generation,'1');assert.equal(result.value.status,'accepted');}
 finally{gate.resolve();result?.release();await task.catch(()=>{});await close(client);}assert.deepEqual(totals(),baseline);
});
test('request review cannot dispatch a captured body after owner change while flush is deferred',async()=>{
 const baseline=totals(),gate=deferred(),client=fixture();let dispatched=0;client.patch({ready:true});client.uiTail=Promise.resolve();client.flushDrafts=()=>gate.promise;
 client.draftOwner=new DraftPersistence('session',async()=>{throw Error('unexpected');},()=> 'csrf');client.draftOwner.checkpoint=checkpoint('1');client.ui=client.draftOwner.checkpoint;client.draftOwner.ownedDispatch=async()=>{dispatched++;throw Error('must not dispatch');};
 const task=client.ownedRequestReview({type:'PrepareRequestReview',draftId:'draft',generation:'1'});void task.catch(()=>{});
 try{await flush();client.lifecycle++;const drain=client.controlReads.release();gate.resolve();await assert.rejects(task,/original command owner changed|cancel/i);await drain;assert.equal(dispatched,0);}
 finally{gate.resolve();const result=await task.catch(()=>undefined);result?.release();await close(client);}assert.deepEqual(totals(),baseline);
});
