import {specReceipt} from './receipt-path.js';
import {test,expect,click} from './integration-fixture.js';
import {mkdtemp,realpath,mkdir,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {serverProcess} from './process.js';
import {ownedOPFS} from './owned-opfs.js';
import {recordDOMErrors} from './error-monitor.js';
import {observeDisplayAborts} from './display-aborts.js';
// @ts-ignore Shared exact Composition transport classifications.
import {expectedCompositionCancellation} from './composition-network.mjs';
// @ts-ignore Dedicated test-only original observation and durable-byte witnesses.
import {acceptedComposition,commandWitness,draftWitness,originalHold,assessSaveControl,publicShortcutFocus,assertShortcutFocus,downloadIdentity,originalResponse,observeSaveEdit} from './composition-save-witness.mjs';
// @ts-ignore Existing independent cleanup, unchanged.
import {independentSteps} from './completion/boundary.mjs';
// @ts-ignore Existing partial acquisition cleanup, unchanged.
import {acquireOwnedSetup} from './completion/setup-owned.mjs';

const RAW='{"compositional_deconstruction":{"background":"","elements":[]},"high_level_description":"Original raw"}';
test('public Scene edit saves the current model during original raw inspection',async({page,context,browserName})=>{
 const out=specReceipt(import.meta.url),dir=await mkdtemp(join(await realpath(tmpdir()),'p1c6-composition-save-')),root=join(dir,'private');await mkdir(out,{recursive:true});
 const result:any={started:new Date().toISOString(),root,browserName,rawExpected:RAW,intended:'Unapplied semantic branch draft',observationErrors:[],requests:[],responses:[],terminals:[],commands:[],uiRequests:[],workers:[],cleanup:{passed:false,failures:[]}};
 const ids=new WeakMap<any,number>();let sequence=0;const id=(r:any)=>{if(!ids.has(r))ids.set(r,++sequence);return ids.get(r)!;};
 let stage='setup',hold:any,server:any,guard:any,dom:any=[],primary:any,admitted=false,displayAborts:Awaited<ReturnType<typeof observeDisplayAborts>>|undefined;const pending:Promise<unknown>[]=[];
 context.on('request',r=>{result.requests.push({id:id(r),url:r.url(),method:r.method(),stage,at:Date.now()});const u=new URL(r.url());if(r.method()==='POST'&&u.pathname==='/api/v1/commands')result.commands.push({id:id(r),command:r.postDataJSON().command,stage});if(r.method()==='POST'&&/^\/api\/v1\/ui\/[^/]+$/.test(u.pathname))result.uiRequests.push({id:id(r),request:r.postDataJSON(),stage,at:Date.now()});});
 context.on('response',r=>{result.responses.push({requestId:id(r.request()),url:r.url(),method:r.request().method(),status:r.status(),sameRequest:true,contentType:r.headers()['content-type'],contentLength:r.headers()['content-length'],etag:r.headers()['etag'],entityVersion:r.headers()['x-app-entity-version']});if(r.status()>=400&&new URL(r.url()).pathname!=='/favicon.ico')result.observationErrors.push('HTTP '+r.status()+' '+r.url());});
 context.on('requestfinished',r=>result.terminals.push({requestId:id(r),kind:'finished',url:r.url()}));context.on('requestfailed',r=>result.terminals.push({channel:'requestfailed',requestId:id(r),kind:'failed',phase:stage,url:r.url(),method:r.method(),resourceType:r.resourceType(),failure:r.failure(),response:result.responses.find((x:any)=>x.requestId===id(r))??null}));
 page.on('worker',w=>result.workers.push({url:w.url(),at:Date.now()}));page.on('pageerror',e=>result.observationErrors.push(String(e)));page.on('console',m=>{if(m.type()==='error'&&!m.location().url.endsWith('/favicon.ico'))result.observationErrors.push(m.text());});
 try{
  const owned=await acquireOwnedSetup([['context',async()=>context,async(c:any)=>c.close()],['server',async()=>serverProcess(root),async(s:any)=>s.close()],['guard',async()=>ownedOPFS(context,'p1c6-composition-save-'+browserName)]]) as {server:Awaited<ReturnType<typeof serverProcess>>;guard:Awaited<ReturnType<typeof ownedOPFS>>};server=owned.server;guard=owned.guard;dom=await recordDOMErrors(context);displayAborts=await observeDisplayAborts(context,id);await guard.admit(page,server.origin);admitted=true;await page.goto(await server.pair());await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();
  await click(page,'New');for(const [name,value]of [['Width (px)','360'],['Height (px)','200']]){const f=page.getByRole('spinbutton',{name,exact:true});await f.fill(value);await f.press('Tab');}await click(page,'Create');await expect(page.getByRole('dialog',{name:'New document',exact:true})).toBeHidden();await page.getByRole('radio',{name:'Composition',exact:true}).press('Space');const scene=page.getByRole('textbox',{name:'Scene',exact:true});await expect(scene).toBeVisible();await scene.fill('Original raw');
  await click(page,'Raw caption inspection and Convert copy');await page.getByRole('textbox',{name:'Raw caption to retain',exact:true}).fill(RAW);await click(page,'Retain and inspect raw');await expect(page.getByText('Original bytes retained separately. Inspection grants no authoring authority.',{exact:true})).toBeVisible();await click(page,'Apply Composition');await expect(page.getByText('Composition applied and saved locally.',{exact:true})).toBeVisible();await expect(scene).toHaveValue('Original raw');await expect(page.getByRole('textbox',{name:'Immutable raw byte page',exact:true})).toHaveValue(RAW);
  const commits=result.commands.filter((x:any)=>x.command.body.type==='CommitCompositionVersion');expect(commits).toHaveLength(1);const commit=commits[0].command;result.acceptedBefore=acceptedComposition(root,commit);expect(result.acceptedBefore.raw.text).toBe(RAW);const revision=String(BigInt(result.acceptedBefore.document.revision)+1n),url=server.origin+'/api/v1/documents/'+commit.documentId+'/composition?revision='+revision+'&raw=0&offset=0';result.owner={clientId:commit.clientId,sessionId:commit.sessionId,documentId:commit.documentId,revision,width:360,height:200};
  await page.route(url,async route=>{let owns=false;try{if(hold)throw Error('Duplicate held raw request');hold=originalHold(route,{url,origin:server.origin,documentId:commit.documentId,revision,page,frame:page.mainFrame()});owns=true;await hold.completion;}catch(e){result.observationErrors.push(String(e));if(!owns)await route.continue().catch(x=>result.observationErrors.push(String(x)));}});
  stage='checkpoint';const status=page.getByRole('region',{name:'Operation status',exact:true});await expect(status).toBeVisible();await status.focus();await expect(status).toBeFocused();result.shortcutFocus=await status.evaluate(publicShortcutFocus);assertShortcutFocus(result.shortcutFocus);await page.keyboard.press(process.platform==='darwin'?'Meta+s':'Control+s');await expect.poll(()=>!!hold,{message:'One original accepted-document raw inspection is held'}).toBe(true);result.held=hold.record;result.held.requestId=id(hold.request);const checkpoints=result.commands.filter((x:any)=>x.stage==='checkpoint'&&x.command.body.type==='SaveCheckpoint');expect(checkpoints).toHaveLength(1);const checkpoint=checkpoints[0].command;result.checkpoint=commandWitness(root,checkpoint);expect(result.checkpoint.document.revision).toBe(revision);expect(checkpoint.documentId).toBe(commit.documentId);expect(checkpoint.clientId).toBe(commit.clientId);expect(checkpoint.sessionId).toBe(commit.sessionId);await expect(scene).toBeEditable();const rawField=page.getByRole('textbox',{name:'Immutable raw byte page',exact:true});
  await page.evaluate(documentId=>{const rows:any[]=[];(window as any).__compositionPublicInputs=rows;document.addEventListener('input',e=>{const input=e.composedPath().find(x=>x instanceof HTMLTextAreaElement) as HTMLTextAreaElement|undefined;const host=e.composedPath().find(x=>x instanceof HTMLElement&&x.id==='composition-scene');if(input&&host)rows.push({trusted:e.isTrusted,value:input.value,at:Date.now(),documentId});},true);},commit.documentId);
  let save:any,downloadPromise:any;
  const downloadURL=server.origin+'/api/v1/documents/'+commit.documentId+'/composition?revision='+revision+'&raw=0&download=1',downloadExpected={url:downloadURL,origin:server.origin,documentId:commit.documentId,revision,page,frame:page.mainFrame()};
  await observeSaveEdit(result,{
   edit:async()=>{stage='edit';await scene.fill(result.intended);const edits=await page.evaluate(()=>(window as any).__compositionPublicInputs);expect(edits).toHaveLength(1);result.edit=edits[0];},
   empty:async()=>{await expect(rawField).toHaveValue('');result.rawEmpty={value:await rawField.inputValue(),at:Date.now(),held:hold.record.releasedAt===null};},
   before:async()=>{const saves=()=>result.uiRequests.filter((x:any)=>x.stage==='edit'&&x.request.body.type==='SaveDraft'&&x.request.body.draft.kind==='composition'&&x.request.body.draft.documentId===commit.documentId&&x.request.body.draft.expectedDocumentRevision===revision);await expect.poll(()=>saves().length,{message:'The trusted Scene edit creates its original SaveDraft'}).toBe(1);save=saves()[0];await expect.poll(()=>result.responses.some((x:any)=>x.requestId===save.id&&x.status===200)).toBe(true);result.before=draftWitness(root,result.owner,save.request);result.beforeAt=Date.now();result.beforeObservedHeld=hold.record.releasedAt===null;result.beforePublicValue=await scene.inputValue();},
   release:async()=>{downloadPromise=page.waitForResponse(r=>r.request().url()===downloadURL);downloadPromise.catch(()=>{});hold.release();await hold.completion;},
   raw:async()=>{const response=await hold.request.response();expect(response).not.toBeNull();result.raw=await originalResponse(hold.request,response!);const download=await downloadPromise,downloadRequest=download.request();result.download={...downloadIdentity(downloadRequest,downloadExpected),requestId:id(downloadRequest),requestAt:result.requests.find((x:any)=>x.id===id(downloadRequest)).at,...await originalResponse(downloadRequest,download)};expect(result.requests.filter((x:any)=>x.url===downloadURL)).toHaveLength(1);await expect.poll(()=>result.terminals.some((x:any)=>x.requestId===id(downloadRequest)&&x.kind==='finished')).toBe(true);},
   fresh:async()=>{await expect(rawField).toHaveValue(RAW);result.rawFresh={value:await rawField.inputValue(),at:Date.now()};},
   after:async()=>{result.after=draftWitness(root,result.owner,save.request);result.afterAt=Date.now();result.afterPublicValue=await scene.inputValue();result.acceptedAfter=acceptedComposition(root,commit,checkpoint);result.unexpectedWorkers=result.workers.length;}
  });
 }catch(e){primary=e;result.primary={message:String(e),stack:(e as Error).stack};}
 finally{
  stage='teardown';
  const failures=result.cleanup.failures;
  await independentSteps([['release-original-hold',async()=>{if(hold){hold.release();await hold.completion;}}],['effect-sample',async()=>{if(server){result.effects=await server.effects();expect(Object.keys(result.effects)).toHaveLength(8);expect(Object.values(result.effects)).toEqual(Array(8).fill(0));}}],['original-read-observations',async()=>{if(displayAborts&&!page.isClosed())await displayAborts.flush(page);}],['page-departure',async()=>{for(const p of context.pages())await p.goto('about:blank');}],['owned-storage',async()=>{if(admitted){await guard.cleanup();guard.verify();result.guard=guard.ledger;}}],['context-close',async()=>{await context.close();result.cleanup.contextClosed=true;}],['server-close',async()=>{if(server){await server.close();result.cleanup.serverClosed=true;}}],['observation-work',async()=>{await Promise.all(pending);}]],failures);
  result.displayAborts=displayAborts?.()??[];result.displayAbortObservations=displayAborts?.observations()??null;if(result.displayAbortObservations?.errors.length)result.observationErrors.push('Original request observation failed');result.domErrors=dom;result.unexpectedWorkers=result.workers.length;result.observationErrors.push(...dom.map((x:any)=>JSON.stringify(x)));result.classifications=result.terminals.filter((x:any)=>x.kind==='failed').map((x:any)=>({requestId:x.requestId,reason:server?expectedCompositionCancellation(x,server.origin,browserName,[],result.displayAborts):false}));const unexpected=result.classifications.filter((x:any)=>!x.reason);result.unexpectedTerminals=unexpected;if(unexpected.length)result.observationErrors.push('Unqualified original request failures');result.cleanup.passed=failures.length===0&&!!result.cleanup.contextClosed&&!!result.cleanup.serverClosed&&admitted;result.shutdown=server?.shutdown;result.lifecycle=server?.lifecycle;
  if(!primary)try{result.assessment=assessSaveControl(result);}catch(e){result.assessmentError=String(e);primary=e;}
  result.ended=new Date().toISOString();await writeFile(join(out,'result.json'),JSON.stringify(result,null,2));
 }
 if(primary)throw primary;expect(result.cleanup.passed).toBe(true);expect(result.assessment.kind,'Original intended Scene must reach the exact saved graph before and after raw response').toBe('GREEN');
});
