import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,chmodSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import {canonical,hashBytes} from '../../dist/local/server/storage/canonical.js';
import {emptyComposition} from '../../dist/local/src/composition/core.js';
import {draftWitness,commandWitness,rawIdentity,originalHold,assessSaveControl,publicShortcutFocus,assertShortcutFocus,downloadIdentity,originalResponse,observeSaveEdit} from './composition-save-witness.mjs';
const base=resolve(process.env.EDITOR_RECEIPT,'composition-observer-controls');mkdirSync(base,{recursive:true});
const seed=JSON.parse(readFileSync(new URL('./completion/busy-state312.json',import.meta.url)));
function fixture(){
 const root=mkdtempSync(join(base,'case-'));chmodSync(root,0o700);const db=new DatabaseSync(join(root,'metadata.sqlite'));db.exec('CREATE TABLE ui_receipts(client_id TEXT,id TEXT,hash TEXT,json TEXT);CREATE TABLE ui_events(client_id TEXT,session_id TEXT,seq TEXT,json TEXT);CREATE TABLE ui_checkpoints(client_id TEXT,session_id TEXT,json TEXT);CREATE TABLE assets(id TEXT,json TEXT);CREATE TABLE documents(id TEXT,json TEXT);CREATE TABLE commands(id TEXT,original TEXT,receipt TEXT)');
 const put=value=>{const text=typeof value==='string'?value:canonical(value),ref={hash:hashBytes(text),byteLength:String(Buffer.byteLength(text)),mediaType:'application/json'},dir=join(root,'objects','sha256',ref.hash.slice(7,9));mkdirSync(dir,{recursive:true,mode:0o700});for(const d of [join(root,'objects'),join(root,'objects','sha256'),dir])chmodSync(d,0o700);writeFileSync(join(dir,ref.hash.slice(7)),text,{mode:0o600});return ref;};
 const owner={clientId:seed.created.clientId,sessionId:seed.created.sessionId,documentId:seed.created.documentId,revision:'1',width:360,height:200},graph={composition:emptyComposition(360,200,randomUUID()),bindings:{},view:'composition'};graph.composition.scene='Original raw';const descriptor={schemaVersion:1,kind:'composition-draft-1',graph:put(graph),raw:[],bindings:{}},asset={id:randomUUID(),blob:put(descriptor)};
 const request={protocolVersion:1,requestId:randomUUID(),sessionId:owner.sessionId,expectedUISeq:'0',body:{type:'SaveDraft',draft:{id:randomUUID(),generation:'1',kind:'composition',documentId:owner.documentId,targetLayerId:null,expectedDocumentRevision:'1',assetId:asset.id,composing:false}}},receipt={protocolVersion:1,requestId:request.requestId,status:'accepted',uiSeq:'1'},checkpoint={sessionId:owner.sessionId,uiSeq:'1',drafts:[{...request.body.draft,status:'saved-unapplied'}]};
 const update=()=>{db.exec('DELETE FROM ui_receipts;DELETE FROM ui_events;DELETE FROM ui_checkpoints;DELETE FROM assets');db.prepare('INSERT INTO ui_receipts VALUES(?,?,?,?)').run(owner.clientId,request.requestId,hashBytes(canonical(request)),canonical(receipt));db.prepare('INSERT INTO ui_events VALUES(?,?,?,?)').run(owner.clientId,owner.sessionId,'1',canonical(request.body));db.prepare('INSERT INTO ui_checkpoints VALUES(?,?,?)').run(owner.clientId,owner.sessionId,canonical(checkpoint));db.prepare('INSERT INTO assets VALUES(?,?)').run(asset.id,canonical(asset));};update();db.prepare('INSERT INTO documents VALUES(?,?)').run(seed.document.id,canonical(seed.document));db.prepare('INSERT INTO commands VALUES(?,?,?)').run(seed.created.commandId,JSON.stringify({protocolVersion:1,command:seed.created}),JSON.stringify(seed.receipt));
 return {root,db,owner,graph,descriptor,asset,request,receipt,checkpoint,put,update,read:()=>draftWitness(root,owner,request),close:()=>db.close()};
}
test('actual durable witness binds original request/receipt/checkpoint/descriptor/full canonical graph',()=>{const f=fixture();try{const r=f.read();assert.equal(r.graph.value.composition.scene,'Original raw');assert.equal(r.graph.sha256,f.descriptor.graph.hash);assert.deepEqual(commandWitness(f.root,seed.created).document,seed.document);}finally{f.close();}});
const mutations={missingReceipt:f=>f.db.exec('DELETE FROM ui_receipts'),duplicateReceipt:f=>f.db.exec('INSERT INTO ui_receipts SELECT * FROM ui_receipts'),receiptHash:f=>f.db.exec("UPDATE ui_receipts SET hash='wrong'"),wrongClient:f=>f.owner.clientId='foreign',wrongSession:f=>f.owner.sessionId='foreign',wrongDocument:f=>f.owner.documentId='foreign',wrongRevision:f=>f.owner.revision='9',wrongKind:f=>f.request.body.draft.kind='text',wrongComposing:f=>f.request.body.draft.composing=true,missingEvent:f=>f.db.exec('DELETE FROM ui_events'),foreignEvent:f=>f.db.exec("UPDATE ui_events SET json='{}'"),missingCheckpoint:f=>f.db.exec('DELETE FROM ui_checkpoints'),duplicateCheckpoint:f=>f.db.exec('INSERT INTO ui_checkpoints SELECT * FROM ui_checkpoints'),wrongDraft:f=>{f.checkpoint.drafts[0].id=randomUUID();f.update();},wrongGeneration:f=>{f.checkpoint.drafts[0].generation='2';f.update();},appliedDraft:f=>{f.checkpoint.drafts[0].status='applied';f.update();},missingAsset:f=>f.db.exec('DELETE FROM assets'),duplicateAsset:f=>f.db.exec('INSERT INTO assets SELECT * FROM assets'),corruptHash:f=>{f.asset.blob.hash='sha256:'+'0'.repeat(64);f.update();},wrongLength:f=>{f.asset.blob.byteLength='1';f.update();},graphBOM:f=>{f.descriptor.graph=f.put('\ufeff'+canonical(f.graph));f.asset.blob=f.put(f.descriptor);f.update();},noncanonical:f=>{f.descriptor.graph=f.put(JSON.stringify(f.graph,null,2));f.asset.blob=f.put(f.descriptor);f.update();},invalidGraph:f=>{f.graph.composition.kind='bad';f.descriptor.graph=f.put(f.graph);f.asset.blob=f.put(f.descriptor);f.update();},wrongFrame:f=>f.owner.width=361};
for(const [name,change]of Object.entries(mutations))test('actual durable witness refuses '+name,()=>{const f=fixture();try{change(f);assert.throws(f.read);}finally{f.close();}});
function holdFixture(){const page={},frame={page:()=>page},expected={origin:'http://127.0.0.1:12345',documentId:'doc',revision:'2',page,frame,url:'http://127.0.0.1:12345/api/v1/documents/doc/composition?revision=2&raw=0&offset=0'},request={method:()=> 'GET',url:()=>expected.url,frame:()=>frame,redirectedFrom:()=>null};let calls=0;return {page,frame,expected,request,route:{request:()=>request,continue:async()=>{calls++;}},calls:()=>calls};}
test('actual route hold continues the exact request once even if finally releases twice',async()=>{const f=holdFixture(),h=originalHold(f.route,f.expected);assert.equal(f.calls(),0);h.release();h.release();await h.completion;assert.equal(f.calls(),1);assert.equal(h.request,f.request);assert.equal(h.record.continueError,null);});
for(const name of ['method','url','frame','redirectedFrom'])test('original hold refuses wrong '+name,()=>{const f=holdFixture();f.request[name]=()=>name==='frame'?{}:name==='redirectedFrom'?{}:'foreign';assert.throws(()=>rawIdentity(f.request,f.expected));assert.equal(f.calls(),0);});
test('actual hold preserves continuation failure without second request',async()=>{const f=holdFixture();let calls=0;f.route.continue=async()=>{calls++;throw Error('injected transport refusal');};const h=originalHold(f.route,f.expected);h.release();await assert.rejects(h.completion);assert.equal(calls,1);assert.match(h.record.continueError,/injected/);});
function assessment(f){const before=f.read(),after=f.read();return {held:{originalRequest:true,originalFrame:true,originalPage:true,requestId:1,heldAt:1,releasedAt:4,continuedAt:5,continueError:null},edit:{trusted:true,value:'Desired',at:2,documentId:f.owner.documentId},intended:'Desired',owner:f.owner,raw:{status:200,sameRequest:true,finished:null,text:'{}',bytes:2,sha256:hashBytes('{}'),completedAt:5},rawExpected:'{}',shortcutFocus:goodFocus(),checkpoint:{command:{...f.owner,body:{type:'SaveCheckpoint'}},receipt:{documentRevision:f.owner.revision},document:{revision:f.owner.revision}},actionSequence:['edit','empty','before','release','raw','fresh','after'].flatMap(n=>['start:'+n,'done:'+n]),heldChecks:['edit','edited','empty','empty-observed','before','before-saved','release'].map(phase=>({phase,releasedAt:null})),rawEmpty:{value:'',at:3,held:true},download:{originalRequest:true,originalFrame:true,originalPage:true,requestId:2,requestAt:4,documentId:f.owner.documentId,revision:f.owner.revision,status:200,sameRequest:true,finished:null,text:'{}',bytes:2,sha256:hashBytes('{}'),completedAt:5},rawFresh:{value:'{}',at:6},beforePublicValue:'Desired',afterPublicValue:'Desired',before,after,beforeObservedHeld:true,beforeAt:3,afterAt:6,cleanup:{passed:true},observationErrors:[],unexpectedWorkers:0,acceptedBefore:{composition:{value:{scene:'Original raw'},sha256:'same'}},acceptedAfter:{composition:{value:{scene:'Original raw'},sha256:'same'}}};}
test('actual assessor labels exact injected loss RED, never application PASS or historical cause',()=>{const f=fixture();try{const r=assessSaveControl(assessment(f));assert.equal(r.kind,'VERIFIED-RED');assert.equal(r.applicationAssertionPassed,false);assert.equal(r.historical322CauseProved,false);}finally{f.close();}});
test('actual assessor labels same intended durable graph GREEN',()=>{const f=fixture();try{f.graph.composition.scene='Desired';f.descriptor.graph=f.put(f.graph);f.asset.blob=f.put(f.descriptor);f.update();assert.equal(assessSaveControl(assessment(f)).kind,'GREEN');}finally{f.close();}});
for(const [name,mutate]of Object.entries({untrusted:x=>x.edit.trusted=false,wrongPublicValue:x=>x.edit.value='wrong',foreignEdit:x=>x.edit.documentId='foreign',notHeld:x=>x.beforeObservedHeld=false,earlyRelease:x=>x.held.releasedAt=2,missingRelease:x=>x.held.releasedAt=null,continuationError:x=>x.held.continueError='failed',foreignResponse:x=>x.raw.sameRequest=false,failedResponse:x=>x.raw.finished='aborted',wrongRawBytes:x=>x.raw.text='bad',wrongHash:x=>x.raw.sha256='bad',foreignDraft:x=>x.after.selected.id='foreign',lateGeneration:x=>x.after.selected.generation='2',foreignRequest:x=>x.after.request.requestId='foreign',postReleaseChanged:x=>x.after.graph.sha256='different',cleanupFailed:x=>x.cleanup.passed=false,lateError:x=>x.observationErrors.push('late'),unexpectedWorker:x=>x.unexpectedWorkers=1,acceptedChanged:x=>x.acceptedAfter.composition.sha256='changed'}))test('actual assessment refuses '+name,()=>{const f=fixture();try{const x=assessment(f);mutate(x);assert.throws(()=>assessSaveControl(x));}finally{f.close();}});

function goodFocus(){return {tag:'SECTION',label:'Operation status',tabIndex:0,active:true,connected:true,visible:true,editable:false,at:0};}
test('actual public focus witness accepts the original non-editable active status region',()=>{const doc={},node={tagName:'SECTION',tabIndex:0,isConnected:true,isContentEditable:false,ownerDocument:doc,getAttribute:()=> 'Operation status',getBoundingClientRect:()=>({width:100,height:40}),matches:()=>false};doc.activeElement=node;const x=publicShortcutFocus(node);assertShortcutFocus(x);doc.activeElement={};assert.throws(()=>assertShortcutFocus(publicShortcutFocus(node)));doc.activeElement=node;node.isContentEditable=true;assert.throws(()=>assertShortcutFocus(publicShortcutFocus(node)));});
for(const [key,value] of Object.entries({tag:'TEXTAREA',label:'Other',tabIndex:-1,active:false,connected:false,visible:false,editable:true}))test('actual focus assessor rejects '+key,()=>{const x=goodFocus();x[key]=value;assert.throws(()=>assertShortcutFocus(x));});
function downloadFixture(){const f=holdFixture();f.expected.url=f.expected.url.replace('offset=0','download=1');return f;}
test('actual follow-up identity binds original same-frame request without fetching',()=>{const f=downloadFixture();assert.equal(downloadIdentity(f.request,f.expected).revision,'2');assert.equal(f.calls(),0);});
for(const name of ['method','url','frame','redirectedFrom'])test('actual follow-up refuses '+name,()=>{const f=downloadFixture();f.request[name]=()=>name==='frame'?{}:name==='redirectedFrom'?{}:'foreign';assert.throws(()=>downloadIdentity(f.request,f.expected));});
for(const bad of ['query','revision','documentId','origin','page'])test('actual follow-up refuses expected '+bad,()=>{const f=downloadFixture();if(bad==='query')f.expected.url=f.expected.url.replace('download=1','offset=0');else f.expected[bad]=bad==='page'?{}:'foreign';assert.throws(()=>downloadIdentity(f.request,f.expected));});
test('actual original response consumes original body and finished only once',async()=>{const request={};let reads=0,ends=0;const response={request:()=>request,status:()=>200,body:async()=>{reads++;return Buffer.from('{}');},finished:async()=>{ends++;return null;}};const x=await originalResponse(request,response);assert.equal(x.bytes,2);assert.equal(reads,1);assert.equal(ends,1);});
for(const bad of ['foreign','status','body','terminal'])test('actual original response refuses '+bad,async()=>{const request={},response={request:()=>bad==='foreign'?{}:request,status:()=>bad==='status'?503:200,body:async()=>{if(bad==='body')throw Error('incomplete');return Buffer.from('{}');},finished:async()=>bad==='terminal'?'aborted':null};await assert.rejects(()=>originalResponse(request,response));});
const freshMutations={staleEmpty:x=>x.rawEmpty.value='{}',emptyAfterRelease:x=>x.rawEmpty.at=5,emptyBeforeEdit:x=>{[x.actionSequence[0],x.actionSequence[2]]=[x.actionSequence[2],x.actionSequence[0]];},unheldEmpty:x=>x.rawEmpty.held=false,foreignDownload:x=>x.download.originalRequest=false,foreignDownloadFrame:x=>x.download.originalFrame=false,foreignDownloadPage:x=>x.download.originalPage=false,downloadDocument:x=>x.download.documentId='foreign',downloadRevision:x=>x.download.revision='foreign',reusedRequest:x=>x.download.requestId=1,earlyDownload:x=>x.download.requestAt=3,failedDownload:x=>x.download.finished='aborted',wrongDownloadBytes:x=>x.download.text='bad',wrongDownloadHash:x=>x.download.sha256='bad',wrongDownloadLength:x=>x.download.bytes=3,earlyFresh:x=>x.rawFresh.at=4,staleFresh:x=>x.rawFresh.value='',earlyAfter:x=>x.afterAt=5,wrongCheckpoint:x=>x.checkpoint.command.body.type='Other',wrongCheckpointDocument:x=>x.checkpoint.command.documentId='foreign',wrongCheckpointRevision:x=>x.checkpoint.receipt.documentRevision='foreign'};
for(const [name,mutate]of Object.entries(freshMutations))test('actual assessor refuses fresh-render gap '+name,()=>{const f=fixture();try{const x=assessment(f);mutate(x);assert.throws(()=>assessSaveControl(x));}finally{f.close();}});
for(const key of ['beforePublicValue','afterPublicValue'])test('durable intended graph cannot qualify GREEN with stale '+key,()=>{const f=fixture();try{f.graph.composition.scene='Desired';f.descriptor.graph=f.put(f.graph);f.asset.blob=f.put(f.descriptor);f.update();const x=assessment(f);x[key]='Original raw';assert.throws(()=>assessSaveControl(x),/GREEN/);}finally{f.close();}});

function actionFixture(){
 const x={held:{releasedAt:null},intended:'Desired',owner:{documentId:'document'},rawExpected:'RAW'},calls=[];let display='RAW',edited=false;
 const actions={
  edit:async()=>{calls.push('edit');edited=true;display='';x.edit={trusted:true,value:'Desired',documentId:'document',at:123};},
  empty:async()=>{calls.push('empty');assert(edited,'A public edit is required before waiting for empty');assert.equal(display,'');x.rawEmpty={value:display,held:x.held.releasedAt===null};},
  before:async()=>{calls.push('before');assert(edited);},
  release:async()=>{calls.push('release');x.held.releasedAt=456;},
  raw:async()=>{calls.push('raw');assert.notEqual(x.held.releasedAt,null);display='RAW';},
  fresh:async()=>{calls.push('fresh');x.rawFresh={value:display};},
  after:async()=>{calls.push('after');assert.equal(display,'RAW');}
 };
 return {x,actions,calls};
}
test('same live action helper edits before empty wait and keeps original hold through saved evidence',async()=>{const f=actionFixture();await observeSaveEdit(f.x,f.actions);assert.deepEqual(f.calls,['edit','empty','before','release','raw','fresh','after']);assert.deepEqual(f.x.actionSequence,f.calls.flatMap(n=>['start:'+n,'done:'+n]));assert.equal(f.x.heldChecks.length,7);});
test('public stand-in with old RAW deterministically rejects the old empty-before-edit driver',async()=>{const f=actionFixture();await assert.rejects(f.actions.empty,/public edit/);assert.deepEqual(f.calls,['empty']);assert.equal(f.x.edit,undefined);assert.equal(f.x.held.releasedAt,null);});
for(const [name,change]of Object.entries({absentEdit:f=>{f.actions.edit=async()=>{};},untrusted:f=>{const edit=f.actions.edit;f.actions.edit=async()=>{await edit();f.x.edit.trusted=false;};},foreignEdit:f=>{const edit=f.actions.edit;f.actions.edit=async()=>{await edit();f.x.edit.documentId='foreign';};},wrongEdit:f=>{const edit=f.actions.edit;f.actions.edit=async()=>{await edit();f.x.edit.value='wrong';};},earlyRelease:f=>{f.x.held.releasedAt=1;},releaseDuringEdit:f=>{const edit=f.actions.edit;f.actions.edit=async()=>{await edit();f.x.held.releasedAt=1;};},emptyAfterRelease:f=>{const empty=f.actions.empty;f.actions.empty=async()=>{await empty();f.x.held.releasedAt=1;};},staleEmpty:f=>{const empty=f.actions.empty;f.actions.empty=async()=>{await empty();f.x.rawEmpty.value='RAW';};},releaseDuringSave:f=>{f.actions.before=async()=>{f.x.held.releasedAt=1;};},noRelease:f=>{f.actions.release=async()=>{};},staleFresh:f=>{f.actions.fresh=async()=>{f.x.rawFresh={value:''};};}}))test('same live action helper refuses '+name,async()=>{const f=actionFixture();change(f);await assert.rejects(()=>observeSaveEdit(f.x,f.actions));assert(!f.x.actionSequence.includes('done:after'));});
test('same live action helper refuses an already-started sequence',async()=>{const f=actionFixture();f.x.actionSequence=[];await assert.rejects(()=>observeSaveEdit(f.x,f.actions));assert.deepEqual(f.calls,[]);});

// Failure-only authoring witness controls. These fixture rows are synthetic;
// they do not explain or reclassify the original hosted properties failure.
import {createAuthoringCommandWitness,readAuthoringCommandSnapshot,AUTHORING_DIAGNOSTIC_LIMITS} from './authoring-command-witness.mjs';
function authoringFixture(){
 const root=mkdtempSync(join(base,'authoring-failure-'));chmodSync(root,0o700);
 const db=new DatabaseSync(join(root,'metadata.sqlite'));db.exec('PRAGMA journal_mode=WAL;CREATE TABLE commands(id TEXT,original TEXT,receipt TEXT);CREATE TABLE history_preparations(id TEXT,original TEXT,operation_id TEXT,phase TEXT)');
 const command={...seed.created,commandId:randomUUID(),transactionId:randomUUID(),body:{type:'SetLayerProperties',layerId:randomUUID(),layerVersion:'2',properties:{visible:true},draft:{sessionId:seed.created.sessionId,draftId:'inspector_selected',generation:'2'}}},wire=JSON.stringify({protocolVersion:1,command}),operationId=randomUUID();
 const accepted={status:'accepted',commandId:command.commandId,transactionId:command.transactionId,documentRevision:'8',fromSeq:'20',toSeq:'21'},rejected={status:'rejected',commandId:command.commandId,code:'STALE_REVISION',currentRevision:'8'};
 return {root,db,command,wire,operationId,accepted,rejected,pending(phase='preparing'){db.prepare('INSERT INTO history_preparations VALUES(?,?,?,?)').run(command.commandId,wire,operationId,phase);},terminal(receipt=accepted){db.prepare('INSERT INTO commands VALUES(?,?,?)').run(command.commandId,wire,JSON.stringify(receipt));},close:()=>db.close()};
}
for(const phase of ['preparing','waiting-for-resources'])test('post-failure authoring witness binds exact original pending '+phase,()=>{const f=authoringFixture();try{f.pending(phase);const r=readAuthoringCommandSnapshot(f.root,f.wire);assert.equal(r.status,'pending');assert.deepEqual(r.pending,{commandId:f.command.commandId,operationId:f.operationId,phase});assert.equal(r.closed,true);assert.ok(r.endedAt>=r.startedAt);assert.equal(r.selected.sha256,hashBytes(f.wire).slice(7));assert.equal(r.selected.wire,undefined);assert.equal(r.selected.clientId,undefined);}finally{f.close();}});
for(const status of ['accepted','rejected'])test('post-failure authoring witness retains '+status+' without changing failed assertion',()=>{const f=authoringFixture();try{f.terminal(f[status]);const r=readAuthoringCommandSnapshot(f.root,f.wire);assert.equal(r.status,'terminal');assert.equal(r.terminal.status,status);assert.equal(r.terminal.commandId,f.command.commandId);assert.equal(r.terminal.code,status==='rejected'?'STALE_REVISION':null);assert.equal(r.closed,true);}finally{f.close();}});
test('authoring witness distinguishes absent, duplicate and simultaneous terminal/pending rows',()=>{const f=authoringFixture();try{assert.equal(readAuthoringCommandSnapshot(f.root,f.wire).status,'absent');f.pending();f.pending();assert.equal(readAuthoringCommandSnapshot(f.root,f.wire).status,'ambiguous');f.db.exec('DELETE FROM history_preparations');f.terminal();f.terminal();assert.equal(readAuthoringCommandSnapshot(f.root,f.wire).status,'ambiguous');f.db.exec('DELETE FROM commands');f.terminal();f.pending();assert.equal(readAuthoringCommandSnapshot(f.root,f.wire).status,'ambiguous');}finally{f.close();}});
test('authoring witness refuses original-wire, receipt-id, transaction and pending-identity mismatches',()=>{const f=authoringFixture();try{
 f.terminal();f.db.prepare('UPDATE commands SET original=?').run(f.wire+' ');assert.equal(readAuthoringCommandSnapshot(f.root,f.wire).status,'original-mismatch');
 f.db.prepare('UPDATE commands SET original=?,receipt=?').run(f.wire,JSON.stringify({...f.accepted,commandId:randomUUID()}));assert.equal(readAuthoringCommandSnapshot(f.root,f.wire).status,'receipt-mismatch');
 f.db.prepare('UPDATE commands SET receipt=?').run(JSON.stringify({...f.accepted,transactionId:randomUUID()}));assert.equal(readAuthoringCommandSnapshot(f.root,f.wire).status,'receipt-mismatch');
 f.db.exec('DELETE FROM commands');f.pending();f.db.prepare('UPDATE history_preparations SET operation_id=?').run('not-selected-identity');assert.equal(readAuthoringCommandSnapshot(f.root,f.wire).status,'pending-mismatch');
 f.db.prepare('UPDATE history_preparations SET operation_id=?,phase=?').run(f.operationId,'native-finished');assert.equal(readAuthoringCommandSnapshot(f.root,f.wire).status,'pending-mismatch');
 }finally{f.close();}});
test('authoring witness bounds wire and stored values, closes real readonly DB on malformed receipt',()=>{const f=authoringFixture();let opened=0,closed=0,handle;const open=(path,options)=>{opened++;assert.deepEqual(options,{readOnly:true});handle=new DatabaseSync(path,options);assert.throws(()=>handle.exec('CREATE TABLE forbidden(x)'));return {exec:sql=>handle.exec(sql),prepare:sql=>handle.prepare(sql),close(){closed++;handle.close();}};};try{
 assert.equal(readAuthoringCommandSnapshot(f.root,'x'.repeat(65537),{open}).status,'unavailable');assert.equal(opened,0);
 f.terminal();f.db.prepare('UPDATE commands SET receipt=?').run('x'.repeat(65537));assert.equal(readAuthoringCommandSnapshot(f.root,f.wire,{open}).status,'receipt-bound');assert.equal(closed,1);
 f.db.prepare('UPDATE commands SET receipt=?').run('{');const r=readAuthoringCommandSnapshot(f.root,f.wire,{open});assert.equal(r.status,'unavailable');assert.equal(r.closed,true);assert.equal(closed,2);assert.throws(()=>handle.prepare('SELECT 1'));
 assert.equal(f.db.prepare("SELECT count(*) AS n FROM sqlite_master WHERE name='forbidden'").get().n,0);assert.equal(f.db.prepare('SELECT count(*) AS n FROM commands').get().n,1);
 }finally{f.close();}});
test('authoring readonly snapshot retains one WAL view while writer commits a later phase',()=>{const f=authoringFixture();let changed=false;try{f.pending();const r=readAuthoringCommandSnapshot(f.root,f.wire,{open(path,options){const db=new DatabaseSync(path,options);return {exec:sql=>db.exec(sql),prepare(sql){const s=db.prepare(sql);return {all(...args){const rows=s.all(...args);if(!changed){changed=true;f.db.prepare('UPDATE history_preparations SET phase=?').run('waiting-for-resources');}return rows;}};},close:()=>db.close()};}});assert.equal(changed,true);assert.equal(r.status,'pending');assert.equal(r.pending.phase,'preparing');assert.equal(r.closed,true);assert.equal(readAuthoringCommandSnapshot(f.root,f.wire).pending.phase,'waiting-for-resources');}finally{f.close();}});
function authoringRequest(origin,id,method='POST'){return {url:()=>origin+'/api/v1/commands'+(method==='GET'?'/'+id:''),method:()=>method};}
test('authoring callbacks associate original POST/exact GET status without any body read or request',()=>{const f=authoringFixture();try{const origin='http://127.0.0.1:12345',w=createAuthoringCommandWitness(origin),post=authoringRequest(origin,f.command.commandId);w.submitted(post,f.wire);
 assert.equal(w.response(authoringRequest(origin,f.command.commandId),200),undefined,'Different POST object is not original');assert.equal(w.response(authoringRequest('http://127.0.0.1:12346',f.command.commandId,'GET'),200),undefined);assert.equal(w.response(authoringRequest(origin,randomUUID(),'GET'),200),undefined);assert.equal(w.response({url:()=>origin+'/api/v1/commands/'+f.command.commandId+'/events',method:()=> 'GET'},200),undefined);
 w.response(post,202);const token=w.response(authoringRequest(origin,f.command.commandId,'GET'),200);w.readFailed(token);w.readResult(token,{kind:'receipt',receipt:f.accepted});const result=w.failureSnapshot(f.root);assert.deepEqual(result.rows.map(x=>x.kind),['submitted','response-callback','response-callback','existing-json-read-failed']);assert.equal(result.rows[1].status,202);assert.equal(result.snapshot.status,'absent');assert.equal(result.qualification,false);assert.match(result.callbackSemantics,/not network EOF/);
 }finally{f.close();}});
test('authoring callbacks record existing JSON observation and preserve frozen failure cutoff',()=>{const f=authoringFixture();try{const origin='http://127.0.0.1:12345',w=createAuthoringCommandWitness(origin),post=authoringRequest(origin,f.command.commandId);w.submitted(post,f.wire);const token=w.response(post,200);w.readResult(token,{kind:'receipt',receipt:f.accepted});const report=w.failureSnapshot(f.root),before=JSON.stringify(report);assert.equal(report.rows[2].sameCommand,true);assert.equal(report.rows[2].receiptStatus,'accepted');w.readFailed(token);w.response(post,200);w.submitted(post,f.wire);assert.equal(JSON.stringify(w.failureSnapshot(f.root)),before);assert.equal(report.snapshot.status,'absent','Observed response does not manufacture durable state');}finally{f.close();}});
test('authoring callback overflow remains explicit and bounded; unavailable snapshot preserves primary error',()=>{const f=authoringFixture();try{const origin='http://127.0.0.1:12345',w=createAuthoringCommandWitness(origin),post=authoringRequest(origin,f.command.commandId);w.submitted(post,f.wire);for(let i=0;i<700;i++)w.response(post,202);const error=Error('original five-second assertion'),openFailure=Error('private diagnostic open failure');let retained,caught;try{try{throw error;}catch(original){retained=w.failureSnapshot(f.root,{open(){throw openFailure;}});throw original;}}catch(e){caught=e;}assert.equal(caught,error);assert.equal(retained.snapshot.status,'unavailable');assert.equal(retained.snapshot.closed,false);assert.equal(retained.overflow,true);assert.equal(retained.rows.length,AUTHORING_DIAGNOSTIC_LIMITS.rows);assert.ok(Buffer.byteLength(JSON.stringify(retained))<=AUTHORING_DIAGNOSTIC_LIMITS.outputBytes);assert.ok(!JSON.stringify(retained).includes(openFailure.message));}finally{f.close();}});


import {existsSync} from 'node:fs';
test('durable object witness inherits the real verifier without constructing a store',()=>{
 const f=fixture();try{
  const path=join(f.root,'objects','sha256',f.asset.blob.hash.slice(7,9),f.asset.blob.hash.slice(7)),before=readFileSync(path);
  assert.equal(existsSync(join(f.root,'staging')),false);
  const first=f.read();assert.deepEqual(first,f.read());
  assert.equal(first.descriptor.text,canonical(f.descriptor));assert.equal(first.descriptor.sha256,f.asset.blob.hash);
  assert.equal(first.graph.text,canonical(f.graph));assert.equal(first.graph.sha256,f.descriptor.graph.hash);
  assert.deepEqual(readFileSync(path),before);assert.equal(existsSync(join(f.root,'staging')),false);
 }finally{f.close();}
});
test('durable object witness reports actual verifier hash failure rather than receiver TypeError',()=>{
 const f=fixture(),path=join(f.root,'objects','sha256',f.asset.blob.hash.slice(7,9),f.asset.blob.hash.slice(7)),before=readFileSync(path);
 try{const corrupt=Buffer.from(before);corrupt[0]^=1;writeFileSync(path,corrupt);assert.throws(f.read,{code:'CORRUPT_OBJECT'});
  writeFileSync(path,before);assert.equal(f.read().descriptor.sha256,f.asset.blob.hash);
 }finally{try{writeFileSync(path,before);}finally{f.close();}}
});
test('durable object witness retains the real 65536-byte verified-read bound',()=>{
 const f=fixture();try{f.asset.blob.byteLength='65537';f.update();assert.throws(f.read,{code:'PAYLOAD_TOO_LARGE'});}finally{f.close();}
});
for(const kind of ['malformed','noncanonical'])test('durable object witness reaches exact '+kind+' JSON refusal after byte verification',()=>{
 const f=fixture();try{f.asset.blob=f.put(kind==='malformed'?'{':JSON.stringify(f.descriptor,null,2));f.update();
  assert.throws(f.read,kind==='malformed'?SyntaxError:assert.AssertionError);
 }finally{f.close();}
});
