// Method adapted from the sealed P1c.3 C6 harness; all fixtures and results here are fresh P1c.5 Composition author evidence.
import {expectedResponseCancellation} from './text-zoom-cancellations.mjs';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {serverProcess} from './process.ts';
import {ownedOPFS} from './text-zoom-owned.ts';
import {recordDOMErrors} from './error-monitor.ts';

const root=process.cwd()+'/';
const inputs={fixture:process.cwd(),productHead:process.env.TEXT_ZOOM_SOURCE??'working-source',sourceCommit:process.env.TEXT_ZOOM_SOURCE??'working-source',profile:JSON.parse(await readFile('src/text/profile.json')).id,playwrightVersion:JSON.parse(await readFile('node_modules/playwright/package.json')).version,browserPin:JSON.parse(await readFile('node_modules/playwright-core/browsers.json')).browsers.find(x=>x.name==='chromium'),files:{}};
const extension={"extensionId": "bjnailnfdjjklngmnageidhlbblpfpac", "manifest": {"manifest_version": 3, "name": "C6 owned browser zoom verification", "version": "1.0.0", "key": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmpllJ1Kc1/1A0TE3g/FkK3VMno+i+V4jXQ7amq5gDQs8Sa3ubCEoMECB2i8ZY3qVbvC53oMsgku6UJCJDfjwPVfFWLf9dCwS7oXKX5HiulVfvhJ4MwfbYLXB3BmUiFJLqF2ZD1g+mmJUEbyIF/xbSAUFL96EVhyTFSSVjfNR5jxQgWn6TAn6YzDncWvgsPLdUMAHzbqfzZIiJerkvc922sLnm942rpMahjGR2iXyQ713C3PHPGsFbYel393pCopX1MWzNCV43ykE9HIKGOjOdtqqZrOUKKxg2SLJx65mStw478S1y3fNidTOkPRHSNHw4QcZ3F6/z/dq1OwHIEMpdwIDAQAB", "permissions": ["tabs"]}, "document": "chrome-extension://bjnailnfdjjklngmnageidhlbblpfpac/controller.html", "script": "chrome-extension://bjnailnfdjjklngmnageidhlbblpfpac/controller.js", "policy": "No background/serviceworker, content scripts, host permissions, product DOM or CSS injection. Only exact-owned-loopback-tab zoom APIs."};
const {chromium}=await import('playwright');
const sharp=createRequire(new URL('../../package.json',import.meta.url))('sharp');
const runName=process.env.TEXT_ZOOM_RECEIPT??'artifacts/p1c5/zoom';
const out=resolve(runName)+'/';await mkdir(out,{mode:0o700});await mkdir(out+'profile',{mode:0o700});
const start=new Date().toISOString();
const sha=b=>createHash('sha256').update(b).digest('hex');
const write=(name,data)=>writeFile(out+name,JSON.stringify(data,null,2)+'\n');
const args=['--window-size=1440,1100','--disable-extensions-except='+root+'tests/editor/text-zoom-extension','--load-extension='+root+'tests/editor/text-zoom-extension'];
const executable=chromium.executablePath();assert(executable.includes('/chromium-1243/'));
const launchOptions={headless:false,viewport:null,executablePath:executable,args,ignoreDefaultArgs:['--disable-extensions']};
await write('started.json',{start,runName,productHead:inputs.productHead,sourceCommit:inputs.sourceCommit,profile:inputs.profile,playwright:inputs.playwrightVersion,browserPin:inputs.browserPin,executable,launchOptions,extension,scope:'P1c.5 author Composition zoom check. No CUA, OS key action, CSS zoom, deviceScaleFactor, viewport or pageScale emulation.'});
for(const [name,identity] of Object.entries(inputs.files))assert.equal(sha(await readFile(inputs.fixture+'/'+name)),identity.sha256,name);
const requestIDs=new WeakMap(),requestResponses=new WeakMap();let nextRequestID=0;const requestID=r=>{if(!requestIDs.has(r))requestIDs.set(r,++nextRequestID);return requestIDs.get(r);};const rawEvents=[],cspErrors=[],errors=[],commands=[],checks=[],samples=[],served=[],responseErrors=[],responseWork=[],fontPaths=new Set(),networkFailures=[],cleanup={};
const safeURL=s=>{try{const u=new URL(s);return u.origin+u.pathname;}catch{return s;}};
let server,context,controller,page,guard,domErrors=[],browserInfo,browserFlags,original,zoomed,before,after,restored,extensionCalls=[],error=null,cleanupErrors=[],assertionsPassed=false,appStylesBefore,appStylesAfter,canvasBefore,canvasAfter,effects,effectsError,classification,originalDir;
const serialize=e=>({name:e.name,message:e.message,stack:e.stack});
const metrics=()=>page.evaluate(()=>({innerWidth,innerHeight,outerWidth,outerHeight,dpr:devicePixelRatio,visualScale:visualViewport.scale,visualWidth:visualViewport.width,scrollWidth:document.documentElement.scrollWidth,cssZoom:getComputedStyle(document.documentElement).zoom,bodyZoom:getComputedStyle(document.body).zoom,rootStyle:document.documentElement.getAttribute('style'),bodyStyle:document.body.getAttribute('style')}));
const styles=()=>page.evaluate(()=>Array.from(document.styleSheets,s=>({href:s.href,rules:Array.from(s.cssRules,r=>r.cssText)})));
const ancillaryMessage='Failed to load resource: the server responded with a status of 404 (Not Found)';
const exactFaviconConsole=(e,origin)=>e.exactOptionalFavicon===true&&e.channel==='console'&&e.type==='error'&&e.page===origin+'/'&&e.location?.url===origin+'/favicon.ico'&&e.message===ancillaryMessage;
const exactFaviconHTTP=(e,origin)=>e.exactOptionalFavicon===true&&e.channel==='response'&&e.url===origin+'/favicon.ico'&&e.method==='GET'&&e.status===404;
function classify(){const origin=server?.origin;return {origin,policy:'Only exact current-owned optional favicon404 with missing icon source/static route. Raw events retained. No general console, CSP, asset or404 exemption.',ancillaryConsole:errors.filter(e=>exactFaviconConsole(e,origin)),unexpectedConsolePage:errors.filter(e=>!exactFaviconConsole(e,origin)),ancillaryHTTP:networkFailures.filter(e=>exactFaviconHTTP(e,origin)),expectedResponseCancellations:networkFailures.filter(e=>expectedResponseCancellation(e,origin)),unexpectedHTTP:networkFailures.filter(e=>e.channel==='response'&&!exactFaviconHTTP(e,origin)),unexpectedRequestFailures:networkFailures.filter(e=>e.channel==='requestfailed'&&!expectedResponseCancellation(e,origin))};}
async function captureActualView(dir){const beforeCapture=await metrics(),focusBefore=await page.evaluate(()=>({focused:document.hasFocus(),active:document.activeElement?.tagName}));const session=await context.newCDPSession(page);const layout=await session.send('Page.getLayoutMetrics'),observations=[];try{for(const fromSurface of [true,false]){const parameters={format:'png',fromSurface,captureBeyondViewport:false},response=await session.send('Page.captureScreenshot',parameters),bytes=Buffer.from(response.data,'base64'),name='browser-200-'+dir+'-'+(fromSurface?'surface':'view')+'.png';await writeFile(out+name,bytes);const {data,info}=await sharp(bytes).raw().toBuffer({resolveWithObject:true});const first=[...data.subarray(0,info.channels)];let differentChannels=0;for(let i=0;i<data.length;i++)if(data[i]!==first[i%info.channels])differentChannels++;observations.push({name,parameters,sha256:sha(bytes),width:info.width,height:info.height,firstPixel:first,differentChannels});}const afterCapture=await metrics(),focusAfter=await page.evaluate(()=>({focused:document.hasFocus(),active:document.activeElement?.tagName}));assert.deepEqual(afterCapture,beforeCapture,'Capture leaves actual metrics unchanged');assert.deepEqual(focusAfter,focusBefore,'Capture leaves focus unchanged');assert.equal(focusAfter.focused,true);const api=await controller.evaluate(()=>c6Zoom.read());assert.equal(api.zoom,2);assert.equal(afterCapture.dpr,after.dpr);assert.equal(afterCapture.innerWidth,after.innerWidth);assert.equal(afterCapture.visualScale,1);assert.equal(afterCapture.cssZoom,after.cssZoom);await write('capture-'+dir+'.json',{layout,observations,beforeCapture,afterCapture,focusBefore,focusAfter,api,scope:'Documented read-only Page.captureScreenshot with no clip or emulation; both raw outputs retained, visual inspection still required.'});assert(observations.some(o=>o.differentChannels>1000),'Actual un-clipped viewport captures have no rendered detail');}finally{await session.detach();}}
async function stable(label,expected,baseline){let previous,count=0;for(let i=0;i<80;i++){const api=await controller.evaluate(()=>c6Zoom.read()),m=await metrics();samples.push({label,at:new Date().toISOString(),api,metrics:m});const value=JSON.stringify(m);const matches=api.zoom===expected&&(!baseline||(m.dpr===baseline.dpr*2&&Math.abs(m.innerWidth*2-baseline.innerWidth)<=2));count=matches&&value===previous?count+1:0;previous=value;if(count>=3)return {api,metrics:m};await new Promise(r=>setTimeout(r,100));}throw Error('Browser zoom renderer metrics did not settle: '+label);}
try{
 server=await serverProcess(out+'private');cleanup.serverStarted={pid:server.pid,origin:server.origin};
 context=await chromium.launchPersistentContext(out+'profile',launchOptions);
 assert.equal(context.serviceWorkers().length,0,'Extension has no background service worker');
 controller=await context.newPage();guard=await ownedOPFS(context,'p1c5-composition-tab-zoom',{page:controller,document:extension.document,script:extension.script});
 domErrors=await recordDOMErrors(context);
 const instrumented=new WeakSet();
 const recordPage=p=>{if(instrumented.has(p))return;instrumented.add(p);p.on('pageerror',e=>{const v={channel:'pageerror',page:safeURL(p.url()),message:e.message};rawEvents.push({at:new Date().toISOString(),...v});errors.push(v);});p.on('console',m=>{const v={channel:'console',type:m.type(),exactOptionalFavicon:m.location().url===server.origin+'/favicon.ico',page:safeURL(p.url()),location:{...m.location(),url:safeURL(m.location().url)},message:m.text()};rawEvents.push({at:new Date().toISOString(),...v});if(m.type()==='error')errors.push(v);});};
 context.on('page',recordPage);for(const p of context.pages())recordPage(p);
 context.on('request',r=>rawEvents.push({at:new Date().toISOString(),channel:'request',requestId:requestID(r),url:safeURL(r.url()),method:r.method(),resourceType:r.resourceType()}));
 context.on('requestfailed',r=>{const v={at:new Date().toISOString(),channel:'requestfailed',requestId:requestID(r),response:requestResponses.get(r)??null,url:safeURL(r.url()),method:r.method(),resourceType:r.resourceType(),failure:r.failure()};rawEvents.push(v);networkFailures.push(v);});
 context.on('response',r=>{const v={requestId:requestID(r.request()),contentType:r.headers()['content-type']??null,contentLength:r.headers()['content-length']??null,etag:r.headers()['etag']??null,entityVersion:r.headers()['x-app-entity-version']??null,exactOptionalFavicon:r.url()===server.origin+'/favicon.ico',url:safeURL(r.url()),method:r.request().method(),resourceType:r.request().resourceType(),status:r.status(),at:new Date().toISOString(),channel:'response'};requestResponses.set(r.request(),v);rawEvents.push(v);if(r.status()>=400)networkFailures.push(v);});
 await context.exposeBinding('recordC6CSP',(_source,value)=>{cspErrors.push(value);rawEvents.push({at:new Date().toISOString(),channel:'CSP',...value});});
 await context.addInitScript(()=>addEventListener('securitypolicyviolation',e=>globalThis.recordC6CSP({documentURI:location.origin+location.pathname,blockedURI:e.blockedURI,effectiveDirective:e.effectiveDirective,violatedDirective:e.violatedDirective,disposition:e.disposition,statusCode:e.statusCode})));
 await controller.goto(extension.document);await controller.waitForFunction(()=>!!globalThis.c6Zoom);
 page=await context.newPage();await guard.admit(page,server.origin);
 const {loadStatic}=await import(new URL('../../dist/local/server/static.js',import.meta.url));const staticFiles=await loadStatic(inputs.fixture+'/dist/app');
 page.on('response',r=>{const u=new URL(r.url());if(u.origin===server.origin&&staticFiles.has(u.pathname)&&/\.(ttf|otf)$/.test(u.pathname)){fontPaths.add(u.pathname);return;}if(u.origin===server.origin&&staticFiles.has(u.pathname)&&r.request().method()==='GET'&&r.status()===200)responseWork.push(r.body().then(b=>{assert.equal(sha(b),sha(staticFiles.get(u.pathname).bytes),u.pathname);served.push({path:u.pathname,status:r.status(),bytes:b.length,sha256:sha(b)});}).catch(e=>responseErrors.push({path:u.pathname,error:serialize(e)})));});
 page.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname==='/api/v1/commands')commands.push(JSON.parse(r.postData()).command.body);});
 const cdp=await context.newCDPSession(page);browserInfo=await cdp.send('Browser.getVersion');await cdp.detach();const ownedProcesses=execFileSync('/bin/ps',['-axww','-o','pid=','-o','command='],{encoding:'utf8'}).split('\n').map(line=>line.match(/^\s*(\d+)\s+(.*)$/)).filter(Boolean).map(m=>({pid:Number(m[1]),command:m[2]})).filter(p=>p.command.startsWith(executable+' ')&&p.command.includes('--user-data-dir='+out+'profile'));assert.equal(ownedProcesses.length,1,'Exactly one owned main browser process');browserFlags={method:'Read-only ps, exact executable and fresh owned user-data-dir match; no other process arguments retained',...ownedProcesses[0],launchOptions};
 assert.equal(browserInfo.product,'Chrome/153.0.8010.12');
 await page.bringToFront();await page.goto(await server.pair());await page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true}).waitFor();
 assert.equal(new URL(page.url()).hash,'');
 const button=n=>page.getByRole('button',{name:n,exact:true});
 const waitEnabled=async b=>{for(let i=0;i<200;i++){if(await b.isEnabled())return;await new Promise(r=>setTimeout(r,50));}throw Error('Public sample button remained busy');};
 const field=async(n,v)=>{const f=page.getByRole('spinbutton',{name:n,exact:true});await f.fill(v);await f.press('Tab');};
 await button('New').click();await field('Width (px)','360');await field('Height (px)','200');await button('Create').click();await page.getByRole('dialog',{name:'New document',exact:true}).waitFor({state:'hidden'});await page.getByRole('radio',{name:'Composition',exact:true}).focus();await page.keyboard.press('Space');await page.getByRole('textbox',{name:'Scene',exact:true}).fill('Composition 😀\nRange and real browser zoom');await button('Add semantic text').click();await page.getByRole('textbox',{name:'Literal lettering',exact:true}).fill('Independent semantic text');
 assert.equal(staticFiles.has('/favicon.ico'),false);assert.equal(await page.locator('link[rel~=icon]').count(),0);
 originalDir=await page.locator('html').getAttribute('dir');
 original=await controller.evaluate(url=>c6Zoom.bind(url),page.url());assert.equal(original.zoom,1,'Fresh profile starts at browser zoom1');
 const input=page.getByRole('textbox',{name:'Scene',exact:true});await input.focus();const fieldHandle=await input.elementHandle(),parentHandle=await fieldHandle.evaluateHandle(el=>el.parentNode);
 const focused=()=>input.evaluate((el,original)=>({sameField:el===original.field,sameParent:el.parentNode===original.parent,focused:el===el.getRootNode().activeElement,documentFocused:document.hasFocus()}),{field:fieldHandle,parent:parentHandle});
 const focusBefore=await focused();assert(focusBefore.sameField&&focusBefore.sameParent&&focusBefore.focused&&focusBefore.documentFocused);assert.equal(original.active,true);
 before=(await stable('baseline',1)).metrics;canvasBefore=await page.getByRole('spinbutton',{name:'Zoom percentage',exact:true}).inputValue();appStylesBefore=sha(JSON.stringify(await styles()));await page.screenshot({path:out+'browser-100-ltr.png'});
 zoomed=await controller.evaluate(()=>c6Zoom.set200());assert.equal(zoomed.zoom,2);assert.equal(zoomed.settings.mode,'automatic');assert.equal(zoomed.settings.scope,'per-tab');
 after=(await stable('zoom200',2,before)).metrics;
 assert.equal(after.dpr/before.dpr,2);assert(Math.abs(after.innerWidth*2-before.innerWidth)<=2);assert.equal(after.visualScale,1);assert.equal(after.outerWidth,before.outerWidth);assert.equal(after.outerHeight,before.outerHeight);assert.equal(after.cssZoom,before.cssZoom);assert.equal(after.bodyZoom,before.bodyZoom);assert.equal(after.rootStyle,before.rootStyle);assert.equal(after.bodyStyle,before.bodyStyle);
 canvasAfter=await page.getByRole('spinbutton',{name:'Zoom percentage',exact:true}).inputValue();assert.equal(canvasAfter,canvasBefore);appStylesAfter=sha(JSON.stringify(await styles()));assert.equal(appStylesAfter,appStylesBefore);
 const focusAfter=await focused();assert(focusAfter.sameField&&focusAfter.sameParent&&focusAfter.focused&&focusAfter.documentFocused,'Focused native input and parent survive browser-managed zoom');await write('focus.json',{before:focusBefore,after:focusAfter});checks.push('Browser API getZoom2, DPR ratio2, half CSS width, fixed outer window, visualScale1, unchanged CSS and canvas zoom');checks.push('Focused native field and parent stable through real browser-managed page zoom');
 for(const dir of ['ltr','rtl']){
  await page.evaluate(d=>document.documentElement.dir=d,dir);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
  const m=await metrics();assert(m.scrollWidth<=m.innerWidth+1,dir+' must reflow without horizontal document overflow');
  await input.scrollIntoViewIfNeeded();await input.focus();await input.press('Home');await input.press('Shift+ArrowRight');
  const range=await input.evaluate(el=>({start:el.selectionStart,end:el.selectionEnd,direction:el.selectionDirection}));
  await input.press('ArrowLeft');assert.equal(await input.inputValue(),'Composition 😀\nRange and real browser zoom');
  assert(await input.evaluate((el,original)=>el===original.field&&el.parentNode===original.parent,{field:fieldHandle,parent:parentHandle}));
  await input.scrollIntoViewIfNeeded();const box=await input.boundingBox();assert(box&&box.x>=-1&&box.x+box.width<=m.innerWidth+1);assert(await input.isVisible());
  await write('reflow-'+dir+'.json',{metrics:m,zoom:await controller.evaluate(()=>c6Zoom.read()),inputBox:box,nativeFocus:true,fieldAndParentStable:true,range});await captureActualView(dir);checks.push(dir+' public Composition textarea, native caret keys, stable input and no document horizontal overflow at browser zoom2');
 }
 // Independent static-byte identity only: this separate GET supplies no proof
 // about completion or cancellation of any browser font request.
 for(const path of fontPaths){const r=await context.request.get(server.origin+path);assert.equal(r.status(),200);const b=await r.body();assert.equal(sha(b),sha(staticFiles.get(path).bytes));served.push({path,status:r.status(),bytes:b.length,sha256:sha(b),method:'Independent APIRequestContext GET for static-byte identity only; not browser-request completion evidence'});await r.dispose();}
 await Promise.all(responseWork);effects=await server.effects();await write('effects.json',effects);classification=classify();await write('error-classification.json',classification);assert(served.length>0);assert.deepEqual(responseErrors,[]);assert.deepEqual(classification.unexpectedConsolePage,[]);assert.deepEqual(classification.unexpectedHTTP,[]);assert.deepEqual(classification.unexpectedRequestFailures,[]);assert.deepEqual(domErrors,[]);assert.deepEqual(cspErrors,[]);assert.equal(Object.keys(effects).length,8);assert(Object.values(effects).every(v=>v===0));checks.push('Own eight effects counters zero; all unexpected HTTP/console/page/DOM/CSP errors absent; exact optional favicon retained separately');assertionsPassed=true;
}catch(e){error=serialize(e);}finally{
 try{if(original&&controller&&!controller.isClosed()){await page.evaluate(dir=>{if(dir===null)document.documentElement.removeAttribute('dir');else document.documentElement.dir=dir;},originalDir);restored=await controller.evaluate(()=>c6Zoom.restore());const restoredMetrics=(await stable('restored',original.zoom)).metrics;assert.equal(restoredMetrics.dpr,before.dpr);assert.equal(restoredMetrics.innerWidth,before.innerWidth);assert.equal(restoredMetrics.outerWidth,before.outerWidth);assert.equal(restoredMetrics.outerHeight,before.outerHeight);assert.equal(restoredMetrics.innerHeight,before.innerHeight);assert.equal(restoredMetrics.visualScale,before.visualScale);assert.equal(restoredMetrics.cssZoom,before.cssZoom);assert.equal(restoredMetrics.bodyZoom,before.bodyZoom);assert.equal(await page.locator('html').getAttribute('dir'),originalDir);cleanup.zoomRestored={state:restored,metrics:restoredMetrics};}}catch(e){cleanupErrors.push({phase:'restore',...serialize(e)});}
 try{if(controller&&!controller.isClosed()){extensionCalls=await controller.evaluate(()=>c6Zoom.log());await controller.close();cleanup.extensionPageClosed=true;}}catch(e){cleanupErrors.push({phase:'extension-close',...serialize(e)});}
 try{if(page&&!page.isClosed())await page.goto('about:blank');if(guard){await guard.cleanup();guard.verify();cleanup.ownedStorageVerified=true;}}catch(e){cleanupErrors.push({phase:'owned-cleanup',...serialize(e)});}
 try{if(context){await context.close();cleanup.contextClosed=true;}}catch(e){cleanupErrors.push({phase:'context-close',...serialize(e)});}
 try{if(server){if(!effects){try{effects=await server.effects();await write('effects.json',effects);}catch(e){effectsError=serialize(e);}}await server.close();cleanup.serverClosed=true;}}catch(e){cleanupErrors.push({phase:'server-close',...serialize(e)});}
 await write('ownership.json',guard?.ledger??[]);await write('extension-calls.json',extensionCalls);await write('metrics-samples.json',samples);await write('browser-flags.json',browserFlags??{});
 classification=classify();await write('error-classification.json',classification);await write('raw-events.json',rawEvents);const passed=classification.unexpectedConsolePage.length===0&&classification.unexpectedHTTP.length===0&&classification.unexpectedRequestFailures.length===0&&cspErrors.length===0&&domErrors.length===0&&effects&&Object.values(effects).every(v=>v===0)&&assertionsPassed&&!error&&cleanupErrors.length===0&&cleanup.ownedStorageVerified&&cleanup.contextClosed&&cleanup.serverClosed&&cleanup.extensionPageClosed&&!!cleanup.zoomRestored;
 await write('result.json',{start,end:new Date().toISOString(),passed,assertionsPassed,error,cleanupErrors,cleanup,browserInfo,original,zoomed,before,after,restored,canvasBefore,canvasAfter,appStylesBefore,appStylesAfter,checks,commands,errors,domErrors,cspErrors,effects,effectsError,classification,served,responseErrors,networkFailures,scope:'P1c.5 AUTHOR actual browser-managed automatic per-tab200% via MV3 extension APIs. Exact owned fresh headed persistent Chromiumr1243/PW1.63, viewport:null/fixed window. No CUA/OS action, emulation or product change; Composition UI author evidence only; physical OS IME/AT and independent acceptance remain outstanding.'});
 console.log(JSON.stringify({passed,start,end:new Date().toISOString(),before,after,error,cleanupErrors}));if(!passed)process.exitCode=1;
}
