import {isolatedBrowserTest as test} from './isolated-browser.js';
import {specReceipt} from './receipt-path.js';
import {confirmImageImports} from './image-import-flow.js';
import {expect,type Page} from '@playwright/test';
import {mkdtemp,realpath,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {observeDisplayAborts} from './display-aborts.js';
import {expectedCompositionCancellation,expectedDisplayBusy} from './composition-network.mjs';
import {serverProcess} from './process.js';
import {ownedOPFS} from './owned-opfs.js';
import {recordDOMErrors} from './error-monitor.js';
const receipt=specReceipt(import.meta.url,'artifacts/p1c5/browser');
const click=(p:Page,name:string)=>p.getByRole('button',{name,exact:true}).click();
async function field(p:Page,name:string,value:string){const f=p.getByRole('spinbutton',{name,exact:true});await f.fill(value);await f.press('Tab');}
async function setup(page:Page){await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await click(page,'New');await field(page,'Width (px)','1600');await field(page,'Height (px)','900');await click(page,'Create');await expect(page.getByRole('dialog',{name:'New document',exact:true})).toBeHidden();await page.getByRole('radio',{name:'Composition',exact:true}).focus();await page.getByRole('radio',{name:'Composition',exact:true}).press('Space');await expect(page.getByRole('textbox',{name:'Scene',exact:true})).toBeVisible();}
for(const scenario of ['authoring','links','raw','controls','geometry','late-review'] as const)test('Composition '+scenario+' uses public controls, durable authority and owned cleanup',async({page,context,browserName})=>{
 const guard=await ownedOPFS(context,'p1c5-'+scenario+'-'+browserName),errors=await recordDOMErrors(context),commands:any[]=[],consoleErrors:any[]=[],requests:string[]=[],failedResponses:unknown[]=[],requestFailures:any[]=[],downloadProofs:any[]=[],responseBodies:unknown[]=[],downloadRequests:any[]=[],responseWork:Promise<void>[]=[],csp:unknown[]=[],publicModes:any[]=[];let browserRuntime:unknown=null,effects:unknown=null,phase='workflow',requestSequence=0,exportWindow=false;const ids=new WeakMap<any,number>(),responses=new WeakMap<any,any>(),requestId=(r:any)=>{if(!ids.has(r))ids.set(r,++requestSequence);return ids.get(r);};
 page.on('response',r=>{responses.set(r.request(),{requestId:requestId(r.request()),url:r.url(),method:r.request().method(),status:r.status(),contentType:r.headers()['content-type'],contentLength:r.headers()['content-length'],etag:r.headers()['etag'],entityVersion:r.headers()['x-app-entity-version']});if(new URL(r.url()).searchParams.get('download')==='1')responseWork.push((async()=>{try{const b=await r.body();responseBodies.push({requestId:requestId(r.request()),bytes:b.length,sha256:createHash('sha256').update(b).digest('hex'),finished:await r.finished()});}catch(e){responseBodies.push({requestId:requestId(r.request()),unavailable:String(e)});}})());if(r.status()>=400)responseWork.push((async()=>{failedResponses.push({requestId:requestId(r.request()),url:r.url(),path:new URL(r.url()).pathname+new URL(r.url()).search,status:r.status(),body:await r.text().catch(()=>'<unavailable>')});})());});page.on('requestfailed',r=>requestFailures.push({channel:'requestfailed',phase,requestId:requestId(r),url:r.url(),method:r.method(),resourceType:r.resourceType(),failure:r.failure(),response:responses.get(r)??null}));page.on('console',m=>{if(m.type()==='error')consoleErrors.push({text:m.text(),url:m.location().url});});page.on('request',r=>{const u=new URL(r.url());if(exportWindow&&r.method()==='GET'&&u.origin===server.origin&&u.pathname.endsWith('/composition')&&u.searchParams.get('download')==='1')downloadRequests.push(r);requests.push(r.method()+' '+new URL(r.url()).pathname);if(r.method()==='POST'&&new URL(r.url()).pathname==='/api/v1/commands')commands.push(JSON.parse(r.postData()!).command.body);});
 const displayAborts=await observeDisplayAborts(context,requestId);
 if(scenario==='raw')await context.addInitScript(()=>Object.defineProperty(window,'showSaveFilePicker',{value:undefined,configurable:true}));
 await context.exposeBinding('compositionCSP',(_source,value)=>{csp.push(value);});await context.addInitScript(()=>addEventListener('securitypolicyviolation',e=>(window as any).compositionCSP({directive:e.effectiveDirective,blocked:e.blockedURI})));
 const dir=await mkdtemp(join(await realpath(tmpdir()),'ie-p1c5-'+scenario+'-')),server=await serverProcess(join(dir,'private'));await mkdir(receipt,{recursive:true});
 const exportOriginal=async(raw:string,scope:'draft'|'accepted')=>{
  downloadRequests.length=0;exportWindow=true;const downloading=page.waitForEvent('download');await click(page,'Export exact original bytes');const download=await downloading,path=join(receipt,'raw-original-'+scope+'.bin');await download.saveAs(path);exportWindow=false;
  expect(downloadRequests).toHaveLength(1);const request=downloadRequests[0],response=responses.get(request),bytes=await readFile(path),sha256=createHash('sha256').update(bytes).digest('hex');expect(bytes).toEqual(Buffer.from(raw));expect(download.suggestedFilename()).toBe('caption-original.bin');expect(download.url().startsWith('blob:'+server.origin+'/')).toBe(true);expect(response.status).toBe(200);expect(response.contentType).toBe('application/octet-stream');expect(response.contentLength).toBe(String(bytes.length));expect(response.etag).toBe('"sha256:'+sha256+'"');expect(new URL(request.url()).pathname).toContain(scope==='draft'?'/ui/':'/documents/');
  // Unchanged writeDestination reads to done, checks length/SHA256, closes its
  // own disk sink, then emits this blob. This exact export has one original GET.
  downloadProofs.push({sourceScope:scope,requestId:requestId(request),url:request.url(),response,bytes:bytes.length,sha256,downloadName:download.suggestedFilename(),downloadURL:download.url(),oneOwnedRequestInExplicitExportWindow:true,destinationComplete:true,proof:'Actual saveAs bytes of normal verified destination blob; protocol response.body availability is recorded separately.'});
  await expect(page.getByText('Original-byte download started; destination remains unconfirmed.',{exact:true})).toBeVisible();
 };
 const publicMode=async(label:string)=>{
  const row:any={label,at:new Date().toISOString(),scope:'Public DOM observation after action or before cleanup; not action-time causality'};publicModes.push(row);
  try{row.dialogs=await page.getByRole('dialog').allTextContents();row.validation=await page.locator('en-validation-summary').evaluateAll(es=>es.map(e=>(e as any).items));row.url=page.url();row.recovery=await page.getByRole('region',{name:'Operation status',exact:true}).evaluateAll(es=>es.map(e=>e.textContent));row.document=await page.getByRole('banner').evaluateAll(es=>es.map(e=>e.textContent));row.radios=await page.getByRole('radio',{name:'Composition',exact:true}).evaluateAll(es=>es.map(e=>({ariaChecked:e.getAttribute('aria-checked'),...typeof (e as HTMLInputElement).checked==='boolean'?{checked:(e as HTMLInputElement).checked}:{}})));row.cards=await page.locator('section.composition-editor').filter({has:page.locator('#composition-scene')}).evaluateAll(es=>es.map(e=>({hidden:(e as HTMLElement).hidden,rects:e.getClientRects().length,display:getComputedStyle(e).display,visibility:getComputedStyle(e).visibility})));row.scenes=await page.getByRole('textbox',{name:'Scene',exact:true}).evaluateAll(es=>es.map(e=>({value:(e as HTMLTextAreaElement).value,rects:e.getClientRects().length})));}catch(error){row.unavailable=String(error);}return row;
 };
 const modeAgreement=async()=>{const row=await publicMode('post-reload-mode-agreement');expect(row.unavailable).toBeUndefined();expect(row.radios).toHaveLength(1);expect(row.radios[0].checked===true||row.radios[0].ariaChecked==='true').toBe(true);expect(row.cards).toHaveLength(1);expect(row.cards[0].hidden).toBe(false);expect(row.cards[0].rects).toBeGreaterThan(0);expect(row.cards[0].display).not.toBe('none');expect(row.cards[0].visibility).not.toBe('hidden');expect(row.scenes).toHaveLength(1);expect(row.scenes[0].rects).toBeGreaterThan(0);};
 try{await guard.admit(page,server.origin);await page.goto(await server.pair());browserRuntime={version:context.browser()?.version()??null,userAgent:await page.evaluate(()=>navigator.userAgent),pin:JSON.parse(await readFile('node_modules/playwright-core/browsers.json','utf8')).browsers.find((b:any)=>b.name===browserName)};await setup(page);
  if(scenario==='authoring'){
   await page.getByRole('textbox',{name:'Scene',exact:true}).fill('Café 東京 scene');await click(page,'Add semantic text');await page.getByRole('textbox',{name:'Literal lettering',exact:true}).fill('Café\n東京');await page.getByRole('textbox',{name:'Appearance description',exact:true}).fill('A heading');
   expect(await page.locator('#layer-tree').getByRole('treeitem').count()).toBe(0);await click(page,'Add literal bounds');await field(page,'X in document pixels','160');await field(page,'Y in document pixels','90');await field(page,'Width in document pixels','1280');await field(page,'Height in document pixels','180');
   await click(page,'Preview request draft');const exact=page.getByRole('textbox',{name:'Exact local prompt string'});await expect(exact).toBeVisible();const first=await exact.inputValue();expect(JSON.parse(first).compositional_deconstruction.elements[0]).toEqual({type:'text',bbox:[100,100,300,900],text:'Café\n東京',desc:'A heading'});
   await page.locator('#apply-composition').evaluate(h=>h.addEventListener('click',e=>e.preventDefault(),{once:true}));await click(page,'Apply Composition');expect(commands.filter(c=>c.type==='CommitCompositionVersion')).toHaveLength(0);await click(page,'Apply Composition');await expect(page.getByText('Composition applied and saved locally.',{exact:true})).toBeVisible();expect(commands.filter(c=>c.type==='CommitCompositionVersion')).toHaveLength(1);
   await displayAborts.settle(page);await page.reload();await expect(page.getByRole('radio',{name:'Composition',exact:true})).toBeVisible();await page.getByRole('radio',{name:'Composition',exact:true}).focus();await page.getByRole('radio',{name:'Composition',exact:true}).press('Space');await publicMode('post-reload-action');await expect(page.locator('#semantic-tree').getByRole('treeitem')).toHaveCount(1);await modeAgreement();await click(page,'Preview request draft');await expect(exact).toHaveValue(first);await click(page,'Approve local request draft');await expect(page.getByText('Local request draft reviewed and saved. No provider request was made.',{exact:true})).toBeVisible();
   await click(page,'Undo');await click(page,'Redo');expect(commands.filter(c=>['CreateTextLayer','ImportAsset'].includes(c.type))).toHaveLength(0);
  }else if(scenario==='links'){
   await click(page,'Import image');await expect(page.getByRole('dialog',{name:'Import image',exact:true})).toBeVisible();await page.locator('en-dialog#editor-dialog').locator('en-file-upload input[type=file]').setInputFiles('tests/raster/fixtures/hidden-alpha.png');await confirmImageImports(page,{names:['hidden-alpha.png'],destination:'current'});await expect(page.locator('#layer-tree').getByRole('treeitem')).toHaveCount(1);expect(await page.locator('#semantic-tree').getByRole('treeitem').count()).toBe(0);await page.locator('#layer-tree').getByRole('treeitem').click();await page.getByRole('textbox',{name:'Layer appearance description',exact:true}).fill('Explicit native appearance');await click(page,'Apply appearance description');await expect(page.getByText('SetLayerAppearance accepted and saved locally.',{exact:true})).toBeVisible();
   await click(page,'Add object');const choice=page.getByRole('combobox',{name:'Native layer for explicit links',exact:true});await expect(choice.locator('option')).toHaveCount(2);await choice.selectOption({index:1});await click(page,'Link appearance');await expect(page.getByRole('textbox',{name:'Appearance description',exact:true})).toHaveValue('Explicit native appearance');await expect(page.getByRole('textbox',{name:'Appearance description',exact:true})).toHaveAttribute('readonly','');await click(page,'Apply Composition');await expect(page.getByText('Composition applied and saved locally.',{exact:true})).toBeVisible();
   await page.getByRole('tab',{name:'Layers',exact:true}).click();await page.getByRole('textbox',{name:'Layer appearance description',exact:true}).fill('Changed native appearance');await click(page,'Apply appearance description');await expect(page.getByText('SetLayerAppearance accepted and saved locally.',{exact:true})).toBeVisible();await page.getByRole('tab',{name:'Composition',exact:true}).click();await page.locator('#semantic-tree').getByRole('treeitem').click();await click(page,'Preview request draft');await expect(page.locator('#composition-errors')).toContainText('STALE_LINK');await click(page,'Detach appearance as last reviewed literal');await expect(page.getByRole('textbox',{name:'Appearance description',exact:true})).toHaveValue('Explicit native appearance');await click(page,'Apply Composition');await expect(page.getByText('Composition applied and saved locally.',{exact:true})).toBeVisible();await page.getByRole('tab',{name:'Layers',exact:true}).click();await expect(page.locator('#layer-tree').getByRole('treeitem')).toHaveCount(1);
  }else if(scenario==='raw'){
   await click(page,'Raw caption inspection and Convert copy');const input=page.getByRole('textbox',{name:'Raw caption to retain',exact:true});const raw='{"compositional_deconstruction":{"background":"","elements":[]}}';await input.fill(raw);await click(page,'Retain and inspect raw');await expect(page.getByText('Original bytes retained separately. Inspection grants no authoring authority.',{exact:true})).toBeVisible();await expect(page.locator('en-validation-summary').filter({hasText:'Raw inspection'})).toContainText('MISSING_SCENE');await exportOriginal(raw,'draft');await click(page,'Convert copy…');await expect(page.getByRole('dialog',{name:'Review Convert copy'})).toBeVisible();await page.getByRole('textbox',{name:'Conversion copy',exact:true}).fill('{"high_level_description":"","compositional_deconstruction":{"background":"","elements":[]}}');await click(page,'Apply reviewed Convert copy');await expect(page.getByRole('dialog',{name:'Review Convert copy'})).toBeHidden();await expect(page.getByText('Composition applied and saved locally.',{exact:true})).toBeVisible();await expect(page.getByRole('textbox',{name:'Immutable raw byte page',exact:true})).toHaveValue(raw);await exportOriginal(raw,'accepted');
   await displayAborts.settle(page);await page.reload();await expect(page.getByRole('radio',{name:'Composition',exact:true})).toBeVisible();await page.getByRole('radio',{name:'Composition',exact:true}).focus();await page.getByRole('radio',{name:'Composition',exact:true}).press('Space');await publicMode('post-reload-action');await click(page,'Raw caption inspection and Convert copy');await expect(page.getByRole('textbox',{name:'Immutable raw byte page',exact:true})).toHaveValue(raw);await modeAgreement();await expect(page.locator('en-validation-summary').filter({hasText:'Raw inspection'})).toContainText('MISSING_SCENE');
   const colors:string[]=[];for(const colorScheme of ['light','dark'] as const){await page.emulateMedia({colorScheme});await page.evaluate(v=>document.documentElement.setAttribute('data-en-appearance',v),colorScheme);colors.push(await page.locator('body').evaluate(el=>getComputedStyle(el).color));await input.focus();await expect(input).toBeFocused();for(const width of [1440,720,320]){await page.setViewportSize({width,height:1000});await displayAborts.settle(page);for(const direction of ['ltr','rtl']){await page.evaluate(v=>document.documentElement.dir=v,direction);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);if(browserName==='chromium'&&((colorScheme==='light'&&width===320&&direction==='rtl')||(colorScheme==='dark'&&width===720&&direction==='ltr')))await page.screenshot({path:join(receipt,`raw-${colorScheme}-${width}-${direction}.png`),fullPage:true,caret:'initial'});}}}expect(colors[0]).not.toBe(colors[1]);await page.setViewportSize({width:1440,height:1000});await displayAborts.settle(page);await page.evaluate(()=>document.documentElement.dir='ltr');
  }
  if(scenario==='controls'){
   await page.getByRole('combobox',{name:'Style',exact:true}).selectOption('photo');await page.getByRole('textbox',{name:'Photography description',exact:true}).fill('Original photo draft');await page.getByRole('combobox',{name:'Style',exact:true}).selectOption('art');await page.getByRole('textbox',{name:'Art style',exact:true}).fill('Watercolor');await page.getByRole('combobox',{name:'Style',exact:true}).selectOption('photo');await expect(page.getByRole('textbox',{name:'Photography description',exact:true})).toHaveValue('Original photo draft');
   await click(page,'Add object');await click(page,'Add literal bounds');await field(page,'Width in document pixels','');await click(page,'Apply Composition');await expect(page.locator('#composition-errors')).toContainText('NUMBER_REQUIRED');await page.locator('#composition-errors').getByRole('link').click();await expect(page.getByRole('spinbutton',{name:'Width in document pixels',exact:true})).toBeFocused();await field(page,'Width in document pixels','-1');await click(page,'Apply Composition');await expect(page.locator('#composition-errors')).toContainText('INVALID_GEOMETRY');await page.locator('#composition-errors').getByRole('link').click();await expect(page.getByRole('spinbutton',{name:'Width in document pixels',exact:true})).toBeFocused();await field(page,'Width in document pixels','100');
   await click(page,'Request frame and guides');await field(page,'Request width','0');await click(page,'Request frame and guides');await click(page,'Apply Composition');await expect(page.locator('#composition-errors')).toContainText('INVALID_FRAME');await page.locator('#composition-errors').getByRole('link').click();await expect(page.getByRole('spinbutton',{name:'Request width',exact:true})).toBeFocused();await field(page,'Request width','512');await click(page,'Request frame and guides');
   await click(page,'Caption palette');await page.getByRole('textbox',{name:'Color draft including alpha or Display P3',exact:true}).fill('color(display-p3 1 0 0 / 0.4)');await click(page,'Preview opaque sRGB color');await expect(page.getByText(/alpha 0.4 becomes 1/)).toBeVisible();await click(page,'Apply color to palette');await expect(page.getByRole('textbox',{name:'Color draft including alpha or Display P3',exact:true})).toHaveValue('color(display-p3 1 0 0 / 0.4)');
   await page.getByRole('button',{name:'Adjust semantic bounds with arrow keys',exact:true}).focus();await page.keyboard.press('ArrowRight');await expect(page.getByRole('spinbutton',{name:'X in document pixels',exact:true})).toHaveValue('1');
   await page.getByRole('combobox',{name:'Prompt expansion',exact:true}).selectOption('Large');await page.getByRole('combobox',{name:'Operation',exact:true}).selectOption('Generate with Fast');await click(page,'Preview request draft');await expect(page.locator('#composition-errors')).toContainText('EXPANSION_ROUTE_CONFLICT');await expect(page.getByRole('combobox',{name:'Prompt expansion',exact:true})).toHaveValue('Large');await page.getByRole('combobox',{name:'Prompt expansion',exact:true}).selectOption('None');
   await click(page,'Preview request draft');expect(JSON.parse(await page.getByRole('textbox',{name:'Exact local prompt string'}).inputValue()).compositional_deconstruction.elements[0].color_palette).toEqual(['#FF0000']);await click(page,'Apply Composition');await expect(page.getByText('Composition applied and saved locally.',{exact:true})).toBeVisible();
   await click(page,'Duplicate semantic element');await expect(page.locator('#semantic-tree').getByRole('treeitem')).toHaveCount(2);await click(page,'Move element earlier');await click(page,'Delete semantic element');await expect(page.locator('#semantic-tree').getByRole('treeitem')).toHaveCount(1);await expect(page.getByText(/1\/256 semantic elements; 0 native layers/)).toBeVisible();await page.getByRole('textbox',{name:'Scene',exact:true}).fill('Recovered unapplied composition');await expect(page.getByRole('contentinfo').getByText('Accepted edits saved locally · Draft saved locally; not applied to the document',{exact:true})).toBeVisible();await displayAborts.settle(page);await page.reload();await expect(page.getByRole('textbox',{name:'Scene',exact:true})).toHaveValue('Recovered unapplied composition');await click(page,'Review current document');await click(page,'Apply Composition');await expect(page.getByText('Composition applied and saved locally.',{exact:true})).toBeVisible();
  }
  if(scenario==='geometry'){
   await click(page,'Add object');await click(page,'Add literal bounds');await page.getByRole('switch',{name:'Move selected semantic bounds on canvas',exact:true}).check();const canvas=page.getByLabel('Document raster preview',{exact:true});await canvas.scrollIntoViewIfNeeded();const box=await canvas.boundingBox();expect(box).not.toBeNull();const x=box!.x+40,y=box!.y+40;
   const drag=async(dx:number,dy:number,cancel=false)=>{await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+dx,y+dy,{steps:6});if(cancel)await page.keyboard.press('Escape');await page.mouse.up();};
   await drag(12,8);await expect(page.getByRole('spinbutton',{name:'X in document pixels',exact:true})).toHaveValue('12');await expect(page.getByRole('spinbutton',{name:'Y in document pixels',exact:true})).toHaveValue('8');expect(commands.filter(c=>c.type==='CommitCompositionVersion')).toHaveLength(0);
   await canvas.evaluate(el=>el.addEventListener('pointerup',e=>e.preventDefault(),{once:true}));await drag(25,25);await expect(page.getByRole('spinbutton',{name:'X in document pixels',exact:true})).toHaveValue('12');await drag(30,30,true);await expect(page.getByRole('spinbutton',{name:'Y in document pixels',exact:true})).toHaveValue('8');
   const scene=page.getByRole('textbox',{name:'Scene',exact:true});await scene.focus();await scene.dispatchEvent('compositionstart');await expect(page.getByRole('button',{name:'Apply Composition',exact:true})).toBeDisabled();await scene.evaluate(el=>{(el as HTMLTextAreaElement).value='Synthetic composition draft';el.dispatchEvent(new InputEvent('input',{bubbles:true,composed:true,isComposing:true,inputType:'insertCompositionText',data:'Synthetic composition draft'}));});await expect(page.getByRole('button',{name:'Apply Composition',exact:true})).toBeDisabled();await scene.dispatchEvent('compositionend',{data:'Synthetic composition draft'});await expect(page.getByRole('button',{name:'Apply Composition',exact:true})).toBeEnabled();await click(page,'Apply Composition');await expect(page.getByText('Composition applied and saved locally.',{exact:true})).toBeVisible();expect(commands.filter(c=>c.type==='CommitCompositionVersion')).toHaveLength(1);expect(commands.filter(c=>['ImportAsset','CreateTextLayer'].includes(c.type))).toHaveLength(0);await displayAborts.settle(page);await page.reload();await page.getByRole('radio',{name:'Composition',exact:true}).focus();await page.getByRole('radio',{name:'Composition',exact:true}).press('Space');await publicMode('post-reload-action');await expect(scene).toHaveValue('Synthetic composition draft');await modeAgreement();
  }
  if(scenario==='late-review'){
   const scene=page.getByRole('textbox',{name:'Scene',exact:true}),applied=()=>expect(page.getByText('Composition applied and saved locally.',{exact:true})).toBeVisible();
   await scene.fill('Document A');await click(page,'Apply Composition');await applied();
   let arm=false,held:any,notify:()=>void=()=>{};
   await page.route('**/api/v1/documents/*/composition?revision=*',async route=>{if(arm){arm=false;held=route;notify();}else await route.continue();});
   const hold=async()=>{const pending=new Promise<void>(r=>notify=r);arm=true;await click(page,'Review current document');await pending;};
   const release=async()=>{const request=held.request(),response=page.waitForResponse(r=>r.request()===request,{timeout:15000});await test.step('Release held review request',async()=>{await held.continue();held=null;});await test.step('Observe released review headers',async()=>{await response;});await page.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));};
   try{
    await hold();await click(page,'New');await field(page,'Width (px)','640');await field(page,'Height (px)','480');await click(page,'Create');await expect(page.getByRole('dialog',{name:'New document',exact:true})).toBeHidden();await scene.fill('Document B');await click(page,'Apply Composition');await applied();await scene.fill('Document B latest intent');await release();await click(page,'Apply Composition');await applied();await expect(scene).toHaveValue('Document B latest intent');
    await hold();await scene.fill('Same document newer draft');await release();await click(page,'Apply Composition');await applied();await expect(scene).toHaveValue('Same document newer draft');
    await hold();await click(page,'Preview request draft');const exact=await page.getByRole('textbox',{name:'Exact local prompt string'}).inputValue();await release();await expect(page.getByRole('textbox',{name:'Exact local prompt string'})).toHaveValue(exact);
    await hold();await click(page,'Review current document');await expect(page.getByText('Current document reviewed. Each stale field still needs explicit relink or detach.',{exact:true})).toBeVisible();const savedBefore=commands.length;await release();await click(page,'Apply Composition');await applied();expect(commands.length).toBeGreaterThan(savedBefore);
    await hold();await page.getByRole('radio',{name:'Plain prompt',exact:true}).focus();await page.keyboard.press('Space');await page.getByRole('radio',{name:'Composition',exact:true}).focus();await page.keyboard.press('Space');await release();await expect(page.getByText('Composition applied and saved locally.',{exact:true})).toBeVisible();
    await click(page,'Raw caption inspection and Convert copy');await page.getByRole('textbox',{name:'Raw caption to retain',exact:true}).fill('{}');await click(page,'Retain and inspect raw');await expect(page.getByText('Original bytes retained separately. Inspection grants no authoring authority.',{exact:true})).toBeVisible();await hold();await click(page,'Convert copy…');await click(page,'Cancel conversion');await release();await expect(page.getByRole('dialog',{name:'Review Convert copy'})).toBeHidden();await click(page,'Apply Composition');await applied();await expect(scene).toHaveValue('Same document newer draft');
    await displayAborts.settle(page);await page.reload();await page.getByRole('radio',{name:'Composition',exact:true}).focus();await page.keyboard.press('Space');await publicMode('post-reload-action');await expect(scene).toHaveValue('Same document newer draft');await modeAgreement();
   }finally{if(held)await held.continue();await page.unrouteAll({behavior:'wait'});}
  }
  if(scenario!=='raw'&&scenario!=='late-review'){await page.getByRole('tab',{name:'Composition',exact:true}).click();await page.locator('#semantic-tree').getByRole('treeitem').first().click();await page.getByRole('textbox',{name:'Scene',exact:true}).scrollIntoViewIfNeeded();}
  // Pinned WebKit screenshot synchronization injects an inline body {} style.
  // Retain run37 captures separately; this workflow oracle stays strict through cleanup.
  if(browserName!=='webkit')await page.screenshot({path:join(receipt,scenario+'.png'),fullPage:true,caret:'initial'});effects=await server.effects();expect(Object.values(effects as object).every(n=>n===0)).toBe(true);expect(errors).toEqual([]);expect(consoleErrors.map(e=>JSON.stringify(e)).sort()).toEqual(failedResponses.filter((e:any)=>expectedDisplayBusy(e,server.origin,displayAborts())).map((e:any)=>JSON.stringify({text:'Failed to load resource: the server responded with a status of 429 (Too Many Requests)',url:e.url})).sort());expect(csp).toEqual([]);
  // Close through the public lifecycle so autosaves and display readers settle
  // before the fixture navigates away and removes its owned storage.
  await click(page,'Close document');await expect(page.getByRole('contentinfo')).toContainText('No document checkpoint');await displayAborts.settle(page);
 }catch(error){await publicMode('failure-before-cleanup');try{await writeFile(join(receipt,scenario+'-failure-dom.html'),await page.content());}catch(diagnostic){publicModes.push({label:'failure-dom-unavailable',error:String(diagnostic)});}throw error;}finally{phase='teardown';try{effects??=await server.effects();}finally{try{for(const p of context.pages())await p.goto('about:blank');await guard.cleanup();guard.verify();}finally{await Promise.all(responseWork);await writeFile(join(receipt,scenario+'-ownership.json'),JSON.stringify(guard.ledger,null,2));await writeFile(join(receipt,scenario+'-observations.json'),JSON.stringify({origin:server.origin,browserName,browserRuntime,publicModes,errors,consoleErrors,csp,commands,requests,failedResponses,requestFailures,displayAborts:displayAborts(),displayAbortObservations:displayAborts.observations(),downloadProofs,responseBodies,classifications:requestFailures.map(e=>({requestId:e.requestId,reason:expectedCompositionCancellation(e,server.origin,browserName,downloadProofs,displayAborts())})),effects,destination:scenario==='raw'?'Actual fallback download; OS picker deliberately unavailable in this fixture; external destination unconfirmed':'not exercised'},null,2));await server.close();}}}
 expect(errors).toEqual([]);expect(consoleErrors.map(e=>JSON.stringify(e)).sort()).toEqual(failedResponses.filter((e:any)=>expectedDisplayBusy(e,server.origin,displayAborts())).map((e:any)=>JSON.stringify({text:'Failed to load resource: the server responded with a status of 429 (Too Many Requests)',url:e.url})).sort());expect(csp).toEqual([]);expect(failedResponses.filter((e:any)=>!expectedDisplayBusy(e,server.origin,displayAborts()))).toEqual([]);expect(requestFailures.filter(e=>!expectedCompositionCancellation(e,server.origin,browserName,downloadProofs,displayAborts()))).toEqual([]);
});
