import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {transformWithOxc} from 'vite';
import {isolatedDiagnosticModules} from '../owned-preview-module.mjs';

const data=code=>'data:text/javascript;base64,'+Buffer.from(code).toString('base64');
const sourceRoot=process.env.COMPOSITION_STAGED_ROOT??process.env.IE_DISPLAY_SOURCE_ROOT??'.';
const correctionRoot=process.env.COMPOSITION_CORRECTION_ROOT??process.env.COMPOSITION_CORRECTIONS_ROOT??process.env.IE_DISPLAY_CORRECTIONS_ROOT;
async function sourceText(path){for(const root of [correctionRoot,sourceRoot,'.'].filter((value,index,values)=>value&&values.indexOf(value)===index)){try{return await readFile(root+'/'+path,'utf8');}catch(error){if(error.code!=='ENOENT')throw error;}}throw Error('Missing fixture source: '+path);}
async function source(path,imports={}){let code=(await transformWithOxc(await sourceText(path),path)).code;for(const [specifier,url]of Object.entries(imports))code=code.replaceAll(JSON.stringify(specifier),JSON.stringify(url)).replaceAll("'"+specifier+"'",JSON.stringify(url));return data(code);}
// Keep deliberately sticky native-cancellation failures in this test file's
// own real ledger. They stay charged; no production cleanup state is reset.
const {allocationsURL:allocationURL,compositionObservationsURL:observationURL}=await isolatedDiagnosticModules();
const promptURL=await source('src/observability/prompt-memory.ts',{'./allocations.js':allocationURL});
const modelURL=await source('src/observability/model-memory.ts',{'./allocations.js':allocationURL,'./prompt-memory.js':promptURL}),{cloneOwnedModel}=await import(modelURL);
const controlURL=await source('src/state/control-memory.ts',{'../observability/allocations.js':allocationURL});
const draftURL=await source('src/state/draft-values.ts',{'../observability/allocations.js':allocationURL,'../observability/prompt-memory.js':promptURL,'../observability/model-memory.js':modelURL,'./control-memory.js':controlURL}),{DraftRegistrations}=await import(draftURL);
const lifetimeURL=await source('src/ui/composition-lifetime.ts');
const coreURL=await source('src/composition/core.ts'),jsonURL=await source('src/protocol/json.ts');
const compositionViewURL=await source('src/composition/view.ts');
const memoryURL=await source('src/composition/memory.ts',{'../observability/allocations.js':allocationURL,'../observability/prompt-memory.js':promptURL,'../observability/composition-observations.js':observationURL,'./view.js':compositionViewURL,'./core.js':coreURL});
const {emptyComposition}=await import(coreURL),{allocationLedger}=await import(allocationURL),{PromptReaderCleanupError,promptReaderCleanupFailures}=await import(promptURL);
const lit=data('export const nothing=null,noChange=Symbol.for("fixture.noChange");export function html(strings,...values){return {strings,values};}');
const color=data('export function parseColor(){throw Error("unused color path")} export function exportSRGB(){throw Error("unused color path")}');
const destination=data('export function chooseDestination(){throw Error("unused destination")}export function writeDestination(){throw Error("unused destination")}');
const phases=data('export const phaseCalls=[];export const browserPhases={recorder:{start(phase,context={}){const row={phase,context:structuredClone(context)};phaseCalls.push(row);let ended=false;return {end(outcome="ok",addition={}){if(ended)return;ended=true;row.outcome=outcome;Object.assign(row.context,structuredClone(addition));return row;}};}}};');
const {phaseCalls}=await import(phases);
const adapter=data((await transformWithOxc(await readFile('src/ui/adapters.ts','utf8'),'adapters.ts')).code);
async function load(path,current=false){
 let code=(await transformWithOxc(await(current?sourceText(path):readFile(path,'utf8')),'composition.ts')).code;
 for(const [specifier,url]of Object.entries({'lit':lit,'@en-reve/elements/color-picker.js':color,'../request/core.js':pathToFileURL(resolve('dist/local/src/request/core.js')).href,'../observability/composition-observations.js':observationURL,'../state/destination.js':destination,'../observability/browser.js':phases,'./adapters.js':adapter,'./composition-lifetime.js':lifetimeURL,'../protocol/json.js':jsonURL,'../composition/core.js':coreURL,'../composition/memory.js':memoryURL,'../observability/prompt-memory.js':promptURL}))code=code.replaceAll(JSON.stringify(specifier),JSON.stringify(url)).replaceAll("'"+specifier+"'",JSON.stringify(url));
 return (await import(data(code))).CompositionEditing;
}
const Current=await load('src/ui/composition.ts',true);
const controllers=new Set(),gates=new Set(),expectedCleanupFailures=new Set(),checkpointDisposers=new Set(),registrationDisposers=new Set();
const flush=async()=>{for(let i=0;i<64;i++)await Promise.resolve();};
const bytes=new TextEncoder();
function rawResponse(value='{}'){const body=typeof value==='string'?bytes.encode(value):value;return new Response(body,{headers:{'content-length':String(body.byteLength),'content-type':'application/json'}});}
const jsonResponse=value=>rawResponse(JSON.stringify(value));
function expectedCleanup(error){assert(error instanceof PromptReaderCleanupError);assert.equal(error.cancellationFailed,true);assert(error.resource.response instanceof Response);assert(error.resource.retainedReader);assert(error.resource.lease);expectedCleanupFailures.add(error);return error;}
function isExpectedCleanup(error){return expectedCleanupFailures.has(error)||error instanceof AggregateError&&error.errors.length>0&&error.errors.every(isExpectedCleanup);}
const allocationBaseline=allocationLedger.snapshot();
function retainedAllocations(){const snapshot=allocationLedger.snapshot();return {records:snapshot.activeRecords-allocationBaseline.activeRecords,cpu:snapshot.cpuBytes-allocationBaseline.cpuBytes,prompt:snapshot.promptBytes-allocationBaseline.promptBytes,handles:snapshot.handles-allocationBaseline.handles,unused:snapshot.unusedHandles-allocationBaseline.unusedHandles};}
test.afterEach(async()=>{
 const releases=[...controllers].map(controller=>Promise.resolve(controller.dispose()));for(const gate of gates)gate.reject(new DOMException('Fixture released.','AbortError'));
 const outcomes=await Promise.allSettled(releases);controllers.clear();
 for(const release of checkpointDisposers)release();checkpointDisposers.clear();
 const registrationOutcomes=await Promise.allSettled([...registrationDisposers].map(release=>release()));registrationDisposers.clear();
 for(const result of registrationOutcomes)assert.equal(result.status,'fulfilled',result.reason?.stack);
 for(const result of outcomes)if(result.status==='rejected')assert(isExpectedCleanup(result.reason),'Unexpected controller cleanup failure: '+result.reason);
 assert.deepEqual(new Set(promptReaderCleanupFailures()),expectedCleanupFailures);
 const retained=expectedCleanupFailures.size;
 assert.deepEqual(retainedAllocations(),{records:retained,cpu:retained*2,prompt:retained*2,handles:retained*2,unused:retained*2});
});
function field(template,id){if(!template||typeof template!=='object')return null;if(template.strings?.[0].includes('<en-textarea id=')&&template.values[0]===id)return template;for(const v of Array.isArray(template)?template:template.values??[]){const found=field(v,id);if(found)return found;}return null;}
function fixture(Controller){
 const registrations=new DraftRegistrations();registrationDisposers.add(async()=>{registrations.dispose();assert.equal(registrations.inspect().editableBorrowers,0,'Controller failed to drain draft registrations');await registrations.drain();});
 const raw={hash:'sha256:'+'1'.repeat(64),byteLength:'2',mediaType:'application/json'},doc={id:'document',revision:'1',width:360,height:200},value=emptyComposition(360,200,crypto.randomUUID());value.scene='Original raw';
 const saved=[],pending=[];let rendered,instance;
 // Historical controllers call the scripted JSON supplier directly. The
 // staged controller reaches it only through transport and the real bounded
 // response parser, retaining the same deferred owner-transition scenarios.
 const editor={sessionId:'session',draftOwner:{drafts:new Map(),refuseChange:(id,doc)=>registrations.refuse(id,doc)},registerDraft(id,doc){this.draftOwner.refuseChange=(id,doc)=>registrations.refuse(id,doc);return registrations.register(id,doc);},view:{ready:true,document:doc},ui:{drafts:[]},json:async()=>({composition:structuredClone(value),layers:[],bindings:{},revision:editor.view.document.revision}),session:{identity:()=> 'client-A',transport(path,init){if(!new URL(path,'http://127.0.0.1').searchParams.has('raw'))return Promise.resolve().then(()=>editor.json(path)).then(jsonResponse);const gate=deferred();pending.push({path,init,resolve:gate.resolve,reject:gate.reject});return gate.promise;}},changeDraft:(id,kind,text,target,composing,revision)=>{saved.push({id,kind,graph:JSON.parse(text),revision});registrations.delete(id);}};
 // Empty UI is a fixed fixture literal. Published saved checkpoints use the
 // actual model owner, including pins that survive replacement during restore.
 let checkpoint,ui=editor.ui;
 Object.defineProperty(editor,'ui',{get:()=>ui,set(value){const next=value&&!(Object.keys(value).length===1&&Array.isArray(value.drafts)&&value.drafts.length===0)?cloneOwnedModel('composition-fixture-checkpoint',value):undefined;const old=checkpoint;checkpoint=next;ui=next?next.value:value;old?.release();}});
 editor.pinUI=()=>checkpoint?checkpoint.pin():()=>{};
 const releaseCheckpoint=()=>{checkpoint?.release();checkpoint=undefined;ui=undefined;};
 checkpointDisposers.add(releaseCheckpoint);
 const presentations=[];
 // Scalar snapshots observe both cleared state at request and actual template
 // publication; they retain no retired graph, string payload or owner.
 const presentation=(update,phase)=>presentations.push({update,phase,models:instance.lifecycle.models,base:instance.base!==null,layers:instance.layers.length,bindings:Object.keys(instance.bindings).length,rawResult:instance.rawResult!==null,sourceRaw:instance.sourceRaw!==null,convertResult:instance.convertResult!==null,convertOpen:instance.convertOpen,conversion:instance.conversion!==null,rawCharacters:instance.lifecycle.rawCharacters,rawInspected:instance.rawInspected.length,issues:instance.issues.length,message:instance.message.length,...(phase==='render'?{scene:field(rendered,'composition-scene')!==null}:{})});
 const host={updates:0,requestUpdate(){const update=++this.updates;presentation(update,'request');this.updateComplete=Promise.resolve().then(()=>{rendered=instance.request();presentation(update,'render');});},updateComplete:Promise.resolve(),querySelector(){return null;}};
 instance=new Controller(host,editor,()=>{},()=>{},async()=>{},()=>{});controllers.add(instance);
 const input=async(handler,value)=>{const target={value,isConnected:true};handler({currentTarget:target,composedPath:()=>[target],detail:{isComposing:false},defaultPrevented:false,preventDefault(){this.defaultPrevented=true;}});await flush();};
 return {instance,editor,value,raw,saved,pending,host,input,presentations,rendered:()=>rendered,scene:()=>field(rendered,'composition-scene'),async initial(){await instance.sync();await flush();assert(this.scene());},async hold(raws=[raw]){value.raw=raws;editor.view.document={...doc,revision:'2'};const completion=instance.sync();await flush();assert.equal(pending.length,1);return {completion};},async finish(completion){pending.shift().resolve(rawResponse());await flush();assert.equal(pending.length,1);pending.shift().resolve(rawResponse());await completion;await flush();}};
}
for(const [label,Controller,expected]of [['corrected',Current,'Desired']])test('actual '+label+' controller saves its rendered Scene during pending raw inspection',async()=>{const f=fixture(Controller);await f.initial();const {completion}=await f.hold();await f.input(f.scene().values.at(-1),'Desired');assert.equal(f.saved.at(-1).graph.composition.scene,expected);await f.finish(completion);assert.equal(f.saved.at(-1).graph.composition.scene,expected);assert.equal(f.instance.c.scene,expected);});
for(const change of ['document','session','owner','disposed'])test('late rendered Scene callback cannot write '+change+' owner',async()=>{const f=fixture(Current);await f.initial();const callback=f.scene().values.at(-1),model=f.instance.c;if(change==='document')f.editor.view.document={...f.editor.view.document,id:'new-document'};if(change==='session')f.editor.sessionId='new-session';if(change==='owner')f.editor.draftOwner={drafts:new Map()};if(change==='disposed')f.instance.dispose();await f.input(callback,'Foreign');assert.equal(f.saved.length,0);assert.equal(model.scene,'Original raw');assert.equal(f.instance.c,change==='disposed'?null:model);});
for(const change of ['document','session','owner','disposed'])test('queued field settlement rejects changed '+change+' ownership',async()=>{const f=fixture(Current);await f.initial();const callback=f.scene().values.at(-1),model=f.instance.c,ev=event('Foreign');callback(ev);if(change==='document')f.editor.view.document={...f.editor.view.document,id:'new-document'};if(change==='session')f.editor.sessionId='new-session';if(change==='owner')f.editor.draftOwner={drafts:new Map()};if(change==='disposed')f.instance.dispose();await flush();if(change!=='disposed')assert.equal(ev.defaultPrevented,true);assert.equal(f.saved.length,0);assert.equal(model.scene,'Original raw');assert.equal(f.instance.c,change==='disposed'?null:model);});
test('late old raw response cannot overwrite a new document model or its public Scene',async()=>{const f=fixture(Current);await f.initial();const {completion}=await f.hold();const old=f.pending.shift();f.editor.view.document={...f.editor.view.document,id:'new-document',revision:'1'};f.value.raw=[];f.value.scene='New owner';await f.instance.sync();await flush();old.resolve(rawResponse());await completion;assert.equal(f.pending.length,0);await flush();assert.equal(f.instance.c.scene,'New owner');assert.equal(f.instance.rawText,'');assert.equal(f.scene().values[2],'New owner');assert.equal(f.saved.length,0);});

function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;}),gate={promise,resolve(value){gates.delete(gate);resolve(value);},reject(error){gates.delete(gate);reject(error);}};gates.add(gate);void promise.catch(()=>{});return gate;}
function event(value){const target={value,isConnected:true};return {currentTarget:target,composedPath:()=>[target],detail:{},defaultPrevented:false,preventDefault(){this.defaultPrevented=true;}};}
function changeOwner(f,change){if(change==='document')f.editor.view.document={...f.editor.view.document,id:'new-document'};if(change==='session')f.editor.sessionId='new-session';if(change==='owner')f.editor.draftOwner={drafts:new Map()};if(change==='disposed')return f.instance.dispose();}
async function assertOwnerSettlement(f,change,updates,disposal){
 if(change!=='disposed'){assert.equal(f.host.updates,updates);return;}
 // Retirement must finish its actual host render before releasing the old
 // payloads. A cleanup render is allowed only while the public state is empty.
 assert(disposal instanceof Promise);await disposal;await f.host.updateComplete;await flush();
 const publications=f.presentations.filter(row=>row.update>=updates);
 assert(publications.some(row=>row.phase==='render'),'Disposal must publish its cleared view');
 for(const row of publications){const {update,phase,scene,...state}=row;assert.deepEqual(state,{models:0,base:false,layers:0,bindings:0,rawResult:false,sourceRaw:false,convertResult:false,convertOpen:false,conversion:false,rawCharacters:0,rawInspected:0,issues:0,message:0},'Retired state was republished at '+update+' '+phase);if(phase==='render')assert.equal(scene,false,'Retired Scene was rendered');}
 assert.equal(f.scene(),null);assert.deepEqual(f.instance.lifecycle,{models:0,rawCharacters:0,pendingSettlements:0,pendingOperations:0,pendingPins:0,cleanupFailures:0,owners:0,retiredOwners:0,queuedActions:0});
 const complete=f.host.updates;await flush();assert.equal(f.host.updates,complete,'Disposed controller requested another update after drain');
}
function templateWhere(t,predicate){if(!t||typeof t!=='object')return null;if(t.strings&&predicate(t))return t;for(const v of Array.isArray(t)?t:t.values??[]){const found=templateWhere(v,predicate);if(found)return found;}return null;}
function inline(f,control){const t=templateWhere(f.rendered(),t=>t.strings[0].includes(control==='prompt'?'<en-segmented-control id="composition-mode" label="Prompt source"':'<en-select id="composition-raw-source" label="Retained raw source"'));assert(t);return t.values[control==='prompt'?2:1];}
for(const [name,Controller,kept]of [['corrected',Current,true]])test(name+' resolves queued real Scene proposal before clean sync replacement',async()=>{
 const f=fixture(Controller);await f.initial();const callback=f.scene().values.at(-1),model=f.instance.c,base=f.instance.base,gate=deferred();
 f.editor.view.document={...f.editor.view.document,revision:'2'};f.editor.json=()=>gate.promise;const pending=f.instance.sync();
 const accepted=structuredClone(f.value);accepted.scene='New accepted';gate.resolve({composition:accepted,layers:[],bindings:{},revision:'2'});
 callback(event('Queued desired'));await pending;await flush();
 assert.equal(f.saved.length,kept?1:0);assert.equal(f.instance.accepted.scene,'New accepted');
 if(kept){assert.equal(f.instance.c,model);assert.equal(f.instance.base,base);assert.equal(f.saved[0].graph.composition.scene,'Queued desired');assert.equal(f.saved[0].revision,'1');assert.equal(f.scene().values[2],'Queued desired');assert.equal(f.instance.dirty,true);assert.throws(()=>f.instance.validate(),/Review the current document/);}
 else assert.equal(f.instance.c.scene,'New accepted');
});
test('cancelled queued proposal does not prevent owned clean synchronization',async()=>{const f=fixture(Current);await f.initial();const gate=deferred(),callback=f.scene().values.at(-1);f.editor.view.document={...f.editor.view.document,revision:'2'};f.editor.json=()=>gate.promise;const pending=f.instance.sync();gate.resolve({composition:structuredClone(f.value),layers:[],bindings:{},revision:'2'});const ev=event('Vetoed');callback(ev);ev.defaultPrevented=true;await pending;await flush();assert.equal(f.saved.length,0);assert.equal(f.instance.base.revision,'2');assert.equal(f.instance.c.scene,'Original raw');});
async function rawStage(f,stage){const {completion}=await f.hold();const outcome=completion.then(()=>({resolved:true}),error=>({error}));let gate=f.pending.shift();
 if(stage==='page-response')return {gate,outcome};
 if(stage==='page-body'){const body=pendingBody();gate.resolve(body.response);await flush();return {gate:body.gate,outcome};}
 gate.resolve(rawResponse());await flush();gate=f.pending.shift();assert(gate);
 if(stage==='full-response')return {gate,outcome};
 const body=pendingBody();gate.resolve(body.response);await flush();return {gate:body.gate,outcome};
}
function pendingBody(){
 const gate=deferred();let canceled=false;
 const response=new Response(new ReadableStream({start(controller){void gate.promise.then(value=>{if(!canceled){controller.enqueue(new Uint8Array(value));controller.close();}},error=>{if(!canceled)controller.error(error);});},cancel(){canceled=true;}}),{headers:{'content-length':'2','content-type':'application/json'}});
 return {gate,response};
}
for(const change of ['document','session','owner','disposed'])for(const stage of ['page-response','page-body','full-response','full-body'])for(const failure of [false,true])test('raw '+stage+' '+(failure?'rejection':'success')+' refuses '+change+' before any new sync',async()=>{
 const f=fixture(Current);await f.initial();const {gate,outcome}=await rawStage(f,stage),model=f.instance.c,hash=model.raw[0].hash,token=f.instance.rawRead,disposal=changeOwner(f,change);const updates=f.host.updates;
 const failureValue=Error('late raw failure');if(failure)gate.reject(failureValue);else gate.resolve(stage.endsWith('body')?new TextEncoder().encode('{}').buffer:rawResponse());
 const result=await outcome;
 // Matching native read/closed errors prove terminal stream failure. Unlock
 // still completes, and stale owner errors cannot mutate or revive that model.
 assert.deepEqual(result,{resolved:true});
 await flush();assert.equal(f.pending.length,0);assert.equal(f.instance.c,change==='disposed'?null:model);assert.equal(model.raw[0].hash,hash);if(change!=='disposed')assert.equal(f.instance.rawRead,token);assert.equal(f.instance.rawText,'');assert.equal(f.instance.rawResult,null);assert.equal(f.instance.rawInspected,'');assert.equal(f.saved.length,0);await assertOwnerSettlement(f,change,updates,disposal);
});
for(const stage of ['page-response','page-body','full-response','full-body'])test('current-owner raw '+stage+' rejection still fails',async()=>{const f=fixture(Current);await f.initial();const {gate,outcome}=await rawStage(f,stage),failure=Error('owned raw error');gate.reject(failure);const r=await outcome;assert.equal(r.error,failure);assert.equal(f.instance.rawText,'');assert.equal(f.saved.length,0);});
for(const change of ['document','session','owner','disposed'])for(const failure of [false,true])test('late sync JSON '+(failure?'rejection':'success')+' refuses '+change+' without successor sync',async()=>{const f=fixture(Current);await f.initial();const gate=deferred(),before=f.instance.c;f.editor.view.document={...f.editor.view.document,revision:'2'};f.editor.json=()=>gate.promise;const pending=f.instance.sync(),disposal=changeOwner(f,change);const updates=f.host.updates;if(failure)gate.reject(Error('old sync failure'));else gate.resolve({composition:structuredClone(f.value),layers:[],bindings:{},revision:'2'});await pending;assert.equal(f.instance.c,change==='disposed'?null:before);await assertOwnerSettlement(f,change,updates,disposal);assert.equal(f.saved.length,0);});
test('current-owner sync JSON error still fails',async()=>{const f=fixture(Current);await f.initial();f.editor.view.document={...f.editor.view.document,revision:'2'};f.editor.json=async()=>{throw Error('owned sync failure');};await assert.rejects(f.instance.sync(),/owned sync failure/);});
for(const change of ['document','session','owner','disposed'])test('old restored-draft error refuses '+change+' before successor sync',async()=>{const f=fixture(Current);await f.initial();f.editor.sessionId='restoring-session';f.editor.ui={...f.editor.ui,drafts:[{id:'saved-draft',kind:'composition',documentId:'document',status:'saved-unapplied',generation:1,expectedDocumentRevision:'1'}]};const gate=deferred();let calls=0;f.editor.json=()=>++calls===1?Promise.resolve({composition:structuredClone(f.value),layers:[],bindings:{},revision:'1'}):gate.promise;const pending=f.instance.sync();await flush();assert.equal(calls,2);const disposal=changeOwner(f,change),updates=f.host.updates;gate.reject(Error('old restore error'));await pending;await assertOwnerSettlement(f,change,updates,disposal);assert.equal(f.saved.length,0);});
for(const control of ['prompt','raw'])for(const change of ['document','session','owner','disposed'])for(const queued of [false,true])test(control+' actual rendered callback refuses '+change+(queued?' after queueing':' before dispatch'),async()=>{const f=fixture(Current);await f.initial();const {completion}=await f.hold();await f.finish(completion);const callback=inline(f,control),view=f.instance.view,index=f.instance.rawIndex,model=f.instance.c,ev=event(control==='prompt'?'composition':'0');if(queued)callback(ev);changeOwner(f,change);if(!queued)callback(ev);await flush();assert.equal(f.saved.length,0);assert.equal(f.instance.c,change==='disposed'?null:model);assert.equal(f.instance.view,view);assert.equal(f.instance.rawIndex,index);assert.equal(f.pending.length,0);});
for(const control of ['prompt','raw'])test(control+' same-owner actual rendered settlement remains enabled',async()=>{const f=fixture(Current);await f.initial();const {completion}=await f.hold();await f.finish(completion);const accepted=JSON.stringify(f.instance.accepted);await f.input(inline(f,control),control==='prompt'?'composition':'0');assert.equal(f.saved.length,1);assert.equal(JSON.stringify(f.instance.accepted),accepted);assert.equal(f.saved[0].revision,'2');if(control==='prompt')assert.equal(f.saved[0].graph.view,'composition');else{assert.equal(f.pending.length,1);f.pending.shift().resolve(rawResponse());await flush();assert.equal(f.instance.rawText,'{}');}});
test('model ownership survives a render after owner transition before sync',async()=>{const f=fixture(Current);await f.initial();f.editor.draftOwner={drafts:new Map()};f.host.requestUpdate();await flush();await f.input(f.scene().values.at(-1),'Foreign');assert.equal(f.saved.length,0);assert.equal(f.instance.c.scene,'Original raw');await f.instance.sync();await flush();await f.input(f.scene().values.at(-1),'New owner edit');assert.equal(f.saved.at(-1).graph.composition.scene,'New owner edit');});

test('successor actual owner starts same-key sync while old raw is pending',async()=>{const f=fixture(Current);await f.initial();const {completion}=await f.hold(),old=f.pending.shift(),gate=deferred();f.editor.draftOwner={drafts:new Map()};f.editor.json=()=>gate.promise;const successor=f.instance.sync();old.resolve(rawResponse());await completion;assert.notEqual(f.instance.loading,'');gate.resolve({composition:{...structuredClone(f.value),scene:'Successor',raw:[]},layers:[],bindings:{},revision:'2'});await successor;await flush();assert.equal(f.instance.c.scene,'Successor');assert.equal(f.instance.loading,'');assert.equal(f.pending.length,0);await f.input(f.scene().values.at(-1),'Successor edit');assert.equal(f.saved.at(-1).graph.composition.scene,'Successor edit');});

async function restoring(Controller){const f=fixture(Controller);await f.initial();f.editor.sessionId='restoring-session';f.editor.view.document={...f.editor.view.document,revision:'2'};f.editor.ui={...f.editor.ui,drafts:[{id:'saved-draft',kind:'composition',documentId:'document',status:'saved-unapplied',generation:1,expectedDocumentRevision:'1'}]};const gate=deferred();let calls=0;f.editor.json=()=>++calls===1?Promise.resolve({composition:structuredClone(f.value),layers:[],bindings:{},revision:'2'}):gate.promise;const completion=f.instance.sync();await flush();assert.equal(calls,2);f.host.requestUpdate();await flush();const graph={composition:{...structuredClone(f.value),scene:'Saved stale draft'},view:'composition'},result={graph,bindings:{}};return {f,gate,completion,result};}
for(const [name,Controller,kept]of [['final correction',Current,true]])test(name+' retains queued rendered Scene at saved-draft replacement',async()=>{const {f,gate,completion,result}=await restoring(Controller),model=f.instance.c,base=f.instance.base,accepted=JSON.stringify(f.instance.accepted);gate.resolve(result);f.scene().values.at(-1)(event('Edit during restore'));await completion;await flush();assert.equal(f.saved.length,kept?1:0);assert.equal(JSON.stringify(f.instance.accepted),accepted);if(kept){assert.equal(f.instance.c,model);assert.equal(f.instance.base,base);assert.equal(f.saved[0].revision,'2');assert.equal(f.saved[0].graph.composition.scene,'Edit during restore');assert.equal(f.scene().values[2],'Edit during restore');}else assert.equal(f.instance.c.scene,'Saved stale draft');});
test('vetoed queued Scene permits saved stale draft restore without automatic rebase',async()=>{const {f,gate,completion,result}=await restoring(Current);gate.resolve(result);const ev=event('Vetoed restore edit');f.scene().values.at(-1)(ev);ev.defaultPrevented=true;await completion;await flush();assert.equal(f.saved.length,0);assert.equal(f.instance.c.scene,'Saved stale draft');assert.equal(f.instance.base.revision,'1');assert.throws(()=>f.instance.validate(),/Review the current document/);});
for(const change of ['document','session','owner','disposed'])test('saved-draft boundary rechecks '+change+' after queued settlement',async()=>{const {f,gate,completion,result}=await restoring(Current),model=f.instance.c;gate.resolve(result);f.scene().values.at(-1)(event('Foreign restore edit'));changeOwner(f,change);await completion;await flush();assert.equal(f.saved.length,0);assert.equal(f.instance.c,change==='disposed'?null:model);assert.equal(model.scene,'Original raw');});

test('second owned proposal dispatched during a vetoed-settlement wait survives replacement',async()=>{const f=fixture(Current);await f.initial();const gate=deferred(),callback=f.scene().values.at(-1);f.editor.view.document={...f.editor.view.document,revision:'2'};f.editor.json=()=>gate.promise;const completion=f.instance.sync();gate.resolve({composition:structuredClone(f.value),layers:[],bindings:{},revision:'2'});const first=event('Vetoed first');callback(first);first.defaultPrevented=true;queueMicrotask(()=>queueMicrotask(()=>callback(event('Second desired'))));await completion;await flush();assert.equal(f.saved.at(-1)?.graph.composition.scene,'Second desired');assert.equal(f.saved.at(-1)?.revision,'1');});

test('second owned proposal dispatched during restore settlement wait keeps its original base',async()=>{const {f,gate,completion,result}=await restoring(Current),callback=f.scene().values.at(-1);gate.resolve(result);const first=event('Vetoed first');callback(first);first.defaultPrevented=true;queueMicrotask(()=>queueMicrotask(()=>callback(event('Second restore edit'))));await completion;await flush();assert.equal(f.saved.at(-1)?.graph.composition.scene,'Second restore edit');assert.equal(f.saved.at(-1)?.revision,'2');assert.equal(f.instance.base.revision,'2');assert.equal(f.instance.c.scene,'Second restore edit');});

// Actual controller + actual ControlAdapter; Lit and the proposal host remain
// explicit NON-BROWSER stand-ins. This does not observe native checked radios.
test('initial mode callback causal agreement',async()=>{
 const f=fixture(Current);f.host.requestUpdate();await flush();assert.equal(f.instance.c,null);const callback=inline(f,'prompt'),before={view:f.instance.view,template:templateWhere(f.rendered(),t=>t.strings[0].includes('<en-segmented-control id="composition-mode" label="Prompt source"')).values[0]};
 await f.initial();const model=f.instance.c,accepted=JSON.stringify(f.instance.accepted),ev=event('composition');callback(ev);await flush();const template=templateWhere(f.instance.request(),t=>t.strings[0].includes('<en-segmented-control id="composition-mode" label="Prompt source"'));
 const result={scope:'NON-BROWSER actual controller/adapter with Lit and host stand-ins; no historical467 cause or native-radio proof',phase:process.env.COMPOSITION_MODE_PHASE??'green',before,host:ev.currentTarget.value,controller:f.instance.view,template:template.values[0],prevented:ev.defaultPrevented,saves:f.saved,modelRetained:f.instance.c===model,acceptedUnchanged:JSON.stringify(f.instance.accepted)===accepted};
 result.verifiedRed=result.phase==='red'&&result.host==='composition'&&result.controller==='plain'&&result.template==='plain'&&!result.prevented&&result.saves.length===0&&result.modelRetained&&result.acceptedUnchanged;
 if(process.env.EDITOR_RECEIPT){await mkdir(process.env.EDITOR_RECEIPT,{recursive:true});await writeFile(resolve(process.env.EDITOR_RECEIPT,'mode-causal.json'),JSON.stringify(result,null,2),{flag:'wx'});}
 if(result.phase==='red')assert.equal(result.verifiedRed,true,'Only exact staged-host/controller/template mismatch is VERIFIED-RED');else{assert.equal(result.host,'composition');assert.equal(result.controller,'composition');assert.equal(result.template,'composition');assert.equal(result.prevented,false);assert.equal(result.saves.length,1);assert.equal(result.saves[0].graph.view,'composition');assert.equal(result.saves[0].graph.composition.id,model.id);}
 assert(result.modelRetained&&result.acceptedUnchanged);
});

for(const change of ['document','session','owner','disposed'])for(const queued of [false,true])test('mode refusal reconciles staged host '+change+' '+queued,async()=>{
 const f=fixture(Current);await f.initial();const callback=inline(f,'prompt'),model=f.instance.c,acceptedModel=f.instance.accepted,accepted=JSON.stringify(acceptedModel),ev=event('composition');if(queued)callback(ev);changeOwner(f,change);if(!queued)callback(ev);await flush();assert.equal(ev.defaultPrevented,true);assert.equal(ev.currentTarget.value,f.instance.view);assert.equal(f.instance.view,'plain');assert.equal(f.saved.length,0);assert.equal(f.instance.c,change==='disposed'?null:model);assert.equal(JSON.stringify(acceptedModel),accepted);assert.equal(f.instance.accepted,change==='disposed'?null:acceptedModel);
});
test('current navigation after owner render never saves the foreign model',async()=>{const f=fixture(Current);await f.initial();const model=f.instance.c;changeOwner(f,'owner');f.host.requestUpdate();await flush();const ev=event('composition');inline(f,'prompt')(ev);await flush();assert.equal(f.instance.view,'composition');assert.equal(ev.currentTarget.value,'composition');assert.equal(templateWhere(f.rendered(),t=>t.strings[0].includes('<en-segmented-control id="composition-mode" label="Prompt source"')).values[0],'composition');assert.equal(f.instance.c,model);assert.equal(f.saved.length,0);});
test('same-owner replacement saves only the current model and draft',async()=>{const f=fixture(Current);await f.initial();const callback=inline(f,'prompt'),old=f.instance.c;f.editor.view.document={...f.editor.view.document,revision:'2'};f.value.scene='New accepted model';await f.instance.sync();await flush();const current=f.instance.c,draft=f.instance.draftId;assert.notEqual(current,old);await f.input(callback,'composition');assert.equal(f.saved.length,1);assert.equal(f.saved[0].id,draft);assert.equal(f.saved[0].revision,'2');assert.equal(f.saved[0].graph.composition.scene,'New accepted model');assert.equal(old.scene,'Original raw');});
test('mode adapter keeps veto and latest proposal semantics',async()=>{const f=fixture(Current);await f.initial();const callback=inline(f,'prompt'),ev=event('composition');callback(ev);ev.preventDefault();ev.currentTarget.value='plain';await flush();assert.equal(f.instance.view,'plain');assert.equal(f.saved.length,0);const first=event('composition'),second={...first};callback(first);first.currentTarget.value='plain';callback(second);await flush();assert.equal(f.instance.view,'plain');assert.equal(f.saved.length,1);assert.equal(f.saved[0].graph.view,'plain');});
for(const value of ['invalid','',null])test('invalid mode reconciles without save '+value,async()=>{const f=fixture(Current);await f.initial();const ev=event(value);inline(f,'prompt')(ev);await flush();assert(ev.defaultPrevented);assert.equal(ev.currentTarget.value,'plain');assert.equal(f.saved.length,0);});
test('disconnected mode proposal has no navigation or save',async()=>{const f=fixture(Current);await f.initial();const ev=event('composition');inline(f,'prompt')(ev);ev.currentTarget.isConnected=false;await flush();assert.equal(f.instance.view,'plain');assert.equal(f.saved.length,0);});

async function modeRestore(stage){
 const f=fixture(Current),first=deferred(),saved=deferred();f.editor.ui={...f.editor.ui,drafts:[{id:'saved-mode-draft',kind:'composition',documentId:'document',status:'saved-unapplied',generation:7,expectedDocumentRevision:'0'}]};let calls=0;f.editor.json=()=>++calls===1?first.promise:saved.promise;f.host.requestUpdate();await flush();const callback=inline(f,'prompt'),completion=f.instance.sync();
 const graph={composition:{...structuredClone(f.value),scene:'Saved domain content',background:'Preserve background'},view:'plain',selected:'saved-selection',numbers:{'request-width':'320'},color:'#123456',guides:false,rawText:'Retained draft text',rawIndex:2,rawOffset:32};const result={graph,bindings:{saved:'layer'}};
 if(stage==='interim'){first.resolve({composition:structuredClone(f.value),layers:[],bindings:{},revision:'1'});await flush();assert.equal(calls,2);assert.equal(f.instance.c.scene,'Original raw');f.host.requestUpdate();await flush();}
 return {f,first,saved,callback,completion,result,calls:()=>calls};
}
for(const stage of ['before-admission','interim'])test('mode intent during '+stage+' preserves saved graph and persists only its admitted identity',async()=>{
 const {f,first,saved,callback,completion,result}=await modeRestore(stage),generation=f.instance.generation;
 callback(event('composition'));await flush();assert.equal(f.instance.view,'composition');assert.equal(f.saved.length,0);assert.equal(f.instance.generation,generation);
 if(stage==='before-admission'){first.resolve({composition:structuredClone(f.value),layers:[],bindings:{},revision:'1'});await flush();}
 assert.equal(f.saved.length,0);saved.resolve(result);await completion;await flush();assert.deepEqual(f.instance.c,result.graph.composition);assert.equal(f.instance.accepted.scene,'Original raw');assert.equal(f.instance.view,'composition');assert.equal(f.instance.generation,generation);assert.equal(f.saved.length,1);assert.equal(f.saved[0].id,'saved-mode-draft');assert.equal(f.saved[0].revision,'0');assert.deepEqual(f.saved[0].graph,{...result.graph,view:'composition',bindings:result.bindings});assert.equal(f.scene().values[2],'Saved domain content');
});
test('latest current mode wins saved view without domain generation change',async()=>{const {f,saved,callback,completion,result}=await modeRestore('interim');callback(event('composition'));await flush();callback(event('plain'));await flush();const generation=f.instance.generation;result.graph.view='composition';saved.resolve(result);await completion;await flush();assert.equal(f.instance.view,'plain');assert.equal(f.instance.generation,generation);assert.equal(f.saved.length,1);assert.equal(f.saved[0].graph.view,'plain');assert.deepEqual(f.saved[0].graph.composition,result.graph.composition);});
for(const change of ['document','session','owner','disposed'])for(const stage of ['before-admission','interim'])test('pending mode restore rejects '+change+' during '+stage,async()=>{const {f,first,saved,callback,completion,result}=await modeRestore(stage);callback(event('composition'));await flush();const model=f.instance.c;changeOwner(f,change);first.resolve({composition:structuredClone(f.value),layers:[],bindings:{},revision:'1'});saved.resolve(result);await completion;await flush();assert.equal(f.instance.c,change==='disposed'?null:model);assert.equal(f.saved.length,0);});
test('replacement owner restores its own saved mode without old deferred intent',async()=>{const {f,saved,callback,completion,result}=await modeRestore('interim');callback(event('composition'));await flush();changeOwner(f,'owner');let calls=0;const next={graph:{...structuredClone(result.graph),view:'plain'},bindings:{}};next.graph.composition.scene='New owner saved';f.editor.json=async()=>++calls===1?{composition:structuredClone(f.value),layers:[],bindings:{},revision:'1'}:next;await f.instance.sync();saved.resolve(result);await completion;await flush();assert.equal(f.instance.view,'plain');assert.equal(f.instance.c.scene,'New owner saved');assert.equal(f.saved.length,0);});
test('queued disposed proposal cannot overwrite a newer owned mode proposal on the same host',async()=>{const f=fixture(Current);await f.initial();const old=inline(f,'prompt'),ev=event('composition');old(ev);f.instance.dispose();const fresh=f.instance.request().values[2];ev.currentTarget.value='plain';fresh({...ev});await flush();assert.equal(ev.currentTarget.value,'plain');assert.equal(f.instance.view,'plain');assert.equal(f.saved.length,0);});
test('disposed controller refuses fresh controls and sync cannot resurrect ownership after drain',async()=>{
 const f=fixture(Current);await f.initial();const conversionInput=()=>{const template=f.instance.dialog(),at=template.strings.findIndex(part=>part.includes('id="conversion-copy"'));assert.ok(at>=0);assert.ok(template.strings[at+1].includes('@en-input='));return template.values[at+1];};const oldScene=f.scene().values.at(-1),oldConversion=conversionInput(),before=retainedAllocations();
 await f.instance.dispose();const released=retainedAllocations();assert.equal(f.instance.c,null);assert.equal(f.instance.accepted,null);assert.equal(f.instance.ownsModel(),false);assert.ok(released.cpu<before.cpu);
 let reads=0;f.editor.json=async()=>{reads++;return {composition:structuredClone(f.value),layers:[],bindings:{},revision:'1'};};
 const mode=event('composition');f.instance.request().values[2](mode);const conversion=event('late conversion');oldConversion(conversion);const freshConversion=event('fresh disposed conversion');conversionInput()(freshConversion);oldScene(event('late Scene'));
 await f.instance.sync();await flush();assert(mode.defaultPrevented);assert(conversion.defaultPrevented);assert(freshConversion.defaultPrevented);assert.equal(mode.currentTarget.value,'plain');assert.equal(f.instance.view,'plain');assert.equal(reads,0);assert.equal(f.saved.length,0);assert.equal(f.instance.c,null);assert.equal(f.instance.accepted,null);assert.equal(f.instance.ownsModel(),false);assert.equal(f.instance.lifecycle.pendingOperations,0);assert.equal(f.instance.lifecycle.pendingSettlements,0);assert.deepEqual(retainedAllocations(),released);
});
test('failed saved read does not make interim graph eligible for mode persistence',async()=>{const {f,saved,callback,completion}=await modeRestore('interim');callback(event('composition'));await flush();saved.reject(Error('saved read failure'));await assert.rejects(completion,/saved read failure/);callback(event('plain'));await flush();assert.equal(f.saved.length,0);assert.equal(f.instance.c.scene,'Original raw');});

function bootstrapFixture(){
 const f=fixture(Current);f.editor.view={ready:false,document:null};f.editor.draftOwner=undefined;f.editor.ui=undefined;f.editor.owner='client-A';let identity='client-A';f.editor.session.identity=()=>identity;
 Object.defineProperty(f.editor,'sessionId',{configurable:true,get(){return this.ui?.sessionId??'editor_'+this.owner;}});
 return {...f,setIdentity(value){identity=value;}};
}
test('bootstrap causal batch uses actual retained and fresh mode callbacks',async()=>{
 const getter=(await readFile('src/state/editor-client.ts','utf8')).match(/get sessionId\(\) \{([^}]+)\}/)?.[1];assert.equal(getter?.trim(),"return this.ui?.sessionId ?? 'editor_' + this.owner;");
 const rows=[];
 for(const placement of ['before-dispatch','queued','fresh-contrast']){
  const f=bootstrapFixture();f.host.requestUpdate();await flush();const initialCallback=inline(f,'prompt'),localSession=f.editor.session,initial={ready:f.editor.view.ready,document:f.editor.view.document,sessionId:f.editor.sessionId,draftOwner:f.editor.draftOwner??null,identity:f.editor.session.identity(),model:f.instance.c,accepted:f.instance.accepted};const firstOwner={sessionId:'restored-ui',drafts:new Map()},ev=event('composition');
  if(placement==='queued')initialCallback(ev);
  f.editor.draftOwner=firstOwner;
  if(placement==='fresh-contrast'){f.host.requestUpdate();await flush();inline(f,'prompt')(ev);}else if(placement==='before-dispatch')initialCallback(ev);
  await flush();const t=templateWhere(f.instance.request(),t=>t.strings[0].includes('<en-segmented-control id="composition-mode" label="Prompt source"'));
  const row={placement,initial,transition:{sameSessionObject:f.editor.session===localSession,identity:f.editor.session.identity(),sessionId:f.editor.sessionId,firstOwnerInstalled:f.editor.draftOwner===firstOwner,ui:f.editor.ui??null,ready:f.editor.view.ready,document:f.editor.view.document},host:ev.currentTarget.value,controller:f.instance.view,template:t.values[0],veto:ev.defaultPrevented,modelUnchanged:f.instance.c===null,acceptedUnchanged:f.instance.accepted===null,saves:f.saved};rows.push(row);
  assert(row.transition.sameSessionObject&&row.transition.firstOwnerInstalled&&row.modelUnchanged&&row.acceptedUnchanged);assert.equal(row.transition.identity,'client-A');assert.equal(row.transition.sessionId,'editor_client-A');assert.equal(row.saves.length,0);
 }
 const red=process.env.COMPOSITION_BOOTSTRAP_PHASE==='red';const result={phase:red?'red':'green',scope:'Actual controller and actual adapter with source-matched EditorClient getter and explicit Lit/host/state stand-ins; not480 runtime cause or native keyboard proof',rows,verifiedRed:rows.slice(0,2).every(x=>x.host==='plain'&&x.controller==='plain'&&x.template==='plain'&&x.veto)&&rows[2].host==='composition'&&rows[2].controller==='composition'&&rows[2].template==='composition'&&!rows[2].veto};
 if(process.env.EDITOR_RECEIPT){await mkdir(process.env.EDITOR_RECEIPT,{recursive:true});await writeFile(resolve(process.env.EDITOR_RECEIPT,'bootstrap-causal.json'),JSON.stringify(result,null,2),{flag:'wx'});}
 if(red)assert.equal(result.verifiedRed,true,'Required exact initial-owner refusal and fresh-render contrast');else for(const row of rows){assert.equal(row.host,'composition');assert.equal(row.controller,'composition');assert.equal(row.template,'composition');assert.equal(row.veto,false);}
});

async function bootstrapRecovery(placement){
 const f=bootstrapFixture();f.host.requestUpdate();await flush();const callback=inline(f,'prompt'),gate=deferred(),owner={sessionId:'restored-ui',drafts:new Map()},document={id:'first-document',revision:'3',width:360,height:200};
 const graph={composition:{...structuredClone(f.value),scene:'Exact saved bootstrap graph',background:'Saved background'},view:'plain',selected:'retained-selection',numbers:{'request-width':'300'},color:'#ABCDEF',guides:false,rawText:'Retained original draft',rawIndex:2,rawOffset:32},result={graph,bindings:{saved:'layer'}},checkpoint={sessionId:'restored-ui',drafts:[{id:'saved-bootstrap',kind:'composition',documentId:document.id,status:'saved-unapplied',generation:7,expectedDocumentRevision:'2'}]};
 let reads=0;f.editor.json=()=>++reads===1?Promise.resolve({composition:structuredClone(f.value),layers:[],bindings:{},revision:'3'}):gate.promise;
 const ev=event('composition');if(placement==='intent-first'||placement==='queued')callback(ev);if(placement==='intent-first')await flush();f.editor.draftOwner=owner;f.editor.ui=checkpoint;f.editor.view={ready:true,document};if(placement==='before-dispatch')callback(ev);const completion=f.instance.sync();await flush();assert.equal(reads,2);assert.equal(f.instance.view,'composition');assert.equal(f.instance.c.scene,'Original raw');assert.equal(f.saved.length,0);assert.equal(f.instance.generation,0);
 return {f,gate,owner,document,callback,completion,result,ev};
}
for(const placement of ['intent-first','before-dispatch','queued'])test('complete initial admission '+placement+' preserves latest mode and exact saved ownership',async()=>{const {f,gate,owner,document,completion,result,ev}=await bootstrapRecovery(placement);assert.equal(ev.defaultPrevented,false);assert.equal(ev.currentTarget.value,'composition');gate.resolve(result);await completion;await flush();assert.equal(f.editor.draftOwner,owner);assert.equal(f.editor.sessionId,'restored-ui');assert.equal(f.editor.view.document,document);assert.deepEqual(f.instance.c,result.graph.composition);assert.equal(f.instance.accepted.scene,'Original raw');assert.equal(f.instance.generation,0);assert.equal(f.saved.length,1);assert.equal(f.saved[0].id,'saved-bootstrap');assert.equal(f.saved[0].revision,'2');assert.deepEqual(f.saved[0].graph,{...result.graph,view:'composition',bindings:result.bindings});});
test('latest bootstrap mode survives pending saved graph without interim writes',async()=>{const {f,gate,callback,completion,result}=await bootstrapRecovery('intent-first');callback(event('plain'));await flush();assert.equal(f.saved.length,0);result.graph.view='composition';gate.resolve(result);await completion;await flush();assert.equal(f.instance.view,'plain');assert.equal(f.saved.length,1);assert.equal(f.saved[0].graph.view,'plain');assert.deepEqual(f.saved[0].graph.composition,result.graph.composition);});
for(const boundary of ['identity','connection','document','session','owner','disposed'])test('bootstrap pending saved graph refuses replaced '+boundary,async()=>{const {f,gate,callback,completion,result}=await bootstrapRecovery('queued');const model=f.instance.c;if(boundary==='identity')f.setIdentity('client-B');else if(boundary==='connection')f.editor.session={...f.editor.session};else if(boundary==='session')f.editor.ui={...f.editor.ui,sessionId:'other-session'};else changeOwner(f,boundary);const ev=event('plain');callback(ev);await flush();assert(ev.defaultPrevented);assert.equal(f.saved.length,0);gate.resolve(result);await completion;await flush();assert.equal(f.saved.length,0);if(!['identity','connection'].includes(boundary))assert.equal(f.instance.c,boundary==='disposed'?null:model);assert.equal(f.instance.generation,boundary==='disposed'?1:0);});
for(const boundary of ['identity','connection','disposed'])for(const queued of [false,true])test('initial bootstrap callback refuses '+boundary+' '+queued,async()=>{const f=bootstrapFixture();f.host.requestUpdate();await flush();const callback=inline(f,'prompt'),ev=event('composition');if(queued)callback(ev);if(boundary==='identity')f.setIdentity('client-B');else if(boundary==='connection')f.editor.session={...f.editor.session};else f.instance.dispose();f.editor.draftOwner={sessionId:'other-ui',drafts:new Map()};if(!queued)callback(ev);await flush();assert(ev.defaultPrevented);assert.equal(f.instance.view,'plain');assert.equal(ev.currentTarget.value,'plain');assert.equal(f.saved.length,0);assert.equal(f.instance.c,null);});
test('established model cannot acquire bootstrap exemption after document disappears',async()=>{const f=fixture(Current);await f.initial();const model=f.instance.c;f.editor.view={ready:false,document:null};f.host.requestUpdate();await flush();const callback=inline(f,'prompt'),ev=event('composition');f.editor.draftOwner={sessionId:'replacement',drafts:new Map()};callback(ev);await flush();assert(ev.defaultPrevented);assert.equal(f.instance.view,'plain');assert.equal(f.instance.c,model);assert.equal(f.saved.length,0);});
test('first recovered document closes old bootstrap callback against later same-connection document changes',async()=>{const {f,gate,callback,completion,result}=await bootstrapRecovery('intent-first');gate.resolve(result);await completion;await flush();const count=f.saved.length;f.editor.view.document={...f.editor.view.document,id:'second-document'};const ev=event('plain');callback(ev);await flush();assert(ev.defaultPrevented);assert.equal(f.saved.length,count);assert.equal(f.instance.view,'composition');});
test('bootstrap saved-read failure keeps the interim graph ineligible for persistence',async()=>{const {f,gate,callback,completion}=await bootstrapRecovery('queued');gate.reject(Error('bootstrap saved read failure'));await assert.rejects(completion,/bootstrap saved read failure/);callback(event('plain'));await flush();assert.equal(f.saved.length,0);assert.equal(f.instance.c.scene,'Original raw');});

function firstAuthenticationFixture(){const f=bootstrapFixture();f.editor.owner=null;f.setIdentity(null);return f;}
test('first authentication causal batch preserves original actual callback observations',async()=>{
 const rows=[];
 for(const placement of ['before-dispatch','queued','fresh-contrast']){
  const f=firstAuthenticationFixture();f.host.requestUpdate();await flush();const callback=inline(f,'prompt'),connection=f.editor.session,initial={identity:f.editor.session.identity(),sessionId:f.editor.sessionId,owner:f.editor.owner,draftOwner:f.editor.draftOwner??null,document:f.editor.view.document,ready:f.editor.view.ready},ev=event('composition');
  if(placement==='queued')callback(ev);f.setIdentity('client-A');
  if(placement==='fresh-contrast'){f.host.requestUpdate();await flush();inline(f,'prompt')(ev);}else if(placement==='before-dispatch')callback(ev);
  await flush();const template=templateWhere(f.instance.request(),t=>t.strings[0].includes('<en-segmented-control id="composition-mode" label="Prompt source"')).values[0];
  rows.push({placement,initial,after:{identity:f.editor.session.identity(),sessionId:f.editor.sessionId,owner:f.editor.owner,sameConnection:f.editor.session===connection},host:ev.currentTarget.value,controller:f.instance.view,template,veto:ev.defaultPrevented,model:f.instance.c,accepted:f.instance.accepted,saves:[...f.saved]});
 }
 const red=process.env.COMPOSITION_AUTH_PHASE==='red',verifiedRed=rows.slice(0,2).every(x=>x.veto&&x.host==='plain'&&x.controller==='plain'&&x.template==='plain')&&!rows[2].veto&&rows[2].host==='composition'&&rows[2].controller==='composition'&&rows[2].template==='composition';
 const result={phase:red?'red':'green',scope:'Actual Composition controller and ControlAdapter, original retained callback with explicit host/state stand-ins and source-faithful owner=null/identity=null getter; no480 event-time or native keyboard claim',rows,verifiedRed};
 for(const row of rows){assert.deepEqual(row.initial,{identity:null,sessionId:'editor_null',owner:null,draftOwner:null,document:null,ready:false});assert.deepEqual(row.after,{identity:'client-A',sessionId:'editor_null',owner:null,sameConnection:true});assert.equal(row.model,null);assert.equal(row.accepted,null);assert.deepEqual(row.saves,[]);}
 if(process.env.EDITOR_RECEIPT){await mkdir(process.env.EDITOR_RECEIPT,{recursive:true});await writeFile(resolve(process.env.EDITOR_RECEIPT,'first-authentication-causal.json'),JSON.stringify(result,null,2),{flag:'wx'});}
 if(red)assert(verifiedRed,'Exact retained first-auth refusal with fresh callback contrast');else for(const row of rows){assert.equal(row.veto,false);assert.equal(row.host,'composition');assert.equal(row.controller,'composition');assert.equal(row.template,'composition');}
});

async function completeFirstAuthentication(placement){
 const f=firstAuthenticationFixture();f.host.requestUpdate();await flush();const callback=inline(f,'prompt'),ev=event('composition'),gate=deferred();
 assert.equal(f.editor.sessionId,'editor_null');assert.equal(f.editor.session.identity(),null);
 if(placement==='intent-first'||placement==='auth-queued')callback(ev);if(placement==='intent-first')await flush();assert.equal(f.saved.length,0);
 f.setIdentity('client-A');if(placement==='auth-before')callback(ev);if(['intent-first','auth-queued','auth-before'].includes(placement))await flush();assert.equal(f.saved.length,0);
 if(placement==='fallback-queued')callback(ev);f.editor.owner='client-A';assert.equal(f.editor.sessionId,'editor_client-A');if(placement==='fallback-before')callback(ev);if(placement.startsWith('fallback-'))await flush();assert.equal(f.saved.length,0);
 if(placement==='owner-queued')callback(ev);const owner={sessionId:'restored-ui',drafts:new Map()};f.editor.draftOwner=owner;if(placement==='owner-before')callback(ev);if(placement.startsWith('owner-'))await flush();assert.equal(f.saved.length,0);
 const document={id:'first-document',revision:'3',width:360,height:200},graph={composition:{...structuredClone(f.value),scene:'Full initial saved graph',background:'Preserved'},view:'plain',selected:'retained',numbers:{'request-width':'300'},color:'#ABCDEF',guides:false,rawText:'Original draft',rawIndex:2,rawOffset:32},result={graph,bindings:{saved:'layer'}};
 f.editor.ui={sessionId:owner.sessionId,drafts:[{id:'saved-initial',kind:'composition',documentId:document.id,status:'saved-unapplied',generation:7,expectedDocumentRevision:'2'}]};f.editor.view={ready:true,document};if(placement==='admission-before')callback(ev);
 let reads=0;f.editor.json=()=>++reads===1?Promise.resolve({composition:structuredClone(f.value),layers:[],bindings:{},revision:'3'}):gate.promise;const completion=f.instance.sync();await flush();assert.equal(reads,2);assert.equal(ev.defaultPrevented,false);assert.equal(f.instance.view,'composition');assert.equal(f.instance.generation,0);assert.equal(f.saved.length,0);assert.equal(f.instance.c.scene,'Original raw');
 return {f,callback,ev,owner,document,result,gate,completion};
}
for(const placement of ['intent-first','auth-before','auth-queued','fallback-before','fallback-queued','owner-before','owner-queued','admission-before'])test('full null identity and owner startup '+placement+' preserves exact saved graph',async()=>{const {f,owner,document,result,gate,completion}=await completeFirstAuthentication(placement);gate.resolve(result);await completion;await flush();assert.equal(f.editor.draftOwner,owner);assert.equal(f.editor.view.document,document);assert.equal(f.instance.view,'composition');assert.deepEqual(f.instance.c,result.graph.composition);assert.equal(f.saved.length,1);assert.deepEqual(f.saved[0],{id:'saved-initial',kind:'composition',graph:{...result.graph,view:'composition',bindings:result.bindings},revision:'2'});assert.equal(f.instance.generation,0);});
test('latest initial mode is reconciled only with the complete saved graph',async()=>{const {f,callback,result,gate,completion}=await completeFirstAuthentication('intent-first');callback(event('plain'));await flush();assert.equal(f.saved.length,0);result.graph.view='composition';gate.resolve(result);await completion;await flush();assert.equal(f.instance.view,'plain');assert.deepEqual(f.saved[0].graph,{...result.graph,view:'plain',bindings:result.bindings});});
for(const boundary of ['identity-B','identity-null','connection','session','owner','document','disposed'])for(const queued of [false,true])test('first established identity refuses '+boundary+' '+queued,async()=>{
 const f=firstAuthenticationFixture();f.host.requestUpdate();await flush();const callback=inline(f,'prompt');f.setIdentity('client-A');f.editor.owner='client-A';const owner={sessionId:'first-ui',drafts:new Map()};f.editor.draftOwner=owner;if(boundary==='document')f.editor.view.document={id:'first-doc'};callback(event('composition'));await flush();assert.equal(f.instance.view,'composition');const ev=event('plain');if(queued)callback(ev);
 if(boundary==='identity-B')f.setIdentity('client-B');else if(boundary==='identity-null')f.setIdentity(null);else if(boundary==='connection')f.editor.session={...f.editor.session};else if(boundary==='session')f.editor.ui={sessionId:'arbitrary-ui'};else if(boundary==='owner')f.editor.draftOwner={sessionId:'foreign-ui',drafts:new Map()};else if(boundary==='document')f.editor.view.document={id:'foreign-doc'};else f.instance.dispose();
 if(!queued)callback(ev);await flush();assert(ev.defaultPrevented);assert.equal(f.instance.view,'composition');assert.equal(ev.currentTarget.value,'composition');assert.equal(f.saved.length,0);assert.equal(f.instance.c,null);
});
for(const placement of ['before-dispatch','queued'])test('same identity fallback transition '+placement+' before first owner is allowed',async()=>{const f=firstAuthenticationFixture();f.setIdentity('client-A');f.host.requestUpdate();await flush();const callback=inline(f,'prompt'),ev=event('composition');if(placement==='queued')callback(ev);f.editor.owner='client-A';if(placement==='before-dispatch')callback(ev);await flush();assert.equal(ev.defaultPrevented,false);assert.equal(f.instance.view,'composition');assert.equal(f.saved.length,0);assert.equal(f.editor.draftOwner,undefined);});
for(const placement of ['before-dispatch','queued'])test('arbitrary fallback session '+placement+' is refused',async()=>{const f=firstAuthenticationFixture();f.setIdentity('client-A');f.host.requestUpdate();await flush();const callback=inline(f,'prompt'),ev=event('composition');if(placement==='queued')callback(ev);f.editor.owner='foreign-B';if(placement==='before-dispatch')callback(ev);await flush();assert(ev.defaultPrevented);assert.equal(f.instance.view,'plain');assert.equal(f.saved.length,0);});
for(const boundary of ['identity-B','identity-null','connection','session','owner','document','disposed'])test('full first-auth saved graph pending refuses '+boundary,async()=>{const {f,callback,gate,result,completion}=await completeFirstAuthentication('auth-queued');if(boundary==='identity-B')f.setIdentity('client-B');else if(boundary==='identity-null')f.setIdentity(null);else if(boundary==='connection')f.editor.session={...f.editor.session};else if(boundary==='session')f.editor.ui={...f.editor.ui,sessionId:'foreign-ui'};else changeOwner(f,boundary);const ev=event('plain');callback(ev);await flush();assert(ev.defaultPrevented);assert.equal(f.saved.length,0);gate.resolve(result);await completion;await flush();assert.equal(f.saved.length,0);});

// Controller wiring only: the recorder itself is a stub, and these local
// function-return observations provide no rendering or wire-transport proof.
test('actual Composition parse wrapper records bounded metadata and rejection without caption content',async()=>{
 const f=fixture(Current);await f.initial();phaseCalls.length=0;
 const raw=new TextEncoder().encode('{"private":"never_record_this_caption"}');
 const result=f.instance.parseLocal(raw);
 assert.equal(result.state,'unsupported');
 assert.deepEqual(phaseCalls,[{phase:'composition.parse',context:{documentId:'document',revision:'1',correlationId:f.instance.c.id,bytes:raw.byteLength,count:0},outcome:'rejected'}]);
 assert.equal(JSON.stringify(phaseCalls).includes('never_record_this_caption'),false);
 assert.equal(f.saved.length,0);
});
test('actual Composition serialization wrapper censors final wire completion and preserves rejection',async()=>{
 const f=fixture(Current);await f.initial();phaseCalls.length=0;f.instance.c.scene='never_record_this_scene';
 const serialized=f.instance.serializeLocal(f.instance.c);
 try{assert.match(serialized.value.prompt,/never_record_this_scene/);}finally{serialized.owner.release();}
 f.instance.c.request.expansion='Medium';f.instance.c.request.rewriteAcknowledged=false;
 assert.throws(()=>f.instance.serializeLocal(f.instance.c),/REWRITE_ACK_REQUIRED/);
 assert.deepEqual(phaseCalls.map(x=>({phase:x.phase,outcome:x.outcome,context:x.context})),['incomplete','rejected'].map(outcome=>({phase:'composition.serialize',outcome,context:{documentId:'document',revision:'1',correlationId:f.instance.c.id,count:0,...(outcome==='incomplete'?{boundary:'observed'}:{})}})));
 assert.equal(JSON.stringify(phaseCalls).includes('never_record_this_scene'),false);
 assert.equal(f.saved.length,0);
});
test('actual Composition standalone bounds wrapper keeps exact return values and rejected geometry',async()=>{
 const f=fixture(Current);await f.initial();phaseCalls.length=0;
 const geometry={rect:[0,0,36,20],transform:[1,0,0,1,0,0]};
 assert.deepEqual(f.instance.projectLocal(geometry,f.instance.c.frame,'inside').quantized,[0,0,100,100]);
 assert.equal(f.instance.projectLocal(geometry,f.instance.c.frame,'omit'),null);
 assert.throws(()=>f.instance.projectLocal(geometry,{...f.instance.c.frame,width:null},'inside'),/UNRESOLVED_AUTO/);
 assert.deepEqual(phaseCalls,['ok','ok','rejected'].map(outcome=>({phase:'composition.project',context:{documentId:'document',revision:'1',correlationId:f.instance.c.id,count:1},outcome})));
 assert.equal(f.saved.length,0);
});

test('document release invalidates synchronously and drains a pending JSON transport before freeing ownership',async()=>{
 const baseline=retainedAllocations(),f=fixture(Current);await f.initial();const model=f.instance.c,accepted=f.instance.accepted,gate=deferred();
 f.editor.view.document={...f.editor.view.document,revision:'2'};f.editor.json=()=>gate.promise;const completion=f.instance.sync();await flush();assert.equal(f.instance.lifecycle.pendingOperations,1);
 let released=false;const release=f.instance.releaseDocument().then(()=>{released=true;});assert.equal(f.instance.c,null);assert.equal(f.instance.accepted,null);assert.equal(f.instance.lifecycle.models,0);await flush();
 assert.equal(released,false);assert.equal(f.instance.lifecycle.pendingOperations,1);assert.ok(retainedAllocations().records>baseline.records);
 gate.resolve({composition:{...structuredClone(f.value),scene:'Late accepted'},layers:[],bindings:{},revision:'2'});await Promise.all([completion,release]);
 assert.equal(released,true);assert.equal(f.instance.lifecycle.pendingOperations,0);assert.equal(f.instance.lifecycle.pendingPins,0);assert.deepEqual(retainedAllocations(),baseline);assert.equal(f.instance.c,null);assert.equal(f.instance.accepted,null);assert.equal(model.scene,'Original raw');assert.equal(accepted.scene,'Original raw');assert.equal(f.saved.length,0);
});

test('a genuine underlying stream cancellation rejection keeps the failed owner and blocks release',async()=>{
 const baseline=retainedAllocations(),f=fixture(Current);await f.initial();const {completion}=await f.hold(),outcome=completion.then(()=>null,error=>error),failure=Error('Underlying cancellation failed');let cancellations=0;
 const response=new Response(new ReadableStream({cancel(){cancellations++;throw failure;}}),{headers:{'content-length':'2','content-type':'application/json'}});f.pending.shift().resolve(response);await flush();
 const release=f.instance.releaseDocument().then(()=>null,error=>error),error=expectedCleanup(await outcome);assert(error.errors.includes(failure));assert.equal(cancellations,1);assert.equal(error.resource.response,response);assert.equal(response.body.locked,false);
 const releaseError=await release;assert(releaseError instanceof AggregateError);assert(releaseError.errors.includes(error));assert.equal(f.instance.lifecycle.cleanupFailures,1);assert.equal(f.instance.lifecycle.models,0);assert.equal(f.instance.lifecycle.pendingOperations,0);assert.equal(f.instance.lifecycle.pendingPins,0);
 assert.deepEqual(retainedAllocations(),{records:baseline.records+1,cpu:baseline.cpu+2,prompt:baseline.prompt+2,handles:baseline.handles+2,unused:baseline.unused+2});await assert.rejects(error.retry(),value=>value===error);assert.equal(cancellations,1);assert.equal(f.saved.length,0);
});

// The explicit historical diagnostic reuses this harness and runs the current
// regressions too. Default test discovery needs no historical source files.
export {load,fixture,flush,deferred,event,changeOwner,inline,restoring,rawResponse};
