import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {transformWithOxc} from 'vite';
import {emptyComposition} from '../../dist/local/src/composition/core.js';

const data=code=>'data:text/javascript;base64,'+Buffer.from(code).toString('base64');
const lit=data('export const nothing=null;export function html(strings,...values){return {strings,values};}');
const color=data('export function parseColor(){throw Error("unused color path")} export function exportSRGB(){throw Error("unused color path")}');
const destination=data('export function chooseDestination(){throw Error("unused destination")}export function writeDestination(){throw Error("unused destination")}');
const adapter=data((await transformWithOxc(await readFile('src/ui/adapters.ts','utf8'),'adapters.ts')).code);
async function load(path){
 let code=(await transformWithOxc(await readFile(path,'utf8'),'composition.ts')).code;
 for(const [specifier,url]of Object.entries({'lit':lit,'@en-reve/elements/color-picker.js':color,'../state/destination.js':destination,'./adapters.js':adapter,'../protocol/json.js':pathToFileURL(resolve('dist/local/src/protocol/json.js')).href,'../composition/core.js':pathToFileURL(resolve('dist/local/src/composition/core.js')).href}))code=code.replaceAll(JSON.stringify(specifier),JSON.stringify(url)).replaceAll("'"+specifier+"'",JSON.stringify(url));
 return (await import(data(code))).CompositionEditing;
}
const Current=await load('src/ui/composition.ts'),Old=await load(process.env.COMPOSITION_OLD_SOURCE),Reviewed=await load(process.env.COMPOSITION_REVIEWED_SOURCE),BeforeRestoreFix=await load(process.env.COMPOSITION_RESTORE_SOURCE);
const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve();};
function field(template,id){if(!template||typeof template!=='object')return null;if(template.strings?.[0].includes('<en-textarea id=')&&template.values[0]===id)return template;for(const v of Array.isArray(template)?template:template.values??[]){const found=field(v,id);if(found)return found;}return null;}
function fixture(Controller){
 const raw={hash:'sha256:'+'1'.repeat(64),byteLength:'2',mediaType:'application/json'},doc={id:'document',revision:'1',width:360,height:200},value=emptyComposition(360,200,crypto.randomUUID());value.scene='Original raw';
 const saved=[],pending=[];let rendered,instance;
 const editor={sessionId:'session',draftOwner:{drafts:new Map()},view:{ready:true,document:doc},ui:{drafts:[]},json:async()=>({composition:structuredClone(value),layers:[],bindings:{},revision:editor.view.document.revision}),session:{identity:()=> 'client-A',transport:path=>new Promise((resolve,reject)=>pending.push({path,resolve,reject}))},changeDraft:(id,kind,text,target,composing,revision)=>saved.push({id,kind,graph:JSON.parse(text),revision})};
 const host={updates:0,requestUpdate(){this.updates++;this.updateComplete=Promise.resolve().then(()=>{rendered=instance.request();});},updateComplete:Promise.resolve(),querySelector(){return null;}};
 instance=new Controller(host,editor,()=>{},()=>{},async()=>{},()=>{});
 const input=async(handler,value)=>{const target={value,isConnected:true};handler({currentTarget:target,composedPath:()=>[target],detail:{isComposing:false},defaultPrevented:false,preventDefault(){this.defaultPrevented=true;}});await flush();};
 return {instance,editor,value,raw,saved,pending,host,input,rendered:()=>rendered,scene:()=>field(rendered,'composition-scene'),async initial(){await instance.sync();await flush();assert(this.scene());},async hold(raws=[raw]){value.raw=raws;editor.view.document={...doc,revision:'2'};const completion=instance.sync();await flush();assert.equal(pending.length,1);return {completion};},async finish(completion){pending.shift().resolve(new Response('{}'));await flush();assert.equal(pending.length,1);pending.shift().resolve(new Response('{}'));await completion;await flush();}};
}
for(const [label,Controller,expected]of [['saved original',Old,'Original raw'],['corrected',Current,'Desired']])test('actual '+label+' controller saves its rendered Scene during pending raw inspection',async()=>{const f=fixture(Controller);await f.initial();const {completion}=await f.hold();await f.input(f.scene().values.at(-1),'Desired');assert.equal(f.saved.at(-1).graph.composition.scene,expected);await f.finish(completion);assert.equal(f.saved.at(-1).graph.composition.scene,expected);assert.equal(f.instance.c.scene,expected);});
for(const change of ['document','session','owner','disposed'])test('late rendered Scene callback cannot write '+change+' owner',async()=>{const f=fixture(Current);await f.initial();const callback=f.scene().values.at(-1);if(change==='document')f.editor.view.document={...f.editor.view.document,id:'new-document'};if(change==='session')f.editor.sessionId='new-session';if(change==='owner')f.editor.draftOwner={drafts:new Map()};if(change==='disposed')f.instance.dispose();await f.input(callback,'Foreign');assert.equal(f.saved.length,0);assert.equal(f.instance.c.scene,'Original raw');});
for(const change of ['document','session','owner','disposed'])test('queued field settlement rejects changed '+change+' ownership',async()=>{const f=fixture(Current);await f.initial();const callback=f.scene().values.at(-1),target={value:'Foreign',isConnected:true};callback({currentTarget:target,composedPath:()=>[target],detail:{},defaultPrevented:false});if(change==='document')f.editor.view.document={...f.editor.view.document,id:'new-document'};if(change==='session')f.editor.sessionId='new-session';if(change==='owner')f.editor.draftOwner={drafts:new Map()};if(change==='disposed')f.instance.dispose();await flush();assert.equal(f.saved.length,0);assert.equal(f.instance.c.scene,'Original raw');});
test('late old raw response cannot overwrite a new document model or its public Scene',async()=>{const f=fixture(Current);await f.initial();const {completion}=await f.hold();const old=f.pending.shift();f.editor.view.document={...f.editor.view.document,id:'new-document',revision:'1'};f.value.raw=[];f.value.scene='New owner';await f.instance.sync();await flush();old.resolve(new Response('{}'));await completion;assert.equal(f.pending.length,0);await flush();assert.equal(f.instance.c.scene,'New owner');assert.equal(f.instance.rawText,'');assert.equal(f.scene().values[2],'New owner');assert.equal(f.saved.length,0);});

function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};}
function event(value){const target={value,isConnected:true};return {currentTarget:target,composedPath:()=>[target],detail:{},defaultPrevented:false,preventDefault(){this.defaultPrevented=true;}};}
function changeOwner(f,change){if(change==='document')f.editor.view.document={...f.editor.view.document,id:'new-document'};if(change==='session')f.editor.sessionId='new-session';if(change==='owner')f.editor.draftOwner={drafts:new Map()};if(change==='disposed')f.instance.dispose();}
function templateWhere(t,predicate){if(!t||typeof t!=='object')return null;if(t.strings&&predicate(t))return t;for(const v of Array.isArray(t)?t:t.values??[]){const found=templateWhere(v,predicate);if(found)return found;}return null;}
function inline(f,control){const t=templateWhere(f.rendered(),t=>t.strings[0].includes(control==='prompt'?'<en-segmented-control label="Prompt source"':'<en-select label="Retained raw source"'));assert(t);return t.values[control==='prompt'?2:1];}
for(const [name,Controller,kept]of [['reviewed first patch',Reviewed,false],['corrected',Current,true]])test(name+' resolves queued real Scene proposal before clean sync replacement',async()=>{
 const f=fixture(Controller);await f.initial();const callback=f.scene().values.at(-1),model=f.instance.c,base=f.instance.base,gate=deferred();
 f.editor.view.document={...f.editor.view.document,revision:'2'};f.editor.json=()=>gate.promise;const pending=f.instance.sync();
 const accepted=structuredClone(f.value);accepted.scene='New accepted';gate.resolve({composition:accepted,layers:[],bindings:{},revision:'2'});
 callback(event('Queued desired'));await pending;await flush();
 assert.equal(f.saved.length,kept?1:0);assert.equal(f.instance.accepted.scene,'New accepted');
 if(kept){assert.equal(f.instance.c,model);assert.equal(f.instance.base,base);assert.equal(f.saved[0].graph.composition.scene,'Queued desired');assert.equal(f.saved[0].revision,'1');assert.equal(f.scene().values[2],'Queued desired');assert.equal(f.instance.dirty,true);assert.throws(()=>f.instance.validate(),/Review the current document/);}
 else assert.equal(f.instance.c.scene,'New accepted');
});
test('cancelled queued proposal does not prevent owned clean synchronization',async()=>{const f=fixture(Current);await f.initial();const gate=deferred(),callback=f.scene().values.at(-1);f.editor.view.document={...f.editor.view.document,revision:'2'};f.editor.json=()=>gate.promise;const pending=f.instance.sync();gate.resolve({composition:structuredClone(f.value),layers:[],bindings:{},revision:'2'});const ev=event('Vetoed');callback(ev);ev.defaultPrevented=true;await pending;await flush();assert.equal(f.saved.length,0);assert.equal(f.instance.base.revision,'2');assert.equal(f.instance.c.scene,'Original raw');});
async function rawStage(f,stage){const {completion}=await f.hold();const outcome=completion.then(()=>({resolved:true}),error=>({error}));let gate=f.pending.shift();
 if(stage==='page-response')return {gate,outcome};
 if(stage==='page-body'){const body=deferred();gate.resolve({ok:true,arrayBuffer:()=>body.promise});await flush();return {gate:body,outcome};}
 gate.resolve(new Response('{}'));await flush();gate=f.pending.shift();assert(gate);
 if(stage==='full-response')return {gate,outcome};
 const body=deferred();gate.resolve({ok:true,arrayBuffer:()=>body.promise});await flush();return {gate:body,outcome};
}
for(const change of ['document','session','owner','disposed'])for(const stage of ['page-response','page-body','full-response','full-body'])for(const failure of [false,true])test('raw '+stage+' '+(failure?'rejection':'success')+' refuses '+change+' before any new sync',async()=>{
 const f=fixture(Current);await f.initial();const {gate,outcome}=await rawStage(f,stage),model=f.instance.c,hash=model.raw[0].hash,token=f.instance.rawRead;changeOwner(f,change);const updates=f.host.updates;
 if(failure)gate.reject(Error('late raw failure'));else gate.resolve(stage.endsWith('body')?new TextEncoder().encode('{}').buffer:new Response('{}'));
 assert.deepEqual(await outcome,{resolved:true});await flush();assert.equal(f.pending.length,0);assert.equal(f.instance.c,model);assert.equal(model.raw[0].hash,hash);if(change!=='disposed')assert.equal(f.instance.rawRead,token);assert.equal(f.instance.rawText,'');assert.equal(f.instance.rawResult,null);assert.equal(f.instance.rawInspected,'');assert.equal(f.saved.length,0);assert.equal(f.host.updates,updates);
});
for(const stage of ['page-response','page-body','full-response','full-body'])test('current-owner raw '+stage+' rejection still fails',async()=>{const f=fixture(Current);await f.initial();const {gate,outcome}=await rawStage(f,stage);gate.reject(Error('owned raw error'));const r=await outcome;assert.match(r.error?.message??'',/owned raw error/);assert.equal(f.instance.rawText,'');assert.equal(f.saved.length,0);});
for(const change of ['document','session','owner','disposed'])for(const failure of [false,true])test('late sync JSON '+(failure?'rejection':'success')+' refuses '+change+' without successor sync',async()=>{const f=fixture(Current);await f.initial();const gate=deferred(),before=f.instance.c;f.editor.view.document={...f.editor.view.document,revision:'2'};f.editor.json=()=>gate.promise;const pending=f.instance.sync();changeOwner(f,change);const updates=f.host.updates;if(failure)gate.reject(Error('old sync failure'));else gate.resolve({composition:structuredClone(f.value),layers:[],bindings:{},revision:'2'});await pending;assert.equal(f.instance.c,before);assert.equal(f.host.updates,updates);assert.equal(f.saved.length,0);});
test('current-owner sync JSON error still fails',async()=>{const f=fixture(Current);await f.initial();f.editor.view.document={...f.editor.view.document,revision:'2'};f.editor.json=async()=>{throw Error('owned sync failure');};await assert.rejects(f.instance.sync(),/owned sync failure/);});
for(const change of ['document','session','owner','disposed'])test('old restored-draft error refuses '+change+' before successor sync',async()=>{const f=fixture(Current);await f.initial();f.editor.sessionId='restoring-session';f.editor.ui.drafts=[{id:'saved-draft',kind:'composition',documentId:'document',status:'saved-unapplied',generation:1,expectedDocumentRevision:'1'}];const gate=deferred();let calls=0;f.editor.json=()=>++calls===1?Promise.resolve({composition:structuredClone(f.value),layers:[],bindings:{},revision:'1'}):gate.promise;const pending=f.instance.sync();await flush();assert.equal(calls,2);changeOwner(f,change);const updates=f.host.updates;gate.reject(Error('old restore error'));await pending;assert.equal(f.host.updates,updates);assert.equal(f.saved.length,0);});
for(const control of ['prompt','raw'])for(const change of ['document','session','owner','disposed'])for(const queued of [false,true])test(control+' actual rendered callback refuses '+change+(queued?' after queueing':' before dispatch'),async()=>{const f=fixture(Current);await f.initial();const {completion}=await f.hold();await f.finish(completion);const callback=inline(f,control),view=f.instance.view,index=f.instance.rawIndex,model=f.instance.c,ev=event(control==='prompt'?'composition':'0');if(queued)callback(ev);changeOwner(f,change);if(!queued)callback(ev);await flush();assert.equal(f.saved.length,0);assert.equal(f.instance.c,model);assert.equal(f.instance.view,view);assert.equal(f.instance.rawIndex,index);assert.equal(f.pending.length,0);});
for(const control of ['prompt','raw'])test(control+' same-owner actual rendered settlement remains enabled',async()=>{const f=fixture(Current);await f.initial();const {completion}=await f.hold();await f.finish(completion);const accepted=JSON.stringify(f.instance.accepted);await f.input(inline(f,control),control==='prompt'?'composition':'0');assert.equal(f.saved.length,1);assert.equal(JSON.stringify(f.instance.accepted),accepted);assert.equal(f.saved[0].revision,'2');if(control==='prompt')assert.equal(f.saved[0].graph.view,'composition');else{assert.equal(f.pending.length,1);f.pending.shift().resolve(new Response('{}'));await flush();assert.equal(f.instance.rawText,'{}');}});
test('model ownership survives a render after owner transition before sync',async()=>{const f=fixture(Current);await f.initial();f.editor.draftOwner={drafts:new Map()};f.host.requestUpdate();await flush();await f.input(f.scene().values.at(-1),'Foreign');assert.equal(f.saved.length,0);assert.equal(f.instance.c.scene,'Original raw');await f.instance.sync();await flush();await f.input(f.scene().values.at(-1),'New owner edit');assert.equal(f.saved.at(-1).graph.composition.scene,'New owner edit');});

test('successor actual owner starts same-key sync while old raw is pending',async()=>{const f=fixture(Current);await f.initial();const {completion}=await f.hold(),old=f.pending.shift(),gate=deferred();f.editor.draftOwner={drafts:new Map()};f.editor.json=()=>gate.promise;const successor=f.instance.sync();old.resolve(new Response('{}'));await completion;assert.notEqual(f.instance.loading,'');gate.resolve({composition:{...structuredClone(f.value),scene:'Successor',raw:[]},layers:[],bindings:{},revision:'2'});await successor;await flush();assert.equal(f.instance.c.scene,'Successor');assert.equal(f.instance.loading,'');assert.equal(f.pending.length,0);await f.input(f.scene().values.at(-1),'Successor edit');assert.equal(f.saved.at(-1).graph.composition.scene,'Successor edit');});
test('reviewed first patch demonstrates foreign raw follow-up and publication before successor sync',async()=>{const f=fixture(Reviewed);await f.initial();const {completion}=await f.hold();changeOwner(f,'owner');f.pending.shift().resolve(new Response('{}'));await flush();assert.equal(f.pending.length,1);f.pending.shift().resolve(new Response('{}'));await completion;assert.equal(f.instance.rawText,'{}');});
test('reviewed first patch demonstrates foreign inline Prompt source save',async()=>{const f=fixture(Reviewed);await f.initial();const callback=inline(f,'prompt');changeOwner(f,'owner');await f.input(callback,'composition');assert.equal(f.saved.length,1);assert.equal(f.saved[0].graph.view,'composition');});

async function restoring(Controller){const f=fixture(Controller);await f.initial();f.editor.sessionId='restoring-session';f.editor.view.document={...f.editor.view.document,revision:'2'};f.editor.ui.drafts=[{id:'saved-draft',kind:'composition',documentId:'document',status:'saved-unapplied',generation:1,expectedDocumentRevision:'1'}];const gate=deferred();let calls=0;f.editor.json=()=>++calls===1?Promise.resolve({composition:structuredClone(f.value),layers:[],bindings:{},revision:'2'}):gate.promise;const completion=f.instance.sync();await flush();assert.equal(calls,2);f.host.requestUpdate();await flush();const graph={composition:{...structuredClone(f.value),scene:'Saved stale draft'},view:'composition'},result={graph,bindings:{}};return {f,gate,completion,result};}
for(const [name,Controller,kept]of [['prior corrected candidate',BeforeRestoreFix,false],['final correction',Current,true]])test(name+' retains queued rendered Scene at saved-draft replacement',async()=>{const {f,gate,completion,result}=await restoring(Controller),model=f.instance.c,base=f.instance.base,accepted=JSON.stringify(f.instance.accepted);gate.resolve(result);f.scene().values.at(-1)(event('Edit during restore'));await completion;await flush();assert.equal(f.saved.length,kept?1:0);assert.equal(JSON.stringify(f.instance.accepted),accepted);if(kept){assert.equal(f.instance.c,model);assert.equal(f.instance.base,base);assert.equal(f.saved[0].revision,'2');assert.equal(f.saved[0].graph.composition.scene,'Edit during restore');assert.equal(f.scene().values[2],'Edit during restore');}else assert.equal(f.instance.c.scene,'Saved stale draft');});
test('vetoed queued Scene permits saved stale draft restore without automatic rebase',async()=>{const {f,gate,completion,result}=await restoring(Current);gate.resolve(result);const ev=event('Vetoed restore edit');f.scene().values.at(-1)(ev);ev.defaultPrevented=true;await completion;await flush();assert.equal(f.saved.length,0);assert.equal(f.instance.c.scene,'Saved stale draft');assert.equal(f.instance.base.revision,'1');assert.throws(()=>f.instance.validate(),/Review the current document/);});
for(const change of ['document','session','owner','disposed'])test('saved-draft boundary rechecks '+change+' after queued settlement',async()=>{const {f,gate,completion,result}=await restoring(Current),model=f.instance.c;gate.resolve(result);f.scene().values.at(-1)(event('Foreign restore edit'));changeOwner(f,change);await completion;await flush();assert.equal(f.saved.length,0);assert.equal(f.instance.c,model);assert.equal(f.instance.c.scene,'Original raw');});

test('second owned proposal dispatched during a vetoed-settlement wait survives replacement',async()=>{const f=fixture(Current);await f.initial();const gate=deferred(),callback=f.scene().values.at(-1);f.editor.view.document={...f.editor.view.document,revision:'2'};f.editor.json=()=>gate.promise;const completion=f.instance.sync();gate.resolve({composition:structuredClone(f.value),layers:[],bindings:{},revision:'2'});const first=event('Vetoed first');callback(first);first.defaultPrevented=true;queueMicrotask(()=>queueMicrotask(()=>callback(event('Second desired'))));await completion;await flush();assert.equal(f.saved.at(-1)?.graph.composition.scene,'Second desired');assert.equal(f.saved.at(-1)?.revision,'1');});

test('second owned proposal dispatched during restore settlement wait keeps its original base',async()=>{const {f,gate,completion,result}=await restoring(Current),callback=f.scene().values.at(-1);gate.resolve(result);const first=event('Vetoed first');callback(first);first.defaultPrevented=true;queueMicrotask(()=>queueMicrotask(()=>callback(event('Second restore edit'))));await completion;await flush();assert.equal(f.saved.at(-1)?.graph.composition.scene,'Second restore edit');assert.equal(f.saved.at(-1)?.revision,'2');assert.equal(f.instance.base.revision,'2');assert.equal(f.instance.c.scene,'Second restore edit');});

// Actual controller + actual ControlAdapter; Lit and the proposal host remain
// explicit NON-BROWSER stand-ins. This does not observe native checked radios.
test('initial mode callback causal agreement',async()=>{
 const f=fixture(Current);f.host.requestUpdate();await flush();assert.equal(f.instance.c,null);const callback=inline(f,'prompt'),before={view:f.instance.view,template:templateWhere(f.rendered(),t=>t.strings[0].includes('<en-segmented-control label="Prompt source"')).values[0]};
 await f.initial();const model=f.instance.c,accepted=JSON.stringify(f.instance.accepted),ev=event('composition');callback(ev);await flush();const template=templateWhere(f.instance.request(),t=>t.strings[0].includes('<en-segmented-control label="Prompt source"'));
 const result={scope:'NON-BROWSER actual controller/adapter with Lit and host stand-ins; no historical467 cause or native-radio proof',phase:process.env.COMPOSITION_MODE_PHASE??'green',before,host:ev.currentTarget.value,controller:f.instance.view,template:template.values[0],prevented:ev.defaultPrevented,saves:f.saved,modelRetained:f.instance.c===model,acceptedUnchanged:JSON.stringify(f.instance.accepted)===accepted};
 result.verifiedRed=result.phase==='red'&&result.host==='composition'&&result.controller==='plain'&&result.template==='plain'&&!result.prevented&&result.saves.length===0&&result.modelRetained&&result.acceptedUnchanged;
 if(process.env.EDITOR_RECEIPT){await mkdir(process.env.EDITOR_RECEIPT,{recursive:true});await writeFile(resolve(process.env.EDITOR_RECEIPT,'mode-causal.json'),JSON.stringify(result,null,2),{flag:'wx'});}
 if(result.phase==='red')assert.equal(result.verifiedRed,true,'Only exact staged-host/controller/template mismatch is VERIFIED-RED');else{assert.equal(result.host,'composition');assert.equal(result.controller,'composition');assert.equal(result.template,'composition');assert.equal(result.prevented,false);assert.equal(result.saves.length,1);assert.equal(result.saves[0].graph.view,'composition');assert.equal(result.saves[0].graph.composition.id,model.id);}
 assert(result.modelRetained&&result.acceptedUnchanged);
});

for(const change of ['document','session','owner','disposed'])for(const queued of [false,true])test('mode refusal reconciles staged host '+change+' '+queued,async()=>{
 const f=fixture(Current);await f.initial();const callback=inline(f,'prompt'),model=f.instance.c,accepted=JSON.stringify(f.instance.accepted),ev=event('composition');if(queued)callback(ev);changeOwner(f,change);if(!queued)callback(ev);await flush();assert.equal(ev.defaultPrevented,true);assert.equal(ev.currentTarget.value,f.instance.view);assert.equal(f.instance.view,'plain');assert.equal(f.saved.length,0);assert.equal(f.instance.c,model);assert.equal(JSON.stringify(f.instance.accepted),accepted);
});
test('current navigation after owner render never saves the foreign model',async()=>{const f=fixture(Current);await f.initial();const model=f.instance.c;changeOwner(f,'owner');f.host.requestUpdate();await flush();const ev=event('composition');inline(f,'prompt')(ev);await flush();assert.equal(f.instance.view,'composition');assert.equal(ev.currentTarget.value,'composition');assert.equal(templateWhere(f.rendered(),t=>t.strings[0].includes('<en-segmented-control label="Prompt source"')).values[0],'composition');assert.equal(f.instance.c,model);assert.equal(f.saved.length,0);});
test('same-owner replacement saves only the current model and draft',async()=>{const f=fixture(Current);await f.initial();const callback=inline(f,'prompt'),old=f.instance.c;f.editor.view.document={...f.editor.view.document,revision:'2'};f.value.scene='New accepted model';await f.instance.sync();await flush();const current=f.instance.c,draft=f.instance.draftId;assert.notEqual(current,old);await f.input(callback,'composition');assert.equal(f.saved.length,1);assert.equal(f.saved[0].id,draft);assert.equal(f.saved[0].revision,'2');assert.equal(f.saved[0].graph.composition.scene,'New accepted model');assert.equal(old.scene,'Original raw');});
test('mode adapter keeps veto and latest proposal semantics',async()=>{const f=fixture(Current);await f.initial();const callback=inline(f,'prompt'),ev=event('composition');callback(ev);ev.preventDefault();ev.currentTarget.value='plain';await flush();assert.equal(f.instance.view,'plain');assert.equal(f.saved.length,0);const first=event('composition'),second={...first};callback(first);first.currentTarget.value='plain';callback(second);await flush();assert.equal(f.instance.view,'plain');assert.equal(f.saved.length,1);assert.equal(f.saved[0].graph.view,'plain');});
for(const value of ['invalid','',null])test('invalid mode reconciles without save '+value,async()=>{const f=fixture(Current);await f.initial();const ev=event(value);inline(f,'prompt')(ev);await flush();assert(ev.defaultPrevented);assert.equal(ev.currentTarget.value,'plain');assert.equal(f.saved.length,0);});
test('disconnected mode proposal has no navigation or save',async()=>{const f=fixture(Current);await f.initial();const ev=event('composition');inline(f,'prompt')(ev);ev.currentTarget.isConnected=false;await flush();assert.equal(f.instance.view,'plain');assert.equal(f.saved.length,0);});

async function modeRestore(stage){
 const f=fixture(Current),first=deferred(),saved=deferred();f.editor.ui.drafts=[{id:'saved-mode-draft',kind:'composition',documentId:'document',status:'saved-unapplied',generation:7,expectedDocumentRevision:'0'}];let calls=0;f.editor.json=()=>++calls===1?first.promise:saved.promise;f.host.requestUpdate();await flush();const callback=inline(f,'prompt'),completion=f.instance.sync();
 const graph={composition:{...structuredClone(f.value),scene:'Saved domain content',background:'Preserve background'},view:'plain',selected:'saved-selection',numbers:{'request-width':'320'},color:'#123456',guides:false,rawText:'Retained draft text',rawIndex:2,rawOffset:32};const result={graph,bindings:{saved:'layer'}};
 if(stage==='interim'){first.resolve({composition:structuredClone(f.value),layers:[],bindings:{},revision:'1'});await flush();assert.equal(calls,2);assert.equal(f.instance.c.scene,'Original raw');f.host.requestUpdate();await flush();}
 return {f,first,saved,callback,completion,result,calls:()=>calls};
}
for(const stage of ['before-admission','interim'])test('mode intent during '+stage+' preserves saved graph and persists only its admitted identity',async()=>{
 const {f,first,saved,callback,completion,result}=await modeRestore(stage),generation=f.instance.generation;
 callback(event('composition'));await flush();assert.equal(f.instance.view,'composition');assert.equal(f.saved.length,0);assert.equal(f.instance.generation,generation);
 if(stage==='before-admission'){first.resolve({composition:structuredClone(f.value),layers:[],bindings:{},revision:'1'});await flush();}
 assert.equal(f.saved.length,0);saved.resolve(result);await completion;await flush();assert.deepEqual(f.instance.c,result.graph.composition);assert.equal(f.instance.accepted.scene,'Original raw');assert.equal(f.instance.view,'composition');assert.equal(f.instance.generation,generation);assert.equal(f.saved.length,1);assert.equal(f.saved[0].id,'saved-mode-draft');assert.equal(f.saved[0].revision,'0');assert.deepEqual(f.saved[0].graph,{...result.graph,view:'composition',bindings:result.bindings});assert.equal(f.scene().values[2],'Saved domain content');
});
test('latest current mode wins saved view without domain generation change',async()=>{const {f,saved,callback,completion,result}=await modeRestore('interim');callback(event('composition'));await flush();callback(event('plain'));await flush();const generation=f.instance.generation;result.graph.view='composition';saved.resolve(result);await completion;await flush();assert.equal(f.instance.view,'plain');assert.equal(f.instance.generation,generation);assert.equal(f.saved.length,1);assert.equal(f.saved[0].graph.view,'plain');assert.deepEqual(f.saved[0].graph.composition,result.graph.composition);});
for(const change of ['document','session','owner','disposed'])for(const stage of ['before-admission','interim'])test('pending mode restore rejects '+change+' during '+stage,async()=>{const {f,first,saved,callback,completion,result}=await modeRestore(stage);callback(event('composition'));await flush();const model=f.instance.c;changeOwner(f,change);first.resolve({composition:structuredClone(f.value),layers:[],bindings:{},revision:'1'});saved.resolve(result);await completion;await flush();assert.equal(f.instance.c,model);assert.equal(f.saved.length,0);});
test('replacement owner restores its own saved mode without old deferred intent',async()=>{const {f,saved,callback,completion,result}=await modeRestore('interim');callback(event('composition'));await flush();changeOwner(f,'owner');let calls=0;const next={graph:{...structuredClone(result.graph),view:'plain'},bindings:{}};next.graph.composition.scene='New owner saved';f.editor.json=async()=>++calls===1?{composition:structuredClone(f.value),layers:[],bindings:{},revision:'1'}:next;await f.instance.sync();saved.resolve(result);await completion;await flush();assert.equal(f.instance.view,'plain');assert.equal(f.instance.c.scene,'New owner saved');assert.equal(f.saved.length,0);});
test('queued disposed proposal cannot overwrite a newer owned mode proposal on the same host',async()=>{const f=fixture(Current);await f.initial();const old=inline(f,'prompt'),ev=event('composition');old(ev);f.instance.dispose();const fresh=f.instance.request().values[2];ev.currentTarget.value='plain';fresh({...ev});await flush();assert.equal(ev.currentTarget.value,'plain');assert.equal(f.instance.view,'plain');assert.equal(f.saved.length,0);});
test('failed saved read does not make interim graph eligible for mode persistence',async()=>{const {f,saved,callback,completion}=await modeRestore('interim');callback(event('composition'));await flush();saved.reject(Error('saved read failure'));await assert.rejects(completion,/saved read failure/);callback(event('plain'));await flush();assert.equal(f.saved.length,0);assert.equal(f.instance.c.scene,'Original raw');});

function bootstrapFixture(){
 const f=fixture(Current);f.editor.view={ready:false,document:null};f.editor.draftOwner=undefined;f.editor.ui=undefined;f.editor.owner='client-A';let identity='client-A';f.editor.session.identity=()=>identity;
 Object.defineProperty(f.editor,'sessionId',{configurable:true,get(){return this.ui?.sessionId??'editor_'+this.owner;}});
 return {...f,setIdentity(value){identity=value;}};
}
test('bootstrap causal batch uses actual retained and fresh mode callbacks',async()=>{
 const getter=(await readFile('src/state/editor-client.ts','utf8')).match(/get sessionId\(\) \{([^}]+)\}/)?.[1];assert.equal(getter?.trim(),"return this.ui?.sessionId ?? 'editor_' + this.owner;");
 const rows=[];
 for(const placement of ['before-dispatch','queued','fresh-contrast']){
  const f=bootstrapFixture();f.host.requestUpdate();await flush();const initialCallback=inline(f,'prompt'),localSession=f.editor.session,initial={ready:f.editor.view.ready,document:f.editor.view.document,sessionId:f.editor.sessionId,draftOwner:f.editor.draftOwner??null,identity:f.editor.session.identity(),model:f.instance.c,accepted:f.instance.accepted};const firstOwner={sessionId:'restored-ui',drafts:new Map()},ev=event('composition');
  if(placement==='queued')initialCallback(ev);
  f.editor.draftOwner=firstOwner;
  if(placement==='fresh-contrast'){f.host.requestUpdate();await flush();inline(f,'prompt')(ev);}else if(placement==='before-dispatch')initialCallback(ev);
  await flush();const t=templateWhere(f.instance.request(),t=>t.strings[0].includes('<en-segmented-control label="Prompt source"'));
  const row={placement,initial,transition:{sameSessionObject:f.editor.session===localSession,identity:f.editor.session.identity(),sessionId:f.editor.sessionId,firstOwnerInstalled:f.editor.draftOwner===firstOwner,ui:f.editor.ui??null,ready:f.editor.view.ready,document:f.editor.view.document},host:ev.currentTarget.value,controller:f.instance.view,template:t.values[0],veto:ev.defaultPrevented,modelUnchanged:f.instance.c===null,acceptedUnchanged:f.instance.accepted===null,saves:f.saved};rows.push(row);
  assert(row.transition.sameSessionObject&&row.transition.firstOwnerInstalled&&row.modelUnchanged&&row.acceptedUnchanged);assert.equal(row.transition.identity,'client-A');assert.equal(row.transition.sessionId,'editor_client-A');assert.equal(row.saves.length,0);
 }
 const red=process.env.COMPOSITION_BOOTSTRAP_PHASE==='red';const result={phase:red?'red':'green',scope:'Actual controller and actual adapter with source-matched EditorClient getter and explicit Lit/host/state stand-ins; not480 runtime cause or native keyboard proof',rows,verifiedRed:rows.slice(0,2).every(x=>x.host==='plain'&&x.controller==='plain'&&x.template==='plain'&&x.veto)&&rows[2].host==='composition'&&rows[2].controller==='composition'&&rows[2].template==='composition'&&!rows[2].veto};
 if(process.env.EDITOR_RECEIPT){await mkdir(process.env.EDITOR_RECEIPT,{recursive:true});await writeFile(resolve(process.env.EDITOR_RECEIPT,'bootstrap-causal.json'),JSON.stringify(result,null,2),{flag:'wx'});}
 if(red)assert.equal(result.verifiedRed,true,'Required exact initial-owner refusal and fresh-render contrast');else for(const row of rows){assert.equal(row.host,'composition');assert.equal(row.controller,'composition');assert.equal(row.template,'composition');assert.equal(row.veto,false);}
});

async function bootstrapRecovery(placement){
 const f=bootstrapFixture();f.host.requestUpdate();await flush();const callback=inline(f,'prompt'),gate=deferred(),owner={sessionId:'restored-ui',drafts:new Map()},document={id:'first-document',revision:'3',width:360,height:200};
 const graph={composition:{...structuredClone(f.value),scene:'Exact saved bootstrap graph',background:'Saved background'},view:'plain',selected:'retained-selection',numbers:{'request-width':'300'},color:'#ABCDEF',guides:false,rawText:'Retained original draft',rawIndex:2,rawOffset:32},result={graph,bindings:{saved:'layer'}},checkpoint={sessionId:'restored-ui',drafts:[{id:'saved-bootstrap',kind:'composition',documentId:document.id,status:'saved-unapplied',generation:7,expectedDocumentRevision:'2'}]};
 let reads=0;f.editor.json=()=>++reads===1?Promise.resolve({composition:structuredClone(f.value),layers:[],bindings:{},revision:'3'}):gate.promise;
 const ev=event('composition');if(placement==='intent-first'||placement==='queued')callback(ev);if(placement==='intent-first')await flush();f.editor.draftOwner=owner;f.editor.ui=checkpoint;f.editor.view={ready:true,document};if(placement==='before-dispatch')callback(ev);const completion=f.instance.sync();await flush();assert.equal(reads,2);assert.equal(f.instance.view,'composition');assert.equal(f.instance.c.scene,'Original raw');assert.equal(f.saved.length,0);assert.equal(f.instance.generation,0);
 return {f,gate,owner,document,callback,completion,result,ev};
}
for(const placement of ['intent-first','before-dispatch','queued'])test('complete initial admission '+placement+' preserves latest mode and exact saved ownership',async()=>{const {f,gate,owner,document,completion,result,ev}=await bootstrapRecovery(placement);assert.equal(ev.defaultPrevented,false);assert.equal(ev.currentTarget.value,'composition');gate.resolve(result);await completion;await flush();assert.equal(f.editor.draftOwner,owner);assert.equal(f.editor.sessionId,'restored-ui');assert.equal(f.editor.view.document,document);assert.deepEqual(f.instance.c,result.graph.composition);assert.equal(f.instance.accepted.scene,'Original raw');assert.equal(f.instance.generation,0);assert.equal(f.saved.length,1);assert.equal(f.saved[0].id,'saved-bootstrap');assert.equal(f.saved[0].revision,'2');assert.deepEqual(f.saved[0].graph,{...result.graph,view:'composition',bindings:result.bindings});});
test('latest bootstrap mode survives pending saved graph without interim writes',async()=>{const {f,gate,callback,completion,result}=await bootstrapRecovery('intent-first');callback(event('plain'));await flush();assert.equal(f.saved.length,0);result.graph.view='composition';gate.resolve(result);await completion;await flush();assert.equal(f.instance.view,'plain');assert.equal(f.saved.length,1);assert.equal(f.saved[0].graph.view,'plain');assert.deepEqual(f.saved[0].graph.composition,result.graph.composition);});
for(const boundary of ['identity','connection','document','session','owner','disposed'])test('bootstrap pending saved graph refuses replaced '+boundary,async()=>{const {f,gate,callback,completion,result}=await bootstrapRecovery('queued');const model=f.instance.c;if(boundary==='identity')f.setIdentity('client-B');else if(boundary==='connection')f.editor.session={...f.editor.session};else if(boundary==='session')f.editor.ui={...f.editor.ui,sessionId:'other-session'};else changeOwner(f,boundary);const ev=event('plain');callback(ev);await flush();assert(ev.defaultPrevented);assert.equal(f.saved.length,0);gate.resolve(result);await completion;await flush();assert.equal(f.saved.length,0);if(!['identity','connection'].includes(boundary))assert.equal(f.instance.c,model);assert.equal(f.instance.generation,boundary==='disposed'?1:0);});
for(const boundary of ['identity','connection','disposed'])for(const queued of [false,true])test('initial bootstrap callback refuses '+boundary+' '+queued,async()=>{const f=bootstrapFixture();f.host.requestUpdate();await flush();const callback=inline(f,'prompt'),ev=event('composition');if(queued)callback(ev);if(boundary==='identity')f.setIdentity('client-B');else if(boundary==='connection')f.editor.session={...f.editor.session};else f.instance.dispose();f.editor.draftOwner={sessionId:'other-ui',drafts:new Map()};if(!queued)callback(ev);await flush();assert(ev.defaultPrevented);assert.equal(f.instance.view,'plain');assert.equal(ev.currentTarget.value,'plain');assert.equal(f.saved.length,0);assert.equal(f.instance.c,null);});
test('established model cannot acquire bootstrap exemption after document disappears',async()=>{const f=fixture(Current);await f.initial();const model=f.instance.c;f.editor.view={ready:false,document:null};f.host.requestUpdate();await flush();const callback=inline(f,'prompt'),ev=event('composition');f.editor.draftOwner={sessionId:'replacement',drafts:new Map()};callback(ev);await flush();assert(ev.defaultPrevented);assert.equal(f.instance.view,'plain');assert.equal(f.instance.c,model);assert.equal(f.saved.length,0);});
test('first recovered document closes old bootstrap callback against later same-connection document changes',async()=>{const {f,gate,callback,completion,result}=await bootstrapRecovery('intent-first');gate.resolve(result);await completion;await flush();const count=f.saved.length;f.editor.view.document={...f.editor.view.document,id:'second-document'};const ev=event('plain');callback(ev);await flush();assert(ev.defaultPrevented);assert.equal(f.saved.length,count);assert.equal(f.instance.view,'composition');});
test('bootstrap saved-read failure keeps the interim graph ineligible for persistence',async()=>{const {f,gate,callback,completion}=await bootstrapRecovery('queued');gate.reject(Error('bootstrap saved read failure'));await assert.rejects(completion,/bootstrap saved read failure/);callback(event('plain'));await flush();assert.equal(f.saved.length,0);assert.equal(f.instance.c.scene,'Original raw');});

function firstAuthenticationFixture(){const f=bootstrapFixture();f.editor.owner=null;f.setIdentity(null);return f;}
test('first authentication causal batch preserves original actual callback observations',async()=>{
 const rows=[];
 for(const placement of ['before-dispatch','queued','fresh-contrast']){
  const f=firstAuthenticationFixture();f.host.requestUpdate();await flush();const callback=inline(f,'prompt'),connection=f.editor.session,initial={identity:f.editor.session.identity(),sessionId:f.editor.sessionId,owner:f.editor.owner,draftOwner:f.editor.draftOwner??null,document:f.editor.view.document,ready:f.editor.view.ready},ev=event('composition');
  if(placement==='queued')callback(ev);f.setIdentity('client-A');
  if(placement==='fresh-contrast'){f.host.requestUpdate();await flush();inline(f,'prompt')(ev);}else if(placement==='before-dispatch')callback(ev);
  await flush();const template=templateWhere(f.instance.request(),t=>t.strings[0].includes('<en-segmented-control label="Prompt source"')).values[0];
  rows.push({placement,initial,after:{identity:f.editor.session.identity(),sessionId:f.editor.sessionId,owner:f.editor.owner,sameConnection:f.editor.session===connection},host:ev.currentTarget.value,controller:f.instance.view,template,veto:ev.defaultPrevented,model:f.instance.c,accepted:f.instance.accepted,saves:[...f.saved]});
 }
 const red=process.env.COMPOSITION_AUTH_PHASE==='red',verifiedRed=rows.slice(0,2).every(x=>x.veto&&x.host==='plain'&&x.controller==='plain'&&x.template==='plain')&&!rows[2].veto&&rows[2].host==='composition'&&rows[2].controller==='composition'&&rows[2].template==='composition';
 const result={phase:red?'red':'green',scope:'Actual Composition controller and ControlAdapter, original retained callback with explicit host/state stand-ins and source-faithful owner=null/identity=null getter; no480 event-time or native keyboard claim',rows,verifiedRed};
 for(const row of rows){assert.deepEqual(row.initial,{identity:null,sessionId:'editor_null',owner:null,draftOwner:null,document:null,ready:false});assert.deepEqual(row.after,{identity:'client-A',sessionId:'editor_null',owner:null,sameConnection:true});assert.equal(row.model,null);assert.equal(row.accepted,null);assert.deepEqual(row.saves,[]);}
 if(process.env.EDITOR_RECEIPT){await mkdir(process.env.EDITOR_RECEIPT,{recursive:true});await writeFile(resolve(process.env.EDITOR_RECEIPT,'first-authentication-causal.json'),JSON.stringify(result,null,2),{flag:'wx'});}
 if(red)assert(verifiedRed,'Exact retained first-auth refusal with fresh callback contrast');else for(const row of rows){assert.equal(row.veto,false);assert.equal(row.host,'composition');assert.equal(row.controller,'composition');assert.equal(row.template,'composition');}
});

async function completeFirstAuthentication(placement){
 const f=firstAuthenticationFixture();f.host.requestUpdate();await flush();const callback=inline(f,'prompt'),ev=event('composition'),gate=deferred();
 assert.equal(f.editor.sessionId,'editor_null');assert.equal(f.editor.session.identity(),null);
 if(placement==='intent-first'||placement==='auth-queued')callback(ev);if(placement==='intent-first')await flush();assert.equal(f.saved.length,0);
 f.setIdentity('client-A');if(placement==='auth-before')callback(ev);if(['intent-first','auth-queued','auth-before'].includes(placement))await flush();assert.equal(f.saved.length,0);
 if(placement==='fallback-queued')callback(ev);f.editor.owner='client-A';assert.equal(f.editor.sessionId,'editor_client-A');if(placement==='fallback-before')callback(ev);if(placement.startsWith('fallback-'))await flush();assert.equal(f.saved.length,0);
 if(placement==='owner-queued')callback(ev);const owner={sessionId:'restored-ui',drafts:new Map()};f.editor.draftOwner=owner;if(placement==='owner-before')callback(ev);if(placement.startsWith('owner-'))await flush();assert.equal(f.saved.length,0);
 const document={id:'first-document',revision:'3',width:360,height:200},graph={composition:{...structuredClone(f.value),scene:'Full initial saved graph',background:'Preserved'},view:'plain',selected:'retained',numbers:{'request-width':'300'},color:'#ABCDEF',guides:false,rawText:'Original draft',rawIndex:2,rawOffset:32},result={graph,bindings:{saved:'layer'}};
 f.editor.ui={sessionId:owner.sessionId,drafts:[{id:'saved-initial',kind:'composition',documentId:document.id,status:'saved-unapplied',generation:7,expectedDocumentRevision:'2'}]};f.editor.view={ready:true,document};if(placement==='admission-before')callback(ev);
 let reads=0;f.editor.json=()=>++reads===1?Promise.resolve({composition:structuredClone(f.value),layers:[],bindings:{},revision:'3'}):gate.promise;const completion=f.instance.sync();await flush();assert.equal(reads,2);assert.equal(ev.defaultPrevented,false);assert.equal(f.instance.view,'composition');assert.equal(f.instance.generation,0);assert.equal(f.saved.length,0);assert.equal(f.instance.c.scene,'Original raw');
 return {f,callback,ev,owner,document,result,gate,completion};
}
for(const placement of ['intent-first','auth-before','auth-queued','fallback-before','fallback-queued','owner-before','owner-queued','admission-before'])test('full null identity and owner startup '+placement+' preserves exact saved graph',async()=>{const {f,owner,document,result,gate,completion}=await completeFirstAuthentication(placement);gate.resolve(result);await completion;await flush();assert.equal(f.editor.draftOwner,owner);assert.equal(f.editor.view.document,document);assert.equal(f.instance.view,'composition');assert.deepEqual(f.instance.c,result.graph.composition);assert.equal(f.saved.length,1);assert.deepEqual(f.saved[0],{id:'saved-initial',kind:'composition',graph:{...result.graph,view:'composition',bindings:result.bindings},revision:'2'});assert.equal(f.instance.generation,0);});
test('latest initial mode is reconciled only with the complete saved graph',async()=>{const {f,callback,result,gate,completion}=await completeFirstAuthentication('intent-first');callback(event('plain'));await flush();assert.equal(f.saved.length,0);result.graph.view='composition';gate.resolve(result);await completion;await flush();assert.equal(f.instance.view,'plain');assert.deepEqual(f.saved[0].graph,{...result.graph,view:'plain',bindings:result.bindings});});
for(const boundary of ['identity-B','identity-null','connection','session','owner','document','disposed'])for(const queued of [false,true])test('first established identity refuses '+boundary+' '+queued,async()=>{
 const f=firstAuthenticationFixture();f.host.requestUpdate();await flush();const callback=inline(f,'prompt');f.setIdentity('client-A');f.editor.owner='client-A';const owner={sessionId:'first-ui',drafts:new Map()};f.editor.draftOwner=owner;if(boundary==='document')f.editor.view.document={id:'first-doc'};callback(event('composition'));await flush();assert.equal(f.instance.view,'composition');const ev=event('plain');if(queued)callback(ev);
 if(boundary==='identity-B')f.setIdentity('client-B');else if(boundary==='identity-null')f.setIdentity(null);else if(boundary==='connection')f.editor.session={...f.editor.session};else if(boundary==='session')f.editor.ui={sessionId:'arbitrary-ui'};else if(boundary==='owner')f.editor.draftOwner={sessionId:'foreign-ui',drafts:new Map()};else if(boundary==='document')f.editor.view.document={id:'foreign-doc'};else f.instance.dispose();
 if(!queued)callback(ev);await flush();assert(ev.defaultPrevented);assert.equal(f.instance.view,'composition');assert.equal(ev.currentTarget.value,'composition');assert.equal(f.saved.length,0);assert.equal(f.instance.c,null);
});
for(const placement of ['before-dispatch','queued'])test('same identity fallback transition '+placement+' before first owner is allowed',async()=>{const f=firstAuthenticationFixture();f.setIdentity('client-A');f.host.requestUpdate();await flush();const callback=inline(f,'prompt'),ev=event('composition');if(placement==='queued')callback(ev);f.editor.owner='client-A';if(placement==='before-dispatch')callback(ev);await flush();assert.equal(ev.defaultPrevented,false);assert.equal(f.instance.view,'composition');assert.equal(f.saved.length,0);assert.equal(f.editor.draftOwner,undefined);});
for(const placement of ['before-dispatch','queued'])test('arbitrary fallback session '+placement+' is refused',async()=>{const f=firstAuthenticationFixture();f.setIdentity('client-A');f.host.requestUpdate();await flush();const callback=inline(f,'prompt'),ev=event('composition');if(placement==='queued')callback(ev);f.editor.owner='foreign-B';if(placement==='before-dispatch')callback(ev);await flush();assert(ev.defaultPrevented);assert.equal(f.instance.view,'plain');assert.equal(f.saved.length,0);});
for(const boundary of ['identity-B','identity-null','connection','session','owner','document','disposed'])test('full first-auth saved graph pending refuses '+boundary,async()=>{const {f,callback,gate,result,completion}=await completeFirstAuthentication('auth-queued');if(boundary==='identity-B')f.setIdentity('client-B');else if(boundary==='identity-null')f.setIdentity(null);else if(boundary==='connection')f.editor.session={...f.editor.session};else if(boundary==='session')f.editor.ui={...f.editor.ui,sessionId:'foreign-ui'};else changeOwner(f,boundary);const ev=event('plain');callback(ev);await flush();assert(ev.defaultPrevented);assert.equal(f.saved.length,0);gate.resolve(result);await completion;await flush();assert.equal(f.saved.length,0);});
