import {confirmImageImports} from './image-import-flow.js';
import {test,expect} from '@playwright/test';
import {mkdtemp,realpath,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const {startLocalServer}=await import(pathToFileURL(resolve('dist/local/server/http.js')).href);
const click=(p:any,name:string)=>p.getByRole('button',{name,exact:true}).click();
test('malformed portable file is rejected visibly without document acceptance; lost command delivery reuses its exact body',async({page})=>{
 const directory=await mkdtemp(join(await realpath(tmpdir()),'ie-fault-')),server=await startLocalServer({root:join(directory,'private'),staticDirectory:resolve('dist/app')});
 try{
 await page.goto(server.issuePairingURL());await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await click(page,'Open');await page.locator('en-file-upload[label="Open portable project"] input[type=file]').setInputFiles({name:'bad.ideogram-project',mimeType:'application/octet-stream',buffer:Buffer.from('not a ZIP64 project')});await expect(page.getByRole('heading',{name:'Action needs attention',exact:true})).toBeVisible();await expect(page.getByText('No document open',{exact:true})).toBeVisible();await click(page,'Cancel');
 // Drop only the receipt after the real writer sees and accepts this exact envelope.
 let first='';const bodies:string[]=[];await page.route('**/api/v1/commands',async route=>{const text=route.request().postData()!,body=JSON.parse(text);if(body.command.body.type==='CreateDocument'){bodies.push(text);if(!first){first=text;await route.fetch();await expect.poll(()=>page.evaluate(async id=>{const response=await fetch('/api/v1/commands/'+id,{headers:{'X-App-Client':'LP-1'},credentials:'same-origin',cache:'no-store',redirect:'error'});if(!response.ok)throw Error('Original receipt lookup failed');const result=await response.json();return result.kind==='receipt'?result.receipt.status:result.kind;},body.command.commandId),{timeout:15000}).toBe('accepted');await route.abort('failed');return;}}await route.continue();});
 await click(page,'New');await click(page,'Create');const newDialog=page.getByRole('dialog',{name:'New document',exact:true}),dialogHost=page.locator('en-dialog#editor-dialog');await expect(newDialog).toBeVisible();const creationError=dialogHost.getByRole('region',{name:'New document needs attention',exact:true});await expect(creationError).toBeVisible();await expect(creationError).toContainText('Your dialog draft is retained.');await expect(dialogHost.getByRole('textbox',{name:'Document name',exact:true})).toHaveValue('Untitled document');await dialogHost.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByRole('button',{name:'Check and retry original',exact:true})).toBeVisible();await click(page,'Check and retry original');await expect(page.getByText('CreateDocument accepted and saved locally.',{exact:true})).toBeVisible();expect(bodies).toEqual([first]);await page.unroute('**/api/v1/commands');
 await click(page,'Open');await expect(page.getByRole('button',{name:/ · 1024 × 1024 · revision 1$/})).toHaveCount(1);
 }finally{await server.close();}
});

test('renewal expires unaccepted review and preserves original bytes without creating a document',async({page})=>{
 const directory=await mkdtemp(join(await realpath(tmpdir()),'ie-expiry-'));let now=Date.now();const server=await startLocalServer({root:join(directory,'private'),staticDirectory:resolve('dist/app'),now:()=>now});
 try{await page.goto(server.issuePairingURL());await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await page.locator('en-file-upload input[type=file]').setInputFiles('tests/raster/fixtures/hidden-alpha.png');const importDialog=page.getByRole('dialog',{name:'Import image',exact:true}),importHost=page.locator('en-dialog#editor-dialog');await expect(importDialog).toBeVisible();const row=importHost.getByRole('listitem').filter({has:page.getByRole('heading',{name:'hidden-alpha.png',exact:true})}),select=row.getByRole('switch',{name:'Import hidden-alpha.png',exact:true});await expect(row.getByRole('img',{name:'Conversion preview: hidden-alpha.png',exact:true})).toBeVisible();await expect(select).toBeEnabled();await expect(select).not.toBeChecked();await select.check();await importHost.getByRole('combobox',{name:'Import destination',exact:true}).selectOption('new');const confirm=importHost.getByRole('button',{name:'Import selected images (1)',exact:true});await expect(confirm).toBeEnabled();now+=31*60*1000;await confirm.click();await expect(row.getByText(/^uncertain · original retained$/)).toBeVisible();await expect(row.getByText('SESSION_REQUIRED',{exact:true})).toBeVisible();await expect(row.getByRole('button',{name:'Resolve original delivery',exact:true})).toBeEnabled();await expect(row.getByText(/^Saved in /)).toHaveCount(0);await expect(page.getByText('No document open',{exact:true})).toBeVisible();
 await importHost.getByRole('button',{name:'Cancel',exact:true}).click();await expect(importDialog).toBeHidden();await click(page,'Connected locally');await click(page,'Check connection');await expect(page.getByText(/Connection expired or unavailable/).first()).toBeVisible();await page.goto(server.issuePairingURL());await page.getByRole('banner').getByRole('button',{name:'Close',exact:true}).click();await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await expect(page.getByRole('dialog',{name:'Import image',exact:true})).toHaveCount(0);
 }finally{await server.close();}
});

test('native composition drafts do not dispatch document actions and a late veto cancels Apply',async({page})=>{
 const directory=await mkdtemp(join(await realpath(tmpdir()),'ie-composition-')),server=await startLocalServer({root:join(directory,'private'),staticDirectory:resolve('dist/app')});const edits:string[]=[];
 try{page.on('request',r=>{if(new URL(r.url()).pathname==='/api/v1/commands'&&r.method()==='POST')edits.push(JSON.parse(r.postData()!).command.body.type);});await page.goto(server.issuePairingURL());await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await page.locator('en-file-upload input[type=file]').setInputFiles('tests/raster/fixtures/hidden-alpha.png');await confirmImageImports(page,{names:['hidden-alpha.png'],destination:'new',close:false});await expect(page.getByText('ImportAsset accepted and saved locally.',{exact:true})).toBeVisible();const importDialog=page.getByRole('dialog',{name:'Import image',exact:true}),importHost=page.locator('en-dialog#editor-dialog');await expect(importDialog).toBeVisible();await importHost.getByRole('button',{name:'Open imported document',exact:true}).click();await importHost.getByRole('button',{name:'Cancel',exact:true}).click();await expect(importDialog).toBeHidden();await page.getByRole('treeitem').click();const name=page.getByRole('textbox',{name:'Layer name',exact:true});await name.focus();await name.evaluate((input:any)=>{input.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true,composed:true}));input.value='日本語 draft';input.dispatchEvent(new InputEvent('input',{bubbles:true,composed:true,inputType:'insertCompositionText',data:'日本語 draft',isComposing:true}));});await expect(page.getByRole('button',{name:'Apply properties',exact:true})).toBeDisabled();await name.press('Meta+z');expect(edits).not.toContain('Undo');await name.evaluate(input=>input.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,composed:true})));await name.fill('fresh Unicode 🌿');
 await page.locator('en-button').filter({hasText:'Apply properties'}).evaluate(host=>host.addEventListener('click',e=>e.preventDefault(),{once:true}));await click(page,'Apply properties');await page.waitForTimeout(100);expect(edits).not.toContain('SetLayerProperties');await expect(name).toHaveValue('fresh Unicode 🌿');
 }finally{await server.close();}
});
