import {test,expect} from '@playwright/test';
import {mkdtemp,realpath,writeFile,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join} from 'node:path';
import {serverProcess} from './process.js';
const output=process.env.EDITOR_RECEIPT!;
test('serial integrated parent actions through renderer Paint, with full preparation and commit work',async({page,context})=>{
 test.setTimeout(180000);const dir=await mkdtemp(join(await realpath(tmpdir()),'ie-parent-paint-')),server=await serverProcess(join(dir,'private'));
 await context.addInitScript(()=>Object.defineProperty(window,'showSaveFilePicker',{value:undefined,configurable:true}));
 const resources:any[]=[];let sampling=false;const sample=setInterval(()=>{if(sampling)return;sampling=true;void server.resources().then(value=>resources.push({at:performance.now(),...value})).finally(()=>sampling=false);},50);
 const cdp=await context.newCDPSession(page),events:any[]=[],steps:any[]=[],receipts:any[]=[],pending=new Map<string,{operation:string;at:number}>();
 page.on('request',r=>{if(new URL(r.url()).pathname==='/api/v1/commands'&&r.method()==='POST'){const c=JSON.parse(r.postData()!).command;pending.set(c.commandId,{operation:c.body.type,at:performance.now()});}});
 page.on('response',r=>{if(/\/api\/v1\/commands(?:\/[^/]+)?$/.test(new URL(r.url()).pathname))void r.json().then(v=>{const c=v.receipt&&pending.get(v.receipt.commandId);if(c){receipts.push({commandId:v.receipt.commandId,operation:c.operation,status:v.receipt.status,requestToObservedReceiptMs:performance.now()-c.at});pending.delete(v.receipt.commandId);}}).catch(()=>{});});
 // Allow-list trace evidence at receipt time: no URLs, headers, source text,
 // request bodies, cookies, tokens, network or credential-bearing trace records.
 cdp.on('Tracing.dataCollected',({value})=>{for(const e of value)if(e.name.startsWith('ie.')||['Paint','EventDispatch','RunTask','FunctionCall','Layout','UpdateLayoutTree','DrawFrame','Commit','CompositeLayers','navigationStart','firstContentfulPaint','firstPaint'].includes(e.name))events.push({name:e.name,cat:e.cat,ph:e.ph,pid:e.pid,tid:e.tid,ts:e.ts,dur:e.dur,args:e.name.startsWith('ie.')?{detail:e.args?.data?.detail??e.args?.detail}:e.name==='EventDispatch'?{type:e.args?.data?.type}:e.name==='Paint'?{clip:e.args?.data?.clip,nodeId:e.args?.data?.nodeId,layerId:e.args?.data?.layerId}:undefined});});
 await cdp.send('Tracing.start',{categories:'devtools.timeline,blink.user_timing,benchmark,cc',transferMode:'ReportEvents'});
 const mark=async(name:string)=>page.evaluate(name=>performance.mark('ie.test.'+name),name);
 const click=(name:string)=>page.getByRole('button',{name,exact:true}).click();
 async function step(name:string,action:()=>Promise<unknown>,ready:()=>Promise<unknown>){await mark('start.'+name);await action();await ready();await mark('verified.'+name);const dom=await cdp.send('DOM.getDocument'),node=await cdp.send('DOM.querySelector',{nodeId:dom.root.nodeId,selector:'canvas'}),canvas=await cdp.send('DOM.describeNode',{nodeId:node.nodeId});steps.push({name,marks:await page.evaluate(()=>performance.getEntriesByType('mark').filter(x=>x.name.startsWith('ie.')).map(x=>({name:x.name,startTime:x.startTime,detail:(x as PerformanceMark).detail}))),document:await page.locator('.document-name').textContent(),asset:await page.locator('canvas').getAttribute('data-asset'),canvasBackendNodeId:canvas.node.backendNodeId,canvasBox:await page.locator('canvas').boundingBox()});}
 try{
 await page.goto(await server.pair());await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await mark('cold.ready');
 await step('import-review-and-apply',async()=>{await page.locator('en-file-upload input[type=file]').setInputFiles('tests/raster/fixtures/hidden-alpha.png');await expect(page.getByRole('dialog',{name:'Review image conversion'})).toBeVisible();await click('Apply reviewed result');},async()=>{await expect(page.getByText('ImportAsset accepted and saved locally.',{exact:true})).toBeVisible();await expect(page.locator('canvas')).not.toHaveAttribute('data-asset','');});
 await step('selection',()=>page.getByRole('treeitem').first().click(),()=>expect(page.getByRole('textbox',{name:'Layer name',exact:true})).toHaveValue('hidden-alpha.png'));
 for(let n=0;n<5;n++){const before=await page.locator('.document-name').textContent();await page.getByRole('spinbutton',{name:'Opacity (0–1)',exact:true}).fill(String(.5+n*.05));await step('opacity-'+n,()=>click('Apply properties'),async()=>{await expect(page.locator('.document-name')).not.toHaveText(before!);await expect(page.getByText('SetLayerProperties accepted and saved locally.',{exact:true})).toBeVisible();await expect(page.getByRole('region',{name:'Operation status'})).toHaveAttribute('aria-busy','false');});}
 await step('undo',()=>click('Undo'),()=>expect(page.getByText('Undo accepted and saved locally.',{exact:true})).toBeVisible());
 await step('redo',()=>click('Redo'),()=>expect(page.getByText('Redo accepted and saved locally.',{exact:true})).toBeVisible());
 const box=await page.locator('canvas').boundingBox();await page.mouse.move(box!.x+box!.width/2,box!.y+box!.height/2);await page.mouse.down();await page.mouse.move(box!.x+box!.width/2+60,box!.y+box!.height/2+30,{steps:12});await page.mouse.up();
 await step('zoom',async()=>{await page.getByRole('spinbutton',{name:'Zoom percentage',exact:true}).fill('150');await page.getByRole('spinbutton',{name:'Zoom percentage',exact:true}).press('Enter');},()=>expect(page.getByRole('spinbutton',{name:'Zoom percentage',exact:true})).toHaveValue('150'));
 await step('resample-review-and-apply',async()=>{await click('Resample image…');await page.getByRole('spinbutton',{name:'Intrinsic width (px)',exact:true}).fill('6');await page.getByRole('spinbutton',{name:'Intrinsic height (px)',exact:true}).fill('4');await click('Prepare preview');await click('Apply reviewed result');},()=>expect(page.getByText('ResampleImage accepted and saved locally.',{exact:true})).toBeVisible());
 await step('flatten-review-and-apply',async()=>{await click('Flatten copy…');await click('Prepare preview');await click('Apply reviewed result');},()=>expect(page.getByText('CreateFlattenedCopy accepted and saved locally.',{exact:true})).toBeVisible());
 await step('checkpoint',()=>click('Save checkpoint'),()=>expect(page.getByText('SaveCheckpoint accepted and saved locally.',{exact:true})).toBeVisible());
 await step('full-copy-ready',async()=>{await click('Save copy');await click('Prepare complete copy');},()=>expect(page.getByRole('region',{name:'Prepared file'})).toContainText('Full-history copy'));
 const bundle=join(dir,'measured.ideogram-project');await step('full-copy-download',async()=>{const downloaded=page.waitForEvent('download');await click('Download prepared file');await(await downloaded).saveAs(bundle);},()=>expect(page.getByText('Download initiated. External destination remains unconfirmed.',{exact:true})).toBeVisible());
 await step('portable-open-review-and-apply',async()=>{await click('Open');await page.locator('en-file-upload[label="Open portable project"] input[type=file]').setInputFiles(bundle);await click('Apply reviewed result');},()=>expect(page.getByText('ImportBundle accepted and saved locally.',{exact:true})).toBeVisible());
 await step('exact-export-ready',()=>click('Export image'),()=>expect(page.getByRole('region',{name:'Prepared file'})).toContainText('Exact PNG'));
 const png=join(dir,'measured.png');await step('exact-export-download',async()=>{const downloaded=page.waitForEvent('download');await click('Download prepared file');await(await downloaded).saveAs(png);},()=>expect(page.getByText('Download initiated. External destination remains unconfirmed.',{exact:true})).toBeVisible());
 const old=await page.locator('canvas').getAttribute('data-asset');await mark('start.warm-reopen');await page.reload();await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await expect(page.locator('canvas')).toHaveAttribute('data-asset',old!);await mark('warm.ready');await page.getByRole('treeitem').first().click();await page.getByRole('spinbutton',{name:'Opacity (0–1)',exact:true}).fill('.9');await click('Apply properties');await expect(page.getByText('SetLayerProperties accepted and saved locally.',{exact:true})).toBeVisible();await mark('warm.test-edit');
 await page.screenshot({path:join(output,'timing-final.png')});expect(Object.values(await server.effects()).every(x=>x===0)).toBe(true);
 }finally{
 clearInterval(sample);const complete=new Promise<void>(r=>cdp.once('Tracing.tracingComplete',()=>r()));await cdp.send('Tracing.end');await complete;
 await writeFile(join(output,'paint-trace.json'),JSON.stringify({traceEvents:events}));await writeFile(join(output,'action-steps.json'),JSON.stringify({ended:new Date().toISOString(),steps,resources,receipts,limits:'Author tiny fixture observations with tracing and automated review dwell; not formal workload, native/display/OS latency or exclusive-host qualification. HTTP request-to-observed-receipt includes preparation/queue/server/client observation and is not the narrower R20 child. Only renderer Paint after verified app draw/update identifies paint; completion/rAF alone is not paint. Download initiation plus Playwright saveAs are separate measured steps; external destination remains unconfirmed. Server RSS samples include this server process and its threads, not browser or separate children; no complete application peak claim.',build:JSON.parse(await readFile('dist/app/build-evidence.json','utf8'))},null,2));await server.close();
 }
});
