// Source-only authored. Root runs these against the merged production source.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {transformWithOxc} from 'vite';
import {viewModelDependencies} from '../view-model-module.mjs';
import {allocationsURL as allocations,promptMemoryURL as prompt} from '../owned-preview-module.mjs';
const root=process.env.FRIENDLY_INSPECTOR_ROOT??'.',viewRoot=process.env.CLIENT_ALLOCATION_ROOT??'.',data=value=>'data:text/javascript;base64,'+Buffer.from(value).toString('base64');
async function source(path,imports={}){let code=(await transformWithOxc(await readFile(path,'utf8'),path)).code;for(const [key,value]of Object.entries(imports))code=code.replaceAll(JSON.stringify(key),JSON.stringify(value)).replaceAll("'"+key+"'",JSON.stringify(value));return data(code);}
const memory=await source('src/observability/model-memory.ts',{'./allocations.js':allocations,'./prompt-memory.js':prompt}),geometry=await source(root+'/src/ui/inspector-transform.ts'),model=await source(root+'/src/ui/inspector-model.ts',{'./inspector-transform.js':geometry,'../observability/allocations.js':allocations,'../observability/model-memory.js':memory,'../observability/prompt-memory.js':prompt}),{viewURL}=await viewModelDependencies(allocations,{root:viewRoot,promptURL:prompt,memoryURL:memory});
const {allocationLedger,ALLOCATION_LIMITS}=await import(allocations),{readOwnedJSON,cloneOwnedModel}=await import(memory),{ViewModelReads}=await import(viewURL),{newInspector,changedInspector,sizedInspector,restoredInspector,serializedInspector,inspectorTransform,friendlyInspectorAvailable}=await import(model),{friendlyTransform,changedFriendlyTransform,inspectorMatrix,matrixValues}=await import(geometry);
const totals=()=>{const s=allocationLedger.snapshot();return {cpu:s.cpuBytes,handles:s.handles,records:s.activeRecords};},flush=async()=>{for(let i=0;i<80;i++)await Promise.resolve();};
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const close=(actual,expected)=>assert(Math.abs(actual-expected)<=Math.max(1,Math.abs(expected))*1e-12,`${actual} != ${expected}`),det=m=>m[0]*m[3]-m[1]*m[2],shear=m=>(m[0]*m[2]+m[1]*m[3])/(Math.hypot(m[0],m[1])*Math.hypot(m[2],m[3]));
const layer={id:'layer',version:'1',assetId:'asset',kind:'image',name:'Layer',opacity:1,visible:true,locked:false,layerToDocument:[2,1,3,-4,12.5,-7.25]},document={id:'document',revision:'1'},extent={width:200,height:100};
const response=value=>{const wire=JSON.stringify(value);return new Response(wire,{headers:{'content-length':String(new TextEncoder().encode(wire).byteLength)}});};
test('identity values are source edge dimensions and rotation uses document coordinates',()=>{assert.deepEqual(friendlyTransform(matrixValues([1,0,0,1,0,0]),extent),{width:'200',height:'100',rotation:'0'});assert.equal(friendlyTransform(matrixValues([0,1,-1,0,0,0]),extent).rotation,'90');});
for(const key of ['width','height'])test(key+' scales only its source column and preserves shear, reflection and exact origin',()=>{const m=layer.layerToDocument,v=matrixValues(m),prior=friendlyTransform(v,extent),next=changedFriendlyTransform(v,extent,{...prior,[key]:String(Number(prior[key])*2)});assert.equal(Math.sign(det(next)),Math.sign(det(m)));close(shear(next),shear(m));assert.equal(next[4],m[4]);assert.equal(next[5],m[5]);const untouched=key==='width'?[2,3]:[0,1];for(const index of untouched)assert.equal(next[index],m[index]);close(Number(friendlyTransform(matrixValues(next),extent)[key]),Number(prior[key])*2);});
test('rotation turns both columns without reflowing, orthogonalizing or moving the layer',()=>{const v=matrixValues(layer.layerToDocument),prior=friendlyTransform(v,extent),next=changedFriendlyTransform(v,extent,{...prior,rotation:String(Number(prior.rotation)+90)});close(next[0],-layer.layerToDocument[1]);close(next[1],layer.layerToDocument[0]);close(next[2],-layer.layerToDocument[3]);close(next[3],layer.layerToDocument[2]);close(shear(next),shear(layer.layerToDocument));close(det(next),det(layer.layerToDocument));assert.deepEqual(next.slice(4),layer.layerToDocument.slice(4));});
test('unchanged and whole-turn angles avoid round-trip drift; tiny finite angles remain representable',()=>{const v=matrixValues([1,0,0,1,-0,17]),prior=friendlyTransform(v,extent);assert.deepEqual(changedFriendlyTransform(v,extent,{...prior,rotation:'720'}),[1,0,0,1,0,17]);const tiny=changedFriendlyTransform(v,extent,{...prior,rotation:'0.00000000000001'});assert(tiny[1]>0);assert(Number(friendlyTransform(matrixValues(tiny),extent).rotation)>0);});
test('blank, nonfinite, singular, overflowing inverse and unsupported extents fail explicitly',()=>{for(const m of [[1,0,0,0,0,0],[1e308,0,0,1e308,0,0],[1e-320,0,0,1e-320,0,0]])assert.throws(()=>inspectorMatrix(matrixValues(m)),/invertible/);assert.throws(()=>inspectorMatrix({...matrixValues([1,0,0,1,0,0]),x:''}),/finite/);const v=matrixValues(layer.layerToDocument),prior=friendlyTransform(v,extent);for(const width of ['','0','-1','Infinity','1e1000'])assert.throws(()=>changedFriendlyTransform(v,extent,{...prior,width}));assert.throws(()=>friendlyTransform(v,{width:0,height:1}),/unavailable/);});
test('incomplete friendly input is owned, serialized and restored while Apply remains blocked',()=>{const before=totals(),first=newInspector(layer,document,'draft',extent),next=changedInspector(first.value,'width','-'),wire=serializedInspector(next.value.values),restored=restoredInspector(first.value,wire.wire,'1','draft');try{assert.equal(next.value.values.width,'-');assert.deepEqual(inspectorMatrix(next.value.values),layer.layerToDocument);assert.equal(restored.value.values.width,'-');assert.throws(()=>inspectorTransform(restored.value),/finite/);assert.equal(friendlyInspectorAvailable(restored.value),true);}finally{wire.release();restored.release();next.release();first.release();}assert.deepEqual(totals(),before);});
test('advanced edits stay authoritative and friendly controls recover after invalid matrix correction',()=>{const before=totals(),first=newInspector({...layer,layerToDocument:[1,0,0,1,0,0]},document,'draft',extent),invalid=changedInspector(first.value,'d',''),valid=changedInspector(invalid.value,'d','-2');try{assert.equal(friendlyInspectorAvailable(invalid.value),false);assert.equal(friendlyInspectorAvailable(valid.value),true);assert.equal(valid.value.values.height,'200');assert.equal(valid.value.values.transformInput,'matrix');assert.equal(inspectorTransform(valid.value)[3],-2);}finally{valid.release();invalid.release();first.release();}assert.deepEqual(totals(),before);});
test('friendly admission refusal preserves exact prior owner and numeric text',()=>{const before=totals(),first=newInspector(layer,document,'draft',extent),held=allocationLedger.snapshot(),block=allocationLedger.reserve({owner:'inspector-test-pressure',kind:'control',cpuBytes:ALLOCATION_LIMITS.cpuBytes-ALLOCATION_LIMITS.textPartitionBytes-held.cpuBytes});try{assert.throws(()=>changedInspector(first.value,'width','500'),/ALLOCATION_BUDGET/);assert.equal(first.value.dirty,false);assert.equal(first.value.values.width,friendlyTransform(matrixValues(layer.layerToDocument),extent).width);}finally{block.release();first.release();}assert.deepEqual(totals(),before);});
test('legacy saved matrix drafts remain readable without new friendly properties',()=>{const before=totals(),first=newInspector(layer,document,'draft',extent),{width,height,rotation,transformInput,...legacy}=first.value.values,restored=restoredInspector(first.value,JSON.stringify(legacy),'1','old');try{assert.deepEqual(inspectorTransform(restored.value),layer.layerToDocument);assert.equal(restored.value.values.transformInput,'matrix');}finally{restored.release();first.release();}assert.deepEqual(totals(),before);});

const assetProjectionURL=pathToFileURL(resolve('dist/local/src/protocol/asset-projection.js')).href;
const compiled=(await transformWithOxc(await readFile(root+'/src/ui/shell.ts','utf8'),'shell.ts')).code,shellClass=compiled.slice(compiled.indexOf('class EditorShell'),compiled.lastIndexOf('scope.register('));
const shellModule=await import(data(`import {allocationLedger} from ${JSON.stringify(allocations)};import {ViewModelReads} from ${JSON.stringify(viewURL)};import {newInspector,ownInspector,restoredInspector,serializedInspector,changedInspector,inspectorTransform,sizedInspector,friendlyInspectorAvailable} from ${JSON.stringify(model)};import {validateAssetProjection} from ${JSON.stringify(assetProjectionURL)};class LitElement{};let editor;export function setEditor(value){editor=value;}\n`+shellClass+'\nexport {EditorShell};'));
function assetProjection(size=extent,id='asset'){const blob=(type,length,digit)=>({hash:'sha256:'+digit.repeat(64),byteLength:String(length),mediaType:type}),manifest=blob('application/json',2,'1'),pixels=blob('application/x-ideogram-rgba8',size.width*size.height*4,'2'),asset={id,version:'1',purpose:'image',blob:blob('image/png',1,'3'),dependencies:[manifest,pixels],safety:'safe',availability:'available',qualification:'canonical-raster',measuredMediaType:'image/png',raster:{schemaVersion:1,pipeline:'cp1-f64-triangle-area-v1/sha256:'+'4'.repeat(64),...size,manifest,pixels,pixelIdentity:'sha256:'+'5'.repeat(64),role:'composite',sourceAssetIds:[],conversion:null}};return {protocolVersion:1,entityVersion:'1',projectionSchema:2,highWater:'1',projection:{kind:'inline',value:asset}};}
function fixture(){let route=async()=>response(assetProjection({width:201,height:101}));const failures=[],writes=[],commands=[],view={document,selected:[layer.id],image:{layers:[]}},editor={view,session:{identity:()=> 'client'},sessionId:'session',documentEpoch:1,documentResources:{releasing:false},ui:{drafts:[]},draftOwner:{drafts:new Map()},changeDraft(...args){writes.push(args);},async flushDrafts(){},async withCommandEvents(body,consume,target){commands.push({body,target});return await consume([]);},ownedJSON(path,owner,init,owns,maxBytes){return readOwnedJSON((...args)=>route(...args),path,{owner,init,owns,maxBytes});},fail(error){failures.push(error);},patch(){}};shellModule.setEditor(editor);const shell=Object.create(shellModule.EditorShell.prototype);Object.assign(shell,{inspectorTasks:new Set(),inspectorSizeReads:new ViewModelReads(),inspectorKey:'document:layer',adapter:{invalidate(){}},requestUpdate(){this.updateComplete=Promise.resolve();},updateComplete:Promise.resolve(),writeFields(){},composition:false});shell.setFields(newInspector(layer,document,'draft'));return {shell,editor,failures,writes,commands,route(value){route=value;},async close(){shell.setFields();await shell.drainInspector();await flush();}};}
test('actual inspector reads canonical asset extents for text too, retaining only its thin snapshot',async()=>{const before=totals(),f=fixture();try{f.shell.setFields(newInspector({...layer,kind:'text'},document,'draft'));f.shell.loadInspectorDimensions();await flush();assert.deepEqual(f.shell.fields.intrinsic,{status:'ready',width:201,height:101});assert.equal(f.shell.fields.layer.assetId,'asset');assert.equal(f.shell.fields.layer.layerToDocument,undefined);assert.equal(f.shell.fields.layer.source,undefined);assert.equal(f.shell.inspectorTasks.size,0);assert.equal(f.shell.inspectorSizeReads.ownership.activeReads,0);}finally{await f.close();}assert.deepEqual(totals(),before);});
test('late dimension response cannot publish into a successor selection',async()=>{const before=totals(),f=fixture(),gate=deferred();try{f.route(async()=>{await gate.promise;return response(assetProjection());});f.shell.loadInspectorDimensions();await flush();f.editor.view.selected=['other'];f.shell.setFields(newInspector({...layer,id:'other',assetId:'other-asset'},document,'other-draft'));gate.resolve();await flush();assert.equal(f.shell.fields.layer.id,'other');assert.equal(f.shell.fields.intrinsic.status,'unread');}finally{gate.resolve();await f.close();}assert.deepEqual(totals(),before);});
test('dimension reads drain actual native stream cancellation before releasing the old inspector',async()=>{const before=totals(),f=fixture(),cancel=deferred(),entered=deferred();let drain;try{f.route(async()=>new Response(new ReadableStream({cancel(){entered.resolve();return cancel.promise;}}),{headers:{'content-length':'2'}}));f.shell.loadInspectorDimensions();await flush();f.shell.setFields();let done=false;drain=f.shell.drainInspector().then(()=>done=true);await entered.promise;await flush();assert.equal(done,false);assert(totals().cpu>before.cpu);cancel.resolve();await drain;assert.equal(f.shell.inspectorTasks.size,0);assert.equal(f.shell.inspectorSizeReads.ownership.activeReads,0);}finally{cancel.resolve();await drain;await f.close();}assert.deepEqual(totals(),before);});
test('native unlock failure remains charged and dimension cleanup retries the real reader',async()=>{const before=totals(),f=fixture();let refuse=true,locked=true,index=0;const bytes=new TextEncoder().encode(JSON.stringify(assetProjection())),reader={async read(){return index++?{done:true}:{done:false,value:bytes};},async cancel(){},releaseLock(){if(refuse)throw Error('unlock');locked=false;}};try{f.route(async()=>({ok:true,headers:new Headers({'content-length':String(bytes.length)}),body:{getReader:()=>reader}}));f.shell.loadInspectorDimensions();await flush();assert.equal(f.shell.inspectorSizeReads.ownership.cleanupFailures,1);await assert.rejects(f.shell.drainInspector(),/INSPECTOR_ACTION_DRAIN_FAILED/);assert.equal(locked,true);assert(totals().cpu>before.cpu);refuse=false;await f.shell.drainInspector();assert.equal(locked,false);assert.equal(f.shell.inspectorSizeReads.ownership.cleanupFailures,0);}finally{refuse=false;await f.close();}assert.deepEqual(totals(),before);});
test('dimension-only publication does not discard a concurrently restored saved draft',async()=>{
 const before=totals(),f=fixture(),gate=deferred(),ui=cloneOwnedModel('inspector-test-ui',{drafts:[{kind:'inspector',documentId:document.id,targetLayerId:layer.id,status:'saved-unapplied',id:'saved',expectedDocumentRevision:'1'}]});let restore;
 try{f.editor.ui=ui.value;f.editor.pinUI=()=>ui.pin();const saved={...f.shell.fields.values,name:'Restored name'};f.editor.ownedDraftText=async id=>{assert.equal(id,'saved');await gate.promise;return cloneOwnedModel('inspector-test-draft',JSON.stringify(saved));};restore=f.shell.restoreInspector('document:layer');void restore.catch(()=>{});await flush();f.shell.loadInspectorDimensions();await flush();assert.equal(f.shell.fields.intrinsic.status,'ready');gate.resolve();await restore;assert.equal(f.shell.fields.values.name,'Restored name');assert.equal(f.shell.fields.intrinsic.status,'ready');}
 finally{gate.resolve();try{if(restore)await restore;}finally{try{await f.close();}finally{ui.release();}}}assert.deepEqual(totals(),before);
});
test('actual Apply uses the same revision fence and rejects incomplete friendly input before a command',async()=>{const before=totals(),f=fixture();try{f.shell.setFields(newInspector(layer,document,'draft',extent));f.shell.editInspector('width','-');await assert.rejects(f.shell.applyFields('transform'),/finite/);assert.equal(f.commands.length,0);assert.equal(f.shell.fields.values.width,'-');f.shell.editInspector('width','500');await f.shell.applyFields('transform');assert.equal(f.commands.length,1);assert.equal(f.commands[0].body.type,'ApplyTransform');assert.deepEqual(f.commands[0].target,document);close(Math.hypot(...f.commands[0].body.transform.slice(0,2))*extent.width,500);assert.equal(f.commands[0].body.transform[4],layer.layerToDocument[4]);}finally{await f.close();}assert.deepEqual(totals(),before);});
test('refused dimension payload is not retried on every render and leaves matrix editing available',async()=>{const before=totals(),f=fixture();let reads=0;try{f.route(async()=>{reads++;return new Response('{}',{headers:{'content-length':'65537'}});});f.shell.loadInspectorDimensions();await flush();assert.equal(f.shell.fields.intrinsic.status,'requested');assert.equal(f.shell.inspectorSizeAbort,undefined);assert.equal(f.failures.length,1);f.shell.loadInspectorDimensions();await flush();assert.equal(reads,1);assert.deepEqual(inspectorTransform(f.shell.fields),layer.layerToDocument);f.route(async()=>{reads++;return response(assetProjection());});f.shell.loadInspectorDimensions(true);await flush();assert.equal(reads,2);assert.equal(f.shell.fields.intrinsic.status,'ready');}finally{await f.close();}assert.deepEqual(totals(),before);});
test('native render refusal after draft publication keeps the installed inspector owner alive',async()=>{const before=totals(),f=fixture(),update=f.shell.requestUpdate;try{f.shell.requestUpdate=()=>{throw Error('native render unavailable');};assert.throws(()=>f.shell.editInspector('name','Published draft'),/native render unavailable/);assert.equal(f.shell.fields.values.name,'Published draft');assert.equal(f.writes.length,1);const unpin=f.shell.fieldsOwner.pin();unpin();}finally{f.shell.requestUpdate=update;await f.close();}assert.deepEqual(totals(),before);});

test('unsupported asset projection schema refuses dimensions before publication',async()=>{const before=totals(),f=fixture();try{f.route(async()=>{const value=assetProjection();value.projectionSchema=99;return response(value);});f.shell.loadInspectorDimensions();await flush();assert.equal(f.shell.fields.intrinsic.status,'requested');assert.equal(f.failures.length,1);assert.deepEqual(inspectorTransform(f.shell.fields),layer.layerToDocument);}finally{await f.close();}assert.deepEqual(totals(),before);});

test('same-ID metadata from a prior session cannot publish into the current inspector',async()=>{const before=totals(),f=fixture(),gate=deferred();try{f.route(async()=>{await gate.promise;return response(assetProjection());});f.shell.loadInspectorDimensions();await flush();f.editor.session={identity:()=> 'other-client'};gate.resolve();await flush();assert.equal(f.shell.fields.intrinsic.status,'requested');assert.equal(f.shell.inspectorSizeReads.ownership.activeReads,0);}finally{gate.resolve();await f.close();}assert.deepEqual(totals(),before);});
