import {confirmImageImports} from './image-import-flow.js';
// @ts-ignore Expected graph from sealed font inputs, never native output.
import {bundledFontIntent} from './completion/font-state.mjs';
import {busyStateObserver} from './completion/busy-state.mjs';
// @ts-ignore Test-only exact original durable Composition witness.
import {commandWitness,draftWitness} from './composition-save-witness.mjs';
import {readFile,writeFile,unlink} from 'node:fs/promises';
import {join} from 'node:path';
import sharp from 'sharp';
import {test,expect,fixture,click,field,state,rows,object,objectPath,sha} from './integration-fixture.js';
import type {Page} from '@playwright/test';
// @ts-ignore Test archive reader; expected object identities come from snapshots.
import {unpack,records} from '../portable/archive-fixture.mjs';

async function ready(page:Page,type:string){await expect(page.getByText(type+' accepted and saved locally.',{exact:true})).toBeVisible();}
async function textApply(page:Page,f:Awaited<ReturnType<typeof fixture>>,intent?:any){await f.native('Preview',async()=>{await click(page,'Preview text');await expect(page.getByText('Text preview ready. Accepted appearance is unchanged.',{exact:true})).toBeVisible();},intent);await f.native('Apply',async()=>{await click(page,'Apply text');await expect(page.locator('#native-text-editor')).toBeHidden();},intent);}
async function compose(page:Page){const choice=page.getByRole('radio',{name:'Composition',exact:true});await choice.focus();await expect(choice).toBeFocused();await page.keyboard.press('Space');await expect(choice).toBeChecked();await expect(page.getByRole('textbox',{name:'Scene',exact:true})).toBeVisible();}
async function reopen(page:Page,id:string){await click(page,'Open');await expect(page.getByRole('dialog',{name:'Open document',exact:true})).toBeVisible();await page.locator('en-dialog#editor-dialog').getByRole('button',{name:new RegExp(' · '+id.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+' · [0-9]+ × [0-9]+ · revision [0-9]+$')}).click();}
async function importCopy(page:Page,path:string){await click(page,'Open');await page.locator('en-file-upload[label="Open portable project"] input').setInputFiles(path);await expect(page.locator('#review-dialog')).toContainText('Apply opens a new local identity');await click(page,'Apply reviewed result');await ready(page,'ImportBundle');}

test('integrated public authoring preserves exact pixels, inactive history and drafts through real restart and two portable namespaces',async({page,context,browserName})=>{
 const f=await fixture(page,context,browserName,'combined');let primaryError:unknown;const compositionRequests:any[]=[];page.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).origin===f.server.origin&&/^\/api\/v1\/ui\/[^/]+$/.test(new URL(r.url()).pathname)){const request=r.postDataJSON();if(request?.body?.type==='SaveDraft'&&request.body.draft.kind==='composition')compositionRequests.push({original:r,request});}});
 const literal='Café e\u0301\nمرحبا',raw=' {"high_level_description":"Original raw","compositional_deconstruction":{"background":"","elements":[]}}\n';
 try{
  await f.admit();await click(page,'New');await field(page,'Width (px)','360');await field(page,'Height (px)','200');await click(page,'Create');
  await click(page,'Import image');await expect(page.getByRole('dialog',{name:'Import image',exact:true})).toBeVisible();await page.locator('en-dialog#editor-dialog').locator('en-file-upload input[type=file]').setInputFiles('tests/raster/fixtures/hidden-alpha.png');await confirmImageImports(page,{names:['hidden-alpha.png'],destination:'current'});await ready(page,'ImportAsset');
  await page.locator('#layer-tree').getByRole('treeitem').click();const advanced=page.getByRole('button',{name:'Advanced affine matrix',exact:true});await advanced.click();await expect(advanced).toHaveAttribute('aria-expanded','true');for(const [n,v] of [['A','30'],['D','30'],['X (document px)','10'],['Y (document px)','5']])await field(page,n,v);await click(page,'Apply transform');await ready(page,'ApplyTransform');
  await click(page,'Select');for(const [n,v] of [['Selection X','5'],['Selection Y','0'],['Selection width','95'],['Selection height','70']])await field(page,n,v);await click(page,'Apply selection');await click(page,'Use selection as mask');await field(page,'Feather radius (document px)','2');await click(page,'Preview mask');await expect(page.getByRole('button',{name:'Apply layer mask',exact:true})).toBeEnabled();await click(page,'Apply layer mask');await ready(page,'SetLayerProperties');
  await click(page,'Text');const input=page.locator('#native-text-content');await input.fill(literal);await page.getByRole('combobox',{name:'Font choice',exact:true}).selectOption('NotoSansArabic');await click(page,'Add explicit fallback');await field(page,'New text X (document px)','12.25');await field(page,'New text Y (document px)','80.5');await field(page,'Text frame height (document px)','100');
  await input.evaluate(el=>{const w=window as any;w.integrationNative=el;w.integrationParent=el.parentNode;(el as HTMLTextAreaElement).focus();(el as HTMLTextAreaElement).setSelectionRange(1,6,'backward');});await click(page,'Continue in inspector');await expect(input).toBeFocused();expect(await input.evaluate(el=>[el===(window as any).integrationNative,el.parentNode===(window as any).integrationParent,(el as HTMLTextAreaElement).selectionStart,(el as HTMLTextAreaElement).selectionEnd,(el as HTMLTextAreaElement).selectionDirection])).toEqual([true,true,1,6,'backward']);await click(page,'Return to card');await textApply(page,f);
  const initial=await state(f.root),textLayer=initial.image.layers.find((l:any)=>l.kind==='text'),imageLayer=initial.image.layers.find((l:any)=>l.kind==='image'),textSource=JSON.parse((await object(f.root,textLayer.source)).toString());
  expect(await object(f.root,textSource.text.textUtf8)).toEqual(Buffer.from(literal));expect(imageLayer.mask).not.toBeNull();expect(initial.image.composition??null).toBeNull();
  await compose(page);await click(page,'Raw caption inspection and Convert copy');await page.getByRole('textbox',{name:'Raw caption to retain',exact:true}).fill(raw);await click(page,'Retain and inspect raw');await expect(page.getByText('Original bytes retained separately. Inspection grants no authoring authority.',{exact:true})).toBeVisible();await click(page,'Convert copy…');await expect(page.getByRole('dialog',{name:'Review Convert copy'})).toBeVisible();await click(page,'Apply reviewed Convert copy');await expect(page.getByRole('dialog',{name:'Review Convert copy'})).toBeHidden();
  await click(page,'Add semantic text');await page.getByRole('combobox',{name:'Native layer for explicit links',exact:true}).selectOption(textLayer.id);await click(page,'Link content');await click(page,'Link bounds');await page.getByRole('textbox',{name:'Appearance description',exact:true}).fill('Independent literal appearance');await click(page,'Apply Composition');await expect(page.getByText('Composition applied and saved locally.',{exact:true})).toBeVisible();
  await page.getByRole('tab',{name:'Layers',exact:true}).click();await page.locator('#layer-tree').getByRole('treeitem',{name:/^Text ·/}).click();
  const beforeDerivative=await state(f.root),beforePNG=await f.png('before-raster.png'),canonicalAsset=rows(f.root,'assets').find(a=>a.id===beforeDerivative.document.image.compositeAssetId),canonicalPixels=await object(f.root,canonicalAsset.raster.pixels);
  expect(await sharp(beforePNG.bytes).ensureAlpha().raw().toBuffer()).toEqual(canonicalPixels);
  await click(page,'Rasterize text copy…');const rasterDialog=page.getByRole('dialog',{name:'Review text raster copy',exact:true}),rasterHost=page.locator('#editor-dialog');await expect(rasterDialog).toBeVisible();await expect(rasterHost).toContainText('editable text original');const reflow=[],colors:string[]=[];
  for(const colorScheme of ['light','dark'] as const){await page.emulateMedia({colorScheme});await page.evaluate(v=>document.documentElement.setAttribute('data-en-appearance',v),colorScheme);colors.push(await rasterHost.evaluate(el=>getComputedStyle(el).color));for(const width of [1440,720,320]){await page.setViewportSize({width,height:1000});for(const direction of ['ltr','rtl']){await page.evaluate(d=>document.documentElement.dir=d,direction);await expect(rasterDialog).toBeVisible();const action=rasterHost.getByRole('button',{name:'Create raster copy',exact:true});await action.scrollIntoViewIfNeeded();await action.focus();await expect(action).toBeFocused();const box=await action.boundingBox();expect(box).not.toBeNull();expect(box!.x).toBeGreaterThanOrEqual(-1);expect(box!.x+box!.width).toBeLessThanOrEqual(width+1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);reflow.push({colorScheme,width,direction,box});if(browserName==='chromium'&&((colorScheme==='light'&&width===720&&direction==='ltr')||(colorScheme==='dark'&&width===320&&direction==='rtl')))await page.screenshot({path:join(f.out,'raster-review-'+colorScheme+'-'+width+'-'+direction+'.png'),caret:'initial'});}}}
  expect(colors[0]).not.toBe(colors[1]);await writeFile(join(f.out,'raster-review-reflow.json'),JSON.stringify({colors,reflow},null,2));await page.setViewportSize({width:1440,height:1000});await page.emulateMedia({colorScheme:'dark'});await page.evaluate(()=>{document.documentElement.dir='ltr';document.documentElement.removeAttribute('data-en-appearance');});await rasterHost.getByRole('button',{name:'Cancel',exact:true}).focus();await page.keyboard.press('Enter');await expect(rasterDialog).toBeHidden();expect((await state(f.root)).document).toEqual(beforeDerivative.document);
  await click(page,'Rasterize text copy…');await click(page,'Create raster copy');await ready(page,'RasterizeTextDerivative');const derivative=await state(f.root);expect(derivative.image.layers.find((l:any)=>l.id===textLayer.id).visible).toBe(false);expect(derivative.image.layers.at(-1).kind).toBe('image');expect(await sharp((await f.png('raster-copy.png')).bytes).ensureAlpha().raw().toBuffer()).toEqual(canonicalPixels);
  await click(page,'Undo');await ready(page,'Undo');expect((await state(f.root)).image).toEqual(beforeDerivative.image);await click(page,'Redo');await ready(page,'Redo');expect((await state(f.root)).image).toEqual(derivative.image);await click(page,'Undo');await ready(page,'Undo');
  await page.locator('#layer-tree').getByRole('treeitem',{name:/^Text ·/}).click();await click(page,'Edit text');await input.fill(literal+' branch');await textApply(page,f);const branch=await state(f.root);expect(branch.document.branchId).not.toBe(derivative.document.branchId);
  await page.getByRole('tab',{name:'Composition',exact:true}).click();await page.locator('#semantic-tree').getByRole('treeitem').click();await click(page,'Preview request draft');await expect(page.locator('#composition-errors')).toContainText('STALE_LINK');await click(page,'Review current document');await page.getByRole('combobox',{name:'Native layer for explicit links',exact:true}).selectOption(textLayer.id);await click(page,'Link content');await click(page,'Link bounds');await click(page,'Apply Composition');await expect(page.getByText('Composition applied and saved locally.',{exact:true})).toBeVisible();
  await page.getByRole('textbox',{name:'Checkpoint name',exact:true}).fill('Combined authoring');await click(page,'Save checkpoint');await ready(page,'SaveCheckpoint');
  const savedCommand=f.commands.filter(c=>c.body.type==='SaveCheckpoint').at(-1),acceptedCheckpoint=commandWitness(f.root,savedCommand),draftOwner={clientId:savedCommand.clientId,sessionId:savedCommand.sessionId,documentId:savedCommand.documentId,revision:acceptedCheckpoint.document.revision,width:360,height:200},editStart=compositionRequests.length;
  await page.getByRole('textbox',{name:'Scene',exact:true}).fill('Unapplied semantic branch draft');await expect(page.getByRole('contentinfo').getByText('Accepted edits saved locally · Draft saved locally; not applied to the document',{exact:true})).toBeVisible();const ownSceneSaves=()=>compositionRequests.slice(editStart).filter(x=>x.request.sessionId===draftOwner.sessionId&&x.request.body.draft.documentId===draftOwner.documentId&&x.request.body.draft.expectedDocumentRevision===draftOwner.revision);await expect.poll(()=>ownSceneSaves().length).toBe(1);const sceneSave=ownSceneSaves()[0];await expect.poll(async()=>(await sceneSave.original.response())?.status()).toBe(200);const beforeView=draftWitness(f.root,draftOwner,sceneSave.request);expect(beforeView.graph.value.composition.scene).toBe('Unapplied semantic branch draft');await writeFile(join(f.out,'composition-before-view.json'),JSON.stringify(beforeView,null,2));await page.getByRole('radio',{name:'Plain prompt',exact:true}).focus();await page.keyboard.press('Space');await page.getByRole('textbox',{name:'Prompt',exact:true}).fill('Inactive plain prompt 日本語');await page.getByRole('textbox',{name:'Prompt',exact:true}).blur();
  await page.getByRole('tab',{name:'Layers',exact:true}).click();await page.locator('#layer-tree').getByRole('treeitem',{name:/^Text ·/}).click();await click(page,'Edit text');await input.fill('Unapplied native draft');await expect(page.getByRole('contentinfo').getByText('Accepted edits saved locally · Draft saved locally; not applied to the document',{exact:true})).toBeVisible();
  const saved=await state(f.root),savedUI=rows(f.root,'ui_checkpoints').find(u=>u.preferences.documentId===saved.document.id&&u.drafts.some((d:any)=>d.kind==='text'&&d.status==='saved-unapplied')),savedPNG=await f.png('saved-canonical.png'),first=await f.copy('first.ideogram-project'),entries=await unpack(f.out,first.bytes),all=records(entries).values;
  for(const ref of [textLayer.source,textSource.text.textUtf8,textSource.render.layout,textSource.render.pixels,...textSource.text.fonts.flatMap((x:any)=>[x.bytes,x.licenseRecord])])expect(entries.get('objects/'+ref.hash.slice(7))).toEqual(await object(f.root,ref));
  expect([...entries.values()].some((b:any)=>b.equals(Buffer.from(raw)))).toBe(true);expect(all.filter((r:any)=>r.entityType==='history').length).toBeGreaterThan(8);expect(all.some((r:any)=>r.entityType==='draft')).toBe(true);
  const beforeRestartDraft=savedUI.drafts.find((d:any)=>d.id===beforeView.selected.id);expect(beforeRestartDraft).toBeDefined();const restartRequests=compositionRequests.filter(x=>x.request.sessionId===draftOwner.sessionId&&x.request.body.draft.id===beforeRestartDraft.id&&x.request.body.draft.generation===beforeRestartDraft.generation);expect(restartRequests).toHaveLength(1);const beforeRestart=draftWitness(f.root,draftOwner,restartRequests[0].request);expect(beforeRestart.graph.value.composition.scene).toBe('Unapplied semantic branch draft');await writeFile(join(f.out,'composition-before-restart.json'),JSON.stringify(beforeRestart,null,2));
  await f.restart();await reopen(page,saved.document.id);expect((await state(f.root,saved.document.id)).image).toEqual(saved.image);expect(await sharp((await f.png('after-restart.png')).bytes).ensureAlpha().raw().toBuffer()).toEqual(await sharp(savedPNG.bytes).ensureAlpha().raw().toBuffer());
  await click(page,'Open');await page.getByRole('button',{name:new RegExp('^Restore '+savedUI.sessionId+' ·')}).click();await expect(input).toHaveValue('Unapplied native draft');await expect(page.getByRole('textbox',{name:'Prompt',exact:true})).toHaveValue('Inactive plain prompt 日本語');await click(page,'Cancel text edit');await expect(page.locator('#native-text-editor')).toBeHidden();await compose(page);await expect(page.getByRole('textbox',{name:'Scene',exact:true})).toHaveValue('Unapplied semantic branch draft');const afterRestart=draftWitness(f.root,draftOwner,restartRequests[0].request);expect(afterRestart.selected.id).toBe(beforeRestart.selected.id);expect(afterRestart.selected.generation).toBe(beforeRestart.selected.generation);expect(afterRestart.graph.sha256).toBe(beforeRestart.graph.sha256);expect(afterRestart.graph.value.composition.scene).toBe('Unapplied semantic branch draft');await writeFile(join(f.out,'composition-after-restart.json'),JSON.stringify(afterRestart,null,2));
  await importCopy(page,first.path);const imported=rows(f.root,'documents').find(d=>d.id!==saved.document.id);expect(imported.id).not.toBe(saved.document.id);const importedState=await state(f.root,imported.id);expect(importedState.image.layers.find((l:any)=>l.kind==='text').source).toEqual(saved.image.layers.find((l:any)=>l.kind==='text').source);
  expect(await sharp((await f.png('imported.png')).bytes).ensureAlpha().raw().toBuffer()).toEqual(await sharp(savedPNG.bytes).ensureAlpha().raw().toBuffer());const nested=await f.copy('nested.ideogram-project');expect(nested.bytes.includes(first.bytes)).toBe(true);await importCopy(page,nested.path);expect(rows(f.root,'documents')).toHaveLength(3);
  const finalDoc=rows(f.root,'documents').find(d=>![saved.document.id,imported.id].includes(d.id));await f.restart();await reopen(page,finalDoc.id);expect(await sharp((await f.png('nested-restarted.png')).bytes).ensureAlpha().raw().toBuffer()).toEqual(await sharp(savedPNG.bytes).ensureAlpha().raw().toBuffer());
  // Imported native layers must remain editable through the public workflow,
  // including after the nested namespace has survived a real server restart.
  const beforeImportedEdit=await state(f.root,finalDoc.id),originalBeforeImportedEdit=await state(f.root,saved.document.id),firstNamespaceBeforeEdit=await state(f.root,imported.id),importedTextLayer=beforeImportedEdit.image.layers.find((l:any)=>l.kind==='text');
  const importedTextSource=JSON.parse((await object(f.root,importedTextLayer.source)).toString()),editedLiteral=literal+' portable edit',priorHistoryIds=new Set(rows(f.root,'history').map(n=>n.id)),priorEditCommands=f.commands.filter(c=>c.body.type==='CommitTextEdit').length;
  expect(await object(f.root,importedTextSource.text.textUtf8)).toEqual(Buffer.from(literal+' branch'));
  await page.getByRole('tab',{name:'Layers',exact:true}).click();await page.locator('#layer-tree').getByRole('treeitem',{name:/^Text ·/}).click();await click(page,'Edit text');await expect(input).toHaveValue(literal+' branch');await expect(input).toBeEditable();await input.fill(editedLiteral);await textApply(page,f);
  const afterImportedEdit=await state(f.root,finalDoc.id),editedTextLayer=afterImportedEdit.image.layers.find((l:any)=>l.id===importedTextLayer.id),editedTextSource=JSON.parse((await object(f.root,editedTextLayer.source)).toString()),editCommand=f.commands.filter(c=>c.body.type==='CommitTextEdit').at(-1);
  expect(f.commands.filter(c=>c.body.type==='CommitTextEdit')).toHaveLength(priorEditCommands+1);expect(editCommand.documentId).toBe(finalDoc.id);expect(editCommand.body.layerId).toBe(importedTextLayer.id);
  expect(editedTextLayer.kind).toBe('text');expect(await object(f.root,editedTextSource.text.textUtf8)).toEqual(Buffer.from(editedLiteral));expect(editedTextSource.text.fonts).toEqual(importedTextSource.text.fonts);expect(editedTextSource.render.resolvedFonts).toEqual(importedTextSource.render.resolvedFonts);expect(editedTextSource.render.rendererProfile).toEqual(importedTextSource.render.rendererProfile);expect(editedTextSource.render.pixels.hash).not.toBe(importedTextSource.render.pixels.hash);
  const importedEditHistory=rows(f.root,'history').filter(n=>n.documentId===finalDoc.id&&!priorHistoryIds.has(n.id));expect(importedEditHistory).toHaveLength(1);expect(importedEditHistory[0].operation).toBe('CommitTextEdit');expect(importedEditHistory[0].parent).toBe(beforeImportedEdit.document.historyHead);expect(afterImportedEdit.document.historyHead).toBe(importedEditHistory[0].id);
  await click(page,'Undo');await ready(page,'Undo');const importedUndo=await state(f.root,finalDoc.id);expect(importedUndo.document.historyHead).toBe(beforeImportedEdit.document.historyHead);expect(importedUndo.image).toEqual(beforeImportedEdit.image);expect(await state(f.root,saved.document.id)).toEqual(originalBeforeImportedEdit);expect(await state(f.root,imported.id)).toEqual(firstNamespaceBeforeEdit);
  const importedEditEffects=await f.server.effects();expect(Object.keys(importedEditEffects)).toHaveLength(8);expect(Object.values(importedEditEffects)).toEqual(Array(8).fill(0));
  await writeFile(join(f.out,'imported-native-edit.json'),JSON.stringify({documentId:finalDoc.id,layerId:importedTextLayer.id,commandId:editCommand.commandId,priorHistoryHead:beforeImportedEdit.document.historyHead,editHistoryHead:afterImportedEdit.document.historyHead,undoHistoryHead:importedUndo.document.historyHead,beforeSource:importedTextLayer.source,afterSource:editedTextLayer.source,expectedText:editedLiteral,exactFonts:editedTextSource.text.fonts,originalDocumentUnchanged:true,firstNamespaceUnchanged:true,externalEffects:importedEditEffects},null,2));
  await writeFile(join(f.out,'closure.json'),JSON.stringify({originalDocument:saved.document,imported:imported.id,nested:finalDoc.id,originalText:textSource,canonicalPixelsSHA256:sha(canonicalPixels),firstBundleSHA256:sha(first.bytes),nestedBundleSHA256:sha(nested.bytes),exactRaw:true,historyRecords:all.filter((r:any)=>r.entityType==='history').length},null,2));
 }catch(error){primaryError=error;}finally{await f.finish(primaryError);}
});

test('real missing and corrupt historical fonts retain appearance, reviewed substitution and complete-copy refusal',async({page,context,browserName})=>{
 const f=await fixture(page,context,browserName,'font-recovery');let restore:{path:string;bytes:Buffer}|undefined;let primaryError:unknown;
 try{
  await f.admit();await click(page,'New');await field(page,'Width (px)','360');await field(page,'Height (px)','200');await click(page,'Create');await click(page,'Text');await page.locator('#native-text-content').fill('Original exact font');await textApply(page,f);
  const original=await state(f.root),layer=original.image.layers[0],source=JSON.parse((await object(f.root,layer.source)).toString()),font=source.text.fonts[0],asset=rows(f.root,'assets').find(a=>a.font?.id===font.id),originalPNG=await f.png('original.png');restore={path:objectPath(f.root,font.bytes),bytes:await object(f.root,font.bytes)};
  await unlink(restore.path);await f.restart();await reopen(page,original.document.id);expect(await sharp((await f.png('missing-retained.png')).bytes).ensureAlpha().raw().toBuffer()).toEqual(await sharp(originalPNG.bytes).ensureAlpha().raw().toBuffer());
  f.fault(f.server.origin+'/api/v1/assets/'+asset.id+'/content',404,'Own exact font object removed; retained canonical pixels remain present.');
  await page.locator('#layer-tree').getByRole('treeitem').click();await click(page,'Edit text');await expect(page.locator('#native-text-editor')).toContainText('Missing exact font bytes');await expect(page.locator('#native-text-content')).toHaveValue('Original exact font');await click(page,'Preview text');await expect(page.locator('#native-text-editor')).toContainText('Missing exact font bytes');const rejectedCount=f.commands.length;await click(page,'Apply text');await expect(page.locator('#native-text-editor')).toContainText('Preview the current text and font layout before Apply');expect(f.commands).toHaveLength(rejectedCount);expect((await state(f.root)).image).toEqual(original.image);
  await writeFile(restore.path,Buffer.from('corrupt current font'),{mode:0o600});await click(page,'Preview text');await expect(page.locator('#native-text-editor')).toContainText('Missing exact font bytes');expect((await state(f.root)).image).toEqual(original.image);expect(await sharp((await f.png('corrupt-current-retained.png')).bytes).ensureAlpha().raw().toBuffer()).toEqual(await sharp(originalPNG.bytes).ensureAlpha().raw().toBuffer());await unlink(restore.path);
  const substitution=await f.selectFont(bundledFontIntent('NotoSansArabic',source.text,'مرحبا'),original.document,'Original exact font');await f.native('Preview',async()=>{await click(page,'Preview text');await expect(page.getByText('Text preview ready. Accepted appearance is unchanged.',{exact:true})).toBeVisible();},substitution);
  const replacementIntent=await f.reopenFont(substitution,bundledFontIntent('NotoSansArabic',source.text,'مرحبا'),original.document,'Original exact font');expect((await state(f.root)).image).toEqual(original.image);await textApply(page,f,replacementIntent);const replacement=await state(f.root);expect(replacement.image.layers[0].source.hash).not.toBe(layer.source.hash);
  await click(page,'Save copy');await click(page,'Prepare complete copy');await expect(page.getByRole('dialog',{name:'Save project copy'})).toBeVisible();await expect(page.locator('#editor-dialog').getByRole('link',{name:/Content unavailable or missing|HASH|CORRUPT/})).toBeVisible();await page.locator('#editor-dialog').getByRole('button',{name:'Cancel',exact:true}).click();
  await click(page,'Undo');await ready(page,'Undo');expect((await state(f.root)).image).toEqual(original.image);expect(await sharp((await f.png('undo-missing.png')).bytes).ensureAlpha().raw().toBuffer()).toEqual(await sharp(originalPNG.bytes).ensureAlpha().raw().toBuffer());await click(page,'Redo');await ready(page,'Redo');
  await writeFile(restore.path,Buffer.from('corrupt retained font'),{mode:0o600});await click(page,'Save copy');await click(page,'Prepare complete copy');await expect(page.getByRole('dialog',{name:'Save project copy'})).toBeVisible();await expect(page.locator('#editor-dialog').getByRole('link',{name:/Content unavailable or missing|HASH|CORRUPT/})).toBeVisible();await page.locator('#editor-dialog').getByRole('button',{name:'Cancel',exact:true}).click();
  await unlink(restore.path);await click(page,'Undo');await ready(page,'Undo');await click(page,'Edit text');await click(page,'Local font import and exact relink');await page.locator('en-file-upload[label="Font file"] input').setInputFiles('vendor/text/fonts/NotoSans-Regular.ttf');await page.locator('en-file-upload[label="Font license record"] input').setInputFiles('vendor/text/notices/Noto-OFL.txt');await click(page,'Relink exact font');await expect(page.getByText('Exact font relinked. Prepare a fresh text preview.',{exact:true})).toBeVisible();expect(await object(f.root,font.bytes)).toEqual(restore.bytes);restore=undefined;await click(page,'Cancel text edit');await click(page,'Redo');await ready(page,'Redo');const copy=await f.copy('repaired-full-history.ideogram-project'),entries=await unpack(f.out,copy.bytes);expect(entries.get('objects/'+font.bytes.hash.slice(7))).toEqual(await object(f.root,font.bytes));expect(entries.get('objects/'+source.render.pixels.hash.slice(7))).toEqual(await object(f.root,source.render.pixels));expect(f.commands.filter(c=>c.body.type==='ReplaceTextFont')).toHaveLength(1);
  await writeFile(join(f.out,'recovery.json'),JSON.stringify({original:original.document,substitution:replacement.document,retainedFont:font,originalPixels:source.render.pixels,fullCopySHA256:sha(copy.bytes),oldHistoryMissingAfterSubstitution:true},null,2));
 }catch(error){primaryError=error;}finally{if(restore)await writeFile(restore.path,restore.bytes,{mode:0o600});await f.finish(primaryError);}
});


test('public text actions wait for the active save before accepting another operation',async({page,context,browserName})=>{
 const f=await fixture(page,context,browserName,'busy-actions');let primaryError:unknown;let release:()=>void=()=>{};
 try{
  await f.admit();await click(page,'New');await field(page,'Width (px)','360');await field(page,'Height (px)','200');await click(page,'Create');await click(page,'Text');await page.locator('#native-text-content').fill('Keep this draft during checkpoint');
  let reached:()=>void=()=>{},unblock:()=>void=()=>{},routeProof:any,heldRequest:any;const held=new Promise<void>(r=>reached=r),gate=new Promise<void>(r=>unblock=r);let released=false;release=()=>{if(!released){released=true;routeProof?.release();unblock();}};
  await page.route('**/api/v1/commands',async route=>{if(route.request().postDataJSON()?.command?.body?.type==='SaveCheckpoint'){heldRequest=route.request();routeProof=f.heldRoute(route);reached();await gate;if(routeProof)await routeProof.continue();else await route.continue();}else await route.continue();});
  await page.getByRole('textbox',{name:'Checkpoint name',exact:true}).fill('While editing');await click(page,'Save checkpoint');await held;
  for(const name of ['Preview text','Apply text'])await expect(page.getByRole('button',{name,exact:true})).toBeDisabled();
  await expect(page.getByRole('button',{name:'Cancel text edit',exact:true})).toBeEnabled();
  expect(await page.locator('#native-text-content').inputValue()).toBe('Keep this draft during checkpoint');
  const creations=f.commands.filter(c=>c.body.type==='CreateDocument');expect(creations).toHaveLength(1);const acceptedNative=busyStateObserver({root:f.root,origin:f.server.origin,request:heldRequest,created:creations[0],held:()=>!released});const acceptedBefore=acceptedNative();routeProof?.publicBefore({previewDisabled:await page.getByRole('button',{name:'Preview text',exact:true}).isDisabled(),applyDisabled:await page.getByRole('button',{name:'Apply text',exact:true}).isDisabled(),cancelDisabled:await page.getByRole('button',{name:'Cancel text edit',exact:true}).isDisabled(),text:await page.locator('#native-text-content').inputValue(),acceptedNative:acceptedBefore});
  await page.getByRole('button',{name:'Cancel text edit',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.locator('#native-text-editor')).toBeHidden();const acceptedAfter=acceptedNative();expect(acceptedAfter).toEqual(acceptedBefore);routeProof?.publicAfter({editorHidden:await page.locator('#native-text-editor').isHidden(),stillHeld:!released,commands:structuredClone(f.commands),acceptedNative:acceptedAfter});release();await ready(page,'SaveCheckpoint');await page.unroute('**/api/v1/commands');expect(f.commands.some(c=>['CreateTextLayer','CommitTextEdit'].includes(c.body.type))).toBe(false);
 }catch(error){primaryError=error;}finally{release();await f.finish(primaryError);}
});
