import {test as base,expect,type Page} from '@playwright/test';
import {mkdtemp,realpath,mkdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {serverProcess} from './process.js';
import {ownedOPFS} from './owned-opfs.js';
import {recordDOMErrors} from './error-monitor.js';
import {textBarrier} from './text-barrier.js';
import {DatabaseSync} from 'node:sqlite';
const test=base.extend({context:async({playwright,browserName,contextOptions,viewport},use)=>{
 const profile=browserName==='webkit'?await mkdtemp(join(await realpath(tmpdir()),'ie-p1c4-webkit-')):undefined;
 const browser=profile?undefined:await playwright[browserName].launch();
 const context=profile?await playwright.webkit.launchPersistentContext(profile,{...contextOptions,viewport}):await browser!.newContext({...contextOptions,viewport});
 await Promise.all(context.pages().map(p=>p.close()));
 try{await use(context);}finally{await context.close();await browser?.close();if(profile)await rm(profile,{recursive:true,force:true});}
}});
const receipt=process.env.EDITOR_RECEIPT??'artifacts/p1c4/browser';
const click=(p:Page,name:string)=>p.getByRole('button',{name,exact:true}).click();
async function field(p:Page,name:string,value:string){const f=p.getByRole('spinbutton',{name,exact:true});await f.fill(value);await f.press('Tab');}
async function setup(page:Page){await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await click(page,'New');await field(page,'Width (px)','360');await field(page,'Height (px)','200');await click(page,'Create');await click(page,'Text');await expect(page.locator('#native-text-content')).toBeVisible();}
test('native F05 range, input, responsive parent and deferred composition authority',async({page,context,browserName})=>{
 const guard=await ownedOPFS(context,'p1c4-native-'+browserName),errors=await recordDOMErrors(context),commands:string[]=[],consoleErrors:string[]=[];
 page.on('pageerror',e=>consoleErrors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});
 page.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname==='/api/v1/commands')commands.push(JSON.parse(r.postData()!).command.body.type);});
 const dir=await mkdtemp(join(await realpath(tmpdir()),'ie-p1c4-')),server=await serverProcess(join(dir,'private'));await mkdir(receipt,{recursive:true});
 try{
  await guard.admit(page,server.origin);await page.goto(await server.pair());await setup(page);const input=page.locator('#native-text-content');
  await input.fill('A😀é\n東京\n'+('Scroll line\n'.repeat(20)));const before=await page.locator('.document-name').textContent();
  await input.evaluate(el=>{const w=window as any;w.nativeNode=el;w.nativeParent=el.parentNode;w.nativeDisconnected=false;w.nativeObserver=new MutationObserver(()=>{if(!el.isConnected||el.parentNode!==w.nativeParent)w.nativeDisconnected=true;});w.nativeObserver.observe(document,{childList:true,subtree:true});});
  await page.evaluate(()=>{const w=window as any;w.nativeEvents=[];for(const type of ['pointerdown','click','focusin','select','scroll'])document.addEventListener(type,e=>{const t=document.querySelector('#native-text-content') as HTMLTextAreaElement;w.nativeEvents.push({at:performance.now(),type,target:(e.target as Element).tagName,start:t.selectionStart,end:t.selectionEnd,direction:t.selectionDirection,top:t.scrollTop,presentation:document.querySelector('#native-text-editor')?.getAttribute('data-presentation')});},{capture:true});});
  for(const [start,end,direction] of [[1,5,'forward'],[1,5,'backward'],[5,5,'none'],[0,0,'none']] as const){
    await input.evaluate((el,args)=>{const t=el as HTMLTextAreaElement;t.focus();t.setSelectionRange(args.start,args.end,args.direction);},{start,end,direction});
    // Let native caret reveal settle before establishing the scroll baseline.
    await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await input.evaluate(el=>{(el as HTMLTextAreaElement).scrollTop=30;});
    const actual=await input.evaluate(el=>{const t=el as HTMLTextAreaElement;return {start:t.selectionStart,end:t.selectionEnd,direction:t.selectionDirection,scrollTop:t.scrollTop,scrollLeft:t.scrollLeft};});
    await click(page,'Continue in inspector');await expect(input).toBeFocused();
    expect(await input.evaluate(el=>{const t=el as HTMLTextAreaElement;return {start:t.selectionStart,end:t.selectionEnd,direction:t.selectionDirection,scrollTop:t.scrollTop,scrollLeft:t.scrollLeft};})).toEqual(actual);
    await click(page,'Return to card');await expect(input).toBeFocused();
  }
  // A newer native range must defeat an older scheduled presentation restore.
  await input.evaluate(el=>(el as HTMLTextAreaElement).setSelectionRange(1,5,'forward'));
  await page.locator('#native-text-editor en-button').filter({hasText:'Continue in inspector'}).evaluate(h=>h.addEventListener('click',()=>setTimeout(()=>{(document.querySelector('#native-text-content') as HTMLTextAreaElement).setSelectionRange(0,0,'none');},0),{once:true}));
  await click(page,'Continue in inspector');await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));expect(await input.evaluate(el=>[(el as HTMLTextAreaElement).selectionStart,(el as HTMLTextAreaElement).selectionEnd])).toEqual([0,0]);await click(page,'Return to card');
  // A later real focus intent must defeat the scheduled presentation restore.
  await page.locator('#native-text-editor en-button').filter({hasText:'Continue in inspector'}).evaluate(h=>h.addEventListener('click',()=>setTimeout(()=>{(document.querySelector('#prompt') as any).focus();},0),{once:true}));
  await click(page,'Continue in inspector');await expect(page.getByRole('textbox',{name:'Prompt',exact:true})).toBeFocused();await click(page,'Return to card');await expect(input).toBeFocused();
  await input.fill('native undo');await input.press('End');await input.pressSequentially(' xyz');await input.press(process.platform==='darwin'?'Meta+z':'Control+z');await expect(input).not.toHaveValue('native undo xyz');await input.press(process.platform==='darwin'?'Meta+Shift+z':'Control+Shift+z');await expect(input).toHaveValue('native undo xyz');
  for(const width of [1000,720,320,1440]){await page.setViewportSize({width,height:1000});for(const dir of ['ltr','rtl']){await page.evaluate(v=>document.documentElement.dir=v,dir);expect(await input.evaluate(el=>el===(window as any).nativeNode&&el.parentNode===(window as any).nativeParent&&el.isConnected)).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}}
  for(const colorScheme of ['light','dark'] as const){await page.emulateMedia({colorScheme});expect(await input.evaluate(el=>el===(window as any).nativeNode&&el.parentNode===(window as any).nativeParent&&el.isConnected)).toBe(true);expect(await input.isVisible()).toBe(true);}
  await page.evaluate(()=>document.documentElement.dir='ltr');await input.focus();await input.dispatchEvent('compositionstart');await input.evaluate(el=>{(el as HTMLTextAreaElement).value='composing';});await input.dispatchEvent('input',{isComposing:true,inputType:'insertCompositionText'});
  await click(page,'Continue in inspector');await expect(page.getByText('Switch after composition',{exact:true})).toBeVisible();await expect(page.locator('#native-text-editor')).toHaveAttribute('data-presentation','anchored');await expect(input).toBeFocused();
  await click(page,'Cancel switch');await input.dispatchEvent('compositionend');await input.dispatchEvent('input',{isComposing:false,inputType:'insertCompositionText'});await expect(page.locator('#native-text-editor')).toHaveAttribute('data-presentation','anchored');
  await input.dispatchEvent('compositionstart');await click(page,'Continue in inspector');await click(page,'Cancel text edit');await expect(input).toBeVisible();await input.dispatchEvent('compositionend');await expect(page.locator('#native-text-editor')).toBeHidden();
  expect(await page.locator('.document-name').textContent()).toBe(before);expect(commands.filter(c=>['CreateTextLayer','CommitTextEdit','ReplaceTextFont'].includes(c))).toEqual([]);expect(await page.evaluate(()=>(window as any).nativeDisconnected)).toBe(false);
  expect(errors).toEqual([]);expect(consoleErrors).toEqual([]);expect(Object.values(await server.effects()).every(n=>n===0)).toBe(true);
 }finally{await writeFile(join(receipt,'native-events.json'),JSON.stringify(await page.evaluate(()=>(window as any).nativeEvents??[]).catch(()=>[]),null,2));try{for(const p of context.pages())await p.goto('about:blank');await guard.cleanup();guard.verify();}finally{await writeFile(join(receipt,'native-ownership.json'),JSON.stringify(guard.ledger,null,2));await writeFile(join(receipt,'native-errors.json'),JSON.stringify({errors,consoleErrors,commands},null,2));await server.close();}}
});
test('native text durable create edit empty undo recovery and reviewed font failure',async({page,context,browserName})=>{
 const guard=await ownedOPFS(context,'p1c4-durable-'+browserName),errors=await recordDOMErrors(context),commands:any[]=[];const dir=await mkdtemp(join(await realpath(tmpdir()),'ie-p1c4-durable-')),server=await serverProcess(join(dir,'private'));await mkdir(receipt,{recursive:true});
 page.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname==='/api/v1/commands')commands.push(JSON.parse(r.postData()!).command.body);});
 try{
  await guard.admit(page,server.origin);await page.goto(await server.pair());await setup(page);const input=page.locator('#native-text-content');
  await input.fill('First text');await field(page,'New text X (document px)','-2.5');await field(page,'New text Y (document px)','8.25');await field(page,'Text size (document px)','24');await click(page,'Preview text');await expect(page.getByText('Text preview ready. Accepted appearance is unchanged.',{exact:true})).toBeVisible();await page.locator('#native-text-editor en-button').filter({hasText:'Apply text'}).evaluate(h=>h.addEventListener('click',e=>e.preventDefault(),{once:true}));await click(page,'Apply text');await expect(page.locator('#native-text-editor')).toBeVisible();expect(commands.filter(c=>c.type==='CreateTextLayer')).toHaveLength(0);await page.screenshot({path:join(receipt,'create-preview.png')});await input.focus();await input.dispatchEvent('compositionstart');await click(page,'Apply text');await expect(page.locator('#native-text-editor')).toBeVisible();expect(commands.filter(c=>c.type==='CreateTextLayer')).toHaveLength(0);await input.dispatchEvent('compositionend');await expect(page.getByRole('treeitem')).toContainText('Text · Text');await expect(page.locator('#native-text-editor')).toBeHidden();expect(commands.filter(c=>c.type==='CreateTextLayer')).toHaveLength(1);expect(commands.find(c=>c.type==='CreateTextLayer').placement).toEqual({x:-2.5,y:8.25});await expect(page.getByRole('spinbutton',{name:'X',exact:true})).toHaveValue('-2.5');await click(page,'Undo');await expect(page.getByRole('treeitem')).toHaveCount(0);await click(page,'Redo');await expect(page.getByRole('treeitem')).toHaveCount(1);await page.getByRole('treeitem').click();
  await click(page,'Edit text');await expect(input).toHaveValue('First text');await input.fill('Saved draft');await expect(page.getByText('Draft saved locally; not applied to the document',{exact:true}).first()).toBeVisible();await page.reload();await expect(page.getByText('Recovered text draft. It has not been applied.',{exact:true})).toBeVisible();await expect(input).toHaveValue('Saved draft');await click(page,'Cancel text edit');
  await click(page,'Edit text');await expect(input).toHaveValue('First text');await input.fill('🧑');await click(page,'Preview text');await expect(page.locator('#native-text-editor en-alert').filter({hasText:'Missing glyphs in selected fonts'})).toBeVisible();expect(commands.filter(c=>c.type==='CommitTextEdit')).toHaveLength(0);
  await input.fill('');await click(page,'Preview text');await expect(page.getByText('Text preview ready. Accepted appearance is unchanged.',{exact:true})).toBeVisible();await click(page,'Apply text');await expect(page.locator('#native-text-editor')).toBeHidden();await expect(page.getByRole('treeitem')).toHaveCount(1);expect(commands.filter(c=>c.type==='CommitTextEdit')).toHaveLength(1);
  await click(page,'Undo');await expect(page.getByText('Undo accepted and saved locally.',{exact:true})).toBeVisible();await click(page,'Edit text');await expect(input).toHaveValue('First text');await page.getByRole('combobox',{name:'Font choice',exact:true}).selectOption('NotoSansArabic');await click(page,'Use selected font');await input.fill('مرحبا');await click(page,'Preview text');await expect(page.getByText('Text preview ready. Accepted appearance is unchanged.',{exact:true})).toBeVisible();await click(page,'Apply text');await expect(page.locator('#native-text-editor')).toBeHidden();expect(commands.filter(c=>c.type==='ReplaceTextFont')).toHaveLength(1);
  expect(errors).toEqual([]);expect(Object.values(await server.effects()).every(n=>n===0)).toBe(true);
 }finally{try{for(const p of context.pages())await p.goto('about:blank');await guard.cleanup();guard.verify();}finally{await writeFile(join(receipt,'durable-ownership.json'),JSON.stringify(guard.ledger,null,2));await writeFile(join(receipt,'durable-errors.json'),JSON.stringify({errors,commands},null,2));await server.close();}}
});

test('text revision conflicts, over-limit retention, overflow and font recovery stay explicit',async({page,context,browserName})=>{
 const guard=await ownedOPFS(context,'p1c4-conflict-'+browserName),errors=await recordDOMErrors(context),dir=await mkdtemp(join(await realpath(tmpdir()),'ie-p1c4-conflict-')),server=await serverProcess(join(dir,'private'));await mkdir(receipt,{recursive:true});
 let fontURL='';const commands:any[]=[];page.on('request',r=>{if(r.method()==='HEAD'&&new URL(r.url()).pathname.startsWith('/api/v1/assets/'))fontURL=r.url();if(r.method()==='POST'&&new URL(r.url()).pathname==='/api/v1/commands')commands.push(JSON.parse(r.postData()!).command.body);});
 try{
  await guard.admit(page,server.origin);await page.goto(await server.pair());await setup(page);const input=page.locator('#native-text-content');
  await input.fill('First\nSecond\nThird');await field(page,'Text frame height (document px)','20');await click(page,'Preview text');await expect(page.locator('#native-text-editor en-alert').filter({hasText:'Clipped overflow.'})).toBeVisible();await click(page,'Apply text');await expect(page.locator('#native-text-editor')).toBeHidden();await click(page,'Edit text');
  await input.fill('\ufeff'.concat('x'.repeat(70000)));await click(page,'Preview text');await expect(page.locator('#native-text-editor en-alert').filter({hasText:'TEXT_BYTES'})).toBeVisible();await expect(input).toHaveValue('\ufeff'.concat('x'.repeat(70000)));await expect(page.getByText('Draft saved locally; not applied to the document',{exact:true}).first()).toBeVisible();await page.reload();await expect(input).toHaveValue('\ufeff'.concat('x'.repeat(70000)));await click(page,'Cancel text edit');await click(page,'Edit text');
  expect(fontURL).toContain('/api/v1/assets/');await page.route(fontURL,route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":{"code":"FONT_UNAVAILABLE"}}'}));
  await click(page,'Preview text');await expect(page.locator('#native-text-editor en-alert').filter({hasText:'Missing exact font bytes.'}).last()).toBeVisible();await expect(input).toHaveValue('First\nSecond\nThird');expect(commands.filter(c=>c.type==='CommitTextEdit')).toHaveLength(0);await page.unroute(fontURL);
  await click(page,'Preview text');await expect(page.getByText('Text preview ready. Accepted appearance is unchanged.',{exact:true})).toBeVisible();
  const second=await context.newPage();await second.goto(server.origin);await expect(second.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await second.getByRole('treeitem').first().click();await field(second,'Opacity (0–1)','0.5');await click(second,'Apply properties');await expect(second.getByText('SetLayerProperties accepted and saved locally.',{exact:true})).toBeVisible();await expect(page.locator('#native-text-editor en-alert').filter({hasText:'Stale text draft.'})).toBeVisible();await expect(page.getByRole('button',{name:'Apply text',exact:true})).toBeDisabled();await expect(input).toHaveValue('First\nSecond\nThird');await second.close();await click(page,'Cancel text edit');
  expect(errors).toEqual([]);expect(Object.values(await server.effects()).every(n=>n===0)).toBe(true);
 }finally{try{for(const p of context.pages())await p.goto('about:blank');await guard.cleanup();guard.verify();}finally{await writeFile(join(receipt,'conflict-ownership.json'),JSON.stringify(guard.ledger,null,2));await writeFile(join(receipt,'conflict-errors.json'),JSON.stringify({errors,commands},null,2));await server.close();}}
});

test('font import, exact relink, locked copy and recovered initial placement',async({page,context,browserName})=>{
 const guard=await ownedOPFS(context,'p1c4-font-'+browserName),errors=await recordDOMErrors(context),dir=await mkdtemp(join(await realpath(tmpdir()),'ie-p1c4-font-')),server=await serverProcess(join(dir,'private'));await mkdir(receipt,{recursive:true});
 try{
  await guard.admit(page,server.origin);await page.goto(await server.pair());await setup(page);const input=page.locator('#native-text-content');await input.fill('Recover position');await field(page,'New text X (document px)','-3.75');await field(page,'New text Y (document px)','12.5');await expect(page.getByText('Draft saved locally; not applied to the document',{exact:true}).first()).toBeVisible();await page.reload();await expect(input).toHaveValue('Recover position');await expect(page.getByRole('spinbutton',{name:'New text X (document px)',exact:true})).toHaveValue('-3.75');
  await click(page,'Local font import and exact relink');await page.locator('en-file-upload[label="Font file"] input').setInputFiles('vendor/text/fonts/NotoSansArabic-Regular.ttf');await page.locator('en-file-upload[label="Font license record"] input').setInputFiles('vendor/text/notices/Noto-OFL.txt');await click(page,'Relink exact font');await expect(page.locator('#native-text-editor en-alert').filter({hasText:'Exact relink requires matching'})).toBeVisible();
  await page.locator('en-file-upload[label="Font file"] input').setInputFiles('vendor/text/fonts/NotoSans-Regular.ttf');await click(page,'Relink exact font');await expect(page.getByText('Exact font relinked. Prepare a fresh text preview.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Import as substitution draft',exact:true})).toBeDisabled();await page.getByRole('switch',{name:'I have permission to embed this font',exact:true}).check();await click(page,'Import as substitution draft');await expect(page.locator('#native-text-editor en-alert').filter({hasText:'Substitution draft: validated local regular font'})).toBeVisible();
  await click(page,'Preview text');await expect(page.getByText('Text preview ready. Accepted appearance is unchanged.',{exact:true})).toBeVisible();await click(page,'Apply text');await expect(page.locator('#native-text-editor')).toBeHidden();await expect(page.getByRole('spinbutton',{name:'X',exact:true})).toHaveValue('-3.75');await click(page,'Lock layer');await click(page,'Edit text');await expect(input).toHaveAttribute('readonly','');await expect(input).toHaveValue('Recover position');await expect(page.getByRole('button',{name:'Apply text',exact:true})).toBeDisabled();await input.focus();await input.press(process.platform==='darwin'?'Meta+a':'Control+a');expect(await input.evaluate(el=>(el as HTMLTextAreaElement).selectionEnd)).toBe('Recover position'.length);await click(page,'Cancel text edit');
  expect(errors).toEqual([]);expect(Object.values(await server.effects()).every(n=>n===0)).toBe(true);
 }finally{try{for(const p of context.pages())await p.goto('about:blank');await guard.cleanup();guard.verify();}finally{await writeFile(join(receipt,'font-ownership.json'),JSON.stringify(guard.ledger,null,2));await writeFile(join(receipt,'font-errors.json'),JSON.stringify({errors},null,2));await server.close();}}
});

test('placement mismatch and final changed draft refuse without history; next valid Apply succeeds',async({page,context,browserName})=>{
 const guard=await ownedOPFS(context,'p1c4-fence-'+browserName),errors=await recordDOMErrors(context),dir=await mkdtemp(join(await realpath(tmpdir()),'ie-p1c4-fence-')),root=join(dir,'private'),server=await textBarrier(root);await mkdir(receipt,{recursive:true});let saved:string|undefined;
 try{
  await guard.admit(page,server.origin);await page.goto(await server.pair());await setup(page);await page.locator('#native-text-content').fill('Atomic position');await field(page,'New text X (document px)','12.25');await click(page,'Preview text');await expect(page.getByText('Text preview ready. Accepted appearance is unchanged.',{exact:true})).toBeVisible();
  let tampered=false;await page.route('**/api/v1/commands',async route=>{const body=route.request().postDataJSON();if(!tampered&&body.command.body.type==='CreateTextLayer'){tampered=true;body.command.body.placement.x=99;await route.continue({postData:JSON.stringify(body)});}else await route.continue();});await click(page,'Apply text');await expect(page.locator('#native-text-editor en-alert').filter({hasText:'TEXT_DRAFT_PLACEMENT_CHANGED'})).toBeVisible();await expect(page.getByRole('treeitem')).toHaveCount(0);await page.unroute('**/api/v1/commands');
  await click(page,'Preview text');await expect(page.getByText('Text preview ready. Accepted appearance is unchanged.',{exact:true})).toBeVisible();await click(page,'Apply text');await server.wait();
  const db=new DatabaseSync(join(root,'metadata.sqlite'));try{const row=db.prepare('SELECT json FROM ui_checkpoints WHERE json LIKE ?').get('%text-draft%')??db.prepare('SELECT json FROM ui_checkpoints WHERE json LIKE ?').get('%"kind":"text"%');saved=String(row!.json);const checkpoint=JSON.parse(saved);checkpoint.drafts.find((d:any)=>d.kind==='text').generation='999';db.prepare('UPDATE ui_checkpoints SET json=? WHERE json=?').run(JSON.stringify(checkpoint),saved);}finally{db.close();}server.release();
  await expect(page.locator('#native-text-editor en-alert').filter({hasText:'DRAFT_GENERATION_CHANGED'})).toBeVisible();await expect(page.getByRole('treeitem')).toHaveCount(0);
  const restore=new DatabaseSync(join(root,'metadata.sqlite'));try{restore.prepare('UPDATE ui_checkpoints SET json=? WHERE json LIKE ?').run(saved!,'%"kind":"text"%');}finally{restore.close();}saved=undefined;
  await click(page,'Preview text');await expect(page.getByText('Text preview ready. Accepted appearance is unchanged.',{exact:true})).toBeVisible();await click(page,'Apply text');await expect(page.locator('#native-text-editor')).toBeHidden();await expect(page.getByRole('treeitem')).toHaveCount(1);await expect(page.getByRole('spinbutton',{name:'X',exact:true})).toHaveValue('12.25');expect(errors).toEqual([]);expect(Object.values(await server.effects()).every(n=>n===0)).toBe(true);
 }finally{server.release();try{for(const p of context.pages())await p.goto('about:blank');await guard.cleanup();guard.verify();}finally{await writeFile(join(receipt,'fence-ownership.json'),JSON.stringify(guard.ledger,null,2));await writeFile(join(receipt,'fence-errors.json'),JSON.stringify({errors,scope:'Fresh owned database fault injection after proofs, before final acceptance; rejected draft restored before next valid request.'},null,2));await server.close();}}
});
