// Source-only authored; no execution in the staging turn.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {transformWithOxc} from 'vite';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import {allocationsURL as allocations,promptMemoryURL as prompt} from '../owned-preview-module.mjs';
import {draftStateDependencies} from '../draft-state-module.mjs';
import {viewModelDependencies} from '../view-model-module.mjs';
const root=process.env.QUEUED_REPLACEMENT_ROOT??'.',data=value=>'data:text/javascript;base64,'+Buffer.from(value).toString('base64');
async function source(path,imports={}){let code=(await transformWithOxc(await readFile(path,'utf8'),path)).code;for(const [key,value]of Object.entries(imports))code=code.replaceAll(JSON.stringify(key),JSON.stringify(value)).replaceAll("'"+key+"'",JSON.stringify(value));return data(code);}
const {draftURL,memoryURL:memory,controlURL,commandsURL}=await draftStateDependencies(allocations,{promptURL:prompt});
const {viewURL}=await viewModelDependencies(allocations,{memoryURL:memory,promptURL:prompt,controlURL});
const fenceURL=await source('src/state/queued-replacement-fence.ts',{'../observability/model-memory.js':memory}),resourcesURL=await source('src/state/document-lifecycle.ts'),registrationURL=await source('src/ui/request-prompt-memory.ts',{'../observability/prompt-memory.js':prompt,'../observability/allocations.js':allocations});
const {allocationLedger,ALLOCATION_LIMITS}=await import(allocations),{captureQueuedReplacementFence,queuedDraftsClean,QUEUED_REPLACEMENT_LIMITS}=await import(fenceURL),{DraftPersistence}=await import(draftURL),{cloneOwnedModel}=await import(memory),{registerRequestEntry}=await import(registrationURL);
const totals=()=>{const s=allocationLedger.snapshot();return {cpu:s.cpuBytes,handles:s.handles,records:s.activeRecords};},flush=async()=>{for(let n=0;n<40;n++)await Promise.resolve();};
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const row=(generation='1')=>({generation,savedGeneration:generation,pending:false,composing:false,error:null});
const fake=()=>({hasRefusedChanges:false,hasPendingRequests:false,checkpoint:{uiSeq:'1'},drafts:new Map([['draft',row()]])});
test('scalar fence detects saved-generation, membership, checkpoint identity and sequence changes',()=>{const baseline=totals(),owner=fake(),fence=captureQueuedReplacementFence(owner);try{assert.equal(fence.unchanged(owner),true);owner.drafts.set('draft',row('2'));assert.equal(fence.unchanged(owner),false);owner.drafts.set('draft',row());owner.drafts.set('new',row());assert.equal(fence.unchanged(owner),false);owner.drafts.delete('new');owner.checkpoint.uiSeq='2';assert.equal(fence.unchanged(owner),false);owner.checkpoint.uiSeq='1';assert.equal(fence.unchanged(owner),true);owner.checkpoint={uiSeq:'1'};assert.equal(fence.unchanged(owner),false);}finally{fence.release();fence.release();}assert.equal(fence.unchanged(owner),false);assert.deepEqual(totals(),baseline);});
test('count and byte admission preserve the complete original inventory without truncation',()=>{const baseline=totals(),owner=fake();owner.drafts=new Map(Array.from({length:QUEUED_REPLACEMENT_LIMITS.drafts+1},(_,i)=>['draft_'+i,row()]));assert.throws(()=>captureQueuedReplacementFence(owner),/current input and saved replacement are retained/);assert.equal(owner.drafts.size,4097);assert.throws(()=>queuedDraftsClean(owner),/review allowance/);owner.drafts=new Map(Array.from({length:4096},(_,i)=>[('draft_'+i).padEnd(128,'x'),row('1'.repeat(128))]));assert.throws(()=>captureQueuedReplacementFence(owner),/review allowance/);assert.equal(owner.drafts.size,4096);assert.deepEqual(totals(),baseline);});
test('central admission refusal leaves no fence or scan owner behind',()=>{const baseline=totals(),owner=fake(),held=allocationLedger.reserve({owner:'queue-test-pressure',kind:'control',cpuBytes:ALLOCATION_LIMITS.cpuBytes-ALLOCATION_LIMITS.textPartitionBytes-allocationLedger.snapshot().cpuBytes-1024});try{assert.throws(()=>captureQueuedReplacementFence(owner),/ALLOCATION_BUDGET/);assert.equal(owner.drafts.get('draft').generation,'1');}finally{held.release();}assert.deepEqual(totals(),baseline);});
test('clean checks inspect real scalar state without constructing a pending request list',()=>{const owner=fake();owner.pendingRequests=()=>assert.fail('must not allocate a request array');assert.equal(queuedDraftsClean(owner),true);for(const key of ['pending','composing','error']){owner.drafts.get('draft')[key]=key==='error'?'conflict':true;assert.equal(queuedDraftsClean(owner),false);owner.drafts.get('draft')[key]=key==='error'?null:false;}owner.hasPendingRequests=true;assert.equal(queuedDraftsClean(owner),false);owner.hasPendingRequests=false;owner.hasRefusedChanges=true;assert.equal(queuedDraftsClean(owner),false);});

const clientCode=(await transformWithOxc(await readFile(root+'/src/state/editor-client.ts','utf8'),'editor-client.ts')).code.replace(/^import\s+[\s\S]*?\sfrom\s+["'][^"']+["'];?\n/gm,'');
const {EditorClient}=await import(data(`import {DraftPersistence} from ${JSON.stringify(draftURL)};import {captureQueuedReplacementFence,queuedDraftsClean,queuedReplacementOperation} from ${JSON.stringify(fenceURL)};import {createValueModel} from ${JSON.stringify(pathToFileURL(createRequire(import.meta.url).resolve('@en-reve/primitives/state/value.js')).href)};import {allocationLedger} from ${JSON.stringify(allocations)};import {ModelPayload} from ${JSON.stringify(memory)};import {ViewModelOwners,ViewModelReads} from ${JSON.stringify(viewURL)};import {CommandControlReads} from ${JSON.stringify(commandsURL)};import {DocumentResources} from ${JSON.stringify(resourcesURL)};
const browserPhases={resetNavigation(){},reset(){}};const sessionStorage={getItem(){return 'session';},setItem(){}};class RecoveryCache{static async open(){return {close(){}};}};class RecoveryConsumer{cancel(){}async release(){}};class BrowserJournal{static async open(){throw Error('Unexpected new journal');}}
`+clientCode));
const response=(value,status=200)=>{const text=JSON.stringify(value);return new Response(text,{status,headers:{'content-length':String(Buffer.byteLength(text))}});};
const checkpoint=()=>({sessionId:'session',uiSeq:'2',preferences:{documentId:null,selectedLayerIds:[]},drafts:[{id:'replacement',kind:'request',status:'saved-unapplied',documentId:'document'}]});
function fixture(){let transport=async()=>response(checkpoint());const session={identity:()=> 'client',csrf:()=> 'csrf',transport:(...args)=>transport(...args)},client=new EditorClient(session),old=new DraftPersistence('session',session.transport,session.csrf),notices=[];
 old.checkpoint={sessionId:'session',uiSeq:'1',preferences:{documentId:'document',selectedLayerIds:[]},drafts:[]};old.change({id:'draft',kind:'request',documentId:'document',targetLayerId:null,expectedDocumentRevision:'1',composing:false,text:'current'});old.drafts.get('draft').savedGeneration='1';old.pendingRequests=()=>assert.fail('must not allocate a pending request list');
 Object.assign(client,{owner:'client',draftOwner:old,ui:old.checkpoint,lifecycle:1,documentLifetime:1});client.patch({ready:true,document:{id:'document'}});const patch=client.patch.bind(client);client.patch=value=>{notices.push(value);patch(value);};
 return {client,old,notices,transport(value){transport=value;},async close(){client.ui=undefined;const owners=new Set([old,client.draftOwner,...client.retiredDraftOwners]);await Promise.all([...owners].map(owner=>owner?.dispose()));await client.drainDraftOwners();await client.controlReads.release();await client.viewReads.release();client.viewModels.clearReplaced({pending:[]});client.viewModels.releaseControlView();}};
}
test('real client publishes the exact saved replacement then calls onAdopt synchronously',async()=>{const baseline=totals(),f=fixture();let adopted;try{await f.client.refreshQueuedReplacement('replacement',f.old,'session',owner=>{assert.equal(f.client.draftOwner,owner);assert.equal(f.client.ui,owner.checkpoint);assert.equal(f.old.drafts.size,0);adopted=owner;});assert(adopted instanceof DraftPersistence);assert.equal(f.client.queuedReplacementActive,false);assert.equal(f.notices.length,1);}finally{await f.close();}assert.deepEqual(totals(),baseline);});
test('dirty then autosaved input cannot pass a fence captured before restore',async()=>{const baseline=totals(),f=fixture(),gate=deferred();let work;try{f.transport(async()=>{await gate.promise;return response(checkpoint());});work=f.client.refreshQueuedReplacement('replacement',f.old,'session',()=>assert.fail('must not adopt'));void work.catch(()=>{});await flush();f.old.change({...f.old.drafts.get('draft'),text:'new input'});f.old.drafts.get('draft').savedGeneration=f.old.drafts.get('draft').generation;assert.equal(queuedDraftsClean(f.old),true);gate.resolve();await assert.rejects(work,/Current input changed/);assert.equal(f.client.draftOwner,f.old);assert.equal(f.old.drafts.get('draft').text,'new input');}finally{gate.resolve();await work?.catch(()=>{});await f.close();}assert.deepEqual(totals(),baseline);});
for(const change of ['session','checkpoint','canAdopt'])test(change+' change prevents late replacement publication',async()=>{const baseline=totals(),f=fixture(),gate=deferred();let work,allowed=true;try{f.transport(async()=>{await gate.promise;return response(checkpoint());});work=f.client.refreshQueuedReplacement('replacement',f.old,'session',()=>assert.fail('must not adopt'),()=>allowed);void work.catch(()=>{});await flush();if(change==='session')f.client.session={...f.client.session};else if(change==='checkpoint')f.old.checkpoint={...f.old.checkpoint};else allowed=false;gate.resolve();await assert.rejects(work,/Current input changed/);assert.equal(f.client.draftOwner,f.old);}finally{gate.resolve();await work?.catch(()=>{});await f.close();}assert.deepEqual(totals(),baseline);});
test('only one replacement read is admitted and a failed restore releases the operation for retry',async()=>{const baseline=totals(),f=fixture(),gate=deferred();let work;try{f.transport(async()=>{await gate.promise;return response({error:{code:'checkpoint unavailable'}},503);});work=f.client.refreshQueuedReplacement('replacement',f.old,'session');void work.catch(()=>{});await flush();await assert.rejects(f.client.refreshQueuedReplacement('replacement',f.old,'session'),/already opening/);gate.resolve();await assert.rejects(work,/checkpoint unavailable/);assert.equal(f.client.draftOwner,f.old);assert.equal(f.client.queuedReplacementActive,false);f.transport(async()=>response(checkpoint()));await f.client.refreshQueuedReplacement('replacement',f.old,'session');assert.notEqual(f.client.draftOwner,f.old);}finally{gate.resolve();await work?.catch(()=>{});await f.close();}assert.deepEqual(totals(),baseline);});
test('restored pending journal delivery prevents adoption and its actual owner is disposed',async()=>{const baseline=totals(),f=fixture();try{f.client.journal={async scan(_prefix,visit){visit({request:{requestId:'pending',sessionId:'session',body:{type:'ClearDraft',draftId:'other'}},draftId:'other',generation:'1'});}};await assert.rejects(f.client.refreshQueuedReplacement('replacement',f.old,'session'),/requires recovery/);assert.equal(f.client.draftOwner,f.old);assert.equal(f.old.drafts.size,1);}finally{await f.close();}assert.deepEqual(totals(),baseline);});
test('callback failure after publication retains the adopted owner and releases only temporary fences',async()=>{const baseline=totals(),f=fixture();try{await assert.rejects(f.client.refreshQueuedReplacement('replacement',f.old,'session',()=>{throw Error('caller refused');}),/caller refused/);assert.notEqual(f.client.draftOwner,f.old);assert.equal(f.client.draftOwner.checkpoint.drafts[0].id,'replacement');assert.equal(f.client.queuedReplacementActive,false);}finally{await f.close();}assert.deepEqual(totals(),baseline);});

for(const callbackFails of [false,true])test('queued publication '+(callbackFails?'failure':'success')+' settles while the real old Entry action remains registered',{timeout:5000},async t=>{
 const baseline=totals(),f=fixture(),entry=registerRequestEntry(cloneOwnedModel('fixture-request-entry',{id:'draft',text:'current'}),()=>f.old.registerDraft('draft','document')),releaseAction=entry.pin();let work,drain;
 // Failure/timeout teardown must first release the same actual UI action pin.
 t.after(async()=>{releaseAction();entry.release();await work?.catch(()=>{});await drain?.catch(()=>{});await f.close();});
 try{
  work=f.client.refreshQueuedReplacement('replacement',f.old,'session',()=>{entry.release();if(callbackFails)throw Error('publication callback failed');});void work.catch(()=>{});
  if(callbackFails)await assert.rejects(work,/publication callback failed/);else await work;
  assert.equal(f.client.queuedReplacementActive,false);assert.notEqual(f.client.draftOwner,f.old);assert.equal(f.old.metadataOwnership.editableBorrowers,1,'No registration is released ahead of its active action');assert.equal(f.client.retiredDraftOwners.has(f.old),true);assert.equal(f.client.draftOwnerDrains.has(f.old),true);
  assert.equal(f.notices.filter(value=>value.drafts?.startsWith('Replacement request draft saved')).length,1,'A real state notification occurs even if the synchronous adoption callback failed');
  let finished=false;drain=f.client.documentResources.release().then(()=>{finished=true;});await flush();assert.equal(finished,false);assert.equal(f.client.documentResources.snapshot.releases,0);assert.equal(f.old.metadataOwnership.editableBorrowers,1);
  releaseAction();await drain;assert.equal(finished,true);assert.equal(f.old.metadataOwnership.editableBorrowers,0);assert.equal(f.client.retiredDraftOwners.size,0);assert.equal(f.client.draftOwnerDrains.size,0);
 }finally{releaseAction();entry.release();await work?.catch(()=>{});await drain?.catch(()=>{});await f.close();}assert.deepEqual(totals(),baseline);
});
test('later retired-owner failure stays visible and blocks the real Close barrier until retry succeeds',async()=>{
 const baseline=totals(),f=fixture(),dispose=f.old.dispose.bind(f.old);let available=false;
 f.old.dispose=async()=>{await dispose();if(!available)throw Error('OLD_DRAFT_DRAIN_FAILED');};
 try{await f.client.refreshQueuedReplacement('replacement',f.old,'session');await flush();assert.equal(f.client.retiredDraftOwners.has(f.old),true);assert.match(f.client.view.error,/OLD_DRAFT_DRAIN_FAILED/);await assert.rejects(f.client.documentResources.release(),AggregateError);assert.equal(f.client.documentResources.snapshot.releases,0);available=true;await f.client.documentResources.release();assert.equal(f.client.retiredDraftOwners.size,0);assert.equal(f.client.documentResources.snapshot.releases,1);}finally{available=true;await f.close();}assert.deepEqual(totals(),baseline);
});

for(const change of ['none','disconnect','draft-owner','authority'])test('connect final native journal scan fences '+change+' before ready publication',async()=>{
 const baseline=totals(),f=fixture(),entered=deferred(),gate=deferred();let streams=0,work;
 f.old.pendingRequests=DraftPersistence.prototype.pendingRequests.bind(f.old);
 Object.assign(f.client,{journal:{async scan(prefix){assert.equal(prefix,'command:');entered.resolve();await gate.promise;},close(){}},sync:async()=>{},listUI:async()=>{},listStages:async()=>{},discoverPending:async()=>{},startStream(){streams++;}});
 try{
  work=f.client.connect();void work.catch(()=>{});await entered.promise;
  if(change==='disconnect')f.client.disconnect();
  if(change==='draft-owner'){const next=new DraftPersistence('session',f.client.session.transport,f.client.session.csrf);next.checkpoint=checkpoint();f.client.draftOwner=next;f.client.ui=next.checkpoint;}
  if(change==='authority')f.client.session.identity=()=> 'replacement-client';
  gate.resolve();await work;
  assert.equal(f.client.view.ready,change==='none');assert.equal(streams,change==='none'?1:0);assert.equal(f.notices.filter(value=>value.ready===true).length,change==='none'?1:0);
 }finally{gate.resolve();await work?.catch(()=>{});await f.close();}assert.deepEqual(totals(),baseline);
});
