import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {join} from 'node:path';
import {setup,terminal,workspace,upload,copy,preview} from '../portable/helpers.mjs';
import {unpack,pack,addEntity,addObject,encoded,records,putRecords} from '../portable/archive-fixture.mjs';
import {newDraft,resolve,routes,hash} from '../../dist/local/src/request/core.js';
import {portableRequestRecord} from '../../dist/local/server/portable/candidates.js';

const weights=()=>{const header=Buffer.from('{"down":{"dtype":"F32","shape":[1],"data_offsets":[0,4]}}'),prefix=Buffer.alloc(8);prefix.writeBigUInt64LE(BigInt(header.length));return Buffer.concat([prefix,header,Buffer.from([0,0,128,63])]);};
async function original(f,bytes,purpose='caption'){const s=await upload(f,bytes,purpose,purpose==='adapter'?'application/octet-stream':'text/plain');return (await workspace(f,{type:'FinalizeStaging',stagingId:s.stagingId,expectedSha256:s.sha256})).event.payload.asset;}
async function register(f,weights,config,prior=null,name='Retained model',provenance=null){return (await workspace(f,{type:'RegisterAdapterVersion',adapterId:prior?.adapter.adapterId??null,previousVersionId:prior?.id??null,weightsAssetId:weights.id,configAssetId:config?.id??null,provenanceAssetId:provenance?.id??null,name,declaredFamily:'ideogram-v4',declaredFormat:'fal',provenanceText:'Test fixture; structure only, no runtime claim.'})).event.payload.asset;}
async function save(f,draft,generation='1'){const asset=await original(f,Buffer.from(JSON.stringify(draft))),sessionId='portable_adapters',ui=(await f.read('/api/v1/ui/'+sessionId)).json;const r=await f.post('/api/v1/ui/'+sessionId,{protocolVersion:1,requestId:randomUUID(),sessionId,expectedUISeq:ui.uiSeq,body:{type:'SaveDraft',draft:{id:'adapter_request',generation,kind:'request',documentId:'document_1',targetLayerId:null,expectedDocumentRevision:'1',assetId:asset.id,composing:false}}});assert.equal(r.json.status,'accepted',r.text);return asset;}
async function fixture(t){const f=await setup(t);await terminal(f,f.command({}, {width:1,height:1}));const w=await original(f,weights(),'adapter'),config=await original(f,Buffer.from('{"rank":1}')),provenance=await original(f,Buffer.from('Exact fixture provenance')),a=await register(f,w,config,null,'Retained model',provenance),b=await register(f,w,config,a,'Retained model',provenance),other=await register(f,await original(f,Buffer.from('UNRELATED_ADAPTER_PRIVATE_WEIGHTS'),'adapter'),null,null,'Unrelated');const prompt=await original(f,Buffer.from('Retain exact adapter order and scales')),draft=newDraft(prompt.blob);draft.operation='generate-adapters';draft.adapters=[{version:b.id,hash:b.blob.hash,scale:'0.2500',runtimeAcknowledged:true},{version:a.id,hash:a.blob.hash,scale:'1.50',runtimeAcknowledged:true}];const draftAsset=await save(f,draft);return {f,w,config,provenance,a,b,other,prompt,draft,draftAsset};}
const assetsFrom=entries=>records(entries).values.filter(r=>r.kind==='entity'&&r.entityType==='asset').map(r=>JSON.parse(entries.get('objects/'+r.payloadRef.hash.slice(7))));
function changeAdapter(entries,change){const {values}=records(entries),record=values.find(r=>r.kind==='entity'&&r.entityType==='asset'&&JSON.parse(entries.get('objects/'+r.payloadRef.hash.slice(7))).qualification==='adapter-version'),v=JSON.parse(entries.get('objects/'+record.payloadRef.hash.slice(7)));change(v);const ref=addObject(entries,encoded(v)),fresh=records(entries);fresh.values.find(r=>r.kind==='entity'&&r.entityType==='asset'&&r.logicalId===v.id).payloadRef=ref;putRecords(entries,fresh.path,fresh.values);}

test('document copy closes exact adapter versions and dependencies; import maps versions without raster decoding or provider execution',async t=>{
 const x=await fixture(t),saved=await copy(x.f),entries=await unpack(x.f.root,saved.bytes),assets=assetsFrom(entries);assert.equal(JSON.parse(entries.get('manifest.json')).formatVersion,9);assert.deepEqual(assets.filter(a=>a.adapter).map(a=>a.id).sort(),[x.a.id,x.b.id].sort());assert(!assets.some(a=>a.id===x.other.id));assert.equal(saved.bytes.includes(Buffer.from('UNRELATED_ADAPTER_PRIVATE_WEIGHTS')),false);assert.deepEqual(entries.get('objects/'+x.w.blob.hash.slice(7)),weights());assert(entries.has('objects/'+x.config.blob.hash.slice(7)));
 const eligible={adapters:new Map(x.draft.adapters.map(a=>[a.version,{hash:a.hash,available:true,profile:'v4-safe-1'}]))},specification=resolve(x.draft,'Retain exact adapter order and scales',eligible),request={endpoint:routes[specification.kind].endpoint,prompt:x.prompt.blob,seed:null,specification,assetBindings:Object.fromEntries(x.draft.adapters.map(a=>[a.version,a.version]))};portableRequestRecord(request);addEntity(entries,'job-result','retained_attempt',{id:'retained_attempt',jobId:'retained_job',documentId:'document_1',requestedCount:1,actualCount:null,phase:'queued',provenance:null,inert:true,request});const manifest=JSON.parse(entries.get('manifest.json'));manifest.formatVersion=9;manifest.documentSchema=9;entries.set('manifest.json',encoded(manifest));
 const imported=await preview(x.f,await pack(x.f.root,entries));assert.equal(imported.review.editable,true);await workspace(x.f,{type:'ImportBundle',reviewId:imported.review.reviewId,reviewHash:imported.review.reviewHash});const session=imported.review.uiSessionIds[0],ui=(await x.f.read('/api/v1/ui/'+session)).json,draft=ui.drafts[0],restored=(await x.f.read('/api/v1/ui/'+session+'/request?draftId='+draft.id+'&generation='+draft.generation)).json.value;
 assert.deepEqual(restored.adapters.map(a=>a.scale),['0.2500','1.50']);assert(restored.adapters.every(a=>a.version.startsWith('p_')));assert.notEqual(restored.adapters[0].version,restored.adapters[1].version);for(const a of restored.adapters){const asset=(await x.f.read('/api/v1/assets/'+a.version)).json.projection.value;assert.equal(asset.adapter.validation.locallyEligible,false);assert.equal(asset.adapter.validation.runtimeVerified,false);assert.equal(asset.adapter.weights.hash,x.w.blob.hash);assert(asset.adapter.adapterId.startsWith('p_'));assert(asset.adapter.sources.weightsAssetId.startsWith('p_'));assert.equal(a.hash,x.w.blob.hash);const withheld=await x.f.read('/api/v1/assets/'+a.version+'/content');assert.equal(withheld.status,403);assert.equal(withheld.json.error.code,'CONTENT_WITHHELD');}
 const db=new DatabaseSync(join(x.f.root,'metadata.sqlite'),{readOnly:true});try{const retained=JSON.parse(db.prepare("SELECT json FROM portable_rows WHERE namespace=? AND kind='job-result'").get(imported.review.namespaceId).json);assert.deepEqual(retained.request.specification,specification);assert.deepEqual(Object.values(retained.request.assetBindings),restored.adapters.map(a=>a.version));assert.equal(db.prepare('SELECT count(*) n FROM queue_jobs').get().n,0);}finally{db.close();}
 const recopy=await copy(x.f,imported.review.documentId),fresh=await setup(t),review=await preview(fresh,recopy.bytes);assert.equal(review.review.editable,true);const roundtrip=await unpack(x.f.root,recopy.bytes);const originalArchive=roundtrip.get('objects/'+imported.review.source.hash.slice(7));assert(originalArchive,'declared original archive is retained');assert.equal('sha256:'+createHash('sha256').update(originalArchive).digest('hex'),imported.review.source.hash);const originalEntries=await unpack(x.f.root,originalArchive);assert.deepEqual(originalEntries.get('objects/'+x.draftAsset.blob.hash.slice(7)),Buffer.from(JSON.stringify(x.draft)));assert.deepEqual(roundtrip.get('objects/'+x.a.adapter.validation.report.hash.slice(7)),entries.get('objects/'+x.a.adapter.validation.report.hash.slice(7)));
});

for(const corruption of ['eligibility','structure'])test('adapter import rejects forged '+corruption+' even when archive object hashes are valid',async t=>{const x=await fixture(t),entries=await unpack(x.f.root,(await copy(x.f)).bytes);changeAdapter(entries,a=>{if(corruption==='eligibility'){a.adapter.validation.profileId='forged';a.adapter.validation.locallyEligible=true;}else a.adapter.validation.structure.tensorCount++;});const bytes=await pack(x.f.root,entries),stage=await upload(x.f,bytes),r=await terminal(x.f,x.f.command({documentId:null,expectedDocumentRevision:null,body:{type:'PreviewBundleImport',stagingId:stage.stagingId,expectedSha256:stage.sha256}}));assert.equal(r.json.receipt.status,'rejected',JSON.stringify(r.json));});

test('inert request provenance refuses undeclared transport authority and incomplete adapter bindings',()=>{const prompt={hash:hash('exact'),byteLength:'5',mediaType:'text/plain'},d=newDraft(prompt);d.operation='generate-adapters';d.adapters=[{version:'version_1',hash:'sha256:'+'b'.repeat(64),scale:'0',runtimeAcknowledged:true}];const specification=resolve(d,'exact', {adapters:new Map([['version_1',{hash:d.adapters[0].hash,available:true,profile:'v4-safe-1'}]])}),request={endpoint:routes[specification.kind].endpoint,prompt,seed:null,specification,assetBindings:{version_1:'mapped_version'}};assert.doesNotThrow(()=>portableRequestRecord(request));assert.throws(()=>portableRequestRecord({...request,assetBindings:{}}));assert.throws(()=>portableRequestRecord({...request,specification:{...specification,Authorization:'secret'}}));});

test('referenced incompatible adapter originals remain recoverable through a copy without acquiring eligibility',async t=>{const x=await fixture(t),draft=structuredClone(x.draft);draft.adapters=[{version:x.other.id,hash:x.other.blob.hash,scale:'1'}];await save(x.f,draft,'2');const saved=await copy(x.f),fresh=await setup(t),r=await preview(fresh,saved.bytes);assert.equal(r.review.editable,true);await workspace(fresh,{type:'ImportBundle',reviewId:r.review.reviewId,reviewHash:r.review.reviewHash});const ui=(await fresh.read('/api/v1/ui/'+r.review.uiSessionIds[0])).json,d=ui.drafts[0],request=(await fresh.read('/api/v1/ui/'+ui.sessionId+'/request?draftId='+d.id+'&generation='+d.generation)).json.value,a=(await fresh.read('/api/v1/assets/'+request.adapters[0].version)).json.projection.value;assert.equal(a.adapter.qualification,'incompatible');assert.equal(a.adapter.validation.locallyEligible,false);assert.equal((await fresh.read('/api/v1/assets/'+a.id+'/content')).status,403);const retained=await unpack(fresh.root,(await copy(fresh,r.review.documentId)).bytes);assert.deepEqual(retained.get('objects/'+a.blob.hash.slice(7)),Buffer.from('UNRELATED_ADAPTER_PRIVATE_WEIGHTS'));});

test('format9 is conditional; future format remains inspection only without creating a namespace',async t=>{const f=await setup(t);await terminal(f,f.command({}, {width:1,height:1}));const base=await copy(f),ordinary=await unpack(f.root,base.bytes);assert.equal(JSON.parse(ordinary.get('manifest.json')).formatVersion,7);const x=await fixture(t),entries=await unpack(x.f.root,(await copy(x.f)).bytes),manifest=JSON.parse(entries.get('manifest.json'));assert.equal(manifest.formatVersion,9);manifest.formatVersion=10;manifest.documentSchema=10;entries.set('manifest.json',encoded(manifest));const r=await preview(x.f,await pack(x.f.root,entries));assert.equal(r.review.editable,false);assert.equal(r.review.reason,'UNSUPPORTED_FORMAT_VERSION');const response=await terminal(x.f,x.f.command({documentId:null,expectedDocumentRevision:null,body:{type:'ImportBundle',reviewId:r.review.reviewId,reviewHash:r.review.reviewHash}}));assert.equal(response.json.receipt.status,'rejected');});

for(const key of ['config','provenance'])test('portable adapter '+key+' source kind must match registration rules',async t=>{const x=await fixture(t),entries=await unpack(x.f.root,(await copy(x.f)).bytes),assetId=x[key].id,{values}=records(entries),record=values.find(r=>r.kind==='entity'&&r.entityType==='asset'&&r.logicalId===assetId),value=JSON.parse(entries.get('objects/'+record.payloadRef.hash.slice(7)));Object.assign(value,{purpose:'adapter',qualification:'pending-adapter',safety:'unknown',measuredMediaType:'application/octet-stream'});const ref=addObject(entries,encoded(value)),fresh=records(entries);fresh.values.find(r=>r.kind==='entity'&&r.entityType==='asset'&&r.logicalId===assetId).payloadRef=ref;putRecords(entries,fresh.path,fresh.values);const stage=await upload(x.f,await pack(x.f.root,entries)),response=await terminal(x.f,x.f.command({documentId:null,expectedDocumentRevision:null,body:{type:'PreviewBundleImport',stagingId:stage.stagingId,expectedSha256:stage.sha256}}));assert.equal(response.json.receipt.status,'rejected');});
