import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {transformWithOxc} from 'vite';
const data=code=>'data:text/javascript;base64,'+Buffer.from(code).toString('base64');
const lit=data('export const nothing=null;export function html(strings,...values){return {strings,values};}');
const profile=data((await transformWithOxc(await readFile('src/adapters/profile.ts','utf8'),'profile.ts')).code);
const controls=data((await transformWithOxc(await readFile('src/ui/adapters.ts','utf8'),'adapters.ts')).code);
let code=(await transformWithOxc(await readFile('src/ui/adapter-library.ts','utf8'),'adapter-library.ts')).code;
for(const [name,value] of [['lit',lit],['./adapters.js',controls],['../adapters/profile.js',profile]])code=code.replaceAll(JSON.stringify(name),JSON.stringify(value)).replaceAll("'"+name+"'",JSON.stringify(value));
const {AdapterLibraryEditing,attachAdapterVersion,adapterScale,adapterStatus,adapterImportProvenance}=await import(data(code));
const hash='sha256:'+'1'.repeat(64),blob={hash,byteLength:'24',mediaType:'application/octet-stream'};
const entry=(changes={})=>({versionId:'version_1',adapterId:'adapter_1',version:'1',name:'Local study',declaredFamily:'ideogram-v4',declaredFormat:'fal',qualification:'structurally-valid',available:true,weights:blob,config:null,profileId:null,runtimeVerified:false,locallyEligible:false,reason:'PROFILE_UNAVAILABLE',...changes});
const eligible=(changes={})=>entry({profileId:'v4-fal-public-example-1',locallyEligible:true,...changes});
const tick=()=>new Promise(r=>setTimeout(r,5));const flush=async()=>{for(let i=0;i<15;i++)await Promise.resolve();};
function find(t,part){if(!t||typeof t!=='object')return;if(t.strings){const i=t.strings.findIndex(s=>s.includes(part));if(i>=0)return {strings:t.strings.slice(i),values:t.values.slice(i)};}for(const v of Array.isArray(t)?t:t.values??[]){const r=find(v,part);if(r)return r;}}
function event(properties={}){const host={isConnected:true,...properties};return {currentTarget:host,composedPath:()=>[host],defaultPrevented:false};}
function fixture(initial=[]){let selected=initial,rendered,identity='client',controller;const uploads=[],commands=[],reads=[],changes=[],focuses=[];const editor={view:{ready:true,document:{id:'doc',revision:'1'}},sessionId:'session',session:{identity:()=>identity},draftOwner:{drafts:new Map()},async flushDrafts(){},async upload(file,purpose,mediaType){uploads.push({file,purpose,mediaType});return {stagingId:'stage_'+uploads.length,sha256:hash};},async command(command){commands.push(command);return [{type:'AssetRegistered',payload:{asset:{id:'asset_'+commands.length,version:'1',blob,dependencies:[],purpose:'adapter',availability:'available',safety:'unknown',qualification:'pending-adapter'}}}];},async json(path){reads.push(path);return path.startsWith('/api/v1/adapters/')?eligible():{protocolVersion:1,items:[entry()],nextAfter:null};}};const host={querySelector(selector){return {focus(){focuses.push(selector);}};},requestUpdate(){this.updateComplete=Promise.resolve().then(()=>render());},updateComplete:Promise.resolve()};const change=next=>{changes.push(next);selected=next;};function render(){rendered=controller.render(selected,change);return rendered;}controller=new AdapterLibraryEditing(host,editor);render();return {controller,editor,host,uploads,commands,reads,changes,focuses,render,template:()=>rendered,identity(v){identity=v;},selected:()=>selected,async choose(kind,file){const part=find(rendered,'label="'+kind+'"');part.values.find(v=>typeof v==='function')(event({files:[file]}));await flush();},async click(id){const part=find(rendered,'id="'+id+'"');assert(part,'rendered '+id);part.values.find(v=>typeof v==='function')(event());await tick();await flush();}};}

test('attachment requires an available supported profile, deduplicates exact versions and caps at three',()=>{
 assert.throws(()=>attachAdapterVersion([],entry()),/cannot attach/);assert.throws(()=>attachAdapterVersion([],eligible({available:false})),/cannot attach/);
 assert.throws(()=>attachAdapterVersion([],eligible({profileId:'unknown-future-profile'})),/cannot attach/);
 const selected=attachAdapterVersion([],eligible());assert.deepEqual(selected,[{version:'version_1',hash,scale:'1'}]);assert.equal(selected[0].runtimeAcknowledged,undefined);
 assert.throws(()=>attachAdapterVersion(selected,eligible()),/already attached/);assert.throws(()=>attachAdapterVersion(['a','b','c'].map(version=>({version,hash,scale:'1'})),eligible()),/at most three/);
});
test('scale retains zero and rejects empty, nonfinite and out-of-range edits',()=>{for(const value of ['0','0.0','1.25','4'])assert.equal(adapterScale(value),value);for(const value of ['',' ','NaN','Infinity','-0.1','4.01'])assert.throws(()=>adapterScale(value),/0 to 4/);});
test('import provenance retains exact local names and rejects combined overflow without truncation',()=>{const files={weights:new File(['x'],'name.safetensors'),config:null,provenance:null};assert.equal(adapterImportProvenance(files,'Source https://example.test'), 'Local filenames: {"weights":"name.safetensors","config":null,"provenance":null}\nUser provenance: Source https://example.test');assert.throws(()=>adapterImportProvenance(files,'x'.repeat(4096)),/exceeds 4096/);});
test('library status distinguishes local structural evidence, runtime evidence and missing artifacts',()=>{assert.equal(adapterStatus(entry()),'Stored — compatibility unverified');assert.equal(adapterStatus(eligible()),'Not runtime verified');assert.equal(adapterStatus(entry({qualification:'incompatible'})),'Incompatible');assert.equal(adapterStatus(entry({available:false})),'Missing artifact');assert.match(adapterStatus(entry({locallyEligible:true,runtimeVerified:true})),/^Runtime verified/);});
test('rendered import stages original handles then requires explicit hash review before registration',async()=>{
 const f=fixture(),weights=new File(['weights'],'study.safetensors'),config=new File(['{}'],'config.json'),provenance=new File(['origin'],'source.txt');
 await f.choose('Adapter weights',weights);await f.choose('Optional adapter config',config);await f.choose('Optional adapter provenance',provenance);await f.click('prepare-adapter-import');
 assert.deepEqual(f.uploads.map(x=>[x.file,x.purpose,x.mediaType]),[[weights,'adapter','application/octet-stream'],[config,'caption','text/plain'],[provenance,'caption','text/plain']]);
 assert.equal(f.commands.length,3);assert(f.commands.every(c=>c.type==='FinalizeStaging'));assert(find(f.template(),'Register immutable adapter version'));
 await f.click('register-adapter-version');assert.deepEqual(f.commands[3],{type:'RegisterAdapterVersion',adapterId:null,previousVersionId:null,weightsAssetId:'asset_1',configAssetId:'asset_2',provenanceAssetId:'asset_3',name:'study',declaredFamily:'ideogram-v4',declaredFormat:'fal',provenanceText:adapterImportProvenance({weights,config,provenance},'')});
 assert.equal(f.reads.at(-1),'/api/v1/adapters');assert(find(f.template(),'Stored versions'));
});
test('wrong extension refuses transfer while preserving the file selection for replacement',async()=>{const f=fixture();await f.choose('Adapter weights',new File(['pickle'],'renamed.pt'));await f.click('prepare-adapter-import');assert.equal(f.uploads.length,0);assert.equal(f.commands.length,0);assert(find(f.template(),'<en-alert role="alert">').values.includes('Choose a nonempty .safetensors file. The backend checks its actual format.'));});
for(const boundary of ['document','revision','session','identity','owner','disposed'])test('an upload resolving after '+boundary+' cannot register or prepare another owner',async()=>{
 const f=fixture();let release;f.editor.upload=()=>new Promise(r=>release=r);await f.choose('Adapter weights',new File(['weights'],'study.safetensors'));const task=f.click('prepare-adapter-import');await tick();
 if(boundary==='document')f.editor.view.document={id:'other',revision:'1'};if(boundary==='revision')f.editor.view.document.revision='2';if(boundary==='session')f.editor.sessionId='other';if(boundary==='identity')f.identity('other');if(boundary==='owner')f.editor.draftOwner={};if(boundary==='disposed')f.controller.dispose();
 release({stagingId:'old',sha256:hash});await task;await flush();assert.equal(f.commands.length,0);assert.equal(find(f.template(),'Register immutable adapter version'),undefined);
});
test('settled file choice and delayed action honor native cancellation',async()=>{const f=fixture(),choose=find(f.template(),'label="Adapter weights"').values.find(v=>typeof v==='function'),e=event({files:[new File(['weights'],'study.safetensors')]});choose(e);e.defaultPrevented=true;await flush();assert.equal(find(f.template(),'id="prepare-adapter-import"').values[0],true);await f.choose('Adapter weights',new File(['weights'],'study.safetensors'));const action=find(f.template(),'id="prepare-adapter-import"').values.find(v=>typeof v==='function'),veto=event();action(veto);veto.defaultPrevented=true;await tick();assert.equal(f.uploads.length,0);});
test('exact restored versions are fetched for eligibility and unknown profiles stay absent',async()=>{const attached={version:'version_1',hash,scale:'0'};const f=fixture([attached]);const e=await f.controller.eligibility([attached]);assert.equal(e.adapters.get('version_1').hash,hash);assert.equal(e.adapters.get('version_1').runtimeVerified,false);f.editor.json=async()=>entry();assert.equal((await f.controller.eligibility([attached])).adapters.size,0);});
test('unknown named compatibility profiles cannot be relabeled as the supported request profile',async()=>{const f=fixture([{version:'version_1',hash,scale:'1',runtimeAcknowledged:true}]);f.editor.json=async()=>eligible({profileId:'future'});assert.equal((await f.controller.eligibility()).adapters.size,0);});
test('async eligibility refuses a changed owner before publishing any usable entry',async()=>{const f=fixture([{version:'version_1',hash,scale:'1'}]);let release;f.editor.json=()=>new Promise(r=>release=r);const pending=f.controller.eligibility();f.identity('other');release(eligible());await assert.rejects(pending,/selection changed/);});
test('scale and explicit acknowledgement update exact drafts without mutating the old version array',async()=>{
 const original=[{version:'version_1',hash,scale:'1'}],f=fixture(original);let part=find(f.template(),'<en-number-field label=');part.values.find(v=>typeof v==='function')(event({value:'0'}));await flush();assert.equal(f.selected()[0].scale,'0');assert.equal(original[0].scale,'1');
 part=find(f.template(),'<en-switch label=');part.values.find(v=>typeof v==='function')(event({checked:true}));await flush();assert.equal(f.selected()[0].runtimeAcknowledged,true);assert.equal(f.selected()[0].scale,'0');assert.equal(original[0].runtimeAcknowledged,undefined);
});
test('invalid scale restores the public control value to the retained exact draft',async()=>{const f=fixture([{version:'version_1',hash,scale:'1'}]),part=find(f.template(),'<en-number-field label='),input=event({value:''});part.values.find(v=>typeof v==='function')(input);await flush();assert.equal(input.currentTarget.value,'1');assert.equal(f.selected()[0].scale,'1');assert.equal(f.changes.length,0);});
test('new owner clears composition lock and binds empty public file selections',async()=>{const f=fixture();await f.choose('Adapter weights',new File(['x'],'first.safetensors'));const root=find(f.template(),'aria-label="Local adapter library"');root.values.find(v=>typeof v==='function')();f.identity('second');f.render();const cleared=find(f.template(),'label="Adapter weights"');assert.deepEqual(cleared.values[0],[]);await f.choose('Adapter weights',new File(['x'],'second.safetensors'));await f.click('prepare-adapter-import');assert.equal(f.uploads.length,1);assert.equal(f.uploads[0].file.name,'second.safetensors');});
function dynamicId(t,id){if(!t||typeof t!=='object')return;if(t.strings){const i=t.values.indexOf(id);if(i>=0&&t.strings[i].endsWith('id='))return t.values.slice(i).find(v=>typeof v==='function');}for(const v of Array.isArray(t)?t:t.values??[]){const result=dynamicId(v,id);if(result)return result;}}
async function deletionFixture(blocked=false){const f=fixture(),plan={kind:'adapter-deletion-plan-1',id:'plan',versionId:'version_1',adapterId:'adapter_1',version:'1',weights:blob,owner:'client',dependencies:blocked?[{kind:'draft',id:'draft_1',detail:'Request still references this exact version'}]:[],dependencyCount:blocked?1:0,dependenciesTruncated:false,dependencyHash:hash,canDelete:!blocked,actualFreedBytes:'0',bytesRetained:true,token:hash};let deleted=false;f.editor.command=async c=>{f.commands.push(c);if(c.type==='DeleteAdapterVersion')deleted=true;return [{type:'AssetRegistered',payload:{asset:{id:'plan',adapterDeletion:{kind:c.type==='PreviewAdapterDeletion'?'preview':'deleted',versionId:'version_1',planId:'plan',token:hash}}}}];};f.editor.json=async path=>{f.reads.push(path);return path.includes('/deletion-reviews/')?plan:{protocolVersion:1,items:deleted?[]:[entry()],nextAfter:null};};await f.click('search-adapter-library');const callback=dynamicId(f.template(),'preview-adapter-deletion-version_1');assert(callback);callback(event());await tick();await flush();return {f,plan};}
test('library deletion previews exact dependencies, then confirms the same immutable token without freed-byte claims',async()=>{const {f}=await deletionFixture();assert.deepEqual(f.commands,[{type:'PreviewAdapterDeletion',versionId:'version_1'}]);assert(find(f.template(),'aria-label="Adapter deletion review"'));await f.click('confirm-adapter-deletion');assert.deepEqual(f.commands.at(-1),{type:'DeleteAdapterVersion',versionId:'version_1',planId:'plan',token:hash});assert(find(f.template(),'<p role="status">').values.some(v=>typeof v==='string'&&v.includes('no disk space was freed')));});
test('blocked deletion explains retained references and refuses confirm even if callback is invoked',async()=>{const {f}=await deletionFixture(true);assert(find(f.template(),'Deletion is blocked until'));await f.click('confirm-adapter-deletion');assert.equal(f.commands.length,1);});
test('dirty or composing drafts cannot be bypassed to prepare deletion',async()=>{const f=fixture();await f.click('search-adapter-library');f.editor.draftOwner.drafts.set('draft',{composing:true,pending:false,savedGeneration:'0',generation:'1'});dynamicId(f.template(),'preview-adapter-deletion-version_1')(event());await tick();await flush();assert.equal(f.commands.length,0);assert(find(f.template(),'<en-alert role="alert">').values.some(v=>typeof v==='string'&&v.includes('finish composing')));});
test('cursor navigation returns through earlier pages, preserves filters and files, and focuses a stable result heading',async()=>{
 const attached=[{version:'selected',hash,scale:'0'}],f=fixture(attached),weights=new File(['x'],'unsaved.safetensors');
 await f.choose('Adapter weights',weights);
 dynamicId(f.template(),'adapter-search')(event({value:'Local study'}));await flush();
 f.editor.json=async path=>{f.reads.push(path);const cursor=new URL(path,'http://127.0.0.1').searchParams.get('after');return {protocolVersion:1,items:[entry({name:'Page '+(cursor??'first')})],nextAfter:cursor===null?'cursor1':cursor==='cursor1'?'cursor2':null};};
 const page=()=>find(f.template(),'Adapter library page ').values[0];
 await f.click('search-adapter-library');assert.equal(page(),1);assert.equal(find(f.template(),'id="first-adapter-page"').values[0],true);assert.equal(find(f.template(),'id="previous-adapter-page"').values[0],true);
 await f.click('next-adapter-page');assert.equal(page(),2);await f.click('next-adapter-page');assert.equal(page(),3);assert.equal(find(f.template(),'id="next-adapter-page"').values[0],true);
 await f.click('previous-adapter-page');assert.equal(page(),2);assert.match(f.reads.at(-1),/after=cursor1/);await f.click('next-adapter-page');assert.equal(page(),3);
 await f.click('first-adapter-page');assert.equal(page(),1);assert.equal(new URL(f.reads.at(-1),'http://127.0.0.1').searchParams.has('after'),false);
 assert(f.reads.every(path=>new URL(path,'http://127.0.0.1').searchParams.get('search')==='Local study'));assert.deepEqual(f.focuses,Array(6).fill('#adapter-library-results'));
 assert.deepEqual(find(f.template(),'label="Adapter weights"').values[0],[weights]);assert.equal(f.selected(),attached);assert.equal(f.changes.length,0);
 dynamicId(f.template(),'adapter-search')(event({value:'Other'}));await flush();assert.equal(find(f.template(),'id="next-adapter-page"'),undefined);await f.click('search-adapter-library');assert.equal(page(),1);assert.equal(f.reads.at(-1),'/api/v1/adapters?search=Other');
});
test('failed page reads retain the current cursor and late owner responses cannot focus or expose their results',async()=>{
 const f=fixture();f.editor.json=async()=>({protocolVersion:1,items:[entry()],nextAfter:'cursor1'});await f.click('search-adapter-library');
 f.editor.json=async()=>{throw Error('Temporary library read failure');};await f.click('next-adapter-page');assert.equal(find(f.template(),'Adapter library page ').values[0],1);assert.equal(f.focuses.length,1);
 let release;f.editor.json=()=>new Promise(resolve=>release=resolve);const next=f.click('next-adapter-page');await tick();f.identity('new-owner');f.render();release({protocolVersion:1,items:[entry({name:'Stale owner page'})],nextAfter:null});await next;await flush();
 assert.equal(find(f.template(),'Adapter library page '),undefined);assert.equal(f.focuses.length,1);assert.equal(find(f.template(),'id="next-adapter-page"'),undefined);
});
test('document release drops resident files and reviews, fences old controls, and permits a fresh import',async()=>{
 const f=fixture(),weights=new File(['x'],'released.safetensors');await f.choose('Adapter weights',weights);await f.choose('Optional adapter config',new File(['{}'],'released.json'));
 await f.click('prepare-adapter-import');await f.click('search-adapter-library');assert(find(f.template(),'Register immutable adapter version'));assert(find(f.template(),'Adapter library page '));
 const oldRegister=find(f.template(),'id="register-adapter-version"').values.find(v=>typeof v==='function'),oldFile=find(f.template(),'label="Adapter weights"').values.find(v=>typeof v==='function');const before=f.commands.length;
 f.controller.releaseDocument();assert.deepEqual(f.controller.files,{weights:null,config:null,provenance:null});assert.deepEqual(f.controller.shownFiles,{weights:[],config:[],provenance:[]});assert.equal(f.controller.prepared,null);assert.equal(f.controller.deletion,null);assert.deepEqual(f.controller.items,[]);assert.deepEqual(f.controller.selected,[]);assert.equal(f.controller.change,null);assert.equal(f.controller.owner,null);
 oldRegister(event());oldFile(event({files:[weights]}));await tick();await flush();assert.equal(f.commands.length,before);
 f.render();assert.deepEqual(find(f.template(),'label="Adapter weights"').values[0],[]);assert.equal(find(f.template(),'Register immutable adapter version'),undefined);assert.equal(find(f.template(),'Adapter library page '),undefined);
 await f.choose('Adapter weights',new File(['next'],'fresh.safetensors'));await f.click('prepare-adapter-import');assert.equal(f.uploads.at(-1).file.name,'fresh.safetensors');assert(find(f.template(),'Register immutable adapter version'));
});
test('permanent disposal cannot reacquire files, selections or callbacks through a stale render',async()=>{
 const f=fixture([{version:'version_1',hash,scale:'1'}]);await f.choose('Adapter weights',new File(['x'],'closed.safetensors'));f.controller.dispose();
 assert.equal(f.controller.render([{version:'foreign',hash,scale:'1'}],()=>assert.fail('disposed callback')),null);assert.deepEqual(f.controller.files,{weights:null,config:null,provenance:null});assert.deepEqual(f.controller.shownFiles,{weights:[],config:[],provenance:[]});assert.deepEqual(f.controller.selected,[]);assert.equal(f.controller.change,null);assert.equal(f.controller.owner,null);
});
test('document release invalidates a pending library page before it can refill cleared state',async()=>{
 const f=fixture();let release;f.editor.json=()=>new Promise(resolve=>release=resolve);const pending=f.click('search-adapter-library');await tick();f.controller.releaseDocument();release({protocolVersion:1,items:[entry()],nextAfter:'old-cursor'});await pending;await flush();
 assert.deepEqual(f.controller.items,[]);assert.equal(f.controller.next,null);assert.equal(f.controller.loaded,false);assert.equal(f.controller.owner,null);assert.deepEqual(f.focuses,[]);
});
