import {readStagedSource,stagedModuleURL} from '../adapter-upload-module.mjs';
import {adapterUploadURL} from '../owned-preview-module.mjs';
import {ownFixtureCommands} from '../owned-command-fixture.mjs';
import {modelMemoryURL} from '../ui-model-module.mjs';
import {uiModelOwnerURL,ownFixtureJSON} from '../ui-model-module.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {transformWithOxc} from 'vite';
const data=code=>'data:text/javascript;base64,'+Buffer.from(code).toString('base64');
const lit=data('export const nothing=null;export function html(strings,...values){return {strings,values};}');
const profile=data((await transformWithOxc(await readStagedSource('src/adapters/profile.ts'),'profile.ts')).code);
const controls=data((await transformWithOxc(await readStagedSource('src/ui/adapters.ts'),'adapters.ts')).code);
const {adapterRegistration}=await import(await stagedModuleURL('src/protocol/adapters.ts',{'./json.js':await stagedModuleURL('src/protocol/json.ts'),'../adapters/profile.js':profile}));
let code=(await transformWithOxc(await readStagedSource('src/ui/adapter-library.ts'),'adapter-library.ts')).code;
for(const [name,value] of [['../observability/adapter-upload.js',adapterUploadURL],['lit',lit],['./adapters.js',controls],['./model-owner.js',uiModelOwnerURL],['../observability/model-memory.js',modelMemoryURL],['../adapters/profile.js',profile]])code=code.replaceAll(JSON.stringify(name),JSON.stringify(value)).replaceAll("'"+name+"'",JSON.stringify(value));
const {AdapterLibraryEditing,attachAdapterVersion,adapterScale,adapterStatus,adapterImportProvenance}=await import(data(code));
const hash='sha256:'+'1'.repeat(64),blob={hash,byteLength:'24',mediaType:'application/octet-stream'};
const entry=(changes={})=>({versionId:'version_1',adapterId:'adapter_1',version:'1',name:'Local study',declaredFamily:'ideogram-v4',declaredFormat:'fal',qualification:'structurally-valid',available:true,weights:blob,config:null,profileId:null,runtimeVerified:false,locallyEligible:false,reason:'PROFILE_UNAVAILABLE',...changes});
const eligible=(changes={})=>entry({profileId:'v4-fal-public-example-1',locallyEligible:true,...changes});
const tick=()=>new Promise(r=>setTimeout(r,5));const flush=async()=>{for(let i=0;i<15;i++)await Promise.resolve();};
function find(t,part){if(!t||typeof t!=='object')return;if(t.strings){const i=t.strings.findIndex(s=>s.includes(part));if(i>=0)return {strings:t.strings.slice(i),values:t.values.slice(i)};const attribute=/^(id|label)="([^"]+)"$/.exec(part),bound=attribute===null?-1:t.values.findIndex((value,index)=>value===attribute[2]&&t.strings[index].endsWith(' '+attribute[1]+'='));if(bound>=0)return {strings:t.strings.slice(bound+1),values:t.values.slice(bound+1)};}for(const v of Array.isArray(t)?t:t.values??[]){const r=find(v,part);if(r)return r;}}
function event(properties={}){const host={isConnected:true,...properties};return {currentTarget:host,composedPath:()=>[host],defaultPrevented:false};}
function fixture(initial=[],initialIssues=[]){let selected=initial,issues=initialIssues,rendered,identity='client',controller;const uploads=[],commands=[],reads=[],changes=[],focuses=[];const editor={view:{ready:true,document:{id:'doc',revision:'1'}},sessionId:'session',session:{identity:()=>identity},draftOwner:{drafts:new Map()},async flushDrafts(){},async upload(file,purpose,mediaType){uploads.push({file,purpose,mediaType});return {stagingId:'stage_'+uploads.length,sha256:hash};},async command(command){commands.push(command);return [{type:'AssetRegistered',payload:{asset:{id:'asset_'+commands.length,version:'1',blob,dependencies:[],purpose:'adapter',availability:'available',safety:'unknown',qualification:'pending-adapter'}}}];},async json(path){reads.push(path);return path.startsWith('/api/v1/adapters/')?eligible():{protocolVersion:1,items:[entry()],nextAfter:null};}};const host={querySelector(selector){return {isConnected:true,focus(){focuses.push(selector);}};},requestUpdate(){this.updateComplete=Promise.resolve().then(()=>render());},updateComplete:Promise.resolve()};const change=next=>{changes.push(next);selected=next;issues=[];};function render(){rendered=controller.render(selected,change,issues);return rendered;}ownFixtureJSON(editor);controller=new AdapterLibraryEditing(host,ownFixtureCommands(editor));render();return {controller,editor,host,uploads,commands,reads,changes,focuses,render,template:()=>rendered,identity(v){identity=v;},selected:()=>selected,issues:()=>issues,setIssues(next){issues=next;render();},async choose(kind,file){const part=find(rendered,'label="'+kind+'"');part.values.find(v=>typeof v==='function')(event({files:[file]}));await flush();},async click(id){const part=find(rendered,'id="'+id+'"');assert(part,'rendered '+id);part.values.find(v=>typeof v==='function')(event());await tick();await flush();}};}

test('attachment requires an available supported profile, deduplicates exact versions and caps at three',()=>{
 assert.throws(()=>attachAdapterVersion([],entry()),/cannot attach/);assert.throws(()=>attachAdapterVersion([],eligible({available:false})),/cannot attach/);
 assert.throws(()=>attachAdapterVersion([],eligible({profileId:'unknown-future-profile'})),/cannot attach/);
 const selected=attachAdapterVersion([],eligible());assert.deepEqual(selected,[{version:'version_1',hash,scale:'1'}]);assert.equal(selected[0].runtimeAcknowledged,undefined);
 assert.throws(()=>attachAdapterVersion(selected,eligible()),/already attached/);assert.throws(()=>attachAdapterVersion(['a','b','c'].map(version=>({version,hash,scale:'1'})),eligible()),/at most three/);
});
test('scale retains zero and rejects empty, nonfinite and out-of-range edits',()=>{for(const value of ['0','0.0','1.25','4'])assert.equal(adapterScale(value),value);for(const value of ['',' ','NaN','Infinity','-0.1','4.01'])assert.throws(()=>adapterScale(value),/0 to 4/);});
test('import provenance retains exact local names and rejects combined overflow without truncation',()=>{const files={weights:new File(['x'],'name.safetensors'),config:null,provenance:null};assert.equal(adapterImportProvenance(files,'Source https://example.test'), 'Local filenames: {"weights":"name.safetensors","config":null,"provenance":null}\nUser provenance: Source https://example.test');assert.throws(()=>adapterImportProvenance(files,'x'.repeat(4096)),/exceeds 4096/);});
test('library status distinguishes local structural evidence, runtime evidence and missing artifacts',()=>{assert.equal(adapterStatus(entry()),'Stored — compatibility unverified');assert.equal(adapterStatus(eligible()),'Not runtime verified');assert.equal(adapterStatus(entry({qualification:'incompatible'})),'Incompatible');assert.equal(adapterStatus(entry({available:false})),'Missing artifact');assert.match(adapterStatus(entry({locallyEligible:true,runtimeVerified:true})),/^Runtime verified/);});
test('rendered import stages original handles then requires explicit hash review before registration',async()=>{
 const f=fixture(),weights=new File(['weights'],'study.safetensors'),config=new File(['{}'],'config.json'),provenance=new File(['origin'],'source.txt');
 await f.choose('Adapter weights',weights);await f.choose('Optional adapter config',config);await f.choose('Optional adapter provenance',provenance);await f.click('prepare-adapter-import');
 assert.deepEqual(f.uploads.map(x=>[x.file,x.purpose,x.mediaType]),[[weights,'adapter','application/octet-stream'],[config,'caption','text/plain'],[provenance,'caption','text/plain']]);
 assert.equal(f.commands.length,3);assert(f.commands.every(c=>c.type==='FinalizeStaging'));assert(find(f.template(),'Register immutable adapter version'));
 await f.click('register-adapter-version');assert.deepEqual(f.commands[3],{type:'RegisterAdapterVersion',adapterId:null,previousVersionId:null,weightsAssetId:'asset_1',configAssetId:'asset_2',provenanceAssetId:'asset_3',name:'study',declaredFamily:'ideogram-v4',declaredFormat:'fal',provenanceText:adapterImportProvenance({weights,config,provenance},'')});
 assert.equal(f.reads.at(-1),'/api/v1/adapters');assert(find(f.template(),'Stored versions'));
});
function fieldPart(t,id){if(!t||typeof t!=='object')return;if(t.strings){let i=t.strings.findIndex(s=>s.includes('id="'+id+'"'));if(i<0)i=t.values.findIndex((value,index)=>value===id&&t.strings[index].endsWith('id='));if(i>=0)return {strings:t.strings.slice(i),values:t.values.slice(i)};}for(const v of Array.isArray(t)?t:t.values??[]){const result=fieldPart(v,id);if(result)return result;}}
function fieldProperty(template,id,name){const part=fieldPart(template,id);assert(part,'rendered '+id);const index=part.strings.findIndex(value=>value.endsWith('.'+name+'='));assert(index>=0,'bound '+id+'.'+name);return part.values[index];}
async function editField(f,id,value){const part=fieldPart(f.template(),id);assert(part,'rendered '+id);const input=event({value});part.values.find(v=>typeof v==='function')(input);await flush();return input;}
const validationItems=f=>find(f.template(),'id="adapter-validation-summary"')?.values[0];
test('wrong extension refuses transfer with a linked inline error and preserves the exact file selection',async t=>{const f=fixture(),weights=new File(['pickle'],'renamed.pt');t.after(()=>f.controller.dispose());await f.choose('Adapter weights',weights);await f.click('prepare-adapter-import');assert.equal(f.uploads.length,0);assert.equal(f.commands.length,0);assert.deepEqual(fieldProperty(f.template(),'adapter-weights','files'),[weights]);assert.equal(fieldProperty(f.template(),'adapter-weights','error'),'Choose a nonempty .safetensors file. The backend checks its actual format.');assert.deepEqual(validationItems(f),[{target:'adapter-weights',message:fieldProperty(f.template(),'adapter-weights','error')}]);assert.deepEqual(f.focuses,['#adapter-validation-summary']);assert.equal(find(f.template(),'<en-alert role="alert">'),undefined);const controls=validationFocusControls(f);assert.equal(await f.controller.focusValidation(f.controller.capture(),f.controller.validation,'adapter-weights'),true);assert.deepEqual(controls.calls,[true]);assert.deepEqual(f.focuses,['#adapter-validation-summary','#adapter-weights']);});
test('import review collects current field errors before transfer and preserves raw corrections',async t=>{
 const f=fixture(),weights=new File(['weights'],'study.safetensors');t.after(()=>f.controller.dispose());await f.choose('Adapter weights',weights);
 for(const [id,value]of [['adapter-name','  '],['adapter-family','x'.repeat(121)],['adapter-format',''],['adapter-provenance','p'.repeat(4096)]])await editField(f,id,value);
 await f.click('prepare-adapter-import');assert.deepEqual(validationItems(f).map(item=>item.target),['adapter-name','adapter-family','adapter-format','adapter-provenance']);assert.equal(f.uploads.length,0);assert.equal(f.commands.length,0);assert.deepEqual(f.focuses,['#adapter-validation-summary']);
 assert.equal(fieldProperty(f.template(),'adapter-name','value'),'  ');assert.equal(fieldProperty(f.template(),'adapter-family','value'),'x'.repeat(121));assert.equal(fieldProperty(f.template(),'adapter-format','value'),'');assert.equal(fieldProperty(f.template(),'adapter-provenance','value'),'p'.repeat(4096));assert.deepEqual(fieldProperty(f.template(),'adapter-weights','files'),[weights]);
 const prior=f.controller.validation;await editField(f,'adapter-name','Corrected name');assert.notEqual(f.controller.validation,prior);assert.equal(fieldProperty(f.template(),'adapter-name','error'),'');assert.deepEqual(validationItems(f).map(item=>item.target),['adapter-family','adapter-format','adapter-provenance']);assert.equal(f.focuses.length,1);
 await editField(f,'adapter-family','ideogram-v4');await editField(f,'adapter-format','fal');await editField(f,'adapter-provenance','Retained source text');assert.equal(validationItems(f),undefined);assert.equal(fieldProperty(f.template(),'adapter-provenance','error'),'');assert.equal(f.uploads.length,0);await f.click('prepare-adapter-import');assert.equal(f.uploads.length,1);assert.equal(f.uploads[0].file,weights);assert(find(f.template(),'Register immutable adapter version'));
});
for(const weights of [null,new File([],'empty.safetensors')])test('missing or empty local weights receive the exact field error without transfer '+(weights?.name??'missing'),async t=>{const f=fixture();t.after(()=>f.controller.dispose());if(weights)await f.choose('Adapter weights',weights);await f.click('prepare-adapter-import');assert.equal(validationItems(f)[0].target,'adapter-weights');assert(fieldProperty(f.template(),'adapter-weights','error'));assert.equal(f.uploads.length,0);assert.equal(f.commands.length,0);});
test('search reports each overlong filter without a read and clears only corrected errors',async t=>{
 const f=fixture();t.after(()=>f.controller.dispose());await editField(f,'adapter-search','q'.repeat(121));await editField(f,'adapter-family-filter','f'.repeat(121));await f.click('search-adapter-library');assert.equal(f.reads.length,0);assert.equal(f.commands.length,0);assert.equal(f.uploads.length,0);assert.deepEqual(validationItems(f).map(item=>item.target),['adapter-search','adapter-family-filter']);assert.equal(fieldProperty(f.template(),'adapter-search','value'),'q'.repeat(121));assert.equal(fieldProperty(f.template(),'adapter-family-filter','value'),'f'.repeat(121));assert.deepEqual(f.focuses,['#adapter-validation-summary']);
 await editField(f,'adapter-search','Local study');assert.equal(fieldProperty(f.template(),'adapter-search','error'),'');assert.deepEqual(validationItems(f).map(item=>item.target),['adapter-family-filter']);await editField(f,'adapter-family-filter','ideogram-v4');assert.equal(validationItems(f),undefined);await f.click('search-adapter-library');assert.equal(f.reads.length,1);assert.match(f.reads[0],/search=Local\+study&family=ideogram-v4/);assert.deepEqual(f.focuses,['#adapter-validation-summary','#adapter-library-results']);
});
function validationFocusControls(f,{allowed=true,settled=Promise.resolve()}={}){const original=f.host.querySelector.bind(f.host),calls=[],fields=new Map(),accordion={isConnected:true,open:false,updateComplete:settled,requestOpen(open){calls.push(open);if(allowed)this.open=open;return allowed?'committed':'canceled';}},controls={accordion,current:accordion,calls,fields};f.host.querySelector=selector=>{if(selector==='#request-adapters')return controls.current;if(selector==='#adapter-name'||selector==='#adapter-weights'){if(!fields.has(selector))fields.set(selector,{isConnected:true,focus(){f.focuses.push(selector);}});return fields.get(selector);}return original(selector);};return controls;}
async function invalidNameFixture(t){const f=fixture();t.after(()=>f.controller.dispose());await f.choose('Adapter weights',new File(['weights'],'study.safetensors'));await editField(f,'adapter-name','');await f.click('prepare-adapter-import');f.focuses.length=0;return f;}
test('linked import summary reveals the public accordion and focuses the offending field',async t=>{const f=await invalidNameFixture(t),controls=validationFocusControls(f),part=find(f.template(),'id="adapter-validation-summary"'),e={defaultPrevented:false,preventDefault(){this.defaultPrevented=true;},detail:{data:{target:'adapter-name'}}};part.values.find(v=>typeof v==='function')(e);await flush();assert.equal(e.defaultPrevented,true);assert.deepEqual(controls.calls,[true]);assert.deepEqual(f.focuses,['#adapter-name']);assert.equal(f.uploads.length,0);});
test('summary navigation honors canceled expansion and refuses unknown or already canceled actions',async t=>{const f=await invalidNameFixture(t),controls=validationFocusControls(f,{allowed:false}),validation=f.controller.validation;assert.equal(await f.controller.focusValidation(f.controller.capture(),validation,'adapter-name'),false);assert.deepEqual(controls.calls,[true]);assert.equal(await f.controller.focusValidation(f.controller.capture(),validation,'unowned-field'),false);const handler=find(f.template(),'id="adapter-validation-summary"').values.find(v=>typeof v==='function');handler({defaultPrevented:true,preventDefault(){assert.fail('canceled event');},detail:{data:{target:'adapter-name'}}});await flush();assert.deepEqual(controls.calls,[true]);assert.deepEqual(f.focuses,[]);});
for(const boundary of ['document','revision','session','identity','owner','edited','action','disposed','accordion','field','collapsed'])test('pending import summary navigation refuses '+boundary+' changes',async t=>{
 const f=await invalidNameFixture(t);let finish,releasing;const controls=validationFocusControls(f,{settled:new Promise(resolve=>finish=resolve)}),validation=f.controller.validation,pending=f.controller.focusValidation(f.controller.capture(),validation,'adapter-name');await flush();assert.deepEqual(controls.calls,[true]);
 if(boundary==='document')f.editor.view.document={id:'other',revision:'1'};if(boundary==='revision')f.editor.view.document.revision='2';if(boundary==='session')f.editor.sessionId='other';if(boundary==='identity')f.identity('other');if(boundary==='owner')f.editor.draftOwner={drafts:new Map()};if(boundary==='edited')await editField(f,'adapter-name','Corrected');if(boundary==='action'){f.controller.action(event(),f.controller.capture(),()=>{});await tick();await flush();assert.equal(f.controller.busy,false);assert.equal(f.controller.validation,validation);}if(boundary==='disposed')releasing=f.controller.dispose();if(boundary==='accordion')controls.current={...controls.accordion};if(boundary==='field')f.host.querySelector('#adapter-name').isConnected=false;if(boundary==='collapsed')controls.accordion.open=false;
 finish();assert.equal(await pending,false);await releasing;assert.deepEqual(f.focuses,[]);
});
for(const boundary of ['edited','identity','action','disconnected'])test('attempted import focus waits for the settled view and refuses '+boundary+' changes',async t=>{
 const f=fixture();t.after(()=>f.controller.dispose());await f.choose('Adapter weights',new File(['weights'],'study.safetensors'));await editField(f,'adapter-name','');let finish;const settled=new Promise(resolve=>finish=resolve),requestUpdate=f.host.requestUpdate;f.host.requestUpdate=function(){this.updateComplete=settled;};await f.click('prepare-adapter-import');assert.equal(f.controller.busy,false);assert.deepEqual(f.focuses,[]);
 if(boundary==='edited')f.controller.changeDraft({name:'Corrected'});if(boundary==='action'){const validation=f.controller.validation;f.controller.action(event(),f.controller.capture(),()=>{});await tick();await flush();assert.equal(f.controller.busy,false);assert.equal(f.controller.validation,validation);}if(boundary==='identity')f.identity('other');if(boundary==='disconnected'){const original=f.host.querySelector.bind(f.host);f.host.querySelector=selector=>selector==='#adapter-validation-summary'?{isConnected:false,focus(){assert.fail('detached summary');}}:original(selector);}
 finish();await flush();f.host.requestUpdate=requestUpdate;assert.deepEqual(f.focuses,[]);
});
for(const [id,key,label]of [['adapter-name','name','Adapter name'],['adapter-family','declaredFamily','Declared model family'],['adapter-format','declaredFormat','Declared naming format'],['adapter-provenance','provenanceText','Import provenance']])test('import '+key+' agrees with the real registration protocol control-character boundary',async t=>{
 const f=fixture(),weights=new File(['weights'],'study.safetensors');t.after(()=>f.controller.dispose());await f.choose('Adapter weights',weights);
 const body=value=>({type:'RegisterAdapterVersion',adapterId:null,previousVersionId:null,weightsAssetId:'weights_1',configAssetId:null,provenanceAssetId:null,name:'Study',declaredFamily:'ideogram-v4',declaredFormat:'fal',provenanceText:'Source text',[key]:key==='provenanceText'?adapterImportProvenance({weights,config:null,provenance:null},value):value});
 for(const point of [0,8,11,12,14,31]){const value='before'+String.fromCharCode(point)+'after';assert.throws(()=>adapterRegistration(body(value)),/ADAPTER_RECORD_INVALID/);const input=await editField(f,id,value);await f.click('prepare-adapter-import');assert.equal(input.currentTarget.value,value);assert.equal(fieldProperty(f.template(),id,'value'),value);assert.equal(fieldProperty(f.template(),id,'error'),label+' cannot contain control characters other than tab, line feed or carriage return.');assert.deepEqual(validationItems(f).map(issue=>issue.target),[id]);assert.deepEqual(fieldProperty(f.template(),'adapter-weights','files'),[weights]);assert.equal(f.uploads.length,0);assert.equal(f.commands.length,0);}
 // The protocol permits these three whitespace controls and DEL. Do not widen its rejection set.
 for(const point of [9,10,13,127]){const value='before'+String.fromCharCode(point)+'after';assert.doesNotThrow(()=>adapterRegistration(body(value)));await editField(f,id,value);assert.equal(fieldProperty(f.template(),id,'error'),'');assert.equal(validationItems(f),undefined);assert.deepEqual(f.controller.validationIssues('import'),[]);}
 await editField(f,id,'Corrected value');await f.click('prepare-adapter-import');assert.equal(f.uploads.length,1);assert.equal(f.uploads[0].file,weights);
});
test('operational import failures remain distinct from field validation',async t=>{const f=fixture();t.after(()=>f.controller.dispose());await f.choose('Adapter weights',new File(['weights'],'study.safetensors'));f.editor.upload=async()=>{throw Error('Local transfer unavailable');};await f.click('prepare-adapter-import');assert.equal(validationItems(f),undefined);assert.equal(fieldProperty(f.template(),'adapter-weights','error'),'');assert(find(f.template(),'<en-alert role="alert">').values.includes('Local transfer unavailable'));assert.deepEqual(f.focuses,[]);});
for(const boundary of ['document','revision','session','identity','owner','disposed'])test('an upload resolving after '+boundary+' cannot register or prepare another owner',async()=>{
 const f=fixture();let release;f.editor.upload=()=>new Promise(r=>release=r);await f.choose('Adapter weights',new File(['weights'],'study.safetensors'));const task=f.click('prepare-adapter-import');await tick();
 if(boundary==='document')f.editor.view.document={id:'other',revision:'1'};if(boundary==='revision')f.editor.view.document.revision='2';if(boundary==='session')f.editor.sessionId='other';if(boundary==='identity')f.identity('other');if(boundary==='owner')f.editor.draftOwner={};if(boundary==='disposed')f.controller.dispose();
 release({stagingId:'old',sha256:hash});await task;await flush();assert.equal(f.commands.length,0);assert.equal(find(f.template(),'Register immutable adapter version'),undefined);
});
test('settled file choice and delayed action honor native cancellation',async()=>{const f=fixture(),choose=find(f.template(),'label="Adapter weights"').values.find(v=>typeof v==='function'),e=event({files:[new File(['weights'],'study.safetensors')]});choose(e);e.defaultPrevented=true;await flush();assert.equal(find(f.template(),'id="prepare-adapter-import"').values[0],true);await f.choose('Adapter weights',new File(['weights'],'study.safetensors'));const action=find(f.template(),'id="prepare-adapter-import"').values.find(v=>typeof v==='function'),veto=event();action(veto);veto.defaultPrevented=true;await tick();assert.equal(f.uploads.length,0);});
test('exact restored versions are fetched for eligibility and unknown profiles stay absent',async()=>{const attached={version:'version_1',hash,scale:'0'};const f=fixture([attached]);const e=await f.controller.eligibility([attached]);assert.equal(e.adapters.get('version_1').hash,hash);assert.equal(e.adapters.get('version_1').runtimeVerified,false);f.editor.json=async()=>entry();assert.equal((await f.controller.eligibility([attached])).adapters.size,0);});
test('unknown named compatibility profiles cannot be relabeled as the supported request profile',async()=>{const f=fixture([{version:'version_1',hash,scale:'1',runtimeAcknowledged:true}]);f.editor.json=async()=>eligible({profileId:'future'});assert.equal((await f.controller.eligibility()).adapters.size,0);});
test('async eligibility refuses a changed owner before publishing any usable entry',async()=>{const f=fixture([{version:'version_1',hash,scale:'1'}]);let release,entered;const started=new Promise(resolve=>entered=resolve);f.editor.json=()=>new Promise(r=>{release=r;entered();});const pending=f.controller.eligibility();await started;f.identity('other');release(eligible());await assert.rejects(pending,/selection changed/);});
test('scale and explicit acknowledgement update exact drafts without mutating the old version array',async()=>{
 const original=[{version:'version_1',hash,scale:'1'}],f=fixture(original);let part=find(f.template(),'<en-number-field label=');part.values.find(v=>typeof v==='function')(event({value:'0'}));await flush();assert.equal(f.selected()[0].scale,'0');assert.equal(original[0].scale,'1');
 part=find(f.template(),'<en-switch label=');part.values.find(v=>typeof v==='function')(event({checked:true}));await flush();assert.equal(f.selected()[0].runtimeAcknowledged,true);assert.equal(f.selected()[0].scale,'0');assert.equal(original[0].runtimeAcknowledged,undefined);
});
function scaleProperty(template,name){const part=find(template,'<en-number-field label=');return part.values[part.strings.findIndex(value=>value.endsWith('.'+name+'='))];}
for(const value of ['',' ','NaN','Infinity','-0.1','4.01'])test('invalid scale '+JSON.stringify(value)+' remains an editable draft with an inline error',async t=>{
 const original=[{version:'version_1',hash,scale:'1'}],f=fixture(original);t.after(()=>f.controller.dispose());const part=find(f.template(),'<en-number-field label='),input=event({value});
 part.values.find(v=>typeof v==='function')(input);await flush();assert.equal(input.currentTarget.value,value);assert.equal(f.selected()[0].scale,value);assert.equal(original[0].scale,'1');assert.equal(f.changes.length,1);
 assert.equal(scaleProperty(f.template(),'value'),value);assert.equal(scaleProperty(f.template(),'error'),'Adapter scale must be a number from 0 to 4.');assert.equal(f.commands.length,0);assert.equal(f.uploads.length,0);
 const correction=find(f.template(),'<en-number-field label=');correction.values.find(v=>typeof v==='function')(event({value:'0'}));await flush();assert.equal(f.selected()[0].scale,'0');assert.equal(scaleProperty(f.template(),'error'),'');
});
test('scale edit length admission preserves the previous complete draft and never truncates',async t=>{
 const f=fixture([{version:'version_1',hash,scale:'1'}]);t.after(()=>f.controller.dispose());const value='0'.repeat(64);let part=find(f.template(),'<en-number-field label=');part.values.find(v=>typeof v==='function')(event({value}));await flush();assert.equal(f.selected()[0].scale,value);assert.equal(scaleProperty(f.template(),'error'),'');
 part=find(f.template(),'<en-number-field label=');const refused=event({value:'0'.repeat(65)});part.values.find(v=>typeof v==='function')(refused);await flush();assert.equal(refused.currentTarget.value,value);assert.equal(f.selected()[0].scale,value);assert.equal(f.changes.length,1);assert(find(f.template(),'<en-alert role="alert">').values.includes('Adapter scale exceeds 64 characters. The previous complete value is retained.'));
});
test('a restored long valid scale keeps the existing semantic validation without being relabelled invalid',async t=>{
 const value='0'.repeat(65),f=fixture([{version:'version_1',hash,scale:value}]);t.after(()=>f.controller.dispose());assert.equal(adapterScale(value),value);assert.equal(scaleProperty(f.template(),'value'),value);assert.equal(scaleProperty(f.template(),'error'),'');assert.equal(await f.controller.focusInvalidScale(),false);assert.equal(f.focuses.length,0);
});
for(const boundary of ['cancelled','owner','selection'])test('settled invalid scale edit cannot cross '+boundary+' ownership',async t=>{
 const original=[{version:'version_1',hash,scale:'1'}],f=fixture(original);t.after(()=>f.controller.dispose());const part=find(f.template(),'<en-number-field label='),input=event({value:'4.01'});part.values.find(v=>typeof v==='function')(input);
 if(boundary==='cancelled')input.defaultPrevented=true;if(boundary==='owner')f.identity('next-owner');if(boundary==='selection')f.controller.render([{...original[0],scale:'2'}],()=>{throw Error('Old scale must not edit a replacement selection');});
 await flush();assert.equal(f.selected(),original);assert.equal(f.changes.length,0);
});
function scaleFocusControls(f,{allowed=true,settled=Promise.resolve()}={}){
 const original=f.host.querySelector.bind(f.host),calls=[],fields=new Map();const accordion={isConnected:true,open:false,updateComplete:settled,requestOpen(open){calls.push(open);if(allowed)this.open=open;return allowed?'committed':'canceled';}};
 const controls={accordion,current:accordion,calls,fields};f.host.querySelector=selector=>{if(selector==='#request-adapters')return controls.current;if(selector.startsWith('#request-adapter-scale-')){if(!fields.has(selector))fields.set(selector,{isConnected:true,focus(){f.focuses.push(selector);}});return fields.get(selector);}return original(selector);};return controls;
}
test('scale summary navigation opens the public accordion and focuses the first invalid exact attachment',async t=>{
 const f=fixture([{version:'version_1',hash,scale:'0'},{version:'version_2',hash,scale:'4.01'}]);t.after(()=>f.controller.dispose());const controls=scaleFocusControls(f);
 assert.equal(await f.controller.focusInvalidScale(),true);assert.deepEqual(controls.calls,[true]);assert.equal(controls.accordion.open,true);assert.deepEqual(f.focuses,['#request-adapter-scale-1']);assert.equal(f.changes.length,0);assert.equal(f.commands.length,0);
});
test('canceled accordion expansion cannot focus a hidden invalid scale',async t=>{
 const f=fixture([{version:'version_1',hash,scale:'4.01'}]);t.after(()=>f.controller.dispose());const controls=scaleFocusControls(f,{allowed:false});assert.equal(await f.controller.focusInvalidScale(),false);assert.deepEqual(controls.calls,[true]);assert.equal(controls.accordion.open,false);assert.deepEqual(f.focuses,[]);
});
for(const boundary of ['document','revision','session','identity','owner','selection','disposed','accordion','field','collapsed'])test('scale focus awaiting expansion cannot cross '+boundary+' ownership',async t=>{
 const f=fixture([{version:'version_1',hash,scale:'4.01'}]);t.after(()=>f.controller.dispose());let finish;const controls=scaleFocusControls(f,{settled:new Promise(resolve=>{finish=resolve;})});const pending=f.controller.focusInvalidScale();await flush();assert.deepEqual(controls.calls,[true]);let releasing;
 if(boundary==='document')f.editor.view.document={id:'other',revision:'1'};if(boundary==='revision')f.editor.view.document.revision='2';if(boundary==='session')f.editor.sessionId='other';if(boundary==='identity')f.identity('other');if(boundary==='owner')f.editor.draftOwner={drafts:new Map()};if(boundary==='selection')f.controller.render([{version:'version_1',hash,scale:'2'}],()=>{});if(boundary==='disposed')releasing=f.controller.dispose();if(boundary==='accordion')controls.current={...controls.accordion};if(boundary==='field')f.host.querySelector('#request-adapter-scale-0').isConnected=false;if(boundary==='collapsed')controls.accordion.open=false;
 finish();assert.equal(await pending,false);await releasing;assert.deepEqual(f.focuses,[]);
});
test('new owner clears composition lock and binds empty public file selections',async()=>{const f=fixture();await f.choose('Adapter weights',new File(['x'],'first.safetensors'));const root=find(f.template(),'aria-label="Local adapter library"');root.values.find(v=>typeof v==='function')();f.identity('second');f.render();await f.controller.models.release();await f.host.updateComplete;f.render();const cleared=find(f.template(),'label="Adapter weights"');assert.deepEqual(cleared.values[0],[]);await f.choose('Adapter weights',new File(['x'],'second.safetensors'));await f.click('prepare-adapter-import');assert.equal(f.uploads.length,1);assert.equal(f.uploads[0].file.name,'second.safetensors');});
function dynamicId(t,id){if(!t||typeof t!=='object')return;if(t.strings){const i=t.values.indexOf(id);if(i>=0&&t.strings[i].endsWith('id='))return t.values.slice(i).find(v=>typeof v==='function');}for(const v of Array.isArray(t)?t:t.values??[]){const result=dynamicId(v,id);if(result)return result;}}
async function deletionFixture(blocked=false){const f=fixture(),plan={kind:'adapter-deletion-plan-1',id:'plan',versionId:'version_1',adapterId:'adapter_1',version:'1',weights:blob,owner:'client',dependencies:blocked?[{kind:'draft',id:'draft_1',detail:'Request still references this exact version'}]:[],dependencyCount:blocked?1:0,dependenciesTruncated:false,dependencyHash:hash,canDelete:!blocked,actualFreedBytes:'0',bytesRetained:true,token:hash};let deleted=false;f.editor.command=async c=>{f.commands.push(c);if(c.type==='DeleteAdapterVersion')deleted=true;return [{type:'AssetRegistered',payload:{asset:{id:'plan',adapterDeletion:{kind:c.type==='PreviewAdapterDeletion'?'preview':'deleted',versionId:'version_1',planId:'plan',token:hash}}}}];};f.editor.json=async path=>{f.reads.push(path);return path.includes('/deletion-reviews/')?plan:{protocolVersion:1,items:deleted?[]:[entry()],nextAfter:null};};await f.click('search-adapter-library');const callback=dynamicId(f.template(),'preview-adapter-deletion-version_1');assert(callback);callback(event());await tick();await flush();return {f,plan};}
test('library deletion previews exact dependencies, then confirms the same immutable token without freed-byte claims',async()=>{const {f}=await deletionFixture();assert.deepEqual(f.commands,[{type:'PreviewAdapterDeletion',versionId:'version_1'}]);assert(find(f.template(),'aria-label="Adapter deletion review"'));await f.click('confirm-adapter-deletion');assert.deepEqual(f.commands.at(-1),{type:'DeleteAdapterVersion',versionId:'version_1',planId:'plan',token:hash});assert(find(f.template(),'<p role="status">').values.some(v=>typeof v==='string'&&v.includes('no disk space was freed')));});
test('blocked deletion explains retained references and refuses confirm even if callback is invoked',async()=>{const {f}=await deletionFixture(true);assert(find(f.template(),'Deletion is blocked until'));await f.click('confirm-adapter-deletion');assert.equal(f.commands.length,1);});
test('dirty or composing drafts cannot be bypassed to prepare deletion',async()=>{const f=fixture();await f.click('search-adapter-library');f.editor.draftOwner.drafts.set('draft',{composing:true,pending:false,savedGeneration:'0',generation:'1'});dynamicId(f.template(),'preview-adapter-deletion-version_1')(event());await tick();await flush();assert.equal(f.commands.length,0);assert(find(f.template(),'<en-alert role="alert">').values.some(v=>typeof v==='string'&&v.includes('finish composing')));});
test('cursor navigation returns through earlier pages, preserves filters and files, and focuses a stable result heading',async()=>{
 const attached=[{version:'selected',hash,scale:'0'}],f=fixture(attached),weights=new File(['x'],'unsaved.safetensors');
 await f.choose('Adapter weights',weights);
 dynamicId(f.template(),'adapter-search')(event({value:'Local study'}));await flush();
 f.editor.json=async path=>{f.reads.push(path);const cursor=new URL(path,'http://127.0.0.1').searchParams.get('after');return {protocolVersion:1,items:[entry({name:'Page '+(cursor??'first')})],nextAfter:cursor===null?'cursor1':cursor==='cursor1'?'cursor2':null};};
 const page=()=>find(f.template(),'Adapter library page ').values[0];
 await f.click('search-adapter-library');assert.equal(page(),1);assert.equal(find(f.template(),'id="first-adapter-page"').values[0],true);assert.equal(find(f.template(),'id="previous-adapter-page"').values[0],true);
 await f.click('next-adapter-page');assert.equal(page(),2);await f.click('next-adapter-page');assert.equal(page(),3);assert.equal(find(f.template(),'id="next-adapter-page"').values[0],true);
 await f.click('previous-adapter-page');assert.equal(page(),2);assert.match(f.reads.at(-1),/after=cursor1/);await f.click('next-adapter-page');assert.equal(page(),3);
 await f.click('first-adapter-page');assert.equal(page(),1);assert.equal(new URL(f.reads.at(-1),'http://127.0.0.1').searchParams.has('after'),false);
 assert(f.reads.every(path=>new URL(path,'http://127.0.0.1').searchParams.get('search')==='Local study'));assert.deepEqual(f.focuses,Array(6).fill('#adapter-library-results'));
 assert.deepEqual(find(f.template(),'label="Adapter weights"').values[0],[weights]);assert.equal(f.selected(),attached);assert.equal(f.changes.length,0);
 dynamicId(f.template(),'adapter-search')(event({value:'Other'}));await flush();assert.equal(find(f.template(),'id="next-adapter-page"'),undefined);await f.click('search-adapter-library');assert.equal(page(),1);assert.equal(f.reads.at(-1),'/api/v1/adapters?search=Other');
});
test('failed page reads retain the current cursor and late owner responses cannot focus or expose their results',async()=>{
 const f=fixture();f.editor.json=async()=>({protocolVersion:1,items:[entry()],nextAfter:'cursor1'});await f.click('search-adapter-library');
 f.editor.json=async()=>{throw Error('Temporary library read failure');};await f.click('next-adapter-page');assert.equal(find(f.template(),'Adapter library page ').values[0],1);assert.equal(f.focuses.length,1);
 let release;f.editor.json=()=>new Promise(resolve=>release=resolve);const next=f.click('next-adapter-page');await tick();f.identity('new-owner');f.render();release({protocolVersion:1,items:[entry({name:'Stale owner page'})],nextAfter:null});await next;await flush();
 assert.equal(find(f.template(),'Adapter library page '),undefined);assert.equal(f.focuses.length,1);assert.equal(find(f.template(),'id="next-adapter-page"'),undefined);
});
test('document release drops resident files and reviews, fences old controls, and permits a fresh import',async()=>{
 const f=fixture(),weights=new File(['x'],'released.safetensors');await f.choose('Adapter weights',weights);await f.choose('Optional adapter config',new File(['{}'],'released.json'));
 await f.click('prepare-adapter-import');await f.click('search-adapter-library');assert(find(f.template(),'Register immutable adapter version'));assert(find(f.template(),'Adapter library page '));
 const oldRegister=find(f.template(),'id="register-adapter-version"').values.find(v=>typeof v==='function'),oldFile=find(f.template(),'label="Adapter weights"').values.find(v=>typeof v==='function');const before=f.commands.length;
 f.controller.releaseDocument();assert.deepEqual(f.controller.files,{weights:null,config:null,provenance:null});assert.deepEqual(f.controller.shownFiles,{weights:[],config:[],provenance:[]});assert.equal(f.controller.prepared,null);assert.equal(f.controller.deletion,null);assert.deepEqual(f.controller.items,[]);assert.deepEqual(f.controller.selected,[]);assert.equal(f.controller.change,null);assert.equal(f.controller.owner,null);
 oldRegister(event());oldFile(event({files:[weights]}));await tick();await flush();assert.equal(f.commands.length,before);
 f.render();assert.deepEqual(find(f.template(),'label="Adapter weights"').values[0],[]);assert.equal(find(f.template(),'Register immutable adapter version'),undefined);assert.equal(find(f.template(),'Adapter library page '),undefined);
 await f.choose('Adapter weights',new File(['next'],'fresh.safetensors'));await f.click('prepare-adapter-import');assert.equal(f.uploads.at(-1).file.name,'fresh.safetensors');assert(find(f.template(),'Register immutable adapter version'));
});
test('permanent disposal cannot reacquire files, selections or callbacks through a stale render',async()=>{
 const f=fixture([{version:'version_1',hash,scale:'1'}]);await f.choose('Adapter weights',new File(['x'],'closed.safetensors'));f.controller.dispose();
 assert.equal(f.controller.render([{version:'foreign',hash,scale:'1'}],()=>assert.fail('disposed callback')),null);assert.deepEqual(f.controller.files,{weights:null,config:null,provenance:null});assert.deepEqual(f.controller.shownFiles,{weights:[],config:[],provenance:[]});assert.deepEqual(f.controller.selected,[]);assert.equal(f.controller.change,null);assert.equal(f.controller.owner,null);
});
test('document release invalidates a pending library page before it can refill cleared state',async()=>{
 const f=fixture();let release;f.editor.json=()=>new Promise(resolve=>release=resolve);const pending=f.click('search-adapter-library');await tick();f.controller.releaseDocument();release({protocolVersion:1,items:[entry()],nextAfter:'old-cursor'});await pending;await flush();
 assert.deepEqual(f.controller.items,[]);assert.equal(f.controller.next,null);assert.equal(f.controller.loaded,false);assert.equal(f.controller.owner,null);assert.deepEqual(f.focuses,[]);
});


const attachmentIssue=code=>({field:'adapters',code,message:({ADAPTER_COUNT:'Attach 1–3 eligible versions.',DUPLICATE_ADAPTER:'Duplicate adapter versions are not allowed.',ADAPTER_RUNTIME_ACK_REQUIRED:'Acknowledge runtime uncertainty for the attached adapter versions.'})[code]??'Other issue'});
const restoredAttachments=count=>Array.from({length:count},(_,index)=>({version:'restored_'+index,hash,scale:index===0?'0':String(index%4)}));
function attachmentFocusControls(f,{allowed=true,settled=Promise.resolve()}={}){
 const original=f.host.querySelector.bind(f.host),calls=[],fields=new Map(),accordion={isConnected:true,open:false,updateComplete:settled,requestOpen(open){calls.push(open);if(allowed)this.open=open;return allowed?'committed':'canceled';}},controls={accordion,current:accordion,calls,fields};
 f.host.querySelector=selector=>{if(selector==='#request-adapters')return controls.current;if(selector==='#adapter-search'||selector.startsWith('#request-adapter-remove-')||selector.startsWith('#request-adapter-ack-')){if(!fields.has(selector))fields.set(selector,{isConnected:true,focus(){f.focuses.push(selector);}});return fields.get(selector);}return original(selector);};return controls;
}
for(const count of [4,16])test('restored '+count+' attachments remain complete and excess count has an explicit removal control',async t=>{
 const original=restoredAttachments(count),f=fixture(original);t.after(()=>f.controller.dispose());assert(find(f.template(),'id="request-adapter-count-error"'));assert.equal(f.selected(),original);assert.equal(f.changes.length,0);for(let index=0;index<count;index++)assert(fieldPart(f.template(),'request-adapter-remove-'+index));
 dynamicId(f.template(),'request-adapter-remove-3')(event());await tick();await flush();assert.deepEqual(f.selected(),original.filter((_,index)=>index!==3));assert.equal(original.length,count);assert.equal(f.selected()[0].scale,'0');assert.equal(f.changes.length,1);assert.equal(f.commands.length,0);assert.equal(f.uploads.length,0);assert.equal(!!find(f.template(),'id="request-adapter-count-error"'),count>4);
});
test('a repeated restored exact version has a row error and explicit removal preserves its first occurrence',async t=>{
 const original=[...restoredAttachments(2),{...restoredAttachments(1)[0],scale:'4.01'}],f=fixture(original);t.after(()=>f.controller.dispose());assert(fieldPart(f.template(),'request-adapter-duplicate-2'));assert.equal(fieldPart(f.template(),'request-adapter-duplicate-0'),undefined);assert.equal(f.selected()[2].scale,'4.01');assert.equal(f.changes.length,0);
 dynamicId(f.template(),'request-adapter-remove-2')(event());await tick();await flush();assert.deepEqual(f.selected(),original.slice(0,2));assert.equal(f.selected()[0].scale,'0');assert.equal(original[2].scale,'4.01');assert.equal(fieldPart(f.template(),'request-adapter-duplicate-2'),undefined);assert.equal(f.commands.length,0);
});
test('unchecked runtime acknowledgement is clear until a current strict issue, then explicit correction clears its group',async t=>{
 const original=restoredAttachments(1),issue=attachmentIssue('ADAPTER_RUNTIME_ACK_REQUIRED'),f=fixture(original);t.after(()=>f.controller.dispose());assert.equal(find(f.template(),'id="request-adapter-ack-error"'),undefined);assert.equal(await f.controller.focusAttachmentIssue(issue),false);assert.equal(fieldProperty(f.template(),'request-adapter-ack-0','checked'),false);
 f.setIssues([issue]);assert(find(f.template(),'id="request-adapter-ack-error"'));const part=fieldPart(f.template(),'request-adapter-ack-0');part.values.find(value=>typeof value==='function')(event({checked:true}));await flush();assert.equal(f.selected()[0].runtimeAcknowledged,true);assert.equal(f.selected()[0].scale,'0');assert.equal(original[0].runtimeAcknowledged,undefined);assert.equal(find(f.template(),'id="request-adapter-ack-error"'),undefined);assert.equal(f.commands.length,0);
});
for(const [code,selected,target]of [
 ['ADAPTER_COUNT',[],'#adapter-search'],['ADAPTER_COUNT',restoredAttachments(4),'#request-adapter-remove-3'],
 ['DUPLICATE_ADAPTER',[...restoredAttachments(2),restoredAttachments(1)[0]],'#request-adapter-remove-2'],
 ['ADAPTER_RUNTIME_ACK_REQUIRED',[{...restoredAttachments(1)[0],runtimeAcknowledged:true},restoredAttachments(2)[1]],'#request-adapter-ack-1'],
])test('current '+code+' summary reveals '+target+' without changing the draft',async t=>{
 const issue=attachmentIssue(code),f=fixture(selected,[issue]);t.after(()=>f.controller.dispose());const controls=attachmentFocusControls(f);assert.equal(await f.controller.focusAttachmentIssue(issue),true);assert.deepEqual(controls.calls,[true]);assert.deepEqual(f.focuses,[target]);assert.equal(f.selected(),selected);assert.equal(f.changes.length,0);assert.equal(f.commands.length,0);assert.equal(f.uploads.length,0);
});
test('attachment summary refuses canceled expansion, unrelated and stale issue identities, and corrected local facts',async t=>{
 const issue=attachmentIssue('ADAPTER_COUNT'),f=fixture(restoredAttachments(4),[issue]);t.after(()=>f.controller.dispose());const controls=attachmentFocusControls(f,{allowed:false});assert.equal(await f.controller.focusAttachmentIssue(issue),false);assert.deepEqual(controls.calls,[true]);assert.equal(await f.controller.focusAttachmentIssue({...issue}),false);assert.equal(await f.controller.focusAttachmentIssue(attachmentIssue('SCALE')),false);assert.deepEqual(f.focuses,[]);
 for(const [code,selected]of [['ADAPTER_COUNT',restoredAttachments(1)],['DUPLICATE_ADAPTER',restoredAttachments(2)],['ADAPTER_RUNTIME_ACK_REQUIRED',[{...restoredAttachments(1)[0],runtimeAcknowledged:true}]]]){const stale=attachmentIssue(code);f.controller.render(selected,()=>assert.fail('Focus must not mutate'),[stale]);assert.equal(await f.controller.focusAttachmentIssue(stale),false);}assert.deepEqual(f.focuses,[]);
});
for(const boundary of ['document','revision','session','identity','owner','selection','issues','caller','action','disposed','accordion','field','collapsed'])test('attachment summary awaiting expansion refuses '+boundary+' changes',async t=>{
 const issue=attachmentIssue('ADAPTER_COUNT'),original=restoredAttachments(4),f=fixture(original,[issue]);t.after(()=>f.controller.dispose());let finish,releasing,caller=true;const controls=attachmentFocusControls(f,{settled:new Promise(resolve=>finish=resolve)}),pending=f.controller.focusAttachmentIssue(issue,()=>caller);await flush();assert.deepEqual(controls.calls,[true]);
 if(boundary==='document')f.editor.view.document={id:'other',revision:'1'};if(boundary==='revision')f.editor.view.document.revision='2';if(boundary==='session')f.editor.sessionId='other';if(boundary==='identity')f.identity('other');if(boundary==='owner')f.editor.draftOwner={drafts:new Map()};if(boundary==='selection')f.controller.render(original.slice(0,3),()=>{},[issue]);if(boundary==='issues')f.setIssues([issue]);if(boundary==='caller')caller=false;if(boundary==='action'){f.controller.action(event(),f.controller.capture(),()=>{});await tick();await flush();assert.equal(f.controller.busy,false);assert.equal(f.controller.requestIssues[0],issue);}if(boundary==='disposed')releasing=f.controller.dispose();if(boundary==='accordion')controls.current={...controls.accordion};if(boundary==='field')f.host.querySelector('#request-adapter-remove-3').isConnected=false;if(boundary==='collapsed')controls.accordion.open=false;
 finish();assert.equal(await pending,false);await releasing;assert.deepEqual(f.focuses,[]);assert.equal(f.changes.length,0);
});

// Exercise the rendered public controls through their actual binding callbacks.
function namedButton(template,label){
 if(!template||typeof template!=='object')return;
 if(template.strings){const at=template.values.findIndex((value,index)=>value===label&&template.strings[index].endsWith('>')&&template.strings[index+1].startsWith('</en-button>'));if(at>=0)return template;}
 for(const child of Array.isArray(template)?template:template.values??[]){const found=namedButton(child,label);if(found)return found;}
}
function buttonDisabled(button){assert(button,'rendered public button');const index=button.strings.findIndex(part=>part.endsWith('?disabled='));assert(index>=0,'actual disabled binding');return button.values[index];}
test('shared action rendering retains exact public IDs, labels, disabled bindings and removal ownership',async t=>{
 const original=[{version:'first',hash,scale:'0',runtimeAcknowledged:true},{version:'second',hash,scale:'4'}],f=fixture(original);t.after(()=>f.controller.dispose());
 for(const [id,label,disabled] of [['prepare-adapter-import','Review local adapter import',true],['search-adapter-library','Search local library',false],['check-adapter-updates','Check attachment updates',false],['request-adapter-remove-1','Remove adapter 2',false]]){
  const part=find(f.template(),'id="'+id+'"');assert(part,id);assert(part.values.includes(label),label);assert.equal(buttonDisabled(part),disabled,id);assert.equal(typeof part.values.find(value=>typeof value==='function'),'function',id);
 }
 assert.equal(find(f.template(),'id="unrelated-adapter-action"'),undefined);
 const remove=find(f.template(),'id="request-adapter-remove-1"').values.find(value=>typeof value==='function'),canceled=event();remove(canceled);canceled.defaultPrevented=true;await tick();await flush();assert.equal(f.selected(),original);assert.equal(f.changes.length,0);
 await f.click('request-adapter-remove-1');assert.deepEqual(f.selected(),[original[0]]);assert.notEqual(f.selected()[0],original[0]);assert.equal(original.length,2);assert.equal(f.commands.length,0);assert.equal(f.uploads.length,0);
 f.identity('replacement');remove(event());await tick();await flush();assert.equal(f.changes.length,1,'old rendered callback cannot change the replacement owner');
});
test('rendered adapter order actions preserve boundary controls, exact order, zero and immutable attachment copies',async t=>{
 const original=[{version:'first',hash,scale:'0',runtimeAcknowledged:true},{version:'second',hash,scale:'1'},{version:'third',hash,scale:'4'}],snapshot=structuredClone(original),f=fixture(original);t.after(()=>f.controller.dispose());
 assert.equal(buttonDisabled(namedButton(f.template(),'Move adapter 1 earlier')),true);assert.equal(buttonDisabled(namedButton(f.template(),'Move adapter 3 later')),true);
 const later=namedButton(f.template(),'Move adapter 1 later'),earlier=namedButton(f.template(),'Move adapter 2 earlier');assert.equal(buttonDisabled(later),false);assert.equal(buttonDisabled(earlier),false);
 later.values.find(value=>typeof value==='function')(event());await tick();await flush();assert.deepEqual(f.selected(),[snapshot[1],snapshot[0],snapshot[2]]);assert.deepEqual(original,snapshot);for(const item of f.selected())assert(!original.includes(item),'every attachment is copied');
 namedButton(f.template(),'Move adapter 2 earlier').values.find(value=>typeof value==='function')(event());await tick();await flush();assert.deepEqual(f.selected(),snapshot);assert.equal(f.selected()[0].scale,'0');assert.equal(f.selected()[0].runtimeAcknowledged,true);
 const retained=f.selected();earlier.values.find(value=>typeof value==='function')(event());await tick();await flush();assert.equal(f.selected(),retained,'stale rendered selection cannot reorder the replacement list');assert.equal(f.commands.length,0);assert.equal(f.uploads.length,0);
});
