import {test as base,expect,type Page} from '@playwright/test';
import {mkdtemp,realpath,mkdir,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {serverProcess} from '../editor/process.js';import {ownedOPFS} from '../editor/owned-opfs.js';import {recordDOMErrors} from '../editor/error-monitor.js';
const receipt=process.env.EDITOR_RECEIPT!,probe=process.env.REVIEW_PROBE!;
const test=base.extend({context:async({playwright,browserName,contextOptions,viewport},use)=>{
 const profile=browserName==='webkit'?await mkdtemp(join(await realpath(tmpdir()),'p22-alignment-profile-')):null;
 const browser=profile?null:await playwright[browserName].launch();const context=profile?await playwright.webkit.launchPersistentContext(profile,{...contextOptions,viewport}):await browser!.newContext({...contextOptions,viewport});
 await Promise.all(context.pages().map(p=>p.close()));try{await use(context);}finally{await context.close();await browser?.close();if(profile)await rm(profile,{recursive:true,force:true});await writeFile(join(receipt,'fixture.json'),JSON.stringify({contextClosed:true,browserClosed:true,profileRemoved:profile}));}
}});
const click=(p:Page,n:string)=>p.getByRole('button',{name:n,exact:true}).click();
async function field(p:Page,n:string,v:string){const f=p.getByRole('spinbutton',{name:n,exact:true});await f.fill(v);await f.press('Tab');}
test('independent '+probe+' public boundary',async({page,context,browserName})=>{
 await mkdir(receipt,{recursive:true});const guard=await ownedOPFS(context,'p22-alignment-'+probe),errors=await recordDOMErrors(context),csp:any[]=[],external:string[]=[],consoleErrors:string[]=[],requests:any[]=[],responses:any[]=[],pending:Promise<void>[]=[];
 await context.exposeBinding('independentCSP',(_s,v)=>csp.push(v));await context.addInitScript(()=>addEventListener('securitypolicyviolation',e=>(window as any).independentCSP({directive:e.effectiveDirective,blocked:e.blockedURI})));
 page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});
 page.on('request',r=>{if(r.method()==='POST'&&r.url().includes('/api/v1/')){const data=r.postData();if(data&&r.headers()['content-type']?.includes('application/json'))requests.push({path:new URL(r.url()).pathname,body:JSON.parse(data)});}});
 page.on('response',r=>{if(r.request().method()==='POST'&&r.url().includes('/api/v1/ui/'))pending.push(r.json().then(body=>{responses.push(body);}));});
 const dir=await mkdtemp(join(await realpath(tmpdir()),'p22-alignment-')),server=await serverProcess(join(dir,'private'));let caught:any=null,effects:any,colors:any[]=[],geometry:any;
 await page.route('**/*',route=>{const u=new URL(route.request().url());if(['http:','https:'].includes(u.protocol)&&u.origin!==server.origin){external.push(u.origin);return route.abort();}return route.continue();});
 try{
  await guard.admit(page,server.origin);await page.goto(await server.pair());await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();
  await click(page,'New');await field(page,'Width (px)','3');await field(page,'Height (px)','2');await click(page,'Create');await expect(page.getByRole('dialog',{name:'New document',exact:true})).toBeHidden();
  if(probe==='mapping'){
   await click(page,'Import image');await page.getByLabel('Image file',{exact:true}).setInputFiles('tests/raster/fixtures/hidden-alpha.png');await click(page,'Apply reviewed result');await expect(page.getByText('ImportAsset accepted and saved locally.',{exact:true})).toBeVisible();await page.getByRole('treeitem').first().click();
   await field(page,'X','1');await click(page,'Apply transform');await expect(page.getByText('ApplyTransform accepted and saved locally.',{exact:true})).toBeVisible();
   await click(page,'Select');await field(page,'Selection X','1');await field(page,'Selection Y','0');await field(page,'Selection width','1');await field(page,'Selection height','2');await click(page,'Apply selection');await click(page,'Use selection as mask');await field(page,'Feather radius (document px)','0');await click(page,'Preview mask');await expect(page.getByRole('button',{name:'Apply layer mask',exact:true})).toBeEnabled();await click(page,'Apply layer mask');await expect(page.getByText('SetLayerProperties accepted and saved locally.',{exact:true})).toBeVisible();
   await page.getByRole('combobox',{name:'Operation',exact:true}).selectOption('Edit masked region');await page.getByRole('textbox',{name:'Prompt',exact:true}).fill('Independent translated-source mask check');await page.getByRole('combobox',{name:'Request size',exact:true}).selectOption('auto');await click(page,'Use operation strength default');await click(page,'Attach selected image asset');await expect(page.getByText(/Source .*version .*3 × 2/)).toBeVisible();await click(page,'Attach selected layer edit mask');await expect(page.getByText(/Mask .*partial coverage/)).toBeVisible();await click(page,'Review current request document');await expect(page.getByText('Request document revision confirmed.',{exact:true})).toBeVisible();await click(page,'Review exact request');
   await expect.poll(async()=>await page.locator('#request-review').count()+await page.locator('#request-errors').count()).toBeGreaterThan(0);
   if(await page.locator('#request-review').count()){
    await click(page,'Accept this exact review locally');await expect.poll(async()=>{await Promise.all(pending);return responses.filter(x=>x.acceptedReview||x.status==='rejected').length;}).toBeGreaterThan(0);
   }
   await Promise.all(pending);await page.screenshot({path:join(receipt,'mapping-outcome.png'),caret:'initial'});
   const transform=requests.find(r=>r.body.command?.body.type==='ApplyTransform')?.body.command.body.transform;expect(transform).toEqual([1,0,0,1,1,0]);
   const mask=requests.find(r=>r.body.command?.body.type==='SetLayerProperties'&&r.body.command.body.properties.mask)?.body.command.body.properties.mask;expect(mask.mapping).toBe('document-r16-v1');
   await writeFile(join(receipt,'mapping-result.json'),JSON.stringify({transform,layerMask:mask,expected:'Reject until explicit source/mask frame resolution; document X=1 maps to original image X=0 under translation +1.',acceptedReviews:responses.filter(x=>x.acceptedReview),preparedReviews:responses.filter(x=>x.review)},null,2));
   expect(responses.filter(x=>x.acceptedReview),'An original-image source must not silently inherit a translated layer document-grid mask.').toHaveLength(0);
   const summary=page.locator('#request-errors');
   await expect(summary.getByRole('heading',{name:'Request needs attention',exact:true})).toBeVisible();
   await expect(summary.getByRole('link',{name:/^MASK_FRAME_MISMATCH:/})).toBeVisible();
   await expect(page.locator('#request-review')).toHaveCount(0);
   expect(responses.filter(x=>x.review),'Unresolved translated mapping must not prepare a review.').toHaveLength(0);
   const originalMask=mask.assetId;await click(page,'Attach visible document snapshot');const visibleSource=page.locator('.typed-request').getByText(/^Source .+ · version .+ · visible-document$/);await expect(visibleSource).toHaveCount(1);await expect(visibleSource).toBeVisible();await expect(page.getByText('Source snapshot attached. Reattach its mask before confirming alignment.',{exact:true})).toBeVisible();await click(page,'Attach selected layer edit mask');await expect(page.getByText('Mask frame attached to the visible-document source. Confirm its alignment.',{exact:true})).toBeVisible();await click(page,'Confirm source and mask alignment');await expect(page.getByText('Source and mask alignment confirmed without changing pixels.',{exact:true})).toBeVisible();await click(page,'Review exact request');await expect(page.getByRole('heading',{name:'Immutable request review',exact:true})).toBeVisible();await expect(page.locator('#request-review')).toBeFocused();await click(page,'Accept this exact review locally');await expect(page.getByText('Request review accepted locally. No job was queued and no provider call was made.',{exact:true})).toBeVisible();await Promise.all(pending);
   const accepted=responses.filter(x=>x.acceptedReview);expect(accepted).toHaveLength(1);const review=responses.find(x=>x.review?.id===accepted[0].acceptedReview).review;expect(review.request.source.scope).toBe('visible-document');expect(review.request.mask.assetId).toBe(originalMask);expect(review.request.mask.frame.layer.transform).toEqual([1,0,0,1,1,0]);expect(review.request.mask.frame.alignment.sourceToDocument).toEqual([1,0,0,1,0,0]);expect(review.request.mask.frame.alignment.maskToDocument).toEqual([1,0,0,1,0,0]);expect(review.conversion).toBeNull();expect(review.dispatch).toBe(false);await writeFile(join(receipt,'compatible-result.json'),JSON.stringify({review,accepted},null,2));await page.screenshot({path:join(receipt,'compatible-outcome.png'),caret:'initial'});

  }else{
   const prompt=page.getByRole('textbox',{name:'Prompt',exact:true});await prompt.fill('Theme keeps Café 東京');
   for(const appearance of ['light','dark']){await page.evaluate(v=>document.documentElement.setAttribute('data-en-appearance',v),appearance);await prompt.focus();await expect(prompt).toBeFocused();await expect(prompt).toHaveValue('Theme keeps Café 東京');colors.push(await page.locator('.typed-request').evaluate(el=>({color:getComputedStyle(el).color,background:getComputedStyle(document.body).backgroundColor})));if(browserName!=='webkit')await page.screenshot({path:join(receipt,appearance+'.png'),caret:'initial'});}
   expect(colors[0]).not.toEqual(colors[1]);await page.setViewportSize({width:320,height:900});const link=page.getByRole('link',{name:'Go to Request',exact:true});await link.focus();await link.press('Enter');await expect(page.locator('.typed-request')).toBeVisible();geometry=await page.locator('.typed-request').evaluate(el=>({width:el.getBoundingClientRect().width,scroll:el.scrollWidth}));expect(geometry.width).toBeGreaterThan(0);expect(geometry.scroll).toBeLessThanOrEqual(geometry.width+1);
  }
  effects=await server.effects();expect(Object.values(effects).every(n=>n===0)).toBe(true);expect(errors).toEqual([]);expect(csp).toEqual([]);expect(external).toEqual([]);expect(consoleErrors).toEqual([]);
 }catch(e){caught=String(e);throw e;}finally{
  await Promise.all(pending);await writeFile(join(receipt,'before-cleanup.json'),JSON.stringify({caught,requests,responses,errors,csp,external,consoleErrors,colors,geometry},null,2));
  try{for(const p of context.pages())await p.goto('about:blank');await guard.cleanup();guard.verify();}finally{effects=await server.effects();await server.close();if(caught)await promisify(execFile)('/usr/bin/tar',['-czf',join(receipt,'failed-private-root.tar.gz'),'-C',dir,'.']);await rm(dir,{recursive:true,force:true});await writeFile(join(receipt,'observations.json'),JSON.stringify({caught,runtime:context.browser()?.version(),errors,csp,external,consoleErrors,effects,colors,geometry,cleanup:{opfs:guard.ledger,serverClosed:true,privateRootRemoved:dir}},null,2));}
 }
});
