// Staged source tests. Shared ledger/native display behavior is outside this
// controller fixture; the actual metadata parser and treatment validators run.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {transformWithOxc} from 'vite';
const data=code=>'data:text/javascript;base64,'+Buffer.from(code).toString('base64'),lit=data('export const nothing=null;export function html(strings,...values){return {strings,values};}');
const imports={...Object.fromEntries(['protocol/json','protocol/sha256'].map(name=>['../'+name+'.js',pathToFileURL(resolve('dist/local/src/'+name+'.js')).href])),'./raster-plan.js':pathToFileURL(resolve('dist/local/src/request/raster-plan.js')).href};
const {canonical}=await import(imports['../protocol/json.js']),{SHA256}=await import(imports['../protocol/sha256.js']),hash=value=>new SHA256().update(new TextEncoder().encode(value)).digest();
async function compiled(path,values){let code=(await transformWithOxc(await readFile(path,'utf8'),path)).code;for(const [from,to]of Object.entries(values))code=code.replaceAll(JSON.stringify(from),JSON.stringify(to)).replaceAll("'"+from+"'",JSON.stringify(to));return data(code);}
const pureURL=await compiled('src/request/text-treatment.ts',imports),{planTextTreatment,textTreatmentPlanRef,bindTextTreatmentEnvelope}=await import(pureURL);
const memoryURL=data(`export const records=[];export function modelPayloadBytes(v){return JSON.stringify(v).length*4;}export function reserveModelBytes(owner,bytes){let refs=1,live=true;const row={owner,bytes,released:false};records.push(row);return {pin(){if(!refs)throw Error('released');refs++;let active=true;return ()=>{if(active){active=false;if(!--refs)row.released=true;}};},release(){if(live){live=false;if(!--refs)row.released=true;}}};}export function createOwnedModel(owner,bytes,create){const p=reserveModelBytes(owner,bytes);try{return {value:create(),release:()=>p.release(),pin:()=>p.pin()};}catch(error){p.release();throw error;}}`),memory=await import(memoryURL),controls=await compiled('src/ui/adapters.ts',{});
const {loadCandidateTextTreatment,CandidateTextTreatmentEditing}=await import(await compiled(new URL('../../src/ui/candidate-text-treatment.ts',import.meta.url).pathname,{...imports,lit,'../request/text-treatment.js':pureURL,'../observability/model-memory.js':memoryURL,'../observability/prompt-memory.js':data('export class PromptReaderCleanupError extends Error{}'),'./adapters.js':controls}));
const ref=(value,mediaType='application/json',byteLength=String(Buffer.byteLength(value)))=>({hash:hash(value),mediaType,byteLength});
function makePlan(count=2,alter=()=>{}){const layers=Array.from({length:count},(_,i)=>({id:'native-'+i,version:'1',kind:'text',visible:true,locked:false,stateHash:hash('state-'+i),contribution:{manifest:ref('contribution-'+i),pixels:ref('pixels-'+i,'application/x-ideogram-rgba8','16'),pixelIdentity:hash('identity-'+i)},native:{source:ref('source-'+i),literal:ref('caption-'+i,'text/plain'),textVersion:hash('text-'+i),renderVersion:hash('render-'+i),dependencyHash:hash('dependencies-'+i)}}));alter(layers);return planTextTreatment({id:'plan',inventory:{schemaVersion:1,kind:'text-treatment-inventory-1',documentId:'document',documentRevision:'1',grid:{width:2,height:2},imageState:ref('image'),layers,composition:null,semanticText:[]},choice:{kind:'baked-lettering',allowedHideNativeIds:['native-0'],duplicationAcknowledgement:'reviewed-duplicates',excludedSemanticIds:[],approvalId:'request-review'},beforeSource:null,afterSource:null,prompt:{mode:'plain',bytes:ref('make lettering','text/plain'),projection:null},edit:null});}
function transport(plan=makePlan(),alter=()=>{}){const bytes=Buffer.from(canonical(plan)),input={candidateId:'candidate',candidateVersion:'1',jobId:'job',attemptId:'attempt',safety:'safe',envelope:bindTextTreatmentEnvelope(plan,textTreatmentPlanRef(plan))},calls=[],pages=[];const editor={async ownedJSON(path,owner,init,current,max){assert.equal(owner,'candidate-text-plan-page');assert.equal(max,65536);assert.equal(init.signal.aborted,false);assert(current());const offset=Number(new URL(path,'http://local').searchParams.get('offset')),part=bytes.subarray(offset,offset+32768),page={bytes:part.toString('base64'),byteLength:String(bytes.length),offset:String(offset),nextOffset:offset+part.length<bytes.length?String(offset+part.length):null};calls.push(path);alter(page,calls.length,init);const record={released:false};pages.push(record);return {value:page,release(){assert(!record.released);record.released=true;}};}};return {plan,input,editor,calls,pages,bytes};}
const flush=async()=>{for(let i=0;i<40;i++)await Promise.resolve();},turn=async()=>{await new Promise(resolve=>setTimeout(resolve,0));await new Promise(setImmediate);await flush();};
function event(value='',checked=false){const control={value,checked,isConnected:true};return {currentTarget:control,composedPath:()=>[control],defaultPrevented:false};}
function handler(t,id,kind='click'){if(!t||typeof t!=='object')return;if(t.strings){const start=t.strings.findIndex((s,i)=>s.includes('id="'+id+'"')||s.endsWith('id=')&&t.values[i]===id);if(start>=0)for(let i=start;i<t.strings.length;i++){if(t.strings[i].endsWith('@'+kind+'='))return t.values[i];if(i>start&&t.strings[i].includes('</en-'))break;}}for(const value of Array.isArray(t)?t:t.values??[]){const found=handler(value,id,kind);if(found)return found;}}
async function fixture(t,plan=makePlan()){const f=transport(plan),start=memory.records.length,errors=[],invalidated=[];let template,controller,current=true;f.editor.view={document:{id:'document',revision:'1'},image:{layers:f.plan.inventory.layers.map(row=>({...row,name:row.id,layerToDocument:[1,0,0,1,8,9]}))}};f.editor.session={identity:()=> 'client'};f.editor.draftOwner={};const host={updateComplete:Promise.resolve(),requestUpdate(){this.updateComplete=Promise.resolve().then(()=>{template=controller.render(f.input);});}};controller=new CandidateTextTreatmentEditing(host,f.editor,{owns:()=>()=>current,invalidatePlacement:id=>invalidated.push(id),error:error=>errors.push(error)});template=controller.render(f.input);await flush();t.after(async()=>{controller.dispose();await flush();await controller.drain();assert(memory.records.slice(start).every(row=>row.released));assert(f.pages.every(page=>page.released));});return {...f,controller,errors,invalidated,stale(){current=false;},async click(id){const cb=handler(template,id);assert.equal(typeof cb,'function',id);cb(event());await turn();},async choose(id,value,checked=false){const cb=handler(template,id,'en-change');assert.equal(typeof cb,'function',id);const dispatched=event(value,checked);cb(dispatched);dispatched.currentTarget=null;await flush();},async render(){host.requestUpdate();await flush();}};}
const placement={newLayerId:'fresh-candidate-layer',placement:'current-document',mode:'full-candidate',preservation:'none'};

test('bounded plan loader reads sequential exact pages and returns the immutable validated plan',async()=>{const f=transport(makePlan(100)),start=memory.records.length,result=await loadCandidateTextTreatment(f.editor,f.input,()=>true,new AbortController().signal);assert(f.calls.length>1);assert(f.calls.length<=17);assert.deepEqual(result.value,f.plan);assert(f.pages.every(page=>page.released));assert(memory.records.slice(start).filter(row=>row.owner==='candidate-text-plan-workspace').every(row=>row.released));result.release();assert(memory.records.slice(start).every(row=>row.released));});
for(const field of ['offset','byteLength','nextOffset'])test('loader refuses changed '+field+' without retaining a plan',async()=>{const f=transport(makePlan(),page=>{page[field]=field==='nextOffset'?'1':'999';}),start=memory.records.length;await assert.rejects(loadCandidateTextTreatment(f.editor,f.input,()=>true,new AbortController().signal),/page/);assert(f.pages.every(page=>page.released));assert(memory.records.slice(start).every(row=>row.released));});
test('loader refuses exact-length corrupted bytes by hash before parsing authority',async()=>{const f=transport(makePlan(),page=>{const bytes=Buffer.from(page.bytes,'base64');bytes[2]^=1;page.bytes=bytes.toString('base64');});await assert.rejects(loadCandidateTextTreatment(f.editor,f.input,()=>true,new AbortController().signal),/bytes changed/);assert(f.pages.every(page=>page.released));});
test('loader cancellation after an owned page releases both page and workspace',async()=>{const abort=new AbortController(),f=transport(makePlan(),()=>abort.abort()),start=memory.records.length;await assert.rejects(loadCandidateTextTreatment(f.editor,f.input,()=>true,abort.signal),{name:'AbortError'});assert(f.pages.every(page=>page.released));assert(memory.records.slice(start).every(row=>row.released));});
test('unsafe candidate and excessive plan size are refused before any read',async()=>{for(const mutate of [input=>input.safety='unknown',input=>input.envelope.plan.byteLength='524289']){const f=transport();mutate(f.input);await assert.rejects(loadCandidateTextTreatment(f.editor,f.input,()=>true,new AbortController().signal));assert.equal(f.calls.length,0);}});
test('keep both requires explicit duplicate acknowledgement and stable exact placement choice',async t=>{const f=await fixture(t);await f.click('candidate-text-load-candidate');await f.choose('candidate-text-action-candidate','keep-both');await f.click('candidate-text-confirm-candidate');assert.match(f.errors.at(-1).message,/Acknowledge duplicate/);assert.throws(()=>f.controller.selection('candidate',placement),/Acknowledge duplicate/);await f.choose('candidate-text-duplicate-candidate','',true);await f.click('candidate-text-confirm-candidate');const selected=f.controller.selection('candidate',placement);assert.equal(selected.choice.newLayerId,placement.newLayerId);assert(selected.choice.duplicationAcknowledgement);assert.deepEqual(selected.choice.hideNativeIds,[]);assert.deepEqual(selected.choice.nativeCopies,[]);assert.equal(f.controller.selection('candidate',placement),selected);});
test('hide selection is explicit and constrained to original request-approved native IDs',async t=>{const f=await fixture(t);await f.click('candidate-text-load-candidate');await f.choose('candidate-text-action-candidate','hide-native-originals');await f.click('candidate-text-confirm-candidate');assert.match(f.errors.at(-1).message,/Select the native originals/);await f.choose('candidate-text-hide-native-0','',true);await f.click('candidate-text-confirm-candidate');assert.deepEqual(f.controller.selection('candidate',placement).choice.hideNativeIds,['native-0']);await f.choose('candidate-text-hide-native-1','',true);await f.click('candidate-text-confirm-candidate');assert.match(f.errors.at(-1).message,/not approved for hiding/);});
test('new document copies only explicit native selections with fresh IDs and reviewed numeric transforms',async t=>{const f=await fixture(t);await f.click('candidate-text-load-candidate');await f.choose('candidate-text-action-candidate','new-document');await f.choose('candidate-text-copy-native-0','',true);await f.click('candidate-text-confirm-candidate');const value=f.controller.selection('candidate',{...placement,placement:'new-document'});assert.equal(value.choice.nativeCopies.length,1);assert.equal(value.choice.nativeCopies[0].sourceLayerId,'native-0');assert.deepEqual(value.choice.nativeCopies[0].transform,[1,0,0,1,8,9]);assert.notEqual(value.choice.nativeCopies[0].newLayerId,'native-0');assert.notEqual(value.choice.nativeCopies[0].newLayerId,placement.newLayerId);assert.deepEqual(value.choice.hideNativeIds,[]);assert.throws(()=>f.controller.selection('candidate',placement),/matching/);});
test('locked or changed native layer cannot carry a previously selected hide into placement',async t=>{const f=await fixture(t);await f.click('candidate-text-load-candidate');await f.choose('candidate-text-action-candidate','hide-native-originals');await f.choose('candidate-text-hide-native-0','',true);await f.click('candidate-text-confirm-candidate');f.editor.view.image.layers[0].locked=true;assert.throws(()=>f.controller.selection('candidate',placement),/hidden, or is locked/);});
test('candidate becoming unknown clears previously loaded plan and choices',async t=>{const f=await fixture(t);await f.click('candidate-text-load-candidate');await f.choose('candidate-text-action-candidate','keep-both');await f.choose('candidate-text-duplicate-candidate','',true);await f.click('candidate-text-confirm-candidate');assert(f.controller.selection('candidate',placement));f.input.safety='unknown';await f.render();assert.equal(f.controller.selection('candidate',placement),undefined);});
test('changed document revision permits immutable provenance inspection but refuses current adoption authority',async t=>{const f=await fixture(t);f.editor.view.document.revision='2';await f.click('candidate-text-load-candidate');assert.deepEqual(f.errors,[]);assert.deepEqual(f.controller.plan.value,f.plan);assert.equal(f.controller.planCurrent(),true);await f.choose('candidate-text-action-candidate','keep-both');await f.choose('candidate-text-duplicate-candidate','',true);await f.click('candidate-text-confirm-candidate');assert.match(f.errors.at(-1).message,/request document changed/);assert.throws(()=>f.controller.selection('candidate',placement),/request document changed/);});

test('fresh new-document review uses immutable request provenance after the source revision changes',async t=>{const f=await fixture(t),original=structuredClone(f.plan);f.editor.view.document.revision='2';await f.click('candidate-text-load-candidate');await f.choose('candidate-text-action-candidate','new-document');assert.throws(()=>f.controller.selection('candidate',{...placement,placement:'new-document'}),/Confirm the lettering/);await f.click('candidate-text-confirm-candidate');const value=f.controller.selection('candidate',{...placement,placement:'new-document'});assert.deepEqual(value.plan,f.input.envelope);assert.deepEqual(value.choice.nativeCopies,[]);assert.deepEqual(value.choice.hideNativeIds,[]);assert.equal(value.choice.preservation,'none');assert.deepEqual(f.plan,original);assert.equal(f.controller.plan.value.inventory.documentRevision,'1');assert.deepEqual(f.errors,[]);});
for(const change of ['edited','deleted','locked'])test('new-document copy selects the retained native version after live original is '+change,async t=>{const f=await fixture(t),original=structuredClone(f.plan);f.editor.view.document.revision='2';if(change==='deleted')f.editor.view.image.layers.shift();else if(change==='edited')Object.assign(f.editor.view.image.layers[0],{version:'2',layerToDocument:[2,0,0,2,90,91]});else f.editor.view.image.layers[0].locked=true;await f.click('candidate-text-load-candidate');await f.choose('candidate-text-action-candidate','new-document');await f.choose('candidate-text-copy-native-0','',true);await f.click('candidate-text-confirm-candidate');const value=f.controller.selection('candidate',{...placement,placement:'new-document'});assert.deepEqual(value.plan,f.input.envelope);assert.equal(value.choice.nativeCopies.length,1);assert.equal(value.choice.nativeCopies[0].sourceLayerId,'native-0');assert.deepEqual(value.choice.nativeCopies[0].transform,change==='locked'?[1,0,0,1,8,9]:[1,0,0,1,0,0]);assert.deepEqual(value.choice.hideNativeIds,[]);assert.deepEqual(f.plan,original);assert.deepEqual(f.errors,[]);});
test('new-document approval cannot survive a later revision or provenance reload',async t=>{const f=await fixture(t);f.editor.view.document.revision='2';await f.click('candidate-text-load-candidate');await f.choose('candidate-text-action-candidate','new-document');await f.click('candidate-text-confirm-candidate');const first=f.controller.selection('candidate',{...placement,placement:'new-document'});f.editor.view.document.revision='3';assert.throws(()=>f.controller.selection('candidate',{...placement,placement:'new-document'}),/Load current text-treatment provenance/);await f.click('candidate-text-load-candidate');assert.throws(()=>f.controller.selection('candidate',{...placement,placement:'new-document'}),/Confirm the lettering/);await f.click('candidate-text-confirm-candidate');const fresh=f.controller.selection('candidate',{...placement,placement:'new-document'});assert.notEqual(fresh.choice.approvalId,first.choice.approvalId);assert.deepEqual(fresh.plan,first.plan);assert.equal(f.controller.plan.value.inventory.documentRevision,'1');});
test('new-document recovery remains bound to the candidate source document',async t=>{const f=await fixture(t);f.editor.view.document={id:'other-document',revision:'1'};await f.click('candidate-text-load-candidate');assert.deepEqual(f.controller.plan.value,f.plan);assert.equal(f.controller.planCurrent(),false);await f.choose('candidate-text-action-candidate','new-document');assert.throws(()=>f.controller.selection('candidate',{...placement,placement:'new-document'}),/Load current text-treatment provenance/);});

for(const flag of ['hidden','locked'])test('new-document copy refuses a native version already '+flag+' in the immutable request',async t=>{const plan=makePlan(2,layers=>{if(flag==='hidden')layers[1].visible=false;else layers[1].locked=true;}),f=await fixture(t,plan);f.editor.view.document.revision='2';Object.assign(f.editor.view.image.layers[1],{visible:true,locked:false,version:'2'});await f.click('candidate-text-load-candidate');await f.choose('candidate-text-action-candidate','new-document');await f.choose('candidate-text-copy-native-1','',true);assert.match(f.errors.at(-1).message,/retained native version was hidden or locked/);await f.click('candidate-text-confirm-candidate');assert.deepEqual(f.controller.selection('candidate',{...placement,placement:'new-document'}).choice.nativeCopies,[]);});
test('copied-native transform stepper change invalidates approval and serializes the displayed value',async t=>{const f=await fixture(t);await f.click('candidate-text-load-candidate');await f.choose('candidate-text-action-candidate','new-document');await f.choose('candidate-text-copy-native-0','',true);await f.click('candidate-text-confirm-candidate');const first=f.controller.selection('candidate',{...placement,placement:'new-document'});assert.equal(first.choice.nativeCopies[0].transform[4],8);await f.choose('candidate-text-transform-native-0-4','9');assert.throws(()=>f.controller.selection('candidate',{...placement,placement:'new-document'}),/Confirm the lettering/);await f.click('candidate-text-confirm-candidate');const changed=f.controller.selection('candidate',{...placement,placement:'new-document'});assert.equal(changed.choice.nativeCopies[0].transform[4],9);assert.notEqual(changed.choice.approvalId,first.choice.approvalId);assert.deepEqual(first.choice.nativeCopies[0].transform,[1,0,0,1,8,9]);});
test('candidate controls retain their public host after the event dispatch currentTarget is cleared',async t=>{const f=await fixture(t);await f.click('candidate-text-load-candidate');await f.choose('candidate-text-action-candidate','new-document');await f.choose('candidate-text-copy-native-0','',true);await f.choose('candidate-text-transform-native-0-5','33');await f.click('candidate-text-confirm-candidate');const value=f.controller.selection('candidate',{...placement,placement:'new-document'});assert.equal(value.choice.action,'new-document');assert.equal(value.choice.nativeCopies.length,1);assert.equal(value.choice.nativeCopies[0].transform[5],33);assert.deepEqual(f.errors,[]);});
