import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {transformWithOxc} from 'vite';
const data=code=>'data:text/javascript;base64,'+Buffer.from(code).toString('base64'),lit=data('export const nothing=null;export function html(strings,...values){return {strings,values};}');
let code=(await transformWithOxc(await readFile('src/ui/request.ts','utf8'),'request.ts')).code;const adapter=data((await transformWithOxc(await readFile('src/ui/adapters.ts','utf8'),'adapters.ts')).code);
for(const [name,url]of Object.entries({'lit':lit,'./adapters.js':adapter,...Object.fromEntries(['request/core','protocol/json','composition/core'].map(n=>['../'+n+'.js',pathToFileURL(resolve('dist/local/src/'+n+'.js')).href]))}))code=code.replaceAll(JSON.stringify(name),JSON.stringify(url)).replaceAll("'"+name+"'",JSON.stringify(url));
const {RequestEditing}=await import(data(code));const flush=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};const tick=()=>new Promise(r=>setTimeout(r,5));
function find(t,part){if(!t||typeof t!=='object')return; if(t.strings){const i=t.strings.findIndex(s=>s.includes(part));if(i>=0)return {strings:t.strings.slice(i),values:t.values.slice(i)};}for(const v of Array.isArray(t)?t:t.values??[]){const f=find(v,part);if(f)return f;}}
function event(value=''){const host={value,isConnected:true};return {currentTarget:host,composedPath:()=>[host],defaultPrevented:false};}
function fixture(){let instance,rendered,identity='client',resolveSave;const saved=[],reviews=[];const editor={view:{ready:true,document:{id:'doc',revision:'1'}},sessionId:'session',session:{identity:()=>identity},draftOwner:{drafts:new Map()},ui:{drafts:[]},json:async()=>({items:[]}),changeDraft(id,kind,text,target,composing,revision){saved.push({id,kind,text,target,composing,revision});const generation=String(saved.length);editor.draftOwner.drafts.set(id,{generation,savedGeneration:null});},async flushDrafts(){for(const d of editor.draftOwner.drafts.values())d.savedGeneration=d.generation;},async requestReview(body){reviews.push(body);return {review:{id:'review',token:'token',request:{kind:'generate'},prompt:{},estimate:{unknown:[]}},acceptedReview:'review'};}};const host={requestUpdate(){this.updateComplete=Promise.resolve().then(()=>rendered=instance.render());},updateComplete:Promise.resolve(),querySelector(){return {focus(){}};}};instance=new RequestEditing(host,editor);return {instance,editor,host,saved,reviews,async initial(){await instance.sync();host.requestUpdate();await flush();},template:()=>rendered,prompt:()=>find(rendered,'<en-textarea id="prompt"').values.find(x=>typeof x==='function'),button:()=>find(rendered,'<en-button id="prepare-request"').values.find(x=>typeof x==='function'),identity(v){identity=v;}};}
for(const boundary of ['document','session','identity','connection','owner','disposed','operation'])for(const queued of [false,true])test('actual rendered request callback refuses '+boundary+' '+queued,async()=>{const f=fixture();await f.initial();const cb=f.prompt(),e=event('foreign');if(queued)cb(e);if(boundary==='document')f.editor.view.document={id:'new',revision:'1'};if(boundary==='session')f.editor.sessionId='new';if(boundary==='identity')f.identity('new');if(boundary==='connection')f.editor.session={...f.editor.session};if(boundary==='owner')f.editor.draftOwner={drafts:new Map()};if(boundary==='disposed')f.instance.dispose();if(boundary==='operation')f.instance.operationChanged('Generate with Fast');const count=f.saved.length;if(!queued)cb(e);await flush();assert.equal(f.saved.length,count);assert(!f.saved.some(x=>JSON.parse(x.text).text==='foreign'));});
test('settled final cancellation and public value govern request field',async()=>{const f=fixture();await f.initial();let e=event('veto');f.prompt()(e);e.defaultPrevented=true;await flush();assert.equal(f.saved.length,0);e=event('tentative');f.prompt()(e);e.currentTarget.value='settled';await flush();assert.equal(JSON.parse(f.saved[0].text).text,'settled');});
test('pending action honors final native veto and detached hosts',async()=>{const f=fixture();await f.initial();for(const kind of ['veto','detach']){const e=event();f.button()(e);if(kind==='veto')e.defaultPrevented=true;else e.currentTarget.isConnected=false;await tick();}assert.equal(f.reviews.length,0);});
test('prepare binds saved current draft and accepted field value',async()=>{const f=fixture();await f.initial();f.prompt()(event('exact'));await flush();f.button()(event());await tick();await flush();assert.equal(f.reviews.length,1);assert.equal(f.reviews[0].type,'PrepareRequestReview');assert.equal(f.reviews[0].generation,f.editor.draftOwner.drafts.get(f.reviews[0].draftId).savedGeneration);});
for(const boundary of ['edit','owner','disposed'])test('pending prepare cannot publish review after '+boundary,async()=>{const f=fixture();await f.initial();f.prompt()(event('exact'));await flush();let release;f.editor.flushDrafts=()=>new Promise(r=>release=r);f.button()(event());await tick();if(boundary==='edit'){f.prompt()(event('new'));await flush();}else if(boundary==='owner')f.editor.draftOwner={drafts:new Map()};else f.instance.dispose();release();await flush();assert.equal(f.reviews.length,0);});
test('operation switch preserves each complete incompatible draft',async()=>{const f=fixture();await f.initial();f.prompt()(event('base'));await flush();f.instance.operationChanged('Generate with Instant');await flush();f.prompt()(event('instant'));await flush();f.instance.operationChanged('Generate image');await flush();assert.equal(find(f.template(),'<en-textarea id="prompt"').values[1],'base');f.instance.operationChanged('Generate with Instant');await flush();assert.equal(find(f.template(),'<en-textarea id="prompt"').values[1],'instant');});
test('plain and raw prompt modes retain separate exact drafts',async()=>{const f=fixture();await f.initial();f.prompt()(event('plain retained'));await flush();const mode=()=>find(f.template(),'<en-select id=').values.find(x=>typeof x==='function');mode()(event('raw'));await flush();f.prompt()(event(' {"future":true} \n'));await flush();mode()(event('plain'));await flush();assert.equal(find(f.template(),'<en-textarea id="prompt"').values[1],'plain retained');mode()(event('raw'));await flush();assert.equal(find(f.template(),'<en-textarea id="prompt"').values[1],' {"future":true} \n');});
test('prepare drains an earlier in-flight save before requiring the current generation receipt',async()=>{const f=fixture();await f.initial();f.prompt()(event('current'));await flush();let calls=0;f.editor.flushDrafts=async()=>{if(++calls===1)return;for(const d of f.editor.draftOwner.drafts.values())d.savedGeneration=d.generation;};f.button()(event());await tick();await flush();assert.equal(calls,2);assert.equal(f.reviews.length,1);});
test('native composition start and end in one dispatch turn release review and save the settled draft',async()=>{const f=fixture();await f.initial();const callbacks=find(f.template(),'<section aria-label="Typed request draft"').values.filter(x=>typeof x==='function');callbacks[0]();callbacks[1]();await flush();assert.equal(f.saved.at(-1).composing,false);f.prompt()(event('settled IME'));await flush();f.button()(event());await tick();await flush();assert.equal(f.reviews.length,1);});
test('same-turn public fields retain both settled values for the same owner',async()=>{const f=fixture();await f.initial();const prompt=f.prompt(),seed=find(f.template(),'<en-text-field id="request-seed"').values.find(x=>typeof x==='function');prompt(event('Both values'));seed(event('9007199254740993123'));await flush();const last=JSON.parse(f.saved.at(-1).text);assert.equal(last.text,'Both values');assert.equal(last.draft.fields.seed,'9007199254740993123');});

for(const boundary of ['document','session','identity','connection','owner','disposed','operation'])for(const queued of [false,true])test('rendered operation selector refuses '+boundary+' '+queued,async()=>{const f=fixture();await f.initial();let changes=0;const cb=f.instance.operationChoice(()=>changes++),e=event('Generate with Instant');if(queued)cb(e);if(boundary==='document')f.editor.view.document={id:'new',revision:'1'};if(boundary==='session')f.editor.sessionId='new';if(boundary==='identity')f.identity('new');if(boundary==='connection')f.editor.session={...f.editor.session};if(boundary==='owner')f.editor.draftOwner={drafts:new Map()};if(boundary==='disposed')f.instance.dispose();if(boundary==='operation')f.instance.operationChanged('Generate with Fast');const op=f.instance.operation,count=f.saved.length;if(!queued)cb(e);await flush();assert.equal(changes,0);assert.equal(f.instance.operation,op);assert.equal(f.saved.length,count);});
