import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {transformWithOxc} from 'vite';
const data=code=>'data:text/javascript;base64,'+Buffer.from(code).toString('base64'),lit=data('export const nothing=null;export function html(strings,...values){return {strings,values};}');
let code=(await transformWithOxc(await readFile('src/ui/request.ts','utf8'),'request.ts')).code;const adapter=data((await transformWithOxc(await readFile('src/ui/adapters.ts','utf8'),'adapters.ts')).code);
for(const [name,url]of Object.entries({'lit':lit,'./adapters.js':adapter,...Object.fromEntries(['request/core','protocol/json','composition/core'].map(n=>['../'+n+'.js',pathToFileURL(resolve('dist/local/src/'+n+'.js')).href]))}))code=code.replaceAll(JSON.stringify(name),JSON.stringify(url)).replaceAll("'"+name+"'",JSON.stringify(url));
const {RequestEditing}=await import(data(code));const ownedControllers=new Set();test.afterEach(()=>{for(const controller of ownedControllers)controller.dispose();ownedControllers.clear();});const flush=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};const tick=()=>new Promise(r=>setTimeout(r,5));
function find(t,part){if(!t||typeof t!=='object')return; if(t.strings){const i=t.strings.findIndex(s=>s.includes(part));if(i>=0)return {strings:t.strings.slice(i),values:t.values.slice(i)};}for(const v of Array.isArray(t)?t:t.values??[]){const f=find(v,part);if(f)return f;}}
function event(value=''){const host={value,isConnected:true};return {currentTarget:host,composedPath:()=>[host],defaultPrevented:false};}
function fixture(){let instance,rendered,identity='client',resolveSave;const saved=[],reviews=[];const editor={view:{ready:true,document:{id:'doc',revision:'1'}},sessionId:'session',session:{identity:()=>identity},draftOwner:{drafts:new Map()},ui:{drafts:[]},json:async()=>({items:[]}),changeDraft(id,kind,text,target,composing,revision){saved.push({id,kind,text,target,composing,revision});const generation=String(saved.length);editor.draftOwner.drafts.set(id,{generation,savedGeneration:null});},async flushDrafts(){for(const d of editor.draftOwner.drafts.values())d.savedGeneration=d.generation;},async requestReview(body){reviews.push(body);return {review:{id:'review',token:'token',request:{kind:'generate'},prompt:{},estimate:{unknown:[]}},acceptedReview:'review'};}};const host={requestUpdate(){this.updateComplete=Promise.resolve().then(()=>rendered=instance.render());},updateComplete:Promise.resolve(),querySelector(){return {focus(){}};}};instance=new RequestEditing(host,editor);ownedControllers.add(instance);return {instance,editor,host,saved,reviews,async initial(){await instance.sync();host.requestUpdate();await flush();},template:()=>rendered,prompt:()=>find(rendered,'<en-textarea id="prompt"').values.find(x=>typeof x==='function'),button:()=>find(rendered,'<en-button id="prepare-request"').values.find(x=>typeof x==='function'),identity(v){identity=v;}};}
for(const boundary of ['document','session','identity','connection','owner','disposed','operation'])for(const queued of [false,true])test('actual rendered request callback refuses '+boundary+' '+queued,async()=>{const f=fixture();await f.initial();const cb=f.prompt(),e=event('foreign');if(queued)cb(e);if(boundary==='document')f.editor.view.document={id:'new',revision:'1'};if(boundary==='session')f.editor.sessionId='new';if(boundary==='identity')f.identity('new');if(boundary==='connection')f.editor.session={...f.editor.session};if(boundary==='owner')f.editor.draftOwner={drafts:new Map()};if(boundary==='disposed')f.instance.dispose();if(boundary==='operation')f.instance.operationChanged('Generate with Fast');const count=f.saved.length;if(!queued)cb(e);await flush();assert.equal(f.saved.length,count);assert(!f.saved.some(x=>JSON.parse(x.text).text==='foreign'));});
test('settled final cancellation and public value govern request field',async()=>{const f=fixture();await f.initial();let e=event('veto');f.prompt()(e);e.defaultPrevented=true;await flush();assert.equal(f.saved.length,0);e=event('tentative');f.prompt()(e);e.currentTarget.value='settled';await flush();assert.equal(JSON.parse(f.saved[0].text).text,'settled');});
test('pending action honors final native veto and detached hosts',async()=>{const f=fixture();await f.initial();for(const kind of ['veto','detach']){const e=event();f.button()(e);if(kind==='veto')e.defaultPrevented=true;else e.currentTarget.isConnected=false;await tick();}assert.equal(f.reviews.length,0);});
test('prepare binds saved current draft and accepted field value',async()=>{const f=fixture();await f.initial();f.prompt()(event('exact'));await flush();f.button()(event());await tick();await flush();assert.equal(f.reviews.length,1);assert.equal(f.reviews[0].type,'PrepareRequestReview');assert.equal(f.reviews[0].generation,f.editor.draftOwner.drafts.get(f.reviews[0].draftId).savedGeneration);});
for(const boundary of ['edit','owner','disposed'])test('pending prepare cannot publish review after '+boundary,async()=>{const f=fixture();await f.initial();f.prompt()(event('exact'));await flush();let release;f.editor.flushDrafts=()=>new Promise(r=>release=r);f.button()(event());await tick();if(boundary==='edit'){f.prompt()(event('new'));await flush();}else if(boundary==='owner')f.editor.draftOwner={drafts:new Map()};else f.instance.dispose();release();await flush();assert.equal(f.reviews.length,0);});
test('operation switch preserves each complete incompatible draft',async()=>{const f=fixture();await f.initial();f.prompt()(event('base'));await flush();f.instance.operationChanged('Generate with Instant');await flush();f.prompt()(event('instant'));await flush();f.instance.operationChanged('Generate image');await flush();assert.equal(find(f.template(),'<en-textarea id="prompt"').values[1],'base');f.instance.operationChanged('Generate with Instant');await flush();assert.equal(find(f.template(),'<en-textarea id="prompt"').values[1],'instant');});
test('plain and raw prompt modes retain separate exact drafts',async()=>{const f=fixture();await f.initial();f.prompt()(event('plain retained'));await flush();const mode=()=>find(f.template(),'<en-select id=').values.find(x=>typeof x==='function');mode()(event('raw'));await flush();f.prompt()(event(' {"future":true} \n'));await flush();mode()(event('plain'));await flush();assert.equal(find(f.template(),'<en-textarea id="prompt"').values[1],'plain retained');mode()(event('raw'));await flush();assert.equal(find(f.template(),'<en-textarea id="prompt"').values[1],' {"future":true} \n');});
test('prepare drains an earlier in-flight save before requiring the current generation receipt',async()=>{const f=fixture();await f.initial();f.prompt()(event('current'));await flush();let calls=0;f.editor.flushDrafts=async()=>{if(++calls===1)return;for(const d of f.editor.draftOwner.drafts.values())d.savedGeneration=d.generation;};f.button()(event());await tick();await flush();assert.equal(calls,2);assert.equal(f.reviews.length,1);});
test('native composition start and end in one dispatch turn release review and save the settled draft',async()=>{const f=fixture();await f.initial();const callbacks=find(f.template(),'<section aria-label="Typed request draft"').values.filter(x=>typeof x==='function');callbacks[0]();callbacks[1]();await flush();assert.equal(f.saved.at(-1).composing,false);f.prompt()(event('settled IME'));await flush();f.button()(event());await tick();await flush();assert.equal(f.reviews.length,1);});
test('same-turn public fields retain both settled values for the same owner',async()=>{const f=fixture();await f.initial();const prompt=f.prompt(),seed=find(f.template(),'<en-text-field id="request-seed"').values.find(x=>typeof x==='function');prompt(event('Both values'));seed(event('9007199254740993123'));await flush();const last=JSON.parse(f.saved.at(-1).text);assert.equal(last.text,'Both values');assert.equal(last.draft.fields.seed,'9007199254740993123');});

for(const boundary of ['document','session','identity','connection','owner','disposed','operation'])for(const queued of [false,true])test('rendered operation selector refuses '+boundary+' '+queued,async()=>{const f=fixture();await f.initial();let changes=0;const cb=f.instance.operationChoice(()=>changes++),e=event('Generate with Instant');if(queued)cb(e);if(boundary==='document')f.editor.view.document={id:'new',revision:'1'};if(boundary==='session')f.editor.sessionId='new';if(boundary==='identity')f.identity('new');if(boundary==='connection')f.editor.session={...f.editor.session};if(boundary==='owner')f.editor.draftOwner={drafts:new Map()};if(boundary==='disposed')f.instance.dispose();if(boundary==='operation')f.instance.operationChanged('Generate with Fast');const op=f.instance.operation,count=f.saved.length;if(!queued)cb(e);await flush();assert.equal(changes,0);assert.equal(f.instance.operation,op);assert.equal(f.saved.length,count);});

const fakeRef=n=>({hash:'sha256:'+String(n).repeat(64),byteLength:'24',mediaType:'application/octet-stream'});
async function maskController(translated=false){const f=fixture();Object.assign(f.editor.view.document,{width:3,height:2,image:{compositeAssetId:'composite'}});f.editor.view.selected=['picture'];f.editor.view.image={layers:[{id:'picture',version:'4',assetId:'source',layerToDocument:[1,0,0,1,translated?1:0,0],mask:{assetId:'mask',mapping:'document-r16-v1',inverted:false}}]};f.editor.json=async path=>path.endsWith('/request-reviews')?{items:[]}:path.endsWith('/raster')?{plan:{statistics:{effectivePixels:2}}}:{projection:{value:{id:path.split('/').at(-1),version:'2',qualification:'canonical-raster',blob:fakeRef(1),raster:{role:path.endsWith('/mask')?'mask':'native',pixels:fakeRef(path.endsWith('/composite')?3:2),width:3,height:2,manifest:fakeRef(4)}}}};await f.initial();return f;}
const actionById=(f,id)=>find(f.template(),'<en-button id="'+id+'"').values.find(v=>typeof v==='function');
async function act(f,id){actionById(f,id)(event());await tick();await flush();}
const lastDraft=f=>JSON.parse(f.saved.at(-1).text).draft;
test('public mask attachment captures exact frame and requires explicit compatible alignment',async()=>{const f=await maskController(true);await act(f,'request-source');await act(f,'request-mask');const original=lastDraft(f);assert.deepEqual(original.mask.frame.layer.transform,[1,0,0,1,1,0]);assert.equal(original.mask.frame.alignment,null);await act(f,'request-mask-alignment');assert.deepEqual(lastDraft(f),original);await act(f,'request-visible-source');const beforeAttach=lastDraft(f);await act(f,'request-mask-alignment');assert.deepEqual(lastDraft(f),beforeAttach);await act(f,'request-mask');await act(f,'request-mask-alignment');const next=lastDraft(f);assert.equal(next.source.scope,'visible-document');assert.deepEqual(next.mask.frame.alignment.sourceToDocument,[1,0,0,1,0,0]);assert.deepEqual(next.mask.frame.alignment.maskToDocument,[1,0,0,1,0,0]);assert.deepEqual(next.mask.pixels,original.mask.pixels);});
for(const boundary of ['owner','revision','veto'])test('alignment confirmation cannot survive '+boundary+' boundary',async()=>{const f=await maskController();await act(f,'request-source');await act(f,'request-mask');const cb=actionById(f,'request-mask-alignment'),e=event(),before=f.saved.length;cb(e);if(boundary==='owner')f.editor.draftOwner={drafts:new Map()};if(boundary==='revision')f.editor.view.document={...f.editor.view.document,revision:'2'};if(boundary==='veto')e.defaultPrevented=true;await tick();await flush();assert.equal(f.saved.length,before);assert.equal(lastDraft(f).mask.frame.alignment,null);});
test('pending mask read cannot attach to a replacement owner',async()=>{const f=await maskController();await act(f,'request-source');let release;const read=f.editor.json;f.editor.json=path=>path.endsWith('/raster')?new Promise(r=>release=r):read(path);actionById(f,'request-mask')(event());await tick();await flush();assert(release);f.editor.draftOwner={drafts:new Map()};release({plan:{statistics:{effectivePixels:2}}});await flush();assert.equal(lastDraft(f).mask,null);});

for(const boundary of ['owner','session','identity','document','disposed','veto'])for(const queued of [false,true])test('public queue refresh refuses stale authority '+boundary+' '+queued,async()=>{const f=fixture();await f.initial();let calls=0;f.editor.json=async()=>{calls++;return {session:{id:'session',cap:null},jobs:[],counts:{},limits:{}};};const cb=actionById(f,'refresh-queue'),e=event();if(queued)cb(e);if(boundary==='owner')f.editor.draftOwner={drafts:new Map()};if(boundary==='session')f.editor.sessionId='new';if(boundary==='identity')f.identity('new');if(boundary==='document')f.editor.view.document={id:'new',revision:'1'};if(boundary==='disposed')f.instance.dispose();if(boundary==='veto')e.defaultPrevented=true;if(!queued)cb(e);await tick();await flush();assert.equal(calls,0);});

async function riskController(kind){const f=fixture();await f.initial();const displayed={jobId:'displayed-job',attemptId:'displayed-attempt',expectedVersion:'7',kind};f.instance.riskReview=displayed;f.host.requestUpdate();await flush();return {...f,displayed,confirm:()=>find(f.template(),'<en-card id="queue-risk"').values.find(v=>typeof v==='function')};}
for(const kind of ['override','retry']){
 for(const scheduled of [false,true])test('rendered '+kind+' refuses replaced selection '+(scheduled?'after scheduling':'before invocation'),async()=>{const f=await riskController(kind),commands=[];f.editor.command=async body=>commands.push(body);const callback=f.confirm(),replacement={jobId:'replacement-job',attemptId:'replacement-attempt',expectedVersion:'9',kind};if(scheduled)callback(event());f.instance.riskReview=replacement;if(!scheduled)callback(event());await tick();await flush();assert.deepEqual(commands,[]);assert.equal(f.instance.riskReview,replacement);});
 test('rendered '+kind+' sends exact displayed payload and retains selection replaced during completion',async()=>{const f=await riskController(kind),commands=[];let complete;f.editor.command=(body,document)=>{commands.push({body,document});return new Promise(r=>complete=r);};f.editor.json=async()=>null;f.confirm()(event());await tick();await flush();assert.equal(commands.length,1);assert.deepEqual(commands[0],{document:null,body:kind==='override'?{type:'OverrideUncertainHold',jobId:'displayed-job',attemptId:'displayed-attempt',expectedVersion:'7',acknowledgeOverlapAndChargeRisk:true}:{type:'RetryUncertainJob',jobId:'displayed-job',attemptId:'displayed-attempt',expectedVersion:'7',acknowledgeDuplicateWorkAndChargeRisk:true}});const replacement={jobId:'replacement-job',attemptId:'replacement-attempt',expectedVersion:'9',kind};f.instance.riskReview=replacement;complete();await tick();await flush();assert.equal(f.instance.riskReview,replacement);assert.equal(commands.length,1);});
 test('rendered '+kind+' honors late native veto',async()=>{const f=await riskController(kind),commands=[];f.editor.command=async body=>commands.push(body);const e=event();f.confirm()(e);e.defaultPrevented=true;await tick();await flush();assert.deepEqual(commands,[]);assert.equal(f.instance.riskReview,f.displayed);});
}

async function capController(){const f=fixture();await f.initial();const queue={session:{id:'spend-session',version:'4',cap:null},jobs:[],counts:{},limits:{},nextCursor:null},commands=[];f.editor.command=async(body,document)=>{commands.push({body,document});};f.editor.json=async()=>queue;f.instance.queue=queue;f.host.requestUpdate();await flush();return {...f,commands,queue,field:()=>find(f.template(),'<en-number-field id="request-cap"').values.filter(v=>typeof v==='function'),set:()=>actionById(f,'set-request-cap')};}
test('disposing during a public queue refresh prevents later polling and publication',async()=>{const f=await capController();let calls=0,release;f.editor.json=async()=>{calls++;return calls===1?f.queue:new Promise(r=>release=r);};actionById(f,'refresh-queue')(event());for(let n=0;!release&&n<100;n++)await tick();assert.equal(calls,2);f.instance.dispose();release(f.queue);await new Promise(r=>setTimeout(r,200));await flush();assert.equal(calls,2);assert.equal(f.instance.queue,null);});
function capEvent(host,draft=host.value,composing=false){return {currentTarget:host,composedPath:()=>[host],defaultPrevented:false,detail:{value:draft,isComposing:composing}};}
async function commitCap(f,host,value){host.value=value;f.field()[1](capEvent(host));await flush();}
async function submitCap(f){f.set()(event());await tick();await flush();}
test('cap draft notification cannot submit an older accepted value; typed acceptance sends exact payload',async()=>{const f=await capController(),host={value:'',isConnected:true};await commitCap(f,host,'7');f.field()[0](capEvent(host,'8'));await flush();await submitCap(f);assert.deepEqual(f.commands,[]);await commitCap(f,host,'8');await submitCap(f);assert.deepEqual(f.commands,[{document:null,body:{type:'SetSpendGuard',spendSessionId:'spend-session',expectedConfigVersion:'4',cap:8}}]);});
test('cap public stepper acceptance works without draft-input notification',async()=>{const f=await capController(),host={value:'',isConnected:true};await commitCap(f,host,'2');await submitCap(f);assert.equal(f.commands[0].body.cap,2);await commitCap(f,host,'1');await submitCap(f);assert.equal(f.commands[1].body.cap,1);});
test('cap late-veto rollback blocks submission until a later accepted change',async()=>{const f=await capController(),host={value:'',isConnected:true};await commitCap(f,host,'2');host.value='3';const veto=capEvent(host);f.field()[1](veto);veto.defaultPrevented=true;host.value='2';await flush();await submitCap(f);assert.deepEqual(f.commands,[]);assert.equal(f.instance.cap,'2');await commitCap(f,host,'4');await submitCap(f);assert.equal(f.commands[0].body.cap,4);});
test('cap uses final accepted host value and latest rapid acceptance, never tentative details',async()=>{const f=await capController(),host={value:'2',isConnected:true},change=f.field()[1];change(capEvent(host,'999'));host.value='3';change(capEvent(host,'888'));host.value='4';await flush();await submitCap(f);assert.equal(f.commands.length,1);assert.equal(f.commands[0].body.cap,4);});
for(const value of ['', '0','-1','1.5','9007199254740992'])test('cap refuses invalid accepted value '+JSON.stringify(value),async()=>{const f=await capController(),host={value:'',isConnected:true};await commitCap(f,host,value);await submitCap(f);assert.deepEqual(f.commands,[]);assert.equal(f.instance.issues[0].code,'REQUEST_CAP');});
test('cap composition draft cannot submit the earlier accepted value',async()=>{const f=await capController(),host={value:'',isConnected:true};await commitCap(f,host,'2');f.field()[0](capEvent(host,'3',true));await flush();await submitCap(f);assert.deepEqual(f.commands,[]);});
for(const boundary of ['owner','session','document','identity','disposed'])for(const queued of [false,true])test('cap accepted callback refuses '+boundary+' '+queued,async()=>{const f=await capController(),host={value:'5',isConnected:true},callback=f.field()[1],e=capEvent(host);if(queued)callback(e);if(boundary==='owner')f.editor.draftOwner={drafts:new Map()};if(boundary==='session')f.editor.sessionId='other';if(boundary==='document')f.editor.view.document={id:'other',revision:'1'};if(boundary==='identity')f.identity('other');if(boundary==='disposed')f.instance.dispose();if(!queued)callback(e);await flush();assert.equal(f.instance.cap,'');assert.deepEqual(f.commands,[]);});

test('cap same-turn composition tail preserves accepted transaction',async()=>{const f=await capController(),host={value:'',isConnected:true},[input,change]=f.field();input(capEvent(host,'1'));host.value='1';change(capEvent(host));input(capEvent(host,'1'));await flush();await submitCap(f);assert.deepEqual({accepted:f.instance.cap,pending:f.instance.capPending,commands:f.commands},{accepted:'1',pending:false,commands:[{document:null,body:{type:'SetSpendGuard',spendSessionId:'spend-session',expectedConfigVersion:'4',cap:1}}]});});
test('cap different composition tail stays pending until that new draft is accepted',async()=>{const f=await capController(),host={value:'',isConnected:true},[input,change]=f.field();input(capEvent(host,'1'));host.value='1';change(capEvent(host));input(capEvent(host,'12'));await flush();await submitCap(f);assert.equal(f.instance.cap,'1');assert.equal(f.instance.capPending,true);assert.deepEqual(f.commands,[]);host.value='12';change(capEvent(host));input(capEvent(host,'12'));await flush();await submitCap(f);assert.deepEqual(f.commands,[{document:null,body:{type:'SetSpendGuard',spendSessionId:'spend-session',expectedConfigVersion:'4',cap:12}}]);});
test('cap veto with rollback and duplicate tail cannot submit the previous accepted value',async()=>{const f=await capController(),host={value:'',isConnected:true};await commitCap(f,host,'2');const [input,change]=f.field();input(capEvent(host,'3'));host.value='3';const proposal=capEvent(host);change(proposal);proposal.defaultPrevented=true;host.value='2';input(capEvent(host,'2'));await flush();await submitCap(f);assert.equal(f.instance.cap,'2');assert.equal(f.instance.capPending,true);assert.deepEqual(f.commands,[]);await commitCap(f,host,'4');await submitCap(f);assert.equal(f.commands[0].body.cap,4);});
test('cap rapid accepted transactions with duplicate tails submit only the newest value',async()=>{const f=await capController(),host={value:'',isConnected:true},[input,change]=f.field();for(const value of ['1','12','123']){input(capEvent(host,value));host.value=value;change(capEvent(host));input(capEvent(host,value));}await flush();await submitCap(f);assert.deepEqual(f.commands,[{document:null,body:{type:'SetSpendGuard',spendSessionId:'spend-session',expectedConfigVersion:'4',cap:123}}]);});
test('cap accepted transaction followed by composing draft remains blocked',async()=>{const f=await capController(),host={value:'1',isConnected:true},[input,change]=f.field();change(capEvent(host));input(capEvent(host,'1',true));await flush();await submitCap(f);assert.deepEqual(f.commands,[]);input(capEvent(host,'1',false));await flush();await submitCap(f);assert.equal(f.commands[0].body.cap,1);});
test('cap outer composition guards commands until the native end callback',async()=>{const f=await capController(),host={value:'',isConnected:true};const [start,end]=find(f.template(),'<section aria-label="Typed request draft"').values.filter(v=>typeof v==='function');start();await flush();const [input,change]=f.field();input(capEvent(host,'1',true));host.value='1';change(capEvent(host));input(capEvent(host,'1',false));await flush();await submitCap(f);assert.deepEqual(f.commands,[]);assert.equal(f.instance.composing,true);end();await flush();await submitCap(f);assert.deepEqual(f.commands,[{document:null,body:{type:'SetSpendGuard',spendSessionId:'spend-session',expectedConfigVersion:'4',cap:1}}]);assert.equal(f.saved.at(-1).composing,false);});
test('cap outer composition end and duplicate tail in one turn preserve exact acceptance',async()=>{const f=await capController(),host={value:'',isConnected:true},[input,change]=f.field(),[start,end]=find(f.template(),'<section aria-label="Typed request draft"').values.filter(v=>typeof v==='function');start();input(capEvent(host,'1'));host.value='1';change(capEvent(host));end();input(capEvent(host,'1'));await flush();await submitCap(f);assert.equal(f.instance.composing,false);assert.equal(f.instance.capPending,false);assert.equal(f.commands.length,1);assert.equal(f.commands[0].body.cap,1);});
for(const boundary of ['owner','session','document','identity','disposed','connection','operation'])test('cap composition tail cannot cross '+boundary+' replacement before settlement',async()=>{const f=await capController(),host={value:'',isConnected:true},[input,change]=f.field(),set=f.set();input(capEvent(host,'1'));host.value='1';change(capEvent(host));input(capEvent(host,'1'));if(boundary==='owner')f.editor.draftOwner={drafts:new Map()};if(boundary==='session')f.editor.sessionId='other';if(boundary==='document')f.editor.view.document={id:'other',revision:'1'};if(boundary==='identity')f.identity('other');if(boundary==='disposed')f.instance.dispose();if(boundary==='connection')f.editor.session={...f.editor.session};if(boundary==='operation')f.instance.operationChanged('Generate with Fast');await flush();set(event());await tick();await flush();assert.equal(f.instance.cap,'');assert.deepEqual(f.commands,[]);});
