import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {newDraft,hash,resolve,resolveInactive,bodyTemplate,operations,routes,estimate,draftShape,maskAlignment,requireMaskAlignment,confirmRequestMask,bindRequestMask,requestMaskDependencies,refs} from '../../dist/local/src/request/core.js';
import {createRequestRasterPlan} from '../../dist/local/src/request/raster-plan.js';
import {canonical} from '../../dist/local/src/protocol/json.js';
const text='Café\n東京';const ref=(s,type='text/plain')=>({hash:hash(s),byteLength:String(Buffer.byteLength(s)),mediaType:type});
const pixels=(value,bytes,mediaType)=>({hash:'sha256:'+createHash('sha256').update(Buffer.alloc(bytes,value)).digest('hex'),byteLength:String(bytes),mediaType});
const authored=pixels(0,1024*1024*2,'application/x-ideogram-r16le'),effective=pixels(1,1024*1024*2,'application/x-ideogram-r16le');
const source={assetId:'source',version:'2',blob:ref('png','image/png'),pixels:pixels(2,1024*1024*4,'application/x-ideogram-rgba8'),width:1024,height:1024,scope:'asset',documentRevision:'1'};
const mask={assetId:'mask',version:'3',blob:ref('mask','image/png'),pixels:pixels(3,1024*1024*4,'application/x-ideogram-rgba8'),width:1024,height:1024,sourceHash:source.pixels.hash,polarity:'white-edit',fullAcknowledged:false,empty:false,full:false,plan:ref('plan','application/json'),frame:{kind:'document-mask-frame-1',document:{id:'document_1',revision:'1',width:1024,height:1024},layer:{id:'layer',version:'1',assetId:'source',transform:[1,0,0,1,0,0],mask:{assetId:'mask',mapping:'document-r16-v1',inverted:false}},alignment:null}};mask.frame.alignment=maskAlignment(source,mask);mask.requestPlan=confirmRequestMask(source,mask,authored,effective,'initial-mask-review');
const adapters=[{version:'adapter-1',hash:hash('weights'),scale:'0'}],eligible={adapters:new Map([['adapter-1',{hash:hash('weights'),available:true,profile:'v4-safe-1',runtimeVerified:true}]])};
function fixture(op){const d=newDraft(ref(text));d.operation=op;if(op==='instant')resolveInactive(d,'speed');if(op==='instant'||op==='fast')resolveInactive(d,'acceleration');if(op.startsWith('transform')||op.startsWith('inpaint')){d.source=structuredClone(source);d.fields.strength=op.startsWith('inpaint')?'1':'0.8';d.fields.size='auto';}if(op.startsWith('inpaint'))d.mask=structuredClone(mask);if(op.endsWith('adapters'))d.adapters=structuredClone(adapters);return d;}
const expectedRoutes=['ideogram/v4','ideogram/v4/instant','ideogram/v4/fast','ideogram/v4/image-to-image','ideogram/v4/inpaint','ideogram/v4/lora','ideogram/v4/image-to-image/lora','ideogram/v4/inpaint/lora'];
for(const [i,op] of operations.entries())test(op+' has exact independently stated route and allowed body',()=>{const d=fixture(op),r=resolve(d,text,eligible),body=JSON.parse(bodyTemplate(r,text));const expected={prompt:text,expansion_model:'Medium',image_size:i===3||i===4||i===6||i===7?'auto':{width:1024,height:1024},num_images:1,output_format:'png',sync_mode:false,enable_safety_checker:true};if(i!==1)expected.rendering_speed='BALANCED';if(i!==1&&i!==2)expected.acceleration='none';if([3,4,6,7].includes(i)){expected.image_url='asset:'+source.blob.hash;expected.strength=[4,7].includes(i)?1:0.8;}if([4,7].includes(i))expected.mask_url='asset:'+mask.blob.hash;if(i>=5)expected.loras=[{path:'asset:'+hash('weights'),scale:0}];assert.equal(routes[op].endpoint,expectedRoutes[i]);assert.deepEqual(body,expected);assert(!('seed'in body));assert.equal(estimate(r).total,null);});
for(const speed of ['TURBO','BALANCED','QUALITY'])for(const expansion of ['None','Medium'])test('Fast '+speed+' × '+expansion,()=>{const d=fixture('fast');Object.assign(d.fields,{width:'1600',height:'896',speed,expansion});d.guidanceAcknowledged=true;const body=JSON.parse(bodyTemplate(resolve(d,text),text));assert.equal(body.rendering_speed,speed);assert.equal(body.expansion_model,expansion);assert.deepEqual(body.image_size,{width:1600,height:896});});
for(const field of ['source','mask','adapters','acceleration','expansion','size'])test('Fast rejects independent '+field,()=>{const d=fixture('fast');if(field==='source')d.source=source;if(field==='mask')d.mask=mask;if(field==='adapters')d.adapters=adapters;if(field==='acceleration')d.fields.acceleration='high';if(field==='expansion')d.fields.expansion='Large';if(field==='size')d.fields.size='auto';const before=structuredClone(d);assert.throws(()=>resolve(d,text,eligible),e=>e.issues.some(i=>i.field===field));assert.deepEqual(d,before);});
for(const height of ['900','895','0','2049','896.5'])test('Fast refuses exact invalid height '+height+' without rounding',()=>{const d=fixture('fast');d.fields.width='1600';d.fields.height=height;assert.throws(()=>resolve(d,text));assert.equal(d.fields.height,height);});
test('explicit exclusions bind values and operation while preserving original attachments',()=>{const d=fixture('fast');d.source=source;resolveInactive(d,'source');resolve(d,text);assert.deepEqual(d.source,source);d.source={...source,version:'3'};assert.throws(()=>resolve(d,text));resolveInactive(d,'source');d.operation='instant';assert.throws(()=>resolve(d,text));});
for(const seed of ['0','-1','900719925474099312345678901234567890'])test('lossless JSON seed '+seed,()=>{const d=fixture('generate');d.fields.seed=seed;const wire=bodyTemplate(resolve(d,text),text);assert(wire.endsWith('"seed":'+seed+'}'));assert(!wire.includes('"seed":"'));});
for(const seed of ['null','1.2','1e3','+3','01',' '])test('invalid exact seed '+seed,()=>{const d=fixture('generate');d.fields.seed=seed;assert.throws(()=>resolve(d,text));});
for(const edit of [d=>d.fields.count=null,d=>d.source=undefined,d=>d.prompt.text=null,d=>d.fields.strength=null,d=>d.fields.extra='invented',d=>d.json_prompt={}])test('null, omission and undeclared draft fields refuse',()=>{const d=fixture('generate');edit(d);assert.throws(()=>resolve(d,text));});
test('conversion approval binds exact source and target; originals stay intact',()=>{const d=fixture('transform');d.fields.size='custom';d.fields.width='1600';d.fields.height='896';assert.throws(()=>resolve(d,text),/CONVERSION_REQUIRED/);d.conversion={from:{width:1024,height:1024},to:{width:1600,height:896},mapping:'stretch',approved:true};resolve(d,text);d.fields.width='1616';assert.throws(()=>resolve(d,text),/CONVERSION_REQUIRED/);assert.equal(d.source.width,1024);});
for(const change of [d=>d.mask=null,d=>d.source=null,d=>d.mask.sourceHash=hash('other'),d=>d.mask.empty=true,d=>d.mask.full=true])test('independent mask/source invariant refuses',()=>{const d=fixture('inpaint');change(d);assert.throws(()=>resolve(d,text));});
test('full mask has explicit acknowledgement',()=>{const d=fixture('inpaint');d.mask.full=true;d.mask.fullAcknowledged=true;resolve(d,text);});
for(const change of [d=>d.adapters=[],d=>d.adapters.push({...adapters[0]}),d=>d.adapters[0].scale='4.1',d=>d.adapters[0].hash=hash('other')])test('adapter identity, count and scale never fall back',()=>{const d=fixture('generate-adapters');change(d);assert.throws(()=>resolve(d,text,eligible));});
test('production adapter registry denies otherwise valid adapter',()=>assert.throws(()=>resolve(fixture('generate-adapters'),text),/ADAPTER_UNAVAILABLE/));
test('locally eligible adapter requires a retained runtime acknowledgement when provider verification is absent',()=>{const d=fixture('generate-adapters'),unverified={adapters:new Map([['adapter-1',{hash:hash('weights'),available:true,profile:'v4-safe-1',runtimeVerified:false}]])},before=structuredClone(d);assert.throws(()=>resolve(d,text,unverified),/ADAPTER_RUNTIME_ACK_REQUIRED/);assert.deepEqual(d,before);d.adapters[0].runtimeAcknowledged=true;const r=resolve(d,text,unverified);assert.equal(r.adapters[0].runtimeAcknowledged,true);assert.deepEqual(JSON.parse(bodyTemplate(r,text)).loras,[{path:'asset:'+hash('weights'),scale:0}]);assert(!bodyTemplate(r,text).includes('runtimeAcknowledged'));});
test('plain None, raw and rewritten structured prompts need explicit disclosure acknowledgements',()=>{const d=fixture('generate');d.fields.expansion='None';assert.throws(()=>resolve(d,text),/GUIDANCE_ACK/);d.guidanceAcknowledged=true;resolve(d,text);d.prompt.mode='raw';d.guidanceAcknowledged=false;assert.throws(()=>resolve(d,text),/OPAQUE_ACK/);d.guidanceAcknowledged=true;d.fields.expansion='Medium';assert.throws(()=>resolve(d,text),/REWRITE_ACK/);d.rewriteAcknowledged=true;resolve(d,text);});
test('exact raw whitespace and escaping are preserved through one outer decode',()=>{const raw=' {"future":"Café\\n東京", "x":null} \n';const d=newDraft(ref(raw));d.prompt.mode='raw';d.guidanceAcknowledged=true;d.rewriteAcknowledged=true;assert.equal(JSON.parse(bodyTemplate(resolve(d,raw),raw)).prompt,raw);});
const api=await (await import('node:fs/promises')).readFile('docs/spec/api.md','utf8');
for(const [op,id]of Object.entries({generate:'A01',instant:'A09',fast:'A02',transform:'A03',inpaint:'A07','generate-adapters':'A10','transform-adapters':'A04','inpaint-adapters':'A08'}))test(op+' matches captured independent schema identity and full request allowlist',()=>{const section=api.split('### '+id+'. ')[1].split('\n### ')[0],schema=section.match(/Raw schema SHA-256 `([a-f0-9]{64})`/)[1];assert.equal(routes[op].schemaHash,'sha256:'+schema);assert.equal(section.split('\n')[0],routes[op].endpoint);const requestSection=section.split('**Request**')[1].split('**Response**')[0],fields=[...requestSection.matchAll(/^\| `([^`]+)` \| [RO] \|/gm)].map(x=>x[1]);const d=fixture(op);d.fields.seed='42';assert.deepEqual(Object.keys(JSON.parse(bodyTemplate(resolve(d,text,eligible),text))).sort(),fields.sort());});

test('equal-size translated source and document mask are not aligned',()=>{const d=fixture('inpaint');d.mask.frame.layer.transform=[1,0,0,1,1,0];assert.throws(()=>resolve(d,text),/MASK_FRAME_MISMATCH/);assert.equal(d.source.width,d.mask.width);assert.deepEqual(d.mask.frame.layer.transform,[1,0,0,1,1,0]);});
test('explicit retained grid translation matches original source coordinates without converting pixels',()=>{const d=fixture('inpaint');d.mask.frame.layer.transform=[1,0,0,1,7,-3];d.mask.frame.layer.mask={assetId:'mask',mapping:'retained-r16-v1',offsetX:7,offsetY:-3,width:1024,height:1024,outside:'zero',inverted:false};const alignment=maskAlignment(d.source,d.mask);assert.deepEqual(alignment.sourceToDocument,[1,0,0,1,7,-3]);assert.deepEqual(alignment.maskToDocument,[1,0,0,1,7,-3]);assert.throws(()=>resolve(d,text),/MASK_FRAME_REVIEW_REQUIRED/);d.mask.frame.alignment=alignment;d.mask.requestPlan=confirmRequestMask(d.source,d.mask,authored,effective,'retained-grid-review');resolve(d,text);});
test('explicit document source resolution ignores native layer translation but binds document grid',()=>{const d=fixture('inpaint');d.mask.frame.layer.transform=[1,0,0,1,1,0];d.source={...d.source,scope:'visible-document',assetId:'composite'};d.mask.frame.alignment=null;const a=maskAlignment(d.source,d.mask);assert.deepEqual(a.sourceToDocument,[1,0,0,1,0,0]);assert.deepEqual(a.maskToDocument,[1,0,0,1,0,0]);assert.throws(()=>resolve(d,text),/MASK_FRAME_REVIEW_REQUIRED/);d.mask.frame.alignment=a;d.mask.requestPlan=confirmRequestMask(d.source,d.mask,authored,effective,'document-grid-review');resolve(d,text);});
for(const change of [d=>delete d.mask.frame,d=>d.mask.frame.alignment=null,d=>d.mask.frame.alignment.sourceHash=hash('forged'),d=>d.mask.frame.layer.version='9',d=>d.mask.frame.layer.mask.assetId='other',d=>d.source.version='99'])test('missing or changed alignment approval cannot inherit authority',()=>{const d=fixture('inpaint');change(d);draftShape(d);assert.throws(()=>resolve(d,text),/MASK_FRAME/);});


test('legacy aligned mask remains recoverable but cannot inherit a fresh request plan',()=>{const d=fixture('inpaint');delete d.mask.requestPlan;const before=structuredClone(d);draftShape(d);assert.throws(()=>resolve(d,text),/MASK_PLAN_REVIEW_REQUIRED/);assert.deepEqual(d,before);d.mask.requestPlan=confirmRequestMask(d.source,d.mask,authored,effective,'renewed-mask-review');assert.equal(resolve(d,text).mask.requestPlan.approvalId,'renewed-mask-review');});
for(const change of ['source','mask-pixels','mask-manifest','mask-version'])test('request plan refuses changed '+change+' even after frame alignment is renewed',()=>{const d=fixture('inpaint');if(change==='source'){d.source.pixels={...d.source.pixels,hash:hash('replacement-source')};d.mask.sourceHash=d.source.pixels.hash;}if(change==='mask-pixels')d.mask.pixels={...d.mask.pixels,hash:hash('replacement-display')};if(change==='mask-manifest')d.mask.plan=ref('replacement-plan','application/json');if(change==='mask-version')d.mask.version='4';d.mask.frame.alignment=maskAlignment(d.source,d.mask);const before=structuredClone(d);draftShape(d);assert.throws(()=>resolve(d,text),/MASK_PLAN_REVIEW_REQUIRED/);assert.deepEqual(d,before);});
for(const size of ['square_hd','resized'])test('identity request plan refuses '+size+' output without silently changing mapping',()=>{const d=fixture('inpaint');if(size==='resized'){Object.assign(d.fields,{size:'custom',width:'512',height:'1024'});d.conversion={from:{width:1024,height:1024},to:{width:512,height:1024},mapping:'stretch',approved:true};}else d.fields.size=size;const before=structuredClone(d);assert.throws(()=>resolve(d,text),/MASK_MAPPING_REVIEW_REQUIRED/);assert.deepEqual(d,before);});
test('exact custom source dimensions retain the approved identity request plan',()=>{const d=fixture('inpaint');d.fields.size='custom';const r=resolve(d,text);assert.deepEqual(r.mask.requestPlan,d.mask.requestPlan);assert.deepEqual(r.size,{kind:'custom',width:1024,height:1024});assert.deepEqual(r.mask.requestPlan.authoredMask,authored);assert.deepEqual(r.mask.requestPlan.effectiveMask,effective);});

function independentFixture(scope='single-layer'){
 const d=fixture('inpaint');d.source={...d.source,scope,capture:ref('rendered-source-capture','application/json')};delete d.mask.frame;delete d.mask.requestPlan;d.mask.binding=bindRequestMask(d.source);d.mask.requestPlan=confirmRequestMask(d.source,d.mask,authored,effective,'independent-mask-review');return d;
}
for(const scope of ['single-layer','selected-layers','visible-document'])test('captured '+scope+' source supports a separate source-bound request mask',()=>{const d=independentFixture(scope),before=structuredClone(d),r=resolve(d,text);assert.equal(r.source.scope,scope);assert.deepEqual(r.source.capture,d.source.capture);assert.deepEqual(r.mask.binding,{kind:'request-mask-source-1',sourceIdentity:hash(canonical(d.source))});assert.equal(r.mask.frame,undefined);assert.deepEqual(requireMaskAlignment(d.source,d.mask).sourceToDocument,[1,0,0,1,0,0]);assert.deepEqual(d,before);assert(refs(d).some(value=>canonical(value)===canonical(d.source.capture)));});
for(const scope of ['single-layer','selected-layers'])test(scope+' cannot claim rendered source provenance without its retained capture',()=>{const d=independentFixture(scope);delete d.source.capture;assert.throws(()=>draftShape(d));});
test('independent mask binding requires a rendered capture and excludes a layer-mask frame',()=>{assert.throws(()=>bindRequestMask(source),/SOURCE_CAPTURE_REQUIRED/);const d=independentFixture();d.mask.frame=structuredClone(mask.frame);assert.throws(()=>draftShape(d));});
for(const field of ['assetId','version','capture','scope','documentRevision'])test('independent binding refuses changed source '+field+' even when pixels and dimensions are unchanged',()=>{const d=independentFixture();if(field==='capture')d.source.capture=ref('different-source-capture','application/json');else if(field==='scope')d.source.scope='selected-layers';else d.source[field]=field==='assetId'?'other-source':'99';const before=structuredClone(d);draftShape(d);assert.throws(()=>resolve(d,text),/MASK_FRAME_MISMATCH/);assert.deepEqual(d,before);assert.equal(d.source.pixels.hash,source.pixels.hash);});
test('independent binding cannot inherit a request-plan approval after explicit source rebinding',()=>{const d=independentFixture();d.source.version='99';d.mask.binding=bindRequestMask(d.source);assert.throws(()=>resolve(d,text),/MASK_PLAN_REVIEW_REQUIRED/);d.mask.requestPlan=confirmRequestMask(d.source,d.mask,authored,effective,'rebound-mask-review');assert.equal(resolve(d,text).mask.requestPlan.approvalId,'rebound-mask-review');});
for(const mapping of ['crop','scaled-padded'])test('independent mask uses explicit '+mapping+' request geometry without source mutation',()=>{const d=independentFixture(),crop=mapping==='crop'?{x:128,y:128,width:512,height:512}:{x:0,y:0,width:1024,height:1024},padding=mapping==='crop'?{left:0,top:0,right:0,bottom:0}:{left:16,top:16,right:16,bottom:16},requestGrid=mapping==='crop'?{width:512,height:512}:{width:528,height:528};d.mask.requestPlan=createRequestRasterPlan({document:{width:1024,height:1024},crop,padding,requestGrid,sourcePixels:d.source.pixels,authoredMask:authored,effectiveMask:effective,dependenciesHash:requestMaskDependencies(d.source,d.mask),resolution:'already-contained',approvalId:'mapped-mask-review'});Object.assign(d.fields,{size:'custom',width:String(requestGrid.width),height:String(requestGrid.height)});const before=structuredClone(d),r=resolve(d,text);assert.deepEqual(r.size,{kind:'custom',...requestGrid});assert.deepEqual(r.mask.requestPlan,d.mask.requestPlan);assert.equal(d.conversion,null);assert.deepEqual(d,before);d.fields.width=String(requestGrid.width+1);assert.throws(()=>resolve(d,text),/MASK_MAPPING_REVIEW_REQUIRED/);});

const maskAuthoringDraft=()=>({kind:'request-mask-authoring-1',shape:'polygon',combine:'subtract',x:'-',y:'NaN',width:'',height:'1e',polygon:'0,0\nunfinished',feather:'-0.5?',stroke:' 1,2\n3, ',brushSize:'twenty',brushHardness:'1..0',brushMode:'subtract',geometry:{x:'-',y:'',width:'0?',height:'2.5',left:'-1',top:'NaN',right:'Infinity',bottom:' '},importX:'?',importY:'001',importInverted:true});
test('raw request-mask authoring drafts retain unfinished numeric strings without changing the resolved request',()=>{const d=independentFixture(),request=resolve(d,text),references=refs(d);d.requestMaskDraft=maskAuthoringDraft();const before=structuredClone(d),roundtrip=JSON.parse(JSON.stringify(d));draftShape(roundtrip);assert.deepEqual(roundtrip,d);assert.deepEqual(resolve(d,text),request);assert.deepEqual(refs(d),references);assert.deepEqual(d,before);assert(!bodyTemplate(resolve(d,text),text).includes('requestMaskDraft'));});
for(const change of ['unknown-field','unknown-geometry','oversized-field','oversized-total'])test('request-mask authoring draft refuses '+change+' without repairing retained values',()=>{const d=independentFixture();d.requestMaskDraft=maskAuthoringDraft();if(change==='unknown-field')d.requestMaskDraft.extra='unrecognized';if(change==='unknown-geometry')d.requestMaskDraft.geometry.scale='2';if(change==='oversized-field')d.requestMaskDraft.polygon='x'.repeat(16385);if(change==='oversized-total')for(const field of ['polygon','stroke','width','height'])d.requestMaskDraft[field]='é'.repeat(9000);const before=structuredClone(d);assert.throws(()=>draftShape(d));assert.deepEqual(d,before);});
