import {ownFixtureCommands} from '../owned-command-fixture.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {RequestError,bindRequestMask} from '../../dist/local/src/request/core.js';
import {RequestRasterError,validateRequestRasterPlan} from '../../dist/local/src/request/raster-plan.js';
import {editModelsURL,requestEditsURL,comparisonURL,modelMemoryURL,allocationsURL,readOwnedJSON} from './edit-model-module.mjs';
const {RequestEditModels,REQUEST_EDIT_LIMITS}=await import(editModelsURL),{RequestEdits}=await import(requestEditsURL),{CandidateComparison}=await import(comparisonURL),{createOwnedModel,modelPayloadBytes}=await import(modelMemoryURL),{allocationLedger,ALLOCATION_LIMITS}=await import(allocationsURL);
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const flush=async()=>{for(let i=0;i<30;i++)await Promise.resolve();};
const totals=()=>{const s=allocationLedger.snapshot();return {cpu:s.cpuBytes,handles:s.handles,records:s.activeRecords};};
const candidate=(id='candidate',version='1')=>({id,version,documentId:'document',jobId:'job',attemptId:'attempt',requestId:'request',outputIndex:0,outputIdentity:'output',safety:'safe',state:'prepared',hidden:false,encodedAssetId:'encoded',preparedAssetId:'prepared',warning:null});
function fixture(draft){const doc={id:'document',revision:'1',width:4,height:4},root=createOwnedModel('edit-test-document',modelPayloadBytes(doc),()=>doc),host={updateComplete:Promise.resolve(),requestUpdate(){this.updateComplete=Promise.resolve();},querySelector(){return null;},isConnected:true};let route=async()=>{throw Error('Unexpected read');};const editor={view:{document:doc,ready:true,selected:[]},draftOwner:{},sessionId:'session',session:{identity:()=> 'identity',transport:(path,init)=>route(path,init)},pinViewModels(...values){assert(values.every(value=>!value||value===doc));return root.pin();},ownedJSON(path,owner,init,owns,maxBytes){return readOwnedJSON(this.session.transport,path,{owner,init,owns,maxBytes});},async command(){return [];},async open(){}};const errors=[],controller=new RequestEdits(host,ownFixtureCommands(editor),{draft:()=>draft,entryKey:()=>undefined,hold:()=>()=>{},mutate:()=>{throw Error('Unexpected draft mutation');},owns:()=>()=>true,error:error=>errors.push(error),changed:()=>host.requestUpdate()});return {host,editor,controller,errors,route(fn){route=fn;},async close(){await controller.dispose();root.release();}};}
function fieldInput(template,id){const slots=[];const expand=value=>value===null||value===undefined?'':Array.isArray(value)?value.map(expand).join(''):value?.strings?value.strings.reduce((all,text,i)=>all+text+(i<value.values.length?expand(value.values[i]):''),''):'__slot'+(slots.push(value)-1)+'__';const markup=expand(template),text=value=>value.replace(/__slot(\d+)__/g,(_,i)=>String(slots[Number(i)]));for(const [,attrs]of markup.matchAll(/<en-number-field\b([^>]*)>/g)){const target=/id=(?:"([^"]*)"|([^ >]+))/.exec(attrs);if(!target||text(target[1]??target[2])!==id)continue;const input=/@en-input=__slot(\d+)__/.exec(attrs);assert(input,'Actual number field input binding');return slots[Number(input[1])];}assert.fail('Rendered field '+id);}
function response(value){const text=JSON.stringify(value);return new Response(text,{headers:{'content-length':String(Buffer.byteLength(text))}});}

test('candidate index preparation admits a generator before publication and preserves prior index on refusal',async()=>{const before=totals(),f=fixture();try{f.controller.retainCandidates([candidate()]);const prior=f.controller.candidates;const token=f.controller.prepareCandidates((function*(){yield candidate('next');})());assert.equal(f.controller.candidates,prior);token.release();assert.equal(f.controller.candidates,prior);assert.throws(()=>f.controller.prepareCandidates((function*(){for(let n=0;n<=REQUEST_EDIT_LIMITS.candidates;n++)yield candidate('c'+n);})()),/CANDIDATE_LIMIT/);assert.equal(f.controller.candidates,prior);assert.equal(prior.get('candidate').id,'candidate');}finally{await f.close();}assert.deepEqual(totals(),before);});

test('candidate pruning retires complete inspection metadata only after its actual host commit',async()=>{const before=totals(),f=fixture(),commit=deferred();try{f.controller.retainCandidates([candidate()]);await flush();const value={candidate:f.controller.candidates.get('candidate'),asset:{note:'retained asset'},raster:null,sourceURL:'',candidateURL:'',maskURL:'',actualApproved:false,clipActual:false};f.controller.retain('inspection:candidate',value);f.controller.inspections.set('candidate',value);const held=totals();f.host.requestUpdate=()=>{f.host.updateComplete=commit.promise;};f.controller.retainCandidates([]);assert.equal(f.controller.inspections.size,0);await flush();assert(totals().cpu>=held.cpu);commit.resolve();await flush();assert(totals().cpu<held.cpu);}finally{commit.resolve();await f.close();}assert.deepEqual(totals(),before);});

test('parsed JSON remains admitted through the consumer handoff and keeps document release pending',async()=>{const before=totals(),f=fixture();try{f.route(async()=>response({review:{name:'owned response'}}));const op=f.controller.models.operation(),value=await op.read('/review',()=>true);let done=false;const closing=f.controller.dispose().then(()=>{done=true;});await flush();assert.equal(done,false);assert.equal(value.review.name,'owned response');assert(totals().cpu>before.cpu);op.release();await closing;assert.equal(done,true);}finally{await f.close();}assert.deepEqual(totals(),before);});

test('native body cancellation is drained before a read operation refunds its response and path owners',async()=>{const before=totals(),f=fixture(),read=deferred(),cancel=deferred();try{f.route(async()=>new Response(new ReadableStream({pull(){read.resolve();},cancel(){return cancel.promise;}}),{headers:{'content-length':'32'}}));const op=f.controller.models.operation(),pending=op.read('/slow-review',()=>true).catch(error=>error).finally(()=>op.release());await read.promise;let done=false;const closing=f.controller.dispose().then(()=>{done=true;});await flush();assert.equal(done,false);assert(f.controller.models.lifecycle.operations>0);cancel.resolve();await pending;await closing;assert.equal(done,true);}finally{cancel.resolve();await f.close();}assert.deepEqual(totals(),before);});

test('refused retained review leaves the complete prior review and current model intact',async()=>{const before=totals(),f=fixture();let pressure;try{const prior={name:'prior complete review',layers:[{name:'kept'}]};f.controller.retain('placement:candidate',prior);await flush();const modelCount=f.controller.models.lifecycle.models,used=allocationLedger.snapshot().cpuBytes;pressure=allocationLedger.reserve({owner:'edit-test-pressure',kind:'control',cpuBytes:ALLOCATION_LIMITS.cpuBytes-ALLOCATION_LIMITS.textPartitionBytes-used});assert.throws(()=>f.controller.retain('placement:candidate',{name:'replacement refused'}),/ALLOCATION_BUDGET/);assert.equal(f.controller.models.lifecycle.models,modelCount);pressure.release();pressure=null;f.controller.retain('placement:candidate',{name:'replacement accepted'});await flush();}finally{pressure?.release();await f.close();}assert.deepEqual(totals(),before);});

test('new document opening transfers its scalar owner and can release the originating controller without a cycle',async()=>{const before=totals(),f=fixture(),opened=deferred();try{f.editor.open=async id=>{assert.equal(id,'new-document');await f.controller.dispose();opened.resolve();};const op=f.controller.models.operation();f.controller.openAfterAction('new-document');await flush();op.release();await opened.promise;await flush();}finally{await f.close();}assert.deepEqual(totals(),before);});

test('comparison refusal restores an oversized reveal field and old state survives a failed replacement commit',async()=>{const before=totals(),f=fixture(),comparison=new CandidateComparison(f.host);try{const input={sourceURL:'blob:a',preparedURL:'blob:b',beforeURL:'blob:c',afterURL:'blob:d',width:4,height:4,documentWidth:4,documentHeight:4,placement:'current-document',newDocSameGrid:true};const template=comparison.render('candidate',input,()=>true);await flush();const retained=comparison.states.get('candidate'),state=retained.source??retained.pairs.source,control={isConnected:true,value:'9'.repeat(129)},event={currentTarget:control,composedPath:()=>[control],defaultPrevented:false};fieldInput(template,'candidate-comparison-candidate-source-reveal')(event);await flush();assert.equal(control.value,'50');assert.equal(state.value,'50');assert.match(state.error,/percentage|previous value/);const update=f.host.requestUpdate;f.host.requestUpdate=()=>{f.host.updateComplete=Promise.reject(Error('COMMIT_FAILED'));void f.host.updateComplete.catch(()=>{});};await assert.rejects(comparison.dispose(),/COMPARISON_RELEASE/);assert(comparison.lifecycle.retired>0);f.host.requestUpdate=update;await comparison.dispose();}finally{await comparison.dispose();await f.close();}assert.deepEqual(totals(),before);});

test('candidate commit performs no admission or synchronous host notification after preparation',async()=>{const before=totals(),f=fixture();let pressure;const update=f.host.requestUpdate;try{f.controller.retainCandidates([candidate()]);await flush();const prepared=f.controller.prepareCandidates([candidate('next')]),used=allocationLedger.snapshot().cpuBytes;pressure=allocationLedger.reserve({owner:'edit-test-pressure',kind:'control',cpuBytes:ALLOCATION_LIMITS.cpuBytes-ALLOCATION_LIMITS.textPartitionBytes-used});f.host.requestUpdate=()=>{throw Error('HOST_COMMIT_FAILED');};assert.doesNotThrow(()=>prepared.commit());assert.equal(f.controller.candidates.get('next').id,'next');assert.equal(f.controller.candidates.has('candidate'),false);await flush();pressure.release();pressure=null;f.host.requestUpdate=update;}finally{pressure?.release();f.host.requestUpdate=update;await f.close();}assert.deepEqual(totals(),before);});

test('URL cleanup failure still drains every sibling before returning and retains the failed native URL for retry',async()=>{const before=totals(),f=fixture(),slow=deferred(),started=deferred(),revoked=[];let fail=true,settled=false;globalThis.__requestEditRevoke=url=>{if(url==='blob:first'&&fail)throw Error('NATIVE_REVOKE_FAILED');revoked.push(url);};try{const op=f.controller.models.operation();f.controller.url=async id=>id==='first'?'blob:first':slow.promise;const pending=f.controller.previewURLs(op,()=>true,async acquire=>{await acquire('first');void acquire('slow').catch(()=>{});started.resolve();throw Error('LOAD_FAILED');}).then(()=>assert.fail('Expected failed preview'),error=>{assert.match(error.message,/PREVIEW_RELEASE/);}).finally(()=>{settled=true;op.release();});await started.promise;await flush();assert.equal(settled,false);assert(f.controller.cleanupURLs.has('blob:first'));assert(f.controller.models.lifecycle.operations>0);slow.resolve('blob:slow');await pending;assert.equal(settled,true);assert(revoked.includes('blob:slow'));fail=false;await f.controller.dispose();assert.equal(f.controller.cleanupURLs.size,0);assert(revoked.includes('blob:first'));}finally{fail=false;slow.resolve('blob:slow');await f.close();delete globalThis.__requestEditRevoke;}assert.deepEqual(totals(),before);});

test('a reused server review ID cannot resolve a superseded local adoption callback',async()=>{const before=totals(),f=fixture();try{const old={token:1,review:{reviewId:'same-server-id'}},next={token:2,review:{reviewId:'same-server-id'}};f.controller.retain('placement:candidate',old);f.controller.placementReviews.set('candidate',old);assert.equal(f.controller.currentPlacement('candidate',1),old);f.controller.retain('placement:candidate',next);f.controller.placementReviews.set('candidate',next);assert.throws(()=>f.controller.currentPlacement('candidate',1),/current, unexpired placement review/);assert.equal(f.controller.currentPlacement('candidate',2),next);f.controller.placementReviews.clear();}finally{await f.close();}assert.deepEqual(totals(),before);});

test('a canceled encoded owner remains admitted while its old placement view is pinned or awaiting Lit retirement',async()=>{const before=totals(),f=fixture(),commit=deferred();try{const owner={candidateId:'candidate',preparing:false,cancelRequested:true};owner.payload=f.controller.models.prepare(owner,{candidateId:owner.candidateId,commandId:'review-command'});const view={encodedOwner:owner,review:{reviewId:'encoded-review'}};f.controller.retain('placement:candidate',view);await flush();const held=f.controller.models.hold(),charged=totals().cpu;f.controller.releaseEncodedOwner(owner);assert.equal(owner.payload,undefined);assert.equal(totals().cpu,charged,'Native base release transfers ownership to the retained view pin');f.host.requestUpdate=()=>{f.host.updateComplete=commit.promise;};f.controller.models.clear('placement:candidate');await flush();assert.equal(totals().cpu,charged);commit.resolve();await flush();assert.equal(totals().cpu,charged,'Active action still owns the old view');held();await flush();assert(totals().cpu<charged);f.host.requestUpdate=()=>{f.host.updateComplete=Promise.resolve();};}finally{commit.resolve();await f.close();}assert.deepEqual(totals(),before);});

test('a command owner arriving after release stays tracked until its stale consumer and root cleanup finish',async()=>{const before=totals(),f=fixture(),arrived=deferred();try{const events=[{type:'AssetRegistered',payload:{asset:{id:'retained-command-asset'}}}],owner=createOwnedModel('edit-test-command',modelPayloadBytes(events),()=>events);f.editor.ownedCommand=()=>arrived.promise;const op=f.controller.models.operation(),result=op.command({type:'SaveCheckpoint',name:'test'},null).catch(error=>error);await flush();op.release();let finished=false;const closing=f.controller.dispose().then(()=>{finished=true;});await flush();assert.equal(finished,false);assert(f.controller.models.lifecycle.operations>0);arrived.resolve(owner);assert.equal((await result).name,'AbortError');await closing;assert.equal(finished,true);}finally{await f.close();}assert.deepEqual(totals(),before);});

test('owned command events remain the actual returned root through asynchronous consumer work',async()=>{const before=totals(),f=fixture();try{const events=[{type:'AssetRegistered',payload:{asset:{id:'owned-command-asset'}}}],owner=createOwnedModel('edit-test-command',modelPayloadBytes(events),()=>events);let released=false;f.editor.ownedCommand=async()=>({value:owner.value,pin:()=>owner.pin(),release(){released=true;owner.release();}});const op=f.controller.models.operation(),received=await op.command({type:'SaveCheckpoint',name:'test'},null);assert.equal(received,events);await flush();assert.equal(released,false);op.release();assert.equal(released,true);}finally{await f.close();}assert.deepEqual(totals(),before);});

test('owned upload forwards release abort and retains a late staging result through completion',async()=>{const before=totals(),f=fixture(),arrived=deferred();let signal;try{f.editor.ownedUpload=(_file,_purpose,_type,_existing,_current,external)=>{signal=external;return arrived.promise;};const stage={protocolVersion:1,stagingId:'stage',purpose:'image',expectedBytes:'1',sha256:'sha256:'+'1'.repeat(64),mediaType:'image/png'},owner=createOwnedModel('edit-test-stage',modelPayloadBytes(stage),()=>stage),op=f.controller.models.operation(),pending=op.upload(new Blob(['x']),'image','image/png',undefined,()=>true).catch(error=>error);await flush();op.release();assert.equal(signal.aborted,true,'Explicit operation release aborts its owned upload');let done=false;const closing=f.controller.dispose().then(()=>{done=true;});await flush();assert.equal(signal.aborted,true);assert.equal(done,false);arrived.resolve(owner);assert.equal((await pending).name,'AbortError');op.release();await closing;assert.equal(done,true);}finally{await f.close();}assert.deepEqual(totals(),before);});

test('encoded cancellation releases the actual owned result after its acknowledgement consumer',async()=>{const before=totals(),f=fixture();try{const response={protocolVersion:1,commandId:'review-command',status:'canceled'},result=createOwnedModel('edit-test-cancel',modelPayloadBytes(response),()=>response);let released=false;f.editor.ownedCancelCandidateReview=async()=>({value:result.value,pin:()=>result.pin(),release(){released=true;result.release();}});const owner=f.controller.ownEncodedReview('candidate',()=>true);owner.commandId='review-command';owner.preparing=false;f.controller.cancelEncodedReview(owner);await owner.canceling;assert.equal(released,true);assert.equal(owner.payload,undefined);assert.equal(f.controller.failedEncoded.size,0);}finally{await f.close();}assert.deepEqual(totals(),before);});

function transportDraft(){
 const ref=(number,mediaType='application/json',byteLength='32')=>({hash:'sha256:'+number.toString(16).padStart(64,'0'),byteLength,mediaType});
 const source={assetId:'source',version:'1',blob:ref(1,'image/png'),pixels:ref(2,'application/x-ideogram-rgba8','64'),width:4,height:4,scope:'single-layer',documentRevision:'1',capture:ref(3)};
 const mask={assetId:'mask',version:'1',blob:ref(4,'image/png'),pixels:ref(5,'application/x-ideogram-rgba8','64'),width:4,height:4,sourceHash:source.pixels.hash,polarity:'white-edit',empty:false,full:false,fullAcknowledged:false,plan:ref(6),binding:bindRequestMask(source)};
 const draft={operation:'inpaint-v45',source,mask,fields:{size:'auto',width:'128',height:'128'}},manifest={plan:{hard:ref(7,'application/x-ideogram-r16le','32'),effective:ref(8,'application/x-ideogram-r16le','32')}};
 return {draft,manifest};
}

test('actual masked mapping classifies only invalid prepared grid axes without changing raw source or coverage',async()=>{
 const before=totals(),{draft,manifest}=transportDraft(),f=fixture(draft);f.controller.geometry={x:'0',y:'0',width:'4',height:'4',left:'0',top:'0',right:'0',bottom:'0'};
 try{
  // NaN/Infinity are persisted/controller strings, not spellings accepted by native number typing.
  for(const [width,height,fields] of [['','128',['width']],['NaN','128',['width']],['Infinity','128',['width']],['128.5','128',['width']],['-1','128',['width']],['0','128',['width']],['8193','128',['width']],['9007199254740992','128',['width']],['128','',['height']],['','Infinity',['width','height']],['5001','5000',['width','height']]]){
   draft.fields.width=width;draft.fields.height=height;const saved=structuredClone(draft);
   assert.throws(()=>f.controller.mappingPlan(draft.mask,manifest,'already-contained'),error=>{assert(error instanceof RequestError);assert.deepEqual(error.issues.map(issue=>issue.field),fields);assert(error.issues.every(issue=>issue.code==='REQUEST_GRID_SIZE'));return true;});assert.deepEqual(draft,saved);
  }
  // Saved Number-compatible spellings were already accepted by whole(); retain that grammar.
  for(const width of ['128','128.0','1.28e2','+128','0x80',' 128 ']){draft.fields.width=width;draft.fields.height='128';const plan=f.controller.mappingPlan(draft.mask,manifest,'already-contained');validateRequestRasterPlan(plan);assert.deepEqual(plan.requestGrid,{width:128,height:128});assert.deepEqual(plan.expectedOutput,plan.requestGrid);assert.deepEqual(plan.sourcePixels,draft.source.pixels);assert.deepEqual(plan.authoredMask,manifest.plan.hard);assert.deepEqual(plan.effectiveMask,manifest.plan.effective);assert.equal(draft.fields.width,width);}
  for(const [width,height] of [['8192','1'],['5000','5000']]){draft.fields.width=width;draft.fields.height=height;assert.deepEqual(f.controller.mappingPlan(draft.mask,manifest,'already-contained').requestGrid,{width:Number(width),height:Number(height)});}
  draft.fields.width=draft.fields.height='128';f.controller.geometry.width='0';assert.throws(()=>f.controller.mappingPlan(draft.mask,manifest,'already-contained'),error=>error instanceof RequestRasterError&&error.code==='MASK_MAPPING_REVIEW_REQUIRED');f.controller.geometry.width='4';
  f.controller.geometry.left='8193';assert.throws(()=>f.controller.mappingPlan(draft.mask,manifest,'already-contained'),error=>error instanceof RequestRasterError&&error.code==='REQUEST_RASTER_EXTENT');f.controller.geometry.left='0';
  draft.source.width=8193;assert.throws(()=>f.controller.mappingPlan(draft.mask,manifest,'already-contained'),error=>error instanceof RequestRasterError&&error.code==='REQUEST_RASTER_EXTENT');draft.source.width=4;
  draft.operation='inpaint';draft.fields.size='custom';draft.fields.width='';assert.throws(()=>f.controller.mappingPlan(draft.mask,manifest,'already-contained'),error=>!(error instanceof RequestError)&&/finite Request width/.test(error.message));
 }finally{await f.close();}assert.deepEqual(totals(),before);
});
