// Source-only authored fixture. Run after the effective V45 family is built.
// REQUEST_COMBINED_ROOT selects this overlay; otherwise use promoted source.
import {allocationsURL as allocationURL,promptMemoryURL as promptURL,compositionObservationsURL} from '../owned-preview-module.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {transformWithOxc} from 'vite';
const root=process.env.REQUEST_COMBINED_ROOT??'.',requestRoot=process.env.REQUEST_PROMPT_ROOT??root,data=code=>'data:text/javascript;base64,'+Buffer.from(code).toString('base64');
async function source(path,imports={}){const original=await readFile(path,'utf8');let code=(await transformWithOxc(original,path)).code;for(const [name,url]of Object.entries(imports))code=code.replaceAll(JSON.stringify(name),JSON.stringify(url)).replaceAll("'"+name+"'",JSON.stringify(url));return data(code+'\n//# sourceURL=ideogram-request-entry-fixture/'+path+'?sha256='+createHash('sha256').update(original).digest('hex')+'\n');}
const modelURL=await source('src/observability/model-memory.ts',{'./allocations.js':allocationURL,'./prompt-memory.js':promptURL});
async function stateSource(name,imports){for(const stateRoot of [process.env.IE_DRAFT_METADATA_SOURCE_ROOT,process.env.CLIENT_CONTROL_ROOT,'.'].filter(Boolean)){try{return await source(stateRoot+'/src/state/'+name+'.ts',imports);}catch(error){if(error.code!=='ENOENT')throw error;}}throw Error('Missing effective draft source '+name);}
const stateImports={'../observability/allocations.js':allocationURL,'../observability/prompt-memory.js':promptURL,'../observability/model-memory.js':modelURL};
const controlURL=await stateSource('control-memory',stateImports);
const commandURL=await stateSource('command-results',{...stateImports,'./control-memory.js':controlURL,...Object.fromEntries(['protocol/json','protocol/sha256','protocol/validate'].map(name=>['../'+name+'.js',pathToFileURL(resolve('dist/local/src/'+name+'.js')).href]))});
const draftValuesURL=await stateSource('draft-values',{...stateImports,'./control-memory.js':controlURL});
const persistenceURL=await stateSource('draft-persistence',{...stateImports,'./control-memory.js':controlURL,'./command-results.js':commandURL,'./draft-values.js':draftValuesURL});
const compositionViewURL=await source('src/composition/view.ts');
const compositionURL=await source('src/composition/core.ts'),compositionMemoryURL=await source('src/composition/memory.ts',{'./view.js':compositionViewURL,'./core.js':compositionURL,'../observability/allocations.js':allocationURL,'../observability/prompt-memory.js':promptURL,'../observability/composition-observations.js':compositionObservationsURL});
const entryURL=await source(root+'/src/ui/request-entry-memory.ts',{'../observability/model-memory.js':modelURL,'../observability/prompt-memory.js':promptURL});
const ownerURL=await source((process.env.UI_MODEL_ROOT??'.')+'/src/ui/model-owner.ts',{'../observability/model-memory.js':modelURL,'../observability/prompt-memory.js':promptURL});
const navigationURL=await source(root+'/src/ui/request-navigation-memory.ts',{'../observability/model-memory.js':modelURL,'./model-owner.js':ownerURL});
const promptInputURL=await source(requestRoot+'/src/ui/request-prompt-memory.ts',{'../observability/prompt-memory.js':promptURL,'../observability/allocations.js':allocationURL});
const lit=data('export const nothing=null;export const noChange=Symbol.for("lit-noChange");export const html=(strings,...values)=>({strings,values});');
const children=data(`export class AdapterLibraryEditing{dispose(){}render(){return null;}async eligibility(){return {adapters:new Map()};}}export class RequestEdits{constructor(host,editor,hooks){this.hooks=hooks;}dispose(){}async sync(){}retainCandidates(){}prepareCandidates(){return {commit(){},release(){}};}renderSourceMask(){return null;}renderCandidate(){return null;}}export class V45EditInputsEditing{constructor(host,editor,hooks){this.hooks=hooks;}dispose(){}render(){return null;}}export class TextTreatmentEditing{dispose(){}async drain(){}intent(){return undefined;}render(){return null;}}export class ReturnedDescriptionEditing{async releaseDocument(){}render(){return null;}}export const renderV45EditSettings=()=>null,renderV45EditReview=()=>null;`);
const display=data('export const displayImage=value=>value;export function revokeDisplayPreviewURL(){}export function displayPreviewInfo(){return null;}export async function readDisplaySource(){throw Error("unused display read");}export const withDisplaySource=readDisplaySource;export async function createDisplayPreviewURL(){throw Error("unused display preview");}export async function validateDisplayImage(){throw Error("unused display validation");}');
const v45=data('export const renderV45Generation=()=>null,renderV45GenerationReview=()=>null,renderV45UnavailableResultMetadata=()=>null,renderRequestEstimate=()=>null;');
const compiled=name=>pathToFileURL(resolve('dist/local/src/'+name+'.js')).href;
const compositionTextImports={'lit':lit,'../composition/text-export.js':compiled('composition/text-export'),'../protocol/json.js':compiled('protocol/json'),'../observability/model-memory.js':modelURL,'../observability/prompt-memory.js':promptURL};
// Historical partial request overlays may omit this newly introduced helper.
const compositionTextURL=await source(requestRoot+'/src/ui/request-composition-text.ts',compositionTextImports).catch(error=>{if(error.code!=='ENOENT')throw error;return source('src/ui/request-composition-text.ts',compositionTextImports);});
const keyboardScopeURL=await source(requestRoot+'/src/ui/keyboard-scope.ts').catch(error=>{if(error.code!=='ENOENT')throw error;return source('src/ui/keyboard-scope.ts');});
const controllerURL=await source(requestRoot+'/src/ui/request.ts',{'lit':lit,'lit/directives/repeat.js':data('export const repeat=(items,key,render)=>Array.from(items,render);'),'./adapters.js':await source('src/ui/adapters.ts'),'./display-image.js':display,'../observability/display-preview.js':display,'../observability/prompt-memory.js':promptURL,'../observability/model-memory.js':modelURL,'./request-entry-memory.js':entryURL,'./request-prompt-memory.js':promptInputURL,'./request-navigation-memory.js':navigationURL,'./request-composition-text.js':compositionTextURL,'./keyboard-scope.js':keyboardScopeURL,'./adapter-library.js':children,'./request-edits.js':children,'./request-v45-edit.js':children,'./request-v45.js':v45,'./text-treatment.js':children,'./returned-description.js':children,'../protocol/asset-projection.js':compiled('protocol/asset-projection'),'../composition/core.js':compositionURL,'../composition/memory.js':compositionMemoryURL,'../protocol/json.js':compiled('protocol/json'),'../request/core.js':compiled('request/core'),'../request/family.js':compiled('request/family')});
const {navigationHistory}=await import(navigationURL);
const {RequestEditing}=await import(controllerURL),{allocationLedger,ALLOCATION_LIMITS}=await import(allocationURL),{readOwnedJSON,modelPayloadBytes}=await import(modelURL),{DraftPersistence}=await import(persistenceURL),{PromptReaderCleanupError}=await import(promptURL),{ownRequestEntry}=await import(entryURL),{newDraft,hash}=await import(compiled('request/core')),{newV45EditDraft}=await import(compiled('request/family')),{emptyComposition,serialize}=await import(compositionURL);
const flush=async()=>{for(let n=0;n<100;n++)await Promise.resolve();},turn=()=>new Promise(resolve=>setTimeout(resolve,5));
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const ref=text=>({hash:hash(text),byteLength:String(new TextEncoder().encode(text).byteLength),mediaType:'text/plain'});
const response=value=>{const text=JSON.stringify(value);return new Response(text,{headers:{'content-length':String(new TextEncoder().encode(text).byteLength)}});};
const event=(id,value='',currentTarget={id,value,isConnected:true})=>{currentTarget.value=value;return {currentTarget,composedPath:()=>[currentTarget],defaultPrevented:false,preventDefault(){this.defaultPrevented=true;}};};
function field(template,id){if(!template||typeof template!=='object')return null;if(template.strings){const at=template.strings.findIndex(s=>s.includes('id="'+id+'"'));if(at>=0){const end=template.strings.findIndex((s,i)=>i>at&&s.includes('</en-'));return template.values.slice(at,end<0?undefined:end).find(value=>typeof value==='function');}}for(const value of Array.isArray(template)?template:template.values??[]){const found=field(value,id);if(found)return found;}return null;}
function renderedPromptValue(template){if(!template||typeof template!=='object')return undefined;if(template.strings?.some(text=>text.includes('<en-textarea id="prompt"')))return template.values[1];for(const value of Array.isArray(template)?template:template.values??[]){const found=renderedPromptValue(value);if(found!==undefined)return found;}}
function fixture(){let uiPins=0,instance,route=async()=>{throw Error('Unexpected transport');},rendered,native={id:'prompt',value:'',isConnected:false,updateComplete:Promise.resolve()};const owners=[],saved=[],reads=[];const editor={sessionId:'session',view:{ready:true,document:{id:'old',revision:'1',width:512,height:512},image:{layers:[]},selected:[]},session:{identity:()=> 'client',transport(path,init){reads.push(path);return path.endsWith('/request-reviews')?Promise.resolve(response({items:[]})):route(path,init);}},ui:{drafts:[]},registerDraft(id,documentId){if(!this.draftOwner||this.view.document?.id!==documentId)throw Error('DRAFT_OWNER_CHANGED');return this.draftOwner.registerDraft(id,documentId);},pinUI(){uiPins++;let held=true;return ()=>{assert(held,'UI checkpoint pin released twice');held=false;uiPins--;};},async json(){return {items:[]};},ownedJSON(path,owner,init,owns,maxBytes,kind){return readOwnedJSON(this.session.transport.bind(this.session),path,{owner,init,owns,maxBytes,kind});},changeDraft(id,kind,text,targetLayerId,composing,expectedDocumentRevision){this.draftOwner.change({id,kind,text,targetLayerId,composing,expectedDocumentRevision,documentId:this.view.document.id});saved.push({id,text});},async flushDrafts(){for(const draft of this.draftOwner.drafts.values())draft.savedGeneration=draft.generation;}};
 const owner=()=>{const value=new DraftPersistence('session',editor.session.transport.bind(editor.session),()=> 'csrf');value.checkpoint={drafts:[],uiSeq:'1'};owners.push(value);return value;};editor.draftOwner=owner();
 // Mirror the rendered prompt with one native node until its control is removed.
 const host={requestUpdate(){this.updateComplete=Promise.resolve().then(()=>{rendered=instance.render();const value=renderedPromptValue(rendered);if(value!==undefined){if(!native.isConnected)native={id:'prompt',value:'',isConnected:true,updateComplete:Promise.resolve()};if(typeof value==='string')native.value=value;}else native.isConnected=false;});},updateComplete:Promise.resolve(),querySelector(selector){return selector==='#prompt'&&native.isConnected?native:null;}};instance=new RequestEditing(host,editor);
 return {instance,editor,host,saved,reads,owner,promptEvent(value){assert(native.isConnected,'Prompt event requires its mounted control');return event('prompt',value,native);},route(value){route=value;},template:()=>rendered,async initial(){await instance.sync();await flush();},async close(){await instance.dispose();for(const value of owners)await value.dispose();await flush();assert.equal(uiPins,0,'Every checkpoint restoration pin released');}};
}
const pressure=available=>allocationLedger.reserve({owner:'request-entry-test-pressure',kind:'prompt',cpuBytes:ALLOCATION_LIMITS.promptBytes-allocationLedger.snapshot().promptBytes-available});
const sameUsage=(a,b)=>{for(const key of ['cpuBytes','promptBytes','activeRecords','handles'])assert.equal(a[key],b[key],key);};

test('metadata-heavy operation fork refuses before clone and preserves exact Entry and selection',async()=>{const baseline=allocationLedger.snapshot(),f=fixture();let block;const clone=globalThis.structuredClone;try{await f.initial();f.instance.mutateEntry('p'.repeat(16000),next=>{next.draft.requestMaskDraft={kind:'request-mask-authoring-1',shape:'polygon',combine:'replace',x:'0',y:'0',width:'1',height:'1',polygon:'0,0 '.repeat(4000),feather:'0',stroke:'',brushSize:'1',brushHardness:'1',brushMode:'add',geometry:{x:'0',y:'0',width:'1',height:'1',left:'0',top:'0',right:'0',bottom:'0'},importX:'0',importY:'0',importInverted:false};});await flush();const prior=f.instance.entry(),used=allocationLedger.snapshot();assert(modelPayloadBytes(prior)>30000);block=pressure(0);let clones=0;globalThis.structuredClone=(...args)=>{clones++;return clone(...args);};assert.throws(()=>f.instance.operationChanged('Generate with Fast'),/PROMPT_MEMORY_BUDGET/);assert.equal(clones,0);assert.equal(f.instance.entry(),prior);assert.equal(f.instance.op,'generate');assert.equal(f.instance.entries.size,1);globalThis.structuredClone=clone;block.release();block=null;sameUsage(allocationLedger.snapshot(),used);}finally{globalThis.structuredClone=clone;block?.release();await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

for(const operation of ['field','mode','save'])test(operation+' admission refusal retains current root, IDs, prompt and serialized generation',async()=>{const baseline=allocationLedger.snapshot(),f=fixture();let block;try{await f.initial();f.instance.mutateEntry('old',next=>{next.text='old';});await flush();const prior=f.instance.entry(),saved=f.saved.length,used=allocationLedger.snapshot(),priorRow=f.editor.draftOwner.drafts.get(prior.id),generation=priorRow.generation,savedGeneration=priorRow.savedGeneration;block=pressure(0);
 if(operation==='field'){const callback=field(f.instance.render(),'prompt'),e=f.promptEvent('new');assert(callback);callback(e);await flush();assert.equal(e.currentTarget.value,'new');assert.equal(renderedPromptValue(f.template()),'new');assert.equal(f.instance.promptInput.refused,true);assert.equal(f.editor.draftOwner.hasRefusedChanges,true);assert.match(JSON.stringify(f.template()),/previous saved draft is retained/);}
 else assert.throws(()=>operation==='mode'?f.instance.modeChanged('raw'):f.instance.save(),/PROMPT_MEMORY_BUDGET/);
 assert.equal(f.instance.entry(),prior);assert.equal(f.instance.mode,'plain');assert.equal(f.saved.length,saved);assert.equal(f.editor.draftOwner.drafts.get(prior.id),priorRow);assert.equal(priorRow.generation,generation);assert.equal(priorRow.savedGeneration,savedGeneration);block.release();block=null;await flush();
 if(operation==='field'){const retry=field(f.instance.render(),'prompt');assert(retry);retry(f.promptEvent('new'));await flush();assert.equal(f.instance.entry().text,'new');assert.equal(JSON.parse(f.saved.at(-1).text).text,'new');assert.equal(f.instance.promptInput.refused,false);assert.equal(f.editor.draftOwner.hasRefusedChanges,false);assert.equal(prior.text,'old');}
 sameUsage(allocationLedger.snapshot(),used);
 }finally{block?.release();await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

test('serialization is pre-admitted after prospective clone and never replaces prior on refusal',async()=>{const baseline=allocationLedger.snapshot(),f=fixture();let block;const stringify=JSON.stringify;try{await f.initial();const text='\0'.repeat(10000);f.instance.mutateEntry(text,next=>next.text=text);await flush();const prior=f.instance.entry(),saved=f.saved.length;block=pressure(65000);let serializations=0;JSON.stringify=(...args)=>{serializations++;return stringify(...args);};assert.throws(()=>f.instance.save(),/PROMPT_MEMORY_BUDGET/);assert.equal(serializations,0);assert.equal(f.instance.entry(),prior);assert.equal(f.saved.length,saved);}finally{JSON.stringify=stringify;block?.release();await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

test('immutable helper mutation keeps stable Entry identity and returns independently owned V45 successor',async()=>{const baseline=allocationLedger.snapshot(),f=fixture();try{await f.initial();f.instance.operationChanged('Transform with Ideogram v4.5');assert.equal(f.instance.op,'transform-v45');await flush();const prior=f.instance.entry(),key=f.instance.requestEdits.hooks.entryKey(),held=f.instance.holdEntry(prior.draft);const next=f.instance.mutateV45Draft(prior.draft,'2',draft=>draft.fields.count='2');assert.notEqual(next,prior.draft);assert.equal(prior.draft.fields.count,'1');assert.equal(next.fields.count,'2');assert.equal(f.instance.entry().id,prior.id);assert.equal(f.instance.requestEdits.hooks.entryKey(),key);held();await flush();}finally{await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

test('failed successor recovery keeps old roots and ownership, then retries the same successor',async()=>{const baseline=allocationLedger.snapshot(),f=fixture();try{await f.initial();const prior=f.instance.entry(),oldOwner=f.instance.owner,oldId=f.instance.documentId,predicate=f.instance.owns(false);f.editor.view.document={...f.editor.view.document,id:'next'};f.editor.draftOwner=f.owner();const first=newDraft(ref('one')),second=newDraft(ref('two'));second.operation='fast';f.editor.ui.drafts=[{kind:'request',id:'one',documentId:'next',generation:'1',expectedDocumentRevision:'1'},{kind:'request',id:'two',documentId:'next',generation:'1',expectedDocumentRevision:'1'}];let fail=true;f.route(async path=>{if(path.includes('draftId=one'))return path.includes('content=1')?new Response('one',{headers:{'content-length':'3'}}):response({value:first});if(path.includes('draftId=two')){if(path.includes('content=1'))return new Response(fail?'t':'two',{headers:{'content-length':fail?'1':'3'}});return response({value:second});}throw Error(path);});await assert.rejects(f.instance.sync(),/PROMPT_CONTENT_SIZE/);assert.equal(f.instance.entry(),prior);assert.equal(f.instance.owner,oldOwner);assert.equal(f.instance.documentId,oldId);assert.equal(predicate(),false);assert.equal(f.instance.loading,false);fail=false;await f.instance.sync();await flush();assert.equal(f.instance.entry().text,'one');assert.equal(f.instance.owner,f.editor.draftOwner);assert.equal(f.instance.documentId,'next');assert.equal(f.instance.entries.size,2);}finally{await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

test('preferred queued replacement wins same-key recovery independent of checkpoint order',async()=>{const baseline=allocationLedger.snapshot(),f=fixture();try{await f.initial();f.editor.draftOwner=f.owner();f.editor.ui.drafts=['preferred','later-old'].map(id=>({kind:'request',id,documentId:'old',generation:'1',expectedDocumentRevision:'1'}));f.instance.preferredQueuedDraftId='preferred';f.instance.preferredQueuedOwner=f.editor.draftOwner;f.route(async path=>{const id=path.includes('draftId=preferred')?'preferred':'later-old';return path.includes('content=1')?new Response(id,{headers:{'content-length':String(id.length)}}):response({value:newDraft(ref(id))});});await f.instance.sync();assert.equal(f.instance.entry().id,'preferred');assert.equal(f.instance.preferredQueuedDraftId,null);}finally{await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

test('deferred action pins old Entry through replacement and release waits the actual action',async()=>{const baseline=allocationLedger.snapshot(),f=fixture(),work=deferred();try{await f.initial();const prior=f.instance.entry(),started=deferred();f.instance.action(event('action'),async()=>{started.resolve();await work.promise;assert.equal(prior.draft.operation,'generate');});await turn();await started.promise;f.instance.mutateEntry('new',next=>next.text='new');await flush();assert.equal(f.instance.entryRetired.size,0);assert(allocationLedger.snapshot().promptBytes>modelPayloadBytes(f.instance.entry()));let closed=false;const closing=f.instance.dispose().then(()=>closed=true);await flush();assert.equal(closed,false);work.resolve();await closing;assert.equal(closed,true);}finally{work.resolve();await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

test('late native veto drops deferred hold without invoking mutation and release drains',async()=>{const baseline=allocationLedger.snapshot(),f=fixture();try{await f.initial();let called=false;const e=event('action');f.instance.action(e,()=>{called=true;});e.preventDefault();await f.instance.dispose();assert.equal(called,false);assert.equal(f.instance.entryHolds.size,0);}finally{await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

test('composition projection adopts independent copies and releases read/projection temporaries',async()=>{const baseline=allocationLedger.snapshot(),f=fixture();try{await f.initial();const composition=emptyComposition(512,512,'composition');composition.scene='A bounded scene';const projected=serialize(composition,[],{});composition.review={serializer:'caption-json-1',sourceId:composition.id,frame:structuredClone(composition.frame),request:structuredClone(composition.request),dependencies:projected.dependencies,boxes:projected.boxes,prompt:ref(projected.prompt)};const reference={value:{hash:hash('composition'),byteLength:'10',mediaType:'application/json'},id:'composition'};f.editor.view.image.composition=reference;f.route(async()=>response({composition,layers:[],bindings:{}}));await f.instance.composition();await flush();const entry=f.instance.entry();assert.equal(entry.text,projected.prompt);assert.equal(entry.draft.prompt.mode,'composition');assert.deepEqual(entry.draft.prompt.projection,composition.review);assert.notEqual(entry.draft.prompt.projection,composition.review);assert.notEqual(entry.draft.prompt.composition,reference);assert.equal(f.instance.entryReads.size,0);assert.equal(f.instance.entryTasks.size,0);}finally{await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

test('native unlock failure remains an actual resource until release retries it',async()=>{const baseline=allocationLedger.snapshot(),f=fixture();try{await f.initial();const bytes=new TextEncoder().encode('{}');let index=0,locked=true,refuse=true;const reader={async read(){return index++?{done:true}:{done:false,value:bytes};},async cancel(){},releaseLock(){if(refuse)throw undefined;locked=false;}};f.route(async()=>({ok:true,headers:new Headers({'content-length':String(bytes.length)}),body:{getReader:()=>reader}}));await assert.rejects(f.instance.entryWork(()=>f.instance.entryJSON('/broken',()=>true)),error=>error instanceof PromptReaderCleanupError);assert.equal(locked,true);assert.equal(f.instance.entryCleanup.size,1);const failed=allocationLedger.snapshot();assert(failed.unusedRecords>0||failed.activeRecords>baseline.activeRecords);refuse=false;await f.instance.dispose();assert.equal(locked,false);assert.equal(f.instance.entryCleanup.size,0);}finally{await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

test('composition response admission can succeed while projection admission refuses atomically',async()=>{const baseline=allocationLedger.snapshot(),f=fixture();let block;try{await f.initial();const prior=f.instance.entry(),saved=f.saved.length,composition=emptyComposition(512,512,'composition');composition.scene='Retained composition';const projected=serialize(composition,[],{});composition.review={serializer:'caption-json-1',sourceId:composition.id,frame:structuredClone(composition.frame),request:structuredClone(composition.request),dependencies:projected.dependencies,boxes:projected.boxes,prompt:ref(projected.prompt)};f.editor.view.image.composition={value:ref('graph'),id:'composition'};f.route(async()=>response({composition,layers:[],bindings:{}}));const read=f.editor.ownedJSON.bind(f.editor);f.editor.ownedJSON=async(...args)=>{const model=await read(...args);block=pressure(0);return model;};await assert.rejects(f.instance.composition(),/PROMPT_MEMORY_BUDGET/);assert.equal(f.instance.entry(),prior);assert.equal(f.instance.mode,'plain');assert.equal(f.saved.length,saved);block.release();block=null;await flush();assert.equal(f.instance.entryReads.size,0);}finally{block?.release();await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

test('document release waits aborted native composition reader cancellation',async()=>{const baseline=allocationLedger.snapshot(),f=fixture(),cancel=deferred(),started=deferred();let work,closing;try{await f.initial();f.route(async()=>new Response(new ReadableStream({cancel(){started.resolve();return cancel.promise;}}),{headers:{'content-length':'2'}}));work=f.instance.composition();void work.catch(()=>{});await flush();let drained=false;closing=f.instance.dispose().then(()=>drained=true);await started.promise;await flush();assert.equal(drained,false);assert(allocationLedger.snapshot().activeRecords>baseline.activeRecords);cancel.resolve();await assert.rejects(work,/PROMPT_READ_STALE|superseded/);await closing;assert.equal(drained,true);}finally{cancel.resolve();await work?.catch(()=>{});await closing;await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

test('failed Lit retirement keeps both actual owners until a successful drain retry',async()=>{const baseline=allocationLedger.snapshot(),f=fixture();try{await f.initial();const prior=f.instance.entry(),oldModel=f.instance.entryModels.get(prior),update=f.host.requestUpdate;f.host.requestUpdate=()=>{throw Error('render unavailable');};assert.throws(()=>f.instance.mutateEntry('next',next=>next.text='next'),/render unavailable/);const current=f.instance.entry();assert.notEqual(current,prior);assert(f.instance.entryModels.has(current));await flush();assert(f.instance.entryRetired.has(oldModel));assert(allocationLedger.snapshot().promptBytes>=modelPayloadBytes(prior)+modelPayloadBytes(current));f.host.requestUpdate=update;await f.instance.dispose();assert.equal(f.instance.entryRetired.size,0);}finally{await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

// Shared Entry + Navigation lifecycle regressions use the real merged controller.
test('permanent disposal refuses fresh callbacks and sync without creating any new owner',async()=>{
 const baseline=allocationLedger.snapshot(),f=fixture();try{await f.initial();await f.instance.dispose();await flush();const drained=allocationLedger.snapshot(),reads=f.reads.length;let invoked=false;
  f.instance.action(event('fresh-action'),()=>{invoked=true;});f.instance.field(event('prompt','after close'),()=>{invoked=true;});await f.instance.sync();await turn();await flush();assert.equal(invoked,false);assert.equal(f.reads.length,reads);assert.equal(f.instance.inspectMemory().disposed,true);assert.equal(f.instance.entries.size,0);assert.equal(f.instance.entryHolds.size,0);sameUsage(allocationLedger.snapshot(),drained);
 }finally{await f.close();}sameUsage(allocationLedger.snapshot(),baseline);
});
test('release awaits adapter drain despite synchronous render failure and retries actual Entry commit',async()=>{
 const baseline=allocationLedger.snapshot(),f=fixture(),gate=deferred();let closing,update;try{await f.initial();update=f.host.requestUpdate;const prior=f.instance.entry(),priorOwner=f.instance.entryModels.get(prior);f.instance.adapterLibrary.dispose=()=>gate.promise;f.host.requestUpdate=()=>{throw Error('native render unavailable');};let finished=false;
  closing=f.instance.dispose();assert(closing instanceof Promise);void closing.then(()=>{finished=true;},()=>{finished=true;});await flush();assert.equal(finished,false);assert(f.instance.entryRetired.has(priorOwner));assert(allocationLedger.snapshot().promptBytes>=modelPayloadBytes(prior));gate.resolve();await assert.rejects(closing,error=>error instanceof AggregateError&&error.message==='REQUEST_RELEASE_INCOMPLETE');assert(f.instance.entryRetired.has(priorOwner));assert.equal(f.instance.inspectMemory().releasing,true);
  f.host.requestUpdate=update;await f.instance.dispose();await flush();assert.equal(f.instance.entryRetired.size,0);assert.equal(f.instance.inspectMemory().releasing,false);
 }finally{gate.resolve();await closing?.catch(()=>{});if(update)f.host.requestUpdate=update;await f.close();}sameUsage(allocationLedger.snapshot(),baseline);
});
test('reusable document release drains all children before a successor can reopen',async()=>{
 const baseline=allocationLedger.snapshot(),f=fixture(),gate=deferred();let closing;try{await f.initial();const oldAdapter=f.instance.adapterLibrary,oldEntry=f.instance.entry();oldAdapter.dispose=()=>gate.promise;let finished=false;closing=f.instance.releaseDocument().then(()=>{finished=true;});await flush();await f.instance.sync();assert.equal(finished,false);assert.equal(f.instance.loaded,false);assert.equal(f.instance.entry(),undefined);assert.equal(f.instance.adapterLibrary,oldAdapter);assert.equal(f.instance.inspectMemory().releasing,true);
  gate.resolve();await closing;assert.equal(f.instance.inspectMemory().disposed,false);assert.equal(f.instance.inspectMemory().releasing,false);assert.notEqual(f.instance.adapterLibrary,oldAdapter);await f.instance.sync();await flush();assert.equal(f.instance.loaded,true);assert.notEqual(f.instance.entry(),oldEntry);assert.equal(f.instance.documentId,'old');assert.equal(f.instance.entryRetired.size,0);
 }finally{gate.resolve();await closing;await f.close();}sameUsage(allocationLedger.snapshot(),baseline);
});

test('queue navigation releases its prepared history if the initial render request throws',async()=>{
 const baseline=allocationLedger.snapshot(),f=fixture();let update;try{await f.initial();const before=allocationLedger.snapshot(),back=navigationHistory(['prior-cursor']);update=f.host.requestUpdate;f.host.requestUpdate=()=>{throw Error('queue render unavailable');};await assert.rejects(f.instance.refreshQueue('next-cursor',back),/queue render unavailable/);f.host.requestUpdate=update;await flush();assert.equal(f.instance.queueNavigating,false);assert.deepEqual(f.instance.queueBack,[]);sameUsage(allocationLedger.snapshot(),before);
 }finally{if(update)f.host.requestUpdate=update;await f.close();}sameUsage(allocationLedger.snapshot(),baseline);
});
