// Staged future integration fixture: root owns execution after all staged patches are reconciled.
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {readFile} from 'node:fs/promises';import {join} from 'node:path';
import {setup,call,mutationHeaders} from '../protocol/helpers.mjs';import {operate,terminal} from '../raster/helpers.mjs';
import {newDraft,newV45Draft,hash} from '../../dist/local/src/request/family.js';
import {openWriter} from '../../dist/local/server/storage/writer.js';
async function caption(f,text){const bytes=Buffer.from(text),stagingId=randomUUID(),sha256=hash(text);assert.equal((await f.post('/api/v1/assets/staging',{protocolVersion:1,stagingId,purpose:'caption',expectedBytes:String(bytes.length),sha256,mediaType:'text/plain'})).status,201);assert.equal((await call(f.server.origin,'/api/v1/assets/staging/'+stagingId,{method:'PUT',raw:bytes,headers:{...mutationHeaders(f.server,f.paired),'Content-Type':'application/octet-stream','Upload-Offset':'0'}})).status,200);return (await operate(f,{type:'FinalizeStaging',stagingId,expectedSha256:sha256})).event.payload.asset;}
async function send(f,body,id=randomUUID()){const ui=(await f.read('/api/v1/ui/request_family')).json,request={protocolVersion:1,requestId:id,sessionId:'request_family',expectedUISeq:ui.uiSeq,body};return {request,result:await f.post('/api/v1/ui/request_family',request)};}
async function save(f,family,text,generation='1',mutate=()=>{}){const prompt=await caption(f,text),draft=family==='v4'?newDraft(prompt.blob):newV45Draft(prompt.blob);mutate(draft);const original=JSON.stringify(draft,null,2),asset=await caption(f,original),revision=(await f.read('/api/v1/documents/document_1')).json.projection.value.revision;const response=await send(f,{type:'SaveDraft',draft:{id:'request_'+family,generation,kind:'request',documentId:'document_1',targetLayerId:null,expectedDocumentRevision:revision,assetId:asset.id,composing:false}});assert.equal(response.result.json.status,'accepted',response.result.text);return {draft,asset,original};}
async function fixture(t){const f=await setup(t);await terminal(f,f.command({}, {width:1024,height:1024}));return f;}
const object=(f,ref)=>readFile(join(f.root,'objects/sha256',ref.hash.slice(7,9),ref.hash.slice(7)));
test('writer retains separate V4 and V45 drafts, templates and review identities without changing original bytes',async t=>{
 const f=await fixture(t),old=await save(f,'v4','V4 original'),next=await save(f,'v45','V45 original','1',d=>d.fields.seed='900719925474099312345');
 const a=await send(f,{type:'PrepareRequestReview',draftId:'request_v4',generation:'1'}),b=await send(f,{type:'PrepareRequestReview',draftId:'request_v45',generation:'1'});
 assert.equal(a.result.json.status,'accepted',a.result.text);assert.equal(b.result.json.status,'accepted',b.result.text);const legacy=a.result.json.review,review=b.result.json.review;
 assert.equal(legacy.kind,'request-review-1');assert(!Object.hasOwn(legacy,'providerReview'));assert.equal(legacy.endpoint,'ideogram/v4');assert.equal(review.kind,'request-review-v45-1');assert.equal(review.endpoint,'ideogram/v4.5');assert.equal(review.providerReview.admission.state,'blocked');assert.equal(review.providerReview.privacyProfile,null);
 assert.equal((await object(f,old.asset.blob)).toString(),old.original);assert.equal((await object(f,next.asset.blob)).toString(),next.original);const wire=(await object(f,review.template)).toString();assert(wire.includes('"seed":900719925474099312345'));assert(!wire.includes('enable_safety_checker'));assert(!wire.includes('output_format'));
 const before=(await f.read('/api/v1/documents/document_1')).json,accepted=await send(f,{type:'AcceptRequestReview',reviewId:review.id,token:review.token});assert.equal(accepted.result.json.acceptedReview,review.id);assert.deepEqual((await f.read('/api/v1/documents/document_1')).json,before);assert.deepEqual((await f.post('/api/v1/ui/request_family',b.request)).json,b.result.json);
 for(const [id,saved,text]of [['request_v4',old,'V4 original'],['request_v45',next,'V45 original']]){
  const path='/api/v1/ui/request_family/request?draftId='+id+'&generation=1',metadata=await f.read(path);assert.equal(metadata.status,200,metadata.text);assert.deepEqual(metadata.json.value,saved.draft);assert.deepEqual(metadata.json.textUtf8,saved.draft.prompt.text);
  const content=await f.read(path+'&content=1');assert.equal(content.status,200,content.text);assert.equal(content.text,text);assert.equal(content.headers.etag,'"'+saved.draft.prompt.text.hash+'"');assert.equal(content.headers['content-length'],saved.draft.prompt.text.byteLength);
  for(const suffix of ['', '&content=1']){const stale=await f.read(path.replace('generation=1','generation=0')+suffix);assert.equal(stale.status,410,stale.text);assert.equal(stale.json.error.code,'READ_CONTEXT_EXPIRED');}
 }
});
test('invalid V45 values stay saved and cannot inherit a V4 operation or acknowledgment',async t=>{
 const f=await fixture(t);await save(f,'v45','raw text','1',d=>{d.prompt.mode='raw';d.fields.quality='unfinished';});let r=await send(f,{type:'PrepareRequestReview',draftId:'request_v45',generation:'1'});assert.equal(r.result.json.status,'rejected');assert.match(r.result.json.reason,/OPAQUE_ACK/);
 const retainedRead=await f.read('/api/v1/ui/request_family/request?draftId=request_v45&generation=1');assert.equal(retainedRead.status,200,retainedRead.text);const retained=retainedRead.json.value;assert.equal(retained.fields.quality,'unfinished');assert.equal(retained.guidanceAcknowledged,false);
 await save(f,'v45','raw text','2',d=>{d.prompt.mode='raw';d.guidanceAcknowledged=true;});r=await send(f,{type:'PrepareRequestReview',draftId:'request_v45',generation:'2'});assert.equal(r.result.json.status,'rejected');assert.match(r.result.json.reason,/REWRITE_ACK/);
});
test('restarting retains exact V45 receipts while the writer epoch invalidates fresh acceptance',async t=>{
 const f=await fixture(t);await save(f,'v45','Retained V45');const before=await send(f,{type:'PrepareRequestReview',draftId:'request_v45',generation:'1'});assert.equal(before.result.json.status,'accepted',before.result.text);await f.server.close();const writer=await openWriter({root:f.root});t.after(()=>writer.close());const auth={clientId:f.paired.json.clientId,sessionHash:'a'.repeat(64),now:Date.now(),expires:Date.now()+1800000};assert.deepEqual(await writer.uiPersist(Buffer.from(JSON.stringify(before.request)),auth),before.result.json);
 const ui=await writer.uiRead('request_family',auth),review=before.result.json.review,result=await writer.uiPersist(Buffer.from(JSON.stringify({protocolVersion:1,requestId:randomUUID(),sessionId:'request_family',expectedUISeq:ui.uiSeq,body:{type:'AcceptRequestReview',reviewId:review.id,token:review.token}})),auth);assert.equal(result.status,'rejected');assert.match(result.reason,/STALE_REVIEW/);
});
