import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';import {mkdtemp,writeFile,readFile,rm,access} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {transformWithOxc} from 'vite';
const load=async file=>import('data:text/javascript;base64,'+Buffer.from((await transformWithOxc(await readFile(file,'utf8'),file)).code).toString('base64'));
const {ownedOPFS}=await load('tests/editor/owned-opfs.ts'),{step,throwFailures,retainOrRemove,archiveVerified}=await load('tests/editor/harness-lifecycle.ts'),{savedDraftWitness}=await load('tests/request/persistence-witness.ts');
const {createHash}=await import('node:crypto');
function witness(){const expected={sessionId:'owner',documentId:'document',revision:'1',generation:'1',prompt:'Theme keeps Café 東京',operation:'generate'},draft={id:'draft',generation:'1',kind:'request',documentId:'document',targetLayerId:null,expectedDocumentRevision:'1',composing:false,assetId:'asset'};return {expected,input:{request:{protocolVersion:1,requestId:'save',sessionId:'owner',body:{type:'SaveDraft',draft}},receipt:{protocolVersion:1,requestId:'save',status:'accepted',uiSeq:'4'},checkpoint:{sessionId:'owner',uiSeq:'4',preferences:{documentId:'document'},drafts:[{...draft,status:'saved-unapplied'}]},value:{operation:'generate',prompt:{mode:'plain',text:{hash:'sha256:'+createHash('sha256').update(expected.prompt).digest('hex'),byteLength:String(Buffer.byteLength(expected.prompt)),mediaType:'text/plain'}}},content:expected.prompt,revision:'1'}};}
test('delayed persistence cannot cross the exact saved boundary before receipt and checkpoint',()=>{const {expected,input}=witness(),receipt=input.receipt,checkpoint=input.checkpoint;input.receipt=undefined;assert.throws(()=>savedDraftWitness(expected,input),/matching accepted receipt/);input.receipt=receipt;input.checkpoint={...checkpoint,drafts:[]};assert.throws(()=>savedDraftWitness(expected,input),/saved draft/);input.checkpoint=checkpoint;assert.equal(savedDraftWitness(expected,input).draftId,'draft');});
for(const [name,mutate]of Object.entries({owner:x=>x.request.sessionId='other',checkpointOwner:x=>x.checkpoint.sessionId='other',revision:x=>x.revision='2',draftRevision:x=>x.request.body.draft.expectedDocumentRevision='2',generation:x=>x.request.body.draft.generation='2',receipt:x=>x.receipt.requestId='old',sequence:x=>x.checkpoint.uiSeq='5',asset:x=>x.checkpoint.drafts[0].assetId='other',text:x=>x.content='old',hash:x=>x.value.prompt.text.hash='sha256:wrong'}))test('saved witness refuses wrong '+name,()=>{const {expected,input}=witness();mutate(input);assert.throws(()=>savedDraftWitness(expected,input),/DRAFT_NOT_SETTLED/);});
class Context extends EventEmitter{pagesOwned=[];resets=0;async cookies(){return [];}pages(){return this.pagesOwned.filter(p=>!p.closed);}serviceWorkers(){return [];}async newPage(){const p=new Page(this);this.pagesOwned.push(p);this.emit('page',p);return p;}async setStorageState(){this.resets++;}}
class Page extends EventEmitter{closed=false;location='about:blank';constructor(context){super();this.context=context;this.frame={page:()=>this,url:()=>this.location};}url(){return this.location;}isClosed(){return this.closed;}async route(){}async goto(url){this.location=url;this.context.emit('request',request(this,url));this.emit('framenavigated',this.frame);}async evaluate(){return {entries:[],localStorage:0,indexedDB:[],serviceWorkers:0};}async close(){if(this.closed)return;this.closed=true;if(this.onClose)await this.onClose();}}
function request(page,url='http://127.0.0.1:12345/api/v1/documents/example?secret=do-not-log',method='HEAD'){return {url:()=>url,frame:()=>{if(!page)throw Error('no frame');return page.frame;},method:()=>method,resourceType:()=>method==='HEAD'?'fetch':'eventsource'};}
for(const fault of ['closing','missing frame'])test('actual OPFS guard refuses '+fault+' without reset and retains passive request identity',async()=>{const context=new Context(),page=await context.newPage(),guard=await ownedOPFS(context,'unit');await guard.admit(page,'http://127.0.0.1:12345');let r;if(fault==='closing')page.onClose=async()=>{r=request(page);context.emit('request',r);context.emit('requestfinished',r);};else{r=request(null,undefined,'GET');context.emit('request',r);context.emit('requestfailed',r);}await assert.rejects(guard.cleanup(),/OPFS_RESET_REFUSED/);assert.equal(context.resets,0);assert.equal(guard.ledger.at(-1).resetCalls,0);assert(guard.ledger.some(e=>e.reason?.startsWith(fault==='closing'?'UNPLANNED_REQUEST':'UNOWNED_REQUEST')));const events=guard.requests.filter(e=>e.location.path==='/api/v1/documents/example');assert.equal(events.length,2);assert.equal(events[0].requestId,events[1].requestId);assert(events[0].sequence<events[1].sequence);assert.equal(events[0].guardPhase,fault==='closing'?'closing':'active');assert.equal(events[0].frameIdentity,fault==='closing'?'available':'unavailable');assert.equal(events[0].method,fault==='closing'?'HEAD':'GET');assert(!JSON.stringify(events).includes('do-not-log'));assert(events[0].at&&Number.isFinite(events[0].monotonicMs));assert.throws(()=>guard.verify(),/OPFS_CLEANUP_INCOMPLETE/);});
function state(root,receipt){return {failures:[],roots:[root],writerClosed:true,contextClosed:true,browserClosed:true,retention:[],receipt,prefix:''};}
for(const phase of ['body','logical-cleanup'])test(phase+' original error survives and private state is verified before removal',async()=>{const root=await mkdtemp(join(tmpdir(),'harness-state-')),receipt=await mkdtemp(join(tmpdir(),'harness-proof-'));try{await writeFile(join(root,'sentinel'),'private exact failed state');const s=state(root,receipt),original=Error(phase);await step(s,phase,async()=>{throw original;});assert.throws(()=>throwFailures(s.failures),e=>e===original);let archived=false;await retainOrRemove(s,async(r,d)=>{const proof=await archiveVerified(r,d);assert.equal(await readFile(join(r,'sentinel'),'utf8'),'private exact failed state');archived=true;return proof;},async r=>{assert(archived);await rm(r,{recursive:true});});assert(s.retention.some(r=>r.verified));await assert.rejects(access(root));assert.throws(()=>throwFailures(s.failures),e=>e===original);}finally{await rm(root,{recursive:true,force:true});await rm(receipt,{recursive:true,force:true});}});
test('cleanup-only plus archive failure retains root and both original errors',async()=>{const root=await mkdtemp(join(tmpdir(),'harness-retained-'));try{await writeFile(join(root,'state'),'recoverable');const s=state(root,root),cleanup=Error('original cleanup refusal'),archive=Error('archive unavailable');s.failures.push({phase:'logical-cleanup',error:cleanup});let removed=false;await retainOrRemove(s,async()=>{throw archive;},async()=>{removed=true;});assert(!removed);assert.equal(await readFile(join(root,'state'),'utf8'),'recoverable');assert(s.retention.some(r=>r.retained));assert.throws(()=>throwFailures(s.failures),e=>e instanceof AggregateError&&e.errors[0]===cleanup&&e.errors[1]===archive);}finally{await rm(root,{recursive:true,force:true});}});
test('unverified writer closure prohibits archive and deletion',async()=>{const s=state('private','evidence');s.writerClosed=false;let calls=0;await retainOrRemove(s,async()=>{calls++;},async()=>{calls++;});assert.equal(calls,0);assert(s.retention[0].retained);assert.throws(()=>throwFailures(s.failures),/WRITER_NOT_CLOSED/);});
test('actual fixture retains a cleanup-only failure after writer shutdown through final observations',async()=>{const {runs,finishFixture}=await load('tests/editor/harness-lifecycle.ts');const root=await mkdtemp(join(tmpdir(),'fixture-state-')),receipt=await mkdtemp(join(tmpdir(),'fixture-proof-'));try{await writeFile(join(root,'private'),'original bytes');const context={async close(){seen.push('context closed');}},seen=[],s=state(root,receipt),original=Error('original logical cleanup');s.contextClosed=false;s.browserClosed=false;s.failures.push({phase:'logical-cleanup',error:original});s.observe=()=>({observations:seen});runs.set(context,s);await finishFixture(context,{async close(){seen.push('browser closed');}},null,receipt,'');assert.throws(()=>throwFailures(s.failures),e=>e===original);const o=JSON.parse(await readFile(join(receipt,'observations.json'),'utf8'));assert.deepEqual(o.observations,['context closed','browser closed']);assert.equal(o.failures[0].error.message,original.message);assert(o.retention.some(r=>r.verified));await assert.rejects(access(root));}finally{await rm(root,{recursive:true,force:true});await rm(receipt,{recursive:true,force:true});}});
test('a fixture-only context close failure preserves original error and private root',async()=>{const {runs,finishFixture}=await load('tests/editor/harness-lifecycle.ts');const root=await mkdtemp(join(tmpdir(),'fixture-close-')),receipt=await mkdtemp(join(tmpdir(),'fixture-close-proof-'));try{await writeFile(join(root,'private'),'retained');const original=Error('original context close'),context={async close(){throw original;}},s=state(root,receipt);runs.set(context,s);await assert.rejects(finishFixture(context,null,null,receipt,''),e=>e instanceof AggregateError&&e.errors[0]===original);assert.equal(await readFile(join(root,'private'),'utf8'),'retained');const o=JSON.parse(await readFile(join(receipt,'observations.json'),'utf8'));assert.equal(o.physicalClosure.contextClosed,false);assert(o.retention.some(r=>r.retained));}finally{await rm(root,{recursive:true,force:true});await rm(receipt,{recursive:true,force:true});}});
test('actual archive command failure leaves failed private state intact',async()=>{const root=await mkdtemp(join(tmpdir(),'archive-command-'));try{await writeFile(join(root,'private'),'still present');const s=state(root,join(root,'absent','evidence'));s.failures.push({phase:'logical-cleanup',error:Error('original failure')});await retainOrRemove(s);assert.equal(await readFile(join(root,'private'),'utf8'),'still present');assert(s.failures.some(f=>f.phase==='archive'));assert(s.retention.some(r=>r.retained));}finally{await rm(root,{recursive:true,force:true});}});
test('a partial removal failure keeps the pre-removal verified archive',async()=>{const root=await mkdtemp(join(tmpdir(),'remove-failure-')),receipt=await mkdtemp(join(tmpdir(),'remove-proof-'));try{await writeFile(join(root,'private'),'backup before removal');const s=state(root,receipt),original=Error('partial removal');await retainOrRemove(s,archiveVerified,async()=>{await rm(join(root,'private'));throw original;});assert(s.retention.some(r=>r.verified));assert.throws(()=>throwFailures(s.failures),e=>e===original);await access(s.retention.find(r=>r.verified).archive);}finally{await rm(root,{recursive:true,force:true});await rm(receipt,{recursive:true,force:true});}});
const {CurrentEditBinding}=await load('tests/request/persistence-witness.ts');
function editFixture(generation='3'){
 const w=witness();w.expected.generation=generation;w.input.request.body.draft.generation=generation;w.input.checkpoint.drafts[0].generation=generation;w.input.request.expectedUISeq='3';
 const {generation:_unused,...expected}=w.expected;const start={actionId:'specific-public-edit',expected,promptBefore:'',checkpoint:{sessionId:'owner',uiSeq:'3',preferences:{documentId:'document'},drafts:[]},requestBoundary:10,priorRequests:[],pendingMutations:0};
 const binder=new CurrentEditBinding(start),event={sequence:11,request:w.input.request};return {...w,start,binder,event,complete(){binder.completeAction(w.expected.prompt);binder.observe(event);return binder.bind();}};
}
test('actual binder accepts observed generation three without predicting native change count',()=>{const f=editFixture();assert.equal(f.binder.bind(),null);const bound=f.complete();assert.equal(bound.generation,'3');assert.equal(bound.actionId,'specific-public-edit');assert.equal(savedDraftWitness(bound.expected,{...f.input,request:bound.request}).generation,'3');assert.equal(f.binder.snapshot().observed.length,1);});
test('bound save waits for its receipt and matching checkpoint without changing the binding',()=>{const f=editFixture(),bound=f.complete();assert.equal(f.binder.receipt([]),null);assert.equal(f.binder.receipt([{...f.input.receipt,requestId:'stale'}]),null);assert.deepEqual(f.binder.receipt([f.input.receipt]),f.input.receipt);assert.throws(()=>savedDraftWitness(bound.expected,{...f.input,checkpoint:{...f.input.checkpoint,drafts:[]}}),/saved draft/);assert.equal(f.binder.bound.requestId,bound.requestId);assert.equal(savedDraftWitness(bound.expected,f.input).generation,'3');});
test('stale pre-action same-text save cannot identify the current edit',()=>{const f=editFixture();f.binder.completeAction(f.expected.prompt);f.binder.observe({...f.event,sequence:10});assert.throws(()=>f.binder.bind(),/STALE_PRE_ACTION_SAVE/);assert.equal(f.binder.snapshot().refusals.at(-1).reason,'STALE_PRE_ACTION_SAVE');});
for(const [name,mutate]of Object.entries({owner:r=>r.sessionId='other',document:r=>r.body.draft.documentId='other',revision:r=>r.body.draft.expectedDocumentRevision='2',target:r=>r.body.draft.targetLayerId='other',composition:r=>r.body.draft.composing=true,sequence:r=>r.expectedUISeq='2'}))test('actual edit binder rejects changed '+name,()=>{const f=editFixture();mutate(f.event.request);f.binder.completeAction(f.expected.prompt);f.binder.observe(f.event);assert.throws(()=>f.binder.bind(),/EDIT_BINDING_REFUSED/);});
for(const kind of ['draft','generation','competing request'])test('binding cannot be satisfied by a later '+kind,()=>{const f=editFixture(),bound=f.complete(),next=structuredClone(f.event);next.sequence=12;next.request.requestId='later';if(kind==='draft')next.request.body.draft.id='other-draft';if(kind==='generation')next.request.body.draft.generation='4';f.binder.observe(next);assert.throws(()=>f.binder.assertCurrent(),/AMBIGUOUS_OR_SUPERSEDING_SAVE/);assert.equal(f.binder.bound.generation,bound.generation);assert.equal(f.binder.snapshot().observed.length,2);});
test('two attributable-looking saves before binding are refused rather than choosing first or latest',()=>{const f=editFixture();f.binder.completeAction(f.expected.prompt);f.binder.observe(f.event);f.binder.observe({sequence:12,request:{...f.input.request,requestId:'second'}});assert.throws(()=>f.binder.bind(),/AMBIGUOUS_OR_SUPERSEDING_SAVE/);assert.equal(f.binder.bound,null);});
test('exact redelivery preserves one original identity but changed envelope is refused',()=>{const f=editFixture(),bound=f.complete();f.binder.observe({...structuredClone(f.event),sequence:12});assert.deepEqual(f.binder.bind(),bound);const changed=structuredClone(f.event);changed.sequence=13;changed.request.body.draft.assetId='changed';f.binder.observe(changed);assert.throws(()=>f.binder.assertCurrent(),/REQUEST_ENVELOPE_CHANGED/);});
test('conflicting receipts for the bound identity cannot choose a convenient success',()=>{const f=editFixture();f.complete();assert.deepEqual(f.binder.receipt([f.input.receipt,structuredClone(f.input.receipt)]),f.input.receipt);assert.throws(()=>f.binder.receipt([f.input.receipt,{...f.input.receipt,uiSeq:'5'}]),/AMBIGUOUS_RECEIPT/);});
for(const [name,mutate]of Object.entries({draft:x=>x.checkpoint.drafts[0].id='other-draft',generation:x=>x.checkpoint.drafts[0].generation='4',asset:x=>x.checkpoint.drafts[0].assetId='different',content:x=>x.content='not this edit',receipt:x=>x.receipt.requestId='old',checkpoint:x=>x.checkpoint.uiSeq='3'}))test('actual bound witness refuses changed '+name,()=>{const f=editFixture(),bound=f.complete();mutate(f.input);assert.throws(()=>savedDraftWitness(bound.expected,{...f.input,request:bound.request}),/DRAFT_NOT_SETTLED/);assert.equal(f.binder.bound.generation,'3');});
for(const [name,mutate]of Object.entries({prompt:s=>s.promptBefore='same expected text already present',pending:s=>s.pendingMutations=1,checkpoint:s=>s.checkpoint.drafts=[{kind:'request',documentId:'document',id:'older'}],staging:s=>s.priorRequests=[{sequence:9,path:'/api/v1/assets/staging',request:{}}]}))test('pre-action '+name+' prevents a false fresh edit binding',()=>{const f=editFixture();mutate(f.start);assert.throws(()=>new CurrentEditBinding(f.start),/PRE_ACTION/);});
test('action must finish with the independently intended public prompt',()=>{const f=editFixture();f.binder.observe(f.event);assert.equal(f.binder.bind(),null);assert.throws(()=>f.binder.completeAction('wrong prompt'),/EDIT_ACTION_MISMATCH/);});
