// Source-only controller qualification. The coordinator runs this after the
// prompt source and the shared controller-loader successors are assembled.
import test from 'node:test';
import assert from 'node:assert/strict';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const {RequestEditing,allocationLedger,allocationsURL,createOwnedModel,modelPayloadBytes,readOwnedJSON}=await import(pathToFileURL(resolve(process.env.REQUEST_PROMPT_TEST_ROOT??'.','tests/request/request-controller-module.mjs')).href);
const {ALLOCATION_LIMITS}=await import(allocationsURL),{newDraft,hash}=await import(pathToFileURL(resolve('dist/local/src/request/core.js')).href);
const flush=async()=>{for(let i=0;i<100;i++)await Promise.resolve();},turn=async()=>{await new Promise(resolve=>setTimeout(resolve,0));await flush();},deferred=()=>{let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};};
const usage=()=>{const s=allocationLedger.snapshot();return {cpuBytes:s.cpuBytes,promptBytes:s.promptBytes,activeRecords:s.activeRecords,handles:s.handles};};
const pressure=()=>allocationLedger.reserve({owner:'prompt-controller-pressure',kind:'prompt',cpuBytes:ALLOCATION_LIMITS.promptBytes-allocationLedger.snapshot().promptBytes});
const response=value=>{const wire=JSON.stringify(value);return new Response(wire,{headers:{'content-length':String(Buffer.byteLength(wire))}});};
const ref=value=>({hash:hash(value),byteLength:String(Buffer.byteLength(value)),mediaType:'text/plain'});
function find(template,part){if(!template||typeof template!=='object')return;if(template.strings?.some(value=>value.includes(part)))return template;for(const value of Array.isArray(template)?template:template.values??[]){const result=find(value,part);if(result)return result;}}
function binding(template,key){assert(template,'Rendered template');const index=template.strings.findIndex(value=>value.includes(key));assert(index>=0,'Rendered binding '+key);return template.values[index];}
function event(value='',detail,host={value,isConnected:true}){host.value=value;return {currentTarget:host,composedPath:()=>[host],defaultPrevented:false,detail,preventDefault(){this.defaultPrevented=true;}};}
function registry(){const records=[];let refusedId=null;return {records,setRefused(id){refusedId=id;},active(){return records.filter(record=>record.active).length;},register(id,documentId){if(id===refusedId||refusedId==='*')throw Error('REGISTER_REFUSED');const record={id,documentId,active:true,releases:0};records.push(record);return ()=>{assert(record.active,'Registration released twice');record.active=false;record.releases++;};}};}
function fixture(t){
 const baseline=usage(),registrations=registry(),saved=[],commands=[],reviews=[],refusals=[],roots=[],owners=[],ui=createOwnedModel('prompt-controller-ui',1024,()=>({drafts:[]}));let flow,rendered,native={value:'',isConnected:false,updateComplete:Promise.resolve()},route=async path=>{throw Error('Unexpected transport '+path);},closed=false;
 const makeOwner=()=>{const owner={drafts:new Map(),refused:new Set(),registerDraft(id,documentId){return registrations.register(id,documentId);},refuseChange(id,documentId){this.refused.add(id);refusals.push({id,documentId});}};owners.push(owner);return owner;};
 const own=value=>{const model=createOwnedModel('prompt-controller-response',modelPayloadBytes(value),()=>structuredClone(value));roots.push(model);return model;};
 const editor={documentEpoch:1,sessionId:'session',view:{ready:true,document:{id:'doc',revision:'1',width:512,height:512},image:{layers:[]},selected:[]},ui:ui.value,draftOwner:makeOwner(),session:{identity:()=> 'client',transport(path,init){return path.endsWith('/request-reviews')?Promise.resolve(response({items:[]})):route(path,init);}},registerDraft(id,documentId){assert.equal(documentId,this.view.document.id);return this.draftOwner.registerDraft(id,documentId);},pinUI(){return ui.pin();},pinViewModels(document,image){const model=own({document,image});const release=model.pin();model.release();return release;},ownedJSON(path,owner,init,owns,maxBytes,kind){return readOwnedJSON(this.session.transport.bind(this.session),path,{owner,init,owns,maxBytes,kind});},async ownedCommand(body){commands.push(structuredClone(body));return own([]);},async withCommandEvents(body,work){const model=await this.ownedCommand(body);try{return await work(model.value);}finally{model.release();}},async ownedRequestReview(body){reviews.push(structuredClone(body));return own({review:{id:'review',token:'token',request:{kind:'generate'},prompt:{},estimate:{unknown:[]}},acceptedReview:'review'});},json(){assert.fail('Raw response API forbidden');},command(){assert.fail('Raw command API forbidden');},requestReview(){assert.fail('Raw review API forbidden');},changeDraft(id,kind,text,target,composing,revision){assert(registrations.records.some(record=>record.active&&record.id===id),'Draft registration predates adoption');const generation=String(saved.length+1);saved.push({id,kind,text,target,composing,revision,generation});this.draftOwner.drafts.set(id,{generation,savedGeneration:generation});this.draftOwner.refused.delete(id);},async flushDrafts(){}};
 const host={requestUpdate(){this.updateComplete=Promise.resolve().then(()=>{rendered=flow.render();const field=find(rendered,'<en-textarea id="prompt"');if(field){if(!native.isConnected)native={value:'',isConnected:true,updateComplete:Promise.resolve()};const value=binding(field,'.value=');if(typeof value==='string')native.value=value;}else native.isConnected=false;});},updateComplete:Promise.resolve(),querySelector(selector){return selector==='#prompt'?(native.isConnected?native:null):{focus(){}};}};flow=new RequestEditing(host,editor);
 const close=async()=>{if(closed)return;await flow.dispose();closed=true;ui.release();for(const root of roots){assert.throws(()=>{const release=root.pin();release();},/MODEL_MEMORY_RELEASED/);}await flush();assert.equal(registrations.active(),0,'Entry and native-input registrations drain');assert.deepEqual(usage(),baseline);};t.after(close);
 return {flow,editor,host,get native(){return native;},saved,commands,reviews,refusals,registrations,makeOwner,close,route:value=>route=value,template:()=>rendered,prompt:()=>find(rendered,'<en-textarea id="prompt"'),async initial(){await flow.sync();host.requestUpdate();await flush();},async input(value,detail){const payload=detail??{value,isComposing:false},e=event(native.value,payload,native);binding(this.prompt(),'@en-input=')(e);if(!payload.isComposing)native.value=value;await turn();return e;},async click(id){const template=find(rendered,'id="'+id+'"');binding(template,'@click=')(event());await turn();},render(){host.requestUpdate();return flush();}};
}

test('accepted native text remains complete under Entry refusal and exact Retry preserves the prior saved generation until success',async t=>{
 const f=fixture(t);let block;try{await f.initial();await f.input('previous saved');const prior=f.flow.entry(),saved=f.saved.length,generation=f.editor.draftOwner.drafts.get(prior.id).savedGeneration,raw='new\n東京 😀 '+String.fromCharCode(0)+' complete',registered=f.registrations.active();block=pressure();const e=await f.input(raw);assert.equal(e.currentTarget.value,raw);assert.equal(f.flow.entry(),prior);assert.equal(f.saved.length,saved);assert.equal(f.editor.draftOwner.drafts.get(prior.id).savedGeneration,generation);assert.equal(binding(f.prompt(),'.value='),raw);assert.equal(f.flow.inspectMemory().promptInput.refused,true);assert.equal(f.editor.draftOwner.refused.has(prior.id),true);assert.equal(f.registrations.active(),registered);assert(find(f.template(),'id="request-prompt-retry"'));assert.throws(()=>f.flow.operationChanged('Generate with Fast'),/full input remains/);await assert.rejects(f.flow.prepare(),/full input remains/);assert.deepEqual(f.reviews,[]);assert.deepEqual(f.commands,[]);block.release();block=null;await f.click('request-prompt-retry');assert.equal(f.flow.entry().text,raw);assert.equal(f.saved.length,saved+1);assert.equal(JSON.parse(f.saved.at(-1).text).text,raw);assert.equal(f.editor.draftOwner.refused.has(prior.id),false);assert.equal(f.flow.inspectMemory().promptInput.refused,false);assert.equal(find(f.template(),'id="request-prompt-retry"'),undefined);}finally{block?.release();await f.close();}
});

test('the next complete native edit can replace a refused value after capacity returns',async t=>{
 const f=fixture(t);let block;try{await f.initial();await f.input('saved');block=pressure();await f.input('refused complete text');assert.equal(f.flow.entry().text,'saved');block.release();block=null;await f.input('revised 東京😀');assert.equal(f.flow.entry().text,'revised 東京😀');assert.equal(binding(f.prompt(),'.value='),'revised 東京😀');assert.equal(f.flow.inspectMemory().promptInput.refused,false);assert.equal(f.editor.draftOwner.refused.size,0);}finally{block?.release();await f.close();}
});

test('beforeinput accounts for selected UTF16 units before admitting the entire insertion',async t=>{
 const f=fixture(t);await f.initial();const before=f.flow.inspectMemory().promptInput;assert.equal(before.capacity,65536);assert(before.maximum>before.capacity);const native={value:'x'.repeat(65534)+'😀',selectionStart:65534,selectionEnd:65536},host=Object.assign(f.native,{value:native.value}),e={currentTarget:host,composedPath:()=>[native,host],inputType:'insertText',data:'東京😀',cancelable:true,defaultPrevented:false,preventDefault(){this.defaultPrevented=true;}};binding(f.prompt(),'@beforeinput=')(e);assert.equal(e.defaultPrevented,false);assert(f.flow.inspectMemory().promptInput.capacity>=65538);assert.equal(f.flow.inspectMemory().promptInput.maximum,before.maximum,'The fixed native upper bound does not follow reactive headroom');assert.equal(f.saved.length,0,'A proposal does not save before input is accepted');await f.input('x'.repeat(65534)+'東京😀');assert.equal(f.flow.entry().text,'x'.repeat(65534)+'東京😀');await f.close();
});

test('prospective beforeinput refusal cancels the complete insertion and does not mark the unchanged saved draft refused',async t=>{
 const f=fixture(t);let block;try{await f.initial();await f.input('saved');const prior=f.flow.entry(),saved=f.saved.length,capacity=f.flow.inspectMemory().promptInput.capacity,native={value:'x'.repeat(capacity),selectionStart:capacity,selectionEnd:capacity},host=Object.assign(f.native,{value:native.value}),e={currentTarget:host,composedPath:()=>[native,host],inputType:'insertText',data:'😀',cancelable:true,defaultPrevented:false,preventDefault(){this.defaultPrevented=true;}};block=pressure();binding(f.prompt(),'@beforeinput=')(e);await flush();assert.equal(e.defaultPrevented,true);assert.equal(native.value,'x'.repeat(capacity));assert.equal(f.flow.entry(),prior);assert.equal(f.saved.length,saved);assert.equal(f.flow.inspectMemory().promptInput.capacity,capacity);assert.equal(f.flow.inspectMemory().promptInput.refused,false);assert.equal(f.editor.draftOwner.refused.size,0);assert.match(find(f.template(),'<en-alert role="status">').values.join(''),/No part of the insertion was accepted/);block.release();block=null;e.defaultPrevented=false;binding(f.prompt(),'@beforeinput=')(e);assert.equal(e.defaultPrevented,false);assert(f.flow.inspectMemory().promptInput.capacity>=capacity+2);}finally{block?.release();await f.close();}
});

test('noncancelable overflow preserves native ownership and retries from the actual full native value',async t=>{
 const f=fixture(t);let block;try{await f.initial();await f.input('saved');const native='x'.repeat(65537)+'東京😀',prior=f.flow.entry();f.flow.review={id:'sentinel',token:'review-token',request:{kind:'generate'},prompt:{},estimate:{unknown:[]}};f.flow.accepted=true;const intent=f.flow.intent;block=pressure();const host=Object.assign(f.native,{value:'saved'}),control={value:'saved',selectionStart:0,selectionEnd:5},proposal={currentTarget:host,composedPath:()=>[control,host],inputType:'insertCompositionText',data:native,cancelable:false,preventDefault(){assert.fail('Noncancelable insertion cannot be vetoed');}};binding(f.prompt(),'@beforeinput=')(proposal);assert.equal(f.flow.review,null,'Existing review invalidates before any input notification');assert.equal(f.flow.accepted,false);assert(f.flow.intent>intent);assert.equal(f.flow.entry(),prior);assert.equal(f.flow.inspectMemory().promptInput.nativeOverflow,true);const e=await f.input(native);assert.equal(e.currentTarget.value,native);const observed=usage();assert(observed.promptBytes>ALLOCATION_LIMITS.promptBytes,'Already accepted native overflow remains truthfully above the ordinary ceiling');assert(allocationLedger.snapshot().promptPeakBytes>=observed.promptBytes);assert(allocationLedger.snapshot().peaks.cpuBytes>=observed.cpuBytes);assert.deepEqual(f.commands,[]);assert.deepEqual(f.reviews,[]);assert.equal(f.flow.entry(),prior);assert.equal(f.flow.inspectMemory().promptInput.nativeOverflow,true);assert.notEqual(binding(f.prompt(),'.value='),'saved','Exceptional native ownership must not rewrite the text with accepted Entry content');assert.notEqual(typeof binding(f.prompt(),'.value='),'string','Lit noChange preserves the complete native editor buffer');block.release();block=null;await f.click('request-prompt-retry');assert.equal(f.flow.entry().text,native);assert.equal(f.flow.inspectMemory().promptInput.nativeOverflow,false);assert.equal(f.flow.inspectMemory().promptInput.refused,false);assert.equal(binding(f.prompt(),'.value='),native);}finally{block?.release();await f.close();}
});

test('composing raw detail survives a stale public value and refusal keeps Retry disabled until actual compositionend',async t=>{
 const f=fixture(t);let block;try{await f.initial();await f.input('accepted');block=pressure();binding(find(f.template(),'aria-label="Typed request draft"'),'@compositionstart=')();await flush();assert.equal(f.flow.composing,true);await f.input('accepted',{value:'東京 composing 😀',isComposing:true});assert.equal(binding(f.prompt(),'.value='),'東京 composing 😀');assert.equal(f.flow.entry().text,'accepted');assert.equal(binding(find(f.template(),'id="request-prompt-retry"'),'?disabled='),true);binding(find(f.template(),'aria-label="Typed request draft"'),'@compositionend=')();await flush();assert.equal(f.flow.composing,false);assert.equal(binding(find(f.template(),'id="request-prompt-retry"'),'?disabled='),false);block.release();block=null;await f.click('request-prompt-retry');assert.equal(f.flow.entry().text,'東京 composing 😀');assert.equal(f.saved.at(-1).composing,false);}finally{block?.release();await f.close();}
});

test('duplicate completed input notifications do not create another saved Entry generation',async t=>{
 const f=fixture(t);await f.initial();await f.input('東京 completed');const prior=f.flow.entry(),saved=f.saved.length;await f.input('東京 completed',{value:'東京 completed',isComposing:false});assert.equal(f.flow.entry(),prior);assert.equal(f.saved.length,saved);assert.equal(f.flow.inspectMemory().promptInput.refused,false);await f.close();
});

test('a registration refusal after native acceptance retains its raw value and releases only the failed successor',async t=>{
 const f=fixture(t);try{await f.initial();await f.input('saved');const prior=f.flow.entry(),count=f.registrations.active(),saved=f.saved.length;f.registrations.setRefused(prior.id);await f.input('complete pending input');assert.equal(f.flow.entry(),prior);assert.equal(f.saved.length,saved);assert.equal(f.registrations.active(),count);assert.equal(binding(f.prompt(),'.value='),'complete pending input');assert.equal(f.editor.draftOwner.refused.has(prior.id),true);f.registrations.setRefused(null);await f.click('request-prompt-retry');assert.equal(f.flow.entry().text,'complete pending input');assert.equal(f.registrations.active(),count);}finally{f.registrations.setRefused(null);await f.close();}
});

test('native input registration is acquired before the editable control appears and retries without replacing the accepted Entry',async t=>{
 const f=fixture(t);try{await f.flow.sync();await flush();const accepted=f.flow.entry();f.registrations.setRefused(accepted.id);f.flow.releasePromptInput();await flush();await f.render();assert.equal(f.prompt(),undefined);assert.equal(f.flow.entry(),accepted);assert.equal(f.flow.inspectMemory().promptInput.unavailable,true);assert.match(find(f.template(),'<en-alert>Prompt editing').strings.join(''),/allowance cannot be admitted/);f.registrations.setRefused(null);await f.render();assert(f.prompt());assert.equal(f.flow.entry(),accepted);assert.equal(f.flow.inspectMemory().promptInput.unavailable,false);}finally{f.registrations.setRefused(null);await f.close();}
});

test('saved-draft restoration preregisters every successor before replacing any prior roots or displayed history',async t=>{
 const f=fixture(t);try{await f.initial();await f.input('prior saved');const prior=f.flow.entry(),owner=f.flow.owner,documentId=f.flow.documentId,message=f.flow.message,historical=f.flow.historical,active=f.registrations.active();f.editor.view.document={...f.editor.view.document,id:'next'};f.editor.documentEpoch++;f.editor.draftOwner=f.makeOwner();f.editor.ui.drafts=['one','two'].map(id=>({kind:'request',id,documentId:'next',generation:'1',expectedDocumentRevision:'1'}));const one=newDraft(ref('one')),two=newDraft(ref('two'));two.operation='fast';f.route(async path=>{const id=path.includes('draftId=one')?'one':'two';return path.includes('content=1')?new Response(id,{headers:{'content-length':'3'}}):response({value:id==='one'?one:two});});f.registrations.setRefused('two');await assert.rejects(f.flow.sync(),/REGISTER_REFUSED/);assert.equal(f.flow.entry(),prior);assert.equal(f.flow.owner,owner);assert.equal(f.flow.documentId,documentId);assert.equal(f.flow.message,message);assert.equal(f.flow.historical,historical);assert.equal(f.registrations.active(),active);assert.equal(f.registrations.records.filter(record=>record.id==='one'&&record.active).length,0,'Earlier staged registration unwinds');f.registrations.setRefused(null);await f.flow.sync();await flush();assert.equal(f.flow.documentId,'next');assert.equal(f.flow.owner,f.editor.draftOwner);assert.equal(f.flow.entries.size,2);assert.deepEqual([...f.flow.entries.values()].map(entry=>entry.text).sort(),['one','two']);assert.equal(f.flow.inspectMemory().promptInput.refused,false);}finally{f.registrations.setRefused(null);await f.close();}
});

for(const boundary of ['requestUpdate','updateComplete'])test('failed '+boundary+' retains actual native-input registration until a successful release retry',async t=>{
 // Exercise the actual prompt retirement/drain boundary independently of child
 // preview retirement, whose cleanup qualification lives in its own suites.
 const f=fixture(t);let update,retiring;try{await f.initial();const active=f.registrations.active(),bytes=usage().promptBytes;f.flow.loaded=false;update=f.host.requestUpdate;f.host.requestUpdate=boundary==='requestUpdate'?()=>{throw Error('render unavailable');}:function(){this.updateComplete=Promise.reject(Error('render unavailable'));void this.updateComplete.catch(()=>{});};retiring=f.flow.releasePromptInput();await assert.rejects(retiring,/render unavailable/);assert.equal(f.flow.inspectMemory().promptInput.retired,1);assert.equal(f.registrations.active(),active);assert.equal(usage().promptBytes,bytes);f.host.requestUpdate=update;await f.flow.drainEntries();assert.equal(f.flow.inspectMemory().promptInput.retired,0);assert.equal(f.registrations.active(),active-1,'Only the native slot retires; the accepted Entry remains owned');assert(usage().promptBytes<bytes);}finally{if(update)f.host.requestUpdate=update;await retiring?.catch(()=>{});await f.close();}
});

test('document release waits for the render that retires the native input and its prebooked registration',async t=>{
 const f=fixture(t),render=deferred();let update,closing;try{await f.initial();update=f.host.requestUpdate;f.host.requestUpdate=function(){this.updateComplete=render.promise.then(()=>{update.call(this);return this.updateComplete;});};let drained=false;closing=f.flow.releaseDocument().then(()=>{drained=true;});await flush();assert.equal(drained,false);assert(f.flow.inspectMemory().promptInput.retired>0);assert(f.registrations.active()>0);f.host.requestUpdate=update;render.resolve();await closing;assert.equal(f.registrations.active(),0);assert.equal(f.flow.inspectMemory().promptInput.retired,0);assert.equal(f.flow.inspectMemory().disposed,false);await f.flow.sync();await flush();assert(f.prompt());assert.equal(f.flow.inspectMemory().promptInput.refused,false);}finally{if(update)f.host.requestUpdate=update;render.resolve();await closing;await f.close();}
});

test('a delayed canceled Retry retains the native input through retirement and releases its dispatch pin after the veto',async t=>{
 const f=fixture(t);let block;try{await f.initial();await f.input('saved');block=pressure();await f.input('full refused input');block.release();block=null;t.mock.timers.enable({apis:['setTimeout']});const saved=f.saved.length,input=f.flow.promptInput,registrations=f.registrations.active(),click=event();binding(find(f.template(),'id="request-prompt-retry"'),'@click=')(click);click.defaultPrevented=true;f.flow.loaded=false;await f.flow.releasePromptInput();await flush();assert.equal(f.flow.inspectMemory().promptInput.retired,0,'The rendered root has completed retirement');assert.equal(f.registrations.active(),registrations,'The deferred Retry still owns the retired native input');assert.equal(input.value,'full refused input');assert.equal(f.saved.length,saved);t.mock.timers.tick(0);await flush();assert.equal(f.saved.length,saved,'A late native veto cannot retry persistence');assert.equal(f.registrations.active(),registrations-1);assert.throws(()=>input.value,/REQUEST_PROMPT_RELEASED/);assert.equal(f.flow.inspectMemory().entryHolds,0);}finally{block?.release();t.mock.timers.reset();await f.close();}
});

test('superseded native notifications retain one latest event owner and save only its complete value',async t=>{
 const f=fixture(t);try{await f.initial();const accept=binding(f.prompt(),'@en-input='),saved=f.saved.length,registrations=f.registrations.active();let latest;
  for(let i=0;i<32;i++){latest=event('complete '+i+' 東京😀',{value:'complete '+i+' 東京😀',isComposing:false},f.native);accept(latest);assert.equal(f.flow.promptPending.event,latest);assert.equal(f.flow.entryHolds.size,1,'The superseded event releases its Entry hold');}
  await turn();assert.equal(f.flow.promptPending,null);assert.equal(f.flow.entry().text,'complete 31 東京😀');assert.equal(f.saved.length,saved+1);assert.equal(f.registrations.active(),registrations);assert.equal(f.flow.inspectMemory().entryHolds,0);
 }finally{await f.close();}
});

test('shortening refused native overflow remains charged until its real render and captured old action retire',async t=>{
 const f=fixture(t);let block,release,update;const render=deferred();try{await f.initial();await f.input('saved');block=pressure();const huge='x'.repeat(65536+1024)+'東京😀';await f.input(huge);const input=f.flow.promptInput,charged=usage();release=input.pin();update=f.host.requestUpdate;f.host.requestUpdate=function(){this.updateComplete=render.promise;};f.native.value='short';binding(f.prompt(),'@en-input=')(event('short',undefined,f.native));await flush();assert(usage().promptBytes>=charged.promptBytes);assert.equal(f.flow.entry().text,'saved');f.host.requestUpdate=update;f.host.requestUpdate();await flush();render.resolve();await flush();assert(usage().promptBytes>=charged.promptBytes,'Rendered replacement alone does not retire the old captured action');release();release=null;await turn();assert(usage().promptBytes<charged.promptBytes);assert.equal(f.native.value,'short');block.release();block=null;await f.click('request-prompt-retry');assert.equal(f.flow.entry().text,'short');assert.equal(f.flow.inspectMemory().promptInput.refused,false);}finally{if(update)f.host.requestUpdate=update;render.resolve();release?.();block?.release();await f.close();}
});

test('IME overflow keeps full detail charged and refuses stale public-value retry until native settlement',async t=>{
 const f=fixture(t);let block;try{await f.initial();await f.input('saved');block=pressure();binding(find(f.template(),'aria-label="Typed request draft"'),'@compositionstart=')();await flush();const full='東京😀'.repeat(18000);await f.input('saved',{value:full,isComposing:true});assert.equal(f.native.value,'saved');assert.equal(f.flow.inspectMemory().promptInput.nativeOverflow,true);const charged=usage();assert(charged.promptBytes>ALLOCATION_LIMITS.promptBytes);binding(find(f.template(),'aria-label="Typed request draft"'),'@compositionend=')();await turn();block.release();block=null;const saved=f.saved.length;await f.click('request-prompt-retry');assert.equal(f.saved.length,saved,'The stale public value cannot replace the complete refused detail');assert.equal(f.flow.entry().text,'saved');assert.equal(f.flow.promptInput.pendingValue,full);assert.equal(f.flow.inspectMemory().promptInput.refused,true);f.native.value=full;await f.click('request-prompt-retry');assert.equal(f.flow.entry().text,full);assert.equal(f.flow.inspectMemory().promptInput.refused,false);}finally{block?.release();await f.close();}
});

test('a vetoed native event retains actual overflow without publishing a saved draft',async t=>{
 const f=fixture(t);try{await f.initial();await f.input('saved');const before=f.saved.length,value='x'.repeat(65536+500),e=event(value,{value,isComposing:false},f.native);binding(f.prompt(),'@en-input=')(e);e.defaultPrevented=true;await turn();assert.equal(f.saved.length,before);assert.equal(f.flow.entry().text,'saved');assert.equal(f.native.value,value);assert.equal(f.flow.promptInput.pendingValue,value);assert.equal(f.flow.inspectMemory().promptInput.nativeOverflow,true);assert(f.flow.inspectMemory().promptInput.observedCPUBytes>=value.length*8+1024);assert.deepEqual(f.commands,[]);await f.click('request-prompt-retry');assert.equal(f.flow.entry().text,value);}finally{await f.close();}
});

test('ordinary En Reve input reads the accepted value after dispatch and preserves later author writes or change vetoes',async t=>{
 const f=fixture(t);try{await f.initial();await f.input('old accepted');const saved=f.saved.length,accept=binding(f.prompt(),'@en-input=');
  // Installed EditingController: setDraft(new), dispatch en-input, then
  // requestValue(new). The public FormField.value is still old during dispatch.
  const first=event('old accepted',{value:'new native',isComposing:false},f.native);accept(first);assert.equal(f.flow.promptInput.pendingValue,'new native','Real detail bytes are observed immediately');assert.equal(f.flow.entry().text,'old accepted');f.native.value='new native';await turn();assert.equal(f.flow.entry().text,'new native');assert.equal(f.saved.length,saved+1);
  // An author write during the notification supersedes the later default.
  const second=event('new native',{value:'proposed native',isComposing:false},f.native);binding(f.prompt(),'@en-input=')(second);f.native.value='author supplied replacement';await turn();assert.equal(f.flow.entry().text,'author supplied replacement');
  // A canceled en-change transaction rolls the accepted public value back.
  // en-input itself is a noncancelable notification and is not marked vetoed.
  const count=f.saved.length,third=event('author supplied replacement',{value:'vetoed proposal',isComposing:false},f.native);binding(f.prompt(),'@en-input=')(third);await turn();assert.equal(f.saved.length,count);assert.equal(f.flow.entry().text,'author supplied replacement');assert.equal(f.flow.inspectMemory().promptInput.refused,false);
 }finally{await f.close();}
});

test('recovered long prompt binds before a composing control is reused for an existing short draft without any input event',async t=>{
 const f=fixture(t),long='東京😀'.repeat(18000),short='retained short';try{
  f.editor.ui.drafts=['long','short'].map(id=>({kind:'request',id,documentId:'doc',generation:'1',expectedDocumentRevision:'1'}));const generated=newDraft(ref(long)),fast=newDraft(ref(short));fast.operation='fast';f.route(async path=>{const isLong=path.includes('draftId=long'),text=isLong?long:short;return path.includes('content=1')?new Response(text,{headers:{'content-length':String(Buffer.byteLength(text))}}):response({value:isLong?generated:fast});});await f.initial();assert.equal(f.flow.entry().text,long);const prior=f.flow.promptInput,node=f.native;assert.equal(prior.native,null,'No beforeinput or en-input observation has occurred');
  // Installed FormField's accepted value can change during composition while
  // its actual draft remains unchanged until a later native composition end.
  let accepted=node.value,draft=accepted,composing=true;Object.defineProperty(node,'value',{get(){return accepted;},set(value){accepted=value;if(!composing)draft=value;},configurable:true});binding(find(f.template(),'aria-label="Typed request draft"'),'@compositionstart=')();await flush();f.flow.operationChanged('Generate with Fast');await f.render();await turn();assert.equal(f.flow.entry().text,short);assert.equal(f.native,node,'The renderer reuses the connected native control');assert.equal(accepted,short);assert.equal(draft,long,'The older actual composing draft has not been replaced');const next=f.flow.promptInput;assert.notEqual(next,prior);assert(next.capacity>=long.length);assert(next.observedCPUBytes>=long.length*8+1024);assert.equal(f.flow.inspectMemory().promptInput.retired,0,'A fully admitted successor now owns the old native floor');assert.throws(()=>prior.value,/REQUEST_PROMPT_RELEASED/);composing=false;
 }finally{await f.close();}
});
