// Source-only response ownership regressions. Run only after the coordinated gate.
// REQUEST_RESPONSES_ROOT selects migrated request.ts; support modules come from
// REQUEST_RESPONSE_SUPPORT_ROOT (or promoted source), UIModelOwner from UI_MODEL_ROOT.
import {allocationsURL as ledgerURL,promptMemoryURL as promptURL,compositionObservationsURL} from '../owned-preview-module.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {transformWithOxc} from 'vite';
const root=process.env.REQUEST_PROMPT_ROOT??process.env.REQUEST_RESPONSES_ROOT??'.',support=process.env.REQUEST_RESPONSE_SUPPORT_ROOT??'.',data=code=>'data:text/javascript;base64,'+Buffer.from(code).toString('base64'),compiled=name=>pathToFileURL(resolve('dist/local/src/'+name+'.js')).href;
async function source(path,imports={}){const original=await readFile(path,'utf8');let code=(await transformWithOxc(original,path)).code;for(const [name,url]of Object.entries(imports))code=code.replaceAll(JSON.stringify(name),JSON.stringify(url)).replaceAll("'"+name+"'",JSON.stringify(url));return data(code+'\n//# sourceURL=ideogram-request-response-fixture/'+path+'?sha256='+createHash('sha256').update(original).digest('hex')+'\n');}
const modelURL=await source('src/observability/model-memory.ts',{'./allocations.js':ledgerURL,'./prompt-memory.js':promptURL});
async function stateSource(name,imports){for(const stateRoot of [process.env.IE_DRAFT_METADATA_SOURCE_ROOT,process.env.CLIENT_CONTROL_ROOT,'.'].filter(Boolean)){try{return await source(stateRoot+'/src/state/'+name+'.ts',imports);}catch(error){if(error.code!=='ENOENT')throw error;}}throw Error('Missing effective draft source '+name);}
const stateImports={'../observability/allocations.js':ledgerURL,'../observability/prompt-memory.js':promptURL,'../observability/model-memory.js':modelURL};
const controlURL=await stateSource('control-memory',stateImports);
const commandURL=await stateSource('command-results',{...stateImports,'./control-memory.js':controlURL,...Object.fromEntries(['protocol/json','protocol/sha256','protocol/validate'].map(name=>['../'+name+'.js',pathToFileURL(resolve('dist/local/src/'+name+'.js')).href]))});
const draftValuesURL=await stateSource('draft-values',{...stateImports,'./control-memory.js':controlURL});
const persistenceURL=await stateSource('draft-persistence',{...stateImports,'./control-memory.js':controlURL,'./command-results.js':commandURL,'./draft-values.js':draftValuesURL});
const compositionViewURL=await source('src/composition/view.ts');
const compositionURL=await source('src/composition/core.ts'),compositionMemoryURL=await source('src/composition/memory.ts',{'./view.js':compositionViewURL,'./core.js':compositionURL,'../observability/allocations.js':ledgerURL,'../observability/prompt-memory.js':promptURL,'../observability/composition-observations.js':compositionObservationsURL}),entryURL=await source(support+'/src/ui/request-entry-memory.ts',{'../observability/model-memory.js':modelURL,'../observability/prompt-memory.js':promptURL}),ownerURL=await source((process.env.UI_MODEL_ROOT??'.')+'/src/ui/model-owner.ts',{'../observability/model-memory.js':modelURL,'../observability/prompt-memory.js':promptURL}),navigationURL=await source(support+'/src/ui/request-navigation-memory.ts',{'../observability/model-memory.js':modelURL,'./model-owner.js':ownerURL});
const promptInputURL=await source(root+'/src/ui/request-prompt-memory.ts',{'../observability/prompt-memory.js':promptURL,'../observability/allocations.js':ledgerURL});
const lit=data('export const nothing=null;export const noChange=Symbol.for("lit-noChange");export const html=(strings,...values)=>({strings,values});');
const children=data(`export class AdapterLibraryEditing{dispose(){}render(){return null;}renderJobUpdates(){return null;}async eligibility(){return {adapters:new Map()};}}export class RequestEdits{dispose(){}async sync(){}retainCandidates(){}prepareCandidates(){return {commit(){},release(){}};}renderSourceMask(){return null;}renderCandidate(){return null;}renderCandidateNavigator(){return null;}}export class V45EditInputsEditing{dispose(){}render(){return null;}}export class TextTreatmentEditing{dispose(){}async drain(){}intent(){return null;}render(){return null;}}export class ReturnedDescriptionEditing{async releaseDocument(){}render(){return null;}}export const renderV45EditSettings=()=>null,renderV45EditReview=()=>null,renderV45Generation=()=>null,renderV45GenerationReview=()=>null,renderV45UnavailableResultMetadata=()=>null,renderRequestEstimate=()=>null;`);
const display=data('export const displayImage=value=>value;export function revokeDisplayPreviewURL(){}export function displayPreviewInfo(){return null;}export async function readDisplaySource(){throw Error("Unexpected display read");}export const withDisplaySource=readDisplaySource;export async function createDisplayPreviewURL(){throw Error("Unexpected display preview");}export function validateDisplayImage(){throw Error("Unexpected display validation");}');
const compositionTextImports={'lit':lit,'../composition/text-export.js':compiled('composition/text-export'),'../protocol/json.js':compiled('protocol/json'),'../observability/model-memory.js':modelURL,'../observability/prompt-memory.js':promptURL};
// Historical partial request overlays may omit this newly introduced helper.
const compositionTextURL=await source(root+'/src/ui/request-composition-text.ts',compositionTextImports).catch(error=>{if(error.code!=='ENOENT')throw error;return source('src/ui/request-composition-text.ts',compositionTextImports);});
const keyboardScopeURL=await source(root+'/src/ui/keyboard-scope.ts').catch(error=>{if(error.code!=='ENOENT')throw error;return source('src/ui/keyboard-scope.ts');});
const controllerURL=await source(root+'/src/ui/request.ts',{'../observability/composition-observations.js':compositionObservationsURL,'lit':lit,'lit/directives/repeat.js':data('export const repeat=(items,key,render)=>Array.from(items,render);'),'./adapters.js':await source('src/ui/adapters.ts'),'./display-image.js':display,'../observability/display-preview.js':display,'../observability/prompt-memory.js':promptURL,'../observability/model-memory.js':modelURL,'./request-entry-memory.js':entryURL,'./request-prompt-memory.js':promptInputURL,'./request-navigation-memory.js':navigationURL,'./request-composition-text.js':compositionTextURL,'./keyboard-scope.js':keyboardScopeURL,'../composition/core.js':compositionURL,'../composition/memory.js':compositionMemoryURL,...Object.fromEntries(['adapter-library','request-edits','request-v45-edit','request-v45','text-treatment','returned-description'].map(name=>['./'+name+'.js',children])),...Object.fromEntries(['protocol/asset-projection','protocol/json','request/core','request/family'].map(name=>['../'+name+'.js',compiled(name)]))});
const {RequestEditing}=await import(controllerURL),{allocationLedger}=await import(ledgerURL),{createOwnedModel,modelPayloadBytes,readOwnedJSON}=await import(modelURL),{DraftPersistence}=await import(persistenceURL),{newDraft,hash}=await import(compiled('request/core'));
const flush=async()=>{for(let n=0;n<100;n++)await Promise.resolve();},turn=async()=>{await new Promise(resolve=>setTimeout(resolve,0));await new Promise(setImmediate);await flush();},deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};},until=async condition=>{const end=Date.now()+2000;while(!condition()){assert(Date.now()<end,'Expected asynchronous fixture boundary');await new Promise(setImmediate);}};
const usage=()=>{const s=allocationLedger.snapshot();return {cpuBytes:s.cpuBytes,promptBytes:s.promptBytes,handles:s.handles,activeRecords:s.activeRecords};},ref=(text,mediaType='text/plain')=>({hash:hash(text),byteLength:String(Buffer.byteLength(text)),mediaType}),response=value=>{const text=JSON.stringify(value);return new Response(text,{headers:{'content-length':String(Buffer.byteLength(text))}});},textResponse=text=>new Response(text,{headers:{'content-length':String(Buffer.byteLength(text))}});
// Accessors remain cloneable, unlike proxies. Borrowed nested graphs fail closed
// after the last real owner/pin is released, exposing premature result release.
function guardedGraph(value,live){const cache=new WeakMap();const wrap=item=>{if(!item||typeof item!=='object')return item;if(cache.has(item))return cache.get(item);const result=Array.isArray(item)?[]:{};cache.set(item,result);for(const key of Object.keys(item)){const nested=wrap(item[key]);Object.defineProperty(result,key,{enumerable:true,configurable:true,get(){assert(live(),'Borrowed response graph read after release');return nested;}});}return result;};return wrap(value);}
// Diagnostic labels keep command casing; allocation owners use the ledger's lowercase identifier grammar.
function tracked(value,label,kind='control'){const owned=createOwnedModel('request-response-'+label.toLowerCase(),modelPayloadBytes(value)+256,()=>structuredClone(value),kind),record={label,releases:0,pins:0,accesses:0};let retained=true;const live=()=>retained||record.pins>0,graph=guardedGraph(owned.value,live);const model={get value(){record.accesses++;assert(live(),'Response root read after release');return graph;},pin(){assert(live());const unpin=owned.pin();record.pins++;let held=true;return ()=>{assert(held,'Pin released twice');held=false;record.pins--;unpin();};},release(){assert(retained,'Response released twice');retained=false;record.releases++;owned.release();}};return {model,record,live,graph,borrowedReview:Object.hasOwn(graph,'review')?graph.review:undefined};}
const reviewValue=()=>({kind:'request-review-1',id:'review',token:'token',documentId:'doc',documentRevision:'1',endpoint:'ideogram/v4',request:{kind:'generate',settings:{count:1},adapters:[]},prompt:ref('Exact prompt'),estimate:{rate:0.015,unit:'megapixel',count:1,source:'fixture',unknown:[]},dispatch:false});
function fixture(t,{checkpoint={drafts:[]}}={}){const baseline=usage(),responses=[],uiRoots=[],reads=[],commands=[],uploads=[],reviews=[],owners=[];let flow,route=async path=>{throw Error('Unexpected transport '+path);},uploadHook=null,reviewHook=null,commandHook=null,ui=makeUI(checkpoint),closed=false;
 function makeUI(value){const root=tracked(value,'ui','control');uiRoots.push(root);return root;}
 const own=(value,label)=>{const root=tracked(value,label);responses.push(root);return root;};
 const editor={documentEpoch:1,sessionId:'session',view:{ready:true,document:{id:'doc',revision:'1',width:512,height:512},image:{layers:[]},selected:[]},session:{identity:()=> 'client',transport(path,init){reads.push(path);return path.endsWith('/request-reviews')?Promise.resolve(response({items:[]})):route(path,init);}},get ui(){return ui.model.value;},registerDraft(id,documentId){if(!this.draftOwner||this.view.document?.id!==documentId)throw Error('DRAFT_OWNER_CHANGED');return this.draftOwner.registerDraft(id,documentId);},pinUI(){return ui.model.pin();},json(){assert.fail('Raw JSON API is forbidden in this response ownership fixture');},command(){assert.fail('Raw command API is forbidden');},upload(){assert.fail('Raw upload API is forbidden');},requestReview(){assert.fail('Raw request-review API is forbidden');},ownedJSON(path,owner,init,owns,maxBytes,kind){return readOwnedJSON(this.session.transport.bind(this.session),path,{owner,init,owns,maxBytes,kind});},changeDraft(id,kind,text,targetLayerId,composing,expectedDocumentRevision){this.draftOwner.change({id,kind,text,targetLayerId,composing,expectedDocumentRevision,documentId:this.view.document.id});},async flushDrafts(){for(const value of this.draftOwner.drafts.values())value.savedGeneration=value.generation;},async ownedUpload(...args){uploads.push(args);return uploadHook?uploadHook(...args):own({stagingId:'stage',sha256:hash('original'),expectedBytes:'8',purpose:'image',mediaType:'image/png',fileName:'original.png'},'upload').model;},async ownedRequestReview(body){reviews.push(structuredClone(body));return reviewHook?reviewHook(body):own(body.type==='PrepareRequestReview'?{review:reviewValue(),requestId:'prepare'}:{acceptedReview:'review',requestId:'acceptance'},body.type).model;},async ownedCommand(body,target){commands.push({body:structuredClone(body),target});const events=body.type==='FinalizeStaging'?[{type:'AssetRegistered',payload:{asset:{id:'recovered-asset',version:'1'}}}]:[{type:'QueueStateChanged',payload:{}}],root=own(events,body.type);try{if(commandHook)await commandHook(body,root);return root.model;}catch(error){root.model.release();throw error;}},async withCommandEvents(body,work,target,newId,onJournaled){const model=await this.ownedCommand(body,target,newId,onJournaled);try{return await work(model.value);}finally{model.release();}}};
 const owner=new DraftPersistence('session',editor.session.transport.bind(editor.session),()=> 'csrf');owner.checkpoint={drafts:[],uiSeq:'1'};editor.draftOwner=owner;owners.push(owner);const host={requestUpdate(){this.updateComplete=Promise.resolve().then(()=>flow.render());},updateComplete:Promise.resolve(),querySelector(selector){return selector==='#prompt'?null:{focus(){}};}};flow=new RequestEditing(host,editor);
 // Queue rendering/pagination is independently covered. Keep the real queue
 // command callback and its response scope, while avoiding an unrelated refresh.
 flow.refreshQueue=async()=>{};
 const close=async()=>{if(closed)return;closed=true;await flow.dispose();for(const owner of owners)await owner.dispose();if(ui.record.releases===0)ui.model.release();await turn();assert(responses.every(root=>root.record.releases===1),'Every owned response is released exactly once');assert(uiRoots.every(root=>root.record.pins===0&&root.record.releases===1),'Every UI checkpoint root and pin is released');assert.deepEqual(usage(),baseline);};t.after(close);
 return {flow,editor,host,reads,commands,uploads,reviews,responses,uiRoots,own,close,route:fn=>route=fn,setUpload:fn=>uploadHook=fn,setReview:fn=>reviewHook=fn,setCommand:fn=>commandHook=fn,currentUI:()=>ui,replaceUI(value){const old=ui;ui=makeUI(value);old.model.release();return old;},async initial(){await flow.sync();await flush();},async prompt(){await flow.sync();flow.mutateEntry('Exact prompt',next=>{next.text='Exact prompt';});await flush();}};
}

test('prepared review receives an independent admitted graph before its owned receipt releases',async t=>{const f=fixture(t);await f.prompt();await f.flow.prepare();const root=f.responses.find(root=>root.record.label==='PrepareRequestReview');assert(root);assert.equal(root.record.releases,1);assert.equal(f.flow.review.id,'review');assert.notEqual(f.flow.review,root.borrowedReview);assert.equal(f.flow.reviewJSON,JSON.stringify(f.flow.review,null,2));assert.doesNotThrow(()=>f.flow.render());await f.close();});

for(const outcome of ['stale','invalid-review'])test('prepared-review receipt releases on '+outcome,async t=>{const f=fixture(t),gate=deferred();await f.prompt();f.setReview(()=>gate.promise);const work=f.flow.prepare();await until(()=>f.reviews.length===1);if(outcome==='stale')f.flow.mutateEntry('later',next=>{next.text='later';});const root=f.own({review:outcome==='invalid-review'?{...reviewValue(),oversize:'x'.repeat(65537)}:reviewValue()},'prepared-late');gate.resolve(root.model);if(outcome==='invalid-review')await assert.rejects(work,/REQUEST_REVIEW_LIMIT/);else await work;assert.equal(root.record.releases,1);assert.equal(f.flow.review,null);await f.close();});

for(const outcome of ['accepted','stale'])test('acceptance receipt releases after '+outcome+' result handling',async t=>{const f=fixture(t),gate=deferred();await f.prompt();f.flow.review=reviewValue();f.setReview(()=>gate.promise);const work=f.flow.accept();await until(()=>f.reviews.length===1);if(outcome==='stale')f.flow.mutateEntry('later',next=>{next.text='later';});const root=f.own({acceptedReview:'review',requestId:'acceptance'},'accept');gate.resolve(root.model);await work;assert.equal(root.record.releases,1);assert.equal(f.flow.accepted,outcome==='accepted');assert.equal(f.flow.acceptanceId,outcome==='accepted'?'acceptance':'');await f.close();});

function savedCheckpoint(){return {drafts:[{kind:'request',documentId:'doc',id:'saved-request',generation:'1',expectedDocumentRevision:'1'},{kind:'prompt',documentId:'doc',id:'saved-legacy',generation:'1',assetId:'legacy-asset',expectedDocumentRevision:'1'}]};}
test('restore pins one checkpoint across both saved-request and legacy-prompt loops despite UI replacement',async t=>{const f=fixture(t,{checkpoint:savedCheckpoint()}),gate=deferred(),old=f.currentUI(),requestText='Restored request',legacy=JSON.stringify({schema:'editor-prompt-1',operation:'Generate with Fast',text:'Legacy retained'});f.route(async path=>path.includes('draftId=saved-request')?path.includes('content=1')?gate.promise:response({value:newDraft(ref(requestText))}):path==='/api/v1/assets/legacy-asset/content'?textResponse(legacy):assert.fail('Unexpected restore read '+path));const work=f.flow.sync();await until(()=>f.reads.some(path=>path.includes('content=1')));assert.equal(old.record.pins,1);f.replaceUI({drafts:[]});assert.equal(old.record.releases,1);assert.equal(old.live(),true,'The old checkpoint remains live through its restoration pin');gate.resolve(textResponse(requestText));await work;assert.equal(old.record.pins,0);assert.equal(old.live(),false);assert.deepEqual([...f.flow.entries.values()].map(entry=>entry.text).sort(),['Legacy retained','Restored request']);assert.equal(f.reads.filter(path=>path==='/api/v1/assets/legacy-asset/content').length,1);assert.doesNotThrow(()=>f.flow.render());await f.close();});

for(const outcome of ['read-failure','stale-document'])test('saved-checkpoint pin releases on '+outcome+' restoration exit',async t=>{const f=fixture(t,{checkpoint:savedCheckpoint()}),gate=deferred(),old=f.currentUI();f.route(async()=>gate.promise);const work=f.flow.sync();await until(()=>f.reads.some(path=>path.includes('draftId=saved-request')));assert.equal(old.record.pins,1);if(outcome==='read-failure')gate.reject(Error('metadata unavailable'));else{f.editor.view.document={...f.editor.view.document,id:'replacement'};f.editor.documentEpoch++;gate.resolve(response({value:newDraft(ref('Restored'))}));}if(outcome==='read-failure')await assert.rejects(work,/metadata unavailable/);else await work;assert.equal(old.record.pins,0);assert.equal(f.flow.entries.size,0);await f.close();});

function repair(f){const file=new File(['original'],'original.png',{type:'image/png'});f.flow.setRepairFile('candidate',file);return {file,expected:ref('original','image/png')};}
test('repair owns upload and finalize results through the pending recovery command and copies expected identity before upload',async t=>{const f=fixture(t),upload=deferred(),recover=deferred();await f.initial();const {file,expected}=repair(f),identity=f.own(expected,'repair-identity');f.setUpload(()=>upload.promise);f.setCommand(body=>body.type==='RecoverCandidateOriginal'?recover.promise:undefined);const work=f.flow.recoverOriginal('candidate','4',identity.model.value);await until(()=>f.uploads.length===1);identity.model.release();const stage=f.own({stagingId:'stage',sha256:expected.hash,expectedBytes:expected.byteLength},'repair-upload');upload.resolve(stage.model);await until(()=>f.commands.some(call=>call.body.type==='RecoverCandidateOriginal'));const finalize=f.responses.find(root=>root.record.label==='FinalizeStaging');assert.equal(stage.record.releases,0);assert.equal(finalize.record.releases,0);assert.equal(f.flow.repairFiles.get('candidate'),file);assert.deepEqual(f.commands.map(call=>call.body),[{type:'FinalizeStaging',stagingId:'stage',expectedSha256:expected.hash},{type:'RecoverCandidateOriginal',candidateId:'candidate',expectedVersion:'4',assetId:'recovered-asset'}]);recover.resolve();await work;assert.equal(stage.record.releases,1);assert.equal(finalize.record.releases,1);assert.equal(f.flow.repairFiles.has('candidate'),false);await f.close();});

for(const mismatch of ['sha256','expectedBytes'])test('repair '+mismatch+' mismatch releases upload without finalizing or clearing the selected file',async t=>{const f=fixture(t);await f.initial();const {file,expected}=repair(f),stage=f.own({stagingId:'stage',sha256:expected.hash,expectedBytes:expected.byteLength,[mismatch]:mismatch==='sha256'?hash('other'):'9'},'mismatch');f.setUpload(()=>stage.model);await assert.rejects(f.flow.recoverOriginal('candidate','4',expected),/does not match/);assert.equal(stage.record.releases,1);assert.deepEqual(f.commands,[]);assert.equal(f.flow.repairFiles.get('candidate'),file);await f.close();});

test('a stale upload releases its result without entering finalization',async t=>{const f=fixture(t),gate=deferred();await f.initial();const {file,expected}=repair(f);f.setUpload(()=>gate.promise);const work=f.flow.recoverOriginal('candidate','4',expected);f.flow.mutateEntry('later',next=>{next.text='later';});const stage=f.own({stagingId:'stage',sha256:expected.hash,expectedBytes:expected.byteLength},'stale-upload');gate.resolve(stage.model);await work;assert.equal(stage.record.releases,1);assert.deepEqual(f.commands,[]);assert.equal(f.flow.repairFiles.get('candidate'),file);await f.close();});

test('failure in the nested recovery command releases upload and finalize scopes and keeps the file',async t=>{const f=fixture(t);await f.initial();const {file,expected}=repair(f);f.setCommand(body=>{if(body.type==='RecoverCandidateOriginal')throw Error('recovery unavailable');});await assert.rejects(f.flow.recoverOriginal('candidate','4',expected),/recovery unavailable/);for(const root of f.responses)assert.equal(root.record.releases,1);assert.equal(f.flow.repairFiles.get('candidate'),file);await f.close();});

for(const replacement of ['file','draft'])test('repair completion preserves a replacement '+replacement+' while releasing both result scopes',async t=>{const f=fixture(t),gate=deferred();await f.initial();const {file,expected}=repair(f);f.setCommand(body=>body.type==='RecoverCandidateOriginal'?gate.promise:undefined);const work=f.flow.recoverOriginal('candidate','4',expected);await until(()=>f.commands.some(call=>call.body.type==='RecoverCandidateOriginal'));let retained=file;if(replacement==='file'){retained=new File(['new original'],'replacement.png',{type:'image/png'});f.flow.setRepairFile('candidate',retained);}else f.flow.mutateEntry('later',next=>{next.text='later';});gate.resolve();await work;assert.equal(f.flow.repairFiles.get('candidate'),retained);for(const root of f.responses)assert.equal(root.record.releases,1);await f.close();});


const {compositionObservations:inspectionObserver}=await import(compositionObservationsURL);
function inspectionSnapshot(){const owner=inspectionObserver.readSnapshot();try{return structuredClone(owner.value);}finally{owner.release();}}
function promptView(source){return {protocolVersion:1,jobId:'job',documentId:'doc',request:{endpoint:'ideogram/v4',prompt:source,seed:null},observation:null,requestedCount:1,actualCount:0,items:[],provenance:null,inert:false,nextCursor:null};}
test('prompt inspection binds a trimmed UTF8 page to the captured retained source',async t=>{
 const f=fixture(t);await f.initial();const text='a'.repeat(32767)+'é',source=ref(text);f.flow.candidateViews.set('attempt',promptView(source));
 f.route(async()=>response({bytes:Buffer.from(text.slice(0,32767)).toString('base64'),byteLength:source.byteLength,offset:'0',nextOffset:'32767'}));const before=inspectionSnapshot();await f.flow.readPrompt('job','attempt','requested');
 const after=inspectionSnapshot(),rows=after.records.filter(row=>row.sequence>before.cursor);assert.equal(f.flow.promptPage.text.length,32767);assert.equal(f.flow.promptPage.next,'32767');
 assert.deepEqual(rows.filter(row=>row.kind==='raw-inspection-begin').map(row=>[row.sourceHash,row.sourceBytes,row.offset]),[[source.hash,32769,0]]);assert.deepEqual(rows.filter(row=>row.kind==='raw-inspection-read').map(row=>row.receivedBytes),[32767]);assert.deepEqual(rows.filter(row=>row.kind==='raw-inspection-end').map(row=>row.outcome),['page']);assert.equal(after.activeInspections,0);
});
for(const defect of ['length','offset','next','short','terminal-short','missing-source'])test('prompt inspection rejects '+defect+' and cannot complete its source witness',async t=>{
 const f=fixture(t);await f.initial();const text='abcdef',source=ref(text);if(defect!=='missing-source')f.flow.candidateViews.set('attempt',promptView(source));
 f.route(async()=>response({bytes:Buffer.from(defect==='short'?'a':defect==='terminal-short'?'abc':text).toString('base64'),byteLength:defect==='length'?'7':source.byteLength,offset:defect==='offset'?'1':'0',nextOffset:defect==='next'?'6':defect==='terminal-short'?'3':null}));const before=inspectionSnapshot();await assert.rejects(f.flow.readPrompt('job','attempt','requested'),/PROMPT_PAGE_/);
 const after=inspectionSnapshot(),rows=after.records.filter(row=>row.sequence>before.cursor);assert.equal(f.flow.promptPage,null);assert.equal(after.activeInspections,0);assert.deepEqual(rows.filter(row=>row.kind==='raw-inspection-end').map(row=>row.outcome),defect==='missing-source'?[]:['failed']);
});
