import {confirmImageImports} from '../editor/image-import-flow.js';
import {test as base,expect,type Page,type BrowserContext,type Request,type Response,type ConsoleMessage} from '@playwright/test';
import {mkdtemp,realpath,mkdir,writeFile,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {serverProcess} from '../editor/process.js';import {ownedOPFS} from '../editor/owned-opfs.js';import {recordDOMErrors} from '../editor/error-monitor.js';
import {runs,step,throwFailures,finishFixture,type RunState} from '../editor/harness-lifecycle.js';
const test=base.extend({context:async({playwright,browserName,contextOptions,viewport},use,testInfo)=>{
 const profile=browserName==='webkit'?await mkdtemp(join(await realpath(tmpdir()),'ie-p2-request-webkit-')):undefined;
 const browser=profile?undefined:await playwright[browserName].launch();const context=profile?await playwright.webkit.launchPersistentContext(profile,{...contextOptions,viewport}):await browser!.newContext({...contextOptions,viewport});await Promise.all(context.pages().map(p=>p.close()));
 try{await use(context);}finally{await finishFixture(context,browser,profile,receipt,testInfo.title.split(' ')[2]+'-',testInfo);}
}});
const receipt=process.env.EDITOR_RECEIPT??'artifacts/p2-request';const click=(page:Page,name:string)=>page.getByRole('button',{name,exact:true}).click();
// Visible feedback and the dedicated live region are separate public surfaces.
async function requestFeedback(page:Page,text:string){
 const region=page.getByRole('region',{name:'Typed request draft',exact:true}),group=region.getByRole('group',{name:'Request draft keyboard actions',exact:true}),feedback=group.locator(':scope > en-alert[announcement="none"]'),status=group.getByRole('status',{name:'Request status',exact:true});
 await expect(feedback).toHaveText(text);await expect(feedback).toBeVisible();await expect(status).toHaveText(text);await expect(status).toHaveAttribute('aria-live','polite');await expect(status).toHaveAttribute('aria-atomic','true');
}
async function number(page:Page,name:string,value:string){const f=page.getByRole('spinbutton',{name,exact:true});await f.fill(value);await f.press('Tab');}
// Pass-through metadata only. Join retained request identities; bounded loss is explicit.
function observeRequestTransport(context:BrowserContext,page:Page){
 const limit=1024,rows:Record<string,unknown>[]=[],ids=new WeakMap<Request,number>();let nextId=0,sequence=0,requests=0,responses=0,consoleErrors=0,dropped=0,readFailures=0,truncatedFields=0,stopped=false;
 const bounded=(value:string,limit:number)=>{if(value.length<=limit)return value;truncatedFields++;return value.slice(0,limit);};
 const location=(raw:string,includeDisplayQuery=true)=>{if(!raw)return {available:false};try{const url=new URL(raw),display=includeDisplayQuery&&/^\/api\/v1\/assets\/[^/]+\/display(?:-tile)?$/.test(url.pathname),query:[string,string][]=[];let omittedQueryValues=0;
  for(const [key,value]of url.searchParams){if(display&&['identity','basis','edge','lod','x','y'].includes(key)&&query.length<8)query.push([key,bounded(value,128)]);else omittedQueryValues++;}
  return {available:true,origin:bounded(url.origin,256),path:bounded(url.pathname,512),displayQuery:query,omittedQueryValues};
 }catch{return {available:false,invalid:true};}};
 const id=(request:Request)=>{let value=ids.get(request);if(value===undefined){value=++nextId;ids.set(request,value);}return value;};
 const record=(event:string,read:()=>Record<string,unknown>)=>{const current=++sequence;if(stopped)return;if(rows.length>=limit){dropped++;return;}try{rows.push({sequence:current,at:Date.now(),event,...read()});}catch{readFailures++;}};
 const request=(value:Request)=>{requests++;record('request',()=>({requestId:id(value),method:bounded(value.method(),16),resourceType:bounded(value.resourceType(),32),location:location(value.url())}));};
 const response=(value:Response)=>{responses++;record('response',()=>{const request=value.request(),requestObserved=ids.has(request);return {requestId:id(request),requestObserved,status:value.status(),method:bounded(request.method(),16),resourceType:bounded(request.resourceType(),32),location:location(request.url())};});};
 const consoleError=(value:ConsoleMessage)=>{if(value.type()!=='error')return;consoleErrors++;record('console-error',()=>{const source=value.location();return {location:location(source.url,false),lineNumber:Number.isFinite(source.lineNumber)?source.lineNumber:null,columnNumber:Number.isFinite(source.columnNumber)?source.columnNumber:null};});};
 context.on('request',request);context.on('response',response);page.on('console',consoleError);
 return {snapshot:()=>({schemaVersion:1,scope:'Synchronous public Playwright metadata; no response bodies or headers read.',limit,requests,responses,consoleErrors,dropped,readFailures,truncatedFields,stopped,rows}),stop(){if(stopped)return;stopped=true;context.off('request',request);context.off('response',response);page.off('console',consoleError);}};
}
for(const scenario of ['review','recovery','source','adapters'] as const)test('public request '+scenario+' binds exact accepted values with no dispatch',async({page,context,browserName},testInfo)=>{
 const guard=await ownedOPFS(context,'p2-request-'+scenario),errors=await recordDOMErrors(context),csp:unknown[]=[],requests:any[]=[],responses:any[]=[],external:string[]=[],consoleErrors:string[]=[],publicEvents:unknown[]=[];
 await context.exposeBinding('requestEvent',(_source,value)=>publicEvents.push(value));await context.addInitScript(()=>{for(const type of ['click','keydown','focusin','en-input','en-change','compositionstart','compositionend'])addEventListener(type,e=>{const target=e.target as HTMLElement;if(!target.closest?.('.typed-request'))return;setTimeout(()=>(window as any).requestEvent({type,target:target.id||target.tagName,key:(e as KeyboardEvent).key,cancelled:e.defaultPrevented,active:document.activeElement?.id,issues:(document.querySelector('#request-errors') as any)?.items}),0);});});
 await context.exposeBinding('requestCSP',(_source,value)=>csp.push(value));await context.addInitScript(()=>addEventListener('securitypolicyviolation',e=>(window as any).requestCSP({directive:e.effectiveDirective,blocked:e.blockedURI})));
 page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('request',r=>{if(r.method()==='POST'&&r.url().includes('/api/v1/ui/'))requests.push(JSON.parse(r.postData()!));});
 const dir=await mkdtemp(join(await realpath(tmpdir()),'ie-p2-request-')),server=await serverProcess(join(dir,'private'));let effects:unknown,runtime:unknown;const responseWork:Promise<void>[]=[],transportDiagnostics=observeRequestTransport(context,page);
 const state:RunState={failures:[],roots:[dir],writerClosed:false,contextClosed:false,browserClosed:false,retention:[],receipt,prefix:scenario+'-'};runs.set(context,state);
 state.observe=()=>({runtime,errors,csp,external,consoleErrors,publicEvents,requests,responses,requestLifecycle:guard.requests,transportDiagnostics:transportDiagnostics.snapshot(),effects,cleanup:{opfs:guard.ledger,serverClosed:state.writerClosed,privateRootRemoved:state.retention.some((r:any)=>r.root===dir&&r.removed)?dir:null}});
 state.finalCheck=async()=>{guard.verify();expect(guard.ledger.filter(e=>e.phase==='refused')).toEqual([]);expect(errors).toEqual([]);expect(csp).toEqual([]);expect(external).toEqual([]);expect(consoleErrors).toEqual([]);};
 await page.route('**/*',route=>{const u=new URL(route.request().url());if(['http:','https:'].includes(u.protocol)&&u.origin!==server.origin){external.push(u.origin);return route.abort();}return route.continue();});
 page.on('response',r=>{if(r.request().method()==='POST'&&r.url().includes('/api/v1/ui/'))responseWork.push(r.json().then(body=>{responses.push(body);}));});await mkdir(receipt,{recursive:true});
 try{await guard.admit(page,server.origin);await page.goto(await server.pair());runtime={version:context.browser()?.version(),pin:JSON.parse(await readFile('node_modules/playwright-core/browsers.json','utf8')).browsers.find((b:any)=>b.name===browserName)};
  await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await click(page,'New');await number(page,'Width (px)','1024');await number(page,'Height (px)','1024');await click(page,'Create');await expect(page.getByRole('dialog',{name:'New document',exact:true})).toBeHidden();
  const prompt=page.getByRole('textbox',{name:'Prompt',exact:true});await expect(prompt).toBeVisible();await prompt.fill('Café\n東京 exact request');
  if(scenario==='review'){
   await page.getByRole('combobox',{name:'Operation',exact:true}).selectOption('Generate with Fast');await click(page,'Review exact request');await expect(page.locator('#request-errors')).toContainText('acceleration');await page.locator('#request-errors').getByRole('link').first().click();await expect(page.getByRole('combobox',{name:'Acceleration',exact:true})).toBeFocused();await click(page,'Keep acceleration inactive in this draft');await expect(page.getByText('acceleration is confirmed inactive for this operation.',{exact:true})).toBeVisible();
   for(const [label,value,code,repair] of [['Output count','0','COUNT','1'],['Output width','','SIZE','1024']]){
    const input=page.getByRole('spinbutton',{name:label,exact:true});await number(page,label,value);await click(page,'Review exact request');await expect(input).toHaveValue(value);await expect(input).toHaveAttribute('aria-invalid','true');await expect(page.locator('#request-errors')).toBeFocused();await page.locator('#request-errors').getByRole('link',{name:new RegExp(code+':')}).click();await expect(input).toBeFocused();expect(requests.filter(r=>r.body.type==='PrepareRequestReview')).toHaveLength(0);await number(page,label,repair);await expect(input).not.toHaveAttribute('aria-invalid','true');await expect(page.locator('#request-errors')).toBeHidden();
   }
   const seed=page.getByRole('textbox',{name:'Exact seed (empty means Random)',exact:true});await seed.fill('1.5');await click(page,'Review exact request');await expect(seed).toHaveValue('1.5');await expect(seed).toHaveAttribute('aria-invalid','true');await page.locator('#request-errors').getByRole('link',{name:/SEED:/}).click();await expect(seed).toBeFocused();await seed.fill('');await expect(seed).not.toHaveAttribute('aria-invalid','true');
   await number(page,'Output width','1600');await number(page,'Output height','900');await click(page,'Review exact request');await expect(page.locator('#request-errors')).toContainText('SIZE');await expect(page.getByRole('spinbutton',{name:'Output height',exact:true})).toHaveValue('900');await expect(page.getByRole('spinbutton',{name:'Output height',exact:true})).toHaveAttribute('aria-invalid','true');await expect(page.getByRole('spinbutton',{name:'Output width',exact:true})).not.toHaveAttribute('aria-invalid','true');await page.locator('#request-errors').getByRole('link',{name:/SIZE:/}).click();await expect(page.getByRole('spinbutton',{name:'Output height',exact:true})).toBeFocused();await number(page,'Output height','896');await expect(page.getByRole('spinbutton',{name:'Output height',exact:true})).not.toHaveAttribute('aria-invalid','true');
   await page.getByRole('textbox',{name:'Exact seed (empty means Random)',exact:true}).fill('900719925474099312345');
   await page.locator('#prepare-request').evaluate(el=>el.addEventListener('click',e=>e.preventDefault(),{once:true}));await click(page,'Review exact request');expect(requests.filter(r=>r.body.type==='PrepareRequestReview')).toHaveLength(0);
   await page.getByRole('button',{name:'Review exact request',exact:true}).focus();await expect(page.getByRole('button',{name:'Review exact request',exact:true})).toBeFocused();await page.keyboard.press('Enter');await expect(page.getByRole('heading',{name:'Immutable request review',exact:true})).toBeVisible();await expect(page.locator('#request-review')).toBeFocused();await expect(page.locator('#request-review')).toContainText('ideogram/v4/fast');
   await click(page,'Exact request provenance');await expect(page.getByRole('textbox',{name:'Frozen prompt',exact:true})).toHaveValue('Café\n東京 exact request');await click(page,'Accept this exact review locally');await requestFeedback(page,'Request review accepted locally. No job was queued and no provider call was made.');
   await Promise.all(responseWork);const review=responses.find(r=>r.review)?.review;expect(review.request.settings.seed).toEqual({kind:'integer',decimal:'900719925474099312345'});expect(review.request.size).toEqual({kind:'custom',width:1600,height:896});expect(review.dispatch).toBe(false);expect(requests.filter(r=>r.body.type==='AcceptRequestReview')).toHaveLength(1);
   await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await page.setViewportSize({width:320,height:900});const requestLink=page.getByRole('link',{name:'Go to Request',exact:true});await requestLink.focus();await requestLink.press('Enter');await expect(page.getByRole('button',{name:'Close request review',exact:true})).toBeVisible();await page.getByRole('button',{name:'Close request review',exact:true}).scrollIntoViewIfNeeded();const geometry=await page.locator('.typed-request').evaluate(el=>({width:el.getBoundingClientRect().width,scroll:el.scrollWidth}));expect(geometry.scroll).toBeLessThanOrEqual(geometry.width+1);await click(page,'Close request review');await expect(page.getByRole('button',{name:'Review exact request',exact:true})).toBeFocused();
  }else if(scenario==='recovery'){
   await number(page,'Output width','1536');await page.getByRole('combobox',{name:'Operation',exact:true}).selectOption('Generate with Instant');await prompt.fill('Instant draft retained');await click(page,'Keep acceleration inactive in this draft');await expect(page.getByText('acceleration is confirmed inactive for this operation.',{exact:true})).toBeVisible();await click(page,'Keep speed inactive in this draft');await expect(page.getByText('speed is confirmed inactive for this operation.',{exact:true})).toBeVisible();await page.getByRole('combobox',{name:'Operation',exact:true}).selectOption('Generate image');await expect(prompt).toHaveValue('Café\n東京 exact request');await expect(page.getByRole('spinbutton',{name:'Output width',exact:true})).toHaveValue('1536');
   await click(page,'Review exact request');await expect(page.getByRole('heading',{name:'Immutable request review',exact:true})).toBeVisible();await prompt.fill('New text invalidates this review');await expect(page.getByRole('heading',{name:'Immutable request review',exact:true})).toBeHidden();
   await click(page,'Review exact request');await expect(page.getByRole('heading',{name:'Immutable request review',exact:true})).toBeVisible();await click(page,'Accept this exact review locally');await requestFeedback(page,'Request review accepted locally. No job was queued and no provider call was made.');
   await page.getByRole('combobox',{name:'Request prompt type',exact:true}).selectOption('raw');await prompt.fill(' {"future":true} \n');await page.getByRole('combobox',{name:'Request prompt type',exact:true}).selectOption('plain');await expect(prompt).toHaveValue('New text invalidates this review');await expect(page.locator('footer')).toContainText('Draft saved locally');
   await page.reload();await expect(prompt).toHaveValue('New text invalidates this review');await expect(page.getByRole('heading',{name:'Immutable request review',exact:true})).toBeHidden();await click(page,'Retained request reviews');await expect(page.getByText(/Historical records are read-only/)).toBeVisible();await page.getByRole('combobox',{name:'Request prompt type',exact:true}).selectOption('raw');await expect(prompt).toHaveValue(' {"future":true} \n');await page.getByRole('combobox',{name:'Request prompt type',exact:true}).selectOption('plain');
   await page.getByRole('combobox',{name:'Operation',exact:true}).selectOption('Generate with Instant');await expect(prompt).toHaveValue('Instant draft retained');await expect(page.getByRole('spinbutton',{name:'Output width',exact:true})).toHaveValue('1536');expect(requests.filter(r=>r.body.type==='AcceptRequestReview')).toHaveLength(1);
  }else if(scenario==='adapters'){
   const operation=page.getByRole('combobox',{name:'Operation',exact:true}),sourceRegion=page.getByRole('region',{name:'Request source and separate edit mask',exact:true});
   for(const [origin,target,heading] of [['Transform image','Transform with adapters','Capture request source'],['Edit masked region','Edit with adapters','Separate request mask']]){
    await operation.selectOption(origin);await prompt.fill('Original '+origin);await number(page,'Transformation strength','1.25');
    const contextual=sourceRegion.getByRole('button',{name:'Use adapters',exact:true});await expect(sourceRegion.getByRole('heading',{name:heading,exact:true})).toBeVisible();await expect(contextual).toBeVisible();
    await contextual.focus();await contextual.press('Enter');await expect(operation).toHaveValue(target);const library=page.getByRole('button',{name:'Adapter library',exact:true});await expect(library).toHaveAttribute('aria-expanded','true');await expect(library).toBeFocused();
    await expect(prompt).toHaveValue('Original '+origin);await expect(page.getByRole('spinbutton',{name:'Transformation strength',exact:true})).toHaveValue('1.25');await expect(sourceRegion.getByRole('button',{name:'Use adapters',exact:true})).toHaveCount(0);
    await prompt.fill('Retained '+target);await number(page,'Transformation strength','0');await operation.selectOption(origin);await expect(prompt).toHaveValue('Original '+origin);await expect(page.getByRole('spinbutton',{name:'Transformation strength',exact:true})).toHaveValue('1.25');
    await sourceRegion.getByRole('button',{name:'Use adapters',exact:true}).focus();await page.keyboard.press('Space');await expect(operation).toHaveValue(target);await expect(prompt).toHaveValue('Retained '+target);await expect(page.getByRole('spinbutton',{name:'Transformation strength',exact:true})).toHaveValue('0');await expect(library).toBeFocused();
   }
   expect(requests.filter(r=>['PrepareRequestReview','AcceptRequestReview','EnqueueAcceptedRequest','RegisterAdapterVersion','FinalizeStaging'].includes(r.body.type))).toEqual([]);await expect(page.locator('#request-review')).toHaveCount(0);
  }else{
   await click(page,'Import image');await page.getByLabel('Image file',{exact:true}).setInputFiles('tests/raster/fixtures/hidden-alpha.png');await confirmImageImports(page,{names:['hidden-alpha.png'],destination:'current'});await expect(page.getByText('ImportAsset accepted and saved locally.',{exact:true})).toBeVisible();await page.getByRole('treeitem').first().click();
   await page.getByRole('combobox',{name:'Operation',exact:true}).selectOption('Transform image');await expect(page.getByRole('spinbutton',{name:'Transformation strength',exact:true})).toHaveValue('');await click(page,'Use operation strength default');await expect(page.getByRole('spinbutton',{name:'Transformation strength',exact:true})).toHaveValue('0.8');const legacy=page.getByRole('button',{name:'Legacy source and layer mask recovery',exact:true});await legacy.click();await expect(legacy).toHaveAttribute('aria-expanded','true');await click(page,'Attach selected image asset');await expect(page.getByText(/Source .*version .*3 × 2/)).toBeVisible();
   const strength=page.getByRole('spinbutton',{name:'Transformation strength',exact:true});await number(page,'Transformation strength','1.01');await click(page,'Review exact request');await expect(strength).toHaveValue('1.01');await expect(strength).toHaveAttribute('aria-invalid','true');await page.locator('#request-errors').getByRole('link',{name:/STRENGTH:/}).click();await expect(strength).toBeFocused();expect(requests.filter(r=>r.body.type==='PrepareRequestReview')).toHaveLength(0);await number(page,'Transformation strength','0');await expect(strength).toHaveValue('0');await expect(strength).not.toHaveAttribute('aria-invalid','true');await click(page,'Use operation strength default');await expect(strength).toHaveValue('0.8');
   await click(page,'Review exact request');await expect(page.locator('#request-errors')).toContainText('CONVERSION_REQUIRED');await expect(page.getByRole('combobox',{name:'Request size',exact:true})).not.toHaveAttribute('aria-invalid','true');const resize=page.getByRole('img',{name:'Preview of the request source with the proposed stretch mapping',exact:true});await expect(resize).toBeVisible();await expect(resize).toHaveAttribute('viewBox','0 0 1024 1024');await click(page,'Confirm this request resize mapping');await expect(page.getByText('Request resize mapping confirmed.',{exact:true})).toBeVisible();await click(page,'Review current request document');await expect(page.getByText('Request document revision confirmed.',{exact:true})).toBeVisible();await click(page,'Review exact request');await expect(page.getByRole('heading',{name:'Immutable request review',exact:true})).toBeVisible();await expect(page.locator('#request-review')).toContainText('ideogram/v4/image-to-image');await click(page,'Accept this exact review locally');await requestFeedback(page,'Request review accepted locally. No job was queued and no provider call was made.');
  }
  // Pinned WebKit screenshot synchronization injects inline styles; keep its CSP oracle strict.
  if(browserName!=='webkit')await page.screenshot({path:join(receipt,scenario+'-viewport.png'),caret:'initial'});
  effects=await server.effects();expect(Object.values(effects as object).every(n=>n===0)).toBe(true);expect(errors).toEqual([]);expect(csp).toEqual([]);expect(external).toEqual([]);expect(consoleErrors).toEqual([]);
 }catch(error){state.failures.push({phase:'body',error});}finally{
  await step(state,'response-observations',()=>Promise.all(responseWork));
  if(!state.failures.length)await step(state,'logical-cleanup',async()=>{for(const p of context.pages())await p.goto('about:blank');await guard.cleanup();guard.verify();});
  await step(state,'final-effects',async()=>{effects=await server.effects();expect(Object.values(effects as object).every(n=>n===0)).toBe(true);});
  state.writerClosed=await step(state,'writer-close',()=>server.close());
  await step(state,'transport-diagnostics',async()=>{transportDiagnostics.stop();await testInfo.attach('request-transport.json',{body:Buffer.from(JSON.stringify(transportDiagnostics.snapshot(),null,2)),contentType:'application/json'});});
  throwFailures(state.failures);
 }
});
