import {test as base,expect,type Page} from '@playwright/test';
import {mkdtemp,realpath,mkdir,writeFile,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {serverProcess} from '../editor/process.js';import {ownedOPFS} from '../editor/owned-opfs.js';import {recordDOMErrors} from '../editor/error-monitor.js';
import {runs,step,throwFailures,finishFixture,type RunState} from '../editor/harness-lifecycle.js';
const test=base.extend({context:async({playwright,browserName,contextOptions,viewport},use,testInfo)=>{
 const profile=browserName==='webkit'?await mkdtemp(join(await realpath(tmpdir()),'ie-p2-request-webkit-')):undefined;
 const browser=profile?undefined:await playwright[browserName].launch();const context=profile?await playwright.webkit.launchPersistentContext(profile,{...contextOptions,viewport}):await browser!.newContext({...contextOptions,viewport});await Promise.all(context.pages().map(p=>p.close()));
 try{await use(context);}finally{await finishFixture(context,browser,profile,receipt,testInfo.title.split(' ')[2]+'-',testInfo);}
}});
const receipt=process.env.EDITOR_RECEIPT??'artifacts/p2-request';const click=(page:Page,name:string)=>page.getByRole('button',{name,exact:true}).click();
async function number(page:Page,name:string,value:string){const f=page.getByRole('spinbutton',{name,exact:true});await f.fill(value);await f.press('Tab');}
for(const scenario of ['review','recovery','source'] as const)test('public request '+scenario+' binds exact accepted values with no dispatch',async({page,context,browserName})=>{
 const guard=await ownedOPFS(context,'p2-request-'+scenario),errors=await recordDOMErrors(context),csp:unknown[]=[],requests:any[]=[],responses:any[]=[],external:string[]=[],consoleErrors:string[]=[],publicEvents:unknown[]=[];
 await context.exposeBinding('requestEvent',(_source,value)=>publicEvents.push(value));await context.addInitScript(()=>{for(const type of ['click','keydown','focusin','en-input','en-change','compositionstart','compositionend'])addEventListener(type,e=>{const target=e.target as HTMLElement;if(!target.closest?.('.typed-request'))return;setTimeout(()=>(window as any).requestEvent({type,target:target.id||target.tagName,key:(e as KeyboardEvent).key,cancelled:e.defaultPrevented,active:document.activeElement?.id,issues:(document.querySelector('#request-errors') as any)?.items}),0);});});
 await context.exposeBinding('requestCSP',(_source,value)=>csp.push(value));await context.addInitScript(()=>addEventListener('securitypolicyviolation',e=>(window as any).requestCSP({directive:e.effectiveDirective,blocked:e.blockedURI})));
 page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('request',r=>{if(r.method()==='POST'&&r.url().includes('/api/v1/ui/'))requests.push(JSON.parse(r.postData()!));});
 const dir=await mkdtemp(join(await realpath(tmpdir()),'ie-p2-request-')),server=await serverProcess(join(dir,'private'));let effects:unknown,runtime:unknown;const responseWork:Promise<void>[]=[];
 const state:RunState={failures:[],roots:[dir],writerClosed:false,contextClosed:false,browserClosed:false,retention:[],receipt,prefix:scenario+'-'};runs.set(context,state);
 state.observe=()=>({runtime,errors,csp,external,consoleErrors,publicEvents,requests,responses,requestLifecycle:guard.requests,effects,cleanup:{opfs:guard.ledger,serverClosed:state.writerClosed,privateRootRemoved:state.retention.some((r:any)=>r.root===dir&&r.removed)?dir:null}});
 state.finalCheck=async()=>{guard.verify();expect(guard.ledger.filter(e=>e.phase==='refused')).toEqual([]);expect(errors).toEqual([]);expect(csp).toEqual([]);expect(external).toEqual([]);expect(consoleErrors).toEqual([]);};
 await page.route('**/*',route=>{const u=new URL(route.request().url());if(['http:','https:'].includes(u.protocol)&&u.origin!==server.origin){external.push(u.origin);return route.abort();}return route.continue();});
 page.on('response',r=>{if(r.request().method()==='POST'&&r.url().includes('/api/v1/ui/'))responseWork.push(r.json().then(body=>{responses.push(body);}));});await mkdir(receipt,{recursive:true});
 try{await guard.admit(page,server.origin);await page.goto(await server.pair());runtime={version:context.browser()?.version(),pin:JSON.parse(await readFile('node_modules/playwright-core/browsers.json','utf8')).browsers.find((b:any)=>b.name===browserName)};
  await expect(page.getByText('Local recovery complete. Accepted edits are saved locally.',{exact:true})).toBeVisible();await click(page,'New');await number(page,'Width (px)','1024');await number(page,'Height (px)','1024');await click(page,'Create');await expect(page.getByRole('dialog',{name:'New document',exact:true})).toBeHidden();
  const prompt=page.getByRole('textbox',{name:'Prompt',exact:true});await expect(prompt).toBeVisible();await prompt.fill('Café\n東京 exact request');
  if(scenario==='review'){
   await page.getByRole('combobox',{name:'Operation',exact:true}).selectOption('Generate with Fast');await click(page,'Review exact request');await expect(page.locator('#request-errors')).toContainText('acceleration');await page.locator('#request-errors').getByRole('link').first().click();await expect(page.getByRole('combobox',{name:'Acceleration',exact:true})).toBeFocused();await click(page,'Keep acceleration inactive in this draft');await expect(page.getByText('acceleration is confirmed inactive for this operation.',{exact:true})).toBeVisible();
   await number(page,'Output width','1600');await number(page,'Output height','900');await click(page,'Review exact request');await expect(page.locator('#request-errors')).toContainText('SIZE');await expect(page.getByRole('spinbutton',{name:'Output height',exact:true})).toHaveValue('900');await number(page,'Output height','896');
   await page.getByRole('textbox',{name:'Exact seed (empty means Random)',exact:true}).fill('900719925474099312345');
   await page.locator('#prepare-request').evaluate(el=>el.addEventListener('click',e=>e.preventDefault(),{once:true}));await click(page,'Review exact request');expect(requests.filter(r=>r.body.type==='PrepareRequestReview')).toHaveLength(0);
   await page.getByRole('button',{name:'Review exact request',exact:true}).focus();await expect(page.getByRole('button',{name:'Review exact request',exact:true})).toBeFocused();await page.keyboard.press('Enter');await expect(page.getByRole('heading',{name:'Immutable request review',exact:true})).toBeVisible();await expect(page.locator('#request-review')).toBeFocused();await expect(page.locator('#request-review')).toContainText('ideogram/v4/fast');
   await click(page,'Exact request provenance');await expect(page.getByRole('textbox',{name:'Frozen prompt',exact:true})).toHaveValue('Café\n東京 exact request');await click(page,'Accept this exact review locally');await expect(page.getByText('Request review accepted locally. No job was queued and no provider call was made.',{exact:true})).toBeVisible();
   await Promise.all(responseWork);const review=responses.find(r=>r.review)?.review;expect(review.request.settings.seed).toEqual({kind:'integer',decimal:'900719925474099312345'});expect(review.request.size).toEqual({kind:'custom',width:1600,height:896});expect(review.dispatch).toBe(false);expect(requests.filter(r=>r.body.type==='AcceptRequestReview')).toHaveLength(1);
   await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await page.setViewportSize({width:320,height:900});const requestLink=page.getByRole('link',{name:'Go to Request',exact:true});await requestLink.focus();await requestLink.press('Enter');await expect(page.getByRole('button',{name:'Close request review',exact:true})).toBeVisible();await page.getByRole('button',{name:'Close request review',exact:true}).scrollIntoViewIfNeeded();const geometry=await page.locator('.typed-request').evaluate(el=>({width:el.getBoundingClientRect().width,scroll:el.scrollWidth}));expect(geometry.scroll).toBeLessThanOrEqual(geometry.width+1);await click(page,'Close request review');await expect(page.getByRole('button',{name:'Review exact request',exact:true})).toBeFocused();
  }else if(scenario==='recovery'){
   await number(page,'Output width','1536');await page.getByRole('combobox',{name:'Operation',exact:true}).selectOption('Generate with Instant');await prompt.fill('Instant draft retained');await click(page,'Keep acceleration inactive in this draft');await expect(page.getByText('acceleration is confirmed inactive for this operation.',{exact:true})).toBeVisible();await click(page,'Keep speed inactive in this draft');await expect(page.getByText('speed is confirmed inactive for this operation.',{exact:true})).toBeVisible();await page.getByRole('combobox',{name:'Operation',exact:true}).selectOption('Generate image');await expect(prompt).toHaveValue('Café\n東京 exact request');await expect(page.getByRole('spinbutton',{name:'Output width',exact:true})).toHaveValue('1536');
   await click(page,'Review exact request');await expect(page.getByRole('heading',{name:'Immutable request review',exact:true})).toBeVisible();await prompt.fill('New text invalidates this review');await expect(page.getByRole('heading',{name:'Immutable request review',exact:true})).toBeHidden();
   await click(page,'Review exact request');await expect(page.getByRole('heading',{name:'Immutable request review',exact:true})).toBeVisible();await click(page,'Accept this exact review locally');await expect(page.getByText('Request review accepted locally. No job was queued and no provider call was made.',{exact:true})).toBeVisible();
   await page.getByRole('combobox',{name:'Request prompt type',exact:true}).selectOption('raw');await prompt.fill(' {"future":true} \n');await page.getByRole('combobox',{name:'Request prompt type',exact:true}).selectOption('plain');await expect(prompt).toHaveValue('New text invalidates this review');await expect(page.locator('footer')).toContainText('Draft saved locally');
   await page.reload();await expect(prompt).toHaveValue('New text invalidates this review');await expect(page.getByRole('heading',{name:'Immutable request review',exact:true})).toBeHidden();await click(page,'Retained request reviews');await expect(page.getByText(/Historical records are read-only/)).toBeVisible();await page.getByRole('combobox',{name:'Request prompt type',exact:true}).selectOption('raw');await expect(prompt).toHaveValue(' {"future":true} \n');await page.getByRole('combobox',{name:'Request prompt type',exact:true}).selectOption('plain');
   await page.getByRole('combobox',{name:'Operation',exact:true}).selectOption('Generate with Instant');await expect(prompt).toHaveValue('Instant draft retained');await expect(page.getByRole('spinbutton',{name:'Output width',exact:true})).toHaveValue('1536');expect(requests.filter(r=>r.body.type==='AcceptRequestReview')).toHaveLength(1);
  }else{
   await click(page,'Import image');await page.getByLabel('Image file',{exact:true}).setInputFiles('tests/raster/fixtures/hidden-alpha.png');await click(page,'Apply reviewed result');await expect(page.getByText('ImportAsset accepted and saved locally.',{exact:true})).toBeVisible();await page.getByRole('treeitem').first().click();
   await page.getByRole('combobox',{name:'Operation',exact:true}).selectOption('Transform image');await expect(page.getByRole('spinbutton',{name:'Transformation strength',exact:true})).toHaveValue('');await click(page,'Use operation strength default');await expect(page.getByRole('spinbutton',{name:'Transformation strength',exact:true})).toHaveValue('0.8');await click(page,'Attach selected image asset');await expect(page.getByText(/Source .*version .*3 × 2/)).toBeVisible();
   await click(page,'Review exact request');await expect(page.locator('#request-errors')).toContainText('CONVERSION_REQUIRED');const resize=page.getByRole('img',{name:'Preview of the request source with the proposed stretch mapping',exact:true});await expect(resize).toBeVisible();await expect(resize).toHaveAttribute('viewBox','0 0 1024 1024');await click(page,'Confirm this request resize mapping');await expect(page.getByText('Request resize mapping confirmed.',{exact:true})).toBeVisible();await click(page,'Review current request document');await expect(page.getByText('Request document revision confirmed.',{exact:true})).toBeVisible();await click(page,'Review exact request');await expect(page.getByRole('heading',{name:'Immutable request review',exact:true})).toBeVisible();await expect(page.locator('#request-review')).toContainText('ideogram/v4/image-to-image');await click(page,'Accept this exact review locally');await expect(page.getByText('Request review accepted locally. No job was queued and no provider call was made.',{exact:true})).toBeVisible();
  }
  // Pinned WebKit screenshot synchronization injects inline styles; keep its CSP oracle strict.
  if(browserName!=='webkit')await page.screenshot({path:join(receipt,scenario+'-viewport.png'),caret:'initial'});
  effects=await server.effects();expect(Object.values(effects as object).every(n=>n===0)).toBe(true);expect(errors).toEqual([]);expect(csp).toEqual([]);expect(external).toEqual([]);expect(consoleErrors).toEqual([]);
 }catch(error){state.failures.push({phase:'body',error});}finally{
  await step(state,'response-observations',()=>Promise.all(responseWork));
  if(!state.failures.length)await step(state,'logical-cleanup',async()=>{for(const p of context.pages())await p.goto('about:blank');await guard.cleanup();guard.verify();});
  await step(state,'final-effects',async()=>{effects=await server.effects();expect(Object.values(effects as object).every(n=>n===0)).toBe(true);});
  state.writerClosed=await step(state,'writer-close',()=>server.close());
  throwFailures(state.failures);
 }
});
