// Source-only staged controller regressions. Native display decoding and the
// shared model ledger are controlled boundaries; these are not browser or RSS qualification.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {transformWithOxc} from 'vite';
import {displayControlURL} from '../display-module.mjs';
const data=code=>'data:text/javascript;base64,'+Buffer.from(code).toString('base64'),lit=data('export const nothing=null;export function html(strings,...values){return {strings,values};}export const svg=html;');
const stable=Object.fromEntries(['request/core','protocol/json','protocol/request-edits'].map(name=>['../'+name+'.js',pathToFileURL(resolve('dist/local/src/'+name+'.js')).href]));
const {hash}=await import(stable['../request/core.js']),{canonical}=await import(stable['../protocol/json.js']);
const modelURL=data(`export const records=[];export function modelPayloadBytes(v){return JSON.stringify(v).length*4;}export function reserveModelBytes(owner,bytes){let refs=1,live=true;const row={owner,bytes,released:false};records.push(row);return {pin(){if(!refs)throw Error('released');refs++;let active=true;return ()=>{if(active){active=false;if(!--refs)row.released=true;}};},release(){if(live){live=false;if(!--refs)row.released=true;}}};}export function createOwnedModel(owner,bytes,create){const payload=reserveModelBytes(owner,bytes);try{return {value:create(),pin:()=>payload.pin(),release:()=>payload.release()};}catch(error){payload.release();throw error;}}`),{records,createOwnedModel,modelPayloadBytes}=await import(modelURL);
const displayURL=data(`import {readOwnedDisplayControl,DISPLAY_SOURCE_CONTROL_BYTES} from ${JSON.stringify(displayControlURL)};
 export async function withDisplaySource(transport,id,options,consume){const owner=await readOwnedDisplayControl('fixture-display-source',DISPLAY_SOURCE_CONTROL_BYTES,()=>readDisplaySource(transport,id,options));try{return await consume(owner.value);}finally{owner.release();}}
 export const created=[],released=[];export let failAt=0;export const fail=n=>failAt=n;export async function readDisplaySource(_transport,id){return {assetId:id};}export async function createDisplayPreviewURL(_transport,source,options){if(failAt&&created.length+1===failAt)throw Error('DISPLAY_TEST_FAILURE');if(options.signal.aborted||!options.owns())throw new DOMException('stale','AbortError');const url='blob:'+source.assetId+'/'+created.length;created.push(url);return url;}export function revokeDisplayPreviewURL(url){if(released.includes(url))throw Error('double release');released.push(url);}export function validateDisplayImage(){}`),display=await import(displayURL);
const promptURL=data('export class PromptReaderCleanupError extends Error{}');
async function moduleSource(path,imports){let code=(await transformWithOxc(await readFile(path,'utf8'),path)).code;for(const [name,url]of Object.entries(imports))code=code.replaceAll(JSON.stringify(name),JSON.stringify(url)).replaceAll("'"+name+"'",JSON.stringify(url));return data(code);}
const controls=await moduleSource('src/ui/adapters.ts',{}),helper=new URL('../../src/ui/text-treatment.ts',import.meta.url),{TextTreatmentEditing,textTreatmentUISelection}=await import(await moduleSource(helper.pathname,{...stable,lit,'./adapters.js':controls,'../observability/model-memory.js':modelURL,'../observability/prompt-memory.js':promptURL,'../observability/display-preview.js':displayURL,'./display-image.js':data('export const displayImage=v=>v;')}));
const flush=async()=>{for(let i=0;i<30;i++)await Promise.resolve();},turn=async()=>{await new Promise(resolve=>setTimeout(resolve,0));await new Promise(setImmediate);await flush();},clone=structuredClone;
const ref=(label,mediaType='application/json',byteLength='32')=>({hash:hash(label),mediaType,byteLength}),deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
function event(value='',checked=false){const control={value,checked,isConnected:true};return {currentTarget:control,composedPath:()=>[control],defaultPrevented:false};}
// Exercise the actual EventTarget dispatch and cancellation path. Node's Event
// target retention differs between releases; enforce the browser's currentTarget
// lifetime explicitly while keeping the real event and its native composedPath.
function dispatchChange(callback,value='',checked=false,{veto=false}={}){
 const control=Object.assign(new EventTarget(),{value,checked,isConnected:true}),event=new Event('en-change',{bubbles:true,composed:true,cancelable:true});let dispatching=true,accepted;
 Object.defineProperty(event,'currentTarget',{get:()=>dispatching?control:null});
 const cancel=event=>event.preventDefault();control.addEventListener('en-change',callback);if(veto)control.addEventListener('en-change',cancel);
 try{accepted=control.dispatchEvent(event);}finally{dispatching=false;control.removeEventListener('en-change',callback);control.removeEventListener('en-change',cancel);}
 assert.equal(event.target,control);assert.equal(event.currentTarget,null,'A deferred reader cannot use currentTarget after dispatch');assert.deepEqual(event.composedPath(),[]);
 return {control,event,accepted};
}
function handler(template,id,kind='click'){if(!template||typeof template!=='object')return;if(template.strings){let index=template.strings.findIndex((s,i)=>s.includes('id="'+id+'"')||s.endsWith('id=')&&template.values[i]===id);if(index>=0){for(let i=index;i<template.strings.length;i++){if(template.strings[i].endsWith('@'+kind+'='))return template.values[i];if(i>index&&template.strings[i].includes('</en-'))break;}}}for(const item of Array.isArray(template)?template:template.values??[]){const result=handler(item,id,kind);if(result)return result;}}
async function fixture(t,{operation='transform-v45',sourceIds=['bg','text'],semantic=[],mode='plain',mask=null,approved=null}={}){
 const startModels=records.length,startURLs=display.created.length,startReleases=display.released.length;display.fail(0);let draft,template,controller,serial=0,entryKey='entry',generation=0,override=null,attachFailure=false;
 const imageVersion={state:ref('state'),semanticDigest:hash('state-digest'),compositeAssetId:'visible'},document={id:'document',revision:'7',width:4,height:4,image:imageVersion},layers=[{id:'bg',version:'1',kind:'image',name:'Background',visible:true,locked:false},{id:'text',version:'1',kind:'text',name:'Caption',visible:true,locked:false}],manifests=new Map(),commands=[],errors=[],holds=[],attachments=[];
 function capture(id,scope,ids){const pixels=ref(id+'pixels','application/x-ideogram-rgba8','64'),root={width:4,height:4,pixels,plan:{kind:'request-source-capture-v1',capture:{schemaVersion:1,documentId:'document',documentRevision:'7',image:imageVersion,scope,layerIds:ids}}},wire=canonical(root),manifest={hash:hash(wire),mediaType:'application/json',byteLength:String(Buffer.byteLength(wire))},asset={id,version:'1',blob:ref(id+'png','image/png','48'),availability:'available',qualification:'canonical-raster',safety:'safe',raster:{manifest,pixels,role:'composite',width:4,height:4}};manifests.set(id,root);return {asset,source:{assetId:id,version:'1',blob:asset.blob,pixels,width:4,height:4,scope,documentRevision:'7',capture:manifest}};}
 const original=capture('original',sourceIds.length===1?'single-layer':'selected-layers',sourceIds).source;draft={operation,prompt:{mode},source:operation==='generate-v45'?null:original,mask,preparedInputs:{original:true}};
 const semanticView={key:'semantics-1',items:semantic.map(id=>({id,label:id})),approvedExcludedIds:approved};
 const editor={view:{ready:true,document,image:{width:4,height:4,layers}},draftOwner:{},sessionId:'session',session:{identity:()=> 'client',transport:()=>assert.fail('No unowned network reads')},command(){assert.fail('Capture must use scoped command events');},async withCommandEvents(body,consume,target){commands.push({body:clone(body),target:clone(target)});let events;if(override)events=await override(body,target);else{const ids=body.scope==='visible-document'?layers.filter(row=>row.visible).map(row=>row.id):body.layerIds,value=capture('capture-'+(++serial),body.scope,ids);events=[{type:'AssetRegistered',payload:{asset:value.asset}}];}const model=createOwnedModel('fixture-command-events',modelPayloadBytes(events),()=>clone(events));try{return await consume(model.value);}finally{model.release();}},async ownedJSON(path){const id=/\/assets\/([^/]+)\/raster$/.exec(path)?.[1];assert(manifests.has(id));const payload=records.length;const value=clone(manifests.get(id));records.push({owner:'fixture-manifest',released:false});return {value,release(){assert(!records[payload].released);records[payload].released=true;}};}};
 const host={updateComplete:Promise.resolve(),requestUpdate(){this.updateComplete=Promise.resolve().then(()=>{template=controller.render();});}};
 const owns=()=>{const prior=draft,revision=generation,owner=editor.draftOwner,doc=editor.view.document;return ()=>prior===draft&&revision===generation&&owner===editor.draftOwner&&doc.revision===editor.view.document.revision;};
 controller=new TextTreatmentEditing(host,editor,{draft:()=>draft,entryKey:()=>entryKey,hold(expected){assert.equal(expected,draft);const held={released:false};holds.push(held);return ()=>{assert(!held.released);held.released=true;};},owns,semantic:()=>semanticView,attachAlternateSource(expected,source){assert.equal(expected,draft);if(attachFailure)throw Error('ENTRY_ADMISSION_REFUSED');attachments.push(source);draft={...clone(draft),source:clone(source),mask:null,preparedInputs:null};generation++;return draft;},openComposition:()=>commands.push({composition:true}),error:error=>errors.push(error)});
 template=controller.render();await flush();
 t.after(async()=>{controller.dispose();await flush();await controller.drain();await flush();assert(holds.every(held=>held.released),'Entry holds release after complete async work and Lit retirement');assert(records.slice(startModels).every(row=>row.released),'All controlled model owners release');assert.deepEqual(display.released.slice(startReleases).sort(),display.created.slice(startURLs).sort());});
 return {controller,editor,commands,errors,holds,attachments,manifests,semantic:semanticView,source:original,capture,draft:()=>draft,setCommand(fn){override=fn;},refuseAttach(){attachFailure=true;},replaceDraft(){draft=clone(draft);generation++;},replaceEntry(){entryKey+='2';draft=clone(draft);generation++;},async click(id){const callback=handler(template,id);assert.equal(typeof callback,'function',id);callback(event());await turn();},async choose(id,value,checked=false){const callback=handler(template,id,'en-change');assert.equal(typeof callback,'function',id);callback(event(value,checked));await flush();},async dispatch(id,value,checked=false,options){const callback=handler(template,id,'en-change');assert.equal(typeof callback,'function',id);const result=dispatchChange(callback,value,checked,options);await flush();return result;},callback(id){return handler(template,id);},async loaded(){for(const picture of Object.values(controller.review?.pictures??{}))if(picture)picture.loaded=true;host.requestUpdate();await flush();},async repaint(){host.requestUpdate();await flush();}};
}
async function overlay(f){await f.choose('text-treatment-kind','native-overlay');await f.choose('text-treatment-retain-text','',true);}

test('selection preserves painter order and removes only explicitly retained native source IDs',()=>{assert.deepEqual(textTreatmentUISelection(['background','native','upper'],['background','native','upper'],['native'],'native-overlay'),['background','upper']);assert.deepEqual(textTreatmentUISelection(['background','native'],['background','native'],['native'],'baked-lettering'),['background','native']);assert.throws(()=>textTreatmentUISelection(['hidden'],['visible'],[],'no-native-text'),/hidden/);});

test('native overlay captures visible inventory and exact prior-source subset; attachment waits for explicit confirmed previews',async t=>{const f=await fixture(t);await overlay(f);await f.click('text-treatment-prepare');assert.deepEqual(f.errors,[]);assert.deepEqual(f.commands.map(row=>row.body),[{type:'PrepareRequestSource',scope:'visible-document',layerIds:[]},{type:'PrepareRequestSource',scope:'single-layer',layerIds:['bg']}]);assert.equal(f.draft().source,f.source);assert.equal(f.controller.intent(),undefined);await f.click('text-treatment-confirm');assert.match(f.errors.at(-1).message,/every retained source preview/);assert.equal(f.attachments.length,0);await f.loaded();await f.click('text-treatment-confirm');assert.equal(f.attachments.length,1);assert.equal(f.draft().source.scope,'single-layer');assert.equal(f.draft().mask,null);assert.equal(f.draft().preparedInputs,null);const intent=f.controller.intent();assert.equal(intent.kind,'text-treatment-review-intent-1');assert.deepEqual(intent.beforeSource,f.source);assert.equal(intent.baseline.scope,'visible-document');assert.deepEqual(intent.choice.retainedNativeIds,['text']);});

test('Generate uses baseline only and never auto-attaches a source or changes its operation',async t=>{const f=await fixture(t,{operation:'generate-v45'});await overlay(f);await f.click('text-treatment-prepare');await f.loaded();await f.click('text-treatment-confirm');assert.deepEqual(f.errors,[]);assert.equal(f.commands.length,1);assert.equal(f.draft().source,null);assert.equal(f.draft().operation,'generate-v45');assert.equal(f.attachments.length,0);assert.equal(f.controller.intent().beforeSource,null);});

test('no excluded native pixels retains the exact original source without a redundant alternate capture',async t=>{const f=await fixture(t,{sourceIds:['bg']});await overlay(f);await f.click('text-treatment-prepare');await f.loaded();await f.click('text-treatment-confirm');assert.equal(f.commands.length,1);assert.equal(f.attachments.length,0);assert.equal(f.draft().source,f.source);assert.deepEqual(f.errors,[]);});

test('excluding every source layer refuses editing without silently selecting Generate',async t=>{const f=await fixture(t,{sourceIds:['text']});await overlay(f);await f.click('text-treatment-prepare');assert.match(f.errors.at(-1).message,/leaves no request source/);assert.equal(f.commands.length,0);assert.equal(f.draft().operation,'transform-v45');assert.equal(f.draft().source,f.source);});

test('an existing mask must be detached explicitly before any alternate-source work',async t=>{const f=await fixture(t,{mask:{assetId:'mask'}});await overlay(f);await f.click('text-treatment-prepare');assert.match(f.errors.at(-1).message,/Detach the current request mask/);assert.equal(f.commands.length,0);assert.equal(f.draft().mask.assetId,'mask');});

test('plain prompt semantic text exclusions require explicit choices independently of native pixels',async t=>{const f=await fixture(t,{semantic:['caption']});await overlay(f);await f.click('text-treatment-prepare');assert.match(f.errors.at(-1).message,/Explicitly exclude every semantic/);assert.equal(f.commands.length,0);await f.choose('text-treatment-semantic-caption','',true);await f.click('text-treatment-prepare');await f.loaded();await f.click('text-treatment-confirm');assert.deepEqual(f.controller.intent().choice.excludedSemanticIds,['caption']);});

test('Composition mismatched exclusions refuse without changing approved semantic values',async t=>{const f=await fixture(t,{operation:'transform',mode:'composition',semantic:['caption'],approved:['caption']});await overlay(f);await f.click('text-treatment-prepare');assert.match(f.errors.at(-1).message,/Composition editor/);assert.deepEqual(f.semantic.approvedExcludedIds,['caption']);assert.equal(f.commands.length,0);await f.choose('text-treatment-semantic-caption','',true);await f.click('text-treatment-prepare');assert(f.controller.review);assert.deepEqual(f.semantic.approvedExcludedIds,['caption']);});

test('stale draft after baseline command cannot publish previews or a treatment intent',async t=>{const f=await fixture(t),gate=deferred();await overlay(f);f.setCommand(()=>gate.promise);await f.click('text-treatment-prepare');assert.equal(f.commands.length,1);f.replaceDraft();const a=f.capture('late','visible-document',['bg','text']).asset;gate.resolve([{type:'AssetRegistered',payload:{asset:a}}]);await flush();assert.equal(f.controller.review,null);assert.equal(f.controller.intent(),undefined);assert.equal(f.attachments.length,0);assert.deepEqual(f.errors,[]);});

test('capture manifest bytes and current document identity are verified before baseline work',async t=>{const f=await fixture(t);f.manifests.get('original').plan.capture.documentId='other';await overlay(f);await f.click('text-treatment-prepare');assert.match(f.errors.at(-1).message,/manifest identity changed/);assert.equal(f.commands.length,0);assert.equal(f.controller.review,null);});

test('partial preview acquisition failure releases acquired siblings and preserves the draft',async t=>{const f=await fixture(t),start=display.created.length;await overlay(f);display.fail(start+2);await f.click('text-treatment-prepare');assert.match(f.errors.at(-1).message,/DISPLAY_TEST_FAILURE/);assert.equal(display.created.length,start+1);assert(display.released.includes(display.created[start]));assert.equal(f.controller.review,null);assert.equal(f.draft().source,f.source);display.fail(0);});

test('source attachment admission refusal retains the complete review and leaves the current request intact',async t=>{const f=await fixture(t);await overlay(f);await f.click('text-treatment-prepare');await f.loaded();const review=f.controller.review,prior=f.draft();f.refuseAttach();await f.click('text-treatment-confirm');assert.match(f.errors.at(-1).message,/ENTRY_ADMISSION_REFUSED/);assert.equal(f.controller.review,review);assert.equal(f.controller.intent(),undefined);assert.equal(f.draft(),prior);assert.equal(f.attachments.length,0);});

test('native veto releases the scheduled Entry hold without capture or review',async t=>{const f=await fixture(t);await overlay(f);const e=event(),before=f.holds.length;f.callback('text-treatment-prepare')(e);e.defaultPrevented=true;await turn();assert(f.holds.slice(before).every(row=>row.released));assert.equal(f.commands.length,0);assert.equal(f.controller.review,null);});

test('a new request entry clears deliberate text choices and invalidates earlier approval',async t=>{const f=await fixture(t);await overlay(f);await f.click('text-treatment-prepare');await f.loaded();await f.click('text-treatment-confirm');assert(f.controller.intent());f.replaceEntry();await f.repaint();assert.equal(f.controller.intent(),undefined);assert.equal(f.controller.kind,'');assert.equal(f.controller.retained.size,0);});


test('real dispatched treatment controls retain their host after currentTarget clears',async t=>{
 const f=await fixture(t,{operation:'inpaint-v45',sourceIds:['bg']});
 const kind=await f.dispatch('text-treatment-kind','native-overlay');assert.equal(kind.event.currentTarget,null);assert.equal(f.controller.kind,'native-overlay');
 const checked=await f.dispatch('text-treatment-retain-text','',true);assert.equal(checked.event.currentTarget,null);assert.deepEqual([...f.controller.retained],['text']);
 const placement=await f.dispatch('text-treatment-placement','current-document');assert.equal(placement.event.currentTarget,null);assert.equal(f.controller.placement,'current-document');
 await f.click('text-treatment-prepare');await f.loaded();await f.click('text-treatment-confirm');
 assert.deepEqual(f.errors,[]);assert.equal(f.controller.intent().choice.kind,'native-overlay');assert.deepEqual(f.controller.intent().choice.retainedNativeIds,['text']);assert.equal(f.controller.intent().choice.placement,'current-document');
});

test('later real event listeners can veto all deferred treatment control proposals',async t=>{
 const f=await fixture(t,{operation:'inpaint-v45',sourceIds:['bg']});
 assert.equal((await f.dispatch('text-treatment-kind','native-overlay',false,{veto:true})).accepted,false);assert.equal(f.controller.kind,'');
 await f.dispatch('text-treatment-kind','native-overlay');
 assert.equal((await f.dispatch('text-treatment-retain-text','',true,{veto:true})).accepted,false);assert.equal(f.controller.retained.size,0);
 assert.equal((await f.dispatch('text-treatment-placement','current-document',false,{veto:true})).accepted,false);assert.equal(f.controller.placement,'new-document');
 assert.deepEqual(f.errors,[]);assert.equal(f.commands.length,0);assert.equal(f.controller.intent(),undefined);
});
