// Authored source-only. Requires the effective V45 family in dist/local.
import {allocationsURL as ledgerURL,promptMemoryURL as promptURL} from '../owned-preview-module.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {transformWithOxc} from 'vite';
const root=process.env.V45_INPUT_ROOT??'.',modelRoot=process.env.UI_MODEL_ROOT??'.',data=code=>'data:text/javascript;base64,'+Buffer.from(code).toString('base64'),compiled=name=>pathToFileURL(resolve('dist/local/src/'+name+'.js')).href;
async function source(path,imports={}){let code=(await transformWithOxc(await readFile(path,'utf8'),path)).code;for(const [name,url]of Object.entries(imports))code=code.replaceAll(JSON.stringify(name),JSON.stringify(url)).replaceAll("'"+name+"'",JSON.stringify(url));return data(code);}
const modelURL=await source('src/observability/model-memory.ts',{'./allocations.js':ledgerURL,'./prompt-memory.js':promptURL}),ownerURL=await source(modelRoot+'/src/ui/model-owner.ts',{'../observability/model-memory.js':modelURL,'../observability/prompt-memory.js':promptURL}),memoryURL=await source(root+'/src/ui/request-v45-memory.ts',{'../observability/model-memory.js':modelURL,'../observability/prompt-memory.js':promptURL});
const lit=data('export const nothing=null;export const html=(strings,...values)=>({strings,values});'),uiURL=await source((process.env.REQUEST_RESPONSES_ROOT??root)+'/src/ui/request-v45-edit.ts',{'lit':lit,'./adapters.js':await source('src/ui/adapters.ts'),'./model-owner.js':ownerURL,'./request-v45-memory.js':memoryURL,'../observability/model-memory.js':modelURL,...Object.fromEntries(['request/core','request/v45-family-edit','request/v45-edit','protocol/v45-inputs','protocol/json'].map(name=>['../'+name+'.js',compiled(name)]))});
const {V45EditInputsEditing}=await import(uiURL),{allocationLedger,ALLOCATION_LIMITS}=await import(ledgerURL),{createOwnedModel,modelPayloadBytes,readOwnedJSON}=await import(modelURL),{formatV45Input,ownV45Fingerprint,joinV45Input}=await import(memoryURL),{newV45EditDraft}=await import(compiled('request/v45-family-edit')),{hash,bindRequestMask,requestMaskDependencies}=await import(compiled('request/core')),{createRequestRasterPlan,requestRasterGrid}=await import(compiled('request/raster-plan')),{canonical}=await import(compiled('protocol/json'));
const flush=async()=>{for(let n=0;n<100;n++)await Promise.resolve();},turn=async()=>{await new Promise(resolve=>setTimeout(resolve,5));await flush();},deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const ref=(label,mediaType='application/json',byteLength='32')=>({hash:hash(label),mediaType,byteLength});
const originalSource=(name,pixels=ref('shared-reference-pixels','application/x-ideogram-rgba8','128'))=>({assetId:name,version:'1',blob:ref(name+'-png','image/png'),pixels:structuredClone(pixels),width:8,height:4,scope:'single-layer',documentRevision:'7',capture:ref(name+'-capture')});
function draftFor(masked=false){const draft=newV45EditDraft(ref('Exact prompt','text/plain','12'),masked?'inpaint-v45':'transform-v45');draft.source=originalSource('source',ref('original-pixels','application/x-ideogram-rgba8','128'));draft.references=[originalSource('reference-a'),originalSource('reference-b'),originalSource('reference-a')];if(masked){draft.fields.width='4';draft.fields.height='4';draft.mask={assetId:'mask',version:'1',blob:ref('white-mask','image/png'),pixels:ref('white-mask-pixels','application/x-ideogram-rgba8','128'),width:8,height:4,sourceHash:draft.source.pixels.hash,polarity:'white-edit',empty:false,full:false,fullAcknowledged:false,plan:ref('mask-authoring'),binding:bindRequestMask(draft.source)};draft.mask.requestPlan=createRequestRasterPlan({document:{width:8,height:4},crop:{x:0,y:0,width:8,height:4},padding:{left:0,top:0,right:0,bottom:0},requestGrid:{width:4,height:4},sourcePixels:draft.source.pixels,authoredMask:ref('hard','application/x-ideogram-r16le','64'),effectiveMask:ref('effective','application/x-ideogram-r16le','64'),dependenciesHash:requestMaskDependencies(draft.source,draft.mask),resolution:'already-contained',approvalId:'original-approval'});}return draft;}
const raster=(name,width,height,pixels)=>({blob:ref(name+'-png','image/png'),pixels,manifest:ref(name+'-manifest'),pixelIdentity:hash(name+'-identity'),width,height});
function preparedBundle(draft){const masked=draft.operation==='inpaint-v45',grid=masked?requestRasterGrid(draft.mask.requestPlan):draft.source,pixels=masked?ref('transport-source-pixels','application/x-ideogram-rgba8',String(grid.width*grid.height*4)):draft.source.pixels;
 const mask=masked?{...raster('black-mask',grid.width,grid.height,ref('black-mask-pixels','application/x-ideogram-rgba8',String(grid.width*grid.height*4))),polarity:'black-edit',sourcePixels:pixels,editPixels:4,keepPixels:grid.width*grid.height-4}:null;
 const plan={kind:'v45-edit-inputs-1',endpoint:'ideogram/v4.5/edit',input:ref('input-plan'),assetBindings:{source:draft.source.assetId,mask:masked?draft.mask.assetId:null,references:draft.references.map(item=>item.assetId)},original:{source:structuredClone(draft.source),mask:masked?structuredClone(draft.mask):null},mask,requestPlan:masked?structuredClone(draft.mask.requestPlan):null,references:draft.references.map((original,index)=>({original:structuredClone(original),input:raster('reference-'+index,original.width,original.height,structuredClone(original.pixels))}))};
 const tiles=[{x:0,y:0,width:grid.width,height:grid.height,hash:pixels.hash}],pipeline='cp1-f64-triangle-area-v1',manifest={schemaVersion:1,pipeline,width:grid.width,height:grid.height,format:'straight-srgb-rgba8',layout:'row-major-tile-views-v1',tileSize:512,pixels,tiles,dependencies:[],plan},manifestRef=ref(canonical(manifest),'application/json',String(Buffer.byteLength(canonical(manifest))));
 const asset={id:'prepared-inputs',version:'1',purpose:'image',qualification:'canonical-raster',safety:'safe',availability:'available',measuredMediaType:'image/png',dependencies:[],blob:ref('prepared-source-png','image/png'),raster:{schemaVersion:1,pipeline,width:grid.width,height:grid.height,manifest:manifestRef,pixels,pixelIdentity:hash(canonical({pipeline,width:grid.width,height:grid.height,tiles})),role:'composite',sourceAssetIds:[draft.source.assetId],conversion:null}};return {asset,manifest};}
const nativeResponse=value=>{const text=JSON.stringify(value);return new Response(text,{headers:{'content-length':String(Buffer.byteLength(text))}});};
const pressure=available=>allocationLedger.reserve({owner:'v45-input-test-pressure',kind:'prompt',cpuBytes:ALLOCATION_LIMITS.promptBytes-allocationLedger.snapshot().promptBytes-available});
const sameUsage=(a,b)=>{for(const key of ['cpuBytes','promptBytes','activeRecords','handles'])assert.equal(a[key],b[key],key);};
function fixture(masked=false){let draftModel=createOwnedModel('v45-test-entry',modelPayloadBytes(draftFor(masked)),()=>draftFor(masked),'prompt'),documentModel=createOwnedModel('v45-test-document',1024,()=>({id:'document',revision:'7',width:8,height:4}),'control'),controller,bundle,transportHook,commandHook,readHook,admission=()=>{},generation=0,documentPins=0;const commands=[],reads=[],errors=[],entryHolds=new Map();
 const draft=()=>draftModel.value,editor={view:{document:documentModel.value,selected:['selected-a','selected-b']},draftOwner:{},sessionId:'session',session:{identity:()=> 'client',async transport(path,init){if(transportHook)return transportHook(path,init);return nativeResponse(bundle.manifest);}},pinViewModels(value){assert.equal(value,editor.view.document);const release=documentModel.pin();documentPins++;let live=true;return ()=>{if(live){live=false;documentPins--;release();}};},command(){assert.fail('V45 input commands must use scoped events');},async withCommandEvents(body,consume,target){commands.push({body,target});let events;if(commandHook)events=await commandHook(body,target);else{bundle=preparedBundle(draft());events=[{type:'AssetRegistered',payload:{asset:bundle.asset}}];}const model=createOwnedModel('v45-test-command-events',modelPayloadBytes(events),()=>structuredClone(events),'control');try{return await consume(model.value);}finally{model.release();}},async ownedJSON(path,owner,init,owns,maxBytes,kind){reads.push({path,maxBytes,kind});if(readHook)return readHook({path,owner,init,owns,maxBytes,kind});return readOwnedJSON(editor.session.transport.bind(editor.session),path,{owner,init,owns,maxBytes,kind});}};
 const host={requestUpdate(){this.updateComplete=Promise.resolve().then(()=>controller.render());},updateComplete:Promise.resolve()},owns=()=>{const expected=draft(),version=generation,documentId=editor.view.document.id,revision=editor.view.document.revision;return ()=>draft()===expected&&generation===version&&editor.view.document.id===documentId&&editor.view.document.revision===revision;};
 const hold=expected=>{assert.equal(expected,draft());const release=draftModel.pin();entryHolds.set(expected,(entryHolds.get(expected)??0)+1);let live=true;return ()=>{if(!live)return;live=false;release();const count=entryHolds.get(expected)-1;if(count)entryHolds.set(expected,count);else entryHolds.delete(expected);};};
 const mutate=(expected,growth,change)=>{assert.equal(expected,draft());admission();const next=createOwnedModel('v45-test-entry',modelPayloadBytes(expected)+modelPayloadBytes(growth)+4096,()=>{const next=structuredClone(expected);change(next);return next;},'prompt');const old=draftModel;draftModel=next;old.release();generation++;host.requestUpdate();return next.value;};
 controller=new V45EditInputsEditing(host,editor,{draft,owns,hold,mutate,changed:()=>assert.fail('No duplicate touch'),error:error=>errors.push(error),invalidateMapping(){}});controller.render();
 const action=work=>{const target={isConnected:true};const e={currentTarget:target,composedPath:()=>[target],defaultPrevented:false};controller.action(e,work);return e;};
 return {controller,editor,host,commands,reads,errors,entryHolds,draft,mutate,action,owns,bundle:()=>bundle,documentPins:()=>documentPins,setAdmission(fn){admission=fn;},setCommand(fn){commandHook=fn;},setTransport(fn){transportHook=fn;},setRead(fn){readHook=fn;},async prepare(){action((draft,owns)=>controller.prepare(draft,owns));await turn();await flush();},async confirm(){action(draft=>controller.confirm(draft));await turn();await flush();},async close(){await controller.dispose();draftModel.release();documentModel.release();await flush();}};
}

for(const masked of [false,true])test('owned '+(masked?'masked':'unmasked')+' prepared metadata is copied and rendered without repeated formatting',async()=>{const baseline=allocationLedger.snapshot(),f=fixture(masked);try{await f.prepare();assert.deepEqual(f.errors,[]);assert.equal(f.reads[0].maxBytes,65536);assert.equal(f.reads[0].kind,'prompt');const pending=f.controller.pending,original=f.draft();assert(pending);assert.notEqual(pending.value.mask,f.bundle().manifest.plan.mask??undefined);assert.equal(pending.formatted,JSON.stringify(pending.value,null,2));assert.equal(original.preparedInputs,null);const stringify=JSON.stringify;let pretty=0;JSON.stringify=(value,replacer,space)=>{if(space===2)pretty++;return stringify(value,replacer,space);};try{f.controller.render();f.controller.render();await f.confirm();f.controller.render();assert.equal(pretty,0,'Confirmed review reuses the admitted formatted component');}finally{JSON.stringify=stringify;}assert.notEqual(f.draft(),original);assert.equal(f.draft().preparedInputs.assetId,'prepared-inputs');assert.equal(f.controller.pending,null);await flush();assert.equal(f.entryHolds.has(original),false,'Old Entry does not survive solely through transferred review text');assert.equal(f.entryHolds.has(f.draft()),true);}finally{await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

test('format and fingerprint workspaces reject before serializer or canonical/hash callback',()=>{const baseline=allocationLedger.snapshot(),block=pressure(0),stringify=JSON.stringify;try{let formatted=0,encoded=0,digested=0;JSON.stringify=(...args)=>{formatted++;return stringify(...args);};assert.throws(()=>formatV45Input({nested:['text']}),/PROMPT_MEMORY_BUDGET/);assert.equal(formatted,0);assert.throws(()=>ownV45Fingerprint({source:'bytes'},()=>{encoded++;return '{}';},()=>{digested++;return 'sha256:'+'0'.repeat(64);}),/PROMPT_MEMORY_BUDGET/);assert.equal(encoded,0);assert.equal(digested,0);}finally{JSON.stringify=stringify;block.release();}sameUsage(allocationLedger.snapshot(),baseline);});

test('confirmation refusal preserves exact pending owner, Entry root and review text',async()=>{const baseline=allocationLedger.snapshot(),f=fixture();try{await f.prepare();const prior=f.draft(),pending=f.controller.pending,usage=allocationLedger.snapshot();f.setAdmission(()=>{throw Error('fixture entry refusal');});await f.confirm();assert.equal(f.draft(),prior);assert.equal(f.controller.pending,pending);assert.equal(f.controller.pending.formatted,pending.formatted);assert.match(f.errors.at(-1).message,/entry refusal/);await flush();sameUsage(allocationLedger.snapshot(),usage);}finally{await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

test('oversize manifest refuses before body read and preserves prior prepared review',async()=>{const baseline=allocationLedger.snapshot(),f=fixture();try{await f.prepare();const prior=f.controller.pending;let reads=0,cancels=0;f.setTransport(async()=>({ok:true,headers:new Headers({'content-length':'65537'}),body:{getReader(){return {read(){reads++;return Promise.resolve({done:true});},cancel(){cancels++;return Promise.resolve();},releaseLock(){}};}}}));await f.prepare();assert.equal(reads,0);assert.equal(cancels,1);assert.equal(f.controller.pending,prior);assert.match(f.errors.at(-1).message,/PROMPT_CONTENT_SIZE/);}finally{await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

test('a canceled native dispatch is drained without work or leaked Entry/model holds',async()=>{const baseline=allocationLedger.snapshot(),f=fixture();try{let worked=false;const event=f.action(()=>{worked=true;});event.defaultPrevented=true;await f.controller.dispose();assert.equal(worked,false);assert.equal(f.controller.lifecycle.pending,0);assert.equal(f.entryHolds.size,0);assert.equal(f.controller.blocked,false);}finally{await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

test('reusable dispose stays blocked until native cancellation completes, then permits a fresh view',async()=>{const baseline=allocationLedger.snapshot(),f=fixture(),cancel=deferred(),started=deferred();let closing;try{f.setTransport(async()=>new Response(new ReadableStream({cancel(){started.resolve();return cancel.promise;}}),{headers:{'content-length':'2'}}));await f.prepare();let done=false;closing=f.controller.dispose().then(()=>done=true);await started.promise;await flush();assert.equal(done,false);assert.equal(f.controller.blocked,true);assert.equal(f.controller.render(),null);let worked=false;f.action(()=>{worked=true;});await turn();assert.equal(worked,false);cancel.resolve();await closing;assert.equal(f.controller.blocked,false);assert(f.controller.render());}finally{cancel.resolve();await closing;await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

test('capture holds actual document and Entry through command settlement after disposal',async()=>{const baseline=allocationLedger.snapshot(),f=fixture(),gate=deferred();let closing;try{f.setCommand(()=>gate.promise);f.action((draft,owns)=>f.controller.captureReference(draft,'single-layer',owns));await turn();assert.equal(f.documentPins(),1);let done=false;closing=f.controller.dispose().then(()=>done=true);await flush();assert.equal(done,false);assert.equal(f.documentPins(),1);gate.resolve([]);await closing;assert.equal(f.documentPins(),0);assert.equal(f.entryHolds.size,0);}finally{gate.resolve([]);await closing;await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

test('owned fingerprint still fences a same-root original source mutation during preparation',async()=>{const baseline=allocationLedger.snapshot(),f=fixture(),gate=deferred();try{const bundle=preparedBundle(f.draft());f.setCommand(()=>gate.promise);await f.prepare();f.draft().source.version='2';gate.resolve([{type:'AssetRegistered',payload:{asset:bundle.asset}}]);await flush();assert.equal(f.reads.length,0);assert.equal(f.controller.pending,null);assert.deepEqual(f.errors,[]);}finally{gate.resolve([]);await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

test('descriptor owners remain through an outstanding Lit retirement commit',async()=>{const baseline=allocationLedger.snapshot(),f=fixture(),render=deferred();let closing;try{await f.prepare();const usage=allocationLedger.snapshot();f.host.requestUpdate=()=>{f.host.updateComplete=render.promise;};let done=false;closing=f.controller.dispose().then(()=>done=true);await flush();assert.equal(done,false);assert.equal(f.controller.lifecycle.models,0);assert(allocationLedger.snapshot().promptBytes>=usage.promptBytes-1024);render.resolve();await closing;assert.equal(f.entryHolds.size,0);}finally{render.resolve();await closing;await f.close();}sameUsage(allocationLedger.snapshot(),baseline);});

test('joined cleanup tries all independent owners and borrow, retains falsey failure for retry',()=>{const calls=[];let refuse=true;const owner=(id,fail=false)=>({value:id,pin:()=>()=>{},release(){calls.push(id);if(fail&&refuse)throw undefined;}}),joined=joinV45Input('value',[owner('first',true),owner('second')],()=>calls.push('entry'));assert.throws(()=>joined.release(),error=>error instanceof AggregateError&&error.errors.length===1&&error.errors[0]===undefined);assert.deepEqual(calls,['first','second','entry']);refuse=false;joined.release();assert.deepEqual(calls,['first','second','entry','first']);});

test('released fingerprint guard returns false before inspecting or encoding new input',()=>{const baseline=allocationLedger.snapshot();let encoded=0,digested=0;const owner=ownV45Fingerprint({source:'value'},value=>{encoded++;return JSON.stringify(value);},()=>{digested++;return 'sha256:'+'0'.repeat(64);}),guard=owner.value;assert.equal(encoded,1);assert.equal(digested,1);owner.release();const hostile=new Proxy({},{ownKeys(){assert.fail('Released guard traversed input');}});assert.equal(guard.matches(hostile),false);assert.equal(encoded,1);assert.equal(digested,1);sameUsage(allocationLedger.snapshot(),baseline);});
