import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {readFile} from 'node:fs/promises';import {join} from 'node:path';
import {setup,call,mutationHeaders} from '../protocol/helpers.mjs';import {operate,terminal,importRaster} from '../raster/helpers.mjs';import {newDraft,hash,captureMaskFrame,maskAlignment,confirmRequestMask,bindRequestMask,requestMaskDependencies} from '../../dist/local/src/request/core.js';
import {createRequestRasterPlan} from '../../dist/local/src/request/raster-plan.js';
import {newV45Draft} from '../../dist/local/src/request/family.js';
import {exportCompositionText} from '../../dist/local/src/composition/text-export.js';
import {unpack,pack} from '../portable/archive-fixture.mjs';
import {DatabaseSync} from 'node:sqlite';
async function caption(f,text){const bytes=Buffer.from(text),stagingId=randomUUID(),sha256=hash(text);assert.equal((await f.post('/api/v1/assets/staging',{protocolVersion:1,stagingId,purpose:'caption',expectedBytes:String(bytes.length),sha256,mediaType:'text/plain'})).status,201);assert.equal((await call(f.server.origin,'/api/v1/assets/staging/'+stagingId,{method:'PUT',raw:bytes,headers:{...mutationHeaders(f.server,f.paired),'Content-Type':'application/octet-stream','Upload-Offset':'0'}})).status,200);return (await operate(f,{type:'FinalizeStaging',stagingId,expectedSha256:sha256})).event.payload.asset;}
async function send(f,body,id=randomUUID()){const ui=(await f.read('/api/v1/ui/request_session')).json;const request={protocolVersion:1,requestId:id,sessionId:'request_session',expectedUISeq:ui.uiSeq,body};return {request,result:await f.post('/api/v1/ui/request_session',request)};}
async function saved(f,text='Café 東京',generation='1',mutate=()=>{}){const revision=(await f.read('/api/v1/documents/document_1')).json.projection.value.revision,prompt=await caption(f,text),draft=newDraft(prompt.blob);mutate(draft);const a=await caption(f,JSON.stringify(draft));const r=await send(f,{type:'SaveDraft',draft:{id:'request_draft',generation,kind:'request',documentId:'document_1',targetLayerId:null,expectedDocumentRevision:revision,assetId:a.id,composing:false}});assert.equal(r.result.json.status,'accepted',r.result.text);return draft;}
async function fixture(t){const f=await setup(t);await terminal(f,f.command({}, {width:1024,height:1024}));await saved(f);return f;}
async function prepare(f){const r=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'1'});assert.equal(r.result.status,200,r.result.text);assert.equal(r.result.json.status,'accepted',r.result.text);return r;}
test('real writer freezes exact template and accepts review without a document or provider effect',async t=>{const f=await fixture(t),p=await prepare(f),r=p.result.json.review;assert.equal(r.dispatch,false);assert.equal(r.endpoint,'ideogram/v4');const bytes=await readFile(join(f.root,'objects/sha256',r.template.hash.slice(7,9),r.template.hash.slice(7)));assert.equal(hash(bytes.toString()),r.template.hash);assert.deepEqual(JSON.parse(bytes),{prompt:'Café 東京',expansion_model:'Medium',image_size:{width:1024,height:1024},rendering_speed:'BALANCED',acceleration:'none',num_images:1,output_format:'png',sync_mode:false,enable_safety_checker:true});const before=(await f.read('/api/v1/documents/document_1')).json;const a=await send(f,{type:'AcceptRequestReview',reviewId:r.id,token:r.token});assert.equal(a.result.json.status,'accepted',a.result.text);assert.equal(a.result.json.acceptedReview,r.id);assert.deepEqual((await f.read('/api/v1/documents/document_1')).json,before);assert.deepEqual((await f.post('/api/v1/ui/request_session',a.request)).json,a.result.json);assert.deepEqual((await f.post('/api/v1/ui/request_session',p.request)).json,p.result.json);});
test('altered token and changed draft are rejected and exact saved input remains',async t=>{const f=await fixture(t),p=(await prepare(f)).result.json.review;const bad=await send(f,{type:'AcceptRequestReview',reviewId:p.id,token:hash('altered')});assert.equal(bad.result.json.status,'rejected');await saved(f,'Newer retained text','2');const stale=await send(f,{type:'AcceptRequestReview',reviewId:p.id,token:p.token});assert.equal(stale.result.json.status,'rejected');const read=await f.read('/api/v1/ui/request_session/request?draftId=request_draft&generation=2&content=1');assert.equal(read.text,'Newer retained text');});
test('changed document dependency rejects acceptance without changing the request',async t=>{const f=await fixture(t),p=(await prepare(f)).result.json.review;await terminal(f,f.command({expectedDocumentRevision:'1',body:{type:'ResizeCanvas',width:1000,height:1000,offsetX:0,offsetY:0,draft:null}}));const r=await send(f,{type:'AcceptRequestReview',reviewId:p.id,token:p.token});assert.equal(r.result.json.status,'rejected');assert.match(r.result.json.reason,/STALE_REVISION/);});
test('invalid operation keeps draft and returns durable rejection; no default repair',async t=>{const f=await setup(t);await terminal(f,f.command({}, {width:1024,height:1024}));await saved(f,'Fast invalid','1',d=>{d.operation='fast';d.fields.expansion='Large';d.fields.height='900';});const r=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'1'});assert.equal(r.result.json.status,'rejected',r.result.text);assert.match(r.result.json.reason,/EXPANSION/);assert.match(r.result.json.reason,/SIZE/);assert.equal((await f.read('/api/v1/ui/request_session')).json.drafts[0].generation,'1');});
test('owner/session cannot accept a review belonging to another draft session',async t=>{const f=await fixture(t),p=(await prepare(f)).result.json.review;const request={protocolVersion:1,requestId:randomUUID(),sessionId:'other',expectedUISeq:'0',body:{type:'AcceptRequestReview',reviewId:p.id,token:p.token}};const r=await f.post('/api/v1/ui/other',request);assert.equal(r.json.status,'rejected');});
import {doc,edit,copy,preview,workspace,upload} from '../portable/helpers.mjs';import {emptyComposition,emptyElement,serialize} from '../../dist/local/src/composition/core.js';import {canonical} from '../../dist/local/src/protocol/json.js';import {openWriter} from '../../dist/local/server/storage/writer.js';
test('active source is exact and inactive unavailable identity stays preserved without attachment',async t=>{const f=await fixture(t),{asset}=await importRaster(f,'hidden-alpha.png'),source={assetId:asset.id,version:asset.version,blob:asset.blob,pixels:asset.raster.pixels,width:asset.raster.width,height:asset.raster.height,scope:'asset',documentRevision:'1'};await saved(f,'Transform','2',d=>{d.operation='transform';d.source=source;d.fields.size='auto';d.fields.strength='0.8';});let p=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'2'});assert.equal(p.result.json.status,'accepted',p.result.text);assert.deepEqual(p.result.json.review.request.source,source);await saved(f,'Wrong version','3',d=>{d.operation='transform';d.source={...source,version:'999'};d.fields.size='auto';d.fields.strength='0.8';});p=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'3'});assert.match(p.result.json.reason,/DEPENDENCY_CHANGED/);await saved(f,'Excluded source','4',d=>{d.source={...source,assetId:'unavailable'};resolveInactive(d,'source');});p=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'4'});assert.equal(p.result.json.status,'accepted',p.result.text);assert(!('source'in p.result.json.review.request));});
import {resolveInactive} from '../../dist/local/src/request/core.js';
test('unknown draft fields and stale generation readers reject without deleting saved content',async t=>{const f=await fixture(t);assert.equal((await f.read('/api/v1/ui/request_session/request?draftId=request_draft&generation=2')).status,410);const a=await caption(f,JSON.stringify({...newDraft({hash:hash('Café 東京'),byteLength:String(Buffer.byteLength('Café 東京')),mediaType:'text/plain'}),undeclared:true}));const r=await send(f,{type:'SaveDraft',draft:{id:'request_draft',generation:'2',kind:'request',documentId:'document_1',targetLayerId:null,expectedDocumentRevision:'1',assetId:a.id,composing:false}});assert.equal(r.result.status,400);assert.equal((await f.read('/api/v1/ui/request_session/request?draftId=request_draft&generation=1&content=1')).text,'Café 東京');});
async function blob(f,text,mediaType='application/json'){const stage=await upload(f,Buffer.from(text),'text','application/octet-stream'),a=(await workspace(f,{type:'FinalizeStaging',stagingId:stage.stagingId,expectedSha256:stage.sha256})).event.payload.asset;return {...a.blob,mediaType};}
async function retainedCompositionText(f,{commit=false}={}){
 const d=await doc(f),c=emptyComposition(d.width,d.height,randomUUID()),e=emptyElement('text','exported_lettering');c.scene='Café 東京';e.desc.value='A heading';e.text.value='Exact text 👩🏾‍🔬\nCafe\u0301';c.elements=[e];
 const rawBytes=Buffer.from([0xff,0,10,0xc3]),raw=await blob(f,rawBytes,'application/octet-stream');c.raw=[raw];
 const p=serialize(c,[],{}),sourcePrompt=await blob(f,p.prompt,'text/plain');c.review={serializer:'caption-json-1',sourceId:c.id,frame:structuredClone(c.frame),request:structuredClone(c.request),dependencies:p.dependencies,boxes:p.boxes,prompt:sourcePrompt};
 const composition={id:c.id,value:await blob(f,canonical(c)),bindings:{}},exported=exportCompositionText(c,[],{}),text=await blob(f,exported.prompt,'text/plain');assert.deepEqual(text,exported.review.prompt);
 if(commit)await edit(f,{type:'ApprovePromptProjection',composition,draft:null});
 return {c,raw,rawBytes,sourcePrompt,exported,prompt:{mode:'plain',text,projection:exported.review,composition}};
}
async function saveCompositionTextRequest(f,value,generation){
 const draft=newV45Draft(value.prompt.text);draft.prompt=structuredClone(value.prompt);const asset=await caption(f,canonical(draft));
 const result=await send(f,{type:'SaveDraft',draft:{id:'request_draft',generation,kind:'request',documentId:'document_1',targetLayerId:null,expectedDocumentRevision:(await doc(f)).revision,assetId:asset.id,composing:false}});
 assert.equal(result.result.json.status,'accepted',result.result.text);return draft;
}
test('V45 writer reviews the exact explicit Composition text export as an ordinary plain prompt',async t=>{
 const f=await fixture(t),value=await retainedCompositionText(f,{commit:true}),draft=await saveCompositionTextRequest(f,value,'2'),before=await doc(f);
 const prepared=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'2'});assert.equal(prepared.result.json.status,'accepted',prepared.result.text);
 const review=prepared.result.json.review,template=JSON.parse(await readFile(join(f.root,'objects/sha256',review.template.hash.slice(7,9),review.template.hash.slice(7)),'utf8'));
 assert.equal(review.kind,'request-review-v45-1');assert.equal(review.endpoint,'ideogram/v4.5');assert.equal(template.prompt,value.exported.prompt);assert.notEqual(template.prompt,serialize(value.c,[],{}).prompt);
 assert.deepEqual(review.request.settings.prompt,draft.prompt);assert.equal(review.request.modelRequest.promptMode,'plain');assert.equal(review.providerReview.admission.state,'blocked');assert.equal(review.dispatch,false);
 assert.equal((await send(f,{type:'AcceptRequestReview',reviewId:review.id,token:review.token})).result.json.status,'accepted');assert.deepEqual(await doc(f),before);
 assert.equal((await f.read('/api/v1/ui/request_session/request?draftId=request_draft&generation=2&content=1')).text,value.exported.prompt);
});
test('V45 writer retains a frozen exported draft but refuses a fresh review after its current Composition changes',async t=>{
 const f=await fixture(t),value=await retainedCompositionText(f,{commit:true});await saveCompositionTextRequest(f,value,'2');
 const accepted=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'2'});assert.equal(accepted.result.json.status,'accepted',accepted.result.text);
 const d=await doc(f),next=emptyComposition(d.width,d.height,randomUUID());next.scene='A separately committed successor';await edit(f,{type:'CommitCompositionVersion',composition:{id:next.id,value:await blob(f,canonical(next)),bindings:{}},draft:null});
 // Save the historical source at the current document revision so the source
 // fence, rather than an earlier document-revision check, must reject it.
 const draft=await saveCompositionTextRequest(f,value,'3'),current=await doc(f),rejected=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'3'});
 assert.equal(rejected.result.json.status,'rejected',rejected.result.text);assert.match(rejected.result.json.reason,/COMPOSITION_TEXT_CHANGED/);assert.deepEqual(await doc(f),current);
 const path='/api/v1/ui/request_session/request?draftId=request_draft&generation=3';assert.deepEqual((await f.read(path)).json.value,draft);assert.equal((await f.read(path+'&content=1')).text,value.exported.prompt);
});
test('portable V45 draft retains an absent-current Composition source, its original projection and opaque raw leaves',async t=>{
 const f=await fixture(t),value=await retainedCompositionText(f),draft=await saveCompositionTextRequest(f,value,'2');assert.equal((await f.read('/api/v1/documents/document_1/image')).json.composition??null,null);
 const rejected=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'2'});assert.equal(rejected.result.json.status,'rejected',rejected.result.text);assert.match(rejected.result.json.reason,/COMPOSITION_TEXT_CHANGED/);
 let documentId='document_1';
 for(let round=0;round<2;round++){
  const archive=await copy(f,documentId),entries=await unpack(f.root,archive.bytes),manifest=JSON.parse(entries.get('manifest.json'));assert.equal(manifest.formatVersion,12);assert.equal(manifest.documentSchema,12);assert.equal(manifest.complete,true);assert.equal(archive.bundle.complete,true);
  assert.deepEqual(entries.get('objects/'+value.raw.hash.slice(7)),value.rawBytes);assert.equal(entries.get('objects/'+value.prompt.composition.value.hash.slice(7)).toString(),canonical(value.c));assert.equal(entries.get('objects/'+value.sourcePrompt.hash.slice(7)).toString(),serialize(value.c,[],{}).prompt);assert.equal(entries.get('objects/'+value.prompt.text.hash.slice(7)).toString(),value.exported.prompt);
  const review=(await preview(f,archive.bytes)).review;assert.equal(review.editable,true,JSON.stringify(review));assert.equal(review.formatVersion,12);assert.equal(review.documentSchema,12);await workspace(f,{type:'ImportBundle',reviewId:review.reviewId,reviewHash:review.reviewHash});documentId=review.documentId;
  const session=review.uiSessionIds[0],ui=(await f.read('/api/v1/ui/'+session)).json,saved=ui.drafts.find(row=>row.kind==='request');assert(saved);const path='/api/v1/ui/'+session+'/request?draftId='+saved.id+'&generation='+saved.generation;
  assert.deepEqual((await f.read(path)).json.value,draft);assert.equal((await f.read(path+'&content=1')).text,value.exported.prompt);assert.equal((await f.read('/api/v1/documents/'+documentId+'/image')).json.composition??null,null);
  const refusal=await f.post('/api/v1/ui/'+session,{protocolVersion:1,requestId:randomUUID(),sessionId:session,expectedUISeq:ui.uiSeq,body:{type:'PrepareRequestReview',draftId:saved.id,generation:saved.generation}});assert.equal(refusal.json.status,'rejected',refusal.text);assert.match(refusal.json.reason,/COMPOSITION_TEXT_CHANGED/);
 }
});
test('portable12 Composition text draft cannot be relabeled as format10 without changing any source or publishing an import namespace',async t=>{
 const f=await fixture(t),value=await retainedCompositionText(f),draft=await saveCompositionTextRequest(f,value,'2'),source=await doc(f),archive=await copy(f),entries=await unpack(f.root,archive.bytes),manifest=JSON.parse(entries.get('manifest.json'));
 assert.equal(manifest.formatVersion,12);assert.equal(manifest.documentSchema,12);assert.equal(manifest.complete,true);manifest.formatVersion=10;manifest.documentSchema=10;entries.set('manifest.json',Buffer.from(canonical(manifest)));
 const bytes=await pack(f.root,entries),stage=await upload(f,bytes),command=f.command({documentId:null,expectedDocumentRevision:null,body:{type:'PreviewBundleImport',stagingId:stage.stagingId,expectedSha256:stage.sha256}}),rejected=await terminal(f,command);
 assert.equal(rejected.json.receipt.status,'rejected',rejected.text);assert.deepEqual((await terminal(f,command)).json.receipt,rejected.json.receipt);assert.deepEqual(await doc(f),source);
 const path='/api/v1/ui/request_session/request?draftId=request_draft&generation=2';assert.deepEqual((await f.read(path)).json.value,draft);assert.equal((await f.read(path+'&content=1')).text,value.exported.prompt);
 const db=new DatabaseSync(join(f.root,'metadata.sqlite'),{readOnly:true});let filename;try{assert.equal(db.prepare('SELECT count(*) n FROM portable_namespaces').get().n,0);filename=db.prepare('SELECT filename FROM staged_assets WHERE id=?').get(stage.stagingId).filename;}finally{db.close();}assert.deepEqual(await readFile(join(f.root,'uploads',filename)),bytes);
});
test('future portable14 Composition text source remains inspection-only and cannot publish an imported document',async t=>{
 const f=await fixture(t),value=await retainedCompositionText(f),draft=await saveCompositionTextRequest(f,value,'2'),source=await doc(f),archive=await copy(f),entries=await unpack(f.root,archive.bytes),manifest=JSON.parse(entries.get('manifest.json'));
 assert.equal(manifest.formatVersion,12);manifest.formatVersion=14;manifest.documentSchema=14;entries.set('manifest.json',Buffer.from(canonical(manifest)));
 const bytes=await pack(f.root,entries),inspected=await preview(f,bytes),review=inspected.review;assert.equal(review.formatVersion,14);assert.equal(review.documentSchema,14);assert.equal(review.editable,false);assert.match(review.reason,/UNSUPPORTED_FORMAT_VERSION/);
 const command=f.command({documentId:null,expectedDocumentRevision:null,body:{type:'ImportBundle',reviewId:review.reviewId,reviewHash:review.reviewHash}}),rejected=await terminal(f,command);assert.equal(rejected.json.receipt.status,'rejected',rejected.text);assert.equal((await f.read('/api/v1/documents/'+review.documentId)).status,404);assert.deepEqual(await doc(f),source);
 const path='/api/v1/ui/request_session/request?draftId=request_draft&generation=2';assert.deepEqual((await f.read(path)).json.value,draft);assert.equal((await f.read(path+'&content=1')).text,value.exported.prompt);
 const db=new DatabaseSync(join(f.root,'metadata.sqlite'),{readOnly:true});let filename;try{filename=db.prepare('SELECT filename FROM staged_assets WHERE id=?').get(inspected.stage.stagingId).filename;}finally{db.close();}assert.deepEqual(await readFile(join(f.root,'uploads',filename)),bytes);
});
test('approved Composition serializes once and binds the actual accepted projection',async t=>{const f=await fixture(t),c=emptyComposition(1024,1024,randomUUID());c.scene='Café';const el=emptyElement('text','lettering');el.text.value='東京';c.elements=[el];const p=serialize(c,[],{}),prompt=await blob(f,p.prompt,'text/plain');c.review={serializer:'caption-json-1',sourceId:c.id,frame:c.frame,request:c.request,dependencies:p.dependencies,boxes:p.boxes,prompt};const composition={id:c.id,value:await blob(f,canonical(c)),bindings:{}};await edit(f,{type:'ApprovePromptProjection',composition,draft:null});await saved(f,p.prompt,'2',d=>{d.prompt={mode:'composition',text:prompt,projection:c.review,composition};d.fields.expansion=c.request.expansion;d.rewriteAcknowledged=c.request.rewriteAcknowledged;});const r=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'2'});assert.equal(r.result.json.status,'accepted',r.result.text);const review=r.result.json.review,bytes=await readFile(join(f.root,'objects/sha256',review.template.hash.slice(7,9),review.template.hash.slice(7)));assert.equal(JSON.parse(bytes).prompt,p.prompt);assert.deepEqual(JSON.parse(JSON.parse(bytes).prompt),p.caption);await saved(f,p.prompt,'3',d=>{d.prompt={mode:'composition',text:prompt,projection:{...c.review,sourceId:'other'},composition};d.fields.expansion=c.request.expansion;d.rewriteAcknowledged=true;});const bad=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'3'});assert.match(bad.result.json.reason,/PROJECTION_CHANGED/);});
test('writer restart retains exact receipts and drafts but does not renew review authority',async t=>{const f=await fixture(t),p=await prepare(f);await f.server.close();const writer=await openWriter({root:f.root});t.after(()=>writer.close());const auth={clientId:f.paired.json.clientId,sessionHash:'a'.repeat(64),now:Date.now(),expires:Date.now()+1800000};assert.deepEqual(await writer.uiPersist(Buffer.from(JSON.stringify(p.request)),auth),p.result.json);const ui=await writer.uiRead('request_session',auth),request={protocolVersion:1,requestId:randomUUID(),sessionId:'request_session',expectedUISeq:ui.uiSeq,body:{type:'AcceptRequestReview',reviewId:p.result.json.review.id,token:p.result.json.review.token}};assert.match((await writer.uiPersist(Buffer.from(JSON.stringify(request)),auth)).reason,/STALE_REVIEW/);assert.equal((await writer.uiRead('request_session',auth)).drafts[0].generation,'1');});
test('portable request draft keeps exact raw bytes and inactive fields after copy',async t=>{const f=await fixture(t),text=' {"future":true,"future":false} \n';await saved(f,text,'2',d=>{d.prompt.mode='raw';d.fields.height='invalid retained';});const {asset}=await importRaster(f,'hidden-alpha.png');await edit(f,{type:'ImportAsset',assetId:asset.id,layerId:'copy-source',name:'Copy source',draft:null});const archive=await copy(f),r=(await preview(f,archive.bytes)).review;assert.equal(r.editable,true,JSON.stringify(r));await workspace(f,{type:'ImportBundle',reviewId:r.reviewId,reviewHash:r.reviewHash});const session=r.uiSessionIds[0],ui=(await f.read('/api/v1/ui/'+session)).json,draft=ui.drafts.find(d=>d.kind==='request');assert(draft);const path='/api/v1/ui/'+session+'/request?draftId='+draft.id+'&generation='+draft.generation;assert.equal((await f.read(path+'&content=1')).text,text);assert.equal((await f.read(path)).json.value.fields.height,'invalid retained');});
const maskCoverage=new Map();
async function maskFixture(t,{translated=false,full=false}={}){const f=await setup(t);await terminal(f,f.command({}, {width:3,height:2}));const {asset}=await importRaster(f,'hidden-alpha.png');await edit(f,{type:'ImportAsset',assetId:asset.id,layerId:'picture',name:'Picture',draft:null});if(translated)await edit(f,{type:'ApplyTransform',layerId:'picture',layerVersion:'1',transform:[1,0,0,1,1,0],draft:null});const a=(await operate(f,{type:'PrepareMask',plan:{width:3,height:2,feather:0,operations:full?[{kind:'fill'}]:[{kind:'shape',shape:{kind:'rectangle',x:1,y:0,width:1,height:2},mode:'replace'}]}})).event.payload.asset;let layer=(await f.read('/api/v1/documents/document_1/image')).json.layers[0];await edit(f,{type:'SetLayerProperties',layerId:layer.id,layerVersion:layer.version,properties:{mask:{assetId:a.id,mapping:'document-r16-v1',inverted:false}},draft:null});layer=(await f.read('/api/v1/documents/document_1/image')).json.layers[0];const document=await doc(f),source={assetId:asset.id,version:asset.version,blob:asset.blob,pixels:asset.raster.pixels,width:3,height:2,scope:'asset',documentRevision:document.revision},mask={assetId:a.id,version:a.version,blob:a.blob,pixels:a.raster.pixels,width:3,height:2,sourceHash:source.pixels.hash,polarity:'white-edit',empty:false,full,fullAcknowledged:full,plan:a.raster.manifest,frame:captureMaskFrame(document,layer)};const manifest=(await f.read('/api/v1/assets/'+a.id+'/raster')).json;maskCoverage.set(a.id,{authored:manifest.plan.hard,effective:manifest.plan.effective});return {f,source,mask,layer,document};}
const masked=(source,mask,confirm=true)=>(d)=>{if(confirm&&mask.frame?.alignment&&!mask.requestPlan){const coverage=maskCoverage.get(mask.assetId);mask.requestPlan=confirmRequestMask(source,mask,coverage.authored,coverage.effective,'writer-mask-review');}d.operation='inpaint';d.source=source;d.mask=mask;d.fields.size='auto';d.fields.strength='1';};
test('writer verifies mask coverage and source binding instead of trusting draft flags',async t=>{const {f,source,mask}=await maskFixture(t,{full:true});mask.frame.alignment=maskAlignment(source,mask);await saved(f,'Inpaint','1',masked(source,mask));let r=await prepare(f);assert.deepEqual(r.result.json.review.request.mask,mask);await saved(f,'Forged coverage','2',masked(source,{...mask,full:false,fullAcknowledged:false}));r=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'2'});assert.match(r.result.json.reason,/MASK_COVERAGE/);});
test('writer blocks translated equal-size mask and admits explicit document-frame resolution',async t=>{const {f,source,mask,document}=await maskFixture(t,{translated:true});assert.deepEqual(mask.frame.layer.transform,[1,0,0,1,1,0]);await saved(f,'Wrong frame','1',masked(source,mask));let p=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'1'});assert.equal(p.result.json.status,'rejected');assert.match(p.result.json.reason,/MASK_FRAME_MISMATCH/);const a=(await f.read('/api/v1/assets/'+document.image.compositeAssetId)).json.projection.value,visible={assetId:a.id,version:a.version,blob:a.blob,pixels:a.raster.pixels,width:3,height:2,scope:'visible-document',documentRevision:document.revision};mask.sourceHash=visible.pixels.hash;mask.frame.alignment=maskAlignment(visible,mask);assert.deepEqual(mask.frame.alignment.sourceToDocument,[1,0,0,1,0,0]);await saved(f,'Explicit visible document','2',masked(visible,mask));p=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'2'});assert.equal(p.result.json.status,'accepted',p.result.text);const r=p.result.json.review,accepted=await send(f,{type:'AcceptRequestReview',reviewId:r.id,token:r.token});assert.equal(accepted.result.json.acceptedReview,r.id);assert.equal(r.conversion,null);assert.deepEqual(r.request.mask.frame.alignment.maskToDocument,[1,0,0,1,0,0]);});
test('aligned original asset requires an explicit exact frame approval and then accepts',async t=>{const {f,source,mask}=await maskFixture(t);await saved(f,'Unconfirmed','1',masked(source,mask));let p=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'1'});assert.match(p.result.json.reason,/MASK_FRAME_REVIEW_REQUIRED/);mask.frame.alignment=maskAlignment(source,mask);await saved(f,'Confirmed','2',masked(source,mask));p=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'2'});assert.equal(p.result.json.status,'accepted',p.result.text);const r=p.result.json.review;assert.equal((await send(f,{type:'AcceptRequestReview',reviewId:r.id,token:r.token})).result.json.acceptedReview,r.id);});
for(const change of ['missing','layer','transform','mask','document','source-scope'])test('writer refuses forged '+change+' frame while retaining the draft',async t=>{const {f,source,mask}=await maskFixture(t,{translated:true});if(change==='missing')delete mask.frame;else{if(change==='layer')mask.frame.layer.id='other';if(change==='transform')mask.frame.layer.transform=[1,0,0,1,0,0];if(change==='mask')mask.frame.layer.mask={...mask.frame.layer.mask,mapping:'retained-r16-v1',offsetX:1,offsetY:0,width:3,height:2,outside:'zero'};if(change==='document')mask.frame.document.id='other';if(change==='source-scope')source.scope='visible-document';try{mask.frame.alignment=maskAlignment(source,mask);}catch{}}await saved(f,'Retained mismatch','1',masked(source,mask));const r=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'1'});assert.equal(r.result.json.status,'rejected',r.result.text);assert.match(r.result.json.reason,/MASK_FRAME|SOURCE_CHANGED/);const retained=(await f.read('/api/v1/ui/request_session/request?draftId=request_draft&generation=1')).json.value;assert.deepEqual(retained.mask,mask);});
for(const change of ['transform','layer-version','mask','source'])test('prepared aligned review refuses stale '+change+' before acceptance',async t=>{const {f,source,mask,layer}=await maskFixture(t);mask.frame.alignment=maskAlignment(source,mask);await saved(f,'Aligned','1',masked(source,mask));const p=(await prepare(f)).result.json.review;if(change==='transform')await edit(f,{type:'ApplyTransform',layerId:layer.id,layerVersion:layer.version,transform:[1,0,0,1,1,0],draft:null});if(change==='layer-version')await edit(f,{type:'SetLayerProperties',layerId:layer.id,layerVersion:layer.version,properties:{opacity:0.5},draft:null});if(change==='mask')await edit(f,{type:'SetLayerProperties',layerId:layer.id,layerVersion:layer.version,properties:{mask:null},draft:null});if(change==='source')await saved(f,'New source intent','2',masked({...source,version:'999'},mask));const result=await send(f,{type:'AcceptRequestReview',reviewId:p.id,token:p.token});assert.equal(result.result.json.status,'rejected');assert.match(result.result.json.reason,/STALE_REVISION|STALE_REVIEW/);});
test('masked restart keeps immutable accepted receipt without renewing its authority',async t=>{const {f,source,mask}=await maskFixture(t);mask.frame.alignment=maskAlignment(source,mask);await saved(f,'Aligned','1',masked(source,mask));const p=(await prepare(f)).result.json.review,a=await send(f,{type:'AcceptRequestReview',reviewId:p.id,token:p.token});assert.equal(a.result.json.acceptedReview,p.id);await f.server.close();const writer=await openWriter({root:f.root});t.after(()=>writer.close());const auth={clientId:f.paired.json.clientId,sessionHash:'b'.repeat(64),now:Date.now(),expires:Date.now()+1800000};assert.deepEqual(await writer.uiPersist(Buffer.from(JSON.stringify(a.request)),auth),a.result.json);const ui=await writer.uiRead('request_session',auth);const r=await writer.uiPersist(Buffer.from(JSON.stringify({...a.request,requestId:randomUUID(),expectedUISeq:ui.uiSeq})),auth);assert.match(r.reason,/STALE_REVIEW/);});
test('portable aligned draft preserves old frame exactly and requires fresh authority in the copied document',async t=>{const {f,source,mask}=await maskFixture(t);mask.frame.alignment=maskAlignment(source,mask);await saved(f,'Copied frame','1',masked(source,mask));const archive=await copy(f),r=(await preview(f,archive.bytes)).review;await workspace(f,{type:'ImportBundle',reviewId:r.reviewId,reviewHash:r.reviewHash});const session=r.uiSessionIds[0],ui=(await f.read('/api/v1/ui/'+session)).json,d=ui.drafts.find(x=>x.kind==='request'),path='/api/v1/ui/'+session+'/request?draftId='+d.id+'&generation='+d.generation;assert.deepEqual((await f.read(path)).json.value.mask.frame,mask.frame);const result=await f.post('/api/v1/ui/'+session,{protocolVersion:1,requestId:randomUUID(),sessionId:session,expectedUISeq:ui.uiSeq,body:{type:'PrepareRequestReview',draftId:d.id,generation:d.generation}});assert.equal(result.json.status,'rejected');assert.match(result.json.reason,/MASK_FRAME_CHANGED|DEPENDENCY_CHANGED|STALE_REVISION/);});

test('writer approves a declared retained grid only when both exact translations agree',async t=>{const {f,source,mask}=await maskFixture(t);await edit(f,{type:'ResizeCanvas',width:5,height:2,offsetX:1,offsetY:0,draft:null});const document=await doc(f),layer=(await f.read('/api/v1/documents/document_1/image')).json.layers[0];source.documentRevision=document.revision;mask.frame=captureMaskFrame(document,layer);assert.deepEqual(layer.layerToDocument,[1,0,0,1,1,0]);assert.deepEqual(layer.mask,{assetId:mask.assetId,mapping:'retained-r16-v1',inverted:false,offsetX:1,offsetY:0,width:3,height:2,outside:'zero'});mask.frame.alignment=maskAlignment(source,mask);assert.deepEqual(mask.frame.alignment.sourceToDocument,[1,0,0,1,1,0]);assert.deepEqual(mask.frame.alignment.maskToDocument,[1,0,0,1,1,0]);await saved(f,'Explicit equal retained grids','1',masked(source,mask));const r=(await prepare(f)).result.json.review;assert.equal((await send(f,{type:'AcceptRequestReview',reviewId:r.id,token:r.token})).result.json.acceptedReview,r.id);});


test('legacy aligned writer draft is retained but must confirm a separate request mask plan',async t=>{const {f,source,mask}=await maskFixture(t);mask.frame.alignment=maskAlignment(source,mask);await saved(f,'Retained legacy mask','1',masked(source,mask,false));const result=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'1'});assert.equal(result.result.json.status,'rejected',result.result.text);assert.match(result.result.json.reason,/MASK_PLAN_REVIEW_REQUIRED/);const retained=(await f.read('/api/v1/ui/request_session/request?draftId=request_draft&generation=1')).json.value;assert.deepEqual(retained.mask,mask);assert.equal((await f.read('/api/v1/ui/request_session/request?draftId=request_draft&generation=1&content=1')).text,'Retained legacy mask');await saved(f,'Retained legacy mask','2',masked(source,mask));const confirmed=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'2'});assert.equal(confirmed.result.json.status,'accepted',confirmed.result.text);});
for(const role of ['authoredMask','effectiveMask'])test('writer refuses forged retained '+role+' identity before request review',async t=>{const {f,source,mask}=await maskFixture(t);mask.frame.alignment=maskAlignment(source,mask);const coverage=maskCoverage.get(mask.assetId);mask.requestPlan=confirmRequestMask(source,mask,coverage.authored,coverage.effective,'forged-coverage-review');const alternate=(await operate(f,{type:'PrepareMask',plan:{width:3,height:2,feather:0,operations:[{kind:'fill'}]}})).event.payload.asset;const alternateCoverage=(await f.read('/api/v1/assets/'+alternate.id+'/raster')).json.plan.effective;assert.notEqual(alternateCoverage.hash,mask.requestPlan[role].hash);mask.requestPlan[role]=alternateCoverage;await saved(f,'Forged request coverage','1',masked(source,mask));const result=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'1'});assert.equal(result.result.json.status,'rejected',result.result.text);assert.match(result.result.json.reason,/REQUEST_RASTER_DEPENDENCIES_CHANGED/);assert.deepEqual((await f.read('/api/v1/ui/request_session/request?draftId=request_draft&generation=1')).json.value.mask.requestPlan,mask.requestPlan);});
for(const size of ['square_hd','resized'])test('writer rejects '+size+' mapping despite an approved source mask plan',async t=>{const {f,source,mask}=await maskFixture(t);mask.frame.alignment=maskAlignment(source,mask);await saved(f,'Changed request mapping','1',d=>{masked(source,mask)(d);if(size==='resized'){Object.assign(d.fields,{size:'custom',width:'6',height:'2'});d.conversion={from:{width:3,height:2},to:{width:6,height:2},mapping:'stretch',approved:true};}else d.fields.size=size;});const before=await doc(f),result=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'1'});assert.equal(result.result.json.status,'rejected',result.result.text);assert.match(result.result.json.reason,/MASK_MAPPING_REVIEW_REQUIRED/);assert.deepEqual(await doc(f),before);});

async function captureRequestSource(f,scope='single-layer',layerIds=['picture']){
 const before=await doc(f),result=await edit(f,{type:'PrepareRequestSource',scope,layerIds:scope==='visible-document'?[]:layerIds}),asset=result.event.payload.asset;
 assert.deepEqual(await doc(f),before);
 return {asset,source:{assetId:asset.id,version:asset.version,blob:asset.blob,pixels:asset.raster.pixels,width:asset.raster.width,height:asset.raster.height,scope,documentRevision:before.revision,capture:asset.raster.manifest}};
}
async function independentMaskFixture(t,{scope='single-layer'}={}){
 const f=await setup(t);await terminal(f,f.command({}, {width:3,height:2}));const {asset:original}=await importRaster(f,'hidden-alpha.png');await edit(f,{type:'ImportAsset',assetId:original.id,layerId:'picture',name:'Picture',draft:null});
 const {source}=await captureRequestSource(f,scope),asset=(await operate(f,{type:'PrepareRequestMask',sourceAssetId:source.assetId,plan:{width:3,height:2,feather:0,operations:[{kind:'shape',shape:{kind:'rectangle',x:1,y:0,width:1,height:2},mode:'replace'}]},clip:null})).event.payload.asset,manifest=(await f.read('/api/v1/assets/'+asset.id+'/raster')).json;
 const mask={assetId:asset.id,version:asset.version,blob:asset.blob,pixels:asset.raster.pixels,width:3,height:2,sourceHash:source.pixels.hash,polarity:'white-edit',fullAcknowledged:false,empty:false,full:false,plan:asset.raster.manifest,binding:bindRequestMask(source)};
 mask.requestPlan=confirmRequestMask(source,mask,manifest.plan.hard,manifest.plan.effective,'independent-writer-review');
 return {f,original,source,mask,manifest};
}
for(const scope of ['single-layer','selected-layers','visible-document'])test('writer reviews a captured '+scope+' source with an independent mask and no layer-mask attachment',async t=>{
 const {f,source,mask,manifest}=await independentMaskFixture(t,{scope}),before=await doc(f),capture=(await f.read('/api/v1/assets/'+source.assetId+'/raster')).json;
 assert.equal(capture.plan.kind,'request-source-capture-v1');assert.equal(capture.plan.capture.scope,scope);assert.deepEqual(capture.plan.capture.layerIds,['picture']);assert.equal(capture.plan.capture.documentRevision,source.documentRevision);assert.deepEqual(capture.pixels,source.pixels);
 assert.equal(manifest.plan.kind,'authored-request-mask-v1');assert.equal(manifest.plan.sourceAssetId,source.assetId);assert.deepEqual(manifest.plan.source,source.capture);assert.deepEqual(manifest.plan.sourcePixels,source.pixels);assert.equal(manifest.plan.clip,null);
 const layer=(await f.read('/api/v1/documents/document_1/image')).json.layers[0];assert.equal(layer.mask,null);
 await saved(f,'Separate edit mask','1',masked(source,mask));const review=(await prepare(f)).result.json.review;assert.deepEqual(review.request.source,source);assert.deepEqual(review.request.mask,mask);assert.equal(review.request.mask.frame,undefined);assert.equal((await send(f,{type:'AcceptRequestReview',reviewId:review.id,token:review.token})).result.json.acceptedReview,review.id);assert.deepEqual(await doc(f),before);
});
test('a later layer edit invalidates an open review but a fresh review keeps the immutable captured source',async t=>{
 const {f,source,mask}=await independentMaskFixture(t),captureBefore=(await f.read('/api/v1/assets/'+source.assetId+'/raster')).json;
 await saved(f,'Frozen rendered source','1',masked(source,mask));const first=(await prepare(f)).result.json.review;
 await edit(f,{type:'ApplyTransform',layerId:'picture',layerVersion:'1',transform:[1,0,0,1,1,0],draft:null});
 const stale=await send(f,{type:'AcceptRequestReview',reviewId:first.id,token:first.token});assert.equal(stale.result.json.status,'rejected');assert.match(stale.result.json.reason,/STALE_REVISION/);
 assert.notEqual((await doc(f)).revision,source.documentRevision);await saved(f,'Frozen rendered source','2',masked(source,mask));const next=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'2'});assert.equal(next.result.json.status,'accepted',next.result.text);assert.deepEqual(next.result.json.review.request.source,source);assert.deepEqual((await f.read('/api/v1/assets/'+source.assetId+'/raster')).json,captureBefore);assert.deepEqual(next.result.json.review.request.mask,mask);
});
test('writer refuses a mask rebound to a different capture even when pixels and capture bytes agree',async t=>{
 const {f,source,mask,manifest}=await independentMaskFixture(t),{source:other}=await captureRequestSource(f);
 assert.notEqual(other.assetId,source.assetId);assert.deepEqual(other.pixels,source.pixels);assert.deepEqual(other.capture,source.capture);
 mask.binding=bindRequestMask(other);mask.requestPlan=confirmRequestMask(other,mask,manifest.plan.hard,manifest.plan.effective,'forged-rebound-review');await saved(f,'Rebound old mask','1',masked(other,mask));
 const result=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'1'});assert.equal(result.result.json.status,'rejected',result.result.text);assert.match(result.result.json.reason,/MASK_SOURCE_CHANGED/);assert.deepEqual((await f.read('/api/v1/ui/request_session/request?draftId=request_draft&generation=1')).json.value.mask,mask);
});
test('writer requires a prepared independent-mask successor instead of relabeling a legacy layer mask',async t=>{
 const {f,mask}=await maskFixture(t),{source}=await captureRequestSource(f);delete mask.frame;mask.binding=bindRequestMask(source);mask.sourceHash=source.pixels.hash;const coverage=maskCoverage.get(mask.assetId);mask.requestPlan=confirmRequestMask(source,mask,coverage.authored,coverage.effective,'relabelled-legacy-mask');await saved(f,'Legacy coverage retained','1',masked(source,mask));
 const result=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'1'});assert.equal(result.result.json.status,'rejected',result.result.text);assert.match(result.result.json.reason,/MASK_SOURCE_CHANGED/);
});
for(const field of ['scope','documentRevision','capture'])test('writer verifies retained source '+field+' before reviewing an independent mask',async t=>{
 const {f,source,mask,manifest}=await independentMaskFixture(t);if(field==='scope')source.scope='selected-layers';if(field==='documentRevision')source.documentRevision='999';if(field==='capture'){const other=await captureRequestSource(f,'visible-document');source.capture=other.source.capture;}mask.binding=bindRequestMask(source);mask.requestPlan=confirmRequestMask(source,mask,manifest.plan.hard,manifest.plan.effective,'forged-source-review');await saved(f,'Changed source metadata','1',masked(source,mask));
 const result=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'1'});assert.equal(result.result.json.status,'rejected',result.result.text);assert.match(result.result.json.reason,/SOURCE_CAPTURE_CHANGED/);
});
test('an independent crop covering its whole source domain requires its own extent acknowledgement',async t=>{
 const {f,source,mask,manifest}=await independentMaskFixture(t);mask.requestPlan=createRequestRasterPlan({document:{width:3,height:2},crop:{x:1,y:0,width:1,height:2},padding:{left:0,top:0,right:0,bottom:0},requestGrid:{width:1,height:2},sourcePixels:source.pixels,authoredMask:manifest.plan.hard,effectiveMask:manifest.plan.effective,dependenciesHash:requestMaskDependencies(source,mask),resolution:'already-contained',approvalId:'full-crop-review'});
 const configure=d=>{masked(source,mask)(d);Object.assign(d.fields,{size:'custom',width:'1',height:'2'});};await saved(f,'Whole crop','1',configure);const first=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'1'});assert.equal(first.result.json.status,'rejected',first.result.text);assert.match(first.result.json.reason,/FULL_SOURCE_CROP_ACK_REQUIRED/);assert.equal(mask.full,false);
 mask.cropAcknowledged=true;await saved(f,'Whole crop','2',configure);const approved=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:'2'});assert.equal(approved.result.json.status,'accepted',approved.result.text);assert.equal(approved.result.json.review.request.mask.cropAcknowledged,true);assert.deepEqual(approved.result.json.review.request.size,{kind:'custom',width:1,height:2});assert.equal(approved.result.json.review.conversion,null);
});
test('independent source and mask bytes survive import and re-copy without renewing historical request authority',async t=>{
 const {f,source,mask}=await independentMaskFixture(t);await saved(f,'Portable independent edit','1',masked(source,mask));await prepare(f);let documentId='document_1',priorSource=source,priorMask=mask;
 for(let round=1;round<=2;round++){
  const archive=await copy(f,documentId),review=(await preview(f,archive.bytes)).review;assert.equal(review.editable,true,JSON.stringify(review));await workspace(f,{type:'ImportBundle',reviewId:review.reviewId,reviewHash:review.reviewHash});documentId=review.documentId;
  const session=review.uiSessionIds[0],ui=(await f.read('/api/v1/ui/'+session)).json,draft=ui.drafts.find(value=>value.kind==='request');assert(draft,'copied request draft '+round);const path='/api/v1/ui/'+session+'/request?draftId='+draft.id+'&generation='+draft.generation,retained=(await f.read(path)).json.value;
  assert.equal((await f.read(path+'&content=1')).text,'Portable independent edit');assert.notEqual(retained.source.assetId,priorSource.assetId);assert.notEqual(retained.mask.assetId,priorMask.assetId);assert.deepEqual(retained.source.blob,source.blob);assert.deepEqual(retained.source.pixels,source.pixels);assert.deepEqual(retained.mask.blob,mask.blob);assert.deepEqual(retained.mask.pixels,mask.pixels);assert.deepEqual(retained.mask.binding,mask.binding);assert.deepEqual(retained.mask.requestPlan,mask.requestPlan);
  const sourceAsset=(await f.read('/api/v1/assets/'+retained.source.assetId)).json.projection.value,maskAsset=(await f.read('/api/v1/assets/'+retained.mask.assetId)).json.projection.value,sourceManifest=(await f.read('/api/v1/assets/'+retained.source.assetId+'/raster')).json,maskManifest=(await f.read('/api/v1/assets/'+retained.mask.assetId+'/raster')).json;
  assert.deepEqual(retained.source.capture,sourceAsset.raster.manifest);assert.deepEqual(retained.mask.plan,maskAsset.raster.manifest);assert.equal(sourceManifest.plan.capture.documentId,documentId);assert.equal(maskManifest.plan.sourceAssetId,retained.source.assetId);assert.deepEqual(maskManifest.plan.source,retained.source.capture);assert.deepEqual(maskManifest.plan.hard,mask.requestPlan.authoredMask);assert.deepEqual(maskManifest.plan.effective,mask.requestPlan.effectiveMask);
  const result=await f.post('/api/v1/ui/'+session,{protocolVersion:1,requestId:randomUUID(),sessionId:session,expectedUISeq:ui.uiSeq,body:{type:'PrepareRequestReview',draftId:draft.id,generation:draft.generation}});assert.equal(result.json.status,'rejected',result.text);assert.match(result.json.reason,/MASK_FRAME_MISMATCH/);priorSource=retained.source;priorMask=retained.mask;
 }
});
test('a retained clipped request mask requires a clipping approval even when its final coverage fits the request domain',async t=>{
 const {f,source,mask:original,manifest:originalManifest}=await independentMaskFixture(t),clip={x:1,y:0,width:1,height:1},asset=(await operate(f,{type:'PrepareRequestMask',sourceAssetId:source.assetId,plan:originalManifest.plan.authoring,clip})).event.payload.asset,manifest=(await f.read('/api/v1/assets/'+asset.id+'/raster')).json;
 assert.deepEqual(manifest.plan.clip,clip);assert.equal(manifest.plan.lostEffectivePixels,1);assert.deepEqual(manifest.plan.hard,originalManifest.plan.hard);assert.notEqual(manifest.plan.effective.hash,originalManifest.plan.effective.hash);assert.deepEqual(manifest.plan.statistics,{hardPixels:2,effectivePixels:1,support:{x:1,y:0,width:1,height:1}});
 const bytes=await readFile(join(f.root,'objects/sha256',manifest.plan.effective.hash.slice(7,9),manifest.plan.effective.hash.slice(7)));assert.deepEqual(Array.from({length:6},(_,i)=>bytes.readUInt16LE(i*2)),[0,65535,0,0,0,0]);
 const mask={...original,assetId:asset.id,version:asset.version,blob:asset.blob,pixels:asset.raster.pixels,plan:asset.raster.manifest};let generation=0;
 for(const resolution of ['already-contained','expanded-and-approved','clipped-and-approved']){
  mask.requestPlan=createRequestRasterPlan({document:{width:3,height:2},crop:{x:0,y:0,width:3,height:2},padding:{left:0,top:0,right:0,bottom:0},requestGrid:{width:3,height:2},sourcePixels:source.pixels,authoredMask:manifest.plan.hard,effectiveMask:manifest.plan.effective,dependenciesHash:requestMaskDependencies(source,mask),resolution,approvalId:'retained-clipping-review'});const current=String(++generation);await saved(f,'Explicit clipped coverage',current,masked(source,mask));const result=await send(f,{type:'PrepareRequestReview',draftId:'request_draft',generation:current});
  if(resolution==='clipped-and-approved'){assert.equal(result.result.json.status,'accepted',result.result.text);assert.equal(result.result.json.review.request.mask.requestPlan.resolution,resolution);}else{assert.equal(result.result.json.status,'rejected',result.result.text);assert.match(result.result.json.reason,/MASK_CLIP_REVIEW_REQUIRED/);assert.deepEqual((await f.read('/api/v1/ui/request_session/request?draftId=request_draft&generation='+current)).json.value.mask,mask);}
 }
});
